### ISSUE TITLE
[💡 Feature]: <title>

### ISSUE THREAD

**Issue by jhaltrecht-rev** [webdriverio/webdriverio#10012]
### Is your feature request related to a problem?

When running my tests, the browser will start timing out for all tests within a suite. I believe it is related to the number of instances I am running and my CPU/Memory, as it occurs after a large amount of tests.  In these cases the browser might crash or disconnect.  A wdio tool to retry a test if the browser crashes, without timing out each test in the suite, would be ideal.

There is an [issue about this](https://github.com/GoogleChrome/puppeteer/issues/1947) on the puppeteer repository as well. 

There is a library [puppeteer-cluster](https://github.com/thomasdondorf/puppeteer-cluster) which may handle these kinds of error cases?

Using 1 instance rather than 2 does not cause this issue.  I only want to retry if the browser crashes, not if my test is flakey/does not pass.  All tests within a suite will have a message like below:

Error: Timeout of 210000ms exceeded. The execution in the test ..." took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (C:\Users\....js)
at createTimeoutError (C:\Users.......node_modules\mocha\lib\errors.js:498:15)
at Test.Runnable._timeoutError (C:\Users....node_modules\mocha\lib\runnable.js:431:10)
at Timeout.<anonymous> ....workspace\linklive-automation\node_modules\mocha\lib\runnable.js:246:24)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)

### Describe the solution you'd like.

A WDIO tool that will restart a browser if it crashes, and restart the test where it crashed (ignoring any retry counts set for flakey tests)

### Describe alternatives you've considered.

Running 1 instance instead of 2, which doubles my test execution time.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
Thanks for reporting!

As mentioned in the Matrix channel I believe we can check within`devtools` and `webdriver` packages when a browser crashes and initiate a restart if so.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!
