### ISSUE TITLE
[🐛 Bug]: <title>

### ISSUE THREAD

**Issue by nam81285** [webdriverio/webdriverio#10033]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v8.6.7

### Node.js Version

16.15.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
'browserName': chrome, 
'goog:chromeOptions': {
            // to run chrome headless the following flags are required
            // --headless
            headless: false,
            args:[

                '--no-sandbox',
                '--disable-dev-shm-usage'],
            //args: ["--start-maximized", "--disable-infobars", "--disable-gpu", "--disable-dev-shm-usage", "--no-sandbox"],
            useAutomationExtension: false,
```

### What happened?

Trying to run the automation test for my UI application, The browser is getting launched but test is failing and getting Target closed error

### What is your expected behavior?

Browser should get launched with the provided URL.

### Below package.json:-

"devDependencies": {
    "@babel/core": "^7.21.3",
    "@babel/preset-env": "^7.20.2",
    "@babel/register": "^7.21.0",
    "@wdio/cli": "^8.6.7",
    "@wdio/cucumber-framework": "^8.6.6",
    "@wdio/globals": "^8.6.7",
    "@wdio/local-runner": "^8.6.7",
    "@wdio/sauce-service": "^8.1.3",
    "@wdio/selenium-standalone-service": "^8.6.6",
    "@wdio/spec-reporter": "^8.6.6",
    "json-override": "^0.2.0",
    "msedgedriver": "^91.0.0",
    "wdio-chromedriver-service": "^8.0.1",
    "wdio-edgedriver-service": "^2.1.2",
    "wdio-wait-for": "^3.0.1",
    "webdriverio": "^8.1.3"
  },
  "engines": {
    "node": ">=10.0.0"
  },
  "dependencies": {
    "assert-diff": "^3.0.2",
    "await": "^0.2.6",
    "axe-webdriverjs": "^2.3.0",
    "chai": "^4.3.7",
    "dargs": "^7.0.0",
    "date-diff": "^1.0.2",
    "deepmerge": "^4.3.1",
    "dom-compare": "^0.6.0",
    "edgedriver": "^4.17134.1",
    "exceljs": "^4.3.0",
    "find-remove": "^4.1.0",
    "gulp": "^4.0.2",
    "gulp-util": "^3.0.8",
    "gulp4-run-sequence": "^1.0.1",
    "js-yaml": "^4.1.0",
    "loadtest": "^5.2.0",
    "mockserver-client": "^5.15.0",
    "node-datetime": "^2.1.2",
    "node-run-cmd": "^1.0.1",
    "randomstring": "^1.2.3",
    "request-promise": "^4.2.6",
    "system-sleep": "^1.3.7",
    "through2": "^4.0.2",
    "xlsx": "^0.18.5",
    "xml2js": "^0.4.23",
    "xmldom": "^0.6.0",
    "xpath": "0.0.32",
    "yaml-merge": "^0.0.2"
  }

WDIO ConfigFile:- 
[wdio.conf.zip](https://github.com/webdriverio/webdriverio/files/11042906/wdio.conf.zip)

### Relevant log output

```typescript
[0-0] node:internal/process/promises:279
[0-0]             triggerUncaughtException(err, true /* fromPromise */);
[0-0]             ^
[0-0]
[0-0] Protocol error (Page.navigate): Target closed.
[0-0] ProtocolError: Protocol error (Page.navigate): Target closed.
[0-0]     at file:///C:/SwCoWAT_Framework/ra-js-test-framework/RA_WDIO_Framework/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:324:24
[0-0]     at new Promise (<anonymous>)
[0-0]     at CDPSessionImpl.send (file:///C:/SwCoWAT_Framework/ra-js-test-framework/RA_WDIO_Framework/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:320:16)
[0-0]     at navigate (file:///C:/SwCoWAT_Framework/ra-js-test-framework/RA_WDIO_Framework/node_modules/puppeteer-core/lib/esm/puppeteer/common/Frame.js:203:47)
[0-0]     at Frame.goto (file:///C:/SwCoWAT_Framework/ra-js-test-framework/RA_WDIO_Framework/node_modules/puppeteer-core/lib/esm/puppeteer/common/Frame.js:181:13)
[0-0]     at CDPPage.goto (file:///C:/SwCoWAT_Framework/ra-js-test-framework/RA_WDIO_Framework/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:436:91)
[0-0]     at DevToolsDriver.navigateTo (file:///C:/SwCoWAT_Framework/ra-js-test-framework/RA_WDIO_Framework/node_modules/devtools/build/commands/navigateTo.js:16:16)
[0-0]     at Proxy.wrappedCommand (file:///C:/SwCoWAT_Framework/ra-js-test-framework/RA_WDIO_Framework/node_modules/devtools/build/devtoolsdriver.js:127:55)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Proxy.wrapCommandFn (file:///C:/SwCoWAT_Framework/ra-js-test-framework/RA_WDIO_Framework/node_modules/@wdio/utils/build/shim.js:72:29)
[0-0]     at async Proxy.wrapCommandFn (file:///C:/SwCoWAT_Framework/ra-js-test-framework/RA_WDIO_Framework/node_modules/@wdio/utils/build/shim.js:72:29) {
[0-0]   [Symbol(originalCallSite)]: [
[0-0]     CallSite {}, CallSite {},
[0-0]     CallSite {}, CallSite {},
[0-0]     CallSite {}, CallSite {},
[0-0]     CallSite {}, CallSite {},
[0-0]     CallSite {}, CallSite {},
[0-0]     CallSite {}
[0-0]   ],
[0-0]   [Symbol(mutatedCallSite)]: [
[0-0]     CallSite {}, CallSite {},
[0-0]     CallSite {}, CallSite {},
[0-0]     CallSite {}, CallSite {},
[0-0]     CallSite {}, CallSite {},
[0-0]     CallSite {}, CallSite {},
[0-0]     CallSite {}
[0-0]   ]
[0-0] }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Your capabilities don't include a `browserName` which is required for running a browser. The following example works for me:

```
import { remote } from 'webdriverio'

const browser = await remote({
    automationProtocol: 'devtools',
    capabilities: {
        browserName: 'chrome',
        // to run chrome headless the following flags are required
        // --headless
        headless: false,
        args:[

            '--no-sandbox',
            '--disable-dev-shm-usage'],
        //args: ["--start-maximized", "--disable-infobars", "--disable-gpu", "--disable-dev-shm-usage", "--no-sandbox"],
        useAutomationExtension: false
    }
})
await browser.deleteSession()
```

**Comment by nam81285** [comment]
Its still not working.. 

I am passing the browsername from the command line.

**Comment by nam81285** [comment]
The command I run is wdio run wdio.conf.js --ff <featurefile name>

**Comment by christian-bromann** [comment]
> I am passing the browsername from the command line.

Are you sure the config is set correctly? As you can see in my example , if set correctly the browser opens.

> The command I run is wdio run wdio.conf.js --ff

`--ff` is not a valid WebdriverIO parameter
