### ISSUE TITLE
[🐛 Bug]:  ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4444 in WDIO v 7.30.2 using gulp to run selenium

### ISSUE THREAD

**Issue by Sandeepthesun** [webdriverio/webdriverio#10030]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.30.2

### Node.js Version

16.18.10

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
let localConfig = {
        //
       // services: ['selenium-standalone'],
        hostname: 'localhost',
        port: 4444,
        path: '/',
        // ====================
        // Runner Configuration
        // ====================
        // WebdriverIO supports running e2e tests as well as unit and component tests.
        runner: 'local',
  specs: [
            featureFilePath
        ],  
capabilities: [{
 maxInstances: 1,
 'goog:chromeOptions': {
                // to run chrome headless the following flags are required
                // --headless
               args:[
               '--no-sandbox',
               '--disable-dev-shm-usage'],
               //args: ["--start-maximized", "--disable-infobars", "--disable-gpu", "--disable-dev-shm-usage", "--no-sandbox"],
               useAutomationExtension: false,
            },
 'ms:edgeOptions': {
                // to run edge headless the following flags are required
                // --headless
                args: ["--start-maximized", "--disable-infobars", "--disable-gpu", "--disable-dev-shm-usage", "--no-sandbox"],
                useAutomationExtension: false,
            },

            'browserName': browserName,
}
        ],
//
framework:'cucumber',
```

### What happened?

We are trying to run automation test using gulp I keep on getting the  error as below

[0-0] RUNNING in msedge - C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\tests\features\featureFiles\web\newFeatureCheck\csAsIFARpAllPayeeNewVersion.feature
[0-0] **2023-03-22T13:07:09.535Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4444**
[0-0]     at ClientRequest.<anonymous> (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\got\dist\source\core\index.js:970:111)
[0-0]     at Object.onceWrapper (node:events:628:26)
[0-0]     at ClientRequest.emit (node:events:525:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at ClientRequest.origin.emit (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
[0-0]     at Socket.socketErrorListener (node:_http_client:494:9)
[0-0]     at Socket.emit (node:events:513:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:157:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
[0-0] 2023-03-22T13:07:09.537Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://localhost:4444/", make sure browser driver is running on that address.
[0-0] If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-0]     at startWebDriverSession (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\webdriver\build\utils.js:73:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Function.newSession (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\webdriver\build\index.js:46:45)
[0-0]     at async remote (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\webdriverio\build\index.js:78:22)
[0-0]     at async Runner._startSession (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\@wdio\runner\build\index.js:223:56)
[0-0]     at async Runner._initSession (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\@wdio\runner\build\index.js:176:25)
[0-0]     at async Runner.run (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\@wdio\runner\build\index.js:88:19)
[0-0] FAILED in msedge - C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\tests\features\featureFiles\web\newFeatureCheck\csAsIFARpAllPayeeNewVersion.feature

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:05

### What is your expected behavior?

test should run launching in msedge driver

### Below Gulp file is used
-----------------------------------------------------------
const path = require('path'),
    gulp = require('gulp'),
    fs = require('fs'),
    findRemoveSync = require('find-remove'),
    fs_extra = require('fs-extra'),
    through = require('through2'),
    dargs = require('dargs'),
    gutil = require('gulp-util'),
    spawn = require('child_process').spawn,
    deepmerge = require('deepmerge'),
    argv = require('yargs').argv,
    exec = require('child_process').exec,
    runSequence = require('gulp4-run-sequence');

const chalk = require('chalk');
const rimRaf = require("rimraf");

const isWin = /^win/.test(process.platform);
const cmd = isWin ? 'wdio.cmd' : 'wdio';
let seleniumServer;
let runType;

let webdriver = module.exports = function (options) {
    return through.obj(function (file, enc, done) {
        let tags = ['~@unit'];
        let config = require(file.history[0]).config;
        config.cucumberOpts = config.cucumberOpts || {};
       
        config.cucumberOpts.tags = tags;

        let jsString = [];
        jsString.push('exports.config=');
        jsString.push(JSON.stringify(config));

        let currenttime = new Date().toJSON().replace(/:/g, "-");
        let tmpFile = path.resolve(__dirname, 'cuke-' + currenttime + '.tmp');
        fs.writeFileSync(tmpFile, jsString.join(''));

        let stream = this,
            configFile = tmpFile,
            isWin = /^win/.test(process.platform),
            wdioBin = path.join(__dirname, 'node_modules', '.bin', isWin ? 'wdio.cmd' : 'wdio');

        let opts = deepmerge({
            wdioBin: wdioBin
        }, options || {});

        /**
         * check webdriverio dependency
         */
        if (!fs.existsSync(opts.wdioBin)) {
            return this.emit('error', new gutil.PluginError('gulp-webdriver', 'Haven\'t found the WebdriverIO test runner', {
                showStack: false
            }));
        }

        let args = process.execArgv.concat([configFile]).concat(dargs(opts, {
            excludes: ['wdioBin'],
            keepCamelCase: true
        }));

        gutil.log('spawn wdio with these attributes:\n', args.join('\n'));
        let wdio = spawn(opts.wdioBin, args, {
            stdio: 'inherit'
        });

        wdio.on('exit', function (code) {
            gutil.log('wdio testrunner finished with exit code', code);
            console.log("Deleting tmp cuke file");
            fs.unlinkSync(tmpFile);
            done();
            done = null;
        });

        return stream;
    });
};

/**************************************************Start of -- gulp Command to execute Web scripts in local system*****************************************************/
gulp.task('run-wdio', (cb) => {
    process.env.IS_WDIO_TASK = true;
    return runSequence('start-selenium-and-wdio', 'stop-selenium', cb);
});

/**************************************************End of -- gulp Command to execute Web scripts in local system*****************************************************/

/**************************************************Start of -- gulp Command to launch the selenium server to execute Web scripts in local system *****************************************************/

gulp.task('start-selenium-and-wdio', () => {
    const Chromeexecutable = isWin ? './node_modules/chromedriver/lib/chromedriver/chromedriver.exe' : 'node_modules/chromedriver/bin/chromedriver';
    const ieexecutable = isWin ? './tools/IEDriverServer.exe' : 'node_modules/iedriver/bin/iedriver';
    //const ffexecutable = isWin ? 'node_modules/geckodriver/lib/geckodriver.js' : 'node_modules/geckodriver/bin/geckodriver';
    const edgeexecutable = isWin ? './node_modules/msedgedriver/lib/msedgedriver/msedgedriver.exe' : 'node_modules/msedgedriver/bin/msedgedriver';

    let command;
    // if (argv.b == 'chrome') {
    //   command = 'java -jar ./node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-2.53.1.jar -log ../seleniumLog.txt -Dwebdriver.chrome.driver=' + path.resolve(__dirname, Chromeexecutable);
    // }
    //else
    // if (argv.b == 'internet explorer' || argv.b == 'IE') {
    // command = 'java -jar ./node_modules/selenium-server-standalone-jar/jar/selenium-server-standalone-2.53.1.jar -log ../seleniumLog.txt -Dwebdriver.ie.driver=' + path.resolve(__dirname, ieexecutable);
    //}
    // else if (argv.b == 'firefox' || argv.b == 'FF') {
    //  command = 'java -jar ./tools/selenium-server-standalone-2.53.1.jar -log ../seleniumLog.txt';
    // }
    ///  else if (argv.b == 'edge') {
    //  command = 'java -jar ./node_modules/selenium-server-standalone-jar/jar/selenium-server-4.7.1.jar -log ../seleniumLog.txt -Dwebdriver.edge.driver=' + path.resolve(__dirname, edgeexecutable);
    //}
    //  else {
    console.log('edgeexecutable: ' +edgeexecutable);
    command = 'java -jar ./node_modules/selenium-server-standalone-jar/jar/selenium-server-4.7.1.jar -log ../seleniumLog.txt -Dwebdriver.edge.driver=' + path.resolve(__dirname, edgeexecutable);
    //command = 'java -jar ./node_modules/selenium-server-standalone-jar/jar/selenium-server-4.7.1.jar -log ../seleniumLog.txt -Dwebdriver.chrome.driver=' + path.resolve(__dirname, Chromeexecutable) + ' standalone';

    console.log('command: ' + command);
    // }

    console.log('Starting Selenium Server');
    let currentDateTime = new Date();
    process.env.startTime = currentDateTime;
    seleniumServer = exec(command, function () {
        console.error()
        seleniumServer = null;
    });
    return gulp.src('tests/conf/local.conf.js').pipe(webdriver({

        wdioBin: path.join(__dirname, 'node_modules', '.bin', cmd)

    }));

});

/**************************************************End of -- gulp Command to launch the selenium server to execute Web scripts in local system*****************************************************/

/**************************************************Start of -- gulp Command to Stop the selenium server*****************************************************/

gulp.task('stop-selenium', (cb) => {

    if (seleniumServer) {
        process.kill(seleniumServer.pid, 'SIGINT');
    }
    cb();
    process.exit(0);

});

/**************************************************End of -- gulp Command to Stop the selenium server*****************************************************/

gulp.task('remove-samples', () => {
    findRemoveSync('tests/', {prefix: 'sample'});
    fs_extra.remove('find-customer-details-api');
    fs_extra.remove('mock-server');
});

### Below Package.json used
---------------------------------------------------------

"pre-commit": [
    "lint"
  ],
  "devDependencies": {
    "@wdio/cli": "^7.30.2",
    "@wdio/cucumber-framework": "^7.30.2",
    "@wdio/local-runner": "^7.30.2",
    "@wdio/logger": "^8.1.0",
    "@wdio/selenium-standalone-service": "^7.30.2",
    "@wdio/spec-reporter": "^7.30.2",
    "cucumber-html-reporter": "^5.5.1",
    "json-override": "^0.2.0",
    "msedgedriver": "^91.0.0",
    "multiple-cucumber-html-reporter": "^3.3.0",
    "npm": "^9.6.2",
    "selenium-server-standalone-jar": "4.7.1",
    "wdio-cucumberjs-json-reporter": "^4.4.3",
    "wdio-edgedriver-service": "^2.1.2"
  },
  "engines": {
    "node": ">=4.0.0"
  },
  "dependencies": {
    "@wdio/junit-reporter": "^7.30.2",
    "assert-diff": "^3.0.2",
    "axe-webdriverjs": "^2.3.0",
    "browser-webdriver-downloader": "^1.5.4",
    "chai": "^4.3.7",
    "dargs": "^7.0.0",
    "date-diff": "^1.0.2",
    "edgedriver": "^4.17134.1",
    "exceljs": "^4.3.0",
    "find-remove": "^4.1.0",
    "gulp": "^4.0.2",
    "gulp-util": "^3.0.8",
    "gulp4-run-sequence": "^1.0.1",
    "js-yaml": "^4.1.0",
    "mockserver-client": "^5.15.0",
    "node-datetime": "^2.1.2",
    "randomstring": "^1.2.3",
    "request-promise": "^4.2.6",
    "system-sleep": "^1.3.7",
    "through2": "^4.0.2",
    "xlsx": "^0.18.5",
    "xmldom": "^0.6.0",
    "xpath": "0.0.32"
  }
}

### Relevant log output

```typescript
C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework>gulp run-wdio --ff csAsIFARpAllPayeeNewVersion
[13:07:00] Using gulpfile C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\gulpfile.js
[13:07:00] Starting 'run-wdio'...
[13:07:00] Starting 'start-selenium-and-wdio'...
edgeexecutable: ./node_modules/msedgedriver/lib/msedgedriver/msedgedriver.exe
command: java -jar ./node_modules/selenium-server-standalone-jar/jar/selenium-server-4.7.1.jar -log ../seleniumLog.txt -Dwebdriver.edge.driver=C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\msedgedriver\lib\msedgedriver\msedgedriver.exe
Starting Selenium Server
[13:07:00] spawn wdio with these attributes:
 C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\cuke-2023-03-22T13-07-00.302Z.tmp


Execution of 1 workers started at 2023-03-22T13:07:04.172Z

[0-0] RUNNING in msedge - C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\tests\features\featureFiles\web\newFeatureCheck\csAsIFARpAllPayeeNewVersion.feature
[0-0] 2023-03-22T13:07:09.535Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4444
[0-0]     at ClientRequest.<anonymous> (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\got\dist\source\core\index.js:970:111)
[0-0]     at Object.onceWrapper (node:events:628:26)
[0-0]     at ClientRequest.emit (node:events:525:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at ClientRequest.origin.emit (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
[0-0]     at Socket.socketErrorListener (node:_http_client:494:9)
[0-0]     at Socket.emit (node:events:513:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:157:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
[0-0] 2023-03-22T13:07:09.537Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://localhost:4444/", make sure browser driver is running on that address.
[0-0] If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-0]     at startWebDriverSession (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\webdriver\build\utils.js:73:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Function.newSession (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\webdriver\build\index.js:46:45)
[0-0]     at async remote (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\webdriverio\build\index.js:78:22)
[0-0]     at async Runner._startSession (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\@wdio\runner\build\index.js:223:56)
[0-0]     at async Runner._initSession (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\@wdio\runner\build\index.js:176:25)
[0-0]     at async Runner.run (C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\node_modules\@wdio\runner\build\index.js:88:19)
[0-0] FAILED in msedge - C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework\tests\features\featureFiles\web\newFeatureCheck\csAsIFARpAllPayeeNewVersion.feature

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:05

[13:07:09] wdio testrunner finished with exit code 1
Deleting tmp cuke file
[13:07:09] Finished 'start-selenium-and-wdio' after 9.72 s
[13:07:09] Starting 'stop-selenium'...
[13:07:09] Finished 'stop-selenium' after 1.99 ms
[13:07:09] Finished 'run-wdio' after 9.73 s

C:\SwCoWAT_Framework\ra-js-test-framework\RA_WDIO_Framework>
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ```ts
> RequestError: connect ECONNREFUSED 127.0.0.1:4444
> ```

This means the Selenium server hasn't started so WebdriverIO can't connect. Please verify you have started the Selenium server correctly and the server is ready to receive requests before running WebdriverIO tests. You might want to take a look and use the WebdriverIO Selenium service.

I will close this because this doesn't seem to be an issue with WebdriverIO.
