### ISSUE TITLE
[🐛 Bug]: TypeError: browser.getElementRect is not a function when calling scrollIntoView

### ISSUE THREAD

**Issue by kobenguyent** [webdriverio/webdriverio#10044]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

webdriverio@8.6.8

### Node.js Version

v16.19.1

### Mode

Standalone Mode

### What happened?

TypeError: browser.getElementRect is not a function when calling scrollIntoView, happens only with ci/cd, github in this case, locally working fine.
https://github.com/codeceptjs/CodeceptJS/actions/runs/4511428723/jobs/7943563879

### How to reproduce the bug.

https://github.com/codeceptjs/CodeceptJS/actions/runs/4511428723/jobs/7943563879

trigger the build on pipeline, please contact me if you need to trigger the build

### Relevant log output

```typescript
1) WebDriver
       #scrollIntoView
         should scroll element into viewport:
     TypeError: browser.getElementRect is not a function
      at Element.scrollIntoView (file:///home/runner/work/CodeceptJS/CodeceptJS/node_modules/webdriverio/build/commands/element/scrollIntoView.js:46:36)
      at Element.wrapCommandFn (file:///home/runner/work/CodeceptJS/CodeceptJS/node_modules/@wdio/utils/build/shim.js:72:38)
      at Element.<anonymous> (file:///home/runner/work/CodeceptJS/CodeceptJS/node_modules/@wdio/utils/build/shim.js:210:24)
      at Element.elementErrorHandlerCallbackFn (file:///home/runner/work/CodeceptJS/CodeceptJS/node_modules/webdriverio/build/middlewares.js:18:65)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Element.wrapCommandFn (file:///home/runner/work/CodeceptJS/CodeceptJS/node_modules/@wdio/utils/build/shim.js:72:29)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide a minimal reproducible example please? I need to be able to reproduce this on my machine and not in CI.
