### ISSUE TITLE
[🐛 Bug]: Parent Elements cannot be selected by the Text

### ISSUE THREAD

**Issue by RahulARanger** [webdriverio/webdriverio#10040]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.6.7

### Node.js Version

18.14.2

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
browserName: "chrome",
maxInstances: 1
}
```

### What happened?

For our project, we have preferred [selecting an element by text](https://webdriver.io/docs/selectors/#element-with-certain-text). This helped us select very minor elements easily and quickly but recently we observed it was not able to select the required elements.

After deep dive we have observed, the following change

For instance, for the below snipped, in order to select the button
```html
<button>
      <span>Button Text</span>
</button>
```

we wrote the following script,

```js
$("button=Button Text").click()
```

but now we are now required to write 
```js
$("span=Button Text").click()
```

In the first case the main advantage was;

1. Allow Users to select the Parent elements based on the text regardless of its child nodes
```js
expect($("button#button-id")).toHaveText("Button Text")
```
2.  From the User perspective, both tags have the same Text.

And after we updated our packages we faced this issue, after some exploring, I really accept the motive behind #9992 which is technically correct since span is the only element having that text but from the user perspective, it is also valid to say that the button tag has the same text.

### What is your expected behavior?

Both methods must be allowed to select any element with the requested text.

```js
$("button=Button Text").click()
```
```js
$("span=Button Text").click()
```

### How to reproduce the bug.

To reproduce this bug, please execute this following standalone code:

### Aim: To select the Following Button for Sign In

<img width="960" alt="image" src="https://user-images.githubusercontent.com/57987728/227316687-c59c846c-574f-4b5e-822f-d83a0f088419.png">

### Target Element's HTML

```html
<a class="gb_ja gb_ka gb_ge gb_gd">
<span class="gb_ie">Sign in</span>
</a>
```

#### Automation Script

```js
import { remote } from 'webdriverio'

const browser = await remote({
    capabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: process.env.CI ? ['headless', 'disable-gpu'] : []
        }
    }
})

await browser.url('https://www.google.com/')


if(await browser.$("span=Sign in").getText("Sign in") !== "Sign in")
    throw new Error("Failed")

try{
    await browser.$("button=Sign in").getText();
}
catch(error){
    console.log("Fails because of the error: ", error);
}
finally{
    console.log("Please allow both the notations");
}

await browser.deleteSession();
```

### Relevant log output

```typescript
023-03-23T18:53:48.391Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
2023-03-23T18:53:48.395Z INFO devtools: Launch Google Chrome (undefined) with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900
2023-03-23T18:53:48.966Z INFO devtools: Connect Puppeteer with browser on port 58770
2023-03-23T18:53:49.375Z INFO devtools: COMMAND navigateTo("https://www.google.com/")
2023-03-23T18:53:51.043Z INFO devtools: RESULT null
2023-03-23T18:53:51.053Z INFO devtools: COMMAND findElement("xpath", ".//span[normalize-space(text()) = "Sign in"]")
2023-03-23T18:53:51.108Z INFO devtools: RESULT { 'element-6066-11e4-a52e-4f735466cecf': 'ELEMENT-1' }
2023-03-23T18:53:51.121Z INFO devtools: COMMAND getElementText("ELEMENT-1")
2023-03-23T18:53:51.131Z INFO devtools: RESULT Sign in
2023-03-23T18:53:51.134Z INFO devtools: COMMAND findElement("xpath", ".//button[normalize-space(text()) = "Sign in"]")
2023-03-23T18:53:51.145Z INFO devtools: RESULT Error: Element with selector ".//button[normalize-space(text()) = "Sign in"]" not found
    at DevToolsDriver.findElement (file:///..//WebdriverioPlayground/node_modules/devtools/build/utils.js:98:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Browser.wrappedCommand (file:///..//WebdriverioPlayground/node_modules/devtools/build/devtoolsdriver.js:127:26)
    at async Browser.wrapCommandFn (file:///..//WebdriverioPlayground/node_modules/@wdio/utils/build/shim.js:72:29)
    at async Browser.$ (file:///..//WebdriverioPlayground/node_modules/webdriverio/build/commands/browser/$.js:74:17)
    at async Browser.wrapCommandFn (file:///..//WebdriverioPlayground/node_modules/@wdio/utils/build/shim.js:72:29)
    at async file:///..//WebdriverioPlayground/test.js:19:5
2023-03-23T18:53:51.155Z INFO devtools: COMMAND findElements("xpath", ".//button[normalize-space(text()) = "Sign in"]")
2023-03-23T18:53:51.165Z INFO devtools: RESULT []
2023-03-23T18:53:51.661Z INFO devtools: COMMAND findElements("xpath", ".//button[normalize-space(text()) = "Sign in"]")
2023-03-23T18:53:51.676Z INFO devtools: RESULT []
2023-03-23T18:53:52.169Z INFO devtools: COMMAND findElements("xpath", ".//button[normalize-space(text()) = "Sign in"]")
2023-03-23T18:53:52.181Z INFO devtools: RESULT []
2023-03-23T18:53:52.662Z INFO devtools: COMMAND findElements("xpath", ".//button[normalize-space(text()) = "Sign in"]")
2023-03-23T18:53:52.674Z INFO devtools: RESULT []
2023-03-23T18:53:53.159Z INFO devtools: COMMAND findElements("xpath", ".//button[normalize-space(text()) = "Sign in"]")
2023-03-23T18:53:53.168Z INFO devtools: RESULT []
2023-03-23T18:53:53.667Z INFO devtools: COMMAND findElements("xpath", ".//button[normalize-space(text()) = "Sign in"]")
2023-03-23T18:53:53.686Z INFO devtools: RESULT []
Fails because of the error:  Error: Can't call getText on element with selector "button=Sign in" because element wasn't found
    at implicitWait (file:///..//WebdriverioPlayground/node_modules/webdriverio/build/utils/implicitWait.js:29:19)
    at async Element.elementErrorHandlerCallbackFn (file:///..//WebdriverioPlayground/node_modules/webdriverio/build/middlewares.js:14:29)
    at async Element.wrapCommandFn (file:///..//WebdriverioPlayground/node_modules/@wdio/utils/build/shim.js:72:29)
    at async file:///..//WebdriverioPlayground/test.js:19:5
Please allow both the notations
2023-03-23T18:53:54.165Z INFO devtools: COMMAND deleteSession()
2023-03-23T18:53:54.167Z INFO devtools: RESULT null
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @RahulARanger , thanks for raising the issue and for this great description! I actually encountered this DX issue myself and already tried to find a solution, without success. My use case was even more trivial: given a node like this:

```html
<span>
    Hello
    World
</span>
```

`Hello World` can be two HTML text nodes which causes a selector like `$('span=Hello World')` to fail.

> but from the user perspective, it is also valid to say that the button tag has the same text.

Yes, there is an edge case though, let's say we have this:
```html
<button style="display: block; width: 100px;">
      <span style="width: 20px; margin-left: 60px">Button Text</span>
</button>
```
and the click listener is registered on the span rather than the button. If we would select the button, WebDriver would click to the middle of it and misses the span which is also not optimal.

The change that causes this is this one:
```patch
- .//span[normalize-space() = "Sign in"]
+ .//span[normalize-space(text()) = "Sign in"]
```

I tried an attempt where I would chain both e.g. `(.//span[normalize-space(text()) = "Sign in"] | .//span[normalize-space() = "Sign in"])` where xPath would pick the first query that would find a node (like we do for the a11y selectors). Basically try the more strict selector first and then the looser one. However that wasn't working. Maybe I did something wrong with the chaining, I don't know. We could also think about creating a helper that would allow making actual `findElement` calls to see if individual queries actual hold elements.

I am open for suggestions here and would like to see this improved as well.

**Comment by RahulARanger** [comment]
Sure. Yes, those are the cases we might experience and would fail if used the previous XPath expression.
I really like the chaining approach. I will explore it.
I will try to cover possible cases.

**Comment by christian-bromann** [comment]
Awesome! Just fyi: I found that tweaking around with locators is the easiest using the browser runner as you can just render any HTML on the page and test it with WebDriver locators. This is why I extended our locator tests and added some locator e2e test in our [lit component test case](https://github.com/webdriverio/webdriverio/blob/main/e2e/browser-runner/lit.test.js#L115-L235). You can run this via:

```sh
npm run test:component:setup
cd e2e
npm run test:browser:lit:wdio -- --watch
```

**Comment by RahulARanger** [comment]
Sure. I will try it.
