### ISSUE TITLE
[🐛 Bug]: waitForDisplayed, waitForExist doesn't work with SauceLabs

### ISSUE THREAD

**Issue by Eriusik** [webdriverio/webdriverio#10118]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v16.14.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'sauce:options': {
            'build': 'test',
            'tags': 'web',
            'screenResolution': '1920x1080'
        },
    }],
```

### What happened?

I used default config with saucelabs options and command:
        await this.inputUsername.waitForDisplayed({timeout: 15000});
Element is shown after 3-5 seconds but starting from Monday it doesn't wait.

[chrome 111.0.5563.65 windows #0-0] Running: chrome (v111.0.5563.65) on windows
[chrome 111.0.5563.65 windows #0-0] Session ID: 4eb7538213264c16ac72d85644fa862a
[chrome 111.0.5563.65 windows #0-0]
[chrome 111.0.5563.65 windows #0-0] » /test/specs/example.e2e.js
[chrome 111.0.5563.65 windows #0-0] My Login application
[chrome 111.0.5563.65 windows #0-0]    ✖ should login with valid credentials
[chrome 111.0.5563.65 windows #0-0]
[chrome 111.0.5563.65 windows #0-0] 1 failing (2.7s)
[chrome 111.0.5563.65 windows #0-0]
[chrome 111.0.5563.65 windows #0-0] 1) My Login application should login with valid credentials
[chrome 111.0.5563.65 windows #0-0] no such element: Unable to locate element: {"method":"css selector","selector":"#username"}
  (Session info: chrome=111.0.5563.65)

### How to reproduce the bug.

If use in config
        'sauce:options': {
            'build': 'test',
            'tags': 'web',
            'screenResolution': '1920x1080'
        },
Commands like waitForDisplayed doesn't work.
But if I delete this section this command works.

I have this problem on WDIO 7 but I check it on WDIO 8 with default tests and configuration and problem is reproduced.

### Relevant log output

```typescript
2023-04-04T18:27:02.720Z INFO webdriver: COMMAND findElement("css selector", "#username")
[0-0] 2023-04-04T18:27:02.721Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/4eb7538213264c16ac72d85644fa862a/element
[0-0] 2023-04-04T18:27:02.721Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2023-04-04T18:27:02.837Z WARN webdriver: Request failed with status 200 due to no such element: Unable to locate element: {"method":"css selector","selector":"#username"}
[0-0]   (Session info: chrome=111.0.5563.65)
[0-0] 2023-04-04T18:27:02.837Z INFO webdriver: Retrying 1/3
[0-0] 2023-04-04T18:27:02.837Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/4eb7538213264c16ac72d85644fa862a/element
[0-0] 2023-04-04T18:27:02.837Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2023-04-04T18:27:02.932Z WARN webdriver: Request failed with status 200 due to no such element: Unable to locate element: {"method":"css selector","selector":"#username"}
[0-0]   (Session info: chrome=111.0.5563.65)
[0-0] 2023-04-04T18:27:02.932Z INFO webdriver: Retrying 2/3
[0-0] 2023-04-04T18:27:02.932Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/4eb7538213264c16ac72d85644fa862a/element
[0-0] 2023-04-04T18:27:02.932Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2023-04-04T18:27:03.031Z WARN webdriver: Request failed with status 200 due to no such element: Unable to locate element: {"method":"css selector","selector":"#username"}
[0-0]   (Session info: chrome=111.0.5563.65)
[0-0] 2023-04-04T18:27:03.031Z INFO webdriver: Retrying 3/3
[0-0] 2023-04-04T18:27:03.031Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/4eb7538213264c16ac72d85644fa862a/element
[0-0] 2023-04-04T18:27:03.031Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2023-04-04T18:27:03.128Z ERROR webdriver: Request failed with status 200 due to no such element: no such element: Unable to locate element: {"method":"css selector","selector":"#username"}
[0-0]   (Session info: chrome=111.0.5563.65)
[0-0] 2023-04-04T18:27:03.130Z INFO webdriver: COMMAND executeScript("sauce:context=  (Session info: chrome=111.0.5563.65)", <object>)
[0-0] 2023-04-04T18:27:03.130Z INFO webdriver: COMMAND executeScript("sauce:context=    at processTicksAndRejections (node:internal/process/task_queues:96:5)", <object>)
[0-0] 2023-04-04T18:27:03.130Z INFO webdriver: COMMAND executeScript("sauce:context=    at async LoginPage.login (file:///Users/wildix/tests/rnc-autotests/wdio8/test/pageobjects/login.page.js:29:9)", <object>)
[0-0] 2023-04-04T18:27:03.131Z INFO webdriver: COMMAND executeScript("sauce:context=    at async Context.<anonymous> (file:///Users/wildix/tests/rnc-autotests/wdio8/test/specs/example.e2e.js:8:9)", <object>)
[0-0] 2023-04-04T18:27:03.131Z INFO webdriver: COMMAND executeScript("sauce:context=no such element: no such element: Unable to locate element: {"method":"css selector","selector":"#username"}", <object>)
[0-0] no such element in "My Login application.should login with valid credentials"
no such element: no such element: Unable to locate element: {"method":"css selector","selector":"#username"}
  (Session info: chrome=111.0.5563.65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LoginPage.login (file:///Users/wildix/tests/rnc-autotests/wdio8/test/pageobjects/login.page.js:29:9)
    at async Context.<anonymous> (file:///Users/wildix/tests/rnc-autotests/wdio8/test/specs/example.e2e.js:8:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide a reproducible example? I just created a new WDIO project and selected Sauce as backend and the provided example test passed just fine.

**Comment by Eriusik** [comment]
I added sauce options to the capabilities
    capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'sauce:options': {
            'build': 'test',
            'tags': 'web',
            'screenResolution': '1920x1080'
        },
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],

than I added command waitForDisplayed to the default page object
    async login (username, password) {
        await this.inputUsername.waitForDisplayed({timeout: 15000});
        await this.inputUsername.setValue(username);
        await this.inputPassword.setValue(password);
        await this.btnSubmit.click();
    }

than I change selector to the incorrect to see the error. 
    get inputUsername () {
        return $('#usernamem');
    }

I wanted to see the error after 15 seconds, but ,it doesn't wait 15 seconds and shows me an error "no such element"

**Comment by christian-bromann** [comment]
Checkout this job: https://app.saucelabs.com/tests/d8a92515532043d7b40ed83228a27570?auth=be05ed7191b03f437e14ed3917ff0902 it uses the capabilities you mention but passes.

**Comment by Eriusik** [comment]
Yes, but here test doesn't wait several seconds.The page is loading very quickly. I need to wait several seconds when elements will be shown on my real site. But the command doesn't wait. So, here is example, when I want to wait 15 seconds and I use incorrect  selector for this:
https://app.eu-central-1.saucelabs.com/tests/c07560906b0b4b64b5463ee0f7b29c02?auth=6c9bad67f5dd0ba5688e3bb86d85c562#6
But you can see that command "FIND" works only during 1 second

And the default configuration without any options:
https://app.eu-central-1.saucelabs.com/tests/18c7fcb59d6b4974875c65cc8e2f848e?auth=efd49f26148cfb7336703d4f2ee27274
Here I see that we are waiting for 15 seconds and the error has correct message.

**Comment by christian-bromann** [comment]
It seems like Sauce Labs is treating the test without `sauce:option` as a JSONWireProtocol session which could be the reason why the behavior differs. Anyhow I don't see how this is connected to an issue within WebdriverIO and I am not sure what we can do here about it. I recommend to reach out to their support. Happy to answer further questions.

**Comment by Eriusik** [comment]
This problem not only with sauce options. If I add "browserVersion: 'latest'," waitForDisplayed doesn't work correctly too. We are speaking with sauceLabs support but they don't have answer what happened.

**Comment by igor-lantushenko** [comment]
Man I have the same issue with sauce labs started on previous week.
So what I found out:
sauce labs returns 
```no such element```

**Comment by igor-lantushenko** [comment]
> > Which is wrong according to the W3C format
> 
> Did you reach out to their support team to raise this issue?

Messaged them and described the error - and they seems not to be impressed or pleaded guilty,
I have a call with them tomorrow.

But the reply so far is:
```
The status code in Postman is the code for the call itself, not for the reply
 
It means that we successfully received an API response. And that response contains a "no such element" message. While the 404 in the UI with "no such element" is related to the response itself 
 
Please let me know if it makes sense
```

I believe they are wrong when trying to describe `The status code in Postman is the code for the call itself`
Because I printout the response code in wdio library and its also 200 instead of 404

**Comment by Tomasz-Klubasz** [comment]
> > > Which is wrong according to the W3C format
> > 
> > 
> > Did you reach out to their support team to raise this issue?
> 
> Messaged them and described the error - and they seems not to be impressed or pleaded guilty, I have a call with them tomorrow.
> 
> But the reply so far is:
> 
> ```
> The status code in Postman is the code for the call itself, not for the reply
>  
> It means that we successfully received an API response. And that response contains a "no such element" message. While the 404 in the UI with "no such element" is related to the response itself 
>  
> Please let me know if it makes sense
> ```
> 
> I believe they are wrong when trying to describe `The status code in Postman is the code for the call itself` Because I printout the response code in wdio library and its also 200 instead of 404
> 
> There are logs in their UI system - and logs have 404 error - which is correct, but in fact response is 200

@igor-lantushenko - Was that call helpful? I'm facing same issues, so are other people - https://github.com/webdriverio/webdriverio/issues/10182

**Comment by Eriusik** [comment]
@igor-lantushenko Have you any news after the call. 
For more than one week I don't get a response from SauceLabs where they would acknowledge the problem.

**Comment by igor-lantushenko** [comment]
> > > > Which is wrong according to the W3C format
> > > 
> > > 
> > > Did you reach out to their support team to raise this issue?
> > 
> > 
> > Messaged them and described the error - and they seems not to be impressed or pleaded guilty, I have a call with them tomorrow.
> > But the reply so far is:
> > ```
> > The status code in Postman is the code for the call itself, not for the reply
> >  
> > It means that we successfully received an API response. And that response contains a "no such element" message. While the 404 in the UI with "no such element" is related to the response itself 
> >  
> > Please let me know if it makes sense
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I believe they are wrong when trying to describe `The status code in Postman is the code for the call itself` Because I printout the response code in wdio library and its also 200 instead of 404
> > There are logs in their UI system - and logs have 404 error - which is correct, but in fact response is 200
> 
> @igor-lantushenko - Was that call helpful? I'm facing same issues, so are other people - #10182

I would say yes, it was helpful - in terms of better describing what exactly is wrong. So they promised to take a look precisely, I provided all the examples and basically i'm waiting for the response from support after they reached development team. I'll keep you updated
