### ISSUE TITLE
[🐛 Bug]: can't include 'android/ios' string in config file while start repl session

### ISSUE THREAD

**Issue by efinal** [webdriverio/webdriverio#10165]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.15.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
            platformName: 'Android',
            'appium:automationName': 'UiAutomator2',
            'appium:deviceName': 'Android',
            'appium:app': 'xxx.apk',
            'appium:noReset': 'true',
            'appium:forceAppLaunch': 'true',
            'appium:shouldTerminateApp': 'true',
            'appium:autoGrantPermissions': 'false',
            'appium:allowTestPackages': 'true',
            'appium:enforceAppInstall': 'false',
            'appium:skipUnlock': 'true',
            'appium:skipServerInstallation': 'true',
        }
```

### What happened?

I tried to start a new repl session with `wdio repl "path/to/config/wdio.repl.android.conf.js" 0 -h 10.8.15.1 -p 4723`, however, it nerver read contents in config file.

### What is your expected behavior?

the capabilities in the config file can be used

### How to reproduce the bug.

just use a string contains 'android' or 'ios' to name the config file, like 'wdio.repl.android.conf.js'

the problem is in 'webdriverio/packages/wdio-cli/src/utils.ts' getCapabilities function line 298 where 'android/ios' string is tested against the args.  

### Relevant log output

```typescript
All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: automationName,deviceName
    at startWebDriverSession (file:///C:/Users/yangy/AppData/Roaming/nvm/v18.15.0/node_modules/@wdio/cli/node_modules/webdriver/build/utils.js:68:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebDriver.newSession (file:///C:/Users/yangy/AppData/Roaming/nvm/v18.15.0/node_modules/@wdio/cli/node_modules/webdriver/build/index.js:24:45)
    at async remote (file:///C:/Users/yangy/AppData/Roaming/nvm/v18.15.0/node_modules/@wdio/cli/node_modules/webdriverio/build/index.js:48:22)
    at async Object.handler (file:///C:/Users/yangy/AppData/Roaming/nvm/v18.15.0/node_modules/@wdio/cli/build/commands/repl.js:44:20)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!



Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
@efinal I looked into this and I can launch the correct capabilities based on the repl values. It seems that this error comes from Appium. Can you provide your full wdio.conf.js and the wdio logs?

**Comment by christian-bromann** [comment]
Closing due to inactivity
