### ISSUE TITLE
[🐛 Bug]: browser.mock doesn't work with Dynamic Selenium Grid 4

### ISSUE THREAD

**Issue by PinhoL** [webdriverio/webdriverio#10192]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v16.13.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
const path = require("node:path");

exports.config = {
    /**
     * specify test files
     */
    specs: [[path.resolve(__dirname, "*.spec.js")]],

    /**
     * capabilities
     */
    capabilities: [
        {
            browserName: "chrome",
            acceptInsecureCerts: true,
            "wdio:devtoolsOptions": {
                headless: true,
            },
        },
    ],

    /**
     * test configurations
     */
    logLevel: "trace",
    outputDir: __dirname,
    framework: "jasmine",

    reporters: ["spec"],

    hostname: "<external-IP>",
    port: 4444,
    path: "/wd/hub",

    jasmineOpts: {
        defaultTimeoutInterval: 1000 * 60 * 3,
    }
};
```

### What happened?

I've a setup of a Selenium Grid distributed over different VMs where I run my WDIO tests mocking resources with success.
I've tried to implement a Distributed Dynamic Selenium Grid ( https://github.com/SeleniumHQ/docker-selenium#using-dynamic-grid-in-different-machinesvms ) and I've noticed that the `browser.mock` is not handling this very well due to the CDP connection (I think). In this distributed system, we have a `Hub` connected to a `node-docker` which eventually will launch a chrome/firefox/etc if it's asked to. I think that the CDP connection is being attributed to the `node-docker` instead of the new container launched.

### What is your expected behavior?

The expected behaviour is that the CDP connection is made to the launched container.

### How to reproduce the bug.

In order to replicate this, I've a setup of 2 different VMs running the `hub`/`node`.

VM1:
```
docker run -p 4442-4444:4442-4444 selenium/hub:4.8.3-20230404
```

VM2:
```
docker run --net=host -p 5555:5555 \
    -e SE_EVENT_BUS_HOST=<IP-VM1> \
    -e SE_NODE_GRID_URL=http://<IP-VM1>:4444 \
    -e SE_NODE_HOST=<IP-VM2> \
    -e SE_NODE_PORT=5555 \
    -e START_XVFB=false \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -e SE_NODE_OVERRIDE_MAX_SESSIONS=true \
    -v ${PWD}/config.toml:/opt/bin/config.toml \
    -v ${PWD}/assets:/opt/selenium/assets \
    -v /var/run/docker.sock:/var/run/docker.sock \
    selenium/node-docker:4.8.3-20230404
```

And my test file can be anything with a `browser.mock`, I've used this example:
```
describe("webdriver.io page", () => {
    it("should have the right title", async () => {
        const pageMock = await browser.mock("https://google.com/");
        pageMock.respond("https://webdriver.io");
        await browser.url("https://google.com");
        console.log(await browser.getTitle()); // returns "WebdriverIO · Next-gen browser and mobile automation test framework for Node.js"
    });
});
```

If I run a test without the `browser.mock` instruction, everything runs fine. With the instruction, I get this error on the node:
```
 [Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --disable-web-security, --auto-open-devtools-for-tabs], mobileEmulation: {deviceName: iPhone 6}}}]
16:00:53.904 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 96ebc87665f305c3b8d2b0c0b480c695
 Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 111.0.5563.146, chrome: {chromedriverVersion: 111.0.5563.64 (c710e93d5b63..., userDataDir: /tmp/.com.google.Chrome.Jtc6Vn}, goog:chromeOptions: {debuggerAddress: localhost:46211}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: LINUX, proxy: {}, se:bidiEnabled: false, se:cdp: ws://<IP-VM1>..., se:cdpVersion: 111.0.5563.146, se:forwardCdp: ws://172.17.0.2:12927/sessi..., se:vnc: ws://<IP-VM1>..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
16:00:54.443 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:131)
	at org.openqa.selenium.netty.server.RequestConverter.channelRead0(RequestConverter.java:55)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.openqa.selenium.netty.server.WebSocketUpgradeHandler.channelRead(WebSocketUpgradeHandler.java:100)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

What caught my attention here was the `forwardCdp` param. It is pointing to 172.17.0.2, where previously (when I had a chrome directly connected to the hub) it would point to `localhost`.

![image](https://user-images.githubusercontent.com/106379282/232034349-86e0c97a-5719-4332-b73f-31010bf8f4b5.png)

As you can see by the above image, the `node-docker` container is responsible to start new containers on different ports, but it is indeed the `node-docker` that is connected to the `hub`, which is why I think that the CDP connection is maybe being created by this link, instead of being mapped to the "new" container created. (172.17.0.2 is the container's IP, which doesn't have that WS port).

### Relevant log output

```typescript
The WDIO log just shows:

[0-0] RUNNING in chrome - file:///jasmine/jasmine.spec.js
[0-0] Error in "webdriver.io page should have the right title"
socket hang up
[0-0] FAILED in chrome - file:///jasmine/jasmine.spec.js
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by PinhoL** [comment]
Tagging @dylanlive as he might have some clues on this

**Comment by PinhoL** [comment]
Hello @christian-bromann thanks so much for taking the time to reply!

A reproducible example can be achieved very fast with:

Start this with docker-compose file with `docker-compose -f docker-compose.yml up`. I had to create the /assets folder locally and also expose the 2376 port on my docker for mac ( I ran `socat -d TCP-LISTEN:2376,range=127.0.0.1/32,reuseaddr,fork UNIX:/Users/MY-USER/.docker/run/docker.sock` to achieve this).

```yaml
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.8.3-20230404
    volumes:
      - ./config.toml:/opt/bin/config.toml
      - ./assets:/opt/selenium/assets
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.8.3-20230404
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

The TOML file can be just this:
```toml
[docker]
configs = [
    "selenium/standalone-chrome:4.8.3-20230404", '{"browserName": "chrome"}'
    ]

url = "http://127.0.0.1:2375"
```


When the grid is up, running a simple test like:
```javascript
describe("webdriver.io page", () => {
    it("should have the right title", async () => {
        const pageMock = await browser.mock("https://google.com/");
        pageMock.respond("https://webdriver.io");
        await browser.url("https://google.com");
        console.log(await browser.getTitle()); // returns "WebdriverIO · Next-gen browser and mobile automation test framework for Node.js"
    });
});
```

Having the appropriate conf file with:
```
    hostname: "localhost",
    port: 4444,
    path: "/wd/hub",
```

Will make the test fail. If I remove the `browser.mock` it runs successfully.

I'll try to dig in a little bit deeper on this problem, but I'm a little bit lost on the codebase. I do thing it's the CDP connection, because I get an error like: ```[chrome 111.0.5563.146 LINUX #0-0] 1) webdriver.io page should have the right title
[chrome 111.0.5563.146 LINUX #0-0] connect ETIMEDOUT 172.22.0.3:4444```. I think with this architecture, the way that the CDP is retrieved from the grid endpoint is not accurate, but I'm not sure.

**Comment by PinhoL** [comment]
I found the problem. It's not directly related to WDIO.

Just for context, when I run this, we've this capabilities from the Selenium:
```
[0-0]   'se:bidiEnabled': false,
[0-0]   'se:cdp': 'ws://VIP-MACHINE-1:4444/session/b3d858244010dc6ed92ad991f3c101a2/se/cdp',
[0-0]   'se:cdpVersion': '111.0.5563.146',
[0-0]   'se:forwardCdp': 'ws://172.17.0.6:8850/session/b3d858244010dc6ed92ad991f3c101a2/se/fwd',
[0-0]   'se:vnc': 'ws://VIP-MACHINE-1:4444/session/b3d858244010dc6ed92ad991f3c101a2/se/vnc',
[0-0]   'se:vncEnabled': true,
[0-0]   'se:vncLocalAddress': 'ws://172.17.0.6:7900',
```

Problem here is that this `forwardCdp` is a field that is returned due to the `node-container` spawning other containers, so we know where to connect here https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/getPuppeteer.ts#L62 

As you can see, this param is being returned as the internal IP of the docker container that spawns others, so it will never work on a distributed system.

Sorry for creating this issue as it's not related to WDIO, I'll try to contact the selenium guys. Closing this issue

**Comment by christian-bromann** [comment]
@PinhoL thanks for providing this insight. How did you end up fixing the issue?

**Comment by PinhoL** [comment]
I didn't, I'm staying with the "non-dynamic" grid for now as I can run all my WDIO tests successfully there. From what I looked, I believe that https://github.com/SeleniumHQ/selenium/issues/9202#issuecomment-799435392 this will have to change to accommodate the `se:forwardCdp` in order for the Puppetteer inside WDIO to be able to connect to that.

**Comment by christian-bromann** [comment]
What https://github.com/SeleniumHQ/selenium/issues/9202#issuecomment-799435392 tells me is that you can pass in a parameter to your grid to have the `se:cdp` parameter correctly pointing to your grid node. We don't use `forwardCdp` in the project, are we suppose to?

**Comment by christian-bromann** [comment]
Awesome, thanks!
