### ISSUE TITLE
[🐛 Bug]: WebdriverIO reporter modules don't support CJS

### ISSUE THREAD

**Issue by jan-molak** [webdriverio/webdriverio#10314]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.9.0

### Node.js Version

18

### Mode

Standalone Mode

### What happened?

`webdriverio` module tries to support both ESM and CJS:
https://github.com/webdriverio/webdriverio/blob/630caf1aaf782d92c5ff7b7db1940bd181eadba8/packages/webdriverio/package.json#L50-L60
However, WebdriverIO **reporting modules** require the consumer to use ESM and don't support CJS at all:
https://github.com/webdriverio/webdriverio/blob/630caf1aaf782d92c5ff7b7db1940bd181eadba8/packages/wdio-reporter/package.json#L29-L32

This forces any custom WebdriverIO reporters to use ESM, forcing the wider WebdriverIO community to migrate to ESM as well.

While this might be the desired outcome, I think that the expectation to use ESM should be highlighted more in the documentation.

### What is your expected behavior?

If WebdriverIO wants to support both ESM and CJS, I believe this should be done consistently in all the `@wdio` modules. 

Having said that, I'm wondering if given the complexity and the cost of maintaining both ESM and CJS, and the fact that the wider ecosystem is slowly moving towards ESM, is it not worth for WebdriverIO to drop CJS support altogether and avoid the confusion.

### How to reproduce the bug.

To reproduce the issue, create a non-ES Node module with a WebdriverIO reporter:

```typescript
import Reporter from '@wdio/reporter';

export class MyReporter extends Reporter {
  // ...
}
```
Note that it's not possible to import the base `Reporter` class from `@wdio/reporter` in a Node module that's not an ES module.

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

> forcing the wider WebdriverIO community to migrate to ESM as well.

I am not sure if this is true. Only people that build their custom reporter are forced to write that specific reporter in ESM. Note that v7 reporter written in CJS will work with WebdriverIO v8.

> I think that the expectation to use ESM should be highlighted more in the documentation

I agree with that.

Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by jan-molak** [comment]
Hey @christian-bromann! Thanks for reviewing :-)

> > forcing the wider WebdriverIO community to migrate to ESM as well.

> I am not sure if this is true. Only people that build their custom reporter are forced to write that specific reporter in ESM. 

I put together a sample repo to explore this further: https://github.com/jan-molak/wdio-10314

So far I noticed that WDIO v8 works with tests written in CJS, as long as you:
  - [remove `"type": "module"` from `package.json`](https://github.com/jan-molak/wdio-10314/blob/main/package.json)
  - switch to [`"module": "CommonJS"` in `tsconfig.json`](https://github.com/jan-molak/wdio-10314/blob/main/tsconfig.json)
  
This is good news, as it should spare most consumers from migrating their existing test suites.

> Note that v7 reporter written in CJS will work with WebdriverIO v8.

I'm not sure if that's accurate, but perhaps I'm missing something. My understanding is that a [custom reporter](https://webdriver.io/docs/customreporter/) must extend the base reporter, and that base reporter must use the same major WDIO version as the test suite it's used with (is that not the case?).

Since `@wdio/reporter` exposes only ESM-compatible interface, I don't think it's possible to write a CJS reporter using the ESM base. Well, technically speaking one could use dynamic imports, but I don't believe WDIO would be able to load a reporter written this way, would it?

[Introducing a CJS-based reporter](https://github.com/jan-molak/wdio-10314/commit/2e8a9fdc644935485e3cc2bb05b16763eec6547c) resulted in a [compilation error](https://github.com/jan-molak/wdio-10314/actions/runs/4874071622/jobs/8694525183):

```
2023-05-03T16:07:46.493Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///home/runner/work/wdio-10314/wdio-10314/wdio.conf.ts: require() of ES Module /home/runner/work/wdio-10314/wdio-10314/node_modules/@wdio/reporter/build/index.js from /home/runner/work/wdio-10314/wdio-10314/test/CustomReporter.ts not supported.
Instead change the require of index.js in /home/runner/work/wdio-10314/wdio-10314/test/CustomReporter.ts to a dynamic import() which is available in all CommonJS modules.
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/wdio-10314/wdio-10314/node_modules/@wdio/reporter/build/index.js from /home/runner/work/wdio-10314/wdio-10314/test/CustomReporter.ts not supported.
Instead change the require of index.js in /home/runner/work/wdio-10314/wdio-10314/test/CustomReporter.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (/home/runner/work/wdio-10314/wdio-10314/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/home/runner/work/wdio-10314/wdio-10314/test/CustomReporter.ts:3:20)
    at Module.m._compile (/home/runner/work/wdio-10314/wdio-10314/node_modules/ts-node/dist/index.js:857:29)
    at Object.require.extensions.<computed> [as .ts] (/home/runner/work/wdio-10314/wdio-10314/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/home/runner/work/wdio-10314/wdio-10314/wdio.conf.ts:4:26)
    at Module.m._compile (/home/runner/work/wdio-10314/wdio-10314/node_modules/ts-node/dist/index.js:857:29)
    at Object.require.extensions.<computed> [as .ts] (/home/runner/work/wdio-10314/wdio-10314/node_modules/ts-node/dist/index.js:859:16)
    at async Promise.all (index 0)
    at async ConfigParser.addConfigFile (file:///home/runner/work/wdio-10314/wdio-10314/node_modules/@wdio/config/build/lib/ConfigParser.js:85:36)
    at async ConfigParser.initialize (file:///home/runner/work/wdio-10314/wdio-10314/node_modules/@wdio/config/build/lib/ConfigParser.js:47:[13](https://github.com/jan-molak/wdio-10314/actions/runs/4874071622/jobs/8694525183#step:5:14))
    at async Launcher.run (file:///home/runner/work/wdio-103[14](https://github.com/jan-molak/wdio-10314/actions/runs/4874071622/jobs/8694525183#step:5:15)/wdio-10314/node_modules/@wdio/cli/build/launcher.js:37:9) {
  code: 'ERR_REQUIRE_ESM'
```

**Comment by christian-bromann** [comment]
> and that base reporter must use the same major WDIO version as the test suite it's used with (is that not the case?).

That is not necessary. You can use a reporter that used `@wdio/reporter@v7`.

> * maintainers of libraries that depend on WDIO must use ESM; direct consumers of those libraries must use ESM too 🤔

Maintainer that want to create reporters can use the latest `@wdio/reporters` v8 package. However if your reporter exports interfaces to add data to reports or require support for WebdriverIO v7, a CJS export is required. See our [allure-reporter](https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-allure-reporter) as example.

> * WDIO 7 reporters won't work with WDIO 8, unless they depend on v8 base reporter (I don't know if that's true?)

They should work. WebdriverIO v8 running in ESM context can dynamically import CJS packages/reporters.

**Comment by jan-molak** [comment]
Cool, thanks, let me try that 👍🏻

**Comment by jan-molak** [comment]
OK, I've decided to approach it differently and build a hybrid module that compiles to both ESM and CJS. As always, thanks for your help, @christian-bromann!

**Comment by christian-bromann** [comment]
@jan-molak this approach seems reasonable to me. Closing.

**Comment by LindsayWangGreat** [comment]
How do you solve the issue? When I run the script, it says
ERROR @wdio/config:ConfigParser: Failed loading configuration file: file://.conf.js: require() of ES Module project/node_modules/wdio-video-reporter/dist/wdio-video-reporter.mjs not supported.
Not sure how should I proceed, I tried also solution mentioned [here](https://github.com/webdriverio/webdriverio/issues/9869). still it says 'ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't initialize "wdio-video-reporter".
[0-0] undefined'
If I require this by require('wdio-video-reporter'); it says ES Module not supported
my package.json
`  "dependencies": {
        "@wdio/cucumber-framework": "^8.29.3",
        "@wdio/sauce-service": "^8",
        "deepmerge": "^4.3.1",
        "rimraf": "^5.0",
        "wdio-video-reporter": "^5.1.4"
    },
    "devDependencies": {
        "@wdio/allure-reporter": "^8.27.2",
        "@wdio/cli": "^8.32.2",
        "@wdio/dot-reporter": "^8.27.0",
        "@wdio/junit-reporter": "^8.27.0",
        "@wdio/local-runner": "^8.27.0",
        "@wdio/mocha-framework": "^8.27.0",
        "@wdio/spec-reporter": "^8.27.0",
        "wdio-timeline-reporter": "^5.1.4",
        "wdio-ui5-service": "^2.0.4"
    },`

my conf.js is listed below
`
const { config } = require("./wdio.chrome.conf")
const merge = require("deepmerge")
const video = require('wdio-video-reporter');

const _config = {    

    mochaOpts: {
        timeout: 60000
    },

    reporters: [
        ['junit', {
            outputDir: 'target',
            outputFileFormat: function(config) { // optional
                return 'results.xml'
            }
        }],
        [video, {
            saveAllVideos: false,       // If true, also saves videos for successful test cases
            videoSlowdownMultiplier: 3, // Higher to get slower videos, lower for faster videos [Value 1-100]
        }],
        ['allure', {
            outputDir: 'target/allure-results',
            disableWebdriverStepsReporting: false,
            disableWebdriverScreenshotsReporting: false,
        }]
    ],

    capabilities: [
        {
            // maxInstances can get overwritten per capability. So if you have an in-house Selenium
            // grid with only 5 firefox instances available you can make sure that not more than
            // 5 instances get started at a time.
            maxInstances: 5,
            //
            browserName: "chrome",
            acceptInsecureCerts: true,
            // If outputDir is provided WebdriverIO can capture driver session logs
            // it is possible to configure which logTypes to include/exclude.
            // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
            // excludeDriverLogs: ['bugreport', 'server'],
            "goog:chromeOptions": {
                args:
                    process.argv.indexOf("--headless") > -1
                        ? ["--headless"]
                        : process.argv.indexOf("--debug") > -1
                        ? ["window-size=1920,1080", "--auto-open-devtools-for-tabs"]
                        : ["window-size=1920,1080"]
            },
            "wdi5:authentication": {
                provider: "custom", //> mandatory
                usernameSelector: "input[id='USERNAME_FIELD-inner']", //> mandatory
                passwordSelector: "input[id='PASSWORD_FIELD-inner']", //> mandatory
                submitSelector: "button[id='LOGIN_LINK']", //> mandatory
                //basicAuthUrls: ["https://ldcifrd.wdf.sap.corp:44300/sap/bc/ui2/flp?sap-client=100"] //> optional: default is the configured `baseUrl`
            },
        }
    ],

    baseUrl: 'https://ldcifrd.wdf.sap.corp:44300/sap/bc/ui2/flp?sap-client=100&sap-language=EN'
}

exports.config = merge(config, _config)`

**Comment by christian-bromann** [comment]
@LindsayWangGreat do the following change in your WDIO config:

```patch
-     [video, {
+     ['video', {
        saveAllVideos: false,       // If true, also saves videos for successful test cases
        videoSlowdownMultiplier: 3, // Higher to get slower videos, lower for faster videos [Value 1-100]
    }],
```

and remove the `const video = require('wdio-video-reporter');` line.

**Comment by siri100** [comment]
@christian-bromann 
getting this error :
ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't find plugin "SlackReporter" reporter, neither as wdio scoped package "@wdio/slackreporter-reporter" nor as community package "wdio-slackreporter-reporter". Please make sure you have it installed!
for : 
 reporters: ['spec' ,[
    
    'SlackReporter',
    {
      slackOptions: {
        type: 'web-api',
        channel: process.env.SLACK_CHANNEL || 'Cxxxxxxxxxx',
        slackBotToken: process.env.SLACK_BOT_TOKEN || 'xoxb-xxxxxxxxxx-xxxxxx...',
      },
    }
  ],
],
Loading this is in commonjs module

**Comment by christian-bromann** [comment]
@siri100 there is no such reporter

**Comment by siri100** [comment]
@christian-bromann  i'm referring this https://webdriver.io/docs/wdio-slack-reporter

**Comment by christian-bromann** [comment]
It seems that you have wrapped the import into `'`, the correct way to define the reporter is:
```ts
import SlackReporter from '@moroo/wdio-slack-reporter';
export const config: WebdriverIO.Config = {
  reporters: ['spec' ,['slack', {
    slackOptions: {
      type: 'web-api',
      channel: process.env.SLACK_CHANNEL || 'Cxxxxxxxxxx',
      slackBotToken: process.env.SLACK_BOT_TOKEN || 'xoxb-xxxxxxxxxx-xxxxxx...',
    },
  }],
],
```

**Comment by siri100** [comment]
@christian-bromann Thanks this worked
