### ISSUE TITLE
[🐛 Bug]: Unable to execute the test due to chrome-launcher error

### ISSUE THREAD

**Issue by amrsa1** [webdriverio/webdriverio#10406]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### What happened?

Executing the test with the regular command "npx wdio ...." is throwing error as shown below

```
/home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/chrome-finder.js:14
const log = require('lighthouse-logger');
            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/warrior/Desktop/sample-master/node_modules/lighthouse-logger/index.js from /home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/chrome-finder.js not supported.
Instead change the require of index.js in /home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/chrome-finder.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/chrome-finder.js:14:13)
    at Object.<anonymous> (/home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/chrome-launcher.js:11:22)
    at Object.<anonymous> (/home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/index.js:13:14)
    at async Promise.all (index 0)
    at async file:///home/warrior/Desktop/sample-master/node_modules/@wdio/cli/bin/wdio.js:15:17 {
  code: 'ERR_REQUIRE_ESM'
}

```

Seems an issue with the dependency of **Lighthouse-logger** that used by chrome-launcher referring to this:

https://github.com/GoogleChrome/chrome-launcher/issues/299

upgrading the exiting chrome-launcher might be needed

### What is your expected behavior?

Test should be running normally 

### How to reproduce the bug.

- Delete node_modules, package-lock.json
- Use latest wdio version
- run npm i
- Execute any test 

### Relevant log output

```typescript
> npx wdio src/test/config/android.conf.ts

/home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/chrome-finder.js:14
const log = require('lighthouse-logger');
            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/warrior/Desktop/sample-master/node_modules/lighthouse-logger/index.js from /home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/chrome-finder.js not supported.
Instead change the require of index.js in /home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/chrome-finder.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/chrome-finder.js:14:13)
    at Object.<anonymous> (/home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/chrome-launcher.js:11:22)
    at Object.<anonymous> (/home/warrior/Desktop/sample-master/node_modules/chrome-launcher/dist/index.js:13:14)
    at async Promise.all (index 0)
    at async file:///home/warrior/Desktop/sample-master/node_modules/@wdio/cli/bin/wdio.js:15:17 {
  code: 'ERR_REQUIRE_ESM'
}

 *  The terminal process "/usr/bin/bash '-c', 'npm run android'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by amrsa1** [comment]
false alarm 
Ignore, seems now working again with the the new Lighthouse-logger which is subsequently reflect on chrome-launcher
