### ISSUE TITLE
[🐛 Bug]: Control + V does not work in headless mode, Linux

### ISSUE THREAD

**Issue by gladykov** [webdriverio/webdriverio#10414]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.10.2

### Node.js Version

v18.15.0

### Mode

Standalone Mode

### What happened?

Ctrl + V does not work in headless mode on Linux. Below code will work in head..full ;)

Same behavior happens with Playwright

### What is your expected behavior?

Expected: Text from clipboard is pasted into input, textarea

Checked wth screenshot and `element.getValue()`

### How to reproduce the bug.

```js
this.browser = remote({
                    capabilities: {
                        browserName: 'chrome',
                        'goog:chromeOptions': {
                            args: headless ? ['headless', 'disable-gpu'] : [],
                        },
                    },
                });


const element = this.browser.$(selector)
const button = ["\uE051", 'v', "\uE051"]

// Activate element
element.click()

// Method 1
await this.browser.keys(button);

// Method 2
await this.browser.action('key')
    .down("\uE051")
    .down("v")
    .up("v")
    .up("\uE051")
    .perform()

```

### Relevant log output

```typescript
npm test                                                                                                                       

> ********
> jest ************.ts --runInBand --detectOpenHandles

2023-05-18T22:32:40.684Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
2023-05-18T22:32:40.686Z INFO devtools: Launch Google Chrome (undefined) with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --headless --disable-gpu
2023-05-18T22:32:41.317Z INFO devtools: Connect Puppeteer with browser on port 41877
2023-05-18T22:32:41.411Z INFO devtools: COMMAND navigateTo("https://**************")
2023-05-18T22:32:44.141Z INFO devtools: RESULT null
  console.log
    Inserting into

      at Login.log [as fill] (tests/page_objects/basePageWebdriver.po.ts:26:17)

  console.log
    [id=username]

      at Login.log [as fill] (tests/page_objects/basePageWebdriver.po.ts:27:17)

  console.log
    is editable

      at Login.log [as fill] (tests/page_objects/basePageWebdriver.po.ts:30:17)

2023-05-18T22:32:46.223Z INFO devtools: COMMAND findElement("css selector", "[id=username]")
2023-05-18T22:32:46.243Z INFO devtools: RESULT { 'element-6066-11e4-a52e-4f735466cecf': 'ELEMENT-1' }
2023-05-18T22:32:46.253Z INFO devtools: COMMAND isElementEnabled("ELEMENT-1")
2023-05-18T22:32:46.264Z INFO devtools: RESULT true
  console.log
    is visible

      at Login.log [as fill] (tests/page_objects/basePageWebdriver.po.ts:32:17)

2023-05-18T22:32:46.269Z INFO devtools: COMMAND findElement("css selector", "[id=username]")
2023-05-18T22:32:46.272Z INFO devtools: RESULT { 'element-6066-11e4-a52e-4f735466cecf': 'ELEMENT-2' }
2023-05-18T22:32:46.278Z INFO devtools: COMMAND executeScript(<fn>, <object>)
2023-05-18T22:32:46.287Z INFO devtools: RESULT true
  console.log
    Really enetering baby

      at Login.log [as fill] (tests/page_objects/basePageWebdriver.po.ts:34:17)

2023-05-18T22:32:51.298Z INFO devtools: COMMAND findElement("css selector", "[id=username]")
2023-05-18T22:32:51.300Z INFO devtools: RESULT { 'element-6066-11e4-a52e-4f735466cecf': 'ELEMENT-3' }
2023-05-18T22:32:51.305Z INFO devtools: COMMAND elementClick("ELEMENT-3")
2023-05-18T22:32:51.327Z INFO devtools: RESULT null
2023-05-18T22:32:51.333Z INFO devtools: COMMAND performActions(<object>)
2023-05-18T22:32:51.362Z INFO devtools: COMMAND releaseActions()
2023-05-18T22:32:51.366Z INFO devtools: COMMAND performActions(<object>)
2023-05-18T22:32:51.375Z INFO devtools: COMMAND releaseActions()
2023-05-18T22:32:51.378Z INFO devtools: COMMAND findElement("css selector", "[id=username]")
2023-05-18T22:32:51.380Z INFO devtools: RESULT { 'element-6066-11e4-a52e-4f735466cecf': 'ELEMENT-4' }
2023-05-18T22:32:56.393Z INFO devtools: COMMAND takeScreenshot()
2023-05-18T22:32:56.464Z INFO devtools: RESULT iVBORw0KGgoAAAANSUhEUgAABLAAAAOECAYAAACxbcj6AAAAAXNSR0IArs4c6...
2023-05-18T22:32:56.468Z INFO devtools: COMMAND getElementProperty("ELEMENT-4", "value")
2023-05-18T22:32:56.474Z INFO devtools: RESULT 
2023-05-18T22:32:56.564Z INFO devtools: COMMAND deleteSession()
2023-05-18T22:32:56.570Z INFO devtools: RESULT null
 FAIL  tests/htmlMacro.test.ts (18.032 s)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Did any of this work in headful mode?

Any contributions that resolves the bug are highly appreciated. Don't expect this to be picked up by active contributors as they have their own priorities. If you depend on this bug to be fixed, your contribution is required. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) or join our [Discord](http://discord.webdriver.io/) development server and let us know if you have any questions. Cheers!

**Comment by gladykov** [comment]
Yes, in headful mode all works flawless.

**Comment by christian-bromann** [comment]
It seems like you are using Devtools as automation engine, have you tried running Chromedriver?

I can only guess here why this doesn't work in headless. I doubt it has to do with WebdriverIO though.

**Comment by christian-bromann** [comment]
@gladykov we recommend using the WebDriver protocol for automation. Here is an example script how it works with WebdriverIO (headless and headful):

```js
import { remote, Key } from 'webdriverio'

const browser = await remote({
    logLevel: 'error',
    capabilities: {
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: ['--headless=new']
        }
    }
})

await browser.url('https://google.com')
await browser.$('aria/Accept all').click()
await browser.$('aria/Search').setValue('WebdriverIO')
console.log(`After setting value: ${await browser.$('aria/Search').getValue()}`)

await browser.keys([Key.Ctrl, 'a', 'x'])
console.log(`After cut out value: ${await browser.$('aria/Search').getValue()}`)

await browser.keys([Key.Ctrl, 'v'])
console.log(`After paste value: ${await browser.$('aria/Search').getValue()}`)

await browser.deleteSession()
```

**Comment by gladykov** [comment]
Thank you for the tip and explanation here :)

**Comment by siddharthsid** [comment]
Hi @christian-bromann , I am still facing issue with copy paste from clipboard in headless mode (MacOs)
I have used below step to perform paste action in paste area
Can you please help me out here?

import { Key } from "webdriverio";
await browser.setPermissions({ name: "clipboard-read" }, "granted");
await browser.setPermissions({ name: "clipboard-write" }, "granted");
await browser.keys([Key.Ctrl, "v"]);

**Comment by christian-bromann** [comment]
@siddharthsid are you sure that you have text in your clipboard? Can you provide a minimal reproducible example?

**Comment by siddharthsid** [comment]
Hi @christian-bromann  - Thank you speedy response :)

Unfortunately  don’t have a demo website for you to reproduce but these are the steps which I followed , let me know if it helps else I ill try to find a demo website meanwhile

capabilities: [
    {
      maxInstances: 1,
      browserName: "chrome",
      "goog:chromeOptions": {
        args: ["--headless=new"],
      },
      unhandledPromptBehavior: "ignore",
      acceptInsecureCerts: true,
    },
  ]
  
 await browser.setPermissions({ name: "clipboard-read" }, "granted"); // This set permission for clipboard 
 await browser.setPermissions({ name: "clipboard-write" }, "granted"); // This set permission for clipboard 

// This I am performing to write data to clipboard 
 await browser.execute((data) => {
      navigator.clipboard.writeText(data);
    }, data);

// This I used to Read data from clipboard , to verify if clipboard has the data , which it printed correctly 
const clipboardText = await browser.execute(() => navigator.clipboard.readText());
 console.log(clipboardText);

// This is used to paste data from clipboard to paste area
Method 1 :
await browser.keys([Key.Ctrl, 'v']) // this doesn't work in both headless as well as headful mode
Method 2 :
await browser.keys([Key.Command, "v"]); // This works fine in headful mode but in headless mode it doesn't work

Note : 
OS : macOS (Sonoma)
Chrome : 120 
webdriverio : "8.10.2"
node : 18.14.1
 
LOGs: 
2024-01-08T15:32:14.221Z INFO webdriver: RESULT true
2024-01-08T15:32:14.222Z INFO webdriver: COMMAND getElementText("DE5A21BF6B451EC033D86BB2DD70D2DF_element_68")
2024-01-08T15:32:14.222Z INFO webdriver: [GET] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/element/DE5A21BF6B451EC033D86BB2DD70D2DF_element_68/text
2024-01-08T15:32:14.227Z INFO webdriver: RESULT Copy data from your file and paste it here (⌘V).
2024-01-08T15:32:14.234Z INFO webdriver: COMMAND executeScript("return ((data) => {
            navigator.clipboard.writeText(data);
        }).apply(null, arguments)", <object>)
2024-01-08T15:32:14.235Z INFO webdriver: [POST] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/execute/sync
2024-01-08T15:32:14.235Z INFO webdriver: DATA {
  script: 'return ((data) => {\n' +
    '            navigator.clipboard.writeText(data);\n' +
    '        }).apply(null, arguments)',
  args: [
    'role_cluster_read_only\tbusiness_unit_read_only\tlocation_read_only\tstart_of_2023_11_initial_fte_read_only\tend_of_2023_11\tend_of_2023_12\tend_of_2024_01\tend_of_2024_02\n' +
      'Finance - Junior\tFinance\tNorth America\t6\t3\t4\t5\t6'
  ]
}
2024-01-08T15:32:14.238Z INFO webdriver: RESULT null
2024-01-08T15:32:15.241Z INFO webdriver: COMMAND executeScript("return (() => navigator.clipboard.readText()).apply(null, arguments)", <object>)
2024-01-08T15:32:15.243Z INFO webdriver: [POST] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/execute/sync
2024-01-08T15:32:15.243Z INFO webdriver: DATA {
  script: 'return (() => navigator.clipboard.readText()).apply(null, arguments)',
  args: []
}
2024-01-08T15:32:15.254Z INFO webdriver: RESULT role_cluster_read_only  business_unit_read_only location_read_only  start_of_2023_11_initial_fte_read_only  end_of_2023_11  end_of_2023_12  end_of_2024_01  end_of_2024_02
Finance - Junior  Finance North America 6 3 4 5 6
2024-01-08T15:32:15.256Z INFO webdriver: COMMAND findElement("xpath", "//*[@data-testid="pasteMergeModal.pasteAreaContent"]//h4")
2024-01-08T15:32:15.257Z INFO webdriver: [POST] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/element
2024-01-08T15:32:15.257Z INFO webdriver: DATA {
  using: 'xpath',
  value: '//*[@data-testid="pasteMergeModal.pasteAreaContent"]//h4'
}
2024-01-08T15:32:15.269Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': 'DE5A21BF6B451EC033D86BB2DD70D2DF_element_67'
}
2024-01-08T15:32:15.272Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2024-01-08T15:32:15.273Z INFO webdriver: [POST] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/execute/sync
2024-01-08T15:32:15.273Z INFO webdriver: DATA {
  script: 'isElementDisplayed(...) [8007 bytes]',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': 'DE5A21BF6B451EC033D86BB2DD70D2DF_element_67',
      ELEMENT: 'DE5A21BF6B451EC033D86BB2DD70D2DF_element_67'
    }
  ]
}
2024-01-08T15:32:15.279Z INFO webdriver: RESULT true
2024-01-08T15:32:15.281Z INFO webdriver: COMMAND performActions(<object>)
2024-01-08T15:32:15.282Z INFO webdriver: COMMAND performActions(<object>)
2024-01-08T15:32:15.282Z INFO webdriver: [POST] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/actions
2024-01-08T15:32:15.282Z INFO webdriver: DATA {
  actions: [ { id: 'action8', type: 'key', parameters: {}, actions: [Array] } ]
}
2024-01-08T15:32:15.283Z INFO webdriver: [POST] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/actions
2024-01-08T15:32:15.283Z INFO webdriver: DATA {
  actions: [
    {
      id: 'action9',
      type: 'pointer',
      parameters: [Object],
      actions: [Array]
    }
  ]
}
2024-01-08T15:32:15.301Z INFO webdriver: RESULT null
2024-01-08T15:32:15.302Z INFO webdriver: COMMAND releaseActions()
2024-01-08T15:32:15.302Z INFO webdriver: [DELETE] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/actions
2024-01-08T15:32:15.439Z INFO webdriver: RESULT null
2024-01-08T15:32:15.440Z INFO webdriver: COMMAND releaseActions()
2024-01-08T15:32:15.441Z INFO webdriver: [DELETE] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/actions
2024-01-08T15:32:15.448Z INFO webdriver: RESULT null
2024-01-08T15:32:15.449Z INFO webdriver: COMMAND performActions(<object>)
2024-01-08T15:32:15.450Z INFO webdriver: [POST] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/actions
2024-01-08T15:32:15.450Z INFO webdriver: DATA {
  actions: [ { id: 'action10', type: 'key', parameters: {}, actions: [Array] } ]
}
2024-01-08T15:32:15.463Z INFO webdriver: RESULT null
2024-01-08T15:32:15.477Z INFO webdriver: RESULT null
2024-01-08T15:32:15.477Z INFO webdriver: COMMAND releaseActions()
2024-01-08T15:32:15.478Z INFO webdriver: [DELETE] http://localhost:9515/session/89ba93a001fd7b6034a7c3cf72b7f5a2/actions

**Comment by siddharthsid** [comment]
Hi @christian-bromann - Did you got a chance to look into the above example i have provided? 
Any help here would be appreciated :)

**Comment by christian-bromann** [comment]
Unfortunately not, when things work headful but not headless is it likely an issue outside of the WebdriverIO spectrum and hard to fix on our side. Any investigations why Chrome behaves this way would be appreciated.

**Comment by nair-sumesh** [comment]
> browser.setPermissions

Why do I get `browser.setPermissions is not a function` error.
I am at `8.28.8` version.

**Comment by christian-bromann** [comment]
@nair-sumesh impossible to guess the reason with just the version number, a reproducible example would be more helpful.

**Comment by nair-sumesh** [comment]
Hi @christian-bromann,

I will try to create an example.
Meanwhile what I observed is that in headless mode , the `browser.execute` never reaches the code in promise resolution.
And hence the `navigator.clipboard.writeText(t)` is not being executed.
```
 toCopy: async function (text) {
        await browser.execute((t) => {
          navigator.clipboard.writeText(t);
        }, text);
```
I also tried with `browser.executeAsync`, however here the test waits for ever for the promise to be resolved.

**Comment by nair-sumesh** [comment]
Hi @christian-bromann ,

This is how my browser instance looks like.
![image](https://github.com/webdriverio/webdriverio/assets/12034160/1ddbb163-a6c7-44cb-bd68-78adaf19d86d)

I am using latest ( or almost latest version) of wdio
```
 "@wdio/cucumber-framework": "8.32.2",
    "@wdio/dot-reporter": "8.32.2",
    "@wdio/firefox-profile-service": "8.32.2",
    "@wdio/junit-reporter": "8.32.2",
    "@wdio/local-runner": "8.32.2",
    "@wdio/mocha-framework": "8.32.2",
    "@wdio/spec-reporter": "8.32.2",
    "multiple-cucumber-html-reporter": "3.6.2",
     "wdio-chromedriver-service": "8.1.1",
    "wdio-cucumberjs-json-reporter": "5.2.1",
    "wdio-timeline-reporter": "5.1.4",
    "wdio-ui5-service": "2.0.6",
    "webdriverio": "8.32.2",
```
My project is CommonJS based.

What could be the reason that I don't see `browser.setPermissions` method.

**Comment by christian-bromann** [comment]
> What could be the reason that I don't see `browser.setPermissions` method.

Really hard to tell without a reproducible example, sorry!

**Comment by nair-sumesh** [comment]
Found it .
I had 'goog:chromeOptions'.w3c : false in conf.
Not sure why I added this ( need some investigation)
What's interesting is that with this flag off, `setPermissions` function becomes unavailable.

**Comment by christian-bromann** [comment]
> What's interesting is that with this flag off, `setPermissions` function becomes unavailable.

WebdriverIO defines certain commands based on the protocol they are associated with. The `setPermission` command is a WebDriver protocol command so if you have `w3c` off you use JSON Wire Protocol and the commands defined in our WebDriver protocol document are not applied to the instance. I agree we you that it should say something like: this command is only supported when using WebDriver. Let me raise an issue for this.
