### ISSUE TITLE
An elegant way to assert element not exists in Promise style

### ISSUE THREAD

**Issue by jasonslyvia** [webdriverio/webdriverio#1045]
According to http://webdriver.io/guide/usage/transferpromises.html , it's really amazing and straight-forward to write tests and make assertions.

However, when I want to assert some elements representing error (eg. an `.error-message` element) not exist, the following snippet will throw.

```javascript
client
.click('.ui-tab-head .ui-tab-head-item:nth-child(3)')
.pause(1500)
.element('.ui-loading').should.eventually.not.exist
.element('.error-message').should.eventually.not.exist
.end(done);
```

It throws:

```
     Error: no such element: Unable to locate element: {"method":"css selector","selector":".ui-loading"}
      at new ErrorHandler.RuntimeError (node_modules/webdriverio/lib/utils/ErrorHandler.js:93:12)
      at RequestHandler.<anonymous> (node_modules/webdriverio/lib/utils/RequestHandler.js:138:25)
      at Request.self.callback (node_modules/request/request.js:373:22)
      at Request.<anonymous> (node_modules/request/request.js:1318:14)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1266:12)
      at endReadableNT (_stream_readable.js:905:12)
```

I temporarily switch to use `getHTML()` and assert it doesn't contain such selectors, it just works fine. But still I'm wondering is it possible to make assertions like above?

**Comment by christian-bromann** [comment]
This is not possible. The element command throws an exception if no element can be found. What you could do is to run the `elements` command and check if the result value is empty.
