### ISSUE TITLE
SauceAPI does not work in vs8 with multi remote caps

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#10476]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.10.5

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: {
      browser1: {
        capabilities: {
          browserName: 'chrome'
        }
      },
      browser2: {
        capabilities: {
          browserName: 'chrome'
        }
      }
    },
```

### What happened?

In vs 7 using multi-remote caps with the sauce service running we are able to get the network logs from either endpoint using:

const reqs = await browser1.getPageLogs('sauce:network');

in wdio 8:

2023-05-30T17:50:47.435Z INFO webdriver: COMMAND executeScript("sauce:context=TypeError: browser2.getPageLogs is not a function", <object>)

### What is your expected behavior?

WDIO 8 should support sauceAPI in multi-remote as version 7

### How to reproduce the bug.

use these caps and run a mocha test over sauclabs:

capabilities: {
      browser1: {
        capabilities: {
          browserName: 'chrome'
        }
      },
      browser2: {
        capabilities: {
          browserName: 'chrome'
        }
      }
    },
    
    call  const reqs = await browser1.getPageLogs('sauce:network'); in your test after a page load.

### Relevant log output

```typescript
2023-05-30T17:50:47.435Z INFO webdriver: COMMAND executeScript("sauce:context=TypeError: browser2.getPageLogs is not a function", <object>)
2023-05-30T17:50:47.435Z INFO webdriver: COMMAND executeScript("sauce:context=TypeError: browser2.getPageLogs is not a function", <object>)
2023-05-30T17:50:47.435Z INFO webdriver: COMMAND executeScript("sauce:context=    at Context.<anonymous> (/Users/pmerwin/Projects/Adept/lib-wdio-8-multi-remote-ts/test/specs/forgotpassword/multi.forgot.password.ts:68:38)", <object>)
2023-05-30T17:50:47.435Z INFO webdriver: COMMAND executeScript("sauce:context=    at Context.<anonymous> (/Users/pmerwin/Projects/Adept/lib-wdio-8-multi-remote-ts/test/specs/forgotpassword/multi.forgot.password.ts:68:38)", <object>)
2023-05-30T17:50:47.436Z INFO webdriver: COMMAND executeScript("sauce:context=    at processTicksAndRejections (node:internal/process/task_queues:95:5)", <object>)
2023-05-30T17:50:47.436Z INFO webdriver: COMMAND executeScript("sauce:context=    at processTicksAndRejections (node:internal/process/task_queues:95:5)", <object>)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide the whole wdio logs as well as ideally a reproducible example?

**Comment by pmerwin** [comment]
sauce job for more logs:

https://app.saucelabs.com/tests/c611872a67a648dd8d6156658aae7e24

**Comment by christian-bromann** [comment]
Thanks adding logs!

It seems like the `addCommand` call for adding `getPageLogs` is either not called or not registered properly in the sauce service. Worth taking a look i[n there](https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-sauce-service) first.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by rashiq231** [comment]
@christian-bromann ,
I was looking into this issue, if we add the sauce option : **extendedDebugging: true**, I am able to retrieve logs for multiple remote sessions.

@pmerwin 
Could you please share the config file details, to look into it.
Incase if you need more details, I was referring to [sauce debugging page](https://docs.saucelabs.com/insights/debug/index.html)

**Comment by christian-bromann** [comment]
@rashiq231 thanks for pointing this out. Yes this log type is only available when using Sauce Labs extended debugging services. Closing but happy to answer any question that arise.
