### ISSUE TITLE
[🐛 Bug]: @wdio/logger : ERROR @wdio/runner: Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by xbrys31** [webdriverio/webdriverio#10520]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.10.6

### Node.js Version

16.20

### Mode

WDIO Testrunner

### What happened?

On a new project created with npm init wdio .
with cucumber, page objects, chroedriver, spec reporter, typescript
I add the @wdio/logger as described here : https://www.npmjs.com/package/@wdio/logger?activeTab=readme
and add the following lines in wdio.conf.ts (afterFeature) or in a step

```
import logger from '@wdio/logger'
const log = logger('myPackage')
log.info('some logs')
```

when i run the test, this error is raised
[1-1] 2023-06-06T13:32:01.599Z ERROR @wdio/runner: Error [ERR_REQUIRE_ESM]: require() of ES Module C:\dev\XXX\yyy\node_modules\@wdio\logger\build\index.js from C:\dev\XXX\yyy\features\step-definitions\steps.ts not supported.
[1-1] Instead change the require of index.js in C:\dev\XXX\yyy\features\step-definitions\steps.ts to a dynamic import() which is available in all CommonJS modules.

My tsconfig : 

```
{

    "compilerOptions": {
        "moduleResolution": "node",
        "module": "commonjs",
        "types": [
            "node",
            "@wdio/globals/types",
            "expect-webdriverio",
            "@wdio/cucumber-framework"
        ],
        "target": "es2022",
        "esModuleInterop": true,
    }
}
```

### What is your expected behavior?

No error

### How to reproduce the bug.

create a new project with cucumber, po, spec reporter, typescript
npm install @wdio/logger

add those lines in the steps.ts file 
import logger from '@wdio/logger'

const log = logger('myPackage')
log.info('some logs')

and run the tests 

### Relevant log output

```typescript
[1-1] 2023-06-06T13:32:01.599Z ERROR @wdio/runner: Error [ERR_REQUIRE_ESM]: require() of ES Module C:\dev\XXX\yyy\node_modules\@wdio\logger\build\index.js from C:\dev\XXX\yyy\features\step-definitions\steps.ts not supported.
[1-1] Instead change the require of index.js in C:\dev\XXX\yyy\features\step-definitions\steps.ts to a dynamic import() which is available in all CommonJS modules.
[1-1]     at Object.require.extensions.<computed> [as .js] (C:\dev\XXXX\yyy\node_modules\ts-node\dist\index.js:851:20)
[1-1]     at Function.hookedLoader [as _load] (C:\dev\XXX\yyy\node_modules\mockery\mockery.js:111:12)
[1-1]     at Object.<anonymous> (C:\dev\XXX\yyy\features\step-definitions\steps.ts:8:34)
[1-1]     at Module.m._compile (C:\dev\XXX\yyy\node_modules\ts-node\dist\index.js:857:29)
[1-1]     at Object.require.extensions.<computed> [as .ts] (C:\dev\XXX\yyy\node_modules\ts-node\dist\index.js:859:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by nils-hoyer** [comment]
@christian-bromann 
if you apply both installation guides, you run in the same issue. To me it´s not clear, if: 
a) the wdio documentation for typescript is incomplete: https://webdriver.io/docs/typescript
b) the wdio-logger documentation in invalid: https://www.npmjs.com/package/@wdio/logger?activeTab=readme

**Comment by christian-bromann** [comment]
> the wdio documentation for typescript is incomplete

Incomplete for what use case?

> the wdio-logger documentation in invalid

Maybe the documentation of the v7 logger is invalid because it also uses `import` even though it is a CJS package.

**Comment by nils-hoyer** [comment]
Hi @christian-bromann, 
apologizes for the late response (holiday-related). My assumption was that wdio 8 is not bootstrapping the correct ts config. I double checked and can confirm that I was wrong. As of now everything looks:

```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "ESNext",
    "target": "es2022",
    "types": [
      "node",
      "@wdio/globals/types",
      "expect-webdriverio",
      "@wdio/mocha-framework"
    ]
  }
}
```
