### ISSUE TITLE
[🐛 Bug]: Wrong environment detection, return `isMobile: true` when automating Chrome 

### ISSUE THREAD

**Issue by duy-alex-genetica** [webdriverio/webdriverio#10579]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.11.2

### Node.js Version

18.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  platformName: 'macOS',
  browserName: 'Chromium',
  'appium:options': {
    automationName: 'Chromium',
    autoGrantPermissions: true,
    newCommandTimeout: 300,
    noReset: true,
  },
  'goog:chromeOptions': {
    args: ['window-size=1440,900', 'lang=en'],
  },
}
```

### What happened?

Wrong environment detection when automate with Chromium browsers

After init a session with `remote`, `isMobile` return `true`, which disables some browser-only APIs like `newWindow` or `waitForClickable`

```
const web = await remote(webConfigs);

console.log(web.isMobile) // return true
```

Caused by [this snippet](https://github.com/webdriverio/webdriverio/blob/33aa5aade1047b1a7876c576a44fe30f1a236ae5/packages/wdio-utils/src/envDetector.ts#L4), where `automationName` property is listed as mobile's capabilities while it's required for brower also.

### What is your expected behavior?

`web.isMobile` return false

### How to reproduce the bug.

Create new session with provided `capabilities` and call `newWindow` API

### Relevant log output

```typescript
% node tester.js
{
  isW3C: true,
  isChrome: true,
  isFirefox: false,
  isMobile: true,
  isIOS: false,
  isAndroid: false,
  isSauce: false,
  isSeleniumStandalone: false,
  isBidi: false
}
file:///Users/alexpham/Workspace/_genetica/genetica-user-app/node_modules/webdriverio/build/commands/browser/newWindow.js:53
        throw new Error('newWindow command is not supported on mobile platforms');
              ^

Error: newWindow command is not supported on mobile platforms
    at Browser.newWindow (file:///Users/alexpham/Workspace/_genetica/genetica-user-app/node_modules/webdriverio/build/commands/browser/newWindow.js:53:15)
    at Browser.wrapCommandFn (file:///Users/alexpham/Workspace/_genetica/genetica-user-app/node_modules/@wdio/utils/build/shim.js:72:38)
    at Browser.<anonymous> (file:///Users/alexpham/Workspace/_genetica/genetica-user-app/node_modules/@wdio/utils/build/shim.js:210:24)
    at /Users/alexpham/Workspace/_genetica/genetica-user-app/tester.js:115:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@duy-alex-genetica why did you set Appium capabilities when not running tests on Appium?

**Comment by duy-alex-genetica** [comment]
@christian-bromann
I'm running test with both mobile and browser simultaneously.

I did try running the browser without Appium capabilities.

But it gave me this error, says `automationName` is missing
```
2023-06-13T16:42:38.831Z ERROR webdriver: Request failed with status 400 due to invalid argument: 'automationName' can't be blank
2023-06-13T16:42:38.831Z ERROR webdriver: invalid argument: 'automationName' can't be blank
    at getErrorFromResponseBody (file:///Users/alexpham/Workspace/_genetica/genetica-user-app/node_modules/webdriver/build/utils.js:194:12)
    at NodeJSRequest._request (file:///Users/alexpham/Workspace/_genetica/genetica-user-app/node_modules/webdriver/build/request/index.js:164:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startWebDriverSession (file:///Users/alexpham/Workspace/_genetica/genetica-user-app/node_modules/webdriver/build/utils.js:63:20)
    at async WebDriver.newSession (file:///Users/alexpham/Workspace/_genetica/genetica-user-app/node_modules/webdriver/build/index.js:26:45)
    at async remote (file:///Users/alexpham/Workspace/_genetica/genetica-user-app/node_modules/webdriverio/build/index.js:48:22)
    at async Promise.all (index 0)
    at async /Users/alexpham/Workspace/_genetica/genetica-user-app/tester.js:107:7
file:///Users/alexpham/Workspace/_genetica/genetica-user-app/node_modules/webdriver/build/utils.js:68
        throw new Error('Failed to create session.\n' + message);
              ^

Error: Failed to create session.
'automationName' can't be blank
```

So. i had to add it as Appium capabilities to so it recognizes the driver

**Comment by christian-bromann** [comment]
> I'm running test with both mobile and browser simultaneously.

Make sure you don't apply mobile capabilities to the browser sessions. This can confuse WebdriverIO and the driver.

> invalid argument: 'automationName' can't be blank

Where do you run the tests? If you use Appium this capability needs to be set.

**Comment by christian-bromann** [comment]
Closing due to inactivity. Happy to re-open if a reproducible example can be provided. Thanks!
