### ISSUE TITLE
[🐛 Bug]: Cannot run WDIO Launcher programmatically 

### ISSUE THREAD

**Issue by dukhanov** [webdriverio/webdriverio#10585]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.11.2

### Node.js Version

v18.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

_Default capabilities_

### What happened?

Using Launcher from version 8 does not work as it was before in V7:

![image](https://github.com/webdriverio/webdriverio/assets/11015670/a576abc3-c86b-4df2-8159-8b819d2db373)

### What is your expected behavior?

Installed WDIO from scratch and tried to start runner programmatically from JS:
```
const Launcher = require('@wdio/cli').Launcher

const wdio = new Launcher('./wdio.conf.js')
wdio.run().then(
    () => process.exit(0),
    (e) => { console.warn(e); process.exit(1) }
)
```

And I have an error:
```
TypeError: Cannot read properties of undefined (reading 'run')
    at Launcher.run (/Users/Solutions/playground/wdiocli/node_modules/@wdio/cli/build/cjs/index.js:17:34)
    at Object.<anonymous> (/Users/Solutions/playground/wdiocli/main.js:4:6)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

### How to reproduce the bug.

```
const Launcher = require('@wdio/cli').Launcher

const wdio = new Launcher('./wdio.conf.js')
wdio.run().then(
    () => process.exit(0),
    (e) => { console.warn(e); process.exit(1) }
)
```

### Relevant log output

```typescript
TypeError: Cannot read properties of undefined (reading 'run')
    at Launcher.run (/Users/Solutions/playground/wdiocli/node_modules/@wdio/cli/build/cjs/index.js:17:34)
    at Object.<anonymous> (/Users/Solutions/playground/wdiocli/main.js:4:6)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by dukhanov** [comment]
Yes it might be a solution but running in CJS mode it does not work for sure

**Comment by christian-bromann** [comment]
Raised a draft PR #10607 and will try to finish and land this by end of next week. I recommend though to go with ESM as this is how the ecosystem will move forward.

**Comment by rashiq231** [comment]
@christian-bromann, I tried the above changes in my local,  the program runs, but it is throwing the below error
```shell
SyntaxError: Unexpected token 'export'
``` 
as we are using export const config in wdio.conf.js and removing type: module if we are running this from the same place where our package.json resides. is there anything that we need to update?

**Comment by christian-bromann** [comment]
> . is there anything that we need to update?

Make sure to use CJS syntax (`exports.config = { ... }`) or ESM `export const config = { ... }`. I recommend latter.
