### ISSUE TITLE
[🐛 Bug]: Component tests get timed out.

### ISSUE THREAD

**Issue by NyawiraMuturi** [webdriverio/webdriverio#10669]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
 
        browserName: 'chrome' 
    }],
```

### What happened?

I installed wdio in my react project for unit and component testing. The example component code runs well. However, when I run simple code such as render(<NewComponent/>), the tests time out. I have also trying copying the sample code on an alternative test file. The test also times out. How do I work around this problem? Only the sample test runs

### What is your expected behavior?

I expect that my components are rendered when I call the render method for easier testing.

### How to reproduce the bug.

N/A

### Relevant log output

```typescript
[0-1] 2023-07-04T10:05:59.756Z ERROR @wdio/runner: Failed to run browser tests with cid 0-1: Error: browser test timed out
[0-1]     at file:///home/nyawira/lmsTests/node_modules/webdriverio/build/commands/browser/waitUntil.js:39:23
[0-1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-1]     at Proxy.wrapCommandFn (file:///home/nyawira/lmsTests/node_modules/@wdio/utils/build/shim.js:72:29)
[0-1]     at BrowserFramework.#loop (file:///home/nyawira/lmsTests/node_modules/@wdio/runner/build/browser.js:85:13)
[0-1]     at BrowserFramework.run (file:///home/nyawira/lmsTests/node_modules/@wdio/runner/build/browser.js:39:30)
[0-1]     at Runner.run (file:///home/nyawira/lmsTests/node_modules/@wdio/runner/build/index.js:145:24)
[0-1]  Error:  browser test timed out
[0-1] FAILED in chrome - file:///src/tests/Login.test.jsx
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@NyawiraMuturi thanks for filing the issue. Something must go wrong setting up the test. Can you see any errors in DevTools in the console tab?

**Comment by NyawiraMuturi** [comment]
Yes 
authSlice.js:6 Uncaught (in promise) ReferenceError: require is not defined
    at authSlice.js:6:43

**Comment by christian-bromann** [comment]
It seems like you are using CJS modules and import your components using `require` correct? Mind sharing a minimal reproducible example?

**Comment by NyawiraMuturi** [comment]
I figured where the problem was. Thankyou so much @christian-bromann. I had not factored in all aspects of the component I was importing.

**Comment by christian-bromann** [comment]
Awesome, let me know if there is anything WebdriverIO could do to not have this problem come up in the first place. Will close.
