### ISSUE TITLE
Running `cucumberjs` from the command line results in "ReferenceError: browser is not defined"

### ISSUE THREAD

**Issue by dcypherthis** [webdriverio/webdriverio#1066]
I was having issue with this on my own project, but I'm thinking something is broken at the core here.

When writing cucumber features, it is helpful to run the CLI command to see which steps have been defined and if any of them are broken.  

You can replicate the issue by going  to examples/wdio/runner-specs/cucumber and running `cucumberjs -r step-definitions.js`

It should ouput something like this : 
```
Feature: Example feature
  As a user of webdriverjs
  I should be able to use different commands
  to get informations about elements on the page


  Scenario: Get size of an element                                     # features/my-feature.feature:6
    Given I go on the website "https://github.com/"                    # features/my-feature.feature:7
      ReferenceError: browser is not defined
        at World.<anonymous> (/webdriverio/examples/wdio/runner-specs/cucumber/step-definitions.js:18:9)
        at nextTickCallbackWith0Args (node.js:433:9)
        at process._tickDomainCallback (node.js:403:13)
        at Function.Module.runMain (module.js:432:11)
        at startup (node.js:141:18)
        at node.js:980:3

    When I use getElementSize() on the element ".header-logo-wordmark" # features/my-feature.feature:8
    Then I should get a width of "89" and height of "26"               # features/my-feature.feature:9


  Scenario: Get title of website                                      # features/my-feature.feature:11
    Given I go on the website "https://github.com/"                   # features/my-feature.feature:12
      ReferenceError: browser is not defined
        at World.<anonymous> (/webdriverio/examples/wdio/runner-specs/cucumber/step-definitions.js:18:9)
        at nextTickCallbackWith0Args (node.js:433:9)
        at process._tickDomainCallback (node.js:403:13)
        at Function.Module.runMain (module.js:432:11)
        at startup (node.js:141:18)
        at node.js:980:3

    When I use getTitle() to get the title of this website            # features/my-feature.feature:13
    Then the command should return "GitHub · Where software is built" # features/my-feature.feature:14


(::) failed steps (::)

ReferenceError: browser is not defined
  at World.<anonymous> (/webdriverio/examples/wdio/runner-specs/cucumber/step-definitions.js:18:9)
  at nextTickCallbackWith0Args (node.js:433:9)
  at process._tickDomainCallback (node.js:403:13)
  at Function.Module.runMain (module.js:432:11)
  at startup (node.js:141:18)
  at node.js:980:3


ReferenceError: browser is not defined
  at World.<anonymous> (/webdriverio/examples/wdio/runner-specs/cucumber/step-definitions.js:18:9)
  at nextTickCallbackWith0Args (node.js:433:9)
  at process._tickDomainCallback (node.js:403:13)
  at Function.Module.runMain (module.js:432:11)
  at startup (node.js:141:18)
  at node.js:980:3


Failing scenarios:
features/my-feature.feature:6 # Scenario: Get size of an element
features/my-feature.feature:11 # Scenario: Get title of website

2 scenarios (2 failed)
6 steps (2 failed, 4 skipped)
```

It looks like cucumber is not importing the global browser variable.

**Comment by christian-bromann** [comment]
All files within this directory should get executed by the wdio cli command, see [here](https://github.com/webdriverio/webdriverio/tree/master/examples#wdio)

**Comment by dcypherthis** [comment]
@christian-bromann 
While the WDIO command does run the tests, it does not give you any boilerplate for undefined steps or traceability for incomplete/improperly formatted tests.  This is especially frustrating since a broken test just hangs up the test runner without error.  

Is there a proper way to spit out that information by tweaking the cucumber opts?  I can't locate any documentation specific to it.

**Comment by xbill82** [comment]
+1 to @dcypherthis remark. Not being able to see what makes the runner hang is very frustrating. I'm currently traversing the issues to see if this problem has been raised already and if there is a solution.
It would be just awesome to see the error with the stack.

**Comment by dcypherthis** [comment]
@xbill82 I'm still having the same issues, 20 days later and haven't found a work around.  If you find something let me know.

**Comment by xbill82** [comment]
@dcypherthis found this https://github.com/webdriverio/webdriverio/issues/888
