### ISSUE TITLE
[🐛 Bug]: browser.keys command cause "Timeout awaiting 'response' for 10000ms when running "actions" with method "DELETE"" error for Edge on Saucelabs

### ISSUE THREAD

**Issue by idem7x** [webdriverio/webdriverio#10711]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.11.2

### Node.js Version

18.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        user: "",
        key: "",
        hostname: 'ondemand.eu-central-1.saucelabs.com',
        services: ["sauce"],
        capabilities: [{
            browserName: "MicrosoftEdge",
            browserVersion: "latest",
            platformName: "Windows 10"
        }]
    }
```

### What happened?

browser.keys command cause next error - " Request timed out! Consider increasing the "connectionRetryTimeout" option". It happens for Edge browser, but works as expected for Chrome. Also I use sauce service to run my tests. 

### What is your expected behavior?

browser.keys should work as expected. 

### How to reproduce the bug.

To reproduce bug you can clone this repo - https://github.com/idem7x/wdiosauce.git.
Then do next: 
- npm install
- setup user, key and region for Saucelabs in [wdio.sauce.edge.ts](https://github.com/idem7x/wdiosauce/blob/main/wdio.sauce.edge.ts)
- npm run test:sauceedge

### Relevant log output

```typescript
> wdiosauce@1.0.0 test:sauceedge
> npx wdio run ./wdio.sauce.edge.ts --suite key


Execution of 1 workers started at 2023-07-10T13:12:36.444Z

2023-07-10T13:12:36.541Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-07-10T13:12:36.543Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-07-10T13:12:36.543Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.sauce.edge.ts,--suite,key
[0-0] 2023-07-10T13:12:36.918Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in MicrosoftEdge - file:///test/specs/scroll.e2e.ts
[0-0] 2023-07-10T13:12:37.078Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-07-10T13:12:37.121Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session
[0-0] 2023-07-10T13:12:37.121Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'MicrosoftEdge',
[0-0]       browserVersion: 'latest',
[0-0]       platformName: 'Windows 10'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'MicrosoftEdge',
[0-0]     browserVersion: 'latest',
[0-0]     platformName: 'Windows 10'
[0-0]   }
[0-0] }
[0-0] 2023-07-10T13:12:47.232Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2023-07-10T13:12:47.232Z INFO webdriver: Retrying 1/3
[0-0] 2023-07-10T13:12:47.232Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session
[0-0] 2023-07-10T13:12:47.232Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'MicrosoftEdge',
[0-0]       browserVersion: 'latest',
[0-0]       platformName: 'Windows 10'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'MicrosoftEdge',
[0-0]     browserVersion: 'latest',
[0-0]     platformName: 'Windows 10'
[0-0]   }
[0-0] }
[0-0] 2023-07-10T13:12:56.784Z INFO webdriver: COMMAND executeScript("sauce:job-name=Scroll Scrol", <object>)
[0-0] 2023-07-10T13:12:56.784Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/execute/sync
[0-0] 2023-07-10T13:12:56.785Z INFO webdriver: DATA { script: 'sauce:job-name=Scroll Scrol', args: [] }
[0-0] 2023-07-10T13:12:56.898Z INFO webdriver: RESULT 
[0-0] 2023-07-10T13:12:56.899Z INFO webdriver: COMMAND executeScript("sauce:context=Scroll Scroll", <object>)
[0-0] 2023-07-10T13:12:56.899Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/execute/sync
[0-0] 2023-07-10T13:12:56.900Z INFO webdriver: DATA { script: 'sauce:context=Scroll Scroll', args: [] }
[0-0] 2023-07-10T13:12:56.977Z INFO webdriver: RESULT 
[0-0] 2023-07-10T13:12:56.978Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/key_presses")
[0-0] 2023-07-10T13:12:56.979Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/url
[0-0] 2023-07-10T13:12:56.979Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/key_presses' }
[0-0] 2023-07-10T13:12:59.130Z INFO webdriver: RESULT null
[0-0] 2023-07-10T13:12:59.133Z INFO webdriver: COMMAND findElement("css selector", "#target")
[0-0] 2023-07-10T13:12:59.134Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/element
[0-0] 2023-07-10T13:12:59.134Z INFO webdriver: DATA { using: 'css selector', value: '#target' }
[0-0] 2023-07-10T13:12:59.229Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '22EDF843F595689583933E6556DFA4F3_element_3'
[0-0] }
[0-0] 2023-07-10T13:12:59.238Z INFO webdriver: COMMAND elementClick("22EDF843F595689583933E6556DFA4F3_element_3")
[0-0] 2023-07-10T13:12:59.238Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/element/22EDF843F595689583933E6556DFA4F3_element_3/click
[0-0] 2023-07-10T13:12:59.643Z INFO webdriver: RESULT null
[0-0] 2023-07-10T13:12:59.645Z INFO webdriver: COMMAND performActions(<object>)
[0-0] 2023-07-10T13:12:59.645Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/actions
[0-0] 2023-07-10T13:12:59.646Z INFO webdriver: DATA {
[0-0]   actions: [ { id: 'action1', type: 'key', parameters: {}, actions: [Array] } ]
[0-0] }
[0-0] 2023-07-10T13:12:59.754Z INFO webdriver: RESULT null
[0-0] 2023-07-10T13:12:59.754Z INFO webdriver: COMMAND releaseActions()
[0-0] 2023-07-10T13:12:59.755Z INFO webdriver: [DELETE] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/actions
[0-0] 2023-07-10T13:13:47.295Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2023-07-10T13:13:47.296Z INFO webdriver: Retrying 1/3
[0-0] 2023-07-10T13:13:47.296Z INFO webdriver: [DELETE] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/actions
[0-0] 2023-07-10T13:14:34.875Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2023-07-10T13:14:34.875Z INFO webdriver: Retrying 2/3
[0-0] 2023-07-10T13:14:34.875Z INFO webdriver: [DELETE] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/actions
[0-0] 2023-07-10T13:15:22.419Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2023-07-10T13:15:22.419Z INFO webdriver: Retrying 3/3
[0-0] 2023-07-10T13:15:22.419Z INFO webdriver: [DELETE] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/actions
[0-0] 2023-07-10T13:16:09.992Z ERROR webdriver: Request failed with status undefined due to TimeoutError: Timeout awaiting 'response' for 10000ms when running "actions" with method "DELETE"
[0-0] 2023-07-10T13:16:10.007Z INFO webdriver: COMMAND executeScript("sauce:context=    at processTicksAndRejections (node:internal/process/task_queues:95:5)", <object>)
[0-0] 2023-07-10T13:16:10.008Z INFO webdriver: COMMAND executeScript("sauce:context=    at async KeyPressesPage.keys (/Users/dem7x/WebstormProjects/wdiosauce/test/pageobjects/key.presses.page.ts:23:9)", <object>)
[0-0] 2023-07-10T13:16:10.008Z INFO webdriver: COMMAND executeScript("sauce:context=    at async UserContext.<anonymous> (/Users/dem7x/WebstormProjects/wdiosauce/test/specs/scroll.e2e.ts:8:9)", <object>)
[0-0] 2023-07-10T13:16:10.009Z INFO webdriver: COMMAND executeScript("sauce:context=TimeoutError: Timeout awaiting 'response' for 10000ms when running "actions" with method "DELETE"", <object>)
[0-0] Error in "Scroll Scroll"
error properties: Object({ input: undefined, code: 'ETIMEDOUT', timings: Object({ start: 1688994959878, socket: 1688994959878, lookup: 1688994959879, connect: 1688994959932, secureConnect: 1688994959987, upload: 1688994959987, response: undefined, end: undefined, error: 1688994969990, abort: undefined, phases: Object({ wait: 0, dns: 1, tcp: 53, tls: 55, request: 0, firstByte: undefined, download: undefined, total: 10112 }) }), options: Options({ _unixOptions: undefined, _internals: Object({ request: undefined, agent: Object({ http: Agent({ _events: null({ free: Function, newListener: Function }), _eventsCount: 2, _maxListeners: undefined, defaultPort: 80, protocol: 'http:', options: null({ keepAlive: true, noDelay: true, path: null }), requests: null({  }), sockets: null({  }), freeSockets: null({  }), keepAliveMsecs: 1000, keepAlive: true, maxSockets: Infinity, maxFreeSockets: 256, scheduling: 'lifo', maxTotalSockets: Infinity, totalSocketCount: 0, Symbol(kCapture): false }), https: Agent({ _events:  ...
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async KeyPressesPage.keys (/Users/dem7x/WebstormProjects/wdiosauce/test/pageobjects/key.presses.page.ts:23:9)
    at async UserContext.<anonymous> (/Users/dem7x/WebstormProjects/wdiosauce/test/specs/scroll.e2e.ts:8:9)
[0-0] 2023-07-10T13:16:10.021Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/execute/sync
[0-0] 2023-07-10T13:16:10.021Z INFO webdriver: DATA {
[0-0]   script: 'sauce:context=    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
[0-0]   args: []
[0-0] }
[0-0] 2023-07-10T13:16:10.023Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/execute/sync
[0-0] 2023-07-10T13:16:10.023Z INFO webdriver: DATA {
[0-0]   script: 'sauce:context=    at async KeyPressesPage.keys (/Users/dem7x/WebstormProjects/wdiosauce/test/pageobjects/key.presses.page.ts:23:9)',
[0-0]   args: []
[0-0] }
[0-0] 2023-07-10T13:16:10.024Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/execute/sync
[0-0] 2023-07-10T13:16:10.024Z INFO webdriver: DATA {
[0-0]   script: 'sauce:context=    at async UserContext.<anonymous> (/Users/dem7x/WebstormProjects/wdiosauce/test/specs/scroll.e2e.ts:8:9)',
[0-0]   args: []
[0-0] }
[0-0] 2023-07-10T13:16:10.035Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315/execute/sync
[0-0] 2023-07-10T13:16:10.035Z INFO webdriver: DATA {
[0-0]   script: `sauce:context=TimeoutError: Timeout awaiting 'response' for 10000ms when running "actions" with method "DELETE"`,
[0-0]   args: []
[0-0] }
[0-0] 2023-07-10T13:16:10.041Z INFO @wdio/sauce-service: Update job with sessionId 48e1239a28364b54a168de3cea730315, status: failing
[0-0] 2023-07-10T13:16:10.214Z INFO webdriver: RESULT 
[0-0] 2023-07-10T13:16:11.180Z INFO webdriver: RESULT 
[0-0] 2023-07-10T13:16:11.206Z INFO webdriver: RESULT 
[0-0] 2023-07-10T13:16:11.208Z INFO webdriver: RESULT 
[0-0] 2023-07-10T13:16:13.647Z ERROR @wdio/utils:shim: Error: Failed calling updateJob: Response code 404 (Not Found), Not found
[0-0]     at SauceLabs._callAPI (/Users/dem7x/WebstormProjects/wdiosauce/node_modules/saucelabs/build/index.js:577:13)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async SauceService.updateJob (file:///Users/dem7x/WebstormProjects/wdiosauce/node_modules/@wdio/sauce-service/build/service.js:269:9)
[0-0]     at async Promise.all (index 0)
[0-0]     at async executeHooksWithArgsShim (file:///Users/dem7x/WebstormProjects/wdiosauce/node_modules/@wdio/utils/build/shim.js:50:20)
[0-0]     at async JasmineAdapter.run (file:///Users/dem7x/WebstormProjects/wdiosauce/node_modules/@wdio/jasmine-framework/build/index.js:208:9)
[0-0]     at async Runner.run (file:///Users/dem7x/WebstormProjects/wdiosauce/node_modules/@wdio/runner/build/index.js:145:24)
[0-0] 2023-07-10T13:16:13.648Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-07-10T13:16:13.649Z INFO webdriver: [DELETE] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/48e1239a28364b54a168de3cea730315
[0-0] 2023-07-10T13:16:13.830Z INFO webdriver: RESULT 
[0-0] FAILED in MicrosoftEdge - file:///test/specs/scroll.e2e.ts
2023-07-10T13:16:13.955Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-07-10T13:16:13.956Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[msedge 113.0.1774.35 Windows 10 #0-0] Running: msedge (v113.0.1774.35) on Windows 10
[msedge 113.0.1774.35 Windows 10 #0-0] Session ID: 48e1239a28364b54a168de3cea730315
[msedge 113.0.1774.35 Windows 10 #0-0]
[msedge 113.0.1774.35 Windows 10 #0-0] » /test/specs/scroll.e2e.ts
[msedge 113.0.1774.35 Windows 10 #0-0] Scroll
[msedge 113.0.1774.35 Windows 10 #0-0]    ✖ Scroll
[msedge 113.0.1774.35 Windows 10 #0-0]
[msedge 113.0.1774.35 Windows 10 #0-0] 1 failing (3m 17s)
[msedge 113.0.1774.35 Windows 10 #0-0]
[msedge 113.0.1774.35 Windows 10 #0-0] 1) Scroll Scroll
[msedge 113.0.1774.35 Windows 10 #0-0] TimeoutError: Timeout awaiting 'response' for 10000ms when running "actions" with method "DELETE"
[msedge 113.0.1774.35 Windows 10 #0-0] error properties: Object({ input: undefined, code: 'ETIMEDOUT', timings: Object({ start: 1688994959878, socket: 1688994959878, lookup: 1688994959879, connect: 1688994959932, secureConnect: 1688994959987, upload: 1688994959987, response: undefined, end: undefined, error: 1688994969990, abort: undefined, phases: Object({ wait: 0, dns: 1, tcp: 53, tls: 55, request: 0, firstByte: undefined, download: undefined, total: 10112 }) }), options: Options({ _unixOptions: undefined, _internals: Object({ request: undefined, agent: Object({ http: Agent({ _events: null({ free: Function, newListener: Function }), _eventsCount: 2, _maxListeners: undefined, defaultPort: 80, protocol: 'http:', options: null({ keepAlive: true, noDelay: true, path: null }), requests: null({  }), sockets: null({  }), freeSockets: null({  }), keepAliveMsecs: 1000, keepAlive: true, maxSockets: Infinity, maxFreeSockets: 256, scheduling: 'lifo', maxTotalSockets: Infinity, totalSocketCount: 0, Symbol(kCapture): false }), https: Agent({ _events:  ...
[msedge 113.0.1774.35 Windows 10 #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[msedge 113.0.1774.35 Windows 10 #0-0]     at async KeyPressesPage.keys (/Users/dem7x/WebstormProjects/wdiosauce/test/pageobjects/key.presses.page.ts:23:9)
[msedge 113.0.1774.35 Windows 10 #0-0]     at async UserContext.<anonymous> (/Users/dem7x/WebstormProjects/wdiosauce/test/specs/scroll.e2e.ts:8:9)
[msedge 113.0.1774.35 Windows 10 #0-0]
[msedge 113.0.1774.35 Windows 10 #0-0] Check out job at https://app.eu-central-1.saucelabs.com/tests/48e1239a28364b54a168de3cea730315?auth=ee1c4a08ac9e0f80dade135c6ad6d0b8


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:03:37 

2023-07-10T13:16:13.961Z INFO @wdio/local-runner: Shutting down spawned worker
2023-07-10T13:16:14.214Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-07-10T13:16:14.216Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
See error message in logs:

> Request timed out! Consider increasing the "connectionRetryTimeout" option.

Here are some docs around this option: https://webdriver.io/docs/configuration#connectionretrytimeout
