### ISSUE TITLE
Error: Cannot generate spec hash for runner with no 'specs' key

### ISSUE THREAD

**Issue by justinIs** [webdriverio/webdriverio#1073]
From the [install page](http://webdriver.io/guide/getstarted/install.html) I was able to install webdriverio, and selenium-standalone.

I'm using node v5.0. Using the command `wdio config`, I selected Jasmine and dot, however the installer was unable to successfully instal wdio-jasmine-framework (when I ran wdio wdio.config.js I got an error saying the dependency was not found), so I manually installed it globally, then did the same for dot.

Now when I try to run: wdio wdio.conf.js I get:

```
Error: Cannot generate spec hash for runner with no 'specs' key
    at Error (native)
    at ReporterStats.getSpecHash (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:212:42)
    at ReporterStats.getSpecStats (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:227:33)
    at ReporterStats.suiteStart (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:239:18)
    at BaseReporter.<anonymous> (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/utils/BaseReporter.js:134:25)
    at emitOne (events.js:77:13)
    at BaseReporter.emit (events.js:169:7)
    at BaseReporter.handleEvent (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/utils/BaseReporter.js:326:27)
    at Launcher.messageHandler (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/webdriverio/build/lib/launcher.js:469:28)
    at emitTwo (events.js:87:13)
```

And then after a while:

```
/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/wdio-jasmine-framework/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:324
    var expectationResult = this.expectationResultFactory(data);
                                 ^

TypeError: this.expectationResultFactory is not a function
    at JasmineAdapter.Spec.addExpectationResult (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/wdio-jasmine-framework/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:324:34)
    at Spec.addExpectationResult (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/wdio-jasmine-framework/build/adapter.js:408:36)
    at Spec.onException (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/wdio-jasmine-framework/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:380:10)
    at QueueRunner.queueRunnerFactory.onException (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/wdio-jasmine-framework/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:355:50)
    at onException (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/wdio-jasmine-framework/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1827:12)
    at null._onTimeout (/Users/justin.williams/.nvm/versions/node/v5.0.0/lib/node_modules/wdio-jasmine-framework/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1813:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

I'm using chrome as my browser as I can't get past the "firstrun" page for firefox. I've tried this multiple times with no success. I haven't touched the config file other than changing the browser to chrome.
I was able to run a simple test with webdriverio:
```
var webdriverio = require('webdriverio');
var options = {
  desiredCapabilities: {
    browserName: 'chrome'
  }
};

webdriverio
  .remote(options)
  .init()
  .url('http://www.google.com')
  .title(function(err, res) {
    console.log('Title was: ' + res.value);
  })
  .end();
```

**Comment by christian-bromann** [comment]
If you are using wdio, you shouldn't create a selenium session like this. wdio does that for you. Please check out the examples https://github.com/webdriverio/webdriverio/tree/master/examples/wdio

**Comment by justinIs** [comment]
Thanks for the super quick response! 

I'm not sure what you mean by creating a selenium session...
I've used wdio to create my config file, then I use selenium-standalone (is this what you're talking about?) as my selenium server and run `wdio wdio.config.js`

My config file looks pretty similar to [the example jasmine config](https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/wdio.jasmine.conf.js) and I tried running the wdio binary straight from the install path, without having selenium-standalone running I get `ERROR: Couldn't connect to selenium server`

**Comment by christian-bromann** [comment]
So webdriverio can be used in two different ways:
1. as a standalone package, where you have to initialise the selenium session by yourself and integrate it into the test framework you want to use. Example: https://github.com/webdriverio/webdriverio/blob/master/examples/standalone/webdriverio.with.mocha.js

2. using the wdio test runner. The wdio test runner helps you to run more sufficient test suites in parallel and it takes care of important issues like initialising and ending the session for you. In this case you have a config file like this: https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/wdio.jasmine.conf.js and multiple spec files like this where you just use the global `browser` variable to run commands, example: https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/runner-specs/jasmine.spec.js
(these examples require webdriverio v4)

**Comment by justinIs** [comment]
I'd like to go with the wdio test runner.

Here's my config file `wdio wdio.config.js`:
```
exports.config = {
    
    specs: [
        './test/integration/specs/**/*.js'
    ],
    exclude: [
    ],
    capabilities: [{
        browserName: 'chrome'
    }],
    logLevel: 'verbose',
    coloredLogs: true,
    screenshotPath: './test/integration/errorShots',
    waitforTimeout: 20000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: 'jasmine',
    reporters: ['dot'],
    reporterOptions: {
      outputDir: './test/integration/dotReport'
    },
    
    jasmineNodeOpts: {
        defaultTimeoutInterval: 10000,
        expectationResultHandler: function(passed, assertion) {
        }
    },
    
}
```
and here's my one spec so far `./test/integration/specs/landingPage.js`:
```
describe('landing page', function () {
  it('should have the right title', function (done) {
    client
      .url('/')
      .getTitle().then(function (title) {
      expect(title).toBe('Free texting and calling');
      done();
    });
  });
});

```

I then run `wdio wdio.config.js` and I get the error mentioned above (if the standalone server is running).
With the standalone selenium server off I get an error saying "ERROR: Couldn't connect to selenium server".

I've tried downloading the full repo and attempting to run the wdio.jasmine.conf.js in the examples/wdio directory, and experiencing the same results.

**Comment by christian-bromann** [comment]
Which version are you using?

**Comment by justinIs** [comment]
Using wdio version 4.0.2

**Comment by christian-bromann** [comment]
Ok, sorry for the trouble, we just released v4 and we haven't updated the page. So apparently there is a bug in the jasmine framework adapter which I will fix asap. Please switch over to cucumber or mocha. Here is an mocha example you can use:

__wdio.conf.js__
```js
exports.config = {
    specs: [
        './test.js'
    ],
    capabilities: [{
        browserName: 'phantomjs'
    }],
    logLevel: 'silent',
    coloredLogs: true,
    screenshotPath: './errorShots/',
    baseUrl: 'http://google.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: 'mocha',
    reporters: ['dot'],
    mochaOpts: {
        timeout: 10000
    }
}
```
__test.js__
```js
describe('landing page', function () {
  it('should have the right title', function (done) {
    browser.url('/')
    console.log(browser.getTitle());
  });
});
```
As you can see all commands are now running synchronously, so no then no promises ;-). I recommend to check out our page object example: https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject

**Comment by rbose85** [comment]
@christian-bromann, thanks for the excellent answer. I'm seeing the same issue, but I'm not using Jasmine specs. I'm working with CucumberJS and `.feature` files. Am I missing something obvious?


```javascript
const config = {
  specs: [
    'test/e2e/features/*.feature'
  ],
  capabilities: [{
    browserName: 'chrome'
  }],
  logLevel: 'verbose',
  coloredLogs: true,
  baseUrl: 'http://localhost:8080',
  framework: 'cucumber',
  reporter: 'dot',
  reporterOptions: {
    outputDir: 'test/e2e/reports/'
  },
  cucumberOpts: {
    require: [
      'test/e2e/features/step_definitions/given.js',
      'test/e2e/features/step_definitions/then.js',
      'test/e2e/features/step_definitions/when.js'
    ]
  }
}

// test if running on CircleCI
if (process.env.CI) {
  config.screenshotPath = process.env.CIRCLE_ARTIFACTS
  config.reporterOptions.outputDir = process.env.CIRCLE_TEST_REPORTS
  config.reporter = 'xunit'
}

exports.config = config
```

**Comment by christian-bromann** [comment]
@rbose85 I had trouble getting cucumber tests running yesterday so the adapter might be borked. I will try fixing that asap

**Comment by teneightfive** [comment]
Hi. I've just tried to update from webdriverio v3 to v4 and upgrade cucumber from v5 to v9 and am having a similar issue. Is this something to do with [wdio-cucumber-framework](https://github.com/webdriverio/wdio-cucumber-framework)?

**Comment by christian-bromann** [comment]
@teneightfive haven't got the chance to look into it

**Comment by teneightfive** [comment]
Ok, no worries. Will park upgrading for now. Wasn't sure if it was an issue with my config/setup, but if it might be down to the lib not being ready yet I can park it/take a look if I get time.

**Comment by AndyOGo** [comment]
I have the same issue with jasmine since upgrading

**Comment by mohindroo83** [comment]
Hi I am getting the below error when i try to run my tests.
․/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:246
            if (!specStats.suites[suiteTitle]) throw Error('Unrecognised suite [' + suiteTitle + '] for runner [' + specStats.specHash + ']');
                                               ^

Error: Unrecognised suite [] for runner [1971963139046c929f367a5eed8d4031]
    at Error (native)
    at ReporterStats.getSuiteStats (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:246:54)
    at ReporterStats.testStart (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:252:18)
    at ReporterStats.testFail (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:306:22)
    at BaseReporter.<anonymous> (/usr/local/lib/node_modules/webdriverio/build/lib/utils/BaseReporter.js:146:25)
    at emitOne (events.js:90:13)
    at BaseReporter.emit (events.js:182:7)
    at BaseReporter.handleEvent (/usr/local/lib/node_modules/webdriverio/build/lib/utils/BaseReporter.js:326:27)
    at Launcher.messageHandler (/usr/local/lib/node_modules/webdriverio/build/lib/launcher.js:469:28)
    at emitTwo (events.js:100:13)

I am using webdriverio version 4.0.3. Any ideas of how to fix this ?

**Comment by Harsha509** [comment]
HI am getting this error when i try to run the tests 
wdio version : 4.0.3, framework:jasmine

C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\ReporterStats.js:212
                if (!runner.specs) throw Error('Cannot generate spec hash for runner with no \'specs\' key');
                                   ^
Error: Cannot generate spec hash for runner with no 'specs' key
    at Error (native)
    at ReporterStats.getSpecHash (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\ReporterSt
ats.js:212:42)
    at ReporterStats.getSpecStats (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\ReporterS
tats.js:227:33)
    at ReporterStats.suiteStart (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\ReporterSta
ts.js:239:18)
    at BaseReporter.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\BaseReporte
r.js:134:25)
    at emitOne (events.js:77:13)
    at BaseReporter.emit (events.js:169:7)
    at BaseReporter.handleEvent (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\BaseReporte
r.js:326:27)
    at Launcher.messageHandler (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:469:28
)
    at emitTwo (events.js:87:13)

**Comment by dgasi** [comment]
hi Guys,

I managed to get rid of the error with downgrading wdio from 4.0.3 to 3.4.0.

BR.

**Comment by christian-bromann** [comment]
This is fixed with the latest `wdio-jasmine-framework` release

**Comment by dcosson** [comment]
@christian-bromann The `wdio config` bootstrap command still causes this error on the latest `wdio-jasmine-framework` 0.1.7 because it still creates an empty `expectationResultHandler` method, I had to delete it out of the config file.

And what's the new way to e.g. save a screenshot on a failure now that this method is broken?

**Comment by christian-bromann** [comment]
In v4 you can use the `onError` hook for that.

I will take a look into the `expectationResultHandler` config property. Thanks!

**Comment by dcosson** [comment]
Cool, I'll look into that.

**Comment by rajivsavroop** [comment]
Hi, 
Why can't I use 'done()' with wdio-jasmine-framework, keeps throwing err 'TypeError: done is not a function '
/node_modules/wdio-jasmine-framework/node_modules/wdio-sync/build/index.js:579:24

**Comment by christian-bromann** [comment]
@rajivsavroop why want you use `done`? All commands run synchronous anyway.

**Comment by rajivsavroop** [comment]
@christian-bromann I wanted to use  ```done``` for my asynchronous specs.If I don't call ```done`` for async specs in standard jasmine they would fail be because of async timeout.

**Comment by christian-bromann** [comment]
then please use proper promise syntax. `done` is not the proper way to resolve async commands.
