### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by avaranovich** [webdriverio/webdriverio#108]
I am getting such warning while running mocha tests.

```
[16:19:53][Step 3/3] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
[16:19:53][Step 3/3] Trace
[16:19:53][Step 3/3]     at process.EventEmitter.addListener (events.js:167:15)
[16:19:53][Step 3/3]     at process.on.process.addListener (node.js:881:26)
[16:19:53][Step 3/3]     at /work/b81f7e7d29006fd9/test/browser/node_modules/webdriverjs/lib/utils/QueueItem.js:31:25
[16:19:53][Step 3/3]     at null.<anonymous> (/work/b81f7e7d29006fd9/test/browser/node_modules/webdriverjs/lib/commands/end.js:6:13)
[16:19:53][Step 3/3]     at /work/b81f7e7d29006fd9/test/browser/node_modules/webdriverjs/lib/utils/QueueItem.js:34:24
[16:19:53][Step 3/3]     at /work/b81f7e7d29006fd9/test/browser/node_modules/webdriverjs/lib/protocol/session.js:47:21
[16:19:53][Step 3/3]     at null.<anonymous> (/work/b81f7e7d29006fd9/test/browser/node_modules/webdriverjs/lib/utils/RequestHandler.js:229:25)
[16:19:53][Step 3/3]     at IncomingMessage.EventEmitter.emit (events.js:120:20)
[16:19:53][Step 3/3]     at _stream_readable.js:896:16
[16:19:53][Step 3/3]     at process._tickCallback (node.js:598:11)
```

There are many related discussion about this memory leak, but I am wondering what is the right way to address it in requirejs and if this might be a bug.

**Comment by ckurban** [comment]
This issue seems to be still exist. I am using WDIO 4.12.0. 

```
/Users/xxxxx/dev/xxxxx/node_modules/webdriverio/build/lib/utils/BaseReporter.js:336
                        throw _iteratorError;
                        ^

TypeError: Cannot read property 'trim' of undefined
    at getTestStatus (/Users/xxxxx/dev/xxxxx/node_modules/wdio-allure-reporter/build/utils.js:31:41)
    at AllureReporter.testFail (/Users/xxxxx/dev/xxxxx/node_modules/wdio-allure-reporter/build/reporter.js:175:51)
    at emitOne (events.js:116:13)
    at AllureReporter.emit (events.js:211:7)
    at BaseReporter.handleEvent (/Users/xxxxx/dev/xxxxx/node_modules/webdriverio/build/lib/utils/BaseReporter.js:324:35)
    at Launcher.messageHandler (/Users/xxxxx/dev/xxxxx/node_modules/webdriverio/build/lib/launcher.js:688:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:762:12)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxxxx@0.0.1 devsk: `npm run removeReports && wdio test/config/env/dev/opCo/sk/devSK.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xxxxx@0.0.1 devsk script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxx/.npm/_logs/2018-10-09T09_13_50_399Z-debug.log
➜  xxxxx git:(develop) ✗ events.js:183
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:578:16)
    at CucumberReporter.send (/Users/xxxxx/dev/xxxxx/node_modules/wdio-cucumber-framework/build/reporter.js:284:28)
    at CucumberReporter.emit (/Users/xxxxx/dev/xxxxx/node_modules/wdio-cucumber-framework/build/reporter.js:279:18)
    at CucumberReporter.handleStepResultEvent (/Users/xxxxx/dev/xxxxx/node_modules/wdio-cucumber-framework/build/reporter.js:221:18)
    at Object.hear (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/listener.js:6:9)
    at iterator (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:176:20)
    at iterate (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/util/async_for_each.js:7:7)
    at Object.asyncForEach (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/util/async_for_each.js:15:3)
    at broadcastToListeners (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:178:23)
    at Object.broadcastEvent (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:186:7)
    at Object.visitStepResult (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:144:12)
    at /Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/runtime/ast_tree_walker.js:264:14
    at finish (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/support_code/step_definition.js:92:9)
    at process.finish (/Users/xxxxx/dev/xxxxx/node_modules/cucumber/lib/cucumber/util/run.js:13:5)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)
```

**Comment by BorisOsipov** [comment]
@ckurban it is another issue related to wdio-allure-reporter

Please, file issue in https://github.com/webdriverio-boneyard/wdio-allure-reporter/issues

**Comment by ckurban** [comment]
@BorisOsipov it is not stable. Upgrading might be tricky as it might/will change the structure of the Step Definitions which means I would need to apply major refactoring on all my scenarios but i will have it a go and see whats the outcome.
