### ISSUE TITLE
[🐛 Bug]: create-wdio automatically installs nuxt service, then fails with error

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#10811]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16

### Mode

WDIO Testrunner

### What happened?

using the latest version of the create-wdio package I have instantiated a new project which, when run, fails on the following error: `Cannot find any nuxt version`

### What is your expected behavior?

If the nuxt service is not required, I do not expect it to automatically be installed.
If it is installed however, I expect it to work without errors.

### How to reproduce the bug.

instantiate a new project using the create-wdio package like so: npm init wdio ./foo
accept all defaults

### Relevant log output

```typescript
2023-07-28T12:32:08.612Z ERROR wdio-nuxt-service: Cannot start nuxt: Error: Cannot find any nuxt version from /Users/erwin/Documents/Development/Personal/foo
    at loadNuxt (file:///Users/erwin/Documents/Development/Personal/foo/node_modules/@nuxt/kit/dist/index.mjs:2530:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (file:///Users/erwin/Documents/Development/Personal/foo/node_modules/wdio-nuxt-service/dist/launcher.js:90:100)
    at async NuxtServiceLauncher.onPrepare (file:///Users/erwin/Documents/Development/Personal/foo/node_modules/wdio-nuxt-service/dist/launcher.js:184:9)
    at async file:///Users/erwin/Documents/Development/Personal/foo/node_modules/@wdio/cli/build/utils.js:43:17
    at async Promise.all (index 1)
    at async Launcher.run (file:///Users/erwin/Documents/Development/Personal/foo/node_modules/@wdio/cli/build/launcher.js:82:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting @erwinheitzman , I pushed a fix for this. There is an open issue for creating an e2e test suite for the wizard that I am unfortunately haven't had a chance to take a look at.
