### ISSUE TITLE
[🐛 Bug]: wdio types now throw an error for the config

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#10812]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16

### Mode

WDIO Testrunner

### What happened?

Given I instantiate a new project with typescript using the create-wdio package.
When I run the tests.
Then I get errors.

### What is your expected behavior?

I expect no errors from a newly created project using our own cli wizard / create-wdio package.

### How to reproduce the bug.

using the latest version of the create-wdio package instantiate a new project with typescript as a selected option.
then run the tests.

### Relevant log output

```typescript
2023-07-28T12:28:31.643Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/erwin/Documents/Development/Personal/foo/wdio.conf.ts: ⨯ Unable to compile TypeScript:
wdio.conf.ts:147:44 - error TS6133: 'passed' is declared but its value is never read.

147         expectationResultHandler: function(passed, assertion) {
                                               ~~~~~~
wdio.conf.ts:147:52 - error TS6133: 'assertion' is declared but its value is never read.

147         expectationResultHandler: function(passed, assertion) {
                                                       ~~~~~~~~~

wdio.conf.ts:147:44 - error TS6133: 'passed' is declared but its value is never read.

147         expectationResultHandler: function(passed, assertion) {
                                               ~~~~~~
wdio.conf.ts:147:52 - error TS6133: 'assertion' is declared but its value is never read.

147         expectationResultHandler: function(passed, assertion) {
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
Could we add a smoke test that instantiates some projects using the create-wdio package and then runs the tests?
I think this would greatly reduce the number of issues when making changes.

**Comment by erwinheitzman** [comment]
Perhaps a simple workaround could be to add an underscore so that Typescript does not complain about these arguments not being used.

**Comment by christian-bromann** [comment]
@erwinheitzman what do you suggest?

**Comment by erwinheitzman** [comment]
I personally have a gut feeling that it is related to https://github.com/webdriverio/webdriverio/issues/10723

**Comment by christian-bromann** [comment]
@erwinheitzman we recently landed https://github.com/webdriverio/webdriverio/pull/10816 , can you try again?

**Comment by christian-bromann** [comment]
I would suggest to close this. You can also disable this by setting [`noUnusedParameters`](https://www.typescriptlang.org/tsconfig#noUnusedParameters) to `false`. I would prefer to keep as is given it demonstrates how you could use `expectationResultHandler` in your config.

**Comment by erwinheitzman** [comment]
Tried to test this again by generating a new project from scratch with the create-wdio package and got the following error during the creation:
``` 
@wdio/cli (v8.14.3)

TypeError: this.opt.choices.getChoice is not a function
    at CheckboxPrompt.render (file:///Users/erwin/Documents/Development/Personal/foosdfds/node_modules/inquirer/lib/prompts/checkbox.js:108:26)
    at CheckboxPrompt._run (file:///Users/erwin/Documents/Development/Personal/foosdfds/node_modules/inquirer/lib/prompts/checkbox.js:73:10)
    at file:///Users/erwin/Documents/Development/Personal/foosdfds/node_modules/inquirer/lib/prompts/base.js:64:12
    at new Promise (<anonymous>)
    at CheckboxPrompt.run (file:///Users/erwin/Documents/Development/Personal/foosdfds/node_modules/inquirer/lib/prompts/base.js:63:12)
    at file:///Users/erwin/Documents/Development/Personal/foosdfds/node_modules/inquirer/lib/ui/prompt.js:106:30
    at Observable._subscribe (/Users/erwin/Documents/Development/Personal/foosdfds/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:31)
    at Observable._trySubscribe (/Users/erwin/Documents/Development/Personal/foosdfds/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at /Users/erwin/Documents/Development/Personal/foosdfds/node_modules/rxjs/dist/cjs/internal/Observable.js:35:31
    at Object.errorContext (/Users/erwin/Documents/Development/Personal/foosdfds/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Observable.subscribe (/Users/erwin/Documents/Development/Personal/foosdfds/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
    at doInnerSub (/Users/erwin/Documents/Development/Personal/foosdfds/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:56)
    at outerNext (/Users/erwin/Documents/Development/Personal/foosdfds/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (/Users/erwin/Documents/Development/Personal/foosdfds/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (/Users/erwin/Documents/Development/Personal/foosdfds/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /Users/erwin/Documents/Development/Personal/foosdfds/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:28:28
```

**Comment by christian-bromann** [comment]
darn, that is weird

**Comment by christian-bromann** [comment]
@erwinheitzman I fixed the error, can you please retry?

**Comment by erwinheitzman** [comment]
Both issues are now resolved, thanks for your hard work!

**Comment by erwinheitzman** [comment]
@christian-bromann thanks again!
