### ISSUE TITLE
[🐛 Bug]: Driver manager: Multiple Firefox instances not running, same port used

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#10839]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.5.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  "browserName": "firefox"
}
```

### What happened?

When running multiple instances at the same time, `geckodriver` is started on the same port for all of them, causing only one instance to connect and run the tests, while all others fail.

### How to reproduce the bug.

Run tests with Firefox with `maxInstances` > 1

### Relevant log output

`geckodriver` log for a failed instance:

```shell
1690884069599	geckodriver	INFO	Listening on 0.0.0.0:57617
1690884070907	mozrunner::runner	INFO	Running command: MOZ_CRASHREPORTER="1" MOZ_CRASHREPORTER_NO_REPORT="1" MOZ_CRASHREPORTER_SHUTDOWN="1" MOZ_NO_REMOTE="1" "/App ... g-port" "9222" "-foreground" "-no-remote" "-profile" "/var/folders/sx/5p7dvbm54g155b9l4ddy7ln40000gn/T/rust_mozprofilePWXcIj"
console.warn: services.settings: Ignoring preference override of remote settings server
console.warn: services.settings: Allow by setting MOZ_REMOTE_SETTINGS_DEVTOOLS=1 in the environment
1690884071484	Marionette	INFO	Marionette enabled
1690884071619	Marionette	INFO	Listening on port 57639
Read port: 57639

!!! could not start server on port 9222: [Exception... "Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.init]"  nsresult: "0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE)"  location: "JS frame :: chrome://remote/content/server/HTTPD.jsm :: _start :: line 587"  data: no]

1690884071844	RemoteAgent	ERROR	Unable to stop listener: [Exception... "Unexpected error"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://remote/content/server/HTTPD.jsm :: stop :: line 641"  data: no] Stack trace: stop()@HTTPD.jsm:641
#stop()@RemoteAgent.sys.mjs:315
1690884071844	RemoteAgent	ERROR	Unable to start remote agent: : [Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: chrome://remote/content/server/HTTPD.jsm :: _start :: line 632"  data: no] Stack trace: _start()@HTTPD.jsm:632
#listen()@RemoteAgent.sys.mjs:234
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
```

Failed workers log on the console:

```shell
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected server response: 404
    at ClientRequest.<anonymous> (/Users/user/repos/repo/node_modules/ws/lib/websocket.js:888:7)
    at ClientRequest.emit (node:events:514:28)
    at ClientRequest.emit (node:domain:489:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at Socket.socketOnData (node:_http_client:535:22)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/Users/user/repos/repo/node_modules/ws/lib/websocket.js:1008:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by nextlevelbeard** [comment]
Suggestion: Driver log file names would be more practical if named with the same pattern as other logs that include the `cid`.
i.e. `wdio-0-2-chromedriver-55940.log` over `wdio-chromedriver-55940.log`

**Comment by christian-bromann** [comment]
> Suggestion: Driver log file names would be more practical if named with the same pattern as other logs that include the `cid`.
> i.e. `wdio-0-2-chromedriver-55940.log` over `wdio-chromedriver-55940.log`

This has been fixed with https://github.com/webdriverio/webdriverio/pull/10852

**Comment by christian-bromann** [comment]
@nextlevelbeard can you provide a reproducible example? I can start a WDIO testrun with multiple parallel Firefox sessions with no problem.

**Comment by christian-bromann** [comment]
Closing as no reproducible example can be provided. Happy to re-open.

**Comment by nextlevelbeard** [comment]
@christian-bromann I've found the root cause for this and made a fix in the `node-geckodriver` project. See: https://github.com/webdriverio-community/node-geckodriver/pull/196
