### ISSUE TITLE
[🐛 Bug]: Worker starts with downloading the chromedriver from incorrect path what leads to a failure

### ISSUE THREAD

**Issue by HannaTarasevich** [webdriverio/webdriverio#10860]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.14.4

### Node.js Version

18.17.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
"@wdio/cli": "^8.14.4",
    "@wdio/cucumber-framework": "^8.14.0",
    "@wdio/local-runner": "^8.14.3",
    "@wdio/spec-reporter": "^8.14.0"
```

### What happened?

I setup the project from the scratch today (3 August 2023) with JS, Cucumber, local-runner and spec-reporter. After the successful message in the console, I run "npm run wdio" and this job failed due to an error (please find repository here https://github.com/HannaTarasevich/wdio-cucumber-bug):
![image](https://github.com/webdriverio/webdriverio/assets/79576380/e43e6674-0493-4518-acae-3ea0d19bc55f)

According to my investigation, there is incorrect link to Chromedriver download. I'm using Chrome locally, current version is 115.0.5790.171, but WDIO tries downloading the same version of Chromedriver, but actually there is no such version (Chrome for Testing also does not have this version, only desktop has):
![image](https://github.com/webdriverio/webdriverio/assets/79576380/d6e8fa4b-b829-4175-819d-5af9da320a7f)

### What is your expected behavior?

WDIO should take correct version from https://googlechromelabs.github.io/chrome-for-testing/ and https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints, not using Chrome desktop versions

### How to reproduce the bug.

1) Please clone repo https://github.com/HannaTarasevich/wdio-cucumber-bug
2) Run npm/yarn install
3) Run "npm run wdio"

### Relevant log output

```typescript
"C:\Program Files\nodejs\npm.cmd" run wdio

> wdio
> wdio run ./wdio.conf.js


Execution of 1 workers started at 2023-08-03T19:29:27.307Z

2023-08-03T19:29:27.335Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-08-03T19:29:27.340Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-08-03T19:29:27.342Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js
[0-0] 2023-08-03T19:29:29.671Z INFO @wdio/local-runner: Run worker command: run
[0-0] (node:19188) DeprecationWarning: `PickleFilter` is deprecated, use `loadSources` instead; see https://github.com/cucumber/cucumber-js/blob/main/docs/deprecations.md
[0-0] (Use `node --trace-deprecation ...` to show where the warning was created)
[0-0] (node:19188) DeprecationWarning: `parseGherkinMessageStream` is deprecated, use `loadSources` instead; see https://github.com/cucumber/cucumber-js/blob/main/docs/deprecations
.md
[0-0] RUNNING in chrome - file:///C:/123/features/login.feature
[0-0] 2023-08-03T19:29:30.443Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-08-03T19:29:30.455Z INFO webdriver: Downloading Chromedriver v115.0.5790.171
[0-0] 2023-08-03T19:29:31.161Z ERROR @wdio/runner: Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.171
/win64/chromedriver-win64.zip
[0-0]     at file:///C:/123/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:74:31
[0-0]     at ClientRequest.requestCallback (file:///C:/123/node_modules/@puppeteer/browsers/lib/esm/httpUtil.js:52:13)
[0-0]     at Object.onceWrapper (node:events:629:26)
[0-0]     at ClientRequest.emit (node:events:514:28)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
[0-0]     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
[0-0]     at TLSSocket.socketOnData (node:_http_client:541:22)
[0-0]     at TLSSocket.emit (node:events:514:28)
[0-0]     at TLSSocket.emit (node:domain:489:12)
[0-0]     at addChunk (node:internal/streams/readable:324:12)
[0-0]     at readableAddChunk (node:internal/streams/readable:297:9)
[0-0]     at Readable.push (node:internal/streams/readable:234:10)
[0-0]     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[0-0] FAILED in chrome - file:///C:/123/features/login.feature
2023-08-03T19:29:31.415Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-08-03T19:29:31.416Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:04

2023-08-03T19:29:31.419Z INFO @wdio/local-runner: Shutting down spawned worker
2023-08-03T19:29:31.676Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-08-03T19:29:31.677Z INFO @wdio/local-runner: shutting down

Process finished with exit code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey @HannaTarasevich , thanks for raising the issue.

If no `browserName` is defined, WebdriverIO will check for a local installed Chrome browser and will try to install a Chromedriver that matches it. I wonder if there are Chrome versions that aren't compiled with a Chromedriver. You can resolve the issue by adding `browserName: 'stable'` to your capabilities.

I think WebdriverIO should attempt to just download the latest Chromedriver for v115 in this case.

**Comment by HannaTarasevich** [comment]
Hi @christian-bromann, Thanks for your quick response.

It was really helpful, and now it works with browserVersion: 'stable'. 
Agree with you (WebdriverIO should attempt to just download the latest Chromedriver for v115 in this case), I'll investigate the way how to fix it

**Comment by smohamali** [comment]
> Hey @HannaTarasevich , thanks for raising the issue.
> 
> If no `browserName` is defined, WebdriverIO will check for a local installed Chrome browser and will try to install a Chromedriver that matches it. I wonder if there are Chrome versions that aren't compiled with a Chromedriver. You can resolve the issue by adding `browserName: 'stable'` to your capabilities.
> 
> I think WebdriverIO should attempt to just download the latest Chromedriver for v115 in this case.
> 
> We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

Hey @christian-bromann,

Unfortunately, this didn't work for us. Instead we were met with the following error:

```
[0-0] 2023-08-08T07:13:57.759Z ERROR @wdio/runner: Error: Unknown browser name "stable". Make sure to pick from one of the following chrome,googlechrome,chromium,chromium-browser,firefox,ff,mozilla,mozilla firefox,edge,microsoftedge,msedge,safari,safari technology preview
[0-0]     at startWebDriver (file:///builds/azupay/codebase/ecg/e2e-tests/node_modules/webdriver/build/driver/index.js:124:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async Function.newSession (file:///builds/azupay/codebase/ecg/e2e-tests/node_modules/webdriver/build/index.js:27:31)
[0-0]     at async remote (file:///builds/azupay/codebase/ecg/e2e-tests/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (file:///builds/azupay/codebase/ecg/e2e-tests/node_modules/@wdio/runner/build/index.js:222:29)
[0-0]     at async Runner._initSession (file:///builds/azupay/codebase/ecg/e2e-tests/node_modules/@wdio/runner/build/index.js:188:25)
[0-0]     at async Runner.run (file:///builds/azupay/codebase/ecg/e2e-tests/node_modules/@wdio/runner/build/index.js:77:19)
```

**Comment by HannaTarasevich** [comment]
Hi @smohamali ,
Please use the following combination:
"browserName": "chrome",
"browserVersion": "stable"

**Comment by HannaTarasevich** [comment]
Hi @christian-bromann,
I've just prepared PR to fix the issue, kindly ask you to review https://github.com/webdriverio/webdriverio/pull/10899.

**Comment by christian-bromann** [comment]
> Error: Unknown browser name "stable".

@smohamali it seems you have set `browserName: 'stable'` which is invalid. It should be `browserVersion: 'stable'`

**Comment by christian-bromann** [comment]
@HannaTarasevich thanks for the contribution, I reviewed the PR. Looking forward working with you getting this landed.

**Comment by ForesightImaging** [comment]
I'm getting this same result of  ERROR @wdio/runner: Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.171/win64/chromedriver-win64.zip 

...but I'm using the electron service by cloning the [electron quickstart](https://github.com/electron/electron-quick-start), then running
```
npm init wdio and gave the following responses.

? A project named "electron-quick-start" was detected at "C:\gitlab\wdio-electron-trouble\electron-quick-start", correct? Yes
? What type of testing would you like to do? Desktop Testing - of Electron Applications
> https://webdriver.io/docs/desktop-testing/electron
? What is the path to your compiled Electron app? ./dist
? Which framework do you want to use? Mocha (https://mochajs.org/)
? Do you want to use a compiler? Babel (https://babeljs.io/)
? Do you want WebdriverIO to autogenerate some test files? Yes
? Where should these files be located? C:\gitlab\wdio-electron-trouble\electron-quick-start\test\specs***.js
? Which reporter do you want to use? spec
? Do you want to add a plugin to your test setup?
? Do you want to add a service to your test setup? electron
? Do you want me to run npm install Yes

Setting up Babel project...
✔ Success!

Installing wdio packages:

@wdio/local-runner@latest
@wdio/mocha-framework@latest
@wdio/spec-reporter@latest
wdio-electron-service
@babel/register
@babel/core
@babel/preset-env
This setup exhibited the same trouble. It ignores the electron config and goes for the local browser:
C:\gitlab\wdio-electron-trouble\electron-quick-start>npm run wdio

electron-quick-start@1.0.0 wdio
wdio run ./wdio.conf.js

Execution of 1 workers started at 2023-08-10T17:18:22.162Z

2023-08-10T17:18:22.179Z DEBUG @wdio/utils:initialiseServices: initialise service "electron" as NPM package
2023-08-10T17:18:22.240Z DEBUG electron-service: launcher received options: {
appPath: './dist',
appName: 'dave',
appArgs: [ 'foo', 'bar=baz' ],
chromedriver: { logFileName: 'wdio-chromedriver.log' },
electronVersion: '23.1.0'
}
2023-08-10T17:18:22.243Z DEBUG electron-service: setting chromedriver service options: {
logFileName: 'wdio-chromedriver.log',
chromedriverCustomPath: 'C:\gitlab\wdio-electron-trouble\electron-quick-start\node_modules\wdio-electron-service\bin\chromedriver.exe'
}
2023-08-10T17:18:22.244Z INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)
2023-08-10T17:18:22.245Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-08-10T17:18:22.245Z DEBUG electron-service: downloading Chromedriver for Electron v23.1.0...
2023-08-10T17:18:22.246Z DEBUG electron-service: chromedriver download config: {
version: '23.1.0',
artifactName: 'chromedriver',
force: false,
cacheRoot: undefined,
platform: undefined,
arch: undefined
}
2023-08-10T17:18:22.252Z DEBUG electron-service: assets downloaded to C:\Users\stroppoli\AppData\Local\electron\Cache\aa87dbcf7862ac804df9d46cb5e9a4f6ec81289bedb90aa64d3922d9ebd37c63\chromedriver-v23.1.0-win32-x64.zip
2023-08-10T17:18:22.494Z DEBUG electron-service: assets extracted
2023-08-10T17:18:22.495Z INFO chromedriver: Start Chromedriver (C:\gitlab\wdio-electron-trouble\electron-quick-start\node_modules\wdio-electron-service\bin\chromedriver.exe) with args --port=9515 --url-base=/
2023-08-10T17:18:22.525Z INFO chromedriver: Starting ChromeDriver 110.0.5481.100 (4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{https://github.com/webdriverio-community/wdio-electron-service/issues/14}) on port 9515
2023-08-10T17:18:22.526Z INFO chromedriver: Only local connections are allowed.
2023-08-10T17:18:22.526Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-08-10T17:18:22.534Z INFO chromedriver: ChromeDriver was started successfully.
2023-08-10T17:18:22.624Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 379ms
2023-08-10T17:18:22.628Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-08-10T17:18:22.628Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2023-08-10T17:18:22.630Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js
2023-08-10T17:18:22.637Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
[0-0] 2023-08-10T17:18:23.427Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-08-10T17:18:23.774Z DEBUG @wdio/runner: init remote session
[0-0] 2023-08-10T17:18:23.776Z DEBUG @wdio/utils:initialiseServices: initialise service "electron" as NPM package
[0-0] 2023-08-10T17:18:23.841Z DEBUG electron-service: setting browser capabilities {
[0-0] browserName: 'chrome',
[0-0] 'goog:chromeOptions': {
[0-0] binary: './dist/win-unpacked/dave.exe',
[0-0] args: [ 'foo', 'bar=baz' ],
[0-0] windowTypes: [ 'app', 'webview' ]
[0-0] }
[0-0] }
[0-0] 2023-08-10T17:18:23.843Z DEBUG @wdio/utils:shim: Finished to run "beforeSession" hook in 0ms
[0-0] RUNNING in chrome - file:///C:/gitlab/wdio-electron-trouble/electron-quick-start/test/specs/test.e2e.js
[0-0] 2023-08-10T17:18:23.943Z DEBUG @wdio/runner: init remote session
[0-0] 2023-08-10T17:18:23.944Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-08-10T17:18:23.952Z INFO webdriver: Downloading Chromedriver v115.0.5790.171
[0-0] 2023-08-10T17:18:24.418Z ERROR @wdio/runner: Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.171/win64/chromedriver-win64.zip
[0-0] at file:///C:/gitlab/wdio-electron-trouble/electron-quick-start/node_modules/@puppeteer/browsers/src/httpUtil.ts:96:23
[0-0] at ClientRequest.requestCallback (file:///C:/gitlab/wdio-electron-trouble/electron-quick-start/node_modules/@puppeteer/browsers/src/httpUtil.ts:66:7)
[0-0] at Object.onceWrapper (node:events:628:26)
[0-0] at ClientRequest.emit (node:events:513:28)
[0-0] at ClientRequest.emit (node:domain:489:12)
[0-0] at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
[0-0] at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
[0-0] at TLSSocket.socketOnData (node:_http_client:534:22)
[0-0] at TLSSocket.emit (node:events:513:28)
[0-0] at TLSSocket.emit (node:domain:489:12)
[0-0] at addChunk (node:internal/streams/readable:315:12)
[0-0] at readableAddChunk (node:internal/streams/readable:289:9)
[0-0] at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
[0-0] at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
2023-08-10T17:18:25.260Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///C:/gitlab/wdio-electron-trouble/electron-quick-start/test/specs/test.e2e.js
2023-08-10T17:18:25.262Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-08-10T17:18:25.263Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 1ms
2023-08-10T17:18:25.263Z INFO @wdio/cli:launcher: Run onComplete hook
2023-08-10T17:18:25.264Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms

Spec Files: 0 passed, 1 failed, 1 total (100% completed) in 00:00:03

2023-08-10T17:18:25.265Z INFO @wdio/local-runner: Shutting down spawned worker
2023-08-10T17:18:25.518Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-08-10T17:18:25.520Z INFO @wdio/local-runner: shutting down
```

**Comment by zohids** [comment]
Hi @HannaTarasevich,
when I used        ```
 "browserName": "chrome",
  "browserVersion": "stable"
```
I got this:
[0-0] RUNNING in chrome - file:///C:/Users/Zohidjon%20Subkhonzoda/WDIO%20Basic%20practical%20tasks/test/specs/test.spec.js
[0-0] 2023-08-11T06:32:45.594Z ERROR @wdio/runner: Error: getaddrinfo ENOTFOUND googlechromelabs.github.io
[0-0]     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[0-0] FAILED in chrome - file:///C:/Users/Zohidjon%20Subkhonzoda/WDIO%20Basic%20practical%20tasks/test/specs/test.spec.js

**Comment by christian-bromann** [comment]
@zohids are you behind a corporate firewall?

**Comment by christian-bromann** [comment]
fixed by #10902

**Comment by zohids** [comment]
> @zohids are you behind a corporate firewall?

I am sorry.
I think it was happening from my end. After updating Google Chrome browser, the problem has been eliminated
Thanks

**Comment by rouse-iran-barbosa** [comment]
For me worked doing 2 things:

**Comment by christian-bromann** [comment]
> * Adding `browserVersion: 'stable'` and `baseURL: 'https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing'` to the chromedriver capabilities

@rouse-iran-barbosa afaik this is the [default value](https://github.com/puppeteer/puppeteer/blob/ce9e2df04d55829f9cdca273513e58c087b04667/packages/browsers/src/browser-data/chromedriver.ts#L38), why do you need to set it?

**Comment by AZANIR** [comment]
2024-02-17T10:37:10.766Z ERROR webdriver: Failed downloading chromedriver v121.0.6167.184: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/win64/chromedriver-win64.zip, retrying ..


yesterday all work

capabilities: [
        {
            maxInstances: 1,
            browserName: 'chrome',
            'goog:chromeOptions': browserOptions,
            acceptInsecureCerts: true
        }
    ]

**Comment by AZANIR** [comment]
when i use 
capabilities: [
        {
            maxInstances: 1,
            browserName: 'chrome',
            browserVersion: 'stable',
            'goog:chromeOptions': browserOptions,
            acceptInsecureCerts: true
        }
    ],
    
    Error: Error: Couldn't find a matching chrome browser for tag "121.0.6167.184" on platform "win64"

**Comment by christian-bromann** [comment]
Please see https://github.com/webdriverio/webdriverio/issues/12251

**Comment by SinghMegha27** [comment]
https://github.com/webdriverio/webdriverio/issues/12251#issuecomment-1951347480 - please go through this

**Comment by SinghMegha27** [comment]
https://github.com/webdriverio/webdriverio/issues/12251#issuecomment-1951349962
