### ISSUE TITLE
[🐛 Bug]: browser.reloadSession() causes 'ERROR webdriver: RequestError: read ECONNRESET' error

### ISSUE THREAD

**Issue by idem7x** [webdriverio/webdriverio#10887]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.14.3

### Node.js Version

18.17.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
browserName: "chrome",
"goog:chromeOptions": {
                args: [
                    "--no-sandbox",
                    "--disable-dev-shm-usage",
                    "--disable-extensions",
                    "--disable-web-security",
                    // "--headless=new",
                    "--window-size=1600,900",
                    "--disable-gpu",
                    "--enable-logging --v=1",
                    "--ignore-certificate-errors",
                    "--unlimited-storage"
                ],
                prefs: {
                    "profile.default_content_settings.popups": 2,
                    "download.default_directory": __dirname + "/test/resources",
                    "plugins.always_open_pdf_externally": true
                }
```

### What happened?

After update to chromedriver 115, browser.reloadSession() causes 'ERROR webdriver: RequestError: read ECONNRESET' error. 

### What is your expected behavior?

`browser.reloadSession()`  should reload page without any issues. 

### How to reproduce the bug.

To reproduce bug clone next [repo](https://github.com/idem7x/wdiosauce). 
Then use steps from `Chromedriver bug with reload`.

### Relevant log output

```typescript
max@Maksyms-Air wdiosauce (main) $ npm run test:chrome 

> wdiosauce@1.0.0 test:chrome
> npx wdio run ./wdio.local.ts --suite download


Execution of 1 workers started at 2023-08-07T18:04:11.913Z

2023-08-07T18:04:11.988Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-08-07T18:04:11.990Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-08-07T18:04:11.990Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.local.ts,--suite,download
[0-0] 2023-08-07T18:04:12.589Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///test/specs/download.ts
[0-0] 2023-08-07T18:04:12.753Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-08-07T18:04:13.113Z INFO webdriver: Setting up Chrome v115.0.5790.170
[0-0] 2023-08-07T18:04:13.114Z INFO webdriver: Using Chromedriver v115.0.5790.170 from cache directory /var/folders/cg/xpq_5gl916b60hhptxyjfwt40000gn/T
[0-0] 2023-08-07T18:04:14.123Z INFO webdriver: Started ChromeDriver v115.0.5790.170 with params --port=56055 --allowed-origins=* --allowed-ips= in 1369ms on port 56055
[0-0] 2023-08-07T18:04:14.166Z INFO webdriver: [POST] http://0.0.0.0:56055/session
[0-0] 2023-08-07T18:04:14.166Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/var/folders/cg/xpq_5gl916b60hhptxyjfwt40000gn/T/chrome/mac_arm-115.0.5790.170/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing',
[0-0]       args: [Array],
[0-0]       prefs: [Object]
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2023-08-07T18:04:15.511Z INFO wdio-image-comparison-service: Adding commands to global browser
[0-0] 2023-08-07T18:04:15.520Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/download")
[0-0] 2023-08-07T18:04:15.521Z INFO webdriver: [POST] http://0.0.0.0:56055/session/e63f74ebe0bfb147933c350c80eaa905/url
[0-0] 2023-08-07T18:04:15.521Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/download' }
[0-0] 2023-08-07T18:04:17.285Z INFO webdriver: RESULT null
[0-0] 2023-08-07T18:04:17.288Z INFO webdriver: COMMAND findElement("css selector", "a[href='download/myfile.pdf']")
[0-0] 2023-08-07T18:04:17.289Z INFO webdriver: [POST] http://0.0.0.0:56055/session/e63f74ebe0bfb147933c350c80eaa905/element
[0-0] 2023-08-07T18:04:17.290Z INFO webdriver: DATA { using: 'css selector', value: "a[href='download/myfile.pdf']" }
[0-0] 2023-08-07T18:04:17.304Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'D1E7CAAE103F18E7B7C61D2908FCB1F7_element_3'
[0-0] }
[0-0] 2023-08-07T18:04:17.313Z INFO webdriver: COMMAND elementClick("D1E7CAAE103F18E7B7C61D2908FCB1F7_element_3")
[0-0] 2023-08-07T18:04:17.314Z INFO webdriver: [POST] http://0.0.0.0:56055/session/e63f74ebe0bfb147933c350c80eaa905/element/D1E7CAAE103F18E7B7C61D2908FCB1F7_element_3/click
[0-0] 2023-08-07T18:04:17.607Z INFO webdriver: RESULT null
[0-0] 2023-08-07T18:04:21.611Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/login")
[0-0] 2023-08-07T18:04:21.611Z INFO webdriver: [POST] http://0.0.0.0:56055/session/e63f74ebe0bfb147933c350c80eaa905/url
[0-0] 2023-08-07T18:04:21.611Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2023-08-07T18:04:22.213Z INFO webdriver: RESULT null
[0-0] 2023-08-07T18:04:22.214Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-08-07T18:04:22.215Z INFO webdriver: [DELETE] http://0.0.0.0:56055/session/e63f74ebe0bfb147933c350c80eaa905
[0-0] 2023-08-07T18:04:22.272Z INFO webdriver: RESULT null
[0-0] 2023-08-07T18:04:22.273Z INFO webdriver: Kill /var/folders/cg/xpq_5gl916b60hhptxyjfwt40000gn/T/chromedriver/mac_arm-115.0.5790.170/chromedriver-mac-arm64/chromedriver driver process with command line: --port=56055 --allowed-origins=* --allowed-ips=
[0-0] 2023-08-07T18:04:22.274Z INFO webdriver: [POST] http://0.0.0.0:56055/session
[0-0] 2023-08-07T18:04:22.274Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': { args: [Array], prefs: [Object] }
[0-0]   }
[0-0] }
[0-0] 2023-08-07T18:04:22.277Z ERROR webdriver: RequestError: read ECONNRESET
[0-0]     at ClientRequest.<anonymous> (file:///Users/dem7x/WebstormProjects/wdiosauce/node_modules/webdriver/node_modules/got/dist/source/core/index.js:790:107)
[0-0]     at Object.onceWrapper (node:events:629:26)
[0-0]     at ClientRequest.emit (node:events:526:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:501:9)
[0-0]     at Socket.emit (node:events:514:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[0-0]     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
[0-0] Error in "Reload session bug reloadSession"
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserContext.<anonymous> (/Users/dem7x/WebstormProjects/wdiosauce/test/specs/download.ts:15:9)
[0-0] 2023-08-07T18:04:22.281Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-08-07T18:04:22.281Z INFO webdriver: [DELETE] http://0.0.0.0:56055/session/e63f74ebe0bfb147933c350c80eaa905
[0-0] 2023-08-07T18:04:29.350Z ERROR @wdio/local-runner: Failed launching test session: RequestError: connect ECONNREFUSED 0.0.0.0:56055
[0-0]     at ClientRequest.<anonymous> (file:///Users/dem7x/WebstormProjects/wdiosauce/node_modules/webdriver/node_modules/got/dist/source/core/index.js:790:107)
[0-0]     at Object.onceWrapper (node:events:629:26)
[0-0]     at ClientRequest.emit (node:events:526:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:501:9)
[0-0]     at Socket.emit (node:events:514:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
[0-0] FAILED in chrome - file:///test/specs/download.ts
2023-08-07T18:04:29.462Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-08-07T18:04:29.463Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:17 

2023-08-07T18:04:29.469Z INFO @wdio/local-runner: Shutting down spawned worker
2023-08-07T18:04:29.721Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-08-07T18:04:29.721Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

It seems that this use case hasn't been test when adding this feature. We should find out why Chromedriver isn't started or find a way to not have it being killed when reloading the session.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!
