### ISSUE TITLE
[🐛 Bug]: First time test run of WDIO with default configs results in ES related errors

### ISSUE THREAD

**Issue by zac11** [webdriverio/webdriverio#10901]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v20.5.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome'
    }],
```

### What happened?

I started with WDIO installation following these steps

- Created a git repo, cloned it on my system and did `npm init`
- Proceeded with `npm init wdio` and accepted the default behavior in most cases 
-  Ran `npm run wdio` and faced errors

Attached screenshot of the `npm init wdio` step 

<img width="1680" alt="Screenshot 2023-08-09 at 11 10 26 AM" src="https://github.com/webdriverio/webdriverio/assets/8002297/53cf6d36-56b8-4d76-ae4b-98e093a80b0d">

### What is your expected behavior?

The initial `npm run wdio` should have worked fine. Instead it started throwing error - 

`SyntaxError: Cannot use import statement outside a module`

Full stack trace I have pasted in the log output section.

### How to reproduce the bug.

-  Clone this repo : https://github.com/zac11/wdio-work-demo
-  Run `npm run wdio`

### Relevant log output

```typescript
npm run wdio

> wdio-work-demo@1.0.0 wdio
> wdio run ./wdio.conf.ts

2023-08-09T05:30:14.234Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/annubha/Documents/Rahul/wdio-work-demo/wdio.conf.ts: Cannot use import statement outside a module
/Users/annubha/Documents/Rahul/wdio-work-demo/wdio.conf.ts:1
import type { Options } from '@wdio/types'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1197:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at async CustomizedModuleLoader.import (node:internal/modules/esm/loader:228:24)
    at async ConfigParser.addConfigFile (file:///Users/annubha/Documents/Rahul/wdio-work-demo/node_modules/@wdio/config/build/lib/ConfigParser.js:85:36)
    at async ConfigParser.initialize (file:///Users/annubha/Documents/Rahul/wdio-work-demo/node_modules/@wdio/config/build/lib/ConfigParser.js:47:13)
    at async Launcher.run (file:///Users/annubha/Documents/Rahul/wdio-work-demo/node_modules/@wdio/cli/build/launcher.js:37:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@zac11 thanks for raising an issue. We have recently made changes to the TypeScript loader (see #10816, cc @jan-molak) which has caused this regression. I recommend to proceed your project as ESM project or name all testing files `.mts` so it is properly detected as ESM module until we have a fix.

**Comment by christian-bromann** [comment]
One way to go about this is by checking if the project runs ESM or CJS and apply the correct `ts-node` flags. However there doesn't seem to be a straight forward way to do this.

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by zac11** [comment]
Thanks @christian-bromann for the reply. I changed the file names to `.mts`. I've tried two approaches
1. Changed only the files inside the `specs` dir to be `.mts`.
2. Changed all files to be `.mts`.

Both result in errors

<img width="1271" alt="Screenshot 2023-08-09 at 12 05 52 PM" src="https://github.com/webdriverio/webdriverio/assets/8002297/88fc5151-4d25-4045-b4a6-d9437565b587">
<img width="1292" alt="Screenshot 2023-08-09 at 12 06 34 PM" src="https://github.com/webdriverio/webdriverio/assets/8002297/204053fe-a11b-4b67-8f74-549eec79c616">

The sample repo has two branch - `main_changeMTS` and `main_changeMTS2` for both approaches - if this helps.

And surely I'll keep investigating this by trying to test with ESM.

**Comment by zac11** [comment]
https://github.com/zac11/wdio-work-demo/blob/main_changeMTS2/wdio.conf.mts - this branch contains the changes for the `specs` option in the `conf` file.

It complains that it cannot find any tests 
```

annubha@Annubhas-MacBook-Pro wdio-work-demo % npm run wdio

> wdio-work-demo@1.0.0 wdio
> wdio run ./wdio.conf.mts

2023-08-09T06:36:27.079Z WARN @wdio/config:ConfigParser: pattern ./test/specs/**/*.mts did not match any file

Execution of 0 workers started at 2023-08-09T06:36:27.080Z

2023-08-09T06:36:27.088Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-08-09T06:36:27.089Z WARN @wdio/config:ConfigParser: pattern ./test/specs/**/*.mts did not match any file
2023-08-09T06:36:27.089Z ERROR @wdio/cli:launcher: No specs found to run, exiting with failure
2023-08-09T06:36:27.089Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 0 total (0% completed) in 00:00:00 

2023-08-09T06:36:27.089Z INFO @wdio/local-runner: Shutting down spawned worker
2023-08-09T06:36:27.341Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-08-09T06:36:27.343Z INFO @wdio/local-runner: shutting down
```

**Comment by christian-bromann** [comment]
Dang .. I pushed a PR with a fix for it. Hope to release this asap.

**Comment by jan-molak** [comment]
@christian-bromann and @zac11 - Using Node v18.16.0 (current LTS) as well as Node 16 I'm getting a passing build:

<img width="2271" alt="Screenshot 2023-09-15 at 22 10 10" src="https://github.com/webdriverio/webdriverio/assets/1089173/d74a6d74-18ba-4c7d-ba49-49014bfb5ef7">

I am, however, able to reproduce the error in Node 20.6.1:

<img width="2140" alt="Screenshot 2023-09-15 at 22 12 57" src="https://github.com/webdriverio/webdriverio/assets/1089173/ce303a01-68c5-4176-8e36-88723b7dd48f">

I wonder what's changed between Node 18 and 20 in this space
