### ISSUE TITLE
[🐛 Bug]: Wdio 8.14 fails to download win chromedriver 115.0.5790.171 because it doesn't exist

### ISSUE THREAD

**Issue by salvag-ntt** [webdriverio/webdriverio#10907]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.14.4

### Node.js Version

19.2.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
// I don't think the bug is specifically related to the capability section
{
      maxInstances: 5,
      browserName: 'chrome',
      browser_version: '114.0.5790.170',
      'goog:chromeOptions': {
        args: ['--no-sandbox'],
      },
      acceptInsecureCerts: true,
}
```

### What happened?

Looks like Webdriver.io tries do download the Chormedriver and fails because it can't find the specific version on the Google ChromeDriver in the Chrome Test location (see logs below). I just a 404 and even if I try to force to a specific browser version (hoping that would be used for downloading that driver version) that doesn't seem to be picked up for download.

On another linux machine, the browser version is 114.0.5790.170, the driver is correctly found (here https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.170/linux64/chrome-linux64.zip), downloaded and installed. On the Windows machine the driver used is almost exactly the same 114.0.5790.171 but, that doesn't exist on the server here https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.171/win64/chrome-win64.zip, you can see in the log I get a 404

I also tried to download it manually to add it in the node_modules but as the driver is not available, no joy

I haven't added any chromedriver, chormedriver-service or selenium-standalone in the dependencies as it looks like from WDIO 8.14 and above I get a message that they are not needed, which is good because my devDependencies look so much lighter. Nonetheless, if WDIO handles that under the hood I would expect the process to succeed, or to have a way to override the version number I would need.

### What is your expected behavior?

1. If I don't specify the browser/driver version I guess the latest will be used, but that should be available on the Chromedriver server.
2. Specifying the actual browser version in the capability section should be used to select what Chromedriver to download/install

### How to reproduce the bug.

If needed I can setup a demo repo but this is easily reproducible by installing wdio from scratch with the below configuration:

`npm wdio init .` 

to create a new project and used the following configuration from the interactive installation process:

```
===============================
🤖 WDIO Configuration Wizard 🧙
===============================

? What type of testing would you like to do? E2E Testing - of Web or Mobile Applications
? Where is your automation backend located? On my local machine
? Which environment you would like to automate? Web - web applications in the browser
? With which browser should we start? Chrome
? Which framework do you want to use? Cucumber (https://cucumber.io/)
? Do you want to use a compiler? TypeScript (https://www.typescriptlang.org/)
? Do you want WebdriverIO to autogenerate some test files? Yes
? Where should these feature files be located? C:\Users\salvag\workspace\webdriverio\features\**\*.feature
? Where should these step definitions be located? C:\Users\salvag\workspace\webdriverio\features\step-definitions\steps.ts
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? Yes
? Where are your page objects located? C:\Users\salvag\workspace\webdriverio\features\pageobjects\**\*.ts
? Which reporter do you want to use? spec
? Do you want to add a plugin to your test setup? No
? Do you want to add a service to your test setup? No
? What is the base url? http://localhost
? Do you want me to run `npm install` Yes


Setting up TypeScript...
✔ Success!

Installing wdio packages:
- @wdio/local-runner@latest
- @wdio/cucumber-framework@latest
- @wdio/spec-reporter@latest
- ts-node
- typescript
```

and the version of the dependencies installed in the `package.json` are as follows, just in case you need the specific versions

```
{
  "name": "my-new-project",
  "type": "module",
  "devDependencies": {
    "@wdio/cli": "^8.14.4",
    "@wdio/cucumber-framework": "^8.14.0",
    "@wdio/local-runner": "^8.14.3",
    "@wdio/spec-reporter": "^8.14.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.6"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.conf.ts"
  }
}
```

and then just run it as specified by the installer

`npm run wdio`

### Relevant log output

```typescript
npm run wdio

> wdio-test@1.0.0 wdio
> wdio run ./wdio.conf.ts


Execution of 1 workers started at 2023-08-10T08:39:56.377Z

2023-08-10T08:39:56.406Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-08-10T08:39:56.409Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-08-10T08:39:56.411Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] 2023-08-10T08:39:58.176Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///C:/Users/salvag/workspace/webdriverio/test/features/swaglabs.feature
[0-0] 2023-08-10T08:39:58.749Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-08-10T08:39:58.766Z INFO webdriver: Downloading Chromedriver v115.0.5790.171
[0-0] 2023-08-10T08:39:59.150Z ERROR @wdio/runner: Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/115.0.5790.171/win64/chromedriver-win64.zip
[0-0]     at file:///C:/Users/salvag/workspace/webdriverio/node_modules/@puppeteer/browsers/src/httpUtil.ts:98:23
[0-0]     at ClientRequest.requestCallback (file:///C:/Users/salvag/workspace/webdriverio/node_modules/@puppeteer/browsers/src/httpUtil.ts:68:7)
[0-0]     at Object.onceWrapper (node:events:628:26)
[0-0]     at ClientRequest.emit (node:events:513:28)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at HTTPParser.parserOnIncomingClient (node:_http_client:688:27)
[0-0]     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
[0-0]     at TLSSocket.socketOnData (node:_http_client:530:22)
[0-0]     at TLSSocket.emit (node:events:513:28)
[0-0]     at TLSSocket.emit (node:domain:489:12)
[0-0]     at addChunk (node:internal/streams/readable:324:12)
[0-0]     at readableAddChunk (node:internal/streams/readable:297:9)
[0-0]     at TLSSocket.Readable.push (node:internal/streams/readable:234:10)
[0-0]     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[0-0] FAILED in chrome - file:///C:/Users/salvag/workspace/webdriverio/test/features/swaglabs.feature
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by salvag-ntt** [comment]
Right.... closing this ticket as it seems like it's a duplicate of this https://github.com/webdriverio/webdriverio/issues/10860
Apologies for that, the title of the other one was a bit misleading

**Comment by salvag-ntt** [comment]
Closing as duplicate of https://github.com/webdriverio/webdriverio/issues/10860
