### ISSUE TITLE
[🐛 Bug]: number of retries and limit is always 0 even when defining retries

### ISSUE THREAD

**Issue by HananArgov** [webdriverio/webdriverio#10993]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.15.4

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      browserName: "chrome",
    },
```

### What happened?

retries in Jasmine hooks are showing zeros:
`{attempts: 0, limit: 0}`
this is for `afterTest`, `afterHook`

### What is your expected behavior?

the attempts should show the current number of runs, and limits should show the number defined in `specFileRetries`

### How to reproduce the bug.

1. use the initiated wdio, with jasmine framework.
2. in wdio.conf set `specFileRetries` to any number of retries (doesn't matter)
3. in wdio.conf set afterTest, for an example, put the following code:
```
  afterTest: function (test, context, { error, result, duration, passed, retries }) {
    console.log('retries:', retries);
  },
```

### Relevant log output

```typescript
Debugger listening on ws://127.0.0.1:53733/c1618a04-8a79-4493-b952-60902d196caf
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
yarn run v1.22.19
warning package.json: No license field
$ wdio run ./wdio.conf.ts
Debugger listening on ws://127.0.0.1:53737/e32540bf-1fac-4f00-8a42-3a8c8668416e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:53740/a53db057-7560-481a-9503-cefc2425fd5e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

Execution of 1 workers started at 2023-08-22T02:18:32.019Z

2023-08-22T02:18:32.058Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-08-22T02:18:32.062Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-08-22T02:18:32.063Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] For help, see: https://nodejs.org/en/docs/inspector
[0-0] 2023-08-22T02:18:34.364Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-08-22T02:18:34.771Z INFO @moroo/wdio-slack-reporter: Created Slack Webhook Instance.
[0-0] RUNNING in chrome - file:///test/specs/test.e2e.ts
[0-0] 2023-08-22T02:18:34.892Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-08-22T02:18:35.728Z INFO webdriver: Setting up Chrome v116.0.5845.96
[0-0] 2023-08-22T02:18:35.730Z INFO webdriver: Using Chromedriver v116.0.5845.96 from cache directory /var/folders/mj/s4sjm80d14sggxry24xb2yx40000gp/T
[0-0] 2023-08-22T02:18:36.754Z INFO webdriver: Started ChromeDriver v116.0.5845.96 with params --port=53746 --allowed-origins=* --allowed-ips= in 1861ms on port 53746
[0-0] 2023-08-22T02:18:36.946Z INFO webdriver: [POST] http://0.0.0.0:53746/session
[0-0] 2023-08-22T02:18:36.947Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/var/folders/mj/s4sjm80d14sggxry24xb2yx40000gp/T/chrome/mac-116.0.5845.96/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2023-08-22T02:18:38.931Z INFO @moroo/wdio-slack-reporter: INFO Test Framework: jasmine
[0-0] 2023-08-22T02:18:38.931Z INFO @moroo/wdio-slack-reporter: INFO ON RUNNER START: SEND
[0-0] 2023-08-22T02:18:38.941Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/login")
[0-0] 2023-08-22T02:18:38.942Z INFO webdriver: [POST] http://0.0.0.0:53746/session/23b0e9ca4c78df197ee982d524dd9460/url
[0-0] 2023-08-22T02:18:38.942Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2023-08-22T02:18:38.984Z INFO @moroo/wdio-slack-reporter: Start Synchronising...
[0-0] 2023-08-22T02:18:38.984Z INFO @moroo/wdio-slack-reporter: POST Slack Request webhook:send
[0-0] 2023-08-22T02:18:39.699Z INFO @moroo/wdio-slack-reporter: End Synchronising!!!
[0-0] 2023-08-22T02:18:40.003Z INFO webdriver: RESULT null
[0-0] afterTest
[0-0] Error in "My Login application should login with valid credentials"
    at <Jasmine>
    at UserContext.<anonymous> (file:///Users/hananargov/Documents/wdio/test/specs/test.e2e.ts:14:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0] 2023-08-22T02:19:13.585Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-08-22T02:19:13.585Z INFO webdriver: [DELETE] http://0.0.0.0:53746/session/23b0e9ca4c78df197ee982d524dd9460
[0-0] 2023-08-22T02:19:13.587Z INFO @moroo/wdio-slack-reporter: Start Synchronising...
[0-0] 2023-08-22T02:19:13.587Z INFO @moroo/wdio-slack-reporter: POST Slack Request webhook:send
[0-0] 2023-08-22T02:19:13.645Z INFO webdriver: RESULT null
[0-0] 2023-08-22T02:19:13.646Z INFO webdriver: Kill /var/folders/mj/s4sjm80d14sggxry24xb2yx40000gp/T/chromedriver/mac-116.0.5845.96/chromedriver-mac-x64/chromedriver driver process with command line: --port=53746 --allowed-origins=* --allowed-ips=
[0-0] 2023-08-22T02:19:13.652Z ERROR @moroo/wdio-slack-reporter: false
[0-0] 2023-08-22T02:19:13.755Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:19:13.855Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:19:13.957Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:19:14.058Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:19:14.159Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:19:14.206Z INFO @moroo/wdio-slack-reporter: POST Slack Request webhook:send
[0-0] 2023-08-22T02:19:14.266Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:19:14.367Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:19:14.468Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:19:14.569Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:19:14.629Z INFO @moroo/wdio-slack-reporter: End Synchronising!!!
[0-0] RETRYING in chrome - file:///test/specs/test.e2e.ts
2023-08-22T02:19:15.625Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-08-22T02:19:15.628Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-08-22T02:19:15.629Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] For help, see: https://nodejs.org/en/docs/inspector
[0-0] 2023-08-22T02:19:18.092Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-08-22T02:19:18.653Z INFO @moroo/wdio-slack-reporter: Created Slack Webhook Instance.
[0-0] RUNNING in chrome - file:///test/specs/test.e2e.ts
[0-0] 2023-08-22T02:19:18.761Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-08-22T02:19:19.555Z INFO webdriver: Setting up Chrome v116.0.5845.96
[0-0] 2023-08-22T02:19:19.557Z INFO webdriver: Using Chromedriver v116.0.5845.96 from cache directory /var/folders/mj/s4sjm80d14sggxry24xb2yx40000gp/T
[0-0] 2023-08-22T02:19:20.583Z INFO webdriver: Started ChromeDriver v116.0.5845.96 with params --port=53787 --allowed-origins=* --allowed-ips= in 1821ms on port 53787
[0-0] 2023-08-22T02:19:20.763Z INFO webdriver: [POST] http://0.0.0.0:53787/session
[0-0] 2023-08-22T02:19:20.763Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/var/folders/mj/s4sjm80d14sggxry24xb2yx40000gp/T/chrome/mac-116.0.5845.96/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2023-08-22T02:19:22.091Z INFO @moroo/wdio-slack-reporter: INFO Test Framework: jasmine
[0-0] 2023-08-22T02:19:22.091Z INFO @moroo/wdio-slack-reporter: INFO ON RUNNER START: SEND
[0-0] 2023-08-22T02:19:22.102Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/login")
[0-0] 2023-08-22T02:19:22.103Z INFO webdriver: [POST] http://0.0.0.0:53787/session/9c0649f93f9d147f555c1800a87c5eb1/url
[0-0] 2023-08-22T02:19:22.103Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2023-08-22T02:19:22.116Z INFO @moroo/wdio-slack-reporter: Start Synchronising...
[0-0] 2023-08-22T02:19:22.117Z INFO @moroo/wdio-slack-reporter: POST Slack Request webhook:send
[0-0] 2023-08-22T02:19:22.600Z INFO @moroo/wdio-slack-reporter: End Synchronising!!!
[0-0] 2023-08-22T02:19:23.034Z INFO webdriver: RESULT null
[0-0] afterTest
[0-0] Error in "My Login application should login with valid credentials"
    at <Jasmine>
    at UserContext.<anonymous> (file:///Users/hananargov/Documents/wdio/test/specs/test.e2e.ts:14:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0] 2023-08-22T02:20:31.321Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-08-22T02:20:31.322Z INFO webdriver: [DELETE] http://0.0.0.0:53787/session/9c0649f93f9d147f555c1800a87c5eb1
[0-0] 2023-08-22T02:20:31.324Z INFO @moroo/wdio-slack-reporter: Start Synchronising...
[0-0] 2023-08-22T02:20:31.324Z INFO @moroo/wdio-slack-reporter: POST Slack Request webhook:send
[0-0] 2023-08-22T02:20:31.381Z INFO webdriver: RESULT null
[0-0] 2023-08-22T02:20:31.381Z INFO webdriver: Kill /var/folders/mj/s4sjm80d14sggxry24xb2yx40000gp/T/chromedriver/mac-116.0.5845.96/chromedriver-mac-x64/chromedriver driver process with command line: --port=53787 --allowed-origins=* --allowed-ips=
[0-0] 2023-08-22T02:20:31.385Z ERROR @moroo/wdio-slack-reporter: false
[0-0] 2023-08-22T02:20:31.487Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:31.588Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:31.690Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:31.791Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:31.892Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:31.992Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:32.093Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:32.194Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:32.295Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:32.331Z INFO @moroo/wdio-slack-reporter: POST Slack Request webhook:send
[0-0] 2023-08-22T02:20:32.396Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:32.496Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:32.596Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:32.697Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:32.798Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:20:32.862Z INFO @moroo/wdio-slack-reporter: End Synchronising!!!
[0-0] RETRYING in chrome - file:///test/specs/test.e2e.ts (1 retries)
2023-08-22T02:20:33.925Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-08-22T02:20:33.927Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-08-22T02:20:33.928Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] For help, see: https://nodejs.org/en/docs/inspector
[0-0] 2023-08-22T02:20:36.296Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-08-22T02:20:36.761Z INFO @moroo/wdio-slack-reporter: Created Slack Webhook Instance.
[0-0] RUNNING in chrome - file:///test/specs/test.e2e.ts
[0-0] 2023-08-22T02:20:36.919Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-08-22T02:20:37.693Z INFO webdriver: Setting up Chrome v116.0.5845.96
[0-0] 2023-08-22T02:20:37.695Z INFO webdriver: Using Chromedriver v116.0.5845.96 from cache directory /var/folders/mj/s4sjm80d14sggxry24xb2yx40000gp/T
[0-0] 2023-08-22T02:20:38.720Z INFO webdriver: Started ChromeDriver v116.0.5845.96 with params --port=53838 --allowed-origins=* --allowed-ips= in 1800ms on port 53838
[0-0] 2023-08-22T02:20:38.886Z INFO webdriver: [POST] http://0.0.0.0:53838/session
[0-0] 2023-08-22T02:20:38.886Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/var/folders/mj/s4sjm80d14sggxry24xb2yx40000gp/T/chrome/mac-116.0.5845.96/chrome-mac-x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'
[0-0]     }
[0-0]   }
[0-0] }
[0-0] 2023-08-22T02:20:40.160Z INFO @moroo/wdio-slack-reporter: INFO Test Framework: jasmine
[0-0] 2023-08-22T02:20:40.160Z INFO @moroo/wdio-slack-reporter: INFO ON RUNNER START: SEND
[0-0] 2023-08-22T02:20:40.169Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/login")
[0-0] 2023-08-22T02:20:40.170Z INFO webdriver: [POST] http://0.0.0.0:53838/session/09546e2d9277632236a20dd8a6a33e2a/url
[0-0] 2023-08-22T02:20:40.170Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2023-08-22T02:20:40.205Z INFO @moroo/wdio-slack-reporter: Start Synchronising...
[0-0] 2023-08-22T02:20:40.206Z INFO @moroo/wdio-slack-reporter: POST Slack Request webhook:send
[0-0] 2023-08-22T02:20:40.967Z INFO @moroo/wdio-slack-reporter: End Synchronising!!!
[0-0] 2023-08-22T02:20:41.449Z INFO webdriver: RESULT null
Debugger ending on ws://127.0.0.1:53733/c1618a04-8a79-4493-b952-60902d196caf
For help, see: https://nodejs.org/en/docs/inspector
Debugger ending on ws://127.0.0.1:53737/e32540bf-1fac-4f00-8a42-3a8c8668416e
For help, see: https://nodejs.org/en/docs/inspector
Debugger ending on ws://127.0.0.1:53740/a53db057-7560-481a-9503-cefc2425fd5e
For help, see: https://nodejs.org/en/docs/inspector
[0-0] Debugger ending on ws://127.0.0.1:53835/7484ae3e-8df9-4300-b318-0d194164cfd7
[0-0] For help, see: https://nodejs.org/en/docs/inspector
[0-0] afterTest
[0-0] Error in "My Login application should login with valid credentials"
    at <Jasmine>
    at UserContext.<anonymous> (file:///Users/hananargov/Documents/wdio/test/specs/test.e2e.ts:14:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0] 2023-08-22T02:21:32.118Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-08-22T02:21:32.118Z INFO webdriver: [DELETE] http://0.0.0.0:53838/session/09546e2d9277632236a20dd8a6a33e2a
[0-0] 2023-08-22T02:21:32.119Z INFO @moroo/wdio-slack-reporter: Start Synchronising...
[0-0] 2023-08-22T02:21:32.120Z INFO @moroo/wdio-slack-reporter: POST Slack Request webhook:send
[0-0] 2023-08-22T02:21:32.177Z INFO webdriver: RESULT null
[0-0] 2023-08-22T02:21:32.177Z INFO webdriver: Kill /var/folders/mj/s4sjm80d14sggxry24xb2yx40000gp/T/chromedriver/mac-116.0.5845.96/chromedriver-mac-x64/chromedriver driver process with command line: --port=53838 --allowed-origins=* --allowed-ips=
[0-0] 2023-08-22T02:21:32.180Z ERROR @moroo/wdio-slack-reporter: false
[0-0] 2023-08-22T02:21:32.281Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:32.382Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:32.482Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:32.584Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:32.684Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:32.797Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:32.803Z INFO @moroo/wdio-slack-reporter: POST Slack Request webhook:send
[0-0] 2023-08-22T02:21:32.898Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:32.998Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:33.098Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:33.198Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:33.298Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-08-22T02:21:33.320Z INFO @moroo/wdio-slack-reporter: End Synchronising!!!
[0-0] RETRYING in chrome - file:///test/specs/test.e2e.ts (2 retries)
2023-08-22T02:21:34.253Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-08-22T02:21:34.255Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-08-22T02:21:34.255Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] For help, see: https://nodejs.org/en/docs/inspector
[0-0] Debugger ending on ws://127.0.0.1:53877/06885900-da23-4c61-b3ce-d74b8a0449c4
[0-0] For help, see: https://nodejs.org/en/docs/inspector
^C

Ended WebDriver sessions gracefully after a SIGINT signal was received!
2023-08-22T02:21:35.430Z INFO @wdio/local-runner: Shutting down spawned worker

[0-0] RETRYING (3 retries)                                                                                                                                                                                
2023-08-22T02:21:35.450Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-08-22T02:21:35.450Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 116.0.5845.96 mac os x #0-0] Running: chrome (v116.0.5845.96) on mac os x
[chrome 116.0.5845.96 mac os x #0-0] Session ID: 23b0e9ca4c78df197ee982d524dd9460
[chrome 116.0.5845.96 mac os x #0-0]
[chrome 116.0.5845.96 mac os x #0-0] » file:///test/specs/test.e2e.ts
[chrome 116.0.5845.96 mac os x #0-0] My Login application
[chrome 116.0.5845.96 mac os x #0-0]    ✖ should login with valid credentials
[chrome 116.0.5845.96 mac os x #0-0]
[chrome 116.0.5845.96 mac os x #0-0] 1 failing (34.7s)
[chrome 116.0.5845.96 mac os x #0-0]
[chrome 116.0.5845.96 mac os x #0-0] 1) My Login application should login with valid credentials
[chrome 116.0.5845.96 mac os x #0-0] Expected true to be falsy.      
      actual expected
      
      true[]
      
[chrome 116.0.5845.96 mac os x #0-0]     at <Jasmine>
[chrome 116.0.5845.96 mac os x #0-0]     at UserContext.<anonymous> (file:///Users/hananargov/Documents/wdio/test/specs/test.e2e.ts:14:18)
[chrome 116.0.5845.96 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
------------------------------------------------------------------
[chrome 116.0.5845.96 mac os x #0-0] Running: chrome (v116.0.5845.96) on mac os x
[chrome 116.0.5845.96 mac os x #0-0] Session ID: 9c0649f93f9d147f555c1800a87c5eb1
[chrome 116.0.5845.96 mac os x #0-0]
[chrome 116.0.5845.96 mac os x #0-0] » file:///test/specs/test.e2e.ts
[chrome 116.0.5845.96 mac os x #0-0] My Login application
[chrome 116.0.5845.96 mac os x #0-0]    ✖ should login with valid credentials
[chrome 116.0.5845.96 mac os x #0-0]
[chrome 116.0.5845.96 mac os x #0-0] 1 failing (1m 9.2s)
[chrome 116.0.5845.96 mac os x #0-0]
[chrome 116.0.5845.96 mac os x #0-0] 1) My Login application should login with valid credentials
[chrome 116.0.5845.96 mac os x #0-0] Expected true to be falsy.      
      actual expected
      
      true[]
      
[chrome 116.0.5845.96 mac os x #0-0]     at <Jasmine>
[chrome 116.0.5845.96 mac os x #0-0]     at UserContext.<anonymous> (file:///Users/hananargov/Documents/wdio/test/specs/test.e2e.ts:14:18)
[chrome 116.0.5845.96 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
------------------------------------------------------------------
[chrome 116.0.5845.96 mac os x #0-0] Running: chrome (v116.0.5845.96) on mac os x
[chrome 116.0.5845.96 mac os x #0-0] Session ID: 09546e2d9277632236a20dd8a6a33e2a
[chrome 116.0.5845.96 mac os x #0-0]
[chrome 116.0.5845.96 mac os x #0-0] » file:///test/specs/test.e2e.ts
[chrome 116.0.5845.96 mac os x #0-0] My Login application
[chrome 116.0.5845.96 mac os x #0-0]    ✖ should login with valid credentials
[chrome 116.0.5845.96 mac os x #0-0]
[chrome 116.0.5845.96 mac os x #0-0] 1 failing (52s)
[chrome 116.0.5845.96 mac os x #0-0]
[chrome 116.0.5845.96 mac os x #0-0] 1) My Login application should login with valid credentials
[chrome 116.0.5845.96 mac os x #0-0] Expected true to be falsy.      
      actual expected
      
      true[]
      
[chrome 116.0.5845.96 mac os x #0-0]     at <Jasmine>
[chrome 116.0.5845.96 mac os x #0-0]     at UserContext.<anonymous> (file:///Users/hananargov/Documents/wdio/test/specs/test.e2e.ts:14:18)
[chrome 116.0.5845.96 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)


Spec Files:      0 passed, 4 retries, 1 total (0% completed) in 00:03:03
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by HananArgov** [comment]
iirc, I remember this since the beginning of wdio v8

**Comment by HananArgov** [comment]
i've gotten to this:
https://github.com/webdriverio/webdriverio/blob/1940c54e5537d54b5ecda24179285d5a5c3e88a1/packages/wdio-utils/src/test-framework/testFnWrapper.ts#L55
but it seems that `repeatTest` is always 0 from Jasmine (or i'm missing something), and the attempts is set to always be 0 as well

**Comment by christian-bromann** [comment]
I am not sure what the bug is, can you provide an issue title and update the description. Ideally a reproducible example would be good too.

**Comment by HananArgov** [comment]
sorry about this, i've filled the form, but forgot the title 😅
i'll update the description as well

**Comment by HananArgov** [comment]
i've put this in the description. anything else I need to put?
### How to reproduce the bug.
**1. use the initiated wdio, with jasmine framework.
2. in wdio.conf set `specFileRetries` to any number of retries (doesn't matter how many)
3. in wdio.conf setafterTest, for an example, put the following code:**
```
  afterTest: function (test, context, { error, result, duration, passed, retries }) {
    console.log('retries:', retries);
  },
```

**Comment by christian-bromann** [comment]
> anything else I need to put?

How does the test need to look like?

**Comment by erwinheitzman** [comment]
The afterWorker hook shows the retries but instead of increasing it decreases from the amount of specFileRetries to 0.
The afterTest hook does not show retries since you aren't rerunning the test but the whole file (aka suite).
The other hooks do not show any retries from what I can tell.

**Comment by HananArgov** [comment]
> The afterWorker hook shows the retries but instead of increasing it decreases from the amount of specFileRetries to 0. The afterTest hook does not show retries since you aren't rerunning the test but the whole file (aka suite). The other hooks do not show these retries from what I can tell.

@erwinheitzman 
so this means that for jasmine, `afterTest` and `after` the retries will always have `{ attempts: 0, limit: 0 }`?
and if I want to see in which retry the spec is in, I need to look at afterWorker?

if I understood correctly, if I want to send an alert with the info of how many times a test failed, with the errors themselves, i'll need to save the error in the `afterTest`, and then bring it back in the `afterWorker`

**Comment by christian-bromann** [comment]
@erwinheitzman is correct. The retry object in the `afterTest` hook is for test block retries, see https://webdriver.io/docs/retry/#rerun-single-tests-in-jasmine-or-mocha , e.g.:

```ts
describe('My Login application', () => {
    let retryCount = 0
    it('should login with valid credentials', async () => {
        if (retryCount === 2) {
            return 'success'
        }
        
        ++retryCount
        throw new Error('Bug')
    }, jasmine.DEFAULT_TIMEOUT_INTERVAL, 3)
})
```

If you log the retry object in the `afterTest` hook it will return `{ attempts: 2, limit: 3 }`. `specFileRetries` are rerunning the whole file so it wouldn't make much sense to report this on individual test block level. I will push a commit to clarify this in the documentation.

**Comment by christian-bromann** [comment]
This was definitely poorly documented. Hope it is much clearer now. Thanks @HananArgov for pointing this out.

**Comment by HananArgov** [comment]
thank you very much, and sorry for not explaining the issue clearer at first
