### ISSUE TITLE
[🐛 Bug]: <Allure Report showing passed for failed expect()>

### ISSUE THREAD

**Issue by bhanuagarwal73** [webdriverio/webdriverio#11024]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.15.9

### Node.js Version

18.17.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{

        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 3,
        //
        browserName: runtimeArgs.browserName,
        browserVersion: runtimeArgs.browserVersion,
        acceptInsecureCerts: true,

        "goog:chromeOptions": {
            "args": ["user-agent=gcp-automation-test (Windows NT)",
                `${process.env.HEADLESS === 'true' ? '--headless' : undefined}`,
                `${process.env.HEADLESS === 'true' ? '--disable-dev-shm-usage' : undefined}`,
                `${process.env.HEADLESS === 'true' ? '--no-sandbox' : undefined}`,
                `${process.env.HEADLESS === 'true' ? '--window-size=1920,1080' : undefined}`
            ]
        },

        "bstack:options": runtimeArgs.service === 'browserstack' ? {
            "projectName": "merx-shopify-automation",
            "buildName": `${runtimeArgs.env} - ${runtimeArgs.brand} - ${runtimeArgs.suite} - ${runtimeArgs.browserName}`,
            "os": runtimeArgs.os,
            "osVersion": runtimeArgs.osVersion,
            "deviceName": runtimeArgs.device,
            "networkLogs": true,
            "consoleLogs": "errors",
            "browserVersion": "latest",
            "local": true
        } : {}
    }]
```

### What happened?

Allure report showing test case as passed though expect() condition failed.
I checked the logs & found that the test failed as expected & the report I created also showing the same --> so wdioReporter is showing the results great & issue with allure reports only.

![image](https://github.com/webdriverio/webdriverio/assets/38572421/2d866538-fd06-4083-8b77-5c1136cc039e)
![image](https://github.com/webdriverio/webdriverio/assets/38572421/a965745b-ca66-48cb-9955-378e3952aaf3)
![image](https://github.com/webdriverio/webdriverio/assets/38572421/498e6f7b-1877-4d38-932d-e77921dffba2)

Even the steps getting missed in allure reports for such tests.

### What is your expected behavior?

Test should failed in allure reports & should have all the steps.

### How to reproduce the bug.

You need to fail the expect condition as expect(element).toHaveTextContaining(text);

### Relevant log output

```typescript
Expected: "Afterpay"
Received: undefined
[chrome 116.0.5845.96 linux #0-2] Error: Expect $(`//div[contains(@class, 'footer')]//p[contains(text(),'Afterpay')]`) to have text containing
[chrome 116.0.5845.96 linux #0-2]
[chrome 116.0.5845.96 linux #0-2] Expected: "Afterpay"
[chrome 116.0.5845.96 linux #0-2] Received: undefined
[chrome 116.0.5845.96 linux #0-2]     at PaymentPage.<anonymous> (/tmp/workspace/Automation-Jobs/merx-shopify-automation/src/pageobjects/paymentPage.page.ts:184:65)
[chrome 116.0.5845.96 linux #0-2]     at Generator.next (<anonymous>)
[chrome 116.0.5845.96 linux #0-2]     at fulfilled (/tmp/workspace/Automation-Jobs/merx-shopify-automation/src/pageobjects/paymentPage.page.ts:5:58)
[chrome 116.0.5845.96 linux #0-2]     at runMicrotasks (<anonymous>)
[chrome 116.0.5845.96 linux #0-2]     at processTicksAndRejections (node:internal/process/task_queues:96:5)


Spec Files:	 5 passed, 1 failed, 6 total (100% completed) in 00:19:56
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
@bhanuagarwal73 We need a reproducible example. Not your whole `merx-shopify-automation` repo, but an SSCCE (Short, Self Contained, Correct
 Example), see http://sscce.org/

**Comment by bhanuagarwal73** [comment]
5 mins, I will post the repo link & command

**Comment by bhanuagarwal73** [comment]
As I can see this issue is happening when connection is getting lost from browserstack side.

As of now, its difficult to post the project link but you can try by making connection lost from browserstack.

**Comment by BorisOsipov** [comment]
> its difficult to post the project link

You do not need to publish your project, instead you can simply create a new project from scratch https://webdriver.io/docs/gettingstarted, create some specs to reproduce the problem and publish the repo.

>you can try by making connection lost from browserstack.

No one will waste time on this.

**Comment by christian-bromann** [comment]
Closing due to inactivity. Happy to re-open if a minimal reproducible example can be provided.

**Comment by bhanuagarwal73** [comment]
Not seeing this issue now. Seems issue with old allure-command-line package.

**Comment by christian-bromann** [comment]
Thanks for confirming!
