### ISSUE TITLE
wdio - Object #<Object> has no method 'isAbsolute'

### ISSUE THREAD

**Issue by dmfranko** [webdriverio/webdriverio#1102]
Hello,

I just installed webdriverio v4.03 and I'm having an issue when I try to run my test.  Here's what I did:

- Created a new config using wdio
- Created a file called test.js, the code is the example from the webdriverio page
- Changed the config to target specs '/tmp/test.js'
- Run wdio wdio.config.js from my current directory

`/usr/lib/node_modules/webdriverio/build/lib/cli.js:359
            throw e;
                  ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at /usr/lib/node_modules/webdriverio/build/lib/utils/ConfigParser.js:298:50
    at Array.map (native)
    at Function.getFilePaths (/usr/lib/node_modules/webdriverio/build/lib/utils/ConfigParser.js:297:43)
    at ConfigParser.getSpecs (/usr/lib/node_modules/webdriverio/build/lib/utils/ConfigParser.js:227:38)
    at Launcher.run$ (/usr/lib/node_modules/webdriverio/build/lib/launcher.js:237:58)
    at tryCatch (/usr/lib/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/lib/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/usr/lib/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/usr/lib/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:146:20)`

**Comment by dmfranko** [comment]
Needed to upgrade node.  Sorry about that!
