### ISSUE TITLE
[🐛 Bug]: Too many screen attempts after timeouts on android

### ISSUE THREAD

**Issue by pkboom** [webdriverio/webdriverio#11058]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.13.13

### Node.js Version

20.5.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  platformName: 'Android',
  'appium:options': {
    automationName: 'UiAutomator2',
    noReset: true,
    uiautomator2ServerReadTimeout: 10000,
    adbExecTimeout: 10000,
    uiautomator2ServerLaunchTimeout: 10000,
  },
}
```

### What happened?

Sometimes screenshot times out and my app keeps trying to take a screenshot too many times. It takes almost 3 minutes until it stops doing it and restarts a new session. I don’t mind it timing out. But I don’t understand why it takes about 3 minutes before it gives up? Please help me with this.

### What is your expected behavior?

Once screenshot times out, it should stop trying taking a screenshot again and again.

### How to reproduce the bug.

> Nothing much here. Just we just take a screenshot of an android.

```
const { remote } = require('webdriverio')
...

let driver = await remote({ options })
...
let image = driver.takeScreenshot() <- It repeats taking a screenshot after timing out.
...
```

### Relevant log output

```typescript
2023-08-30 12:54:41:626 [HTTP] --> GET /session/ea0e9c7f-4295-4fd8-8143-4a39cee48214/screenshot
2023-08-30 12:54:41:626 [HTTP] {}
2023-08-30 12:54:41:626 [AndroidUiautomator2Driver@78da (ea0e9c7f)] Calling AppiumDriver.getScreenshot() with args: ["ea0e9c7f-4295-4fd8-8143-4a39cee48214"]
2023-08-30 12:54:41:627 [AndroidUiautomator2Driver@78da (ea0e9c7f)] Matched '/screenshot' to command name 'getScreenshot'
2023-08-30 12:54:41:627 [AndroidUiautomator2Driver@78da (ea0e9c7f)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8202/session/9621984f-af5d-4cbf-8b0a-b12ec6c7c7c2/screenshot] with no body
2023-08-30 12:54:51:652 [AndroidUiautomator2Driver@78da (ea0e9c7f)] AxiosError: timeout of 10000ms exceeded
2023-08-30 12:54:51:652 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at RedirectableRequest.handleRequestTimeout (/opt/homebrew/lib/node_modules/appium/node_modules/axios/lib/adapters/http.js:628:16)
2023-08-30 12:54:51:652 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at RedirectableRequest.emit (node:events:512:28)
2023-08-30 12:54:51:652 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at Timeout.<anonymous> (/opt/homebrew/lib/node_modules/appium/node_modules/follow-redirects/index.js:169:12)
2023-08-30 12:54:51:652 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at listOnTimeout (node:internal/timers:573:17)
2023-08-30 12:54:51:652 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at processTimers (node:internal/timers:514:7)
2023-08-30 12:54:51:656 [AndroidUiautomator2Driver@78da (ea0e9c7f)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 10000ms exceeded
2023-08-30 12:54:51:656 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at UIA2Proxy.command (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)
2023-08-30 12:54:51:656 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at runNextTicks (node:internal/process/task_queues:60:5)
2023-08-30 12:54:51:656 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at listOnTimeout (node:internal/timers:540:9)
2023-08-30 12:54:51:656 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at processTimers (node:internal/timers:514:7)
2023-08-30 12:54:51:656 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at AndroidUiautomator2Driver.commands.getScreenshot (/Users/rendering/.appium/node_modules/appium-uiautomator2-driver/lib/commands/screenshot.js:18:10)
2023-08-30 12:54:51:657 [HTTP] <-- GET /session/ea0e9c7f-4295-4fd8-8143-4a39cee48214/screenshot 500 10031 ms - 877
2023-08-30 12:57:36:455 [HTTP] 
...
**This repeats 14 times here
...
2023-08-30 12:57:40:474 [HTTP] --> GET /session/ea0e9c7f-4295-4fd8-8143-4a39cee48214/screenshot
2023-08-30 12:57:40:474 [HTTP] {}
2023-08-30 12:57:40:474 [AndroidUiautomator2Driver@78da (ea0e9c7f)] Calling AppiumDriver.getScreenshot() with args: ["ea0e9c7f-4295-4fd8-8143-4a39cee48214"]
2023-08-30 12:57:40:474 [AndroidUiautomator2Driver@78da (ea0e9c7f)] Matched '/screenshot' to command name 'getScreenshot'
2023-08-30 12:57:40:474 [AndroidUiautomator2Driver@78da (ea0e9c7f)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8202/session/9621984f-af5d-4cbf-8b0a-b12ec6c7c7c2/screenshot] with no body
2023-08-30 12:57:50:476 [AndroidUiautomator2Driver@78da (ea0e9c7f)] AxiosError: timeout of 10000ms exceeded
2023-08-30 12:57:50:476 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at RedirectableRequest.handleRequestTimeout (/opt/homebrew/lib/node_modules/appium/node_modules/axios/lib/adapters/http.js:628:16)
2023-08-30 12:57:50:476 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at RedirectableRequest.emit (node:events:512:28)
2023-08-30 12:57:50:476 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at Timeout.<anonymous> (/opt/homebrew/lib/node_modules/appium/node_modules/follow-redirects/index.js:169:12)
2023-08-30 12:57:50:476 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at listOnTimeout (node:internal/timers:573:17)
2023-08-30 12:57:50:476 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at processTimers (node:internal/timers:514:7)
2023-08-30 12:57:50:477 [AndroidUiautomator2Driver@78da (ea0e9c7f)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 10000ms exceeded
2023-08-30 12:57:50:477 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at UIA2Proxy.command (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:355:13)
2023-08-30 12:57:50:477 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at runNextTicks (node:internal/process/task_queues:60:5)
2023-08-30 12:57:50:477 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at listOnTimeout (node:internal/timers:540:9)
2023-08-30 12:57:50:477 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at processTimers (node:internal/timers:514:7)
2023-08-30 12:57:50:477 [AndroidUiautomator2Driver@78da (ea0e9c7f)]     at AndroidUiautomator2Driver.commands.getScreenshot (/Users/rendering/.appium/node_modules/appium-uiautomator2-driver/lib/commands/screenshot.js:18:10)
2023-08-30 12:57:50:477 [HTTP] <-- GET /session/ea0e9c7f-4295-4fd8-8143-4a39cee48214/screenshot 500 10003 ms - 877
2023-08-30 12:57:50:477 [HTTP] 
2023-08-30 12:58:21:960 [Logcat] Logcat terminated with code 0, signal null
2023-08-30 12:58:21:961 [Logcat] Logcat terminated with code 0, signal null
2023-08-30 12:58:21:961 [Instrumentation] The process has exited with code 0
2023-08-30 12:58:21:961 [Logcat] Logcat terminated with code 0, signal null
2023-08-30 12:58:51:181 [Appium] Received SIGINT - shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@pkboom thanks for raising the issue.

Unfortunately there is nothing we can do on the WebdriverIO side to resolve this problem. As you can see WebdriverIO correctly sends a command request which is detected by Appium. However it seems to timeout there for some reasons. I would recommend to raise this issue in the Appium project.

Sorry we couldn't help you out. If you have further questions, feel free to join our [discord server](https://discord.webdriver.io).
