### ISSUE TITLE
[🐛 Bug]: Saucelab got ESM dynamic import

### ISSUE THREAD

**Issue by borracciaBlu** [webdriverio/webdriverio#11077]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v18.17.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  "browserName": 'MicrosoftEdge',
  "browserVersion": 'latest',
  "platformName": 'Windows 10',
  'sauce:options': {build: `${now}`, },
},
{
    browserName: 'chrome',
    browserVersion: '75',
    platformName: 'Windows 10',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'chrome',
    browserVersion: 'latest',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'chrome',
    browserVersion: 'latest',
    platformName: 'macOS 10.15',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'firefox',
    browserVersion: '55',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'firefox',
    browserVersion: 'latest',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'firefox',
    browserVersion: 'latest',
    platformName: 'Windows 10',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'firefox',
    browserVersion: 'latest',
    platformName: 'macOS 10.15',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'safari',
    browserVersion: '11',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'safari',
    browserVersion: '12',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'safari',
    browserVersion: '13',
    platformName: 'Mac 10.15',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'safari',
    browserVersion: '14',
    platformName: 'Mac 11.00',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'safari',
    browserVersion: 'latest',
    platformName: 'macOS 10.15',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'internet explorer',
    browserVersion: '10',
    platformName: 'Windows 2012',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'internet explorer',
    browserVersion: '11',
    platformName: 'Windows 10',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '13',
    platformName: 'Windows 10',
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '14',
    platformName: 'Windows 10',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '15',
    platformName: 'Windows 10',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '16',
    platformName: 'Windows 10',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '17',
    platformName: 'Windows 10',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '18',
    platformName: 'Windows 10',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '79',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '80',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '81',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '84',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '85',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '86',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: '87',
    platformName: 'Mac 10.13',
    'sauce:options': {build: `${now}`, },
},
{
    browserName: 'MicrosoftEdge',
    browserVersion: 'latest',
    platformName: 'macOS 10.15',
    'sauce:options': {build: `${now}`, },
},
{
    'browserName':'Safari',
    'appium:deviceName':'iPhone XS Simulator',
    'appium:platformVersion':'14.0',
    'platformName':'iOS',
    'sauce:options': {
        build: `${now}`,
        appiumVersion: '1.19.1'
    },
},
{
    'browserName':'Safari',
    'appium:deviceName':'iPhone XS Simulator',
    'appium:platformVersion':'12.0',
    'platformName':'iOS',
    'sauce:options': {
        build: `${now}`,
        appiumVersion: '1.9.1'
    },
},
{
    browserName: 'browser',
    'appium:platformVersion': '5.1',
    'appium:deviceName': 'Android Emulator',
    platformName: 'Android',
    'sauce:options': {
        build: `${now}`,
        appiumVersion: '1.18.1'
    },
},
{
    browserName: 'Chrome',
    'appium:platformVersion': '8.0',
    'appium:deviceName': 'Android Emulator',
    platformName: 'Android',
    'sauce:options': {
        build: `${now}`,
        appiumVersion: '1.18.1'
    },
},
{
    browserName: 'Chrome',
    'appium:platformVersion': '11.0',
    'appium:deviceName': 'Android GoogleAPI Emulator',
    platformName: 'Android',
    'sauce:options': {
        build: `${now}`,
        appiumVersion: '1.18.1'
    },
},
```

### What happened?

```
> @borracciablu/dh-addeventlistener@1.0.271 saucelab
> wdio wdio.conf.js


Execution of 34 workers started at 2023-09-04T00:45:35.39[6](https://github.com/borracciaBlu/dh-addeventlistener/actions/runs/6067743581/job/16459803869#step:6:7)Z

2023-09-04T00:45:35.449Z INFO @wdio/local-runner: Shutting down spawned worker
/home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/build/index.js:10
var _got = _interopRequireDefault(require("got"));
                                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/node_modules/got/dist/source/index.js from /home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/build/index.js not supported.
Instead change the require of /home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/node_modules/got/dist/source/index.js in /home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/build/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/build/index.js:10:35) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.1[7](https://github.com/borracciaBlu/dh-addeventlistener/actions/runs/6067743581/job/16459803869#step:6:8).1
Error: Process completed with exit code 1.
```

### What is your expected behavior?

I see that `saucelabs` is  using `got` with require and the runner is expecting an ESM module.

### How to reproduce the bug.

in pipeline using latest packages.

[see](https://github.com/borracciaBlu/dh-addeventlistener/actions/runs/6067743581/job/16459803869#step:6:24)

### Relevant log output

```typescript
> @borracciablu/dh-addeventlistener@1.0.271 saucelab
> wdio wdio.conf.js


Execution of 34 workers started at 2023-09-04T00:45:35.396Z

2023-09-04T00:45:35.449Z INFO @wdio/local-runner: Shutting down spawned worker
/home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/build/index.js:10
var _got = _interopRequireDefault(require("got"));
                                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/node_modules/got/dist/source/index.js from /home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/build/index.js not supported.
Instead change the require of /home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/node_modules/got/dist/source/index.js in /home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/build/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/dh-addeventlistener/dh-addeventlistener/node_modules/saucelabs/build/index.js:10:35) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.17.1
Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by shlomo100** [comment]
I also get this error 

```
Error [ERR_REQUIRE_ESM]: require() of ES Module not supported.
Instead change the require of to a dynamic import() which is available in all CommonJS modules.
```

**Comment by shlomo100** [comment]
Update: This worked for me .
Added to package.json 
```js
"overrides": {
    "saucelabs": "7.2.2"
  }
  ```

**Comment by christian-bromann** [comment]
I raised an issue in the Sauce Labs package. Thanks for providing a workaround. Once this has been fixed on their side this should be resolved. In the meantime I will pin the version of it in the `@wdio/sauce-service` to the one that works.
