### ISSUE TITLE
[💡 Feature]: Align parallel implemention with Cucumber API

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#11101]
### Is your feature request related to a problem?

Since we enabled the Cucumber API to run the tests in #11069 ( and #11067, #11065 , #11010) we are disabling the native parallel implementation for Cucumber, meaning that for each WDIO worker, we invoke `runCucumber` and create an entire Cucumber test run.

That introduces many redundancies when taking advantage of many built-in features of Cucumber.
- If enabled with option `publish`, each WDIO worker indirectly publishes a Cucumber.IO report, instead of having just one per WDIO test run
- Any formatters/reporters that users specify in the configs Cucumber options will generate a set of different outcomes and consolidating that data is either not feasable or not small of a task (i.e. 20 specs trigger 20 HTML reports)

[List of native Cucumber formatters/reporters](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md)

We should take into account that Cucumber hooks can and often do reference the `@wdio/globals`, therefore on top of importing support code we must pass this context to the workers as well, otherwise we can run into reference errors such as 
```shell

Error: No browser instance registered. Don't import @wdio/globals outside of the WDIO testrunner context. Or you have two two different "@wdio/globals" packages installed.
    at Object.get (file:///Users/user/repos/repo/node_modules/@wdio/globals/build/index.js:15:23)
    at Scenario.doStuff (file:///Users/user/repos/repo/e2e/steps/hooks.steps.ts:49:36)
```

We must also consider aligning the WDIO retry mechanism with the Cucumber retry mechanism.

### Describe the solution you'd like.

It should just work, no redundancies should be in place.

When WDIO users specify X `maxInstances`, the Cucumber parallel optional should be enabled and a maximum of X Cucumber workers wrapped in WDIO workers should run seamlessly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@nextlevelbeard can you speak a little bit about how the native parallel implementation for Cucumber differs to the WebdriverIO one? Does it support running Scenarios in parallel as well?

**Comment by jan-molak** [comment]
@nextlevelbeard please note that the Cucumber `publishQuiet` option was [deprecated](https://github.com/cucumber/cucumber-js/blob/c1784c46965e83227fd4f8632dc18fe0a2099c59/docs/deprecations.md?plain=1#L49-L55), and `publish` doesn't seem to be actively promoted by the team either, so its future is rather unclear.

The parallel execution mode is an interesting aspect, though. You might be interested in  https://github.com/cucumber/cucumber-js/issues/2156 when considering your design approach, as I highlighted there several limitations concerning parallel execution via Cucumber. There's also https://github.com/cucumber/cucumber-js/issues/1711 where we talked about options for running Cucumber programmatically. There's also https://github.com/serenity-js/serenity-js/issues/1308 that started some of those conversations.

**Comment by christian-bromann** [comment]
I feel inclined to close this issue since I don't see a way to support this since Cucumber spins up multiple processes to execute itself in parallel and that is just not feasible given that WebdriverIO has to orchestrate this. I am happy to discuss the feature of running multiple scenarios in within a single spec in parallel. This however has been discussed in length in https://github.com/webdriverio/webdriverio/issues/3962 and we came to the conclusion that a file based parallelism approach seems to be the best approach. That said, if there are strong opinions and interest in a higher parallelization degree, I am all open for new discussions.

**Comment by jan-molak** [comment]
@christian-bromann & @nextlevelbeard - see https://github.com/cucumber/cucumber-js/discussions/2357

**Comment by christian-bromann** [comment]
if Cucumber makes orchestrating this easier, I am happy to bring this back.

**Comment by tibioneh** [comment]
This would indeed be a very useful feature.

**Comment by christian-bromann** [comment]
@tibioneh can you comment on why? Note that you have the option to split your scenarios in multiple feature file. Furthermore a lot of time is spend starting and stopping the browser, so we you run many small scenarios in parallel you won't be gaining much time. Can you elaborate on that?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
