### ISSUE TITLE
[🐛 Bug]: Error fetching Chrome version on headless Chromium in @wdio/utils 

### ISSUE THREAD

**Issue by longfeiwAmazonDE** [webdriverio/webdriverio#11113]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.15.10

### Node.js Version

v18.x

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: "chrome",
    goog:chromeOptions: {
        binary: "path/to/executable/chromium/headless_shell"
    }
}
```

### What happened?

When using `webdriverio` v8.15.10 with a headless Chromium browser, the `@wdio/utils` package attempts to fetch the Chrome version using the command `cp.execSync("${chromePath}" --version").toString()`. However, this command fails when running headless Chromium, resulting in the following error:
> Error: Command failed: "/tmp/chromium/chromium" --version.

We also tried Chromium@118 provided from [`@puppeteer/browsers`](https://www.npmjs.com/package/@puppeteer/browsers) and the same error occurred. 

### What is your expected behavior?

Be able to talk to the browser.

### How to reproduce the bug.

1. Set up a project with `webdriverio` v8.15.10
2. Configure the project to use a headless Chromium browser
3. Run a test

### Relevant log output

```typescript
Execution of 1 workers started at 2023-09-07T08:48:46.773Z
2023-09-07T08:48:49.861Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2023-09-07T08:48:49.946Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
[0907/084849.963224:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
2023-09-07T08:48:49.965Z INFO @wdio/local-runner: Shutting down spawned worker
2023-09-07T08:48:50.216Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-09-07T08:48:50.217Z INFO @wdio/local-runner: shutting down
"Error: Error: Command failed: ""/tmp/chromium/chromium"" --version"
[0907/084849.963224:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at getBuildIdByChromePath (file:/path_to/node_modules/@wdio/utils/build/driver/utils.js:41:30)
    at setupPuppeteerBrowser (file:/path_to/node_modules/@wdio/utils/build/driver/utils.js:86:19)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Launcher.run (file://path_to/node_modules/@wdio/cli/build/launcher.js:98:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by longfeiwAmazonDE** [comment]
Hi @christian-bromann , thanks for addressing this issue with `--no-sandbox` flag in the recent PR. We tried the flag locally by using the `path_to_chromium/chromium --version --no-sandbox` as indicated, but unfortunately the execution still hung. 
While we appreciate the efforts to resolve the issue, it seems that this particular fix might not address the root cause of the problem in all scenarios. We would like to follow up if further investigation will be made?

**Comment by christian-bromann** [comment]
> We would like to follow up if further investigation will be made?

Note that this patch has not been released yet. Could you provide more information about your environment?

**Comment by arnulfojr** [comment]
@christian-bromann For the set up we are simply providing the headless_shell in a given path, we compile our own version of the chromium's headless_shell, right now are not planning on using the `@puppeteer/browsers` (https://googlechromelabs.github.io/chrome-for-testing/), maybe in the future but for now we are providing the binary ourselves.

headless_shell does not have a full CLI as full-fledge Chromium or CfT, so calling the binary will start the headless_shell as a long running process and won't return.

**Comment by christian-bromann** [comment]
@arnulfojr understand. Without the binary I can't really tell why the browser is hanging. It seems that the best for you is to provide a custom browser path as well as a custom driver path that to a Chromedriver that matches your Chromium version. Let me know if I can answer further questions.

**Comment by arnulfojr** [comment]
@christian-bromann oh I somehow missed the new documentation around this, yea passing the chromedriver path should do the trick. We will give it a go!

https://webdriver.io/docs/driverbinaries#customizing-the-level-of-automation
