### ISSUE TITLE
[🐛 Bug]: TypeError: console_1.Console is not a constructor

### ISSUE THREAD

**Issue by jarrrule** [webdriverio/webdriverio#11159]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.6

### Node.js Version

18.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome'
    }],
```

### What happened?

I followed the `Getting Started` documentation using the wizard which generates the below `package.json`
```
{
  "name": "my-new-project",
  "type": "module",
  "devDependencies": {
    "@wdio/browserstack-service": "^8.16.6",
    "@wdio/cli": "^8.16.6",
    "@wdio/cucumber-framework": "^8.16.6",
    "@wdio/local-runner": "^8.16.6",
    "@wdio/spec-reporter": "^8.16.3"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.conf.js"
  }
}
```
Along with the `wdio.conf.js`
```
export const config = {
    runner: 'local',
    user: '**********',
    key: '*********',
    specs: [
        './features/**/*.feature'
    ],
    exclude: [
    ],
    maxInstances: 10,
    capabilities: [{
        browserName: 'chrome'
    }],
    logLevel: 'debug',
    bail: 0,
    baseUrl: 'https://webdriver.io',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['browserstack'],
    framework: 'cucumber',
    reporters: ['spec'],
    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ['./features/step-definitions/steps.js'],
        // <boolean> show full backtrace for errors
        backtrace: false,
        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        requireModule: [],
        // <boolean> invoke formatters without executing steps
        dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <boolean> fail if there are any undefined or pending steps
        strict: false,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: '',
        // <number> timeout for step definitions
        timeout: 60000,
        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false
    }
}
```
When running `npx wdio run ./wdio.conf.js` I receive the error `[0-0]  Error:  console_1.Console is not a constructor`

### What is your expected behavior?

I would expect the code to run through Browserstack and open the baseUrl https://the-internet.herokuapp.com as in the example feature auto generated with the setup. 

Commenting out the Browserstack credentials and services the test executes locally as expected.
```
[chrome 116.0.5845.187 mac os x #0-0] Running: chrome (v116.0.5845.187) on mac os x
[chrome 116.0.5845.187 mac os x #0-0] Session ID: a47385f16f81de2bee010665a3670f97
[chrome 116.0.5845.187 mac os x #0-0]
[chrome 116.0.5845.187 mac os x #0-0] » features/login.feature
[chrome 116.0.5845.187 mac os x #0-0] The Internet Guinea Pig Website
[chrome 116.0.5845.187 mac os x #0-0] As a user, I can log into the secure area
[chrome 116.0.5845.187 mac os x #0-0]    ✓ Given I am on the login page
[chrome 116.0.5845.187 mac os x #0-0]    ✓ When I login with tomsmith and SuperSecretPassword!
[chrome 116.0.5845.187 mac os x #0-0]    ✓ Then I should see a flash message saying You logged into a secure area!
[chrome 116.0.5845.187 mac os x #0-0]
[chrome 116.0.5845.187 mac os x #0-0] As a user, I can log into the secure area
[chrome 116.0.5845.187 mac os x #0-0]    ✓ Given I am on the login page
[chrome 116.0.5845.187 mac os x #0-0]    ✓ When I login with foobar and barfoo
[chrome 116.0.5845.187 mac os x #0-0]    ✓ Then I should see a flash message saying Your username is invalid!
[chrome 116.0.5845.187 mac os x #0-0]
[chrome 116.0.5845.187 mac os x #0-0] 6 passing (2.4s)


Spec Files:	 1 passed, 1 total (100% completed) in 00:00:14 
```

### How to reproduce the bug.

Follow the Getting Started documentation using the wdio wizard with values 

`local` for e2e testing
`browserstack` for automation backend
`cucumber` for framework
`no` for compiler
`test files` yes auto-generate
default for paths
`pageobject` yes
`spec` reporter
`no` plugins

I then installed with `yarn`

`npx wdio run ./wdio.conf.js` results in the error.

### Relevant log output

```typescript
[0-0] 2023-09-13T06:54:09.961Z ERROR @wdio/runner: TypeError: console_1.Console is not a constructor
[0-0]     at new ConsoleLogger (/Users/sean.darley/projects/wdio/node_modules/@cucumber/cucumber/lib/api/console_logger.js:9:24)
[0-0]     at loadConfiguration (/Users/sean.darley/projects/wdio/node_modules/@cucumber/cucumber/lib/api/load_configuration.js:20:20)
[0-0]     at CucumberAdapter.run (file:///Users/sean.darley/projects/wdio/node_modules/@wdio/cucumber-framework/build/index.js:197:48)
[0-0]     at async Runner.run (file:///Users/sean.darley/projects/wdio/node_modules/@wdio/runner/build/index.js:148:24)
[0-0]  Error:  console_1.Console is not a constructor
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by nextlevelbeard** [comment]
Can be fixed by #11146

**Comment by sahmod** [comment]
I an getting the same issue with the following
  "dependencies": {
    "@babel/cli": "^7.22.6",
    "@babel/core": "^7.22.8",
    "@babel/preset-env": "^7.22.7",
    "@babel/register": "^7.22.5",
    "@wdio/cucumber-framework": "^8.16.7",
    "@wdio/allure-reporter": "^8.16.7",
    "@wdio/appium-service": "^8.16.7",
    "@wdio/browserstack-service": "^8.16.7",
    "@wdio/cli": "^8.16.7",
    "@wdio/spec-reporter": "^8.16.7",
    "appium": "^2.0.0-rc.5",
    "webdriverio": "^8.16.7"
  }

**Comment by taniya-senawirathne** [comment]
How can I resolve this issue ?

**Comment by jiten-poi** [comment]
@taniya-senawirathne in the short term, I edited the browserstack-service/build/utils.js file in node_modules, with the fix mentioned by @nextlevelbeard above. It allows me to successfully run the tests on browserstack from my local.
