### ISSUE TITLE
Error: Cannot generate spec hash for runner with no 'specs' key

### ISSUE THREAD

**Issue by Harsha509** [webdriverio/webdriverio#1116]
HI christian-bromann,

As this issue is already has been raised and closed, but i have found no proper solution for Jasmine framework. Am getting this error when i try to run the tests using ..
wdio version : 4.0.3, framework:jasmine, platform Win 7

C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\ReporterStats.js:212
if (!runner.specs) throw Error('Cannot generate spec hash for runner with no \'specs\' key');
^
Error: Cannot generate spec hash for runner with no 'specs' key
at Error (native)
at ReporterStats.getSpecHash (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\ReporterSt
ats.js:212:42)
at ReporterStats.getSpecStats (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\ReporterS
tats.js:227:33)
at ReporterStats.suiteStart (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\ReporterSta
ts.js:239:18)
at BaseReporter. (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\BaseReporte
r.js:134:25)
at emitOne (events.js:77:13)
at BaseReporter.emit (events.js:169:7)
at BaseReporter.handleEvent (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\BaseReporte
r.js:326:27)
at Launcher.messageHandler (C:\Users\Admin\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:469:28
)
at emitTwo (events.js:87:13)

**Comment by dgasi** [comment]
Hi,

I have the same issue on Jasmine framework. As a matter a fact also on mocha same thing happens not able to get rid of this error:

/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:212
                if (!runner.specs) throw Error('Cannot generate spec hash for runner with no \'specs\' key');
                                   ^

Error: Cannot generate spec hash for runner with no 'specs' key
    at Error (native)
    at ReporterStats.getSpecHash (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:212:42)
    at ReporterStats.getSpecStats (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:227:33)
    at ReporterStats.suiteStart (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ReporterStats.js:239:18)
    at BaseReporter.<anonymous> (/usr/local/lib/node_modules/webdriverio/build/lib/utils/BaseReporter.js:134:25)
    at emitOne (events.js:90:13)
    at BaseReporter.emit (events.js:182:7)
    at BaseReporter.handleEvent (/usr/local/lib/node_modules/webdriverio/build/lib/utils/BaseReporter.js:326:27)
    at Launcher.messageHandler (/usr/local/lib/node_modules/webdriverio/build/lib/launcher.js:469:28)
    at emitTwo (events.js:100:13)

It would be great if someone could share the solution for this error. It can't be that we are the only ones having it.
thx.

**Comment by dgasi** [comment]
Hi,

After couple of days of breaking my head what could be wrong finally found the issue.

It's in v.4 of wdio.

Just downgrade to 3.4.0 and no more error message!

BR.

**Comment by susu** [comment]
I have the same problem with cucumber. Unfortunately we cannot downgrade to 3.4.0, because it has a different annoying bug (#888).

**Comment by tom-metz** [comment]
I've been hit by the very same problem. Using webdriver.io 4.0.3, cucumber 0.9.5, wdio-cucumber-framework 0.0.4.

I've been changing the version of the packages, as I've found, that version webdriver.io 3.4.0 should work, but then I receive different error from cucumber: 

`ERROR: Cannot read property 'length' of undefined` from cucumber's cli/configuration.js - the `args` object, which is given to cucumber from wdio is undefined.

I haven't found a working combination of packages so far, looks like dead end for the moment. The tests themselves run and as far as I can check, they run correctly.

**Comment by weisenborn** [comment]
@tom-metz try downgrading to cucumber 0.7.0

**Comment by tom-metz** [comment]
@weisenborn I tried, as I wrote, different error is thrown - the `args` object for Cucumber CLI is undefined.

**Comment by christian-bromann** [comment]
We updated all three framework adapters. This bug should not appear anymore
