### ISSUE TITLE
[🐛 Bug]: Error: Appium exited before timeout

### ISSUE THREAD

**Issue by ErodriguezQA** [webdriverio/webdriverio#11174]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.9

### Node.js Version

20.6.21 - 18.17.1 - 14.21.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        // capabilities for local Appium web tests on an Android Emulator
        platformName: 'Android',
        browserName: 'Chrome',
        'appium:deviceName': 'Nexus 7 (2012) API 30',
        'appium:platformVersion': '12.0',
        'appium:automationName': 'UiAutomator2'
    }
```

### What happened?

I tried to run the example e2e test template on an Android Emulator but it seems to fail anyways. I tried to change to different Node.js versions, deleting Node.js and reinstalling it from scratch and reinstalling Appium but nothing seems to work.

### How to reproduce the bug.

Create a package.json file:

`npm init -y`

Start wdio setup

`npm init wdio .`

Run wdio

`npx wdio`

### Relevant log output

```typescript
`PS C:\Users\erodriguez\Documents\test\wdio-gps> npx wdio

Execution of 1 workers started at 2023-09-15T16:32:57.422Z

2023-09-15T16:32:57.554Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-09-15T16:32:57.562Z INFO @wdio/appium-service: Will spawn Appium process: cmd /c node C:\Users\erodriguez\Documents\test\wdio-gps\node_modules\appium\index.js --base-path /
2023-09-15T16:33:10.509Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Appium exited before timeout (exit code: 1)
    at ChildProcess.<anonymous> (file:///C:/Users/erodriguez/Documents/test/wdio-gps/node_modules/@wdio/appium-service/build/launcher.js:135:22)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

Continue...
2023-09-15T16:33:10.515Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-09-15T16:33:10.518Z INFO @wdio/local-runner: Start worker 0-0 with arg:
[0-0] Error: "ts-node/esm/transpile-only 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
[0-0]     at new NodeError (node:internal/errors:405:5)
[0-0]     at ESMLoader.resolve (node:internal/modules/esm/loader:843:13)
[0-0]     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7)
[0-0] FAILED
2023-09-15T16:33:11.117Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-09-15T16:33:11.118Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:13

2023-09-15T16:33:11.125Z INFO @wdio/local-runner: Shutting down spawned worker
2023-09-15T16:33:11.391Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-09-15T16:33:11.392Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@ErodriguezQA thanks for raising the issue.

It seems that the service doesn't really well propagate the error message here. Could you go into `node_modules/@wdio/appium-service/build/launcher.js` and add a `console.log` in `_startAppium` to see what the `error` object contains in the `process.once('exit', exitCode => {` block?

**Comment by ErodriguezQA** [comment]
Hi there, thank you for the quick reply. This is what the console.log returns:

`<Buffer 1b 5b 33 38 3b 35 3b 30 6d 5b 48 54 54 50 5d 1b 5b 30 6d 20 43 6f 75 6c 64 20 6e 6f 74 20 73 74 61 72 74 20 52 45 53 54 20 68 74 74 70 
20 69 6e 74 65 ... 135 more bytes>`

**Comment by ErodriguezQA** [comment]
To complement, i just used JSON.stringify and it gave me a more detailed output:

`{"type":"Buffer","data":[27,91,51,56,59,53,59,48,109,91,72,84,84,80,93,27,91,48,109,32,67,111,117,108,100,32,110,111,116,32,115,116,97,114,116,32,82,69,83,84,32,104,116,116,112,32,105,110,116,101,114,102,97,99,101,32,108,105,115,116,101,110,101,114,46,32,84,104,101,32,114,101,113,117,101,115,116,101,100,32,112,111,114,116,32,109,97,121,32,97,108,114,101,97,100,121,32,98,101,32,105,110,32,117,115,101,46,32,80,108,101,97,115,101,32,109,97,107,101,32,115,117,114,101,32,116,104,101,114,101,32,105,115,32,110,111,32,111,116,104,101,114,32,105,110,115,116,97,110,99,101,32,111,102,32,116,104,105,115,32,115,101,114,118,101,114,32,114,117,110,110,105,110,103,32,97,108,114,101,97,100,121,46,13,10]}`

**Comment by christian-bromann** [comment]
can you try `console.log(error.toString())`?

**Comment by ErodriguezQA** [comment]
I got this

`[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.`

I'm pretty sure there is no other Appium instance running, i'll try to restart the computer.

**Comment by ErodriguezQA** [comment]
I just restarted my PC but the error seems to persist

**Comment by christian-bromann** [comment]
Do you see your browser responding when opening `http://localhost:4444`? (or whatever port Appium starts on)? Maybe you can define a different port for Appium.

**Comment by ErodriguezQA** [comment]
I changed the port parameter to 25565 on wdio.conf.js but the same error shows up

**Comment by christian-bromann** [comment]
mhm .. that's weird, it seems like Appium is not able to start for other reasons. What happens if you start Appium directly?

**Comment by ErodriguezQA** [comment]
it's seems that appium server is starting with webdriverio but it doesn't shut down. If i start appium with no arguments i get the _EADDRINUSE_ error message, but if i add the _--port_ argument, for example, _--port 8001_, appium starts normally without errors. Still, i don't know why WebDriverIO it's not using the port i gave it on _wdio.conf.js_.

**Comment by christian-bromann** [comment]
How did you set the Appium service?

**Comment by ErodriguezQA** [comment]
i opened the cmd and at first, i runned Appium with just the command _appium_, i got this log:

`C:\Users\erodriguez>appium
[Appium] Welcome to Appium v2.1.3
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at C:\Users\erodriguez\node_modules\appium-xcuitest-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\erodriguez\node_modules\appium-uiautomator2-driver
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
[Appium] Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 0.0.0.0:4723
[debug] [Appium] Error: listen EADDRINUSE: address already in use 0.0.0.0:4723
[debug] [Appium]     at Server.setupListenHandle [as _listen2] (node:net:1751:16)
[debug] [Appium]     at listenInCluster (node:net:1799:12)
[debug] [Appium]     at doListen (node:net:1948:7)
[debug] [Appium]     at processTicksAndRejections (node:internal/process/task_queues:83:21)`

Then, i used `appium --port 8001`, i got this log:

`C:\Users\erodriguez>appium --port 8001
[Appium] Welcome to Appium v2.1.3
[Appium] Non-default server args:
[Appium] {
[Appium]   port: 8001
[Appium] }
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at C:\Users\erodriguez\node_modules\appium-xcuitest-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\erodriguez\node_modules\appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on http://0.0.0.0:8001
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium]        http://192.168.1.9:8001/
[Appium]        http://127.0.0.1:8001/ (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - xcuitest@4.34.1 (automationName 'XCUITest')
[Appium]   - uiautomator2@2.29.6 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.`

**Comment by christian-bromann** [comment]
ok, but how do you set the port in the `wdio.conf.js`?

**Comment by ErodriguezQA** [comment]
directly onto the exports.config located in the file the file

```js
exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    // WebdriverIO supports running e2e tests as well as unit and component tests.
    runner: 'local',
    port: 8001,
...

```

**Comment by christian-bromann** [comment]
You don't want to set the port unless you start Appium manually. The Appium service ensures to start Appium on a specific port and configures your session correctly.

**Comment by ErodriguezQA** [comment]
So, what can i do in this case then?

**Comment by christian-bromann** [comment]
Set the port  for Appium through the service settings:

```ts
services: [['appium', { port: 4567 }]]
```

**Comment by ErodriguezQA** [comment]
I tried that but i got the same error

`[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.`

**Comment by christian-bromann** [comment]
Can you provide the full WebdriverIO logs please?

**Comment by ErodriguezQA** [comment]
`
PS C:\Users\erodriguez\Documents\test\wdio-gps> npx wdio

Execution of 1 workers started at 2023-09-18T14:44:04.377Z

2023-09-18T14:44:04.442Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-09-18T14:44:04.449Z INFO @wdio/appium-service: Will spawn Appium process: cmd /c node C:\Users\erodriguez\Documents\test\wdio-gps\node_modules\appium\index.js --base-path /
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other 
instance of this server running already.

2023-09-18T14:44:12.326Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Appium exited before timeout (exit code: 1)
    at ChildProcess.<anonymous> (file:///C:/Users/erodriguez/Documents/test/wdio-gps/node_modules/@wdio/appium-service/build/launcher.js:136:22)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

Continue...
2023-09-18T14:44:12.331Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-09-18T14:44:12.333Z INFO @wdio/local-runner: Start worker 0-0 with arg:
[0-0] Error: "ts-node/esm/transpile-only 'resolve'" did not call the next hook in its chain and did not explicitly signal a short 
circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
[0-0]     at new NodeError (node:internal/errors:405:5)
[0-0]     at ESMLoader.resolve (node:internal/modules/esm/loader:843:13)
[0-0]     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7)
[0-0] FAILED
2023-09-18T14:44:12.680Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-09-18T14:44:12.681Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:08

2023-09-18T14:44:12.694Z INFO @wdio/local-runner: Shutting down spawned worker
2023-09-18T14:44:12.952Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-09-18T14:44:12.959Z INFO @wdio/local-runner: shutting down
PS C:\Users\erodriguez\Documents\test\wdio-gps> 
`

**Comment by christian-bromann** [comment]
Which Node.js version are you using?

**Comment by ErodriguezQA** [comment]
18.17.1

**Comment by christian-bromann** [comment]
According to the logs you still don't set a `port` property for the service:
> 2023-09-18T14:44:04.449Z INFO @wdio/appium-service: Will spawn Appium process: cmd /c node C:\Users\erodriguez\Documents\test\wdio-gps\node_modules\appium\index.js --base-path /
