### ISSUE TITLE
[🐛 Bug]: Jasmine fails with elem[prop] is not a function in shim.js

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#11200]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.7.1

### Mode

WDIO Testrunner

### What happened?

When I have a failing test I get corrupt results when using Jasmine.

Jasmine output:
```
[0-0] 2023-09-18T12:19:52.679Z INFO webdriver: RESULT You logged into a secure area!
[0-0] ×
[0-0] Error in "My Login application should login with valid credentials"
    at <Jasmine>
    at UserContext.<anonymous> (/Users/erwin/Documents/Development/Personal/fak/test/specs/test.e2e.js:11:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0] 2023-09-18T12:19:53.191Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-09-18T12:19:53.191Z INFO webdriver: [DELETE] http://0.0.0.0:62452/session/afab94ac64e36b3df7289e8e65bbddc9
[0-0] file:///Users/erwin/Documents/Development/Personal/fak/node_modules/@wdio/utils/build/shim.js:197
[0-0]                     return elem[prop](...args);
[0-0]                                      ^
[0-0]
[0-0] TypeError: elem[prop] is not a function
[0-0]     at file:///Users/erwin/Documents/Development/Personal/fak/node_modules/@wdio/utils/build/shim.js:197:38
[0-0]
[0-0] Node.js v18.17.1
[0-0] FAILED in chrome - file:///test/specs/test.e2e.js
```

Mocha output:
```
[chrome 117.0.5938.62 mac os x #0-0] 1) My Login application should login with valid credentials
[chrome 117.0.5938.62 mac os x #0-0] Expect $(`#flash`) to have text containing

- Expected  - 1
+ Received  + 2

- You loggekjhjhd into a secure area!
+ You logged into a secure area!
+ ×
[chrome 117.0.5938.62 mac os x #0-0] Error: Expect $(`#flash`) to have text containing
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] - Expected  - 1
[chrome 117.0.5938.62 mac os x #0-0] + Received  + 2
[chrome 117.0.5938.62 mac os x #0-0]
[chrome 117.0.5938.62 mac os x #0-0] - You loggekjhjhd into a secure area!
[chrome 117.0.5938.62 mac os x #0-0] + You logged into a secure area!
[chrome 117.0.5938.62 mac os x #0-0] + ×
[chrome 117.0.5938.62 mac os x #0-0]     at Context.<anonymous> (/Users/erwin/Documents/Development/Personal/duk/test/specs/test.e2e.js:11:41)
[chrome 117.0.5938.62 mac os x #0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:15
```

### How to reproduce the bug.

Intantiate a new project using `npm init wdio ./path/to/new/project` and chose Jasmine.

Change the following assertion:
```
    await expect(SecurePage.flashAlert).toHaveTextContaining(
      "You logged into a secure area!"
    );
```
to something that will not pass like so:
```
    await expect(SecurePage.flashAlert).toHaveTextContaining(
      "You loggekjhjhd into a secure area!"
    );
```
Now run `npm run wdio`.

### Relevant log output

```typescript
already provided
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
Related to https://github.com/webdriverio/webdriverio/pull/11172/files

The timeout is never cleared, will fix later
