### ISSUE TITLE
[🐛 Bug]: Filtering Cucumber scenario per name should launch only feature with matching scenario

### ISSUE THREAD

**Issue by qaflorent** [webdriverio/webdriverio#11204]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v18.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      browserName: 'chrome',
      'selenoid:options': {
        enableVNC: true,
        screenResolution: '1920x1080x24',
        enableVideo: true,
        sessionTimeout: '5m',
        connectionRetryTimeout: '5m',
        videoScreenSize: '1920x1080'
      },
      'goog:chromeOptions': {
        args: ['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu']
      }
    }
```

### What happened?

When filtering a scenario by name using the `cucumberOpts.name = ['Scenario #1 - File 1'] `, all feature files of my project are launched and the filtering is done after the feature is running. If no scenario matches the filter, there is an error and the feature file failed instead of being skipped and ignore.

Error is 
```
file:///home/florent/Documents/code/app_qa-automation/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:134
[0-1]             this._reject(callback, new TargetCloseError('Target closed'));
[0-1]                                    ^
[0-1] 
[0-1] TargetCloseError: Protocol error (Target.getBrowserContexts): Target closed
[0-1]     at CallbackRegistry.clear (file:///home/florent/Documents/code/app_qa-automation/node_modules/puppeteer-core/src/common/Connection.ts:186:30)
[0-1]     at Connection.#onClose (file:///home/florent/Documents/code/app_qa-automation/node_modules/puppeteer-core/src/common/Connection.ts:360:21)
[0-1]     at WebSocket.<anonymous> (file:///home/florent/Documents/code/app_qa-automation/node_modules/puppeteer-core/src/common/NodeWebSocketTransport.ts:60:22)
[0-1]     at callListener (/home/florent/Documents/code/app_qa-automation/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)
[0-1]     at WebSocket.onClose (/home/florent/Documents/code/app_qa-automation/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:220:9)
[0-1]     at WebSocket.emit (node:events:513:28)
[0-1]     at WebSocket.emit (node:domain:489:12)
[0-1]     at WebSocket.emitClose (/home/florent/Documents/code/app_qa-automation/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:258:10)
[0-1]     at Socket.socketOnClose (/home/florent/Documents/code/app_qa-automation/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1264:15)
[0-1]     at Socket.emit (node:events:513:28)
[0-1]     at Socket.emit (node:domain:489:12)
[0-1]     at TCP.<anonymous> (node:net:322:12)
[0-1] 
[0-1] Node.js v18.16.0
[0-1] FAILED in chrome - file:///tests/features/debug/scenario_filtering_test_2.feature
```

### What is your expected behavior?

A feature file without a scenario matching the "name filter" should be ignored before being launched. The behavior should be the same as when filtering by tag. Indeed, when user filter scenario using "tags filter", only feature file with matching scenarios in it are launched.

### How to reproduce the bug.

* `scenario_filtering_test_1.feature`

```
@example_1
Feature: Filter scenario by name - File 1

    Scenario: Scenario #1 - File 1

    Scenario: Scenario #2 - File 1

```

* `scenario_filtering_test_2.feature`

```
@example_2
Feature: Filter scenario by name - File 2

    Scenario: Scenario #1 - File 2
        
    Scenario: Scenario #2 - File 2
```

* Configuration file snapshot

```
cucumberOpts: {
    require: ['tests/steps/**/*.js'], 
    backtrace: false,
    requireModule: ['@babel/register'],
    failFast: false, 
    strict: false, 
    tags: null, 
    ignoreUndefinedDefinitions: false, 
    name: ['Scenario #1 - File 1'] // <<< THIS IS IMPORTANT
  },
```

### Relevant log output

```typescript
florent@florent:~/Documents/code/app_qa-automation$ yarn test
yarn run v1.22.19
$ ./node_modules/.bin/wdio config/main.conf.js

Execution of 2 workers started at 2023-09-19T07:53:38.130Z

 > Tags for this runner "null"
[0-1] RUNNING in chrome - file:///tests/features/debug/scenario_filtering_test_2.feature
[0-0] RUNNING in chrome - file:///tests/features/debug/scenario_filtering_test_1.feature
[0-1] node:internal/process/promises:288
[0-1]             triggerUncaughtException(err, true /* fromPromise */);
[0-1]             ^
[0-1] 
[0-1] [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<ErrorEvent>".] {
[0-1]   code: 'ERR_UNHANDLED_REJECTION'
[0-1] }
[0-1] 
[0-1] Node.js v18.16.0
[0-1] FAILED in chrome - file:///tests/features/debug/scenario_filtering_test_2.feature
[0-0] PASSED in chrome - file:///tests/features/debug/scenario_filtering_test_1.feature

 "spec" Reporter:
------------------------------------------------------------------
[chrome 111.0.5563.64 linux #0-0] Running: chrome (v111.0.5563.64) on linux
[chrome 111.0.5563.64 linux #0-0] Session ID: 246543856105ce1640fced0583276363
[chrome 111.0.5563.64 linux #0-0]
[chrome 111.0.5563.64 linux #0-0] » /tests/features/debug/scenario_filtering_test_1.feature
[chrome 111.0.5563.64 linux #0-0] Filter scenario by name - File 1
[chrome 111.0.5563.64 linux #0-0] Scenario #1 - File 1

Spec Files:      1 passed, 1 failed, 2 total (100% completed) in 00:00:06 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@qaflorent sounds good, we merged the PR and this should be fixed in the next release.

@tamil777selvan thanks for picking this up, great work!
