### ISSUE TITLE
[🐛 Bug]: `findStrategy` cannot be imported in v8

### ISSUE THREAD

**Issue by michaele-blend** [webdriverio/webdriverio#11216]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.16.11

### Node.js Version

v18.17.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
N/A
```

### What happened?

I am migrating from v7 to v8. I first consulted the blog post here:
https://webdriver.io/blog/2022/12/01/webdriverio-v8-released

then I set in. most of my early issues are covered by the blog post. but I'm running into (what I believe to be) an effect of the cjs -> esm change: certain subfolders under the `webdriverio` package are now truly "private" and will not resolve for me.

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/utils/findStrategy' is not defined by "exports" in /home/michaele/git/caliper/server/node_modules/webdriverio/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:695:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/michaele/git/caliper/server/node_modules/@blend/wdio-shared/dist/src/methods/browser.js:9:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

the package I own (`wdio-shared`, listed in the stacktrace above) imports and builds against `findStrategy`:
```ts
// ...
import { findStrategy } from 'webdriverio/build/utils/findStrategy';
// ...
```
the `webdriverio` exports do not allow the import, which is breaking for me:
```json
  "exports": {
    ".": [
      {
        "types": "./build/index.d.ts",
        "import": "./build/index.js",
        "require": "./build/cjs/index.js"
      },
      "./build/cjs/index.js"
    ],
    "./package.json": "./package.json"
  },
```

I haven't found a way to effectively use this function anymore.
```
michaele@remote-dev-00:~/git/caliper/server/node_modules/webdriverio$ grep 'findStrategy' -r .
./build/utils/findStrategy.js:export const findStrategy = function (selector, isW3C, isMobile) {
./build/utils/findStrategy.d.ts.map:{"version":3,"file":"findStrategy.d.ts","sourceRoot":"","sources":["../../src/utils/findStrategy.ts"],"names":[],"mappings":"AA4BA,KAAK,gBAAgB,GAAG,MAAM,GAAG;IAAE,IAAI,EAAE,MAAM,CAAC;IAAC,IAAI,EAAE,MAAM,CAAA;CAAE,CAAA;AA4F/D,eAAO,MAAM,YAAY,aAAuB,gBAAgB,UAAU,OAAO,aAAa,OAAO;;;CAmLpG,CAAA"}
./build/utils/findStrategy.d.ts:export declare const findStrategy: (selector: SelectorStrategy, isW3C?: boolean, isMobile?: boolean) => {
./build/utils/findStrategy.d.ts://# sourceMappingURL=findStrategy.d.ts.map
./build/utils/index.js:import { findStrategy } from './findStrategy.js';
./build/utils/index.js:        const { using, value } = findStrategy(selector, this.isW3C, this.isMobile);
./build/utils/index.js:        const { using, value } = findStrategy(selector, this.isW3C, this.isMobile);
./build/commands/element/shadow$$.js:import { findStrategy } from '../../utils/findStrategy.js';
./build/commands/element/shadow$$.js:        const { using, value } = findStrategy(selector, this.isW3C, this.isMobile);
./build/commands/element/shadow$.js:import { findStrategy } from '../../utils/findStrategy.js';
./build/commands/element/shadow$.js:        const { using, value } = findStrategy(selector, this.isW3C, this.isMobile);
```

I checked `@wdio/utils` as well, which does not seem to be a public analog to `webdriverio/utils`, and neither exposes nor includes the `findStrategy` implementation.
https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-utils

I would like to know what my available options are, as a replacement. or to request that this method be exposed in some fashion, if there is no readily available replacement.

### How to reproduce the bug.

```bash
nvm i 18.17.1
node -e 'require("webdriverio/build/utils/findStrategy")'
```

### Relevant log output

```typescript
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './build/utils/findStrategy' is not defined by "exports" in /home/michaele/git/caliper/server/node_modules/webdriverio/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:695:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/michaele/git/caliper/server/node_modules/@blend/wdio-shared/dist/src/methods/browser.js:9:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
I don't find this an issue as the recommended way to add custom strategies is documented here: https://webdriver.io/docs/selectors/#custom-selector-strategies

**Comment by michaele-blend** [comment]
I don't want to add a custom selector strategy (we don't use those at all), I need to determine the strategy that will be used for an arbitrary selector string, which is currently unknown to me without annotation.

reviewing the docs, I can approximate some of my functionality with repeated `getSize` calls.
my other other use cases require more timing precision, however (I use `executeAsync` for this).
I suppose I'll can refactor our methods to require one type of selector, or to require the caller explicitly annotate which type of selector is being used instead.

thanks.

**Comment by erwinheitzman** [comment]
@michaele-blend fair enough, I'm not against exposing the function but it will only be in ESM.

**Comment by michaele-blend** [comment]
@erwinheitzman thank you, I am not using ESM right now, but performing this migration is preferable to me to having to annotate my selectors internally.
I'm not familiar with ESM at the moment, but I'm willing to send in a patch, please let me know.

**Comment by erwinheitzman** [comment]
@michaele-blend I'm not sure what I should let you know? I'm happy to review a PR if you want to fix it

**Comment by michaele-blend** [comment]
@erwinheitzman I just wanted to make sure that patches are welcome. I was out last week, but I'll send in a patch later this well. thanks.
