### ISSUE TITLE
trouble with tutorial

### ISSUE THREAD

**Issue by andrewjtimmons** [webdriverio/webdriverio#1123]
I am trying to do this tutorial http://webdriver.io/guide.html
I have a mac running yosemite.
I got to step 6 and ran my test file.

Nothing happened.

I did some research and found sometimes webdriver and firefox are not compatible and was getting the same unable to bind in 45000 ms messages that happen when those two don't play nice..

So I curled selenium server 2.52 and updated firefox to 44.0.2

Now when I run node test.js firefox opens the webpage and goes to google.com. However, console.log never runs and tells me the title. I changed the .title function to this to see if it was throwing errors.

  .title(function(err, res) {
        if (err) {
            console.log(err)
        }
        console.log('Title was: ' + res.value);
    })
Nothing was showing up still.

This is the output of the selenium server when I run node test. It seems to be getting the title, but not logging the console output. I even threw a console.log('hi') at the end of the file (after the .end(); and that output to the console. So I know I can output to console.

20:00:22.015 INFO - Executing: [new session: Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@71dd6242, javascriptEnabled=true, browserName=firefox, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.3}, rotatable=true, locationContextEnabled=true}]])
20:00:22.016 INFO - Creating a new session for Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@71dd6242, javascriptEnabled=true, browserName=firefox, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.3}, rotatable=true, locationContextEnabled=true}]
20:00:24.417 INFO - Done: [new session: Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@71dd6242, javascriptEnabled=true, browserName=firefox, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.3}, rotatable=true, locationContextEnabled=true}]]
20:00:24.453 INFO - Executing: [get: http://www.google.com])
20:00:28.143 INFO - Done: [get: http://www.google.com]
20:00:28.153 INFO - Executing: [get title])
20:00:28.263 INFO - Done: [get title]
20:00:28.270 INFO - Executing: [delete session: b9ec05a8-157d-4729-b115-5f61c4665943])
20:00:28.350 INFO - Done: [delete session: b9ec05a8-157d-4729-b115-5f61c4665943]

I figured maybe title was just being goofy so I tried to move on. I updated my code to try and see if I could select an element by clicking on it.

var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'firefox'
    }
};

webdriverio
    .remote(options)
    .init()
    .url('https://undefined.slack.com/')
    .click('#email')
    .end();

But it freezes and output
21:51:12.072 INFO - Launching a standalone Selenium Server
21:51:12.116 INFO - Java: Oracle Corporation 24.65-b04
21:51:12.116 INFO - OS: Mac OS X 10.10.5 x86_64
21:51:12.132 INFO - v2.52.0, with Core v2.52.0. Built from revision 4c2593c
21:51:12.216 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform MAC
21:51:12.216 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
registration capabilities Capabilities [{platform=WINDOWS, browserName=MicrosoftEdge, version=}] does not match the current platform MAC
21:51:12.217 INFO - Driver class not found: com.opera.core.systems.OperaDriver
21:51:12.217 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
21:51:12.314 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
21:51:12.315 INFO - Selenium Server is up and running
21:51:34.783 INFO - Executing: [new session: Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@72538db1, javascriptEnabled=true, browserName=firefox, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.3}, rotatable=true, locationContextEnabled=true}]])
21:51:34.796 INFO - Creating a new session for Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@72538db1, javascriptEnabled=true, browserName=firefox, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.3}, rotatable=true, locationContextEnabled=true}]
21:51:37.776 INFO - Done: [new session: Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@72538db1, javascriptEnabled=true, browserName=firefox, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.3}, rotatable=true, locationContextEnabled=true}]]
21:51:37.801 INFO - Executing: [get: https://undefined.slack.com/])
21:51:39.761 INFO - Done: [get: https://undefined.slack.com/]
21:51:39.775 INFO - Executing: [find element: By.id: email])
21:51:40.406 ERROR - Unexpected exception during findElement
org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Command duration or timeout: 54 milliseconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'andrews-MacBook-Air.local', ip: '10.0.1.10', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_67'
*** Element info: {Using=id, value=email}
Session ID: 67102844-5fca-cb4e-88ad-a431a92c4c2f
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=43.0.4}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
	at com.sun.proxy.$Proxy1.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:188)
	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'andrews-MacBook-Air.local', ip: '10.0.1.10', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_67'
Driver info: driver.version: unknown
	at <anonymous class>.<anonymous method>(https://undefined.slack.com/:431)
21:51:40.636 WARN - Exception thrown
org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Command duration or timeout: 54 milliseconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'andrews-MacBook-Air.local', ip: '10.0.1.10', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_67'
*** Element info: {Using=id, value=email}
Session ID: 67102844-5fca-cb4e-88ad-a431a92c4c2f
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=43.0.4}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:103)
	at com.sun.proxy.$Proxy1.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:188)
	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:48)
	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: Permission denied to access property "handleEvent"
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'andrews-MacBook-Air.local', ip: '10.0.1.10', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_67'
Driver info: driver.version: unknown
	at <anonymous class>.<anonymous method>(https://undefined.slack.com/:431)
21:51:40.643 WARN - Exception: Permission denied to access property "handleEvent"
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: 'andrews-MacBook-Air.local', ip: '10.0.1.10', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_67'
Driver info: driver.version: unknown

**Comment by muki-buki** [comment]
try firefox 42.0, selenium and bindings are lagging a bit behind
also you can upgrade selenium stand alone server to 2.52

**Comment by andrewjtimmons** [comment]
Will give it a shot.  I just switched to chromedriver and got it working with that.

Thank you!
