### ISSUE TITLE
[🐛 Bug]: Error thrown right away when running "yarn create wdio ."

### ISSUE THREAD

**Issue by giuseppe-salvatore** [webdriverio/webdriverio#11399]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.17.0 and 8.17.1

### Node.js Version

18.17.1 and 20.8.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
I didn't even get to configure/use capabilities
```

### What happened?

As soon as I run the command `yarn create wdio .` I get an error. I tried on 2 different linux laptops, and 2 different node version (18 and 20), it happened both on WDIO 8.17.0 and 8.17.1

### What is your expected behavior?

Base framework creation should succeed unless there's other issues (like network or disk problems)

### How to reproduce the bug.

Just run `yarn create wdio .`

### Relevant log output

```typescript
Installing @wdio/cli to initialize project...
✔ Success!
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module 'call-bind'
Require stack:
- /home/gr4ce/workspace/personal/webdriver.io/versions-test/tmp/node_modules/@ljharb/through/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/gr4ce/workspace/personal/webdriver.io/versions-test/tmp/node_modules/@ljharb/through/index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at cjsLoader (node:internal/modules/esm/translators:284:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:234:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async file:///home/gr4ce/workspace/personal/webdriver.io/versions-test/tmp/node_modules/@wdio/cli/bin/wdio.js:15:17 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/gr4ce/workspace/personal/webdriver.io/versions-test/tmp/node_modules/@ljharb/through/index.js'
  ]
}

Node.js v20.8.0


⚠️  Ups, something went wrong: Error calling: npx wdio config!
error Command failed.
Exit code: 1
Command: /home/gr4ce/.yarn/bin/create-wdio
Arguments: .
Directory: /home/gr4ce/workspace/personal/webdriver.io/versions-test/tmp
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Nodosy** [comment]
I have the same error but for Windows 10 and when `npm init wdio .`

**Comment by giuseppe-salvatore** [comment]
@jan-molak  :+1:  thanks for mentioning that, I suspected from the logs it could be a nested dependency issue but didn't have the time to investigate further

**Comment by jan-molak** [comment]
This is caused by a bug in `@ljharb/through` version 2.3.10 - https://github.com/ljharb/through/issues/1
`@ljharb/through` is a dependency of `inquirer`, which in turn WebdriverIO relies on.

To work around it, install `@ljharb/through@2.3.9` in your Node project and re-run WebdriverIO

```
npm install @ljharb/through@2.3.9
```

**Comment by christian-bromann** [comment]
I guess there is nothing we can do aside from waiting for the dependency to be fixed.

**Comment by jan-molak** [comment]
> I guess there is nothing we can do aside from waiting for the dependency to be fixed.

Not necessarily, we could add an explicit dependency on @ljharb/through@2.3.9 in `@wdio/cli`.
Since `inquirer` uses a [dependency range](https://github.com/SBoudrias/Inquirer.js/blob/3fff3fa81a37d5ab646229b7b757f9036e4f1fac/packages/inquirer/package.json#L62), such override would fix it.

**Comment by charlesh21** [comment]
It already be fixed with @ljharb/through@2.3.11
https://github.com/ljharb/through/pull/2

**Comment by christian-bromann** [comment]
Creating a new project from scratch works for me, can anyone confirm?

**Comment by jan-molak** [comment]
> Creating a new project from scratch works for me, can anyone confirm?

Yeah, all good here too :+1:

**Comment by christian-bromann** [comment]
Closing then, thanks for confirming!

If anyone still encounters this, please comment below.

**Comment by giuseppe-salvatore** [comment]
yeah it works! Thanks all. @christian-bromann I have repo I use to test new versions released are ok. What I do is 
- pull the repo
- run the wdio config
- patch some files
- run the sample test

Can that help?

**Comment by christian-bromann** [comment]
I am not sure what you mean 🤔

**Comment by erwinheitzman** [comment]
@giuseppe-salvatore we do have plans to add some smoke tests in the future for some cli setups 👍

**Comment by giuseppe-salvatore** [comment]
@christian-bromann I meant something like this https://github.com/giuseppe-salvatore/webdriverio-autoinit
Quite easy for me to run this command in CI or with cron, pull the latest WDIO, apply my project files (in this repo I am only using a sample project) build and run. This is how I found the issue and reported it

**Comment by christian-bromann** [comment]
We had an issue open for this in https://github.com/webdriverio/webdriverio/issues/5672 but I closed it because it seems very difficult to do and no one picked it up. It would be awesome to have a test similar to what you have. I would prefer to have it use a Node.js tool for this so we don't need to add Python as a dev dependency.

**Comment by giuseppe-salvatore** [comment]
Yeah I think that shouldn't be a problem, I could do some work and branch out, we can do it for jasmine (which is the default) but I guess it would be nice to do it for cucumber as well, the demand/usage with that runner should be pretty high.
Once you are happy you can integrate it in your CI

**Comment by christian-bromann** [comment]
It is also not only the Python dependency .. I would personally just prefer a Node.js based tool since I don't want contributor to have to context switch and understand Python code. I am sure this kind of stuff is also possible with Node.js.
