### ISSUE TITLE
[🐛 Bug]: <@wdio/utils: Connecting to existing driver at http://selenium-hub:undefined/ 2023-10-18T14:33:32.728Z ERROR webdriver: TypeError: Invalid URL     at new NodeError (node:internal/errors:405:5)>

### ISSUE THREAD

**Issue by en-aplecan** [webdriverio/webdriverio#11463]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
browserName:'chrome'
browserVersion: latest
platformName: Mac
```

### What happened?

I am using wdio v8, the issue appears after I removed _selenium-standalone_. On my local machine it works perfectly, but the problem is on Gitlab. 

To run it on Gitlab I am using _selenium-hub_ and as a service docker. 

### What is your expected behavior?

How should be selenium-hub configured?

### How to reproduce the bug.

exports.config = {
    //runner: 'local',
    hostname: 'selenium-hub',
    specs: [
        './test/specs/**/*.js'
    ],
    suites: {
        healthChecks: ['./test/specs/**.js'],
        multitenancy: ['./test/specs/ibexa/globalAdmin/contentStructure.js',
            './test/specs/ibexa/globalAdmin/folderContentType.js',
            './test/specs/ibexa/globalAdmin/folderContentTypeContentTreeActions.js',
            './test/specs/ibexa/globalAdmin/contactPersonContentType.js',
            './test/specs/ibexa/globalAdmin/contactPersonContentTypeContentTreeActions.js',
            './test/specs/ibexa/globalAdmin/infoHubContentType.js',
            './test/specs/ibexa/globalAdmin/infoHubContentTypeContentTreeActions.js',
            './test/specs/ibexa/globalAdmin/postContentType.js',
            './test/specs/ibexa/globalAdmin/postContentTypeContentTreeActions.js'],
        multitenancy1: ['./test/specs/ibexa/globalAdmin/contentStructure.js']
    },
    maxInstances: 1,
    capabilities: utils.initBrowserCapabilities(process.env.BROWSER),
    outputDir: path.join(__dirname, '/logs'),

    logLevel: 'info',
    coloredLogs: true,
    logLevels: {
        webdriver: 'info',
        webdriverio: 'info',
        '@wdio/cli': 'info',
        '@wdio/mocha-framework': 'info'
    },
    bail: 0,
    pageLoad: 31000,
    implicit: 32000,
    script: 33000,
    waitforTimeout: 90000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['docker'],
    framework: 'mocha',
    reporters: [
        'spec',
        [
            'allure',
            {
                outputDir: 'report/allure-results',
                disableWebdriverStepsReporting: true,
                disableWebdriverScreenshotsReporting: false,
                disableMochaHooks: false,
                addConsoleLogs: true
            }
        ]
    ],
    mochaOpts: {
        ui: 'bdd',
        timeout: 400000,
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    before: async function () {
        const chai = require('chai');
        global.assert = chai.assert;
        global.report = allureReporter
        global.logger = logger
        await browser.maximizeWindow()
    },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
    beforeTest: function () {
        global.report.addDescription('generating Allure reports ', 'text');
        global.report.addEnvironment('ENVIRONMENT', process.env.ENV);
        global.report.addEnvironment('AUTOMATION BACKEND', process.env.BACKEND);
        global.report.addEnvironment('BROWSER', browser.capabilities.browserName);
        global.report.addEnvironment('HEADLESS', process.env.HEADLESS);
    },

    /**
     * Function to be executed after a test (in Mocha/Jasmine).
     */
    afterTest: async function (test, scenario, {error}) {
        if (error) {
            await browser.takeScreenshot()
        }
    }
}

### Relevant log output

```typescript
2023-10-18T14:33:32.655Z INFO webdriver: Initiate new session using the WebDriver protocol
2023-10-18T14:33:32.656Z INFO @wdio/utils: Connecting to existing driver at http://selenium-hub:undefined/
2023-10-18T14:33:32.728Z ERROR webdriver: TypeError: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:637:13)
    at Function.getInstance (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriver/build/request/factory.js:16:20)
    at NodeJSRequest._createOptions (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriver/build/request/index.js:86:30)
    at NodeJSRequest.makeRequest (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriver/build/request/index.js:43:94)
    at startWebDriverSession (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriver/build/utils.js:63:20)
    at Function.newSession (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriver/build/index.js:27:45)
    at remote (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriverio/build/index.js:45:22)
    at Runner._startSession (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/@wdio/runner/build/index.js:224:29)
    at Runner._initSession (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/@wdio/runner/build/index.js:190:25)
    at Runner.run (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/@wdio/runner/build/index.js:79:19)
2023-10-18T14:33:32.731Z ERROR @wdio/runner: Error: Failed to create session.
Invalid URL
    at startWebDriverSession (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriver/build/utils.js:68:15)
    at Function.newSession (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriver/build/index.js:27:45)
    at remote (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriverio/build/index.js:45:22)
    at Runner._startSession (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/@wdio/runner/build/index.js:224:29)
    at Runner._initSession (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/@wdio/runner/build/index.js:190:25)
    at Runner.run (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/@wdio/runner/build/index.js:79:19)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ```ts
> Connecting to existing driver at http://selenium-hub:undefined/
> ```

You have to specify a port number in your `wdio.conf.js` to connect to the Selenium Hub.

Let me know if you have further questions.
