### ISSUE TITLE
[🐛 Bug]: ERROR webdriver: Request failed with status 500 due to session not created: session not created: No matching capabilities found

### ISSUE THREAD

**Issue by QA-ler** [webdriverio/webdriverio#11472]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.19.0

### Node.js Version

v19.4.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstances: 5,
        'goog:chromeOptions': {
            args: [
                '--no-sandbox',
                '--disable-notifications',
                '--window-size=1920,1080',
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--auto-open-devtools-for-tabs'
            ]
        },
        browserName: 'chromium',
        acceptInsecureCerts: true
    }]
```

### What happened?

Chrome Browser does not open.

This happens with versions
"@wdio/local-runner": "8.14.6" up to "8.19.0".
Version 8.14.0 does not work also but with another error message

### What is your expected behavior?

Like for versions up to "@wdio/local-runner": "8.13.13" Chrome Browser is opening and test execution starts

### How to reproduce the bug.

1. Have Chrome Browser inntalled
1. Use [package.json](https://github.com/webdriverio/webdriverio/files/13041362/package.json)
install packages
2. place following files on same level as package.json:
[bugTest.test.txt](https://github.com/webdriverio/webdriverio/files/13041472/bugTest.test.txt)
[wdio.conf.bug.txt](https://github.com/webdriverio/webdriverio/files/13041476/wdio.conf.bug.txt)
Couldn't upload it as .js so you need to adjust file extension .txt back to .js
3. run 
```cmd
pnpm wdio run wdio.conf.bug.js --spec .\bugTest.test.js
```
or replace pnpm with npm if you use this
4. Watch the error happen

### Relevant log output

```typescript
This happens with versions:
"@wdio/local-runner": "8.14.6" up to latest "8.19.0".
(Version 8.14.0 does not work also but with another error message)

2023-10-19T09:50:44.808Z DEBUG @wdio/runner: init remote session 
[0-0] 2023-10-19T09:50:44.810Z INFO webdriver: Initiate new session using the WebDriver protocol 
[0-0] 2023-10-19T09:50:44.824Z INFO webdriver: Downloading Chromedriver v118.0.5993.89 
[0-0] 2023-10-19T09:50:44.961Z WARN webdriver: Couldn't download Chromedriver v118.0.5993.89: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/118.0.5993.89/win64/chromedriver-win64.zip, trying to find known good version... 
[0-0] 2023-10-19T09:50:46.154Z INFO webdriver: Started Chromedriver v118.0.5993.70 with params --port=51060 --allowed-origins=* --allowed-ips= in 1343ms on port 51060 
[0-0] 2023-10-19T09:50:46.162Z INFO webdriver: [POST] http://0.0.0.0:51060/session 
[0-0] 2023-10-19T09:50:46.162Z INFO webdriver: DATA { 
[0-0]   capabilities: { 
[0-0]     alwaysMatch: { 
[0-0]       'goog:chromeOptions': [Object], 
[0-0]       browserName: 'chromium', 
[0-0]       acceptInsecureCerts: true 
[0-0]     }, 
[0-0]     firstMatch: [ {} ] 
[0-0]   }, 
[0-0]   desiredCapabilities: { 
[0-0]     'goog:chromeOptions': { 
[0-0]       binary: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', 
[0-0]       args: [Array] 
[0-0]     }, 
[0-0]     browserName: 'chromium', 
[0-0]     acceptInsecureCerts: true 
[0-0]   } 
[0-0] } 
[0-0] 2023-10-19T09:50:46.175Z DEBUG webdriver: request failed due to response error: session not created 
[0-0] 2023-10-19T09:50:46.176Z WARN webdriver: Request failed with status 500 due to session not created: No matching capabilities found 
[0-0] 2023-10-19T09:50:46.176Z INFO webdriver: Retrying 1/1 
[0-0] 2023-10-19T09:50:46.176Z INFO webdriver: [POST] http://0.0.0.0:51060/session 
[0-0] 2023-10-19T09:50:46.176Z INFO webdriver: DATA { 
[0-0]   capabilities: { 
[0-0]     alwaysMatch: { 
[0-0]       'goog:chromeOptions': [Object], 
[0-0]       browserName: 'chromium', 
[0-0]       acceptInsecureCerts: true 
[0-0]     }, 
[0-0]     firstMatch: [ {} ] 
[0-0]   }, 
[0-0]   desiredCapabilities: { 
[0-0]     'goog:chromeOptions': { 
[0-0]       binary: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', 
[0-0]       args: [Array] 
[0-0]     }, 
[0-0]     browserName: 'chromium', 
[0-0]     acceptInsecureCerts: true 
[0-0]   } 
[0-0] } 
[0-0] 2023-10-19T09:50:46.193Z DEBUG webdriver: request failed due to response error: session not created 
[0-0] 2023-10-19T09:50:46.193Z ERROR webdriver: Request failed with status 500 due to session not created: session not created: No matching capabilities found 
[0-0] 2023-10-19T09:50:46.193Z ERROR webdriver: session not created: session not created: No matching capabilities found 
[0-0]     at getErrorFromResponseBody (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/webdriver@8.14.6/node_modules/webdriver/build/utils.js:194:12) 
[0-0]     at NodeJSRequest._request (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/webdriver@8.14.6/node_modules/webdriver/build/request/index.js:164:23) 
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
[0-0]     at async startWebDriverSession (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/webdriver@8.14.6/node_modules/webdriver/build/utils.js:63:20) 
[0-0]     at async WebDriver.newSession (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/webdriver@8.14.6/node_modules/webdriver/build/index.js:28:45) 
[0-0]     at async remote (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/webdriverio@8.14.6/node_modules/webdriverio/build/index.js:45:22) 
[0-0]     at async Runner._startSession (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/@wdio+runner@8.14.6/node_modules/@wdio/runner/build/index.js:222:29) 
[0-0]     at async Runner._initSession (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/@wdio+runner@8.14.6/node_modules/@wdio/runner/build/index.js:188:25) 
[0-0]     at async Runner.run (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/@wdio+runner@8.14.6/node_modules/@wdio/runner/build/index.js:77:19) 
[0-0] 2023-10-19T09:50:46.194Z ERROR @wdio/runner: Error: Failed to create session. 
[0-0] session not created: No matching capabilities found 
[0-0]     at startWebDriverSession (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/webdriver@8.14.6/node_modules/webdriver/build/utils.js:68:15) 
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
[0-0]     at async WebDriver.newSession (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/webdriver@8.14.6/node_modules/webdriver/build/index.js:28:45) 
[0-0]     at async remote (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/webdriverio@8.14.6/node_modules/webdriverio/build/index.js:45:22) 
[0-0]     at async Runner._startSession (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/@wdio+runner@8.14.6/node_modules/@wdio/runner/build/index.js:222:29) 
[0-0]     at async Runner._initSession (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/@wdio+runner@8.14.6/node_modules/@wdio/runner/build/index.js:188:25) 
[0-0]     at async Runner.run (file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/node_modules/.pnpm/@wdio+runner@8.14.6/node_modules/@wdio/runner/build/index.js:77:19) 
2023-10-19T09:50:46.333Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1 
[0-0] FAILED in chromium - file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/__tests__/createWorkflowHappyPath.test.js 
2023-10-19T09:50:46.334Z INFO @wdio/cli:launcher: Run onWorkerEnd hook 
2023-10-19T09:50:46.335Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms 
2023-10-19T09:50:46.336Z INFO @wdio/cli:launcher: Run onComplete hook 
Allure trends updated! 
Report successfully generated to allure-report 
2023-10-19T09:50:51.121Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms 



------------------------------------------------------------------------------------------

On version: "@wdio/local-runner": "8.13.13" Log looks like this:

2023-10-19T10:07:40.020Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 1ms 
2023-10-19T10:07:40.022Z INFO @wdio/utils: Setting up browser driver for: chromium@stable 
2023-10-19T10:07:40.026Z INFO @wdio/utils: Setting up browser binaries for: chromium@stable 
2023-10-19T10:07:40.043Z INFO webdriver: Downloading Chromedriver v118.0.5993.89 
2023-10-19T10:07:40.308Z WARN webdriver: Chromedriver v118.0.5993.89 don't exist, trying to find known good version... 
2023-10-19T10:07:40.410Z INFO webdriver: Download of Chromedriver v118.0.5993.70 was successful 
2023-10-19T10:07:40.412Z WARN @wdio/config:ConfigParser: pattern ./__tests__/businessObjectCall.test.js did not match any file 
2023-10-19T10:07:40.417Z INFO @wdio/cli:launcher: Run onWorkerStart hook 
2023-10-19T10:07:40.417Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms 
2023-10-19T10:07:40.424Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js,--spec,.\\__tests__\\createWorkflowHappyPath.test.js 
2023-10-19T10:07:40.458Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0" 
[0-0] 2023-10-19T10:07:43.429Z INFO @wdio/local-runner: Run worker command: run 
[0-0] 2023-10-19T10:07:44.640Z DEBUG @wdio/runner: init remote session 
[0-0] 2023-10-19T10:07:44.647Z DEBUG @wdio/utils:initialiseServices: initialise service "ui5" as NPM package 
[0-0] 2023-10-19T10:07:44.986Z DEBUG @wdio/utils:initialiseServices: initialise service "intercept" as NPM package 
[0-0] 2023-10-19T10:07:45.011Z DEBUG @wdio/utils:shim: Finished to run "beforeSession" hook in 0ms 
[0-0] RUNNING in chromium - file:///C:/Users/userName/Repos/Pupeteer_DevOps/simplifier-ui-test/__tests__/createWorkflowHappyPath.test.js 
[0-0] 2023-10-19T10:07:45.621Z DEBUG @wdio/runner: init remote session 
[0-0] 2023-10-19T10:07:45.644Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol 
[0-0] 2023-10-19T10:07:45.647Z INFO devtools: Launch Google Chrome (undefined) with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --no-sandbox --disable-notifications --window-size=1920,1080 --disable-dev-shm-usage --disable-gpu --auto-open-devtools-for-tabs --accept-lang=en --lang=en --ignore-certificate-errors 
[0-0] 2023-10-19T10:07:47.001Z INFO devtools: Connect Puppeteer with browser on port 51571 
[0-0] [wdi5] 'url' property in config file deprecated: please use 'baseUrl' only! 
[0-0] 2023-10-19T10:07:48.321Z INFO devtools: COMMAND navigateTo("https://nightly.simplifier.io/UserInterface/#") 
[0-0] 2023-10-19T10:07:52.825Z INFO devtools: RESULT null 
[0-0] 2023-10-19T10:07:52.836Z DEBUG @wdio/utils:shim: Finished to run "before" hook in 4523ms 
[0-0] 2023-10-19T10:07:52.907Z DEBUG @wdio/utils:shim: Finished to run "beforeSuite" hook in 1ms 
[0-0] 2023-10-19T10:07:53.009Z DEBUG @wdio/utils:shim: Finished to run "beforeTest" hook in 1ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ```ts
> browserName: 'chromium',
> ```

This browser name is not supported. Please change it to `chrome` if you like to run tests on Google Chrome.

Let me know if you have further questions. I will go ahead and close this.

**Comment by QA-ler** [comment]
@christian-bromann thanks for the quick reply, but I'm wondering that "chromium" was always a valid browser name until the version "@wdio/local-runner": "8.13.13".
Is there a reason why the support for this was dropped?

We use this for running tests in Docker to use chromium browser as default. Without this, the tests will not run on arm64 machines inside Docker, as there is no downloadable version for Chrome.

**Comment by christian-bromann** [comment]
> Is there a reason why the support for this was dropped?

We introduced [driver management](https://webdriver.io/blog/2023/07/31/driver-management) to WebdriverIO which handles browser and driver installs.

Can you send me a Dockerfile / little reproducible project?

You should be able to still start Chromium by manually providing a path to it, e.g.:

```ts
'goog:chromeOptions': {
  binary: '/path/to/chromium'
}
```

**Comment by QA-ler** [comment]
Oh, good to know, then we'll have to switch to it anyway. 
Thank you :) 






> Can you send me a Dockerfile / little reproducible project?

We have a Base Docker which looks like

-------------------------
FROM node:slim

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

RUN apt-get update && \
    apt-get -y install gnupg && \
    apt-get -y install wget && \
    apt-get -y install default-jre && \
    apt-get -y install git && \
    apt-get install -y chromium && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

-------------------------

And then based on this we use 

-------------------------
FROM ???/qa-automation-base:8.0

ARG BRANCH=LTS-8.0

WORKDIR /usr/lib
RUN git -c http.extraHeader="???" clone https://???


WORKDIR /usr/lib/simplifier-ui-test
RUN git checkout $BRANCH && \
    git status && \
    npm install -g pnpm && \
    pnpm i && \
    # Copy environment file files
    cp setup_environment.docker.js setup_environment.js && \
    echo 'Log the common tools versions:' && \
    npm -version && \
    pnpm --version && \
    node --version && \
    chromium -version


ENTRYPOINT ["pnpm", "test", "--" ]
CMD ["sh", "-c"]

-------------------------

Removed the sensitive data with ???


Both dockers are build in pipeline for amd64 and arm64 using buildx

**Comment by christian-bromann** [comment]
Let's see if https://github.com/webdriverio/webdriverio/pull/11492 will fix this issue.

**Comment by QA-ler** [comment]
Thank you :) 
I'll give it a try.
