### ISSUE TITLE
[🐛 Bug]: Edge browser gives error

### ISSUE THREAD

**Issue by bhuvi4login** [webdriverio/webdriverio#11490]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.19.0

### Node.js Version

16.20.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
            browserName: 'MicrosoftEdge',
            'ms:edgeOptions': {
                args: ['start-maximized'],
                prefs: {
                    'download.directory_upgrade': true,
                    'download.prompt_for_download': false,
                    'download.default_directory': process.cwd() + '\\reports\\downloads'
                    },
            }
        }
```

### What happened?

I was using wdio 8.3.2, node 16.20.2 and e2e-local-web-jasmine-typescript earlier. I am using wdio 8.19.0, node 16.20.2 and e2e-local-web-jasmine-typescript for past 2 days, code is working fine for 1 spec file with chrome and edge. Need to check for more scenarios. But for some of my team members, edge was not running and saying this could support only 115 edge. You are having 117/118 edge version. Why is it so different for me (able to run both chrome/edge) and them(only able to run chrome)?

### What is your expected behavior?

Need to execute for both chrome and edge for all testers

### How to reproduce the bug.

To reproduce bug, use wdio 8.19.0, windows 11 enterprise. Edge 117/118. Run any wdio test spec and check. System: wdio 8.19.0, node 16.20.2 and e2e-local-web-jasmine-typescript, Windows 11 Enterprise.

### Relevant log output

```typescript
Execution of 1 workers started at 2023-10-20T16:18:59.150Z
[0-0] RUNNING in MicrosoftEdge - file:///T:/App/wdio/test_wdio/specs/view/testfile.view-spec.ts
[20876:21872:1020/181912.048:ERROR:policy_logger.cc(154)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
[20876:21872:1020/181912.092:ERROR:assistance_home_client.cc(32)] File path C:\Users\usr123\AppData\Local\Temp\scoped_dir19464_1544261736\Default
DevTools listening on ws://127.0.0.1:51610/devtools/browser/c5f71838-ea40-470c-9b98-8746ad1965f3    
[22028:9972:1020/181913.448:ERROR:policy_logger.cc(154)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
[22028:9972:1020/181913.500:ERROR:assistance_home_client.cc(32)] File path C:\Users\usr123\AppData\Local\Temp\scoped_dir19464_2142738144\Default
DevTools listening on ws://127.0.0.1:51616/devtools/browser/c65df673-dd99-40fe-bb5b-bf6d12828db1    
[0-0] 2023-10-20T16:19:14.495Z ERROR webdriver: Request failed with status 500 due to session not created: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 115
[0-0] Current browser version is 118.0.2088.57 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
[0-0] 2023-10-20T16:19:14.497Z ERROR webdriver: session not created: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 115
[0-0] Current browser version is 118.0.2088.57 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
[0-0]     at getErrorFromResponseBody (file:///T:/App/wdio/node_modules/webdriver/build/utils.js:194:12)
[0-0]     at NodeJSRequest._request (file:///T:/App/wdio/node_modules/webdriver/build/request/index.js:164:23)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async startWebDriverSession (file:///T:/App/wdio/node_modules/webdriver/build/utils.js:63:20)
[0-0]     at async Function.newSession (file:///T:/App/wdio/node_modules/webdriver/build/index.js:27:45)
[0-0]     at async remote (file:///T:/App/wdio/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (file:///T:/App/wdio/node_modules/@wdio/runner/build/index.js:224:29)
[0-0]     at async Runner._initSession (file:///T:/App/wdio/node_modules/@wdio/runner/build/index.js:190:25)
[0-0]     at async Runner.run (file:///T:/App/wdio/node_modules/@wdio/runner/build/index.js:79:19)
[0-0] 2023-10-20T16:19:14.501Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 115
[0-0] Current browser version is 118.0.2088.57 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
[0-0]     at startWebDriverSession (file:///T:/App/wdio/node_modules/webdriver/build/utils.js:68:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Function.newSession (file:///T:/App/wdio/node_modules/webdriver/build/index.js:27:45)
[0-0]     at async remote (file:///T:/App/wdio/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (file:///T:/App/wdio/node_modules/@wdio/runner/build/index.js:224:29)
[0-0]     at async Runner._initSession (file:///T:/App/wdio/node_modules/@wdio/runner/build/index.js:190:25)
[0-0]     at async Runner.run (file:///T:/App/wdio/node_modules/@wdio/runner/build/index.js:79:19)
[0-0] FAILED in MicrosoftEdge - file:///T:/App/wdio/test_wdio/specs/view/testfile.view-spec.ts
 Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:15 undefined
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@bhuvi4login thanks for raising the issue. Could you provide all available wdio logs?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
