### ISSUE TITLE
[🐛 Bug]: <title>

### ISSUE THREAD

**Issue by sauravdas1997** [webdriverio/webdriverio#11748]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.23.4

### Node.js Version

18

### Mode

WDIO Testrunner

### What happened?

Framework - WDIO-Mocha
When the test timesout, the `after` hook is getting called before `afterTest` . But as per the hook description provided [here](https://webdriver.io/docs/configurationfile/), the opposite should be the case, i.e. `afterTest`  should be called first and then followed by `after`. This is breaking some of the reporting functionality.

### What is your expected behavior?

```
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * ...
     */
    after: function (result, capabilities, specs) {
    },
```
As per the doc for `after`, it should be getting called after all tests are done.

```
    /**
     * Function to be executed after a test (in Mocha/Jasmine only)
     * ...
     */
    afterTest: function (test, context, { error, result, duration, passed, retries }) {
    },
```
And for `afterTest`, it should run right after a test.

So ideally, the priority should be given to `afterTest` and then `after`

### How to reproduce the bug.

- Only 1 test in test suite
- test timeout - 5000ms 
- added a sleep of 10000ms to reproduce timeout
-  wdio conf file change
```
    afterTest: async (test, context, { error, result, duration, passed, retries }) => {
        console.log(`~~~~~~~~~~~~~~~~~~~~~~~~ AFTER TEST HOOK :: ${Date.now()} ~~~~~~~~~~~~~~~~~~~~~~~~`)
    },

    after: function (result, capabilities, specs) {
        console.log(`~~~~~~~~~~~~~~~~~~~~~~~~ AFTER HOOK :: ${Date.now()} ~~~~~~~~~~~~~~~~~~~~~~~~`)
    },
```

### Relevant log output

```typescript
Following is the stack trace. The `afterTest` was called after the `after` hook.

[0-0] 2023-11-27T10:42:43.174Z INFO webdriver: RESULT Test: Logo Displayed - Fail
[0-0] HELLO FROM TEST
[0-0] Error in "Sign In - Basic components.Logo Wrapper - Fail.Logo Displayed - Fail"
Error: Timeout of 5000ms exceeded. The execution in the test "Logo Wrapper - Fail Logo Displayed - Fail" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (<path>/specs/e2e/bstack_demo/signIn/signIn.e2e.js)
    at createTimeoutError (<path>/node_modules/mocha/lib/errors.js:498:15)
    at Test.Runnable._timeoutError (<path>/node_modules/mocha/lib/runnable.js:431:10)
    at Timeout.<anonymous> (<path>/node_modules/mocha/lib/runnable.js:246:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[0-0] ~~~~~~~~~~~~~~~~~~~~~~~~ AFTER HOOK :: 1701081767777 ~~~~~~~~~~~~~~~~~~~~~~~~
[0-0] 2023-11-27T10:42:47.778Z INFO @wdio/browserstack-service: Update job with sessionId 5ebd15e8f652463118f5d3f8c08c9e2f2d2a470a
[0-0] ~~~~~~~~~~~~~~~~~~~~~~~~ AFTER TEST HOOK :: 1701081768184 ~~~~~~~~~~~~~~~~~~~~~~~~
[0-0] 2023-11-27T10:42:48.451Z INFO webdriver: COMMAND deleteSession()
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by sauravdas1997** [comment]
Sure, here it is.
- `git clone https://github.com/sauravdas1997/wdio-sample-test`
- `cd wdio-sample-test`
- `npm install`
- Add the required creds in wdio.conf.js
- `npm run test`

I reproduced multiple times, in different system, and the output that I am getting is as follows
```
Execution of 1 workers started at 2023-11-28T15:09:51.620Z

[0-0] RUNNING in chrome - file:///test/specs/test.e2e.js
[0-0] Log From Test
[0-0] Error in "My Login application.should login with valid credentials"
Error: Timeout of 5000ms exceeded. The execution in the test "My Login application should login with valid credentials" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (<path>/test/specs/test.e2e.js)
    at createTimeoutError (<path>/node_modules/mocha/lib/errors.js:498:15)
    at Test.Runnable._timeoutError (<path>/node_modules/mocha/lib/runnable.js:431:10)
    at Timeout.<anonymous> (<path>/node_modules/mocha/lib/runnable.js:246:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
[0-0] ~~~~~~~~~~~~~~~~~~~~~~~~ AFTER HOOK TIMESTAMP :: 1701184205097 ~~~~~~~~~~~~~~~~~~~~~~~~
[0-0] ~~~~~~~~~~~~~~~~~~~~~~~~ AFTER TEST HOOK TIMESTAMP :: 1701184206193 ~~~~~~~~~~~~~~~~~~~~~~~~
[0-0] FAILED in chrome - file:///test/specs/test.e2e.js
```

**Comment by christian-bromann** [comment]
Thanks for providing a reproducible example! There is no need to include BS within it, just adding:

```ts
    afterTest: async function(test, context, { error, result, duration, passed, retries }) {
        await new Promise(r => setTimeout(r, 100))
        console.log(`~~~~~~~~~~~~~~~~~~~~~~~~ AFTER TEST HOOK TIMESTAMP :: ${Date.now()} ~~~~~~~~~~~~~~~~~~~~~~~~`)
    },
```

Makes it show that the `afterTest` in Mocha can be executed after the framework already wrapped up is test execution. My hunch is that this is Mocha related and specific to timeouts, e.g. Mocha has scheduled these hooks but already resolved its testrun function.



We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by tech-dm-klymenko** [comment]
@sauravdas1997 
I tried to reproduce your bug in WebdriverIO **v8.24.16**, but when a timeout occurs, the hooks are executed in the correct order (`'After Test' => 'After'`).
Could you, please, try and tell if the bug is still reproducible in a newer version of the WebdriverIO?
