### ISSUE TITLE
[🐛 Bug]: isDisplayed method does not work properly for Windows Application after upgrading to v8.24.3

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#11759]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.24.3

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    maxInstances: 7,
    platformName: 'WINDOWS',
    'appium:app': `C:\\Program Files\\DieManufacturing.Dev\\Fr.DieManufacturing.Client.exe`,
    'appium:appArguments': '-noCloseConfirmationPopUp -shouldDisplayDiesToTake',
    'ms:experimental-webdriver': true,
    'ms:waitForAppLaunch': '10',
    browserName: `DieManufacturing.Dev`,
  }
```

### What happened?

Windows element call with an automatid like  $("~username") stop working for the method IsDisplayed

### How to reproduce the bug.

Run any available Windows App automation using Appium and try to execute isDisplayed() method for any element by specified locator
Check WDIO logs

### Relevant log output

```typescript
[0-0] 2023-11-29T14:27:27.419Z INFO webdriver: COMMAND $("~username")
[0-0] 2023-11-29T14:27:27.423Z INFO webdriver: COMMAND findElement("accessibility id", "username")
[0-0] 2023-11-29T14:27:27.423Z INFO webdriver: [POST] http://127.0.0.1:4723/session/2a64a8bf-f6cb-4511-8649-d8d950eb3c91/element
[0-0] 2023-11-29T14:27:27.423Z INFO webdriver: DATA { using: 'accessibility id', value: 'username' }
[0-0] 2023-11-29T14:27:28.636Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: 'An element could not be located on the page using the given search parameters.',
[0-0]   stacktrace: 'NoSuchElementError: An element could not be located on the page using the given search parameters.\n' +
[0-0]     '    at errorFromW3CJsonCode (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:780:25)\n' +
[0-0]     '    at ProxyRequestError.getActualError (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:663:14)\n' +
[0-0]     '    at WADProxy.command (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:272:19)\n' +
[0-0]     '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
[0-0]     '    at WinAppDriver.sendCommand (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:221:12)\n' +
[0-0]     '    at WindowsDriver.findElOrEls (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-windows-driver\\lib\\commands\\find.js:11:10)\n' +
[0-0]     '    at WindowsDriver.findElOrElsWithProcessing (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:33:12)\n' +
[0-0]     '    at WindowsDriver.findElement (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:53:10)'
[0-0] }
[0-0] 2023-11-29T14:27:28.644Z INFO webdriver: RESULT WebdriverIO.Element<undefined>
[0-0] 2023-11-29T14:27:28.644Z INFO webdriver: COMMAND $("~username")
[0-0] 2023-11-29T14:27:28.645Z INFO webdriver: COMMAND findElement("accessibility id", "username")
[0-0] 2023-11-29T14:27:28.645Z INFO webdriver: [POST] http://127.0.0.1:4723/session/2a64a8bf-f6cb-4511-8649-d8d950eb3c91/element
[0-0] 2023-11-29T14:27:28.645Z INFO webdriver: DATA { using: 'accessibility id', value: 'username' }
[0-0] 2023-11-29T14:27:29.402Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '42.267144.4.5.1.28',
[0-0]   ELEMENT: '42.267144.4.5.1.28'
[0-0] }
[0-0] 2023-11-29T14:27:29.405Z INFO webdriver: RESULT WebdriverIO.Element<42.267144.4.5.1.28>
[0-0] 2023-11-29T14:27:29.405Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-11-29T14:27:29.406Z INFO webdriver: [POST] http://127.0.0.1:4723/session/2a64a8bf-f6cb-4511-8649-d8d950eb3c91/execute
[0-0] 2023-11-29T14:27:29.406Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8102 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '42.267144.4.5.1.28',
[0-0]       ELEMENT: '42.267144.4.5.1.28'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-11-29T14:27:29.421Z DEBUG webdriver: request failed due to response error: unknown method
[0-0] 2023-11-29T14:27:29.421Z WARN webdriver: Request failed with status 405 due to Method is not implemented
[0-0] 2023-11-29T14:27:29.421Z INFO webdriver: Retrying 1/1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
I don't see how this is related to isDisplayed, it simply cannot find the element

**Comment by BorisOsipov** [comment]
@erwinheitzman  In the log a little further down


```
[0-0] 2023-11-29T14:27:29.405Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-11-29T14:27:29.406Z INFO webdriver: [POST] http://127.0.0.1:4723/session/2a64a8bf-f6cb-4511-8649-d8d950eb3c91/execute
[0-0] 2023-11-29T14:27:29.406Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8102 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '42.267144.4.5.1.28',
[0-0]       ELEMENT: '42.267144.4.5.1.28'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-11-29T14:27:29.421Z DEBUG webdriver: request failed due to response error: unknown method
[0-0] 2023-11-29T14:27:29.421Z WARN webdriver: Request failed with status 405 due to Method is not implemented
```

**Comment by christian-bromann** [comment]
I got this .. we recently tweaked the `isDisplayed` implementation and call the execute script now for all none mobile environments. The capabilities provided have a `browserName` which makes WebdriverIO think it is a browser.

@lacell75 can you explain why the `browserName` is set in the capabilities? I assume it is not required by Appium right?

**Comment by lacell75** [comment]
The browserName is used for internal usage and for our selenium grid. But i have the same issue without the browserName in the capabilities , please below:

`2023-11-29T16:23:44.784Z DEBUG @wdio/utils:initializeServices: initialize service "intercept" as NPM package
2023-11-29T16:23:44.798Z DEBUG @wdio/utils:initializeServices: initialize service "image-comparison" as NPM package
2023-11-29T16:23:44.943Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-11-29T16:23:44.945Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-11-29T16:23:44.947Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.LOCAL.conf.ts,--spec,C:\2-gitlab\end-to-end-tests-wdio\features\XX-QAlityImports\02-importprivateDIE.feature
2023-11-29T16:23:44.958Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
[0-0] 2023-11-29T16:23:47.353Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-11-29T16:23:50.580Z DEBUG @wdio/runner: init remote session
[0-0] 2023-11-29T16:23:50.584Z DEBUG @wdio/utils:initializeServices: initialize service "intercept" as NPM package
[0-0] 2023-11-29T16:23:50.598Z DEBUG @wdio/utils:initializeServices: initialize service "image-comparison" as NPM package
[0-0] RUNNING in WINDOWS - file:///C:/2-gitlab/end-to-end-tests-wdio/features/XX-QAlityImports/02-importprivateDIE.feature
[0-0] 2023-11-29T16:23:51.976Z DEBUG @wdio/runner: init remote session
[0-0] 2023-11-29T16:23:51.978Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-11-29T16:23:51.978Z INFO @wdio/utils: Connecting to existing driver at http://127.0.0.1:4723/
[0-0] 2023-11-29T16:23:52.103Z INFO webdriver: [POST] http://127.0.0.1:4723/session
[0-0] 2023-11-29T16:23:52.104Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       platformName: 'WINDOWS',
[0-0]       'appium:app': 'C:\\Program Files\\DieManufacturing.Dev\\Fr.DieManufacturing.Client.exe',
[0-0]       'appium:appArguments': '-noCloseConfirmationPopUp -shouldDisplayDiesToTake',
[0-0]       'ms:experimental-webdriver': true,
[0-0]       'ms:waitForAppLaunch': '10'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     platformName: 'WINDOWS',
[0-0]     'appium:app': 'C:\\Program Files\\\DieManufacturing.Dev\\Fr.DieManufacturing.Client.exe',
[0-0]     'appium:appArguments': '-noCloseConfirmationPopUp -shouldDisplayDiesToTake',
[0-0]     'ms:experimental-webdriver': true,
[0-0]     'ms:waitForAppLaunch': '10'
[0-0]   }
[0-0] }
[0-0] 2023-11-29T16:24:03.849Z DEBUG @wdio/utils:shim: Finished to run "before" hook in 0ms
[C:\Program Files\DieManufacturing.Dev\Fr.DieManufacturing.Client.exe WINDOWS #0-0] ------------------------------------------------------------------
[C:\Program Files\DieManufacturing.Dev\Fr.DieManufacturing.Client.exe WINDOWS #0-0] Suite started:
[C:\Program Files\DieManufacturing.Dev\Fr.DieManufacturing.Client.exe WINDOWS #0-0]   » \features\XX-QAlityImports\02-importprivateDIE.feature
[C:\Program Files\DieManufacturing.Dev\Fr.DieManufacturing.Client.exe WINDOWS #0-0] XX-QAlityImports.02-Importing private DIE INQA-2050
[0-0] 2023-11-29T16:24:11.523Z WARN webdriver: The "sendKeys" command is deprecated and likely not supported by any browser.
[0-0] 2023-11-29T16:24:11.524Z INFO webdriver: COMMAND sendKeys(<object>)
[0-0] 2023-11-29T16:24:11.525Z INFO webdriver: [POST] http://127.0.0.1:4723/session/a5d6a121-1376-47eb-a654-f54ada3d0cca/keys
[0-0] 2023-11-29T16:24:11.525Z INFO webdriver: DATA { value: [ '', '0', '' ] }
[0-0] 2023-11-29T16:24:11.930Z INFO webdriver: RESULT null
[0-0] 2023-11-29T16:24:11.931Z WARN webdriver: The "sendKeys" command is deprecated and likely not supported by any browser.
[0-0] 2023-11-29T16:24:11.931Z INFO webdriver: COMMAND sendKeys(<object>)
[0-0] 2023-11-29T16:24:11.931Z INFO webdriver: [POST] http://127.0.0.1:4723/session/a5d6a121-1376-47eb-a654-f54ada3d0cca/keys
[0-0] 2023-11-29T16:24:11.931Z INFO webdriver: DATA { value: [ '', '0', '' ] }
[0-0] 2023-11-29T16:24:12.249Z INFO webdriver: RESULT null
[0-0] 2023-11-29T16:24:12.250Z DEBUG @wdio/utils:shim: Finished to run "beforeFeature" hook in 728ms

[C:\Program Files\DieManufacturing.Dev\Fr.DieManufacturing.Client.exe WINDOWS #0-0] Manufacturing a DIE
[0-0] 2023-11-29T16:24:12.337Z WARN webdriver: The "sendKeys" command is deprecated and likely not supported by any browser.
[0-0] 2023-11-29T16:24:12.338Z INFO webdriver: COMMAND sendKeys(<object>)
[0-0] 2023-11-29T16:24:12.338Z INFO webdriver: [POST] http://127.0.0.1:4723/session/a5d6a121-1376-47eb-a654-f54ada3d0cca/keys
[0-0] 2023-11-29T16:24:12.338Z INFO webdriver: DATA { value: [ '', '0', '' ] }
[0-0] 2023-11-29T16:24:12.641Z INFO webdriver: RESULT null
[0-0] 2023-11-29T16:24:12.642Z DEBUG @wdio/utils:shim: Finished to run "beforeScenario" hook in 305ms
[0-0] 2023-11-29T16:24:25.266Z DEBUG @wdio/utils:shim: Finished to run "afterStep" hook in 0ms  
[0-0] 2023-11-29T16:24:25.270Z INFO webdriver: COMMAND maximizeWindow()
[0-0] 2023-11-29T16:24:25.270Z INFO webdriver: [POST] http://127.0.0.1:4723/session/a5d6a121-1376-47eb-a654-f54ada3d0cca/window/current/maximize
[0-0] 2023-11-29T16:24:25.299Z INFO webdriver: RESULT null
[0-0] 2023-11-29T16:24:25.300Z INFO webdriver: COMMAND $("~username")
[0-0] 2023-11-29T16:24:25.302Z INFO webdriver: COMMAND findElement("accessibility id", "username")
[0-0] 2023-11-29T16:24:25.302Z INFO webdriver: [POST] http://127.0.0.1:4723/session/a5d6a121-1376-47eb-a654-f54ada3d0cca/element
[0-0] 2023-11-29T16:24:25.302Z INFO webdriver: DATA { using: 'accessibility id', value: 'username' }
[0-0] 2023-11-29T16:24:26.319Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: 'An element could not be located on the page using the given search parameters.',
[0-0]   stacktrace: 'NoSuchElementError: An element could not be located on the page using the given search parameters.\n' +
[0-0]     '    at errorFromW3CJsonCode (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:780:25)\n' +
[0-0]     '    at ProxyRequestError.getActualError (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:663:14)\n' +
[0-0]     '    at WADProxy.command (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:272:19)\n' +
[0-0]     '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
[0-0]     '    at WinAppDriver.sendCommand (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:221:12)\n' +
[0-0]     '    at WindowsDriver.findElOrEls (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-windows-driver\\lib\\commands\\find.js:11:10)\n' +
[0-0]     '    at WindowsDriver.findElOrElsWithProcessing (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:33:12)\n' +
[0-0]     '    at WindowsDriver.findElement (C:\\2-gitlab\\end-to-end-tests-wdio\\node_modules\\appium-base-driver\\lib\\basedriver\\commands\\find.js:53:10)'
[0-0] }
[0-0] 2023-11-29T16:24:26.327Z INFO webdriver: RESULT WebdriverIO.Element<undefined>
[0-0] 2023-11-29T16:24:26.327Z INFO webdriver: COMMAND $("~username")
[0-0] 2023-11-29T16:24:26.328Z INFO webdriver: COMMAND findElement("accessibility id", "username")
[0-0] 2023-11-29T16:24:26.328Z INFO webdriver: [POST] http://127.0.0.1:4723/session/a5d6a121-1376-47eb-a654-f54ada3d0cca/element
[0-0] 2023-11-29T16:24:26.328Z INFO webdriver: DATA { using: 'accessibility id', value: 'username' }
[0-0] 2023-11-29T16:24:27.101Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '42.1315198.4.5.1.29',
[0-0]   ELEMENT: '42.1315198.4.5.1.29'
[0-0] }
[0-0] 2023-11-29T16:24:27.104Z INFO webdriver: RESULT WebdriverIO.Element<42.1315198.4.5.1.29>
[0-0] 2023-11-29T16:24:27.104Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-11-29T16:24:27.105Z INFO webdriver: [POST] http://127.0.0.1:4723/session/a5d6a121-1376-47eb-a654-f54ada3d0cca/execute
[0-0] 2023-11-29T16:24:27.105Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8102 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '42.1315198.4.5.1.29',
[0-0]       ELEMENT: '42.1315198.4.5.1.29'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-11-29T16:24:27.122Z DEBUG webdriver: request failed due to response error: unknown method
[0-0] 2023-11-29T16:24:27.123Z WARN webdriver: Request failed with status 405 due to Method is not implemented
[0-0] 2023-11-29T16:24:27.123Z INFO webdriver: Retrying 1/1
[0-0] 2023-11-29T16:24:27.123Z INFO webdriver: [POST] http://127.0.0.1:4723/session/a5d6a121-1376-47eb-a654-f54ada3d0cca/execute
[0-0] 2023-11-29T16:24:27.123Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8102 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '42.1315198.4.5.1.29',
[0-0]       ELEMENT: '42.1315198.4.5.1.29'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-11-29T16:24:27.140Z DEBUG webdriver: request failed due to response error: unknown method
[0-0] 2023-11-29T16:24:27.141Z ERROR webdriver: Request failed with status 405 due to unknown method: Method is not implemented
[0-0] 2023-11-29T16:24:27.154Z DEBUG @wdio/utils:shim: Finished to run "afterStep" hook in 0ms
unknown method: Method is not implemented`

**Comment by christian-bromann** [comment]
@lacell75 thanks for providing more information, mind sharing what your terminal returns if you run `console.log(browser.capabilities)`?

**Comment by lacell75** [comment]
> @lacell75 thanks for providing more information, mind sharing what your terminal returns if you run `console.log(browser.capabilities)`?

sure: ` [0-0] undefined `

**Comment by christian-bromann** [comment]
This should not return `undefined` since it is a browser property. What is being printed when calling `console.log(browser)`?

**Comment by lacell75** [comment]
> This should not return `undefined` since it is a browser property. What is being printed when calling `console.log(browser)`?

Sorry, I don't why I had 'undefined' . I have that now:
`0] Browser {
[0-0]   sessionId: '68d059c7-49c7-4a7b-a892-d1967a9d1e5a',
[0-0]   capabilities: {
[0-0]     platformName: 'WINDOWS',
[0-0]     'ms:experimental-webdriver': true,
[0-0]     'ms:waitForAppLaunch': 10,
[0-0]     app: 'C:\\Program Files\\Intescia\\DieManufacturing.Dev\\Fr.Intescia.DieManufacturing.Client.exe',
[0-0]     appArguments: '-noCloseConfirmationPopUp -shouldDisplayDiesToTake'
[0-0]   },
[0-0]   addCommand: [Function (anonymous)],
[0-0]   overwriteCommand: [Function (anonymous)],
[0-0]   addLocatorStrategy: [Function (anonymous)]
[0-0] }
[0-0]capabilities:
[0-0] {
[0-0]   platformName: 'WINDOWS',
[0-0]   'ms:experimental-webdriver': true,
[0-0]   'ms:waitForAppLaunch': 10,
[0-0]   app: 'C:\\Program Files\\Intescia\\DieManufacturing.Dev\\Fr.Intescia.DieManufacturing.Client.exe',
[0-0]   appArguments: '-noCloseConfirmationPopUp -shouldDisplayDiesToTake'
[0-0] }`

**Comment by lacell75** [comment]
> console.log(browser.isMobile

```
[0-0] {
[0-0]   platformName: 'WINDOWS',
[0-0]   'ms:experimental-webdriver': true,
[0-0]   'ms:waitForAppLaunch': 10,
[0-0]   app: 'C:\\Program Files\\Intescia\\DieManufacturing.Dev\\Fr.Intescia.DieManufacturing.Client.exe',
[0-0]   appArguments: '-noCloseConfirmationPopUp -shouldDisplayDiesToTake'
[0-0] }
[0-0] false
```

**Comment by christian-bromann** [comment]
Thanks, I raised a PR with a fix which I will release once merged. Thanks for providing the informations.
