### ISSUE TITLE
[🐛 Bug]: setValue method does not work properly for Windows Application

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#11765]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.24.5

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    maxInstances: 7,
    platformName: 'WINDOWS',
    'appium:app': `C:\\Program Files\\DieManufacturing.Dev\\Fr.DieManufacturing.Client.exe`,
    'appium:appArguments': '-noCloseConfirmationPopUp -shouldDisplayDiesToTake',
    'ms:experimental-webdriver': true,
    'ms:waitForAppLaunch': '10',
}
```

### What happened?

SetValue does not work now because the wrong command is used.

I set value like that  `await $('~username').setValue('foo@bar.com');` 

### What is your expected behavior?

Please see below the logs before upgrading and that works:
```
[0-0] 2023-11-30T09:39:59.709Z INFO webdriver: COMMAND $("~username")
[0-0] 2023-11-30T09:39:59.711Z INFO webdriver: COMMAND findElement("accessibility id", "username")
[0-0] 2023-11-30T09:39:59.712Z INFO webdriver: [POST] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element
[0-0] 2023-11-30T09:39:59.713Z INFO webdriver: DATA { using: 'accessibility id', value: 'username' }
[0-0] 2023-11-30T09:40:00.587Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '42.527538.4.5.1.28',
[0-0]   ELEMENT: '42.527538.4.5.1.28'
[0-0] }
[0-0] 2023-11-30T09:40:00.590Z INFO webdriver: RESULT WebdriverIO.Element<42.527538.4.5.1.28>
[0-0] 2023-11-30T09:40:00.591Z INFO webdriver: COMMAND isElementDisplayed("42.527538.4.5.1.28")
[0-0] 2023-11-30T09:40:00.592Z INFO webdriver: [GET] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element/42.527538.4.5.1.28/displayed
[0-0] 2023-11-30T09:40:00.613Z INFO webdriver: RESULT true
[0-0] 2023-11-30T09:40:00.614Z INFO webdriver: COMMAND $("~username")
[0-0] 2023-11-30T09:40:00.615Z INFO webdriver: COMMAND findElement("accessibility id", "username")
[0-0] 2023-11-30T09:40:00.617Z INFO webdriver: [POST] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element
[0-0] 2023-11-30T09:40:00.617Z INFO webdriver: DATA { using: 'accessibility id', value: 'username' }
[0-0] 2023-11-30T09:40:01.379Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '42.527538.4.5.1.28',
[0-0]   ELEMENT: '42.527538.4.5.1.28'
[0-0] }
[0-0] 2023-11-30T09:40:01.383Z INFO webdriver: RESULT WebdriverIO.Element<42.527538.4.5.1.28>
[0-0] 2023-11-30T09:40:01.383Z INFO webdriver: COMMAND $("~password")
[0-0] 2023-11-30T09:40:01.385Z INFO webdriver: COMMAND elementClear("42.527538.4.5.1.28")
[0-0] 2023-11-30T09:40:01.386Z INFO webdriver: COMMAND findElement("accessibility id", "password")
[0-0] 2023-11-30T09:40:01.387Z INFO webdriver: [POST] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element/42.527538.4.5.1.28/clear
[0-0] 2023-11-30T09:40:01.389Z INFO webdriver: [POST] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element
[0-0] 2023-11-30T09:40:01.389Z INFO webdriver: DATA { using: 'accessibility id', value: 'password' }
[0-0] 2023-11-30T09:40:01.487Z INFO webdriver: RESULT null
[0-0] 2023-11-30T09:40:01.490Z INFO webdriver: COMMAND getElementTagName("42.527538.4.5.1.28")
[0-0] 2023-11-30T09:40:01.492Z INFO webdriver: [GET] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element/42.527538.4.5.1.28/name
[0-0] 2023-11-30T09:40:02.535Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '42.527538.4.5.1.3',
[0-0]   ELEMENT: '42.527538.4.5.1.3'
[0-0] }
[0-0] 2023-11-30T09:40:02.539Z INFO webdriver: RESULT WebdriverIO.Element<42.527538.4.5.1.3>
[0-0] 2023-11-30T09:40:02.541Z INFO webdriver: COMMAND elementClear("42.527538.4.5.1.3")
[0-0] 2023-11-30T09:40:02.543Z INFO webdriver: [POST] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element/42.527538.4.5.1.3/clear
[0-0] 2023-11-30T09:40:02.548Z INFO webdriver: RESULT ControlType.Edit
[0-0] 2023-11-30T09:40:02.550Z INFO webdriver: COMMAND elementSendKeys("42.527538.4.5.1.28", <object>)
[0-0] 2023-11-30T09:40:02.552Z INFO webdriver: [POST] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element/42.527538.4.5.1.28/value
[0-0] 2023-11-30T09:40:02.552Z INFO webdriver: DATA { value: [ 'foo@bar.com' ] }
[0-0] 2023-11-30T09:40:02.571Z INFO webdriver: RESULT null
[0-0] 2023-11-30T09:40:02.573Z INFO webdriver: COMMAND getElementTagName("42.527538.4.5.1.3")
[0-0] 2023-11-30T09:40:02.575Z INFO webdriver: [GET] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element/42.527538.4.5.1.3/name
[0-0] 2023-11-30T09:40:04.046Z INFO webdriver: COMMAND $("name:CONNEXION")
[0-0] 2023-11-30T09:40:04.048Z INFO webdriver: COMMAND findElement("name", "CONNEXION")
[0-0] 2023-11-30T09:40:04.049Z INFO webdriver: [POST] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element
[0-0] 2023-11-30T09:40:04.049Z INFO webdriver: DATA { using: 'name', value: 'CONNEXION' }
[0-0] 2023-11-30T09:40:04.862Z INFO webdriver: RESULT null
[0-0] 2023-11-30T09:40:04.873Z INFO webdriver: RESULT ControlType.Edit
[0-0] 2023-11-30T09:40:04.874Z INFO webdriver: COMMAND elementSendKeys("42.527538.4.5.1.3", <object>)
[0-0] 2023-11-30T09:40:04.876Z INFO webdriver: [POST] http://127.0.0.1:4723/session/f45720dc-ac43-456c-903b-3d43a635e42a/element/42.527538.4.5.1.3/value
[0-0] 2023-11-30T09:40:04.877Z INFO webdriver: DATA { value: [ 'pass' ] }
[0-0] 2023-11-30T09:40:05.652Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '42.527538.4.5.1.37',
[0-0]   ELEMENT: '42.527538.4.5.1.37'
[0-0] }
[0-0] 2023-11-30T09:40:05.656Z INFO webdriver: RESULT WebdriverIO.Element<42.527538.4.5.1.37>
```

### How to reproduce the bug.

Run any available Windows App automation using Appium and try to execute setValue() method for any element by specified locator
Check WDIO logs

```
await $('~username').setValue('foo@bar.com')
```

### Relevant log output

```typescript
[0-0] {
[0-0]   platformName: 'WINDOWS',
[0-0]   'ms:experimental-webdriver': true,
[0-0]   'ms:waitForAppLaunch': 10,
[0-0]   app: 'C:\\Program Files\\Intescia\\DieManufacturing.Dev\\Fr.Intescia.DieManufacturing.Client.exe',
[0-0]   appArguments: '-noCloseConfirmationPopUp -shouldDisplayDiesToTake'
[0-0] }
[0-0] browser.isMobile:
[0-0] true
[0-0] 2023-11-30T09:45:50.022Z INFO webdriver: COMMAND $("~username")
[0-0] 2023-11-30T09:45:50.025Z INFO webdriver: COMMAND findElement("accessibility id", "username")
[0-0] 2023-11-30T09:45:50.026Z INFO webdriver: [POST] http://127.0.0.1:4723/session/fbf9e063-3ff8-432a-840e-7e5552c3e771/element
[0-0] 2023-11-30T09:45:50.026Z INFO webdriver: DATA { using: 'accessibility id', value: 'username' }
[0-0] 2023-11-30T09:45:51.030Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '42.2493634.4.5.1.29',
[0-0]   ELEMENT: '42.2493634.4.5.1.29'
[0-0] }
[0-0] 2023-11-30T09:45:51.040Z INFO webdriver: RESULT WebdriverIO.Element<42.2493634.4.5.1.29>
[0-0] 2023-11-30T09:45:51.040Z INFO webdriver: COMMAND isElementDisplayed("42.2493634.4.5.1.29")
[0-0] 2023-11-30T09:45:51.041Z INFO webdriver: [GET] http://127.0.0.1:4723/session/fbf9e063-3ff8-432a-840e-7e5552c3e771/element/42.2493634.4.5.1.29/displayed
[0-0] 2023-11-30T09:45:51.058Z INFO webdriver: RESULT true
[0-0] 2023-11-30T09:45:51.058Z INFO webdriver: COMMAND $("~username")
[0-0] 2023-11-30T09:45:51.058Z INFO webdriver: COMMAND findElement("accessibility id", "username")
[0-0] 2023-11-30T09:45:51.059Z INFO webdriver: [POST] http://127.0.0.1:4723/session/fbf9e063-3ff8-432a-840e-7e5552c3e771/element
[0-0] 2023-11-30T09:45:51.059Z INFO webdriver: DATA { using: 'accessibility id', value: 'username' }
[0-0] 2023-11-30T09:45:51.813Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '42.2493634.4.5.1.29',
[0-0]   ELEMENT: '42.2493634.4.5.1.29'
[0-0] }
[0-0] 2023-11-30T09:45:51.817Z INFO webdriver: RESULT WebdriverIO.Element<42.2493634.4.5.1.29>
[0-0] 2023-11-30T09:45:51.817Z INFO webdriver: COMMAND $("~password")
[0-0] 2023-11-30T09:45:51.818Z INFO webdriver: COMMAND elementClear("42.2493634.4.5.1.29")
[0-0] 2023-11-30T09:45:51.818Z INFO webdriver: COMMAND findElement("accessibility id", "password")
[0-0] 2023-11-30T09:45:51.819Z INFO webdriver: [POST] http://127.0.0.1:4723/session/fbf9e063-3ff8-432a-840e-7e5552c3e771/element/42.2493634.4.5.1.29/clear
[0-0] 2023-11-30T09:45:51.820Z INFO webdriver: [POST] http://127.0.0.1:4723/session/fbf9e063-3ff8-432a-840e-7e5552c3e771/element
[0-0] 2023-11-30T09:45:51.820Z INFO webdriver: DATA { using: 'accessibility id', value: 'password' }
[0-0] 2023-11-30T09:45:51.922Z INFO webdriver: RESULT null
[0-0] 2023-11-30T09:45:51.923Z INFO webdriver: COMMAND getElementTagName("42.2493634.4.5.1.29")
[0-0] 2023-11-30T09:45:51.923Z INFO webdriver: [GET] http://127.0.0.1:4723/session/fbf9e063-3ff8-432a-840e-7e5552c3e771/element/42.2493634.4.5.1.29/name
[0-0] 2023-11-30T09:45:53.029Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '42.2493634.4.5.1.3',
[0-0]   ELEMENT: '42.2493634.4.5.1.3'
[0-0] }
[0-0] 2023-11-30T09:45:53.034Z INFO webdriver: RESULT WebdriverIO.Element<42.2493634.4.5.1.3>
[0-0] 2023-11-30T09:45:53.034Z INFO webdriver: COMMAND elementClear("42.2493634.4.5.1.3")
[0-0] 2023-11-30T09:45:53.035Z INFO webdriver: [POST] http://127.0.0.1:4723/session/fbf9e063-3ff8-432a-840e-7e5552c3e771/element/42.2493634.4.5.1.3/clear
[0-0] 2023-11-30T09:45:53.040Z INFO webdriver: RESULT ControlType.Edit
[0-0] 2023-11-30T09:45:53.045Z DEBUG @wdio/utils:shim: Finished to run "afterStep" hook in 0ms
[0-0] Error in "0: And I am logged on "DieManufacturing" as "'foo@bar.com" with password "pass""
Error: Malformed type for "text" parameter of command elementSendKeys
Expected: string
Actual: object

For more info see https://w3c.github.io/webdriver/#dfn-element-send-keys

    at Element.protocolCommand (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriver/build/command.js:70:23)
    at Element.wrapCommandFn (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/shim.js:82:38)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Element.wrapCommandFn (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/shim.js:82:29)
    at async Element.elementErrorHandlerCallbackFn (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriverio/build/middlewares.js:18:32)
    at async Element.wrapCommandFn (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/shim.js:82:29)
    at async Element.wrapCommandFn (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/shim.js:82:29)
    at async Element.elementErrorHandlerCallbackFn (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriverio/build/middlewares.js:18:32)
    at async Element.wrapCommandFn (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/shim.js:82:29)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
That's odd, I don't know the WinAppDriver but it is using the old jsonwire protocol 🤔

I wonder if there's a way to use Webdriver instead of the deprecated protocol.

**Comment by christian-bromann** [comment]
> I wonder if there's a way to use Webdriver instead of the deprecated protocol.

I pushed a change to make WebdriverIO recognise this as WebDriver session. As more platforms adopt it we have to refine these utility functions to ensure we detect it right.

**Comment by lacell75** [comment]
> @lacell75 would you mind sharing a little bit what setup you are using to run Windows tests? There is currently not much [documentation](https://webdriver.io/docs/desktop-testing/windows) on that because I thought WinAppDriver is not maintained anymore. I am very curious if there are other options.

Currently, I use WinappDriver and you can find a minimal setup to work with selenium here  : https://github.com/microsoft/WinAppDriver/blob/master/Docs/SeleniumGrid.md 
I can share a projet with webdriverIO and appium only if you want.

**Comment by christian-bromann** [comment]
Thanks for the information. I think I can't recommend this approach to other WebdriverIO users given that the project seems dead. It is great to see that it works for you though. I hope MS will pick up maintenance for it soon.
