### ISSUE TITLE
[🐛 Bug]:  Error in "AfterTest Hook" invalid session id when clicking on a login button

### ISSUE THREAD

**Issue by en-aplecan** [webdriverio/webdriverio#11769]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.19.0

### Node.js Version

v16.15.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
[{
                maxInstances: 1,
                browserName: 'chrome',
                //   acceptInsecureCerts: true,
                'goog:chromeOptions': {
                    args: ['--headless',
                        '--disable-gpu',
                        '--disable-software-rasterizer',
                        '--window-size=1920,1080'],
                    prefs: {
                        'browser.download.dir': downloadDir,
                        'browser.download.folderList': 2,
                    }
                },
            }]
```

### What happened?

Looks like Invalid session id occurs when I am trying to click on the login button. Weird thing is that sometimes the test manage to click on the button, sometimes just throws the error invalid session is.
Another mention is that this error I manage to reproduce just on Gitlab, when I am running it on my local machine every time the test pass. 

### How to reproduce the bug.

import basePage from '../base.page';

const locators = {
    username: '#username',
    password: '#password',
    btnLogin: '.ibexa-login__btn--sign-in',
};

class LoginPage extends basePage {

    open() {
        return super.open(`${process.env.IBEXA_URL}`);
    }

    async openNewBrowserWindow(url = process.env.IBEXA_URL) {
        return super.openNewBrowserWindow(url);
    }

    async typeUsername(username) {
        logger.info(`Typing username...`);
        await super.typeText(locators.username, username);
    }

    async typePassword(password) {
        logger.info(`Typing password...`);
        await super.typeText(locators.password, password);
    }

    async clickLoginButton() {
        logger.info(`Clicking on login button...`);
        await super.clickElement(locators.btnLogin);
    }

    /**
     * Steps
     */

    async login(username, password) {
        logger.info(`Log in to application as user '${username}'.`);
        await this.typeUsername(username);
        await this.typePassword(password);
        await this.clickLoginButton();
    }
}

export default new LoginPage();

### Relevant log output

```typescript
GITLAB LOGS:
[0-0] 2023-12-01 09:39:36 info: Typing username...
[0-0] 2023-12-01 09:39:36 info: Typing password...
[0-0] 2023-12-01 09:39:36 info: Clicking on login button...
[0-0] Error in "AfterTest Hook"
invalid session id
[0-0] invalid session id in "Content Structure: as a local admin, the user can see his content structure..should be able to see the content structure."
invalid session id: invalid session id
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LoginPage.clickElement (/builds/dihk/ahk-customer-platform/automation-tests/test/pageobjects/base.page.js:36:9)
    at LoginPage.clickLoginButton (/builds/dihk/ahk-customer-platform/automation-tests/test/pageobjects/ibexa/login.page.js:31:9)
    at LoginPage.login (/builds/dihk/ahk-customer-platform/automation-tests/test/pageobjects/ibexa/login.page.js:42:9)
    at Context.<anonymous> (/builds/dihk/ahk-customer-platform/automation-tests/test/specs/healthcheks/contentStructure.js:18:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by en-aplecan** [comment]
gitlab.yml file 
cache:
  paths:
    - node_modules/

default:
  image: alpine:latest

variables:
  FF_NETWORK_PER_BUILD: 1

stages:
  - test

test:
  stage: test
  #  tags:
  #    - internal
  services:
    - name: selenium/hub:latest
      alias: selenium-hub
    - name: selenium/node-chrome:latest
      alias: node-chrome
  variables:
    # for the hub
    HUB_HOST: selenium-hub
    HUB_PORT: 4444
    GRID_BROWSER_TIMEOUT: 45000
    GRID_TIMEOUT: 45000
    # for the node-firefox
    SE_NODE_SHM_SIZE: 2gb # this does not have any effect, because it can only be set in the 'config.toml'. Therefore, I can't ramp up the No. of instances.
    SE_EVENT_BUS_HOST: selenium-hub
    SE_EVENT_BUS_PUBLISH_PORT: 4442
    SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    SE_NODE_GRID_URL: http://selenium-hub:4444
    LOCAL_ADMIN_PASS: "$LOCAL_ADMIN_PASS"
    STANDARD_TIMEOUT: "$STANDARD_TIMEOUT"

  before_script:
    - echo "This pipeline was started by '$CI_PIPELINE_SOURCE'" # possible values are push, web, schedule, merge_request_event, etc.
    - echo "The environment passed was '$ENVIRONMENT'"
    - echo "The test suite passed was '$SUITE'"

    - if [[ "$SUITE" == "" ]]; then
      echo "The variable 'SUITE' is empty or was NOT passed. Setting default value as SUITE=healthChecks";
      export SUITE="healthChecks";
      fi

    - echo "The job will now run with the value suite=$SUITE";

    - apk update -q
    - apk add --update nodejs npm openjdk8-jre -q
    - npm --silent install
    - node --version
    - npm -version
  script:
    - ENV=$ENVIRONMENT npm test -- --suite $SUITE
  after_script:
    - npm run generate
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - logs
      - report/allure-report

**Comment by en-aplecan** [comment]
Thank you for your answer @christian-bromann. Here are Wdio logs:

`2023-12-01T13:14:22.735Z INFO @wdio/utils: Connecting to existing driver at http://selenium2023-12-01T2023-12-01T13:14:26.955Z ERROR @wdio/utils:shim: invalid session id: invalid session id
    at getErrorFromResponseBody (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriver/build/utils.js:195:12)
    at NodeJSRequest._request (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriver/build/request/index.js:193:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Browser.wrapCommandFn (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/webdriverio/node_modules/@wdio/utils/build/shim.js:82:29)
    at Object.afterTest (/builds/dihk/ahk-customer-platform/automation-tests/wdio.conf.js:95:13)
    at async Promise.all (index 0)
    at executeHooksWithArgs (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/@wdio/mocha-framework/node_modules/@wdio/utils/build/shim.js:60:20)
    at Context.testFrameworkFnWrapper (file:///builds/dihk/ahk-customer-platform/automation-tests/node_modules/@wdio/mocha-framework/node_modules/@wdio/utils/build/test-framework/testFnWrapper.js:70:40)
Z INFO webdriver: RESULT [ 'F66EF870D17EAA848A3CBCBEAA6C6F6C' ]
2023-12-01T13:14:23.667Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2023-12-01T13:14:23.667Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/execute/sync
2023-12-01T13:14:23.668Z INFO webdriver: DATA {
  script: 'newWindow(...) [149 bytes]',
  args: [
    'https://development-q5nzhaa-mnlkwasnvwjay.fr-4.platformsh.site/admin',
    '',
    ''
  ]
}
2023-12-01T13:14:23.693Z INFO webdriver: RESULT null
2023-12-01T13:14:23.694Z INFO webdriver: COMMAND getWindowHandles()
2023-12-01T13:14:23.694Z INFO webdriver: [GET] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/window/handles
2023-12-01T13:14:23.996Z INFO webdriver: RESULT [
  'F66EF870D17EAA848A3CBCBEAA6C6F6C',
  '2D7BE8C7D7C64E9656F5DFCE1108EBBE'
]
2023-12-01T13:14:23.996Z INFO webdriver: COMMAND getWindowHandles()
2023-12-01T13:14:23.997Z INFO webdriver: [GET] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/window/handles
2023-12-01T13:14:24.013Z INFO webdriver: RESULT [
  'F66EF870D17EAA848A3CBCBEAA6C6F6C',
  '2D7BE8C7D7C64E9656F5DFCE1108EBBE'
]
2023-12-01T13:14:24.014Z INFO webdriver: COMMAND switchToWindow("<Screenshot[base64]>")
2023-12-01T13:14:24.014Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/window
2023-12-01T13:14:24.014Z INFO webdriver: DATA { handle: '2D7BE8C7D7C64E9656F5DFCE1108EBBE' }
2023-12-01T13:14:24.032Z INFO webdriver: RESULT null
2023-12-01T13:14:24.032Z INFO webdriver: COMMAND getWindowHandles()
2023-12-01T13:14:24.032Z INFO webdriver: [GET] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/window/handles
2023-12-01T13:14:24.048Z INFO webdriver: RESULT [
  'F66EF870D17EAA848A3CBCBEAA6C6F6C',
  '2D7BE8C7D7C64E9656F5DFCE1108EBBE'
]
2023-12-01T13:14:24.051Z INFO webdriver: COMMAND findElement("css selector", "#username")
2023-12-01T13:14:24.051Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element
2023-12-01T13:14:24.051Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
2023-12-01T13:14:24.129Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_5'
}
2023-12-01T13:14:24.138Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2023-12-01T13:14:24.138Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/execute/sync
2023-12-01T13:14:24.138Z INFO webdriver: DATA {
  script: 'isElementDisplayed(...) [8297 bytes]',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_5',
      ELEMENT: '81D91A3EB27334F820120B0EC04756D3_element_5'
    }
  ]
}
2023-12-01T13:14:24.165Z INFO webdriver: RESULT true
2023-12-01T13:14:24.166Z INFO webdriver: COMMAND findElement("css selector", "#username")
2023-12-01T13:14:24.167Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element
2023-12-01T13:14:24.167Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
2023-12-01T13:14:24.187Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_5'
}
2023-12-01T13:14:24.191Z INFO webdriver: COMMAND elementClear("81D91A3EB27334F820120B0EC04756D3_element_5")
2023-12-01T13:14:24.191Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element/81D91A3EB27334F820120B0EC04756D3_element_5/clear
2023-12-01T13:14:24.239Z INFO webdriver: RESULT null
2023-12-01T13:14:24.240Z INFO webdriver: COMMAND elementSendKeys("81D91A3EB27334F820120B0EC04756D3_element_5", "norway_e2e")
2023-12-01T13:14:24.240Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element/81D91A3EB27334F820120B0EC04756D3_element_5/value
2023-12-01T13:14:24.240Z INFO webdriver: DATA { text: 'norway_e2e' }
2023-12-01T13:14:24.284Z INFO webdriver: RESULT null
2023-12-01T13:14:24.285Z INFO webdriver: COMMAND findElement("css selector", "#password")
2023-12-01T13:14:24.285Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element
2023-12-01T13:14:24.285Z INFO webdriver: DATA { using: 'css selector', value: '#password' }
2023-12-01T13:14:24.310Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_10'
}
2023-12-01T13:14:24.312Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2023-12-01T13:14:24.312Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/execute/sync
2023-12-01T13:14:24.313Z INFO webdriver: DATA {
  script: 'isElementDisplayed(...) [8297 bytes]',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_10',
      ELEMENT: '81D91A3EB27334F820120B0EC04756D3_element_10'
    }
  ]
}
2023-12-01T13:14:24.337Z INFO webdriver: RESULT true
2023-12-01T13:14:24.337Z INFO webdriver: COMMAND findElement("css selector", "#password")
2023-12-01T13:14:24.337Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element
2023-12-01T13:14:24.337Z INFO webdriver: DATA { using: 'css selector', value: '#password' }
2023-12-01T13:14:24.357Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_10'
}
2023-12-01T13:14:24.361Z INFO webdriver: COMMAND elementClear("81D91A3EB27334F820120B0EC04756D3_element_10")
2023-12-01T13:14:24.361Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element/81D91A3EB27334F820120B0EC04756D3_element_10/clear
2023-12-01T13:14:24.398Z INFO webdriver: RESULT null
2023-12-01T13:14:24.399Z INFO webdriver: COMMAND elementSendKeys("81D91A3EB27334F820120B0EC04756D3_element_10", "<Screenshot[base64]>")
2023-12-01T13:14:24.399Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element/81D91A3EB27334F820120B0EC04756D3_element_10/value
2023-12-01T13:14:24.399Z INFO webdriver: DATA { text: 'MzJkYjI4MmNhZDlk' }
2023-12-01T13:14:24.460Z INFO webdriver: RESULT null
2023-12-01T13:14:24.461Z INFO webdriver: COMMAND findElement("css selector", ".ibexa-login__btn--sign-in")
2023-12-01T13:14:24.461Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element
2023-12-01T13:14:24.461Z INFO webdriver: DATA { using: 'css selector', value: '.ibexa-login__btn--sign-in' }
2023-12-01T13:14:24.485Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_13'
}
2023-12-01T13:14:24.488Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2023-12-01T13:14:24.488Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/execute/sync
2023-12-01T13:14:24.488Z INFO webdriver: DATA {
  script: 'isElementDisplayed(...) [8297 bytes]',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_13',
      ELEMENT: '81D91A3EB27334F820120B0EC04756D3_element_13'
    }
  ]
}
2023-12-01T13:14:24.510Z INFO webdriver: RESULT true
2023-12-01T13:14:24.510Z INFO webdriver: COMMAND findElement("css selector", ".ibexa-login__btn--sign-in")
2023-12-01T13:14:24.510Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element
2023-12-01T13:14:24.510Z INFO webdriver: DATA { using: 'css selector', value: '.ibexa-login__btn--sign-in' }
2023-12-01T13:14:24.531Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_13'
}
2023-12-01T13:14:24.534Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2023-12-01T13:14:24.535Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/execute/sync
2023-12-01T13:14:24.535Z INFO webdriver: DATA {
  script: 'isElementDisplayed(...) [8297 bytes]',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_13',
      ELEMENT: '81D91A3EB27334F820120B0EC04756D3_element_13'
    }
  ]
}
2023-12-01T13:14:24.553Z INFO webdriver: RESULT true
2023-12-01T13:14:24.553Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2023-12-01T13:14:24.553Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/execute/sync
2023-12-01T13:14:24.553Z INFO webdriver: DATA {
  script: 'isElementClickable(...) [5351 bytes]',
  args: [
    {
      'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_13',
      ELEMENT: '81D91A3EB27334F820120B0EC04756D3_element_13'
    }
  ]
}
2023-12-01T13:14:24.575Z INFO webdriver: RESULT true
2023-12-01T13:14:24.575Z INFO webdriver: COMMAND findElement("css selector", ".ibexa-login__btn--sign-in")
2023-12-01T13:14:24.575Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element
2023-12-01T13:14:24.575Z INFO webdriver: DATA { using: 'css selector', value: '.ibexa-login__btn--sign-in' }
2023-12-01T13:14:24.593Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '81D91A3EB27334F820120B0EC04756D3_element_13'
}
2023-12-01T13:14:24.596Z INFO webdriver: COMMAND elementClick("81D91A3EB27334F820120B0EC04756D3_element_13")
2023-12-01T13:14:24.597Z INFO webdriver: [POST] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/element/81D91A3EB27334F820120B0EC04756D3_element_13/click
2023-12-01T13:14:26.936Z ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id
2023-12-01T13:14:26.938Z INFO webdriver: COMMAND takeScreenshot()
2023-12-01T13:14:26.939Z INFO webdriver: [GET] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/screenshot
2023-12-01T13:14:26.954Z ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id
2023-12-01T13:14:26.959Z INFO webdriver: COMMAND getLogTypes()
2023-12-01T13:14:26.959Z INFO webdriver: [GET] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3/se/log/types
2023-12-01T13:14:26.975Z ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id
2023-12-01T13:14:26.975Z INFO webdriver: COMMAND deleteSession()
2023-12-01T13:14:26.976Z INFO webdriver: [DELETE] http://selenium-hub:4444/session/b8133e068feb4b21d7440d570196bec3
2023-12-01T13:14:27.005Z INFO webdriver: RESULT null
`

**Comment by christian-bromann** [comment]
@en-aplecan thanks for providing these.

> 2023-12-01T13:14:26.936Z ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id

As you can see from these logs it seems like something with the Selenium server failed as it can't recognised a session. This could be due to the fact that the session was shut down previously or the server restarted. You might want to look into the Selenium server logs as it might have informations on this.

I will go ahead and close the issue as there is nothing to be "fixed" in WebdriverIO. I am happy to answer more questions and encourage to join our [Discord](https://discord.webdriver.io) server. Thanks!
