### ISSUE TITLE
setValue isn't chainable when using WDIO

### ISSUE THREAD

**Issue by mal** [webdriverio/webdriverio#1178]
```js
const assert = require('assert')

describe('my feature', function () {
  it('should do something', function () {

    browser
      .url('https://duckduckgo.com/')
      .setValue('#search_form_input_homepage', 'WebdriverIO')
      .click('#search_button_homepage')

    var title = browser.getTitle()
    assert.equal(title, 'WebdriverIO (Software) at DuckDuckGo')
  })
})
```

output
```
± ./node_modules/.bin/wdio wdio.conf.js

․

0 passing (2.20s)
1 failing

1) should do something:
Cannot read property 'click' of null
running chrome
TypeError: Cannot read property 'click' of null
    at Context.<anonymous> (/home/mal/code/wdio-test/test/test.js:11:7)
    at /home/mal/code/wdio-test/node_modules/wdio-sync/build/index.js:569:2
```

npm
```
± npm list --depth=0
/home/mal/code/idio/widget
├── wdio-mocha-framework@0.2.11
└── webdriverio@4.0.4
```

**Comment by christian-bromann** [comment]
@mal `setValue` returns `null` so you can't chain a command after that. I will have to fix that, this is a known issue. Do that:

```js
describe('my feature', function () {
  it('should do something', function () {

    browser
      .url('https://duckduckgo.com/')
      .setValue('#search_form_input_homepage', 'WebdriverIO')
      
    browser.click('#search_button_homepage')
    var title = browser.getTitle()
    assert.equal(title, 'WebdriverIO (Software) at DuckDuckGo')
  })
})
```
