### ISSUE TITLE
[🐛 Bug]: browser.keys method does not work properly for Windows Application

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#11818]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    maxInstances: 7,
    platformName: 'WINDOWS',
    'appium:app': `C:\\Program Files\\DieManufacturing.Dev\\Fr.DieManufacturing.Client.exe`,
    'appium:appArguments': '-noCloseConfirmationPopUp -shouldDisplayDiesToTake',
    'ms:experimental-webdriver': true,
    'ms:waitForAppLaunch': '10',
}
```

### What happened?

browser.keys  does not work now because the wrong command is used. 
`actions` is used instead of `sendKeys`. actions API is not implemented in winappdriver

### What is your expected behavior?

sendKeys API should be used

### How to reproduce the bug.

```
await browser.keys(['Control', '0', 'NULL']);
```

### Relevant log output

```typescript
[0-0] 2023-12-06T10:30:08.886Z INFO webdriver: COMMAND performActions(<object>)
[0-0] 2023-12-06T10:30:08.887Z INFO webdriver: [POST] http://172.30.0.31:4444/wd/hub/session/e1c80268-199a-491f-a574-18e365103d2d/actions
[0-0] 2023-12-06T10:30:08.887Z INFO webdriver: DATA {
[0-0]   actions: [ { id: 'action3', type: 'key', parameters: {}, actions: [Array] } ]
[0-0] }
[0-0] 2023-12-06T10:30:09.040Z DEBUG webdriver: request failed due to response error: unsupported operation
[0-0] 2023-12-06T10:30:09.041Z WARN webdriver: Request failed with status 500 due to Currently key input source type is not supported
[0-0] 2023-12-06T10:30:09.041Z INFO webdriver: Retrying 1/1
[0-0] 2023-12-06T10:30:09.041Z INFO webdriver: [POST] http://172.30.0.31:4444/wd/hub/session/e1c80268-199a-491f-a574-18e365103d2d/actions
[0-0] 2023-12-06T10:30:09.041Z INFO webdriver: DATA {
[0-0]   actions: [ { id: 'action3', type: 'key', parameters: {}, actions: [Array] } ]
[0-0] }
[0-0] 2023-12-06T10:30:09.219Z DEBUG webdriver: request failed due to response error: unsupported operation
[0-0] 2023-12-06T10:30:09.219Z ERROR webdriver: Request failed with status 500 due to unsupported operation: Currently key input source type is not supported
[0-0] 2023-12-06T10:30:09.220Z DEBUG @wdio/utils:shim: Finished to run "afterFeature" hook in 337ms
[0-0] 2023-12-06T10:30:09.220Z ERROR @wdio/utils:shim: unsupported operation: Currently key input source type is not supported
[0-0]     at getErrorFromResponseBody (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriver/build/utils.js:195:12)
[0-0]     at NodeJSRequest._request (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriver/build/request/index.js:193:23)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async Browser.wrapCommandFn (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/shim.js:82:29)
[0-0]     at async KeyAction.perform (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriverio/build/utils/actions/base.js:61:9)
[0-0]     at async Browser.wrapCommandFn (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/shim.js:82:29)
[0-0]     at async Object.afterFeature (file:///C:/2-gitlab/end-to-end-tests-wdio/wdio.conf.ts:575:7)
[0-0]     at async Promise.all (index 0)
[0-0]     at async executeHooksWithArgs (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/shim.js:60:20)
[0-0]     at async wdioHookAfterFeature (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/cucumber-framework/build/index.js:313:13)
[0-0]     at async wrapPromiseWithTimeout (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\time.ts:55:10)
[0-0]     at async Object.run (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\user_code_runner.ts:86:16)
[0-0]     at async Runtime.runTestRunHooks (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\runtime\run_test_run_hooks.ts:21:29)
[0-0]     at async Runtime.start (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\runtime\index.ts:118:5)
[0-0]     at async runCucumber (C:\2-gitlab\end-to-end-tests-wdio\node_modules\@cucumber\cucumber\src\api\run_cucumber.ts:125:19)
[0-0]     at async CucumberAdapter.run (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/cucumber-framework/build/index.js:188:33)
[0-0]     at async Runner.run (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/runner/build/index.js:148:24)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> sendKeys API should be used

`sendKeys` is a JSONWP command which we deprecated and likely remove in `v9`. WinAppDriver has not received any WebDriver updates which is why we [don't recommend](https://webdriver.io/docs/desktop-testing/windows) using it. I am aware that this is currently probably the only way to test native Windows apps but there is nothing we can change about that.

I will go ahead and close as `wont-do`
