### ISSUE TITLE
[🐛 Bug]: <Target window could not be located with MicrosoftEdge Browser>

### ISSUE THREAD

**Issue by edward1224** [webdriverio/webdriverio#11829]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.24.13

### Node.js Version

18.18.2

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
    maxInstances: 1,
    browserName: 'MicrosoftEdge',
    "ms:edgeOptions": {
        excludeSwitches: ["enable-automation"],
    }
}]
```

### What happened?

Hi, I noticed this behavior starting from MicrosoftEdge v119, could be even earlier. It was still fine when I was using v115. But the thing here is whenever I include this line
"excludeSwitches: ["enable-automation"]" in the capabilities block, then I would get an error. It seems like webdriverio is executing the actions already on the profile sign in window instead of waiting for the next window to appear.

![image](https://github.com/webdriverio/webdriverio/assets/40449035/3e62f10e-f555-49de-af2c-4bb8439b4425)

### What is your expected behavior?

The issue is a dilemma, I'll try to express it as best as I could.

Previously in MicrosoftEdge v115, with that "enable-automation" line, the webdriver will always ignore the profile sign in window, and able to catch the next window and this gonna appear.

I tried removing the "enable-automation" line in MicrosoftEdge v119, target window can be located but it executes actions on a tiny window in the center of screen without actually spawning the usual browser we would see(with tabs, url header, settings icon etc etc). It actually impacts in a way that I could not create new tab while running the script (browser.window).

I would expect it to behave the same as in MicrosoftEdge v115, to not execute actions during profile sign in window, wait till the actual Browser client spawns, capture that window, then start executing the scripts.

### How to reproduce the bug.

1. Standard npm init wdio .
2. Only MicrosoftEdge is selected
package.json for reference:
{
  "name": "my-new-project",
  "type": "module",
  "devDependencies": {
    "@wdio/cli": "^8.24.16",
    "@wdio/cucumber-framework": "^8.24.13",
    "@wdio/local-runner": "^8.24.12",
    "@wdio/spec-reporter": "^8.24.12",
    "ts-node": "^10.9.1",
    "typescript": "^5.3.3",
    "wdio-wait-for": "^3.0.9"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.conf.ts"
  }
}
3. Add this into capabilities
"ms:edgeOptions": {
    excludeSwitches: ["enable-automation"],
}
4. Execute npm run wdio
5. Do nothing when the profile sign in windows appear
![image](https://github.com/webdriverio/webdriverio/assets/40449035/a2abf081-90c9-488f-90ac-4edb30cbb7f5)
6. The test would fail itself after a few seconds.

### Relevant log output

```typescript
C:\Project\testproject\test wdio latest>npm run wdio

> wdio
> wdio run ./wdio.conf.ts


Execution of 1 workers started at 2023-12-08T08:38:44.297Z

2023-12-08T08:38:44.343Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-12-08T08:38:44.345Z INFO @wdio/utils: Setting up browser driver for: MicrosoftEdge@stable
2023-12-08T08:38:44.346Z INFO @wdio/utils: Setting up browser binaries for: MicrosoftEdge@stable
2023-12-08T08:38:44.351Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-12-08T08:38:44.352Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] 2023-12-08T08:38:47.197Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in MicrosoftEdge - file:///C:/Project/testproject/test%20wdio%20latest/features/login.feature
[0-0] 2023-12-08T08:38:48.398Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-12-08T08:38:48.907Z INFO edgedriver: Starting EdgeDriver at C:\Users\bg0032\AppData\Local\Temp\msedgedriver.exe with params: --port=58239 --allowed-ips=0.0.0.0 --allowed-origins=*
[0-0] 2023-12-08T08:38:48.985Z INFO edgedriver: Starting Microsoft Edge WebDriver 119.0.2151.97 (42f50dec8b7a97d2cd39634128418ccfb4ef77b8) on port 58239
[0-0] 2023-12-08T08:38:48.986Z INFO edgedriver: To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver
[0-0] 2023-12-08T08:38:48.986Z INFO edgedriver:
[0-0] 2023-12-08T08:38:48.986Z INFO edgedriver: Remote connections are allowed by an allowlist (0.0.0.0).
[0-0] 2023-12-08T08:38:48.986Z INFO edgedriver: Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.
[0-0] 2023-12-08T08:38:48.986Z INFO edgedriver:
[0-0] 2023-12-08T08:38:49.068Z INFO edgedriver: Microsoft Edge WebDriver was started successfully.
[0-0] 2023-12-08T08:38:49.991Z INFO @wdio/utils: Started EdgeDriver in 1103ms on port 58239
[0-0] 2023-12-08T08:38:50.011Z INFO webdriver: [POST] http://0.0.0.0:58239/session
[0-0] 2023-12-08T08:38:50.011Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'MicrosoftEdge', 'ms:edgeOptions': [Object] },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'MicrosoftEdge',
[0-0]     'ms:edgeOptions': { excludeSwitches: [Array] }
[0-0]   }
[0-0] }
[19420:37744:1208/163850.615:ERROR:policy_logger.cc(157)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled.
[19420:37744:1208/163850.688:ERROR:assistance_home_client.cc(32)] File path C:\Users\bg0032\AppData\Local\Temp\scoped_dir24916_572907872\Default

DevTools listening on ws://127.0.0.1:58245/devtools/browser/a9451c90-7598-43fc-a7ec-46e5a90cd184
[0-0] 2023-12-08T08:38:53.436Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/login")
[0-0] 2023-12-08T08:38:53.437Z INFO webdriver: [POST] http://0.0.0.0:58239/session/2138d9c6c45478c17646522b65150545/url
[0-0] 2023-12-08T08:38:53.437Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[19420:37744:1208/163853.720:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
[19420:37744:1208/163854.201:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
Opening in existing browser session.
[0-0] 2023-12-08T08:38:57.332Z INFO webdriver: RESULT null
[0-0] 2023-12-08T08:38:57.336Z INFO webdriver: COMMAND findElement("css selector", "#username")
[0-0] 2023-12-08T08:38:57.337Z INFO webdriver: [POST] http://0.0.0.0:58239/session/2138d9c6c45478c17646522b65150545/element
[0-0] 2023-12-08T08:38:57.337Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2023-12-08T08:38:57.347Z WARN webdriver: Request failed with status 404 due to no such window: target window already closed
[0-0] from unknown error: web view not found
[0-0]   (Session info: MicrosoftEdge=119.0.2151.58)
[0-0] 2023-12-08T08:38:57.348Z INFO webdriver: Retrying 1/3
[0-0] 2023-12-08T08:38:57.348Z INFO webdriver: [POST] http://0.0.0.0:58239/session/2138d9c6c45478c17646522b65150545/element
[0-0] 2023-12-08T08:38:57.348Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2023-12-08T08:38:57.352Z WARN webdriver: Request failed with status 404 due to no such window: target window already closed
[0-0] from unknown error: web view not found
[0-0]   (Session info: MicrosoftEdge=119.0.2151.58)
[0-0] 2023-12-08T08:38:57.353Z INFO webdriver: Retrying 2/3
[0-0] 2023-12-08T08:38:57.353Z INFO webdriver: [POST] http://0.0.0.0:58239/session/2138d9c6c45478c17646522b65150545/element
[0-0] 2023-12-08T08:38:57.353Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2023-12-08T08:38:57.358Z INFO webdriver: Retrying 3/3
[0-0] 2023-12-08T08:38:57.358Z INFO webdriver: [POST] http://0.0.0.0:58239/session/2138d9c6c45478c17646522b65150545/element
[0-0] 2023-12-08T08:38:57.358Z INFO webdriver: DATA { using: 'css selector', value: '#username' }
[0-0] 2023-12-08T08:38:57.358Z WARN webdriver: Request failed with status 404 due to no such window: target window already closed
[0-0] from unknown error: web view not found
[0-0]   (Session info: MicrosoftEdge=119.0.2151.58)
[0-0] 2023-12-08T08:38:57.362Z ERROR webdriver: Request failed with status 404 due to no such window: no such window: target window already closed
[0-0] from unknown error: web view not found
[0-0]   (Session info: MicrosoftEdge=119.0.2151.58)
[0-0] Error in "0: When I login with tomsmith and SuperSecretPassword!"
no such window: no such window: target window already closed
from unknown error: web view not found
  (Session info: MicrosoftEdge=119.0.2151.58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LoginPage.login (file:///C:/Project/testproject/test%20wdio%20latest/features/pageobjects/login.page.ts:28:9)
    at async World.<anonymous> (file:///C:/Project/testproject/test%20wdio%20latest/features/step-definitions/steps.ts:16:5)
    at async wrapPromiseWithTimeout (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\time.ts:55:10)
    at async Object.run (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\user_code_runner.ts:86:16)
    at async Object.run (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:20)
    at async TestCaseRunner.invokeStep (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:137:12)
    at async TestCaseRunner.runStep (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:334:20)
    at async C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:240:34
[0-0] 2023-12-08T08:38:57.384Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/login")
[0-0] 2023-12-08T08:38:57.384Z INFO webdriver: [POST] http://0.0.0.0:58239/session/2138d9c6c45478c17646522b65150545/url
[0-0] 2023-12-08T08:38:57.384Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2023-12-08T08:38:57.388Z WARN webdriver: Request failed with status 404 due to no such window: target window already closed
[0-0] from unknown error: web view not found
[0-0]   (Session info: MicrosoftEdge=119.0.2151.58)
[0-0] 2023-12-08T08:38:57.389Z INFO webdriver: Retrying 1/3
[0-0] 2023-12-08T08:38:57.389Z INFO webdriver: [POST] http://0.0.0.0:58239/session/2138d9c6c45478c17646522b65150545/url
[0-0] 2023-12-08T08:38:57.389Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2023-12-08T08:38:57.393Z INFO webdriver: Retrying 2/3
[0-0] 2023-12-08T08:38:57.393Z INFO webdriver: [POST] http://0.0.0.0:58239/session/2138d9c6c45478c17646522b65150545/url
[0-0] 2023-12-08T08:38:57.393Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2023-12-08T08:38:57.393Z WARN webdriver: Request failed with status 404 due to no such window: target window already closed
[0-0] from unknown error: web view not found
[0-0]   (Session info: MicrosoftEdge=119.0.2151.58)
[0-0] 2023-12-08T08:38:57.397Z WARN webdriver: Request failed with status 404 due to no such window: target window already closed
[0-0] from unknown error: web view not found
[0-0]   (Session info: MicrosoftEdge=119.0.2151.58)
[0-0] 2023-12-08T08:38:57.404Z ERROR webdriver: Request failed with status 404 due to no such window: no such window: target window already closed
[0-0] from unknown error: web view not found
[0-0]   (Session info: MicrosoftEdge=119.0.2151.58)
[0-0] 2023-12-08T08:38:57.398Z INFO webdriver: Retrying 3/3
[0-0] 2023-12-08T08:38:57.398Z INFO webdriver: [POST] http://0.0.0.0:58239/session/2138d9c6c45478c17646522b65150545/url
[0-0] 2023-12-08T08:38:57.398Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/login' }
[0-0] 2023-12-08T08:38:57.408Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-12-08T08:38:57.409Z INFO webdriver: [DELETE] http://0.0.0.0:58239/session/2138d9c6c45478c17646522b65150545
[0-0] Error in "1: Given I am on the login page"
no such window: no such window: target window already closed
from unknown error: web view not found
  (Session info: MicrosoftEdge=119.0.2151.58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async World.<anonymous> (file:///C:/Project/testproject/test%20wdio%20latest/features/step-definitions/steps.ts:12:5)
    at async wrapPromiseWithTimeout (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\time.ts:55:10)
    at async Object.run (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\user_code_runner.ts:86:16)
    at async Object.run (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:20)
    at async TestCaseRunner.invokeStep (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:137:12)
    at async TestCaseRunner.runStep (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:334:20)
    at async C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:240:34
    at async TestCaseRunner.aroundTestStep (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:170:28)
    at async TestCaseRunner.runAttempt (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:218:7)
[0-0] 2023-12-08T08:38:57.595Z INFO webdriver: RESULT null
[0-0] 2023-12-08T08:38:57.596Z INFO webdriver: Kill C:\Users\bg0032\AppData\Local\Temp\msedgedriver.exe driver process with command line: --port=58239 --allowed-ips=0.0.0.0 --allowed-origins=*
[0-0] FAILED in MicrosoftEdge - file:///C:/Project/testproject/test%20wdio%20latest/features/login.feature
2023-12-08T08:38:57.724Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-12-08T08:38:57.726Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[msedge 119.0.2151.58 windows #0-0] Running: msedge (v119.0.2151.58) on windows
[msedge 119.0.2151.58 windows #0-0] Session ID: 2138d9c6c45478c17646522b65150545
[msedge 119.0.2151.58 windows #0-0]
[msedge 119.0.2151.58 windows #0-0] » \features\login.feature
[msedge 119.0.2151.58 windows #0-0] The Internet Guinea Pig Website
[msedge 119.0.2151.58 windows #0-0] As a user, I can log into the secure area
[msedge 119.0.2151.58 windows #0-0]    ✓ Given I am on the login page
[msedge 119.0.2151.58 windows #0-0]    ✖ When I login with tomsmith and SuperSecretPassword!
[msedge 119.0.2151.58 windows #0-0]    - Then I should see a flash message saying You logged into a secure area!
[msedge 119.0.2151.58 windows #0-0]
[msedge 119.0.2151.58 windows #0-0] As a user, I can log into the secure area
[msedge 119.0.2151.58 windows #0-0]    ✖ Given I am on the login page
[msedge 119.0.2151.58 windows #0-0]    - When I login with foobar and barfoo
[msedge 119.0.2151.58 windows #0-0]    - Then I should see a flash message saying Your username is invalid!
[msedge 119.0.2151.58 windows #0-0]
[msedge 119.0.2151.58 windows #0-0] 1 passing (4.3s)
[msedge 119.0.2151.58 windows #0-0] 2 failing
[msedge 119.0.2151.58 windows #0-0] 3 skipped
[msedge 119.0.2151.58 windows #0-0]
[msedge 119.0.2151.58 windows #0-0] 1) As a user, I can log into the secure area When I login with tomsmith and SuperSecretPassword!
[msedge 119.0.2151.58 windows #0-0] no such window: no such window: target window already closed
[msedge 119.0.2151.58 windows #0-0] no such window: no such window: target window already closed
[msedge 119.0.2151.58 windows #0-0] from unknown error: web view not found
[msedge 119.0.2151.58 windows #0-0]   (Session info: MicrosoftEdge=119.0.2151.58)
[msedge 119.0.2151.58 windows #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[msedge 119.0.2151.58 windows #0-0]     at async LoginPage.login (file:///C:/Project/testproject/test%20wdio%20latest/features/pageobjects/login.page.ts:28:9)
[msedge 119.0.2151.58 windows #0-0]     at async World.<anonymous> (file:///C:/Project/testproject/test%20wdio%20latest/features/step-definitions/steps.ts:16:5)
[msedge 119.0.2151.58 windows #0-0]     at async wrapPromiseWithTimeout (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\time.ts:55:10)
[msedge 119.0.2151.58 windows #0-0]     at async Object.run (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\user_code_runner.ts:86:16)
[msedge 119.0.2151.58 windows #0-0]     at async Object.run (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:20)
[msedge 119.0.2151.58 windows #0-0]     at async TestCaseRunner.invokeStep (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:137:12)
[msedge 119.0.2151.58 windows #0-0]     at async TestCaseRunner.runStep (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:334:20)
[msedge 119.0.2151.58 windows #0-0]     at async C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:240:34
[msedge 119.0.2151.58 windows #0-0]
[msedge 119.0.2151.58 windows #0-0] 2) As a user, I can log into the secure area Given I am on the login page
[msedge 119.0.2151.58 windows #0-0] no such window: no such window: target window already closed
[msedge 119.0.2151.58 windows #0-0] no such window: no such window: target window already closed
[msedge 119.0.2151.58 windows #0-0] from unknown error: web view not found
[msedge 119.0.2151.58 windows #0-0]   (Session info: MicrosoftEdge=119.0.2151.58)
[msedge 119.0.2151.58 windows #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[msedge 119.0.2151.58 windows #0-0]     at async World.<anonymous> (file:///C:/Project/testproject/test%20wdio%20latest/features/step-definitions/steps.ts:12:5)
[msedge 119.0.2151.58 windows #0-0]     at async wrapPromiseWithTimeout (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\time.ts:55:10)
[msedge 119.0.2151.58 windows #0-0]     at async Object.run (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\user_code_runner.ts:86:16)
[msedge 119.0.2151.58 windows #0-0]     at async Object.run (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:20)
[msedge 119.0.2151.58 windows #0-0]     at async TestCaseRunner.invokeStep (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:137:12)
[msedge 119.0.2151.58 windows #0-0]     at async TestCaseRunner.runStep (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:334:20)
[msedge 119.0.2151.58 windows #0-0]     at async C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:240:34
[msedge 119.0.2151.58 windows #0-0]     at async TestCaseRunner.aroundTestStep (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:170:28)
[msedge 119.0.2151.58 windows #0-0]     at async TestCaseRunner.runAttempt (C:\Project\testproject\test wdio latest\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:218:7)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:13

2023-12-08T08:38:57.733Z INFO @wdio/local-runner: Shutting down spawned worker
2023-12-08T08:38:57.986Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-12-08T08:38:57.987Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@edward1224 thanks for the very detailed issue!

Unfortunately there is nothing WebdriverIO can do to fix this. The problem is related to Microsoft Edge and Egdedriver in should be reported to the [browser team](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact).

**Comment by edward1224** [comment]
@christian-bromann 
Thanks for the quick response. I also suspect the issue is due to the change from Microsoft Edge or Edgedriver or even both. 

However, the issue started when webdriver treats the profile sign-in window is the main window to execute scripts on, hence I am seeing the whole demo scripts (navigation to heroku site and the rest of the actions) on that tiny window in the center. I am just thinking if there is a possibility to treat it otherwise.

**Comment by christian-bromann** [comment]
Can you switch windows and ignore the profile sign window?

**Comment by edward1224** [comment]
@christian-bromann 

Your comment actually gave me the idea for the workaround, it works perfectly whenever I run with Head/GUI mode. Note: headless mode was never an issue.
Below is the snippet on how I handled it, works for MicrosoftEdge Ver. 119:
```
beforeScenario: async function (world, context) {
// Workaround of an issue With MicrosoftEdge discovered on ver. 119 where profile sign-in window is treated as the window to execute test scripts on. (Tested on Webdriver v8.24.12)
// To mitigate this issue, we simply wait till the profile sign-in window closes itself and switch execution to the newly opened main window.
    if(isExecuteWithGUI){
        const profileSignInWindow = await browser.getWindowHandle();

        await browser.waitUntil(async() => {
            const mainWindow = await browser.getWindowHandles();
           
            if(mainWindow[0] !== profileSignInWindow) {
                await browser.switchToWindow(mainWindow[0]);
                return true;
            }
        }, { timeout: 15000, timeoutMsg: "Main Window for test execution is not found."} );
    }
 },
 ```
    
Anyway, I have raised an issue on EdgeDriver repository but not sure if that will get dev's attention.
