### ISSUE TITLE
Unexpected token after setting up wdio.conf.js

### ISSUE THREAD

**Issue by TheQuintessentialQ** [webdriverio/webdriverio#1183]
Hi guys,

I get the following error after running the wdio config command and setting up the wdio.conf.js file. I made sure to install my wdio-mocha-framework globally (as I had to install WebDriverIO globally to ensure the TestRunner came packaged with it). 

I've checked out the library but I can't find anything wrong. Is there something I'm missing?

`ERROR: Unexpected token (
firefox
Syntax    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/matthewquerzoli/.nvm/v0.10.39/lib/node_modules/wdio-mocha-framework/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/matthewquerzoli/.nvm/v0.10.39/lib/node_modules/wdio-mocha-framework/node_modules/mocha/lib/mocha.js:216:14)`

Thanks!

**Comment by christian-bromann** [comment]
Please update the webdriver-standalone server (get the latest [here](http://goo.gl/IHP6Qw))

**Comment by TheQuintessentialQ** [comment]
Thank you!
