### ISSUE TITLE
[🐛 Bug]: Potential ReRun Services and "--spec" parameter in "npx wdio run" is not working properly

### ISSUE THREAD

**Issue by carri747** [webdriverio/webdriverio#11864]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.22.0

### Node.js Version

18.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
        {
            browserName: 'chrome'
        }
    ],
```

### What happened?

Hi everyone and thanks in advance for the help.

I'm using rerun service to re-run testcases in our project, but I found something strange in the number of executions, I mean, the number of executions higher than expected. 

If I've several scenarios that are failing and after that I execute this scenario with the rerun script. I expect that the number of execution will be consistent
**Example**:

> 2 scenarios failing in different feature file: I've 2 errors in the report. That's right

> ReRun those scenarios and then I can see in the report 2 retries failing and other more and I think that's not right, I'll expect 1 retry and other more.

### What is your expected behavior?

Less number of executions

### How to reproduce the bug.

wdio.conf.ts
```
import type { Options } from '@wdio/types';
import AllureReporter from '@wdio/allure-reporter';
import * as fs from 'fs';
import RerunService from 'wdio-rerun-service';

export const config: Options.Testrunner = {
    runner: 'local',
    autoCompileOpts: {
        autoCompile: true,
        tsNodeOpts: {
            project: './tsconfig.json',
            transpileOnly: true
        }
    },
    specs: ['./features/**/*.feature'],
    exclude: [],
    maxInstances: 10,
    capabilities: [
        {
            browserName: 'chrome'
        }
    ],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://www.google.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: [
        [
            RerunService,
            {
                rerunDataDir: './reRun',
                rerunScriptPath: './reRun/rerun.bat',
                customParameters: './wdio.conf.ts'
            }
        ]
    ],
    framework: 'cucumber',
    reporters: ['spec', ['allure', { outputDir: 'out/allure-result', useCucumberStepReporter: true }]],
    cucumberOpts: {
        require: ['./features/step-definitions/steps.ts'],
        backtrace: false,
        requireModule: [],
        dryRun: false,
        failFast: false,
        snippets: true,
        source: true,
        strict: false,
        timeout: 60000,
        ignoreUndefinedDefinitions: false
    },
    afterScenario: function (world, result, context) {   
    },

    after: function (result, capabilities, specs) {
     
    }
};
```

stepDefinition.ts

```
import { Given, When, Then } from '@wdio/cucumber-framework';
import * as chai from 'chai';

Given(/^I am on the (\w+) page$/, async (page) => {
    await chai.expect(false).to.be.true;
});

When(/^I login with (\w+) and (.+)$/, async (username, password) => {});

Then(/^I should see a flash message saying (.*)$/, async (message) => {});

```

featureFile1.feature
```
@Web
Feature: The Internet Guinea Pig Website

  @test
  Scenario Outline: As a user, I can log into the secure area

    Given I am on the login page
    When I login with <username> and <password>
    Then I should see a flash message saying <message>

    Examples:
      | username | password             | message                        |
      | tomsmith | SuperSecretPassword! | You logged into a secure area! |
```

featureFile2.feature
```
@Web
@prueba
Feature: The Internet Guinea Pig Website

  @test
  Scenario Outline: As a user I want to fail

    Given I am on the login page
```
package.json
```
{
    "name": "my-new-project",
    "type": "module",
    "devDependencies": {
        "@wdio/allure-reporter": "^8.21.0",
        "@wdio/cli": "^8.22.1",
        "@wdio/cucumber-framework": "^8.22.0",
        "@wdio/local-runner": "^8.22.1",
        "@wdio/spec-reporter": "^8.21.0",
        "ts-node": "^10.9.1",
        "typescript": "^5.2.2"
    },
    "scripts": {
        "wdio": "wdio run ./wdio.conf.ts",
        "report:generate": "npm run restoreHistory && npx allure generate --clean ./out/allure-result/ -o ./out/allure-report && npm run saveHistory",
        "report:open": "npx allure open out/allure-report",
        "saveNewHistory": "copyfiles -f out/allure-report/history/*.json c:\\allureHistory",
        "restoreHistory": "copyfiles -f c:\\allureHistory\\*.json out/allure-result/history",
        "report": "npm run restoreHistory && npm run report:generate",
        "rerun": "call ./reRun/rerun.bat"
    },
    "dependencies": {
        "@types/node": "^20.9.0",
        "allure-commandline": "^2.24.1",
        "allure-cucumberjs": "^2.9.2",
        "chai": "^4.3.10",
        "copyfiles": "^2.4.1",
        "minimist": "^1.2.8",
        "wdio-rerun-service": "^2.0.7"
    }
}
```

Run this commando 
`npm run wdio`

After the execution a new folder will be created into the project with the name "reRun" with 2 files (rerun.bat and xxx.json)

Generate allure report 
```
npm run report:generate
npm run report:open 
```

And check the testcases' results (2 fails) 

Run 
`npm run rerun`

Now it's possible to check in console that 2 workers are created and wdio execute in both worker both feature file. And this is the issue 
Why wdio are running both feature file in both workers? For me make not sense because in the spec value is specified with feature need to run

Generate again Allure report  and check retries. In the picture bellow you can see 3 execution and I expect only 2

![image](https://github.com/webdriverio/webdriverio/assets/22347831/a2106c6b-c6a7-4f4f-9e41-0e13c1fd882f)

If I add "retry" option in cucumber the number of execution it's even worst

reRun.bat generate automatically by wdio

`set DISABLE_RERUN=true && npx wdio run ./wdio.conf.ts --spec=features/login.feature:14 --spec=features/loginFail2.feature:6`

### Relevant log output

```typescript
-----------------------------------------------------------------
[chrome 120.0.6099.71 windows #0-0] Running: chrome (v120.0.6099.71) on windows
[chrome 120.0.6099.71 windows #0-0] Session ID: f35d3e984d251bcca9c7cb5b3b9df8e6
[chrome 120.0.6099.71 windows #0-0]
[chrome 120.0.6099.71 windows #0-0] » \features\login.feature
[chrome 120.0.6099.71 windows #0-0] The Internet Guinea Pig Website
[chrome 120.0.6099.71 windows #0-0] As a user, I can log into the secure area
[chrome 120.0.6099.71 windows #0-0]    ✖ Given I am on the login page
[chrome 120.0.6099.71 windows #0-0]    - When I login with tomsmith and SuperSecretPassword!
[chrome 120.0.6099.71 windows #0-0]    - Then I should see a flash message saying You logged into a secure area!
[chrome 120.0.6099.71 windows #0-0]
[chrome 120.0.6099.71 windows #0-0] » \features\loginFail2.feature
[chrome 120.0.6099.71 windows #0-0] The Internet Guinea Pig Website
[chrome 120.0.6099.71 windows #0-0] As a user I want to fail
[chrome 120.0.6099.71 windows #0-0]    ✖ Given I am on the login page
[chrome 120.0.6099.71 windows #0-0]
[chrome 120.0.6099.71 windows #0-0] 2 failing (241ms)
[chrome 120.0.6099.71 windows #0-0] 2 skipped
[chrome 120.0.6099.71 windows #0-0]
[chrome 120.0.6099.71 windows #0-0] 1) As a user, I can log into the secure area Given I am on the login page
[chrome 120.0.6099.71 windows #0-0] AssertionError
[chrome 120.0.6099.71 windows #0-0] AssertionError
[chrome 120.0.6099.71 windows #0-0]     + expected - actual
[chrome 120.0.6099.71 windows #0-0]
[chrome 120.0.6099.71 windows #0-0]     -false
[chrome 120.0.6099.71 windows #0-0]     +true
[chrome 120.0.6099.71 windows #0-0]
[chrome 120.0.6099.71 windows #0-0]     at World.<anonymous> (file:///C:/Dev/git/testAllure/features/step-definitions/steps.ts:5:35)
[chrome 120.0.6099.71 windows #0-0]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\user_code_runner.ts:37:21)
[chrome 120.0.6099.71 windows #0-0]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:41)
[chrome 120.0.6099.71 windows #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[chrome 120.0.6099.71 windows #0-0]     at async TestCaseRunner.invokeStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:137:12)        
[chrome 120.0.6099.71 windows #0-0]     at async TestCaseRunner.runStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:334:20)
[chrome 120.0.6099.71 windows #0-0]     at async C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:240:34
[chrome 120.0.6099.71 windows #0-0]     at async TestCaseRunner.aroundTestStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:170:28)    
[chrome 120.0.6099.71 windows #0-0]     at async TestCaseRunner.runAttempt (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:218:7)
[chrome 120.0.6099.71 windows #0-0]     at async TestCaseRunner.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:188:29)
[chrome 120.0.6099.71 windows #0-0]     at async Runtime.runTestCase (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:89:20)
[chrome 120.0.6099.71 windows #0-0]     at async Runtime.start (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:116:7)
[chrome 120.0.6099.71 windows #0-0]     at async runCucumber (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\api\run_cucumber.ts:125:19)
[chrome 120.0.6099.71 windows #0-0]     at async CucumberAdapter.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/cucumber-framework/build/index.js:186:33)
[chrome 120.0.6099.71 windows #0-0]     at async Runner.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/runner/build/index.js:148:24)
[chrome 120.0.6099.71 windows #0-0]
[chrome 120.0.6099.71 windows #0-0] 2) As a user I want to fail Given I am on the login page
[chrome 120.0.6099.71 windows #0-0] AssertionError
[chrome 120.0.6099.71 windows #0-0] AssertionError
[chrome 120.0.6099.71 windows #0-0]     + expected - actual
[chrome 120.0.6099.71 windows #0-0]
[chrome 120.0.6099.71 windows #0-0]     -false
[chrome 120.0.6099.71 windows #0-0]     +true
[chrome 120.0.6099.71 windows #0-0]
[chrome 120.0.6099.71 windows #0-0]     at World.<anonymous> (file:///C:/Dev/git/testAllure/features/step-definitions/steps.ts:5:35)
[chrome 120.0.6099.71 windows #0-0]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\user_code_runner.ts:37:21)
[chrome 120.0.6099.71 windows #0-0]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:41)
[chrome 120.0.6099.71 windows #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[chrome 120.0.6099.71 windows #0-0]     at async TestCaseRunner.invokeStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:137:12)        
[chrome 120.0.6099.71 windows #0-0]     at async TestCaseRunner.runStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:334:20)
[chrome 120.0.6099.71 windows #0-0]     at async C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:240:34
[chrome 120.0.6099.71 windows #0-0]     at async TestCaseRunner.aroundTestStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:170:28)    
[chrome 120.0.6099.71 windows #0-0]     at async TestCaseRunner.runAttempt (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:218:7)
[chrome 120.0.6099.71 windows #0-0]     at async TestCaseRunner.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:188:29)
[chrome 120.0.6099.71 windows #0-0]     at async Runtime.runTestCase (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:89:20)
[chrome 120.0.6099.71 windows #0-0]     at async Runtime.start (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:116:7)
[chrome 120.0.6099.71 windows #0-0]     at async runCucumber (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\api\run_cucumber.ts:125:19)
[chrome 120.0.6099.71 windows #0-0]     at async CucumberAdapter.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/cucumber-framework/build/index.js:186:33)
[chrome 120.0.6099.71 windows #0-0]     at async Runner.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/runner/build/index.js:148:24)
------------------------------------------------------------------
[chrome 120.0.6099.71 windows #0-1] Running: chrome (v120.0.6099.71) on windows
[chrome 120.0.6099.71 windows #0-1] Session ID: 3d30a140a2dd7c137fe29a8cd6be92a2
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1] » \features\login.feature
[chrome 120.0.6099.71 windows #0-1] The Internet Guinea Pig Website
[chrome 120.0.6099.71 windows #0-1] As a user, I can log into the secure area
[chrome 120.0.6099.71 windows #0-1]    ✖ Given I am on the login page
[chrome 120.0.6099.71 windows #0-1]    - When I login with tomsmith and SuperSecretPassword!
[chrome 120.0.6099.71 windows #0-1]    - Then I should see a flash message saying You logged into a secure area!
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1] » \features\loginFail2.feature
[chrome 120.0.6099.71 windows #0-1] The Internet Guinea Pig Website
[chrome 120.0.6099.71 windows #0-1] As a user I want to fail
[chrome 120.0.6099.71 windows #0-1]    ✖ Given I am on the login page
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1] 2 failing (300ms)
[chrome 120.0.6099.71 windows #0-1] 2 skipped
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1] 1) As a user, I can log into the secure area Given I am on the login page
[chrome 120.0.6099.71 windows #0-1] AssertionError
[chrome 120.0.6099.71 windows #0-1] AssertionError
[chrome 120.0.6099.71 windows #0-1]     + expected - actual
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1]     -false
[chrome 120.0.6099.71 windows #0-1]     +true
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1]     at World.<anonymous> (file:///C:/Dev/git/testAllure/features/step-definitions/steps.ts:5:35)
[chrome 120.0.6099.71 windows #0-1]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\user_code_runner.ts:37:21)
[chrome 120.0.6099.71 windows #0-1]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:41)
[chrome 120.0.6099.71 windows #0-1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.invokeStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:137:12)        
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.runStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:334:20)
[chrome 120.0.6099.71 windows #0-1]     at async C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:240:34
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.aroundTestStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:170:28)    
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.runAttempt (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:218:7)
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:188:29)
[chrome 120.0.6099.71 windows #0-1]     at async Runtime.runTestCase (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:89:20)
[chrome 120.0.6099.71 windows #0-1]     at async Runtime.start (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:116:7)
[chrome 120.0.6099.71 windows #0-1]     at async runCucumber (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\api\run_cucumber.ts:125:19)
[chrome 120.0.6099.71 windows #0-1]     at async CucumberAdapter.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/cucumber-framework/build/index.js:186:33)
[chrome 120.0.6099.71 windows #0-1]     at async Runner.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/runner/build/index.js:148:24)
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1] 2) As a user I want to fail Given I am on the login page
[chrome 120.0.6099.71 windows #0-1] AssertionError
[chrome 120.0.6099.71 windows #0-1] AssertionError
[chrome 120.0.6099.71 windows #0-1]     + expected - actual
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1]     -false
[chrome 120.0.6099.71 windows #0-1]     +true
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1]     at World.<anonymous> (file:///C:/Dev/git/testAllure/features/step-definitions/steps.ts:5:35)
[chrome 120.0.6099.71 windows #0-1]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\user_code_runner.ts:37:21)
[chrome 120.0.6099.71 windows #0-1]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:41)
[chrome 120.0.6099.71 windows #0-1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.invokeStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:137:12)        
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.runStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:334:20)
[chrome 120.0.6099.71 windows #0-1]     at async C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:240:34
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.aroundTestStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:170:28)    
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.runAttempt (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:218:7)
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:188:29)
[chrome 120.0.6099.71 windows #0-1]     at async Runtime.runTestCase (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:89:20)
[chrome 120.0.6099.71 windows #0-1]     at async Runtime.start (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:116:7)
[chrome 120.0.6099.71 windows #0-1]     at async runCucumber (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\api\run_cucumber.ts:125:19)
[chrome 120.0.6099.71 windows #0-1]     at async CucumberAdapter.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/cucumber-framework/build/index.js:186:33)
[chrome 120.0.6099.71 windows #0-1]     at async Runner.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/runner/build/index.js:148:24)


Spec Files:      0 passed, 2 failed, 2 total (100% completed) in 00:00:05
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@carri747 thanks for reporting the issue. Please raise this issue in the [rerun service](https://github.com/webdriverio-community/wdio-rerun-service) directly as it has to get fixed there. Thanks a lot!

**Comment by carri747** [comment]
Hi @christian-bromann 

I think that the issue is not in the re-run service is in the runner because if you run this command

`npx wdio run ./wdio.conf.ts --spec=features/login.feature:14 --spec=features/loginFail2.feature:6`

It is the typical command to run something in wdio, you can reproduce the issue, maybe the explanation or the title is not clear but the result yes, and the reRun service only build the command to re-run again and nothing more. Command **npx wdio ...**  is not in the reRun service.

Please take a look again and if you consider that the issue is in reRun service I don't have any problem to create the issue there. But I think that the issue is in the runner, the reRun service was the cause to find this issue
Thanks

**Comment by christian-bromann** [comment]
Ah gotcha, thanks for explaining. I am not sure if I get the time to look into this but all contributions are much appreciated.

**Comment by tamil777selvan** [comment]
@carri747 I attempted to reproduce this error and identified that the issue lies in how we pass arguments to WDIO. As discussed [here](https://github.com/webdriverio/webdriverio/issues/11864#issuecomment-1852554334), it appears to be a problem with the service, not with WDIO's runner. The service is generating an incorrect run command. The correct run command should be `npx wdio run ./wdio.conf.ts -- --spec=features/login.feature:14 --spec=features/loginFail2.feature:6`. As a temporary solution, you can modify the value of `customParameters` to something like `./wdio.conf.ts --`.

Below are the SS after updating the `customParameters` with temporary solution:

![Screenshot 2023-12-24 at 9 39 56 AM](https://github.com/webdriverio/webdriverio/assets/49207189/1f110b64-d3fe-4882-a5ae-2e52262d7a47)

![Screenshot 2023-12-24 at 9 39 10 AM](https://github.com/webdriverio/webdriverio/assets/49207189/157054da-64ab-4881-86a7-8ecc97efa397)

**Comment by christian-bromann** [comment]
Thanks for the investigation @tamil777selvan , I suggest to raise the issue in the [wdio-rerun-service](https://github.com/webdriverio-community/wdio-rerun-service/issues) then.
