### ISSUE TITLE
[🐛 Bug]: Electron app as binary issue : ERROR @wdio/runner: Error: Failed to create session.

### ISSUE THREAD

**Issue by ShanmukhaGajula** [webdriverio/webdriverio#11870]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

V8

### Node.js Version

v18.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      maxInstances: 2,
      browserName: "chrome",
      "goog:chromeOptions": {
        binary: `${process.cwd()}/node_modules/electron/dist/electron.exe`,
        args: [`app=${process.cwd()}/my-electron/`]
      },
      "wdio:chromedriverOptions":{
        port: 9515,
        path: "/wd/hub/",
        binary: `${process.cwd()}/node_modules/electron-chromedriver/bin/chromedriver.exe`
      },
      acceptInsecureCerts: true
    }
```

### What happened?

I am migrating from WDIO v7 to v8, and am using unpackaged electron app as a browser. Which used to work fine in v7. But now it is not even launching the electron app.

### What is your expected behavior?

Expected behaviour is to launch the electron app in the electron container

### How to reproduce the bug.

unable to launch the electron when binary is added to capability 
my capability
 ```
 {
      maxInstances: 2,
      browserName: "chrome",
      "goog:chromeOptions": {
        binary: `${process.cwd()}/node_modules/electron/dist/electron.exe`,
        args: [`app=${process.cwd()}/my-electron/`]
      },
      "wdio:chromedriverOptions":{
        port: 9515,
        path: "/wd/hub/",
        binary: `${process.cwd()}/node_modules/electron-chromedriver/bin/chromedriver.exe`
      },
      acceptInsecureCerts: true
    }
```

my package.json
 ```
"dependencies": {
    "@types/node": "^20.8.2",
    "electron-chromedriver": "^12.0.0",
    "wdio-video-reporter": "^4.0.5"
  },
  "devDependencies": {
    "@types/chai": "^4.3.9",
    "@types/global-agent": "^2.1.1",
    "@types/node-fetch": "^2.6.3",
    "@types/supertest": "^2.0.11",
    "@wdio/allure-reporter": "^8.24.12",
    "@wdio/cli": "^8.26.1",
    "@wdio/cucumber-framework": "^8.24.13",
    "@wdio/local-runner": "^8.26.1",
    "@wdio/spec-reporter": "^8.24.12",
    "allure-commandline": "^2.21.0",
    "chai": "^4.3.10",
    "chromedriver": "^104",
    "crypto-js": "^4.1.1",
    "dotenv": "^10.0.0",
    "electron": "^12.0.4",
    "global-agent": "^3.0.0",
    "perfecto-reporting": "^2.5.4",
    "supertest": "^6.3.3",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-rerun-service": "^1.6.2",
    "winston": "^3.11.0"
  }
```

### Relevant log output

```typescript
2023-12-14T16:48:51.143Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-12-14T16:48:51.144Z INFO @wdio/local-runner: Start worker 0-0 with arg: config/wdio.dit.conf.ts,--cucumberOpts.tagExpression='@Dashboard_SVP'
[0-0] 2023-12-14T16:48:53.546Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-12-14T16:48:54.754Z WARN @wdio/cucumber-framework: 'tagExpression' is deprecated. Use 'tags' instead.
[0-0] RUNNING in chrome - file:///C:/myapp-automation/test/features/dashboard/MAS/DashboardSVP.feature
[0-0] 2023-12-14T16:48:54.789Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-12-14T16:48:55.255Z INFO chromedriver: Starting ChromeDriver 89.0.4389.69 (21a11af22759d597523f704f8aa8a5bb6f5ea869-refs/heads/master@{#846707}) on port 9515
[0-0] 2023-12-14T16:48:55.256Z INFO chromedriver: Remote connections are allowed by an allowlist (0.0.0.0).
[0-0] 2023-12-14T16:48:55.256Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[0-0] 2023-12-14T16:48:55.269Z INFO chromedriver: ChromeDriver was started successfully.
[0-0] 2023-12-14T16:49:05.350Z INFO @wdio/utils: Started Chromedriver vundefined with params --port=9515 --path=/wd/hub/ --binary=C:\myapp-automation/node_modules/electron-chromedriver/bin/chromedriver.exe --allowed-origins=* --allowed-ips=0.0.0.0 in 10184ms on port 40103
[0-0] 2023-12-14T16:49:05.368Z INFO webdriver: [POST] http://0.0.0.0:40103/session
[0-0] 2023-12-14T16:49:05.369Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'goog:chromeOptions': [Object],
[0-0]       'wdio:chromedriverOptions': [Object],
[0-0]       acceptInsecureCerts: true,
[0-0]       timeouts: [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': {
[0-0]       binary: 'C:\\myapp-automation/node_modules/electron/dist/electron.exe',
[0-0]       args: [Array]
[0-0]     },
[0-0]     'wdio:chromedriverOptions': {
[0-0]       port: 9515,
[0-0]       path: '/wd/hub/',
[0-0]       binary: 'C:\\myapp-automation/node_modules/electron-chromedriver/bin/chromedriver.exe',
[0-0]       allowedOrigins: [Array],
[0-0]       allowedIps: [Array]
[0-0]     },
[0-0]     acceptInsecureCerts: true,
[0-0]     timeouts: { implicit: 60000, pageLoad: 60000, script: 600000 }
[0-0]   }
[0-0] }
[0-0] 2023-12-14T16:49:05.705Z ERROR webdriver: RequestError: connect ECONNREFUSED 0.0.0.0:40103
[0-0]     at ClientRequest.<anonymous> (file:///C:/myapp-automation/node_modules/got/dist/source/core/index.js:790:107)
[0-0]     at Object.onceWrapper (node:events:628:26)
[0-0]     at ClientRequest.emit (node:events:525:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:502:9)
[0-0]     at Socket.emit (node:events:513:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
[0-0] 2023-12-14T16:49:05.706Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://0.0.0.0:40103/", make sure browser driver is running on that address.
[0-0] It seems like the service failed to start or is rejecting any connections.
[0-0]     at startWebDriverSession (file:///C:/myapp-automation/node_modules/webdriver/build/utils.js:69:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async Function.newSession (file:///C:/myapp-automation/node_modules/webdriver/build/index.js:19:45)
[0-0]     at async remote (file:///C:/myapp-automation/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (file:///C:/myapp-automation/node_modules/@wdio/runner/build/index.js:224:29)
[0-0]     at async Runner._initSession (file:///C:/myapp-automation/node_modules/@wdio/runner/build/index.js:190:25)
[0-0]     at async Runner.run (file:///C:/myapp-automation/node_modules/@wdio/runner/build/index.js:79:19)
[0-0] FAILED in chrome - file:///C:/myapp-automation/test/features/dashboard/MAS/DashboardSVP.feature
2023-12-14T16:49:05.847Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-12-14T16:49:05.849Z INFO @wdio/cli:launcher: Run onComplete hook
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@ShanmukhaGajula thanks for reporting. It seems like you define the Chromedriver port to be on `9515`:

> Started Chromedriver vundefined with params --port=9515

but the capabilities are modified to use a custom port, which happens [here](https://github.com/webdriverio/webdriverio/blob/658c217ecf224a5ba66394e0109747cc117f1b81/packages/wdio-utils/src/node/startWebDriver.ts#L179). This should be an easy fix.

**Comment by ShanmukhaGajula** [comment]
Thanks for the update @christian-bromann . Happy to help you by testing the fix, if you need it.

**Comment by ShanmukhaGajula** [comment]
Hi @christian-bromann , when i remove the custom port I am getting this error now.
this is my capability -
```
{
     maxInstances: 2,
     browserName: "chrome",
     "goog:chromeOptions": {
       binary: `${process.cwd()}/node_modules/electron/dist/electron.exe`,
       args: [`app=${process.cwd()}/my-electron/`]
     },
     "wdio:chromedriverOptions":{
       port: 9515,
       path: "/wd/hub/",
       binary: `${process.cwd()}/node_modules/electron-chromedriver/bin/chromedriver.exe`
     },
     acceptInsecureCerts: true
   }
```
![image](https://github.com/webdriverio/webdriverio/assets/21192877/0e627410-0e7a-4f9f-b728-972dbdac206c)

**Comment by ShanmukhaGajula** [comment]
@christian-bromann , though I removed the custom port, still the electron app is not launching. 
capabilities

```
{
      browserName: "chrome",
      "wdio:chromedriverOptions":{
        //port: 9515,
        path: "/wd/hub/",
        binary:
          `${process.cwd()}/node_modules/electron-chromedriver/bin/chromedriver.exe`
      },
      "goog:chromeOptions": {
        binary: `${process.cwd()}/node_modules/electron/dist/electron.exe`,
          args: [`app=./my-electron-app`]
   
      },
      acceptInsecureCerts: true
    }
```
console 
```
[0-0] RUNNING in chrome - file:///C:/wdio-v8-sb/test/features/dashboard/MAS/DashboardSVP.feature
[0-0] 2023-12-15T11:45:02.560Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-12-15T11:45:03.082Z INFO chromedriver: Starting ChromeDriver 89.0.4389.69 (21a11af22759d597523f704f8aa8a5bb6f5ea869-refs/heads/master@{#846707}) on port 57533
[0-0] 2023-12-15T11:45:03.083Z INFO chromedriver: Remote connections are allowed by an allowlist (0.0.0.0).
[0-0] 2023-12-15T11:45:03.083Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[0-0] 2023-12-15T11:45:03.097Z INFO chromedriver: ChromeDriver was started successfully.
[0-0] 2023-12-15T11:45:04.048Z INFO @wdio/utils: Started Chromedriver vundefined with params --port=57533 --path=/wd/hub/ --binary=C:\wdio-v8-sb/node_modules/electron-chromedriver/bin/chromedriver.exe --allowed-origins=* --allowed-ips=0.0.0.0 in 1067ms on port 57533
[0-0] 2023-12-15T11:45:04.061Z INFO webdriver: [POST] http://0.0.0.0:57533/session
[0-0] 2023-12-15T11:45:04.061Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'wdio:chromedriverOptions': [Object],
[0-0]       'goog:chromeOptions': [Object],
[0-0]       acceptInsecureCerts: true,
[0-0]       timeouts: [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'wdio:chromedriverOptions': {
[0-0]       path: '/wd/hub/',
[0-0]       binary: 'C:\\wdio-v8-sb/node_modules/electron-chromedriver/bin/chromedriver.exe',
[0-0]       allowedOrigins: [Array],
[0-0]       allowedIps: [Array]
[0-0]     },
[0-0]     'goog:chromeOptions': {
[0-0]       binary: 'C:\\wdio-v8-sb/node_modules/electron/dist/electron.exe',
[0-0]       args: [Array]
[0-0]     },
[0-0]     acceptInsecureCerts: true,
[0-0]     timeouts: { implicit: 60000, pageLoad: 60000, script: 600000 }
[0-0]   }
[0-0] }


DevTools listening on ws://127.0.0.1:57538/devtools/browser/4b0c74ec-c3e8-4ce2-83c6-64cbef1f90fe
```

**Comment by christian-bromann** [comment]
@ShanmukhaGajula have you tried using the [Electron Service](https://webdriver.io/docs/wdio-electron-service)?

**Comment by ShanmukhaGajula** [comment]
Nope as it is not packaged, I am using it in chrome capability

**Comment by christian-bromann** [comment]
> Nope as it is not packaged, I am using it in chrome capability

What do you mean by "it is not packages"?

**Comment by ShanmukhaGajula** [comment]
It is a binary file (source code) and not a exe file

**Comment by christian-bromann** [comment]
If you have a binary of your Electron application you should set the path in your capabilities as follows:

```ts
capabilities: {
    'goog:chromeOptions': {
        binary: '/path/to/compiled/electron/application.exe'
    }
}
```
so don't point to the electron binary, point to your application bundle.

**Comment by ShanmukhaGajula** [comment]
In V7, that used to work. I'll tried the option that you have mentioned and
it is working fine.

**Comment by christian-bromann** [comment]
Great, closing the issue then.
