### ISSUE TITLE
[🐛 Bug]: Retry parameter and exit code console when wdio finish all test

### ISSUE THREAD

**Issue by carri747** [webdriverio/webdriverio#11908]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.22.0

### Node.js Version

18.15.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
        {
            browserName: 'chrome'
        }
    ],
```

### What happened?

Hi and thanks in advance 

I've a project with cucumber and the parameter "retry=1" and I detected that when this parameter is setup with a number greater than 0, sometime when wdio finish to run all the test cases the exit code that return in console is wrong. I explain myself better:

Situation:
3 testcases: 2 of them have a pass results in the first retry other fail and obviously with "retry=1" wdio retry again in the second execution the last testcase pass
Now the exit code that I've in console is 1 and make not sense because all tests cases are success 

Try to clarify more the situation:
Setup cumcumber: retry = 1
4 Test cases

- Test case 1 success in the first attend
- Test case 2 success in the first attend
- Test case 3 fail in the fist attend, success in the second attend (retry configuration)
- Test case 4 success in the first attend 

With this situation I've a exit code in console 1 

### What is your expected behavior?

Exit code 0, in the case that all testcases are success, regardless of whether the retry policy is applied or not

### How to reproduce the bug.

[git](https://github.com/carri747/carri747/tree/wdio11867)

### Relevant log output

```typescript
[chrome 120.0.6099.71 windows #0-1]     -false
[chrome 120.0.6099.71 windows #0-1]     +true
[chrome 120.0.6099.71 windows #0-1]
[chrome 120.0.6099.71 windows #0-1]     at World.<anonymous> (file:///C:/Dev/git/testAllure/features/step-definitions/steps.ts:5:35)
[chrome 120.0.6099.71 windows #0-1]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\user_code_runner.ts:37:21)
[chrome 120.0.6099.71 windows #0-1]     at Object.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:50:41)
[chrome 120.0.6099.71 windows #0-1]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.invokeStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:137:12)        
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.runStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:334:20)
[chrome 120.0.6099.71 windows #0-1]     at async C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:240:34
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.aroundTestStep (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:170:28)    
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.runAttempt (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:218:7)
[chrome 120.0.6099.71 windows #0-1]     at async TestCaseRunner.run (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:188:29)
[chrome 120.0.6099.71 windows #0-1]     at async Runtime.runTestCase (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:89:20)
[chrome 120.0.6099.71 windows #0-1]     at async Runtime.start (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\runtime\index.ts:116:7)
[chrome 120.0.6099.71 windows #0-1]     at async runCucumber (C:\Dev\git\testAllure\node_modules\@cucumber\cucumber\src\api\run_cucumber.ts:125:19)
[chrome 120.0.6099.71 windows #0-1]     at async CucumberAdapter.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/cucumber-framework/build/index.js:186:33)
[chrome 120.0.6099.71 windows #0-1]     at async Runner.run (file:///C:/Dev/git/testAllure/node_modules/@wdio/runner/build/index.js:148:24)


Spec Files:      0 passed, 2 failed, 2 total (100% completed) in 00:00:08

2023-12-14T08:17:58.433Z INFO @wdio/local-runner: Shutting down spawned worker
2023-12-14T08:17:58.696Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-12-14T08:17:58.697Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
I cannot reproduce this, if setup correctly it works fine.

Both passing, failing (multiple retries) and first failing then passing, all work correctly on my end.

Changes I made to test:
```
// passing
Feature: The Internet Guinea Pig Website

  @test
  Scenario Outline: As a user, I can log into the secure area

    Given I pass 1
```
```
// failing then passing
Feature: The Internet Guinea Pig Website

  @test
  Scenario Outline: As a user, I can log into the secure area

    Given I pass 0
```

Code to make the first iteration fail and second iteration pass
```js
import { Given } from '@wdio/cucumber-framework';
import { equal } from 'node:assert';

Given('I pass {int}', (num: number) => {
    if (num !== 1) {
        global.foo = 1;
    }
    equal(global.foo || num, 1);
});
```

Also tried with `retry` set to `2`.

**Comment by erwinheitzman** [comment]
Relevant output when making a test fail completely with two retries:
```
 "spec" Reporter:
------------------------------------------------------------------
[chrome 120.0.6099.109 mac #0-0] Running: chrome (v120.0.6099.109) on mac
[chrome 120.0.6099.109 mac #0-0] Session ID: 398c8fd7c246e74b7df8224d1e6af26b
[chrome 120.0.6099.109 mac #0-0]
[chrome 120.0.6099.109 mac #0-0] » /features/worker1/featuer1.feature
[chrome 120.0.6099.109 mac #0-0] The Internet Guinea Pig Website
[chrome 120.0.6099.109 mac #0-0] As a user, I can log into the secure area
[chrome 120.0.6099.109 mac #0-0]    ✓ Given I pass 1
[chrome 120.0.6099.109 mac #0-0]
[chrome 120.0.6099.109 mac #0-0] 1 passing (106ms)
------------------------------------------------------------------
[chrome 120.0.6099.109 mac #0-1] Running: chrome (v120.0.6099.109) on mac
[chrome 120.0.6099.109 mac #0-1] Session ID: abedaa7e80a89fecb194816c1f69c7a4
[chrome 120.0.6099.109 mac #0-1]
[chrome 120.0.6099.109 mac #0-1] » /features/worker2/featuer2.feature
[chrome 120.0.6099.109 mac #0-1] The Internet Guinea Pig Website
[chrome 120.0.6099.109 mac #0-1] As a user, I can log into the secure area
[chrome 120.0.6099.109 mac #0-1]    ✓ Given I pass 1
[chrome 120.0.6099.109 mac #0-1]
[chrome 120.0.6099.109 mac #0-1] 1 passing (98ms)
------------------------------------------------------------------
[chrome 120.0.6099.109 mac #0-2] Running: chrome (v120.0.6099.109) on mac
[chrome 120.0.6099.109 mac #0-2] Session ID: c5559cecdf3b5a4cb16f5e181da980b9
[chrome 120.0.6099.109 mac #0-2]
[chrome 120.0.6099.109 mac #0-2] » /features/worker2/feature3.feature
[chrome 120.0.6099.109 mac #0-2] The Internet Guinea Pig Website
[chrome 120.0.6099.109 mac #0-2]         As a user I want to fail
[chrome 120.0.6099.109 mac #0-2]            ✖ Given I pass 0
[chrome 120.0.6099.109 mac #0-2]
[chrome 120.0.6099.109 mac #0-2] 3 failing (123ms)
[chrome 120.0.6099.109 mac #0-2]
[chrome 120.0.6099.109 mac #0-2] 1) As a user I want to fail Given I pass 0
[chrome 120.0.6099.109 mac #0-2] AssertionError [ERR_ASSERTION]: 0 == 1
[chrome 120.0.6099.109 mac #0-2] AssertionError [ERR_ASSERTION]: 0 == 1
[chrome 120.0.6099.109 mac #0-2]     + expected - actual
[chrome 120.0.6099.109 mac #0-2]
[chrome 120.0.6099.109 mac #0-2]     -0
[chrome 120.0.6099.109 mac #0-2]     +1
[chrome 120.0.6099.109 mac #0-2]
[chrome 120.0.6099.109 mac #0-2]     at World.<anonymous> (file:///Users/erwin/Development/Personal/carri747/features/step-definitions/steps.ts:7:5)
[chrome 120.0.6099.109 mac #0-2]     at processTicksAndRejections (node:internal/process/task_queues:95:5)


Spec Files:      2 passed, 1 failed, 3 total (100% completed) in 00:00:07  
```

**Comment by christian-bromann** [comment]
Closing due to inactivity.
