### ISSUE TITLE
Unable to run specs by using drivers

### ISSUE THREAD

**Issue by Iwonk** [webdriverio/webdriverio#12026]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
"devDependencies": {
    "@wdio/allure-reporter": "^8.27.2",
    "@wdio/cli": "^8.27.2",
    "@wdio/junit-reporter": "^8.27.2",
    "@wdio/local-runner": "^8.27.2",
    "@wdio/mocha-framework": "^8.27.2",
    "@wdio/spec-reporter": "^8.27.2",
    "allure-commandline": "^2.25.0",
    "chromedriver": "^120.0.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.3.3",
    "wdio-chromedriver-service": "^8.1.1",
    "wdio-edgedriver-service": "^3.0.3",
    "wdio-video-reporter": "^5.1.0"
  }
```

### What happened?

Unable to run specs by using drivers, getting the following Error message even if I followed documentation and even all plugins are installed. I already tried to update using `npx npm-check-updates -u` and re-install the dependencies but still error.

### What is your expected behavior?

Run specs success and execute/running the script

### How to reproduce the bug.

Run specs by given configs

### Relevant log output

```typescript
Execution of 1 workers started at 2024-01-16T04:26:12.355Z

2024-01-16T04:26:12.370Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-01-16T04:26:12.371Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2024-01-16T04:26:12.372Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
2024-01-16T04:26:12.424Z INFO webdriver: Downloading Chromedriver v120.0.6099.216
2024-01-16T04:26:12.861Z WARN webdriver: Chromedriver v120.0.6099.216 don't exist, trying to find known good version...
2024-01-16T04:26:13.691Z INFO webdriver: Download of Chromedriver v120.0.6099.109 was successful
2024-01-16T04:26:13.695Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-01-16T04:26:13.697Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts,--suite,revisiquantity
[0-0] 2024-01-16T04:26:14.453Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2024-01-16T04:26:15.632Z ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't find plugin "video" reporter, neither as wdio scoped package "@wdio/video-reporter" nor as community package "wdio-video-reporter". Please make sure you have it installed!
[0-0]     at initializePlugin (file:///Users/ilhamnuswantoro/Documents/Project%20SRC/ayo-mitra/node_modules/@wdio/utils/build/initializePlugin.js:35:11)
[0-0]     at async BaseReporter._loadReporter (file:///Users/ilhamnuswantoro/Documents/Project%20SRC/ayo-mitra/node_modules/@wdio/runner/build/reporter.js:178:30)
[0-0]     at async Promise.all (index 2)
[0-0]     at async BaseReporter.initReporters (file:///Users/ilhamnuswantoro/Documents/Project%20SRC/ayo-mitra/node_modules/@wdio/runner/build/reporter.js:23:27)
[0-0]     at async Runner.run (file:///Users/ilhamnuswantoro/Documents/Project%20SRC/ayo-mitra/node_modules/@wdio/runner/build/index.js:70:9)
[0-0] FAILED
2024-01-16T04:26:15.663Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-01-16T04:26:15.663Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:03
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> Unable to run specs by using drivers

What do you mean by drivers?

**Comment by Iwonk** [comment]
> > Unable to run specs by using drivers
> 
> What do you mean by drivers?

yeah, I can't use npm run [specs] with webdriverio, tried to update dependencies but still give an error

**Comment by christian-bromann** [comment]
Unfortunately this is not a helpful description about what is going on, please provide a reproducible example, thanks!

**Comment by Iwonk** [comment]
you can check here: https://github.com/Iwonk/ayo_mitra_b2b.git
1. Need to run `npm install`
2. For sample an error please try to run `npm run revisiquantity`

**Comment by christian-bromann** [comment]
@Iwonk thanks for providing the example. I was able to run it without issues, the video report was created:

<img width="1136" alt="Screenshot 2024-01-16 at 12 50 58 AM" src="https://github.com/webdriverio/webdriverio/assets/731337/531e4f73-a469-4752-afc8-2dd9f5b3e57c">

**Comment by Iwonk** [comment]
![Screenshot 2024-01-16 at 16 04 43](https://github.com/webdriverio/webdriverio/assets/42859240/9cfaf06c-923d-4c65-a160-18e08e9cce6c)
I tried to run but error like this "Couldn't find plugin "video" reporter,..."
Are you made any changes or configuration? Or you just straight run the script?
I really need a solution because I already tried on Edgedriver and Chromedriver it's all same

**Comment by Iwonk** [comment]
Oh wait, apparently I provide the old version of my script, can you check again please, latest commit already updated

**Comment by christian-bromann** [comment]
Thanks @BorisOsipov , I found an issue in the `packgage.json` of the new video reporter version. This has been fixed and released. @Iwonk please update your `wdio-video-reporter` package version to latest.
