### ISSUE TITLE
command --watch not working as expected

### ISSUE THREAD

**Issue by troyyer** [webdriverio/webdriverio#12032]
### Discussed in https://github.com/webdriverio/webdriverio/discussions/12024

<div type='discussions-op-text'>

<sup>Originally posted by **troyyer** January 16, 2024</sup>
I am having an issue trying to use the '--watch' feature (https://webdriver.io/docs/watcher)
i saw this bug item https://github.com/webdriverio/webdriverio/issues/9612 but was unsure if it has been resolved as yet

Currently when i run a website test script using the Test Runner and with the watch command enabled, once the test has completed, the browser window will stay open (as expected), then when I try to update the test script file and after saving the file i get an error in the Terminal

```
2024-01-15T23:01:14.917Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js,--watch
[0-0] 2024-01-15T23:01:16.512Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2024-01-15T23:01:17.665Z ERROR @wdio/runner: Error: You are trying to attach to a protocol stub, this should never occur, please file an issue.
[0-0]     at ProtocolStub.attachToSession (file:///C:/code/sample/node_modules/webdriverio/build/protocol-stub.js:31:19)
[0-0]     at attach (file:///C:/code/sample/node_modules/webdriverio/build/index.js:70:27)        
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0] RUNNING in chrome - file:///C:/code/sample/test/specs/test.e2e.js
[0-0] 2024-01-15T23:01:17.985Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/dynamic_loading")
[0-0] 2024-01-15T23:01:17.986Z INFO webdriver: [POST] http://0.0.0.0:52056/session/f8d10edf46f9c1a82a570da029789b4a/url
[0-0] 2024-01-15T23:01:17.986Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/dynamic_loading' }
[0-0] FAILED in chrome - file:///C:/code/sample/test/specs/test.e2e.js
2024-01-15T23:01:18.164Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
```

the reproducable sample is a 2 step process actually.
for browser based testing my repo will do which i updated the package json to have an additional script
https://github.com/troyyer/wdiosampleforwaituntil
after installation
```
npm run watch
```
once the first test passed
edit the test script in '/test/specs/test.e2e.js' by making line 13 to read

`  it.only("tests dynamic loading", async () => {`
after saving, watch will rerun the file and the terminal will show the error and will not re-execute the test

![rerun with wdio watch flag webtest](https://github.com/webdriverio/webdriverio/assets/28956675/7fde3048-6936-4e34-81c1-92f88bb480f9)

I also ran it for component testing 
i ran the cli installer with component testing
```
 npm init wdio . 
```
with the configurations below
```
===============================
🤖 WDIO Configuration Wizard 🧙
===============================

? What type of testing would you like to do? Component or Unit Testing - in the browser
    > https://webdriver.io/docs/component-testing
? Which framework do you use for building components? Lit (https://lit.dev/)
? Which framework do you want to use? Mocha (https://mochajs.org/)
? Do you want to use a compiler? No!
? Do you want WebdriverIO to autogenerate some test files? Yes
? What should be the location of your spec files? C:\code\wdio-component\src\**\*.test.js
? Which reporter do you want to use? spec
? Do you want to add a plugin to your test setup?
? Do you want to add a service to your test setup?
```
dependencies picked up by the cli installation
```
    "@wdio/browser-runner": "^8.27.2",
    "@wdio/cli": "^8.27.2",
    "@wdio/mocha-framework": "^8.27.2",
    "@wdio/spec-reporter": "^8.27.2",
    "lit": "^3.1.1"
```

after install run wdio with watch on 
```
npm run wdio -- -- --watch
```

after the initial run has completed, go into file "{ProjectRoot}\src\Component.test.js"
edit line 20 to now read 
`        await expect(button).not.toHaveText('count is 2') `
 after saving the file i get an error in the Terminal
![rerun with wdio watch flag](https://github.com/webdriverio/webdriverio/assets/28956675/8779a7b4-6c0f-4b79-b63b-e0bd2eb422a8)

```</div>

**Comment by tech-dm-klymenko** [comment]
I will try to fix it

**Comment by christian-bromann** [comment]
Awesome, let me know if you have any questions.

**Comment by tech-dm-klymenko** [comment]
@christian-bromann 

As far as I can see, after running the tests, the Worker process stopped. And when it stopped, the process that handles the driver binary also stopped (because it is a child process for the Worker). This results in loss of connection with the driver binary and open browser when subsequent tests are run after they have been changed. Please correct me, if I am wrong.

Currently, one potential solution I'm considering only for the worker, which is in watch mode, is to initiate the driver binary within a separate child process under the main parent process. Then we need to establish communication between these processes to handle restarts and/or terminations effectively. I think, it would have fewer side effects than altering the logic within the workers themselves.

What do you think? If you have any more efficient solutions in mind, I would greatly appreciate hearing them.

**Comment by christian-bromann** [comment]
> And when it stopped, the process that handles the driver binary also stopped (because it is a child process for the Worker).

Can we work around this limitation?

> only for the worker, which is in watch mode

If we run the WDIO command with `--watch` aren't all workers run with this flag?

Alternatively we might want to think about having a driver manager in an extra process that we connect to through a special rpc interface. We could build commands to start a driver with certain parameters and have it manage all shut downs so we don't leave any lingering process around e.g. if someone kills the worker process through e.g. `process.exit(1)`. It would make sense to move this into a `@wdio/driver` package, since this would be Node.js specific and we could work with conditional imports to e.g. have all operations be a noop if we run WebdriverIO in the browser.

**Comment by christian-bromann** [comment]
Sorry for the delayed response.

> I like the concept of establishing a driver manager. This will be a more comprehensive and convenient solution in the long run.

I totally agree. A `@wdio/driver` package could be initiated by the `@wdio/cli` launcher, would run in a separate process, would expose a socket connection that CLI and worker can connect to and would allow to start driver based on certain capabilities. We could connect a certain driver with a `cid` so we would know rerunning the test which driver should be picked. We would move all the logic from `packages/wdio-utils/src/node` into that package and implement a minimal socket interface to communicate with the driver instance.

These are just some initial ideas, wonder what your thoughts are! Would you like to take a stab at this kind of effort?

**Comment by tech-dm-klymenko** [comment]
Yes, locally I have already started working on this task, approaching it in a similar manner to your description. I've tried to preserve the existing structure as much as possible. But if you say that we can extract the logic from `packages/wdio-utils/src/node` into a separate package, then I will do that. And I also agree that using sockets would be more convenient than an IPC channel.

So I'm ready to take on this task and try to implement it.

**Comment by Badisi** [comment]
Any updates on this ?
Facing the same issue, which unfortunately makes the watch mode completely useless..

**Comment by tech-dm-klymenko** [comment]
I continue to keep that task in mind, but I am currently working on the Windows platform. On this platform, the project periodically builds with errors. Once the project starts building consistently, I will continue working on the task.

**Comment by vlad9719** [comment]
@tech-dm-klymenko @christian-bromann is there any update on this?  We are working on a feature in our service which requires the watch mode to work. It would be interesting to know if there are any rough estimations on a timeline for that fix

Thanks in advance

**Comment by vlad9719** [comment]
Hi @tech-dm-klymenko!
Thank you for your reply and for sharing the possible timelines! We will be working forward to the fix

Meanwhile, I have one observation I wanted to share, just in case it could be of any help

Once received that failure, I went into the code from the error stack trace and debugged it. I've noticed a particular place in the `attach` [function](https://github.com/webdriverio/webdriverio/blob/ee692d116c062896f2a7b0d708b6a46b8ea9f514/packages/webdriverio/src/index.ts#L95)

So in this function, there is a call to the `getProtocolDriver`, which returns a driver for the protocol stub. Subsequently, the `Driver.attachToSession` function is called, which fails with the failure described in the beginning of this discussion

Whatsoever, if I change the code locally by assigning `SupportedAutomationProtocols.webdriver` as the automationProtocol parameter in the end of the params list (thus overwriting its value from the `attachOptions`), the failure does not appear:

```typescript
const params: Capabilities.WebdriverIOConfig & { requestedCapabilities: Capabilities.RequestedStandaloneCapabilities } = {
        ...attachOptions,
        ...detectBackend(attachOptions.options),
        capabilities: attachOptions.capabilities || {},
        requestedCapabilities: attachOptions.requestedCapabilities || {},
        automationProtocol: SupportedAutomationProtocols.webdriver
    }
```

If I do it like this, the `webdriverio` Protocol driver is returned by the `getProtocolDriver` function later on, which then makes the spec run in the watch mode without a failure

However, having read the conversation above, I understand that the fix is likely to be more complicated than this. Anyway, I hope this observation can be of any use for you when implementing the fix :)

**Comment by tech-dm-klymenko** [comment]
@vlad9719 
Thank you for the detailed explanation! It’s great that you noticed such an interesting point! Please correct me if I’m wrong, but I feel that the solution you suggested might be more of a clever workaround than a full fix. You’ve made excellent use of the current implementation’s specifics. However, if the system’s behavior changes significantly due to a not-so-obvious change in parameter order, it may be something to consider for future refactoring, to make it more transparent. This could help prevent challenges for those less familiar with the system in future development. 
But perhaps I’m overthinking it - so it would be great to hear @christian-bromann ’s opinion here as someone who knows and understands the system well.

**Comment by vlad9719** [comment]
Hi @tech-dm-klymenko 

Yes, that's what I meant, this is just an observation and a workaround, and I don't know much about the internals of the webdriverIO, hence I suppose a full fix would be probably based on what you and Christian discussed above

**Comment by christian-bromann** [comment]
> so it would be great to hear @christian-bromann ’s opinion here as someone who knows and understands the system well.

It has been a while since I touched this part of the code but I can try. The whole point of having a stub driver is to allow us to load the framework first and then initiate the session. This way we don't have a browser starting when all of your test files are being skipped. This is a performance optimization.

In the context of watching files this may not be as crucial since the watcher points to a file that you just changed and wants you to run it. Furthermore we have a browser already running so there is no reason why we shouldn't immediately attach to the session.

That said, I don't know a concrete recommendation here and welcome any improvements to the launcher setup.

**Comment by vlad9719** [comment]
Hi @tech-dm-klymenko @christian-bromann just wanted to ask if there are any updates regarding this issue?
