### ISSUE TITLE
[🐛 Bug]: ERROR @wdio/runner: TypeError: currentTest.endTest is not a function

### ISSUE THREAD

**Issue by b1zzu** [webdriverio/webdriverio#12049]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.28.6

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
 browserName: 'chrome',
}
```

### What happened?

When running the test suite at the end of some Scenarios (I don't get how to reproduce it) allure test reporters fails with this error:

```
[0-0] 2024-01-19T14:34:51.108Z ERROR @wdio/runner: TypeError: currentTest.endTest is not a function
[0-0]     at AllureReporter.onSuiteEnd (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/allure-reporter/build/reporter.js:288:29)
[0-0]     at AllureReporter.<anonymous> (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/allure-reporter/node_modules/@wdio/reporter/build/index.js:165:18)
[0-0]     at AllureReporter.emit (node:events:517:28)
[0-0]     at AllureReporter.emit (node:domain:489:12)
[0-0]     at file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/runner/build/reporter.js:47:56
[0-0]     at Array.forEach (<anonymous>)
[0-0]     at BaseReporter.emit (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/runner/build/reporter.js:47:25)
[0-0]     at CucumberFormatter.emit (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:96:23)
[0-0]     at CucumberFormatter.onTestCaseFinished (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:392:14)
[0-0]     at EventEmitter.<anonymous> (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:63:22)
[0-0]     at EventEmitter.emit (node:events:529:35)
[0-0]     at EventEmitter.emit (node:domain:489:12)
[0-0]     at TestCaseRunner.runAttempt (/home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:257:27)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async TestCaseRunner.run (/home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:188:29)
[0-0]     at async Runtime.runTestCase (/home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@cucumber/cucumber/src/runtime/index.ts:89:20)
[0-0]  Error:  currentTest.endTest is not a function
``` 
crashing the testrunner which will continue to the next Feature ignoring all following Scenarios in the Feature where it 

### How to reproduce the bug.

Unknown

### Relevant log output

```typescript
[0-0] 2024-01-19T14:34:51.107Z INFO webdriver: RESULT []
[0-0] 2024-01-19T14:34:51.108Z ERROR @wdio/runner: TypeError: currentTest.endTest is not a function
[0-0]     at AllureReporter.onSuiteEnd (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/allure-reporter/build/reporter.js:288:29)
[0-0]     at AllureReporter.<anonymous> (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/allure-reporter/node_modules/@wdio/reporter/build/index.js:165:18)
[0-0]     at AllureReporter.emit (node:events:517:28)
[0-0]     at AllureReporter.emit (node:domain:489:12)
[0-0]     at file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/runner/build/reporter.js:47:56
[0-0]     at Array.forEach (<anonymous>)
[0-0]     at BaseReporter.emit (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/runner/build/reporter.js:47:25)
[0-0]     at CucumberFormatter.emit (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:96:23)
[0-0]     at CucumberFormatter.onTestCaseFinished (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:392:14)
[0-0]     at EventEmitter.<anonymous> (file:///home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:63:22)
[0-0]     at EventEmitter.emit (node:events:529:35)
[0-0]     at EventEmitter.emit (node:domain:489:12)
[0-0]     at TestCaseRunner.runAttempt (/home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:257:27)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async TestCaseRunner.run (/home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:188:29)
[0-0]     at async Runtime.runTestCase (/home/davide/Projects/bitbucket.org/ntuity/neoom-app/e2e/node_modules/@cucumber/cucumber/src/runtime/index.ts:89:20)
[0-0]  Error:  currentTest.endTest is not a function
[0-0] 2024-01-19T14:34:51.119Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-01-19T14:34:51.119Z INFO webdriver: [DELETE] http://0.0.0.0:34093/session/478fc9aa75d73991d63bd9adda9ab696
[0-0] 2024-01-19T14:34:51.171Z INFO webdriver: RESULT null
[0-0] 2024-01-19T14:34:51.172Z INFO webdriver: Kill /tmp/chromedriver/linux-120.0.6099.109/chromedriver-linux64/chromedriver driver process with command line: --port=34093 --allowed-origins=* --allowed-ips=0.0.0.0
[0-0] FAILED in chrome - file:///features/site/edit_profile.feature
2024-01-19T14:34:51.306Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-01-19T14:34:51.306Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 120.0.6099.224 linux #0-0] Running: chrome (v120.0.6099.224) on linux
[chrome 120.0.6099.224 linux #0-0] Session ID: 478fc9aa75d73991d63bd9adda9ab696
[chrome 120.0.6099.224 linux #0-0]
[chrome 120.0.6099.224 linux #0-0] » /features/site/edit_profile.feature
[chrome 120.0.6099.224 linux #0-0] Edit Profile Data
[chrome 120.0.6099.224 linux #0-0] User navigates to the profile page
[chrome 120.0.6099.224 linux #0-0]    ✓ Given the user is logged in
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clicks on "[data-testid='main-menu-/profiletab']"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user sees "Mein Profil"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clicks on "Mein Profil"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user sees "Profil"
[chrome 120.0.6099.224 linux #0-0]
[chrome 120.0.6099.224 linux #0-0] User edits profile data
[chrome 120.0.6099.224 linux #0-0]    ✓ Given the user sees "Profil"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clicks on "Meine Daten ändern"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user sees "Personendaten"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user selects "Frau" in the dropdown of "[data-testid='user-data-form-salutation']"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clears the value of "[data-testid='user-data-form-firstname']"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user adds the value "Maria" into "[data-testid='user-data-form-firstname']"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clears the value of "[data-testid='user-data-form-lastname']"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user cannot click on "Speichern"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user adds the value "Musterfrau" into "[data-testid='user-data-form-lastname']"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clears the value of "[data-testid='user-data-form-street']"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user adds the value "Musterstraße" into "[data-testid='user-data-form-street']"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clears the value of "[data-testid='user-data-form-street-number']"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user adds the value "10" into "[data-testid='user-data-form-street-number']"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clears the value of "[data-testid='user-data-form-city']"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user adds the value "Musterstadt" into "[data-testid='user-data-form-city']"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clears the value of "[data-testid='user-data-form-zip']"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user adds the value "1010" into "[data-testid='user-data-form-zip']"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user selects "Deutschland" in the dropdown of "[data-testid='user-data-form-country']"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user selects "+49" in the dropdown of "[data-testid='user-data-form-phone-code']"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clears the value of "[data-testid='user-data-form-phone-number']"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user adds the value "123456" into "[data-testid='user-data-form-phone-number']"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user can click on "Speichern"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user scrolls to "[data-testid='bottom-anchor']"
[chrome 120.0.6099.224 linux #0-0]    ✓ When the user clicks on "Speichern"
[chrome 120.0.6099.224 linux #0-0]    ✓ Then the user sees "Frau Maria Musterfrau"
[chrome 120.0.6099.224 linux #0-0]    ✓ And the user sees "Deutschland"
[chrome 120.0.6099.224 linux #0-0]    ✓ And the user sees "+49 123456"
[chrome 120.0.6099.224 linux #0-0]
[chrome 120.0.6099.224 linux #0-0] 33 passing (16.5s)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Closing due to inactivity.

**Comment by roger-lai-appier** [comment]
I've met the same issue and tried to collect some info.
Don't know if it helps and do I need to submit another issue?

- Env
  - macOS 14.3
  - npm 8.1.0
  - node v17.0.1
  - "@wdio/allure-reporter": "^8.10.2",
    "@wdio/cli": "^8.10.1",
    "@wdio/cucumber-framework": "^8.10.1",
    "@wdio/local-runner": "^8.10.1",
    "@wdio/selenium-standalone-service": "^8.10.1",
    "@wdio/spec-reporter": "^8.10.4",
- Troubleshooting
  - disableWebdriverStepsReporting: true, useCucumberStepReporter: true
    - No issue
  - disableWebdriverStepsReporting: false, useCucumberStepReporter: true
    - Has error
  - disableWebdriverStepsReporting: true, useCucumberStepReporter: false
    - No issue
- Log
```
[0-0] Scenario end: Open the webchat to see the bot message
[0-0] 2024-02-02T02:56:21.021Z INFO webdriver: COMMAND takeScreenshot()
[0-0] 2024-02-02T02:56:21.022Z INFO webdriver: [GET] https://***/session/a7e05fd7003a04615ce0f570b4e33695/screenshot
[0-0] 2024-02-02T02:56:21.386Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAABVAAAANwCAYAAADJAkFEAAAAAXNSR0IArs4c6***
[0-0] 2024-02-02T02:56:21.394Z DEBUG @wdio/utils:shim: Finished to run "afterScenario" hook in 374ms
[0-0] 2024-02-02T02:56:21.398Z ERROR @wdio/runner: TypeError: currentTest.endTest is not a function
[0-0]     at AllureReporter.onSuiteEnd (file:///***/node_modules/@wdio/allure-reporter/build/reporter.js:288:29)
[0-0]     at AllureReporter.<anonymous> (file:///***/node_modules/@wdio/reporter/build/index.js:165:18)
[0-0]     at AllureReporter.emit (node:events:390:28)
[0-0]     at AllureReporter.emit (node:domain:475:12)
[0-0]     at file:///***/node_modules/@wdio/runner/build/reporter.js:47:56
[0-0]     at Array.forEach (<anonymous>)
[0-0]     at BaseReporter.emit (file:///***/node_modules/@wdio/runner/build/reporter.js:47:25)
[0-0]     at CucumberFormatter.emit (file:///***/node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:92:23)
[0-0]     at CucumberFormatter.onTestCaseFinished (file:///***/node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:389:14)
[0-0]     at EventEmitter.<anonymous> (file:///***/node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:63:22)
[0-0]  Error:  currentTest.endTest is not a function
[0-0] 2024-02-02T02:56:21.408Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-02-02T02:56:21.409Z INFO webdriver: [DELETE] https://***/session/a7e05fd7003a04615ce0f570b4e33695
[0-0] 2024-02-02T02:56:21.521Z INFO webdriver: RESULT null
2024-02-02T02:56:21.682Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///features/0.critical/70.***.feature
2024-02-02T02:56:21.684Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-02-02T02:56:21.685Z INFO @wdio/cli:launcher: Run onComplete hook
Report successfully generated to allure-report
Allure report successfully generated
```

**Comment by ZhukovMv** [comment]
@christian-bromann I faced the same error. And it turns out that it doesn't reproduced when I set disableWebdriverStepsReporting to true.
Here is the log of the step that is causing the error in the reporter:
`[0-3] 2024-02-12T12:16:04.251Z INFO webdriver: COMMAND findElement("css selector", "div.alertBox.success div.msg")
[0-3] 2024-02-12T12:16:04.251Z INFO webdriver: [POST] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element
[0-3] 2024-02-12T12:16:04.251Z INFO webdriver: DATA { using: 'css selector', value: 'div.alertBox.success div.msg' }
[0-3] 2024-02-12T12:16:04.257Z INFO webdriver: RESULT {
[0-3]   'element-6066-11e4-a52e-4f735466cecf': 'B9E974B05F51EF473904807A96D11914_element_261'
[0-3] }
[0-3] 2024-02-12T12:16:04.258Z INFO webdriver: COMMAND getElementText("B9E974B05F51EF473904807A96D11914_element_261")
[0-3] 2024-02-12T12:16:04.258Z INFO webdriver: [GET] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element/B9E974B05F51EF473904807A96D11914_element_261/text
[0-3] 2024-02-12T12:16:04.262Z INFO webdriver: RESULT Shift creation successful
[0-3] 2024-02-12T12:16:04.764Z INFO webdriver: COMMAND getElementText("B9E974B05F51EF473904807A96D11914_element_261")
[0-3] 2024-02-12T12:16:04.765Z INFO webdriver: [GET] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element/B9E974B05F51EF473904807A96D11914_element_261/text
[0-3] 2024-02-12T12:16:04.780Z WARN webdriver: Request encountered a stale element - terminating request
[0-3] 2024-02-12T12:16:04.782Z INFO webdriver: COMMAND findElement("css selector", "div.alertBox.success div.msg")
[0-3] 2024-02-12T12:16:04.782Z INFO webdriver: [POST] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element
[0-3] 2024-02-12T12:16:04.782Z INFO webdriver: DATA { using: 'css selector', value: 'div.alertBox.success div.msg' }
[0-3] 2024-02-12T12:16:04.790Z INFO webdriver: RESULT {
[0-3]   'element-6066-11e4-a52e-4f735466cecf': 'B9E974B05F51EF473904807A96D11914_element_266'
[0-3] }
[0-3] 2024-02-12T12:16:04.793Z INFO webdriver: COMMAND getElementText("B9E974B05F51EF473904807A96D11914_element_261")
[0-3] 2024-02-12T12:16:04.793Z INFO webdriver: [GET] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element/B9E974B05F51EF473904807A96D11914_element_261/text
[0-3] 2024-02-12T12:16:04.800Z WARN webdriver: Request encountered a stale element - terminating request
[0-3] 2024-02-12T12:16:04.801Z INFO webdriver: COMMAND findElement("css selector", "div.alertBox.success div.msg")
[0-3] 2024-02-12T12:16:04.801Z INFO webdriver: [POST] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element
[0-3] 2024-02-12T12:16:04.801Z INFO webdriver: DATA { using: 'css selector', value: 'div.alertBox.success div.msg' }
[0-3] 2024-02-12T12:16:04.807Z INFO webdriver: RESULT {
[0-3]   'element-6066-11e4-a52e-4f735466cecf': 'B9E974B05F51EF473904807A96D11914_element_266'
[0-3] }
[0-3] 2024-02-12T12:16:04.809Z INFO webdriver: COMMAND getElementText("B9E974B05F51EF473904807A96D11914_element_266")
[0-3] 2024-02-12T12:16:04.809Z INFO webdriver: [GET] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element/B9E974B05F51EF473904807A96D11914_element_266/text
[0-3] 2024-02-12T12:16:04.814Z INFO webdriver: RESULT Sending invitations...
[0-3] 2024-02-12T12:16:05.316Z INFO webdriver: COMMAND getElementText("B9E974B05F51EF473904807A96D11914_element_266")
[0-3] 2024-02-12T12:16:05.316Z INFO webdriver: [GET] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element/B9E974B05F51EF473904807A96D11914_element_266/text
[0-3] 2024-02-12T12:16:05.329Z INFO webdriver: RESULT Sending invitations...
[0-3] 2024-02-12T12:16:05.830Z INFO webdriver: COMMAND getElementText("B9E974B05F51EF473904807A96D11914_element_266")
[0-3] 2024-02-12T12:16:05.830Z INFO webdriver: [GET] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element/B9E974B05F51EF473904807A96D11914_element_266/text
[0-3] 2024-02-12T12:16:05.838Z INFO webdriver: RESULT Sending invitations...
[0-3] 2024-02-12T12:16:06.340Z INFO webdriver: COMMAND getElementText("B9E974B05F51EF473904807A96D11914_element_266")
[0-3] 2024-02-12T12:16:06.341Z INFO webdriver: [GET] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element/B9E974B05F51EF473904807A96D11914_element_266/text
[0-3] 2024-02-12T12:16:06.355Z WARN webdriver: Request encountered a stale element - terminating request
[0-3] 2024-02-12T12:16:06.356Z INFO webdriver: COMMAND findElement("css selector", "div.alertBox.success div.msg")
[0-3] 2024-02-12T12:16:06.356Z INFO webdriver: [POST] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element
[0-3] 2024-02-12T12:16:06.356Z INFO webdriver: DATA { using: 'css selector', value: 'div.alertBox.success div.msg' }
[0-3] 2024-02-12T12:16:06.364Z INFO webdriver: RESULT {
[0-3]   'element-6066-11e4-a52e-4f735466cecf': 'B9E974B05F51EF473904807A96D11914_element_316'
[0-3] }
[0-3] 2024-02-12T12:16:06.366Z INFO webdriver: COMMAND getElementText("B9E974B05F51EF473904807A96D11914_element_266")
[0-3] 2024-02-12T12:16:06.367Z INFO webdriver: [GET] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element/B9E974B05F51EF473904807A96D11914_element_266/text
[0-3] 2024-02-12T12:16:06.374Z WARN webdriver: Request encountered a stale element - terminating request
[0-3] 2024-02-12T12:16:06.375Z INFO webdriver: COMMAND findElement("css selector", "div.alertBox.success div.msg")
[0-3] 2024-02-12T12:16:06.375Z INFO webdriver: [POST] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element
[0-3] 2024-02-12T12:16:06.375Z INFO webdriver: DATA { using: 'css selector', value: 'div.alertBox.success div.msg' }
[0-3] 2024-02-12T12:16:06.381Z INFO webdriver: RESULT {
[0-3]   'element-6066-11e4-a52e-4f735466cecf': 'B9E974B05F51EF473904807A96D11914_element_316'
[0-3] }
[0-3] 2024-02-12T12:16:06.383Z INFO webdriver: COMMAND getElementText("B9E974B05F51EF473904807A96D11914_element_316")
[0-3] 2024-02-12T12:16:06.383Z INFO webdriver: [GET] http://0.0.0.0:60647/session/8c9c8c0444489ba5d9d7b3b31e5915f2/element/B9E974B05F51EF473904807A96D11914_element_316/text
[0-3] 2024-02-12T12:16:06.388Z INFO webdriver: RESULT 1 invitation out of 1 sent successfully
`

**Comment by BorisOsipov** [comment]
@ZhukovMv Unfortunately we can't help you without a reproducible example in this matter. Please read [providing-a-reproducible-example](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#providing-a-reproducible-example)
