### ISSUE TITLE
[🐛 Bug]: wdio/visual-service is not compatible with wdio-video-reporter

### ISSUE THREAD

**Issue by Avinash-Kannan** [webdriverio/webdriverio#12075]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v8

### Node.js Version

v18.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome'
    }],
```

### What happened?

wdio-video-reporter throws error with visual service

### How to reproduce the bug.

Add these in your project :
```
 "@wdio/visual-service": "^1.0.0"
  "wdio-video-reporter": "^5.1.1",
```
Now, add video reporter in your reporter config (with Allure)

### Relevant log output

```typescript
[0-0] 2024-01-23T12:54:28.508Z INFO @wdio/visual-service: Adding commands to global browser
[0-0] 2024-01-23T12:54:28.509Z INFO @wdio/visual-service: Adding element command "saveElement" to browser object[0-0] 2024-01-23T12:54:28.510Z INFO @wdio/visual-service: Adding element command "checkElement" to browser object
[0-0] 2024-01-23T12:54:28.510Z INFO @wdio/visual-service: Adding element command "saveScreen" to browser object 
[0-0] 2024-01-23T12:54:28.510Z INFO @wdio/visual-service: Adding element command "saveFullPageScreen" to browser object
[0-0] 2024-01-23T12:54:28.511Z INFO @wdio/visual-service: Adding element command "saveTabbablePage" to browser object
[0-0] 2024-01-23T12:54:28.511Z INFO @wdio/visual-service: Adding element command "checkScreen" to browser object[0-0] 2024-01-23T12:54:28.511Z INFO @wdio/visual-service: Adding element command "checkFullPageScreen" to browser object
[0-0] 2024-01-23T12:54:28.511Z INFO @wdio/visual-service: Adding element command "checkTabbablePage" to browser 
object
[0-0] Error in ""before all" hook in "{root}""
Error: done() called multiple times in hook <"before all" hook in "{root}"> (of root suite); in addition, done() received error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at createMultipleDoneError (e2e\node_modules\mocha\lib\errors.js:428:13)
    at multiple (e2e\node_modules\mocha\lib\runnable.js:290:24)      
    at Hook.done [as callback] (e2e\node_modules\mocha\lib\runnable.js:301:14)
    at Runner._uncaught (e2e\node_modules\mocha\lib\runner.js:1011:21)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (e2e\node_modules\@cspotcode\source-map-support\source-map-support.js:745:40)
    at process._fatalException (node:internal/process/execution:149:25)
[0-0] file: e2e/node_modules/@wdio/reporter/build/index.js:89
[0-0]             hookStats.complete(getErrorsFromEvent(hook));
[0-0]                       ^
[0-0]
[0-0] TypeError: Cannot read properties of undefined (reading 'complete')
[0-0]     at SpecReporter.<anonymous> (file: e2e/node_modules/@wdio/reporter/build/index.js:89:23)
[0-0]     at SpecReporter.emit (node:events:513:28)
[0-0]     at SpecReporter.emit (node:domain:489:12)
[0-0]     at file: e2e/node_modules/@wdio/runner/build/reporter.js:47:56
[0-0]     at Array.forEach (<anonymous>)
[0-0]     at BaseReporter.emit (file:e2e/node_modules/@wdio/runner/build/reporter.js:47:25)
[0-0]     at MochaAdapter.emit (file:e2e/node_modules/@wdio/mocha-framework/build/index.js:162:24)
[0-0]     at Runner.emit (node:events:525:35)
[0-0]     at Runner.emit (node:domain:489:12)
[0-0]     at Runner.fail (e2e\node_modules\mocha\lib\runner.js:453:8)[0-0]     at Hook.<anonymous> (e2e\node_modules\mocha\lib\runner.js:494:14)
[0-0]     at Hook.emit (node:events:513:28)
[0-0]     at Hook.emit (node:domain:489:12)
[0-0]     at multiple (e2e\node_modules\mocha\lib\runnable.js:290:10)[0-0]     at Hook.done [as callback] (e2e\node_modules\mocha\lib\runnable.js:301:14)
[0-0]     at Runner._uncaught (e2e\node_modules\mocha\lib\runner.js:1011:21)
[0-0]
[0-0] Node.js v18.15.0
[0-0] FAILED in chrome - file:e2e/test/specs/test.e2e.ts
2024-01-23T12:54:28.583Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-01-23T12:54:28.584Z INFO @wdio/cli:launcher: Run onComplete hook
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Avinash-Kannan** [comment]
https://github.com/webdriverio-community/wdio-video-reporter/issues/133
Seems like issue in 3rd party video reporter service..Closing this one
