### ISSUE TITLE
Can't able to merge muiltiple json files using "@wdio/json-reporter"

### ISSUE THREAD

**Issue by LakshmiYaswanth** [webdriverio/webdriverio#12074]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.29.0

### Node.js Version

21.6.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
import type { Options } from '@wdio/types'
import  mergeResults  from "@wdio/json-reporter/build/mergeResults";
export const config: Options.Testrunner = {
    //
    // ====================
    // Runner Configuration
    // ====================
    // WebdriverIO supports running e2e tests as well as unit and component tests.
    runner: 'local',
    autoCompileOpts: {
        autoCompile: true,
        tsNodeOpts: {
            project: './tsconfig.json',
            transpileOnly: true
        }
    },
    
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // of the configuration file being run.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // The path of the spec files will be resolved relative from the directory of
    // of the config file unless it's absolute.
    //
    specs: [
        './test/specs/**/*.ts'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://saucelabs.com/platform/platform-configurator
    //
    capabilities: [{
        browserName: 'chrome'
    }],

    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'info',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/appium-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    // services: [],
    //
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Delay in seconds between the spec file retry attempts
    // specFileRetriesDelay: 0,
    //
    // Whether or not retried spec files should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter
    reporters: ['spec',
    ['json', {
        outputDir: './test-report/json-result/',
        outputFileFormat: function (options: { cid: any }) {
            return `results-${options.cid}.json`
        }
    }],
    [
        'allure',
        {
            outputDir: './test-report/allure-result/',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: false,
        },
    ],
],

    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },

    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed before a worker process is spawned and can be used to initialize specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {string} cid      capability id (e.g 0-0)
     * @param  {object} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {object} specs    specs to be run in the worker process
     * @param  {object} args     object that will be merged with the main configuration once worker is initialized
     * @param  {object} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just after a worker process has exited.
     * @param  {string} cid      capability id (e.g 0-0)
     * @param  {number} exitCode 0 - success, 1 - fail
     * @param  {object} specs    specs to be run in the worker process
     * @param  {number} retries  number of retries used
     */
    // onWorkerEnd: function (cid, exitCode, specs, retries) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     * @param {string} cid worker id (e.g. 0-0)
     */
    // beforeSession: function (config, capabilities, specs, cid) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {object}         browser      instance of created browser/device session
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {string} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Hook that gets executed before the suite starts
     * @param {object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
    // beforeTest: function (test, context) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function (test, context, hookName) {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function (test, context, { error, result, duration, passed, retries }, hookName) {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine only)
     * @param {object}  test             test object
     * @param {object}  context          scope object the test was executed with
     * @param {Error}   result.error     error object in case the test fails, otherwise `undefined`
     * @param {*}       result.result    return object of test function
     * @param {number}  result.duration  duration of test
     * @param {boolean} result.passed    true if test has passed, otherwise false
     * @param {object}  result.retries   information about spec related retries, e.g. `{ attempts: 0, limit: 0 }`
     */
    afterTest: async function(test, context, { error, result, duration, passed, retries }) {
        if (!passed) {
            await browser.takeScreenshot();
        }
    },


    /**
     * Hook that gets executed after the suite has ended
     * @param {object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {string} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {number} result 0 - command success, 1 - command error
     * @param {object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {object} exitCode 0 - success, 1 - fail
     * @param {object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    onComplete: function(exitCode, config, capabilities, results) {
        mergeResults('./test-report/json-result', 'results-*.json', 'wdio-custom-filename.json')
    },
    /**
    * Gets executed when a refresh happens.
    * @param {string} oldSessionId session ID of the old session
    * @param {string} newSessionId session ID of the new session
    */
    // onReload: function(oldSessionId, newSessionId) {
    // }
    /**
    * Hook that gets executed before a WebdriverIO assertion happens.
    * @param {object} params information about the assertion to be executed
    */
    // beforeAssertion: function(params) {
    // }
    /**
    * Hook that gets executed after a WebdriverIO assertion happened.
    * @param {object} params information about the assertion that was executed, including its results
    */
    // afterAssertion: function(params) {
    // }
}
```

### What happened?

2024-01-23T11:39:04.604Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///C:/Users/bbolli065/Documents/GitHub/creat-wedo/wdio.conf.ts: ERR_PACKAGE_PATH_NOT_EXPORTED C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\@wdio\json-reporter\ ./build/mergeResults C:\Users\bbolli065\Documents\GitHub\creat-wedo\wdio.conf.ts
Error: ERR_PACKAGE_PATH_NOT_EXPORTED C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\@wdio\json-reporter\ ./build/mergeResults C:\Users\bbolli065\Documents\GitHub\creat-wedo\wdio.conf.ts
    at throwExportsNotFound (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:380:9)       
    at packageExportsResolve (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:605:3)      
    at packageResolve (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:746:14)
    at moduleResolve (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:912:11)     
    at C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\src\esm.ts:218:35
    at entrypointFallback (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\src\esm.ts:168:34)
    at C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\src\esm.ts:217:14
    at addShortCircuitFlag (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\src\esm.ts:409:21)
    at resolve (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\src\esm.ts:197:12)

### What is your expected behavior?

should not throw error.

### How to reproduce the bug.

- Install a project using npm init wdio@latest .
- add json reporter and sample specs
- add  mergeResults('./test-report/json-result', 'results-*.json', 'wdio-custom-filename.json') in wdio.conf.js
- and Run

### Relevant log output

```typescript
2024-01-23T11:39:04.604Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///C:/Users/bbolli065/Documents/GitHub/creat-wedo/wdio.conf.ts: ERR_PACKAGE_PATH_NOT_EXPORTED C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\@wdio\json-reporter\ ./build/mergeResults C:\Users\bbolli065\Documents\GitHub\creat-wedo\wdio.conf.ts
Error: ERR_PACKAGE_PATH_NOT_EXPORTED C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\@wdio\json-reporter\ ./build/mergeResults C:\Users\bbolli065\Documents\GitHub\creat-wedo\wdio.conf.ts
    at throwExportsNotFound (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:380:9)       
    at packageExportsResolve (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:605:3)      
    at packageResolve (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:746:14)
    at moduleResolve (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:912:11)     
    at C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\src\esm.ts:218:35
    at entrypointFallback (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\src\esm.ts:168:34)
    at C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\src\esm.ts:217:14
    at addShortCircuitFlag (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\src\esm.ts:409:21)
    at resolve (C:\Users\bbolli065\Documents\GitHub\creat-wedo\node_modules\ts-node\src\esm.ts:197:12
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ```ts
> import  mergeResults  from "@wdio/json-reporter/build/mergeResults";
> ```

This is an invalid import path, see the [docs](https://webdriver.io/docs/json-reporter), it states:

```ts
import mergeResults from '@wdio/json-reporter/mergeResults'
```

Let me know if you have further questions!

**Comment by LakshmiYaswanth** [comment]
Thanks for response  @christian-bromann . import mergeResults from '@wdio/json-reporter/mergeResults'

But when we import the above.  '@@wdio/json-reporter" doesnt have mergeResults file. 
mergeResults file was inside the build/mergeResults.

I have given the zip of the project can u download and run it once.

**Comment by LakshmiYaswanth** [comment]
[creat-wedo.zip](https://github.com/webdriverio/webdriverio/files/14028548/creat-wedo.zip)

**Comment by LakshmiYaswanth** [comment]
> Please provide a reproducible example as GitHub repository. Thank you.

[creat-wedo.zip](https://github.com/webdriverio/webdriverio/files/14033101/creat-wedo.zip)
Can u unzip and tryit

**Comment by christian-bromann** [comment]
I am not downloading a zip that I don't know the contents of. Please create a repository.

**Comment by LakshmiYaswanth** [comment]
https://github.com/LakshmiYaswanth/wdio-create 

Can u check this issue. Thank you in advance.

**Comment by christian-bromann** [comment]
3 changes are needed:

- as mention above and in the docs, the import for `mergeResults` is as following: `import mergeResults from '@wdio/json-reporter/mergeResults'`
- change module resolution to `node16` - it is generally not recommended to keep `node` at this point
- change the function call to `mergeResults('./test-report/json-result', 'results-*', 'wdio-custom-filename.json')`

**Comment by gforepsly** [comment]
> 3 changes are needed:
> 
> * as mention above and in the docs, the import for `mergeResults` is as following: `import mergeResults from '@wdio/json-reporter/mergeResults'`
> * change module resolution to `node16` - it is generally not recommended to keep `node` at this point
> * change the function call to `mergeResults('./test-report/json-result', 'results-*', 'wdio-custom-filename.json')`

I'm also having this issue. 
In the official documentation for wdioIO (https://webdriver.io/docs/typescript/), i can't find the module resolution anywhere. What changes if i change from:

"moduleResolution": "node",
        "module": "commonjs",

to

"moduleResolution": "node16",
        "module": "node16" ?

Still, even with that, the import line for merging still doesn't work.

**Comment by gforepsly** [comment]
> @gforepsly can you provide a reproducible example?

Hi! 
Thx for the reply :)

I can try with a new project, I will replicate our conf file (we use conf.ts) and get back to you. I can also open a new topic and provide all relevant data. Would that be ok? 
I'm also quite busy, so I would do this by the end of the week.
