### ISSUE TITLE
Touch command is not supported on non mobile platforms

### ISSUE THREAD

**Issue by ethannguyens** [webdriverio/webdriverio#1212]
I see the following error when trying to perform a touch and other mobile related actions

touch error:

`Uncaught CommandError: touch command is not supported on non mobile platforms`

touchFlick error:

`Uncaught RuntimeError: An unknown server-side error occurred while processing the command. Error converting element ID for using in WD atoms: .header-menu`

I am using Appium on the real iPhone device with the following capability:

`    browserName: 'safari',
    'appium-version': '1.4.13',
    platformName: 'iOS',
    platformVersion: '9.2',
    deviceName: 'iPhone',
    app: 'com.bytearc.SafariLaunchers',
    udid: 'xxxx'
`

And the test i wrote:

`driver
            .url('http://m.mysite.com')
            .touch('.header-menu')
            .pause(5000)
            .call(done);
`
Anyone comes across this error?

**Comment by christian-bromann** [comment]
@ethannguyens please remove the `browserName` capability and rerun your test. You need to make sure that your are in a native context to execute mobile commands.

**Comment by ethannguyens** [comment]
@christian-bromann Thank you. Is there any way I can perform these action on safari browser?

**Comment by christian-bromann** [comment]
You should, you need to switch the context using http://webdriver.io/api/mobile/context.html

**Comment by ethannguyens** [comment]
I am able to switch to WEBVIEW_3 but when I try to switch to NATIVE_APP. I see a consistent error:

info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_3"],"sessionId":"c9cc4db4-ab9e-4296-9ab6-f0f33f1dbf92"}

info: <-- GET /wd/hub/session/c9cc4db4-ab9e-4296-9ab6-f0f33f1dbf92/contexts 200 5.085 ms - 98 {"status":0,"value":["NATIVE_APP","WEBVIEW_3"],"sessionId":"c9cc4db4-ab9e-4296-9ab6-f0f33f1dbf92"}

info: --> POST /wd/hub/session/c9cc4db4-ab9e-4296-9ab6-f0f33f1dbf92/context {"name":"NATIVE_APP"}

info: [debug] Attempting to set context to 'NATIVE_APP'

info: <-- POST /wd/hub/session/c9cc4db4-ab9e-4296-9ab6-f0f33f1dbf92/context 500 2.060 ms - 74 

TypeError: cb is not a function
    at [object Object].WebKitRemoteDebugger.disconnect (/Users/nguyene/Work/appium/lib/devices/ios/webkit-remote-debugger.js:68:5)
    at [object Object].iOSController.setContext (/Users/nguyene/Work/appium/lib/devices/ios/ios-controller.js:1658:21)
    at exports.setContext (/Users/nguyene/Work/appium/lib/server/controller.js:1023:16)
    at Layer.handle [as handle_request] (/Users/nguyene/Work/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/nguyene/Work/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/nguyene/Work/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/nguyene/Work/appium/node_modules/express/lib/router/layer.js:82:5)
    at /Users/nguyene/Work/appium/node_modules/express/lib/router/index.js:267:22
    at param (/Users/nguyene/Work/appium/node_modules/express/lib/router/index.js:340:14)
    at param (/Users/nguyene/Work/appium/node_modules/express/lib/router/index.js:356:14)
    at Function.proto.process_params (/Users/nguyene/Work/appium/node_modules/express/lib/router/index.js:400:3)

**Comment by christian-bromann** [comment]
This seems to be an Appium issue. Please file an issue [here](https://github.com/appium/appium/issues). Thanks!
