### ISSUE TITLE
[🐛 Bug]: <Error: Webview context WEBVIEW_chrome not loaded>

### ISSUE THREAD

**Issue by hemanthsa1997** [webdriverio/webdriverio#12133]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
platformName: "Android",
                //'appium:deviceName': "pixel 4",
                'appium:noReset': true,
                'appium:platformVersion': '12',
                'appium:newCommandTimeout': 5000,
                'appium:app': "/Users/hemanth.sa/Documents/qa-debug.apk",
                'appium:automationName': "UIAutomator2",
                'appium:autoGrantPermissions': true,
                'appium:enableWebviewDetailsCollection': true,
```

### What happened?

showing Error: Webview context WEBVIEW_chrome not loaded

No Error is shown in the Appium logs also

### What is your expected behavior?

find elements in webview

### How to reproduce the bug.

our framework is on Page object model.

**we use the below function to load webview**

```ts
async waitForSpecificWebviewContextLoad(webviewName: string, timeout?: number): Promise<boolean> {
        Logger.info(`Waiting for webview context ${webviewName} to be loaded`);
        const elementFound = await driver.waitUntil(
            async (): Promise<boolean> => {
                try {
                    (await this.getCurrentContexts()).forEach((context) => {
                        Logger.info(`Context: ${context}`);
                        if (isDetailedContext(context)) {
                            Logger.info('Context is of type DetailedContext');
                            return (context as DetailedContext).id.toLowerCase().includes(webviewName.toLowerCase());
                        } else if (typeof context === 'string') {
                            Logger.info('Context is of type string');
                            return (context as string).toLowerCase().includes(webviewName.toLowerCase());
                        }
                    });
                } catch (e) {
                    Logger.error(e);
                }
                return false;
            },
            {
                timeout: timeout ?? 10000,
                timeoutMsg: `Webview context ${webviewName} not loaded`,
                interval: 1000,
            },
        );
        return elementFound === true ? true : false;
    }
```

**once loaded we use this to switch to webview**

```ts
async switchToContext(context: string): Promise<void> {
        try {
            let contextSwitched = false;
            Logger.debug(await this.getCurrentContexts());
            const availableContexts = await this.getCurrentContexts();
            for (const availableContext of availableContexts) {
                Logger.debug(availableContext);
                let availableContextValue;
                if (await eval('availableContext.id')) {
                    availableContextValue = await eval('availableContext.id');
                } else {
                    availableContextValue = availableContext;
                }
                if (await availableContextValue.toLowerCase().indexOf(context.toLowerCase()) > -1) {
                    Logger.info(`Switching to ${availableContextValue}`);
                    Logger.debug(await this.getCurrentContexts());
                    await driver.switchContext(availableContextValue);
                    Logger.info(`Switched to ${context} context`);
                    contextSwitched = true;
                }
            }
            if (!contextSwitched) Logger.error(`Did not switch to context: ${context}`);
            // driver.switchContext(await this.getCurrentContexts()[context === "WEBVIEW_chrome" ? 1 : 0]);
        } catch (e) {
            Logger.info(`Did not switch to context: ${e}`);
        }
    }
```

### Relevant log output

```typescript
Calling AppiumDriver.getContexts() with args: ["be0312d2-5cb0-423c-90c6-bc350f0cdca5"]
[AndroidUiautomator2Driver@e744 (be0312d2)] Getting a list of available webviews
[ADB] Running '/Users/hemanth.sa/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell cat /proc/net/unix'
[AndroidUiautomator2Driver@e744 (be0312d2)] Parsed 2 active devtools sockets: ["@webview_devtools_remote_5930","@chrome_devtools_remote"]
[AndroidUiautomator2Driver@e744 (be0312d2)] Collecting CDP data of 2 webviews
[AndroidUiautomator2Driver@e744 (be0312d2)] Forwarding remote port webview_devtools_remote_5930 to a local port in range 10900..11000
[AndroidUiautomator2Driver@e744 (be0312d2)] You could use the 'webviewDevtoolsPort' capability to customize the starting port number
[AndroidUiautomator2Driver@e744 (be0312d2)] Forwarding remote port chrome_devtools_remote to a local port in range 10900..11000
[AndroidUiautomator2Driver@e744 (be0312d2)] You could use the 'webviewDevtoolsPort' capability to customize the starting port number
[ADB] Running '/Users/hemanth.sa/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp:10900 localabstract:webview_devtools_remote_5930'
[ADB] Removing forwarded port socket connection: 10900 
[ADB] Running '/Users/hemanth.sa/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:10900'
[ADB] Running '/Users/hemanth.sa/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp:10900 localabstract:chrome_devtools_remote'
[ADB] Removing forwarded port socket connection: 10900 
[ADB] Running '/Users/hemanth.sa/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:10900'
[AndroidUiautomator2Driver@e744 (be0312d2)] CDP data collection completed
[AndroidUiautomator2Driver@e744 (be0312d2)] WEBVIEW_5930 mapped to pid 5930
[AndroidUiautomator2Driver@e744 (be0312d2)] Getting process name for webview 'WEBVIEW_5930'
[ADB] Running '/Users/hemanth.sa/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ps -A'
[AndroidUiautomator2Driver@e744 (be0312d2)] Got process name: 'com.rakuten.one.test'
[AndroidUiautomator2Driver@e744 (be0312d2)] Skipping the webview 'WEBVIEW_5930' at '@webview_devtools_remote_5930' since it has reported having zero pages
[AndroidUiautomator2Driver@e744 (be0312d2)] Found 1 webview: ["WEBVIEW_chrome"]
[AndroidUiautomator2Driver@e744 (be0312d2)] Available contexts: ["NATIVE_APP","WEBVIEW_chrome"]
[AndroidUiautomator2Driver@e744 (be0312d2)] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_chrome"]
[HTTP] <-- GET /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/contexts 200 390 ms - 41
[HTTP] 
[HTTP] --> GET /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/screenshot
[HTTP] {}
[AndroidUiautomator2Driver@e744 (be0312d2)] Calling AppiumDriver.getScreenshot() with args: ["be0312d2-5cb0-423c-90c6-bc350f0cdca5"]
[AndroidUiautomator2Driver@e744 (be0312d2)] Matched '/screenshot' to command name 'getScreenshot'
[AndroidUiautomator2Driver@e744 (be0312d2)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8200/session/9e705b78-f065-41d3-8e4e-67262082c13e/screenshot] with no body
[AndroidUiautomator2Driver@e744 (be0312d2)] Got response with status 200: {"sessionId":"9e705b78-f065-41d3-8e4e-67262082c13e","value":"iVBORw0KGgoAAAANSUhEUgAABDgAAAjoCAYAAAA5jhrUAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7N15WFRl+wfw+zDsiIhioAiiuGFYIJYWbqW5r6W++rqkmeWa8iLu5lK5ZKUmriXmkhmpoaYluachuCTmihsiIPsqyzDM3L8/vDg/BmZgGGZh8Pu5ru8VMs885znL0Jx7zjxHICImAAAAAAAAAAATZmbsAQAAAAAAAAAAVBcKHAAAAAAAAABg8lDgAAAAAAAAAACThwIHAAAAAAAAAJg8FDgAAAAAAAAAwOShwAEAAAAAAAAAJg8FDgAAAAAAAAAweShwAAAAAAAAAIDJQ4EDAAAAAAAAAEweChwAAAAAAAAAYPJQ4AAAAAAAAAAAk4cCBwAAAAAAAACYPBQ4AAAAAAAAAMDkocABAAAAAAAAACYPBQ54YQiCQC1atKBNmzbRgwcPSC6Xi1EoFOLPUqmU/vnnH5o9ezY5OTmRIAjGHjoAAAAAAABUQiAiNvYgAPTJxsaGNm7cSKNGjSJLS0syM9O8rqdQKCgnJ4eWLFlCGzZsIGa8XAAAAAAAQDPjx4+npk2bVthm2bJlBhpN7YcCB1CdOnXI0tJS5ZUKCoWC8vPzSSqVGmFk1SORSOi3336jXr16kSAI1boSg5mJmcnS0pLkcrkORwkAAAAAYByOjo7k7e1NjRo1ooYNG5KjoyNlZmZSamoqPX36lG7cuEGZmZnGHqbOeXh4UGxsrEGWdebMGerWrVuFbXDFuO6YG3sAYFzm5uYUGBhIXbp0IWtr63KPZ2Rk0NatW+n3338nhUJhhBFqp2vXrnTq1CmSSCQ66a+kQDJhwgT6/vvvddInAAAAAIAh+fn5Uc+ePemtt96iV199lVxcXCp9TlJSEkVHR9OpU6foxIkTdPXqVQOMVH+mT59OLVq0...
[AndroidUiautomator2Driver@e744 (be0312d2)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAjoCAYAAAA5jhrUAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7N15WFRl+wfw+zDsiIhioAiiuGFYIJYWbqW5r6W++rqkmeWa8iLu5lK5ZKUmriXmkhmpoaYluachuCTmihsiIPsqyzDM3L8/vDg/BmZgGGZh8Pu5ru8VMs885znL0Jx7zjxHICImAAAAAAAAAAATZmbsAQAAAAAAAAAAVBcKHAAAAAAAAABg8lDgAAAAAAAAAACThwIHAAAAAAAAAJg8FDgAAAAAAAAAwOShwAEAAAAAAAAAJg8FDgAAAAAAAAAweShwAAAAAAAAAIDJQ4EDAAAAAAAAAEweChwAAAAAAAAAYPJQ4AAAAAAAAAAAk4cCBwAAAAAAAACYPBQ4AAAAAAAAAMDkocABAAAAAAAAACYPBQ54YQiCQC1atKBNmzbRgwcPSC6Xi1EoFOLPUqmU/vnnH5o9ezY5OTmRIAjGHjoAAAAAAABUQiAiNvYgAPTJxsaGNm7cSKNGjSJLS0syM9O8rqdQKCgnJ4eWLFlCGzZsIGa8XAAAAAAAQDPjx4+npk2bVthm2bJlBhpN7YcCB1CdOnXI0tJS5ZUKCoWC8vPzSSqVGmFk1SORSOi3336jXr16kSAI1boSg5mJmcnS0pLkcrkORwkAAAAAYByOjo7k7e1NjRo1ooYNG5KjoyNlZmZSamoqPX36lG7cuEGZmZnGHqbOeXh4UGxsrEGWdebMGerWrVuFbXDFuO6YG3sAYFzm5uYUGBhIXbp0IWtr63KPZ2Rk0NatW+n3338nhUJhhBFqp2vXrnTq1CmSSCQ66a+kQDJhwgT6/vvvddInAAAAAIAh+fn5Uc+ePemtt96iV199lVxcXCp9TlJSEkVHR9OpU6foxIkTdPXqVQOMVH+mT59OLVq0oFmzZhl7KKAnjLy48fPz4+joaK5IcHAwu7u7G32smkQQBN62bRsrFIoK10lb...
[HTTP] <-- GET /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/screenshot 200 399 ms - 275728
[HTTP] 
[HTTP] --> GET /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/screenshot
[HTTP] {}
[AndroidUiautomator2Driver@e744 (be0312d2)] Calling AppiumDriver.getScreenshot() with args: ["be0312d2-5cb0-423c-90c6-bc350f0cdca5"]
[AndroidUiautomator2Driver@e744 (be0312d2)] Matched '/screenshot' to command name 'getScreenshot'
[AndroidUiautomator2Driver@e744 (be0312d2)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8200/session/9e705b78-f065-41d3-8e4e-67262082c13e/screenshot] with no body
[HTTP] --> GET /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/log/types
[HTTP] {}
[AndroidUiautomator2Driver@e744 (be0312d2)] Calling AppiumDriver.getLogTypes() with args: ["be0312d2-5cb0-423c-90c6-bc350f0cdca5"]
[AndroidUiautomator2Driver@e744 (be0312d2)] Got response with status 200: {"sessionId":"9e705b78-f065-41d3-8e4e-67262082c13e","value":"iVBORw0KGgoAAAANSUhEUgAABDgAAAjoCAYAAAA5jhrUAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7N15WFRl+wfw+zDsiIhioAiiuGFYIJYWbqW5r6W++rqkmeWa8iLu5lK5ZKUmriXmkhmpoaYluachuCTmihsiIPsqyzDM3L8/vDg/BmZgGGZh8Pu5ru8VMs885znL0Jx7zjxHICImAAAAAAAAAAATZmbsAQAAAAAAAAAAVBcKHAAAAAAAAABg8lDgAAAAAAAAAACThwIHAAAAAAAAAJg8FDgAAAAAAAAAwOShwAEAAAAAAAAAJg8FDgAAAAAAAAAweShwAAAAAAAAAIDJQ4EDAAAAAAAAAEweChwAAAAAAAAAYPJQ4AAAAAAAAAAAk4cCBwAAAAAAAACYPBQ4AAAAAAAAAMDkocABAAAAAAAAACYPBQ54YQiCQC1atKBNmzbRgwcPSC6Xi1EoFOLPUqmU/vnnH5o9ezY5OTmRIAjGHjoAAAAAAABUQiAiNvYgAPTJxsaGNm7cSKNGjSJLS0syM9O8rqdQKCgnJ4eWLFlCGzZsIGa8XAAAAAAAQDPjx4+npk2bVthm2bJlBhpN7YcCB1CdOnXI0tJS5ZUKCoWC8vPzSSqVGmFk1SORSOi3336jXr16kSAI1boSg5mJmcnS0pLkcrkORwkAAAAAYByOjo7k7e1NjRo1ooYNG5KjoyNlZmZSamoqPX36lG7cuEGZmZnGHqbOeXh4UGxsrEGWdebMGerWrVuFbXDFuO6YG3sAYFzm5uYUGBhIXbp0IWtr63KPZ2Rk0NatW+n3338nhUJhhBFqp2vXrnTq1CmSSCQ66a+kQDJhwgT6/vvvddInAAAAAIAh+fn5Uc+ePemtt96iV199lVxcXCp9TlJSEkVHR9OpU6foxIkTdPXqVQOMVH+mT59OLVq0...
[AndroidUiautomator2Driver@e744 (be0312d2)] Retrieving supported log types
[AndroidUiautomator2Driver@e744 (be0312d2)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAjoCAYAAAA5jhrUAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7N15WFRl+wfw+zDsiIhioAiiuGFYIJYWbqW5r6W++rqkmeWa8iLu5lK5ZKUmriXmkhmpoaYluachuCTmihsiIPsqyzDM3L8/vDg/BmZgGGZh8Pu5ru8VMs885znL0Jx7zjxHICImAAAAAAAAAAATZmbsAQAAAAAAAAAAVBcKHAAAAAAAAABg8lDgAAAAAAAAAACThwIHAAAAAAAAAJg8FDgAAAAAAAAAwOShwAEAAAAAAAAAJg8FDgAAAAAAAAAweShwAAAAAAAAAIDJQ4EDAAAAAAAAAEweChwAAAAAAAAAYPJQ4AAAAAAAAAAAk4cCBwAAAAAAAACYPBQ4AAAAAAAAAMDkocABAAAAAAAAACYPBQ54YQiCQC1atKBNmzbRgwcPSC6Xi1EoFOLPUqmU/vnnH5o9ezY5OTmRIAjGHjoAAAAAAABUQiAiNvYgAPTJxsaGNm7cSKNGjSJLS0syM9O8rqdQKCgnJ4eWLFlCGzZsIGa8XAAAAAAAQDPjx4+npk2bVthm2bJlBhpN7YcCB1CdOnXI0tJS5ZUKCoWC8vPzSSqVGmFk1SORSOi3336jXr16kSAI1boSg5mJmcnS0pLkcrkORwkAAAAAYByOjo7k7e1NjRo1ooYNG5KjoyNlZmZSamoqPX36lG7cuEGZmZnGHqbOeXh4UGxsrEGWdebMGerWrVuFbXDFuO6YG3sAYFzm5uYUGBhIXbp0IWtr63KPZ2Rk0NatW+n3338nhUJhhBFqp2vXrnTq1CmSSCQ66a+kQDJhwgT6/vvvddInAAAAAIAh+fn5Uc+ePemtt96iV199lVxcXCp9TlJSEkVHR9OpU6foxIkTdPXqVQOMVH+mT59OLVq0oFmzZhl7KKAnjLy48fPz4+joaK5IcHAwu7u7G32smkQQBN62bRsrFIoK10lb...
[HTTP] <-- GET /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/screenshot 200 471 ms - 275752
[HTTP] 
[AndroidUiautomator2Driver@e744 (be0312d2)] Responding to client with driver.getLogTypes() result: ["logcat","bugreport","server"]
[HTTP] <-- GET /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/log/types 200 458 ms - 41
[HTTP] 
[HTTP] --> POST /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/log
[HTTP] {"type":"bugreport"}
[AndroidUiautomator2Driver@e744 (be0312d2)] Calling AppiumDriver.getLog() with args: ["bugreport","be0312d2-5cb0-423c-90c6-bc350f0cdca5"]
[AndroidUiautomator2Driver@e744 (be0312d2)] Retrieving 'bugreport' logs
[ADB] Running '/Users/hemanth.sa/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 bugreport'
[HTTP] --> POST /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/log
[HTTP] {"type":"server"}
[AndroidUiautomator2Driver@e744 (be0312d2)] Calling AppiumDriver.getLog() with args: ["server","be0312d2-5cb0-423c-90c6-bc350f0cdca5"]
[HTTP] --> POST /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/log
[HTTP] {"type":"logcat"}
[AndroidUiautomator2Driver@e744 (be0312d2)] Calling AppiumDriver.getLog() with args: ["logcat","be0312d2-5cb0-423c-90c6-bc350f0cdca5"]
[AndroidUiautomator2Driver@e744 (be0312d2)] Retrieving 'server' logs
[AndroidUiautomator2Driver@e744 (be0312d2)] Responding to client with driver.getLog() result: [{"timestamp":1706691682259,"level":"ALL","message":"/data/user_de/0/com.android.shell/files/bugreports/bugreport-sdk_gphone64_x86_64-S2B2.211203.006-2024-01-31-14-30-08.zip: 1 file pulled, 0 skipped. 69.4 MB/s (5828446 bytes in 0.080s)"},{"timestamp":1706691682259,"level":"ALL","message":"Bug report copied to /Users/hemanth.sa/bugreport-sdk_gphone64_x86_64-S2B2.211203.006-2024-01-31-14-30-08.zip"}]
[HTTP] <-- POST /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/log 200 73342 ms - 412
[HTTP] 
[AndroidUiautomator2Driver@e744 (be0312d2)] Retrieving 'logcat' logs
[AndroidUiautomator2Driver@e744 (be0312d2)] Encountered internal error running command: Error: Potentially insecure feature 'get_server_logs' has not been enabled. If you want to enable this feature and accept the security ramifications, please do so by following the documented instructions at http://appium.io/docs/en/2.0/guides/security/
[AndroidUiautomator2Driver@e744 (be0312d2)]     at AndroidUiautomator2Driver.assertFeatureEnabled (/Users/hemanth.sa/node_modules/@appium/base-driver/lib/basedriver/core.ts:300:13)
[AndroidUiautomator2Driver@e744 (be0312d2)]     at AndroidUiautomator2Driver.ensureFeatureEnabled (/Users/hemanth.sa/node_modules/@appium/base-driver/lib/basedriver/core.ts:289:10)
[AndroidUiautomator2Driver@e744 (be0312d2)]     at Object.getter (/Users/hemanth.sa/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/log.js:39:12)
[AndroidUiautomator2Driver@e744 (be0312d2)]     at AndroidUiautomator2Driver.getLog (/Users/hemanth.sa/node_modules/@appium/base-driver/lib/basedriver/commands/log.ts:30:50)
[AndroidUiautomator2Driver@e744 (be0312d2)]     at AndroidUiautomator2Driver.getLog (/Users/hemanth.sa/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/log.js:172:44)
[AndroidUiautomator2Driver@e744 (be0312d2)]     at commandExecutor (/Users/hemanth.sa/node_modules/@appium/base-driver/lib/basedriver/driver.ts:106:18)
[AndroidUiautomator2Driver@e744 (be0312d2)]     at /Users/hemanth.sa/node_modules/async-lock/lib/index.js:171:12
[AndroidUiautomator2Driver@e744 (be0312d2)]     at AsyncLock._promiseTry (/Users/hemanth.sa/node_modules/async-lock/lib/index.js:306:31)
[AndroidUiautomator2Driver@e744 (be0312d2)]     at exec (/Users/hemanth.sa/node_modules/async-lock/lib/index.js:170:9)
[AndroidUiautomator2Driver@e744 (be0312d2)]     at taskFn (/Users/hemanth.sa/node_modules/async-lock/lib/index.js:201:4)
[AndroidUiautomator2Driver@e744 (be0312d2)]     at done (/Users/hemanth.sa/node_modules/async-lock/lib/index.js:122:29)
[AndroidUiautomator2Driver@e744 (be0312d2)]     at /Users/hemanth.sa/node_modules/async-lock/lib/index.js:174:5
[HTTP] <-- POST /session/be0312d2-5cb0-423c-90c6-bc350f0cdca5/log 500 73340 ms - 1176
[HTTP] 
[AndroidUiautomator2Driver@e744 (be0312d2)] Responding to client with driver.getLog() result: [{"timestamp":1706691495747,"level":"ALL","message":"01-31 14:16:39.173  9793 13725 E ViewRootImpl: \tat android.view.View.setContentDescription(View.java:10805)"},{"timestamp":1706691495747,"level":"ALL","message":"01-31 14:16:39.173  9793 13725 E ViewRootImpl: \tat com.google.android.libraries.inputmethod.widgets.SoftKeyView.k(PG:2)"},{"timestamp":1706691495747,"level":"ALL","message":"01-31 14:16:39.173  9793 13725 E ViewRootImpl: \tat com.google.android.libraries.inputmethod.widgets.SoftKeyView.getContentDescription(PG:1)"},{"timestamp":1706691495747,"level":"ALL","message":"01-31 14:16:39.173  9793 13725 E ViewRootImpl: \tat android.view.View.encodeProperties(View.java:30613)"},{"timestamp":1706691495747,"level":"ALL","message":"01-31 14:16:39.173  9793 13725 E ViewRootImpl: \tat android.view.ViewGroup.encodeProperties(ViewGroup.java:9235)"},{"timestamp":1706691495747,"level":"ALL","message":"01-31 14:16:39.173  9793 13725 E ViewRootImpl: \tat android.widget.FrameLayout.encodeProperties(FrameLayout.ja...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> showing Error: Webview context WEBVIEW_chrome not loaded

Where is error shown?

**Comment by hemanthsa1997** [comment]
in the terminal

**Comment by hemanthsa1997** [comment]
closed by mistake

**Comment by christian-bromann** [comment]
> in the terminal

@hemanthsa1997 the error you mention in the issue ` Webview context WEBVIEW_chrome not loaded` is no where seen above. Please provide a reproducible example too please!

**Comment by christian-bromann** [comment]
Closing due to inactivity.
