### ISSUE TITLE
[🐛 Bug]: [wdio-allure-reporter] Test execution fails with error - "There isn't any active test!"

### ISSUE THREAD

**Issue by ricalbuquerque** [webdriverio/webdriverio#12142]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.29.3

### Node.js Version

20.10.0

### Mode

WDIO Testrunner

### What happened?

Test execution is stopped with a "There isn't any active test!" error before tests are executed when configuring the allure reporter with the `useCucumberStepReporter` flag set to `true`.

### What is your expected behavior?

Test execution not stopped and allure report generated.

### How to reproduce the bug.

Git repo: https://github.com/ricalbuquerque/wdio-allure

1. Clone the repo above
2. Run `npm install`
3. Run the tests by running `npm run test:local`

### Relevant log output

```typescript
`
[chrome-headless-shell 121.0.6167.85 mac #0-0] The Internet Guinea Pig Website
[0-0] 2024-02-01T21:00:09.138Z ERROR @wdio/runner: Error: There isn't any active test!
[0-0]     at AllureReporter._startStep (file:///.../node_modules/@wdio/allure-reporter/build/reporter.js:140:19)
[0-0]     at AllureReporter.onTestStart (file:///.../node_modules/@wdio/allure-reporter/build/reporter.js:292:18)
[0-0]     at AllureReporter.<anonymous> (file:///.../node_modules/@wdio/reporter/build/index.js:100:18)
[0-0]     at AllureReporter.emit (node:events:514:28)
[0-0]     at AllureReporter.emit (node:domain:488:12)
[0-0]     at file:///.../node_modules/@wdio/runner/build/reporter.js:47:56
[0-0]     at Array.forEach (<anonymous>)
[0-0]     at BaseReporter.emit (file:///.../node_modules/@wdio/runner/build/reporter.js:47:25)
[0-0]     at CucumberFormatter.emit (file:///.../node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:96:23)
[0-0]     at CucumberFormatter.onTestCaseStarted (file:///.../node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:317:14)
[0-0]     at EventEmitter.<anonymous> (file:///.../node_modules/@wdio/cucumber-framework/build/cucumberFormatter.js:47:22)
[0-0]     at EventEmitter.emit (node:events:526:35)
[0-0]     at EventEmitter.emit (node:domain:488:12)
[0-0]     at TestCaseRunner.runAttempt (/.../node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:214:27)
[0-0]     at TestCaseRunner.run (/.../node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:188:40)
[0-0]     at Runtime.runTestCase (/.../node_modules/@cucumber/cucumber/src/runtime/index.ts:89:41)


````
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
The root cause is `scenarioLevelReporter: true`
https://github.com/ricalbuquerque/wdio-allure/blob/master/config/wdio.base.ts#L183

It breaks the normal cucumber reporter events order and break the allure and probably any similar reporter.

**Comment by ricalbuquerque** [comment]
Oh, great! Thank you!
So in this particular case, should the thrown error be a bit more explicit? If that's I'm happy to help :)

**Comment by BorisOsipov** [comment]
@ricalbuquerque The problem is in the custom `scenarioLevelReporter' wdio cucumber option which causes unexpected behaviour. It must be fixed in the wdio-cucumber adapter, but not in the allure reporter.
