### ISSUE TITLE
Stale Element error is not beight caught

### ISSUE THREAD

**Issue by qualityshepherd** [webdriverio/webdriverio#1219]
## Stale Element error is not beight caught

I'm getting a stale element when attempting to delete multiple items from a page (no refresh, items are just removed from the dom). After the first is deleted, it throws the error, kills the session, and hangs. WDIO should catch the error and retyr, but doesn't. 

I'm using page objects, if that matters. 

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: 4.2.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asnychronous tests: sync
* Additional wdio packages used (if applicable): jasmine

## Log

``` txt
10:35:54.304 INFO - Executing: [get text: 7 [[ChromeDriver: chrome on MAC (0b722a4c0d36eed5aa856fc859151ea9)] -> css selector: span.details__title-text]])
10:35:54.324 INFO - Done: [get text: 7 [[ChromeDriver: chrome on MAC (0b722a4c0d36eed5aa856fc859151ea9)] -> css selector: span.details__title-text]]
10:35:54.336 INFO - Executing: [get text: 8 [[ChromeDriver: chrome on MAC (0b722a4c0d36eed5aa856fc859151ea9)] -> css selector: span.details__title-text]])
10:35:54.358 INFO - Done: [get text: 8 [[ChromeDriver: chrome on MAC (0b722a4c0d36eed5aa856fc859151ea9)] -> css selector: span.details__title-text]]
10:35:54.380 INFO - Executing: [get text: 9 [[ChromeDriver: chrome on MAC (0b722a4c0d36eed5aa856fc859151ea9)] -> css selector: span.details__title-text]])
10:35:54.409 INFO - Done: [get text: 9 [[ChromeDriver: chrome on MAC (0b722a4c0d36eed5aa856fc859151ea9)] -> css selector: span.details__title-text]]
10:35:54.417 INFO - Executing: [get text: 10 [[ChromeDriver: chrome on MAC (0b722a4c0d36eed5aa856fc859151ea9)] -> css selector: span.details__title-text]])
10:35:54.450 INFO - Done: [get text: 10 [[ChromeDriver: chrome on MAC (0b722a4c0d36eed5aa856fc859151ea9)] -> css selector: span.details__title-text]]
10:35:54.463 INFO - Executing: [get text: 11 [[ChromeDriver: chrome on MAC (0b722a4c0d36eed5aa856fc859151ea9)] -> css selector: span.details__title-text]])
10:35:55.178 WARN - Exception thrown
org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: chrome=49.0.2623.110)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 42 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: '13.local', ip: '192.168.0.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.7.0_75'
Session ID: 0b722a4c0d36eed5aa856fc859151ea9
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/39/2gckmzs959l7x2y1rn_cp9tc0000gn/T/.org.chromium.Chromium.5Wg63U, chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.110, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:179)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:335)
	at com.sun.proxy.$Proxy2.getText(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.getText(EventFiringWebDriver.java:385)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
	at com.sun.proxy.$Proxy3.getText(Unknown Source)
	at org.openqa.selenium.remote.server.handler.GetElementText.call(GetElementText.java:30)
	at org.openqa.selenium.remote.server.handler.GetElementText.call(GetElementText.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
10:35:55.179 WARN - Exception: stale element reference: element is not attached to the page document
  (Session info: chrome=49.0.2623.110)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.3 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 42 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: '13.local', ip: '192.168.0.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.7.0_75'
Session ID: 0b722a4c0d36eed5aa856fc859151ea9
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/39/2gckmzs959l7x2y1rn_cp9tc0000gn/T/.org.chromium.Chromium.5Wg63U, chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.110, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
10:37:30.474 INFO - Executing: [delete session: 436d98a0-2f81-40b9-affe-baf181b0998c])
10:37:30.552 INFO - Done: [delete session: 436d98a0-2f81-40b9-affe-baf181b0998c]
```

## Code Snippet

```js
this.projectTitles.value.forEach(function(titleElm, index) {
    titleText = browser.elementIdText(titleElm.ELEMENT).value;
    if(titleText.match(projectNamePattern)) {
        that.deleteProject(titleText);
        //browser.pause(3333);
    }
});
```

**Comment by albadam000** [comment]
We have the same problem, it started in version 2.46.

**Comment by christian-bromann** [comment]
Without reproducible example I can't do anything here. We have tests that make sure that this feature works and they say currently so. Not sure why it not works for you. I tried it with chrome and it worked. Please reopen if you have something I can reproduce. Sorry

**Comment by sakari** [comment]
i'm encountering intermittent problems where the webdriver io starts making requests to the selenium server in a tight loop and never gets back. Possibly the same issue as described here.

It seems to happen when I do a `element` call followed by a  `elementId*` operation on a possibly stale elements and quickly navigate out of the page.

I might try to create a test case for it but it seems that `npm test` in master fails. So: 

 - is there any instructions how to make the test suite pass in mac os?
 - would it be sensible to work on the build to make it a bit easier to run the tests? like installing selenium-standalone, phantomjs using package.json and handling the startup of the selenium server in the wdio hooks
 - why take the command *before* the found `element` command as the `commandToRepeat` in https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/errorHandler.js#L29. That seems fairly suspect but maybe there is some nuance I'm missing

**Comment by CTaylor1118** [comment]
@christian-bromann I think am also seeing this problem but not 100% sure. It seems to happen the most when using getAttribute for myself though I do not have an example for 100% reproducibility.  What happens for me is that webdriverio will crash with an uncaught error but my session will still be running on the server.

I am not able to reproduce webdriverio crashing but it looks like staleElementReference error is not being rejected at all but rather resolved. Below is a simple set of steps to show the unhandled stale element reference.
````javascript
browser.init()
  .url('https://www.google.com')
        .pause(1000)
        .element('#gb')
        .then(function(res){
          elementID = res.value.ELEMENT;
          return this.execute(function(){
            var el = document.getElementById('gb');
            return el.remove();
          })
          .elementIdAttribute(elementID, 'class')// .catch(console.log)
        })
```
If I place the catch behind the elementIdAttribute, then the browser hangs but if I place then there, it works fine.  I am not sure if this is actually the same problem but everytime I see webdriverio crash, it is usually after a stale element reference.

**Comment by CTaylor1118** [comment]
@christian-bromann Seems like this is actually just that same as #1396
