### ISSUE TITLE
WaitUntil Never Waits Until The Promise Is Resolved With True

### ISSUE THREAD

**Issue by dheeraj1988** [webdriverio/webdriverio#1227]
Problem:

When we try to execute WaitUntil function, it never waits until the promise is resolved. It straight away fails with the timeout error

WebdriverIO version: 4.0.5
Node.js version: 4.2.4
Running with cucumber-boilerplate

Logs : 

[09:14:28]  COMMAND     DELETE   "/wd/hub/session/5fb57ec29f99dff7365170b494d2a242"
[09:14:28]  DATA                {}
[09:14:28]  RESULT           "text"
text
Iteration 1

     Uncaught Error: Promise was rejected with the following reason: timeout
      at new CommandError (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:109:12)
      at C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\build\lib\commands\waitUntil.js:79:15
      at run (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\node_modules\core-js\library\modules\es6.promise.js:104:47)
      at C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\node_modules\core-js\library\modules\es6.promise.js:115:28
      at flush (C:\Mobile_Appium\Cucumber_Boilerplate\node_modules\webdriverio\node_modules\core-js\library\modules\$.microtask.js:19:5)

Code :

module.exports = function (timeout, elem, expectedText, done) {
    
    this.browser.waitUntil(function(){ 
        return this.getText(elem).then(function(text) {
            i++;
            console.log(text);
            console.log("Iteration " + i);
            return text === expectedText;
        }); 
    }, timeout).call(done);
}

**Comment by christian-bromann** [comment]
Just rechecked and seems to be fixed on master.

**Comment by mandalm** [comment]
Hi All,

In my project i am using extensively this method. where i found that sometimes its working and sometime its not. I am also using dynamic test case generation using Promise. 

few info:

webdriver version: > 4.0.7
mode: sync
framework: mocha

I see this code working.
```
browser
            .waitUntil(function() {
                return this.execute(function(){ return document.readyState === 'complete'; });
            },100000,1000);
```

this is not working.
```
browser
            .waitUntil(function() {
                return this.execute(function(){ return window.seleniumScrollDown === 0; })
            },100000,1000);
```

this both piece of code is running inside ```before``` hook. I see that all before hook is quite execution almost same time.

I don't know whether you Timer is using a common scope or for each call it is a different timer value. but ultimately it is not working as expect.

My use case is:

1. it will scroll down.
2. it should wait for scroll to bottom to now checking scroll up.
3. now i am using some flag which stored on browser. 

but this is never happened.

Not working method returning ```false``` initially and then its directly stepping to next set of instruction. It is not waiting for ```true```. 

Also if you know any alternative way i can achieve the same please let me know.

Thanks for this awesome module.

**Comment by nestorneto** [comment]
same problem here. Version 4.12.0

**Comment by igor-lemon** [comment]
+1
