### ISSUE TITLE
ElementNotVisibleException with the following reproduction

### ISSUE THREAD

**Issue by eyalzek** [webdriverio/webdriverio#1232]
Getting an `ElementNotVisibleException` with the following code. It seems like maybe the multiple `addValue` calls are related, but I can't be entirely sure.

Using v4.0.5, selenium server 2.53 and node v4.4.0.
That error happened to me while running with the test runner, but can be reproduced standalone with the following snippet:
https://gist.github.com/eyalzek/5dcd649835e5c1154bf026dde84fbc9b

Attached to the gist is also the exception from the selenium server.

**Comment by christian-bromann** [comment]
Can you post some more logs from before the error happened?

**Comment by eyalzek** [comment]
10:33:23.730 INFO - Executing: [new session: Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@2494c49d, javascriptEnabled=true, browserName=chrome, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.5}, rotatable=true, locationContextEnabled=true}]])
    10:33:23.730 INFO - Creating a new session for Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@2494c49d, javascriptEnabled=true, browserName=chrome, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.5}, rotatable=true, locationContextEnabled=true}]
    Starting ChromeDriver 2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1) on port 20864
    Only local connections are allowed.
    10:33:23.969 INFO - Done: [new session: Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@2494c49d, javascriptEnabled=true, browserName=chrome, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.5}, rotatable=true, locationContextEnabled=true}]]
    10:33:23.982 INFO - Executing: [set window size])
    10:33:24.126 INFO - Done: [set window size]
    10:33:24.136 INFO - Executing: [get: https://showbox.com/workspace.html])
    10:33:29.487 INFO - Done: [get: https://showbox.com/workspace.html]
    10:33:29.493 INFO - Executing: [find elements: By.cssSelector: .login button[data-modal="signup"]])
    10:33:29.508 INFO - Done: [find elements: By.cssSelector: .login button[data-modal="signup"]]
    10:33:29.512 INFO - Executing: [find element: By.cssSelector: .login button[data-modal="signup"]])
    10:33:29.525 INFO - Done: [find element: By.cssSelector: .login button[data-modal="signup"]]
    10:33:29.529 INFO - Executing: [click: 0 [[ChromeDriver: chrome on LINUX (af406dc0445b0a1aa384a7a2b22cf45f)] -> css selector: .login button[data-modal="signup"]]])
    10:33:29.575 INFO - Done: [click: 0 [[ChromeDriver: chrome on LINUX (af406dc0445b0a1aa384a7a2b22cf45f)] -> css selector: .login button[data-modal="signup"]]]
    10:33:31.580 INFO - Executing: [find elements: By.id: fullname])
    10:33:31.602 INFO - Done: [find elements: By.id: fullname]
    10:33:31.609 INFO - Executing: [send keys: 1 [[ChromeDriver: chrome on LINUX (af406dc0445b0a1aa384a7a2b22cf45f)] -> id: fullname], [S, h, o, w, b, o, x,  , U, s, e, r]])
    10:33:31.665 INFO - Done: [send keys: 1 [[ChromeDriver: chrome on LINUX (af406dc0445b0a1aa384a7a2b22cf45f)] -> id: fullname], [S, h, o, w, b, o, x,  , U, s, e, r]]
    10:33:31.668 INFO - Executing: [find elements: By.id: email])
    10:33:31.689 INFO - Done: [find elements: By.id: email]
    10:33:31.697 INFO - Executing: [send keys: 2 [[ChromeDriver: chrome on LINUX (af406dc0445b0a1aa384a7a2b22cf45f)] -> id: email], [e, x, a, m, p, l, e, @, e, x, a, m, p, l, e, ., c, o, m]])
    10:33:31.697 INFO - Executing: [send keys: 3 [[ChromeDriver: chrome on LINUX (af406dc0445b0a1aa384a7a2b22cf45f)] -> id: email], [e, x, a, m, p, l, e, @, e, x, a, m, p, l, e, ., c, o, m]])
    10:33:31.697 INFO - Executing: [send keys: 4 [[ChromeDriver: chrome on LINUX (af406dc0445b0a1aa384a7a2b22cf45f)] -> id: email], [e, x, a, m, p, l, e, @, e, x, a, m, p, l, e, ., c, o, m]])
    10:33:31.746 INFO - Done: [send keys: 2 [[ChromeDriver: chrome on LINUX (af406dc0445b0a1aa384a7a2b22cf45f)] -> id: email], [e, x, a, m, p, l, e, @, e, x, a, m, p, l, e, ., c, o, m]]
    10:33:32.360 WARN - Exception thrown
    org.openqa.selenium.ElementNotVisibleException: element not visible
      (Session info: chrome=49.0.2623.110)
      (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-85-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 22 milliseconds
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'eyal-xubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-85-generic', java.version: '1.7.0_95'
    Session ID: af406dc0445b0a1aa384a7a2b22cf45f
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.emhK7S}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.110, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
        at sun.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
        at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:122)
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:335)
        at com.sun.proxy.$Proxy2.sendKeys(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.sendKeys(EventFiringWebDriver.java:358)
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
        at com.sun.proxy.$Proxy3.sendKeys(Unknown Source)
        at org.openqa.selenium.remote.server.handler.SendKeys.call(SendKeys.java:50)
        at org.openqa.selenium.remote.server.handler.SendKeys.call(SendKeys.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    10:33:32.361 WARN - Exception: element not visible
      (Session info: chrome=49.0.2623.110)
      (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-85-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 22 milliseconds
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'eyal-xubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-85-generic', java.version: '1.7.0_95'
    Session ID: af406dc0445b0a1aa384a7a2b22cf45f
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.emhK7S}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.110, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
    10:33:32.981 WARN - Exception thrown
    org.openqa.selenium.ElementNotVisibleException: element not visible
      (Session info: chrome=49.0.2623.110)
      (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-85-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 24 milliseconds
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'eyal-xubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-85-generic', java.version: '1.7.0_95'
    Session ID: af406dc0445b0a1aa384a7a2b22cf45f
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.emhK7S}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.110, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
        at sun.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
        at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:122)
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:335)
        at com.sun.proxy.$Proxy2.sendKeys(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.sendKeys(EventFiringWebDriver.java:358)
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
        at com.sun.proxy.$Proxy3.sendKeys(Unknown Source)
        at org.openqa.selenium.remote.server.handler.SendKeys.call(SendKeys.java:50)
        at org.openqa.selenium.remote.server.handler.SendKeys.call(SendKeys.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    10:33:32.981 WARN - Exception: element not visible
      (Session info: chrome=49.0.2623.110)
      (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-85-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 24 milliseconds
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'eyal-xubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-85-generic', java.version: '1.7.0_95'
    Session ID: af406dc0445b0a1aa384a7a2b22cf45f
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.emhK7S}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.110, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]

**Comment by christian-bromann** [comment]
@eyalzek it seems that it fails due to [this](https://gist.github.com/eyalzek/5dcd649835e5c1154bf026dde84fbc9b#file-example-js-L13) line. `#email` exists 3 times on the page and by adding keys to the second element it fails because the element is not visible. Make sure your selector doesn't match with not visible elements.

**Comment by christian-bromann** [comment]
proof:
![screen shot 2016-04-08 at 10 50 35](https://cloud.githubusercontent.com/assets/731337/14378893/c707f80e-fd77-11e5-80a5-105471b449f8.png)

**Comment by eyalzek** [comment]
That's the first thing I tested, I made the selector more specific, it didn't work. If I comment that line out the same thing still happens.

**Comment by eyalzek** [comment]
Output when the email part is commented out:

    10:50:10.091 INFO - Executing: [new session: Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@5189b8b, javascriptEnabled=true, browserName=chrome, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.5}, rotatable=true, locationContextEnabled=true}]])
    10:50:10.092 INFO - Creating a new session for Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@5189b8b, javascriptEnabled=true, browserName=chrome, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.5}, rotatable=true, locationContextEnabled=true}]
    Starting ChromeDriver 2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1) on port 32208
    Only local connections are allowed.
    10:50:10.363 INFO - Done: [new session: Capabilities [{loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@5189b8b, javascriptEnabled=true, browserName=chrome, handlesAlerts=true, requestOrigins={name=webdriverio, url=http://webdriver.io, version=4.0.5}, rotatable=true, locationContextEnabled=true}]]
    10:50:10.379 INFO - Executing: [set window size])
    10:50:10.522 INFO - Done: [set window size]
    10:50:10.531 INFO - Executing: [get: https://showbox.com/workspace.html])
    10:50:17.026 INFO - Done: [get: https://showbox.com/workspace.html]
    10:50:17.035 INFO - Executing: [find elements: By.cssSelector: .login button[data-modal="signup"]])
    10:50:17.051 INFO - Done: [find elements: By.cssSelector: .login button[data-modal="signup"]]
    10:50:17.056 INFO - Executing: [find element: By.cssSelector: .login button[data-modal="signup"]])
    10:50:17.071 INFO - Done: [find element: By.cssSelector: .login button[data-modal="signup"]]
    10:50:17.077 INFO - Executing: [click: 0 [[ChromeDriver: chrome on LINUX (13f1a59ffae8c42ee0bc92e4592dbfd3)] -> css selector: .login button[data-modal="signup"]]])
    10:50:17.120 INFO - Done: [click: 0 [[ChromeDriver: chrome on LINUX (13f1a59ffae8c42ee0bc92e4592dbfd3)] -> css selector: .login button[data-modal="signup"]]]
    10:50:19.129 INFO - Executing: [find elements: By.id: fullname])
    10:50:19.150 INFO - Done: [find elements: By.id: fullname]
    10:50:19.159 INFO - Executing: [send keys: 1 [[ChromeDriver: chrome on LINUX (13f1a59ffae8c42ee0bc92e4592dbfd3)] -> id: fullname], [S, h, o, w, b, o, x,  , U, s, e, r]])
    10:50:19.210 INFO - Done: [send keys: 1 [[ChromeDriver: chrome on LINUX (13f1a59ffae8c42ee0bc92e4592dbfd3)] -> id: fullname], [S, h, o, w, b, o, x,  , U, s, e, r]]
    10:50:19.214 INFO - Executing: [find elements: By.id: password])
    10:50:19.235 INFO - Done: [find elements: By.id: password]
    10:50:19.241 INFO - Executing: [send keys: 2 [[ChromeDriver: chrome on LINUX (13f1a59ffae8c42ee0bc92e4592dbfd3)] -> id: password], [t, e, s, t, 1, 2, 3, 4]])
    10:50:19.241 INFO - Executing: [send keys: 3 [[ChromeDriver: chrome on LINUX (13f1a59ffae8c42ee0bc92e4592dbfd3)] -> id: password], [t, e, s, t, 1, 2, 3, 4]])
    10:50:19.290 INFO - Done: [send keys: 2 [[ChromeDriver: chrome on LINUX (13f1a59ffae8c42ee0bc92e4592dbfd3)] -> id: password], [t, e, s, t, 1, 2, 3, 4]]
    10:50:19.937 WARN - Exception thrown
    org.openqa.selenium.ElementNotVisibleException: element not visible
      (Session info: chrome=49.0.2623.110)
      (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-85-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 28 milliseconds
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'eyal-xubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-85-generic', java.version: '1.7.0_95'
    Session ID: 13f1a59ffae8c42ee0bc92e4592dbfd3
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.iVicUa}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.110, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
        at sun.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
        at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:122)
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:335)
        at com.sun.proxy.$Proxy2.sendKeys(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.sendKeys(EventFiringWebDriver.java:358)
        at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
        at com.sun.proxy.$Proxy3.sendKeys(Unknown Source)
        at org.openqa.selenium.remote.server.handler.SendKeys.call(SendKeys.java:50)
        at org.openqa.selenium.remote.server.handler.SendKeys.call(SendKeys.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    10:50:19.937 WARN - Exception: element not visible
      (Session info: chrome=49.0.2623.110)
      (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-85-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 28 milliseconds
    Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
    System info: host: 'eyal-xubuntu', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-85-generic', java.version: '1.7.0_95'
    Session ID: 13f1a59ffae8c42ee0bc92e4592dbfd3
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.iVicUa}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=49.0.2623.110, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
    Vector smash protection is enabled.

**Comment by christian-bromann** [comment]
yep, password also exists 3 times, it's all in the logs
```

10:50:19.214 INFO - Executing: [find elements: By.id: password])
10:50:19.235 INFO - Done: [find elements: By.id: password]
10:50:19.241 INFO - Executing: [send keys: 2 [[ChromeDriver: chrome on LINUX (13f1a59ffae8c42ee0bc92e4592dbfd3)] -> id: password], [t, e, s, t, 1, 2, 3, 4]])
10:50:19.241 INFO - Executing: [send keys: 3 [[ChromeDriver: chrome on LINUX (13f1a59ffae8c42ee0bc92e4592dbfd3)] -> id: password], [t, e, s, t, 1, 2, 3, 4]])
10:50:19.290 INFO - Done: [send keys: 2 [[ChromeDriver: chrome on LINUX (13f1a59ffae8c42ee0bc92e4592dbfd3)] -> id: password], [t, e, s, t, 1, 2, 3, 4]]
10:50:19.937 WARN - Exception thrown
org.openqa.selenium.ElementNotVisibleException: element not visible
```

**Comment by eyalzek** [comment]
You are indeed correct, thanks :+1:
