### ISSUE TITLE
[🐛 Bug]: Failed to use reverse property in waitForDisplayed for Android mobile tests

### ISSUE THREAD

**Issue by QuintilianoNery** [webdriverio/webdriverio#12326]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.6.7

### Node.js Version

16.16.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
config.capabilities = [{
  build: process.env.BROWSERSTACK_BUILD_NAME,
  projectName: 'Automated test',
  name: 'UIAutomator2',
  deviceName: "Samsung Galaxy S21",
  platformVersion: "12.0",
  platformName: 'android',
  autoGrantPermissions: true,
  fullReset: true,
  language: 'es',
  locale: 'AR',
  interactiveDebugging: true
}]
```

### What happened?

When using the reverse function in waitForDisplayed, the test is identifying that the element is still visible, even though it is not displayed in Appium Inspactor
await $(element.baseLoading).waitForDisplayed({ timeout: 7000, reverse: true });

### What is your expected behavior?

When performing the test run with Webdriverio, using an Android device in browserstack, I tried to perform validation so that after the loading element disappeared from the screen, it was possible to click on the image of the page that was being loaded.

I used it as suggested in the documentation, I used the reverse property of waitForDisplayed. However, after passing the indicated timeout, an error was displayed in the execution log, stating that the element was visible after the indicated time.

When observing in Appium Inspactor, I noticed that the loading element was not really visible to be inspected.

![image](https://github.com/webdriverio/webdriverio/assets/48323097/e66d7f3f-f6d4-4fbb-8822-442978f17a26)
![image](https://github.com/webdriverio/webdriverio/assets/48323097/d4af8d5d-cce7-4a9f-aebb-36d376db7a33)

### How to reproduce the bug.

When running a test on a device in browserstack, using webdriverio, to evaluate elements on the screen of a mobile device, when I use the await function $(element.baseLoading).waitForDisplayed({ timeout: 7000, reverse: true });

so that you wait until the loading element is not visible, and then click on the image, but when you reach this point, an error is displayed, informing you that the element is visible after the timeout

element ("android=new UiSelector().resourceIdMatches(".*:id/loading")") still displayed after 7000ms

### Relevant log output

```typescript
[0-0] 2024-02-20T17:59:43.310Z INFO webdriver: COMMAND findElement("-android uiautomator", "new UiSelector().resourceIdMatches(".*:id/loading")")
[0-0] 2024-02-20T17:59:43.311Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/element
[0-0] 2024-02-20T17:59:43.311Z INFO webdriver: DATA {
[0-0]   using: '-android uiautomator',
[0-0]   value: 'new UiSelector().resourceIdMatches(".*:id/loading")'
[0-0] }
[0-0] 2024-02-20T17:59:43.642Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '479e1a6c-c66d-46ee-8697-164717f18871',
[0-0]   ELEMENT: '479e1a6c-c66d-46ee-8697-164717f18871',
[0-0]   sessionId: '8f75aab4165e4a038cd3c2282d06bb4a436e6196',
[0-0]   capabilities: {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '479e1a6c-c66d-46ee-8697-164717f18871',
[0-0]     ELEMENT: '479e1a6c-c66d-46ee-8697-164717f18871',
[0-0]     sessionId: '8f75aab4165e4a038cd3c2282d06bb4a436e6196'
[0-0]   }
[0-0] }
[0-0] 2024-02-20T17:59:43.652Z INFO webdriver: COMMAND isElementDisplayed("479e1a6c-c66d-46ee-8697-164717f18871")
[0-0] 2024-02-20T17:59:43.652Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/element/479e1a6c-c66d-46ee-8697-164717f18871/displayed
[0-0] 2024-02-20T17:59:44.258Z INFO webdriver: RESULT true
[0-0] 2024-02-20T17:59:44.270Z INFO webdriver: COMMAND isElementDisplayed("479e1a6c-c66d-46ee-8697-164717f18871")
[0-0] 2024-02-20T17:59:44.270Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/element/479e1a6c-c66d-46ee-8697-164717f18871/displayed
[0-0] 2024-02-20T17:59:44.575Z INFO webdriver: RESULT true
[0-0] 2024-02-20T17:59:44.674Z INFO webdriver: COMMAND isElementDisplayed("479e1a6c-c66d-46ee-8697-164717f18871")
[0-0] 2024-02-20T17:59:44.678Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/element/479e1a6c-c66d-46ee-8697-164717f18871/displayed
[0-0] 2024-02-20T17:59:45.324Z INFO webdriver: RESULT true
[0-0] 2024-02-20T17:59:45.333Z INFO webdriver: COMMAND isElementDisplayed("479e1a6c-c66d-46ee-8697-164717f18871")
[0-0] 2024-02-20T17:59:45.334Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/element/479e1a6c-c66d-46ee-8697-164717f18871/displayed
[0-0] 2024-02-20T17:59:45.878Z INFO webdriver: RESULT true
[0-0] 2024-02-20T17:59:45.889Z INFO webdriver: COMMAND isElementDisplayed("479e1a6c-c66d-46ee-8697-164717f18871")
[0-0] 2024-02-20T17:59:45.890Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/element/479e1a6c-c66d-46ee-8697-164717f18871/displayed
[0-0] 2024-02-20T17:59:46.209Z INFO webdriver: RESULT true
[0-0] 2024-02-20T17:59:46.215Z INFO webdriver: COMMAND isElementDisplayed("479e1a6c-c66d-46ee-8697-164717f18871")
[0-0] 2024-02-20T17:59:46.217Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/element/479e1a6c-c66d-46ee-8697-164717f18871/displayed
[0-0] 2024-02-20T17:59:46.527Z INFO webdriver: RESULT true
[0-0] 2024-02-20T17:59:46.664Z INFO webdriver: COMMAND isElementDisplayed("479e1a6c-c66d-46ee-8697-164717f18871")
[0-0] 2024-02-20T17:59:46.666Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/element/479e1a6c-c66d-46ee-8697-164717f18871/displayed
[0-0] Error in "Gerenciamento da sacola de compras.Adicionar produto à sacola via lista de produtos"
Error: element ("android=new UiSelector().resourceIdMatches(".*:id/loading")") still displayed after 7000ms
    at async Context.<anonymous> (C:\teste\project\tests\specs\android\manageBag.js:82:9)
[0-0] 2024-02-20T17:59:50.675Z INFO webdriver: COMMAND closeApp()
[0-0] 2024-02-20T17:59:50.676Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/appium/app/close
[0-0] 2024-02-20T18:00:41.687Z WARN webdriver: Request failed with status 500 due to The element 'By.AndroidUiAutomator: new UiSelector().resourceIdMatches(".*:id/loading")' does not exist in DOM anymore
[0-0] 2024-02-20T18:00:41.687Z INFO webdriver: Retrying 1/3
[0-0] 2024-02-20T18:00:41.687Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/element/479e1a6c-c66d-46ee-8697-164717f18871/displayed
[0-0] 2024-02-20T18:00:51.017Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2024-02-20T18:00:51.017Z INFO webdriver: Retrying 1/3
[0-0] 2024-02-20T18:00:51.018Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/appium/app/close
[0-0] 2024-02-20T18:00:53.711Z INFO webdriver: RESULT null
[0-0] 2024-02-20T18:00:53.715Z INFO @wdio/browserstack-service: Update job with sessionId 8f75aab4165e4a038cd3c2282d06bb4a436e6196
[0-0] 2024-02-20T18:00:54.833Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-02-20T18:00:54.833Z INFO webdriver: [DELETE] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196
[0-0] 2024-02-20T18:00:55.530Z INFO webdriver: RESULT 
[0-0] FAILED in bs://b233ccba27e68fe260d686e6e9886231415093ab - file:///C:\teste\project\tests\specs\android\manageBag.js
2024-02-20T18:00:55.689Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-02-20T18:00:55.690Z INFO @wdio/cli:launcher: Run onComplete hook

Visit https://observability.browserstack.com/builds/rf7xeuj5hwn5nfeiftopk3ewr8puvpihbt5ksoox to view build report, insights, and many more debugging information all at one place!


 "spec" Reporter:
------------------------------------------------------------------
[R5CRA016NDR Android 12 #0-0] Running: R5CRA016NDR on Android 12
[R5CRA016NDR Android 12 #0-0] Session ID: 8f75aab4165e4a038cd3c2282d06bb4a436e6196
[R5CRA016NDR Android 12 #0-0]
[R5CRA016NDR Android 12 #0-0] » \tests\specs\android\manageBag.js
[R5CRA016NDR Android 12 #0-0] Gerenciamento da sacola de compras
[R5CRA016NDR Android 12 #0-0]    ✖ Adicionar produto à sacola via lista de produtos
[R5CRA016NDR Android 12 #0-0]
[R5CRA016NDR Android 12 #0-0] 1 failing (1m 54.9s)
[R5CRA016NDR Android 12 #0-0]
[R5CRA016NDR Android 12 #0-0] 1) Gerenciamento da sacola de compras Adicionar produto à sacola via lista de produtos
[R5CRA016NDR Android 12 #0-0] element ("android=new UiSelector().resourceIdMatches(".*:id/loading")") still displayed after 7000ms
[R5CRA016NDR Android 12 #0-0] Error: element ("android=new UiSelector().resourceIdMatches(".*:id/loading")") still displayed after 7000ms
[R5CRA016NDR Android 12 #0-0]     at async Context.<anonymous> (C:\teste\project\tests\specs\android\manageBag.js:82:9)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:02:31

2024-02-20T18:00:56.325Z INFO @wdio/local-runner: Shutting down spawned worker
2024-02-20T18:00:56.580Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-02-20T18:00:56.581Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ```ts
> [0-0] 2024-02-20T17:59:46.215Z INFO webdriver: COMMAND isElementDisplayed("479e1a6c-c66d-46ee-8697-164717f18871")
> [0-0] 2024-02-20T17:59:46.217Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/8f75aab4165e4a038cd3c2282d06bb4a436e6196/element/479e1a6c-c66d-46ee-8697-164717f18871/displayed
> [0-0] 2024-02-20T17:59:46.527Z INFO webdriver: RESULT true
> ```

As you can see in the logs, the displayed check shows that the element is still visible until the timeout was reached. WebdriverIO has to rely on the information provided by the command result. I suggest to reach out to BrowserStack support to find out why the WebDriver call doesn't match with what you see in the video or recording.

Happy to answer further questions but will go ahead and close the issue.
