### ISSUE TITLE
Can't import ConfigParser after upgrade to V8

### ISSUE THREAD

**Issue by Linda815** [webdriverio/webdriverio#12401]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.32.2

### Node.js Version

18.14.0

### Mode

Standalone Mode

### What happened?

Previously, we use the **ConfigParser** to parse the feature tags to do some customization before we execute all the tests.
In V7, it is imported as 
import { ConfigParser } from '@wdio/config';

After upgrade to V8, we change the import as 
import { ConfigParser } from '@wdio/config/node';

However, below error occurred:

```
node:internal/modules/cjs/loader:544
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node' is not defined by "exports" in /xxxxxx/node_modules/@wdio/config/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1033:27)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/xxxx.js:11:13) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### What is your expected behavior?

ConfigParser can be imported 

### How to reproduce the bug.

Create test.js as below:
```
var ConfigParser = require('@wdio/config/node')

function loadFeatureTags(config) {
    let configParser = new ConfigParser();
    configParser.getSpecs();
}

loadFeatureTags();
```

### Relevant log output

```typescript
node src/test.js
node:internal/modules/cjs/loader:544
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node' is not defined by "exports" in /***/node_modules/@wdio/config/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1033:27)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (test.js:2:20) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Linda815** [comment]
> Are you sure you are using latest version of `@wdio/config`? Can you provide a minimal reproducible example?

Please check the test in [git@github.com:Linda815/webdriverio-v8-test.git](https://github.com/Linda815/webdriverio-v8-test) with following commands:
```
npm install
node lib/test.js
```


And below error occurs:
```
node:internal/modules/cjs/loader:544
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node' is not defined by "exports" in /Users/i065037/Documents/Innovation/webdriverio-v8-test/node_modules/@wdio/config/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:13)
    at resolveExports (node:internal/modules/cjs/loader:538:36)
    at Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1033:27)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/i065037/Documents/Innovation/webdriverio-v8-test/lib/test.js:3:13) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.14.0
```
It seems that in V8, **import { ConfigParser } from '@wdio/config/node'** is supported,
but the **var ConfigParser = require("@wdio/config/node")** is not supported

**Comment by christian-bromann** [comment]
As mentioned in our release blog post: https://webdriver.io/blog/2022/12/01/webdriverio-v8-released in v8 we moved to ESM which can't be imported in CJS projects. If you add a `package.json` in `/src` with the following content:
```json
{
    "type": "module"
}
```
the import works. I will go ahead and close this as it is not an issue in WebdriverIO.
