### ISSUE TITLE
[🐛 Bug]: <After running the wdio v 7.20 in selenium grid v 0.20.1 (as a services) we are getting ERROR webdriver: Request failed with status 401 due to Error: Response has empty body, ERROR webdriver: Error: Response has empty body, ERROR @wdio/runner: Error: Failed to create session. [0-7] Make sure to connect to valid hostname:port or the port is not in use. If you use a grid server  [0-7] Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities. [0-7] See more https://www.w3.org/TR/webdriver/#capabilities> 

### ISSUE THREAD

**Issue by LCROZO** [webdriverio/webdriverio#12427]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.20

### Node.js Version

18.17.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
        {
            // Set maxInstances to 1 if screen recordings are enabled:
            maxInstances: parseInt(process.env.MAX_INSTANCES),
            browserName: 'chrome',
            browserVersion:'116',
            platformName: 'ANY',
            acceptInsecureCerts : true,
            pageLoadStrategy : 'eager',
            //strictFileInteractability: false,
            'goog:chromeOptions': {
                excludeSwitches: ['enable-logging'],
                args: [
                '--no-sandbox',
                '--disable-infobars',
                '--disable-gpu',
                '--start-maximized',
                '--disable-dev-shm-usage'
                ],
                prefs: {
                    download: {
                        'prompt_for_download': false,
                        'directory_upgrade': true,
                        'default_directory': `${process.env.BROWSER_DOWNLOAD}session${Date.now()}`
                    },
                    'profile.default_content_setting_values.automatic_downloads': 1
                }
            }
        }
    ]
```

### What happened?

When we are running wdio remote in a kubernetes container using selenium grid v 0.20.1, we are using the suggested PORT and HOSTNAME, with the previous version of selenium grid the execution was corrected.  we getting following error: 
Execution of 17 workers started at 2024-03-01T16:38:53.277Z

```
[0-7] RUNNING in chrome - /functional-testing/features/login_logout.feature
[0-7] 2024-03-01T16:39:11.410Z ERROR webdriver: Request failed with status 401 due to Error: Response has empty body
[0-7] 2024-03-01T16:39:11.412Z ERROR webdriver: Error: Response has empty body
[0-7]     at getErrorFromResponseBody (/app/node_modules/@wdio/runner/node_modules/webdriver/build/utils.js:190:16)
[0-7]     at NodeJSRequest._request (/app/node_modules/@wdio/runner/node_modules/webdriver/build/request/index.js:166:60)
[0-7]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-7]     at async startWebDriverSession (/app/node_modules/@wdio/runner/node_modules/webdriver/build/utils.js:68:20)
[0-7]     at async Function.newSession (/app/node_modules/@wdio/runner/node_modules/webdriver/build/index.js:46:45)
[0-7]     at async remote (/app/node_modules/@wdio/runner/node_modules/webdriverio/build/index.js:77:22)
[0-7]     at async Runner._startSession (/app/node_modules/@wdio/runner/build/index.js:223:56)
[0-7]     at async Runner._initSession (/app/node_modules/@wdio/runner/build/index.js:176:25)
[0-7]     at async Runner.run (/app/node_modules/@wdio/runner/build/index.js:88:19)
[0-7] 2024-03-01T16:39:11.414Z ERROR @wdio/runner: Error: Failed to create session.
[0-7] Make sure to connect to valid hostname:port or the port is not in use.
[0-7] If you use a grid server 
[0-7] Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities.
```

### What is your expected behavior?

The test should usually be running on selenium grid. 

### How to reproduce the bug.

To reproduce the bug you can do it with any test, and you need the following capabilities 

   ```
 capabilities: [
        {
            // Set maxInstances to 1 if screen recordings are enabled:
            maxInstances: parseInt(process.env.MAX_INSTANCES),
            browserName: 'chrome',
            browserVersion:'116',
            platformName: 'ANY',
            acceptInsecureCerts : true,
            pageLoadStrategy : 'eager',
            //strictFileInteractability: false,
            'goog:chromeOptions': {
                excludeSwitches: ['enable-logging'],
                args: [
                '--no-sandbox',
                '--disable-infobars',
                '--disable-gpu',
                '--start-maximized',
                '--disable-dev-shm-usage'
                ],
                prefs: {
                    download: {
                        'prompt_for_download': false,
                        'directory_upgrade': true,
                        'default_directory': `${process.env.BROWSER_DOWNLOAD}session${Date.now()}`
                    },
                    'profile.default_content_setting_values.automatic_downloads': 1
                }
            }
        }
    ]
```
and also use the selenium grid version 0.20.1 https://github.com/SeleniumHQ/docker-selenium/releases/tag/selenium-grid-0.20.1

### Relevant log output

```typescript
Execution of 17 workers started at 2024-03-01T16:38:53.277Z

[0-7] RUNNING in chrome - /functional-testing/features/login_logout.feature
[0-7] 2024-03-01T16:39:11.410Z ERROR webdriver: Request failed with status 401 due to Error: Response has empty body
[0-7] 2024-03-01T16:39:11.412Z ERROR webdriver: Error: Response has empty body
[0-7]     at getErrorFromResponseBody (/app/node_modules/@wdio/runner/node_modules/webdriver/build/utils.js:190:16)
[0-7]     at NodeJSRequest._request (/app/node_modules/@wdio/runner/node_modules/webdriver/build/request/index.js:166:60)
[0-7]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-7]     at async startWebDriverSession (/app/node_modules/@wdio/runner/node_modules/webdriver/build/utils.js:68:20)
[0-7]     at async Function.newSession (/app/node_modules/@wdio/runner/node_modules/webdriver/build/index.js:46:45)
[0-7]     at async remote (/app/node_modules/@wdio/runner/node_modules/webdriverio/build/index.js:77:22)
[0-7]     at async Runner._startSession (/app/node_modules/@wdio/runner/build/index.js:223:56)
[0-7]     at async Runner._initSession (/app/node_modules/@wdio/runner/build/index.js:176:25)
[0-7]     at async Runner.run (/app/node_modules/@wdio/runner/build/index.js:88:19)
[0-7] 2024-03-01T16:39:11.414Z ERROR @wdio/runner: Error: Failed to create session.
[0-7] Make sure to connect to valid hostname:port or the port is not in use.
[0-7] If you use a grid server 
[0-7] Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@LCROZO can you provide a minimal reproducible example for this. I don't really think this is an issue directly with WebdriverIO and rather with the setup you have.
