### ISSUE TITLE
[📖 Docs]: How to configure tests using Chromium (NOT Chrome) browser

### ISSUE THREAD

**Issue by rbruckheimer** [webdriverio/webdriverio#12500]
### Pre-check

- [X] I know I can edit the docs but prefer to file this issue

### Describe the improvement

Missing documentation

### Description of the improvement / report

I cannot find anywhere how to get webdriverIO v8+ to work with Chromium (NOT Chrome) browser.  I am using Ubuntu 20 on aarch64 platform and Chrome does not exist for this platform, so I need to use Chromium.  Pointing to chromium driver does not work, I get error about sessionID not created b/c Chrome is not running.  Not pointing to chromium driver causes error connection refused.  Please help by documenting how to get webdriverIO to work with Chromium.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
@rbruckheimer thanks for raising the issue, have you tried to set `browserName: "chromium"`?

**Comment by rbruckheimer** [comment]
Thanks, that helped.  Note it's not documented here as an option:
https://webdriver.io/docs/configuration/#capabilities
Also, That's not the only change required.  I think webdriverIO cannot fetch the driver itself and so I need to tell the config where to find it and to use that:
```
		browserName: "chromium",
		"wdio:chromedriverOptions": {
			binary: "./node_modules/chromedriver/lib/chromedriver/chromedriver"
		},
```
Is it expected that I should have to do that; that it should fail trying to get the chromium driver?  Without the chromeDriverOptions I get this error on run:
[0-0] 2024-03-18T02:37:08.745Z ERROR webdriver: RequestError: connect ECONNREFUSED 0.0.0.0:33147
[0-0]     at ClientRequest.<anonymous> (file:///home/notroot/git/stx/tests/e2e-v2/node_modules/got/dist/source/core/index.js:790:107)
[0-0]     at Object.onceWrapper (node:events:628:26)
[0-0]     at ClientRequest.emit (node:events:525:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:494:9)
[0-0]     at Socket.emit (node:events:513:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
[0-0] 2024-03-18T02:37:08.746Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://0.0.0.0:33147/", make sure browser driver is running on that address.
[0-0] It seems like the service failed to start or is rejecting any connections.
[0-0]     at startWebDriverSession (file:///home/notroot/git/stx/tests/e2e-v2/node_modules/webdriver/build/utils.js:69:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at Function.newSession (file:///home/notroot/git/stx/tests/e2e-v2/node_modules/webdriver/build/index.js:20:45)
[0-0]     at remote (file:///home/notroot/git/stx/tests/e2e-v2/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at Runner._startSession (file:///home/notroot/git/stx/tests/e2e-v2/node_modules/@wdio/runner/build/index.js:241:29)
[0-0]     at Runner._initSession (file:///home/notroot/git/stx/tests/e2e-v2/node_modules/@wdio/runner/build/index.js:207:25)
[0-0]     at Runner.run (file:///home/notroot/git/stx/tests/e2e-v2/node_modules/@wdio/runner/build/index.js:88:19)

**Comment by christian-bromann** [comment]
> Is it expected that I should have to do that; that it should fail trying to get the chromium driver?

It should be capable to find the Chromedriver to automate Chromium

**Comment by christian-bromann** [comment]
Let's update the docs and ensure it is clear that folks can also use Chromium.

**Comment by M-Hammad-Faisal** [comment]
@christian-bromann @rbruckheimer I believe it is mentioned in [Driver Binaries > Customizing the level of automation > Step 2](https://webdriver.io/docs/driverbinaries#customizing-the-level-of-automation)

``` javascript
{
    capabilities: [
        {
            browserName: 'chrome', // or 'firefox', 'msedge', 'safari', 'chromium'
            'wdio:chromedriverOptions': { // or 'wdio:geckodriverOptions', 'wdio:edgedriverOptions'
                binary: '/path/to/chromedriver' // or 'geckodriver', 'msedgedriver'
            }
        }
    ]
}
```

**Comment by christian-bromann** [comment]
@M-Hammad-Faisal how about we add it [here](https://webdriver.io/docs/capabilities) to, e.g.:

```
browserName: 'chrome', // or 'chromium'
```

Whereever we have the Chrome code examples, wdyt?

**Comment by M-Hammad-Faisal** [comment]
Yeah, Great Idea. Adding `browserName: 'chrome' // or 'chromium'` to our Chrome examples would make things clearer for everyone.

**Comment by christian-bromann** [comment]
@M-Hammad-Faisal would you like to take a stab at it?

**Comment by M-Hammad-Faisal** [comment]
Sure, count me in.

**Comment by M-Hammad-Faisal** [comment]
So, i just need to update the chrome examples wherever in Docs. Right?

If yes, go ahead and assign me this one.

**Comment by M-Hammad-Faisal** [comment]
@christian-bromann this issue can be closed.

**Comment by christian-bromann** [comment]
Thanks @M-Hammad-Faisal 🎉
