### ISSUE TITLE
[🐛 Bug]: Rerun failed tests broken on circleCI with wdio 8

### ISSUE THREAD

**Issue by tnt-Lirim** [webdriverio/webdriverio#12551]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### What happened?

Description:
When using the “Rerun failed tests” feature in CircleCI with our WebdriverIO v8 test framework, the rerun command is not correctly handling the file paths of the failed tests. The expected behavior is to grab and rerun only the feature files that contain failed tests. However, instead of getting and passing only the name of the failed feature file (test.feature), it is getting the name of the file with the prefixed URI ‘file://’ in front (file://test.feature). This leads to an incorrect path and causes the rerun to fail.
“Error: spec file(s) /Users/distiller/project/app/e2e/file:/features/file.feature not found”

We are triggering our test from CircleCI config with this command

"circleci tests glob "./features/**/*.feature" | circleci tests run --command="yarn run test:circleci" --verbose"

and command for test:circleci "(node config/generate.config.js circleci-e2e) && xargs wdio run ./features/wdio.conf.ts --spec"

After triggering the test with a list of feature files, WDIO adds the file:// prefix to them like this

Execution of 5 workers started at 2024-02-27T14:57:48.993Z

Continue...
[0-0] RUNNING in iOS - file:///features/articles.feature
[0-0] PASSED in iOS - file:///features/articles.feature
[0-1] RUNNING in iOS - file:///features/deleteAccount.feature
[0-1] PASSED in iOS - file:///features/deleteAccount.feature
[0-2] RUNNING in iOS - file:///features/mfaElevatedChallenge.feature
...

and then if a test failed in file:///features/articles.feature after rerunning failed test the prefix 'file:///' is added in the middle like this Received: /Users/distiller/project/app/e2e/file:/features/articles.feature

Can someone look into this

### What is your expected behavior?

When rerunning failed tests file:// prefix should be appended in the beginning of file path

### How to reproduce the bug.

Run cucumber wdio 8 tests in circleCI and select rerun failed tests feature

### Relevant log output

```typescript
Running e2e Tests
Installing circleci-tests-plugin-cli plugin.
circleci-tests-plugin-cli plugin Installed. Version: 1.0.7332-dfcf8a1
INFO[2024-03-25T00:44:47Z] received failed tests from workflow [id]
INFO[2024-03-25T00:44:47Z] 1 test(s) failed out of 2 total tests. Rerunning tests from 1 file 
DEBU[2024-03-25T00:44:47Z] if all tests are being run instead of only failed tests, ensure your JUnit XML has a file or classname attribute. 
DEBU[2024-03-25T00:44:47Z] starting execution                           
DEBU[2024-03-25T00:44:47Z] Received: file://./features/content-item/content-item-view/ppt-export.feature 
yarn run v1.22.19
$ (node config/generate.config.js circleci-e2e) && xargs wdio run ./features/wdio.conf.ts --spec
app config:circleci-e2e
Error: spec file(s) /home/circleci/project/frontend/file:/features/content-item/content-item-view/ppt-export.feature not found
    at ConfigParser.setFilePathToFilterOptions (file:///home/circleci/project/frontend/node_modules/@wdio/config/build/node/ConfigParser.js:322:19)
    at ConfigParser.merge (file:///home/circleci/project/frontend/node_modules/@wdio/config/build/node/ConfigParser.js:168:39)
    at ConfigParser.initialize (file:///home/circleci/project/frontend/node_modules/@wdio/config/build/node/ConfigParser.js:50:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Launcher.run (file:///home/circleci/project/frontend/node_modules/@wdio/cli/build/launcher.js:41:9)
error Command failed with exit code 123.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@tnt-Lirim thanks for raising this issue.

> When rerunning failed tests file:// prefix should be appended in the beginning of file path

How is this an issue within WebdriverIO? I think this is better asked in a Circle CI community as I am not very familar with this CI system.

Happy to further help if we can break down the problem closer to WebdriverIO. We can't help on questions related to Circle CI.
