### ISSUE TITLE
CLI arguments for SauceLabs broken?

### ISSUE THREAD

**Issue by khirakawa** [webdriverio/webdriverio#1264]
## The problem

Passing in `--user` and `--key` on the CLI does not run tests in SauceLabs.  Instead, the tests attempt to run locally.  If a selenium standalone server is not running, then an error is thrown:

```
ERROR: Couldn't connect to selenium server
chrome
    at new RuntimeError (/Users/khirakawa/work/starblaster-test-runner/example/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/Users/khirakawa/work/starblaster-test-runner/example/node_modules/webdriverio/build/lib/utils/RequestHandler.js:264:37)
    at self.callback (/Users/khirakawa/work/starblaster-test-runner/example/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/khirakawa/work/starblaster-test-runner/example/node_modules/webdriverio/node_modules/request/request.js:971:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:258:9)
    at emitOne (events.js:77:13)
```

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: 4.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asnychronous tests: synchronous
* Additional wdio packages used (if applicable):

```
"wdio-dot-reporter": "0.0.5",
"wdio-junit-reporter": "0.0.2",
"wdio-mocha-framework": "^0.2.12",
"wdio-sauce-service": "^0.2.2",
```

## Details

The command used:

`node_modules/.bin/wdio --user $SAUCE_USERNAME --key $SAUCE_ACCESS_KEY wdio.conf.js`, where `$SAUCE_USERNAME` and `$SAUCE_ACCESS_KEY` are set to my SauceLabs credentials.  

The launcher succeeds in starting a sauce connect tunnel, but the tests do not run in SauceLabs.

**Comment by christian-bromann** [comment]
Could you try:
`node_modules/.bin/wdio wdio.conf.js --user $SAUCE_USERNAME --key $SAUCE_ACCESS_KEY` or
`node_modules/.bin/wdio wdio.conf.js --user=$SAUCE_USERNAME --key=$SAUCE_ACCESS_KEY`

**Comment by khirakawa** [comment]
@christian-bromann no luck, still the same issue =(

**Comment by dcypherthis** [comment]
@khirakawa does it still work if you place your credentials/env variables in your .conf.js file?

**Comment by khirakawa** [comment]
@dcypherthis Actually, I could just set the value to be 'process.env.SAUCE_USERNAME', but I believe putting the user and key in the conf file would mean the tests would always run in SauceLabs.  However, we have a use case to run locally as well, so adding the credentials in the conf file won't work =\

**Comment by christian-bromann** [comment]
@khirakawa this was actually a bug. Fixed it and will release it with the next version

**Comment by khirakawa** [comment]
@christian-bromann thanks!
