### ISSUE TITLE
[🐛 Bug]: Cannot command on elements coerced into an array: `Malformed type for "elementId" parameter`

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#12706]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.11.1

### Mode

WDIO Testrunner

### What happened?

Using the feature described in https://github.com/webdriverio/webdriverio/issues/8609 and implemented in https://github.com/webdriverio/webdriverio/pull/8736.

When coerceing elements into an element array and then mapping the elements to a command, it throws an error.

### What is your expected behavior?

Feature https://github.com/webdriverio/webdriverio/issues/8609 should be working but appears to have regressed.

### How to reproduce the bug.

```ts
// Should work, doesn't
const texts = await $$([
    $('.item'),
    $('button'),
    $('[data-value="hello"]')
]).map(e => e.getText())

// Workaround
const texts = await Promise.all([
    $('.item'),
    $('button'),
    $('[data-value="hello"]')
]).map(e => e.getText())
```

### Relevant log output

```typescript
Malformed type for "elementId" parameter of command getElementText
Expected: string
Actual: function

For more info see https://w3c.github.io/webdriver/#dfn-get-element-text

    at file:///Users/user/repos/repo/e2e/node_modules/webdriverio/build/commands/browser/waitUntil.js:43:15
    at async Browser.wrapCommandFn (file:///Users/user/repos/repo/e2e/node_modules/@wdio/utils/build/shim.js:90:29)
    at async Scenario.<anonymous> (file:///Users/user/repos/repo/e2e/steps/my.steps.ts:1:1)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ```ts
> // Should work, doesn't
> ```

As per my [comment](https://github.com/webdriverio/webdriverio/issues/8609#issuecomment-1221308154) the passed in elements __can't__ be from type `ChainablePromiseElement`, so your example works if you do:

```ts
const texts = await $$([
    await $('.item'),
    await $('button'),
    await $('[data-value="hello"]')
]).map(e => e.getText())
```

I think it can be easily extended to support `ChainablePromiseElement` types as well. Contributions are welcome.

**Comment by Julias0** [comment]
I would like to take this up. Can you assign this to me?

**Comment by Delta456** [comment]
Hi @Julias0! I would like to take up this issue. Let me know if you are still working on it.

**Comment by Julias0** [comment]
Please go ahead. Didnt get a chance to work on this
