### ISSUE TITLE
[🐛 Bug]: Internal TypeError when chaining from an index of a ChainableElementArray

### ISSUE THREAD

**Issue by isc-aray** [webdriverio/webdriverio#12917]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.33.1

### Node.js Version

20.12.2

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    "goog:chromeOptions": {
        args: [ "--start-maximized" ]
    }
}
```

### What happened?

When I attempt to index a ChainableElementArray that doesn't match anything on the page, I get an internal error message "cannot read properties of undefined."

### What is your expected behavior?

WebdriverIO should either apply normal element waiting for a single-element selection following a multi-element selection, or at least provide a clearer error message than the one seen above.

### How to reproduce the bug.

The line of code that is triggering this error is:
``` typescript
await $$('[data-cy="list"]')[list - 1].$('[data-cy="new-card"]').click();
```

The issue does not occur if I put the following line in front of this:
``` typescript
await $('[data-cy="list"]').waitForExist();
```

### Relevant log output

```typescript
TypeError: Cannot read properties of undefined (reading 'options')
at wrapCommandFn (file:///[REDACTED]/node_modules/@wdio/utils/build/shim.js:80:36)
at file:///[REDACTED]/@wdio/utils/build/shim.js:105:69
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async World.<anonymous> ([MY FILE, REDACTED])
at async wrapPromiseWithTimeout (C:\[REDACTED]\node_modules\@cucumber\cucumber\src\time.ts:55:10)
at async Object.run (C:\[REDACTED]\node_modules\@cucumber\cucumber\src\user_code_runner.ts:86:16)
...
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by isc-aray** [comment]
I'm not allowed to have public repositories due to company policy, so thanks for nothing. That's what you get for free, I guess, but what a way to treat people who are trying to help!

**Comment by christian-bromann** [comment]
I am not sure why you get so upset about this process! We kindly ask to provide a reproducible example as we maintainers can spend hours of our time to try to reproduce something that you have already on your machine. Your issue is therefor no help because we can't prove on our side if this is related to WebdriverIO or a user error.

**Comment by christian-bromann** [comment]
> but I find that the guidelines ask too much of someone reporting a bug, and far more than other open source tools that we use.

Something that would work is just share code here in GitHub. For example I tried to reproduce this with this test:

```ts
import { browser, $$ } from '@wdio/globals'

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await browser.url(`https://the-internet.herokuapp.com/login`)
        await $$('[data-cy="list"]')[123].$('[data-cy="new-card"]').click()
    })
})
```

this fails correctly with `Index out of bounds! $$([data-cy="list"]) returned only 0 elements.`. At this point I can't do any further investigations as I have no clue what circumstances were causing this bug to be thrown.

> You will, I hope, understand that I am not paid to help with software not produced by the company, and any code that I write as part of my employment belongs to my employer, and so I cannot share it publicly without permission from our legal department.

You have shared code snippets above so it should be possible to share code snippets that reproduce the problem on an arbitrary public website. People that contribute to this project aren't paid either. Your company should have an interest to allow you to interact with Open Source projects in a meaningful way or should abstain from using Open Source completely.

> I thought it would be helpful to draw attention to a bug that I encountered which nobody else seems to have reported, but if that sort of interaction is not appreciated, I will refrain in the future.

We appreciate your contribution to the project. If however the problem can not be explained with a reproducible example, it is not of much value for the folks maintaining the project.

**Comment by christian-bromann** [comment]
Closing due to inactivity.
