### ISSUE TITLE
[🐛 Bug]:  App getting stuck after Launch

### ISSUE THREAD

**Issue by HelyJigNect** [webdriverio/webdriverio#12954]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.38.1

### Node.js Version

20.14.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: {
  alwaysMatch: {
    platformName: 'Android',
    'appium:platformVersion': '12.0',
    'appium:orientation': 'PORTRAIT',
    'appium:deviceName': 'Google Pixel 4 GoogleAPI Emulator',
    'appium:automationName': 'UIAutomator2',
    'appium:app': 'storage:4edef738-5883-4705-b57b-4ad70082bcef',
    'appium:waitForIdleTimeout': 10000,
    'appium:appWaitActivity': 'sen.com.auth.pages.welcome.WelcomeActivity',
    'appium:autoAcceptAlerts': true,
    'appium:autoGrantPermissions': true,
    'sauce:options': [Object],
    'wdio:sharedStoreServicePort': 34213
   }
}
```

### What happened?

Hello team, 

I've been facing weird issue on launching app and running test. Many times - appium doesn't take any command after lunching an app. I'm unable to identify why.

Sharing video, appium log and logcat log. Can you please anyone help to see if I'm missing anything ?

https://github.com/webdriverio/webdriverio/assets/159106127/5e9fb95f-758f-4591-9c19-75b07690910e
[logcat.log](https://github.com/webdriverio/webdriverio/files/15501150/logcat.log)
[appium-server.log](https://github.com/webdriverio/webdriverio/files/15501152/appium-server.log)

### What is your expected behavior?

Test cases should be executed seamlessly.

### How to reproduce the bug.

I am currently using WebdriverIO and Appium for Android mobile automation. While the app occasionally works fine, it often gets stuck on the launch page. When this happens, both Appium and WebdriverIO do not proceed, causing the execution to hang without any errors. If the app does not get stuck after launch, all the tests pass successfully. However, the app is getting stuck 4 out of 5 times.

### Relevant log output

```typescript
05-30 12:33:36.920  1378  1391 I VoicemailNotifier: receivers for android.intent.action.PROVIDER_CHANGED :[]
05-30 12:33:36.921  5970  5993 I Dialer  : VvmActivationTask - VVM content provider configured - vvm_type_cvvm
05-30 12:33:36.921  5970  5993 I Dialer  : OmtpVvmCarrierCfgHlpr - OmtpEvent:CONFIG_ACTIVATING
05-30 12:33:36.923  1378  1391 I VoicemailNotifier: receivers for android.intent.action.PROVIDER_CHANGED :[]
05-30 12:33:36.932   927   954 D SmsNumberUtils: enter filterDestAddr. destAddr="[BajqU4K5_YhSYbs-7QUn0dOwcmI]"
05-30 12:33:36.933   927   954 D SmsNumberUtils: destAddr is not formatted.
05-30 12:33:36.933   927   954 D SmsNumberUtils: leave filterDestAddr, new destAddr="[BajqU4K5_YhSYbs-7QUn0dOwcmI]"
05-30 12:33:36.940   592   622 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.voicemailomtp.sms.REQUEST_SENT flg=0x10 pkg=com.android.dialer } from com.android.dialer (pid=-1, uid=10097) requires com.android.dialer.permission.DIALER_ORIGIN due to registered receiver BroadcastFilter{8c15850 10097/u0 ReceiverList{ea0ee13 5970 com.android.dialer/10097/u0 remote:23c0502}}
05-30 12:33:37.621  4943  5117 D EGL_emulation: app_time_stats: avg=128.37ms min=6.98ms max=2535.12ms count=23
05-30 12:33:38.797   592   622 I am_uid_idle: 10097
05-30 12:33:38.802  1725  1725 I BgTaskExecutorImpl: Starting NONEXCLUSIVE background task DOODLE_SCHEDULE_SYNC_TASK.
05-30 12:33:40.308   592   622 I am_uid_idle: 10122
05-30 12:33:40.470   592   622 I am_uid_running: 10126
05-30 12:33:40.470   592   622 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10126; state: DISABLED
05-30 12:33:40.470   592   622 D CompatibilityChangeReporter: Compat change id reported: 177438394; UID 10126; state: DISABLED
05-30 12:33:40.470   592   622 D CompatibilityChangeReporter: Compat change id reported: 135772972; UID 10126; state: DISABLED
05-30 12:33:40.470   592   622 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10126; state: ENABLED
05-30 12:33:40.471   592   623 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10126; state: ENABLED
05-30 12:33:40.477   385   385 D Zygote  : Forked child process 6880
05-30 12:33:40.478   592   623 I am_proc_start: [0,6880,10126,com.google.android.apps.wallpaper,broadcast,{com.google.android.apps.wallpaper/com.android.wallpaper.module.DailyLoggingAlarmReceiver}]
05-30 12:33:40.478   592   623 I ActivityManager: Start proc 6880:com.google.android.apps.wallpaper/u0a126 for broadcast {com.google.android.apps.wallpaper/com.android.wallpaper.module.DailyLoggingAlarmReceiver}
05-30 12:33:40.484  6880  6880 W .apps.wallpape: Unexpected CPU variant for X86 using defaults: x86_64
05-30 12:33:40.488   489   509 I adbd    : jdwp connection from 6880
05-30 12:33:40.492   592  2116 I am_proc_bound: [0,6880,com.google.android.apps.wallpaper]
05-30 12:33:40.493   592  2116 D CompatibilityChangeReporter: Compat change id reported: 168419799; UID 10126; state: DISABLED
05-30 12:33:40.495  6880  6880 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10126; state: DISABLED
05-30 12:33:40.504  6880  6880 V GraphicsEnvironment: ANGLE Developer option for 'com.google.android.apps.wallpaper' set to: 'default'
05-30 12:33:40.504  6880  6880 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
05-30 12:33:40.505  6880  6880 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-30 12:33:40.505  6880  6880 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-30 12:33:40.521   592   621 I am_pss  : [1623,10102,com.google.process.gservices,9695232,5926912,0,99336192,0,11,2]
05-30 12:33:40.525  6189  6219 I SQLiteConnection: /data/user/0/com.google.android.gms/databases/phenotype.db-wal 1289592 bytes: Bigger than 1048576; truncating
05-30 12:33:40.534  6880  6880 W UnsafeUtil: platform method missing - proto runtime falling back to safer methods: java.lang.NoSuchMethodException: sun.misc.Unsafe.copyMemory [class java.lang.Object, long, class java.lang.Object, long, long]
05-30 12:33:40.567  6880  6902 W DiskBasedLogger: Disk-based log buffer doesn't exist, so there's nothing to clean up.
05-30 12:33:40.571   592  2116 I ActivityManager: Killing 5565:com.google.android.googlequicksearchbox/u0a101 (adj 975): empty #17
05-30 12:33:40.571   592  2116 I am_kill : [0,5565,com.google.android.googlequicksearchbox,975,empty #17]
05-30 12:33:40.582   592   904 I am_proc_died: [0,5565,com.google.android.googlequicksearchbox,975,19]
05-30 12:33:40.582   385   385 I Zygote  : Process 5565 exited due to signal 9 (Killed)
05-30 12:33:40.584   592   621 I am_pss  : [1672,10140,com.google.android.permissioncontroller,15681536,12804096,0,107696128,0,19,2]
05-30 12:33:40.586   592   621 I am_pss  : [6540,10102,com.google.android.gms.unstable,21821440,8728576,0,152616960,0,19,2]
05-30 12:33:40.587   592   621 I am_pss  : [1910,10102,com.google.process.gapps,9139200,5193728,0,98877440,0,19,2]
05-30 12:33:40.588  6189  6323 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.pay.gcmtask.PayGcmTaskService started execution. cause:4 exec_start_elapsed_seconds: 114 [CONTEXT service_id=218 ]
05-30 12:33:40.589   592   621 I am_pss  : [5879,10095,com.google.android.configupdater,10629120,8019968,0,102727680,0,19,1]
05-30 12:33:40.590   592   621 I am_pss  : [2451,10061,android.process.media,12968960,10027008,0,108937216,0,19,2]
05-30 12:33:40.592   592   621 I am_pss  : [5809,10090,com.google.android.settings.intelligence,16024576,12681216,0,114692096,0,19,1]
05-30 12:33:40.594   592   621 I am_pss  : [6082,1000,com.android.settings,27630592,25034752,0,119955456,0,19,2]
05-30 12:33:40.596   592   621 I am_pss  : [1007,10098,com.google.android.apps.wellbeing,31273984,27533312,0,133853184,0,19,2]
05-30 12:33:40.596  6189  6368 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.pay.gcmtask.PayGcmTaskService finished executing. cause:4 result: 1 elapsed_millis: 15 uptime_millis: 15 exec_start_elapsed_seconds: 114 [CONTEXT service_id=218 ]
05-30 12:33:40.597  6189  6877 W TapAndPay: NfcAdapter is null while obtaining CardEmulation instance. [CONTEXT service_id=79 ]
05-30 12:33:40.597  6189  6877 W TapAndPay: java.lang.NullPointerException: NfcAdapter is null
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at android.nfc.cardemulation.CardEmulation.getInstance(CardEmulation.java:150)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at bxlw.<init>(:com.google.android.gms@225014047@22.50.14 (190800-499278674):0)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at com.google.android.gms.tapandpay.hce.task.TapAndPayAidRegistrationTaskOperation.a(:com.google.android.gms@225014047@22.50.14 (190800-499278674):5)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskChimeraService.a(:com.google.android.gms@225014047@22.50.14 (190800-499278674):4)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at asuo.call(:com.google.android.gms@225014047@22.50.14 (190800-499278674):4)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at aalr.c(:com.google.android.gms@225014047@22.50.14 (190800-499278674):6)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at aalr.run(:com.google.android.gms@225014047@22.50.14 (190800-499278674):7)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at aaqv.run(:com.google.android.gms@225014047@22.50.14 (190800-499278674):0)
05-30 12:33:40.597  6189  6877 W TapAndPay: 	at java.lang.Thread.run(Thread.java:920)
05-30 12:33:40.598   592   621 I am_pss  : [4095,10149,io.appium.uiautomator2.server,38956032,34865152,0,135725056,0,4,2]
05-30 12:33:40.600  6189  6368 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskService started execution. cause:4 exec_start_elapsed_seconds: 114 [CONTEXT service_id=218 ]
05-30 12:33:40.601  6189  6368 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskService finished executing. cause:4 result: 3 elapsed_millis: 11 uptime_millis: 11 exec_start_elapsed_seconds: 114 [CONTEXT service_id=218 ]
05-30 12:33:40.616   592   624 I libprocessgroup: Successfully killed process cgroup uid 10101 pid 5565 in 45ms
05-30 12:33:40.617  6189  6368 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskService started execution. cause:5 exec_start_elapsed_seconds: 114 [CONTEXT service_id=218 ]
05-30 12:33:40.621  4943  5117 D EGL_emulation: app_time_stats: avg=110.04ms min=7.13ms max=2541.15ms count=27
05-30 12:33:40.627  6189  6368 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.tapandpay.gcmtask.TapAndPayGcmTaskService finished executing. cause:5 result: 1 elapsed_millis: 18 uptime_millis: 18 exec_start_elapsed_seconds: 114 [CONTEXT service_id=218 ]
05-30 12:33:40.747   592   622 I am_uid_idle: 10118
05-30 12:33:40.904   592   622 I am_uid_idle: 10061
05-30 12:33:41.069   592   622 I am_uid_idle: 10121
05-30 12:33:41.775   592   622 I am_uid_idle: 10135
05-30 12:33:41.775   592   622 I am_stop_idle_service: [10135,com.google.pixel.exo/.core.PersistentService]
05-30 12:33:41.775   592   622 W ActivityManager: Stopping service due to app idle: u0a135 -1m19s990ms com.google.pixel.exo/.core.PersistentService
05-30 12:33:41.776  4876  4876 I Exo     : PersistentService: Exo PersistentService destroyed
05-30 12:33:41.777  4876  4876 E ActivityThread: Service com.google.pixel.exo.core.PersistentService has leaked ServiceConnection com.google.pixel.exo.core.PersistentService$1@eae4b00 that was originally bound here
05-30 12:33:41.777  4876  4876 E ActivityThread: android.app.ServiceConnectionLeaked: Service com.google.pixel.exo.core.PersistentService has leaked ServiceConnection com.google.pixel.exo.core.PersistentService$1@eae4b00 that was originally bound here
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1934)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1806)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1785)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1966)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.app.ContextImpl.bindService(ContextImpl.java:1897)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:812)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at com.google.pixel.exo.core.PersistentService.bindToWirecutter(PersistentService.java:131)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at com.google.pixel.exo.core.PersistentService.onStartCommand(PersistentService.java:121)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4639)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.app.ActivityThread.access$2000(ActivityThread.java:247)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.os.Looper.loopOnce(Looper.java:201)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.os.Looper.loop(Looper.java:288)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-30 12:33:41.777  4876  4876 E ActivityThread: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-30 12:33:41.777   592  1048 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@957b3e0
05-30 12:33:42.485   592   613 I commit_sys_config_file: [jobs,4]
05-30 12:33:43.624  4943  5117 D EGL_emulation: app_time_stats: avg=114.18ms min=6.77ms max=2533.45ms count=26
05-30 12:33:44.106   765   982 D EGL_emulation: app_time_stats: avg=40000.58ms min=40000.58ms max=40000.58ms count=1
05-30 12:33:44.312   592   622 I am_uid_idle: 10095
05-30 12:33:46.618  4943  5117 D EGL_emulation: app_time_stats: avg=121.41ms min=6.71ms max=2543.10ms count=24
05-30 12:33:46.671   592   621 I am_pss  : [4943,10151,ajaib.co.dev,172275712,162066432,0,301395968,0,2,7]
05-30 12:33:49.619  4943  5117 D EGL_emulation: app_time_stats: avg=110.21ms min=6.48ms max=2556.62ms count=27
05-30 12:33:52.620  4943  5117 D EGL_emulation: app_time_stats: avg=109.54ms min=6.05ms max=2543.37ms count=27
05-30 12:33:53.245   592   707 D ConnectivityService: releasing NetworkRequest [ REQUEST id=140, [ Transports: CELLULAR Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_VCN_MANAGED Uid: 10101 RequestorUid: 10101 RequestorPkg: com.google.android.googlequicksearchbox] ] (release request)
05-30 12:33:53.252   384   448 I netd    : networkSetPermissionForNetwork(100, 1) <5.20ms>
05-30 12:33:54.657   592   622 I am_uid_idle: 10098
05-30 12:33:55.629  4943  5117 D EGL_emulation: app_time_stats: avg=124.14ms min=6.40ms max=2567.44ms count=24
05-30 12:33:56.925   592   622 I am_uid_idle: 10056
05-30 12:33:58.009   592   622 I am_uid_idle: 10090
05-30 12:33:58.018  1973  6910 I Bugle   : CountryCodeDetector: updateMainDeviceCountry from default subscription network country. detected country: us
05-30 12:33:58.022  4943  5035 I TRuntime.CctTransportBackend: Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
05-30 12:33:58.620  4943  5117 D EGL_emulation: app_time_stats: avg=123.25ms min=6.73ms max=2559.65ms count=24
05-30 12:33:59.898  4943  5035 I TRuntime.CctTransportBackend: Status Code: 200
05-30 12:34:00.032   765   982 D EGL_emulation: app_time_stats: avg=15925.93ms min=15925.93ms max=15925.93ms count=1
05-30 12:34:01.617  4943  5117 D EGL_emulation: app_time_stats: avg=121.95ms min=7.07ms max=2541.60ms count=24
05-30 12:34:01.626   592   621 I am_pss  : [6540,10102,com.google.android.gms.unstable,22113280,8966144,0,153038848,0,19,3]
05-30 12:34:01.637  6169  6912 I ChimeraConfigurator: Starting update, reason: 4 urgentFeatures: vision.ocr:-1
05-30 12:34:01.640  6189  6323 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService started execution. cause:4 exec_start_elapsed_seconds: 135 [CONTEXT service_id=218 ]
05-30 12:34:01.659  6169  6912 I GmsDebugLogger: [73] 1801
05-30 12:34:01.661  6169  6912 W ZappDownloader: No successful module downloads for requested features [vision.ocr].
05-30 12:34:01.661  6169  6912 I GmsDebugLogger: [30] [VisionOcrDynamite.integ:231602402100000],[TfliteDynamiteDynamite.integ:240699101100800],[MlkitOcrCommon.optional:225014100800]
05-30 12:34:01.662  6169  6912 W ChimeraConfigService: Retry attempt was throttled. [CONTEXT service_id=264 ]
05-30 12:34:01.662  6169  6912 I GmsDebugLogger: [83] 1 [vision.ocr]
05-30 12:34:01.664  6169  6911 W Vision  : Request for optional module download of ocr failed. Request again.
05-30 12:34:01.664  6169  6911 I Vision  : Schedule retrying download ocr at 135821 with backoff 80 seconds
05-30 12:34:01.788  6189  6224 W GLSUser : [AppCertManager] Exception while requesting key: 
05-30 12:34:01.788  6189  6224 W GLSUser : java.io.IOException: Invalid device key response.
05-30 12:34:01.788  6189  6224 W GLSUser : 	at nnx.b(:com.google.android.gms@225014047@22.50.14 (190800-499278674):41)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at nnv.b(:com.google.android.gms@225014047@22.50.14 (190800-499278674):2)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at nnq.a(:com.google.android.gms@225014047@22.50.14 (190800-499278674):0)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at nnt.a(:com.google.android.gms@225014047@22.50.14 (190800-499278674):5)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at ldq.call(:com.google.android.gms@225014047@22.50.14 (190800-499278674):13)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at aalr.c(:com.google.android.gms@225014047@22.50.14 (190800-499278674):6)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at aalr.run(:com.google.android.gms@225014047@22.50.14 (190800-499278674):7)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at aaqv.run(:com.google.android.gms@225014047@22.50.14 (190800-499278674):0)
05-30 12:34:01.788  6189  6224 W GLSUser : 	at java.lang.Thread.run(Thread.java:920)
05-30 12:34:01.790  6189  6323 I NetworkScheduler.Stats: Task com.google.android.gms/com.google.android.gms.auth.account.be.legacy.AuthCronService finished executing. cause:4 result: 3 elapsed_millis: 155 uptime_millis: 155 exec_start_elapsed_seconds: 135 [CONTEXT service_id=218 ]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@HelyJigNect thanks for raising the issue.

Unfortunately there is nothing I can do to help on this issue. It seems like Appium was able to initiate the session. Without being able to reproduce this locally there is nothing really anyone in the WebdriverIO community can do to help. I recommend to reach out in our [Discord Server](https://discord.webdriver.io) to see if anyone else had similar experiences.

Cheers.
