### ISSUE TITLE
[🐛 Bug]: Spec CLI arg breakable on Windows

### ISSUE THREAD

**Issue by Xetoris** [webdriverio/webdriverio#12983]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.38.2

### Node.js Version

20.X and 22.2.0

### Mode

WDIO Testrunner

### What happened?

When trying to use the "spec" cli arg on Windows with a `glob` pattern, the runner fails to find matching spec files -- even when the output pattern fully matches the structure and there are tests.

As an example, say I ran something like:

`wdio ./configs/local-config.ts --spec /tests/some-folder/*.spec.ts`

And assume the folder structure looks something like this:

```
- root
- - configs
- - - local-config.ts
- - tests
- - - some-folder
- - - - test1.spec.ts
- - - - test2.spec.ts
- - - another-folder
- - - - test3.spec.ts
- - - top-test.spec.ts
```

In v7, the test runner would have found test1.spec.ts and test2.spec.ts. When testing the upgrade to v8, I get an error that looks something like this:

`Error: spec file(s) C:\Git\my-repo\tests\some-folder\*.spec.ts not found`

I looked for related issues and the closest I found was this guy: https://github.com/webdriverio/webdriverio/issues/9495. But, it's marked closed. I also did some diagnosis to try and pinpoint the issue and it seems to be different than the one listed in 9495.

### What is your expected behavior?

Like in v7, I would expect the test runner to locate test1.spec.ts and test2.spec.ts from the file glob pattern.

### How to reproduce the bug.

I created a test repository that contains a reproducible example when run on a Windows machine:
https://github.com/Xetoris/wdio-v8-spec-bug-example

Pull down that repo, npm install, and run `npm run windows-error` to see the error.

I did some digging through wdio-config to try and diagnose the issue. My findings are in the README and the mocha unit test that demonstrates what I think the error is.

### Relevant log output

```typescript
An example from the repo linked above on my Windows PC:


> wdio-v8-spec-bug-example@1.0.0 windows-error C:\Git\wdio-v8-spec-bug-example
> pnpm exec wdio ./wdio-example/config/config.ts --spec wdio-example/tests/filters/*.spec.ts

Error: spec file(s) C:\Git\wdio-v8-spec-bug-example\wdio-example\tests\filters\*.spec.ts not found
    at ConfigParser.setFilePathToFilterOptions (file:///C:/Git/wdio-v8-spec-bug-example/node_modules/.pnpm/@wdio+config@8.38.2/node_modules/@wdio/config/build/node/ConfigParser.js:344:19)
    at ConfigParser.merge (file:///C:/Git/wdio-v8-spec-bug-example/node_modules/.pnpm/@wdio+config@8.38.2/node_modules/@wdio/config/build/node/ConfigParser.js:190:39)
    at ConfigParser.initialize (file:///C:/Git/wdio-v8-spec-bug-example/node_modules/.pnpm/@wdio+config@8.38.2/node_modules/@wdio/config/build/node/ConfigParser.js:59:14)
    at async Launcher.run (file:///C:/Git/wdio-v8-spec-bug-example/node_modules/.pnpm/@wdio+cli@8.38.2_typescript@5.4.5/node_modules/@wdio/cli/build/launcher.js:39:9)
    at async Module.run (file:///C:/Git/wdio-v8-spec-bug-example/node_modules/.pnpm/@wdio+cli@8.38.2_typescript@5.4.5/node_modules/@wdio/cli/build/run.js:64:20)
 ELIFECYCLE  Command failed with exit code 1.

```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Xetoris** [comment]
Please let me know if you need any more information. I _think_ I found the issue and am happy to submit a PR to try and resolve it. Wanted to get a sanity check to make sure I'm not miss-interpreting or miss-using something and what solution would make the most sense.

**Comment by christian-bromann** [comment]
@Xetoris thanks for raising this super well explained issue.

What do you suggest as a solution to this? From what I see there are two options:

1. use the `windowsPathsNoEscape` flag
2. transform any path given to the glob function into a file path which enables compliant behavior between both OSes

What are your thoughts?

**Comment by Xetoris** [comment]
> @Xetoris thanks for raising this super well explained issue.
> 
> What do you suggest as a solution to this? From what I see there are two options:
> 
> 1. use the `windowsPathsNoEscape` flag
> 2. transform any path given to the glob function into a file path which enables compliant behavior between both OSes
> 
> What are your thoughts?

That's a good question.

I think both solution essentially accomplish the same ends -- you remove an backslashes (regardless if they are escaping special characters or not). This would break for people who might want to access a test file that has, say, a `*` in it. 

We could maybe try and use a regex pattern to detect a backslashes not followed by a special case and swap them for forward slashes. 

Another option I didn't look into is if there's any way to get a resolve() like functionality that we can specify the separator character with. 

I can tinker around with it and see if I can come up with a solution that won't break the escape functionality of glob and still let Windows resolve correctly.

**Comment by Xetoris** [comment]
Writing in another thought so I don't forget it the next time I look at this.

According to the comment above the line where we adjust `.spec` to be a absolute path, it says it does that to make sure patterns are resolved from the CWD. The glob helper allows you to specify the root dir, which gets passed to the CWD of the globSync() method. Maybe we can remove the need to decide and defer to glob to make the smart decisions by just passing CWD as the root dir when we go to iterate the files?

**Comment by christian-bromann** [comment]
> Maybe we can remove the need to decide and defer to glob to make the smart decisions by just passing CWD as the root dir when we go to evaluate the `.spec` property?

I think that makes sense.
