### ISSUE TITLE
[🐛 Bug]: ERROR webdriver: Failed downloading chromedriver v125.0.6422.141: Download failed: server returned code 404

### ISSUE THREAD

**Issue by almostlow** [webdriverio/webdriverio#12981]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.10.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
   browserName: 'chrome',
   browserVersion: 'latest'
   platformName: 'Windows 10'
}
```

### What happened?

Error, that url where chrome should be downloaded not found. Please check logs

### What is your expected behavior?

To be valid url, that chrome will be downloaded.

### How to reproduce the bug.

```js
Wdio config:

const path = require('path')
const fs = require('fs')
//const video = require('wdio-video-reporter');
const allure = require('allure-commandline')

global.downloadsDir = path.join(__dirname, 'downloads')

function rmdir(dir) {
    var list = fs.readdirSync(dir);
    for (var i = 0; i < list.length; i++) {
        var filename = path.join(dir, list[i]);
        var stat = fs.statSync(filename);
        if (filename == "." || filename == "..") {
            //pass
        } else if (stat.isDirectory()) {
            rmdir(filename);
        } else {
            fs.unlinkSync(filename);
        }
    }
    fs.rmdirSync(dir);
}


exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    // WebdriverIO supports running e2e tests as well as unit and component tests.
    runner: 'local',
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // of the configuration file being run.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // If you are calling `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script),
    // then the current working directory is where your `package.json` resides, so `wdio`
    // will be called from there.
    //
    specs: [
        // ToDo: define location for spec files here
        'test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://saucelabs.com/platform/platform-configurator
    //
    capabilities: [
        {
            maxInstances: 1,
            browserName: 'chrome',
            'goog:chromeOptions': {
                prefs: {
                    'download.default_directory': downloadsDir
                }
            },
            'wdio:chromedriverOptions': {
                version: 'latest' // or specify a known good version
            }
        }
        // {
        //     browserName: 'firefox'
        // }
    ],

    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'warn',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/appium-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'https://ambertest.dpd.lt/',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,  //default 10000
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
     services: ['chromedriver'],
    //
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',

    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Delay in seconds between the spec file retry attempts
    // specFileRetriesDelay: 0,
    //
    // Whether or not retried spec files should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter
    reporters: ['spec',
        // [video, {
        //     saveAllVideos: false,       // If true, also saves videos for successful test cases
        //     videoSlowdownMultiplier: 3, // Higher to get slower videos, lower for faster videos [Value 1-100]
        //     outputDir: 'temp',
        // }],
        ['allure', {
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: false,
        }],
    ],


    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000 //default 60000
    },

    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    onPrepare: function (config, capabilities) {
        if (!fs.existsSync(downloadsDir)) {
            fs.mkdirSync(downloadsDir)
        }
    },
    /**
     * Gets executed before a worker process is spawned and can be used to initialize specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {string} cid      capability id (e.g 0-0)
     * @param  {object} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {object} specs    specs to be run in the worker process
     * @param  {object} args     object that will be merged with the main configuration once worker is initialized
     * @param  {object} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just after a worker process has exited.
     * @param  {string} cid      capability id (e.g 0-0)
     * @param  {number} exitCode 0 - success, 1 - fail
     * @param  {object} specs    specs to be run in the worker process
     * @param  {number} retries  number of retries used
     */
    // onWorkerEnd: function (cid, exitCode, specs, retries) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     * @param {string} cid worker id (e.g. 0-0)
     */
    // beforeSession: function (config, capabilities, specs, cid) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {object}         browser      instance of created browser/device session
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {string} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Hook that gets executed before the suite starts
     * @param {object} suite suite details
     */
    beforeSuite: function () {
        try {
            browser.maximizeWindow()
        } catch (error) { }
    },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
    // beforeTest: function (test, context) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function (test, context, hookName) {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function (test, context, { error, result, duration, passed, retries }, hookName) {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine only)
     * @param {object}  test             test object
     * @param {object}  context          scope object the test was executed with
     * @param {Error}   result.error     error object in case the test fails, otherwise `undefined`
     * @param {*}       result.result    return object of test function
     * @param {number}  result.duration  duration of test
     * @param {boolean} result.passed    true if test has passed, otherwise false
     * @param {object}  result.retries   information about spec related retries, e.g. `{ attempts: 0, limit: 0 }`
     */
    afterTest: async function (test, context, { error }) {
        if (error) {
            await browser.takeScreenshot();
        }
    },


    /**
     * Hook that gets executed after the suite has ended
     * @param {object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {string} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {number} result 0 - command success, 1 - command error
     * @param {object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {object} exitCode 0 - success, 1 - fail
     * @param {object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
     onComplete: function () {
         rmdir(downloadsDir)
     },
    /**
    * Gets executed when a refresh happens.
    * @param {string} oldSessionId session ID of the old session
    * @param {string} newSessionId session ID of the new session
    */
    // onReload: function(oldSessionId, newSessionId) {
    // }
    /**
    * Hook that gets executed before a WebdriverIO assertion happens.
    * @param {object} params information about the assertion to be executed
    */
    // beforeAssertion: function(params) {
    // }
    /**
    * Hook that gets executed after a WebdriverIO assertion happened.
    * @param {object} params information about the assertion that was executed, including its results
    */
    // afterAssertion: function(params) {
    // }
}

package.json

{
  "name": "dpd-new-ui",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "wdio": "wdio run ./wdio.conf.js",
    "cleanup": "",
    "tests:lt:test": "set COUNTRY=LT&& npm run cleanup && npx wdio --baseUrl=https://ambertest.dpd.lt",
    "tests:lv:test": "set COUNTRY=LV&& npm run cleanup && npx wdio --baseUrl=https://ambertest.dpd.lv",
    "tests:ee:test": "set COUNTRY=EE&& npm run cleanup && npx wdio --baseUrl=https://ambertest.dpd.ee",
    "tests:lt:stage": "set COUNTRY=LT&& npm run cleanup && npx wdio  --baseUrl=https://amberstage.dpd.lt",
    "tests:lv:stage": "set COUNTRY=LV&& npm run cleanup && npx wdio --baseUrl=https://amberstage.dpd.lv",
    "tests:ee:stage": "set COUNTRY=EE&& npm run cleanup && npx wdio  --baseUrl=https://amberstage.dpd.ee",
    "tests:lt:sandbox": "set COUNTRY=LT&& npm run cleanup && npx wdio --baseUrl=https://sandbox-esiunta.dpd.lt/en",
    "tests:lv:sandbox": "set COUNTRY=LV&& npm run cleanup && npx wdio --baseUrl=https://sandbox-esiunta.dpd.lv/en",
    "tests:ee:sandbox": "set COUNTRY=EE&& npm run cleanup && npx wdio --baseUrl=https://sandbox-esiunta.dpd.ee/en",
    "tests:parcelCreation": "set COUNTRY=LT&& npx wdio --baseUrl=https://sandbox-esiunta.dpd.lt/en  --spec .\\test\\specs\\ad-hoc\\parcelCreationLoggedOut\\AddressToAddressS.js --spec .\\test\\specs\\ad-hoc\\parcelCreation\\AddressToLockerM.js --spec .\\test\\specs\\ad-hoc\\parcelCreation\\LockerToAddressL.js --spec .\\test\\specs\\ad-hoc\\parcelCreation\\LockerToLockerXS.js --multi-run 1",
    "tests:random": "set COUNTRY=LT&& npx wdio --baseUrl=https://sandbox-esiunta.dpd.lt/en  --spec .\\test\\specs\\ad-hoc\\shipments.js --multi-run 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.23.4",
    "@babel/core": "^7.23.6",
    "@babel/preset-env": "^7.23.6",
    "@babel/register": "^7.22.15",
    "@wdio/allure-reporter": "^8.27.2",
    "@wdio/cli": "^8.38.2",
    "@wdio/local-runner": "^8.26.1",
    "@wdio/mocha-framework": "^8.24.12",
    "@wdio/spec-reporter": "^8.24.12",
    "eslint": "^8.56.0",
    "eslint-plugin-wdio": "^8.24.12",
    "wdio-chromedriver-service": "^8.1.1"
  },
  "dependencies": {
    "allure-commandline": "^2.25.0",
    "rimraf": "^5.0.5",
    "wdio-video-reporter": "^4.0.5"
  }
}


'''
```

### Relevant log output

```typescript
10:15:46 2024-06-05T07:15:46.692Z WARN webdriver: Chromedriver v125.0.6422.142 don't exist, trying to find known good version...
10:15:46 2024-06-05T07:15:46.846Z ERROR webdriver: Failed downloading chromedriver v125.0.6422.141: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/125.0.6422.141/win64/chromedriver-win64.zip, retrying ...
10:15:47 Error: Error: Failed downloading chromedriver v125.0.6422.141: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/125.0.6422.141/win64/chromedriver-win64.zip, retrying ...
10:15:47     at file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node/utils.js:105:19
10:15:47     at processTicksAndRejections (node:internal/process/task_queues:95:5)
10:15:47     at _install (file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node/utils.js:102:5)
10:15:47     at _install (file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node/utils.js:102:5)
10:15:47     at setupChromedriver (file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node/utils.js:261:17)
10:15:47     at async Promise.all (index 0)
10:15:47     at async Promise.all (index 0)
10:15:47     at Launcher.run (file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/build/launcher.js:102:13)
10:15:47     at Module.run (file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/build/run.js:64:20)
10:15:47 Error: Failed downloading chromedriver v125.0.6422.141: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/125.0.6422.141/win64/chromedriver-win64.zip, retrying ...
10:15:47     at file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node/utils.js:105:19
10:15:47     at processTicksAndRejections (node:internal/process/task_queues:95:5)
10:15:47     at _install (file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node/utils.js:102:5)
10:15:47     at _install (file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node/utils.js:102:5)
10:15:47     at setupChromedriver (file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/node_modules/@wdio/utils/build/node/utils.js:261:17)
10:15:47     at async Promise.all (index 0)
10:15:47     at async Promise.all (index 0)
10:15:47     at Launcher.run (file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/build/launcher.js:102:13)
10:15:47     at Module.run (file:///C:/Jenkins/.jenkins/workspace/DPD%20Stage/dpd-new-ui-ux-tests/node_modules/@wdio/cli/build/run.js:64:20)
10:15:47 Build step 'Execute Windows batch command' marked build as failure
10:15:48 [dpd-new-ui-ux-tests] $ C:\Jenkins\.jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\2.15.0\bin\allure.bat generate -c -o "C:\Jenkins\.jenkins\workspace\DPD Stage\dpd-new-ui-ux-tests\allure-report"
10:15:50 allure-results does not exist
10:15:51 Report successfully generated to C:\Jenkins\.jenkins\workspace\DPD Stage\dpd-new-ui-ux-tests\allure-report
10:15:51 Allure report was successfully generated.
10:15:51 Creating artifact for the build.
10:15:52 Artifact was added to the build.
10:16:13 [Slack Notifications] found #203 as previous completed, non-aborted build
10:16:13 [Slack Notifications] will send OnEveryFailureNotification because build matches and user preferences allow it
10:16:14 Finished: FAILURE
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@almostlow thanks for raising the issue! Can you double check which `@puppeteer/browsers` version is used in your `package-lock.json`? I would recommend to remove the `package-lock.json`, update all WDIO packages and re-install your dependencies.

**Comment by almostlow** [comment]
1.9.1

For now i solved it with adding "chromedriver" dependancy to package.json. Issue can be closed
