### ISSUE TITLE
[🐛 Bug]: <title>

### ISSUE THREAD

**Issue by jcrosetto** [webdriverio/webdriverio#13013]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.37.0

### Node.js Version

18.20.3

### Mode

Standalone Mode

### What happened?

After upgrading to webdriverio version 8.37.0 some test suite runs are failing with `Error: There isn't any active suite!`

In the allure report the test is showing as passed, so this error must be happening aftewards. I did a little digging and it looks like it may be failing because `_endTest` in `reporter.js` is being called for one of the hook states that gets pushed on the `_state` stack.

This does not occur in version 8.36.1.

### What is your expected behavior?

Tests pass without failures.

### How to reproduce the bug.

Minimal example ([corresponding gist](https://gist.github.com/jcrosetto/e59452c80be5445c8ff49a164c240930)) that recreates the issue:

1. Create a custom service that extends the browser object in the `before` method.
2. Create a test suite that calls the function added to the browser object within the `before` hook followed by a call to `browser.url` (there must be both). I used the mocha test runner but I'm not sure if this matters.
3. Add a nested `describe` block that a contains a single test.
4. Run the test and observe the error in the output.

### Relevant log output

```typescript
Terminal output:

Error: There isn't any active suite!
    at AllureReporter._endSuite (./node_modules/@wdio/allure-reporter/build/reporter.js:80:19)
    at AllureReporter.onSuiteEnd (./node_modules/@wdio/allure-reporter/build/reporter.js:307:14)
    at AllureReporter.<anonymous> (./node_modules/@wdio/reporter/build/index.js:165:18)
    at AllureReporter.emit (node:events:517:28)
    at AllureReporter.emit (node:domain:489:12)
    at ./node_modules/@wdio/runner/build/reporter.js:47:56
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (./node_modules/@wdio/runner/build/reporter.js:47:25)
    at MochaAdapter.emit (./node_modules/@wdio/mocha-framework/build/index.js:162:24)
    at Runner.emit (node:events:529:35)
    at Runner.emit (node:domain:489:12)
    at ./node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runner.js:896:12
    at next (./node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runner.js:474:14)
    at Immediate.<anonymous> (./node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runner.js:559:5)
    at processImmediate (node:internal/timers:476:21)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by mhmmdaminn** [comment]
haloo i got a same error like this :

2024-06-14T09:20:51.207Z ERROR @wdio/utils:shim: Error: There isn't any active test!
[0-0]     at AllureReporter.attachFile (file:///Users/61525/example/testing-mobile-2/testing-mobile/node_modules/@wdio/allure-reporter/build/reporter.js:58:19)
[0-0]     at AllureReporter.attachScreenshot (file:///Users/61525/example/testing-mobile-2/testing-mobile/node_modules/@wdio/allure-reporter/build/reporter.js:71:14)
[0-0]     at AllureReporter.onAfterCommand (file:///Users/61525/example/testing-mobile-2/testing-mobile/node_modules/@wdio/allure-reporter/build/reporter.js:363:18)
[0-0]     at AllureReporter.emit (node:events:532:35)
[0-0]     at AllureReporter.emit (node:domain:488:12)
[0-0]     at file:///Users/61525/example/testing-mobile-2/testing-mobile/node_modules/@wdio/runner/build/reporter.js:47:56
[0-0]     at Array.forEach (<anonymous>)
[0-0]     at BaseReporter.emit (file:///Users/61525/example/testing-mobile-2/testing-mobile/node_modules/@wdio/runner/build/reporter.js:47:25)
[0-0]     at EventEmitter.<anonymous> (file:///Users/61525/example/testing-mobile-2/testing-mobile/node_modules/@wdio/runner/build/index.js:207:58)
[0-0]     at EventEmitter.emit (node:events:520:28)


this log appear when i'm running my script. before feature file is called.

I hope anyone know how to fix this problem.

**Comment by RedX2501** [comment]
When this error happens for me the `afterSession` hook is skipped.

Additionally the application is not closed.

I'm running the tests in Standalone Mode.

**Comment by RedX2501** [comment]
I have investigated my case a bit and the origin of the problem might be different but since the symptom is similar I'm still posting my analysis here.

I have narrowed down the problem in the allure-reporter to the following call chain:

1. `Runner.prototype.runSuite` is called with a `describe` (or suite) that has no tests.
2. This will bail as it has no tests calling the given `fn` which in this case is `done()`.
3. `done()` will then call the `afterSuite` hooks
4. No `startSuite` was called because that would be done after the conditions are checked for bailing out.

Here are the corresponding functions with annotations `// !!!` by me:

```js
// !!! fn is done()
Runner.prototype.runSuite = function (suite, fn) {
  var i = 0;
  var self = this;
  var total = this.grepTotal(suite);

  debug('runSuite(): running %s', suite.fullTitle());

  if (!total || (self.failures && suite._bail)) {
    // !!! the describe has no tests, so bailout happens
    debug('runSuite(): bailing');
   // !!! we are quitting early. Calling fn() (which is done()).
   // !!! not sure if this is really necessary since it's not called
   // !!! in the good path.
    return fn();
  }

  // !!! this never gets called for describes without tests.
  this.emit(constants.EVENT_SUITE_BEGIN, (this.suite = suite));

  function next(errSuite) {
    // !!! removed for clarity
  }

  function done(errSuite) {
    self.suite = suite;
    self.nextSuite = next;

    // remove reference to test
    delete self.test;

   // !!! this is always called, even when bailing out
   // !!! without ever calling EVENT_SUITE_START.
    debug('done(): ending %s', suite.fullTitle());
    self.hook(HOOK_TYPE_AFTER_ALL, function () {
      self.emit(constants.EVENT_SUITE_END, suite);
      fn(errSuite);
    });
  }

  this.nextSuite = next;

  this.hook(HOOK_TYPE_BEFORE_ALL, function (err) {
    if (err) {
      return done();
    }
    self.runTests(suite, next);
  });
};

```

So the fix is to decide whether start and end hooks also apply to empty describes and change the start or end hook call condition accordingly.
