### ISSUE TITLE
A new session could not be created

### ISSUE THREAD

**Issue by alexprice91** [webdriverio/webdriverio#1308]
My code is working perfectly locally, but I am having a problem getting it to run on bitrise.io with appium.

I get the following logs when trying to run my tests:

```
[Appium] New IosDriver session created successfully, session aaf5abfa-2982-47d7-a556-5ce08cedd91c added to master session list
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   javascriptEnabled: true
[Appium]   locationContextEnabled: true
[Appium]   handlesAlerts: true
[Appium]   rotatable: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.3'
[Appium]   deviceName: 'iPhone 6'
[Appium]   app: '/Users/vagrant/git/react-native/ios/build/Release-iphonesimulator/chat.app'
[Appium]   avdReadyTimeout: '3000'
[Appium]   requestOrigins: { url: 'http://webdriver.io',
  version: '4.0.7',
  name: 'webdriverio' }
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":true,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesS...
[HTTP] <-- POST /wd/hub/session 500 6245 ms - 189 
ERROR: A new session could not be created. Details: Problem getting session data for driver type IosDriver; does it implement 'get driverData'?
iphone6.ios.9_3.chat_app
    at new RuntimeError (/Users/vagrant/git/react-native/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/Users/vagrant/git/react-native/node_modules/webdriverio/build/lib/utils/RequestHandler.js:246:32)
    at Request.self.callback (/Users/vagrant/git/react-native/node_modules/request/request.js:373:22)
    at emitTwo (events.js:106:13)
s:191:7)
    at Request.<anonymous> (/Users/vagrant/git/react-native/node_modules/request/request.js:1318:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/vagrant/git/react-native/node_modules/request/request.js:1266:12)
    at emitNone (events.js:91:20)
```

**Comment by christian-bromann** [comment]
This seems to be a problem with https://www.bitrise.io/ not WebdriverIO. Please reach out to their support channel.
