### ISSUE TITLE
ERROR @wdio/cli:utils: Appium fails to start on Windows

### ISSUE THREAD

**Issue by smtripathi99** [webdriverio/webdriverio#13147]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

const { generate } = require('multiple-cucumber-html-reporter');
const { removeSync } = require('fs-extra');
const reportConfig = require('./systemIntegration/utils/reportConfiguration');
const yargs = require('yargs');

const parseCmdArgs = () => yargs.argv;
const getCmdArgs = () => parseCmdArgs();
const getRunOnSauce = () => getCmdArgs().runOnSauce || false;

exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    //
    // =================
    // Service Providers
    // =================
    // WebdriverIO supports Sauce Labs, Browserstack, Testing Bot and LambdaTest (other cloud providers
    // should work too though). These services define specific user and key (or access key)
    // values you need to put in here in order to connect to these services.
    //
    user: process.env.SAUCE_USERNAME || 'AXP_Master_Account',
    key: process.env.SAUCE_ACCESS_KEY || 'SOME-KEY',
    //hostname: 'ondemand.us-west-1.saucelabs.com',
    port: 443,
    path: '/wd/hub',
    //
    // If you run your tests on Sauce Labs you can specify the region you want to run your tests
    // in via the `region` property. Available short handles for regions are `us` (default), `eu` and `apac`.
    // These regions are used for the Sauce Labs VM cloud and the Sauce Labs Real Device Cloud.
    // If you don't provide the region it will default for the `us`
    region: 'us',

    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // If you are calling `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script),
    // then the current working directory is where your `package.json` resides, so `wdio`
    // will be called from there.
    //
    specs: [
        './systemIntegration/features/**/*.feature'

    ],
    exclude: [
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //

    maxInstances: 1,

    capabilities: [

    {

            'appium:platformName': 'Android',

'appium:platformVersion': '12',
        'appium:deviceName': 'Pixel 6a API',
'appium:automationName': 'UiAutomator2',
        'appium:browserName': 'Chrome',
        'appium:noReset':true,
        'appium:newCommandTimeout': 240,
},

],

    port: 4723,
    services: [

    ['appium',

{

    args: {

        relaxedSecurity: true,

        path: '/wd/hub',

        address: '127.0.0.1',
        //port: 4723,
    },
    //port: 4723,
    command: 'appium',
    logPath : './'

}

]

],

logLevel: 'debug',

bail: 0,

    waitforTimeout: 15000,

    waitForInterval: 200,

    connectionRetryTimeout: 90000,

    connectionRetryCount: 3,

    framework: 'cucumber',

    cucumberOpts: {

    ui: 'bdd',

    timeout: 120000

},

    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    onPrepare: () => {
        // Remove the folder that holds the json and report files
        removeSync('./cucumber-reports/');
    },
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to
     * be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialized
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just after a worker process has exited.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {Number} exitCode 0 - success, 1 - fail
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {Number} retries  number of retries used
     */
    // onWorkerEnd: function (cid, exitCode, specs, retries) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     * @param {String} cid worker id (e.g. 0-0)
     */
    // beforeSession: function (config, capabilities, specs, cid) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {Object}         browser      instance of created browser/device session
     */
    before: function (capabilities, specs) {
        browser.maximizeWindow()
    },

    beforeEach:function (){

    },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Cucumber Hooks
     *
     * Runs before a Cucumber Feature.
     * @param {String}                   uri      path to feature file
     * @param {GherkinDocument.IFeature} feature  Cucumber feature object
     */
    // beforeFeature: function (uri, feature) {
    // },
    /**
     *
     * Runs before a Cucumber Scenario.
     * @param {ITestCaseHookParameter} world    world object containing information on pickle and test step
     * @param {Object}                 context  Cucumber World object
     */
    // beforeScenario: function (world, context) {
    // },
    /**
     *
     * Runs before a Cucumber Step.
     * @param {Pickle.IPickleStep} step     step data
     * @param {IPickle}            scenario scenario pickle
     * @param {Object}             context  Cucumber World object
     */
    // beforeStep: function (step, scenario, context) {
    // },

    /**
     *
     * Runs after a Cucumber Step.
     * @param {Pickle.IPickleStep} step             step data
     * @param {IPickle}            scenario         scenario pickle
     * @param {Object}             result           results object containing scenario results
     * @param {boolean}            result.passed    true if scenario has passed
     * @param {string}             result.error     error stack if scenario failed
     * @param {number}             result.duration  duration of scenario in milliseconds
     * @param {Object}             context          Cucumber World object
     */
    afterStep: function (step, scenario, { error, duration, passed }) {
        reportConfig.attachImageToCucumberReport()
    },

    /**
     *
     * Runs after a Cucumber Scenario.
     * @param {ITestCaseHookParameter} world            world object containing information on pickle and test step
     * @param {Object}                 result           results object containing scenario results
     * @param {boolean}                result.passed    true if scenario has passed
     * @param {string}                 result.error     error stack if scenario failed
     * @param {number}                 result.duration  duration of scenario in milliseconds
     * @param {Object}                 context          Cucumber World object
     */

    /**
     *
     * Runs after a Cucumber Feature.
     * @param {String}                   uri      path to feature file
     * @param {GherkinDocument.IFeature} feature  Cucumber feature object
     */
    // afterFeature: function (uri, feature) {
    // },

    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    onComplete: () => {
        generate(reportConfig.getReportOptions());
    }

    /**
     * Gets executed when a refresh happens.
     * @param {String} oldSessionId session ID of the old session
     * @param {String} newSessionId session ID of the new session
     */
    // onReload: function(oldSessionId, newSessionId) {
    // }
}

### What happened?

{

            'appium:platformName': 'Android',

'appium:platformVersion': '12',
        'appium:deviceName': 'Pixel 6a API',
'appium:automationName': 'UiAutomator2',
        'appium:browserName': 'Chrome',
        'appium:noReset':true,
        'appium:newCommandTimeout': 240,
},

### How to reproduce the bug.

[package.json](https://github.com/user-attachments/files/16147859/package.json)

### Relevant log output

```typescript
C:\Users\smtripat\git\wdio> npx wdio run wdio.android.conf.js --cucumberOpts.tags='@carBooking' --runOnSauce=false

Execution of 1 workers started at 2024-07-09T18:25:39.931Z

2024-07-09T18:25:40.123Z DEBUG @wdio/utils:initializeServices: initialize service "appium" as NPM package
2024-07-09T18:25:41.629Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-07-09T18:25:41.684Z INFO @wdio/appium-service: Will spawn Appium process: cmd /c appium --base-path / --relaxed-security --path /wd/hub --address 127.0.0.1
2024-07-09T18:25:53.584Z ERROR @wdio/appium-service: 

2024-07-09T18:25:53.596Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error:

    at Socket.<anonymous> (file:///C:/Users/smtripat/git/wdio/node_modules/@wdio/appium-service/build/launcher.js:174:28)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

Continue...
2024-07-09T18:25:53.597Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 11951ms
2024-07-09T18:25:53.614Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-07-09T18:25:53.615Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2024-07-09T18:25:53.618Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.android.conf.js,--cucumberOpts.tags=@carBooking,--runOnSauce=false
2024-07-09T18:25:53.692Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
2024-07-09T18:25:53.695Z ERROR @wdio/appium-service: Appium exited before timeout (exit code: 1)


[0-0] 2024-07-09T18:26:02.678Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2024-07-09T18:26:09.967Z DEBUG @wdio/runner: init remote session
[0-0] 2024-07-09T18:26:09.978Z DEBUG @wdio/utils:initializeServices: initialize service "appium" as NPM package
[0-0] RUNNING in Android - file:///C:/Users/smtripat/git/wdio/systemIntegration/features/CarBooking.feature
[0-0] 2024-07-09T18:26:18.770Z DEBUG @wdio/runner: init remote session
[0-0] 2024-07-09T18:26:18.772Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-07-09T18:26:18.773Z INFO @wdio/utils: Connecting to existing driver at http://127.0.0.1:4723/
[0-0] 2024-07-09T18:26:18.829Z INFO webdriver: [POST] http://127.0.0.1:4723/session
[0-0] 2024-07-09T18:26:18.829Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       'appium:platformName': 'Android',
[0-0]       'appium:platformVersion': '12',
[0-0]       'appium:deviceName': 'Pixel 6a API',
[0-0]       'appium:automationName': 'UiAutomator2',
[0-0]       'appium:browserName': 'Chrome',
[0-0]       'appium:noReset': true,
[0-0]       'appium:newCommandTimeout': 240
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     'appium:platformName': 'Android',
[0-0]     'appium:platformVersion': '12',
[0-0]     'appium:deviceName': 'Pixel 6a API',
[0-0]     'appium:automationName': 'UiAutomator2',
[0-0]     'appium:browserName': 'Chrome',
[0-0]     'appium:noReset': true,
[0-0]     'appium:newCommandTimeout': 240
[0-0]   }
[0-0] }
[0-0] 2024-07-09T18:26:19.211Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4723
[0-0]     at ClientRequest.<anonymous> (file:///C:/Users/smtripat/git/wdio/node_modules/got/dist/source/core/index.js:790:107)
[0-0]     at Object.onceWrapper (node:events:629:26)
[0-0]     at ClientRequest.emit (node:events:526:35)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:501:9)
[0-0]     at Socket.emit (node:events:514:28)
[0-0]     at Socket.emit (node:domain:489:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
[0-0] 2024-07-09T18:26:19.211Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://127.0.0.1:4723/", make sure browser driver is running on that address.
[0-0] It seems like the service failed to start or is rejecting any connections.
[0-0]     at startWebDriverSession (file:///C:/Users/smtripat/git/wdio/node_modules/webdriver/build/utils.js:69:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at Function.newSession (file:///C:/Users/smtripat/git/wdio/node_modules/webdriver/build/index.js:19:45)
[0-0]     at remote (file:///C:/Users/smtripat/git/wdio/node_modules/webdriverio/build/index.js:46:22)
[0-0]     at Runner._startSession (file:///C:/Users/smtripat/git/wdio/node_modules/@wdio/runner/build/index.js:241:29)
[0-0]     at Runner._initSession (file:///C:/Users/smtripat/git/wdio/node_modules/@wdio/runner/build/index.js:207:25)
[0-0]     at Runner.run (file:///C:/Users/smtripat/git/wdio/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] 2024-07-09T18:26:19.222Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
2024-07-09T18:26:19.361Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in Android - file:///C:/Users/smtripat/git/wdio/systemIntegration/features/CarBooking.feature
2024-07-09T18:26:19.363Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-07-09T18:26:19.364Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
2024-07-09T18:26:19.364Z INFO @wdio/cli:launcher: Run onComplete hook
2024-07-09T18:26:19.396Z ERROR @wdio/cli:utils: Error in onCompleteHook: Error: There were issues reading JSON-files from './cucumber-reports/cucumber-json/'.
    at collectJSONS (C:\Users\smtripat\git\wdio\node_modules\multiple-cucumber-html-reporter\lib\collect-jsons.js:29:15)
    at generate (C:\Users\smtripat\git\wdio\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:78:23)
    at Object.onComplete (C:\Users\smtripat\git\wdio\/wdio.android.conf.js:313:9)
    at file:///C:/Users/smtripat/git/wdio/node_modules/@wdio/cli/build/utils.js:101:19
    at Array.map (<anonymous>)
    at runOnCompleteHook (file:///C:/Users/smtripat/git/wdio/node_modules/@wdio/cli/build/utils.js:99:39)
    at Launcher.run (file:///C:/Users/smtripat/git/wdio/node_modules/@wdio/cli/build/launcher.js:110:45)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-07-09T18:26:19.397Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:39

2024-07-09T18:26:19.399Z INFO @wdio/local-runner: Shutting down spawned worker
2024-07-09T18:26:19.654Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-07-09T18:26:19.656Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
Seems to me like the multiple-cucumber-html-reporter has an issue reading a json file. This is a third party reporter, contact the maintainer for support on the reporter.

**Comment by christian-bromann** [comment]
I believe it is the Appium service not being able to start Appium properly so all tests failing and consequently the report can't be generated.

@smtripathi99 mind give us some help and help us debug why the Appium server can't start?

**Comment by smtripathi99** [comment]
@christian-bromann , In IntelliJ if i start Appium server with >appium --base-path /wd/hub   it starts but when i try to start with WDIO Appium service by running a test it fails:

2024-07-09T18:25:40.123Z DEBUG @wdio/utils:initializeServices: initialize service "appium" as NPM package
2024-07-09T18:25:41.629Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-07-09T18:25:41.684Z INFO @wdio/appium-service: Will spawn Appium process: cmd /c appium --base-path / --relaxed-security --path /wd/hub --address 127.0.0.1
2024-07-09T18:25:53.584Z ERROR @wdio/appium-service: 

**2024-07-09T18:25:53.596Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook**

**Comment by christian-bromann** [comment]
> Will spawn Appium process: cmd /c appium --base-path / --relaxed-security --path /wd/hub --address 127.0.0.1

@smtripathi99 can you try to debug to see why this command fails?

**Comment by smtripathi99** [comment]
Debug is not working in my setup but here is appium doctor output:

                                                                       
WARN AppiumDoctor [Deprecated] Please use appium-doctor installed with "npm install @appium/doctor --location=global"
info AppiumDoctor Appium Doctor v.1.16.2                                                                             
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###                                             
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\node.EXE
info AppiumDoctor  ✔ Node version is 18.17.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: C:\Users\smtripat\AppData\Local\Android\Sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk-11.0.12             
info AppiumDoctor    Checking adb, android, emulator, apkanalyzer.bat
info AppiumDoctor      'adb' is in C:\Users\smtripat\AppData\Local\Android\Sdk\platform-tools\adb.exe
info AppiumDoctor      'emulator' is in C:\Users\smtripat\AppData\Local\Android\Sdk\emulator\emulator.exe
info AppiumDoctor      'apkanalyzer.bat' is in C:\Users\smtripat\AppData\Local\Android\Sdk\cmdline-tools\latest\bin\apkanalyzer.bat
WARN AppiumDoctor  ✖ android could NOT be found in C:\Users\smtripat\AppData\Local\Android\Sdk!
info AppiumDoctor  ✔ 'bin' subfolder exists under 'C:\Program Files\Java\jdk-11.0.12'
info AppiumDoctor ### Diagnostic for necessary dependencies completed, one fix needed. ###
info AppiumDoctor
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
WARN AppiumDoctor  ✖ gst-launch-1.0.exe and/or gst-inspect-1.0.exe cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 5 fixes possible. ###
info AppiumDoctor
info AppiumDoctor ### Manual Fixes Needed ###
info AppiumDoctor The configuration cannot be automatically fixed, please do the following first:
WARN AppiumDoctor  ➜ Manually install android and add it to PATH. https://developer.android.com/studio#cmdline-tools and https://developer.android.com/studio/intro/update#sdk-manager m
ay help to setup.
info AppiumDoctor
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: http://appium.io/docs/en/writing-running-appium/image-comparison/
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it. Also con
sider adding the ".jar" extension into your PATHEXT environment variable in order to fix the problem for Windows
WARN AppiumDoctor  ➜ gst-launch-1.0.exe and gst-inspect-1.0.exe are used to stream the screen of the device under test. Please read https://appium.io/docs/en/writing-running-appium/and
roid/android-screen-streaming/ to install them and for more details
info AppiumDoctor
info AppiumDoctor ###
info AppiumDoctor
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

**Comment by BorisOsipov** [comment]
@smtripathi99 

Your sauce key has been compromised by sharing wdio config with the key in the issue description. I've edited your issue text to no longer share the key.
Please revoke the key ASAP.

**Comment by christian-bromann** [comment]
@BorisOsipov good catch, thanks for pointing this out and removing the key.

@smtripathi99 if you run your tests on Sauce Labs you don't need the Appium service unless you want to run the mobile tests locally.

**Comment by christian-bromann** [comment]
Closing due to inactivity.
