### ISSUE TITLE
[🐛 Bug]: Unable to execute .feature file 

### ISSUE THREAD

**Issue by SupersonicLeah** [webdriverio/webdriverio#13184]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

Node.js v19.9.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
services: ['appium'],
    appium: { command: 'appium' },
    port: 4723, // default appium port
    services: ['selenium-standalone'],   
        
    capabilities: [{
        platformName: 'Android', // or 'iOS'
        //'appium:app': 'MobileApp\\Android-MyDemoAppRN.1.3.0.build-244.apk', // Replace with the path to your APK file
        'appium:deviceName' : 'Android',
        'appium:appPackage': "com.saucelabs.mydemoapp.rn",
        'appium:appActivity': "com.saucelabs.mydemoapp.rn.MainActivity",
        'appium:automationName' : 'UiAutomator2',
        //'appium:browserName' : 'chrome' // for Android
        // Add necessary capabilities for iOS if required
        }],
    //services: ['appium'],
    framework: 'cucumber',
    reporters: ['spec'],
    cucumberOpts: {
        requireModule: ['@babel/register'],
        require: ['./step_definitions/**/*.js']
        },
        // Add other configurations as needed
        specs: [
            './step_definitions/**/*.feature'
        ],
```

### What happened?

I am able to just launch the app but as soon as it does, it crashes. Unable to automate using mobile app using cucumber with javascript, appium and webdriverIO

Attaching some screenshots for references

![Screenshot 2024-07-21 212909](https://github.com/user-attachments/assets/b0b6bedf-4601-4c19-8618-24bf00c62105)
![Screenshot 2024-07-21 213046](https://github.com/user-attachments/assets/17cc5c57-f7fd-4724-a797-43d1c3e0dfde)

### What is your expected behavior?

I should be able to start the app and do basic login automation using different data sets

### How to reproduce the bug.

.feature file code :

Feature: Login Functionality

  Scenario Outline: User logs in with differnet credentials
    Given Navigate to the Login Page 
    When After landing on login page, enter "<username>" and "<password>"
    And Click on the login button
    Then I should see the dashboard

    Examples:
      | username            | password  |
      | bob@example.com     | 10203040  |

step defination file code:

//const { Given, When, Then } = require('cucumber');
const { Given, When, Then } = require('@cucumber/cucumber');
const LoginPage = require('../Pages/Login');
const LandingPage = require('../Pages/LandingPage');
const Checkout = require('../Pages/Checkout');

//Given('The application is launched', () => {
//  LoginPage.open(); // Implement logic to launch the app
//});

Given('Navigate to the Login Page', async function() {
    await $('xpath://android.widget.TextView[@text="Products"]').waitForDisplayed({ timeout: 5000 });
    LandingPage.hamburgerClick();
    LandingPage.LoginClick();
})

When('After landing on login page, enter "<string>" and "<string>', (username, password) => {
  LoginPage.login(username, password);
});

And('Click on the login button', () =>
{
    LoginPage.loginbuttonClick();
})

Then('I should see the dashboard', () => {
  expect(Checkout.Validatetile).to.be.true;
});

### Relevant log output

```typescript
PS C:\Users\anup1\mobile-app-automation> npx wdio --spec .\step_definitions\Loginfeature.feature

Execution of 1 workers started at 2024-07-21T15:36:35.991Z

2024-07-21T15:36:36.008Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-07-21T15:36:36.009Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-07-21T15:36:36.011Z INFO @wdio/local-runner: Start worker 0-0 with arg: --spec,.\step_definitions\Loginfeature.feature
[0-0] 2024-07-21T15:36:37.125Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2024-07-21T15:36:37.377Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialized.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.       
[0-0] Spec file(s): file:///C:/Users/anup1/mobile-app-automation/step_definitions/Loginfeature.feature
[0-0] Error: Error: ERR_UNKNOWN_FILE_EXTENSION .feature C:\Users\anup1\mobile-app-automation\step_definitions\Loginfeature.feature
[0-0]     at defaultGetFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\dist-raw\node-internal-modules-esm-get_format.js:93:15)
[0-0]     at defer (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:296:7)
[0-0]     at entrypointFallback (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:304:22)
[0-0]     at getFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:338:26)
[0-0]     at C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:245:17      
[0-0]     at addShortCircuitFlag (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:409:21)
[0-0]     at load (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:239:12)
[0-0]     at nextLoad (node:internal/modules/esm/hooks:654:28)
[0-0]     at Hooks.load (node:internal/modules/esm/hooks:445:26)
[0-0]     at ESMLoader.load (node:internal/modules/esm/loader:337:38)
[0-0] RUNNING in Android - file:///C:/Users/anup1/mobile-app-automation/step_definitions/Loginfeature.feature
[0-0] 2024-07-21T15:36:37.378Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-07-21T15:36:37.378Z INFO @wdio/utils: Connecting to existing driver at http://0.0.0.0:4723/
[0-0] 2024-07-21T15:36:37.471Z INFO webdriver: [POST] http://0.0.0.0:4723/session
[0-0] 2024-07-21T15:36:37.471Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       platformName: 'Android',
[0-0]       'appium:deviceName': 'Android',
[0-0]       'appium:appPackage': 'com.saucelabs.mydemoapp.rn',
[0-0]       'appium:appActivity': 'com.saucelabs.mydemoapp.rn.MainActivity',
[0-0]       'appium:automationName': 'UiAutomator2'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     platformName: 'Android',
[0-0]     'appium:deviceName': 'Android',
[0-0]     'appium:appPackage': 'com.saucelabs.mydemoapp.rn',
[0-0]     'appium:appActivity': 'com.saucelabs.mydemoapp.rn.MainActivity',
[0-0]     'appium:automationName': 'UiAutomator2'
[0-0]   }
[0-0] }
[0-0] 2024-07-21T15:36:44.615Z ERROR @wdio/runner: Error: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialized.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.       
[0-0] Spec file(s): file:///C:/Users/anup1/mobile-app-automation/step_definitions/Loginfeature.feature
[0-0] Error: Error: ERR_UNKNOWN_FILE_EXTENSION .feature C:\Users\anup1\mobile-app-automation\step_definitions\Loginfeature.feature
[0-0]     at defaultGetFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\dist-raw\node-internal-modules-esm-get_format.js:93:15)
[0-0]     at defer (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:296:7)
[0-0]     at entrypointFallback (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:304:22)
[0-0]     at getFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:338:26)
[0-0]     at C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:245:17      
[0-0]     at addShortCircuitFlag (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:409:21)
[0-0]     at load (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:239:12)
[0-0]     at nextLoad (node:internal/modules/esm/hooks:654:28)
[0-0]     at Hooks.load (node:internal/modules/esm/hooks:445:26)
[0-0]     at ESMLoader.load (node:internal/modules/esm/loader:337:38)
[0-0]     at MochaAdapter._loadFiles (file:///C:/Users/anup1/mobile-app-automation/node_modules/@wdio/mocha-framework/build/index.js:91:35)
[0-0]     at async MochaAdapter.init (file:///C:/Users/anup1/mobile-app-automation/node_modules/@wdio/mocha-framework/build/index.js:66:9)
[0-0]     at async Object.adapterFactory.init (file:///C:/Users/anup1/mobile-app-automation/node_modules/@wdio/mocha-framework/build/index.js:222:22)
[0-0]     at async Runner.run (file:///C:/Users/anup1/mobile-app-automation/node_modules/@wdio/runner/build/index.js:83:27)
[0-0]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialized.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): file:///C:/Users/anup1/mobile-app-automation/step_definitions/Loginfeature.feature
Error: Error: ERR_UNKNOWN_FILE_EXTENSION .feature C:\Users\anup1\mobile-app-automation\step_definitions\Loginfeature.feature
    at defaultGetFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\dist-raw\node-internal-modules-esm-get_format.js:93:15)
    at defer (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:296:7)     
    at entrypointFallback (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:304:22)
    at getFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:338:26)
    at C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:245:17
    at addShortCircuitFlag (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:409:21)
    at load (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:239:12)     
    at nextLoad (node:internal/modules/esm/hooks:654:28)
    at Hooks.load (node:internal/modules/esm/hooks:445:26)
    at ESMLoader.load (node:internal/modules/esm/loader:337:38)
[0-0] 2024-07-21T15:36:44.616Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-07-21T15:36:44.617Z INFO webdriver: [DELETE] http://0.0.0.0:4723/session/cd719a4a-23c7-47ca-9626-3a5735347456
[0-0] 2024-07-21T15:36:45.211Z INFO webdriver: RESULT null
[0-0] FAILED in Android - file:///C:/Users/anup1/mobile-app-automation/step_definitions/Loginfeature.feature
2024-07-21T15:36:45.334Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-07-21T15:36:45.335Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:09

2024-07-21T15:36:45.336Z INFO @wdio/local-runner: Shutting down spawned worker
2024-07-21T15:36:45.587Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-07-21T15:36:45.588Z INFO @wdio/local-runner: shutting down
PS C:\Users\anup1\mobile-app-automation> npx wdio --spec .\step_definitions\Loginfeature.feature

Execution of 1 workers started at 2024-07-21T15:51:00.612Z

2024-07-21T15:51:00.630Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-07-21T15:51:00.631Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-07-21T15:51:00.632Z INFO @wdio/local-runner: Start worker 0-0 with arg: --spec,.\step_definitions\Loginfeature.feature
[0-0] 2024-07-21T15:51:01.750Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2024-07-21T15:51:01.982Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialized.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-0] Spec file(s): file:///C:/Users/anup1/mobile-app-automation/step_definitions/Loginfeature.feature
[0-0] Error: Error: ERR_UNKNOWN_FILE_EXTENSION .feature C:\Users\anup1\mobile-app-automation\step_definitions\Loginfeature.feature
[0-0]     at defaultGetFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\dist-raw\node-internal-modules-esm-get_format.js:93:15)
[0-0]     at defer (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:296:7)
[0-0]     at entrypointFallback (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:304:22)
[0-0]     at getFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:338:26)
[0-0]     at C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:245:17
[0-0]     at addShortCircuitFlag (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:409:21)
[0-0]     at load (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:239:12)
[0-0]     at nextLoad (node:internal/modules/esm/hooks:654:28)
[0-0]     at Hooks.load (node:internal/modules/esm/hooks:445:26)
[0-0]     at ESMLoader.load (node:internal/modules/esm/loader:337:38)
[0-0] RUNNING in Android - file:///C:/Users/anup1/mobile-app-automation/step_definitions/Loginfeature.feature
[0-0] 2024-07-21T15:51:01.983Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-07-21T15:51:01.983Z INFO @wdio/utils: Connecting to existing driver at http://0.0.0.0:4723/
[0-0] 2024-07-21T15:51:02.072Z INFO webdriver: [POST] http://0.0.0.0:4723/session
[0-0] 2024-07-21T15:51:02.072Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       platformName: 'Android',
[0-0]       'appium:deviceName': 'Android',
[0-0]       'appium:appPackage': 'com.saucelabs.mydemoapp.rn',
[0-0]       'appium:appActivity': 'com.saucelabs.mydemoapp.rn.MainActivity',
[0-0]       'appium:automationName': 'UiAutomator2'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     platformName: 'Android',
[0-0]     'appium:deviceName': 'Android',
[0-0]     'appium:appPackage': 'com.saucelabs.mydemoapp.rn',
[0-0]     'appium:appActivity': 'com.saucelabs.mydemoapp.rn.MainActivity',
[0-0]     'appium:automationName': 'UiAutomator2'
[0-0]   }
[0-0] }
[0-0] 2024-07-21T15:51:09.120Z ERROR @wdio/runner: Error: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialized.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-0] Spec file(s): file:///C:/Users/anup1/mobile-app-automation/step_definitions/Loginfeature.feature
[0-0] Error: Error: ERR_UNKNOWN_FILE_EXTENSION .feature C:\Users\anup1\mobile-app-automation\step_definitions\Loginfeature.feature
[0-0]     at defaultGetFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\dist-raw\node-internal-modules-esm-get_format.js:93:15)
[0-0]     at defer (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:296:7)
[0-0]     at entrypointFallback (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:304:22)
[0-0]     at getFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:338:26)
[0-0]     at C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:245:17
[0-0]     at addShortCircuitFlag (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:409:21)
[0-0]     at load (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:239:12)
[0-0]     at nextLoad (node:internal/modules/esm/hooks:654:28)
[0-0]     at Hooks.load (node:internal/modules/esm/hooks:445:26)
[0-0]     at ESMLoader.load (node:internal/modules/esm/loader:337:38)
[0-0]     at MochaAdapter._loadFiles (file:///C:/Users/anup1/mobile-app-automation/node_modules/@wdio/mocha-framework/build/index.js:91:35)
[0-0]     at async MochaAdapter.init (file:///C:/Users/anup1/mobile-app-automation/node_modules/@wdio/mocha-framework/build/index.js:66:9)
[0-0]     at async Object.adapterFactory.init (file:///C:/Users/anup1/mobile-app-automation/node_modules/@wdio/mocha-framework/build/index.js:222:22)
[0-0]     at async Runner.run (file:///C:/Users/anup1/mobile-app-automation/node_modules/@wdio/runner/build/index.js:83:27)
[0-0]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialized.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): file:///C:/Users/anup1/mobile-app-automation/step_definitions/Loginfeature.feature
Error: Error: ERR_UNKNOWN_FILE_EXTENSION .feature C:\Users\anup1\mobile-app-automation\step_definitions\Loginfeature.feature
    at defaultGetFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\dist-raw\node-internal-modules-esm-get_format.js:93:15)
    at defer (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:296:7)
    at entrypointFallback (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:304:22)
    at getFormat (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:338:26)
    at C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:245:17
    at addShortCircuitFlag (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:409:21)
    at load (C:\Users\anup1\mobile-app-automation\node_modules\ts-node\src\esm.ts:239:12)
    at nextLoad (node:internal/modules/esm/hooks:654:28)
    at Hooks.load (node:internal/modules/esm/hooks:445:26)
    at ESMLoader.load (node:internal/modules/esm/loader:337:38)
[0-0] 2024-07-21T15:51:09.123Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-07-21T15:51:09.123Z INFO webdriver: [DELETE] http://0.0.0.0:4723/session/4fa25000-819b-4615-a944-7637c20a604b
[0-0] 2024-07-21T15:51:09.699Z INFO webdriver: RESULT null
[0-0] FAILED in Android - file:///C:/Users/anup1/mobile-app-automation/step_definitions/Loginfeature.feature
2024-07-21T15:51:09.816Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-07-21T15:51:09.816Z INFO @wdio/cli:launcher: Run onComplete hook
2024-07-21T15:51:09.816Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:09
Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:09

2024-07-21T15:51:09.818Z INFO @wdio/local-runner: Shutting down spawned worker
2024-07-21T15:51:09.818Z INFO @wdio/local-runner: Shutting down spawned worker
2024-07-21T15:51:10.070Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-07-21T15:51:10.070Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ```ts
>         // Add other configurations as needed
>         specs: [
>             './step_definitions/**/*.feature'
>         ],
> ```

The `specs` property doesn't belong into the `cucumberOpts` object but is part of the main `WebdriverIO.Config`. See our [docs](https://webdriver.io/docs/configuration/#specs) for more information. I will go ahead and close this issue. Please join our [Discord](https://discord.webdriver.io) if you have further questions.
