### ISSUE TITLE
Can't pass certain mochaOpts

### ISSUE THREAD

**Issue by clample** [webdriverio/webdriverio#1321]
## The problem

I would like to use the mocha flag --no-timeouts, but it seems like I'm unable to set this option in mochaOpts. This option would be very useful to me and it would be nice to have more freedom in setting mocha options. I'm currently working around this by setting a high timeout in mochaOpts, but this isn't ideal.

## Environment

* WebdriverIO version: 4.0.7
* Node.js version:5.5.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
how do you set it?

**Comment by clample** [comment]
I'm trying to set it in my wdio.conf.js file. From the documentation, it looks like you give a key and then a value, for example: 
`mochaOpts: {
        ui: 'bdd'
 }`

I've tried `no-timeouts: true` and `noTimeouts: true`. Using `noTimeouts: true`, I still get failed tests from timeouts. Using `no-timouts: true` gives me:

`SyntaxError: Unexpected token -
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at ConfigParser.addConfigFile (/Users/chrislample/Documents/TestObject/PwC/node_modules/webdriverio/build/lib/utils/ConfigParser.js:116:62)
    at new Launcher (/Users/chrislample/Documents/TestObject/PwC/node_modules/webdriverio/build/lib/launcher.js:40:27)
    at Object.<anonymous> (/Users/chrislample/Documents/TestObject/PwC/node_modules/webdriverio/build/lib/cli.js:354:20)`

Thanks for the help. Maybe it's already possible to set this, but I haven't figured it out yet.

**Comment by clample** [comment]
I think that I've figured it out.

`mochaOpts:  {ui: 'bdd', enableTimeouts: false}`

solves the issue. Still, I'd like to set other mocha flags like --sort. The way that webdriver is calling mocha, mocha.opts file is never read. It would be nice to be able to have the mocha.opts file loaded. Maybe this is an issue that is best solved in mocha, though.

**Comment by christian-bromann** [comment]
Well some things like test annotation or test sorting have to be implemented within the wdio framework adapter. We are aware of that and will try to implement those things asap.

**Comment by clample** [comment]
Ah, ok. Thanks for the help Christian, I appreciate it!
