### ISSUE TITLE
[🐛 Bug]: Middleware interfering with API: waitForDisplayed({ reverse: true })

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#13253]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v8

### Node.js Version

20

### Mode

Standalone Mode

### What happened?

```ts
class MyPage {

  // A button to submit a form
  get submit(){ return $('#submit') }

  // A loading progress bar within the submit button that activates when submit is pressed
  get submitLoading(){ return this.submit.$('.loading') }

}
```

In my tests:

```ts
const myPage = new MyPage()

// Intent is to press the submit button and then wait for the loading to finish before moving on
myPage.submit.click()

// If the loading is finished very briefly the entire form disappears, therefore the submit button dissappears
// WDIO middleware cannot find the submit button, so it stalls until waitForTimeout is reached and then errors

myPage.submitLoading.waitForDisplayed({ reverse: true })
```

### What is your expected behavior?

If the API has an option to wait for an element to not be displayed (waitForDisplayed({ reverse: true })), and:
- the element was built by nesting of elements (ie. $('#submit').$('.loading'))
- a parent element no longer exists

Then waitForDisplayed should not error with a timeout waiting for a parent element to exist

### How to reproduce the bug.

```ts
class MyPage {

  // A button to submit a form
  get submit(){ return $('#submit') }

  // A loading progress bar within the submit button that activates when submit is pressed
  get submitLoading(){ return this.submit.$('.loading') }

}
```

In my tests:

```ts
const myPage = new MyPage()

// Intent is to press the submit button and then wait for the loading to finish before moving on
myPage.submit.click()

// If the loading is finished very briefly the entire form disappears, therefore the submit button dissappears
// WDIO middleware cannot find the submit button, so it stalls until waitForTimeout is reached and then errors

myPage.submitLoading.waitForDisplayed({ reverse: true })
```

### Relevant log output

```typescript
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SerhiiMaksymiv** [comment]
hi, having same with `waitForDisplayed({ reverse: true })` in v9

### WebdriverIO Version  
v9
### Node.js Version  
v20.18.3
### package.json  
```json
{
  "name": "js-wdio",
  "type": "module",
  "devDependencies": {
    "@wdio/allure-reporter": "^9.14.0",
    "@wdio/cli": "^9.14.0",
    "@wdio/cucumber-framework": "^9.14.0",
    "@wdio/dot-reporter": "^9.14.0",
    "@wdio/local-runner": "^9.14.0",
    "@wdio/spec-reporter": "^9.14.0",
    "@wdio/visual-service": "^8.0.2",
    "wdio-wait-for": "^3.1.0"
  },
  "scripts": {
    "wdio": "wdio run ./wdio.conf.js"
  }
}
```
  
### How to reproduce the bug  
- follow getting started guide [https://webdriver.io/docs/gettingstarted](https://webdriver.io/docs/gettingstarted):  
`npm init wdio@latest .`
- optionally you can apply settings that ive used, but dont think they matter in this case:  
```bash
✔ A project named "js-wdio" was detected at "/Users/mcs/repos/js-wdio", correct? yes
✔ What type of testing would you like to do? E2E Testing - of Web or Mobile Applications
✔ Where is your automation backend located? On my local machine
✔ Which environment you would like to automate? Web - web applications in the browser
✔ With which browser should we start? Chrome
✔ Which framework do you want to use? Cucumber (https://cucumber.io/)
✔ Do you want to use Typescript to write tests? no
✔ Do you want WebdriverIO to autogenerate some test files? yes
✔ What should be the location of your feature files? /Users/mcs/repos/js-wdio/features/**/*.feature
✔ What should be the location of your step definitions? /Users/mcs/repos/js-wdio/features/step-definitions/steps.js
✔ Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? yes
✔ Where are your page objects located? /Users/mcs/repos/js-wdio/features/pageobjects/**/*.js
✔ Which reporter do you want to use? spec, dot, allure
✔ Do you want to add a plugin to your test setup? wait-for: utilities that provide functionalities to wait for certain conditions till a defined task is complete.
   > https://www.npmjs.com/package/wdio-wait-for
✔ Would you like to include Visual Testing to your setup? For more information see https://webdriver.io/docs/visual-testing! yes
✔ Do you want to add a service to your test setup? visual
✔ Do you want me to run `npm install` yes
```
- add one action and one validation step into `./features/step-definitions/steps.js` file
```bash
.
├── features
│   ├── login.feature
│   ├── pageobjects
│   │   ├── login.page.js
│   │   ├── page.js
│   │   └── secure.page.js
│   └── step-definitions
│       └── steps.js
├── package-lock.json
├── package.json
```

```javascript
When(/^I close flash message$/, async () => {
    await SecurePage.flashCloseIcon.click() 
});

Then(/^I expect flash message is not displayed$/, async () => {
   await SecurePage.flashAlert.waitForDisplayed({ reverse: true }) 
});
```
- add close flash message locator into `./features/pageobjects/secure.page.js`
```javascript
  get flashCloseIcon() {
    return $('[class="close"]')
  }
``` 
- update feature file with newly added steps:  
```gherkin
    When I close flash message
    Then I expect flash message is not displayed
```
- run tests:  
```bash
npx wdio run ./wdio.conf.js
```

### What is your expected behavior?
After closing flash message `.waitForDisplayed({ reverse: true })` should pass

### What is actual behavior?
test fails indicating that the element is still displayed after 10 sec, even though its not visible, and not present in dom anymore:  
```bash
Error: element ("#flash") still displayed after 10000ms
    at <anonymous> (/Users/mcs/repos/js-wdio/node_modules/webdriverio/build/node.js:5714:15)
    at async Element.wrapCommandFn (/Users/mcs/repos/js-wdio/node_modules/@wdio/utils/build/index.js:907:23)
    at async Element.elementErrorHandlerCallbackFn (/Users/mcs/repos/js-wdio/node_modules/webdriverio/build/node.js:8397:24)
    at async Element.wrapCommandFn (/Users/mcs/repos/js-wdio/node_modules/@wdio/utils/build/index.js:907:23)
    at async Element.wrapCommandFn (/Users/mcs/repos/js-wdio/node_modules/@wdio/utils/build/index.js:907:23)
    at async Element.elementErrorHandlerCallbackFn (/Users/mcs/repos/js-wdio/node_modules/webdriverio/build/node.js:8397:24)
    at async Element.wrapCommandFn (/Users/mcs/repos/js-wdio/node_modules/@wdio/utils/build/index.js:907:23)
    at async World.<anonymous> (file:///Users/mcs/repos/js-wdio/features/step-definitions/steps.js:30:4)
```  
### Attachments:

<img width="1033" alt="Image" src="https://github.com/user-attachments/assets/4ced10d4-7fa0-478e-a180-8c7b0790ed85" />

**Comment by SerhiiMaksymiv** [comment]
ok, so taking my example above from `https://the-internet.herokuapp.com/login`, i think i found the reason as to why test fails, its the new `checkVisibility`. From mdn:
> The element doesn't have an associated box, for example because the CSS [display](https://developer.mozilla.org/en-US/docs/Web/CSS/display) property is set to [none](https://developer.mozilla.org/en-US/docs/Web/CSS/display#none) or [contents](https://developer.mozilla.org/en-US/docs/Web/CSS/display#contents).
    The element is not being rendered because the element or an ancestor element sets the [content-visibility](https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility) property to [hidden](https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility#hidden).

Dont know why `checkVisibility` was prioritized over `export default function isElementDisplayed (element: Element): boolean` implementation, but it broke half of the tests in our code base. 

Unfortunately, our devs using somewhat similar implementaion in react to hide elements and they are not that conscious about every bit of the app to use `content-visibility`. So the new `checkVisibility` does not cover cases that wdio previously did.

<img width="2067" alt="Image" src="https://github.com/user-attachments/assets/6a841362-373d-46ec-911c-3bb228615e9d" />

Here, even though the element is in the DOM, it has no content and thus `not displayed`.

For those wondering why `waitForDisplayed({ reverse: true })` doesn't work, i'd disappointedly suggest to not use this option in most cases.
