### ISSUE TITLE
Sending Shift Keys to Chrome browser not working in Chrome

### ISSUE THREAD

**Issue by smtripathi99** [webdriverio/webdriverio#13257]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

 capabilities: getRunOnSauce() === 'false' ?
        [{
            maxInstances: 1,
            browserName: 'chrome',
            acceptInsecureCerts: true,
            browserVersion: '126.0.6478.182',

        }] 

Services:  ['chromedriver', {
            logFileName: 'wdio-chromedriver.log', // default
            outputDir: 'driver-logs', // overwrites the config.outputDir
           chromedriverCustomPath: 'C:\\Users\\smtripat\\git\\master\\AmexOnline\\src\\test\\resources\\Browser_EXE\\ChromeDriver\\chromedriver.exe',
            args: ['--silent']
        }]

### What happened?
Open a url in chrome browser.

Sending key command like Shift and 6 not working. I need to send the keys to chrome browser not to any element.

### What is your expected behavior?

Sending key command like Shift and 6 should work 

### How to reproduce the bug.
   await browser.url('https://www.amextravel.com/car-searches/')
   //Manually press Shift 6 will give you this but via script it is not working 

   await browser.keys([Key.Shift,'6']); // \uE008  \uE020
   await browser.pause(1000);

![image](https://github.com/user-attachments/assets/a839d470-aef9-4982-82b4-fc475ed4bc6d)

### Relevant log output

```typescript
[0-0] 2024-08-02T21:55:06.874Z INFO webdriver: COMMAND performActions(<object>)
[0-0] 2024-08-02T21:55:06.877Z INFO webdriver: [POST] http://localhost:9515/session/76dc5777ce1e8cac9e22786002d2fab9/actions
[0-0] 2024-08-02T21:55:06.877Z INFO webdriver: DATA {
[0-0]   actions: [ { id: 'action2', type: 'key', parameters: {}, actions: [Array] } ]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> await browser.keys(['Shift','6']); // \uE008 \uE020

As recommend in [our docs](https://webdriver.io/docs/api/browser/keys) we recommend to use the `Key` object from the `webdriverio` package, e.g.:

```ts
import { Key } from 'webdriverio'
await browser.keys([Key.Shift, '6'])
```

Please make sure the element that is suppose to receive the event is active.

Mind providing us a reproducible example? I am not sure what I can do to help as WebdriverIO is only sending the protocol commands.

**Comment by smtripathi99** [comment]
I have added the reproducible example. Please check

**Comment by christian-bromann** [comment]
Thanks @smtripathi99 , I am not sure why the key commands are not triggering the modal. Any hints or suggestions are welcome.

**Comment by smtripathi99** [comment]
@christian-bromann 

There is an error : **TypeError: Cannot read properties of undefined (reading 'Shift')**
The command needs to send to the browser not to any element.

**Comment by christian-bromann** [comment]
Can you provide the full error?

**Comment by smtripathi99** [comment]
@christian-bromann 

[0-0] 2024-08-22T14:57:36.066Z INFO webdriver: RESULT null
[0-0] 2024-08-22T14:57:36.120Z INFO webdriver: COMMAND takeScreenshot()
[0-0] Error in "0: Then User will see the welcome screen for account type"
**TypeError: Cannot read properties of undefined (reading 'Shift')**
    at CommonBookingPage.getIZSession (C:\Users\smtripat\git\wdio\systemIntegration\pageObjects\/commonPage.js:123:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at World.<anonymous> (C:\Users\smtripat\git\wdio\systemIntegration\stepDefinitions\/commonPage.steps.js:45:5)
[0-0] 2024-08-22T14:57:36.124Z INFO webdriver: [GET] http://localhost:9515/session/a26bc9859c1ebe4bd130c3f46b4dc9a2/screenshot
[0-0] 2024-08-22T14:57:36.130Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-08-22T14:57:36.130Z INFO webdriver: [DELETE] http://localhost:9515/session/a26bc9859c1ebe4bd130c3f46b4dc9a2
[0-0] 2024-08-22T14:57:36.239Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAAB4AAAAMsCAIAAAA6USgXAAAAAXNSR0IArs4c6...
[0-0] 2024-08-22T14:57:36.351Z INFO webdriver: RESULT null

**Comment by christian-bromann** [comment]
How do you import `Key` in `C:\Users\smtripat\git\wdio\systemIntegration\pageObjects/commonPage.js`? Regardless of the error message I wasn't able to come up with a script to get the modal triggered. Any feedback and help investigating this would be appreciated.

**Comment by smtripathi99** [comment]
import { Key } from 'webdriverio'

**Comment by christian-bromann** [comment]
Without a reproducible example it is hard to say why this import fails or would return `undefined` for `Key`.
