### ISSUE TITLE
wdio + wdio-sauce-service fails in the 'onPrepare' hook

### ISSUE THREAD

**Issue by tony-pear** [webdriverio/webdriverio#1332]
## The problem
Trying to run wdio with sauce connect yields the following error:

./node_modules/.bin/wdio wdio.conf.js

A service failed in the 'onPrepare' hook
ReferenceError: Promise is not defined
    at SauceLaunchService.onPrepare (/home/ubuntu/webby/node_modules/wdio-sauce-service/build/sauce-launch-service.js:45:24)
    at /home/ubuntu/webby/node_modules/webdriverio/build/lib/launcher.js:330:58
    at Array.map (native)
    at Launcher.runServiceHook$ (/home/ubuntu/webby/node_modules/webdriverio/build/lib/launcher.js:328:80)
    at tryCatch (/home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:146:20)
    at /home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:191:11

Continue...

/home/ubuntu/webby/node_modules/webdriverio/build/lib/cli.js:359
            throw e;
                  ^
TypeError: Object #<Object> has no method 'isAbsolute'
    at /home/ubuntu/webby/node_modules/webdriverio/build/lib/utils/ConfigParser.js:316:50
    at Array.map (native)
    at Function.getFilePaths (/home/ubuntu/webby/node_modules/webdriverio/build/lib/utils/ConfigParser.js:315:43)
    at ConfigParser.getSpecs (/home/ubuntu/webby/node_modules/webdriverio/build/lib/utils/ConfigParser.js:237:38)
    at Launcher.run$ (/home/ubuntu/webby/node_modules/webdriverio/build/lib/launcher.js:238:58)
    at tryCatch (/home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:334:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:105:21)
    at tryCatch (/home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:72:40)
    at invoke (/home/ubuntu/webby/node_modules/webdriverio/node_modules/babel-runtime/regenerator/runtime.js:146:20)

## Environment

* WebdriverIO version:  v4.0.7
* Node.js version:  v4.4.4
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): 
  wdio-sauce-service@0.2.2
  wdio-mocha-framework@0.2.13

**Comment by christian-bromann** [comment]
WebdriverIO requires a NodeJS version bigger than `v0.10.x`. Please update your node and continue.
