### ISSUE TITLE
[🐛 Bug]: v9 fails in non-headless, incognito mode

### ISSUE THREAD

**Issue by zarko-tg** [webdriverio/webdriverio#13377]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9

### Node.js Version

20.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    'goog:chromeOptions': {
        args: ['incognito', 'disable-gpu']
    }
}
```

### What happened?

It seems that all tests fail when running non-headless and in incognito mode. The browser window(s) show and disappear quickly, sort of flashing. I used a macOS (14.6.1).

npm run test:local

> jasmine-boilerplate@1.0.0 test:local
> wdio run wdio.local.conf.ts

Execution of 3 workers started at 2024-08-16T14:12:50.600Z

[0-1] RUNNING in chrome - file:///test/specs/dynamic.spec.ts
[0-2] RUNNING in chrome - file:///test/specs/form.spec.ts
[0-0] RUNNING in chrome - file:///test/specs/checkbox.spec.ts
[0-1] FAILED in chrome - file:///test/specs/dynamic.spec.ts
[0-2] FAILED in chrome - file:///test/specs/form.spec.ts
[0-0] FAILED in chrome - file:///test/specs/checkbox.spec.ts

Spec Files:	 0 passed, 3 failed, 3 total (100% completed) in 00:00:05

### What is your expected behavior?

Regular execution and passing tests.

### How to reproduce the bug.

1. Clone https://github.com/webdriverio/jasmine-boilerplate and npm install.

2. Modify
diff --git a/wdio.local.conf.ts b/wdio.local.conf.ts
index 9a5ed83..83528fe 100644
--- a/wdio.local.conf.ts
+++ b/wdio.local.conf.ts
@@ -6,7 +6,7 @@ export const config: WebdriverIO.Config = {
         capabilities: [{
             browserName: 'chrome',
             'goog:chromeOptions': {
-                args: ['headless', 'disable-gpu']
+                args: ['incognito', 'disable-gpu']
             }
         }]
     }

3. npm run test:local

### Relevant log output

```typescript
**wdio.log:**

2024-08-16T14:12:50.606Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-08-16T14:12:50.606Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2024-08-16T14:12:50.607Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
2024-08-16T14:12:50.637Z INFO webdriver: Using Chromedriver v127.0.6533.120 from cache directory /var/folders/5m/zcxth49d19q9p2rc0w_0k48c0000gn/T
2024-08-16T14:12:50.665Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-08-16T14:12:50.665Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-08-16T14:12:50.665Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-08-16T14:12:50.666Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.local.conf.ts
2024-08-16T14:12:50.668Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
2024-08-16T14:12:50.668Z INFO @wdio/local-runner: Start worker 0-1 with arg: run,wdio.local.conf.ts
2024-08-16T14:12:50.668Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-1"
2024-08-16T14:12:50.668Z INFO @wdio/local-runner: Start worker 0-2 with arg: run,wdio.local.conf.ts
2024-08-16T14:12:50.669Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-2"
2024-08-16T14:12:55.686Z DEBUG @wdio/local-runner: Runner 0-1 finished with exit code 1
2024-08-16T14:12:55.687Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-08-16T14:12:55.707Z DEBUG @wdio/local-runner: Runner 0-2 finished with exit code 1
2024-08-16T14:12:55.707Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-08-16T14:12:55.712Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
2024-08-16T14:12:55.712Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-08-16T14:12:55.712Z INFO @wdio/cli:launcher: Run onComplete hook
2024-08-16T14:12:55.734Z INFO @wdio/local-runner: Shutting down spawned worker
2024-08-16T14:12:55.986Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully


**wdio-0-0-chromedriver.log:**

Starting ChromeDriver 127.0.6533.120 (c51f2916e4a14157c276fd33c8bfb24155aac1ad-refs/branch-heads/6533@{#2000}) on port 51950
Remote connections are allowed by an allowlist (0.0.0.0).
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.


**wdio-0-0.log:**
2024-08-16T14:12:51.156Z INFO @wdio/local-runner: Run worker command: run
2024-08-16T14:12:51.161Z DEBUG @wdio/runner: init remote session
2024-08-16T14:12:51.194Z DEBUG @wdio/runner: init remote session
2024-08-16T14:12:51.195Z INFO webdriver: Initiate new session using the WebDriver protocol
2024-08-16T14:12:51.226Z INFO webdriver: Using Chromedriver v127.0.6533.120 from cache directory /var/folders/5m/zcxth49d19q9p2rc0w_0k48c0000gn/T
2024-08-16T14:12:52.236Z INFO @wdio/utils: Started Chromedriver v127.0.6533.120 with params --port=51950 --allowed-origins=* --allowed-ips=0.0.0.0 in 1041ms on port 51950
2024-08-16T14:12:52.251Z INFO webdriver: [POST] http://localhost:51950/session
2024-08-16T14:12:52.251Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      'goog:chromeOptions': [Object],
      webSocketUrl: true
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': {
      binary: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
      args: [Array]
    },
    webSocketUrl: true
  }
}
2024-08-16T14:12:53.238Z DEBUG webdriver: request failed due to response error: unknown error
2024-08-16T14:12:53.238Z WARN webdriver: Request failed with status 500 due to unknown error: unhandled inspector error: {"code":-32000,"message":"Failed to open new tab - no browser is open"}
  (Session info: chrome=127.0.6533.120)
2024-08-16T14:12:53.238Z INFO webdriver: Retrying 1/3
2024-08-16T14:12:53.238Z INFO webdriver: [POST] http://localhost:51950/session
2024-08-16T14:12:53.238Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      'goog:chromeOptions': [Object],
      webSocketUrl: true
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': {
      binary: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
      args: [Array]
    },
    webSocketUrl: true
  }
}
2024-08-16T14:12:53.958Z DEBUG webdriver: request failed due to response error: unknown error
2024-08-16T14:12:53.958Z WARN webdriver: Request failed with status 500 due to unknown error: unhandled inspector error: {"code":-32000,"message":"Failed to open new tab - no browser is open"}
  (Session info: chrome=127.0.6533.120)
2024-08-16T14:12:53.958Z INFO webdriver: Retrying 2/3
2024-08-16T14:12:53.958Z INFO webdriver: [POST] http://localhost:51950/session
2024-08-16T14:12:53.958Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      'goog:chromeOptions': [Object],
      webSocketUrl: true
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': {
      binary: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
      args: [Array]
    },
    webSocketUrl: true
  }
}
2024-08-16T14:12:54.767Z DEBUG webdriver: request failed due to response error: unknown error
2024-08-16T14:12:54.767Z WARN webdriver: Request failed with status 500 due to unknown error: unhandled inspector error: {"code":-32000,"message":"Failed to open new tab - no browser is open"}
  (Session info: chrome=127.0.6533.120)
2024-08-16T14:12:54.767Z INFO webdriver: Retrying 3/3
2024-08-16T14:12:54.767Z INFO webdriver: [POST] http://localhost:51950/session
2024-08-16T14:12:54.767Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      'goog:chromeOptions': [Object],
      webSocketUrl: true
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': {
      binary: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
      args: [Array]
    },
    webSocketUrl: true
  }
}
2024-08-16T14:12:55.577Z DEBUG webdriver: request failed due to response error: unknown error
2024-08-16T14:12:55.577Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: unhandled inspector error: {"code":-32000,"message":"Failed to open new tab - no browser is open"}
  (Session info: chrome=127.0.6533.120)
2024-08-16T14:12:55.577Z ERROR webdriver: unknown error: unknown error: unhandled inspector error: {"code":-32000,"message":"Failed to open new tab - no browser is open"}
  (Session info: chrome=127.0.6533.120)
    at getErrorFromResponseBody (/Users/zarko/repos/ext/jasmine-boilerplate/node_modules/webdriver/build/index.js:996:10)
    at FetchRequest._request (/Users/zarko/repos/ext/jasmine-boilerplate/node_modules/webdriver/build/index.js:1304:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at startWebDriverSession (/Users/zarko/repos/ext/jasmine-boilerplate/node_modules/webdriver/build/index.js:906:16)
    at Function.newSession (/Users/zarko/repos/ext/jasmine-boilerplate/node_modules/webdriver/build/index.js:1502:41)
    at remote (/Users/zarko/repos/ext/jasmine-boilerplate/node_modules/webdriverio/build/index.js:6910:20)
    at async Runner._startSession (file:///Users/zarko/repos/ext/jasmine-boilerplate/node_modules/@wdio/runner/build/index.js:778:23)
    at async Runner._initSession (file:///Users/zarko/repos/ext/jasmine-boilerplate/node_modules/@wdio/runner/build/index.js:752:22)
    at async Runner.run (file:///Users/zarko/repos/ext/jasmine-boilerplate/node_modules/@wdio/runner/build/index.js:659:16)
2024-08-16T14:12:55.603Z ERROR @wdio/runner: Error: Failed to create session.
unknown error: unhandled inspector error: {"code":-32000,"message":"Failed to open new tab - no browser is open"}
  (Session info: chrome=127.0.6533.120)
    at startWebDriverSession (/Users/zarko/repos/ext/jasmine-boilerplate/node_modules/webdriver/build/index.js:910:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.newSession (/Users/zarko/repos/ext/jasmine-boilerplate/node_modules/webdriver/build/index.js:1502:41)
    at remote (/Users/zarko/repos/ext/jasmine-boilerplate/node_modules/webdriverio/build/index.js:6910:20)
    at async Runner._startSession (file:///Users/zarko/repos/ext/jasmine-boilerplate/node_modules/@wdio/runner/build/index.js:778:23)
    at async Runner._initSession (file:///Users/zarko/repos/ext/jasmine-boilerplate/node_modules/@wdio/runner/build/index.js:752:22)
    at async Runner.run (file:///Users/zarko/repos/ext/jasmine-boilerplate/node_modules/@wdio/runner/build/index.js:659:16)
2024-08-16T14:12:55.603Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting @zarko-tg 

WebDriver by default starts all browser sessions in an incognito mode. So there is no need to apply this browser argument. I pushed a patch to provide a better error message for this scenario.

**Comment by swfcjoel11** [comment]
Since upgrading to v9, I've encountered an issue where, when opening the Chrome browser and navigating to a login page, it automatically shows stored user accounts(this is a function of said login page). This behavior did not occur when using an incognito browser window, where saved accounts wouldn't be used so i could log in using a username and password. It seems as though the browser is somehow accessing my saved accounts even when it's supposed to be 'incognito'. 

And obviously trying to add the --incognito args now throws the following error as expected:` 'ERROR @wdio/runner: Error: Please remove "incognito" from `"goog:chromeOptions".args` as it is not supported running Chrome with WebDriver. WebDriver sessions are always incognito mode and do not persist across browser sessions.'`

**Comment by christian-bromann** [comment]
@swfcjoel11 every WebDriver session starts with an empty user profile so there shouldn't be any previous session information shown. Can you provide a reproduction case to further investigate this?

**Comment by swfcjoel11** [comment]
Thank you for the response. I understand that every WebDriver session should start with an empty user profile which is why it’s confusing here’s some additional context to help investigate:
	1.	Minimal Code Snippet:

describe('Login Page Test', () => {
    it('should navigate to the login page', async () => {
        await browser.url('https://example.com/login');
        await browser.debug();
    });
});


	2.	Environment Details:
	•	Browser: Chrome 131.0.6778.265
	•	WebdriverIO Version: v9.x
	•	Running on a Windows 10 machine
	3.	Observed Behavior:
When navigating to a login page, I see user account options (stored profiles) displayed, even though WebDriver sessions should be isolated. Clicking on a login button shows the saved accounts instead of taking me directly to the username/password input page.
	4.	Configuration:
I’ve tried using goog:chromeOptions to enforce incognito mode and prevent the use of saved profiles, but it didn’t resolve the issue. Here’s the configuration I’m using:

capabilities: [{
    browserName: 'chrome',
    'goog:chromeOptions': {
        args: ['--disable-blink-features=AutomationControlled']
    }
}]


	5.	Debugging Steps Attempted:
	•	Clearing cookies and localStorage within the session:

await browser.execute(() => {
    window.localStorage.clear();
    window.sessionStorage.clear();
});
await browser.deleteCookies();


	•	Explicitly setting wdio:enforceWebDriverClassic to disable BiDi and test classic WebDriver mode.
	•	Ensuring the userDataDir option is not being set to a custom directory.

Despite these attempts, the issue persists. I’m not sure how to reproduce this issue on another machine since it involves saved account data from my personal Chrome profile.

Could this behavior be related to how Chrome manages profiles or a specific browser version? Any guidance or additional troubleshooting steps would be greatly appreciated.

**Comment by swfcjoel11** [comment]
So i got to the bottom of my issue. I was using a site that required Microsoft login, and I noticed that even when running WebdriverIO in 'incognito' mode, it was still retaining login cookies and credentials. This meant that Microsoft would automatically sign me in on each test run, even though I expected a fresh session. Clearing cookies manually didn’t work. 

What fixed it for me was adding "--guest" into the chromeoptions (see below) 

```
 browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                "--guest"
            ]
        },
```
