### ISSUE TITLE
[🐛 Bug]: v9: Can't initialise new WDIO project with "yarn wdio create ." command

### ISSUE THREAD

**Issue by giuseppe-salvatore** [webdriverio/webdriverio#13380]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.1

### Node.js Version

22.6

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
None! I don't even get to the point of having a generated working config file. The error appears earlier
```

### What happened?

I just executed a simple command to initialise a new project. For most of the questions of the interactive configuration I have selected default the answer, only exception are for Typescript and Cucumber framework. I am using yarn instead of npm

`yarn create wdio .`

### What is your expected behavior?

The following command should run through completion and initialise a simple baseline project

`yarn create wdio .`

### How to reproduce the bug.

Run `yarn create wdio .` and use the following selections of the wizard:

===============================
🤖 WDIO Configuration Wizard 🧙
===============================

? A project named "tmp" was detected at "/home/workspace/webdriver.io/tmp", correct? yes
? What type of testing would you like to do? E2E Testing - of Web or Mobile Applications
? Where is your automation backend located? On my local machine
? Which environment you would like to automate? Web - web applications in the browser
? With which browser should we start? Chrome
? Which framework do you want to use? Cucumber (https://cucumber.io/)
? Do you want to use Typescript to write tests? yes
? Do you want WebdriverIO to autogenerate some test files? yes
? What should be the location of your feature files? /home/workspace/webdriver.io/tmp/features/**/*.feature
? What should be the location of your step definitions? /home/workspace/webdriver.io/tmp/features/step-definitions/steps.ts
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? yes
? Where are your page objects located? /home/workspace/webdriver.io/tmp/features/pageobjects/**/*.ts
? Which reporter do you want to use? 
? Do you want to add a plugin to your test setup? 
? Would you like to include Visual Testing to your setup? For more information see https://webdriver.io/docs/visual-testing! no
? Do you want to add a service to your test setup? 
? Do you want me to run `npm install` yes

### Relevant log output

```typescript
Regardless of the last selection of the config wizard (run npm install yes/no), I get the following error:

------------------------------------------------------------------------------

Setting up TypeScript...
✔ Success!

Installing packages using npm:
- @wdio/local-runner@latest
- @wdio/cucumber-framework@latest


npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.1.7: Glob versions prior to v9 are no longer supported
npm warn deprecated reflect-metadata@0.2.1: This version has a critical bug in fallback handling. Please upgrade to reflect-metadata@0.2.2 or newer.
npm warn deprecated reflect-metadata@0.2.1: This version has a critical bug in fallback handling. Please upgrade to reflect-metadata@0.2.2 or newer.
npm warn deprecated reflect-metadata@0.2.1: This version has a critical bug in fallback handling. Please upgrade to reflect-metadata@0.2.2 or newer.

added 117 packages, and audited 518 packages in 2s

104 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
✔ Success!

Creating a WebdriverIO config file...
wdio config

Initialize WebdriverIO and setup configuration in your current project.

Options:
      --version          Show version number                           [boolean]
      --watch            Run WebdriverIO in watch mode                 [boolean]
  -h, --hostname         automation driver host address                 [string]
  -p, --port             automation driver port                         [number]
      --path             path to WebDriver endpoints (default "/")      [string]
  -u, --user             username if using a cloud service as automation backend
                                                                        [string]
  -k, --key              corresponding access key to the user           [string]
  -l, --logLevel         level of logging verbosity
                  [choices: "trace", "debug", "info", "warn", "error", "silent"]
      --bail             stop test runner after specific amount of tests have fa
                         iled                                           [number]
      --baseUrl          shorten url command calls by setting a base url[string]
  -w, --waitforTimeout   timeout for all waitForXXX commands            [number]
  -s, --updateSnapshots  update DOM, image or test snapshots            [string]
  -f, --framework        defines the framework (Mocha, Jasmine or Cucumber) to r
                         un the specs                                   [string]
  -r, --reporters        reporters to print out the results on stdout    [array]
      --suite            overwrites the specs attribute and runs the defined sui
                         te                                              [array]
      --spec             run only a certain spec file - overrides specs piped fr
                         om stdin                                        [array]
      --exclude          exclude certain spec file from the test run - overrides
                          exclude piped from stdin                       [array]
      --repeat           Repeat specific specs and/or suites N times    [number]
      --mochaOpts        Mocha options
      --jasmineOpts      Jasmine options
      --cucumberOpts     Cucumber options
      --coverage         Enable coverage for browser runner
      --shard            Shard tests and execute only the selected shard. Specif
                         y in the one-based form like `--shard x/y`, where x is
                         the current and y the total shard.
      --yarn             Install packages via Yarn package manager.
                                                       [boolean] [default: true]
  -y, --yes              will fill in all config defaults without prompting
                                                      [boolean] [default: false]
  -t, --npmTag           define NPM tag to use for WebdriverIO related packages
                                                    [string] [default: "latest"]
      --help             Show help                                     [boolean]

Documentation: https://webdriver.io
@wdio/cli (v9.0.0)

Error: ⚠️ Couldn't write config file: Error: ENOENT: no such file or directory, open '/home/workspace/webdriver.io/tmp/node_modules/@wdio/cli/build/templates/wdio.conf.tpl.ejs'
    at Object.openSync (node:fs:561:18)
    at Object.readFileSync [as fileLoader] (node:fs:445:35)
    at fileLoader (/home/workspace/webdriver.io/tmp/node_modules/ejs/lib/ejs.js:293:18)
    at handleCache (/home/workspace/webdriver.io/tmp/node_modules/ejs/lib/ejs.js:233:16)
    at tryHandleCache (/home/workspace/webdriver.io/tmp/node_modules/ejs/lib/ejs.js:274:16)
    at exports.renderFile (/home/workspace/webdriver.io/tmp/node_modules/ejs/lib/ejs.js:491:10)
    at node:internal/util:435:21
    at new Promise (<anonymous>)
    at node:internal/util:421:12
    at createWDIOConfig (file:///home/workspace/webdriver.io/tmp/node_modules/@wdio/cli/build/index.js:1792:31)
    at createWDIOConfig (file:///home/workspace/webdriver.io/tmp/node_modules/@wdio/cli/build/index.js:1804:11)
    at async runConfigCommand (file:///home/workspace/webdriver.io/tmp/node_modules/@wdio/cli/build/index.js:2639:3)
    at async Object.handler (file:///home/workspace/webdriver.io/tmp/node_modules/@wdio/cli/build/index.js:2652:3)
error Command failed.
Exit code: 1
Command: wdio
Arguments: config
Directory: /home/gr4ce/workspace/webdriver.io/tmp
Output:

info Visit https://yarnpkg.com/en/docs/cli/exec for documentation about this command.


⚠️  Ups, something went wrong: Error calling: yarn exec wdio config --npm-tag latest!
error Command failed.
Exit code: 1
Command: /home/.yarn/bin/create-wdio
Arguments: .
Directory: /home/workspace/webdriver.io/tmp
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by giuseppe-salvatore** [comment]
Just checked and this file wdio.conf.tpl.ejs was available in previous version I used to generate a sample project (v8.39.1)

**Comment by christian-bromann** [comment]
@giuseppe-salvatore thanks for raising the issue. This is indeed a bug that was caused by us moving to Eslint and changing how the project gets build, let me send a fix for this.

**Comment by giuseppe-salvatore** [comment]
Just checked, it's all working nicely now. Thanks for the real quick bug fix

**Comment by giuseppe-salvatore** [comment]
Unfortunately stumbled upon a subsequent issue that will log in a minute after I verified it's genuine
