### ISSUE TITLE
[🐛 Bug]:  V9- The uploadFile command is not available in chrome-headless-shell

### ISSUE THREAD

**Issue by MahadevMG** [webdriverio/webdriverio#13390]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9

### Node.js Version

18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
        {
            maxInstances: 1,
            browserName: 'chrome',
            acceptInsecureCerts: true,
            'goog:chromeOptions': {
                args: [
                    'headless', 'disable-gpu',
                    '--window-size=1920,1080'
                ],
            },
        },
```

### What happened?

I am trying to upload a file to web app,  and its working fine in non headless mode, and fails when i enable headless

### What is your expected behavior?

Should work fine in both headless and non headlesss mode.

### How to reproduce the bug.

```js
    async uploadFile(file) {
        const filePath = path.join(process.cwd(), DEFAULT_FILEPATH, file);
        console.debug("File path: ", filePath);
        const remoteFilePath = await browser.uploadFile(filePath);
        await fileuploadPage.inputFileUpload.setValue(remoteFilePath);
        await fileuploadPage.submitButton.click();
    }

   await Utils.uploadFile("test.csv");
```

### Relevant log output

```typescript
wdio run ./wdio.conf.js


Execution of 1 workers started at 2024-08-19T10:24:17.056Z

Workspace ID conf:  5
[0-0] RUNNING in chrome - file:///src/test/specs/sanitySuite/test.dscreation.sanity.js
[0-0] File path:  /home/mahadev/Desktop/WDIO_V9_upgrade/ui_automation/src/utilities/files/Reorder.csv
[0-0] Error in "Mammoth Data Source Creation Sanity Tests.File upload @sanity"
Error: The uploadFile command is not available in chrome-headless-shell
    at async Utils.uploadFile (file:///home/mahadev/Desktop/WDIO_V9_upgrade/ui_automation/src/utilities/utils.js:63:32)
    at async Context.<anonymous> (file:///home/mahadev/Desktop/WDIO_V9_upgrade/ui_automation/src/test/specs/sanitySuite/test.dscreation.sanity.js:98:9)
[0-0] FAILED in chrome - file:///src/test/specs/sanitySuite/test.dscreation.sanity.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome-headless-shell 126.0.6478.126 linux #0-0] Running: chrome-headless-shell (v126.0.6478.126) on linux
[chrome-headless-shell 126.0.6478.126 linux #0-0] Session ID: 5b0e1cf78bc61aeeb43979a0a73bc7f6
[chrome-headless-shell 126.0.6478.126 linux #0-0]
[chrome-headless-shell 126.0.6478.126 linux #0-0] » /src/test/specs/sanitySuite/test.dscreation.sanity.js
[chrome-headless-shell 126.0.6478.126 linux #0-0] Mammoth Data Source Creation Sanity Tests
[chrome-headless-shell 126.0.6478.126 linux #0-0]    ✖ File upload @sanity
[chrome-headless-shell 126.0.6478.126 linux #0-0]
[chrome-headless-shell 126.0.6478.126 linux #0-0] 1 failing (14.8s)
[chrome-headless-shell 126.0.6478.126 linux #0-0]
[chrome-headless-shell 126.0.6478.126 linux #0-0] 1) Mammoth Data Source Creation Sanity Tests File upload @sanity
[chrome-headless-shell 126.0.6478.126 linux #0-0] The uploadFile command is not available in chrome-headless-shell
[chrome-headless-shell 126.0.6478.126 linux #0-0] Error: The uploadFile command is not available in chrome-headless-shell
[chrome-headless-shell 126.0.6478.126 linux #0-0]     at async Utils.uploadFile (file:///home/mahadev/Desktop/WDIO_V9_upgrade/ui_automation/src/utilities/utils.js:63:32)
[chrome-headless-shell 126.0.6478.126 linux #0-0]     at async Context.<anonymous> (file:///home/mahadev/Desktop/WDIO_V9_upgrade/ui_automation/src/test/specs/sanitySuite/test.dscreation.sanity.js:98:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by MahadevMG** [comment]
Sorry for making the noise.

This worked fine for me in both headless and noheadless mode. 

```js
    async uploadFile(file){
        const filePath = path.join(process.cwd(), DEFAULT_FILEPATH, file);
        console.debug(`File path: ${filePath}`);
        await fileuploadPage.inputFileUpload.addValue(filePath);
        await fileuploadPage.submitButton.click();
    }
```
