### ISSUE TITLE
[🐛 Bug]: V9: saveScreenshot within Jasmine expectationResultHandler function fails and throws error

### ISSUE THREAD

**Issue by DanLambe** [webdriverio/webdriverio#13418]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
Same capabilities as the local command within Jasmine Boilerplate project linked in the example/repro sections but just chrome.
{
  browserName: 'chrome'
}
```

### What happened?

After upgrading to Version 9 of WebdriverIO I noticed that upon failed tests and assertions that the screenShots directory which is usually full of screenshots in v8 was completely empty and that there was alot of new fetch errors throughout the console logs. I was able to repro this behavior within a forked version of the Jasmine Boilerplate project.

### What is your expected behavior?

I would expect the capability of taking screenshots on assertions and failures to persist regardless of version of have updated docs if the functionality or interface changed.

### How to reproduce the bug.

Pull down the fork and run the test:local script to reproduce the issue. The issue does occur in headless as well but throws the visible errors more obviously not in headless mode.
https://github.com/DanLambe/jasmine-boilerplate/tree/main

### Relevant log output

```typescript
[0-2] Error in "auth form should allow access with correct creds"
    at <Jasmine>
    at UserContext.<anonymous> (c:\Users\dan\repos\jasmine-boilerplate\test\specs\form.spec.ts:23:38)
[0-2] node:internal/deps/undici/undici:11372
[0-2]     Error.captureStackTrace(err, this);
[0-2]           ^
[0-2]
[0-2] TypeError: fetch failed
[0-2]     at Object.fetch (node:internal/deps/undici/undici:11372:11)
[0-2]     at FetchRequest._libRequest (c:/Users/sheer/repos/jasmine-boilerplate/node_modules/webdriverio/node_modules/webdriver/build/index.js:1354:24)
[0-2]     at FetchRequest._request (c:/Users/sheer/repos/jasmine-boilerplate/node_modules/webdriverio/node_modules/webdriver/build/index.js:1274:20)
[0-2]     at Browser.wrapCommandFn (c:/Users/sheer/repos/jasmine-boilerplate/node_modules/webdriverio/node_modules/@wdio/utils/build/index.js:1368:23)
[0-2]     at Browser.saveScreenshot (c:/Users/sheer/repos/jasmine-boilerplate/node_modules/webdriverio/build/index.js:3673:21)
[0-2]     at Browser.wrapCommandFn (c:/Users/sheer/repos/jasmine-boilerplate/node_modules/webdriverio/node_modules/@wdio/utils/build/index.js:1368:23) {
[0-2]   cause: Error: read ECONNRESET
[0-2]       at __node_internal_captureLargerStackTrace (node:internal/errors:497:5)
[0-2]       at __node_internal_errnoException (node:internal/errors:624:12)
[0-2]       at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
[0-2]     errno: -4077,
[0-2]     code: 'ECONNRESET',
[0-2]     syscall: 'read'
[0-2]   }
[0-2] }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@DanLambe thanks again for reporting the issue. Unfortunately this feature doesn't work anymore as we don't support synchronous commands in WebdriverIO. I pushed a PR that would remove the docs to avoid this confusion to happen in the future.
