### ISSUE TITLE
[🐛 Bug]: Upgrading from 8.40.3 to 9.0.4 causes electron window to close immediately after start

### ISSUE THREAD

**Issue by RedX2501** [webdriverio/webdriverio#13414]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.4

### Node.js Version

v20.11.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'electron',
        // Electron service options
        // see https://webdriver.io/docs/desktop-testing/electron/configuration/#service-options
        'wdio:electronServiceOptions': {
            appBinaryPath: "c:\\full\\path\\to\\my\\app.exe",
            // custom application args
            appArgs: []
        }
    }],
```

### What happened?

With version 8.40.3 the application window would open and the tests would execute normally.

After changing the versions of @wdio/{cli,local-runner,mocha-framework,spec-reporter} to 9.0.4 the electron main window will open and close immediately. It closes before anything is shown in the window. I only get to see the title bar for a very brief moment.

Changing back the versions to 8.40.3 and the tests work again.

I can execute the app without problems outside of the WDIO environment.

### What is your expected behavior?

That the tests still pass when upgrading the versions.

I do know there are some obsolete methods/selectors. I'm not using any of those. The error happens before any tests run.

### How to reproduce the bug.

I created a new testing environment using `npm init wdio@latest .` and the error happens when trying to test the app.

### Relevant log output

```console
> wdio
> wdio run ./wdio.conf.ts


Execution of 1 workers started at 2024-08-19T15:01:37.914Z

2024-08-19T15:01:38.365Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-08-19T15:01:38.431Z INFO electron-service: Found Electron v29.1.4 with Chromedriver v122.0.6261.129
2024-08-19T15:01:38.432Z INFO @wdio/utils: Setting up browser driver for: chrome@122.0.6261.129
2024-08-19T15:01:38.432Z INFO @wdio/utils: Setting up browser binaries for: chrome@122.0.6261.129
2024-08-19T15:01:38.433Z INFO webdriver: Downloading Chromedriver v122.0.6261.129
2024-08-19T15:01:38.525Z WARN webdriver: Chromedriver v122.0.6261.129 don't exist, trying to find known good version...
2024-08-19T15:01:38.668Z INFO webdriver: Download of Chromedriver v122.0.6261.128 was successful
2024-08-19T15:01:38.670Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-08-19T15:01:38.671Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] 2024-08-19T15:01:39.670Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///C:/data/_eev/testproj/test/specs/test.e2e.ts
[0-0] 2024-08-19T15:01:40.349Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-08-19T15:01:40.355Z INFO webdriver: Downloading Chromedriver v122.0.6261.129
[0-0] 2024-08-19T15:01:40.508Z WARN webdriver: Chromedriver v122.0.6261.129 don't exist, trying to find known good version...
[0-0] 2024-08-19T15:01:40.641Z INFO webdriver: Download of Chromedriver v122.0.6261.128 was successful
[0-0] 2024-08-19T15:01:40.662Z INFO chromedriver: Starting ChromeDriver 122.0.6261.128 (f18a44fedeb29764b2b5336c120fdd90ef1a3f5c-refs/branch-heads/6261@{#1057}) on port 54439
[0-0] 2024-08-19T15:01:40.662Z INFO chromedriver: Remote connections are allowed by an allowlist (0.0.0.0).
[0-0] 2024-08-19T15:01:40.662Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[0-0] 2024-08-19T15:01:40.665Z INFO chromedriver: ChromeDriver was started successfully.
[0-0] 2024-08-19T15:01:41.668Z INFO @wdio/utils: Started Chromedriver v122.0.6261.129 with params --port=54439 --allowed-origins=* --allowed-ips=0.0.0.0 in 1319ms on port 54439
[0-0] 2024-08-19T15:01:41.674Z INFO webdriver: [POST] http://localhost:54439/session
[0-0] 2024-08-19T15:01:41.674Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'wdio:electronServiceOptions': [Object],
[0-0]       'goog:chromeOptions': [Object],
[0-0]       browserVersion: '122.0.6261.129',
[0-0]       webSocketUrl: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'wdio:electronServiceOptions': {
[0-0]       appBinaryPath: 'c:\\full\\path\\to\\my\\app.exe',
[0-0]       appArgs: []
[0-0]     },
[0-0]     'goog:chromeOptions': {
[0-0]       binary: 'c:\\full\\path\\to\\my\\app.exe',
[0-0]       windowTypes: [Array],
[0-0]       args: []
[0-0]     },
[0-0]     browserVersion: '122.0.6261.129',
[0-0]     webSocketUrl: true
[0-0]   }
[0-0] }

[46176:0819/170141.721:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[46176:0819/170141.721:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[46176:0819/170141.721:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[46176:0819/170141.722:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.

DevTools listening on ws://127.0.0.1:54446/devtools/browser/177d59a9-5ba7-47bc-805e-57107396ba05
[46176:0819/170142.167:WARNING:keyboard_util.cc(281)] Invalid accelerator token: Numpad0
[46176:0819/170142.167:WARNING:accelerator_util.cc(65)] CmdOrCtrl+Numpad0 doesn't contain a valid key
Startup zoom: 0
[46176:0819/170142.261:INFO:CONSOLE(20)] "Launching Mapper instance with selfTargetId: A3AF273F653339A4329A3244A2666471", source:  (20)
[0-0] 2024-08-19T15:01:42.308Z WARN webdriver: Request failed with status 404 due to no such window
[0-0]   (Session info: chrome=122.0.6261.129)
[0-0] 2024-08-19T15:01:42.308Z INFO webdriver: Retrying 1/3
[0-0] 2024-08-19T15:01:42.308Z INFO webdriver: [POST] http://localhost:54439/session
[0-0] 2024-08-19T15:01:42.308Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'wdio:electronServiceOptions': [Object],
[0-0]       'goog:chromeOptions': [Object],
[0-0]       browserVersion: '122.0.6261.129',
[0-0]       webSocketUrl: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'wdio:electronServiceOptions': {
[0-0]       appBinaryPath: 'c:\\full\\path\\to\\my\\app.exe',
[0-0]       appArgs: []
[0-0]     },
[0-0]     'goog:chromeOptions': {
[0-0]       binary: 'c:\\full\\path\\to\\my\\app.exe',
[0-0]       windowTypes: [Array],
[0-0]       args: []
[0-0]     },
[0-0]     browserVersion: '122.0.6261.129',
[0-0]     webSocketUrl: true
[0-0]   }
[0-0] }

[41140:0819/170142.343:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[41140:0819/170142.343:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[41140:0819/170142.344:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[41140:0819/170142.344:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.

DevTools listening on ws://127.0.0.1:54457/devtools/browser/99e35fb3-54d6-4602-9fab-931b6111cee1
[41140:0819/170142.711:WARNING:keyboard_util.cc(281)] Invalid accelerator token: Numpad0
[41140:0819/170142.712:WARNING:accelerator_util.cc(65)] CmdOrCtrl+Numpad0 doesn't contain a valid key
Startup zoom: 0
[41140:0819/170142.842:INFO:CONSOLE(20)] "Launching Mapper instance with selfTargetId: E1FB3CCFA9808A75C755E006DF3F746A", source:  (20)
[0-0] 2024-08-19T15:01:42.877Z WARN webdriver: Request failed with status 404 due to no such window
[0-0]   (Session info: chrome=122.0.6261.129)
[0-0] 2024-08-19T15:01:42.877Z INFO webdriver: Retrying 2/3
[0-0] 2024-08-19T15:01:42.877Z INFO webdriver: [POST] http://localhost:54439/session
[0-0] 2024-08-19T15:01:42.877Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'wdio:electronServiceOptions': [Object],
[0-0]       'goog:chromeOptions': [Object],
[0-0]       browserVersion: '122.0.6261.129',
[0-0]       webSocketUrl: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'wdio:electronServiceOptions': {
[0-0]       appBinaryPath: 'c:\\full\\path\\to\\my\\app.exe',
[0-0]       appArgs: []
[0-0]     },
[0-0]     'goog:chromeOptions': {
[0-0]       binary: 'c:\\full\\path\\to\\my\\app.exe',
[0-0]       windowTypes: [Array],
[0-0]       args: []
[0-0]     },
[0-0]     browserVersion: '122.0.6261.129',
[0-0]     webSocketUrl: true
[0-0]   }
[0-0] }

[47088:0819/170142.915:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[47088:0819/170142.915:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[47088:0819/170142.915:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[47088:0819/170142.915:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.

DevTools listening on ws://127.0.0.1:54467/devtools/browser/9da72db3-277d-4cc9-a365-45034ee46dfa
[47088:0819/170143.288:WARNING:keyboard_util.cc(281)] Invalid accelerator token: Numpad0
[47088:0819/170143.288:WARNING:accelerator_util.cc(65)] CmdOrCtrl+Numpad0 doesn't contain a valid key
Startup zoom: 0
[47088:0819/170143.419:INFO:CONSOLE(20)] "Launching Mapper instance with selfTargetId: 4A8CF32675444B7E8A27E725B9A69B29", source:  (20)
[0-0] 2024-08-19T15:01:43.464Z WARN webdriver: Request failed with status 404 due to no such window
[0-0]   (Session info: chrome=122.0.6261.129)
[0-0] 2024-08-19T15:01:43.464Z INFO webdriver: Retrying 3/3
[0-0] 2024-08-19T15:01:43.464Z INFO webdriver: [POST] http://localhost:54439/session
[0-0] 2024-08-19T15:01:43.464Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'wdio:electronServiceOptions': [Object],
[0-0]       'goog:chromeOptions': [Object],
[0-0]       browserVersion: '122.0.6261.129',
[0-0]       webSocketUrl: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'wdio:electronServiceOptions': {
[0-0]       appBinaryPath: 'c:\\full\\path\\to\\my\\app.exe',
[0-0]       appArgs: []
[0-0]     },
[0-0]     'goog:chromeOptions': {
[0-0]       binary: 'c:\\full\\path\\to\\my\\app.exe',
[0-0]       windowTypes: [Array],
[0-0]       args: []
[0-0]     },
[0-0]     browserVersion: '122.0.6261.129',
[0-0]     webSocketUrl: true
[0-0]   }
[0-0] }

[44564:0819/170143.501:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[44564:0819/170143.501:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[44564:0819/170143.501:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[44564:0819/170143.501:ERROR:node_bindings.cc(376)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.

DevTools listening on ws://127.0.0.1:54478/devtools/browser/a3068c38-31d4-4beb-bb9a-b129fcf5fa3d
[44564:0819/170143.878:WARNING:keyboard_util.cc(281)] Invalid accelerator token: Numpad0
[44564:0819/170143.878:WARNING:accelerator_util.cc(65)] CmdOrCtrl+Numpad0 doesn't contain a valid key
Startup zoom: 0
[44564:0819/170144.005:INFO:CONSOLE(20)] "Launching Mapper instance with selfTargetId: A18ACDF2D85E1FA434A41EC8C827A205", source:  (20)
[0-0] 2024-08-19T15:01:44.038Z ERROR webdriver: Request failed with status 404 due to no such window: no such window
[0-0]   (Session info: chrome=122.0.6261.129)
[0-0] 2024-08-19T15:01:44.038Z ERROR webdriver: no such window: no such window
[0-0]   (Session info: chrome=122.0.6261.129)
[0-0]     at getErrorFromResponseBody (c:/data/_eev/testproj/node_modules/webdriver/build/index.js:996:10)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at startWebDriverSession (c:/data/_eev/testproj/node_modules/webdriver/build/index.js:906:16)
[0-0]     at Function.newSession (c:/data/_eev/testproj/node_modules/webdriver/build/index.js:1502:41)
[0-0]     at remote (c:/data/_eev/testproj/node_modules/webdriverio/build/index.js:6964:20)
[0-0]     at async Runner._startSession (file:///C:/data/_eev/testproj/node_modules/@wdio/runner/build/index.js:778:23)
[0-0]     at async Runner._initSession (file:///C:/data/_eev/testproj/node_modules/@wdio/runner/build/index.js:752:22)
[0-0]     at async Runner.run (file:///C:/data/_eev/testproj/node_modules/@wdio/runner/build/index.js:659:16)
[0-0] 2024-08-19T15:01:44.038Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] no such window
[0-0]   (Session info: chrome=122.0.6261.129)
[0-0]     at startWebDriverSession (c:/data/_eev/testproj/node_modules/webdriver/build/index.js:910:11)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at Function.newSession (c:/data/_eev/testproj/node_modules/webdriver/build/index.js:1502:41)
[0-0]     at remote (c:/data/_eev/testproj/node_modules/webdriverio/build/index.js:6964:20)
[0-0]     at async Runner._startSession (file:///C:/data/_eev/testproj/node_modules/@wdio/runner/build/index.js:778:23)
[0-0]     at async Runner._initSession (file:///C:/data/_eev/testproj/node_modules/@wdio/runner/build/index.js:752:22)
[0-0]     at async Runner.run (file:///C:/data/_eev/testproj/node_modules/@wdio/runner/build/index.js:659:16)
[0-0] 2024-08-19T15:01:44.039Z INFO HtmlReporter: onRunnerStart: 0-0
[0-0] 2024-08-19T15:01:44.040Z INFO HtmlReporter: onRunnerEnd: 0-0
[0-0] 2024-08-19T15:01:44.040Z INFO HtmlReporter: onRunnerEnd: 0-0 awaiting report generation
[0-0] 2024-08-19T15:01:44.041Z INFO ReportGenerator: Report Generation started
[0-0] 2024-08-19T15:01:44.041Z INFO ReportGenerator: Generated 1 specs, 0 suites,
[0-0] 2024-08-19T15:01:44.041Z INFO JsonGenerator: Json stringify starting: C:\data\_eev\testproj\reports\html-reports\report-0-0.json
[0-0] 2024-08-19T15:01:44.041Z ERROR ReportGenerator: Invalid Metrics computed: undefined -- undefined
[0-0] 2024-08-19T15:01:44.046Z INFO JsonGenerator: Json stringify complete
[0-0] 2024-08-19T15:01:44.047Z INFO JsonGenerator: Json write completed: C:\data\_eev\testproj\reports\html-reports\report-0-0.json
[0-0] 2024-08-19T15:01:44.047Z INFO HtmlGenerator: Html Generation started
[0-0] 2024-08-19T15:01:44.047Z INFO HtmlGenerator: Html Generation started in C:\data\_eev\testproj\node_modules\wdio-html-nice-reporter
[0-0] 2024-08-19T15:01:44.061Z INFO HtmlGenerator: Html Generation Completed
[0-0] 2024-08-19T15:01:44.061Z INFO ReportGenerator: Report Generation completed
[0-0] 2024-08-19T15:01:44.158Z INFO HtmlReporter: isSynchronized: true
[0-0] FAILED in chrome - file:///C:/data/_eev/testproj/test/specs/test.e2e.ts
2024-08-19T15:01:44.179Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-08-19T15:01:44.179Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:06

2024-08-19T15:01:44.180Z INFO @wdio/local-runner: Shutting down spawned worker
2024-08-19T15:01:44.438Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-08-19T15:01:44.439Z INFO @wdio/local-runner: shutting down
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@RedX2501 thanks again for reporting the issue. Please take a look at our [Electron boilerplate](https://github.com/webdriverio/electron-boilerplate) which we just updated to v9. Note: make sure you have `wdio-electron-service` set to `v7.0.0-beta.10`. Let me know if you have further questions.

**Comment by RedX2501** [comment]
I had actually wdio-electron-service set to `7.0.0-beta.9` because that's all what was available when I was testing. I'll try again with `beta.10`.

**Comment by RedX2501** [comment]
It seems to solve the startup problem.

Although the basic generated test fails:

```
describe('Electron Testing', () => {
    it('should print application title', async () => {
        await browser.pause(10_000); // Added so that the main window has time to load.
        console.log('Hello', await browser.getTitle(), 'application!')
    })
})

Error:

```
[0-0] 2024-08-20T06:51:03.421Z INFO webdriver: COMMAND getWindowHandles()
[0-0] 2024-08-20T06:51:03.421Z INFO webdriver: [GET] http://localhost:55479/session/d39baa3e59c3e5c9c8035d7328329e58/window/handles
[0-0] 2024-08-20T06:51:03.424Z INFO webdriver: RESULT [ '3F1FAD1B8DFC8444955D7546C4B2D76B' ]
[0-0] 2024-08-20T06:51:03.425Z INFO HtmlReporter: onRunnerStart: 0-0
[0-0] 2024-08-20T06:51:03.427Z INFO HtmlReporter: onHookStart: 0-0:hook-0-0
[0-0] 2024-08-20T06:51:03.427Z INFO HtmlReporter: onHookEnd: 0-0:hook-0-0
[0-0] 2024-08-20T06:51:03.428Z INFO HtmlReporter: onSuiteStart: 0-0:suite-0-0
[0-0] 2024-08-20T06:51:03.428Z INFO HtmlReporter: onTestStart: 0-0:test-00-0
[0-0] 2024-08-20T06:51:13.437Z INFO webdriver: COMMAND getTitle()
[0-0] 2024-08-20T06:51:13.437Z INFO webdriver: [GET] http://localhost:55479/session/d39baa3e59c3e5c9c8035d7328329e58/title
[0-0] 2024-08-20T06:51:13.442Z WARN webdriver: Request failed with status 404 due to no such window: target window already closed       
[0-0] from unknown error: web view not found
[0-0]   (Session info: chrome=122.0.6261.129)
[0-0] 2024-08-20T06:51:13.442Z INFO webdriver: Retrying 1/3
[0-0] 2024-08-20T06:51:13.442Z INFO webdriver: [GET] http://localhost:55479/session/d39baa3e59c3e5c9c8035d7328329e58/title
[0-0] 2024-08-20T06:51:13.444Z WARN webdriver: Request failed with status 404 due to no such window: target window already closed       
[0-0] from unknown error: web view not found
[0-0]   (Session info: chrome=122.0.6261.129)
[0-0] 2024-08-20T06:51:13.444Z INFO webdriver: Retrying 2/3
[0-0] 2024-08-20T06:51:13.444Z INFO webdriver: [GET] http://localhost:55479/session/d39baa3e59c3e5c9c8035d7328329e58/title
[0-0] 2024-08-20T06:51:13.446Z WARN webdriver: Request failed with status 404 due to no such window: target window already closed       
[0-0] from unknown error: web view not found
[0-0]   (Session info: chrome=122.0.6261.129)
[0-0] 2024-08-20T06:51:13.446Z INFO webdriver: Retrying 3/3
[0-0] 2024-08-20T06:51:13.446Z INFO webdriver: [GET] http://localhost:55479/session/d39baa3e59c3e5c9c8035d7328329e58/title
[0-0] 2024-08-20T06:51:13.447Z ERROR webdriver: Request failed with status 404 due to no such window: no such window: target window already closed
[0-0] from unknown error: web view not found
[0-0]   (Session info: chrome=122.0.6261.129)
[0-0] no such window in "Electron Testing.should print application title"
no such window: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=122.0.6261.129)
    at Context.<anonymous> (c:\data\_eev\testproj\test\specs\test.e2e.ts:6:30)
[0-0] 2024-08-20T06:51:13.448Z INFO HtmlReporter: onTestFail: 0-0:test-00-0
[0-0] 2024-08-20T06:51:13.449Z INFO HtmlReporter: onTestEnd: 0-0:test-00-0
[0-0] 2024-08-20T06:51:13.449Z INFO HtmlReporter: onSuiteEnd: 0-0:suite-0-0
[0-0] 2024-08-20T06:51:13.449Z INFO HtmlReporter: onHookStart: 0-0:hook-0-1
[0-0] 2024-08-20T06:51:13.449Z INFO HtmlReporter: onHookEnd: 0-0:hook-0-1
[0-0] 2024-08-20T06:51:13.449Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-08-20T06:51:13.450Z INFO webdriver: [DELETE] http://localhost:55479/session/d39baa3e59c3e5c9c8035d7328329e58
[0-0] 2024-08-20T06:51:13.486Z INFO webdriver: RESULT null
[0-0] 2024-08-20T06:51:13.486Z INFO webdriver: Kill driver process with PID 36272
[0-0] 2024-08-20T06:51:13.488Z INFO HtmlReporter: onRunnerEnd: 0-0
[0-0] 2024-08-20T06:51:13.488Z INFO HtmlReporter: onRunnerEnd: 0-0 awaiting report generation
[0-0] 2024-08-20T06:51:13.488Z INFO ReportGenerator: Report Generation started
[0-0] 2024-08-20T06:51:13.488Z INFO ReportGenerator: Included metrics for suite: 0-0 suite-0-0
[0-0] 2024-08-20T06:51:13.489Z INFO ReportGenerator: Generated 1 specs, 1 suites,
[0-0] 2024-08-20T06:51:13.489Z INFO JsonGenerator: Json stringify starting: C:\data\_eev\testproj\reports\html-reports\report-0-0.json  
[0-0] 2024-08-20T06:51:13.501Z INFO JsonGenerator: Json stringify complete
[0-0] 2024-08-20T06:51:13.502Z INFO JsonGenerator: Json write completed: C:\data\_eev\testproj\reports\html-reports\report-0-0.json     
[0-0] 2024-08-20T06:51:13.503Z INFO HtmlGenerator: Html Generation started
[0-0] 2024-08-20T06:51:13.503Z INFO HtmlGenerator: Html Generation started in C:\data\_eev\testproj\node_modules\wdio-html-nice-reporter[0-0] 2024-08-20T06:51:13.516Z INFO HtmlGenerator: Html Generation Completed
[0-0] 2024-08-20T06:51:13.517Z INFO ReportGenerator: Report Generation completed
[0-0] 2024-08-20T06:51:13.593Z INFO HtmlReporter: isSynchronized: true
[0-0] FAILED in chrome - file:///C:/data/_eev/testproj/test/specs/test.e2e.ts
2024-08-20T06:51:13.606Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-08-20T06:51:13.606Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 122.0.6261.129 windows #0-0] Running: chrome (v122.0.6261.129) on windows
[chrome 122.0.6261.129 windows #0-0] Session ID: d39baa3e59c3e5c9c8035d7328329e58
[chrome 122.0.6261.129 windows #0-0]
[chrome 122.0.6261.129 windows #0-0] » \test\specs\test.e2e.ts
[chrome 122.0.6261.129 windows #0-0] Electron Testing
[chrome 122.0.6261.129 windows #0-0]    ✖ should print application title
[chrome 122.0.6261.129 windows #0-0]
[chrome 122.0.6261.129 windows #0-0] 1 failing (10s)
[chrome 122.0.6261.129 windows #0-0]
[chrome 122.0.6261.129 windows #0-0] 1) Electron Testing should print application title
[chrome 122.0.6261.129 windows #0-0] no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=122.0.6261.129)
[chrome 122.0.6261.129 windows #0-0] no such window: no such window: target window already closed
[chrome 122.0.6261.129 windows #0-0] from unknown error: web view not found
[chrome 122.0.6261.129 windows #0-0]   (Session info: chrome=122.0.6261.129)
[chrome 122.0.6261.129 windows #0-0]     at Context.<anonymous> (c:\data\_eev\testproj\test\specs\test.e2e.ts:6:30)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:14
```

The project uses a splash screen that closes once the main window successfully connects to the backend.

**Comment by christian-bromann** [comment]
Can you raise an issue in the [`wdio-electron-service`](https://github.com/webdriverio-community/wdio-electron-service) project?
