### ISSUE TITLE
[🐛 Bug]: element not located in the shadow root nested element

### ISSUE THREAD

**Issue by govza** [webdriverio/webdriverio#13429]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.5

### Node.js Version

v20.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
defaults
```

### What happened?

selectors (css, tags) in the shadow roots are not located. Regression from v8 deep.

### What is your expected behavior?

element should be located

### How to reproduce the bug.

```js
import { expect, browser } from "@wdio/globals";

describe("Chrome page Shadow Root", () => {
  it("chrome downloads should work", async () => {
    await browser.url(`chrome://downloads/`);

    const downloadsTitle = browser.$("h1");
    
    // this works in v8 
    //const downloadsTitle = browser.$(">>>h1");
    // /html/body/downloads-manager//downloads-toolbar//cr-toolbar//div[1]/div/h1
    
    await expect(downloadsTitle).toBeExisting();
    await expect(downloadsTitle).toHaveText(
        expect.stringContaining("Download history")
      );
  });
});

```

[https://github.com/govza/shadow-root-test-v9/tree/master](https://github.com/govza/shadow-root-test-v9/tree/master)

### Relevant log output

```typescript
pnpm wdio   

> shadow-root-test-v9@ wdio D:\dev\forks\shadow-root-test-v9
> wdio run ./wdio.conf.js


Execution of 1 workers started at 2024-08-20T21:14:41.978Z

2024-08-20T21:14:41.992Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-08-20T21:14:41.993Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2024-08-20T21:14:41.994Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
2024-08-20T21:14:41.995Z INFO webdriver: Using Chromedriver v127.0.6533.120 from cache directory C:\Users\Go\AppData\Local\Temp
2024-08-20T21:14:41.997Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-08-20T21:14:41.998Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js
[0-0] 2024-08-20T21:14:43.011Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///D:/dev/forks/shadow-root-test-v9/test/specs/test.e2e.ts
[0-0] 2024-08-20T21:14:43.110Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-08-20T21:14:43.120Z INFO webdriver: Using Chromedriver v127.0.6533.120 from cache directory C:\Users\Go\AppData\Local\Temp
[0-0] 2024-08-20T21:14:43.136Z INFO chromedriver: Starting ChromeDriver 127.0.6533.120 (c51f2916e4a14157c276fd33c8bfb24155aac1ad-refs/branch-heads/6533@{#2000}) on port 65083
[0-0] 2024-08-20T21:14:43.137Z INFO chromedriver: Remote connections are allowed by an allowlist (0.0.0.0).
[0-0] 2024-08-20T21:14:43.137Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[0-0] 2024-08-20T21:14:43.139Z INFO chromedriver: ChromeDriver was started successfully.
[0-0] 2024-08-20T21:14:44.150Z INFO @wdio/utils: Started Chromedriver v127.0.6533.120 with params --port=65083 --allowed-origins=* --allowed-ips=0.0.0.0 in 1040ms on port 65083
[0-0] 2024-08-20T21:14:44.161Z INFO webdriver: [POST] http://localhost:65083/session
[0-0] 2024-08-20T21:14:44.162Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'goog:chromeOptions': [Object],
[0-0]       webSocketUrl: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': {
[0-0]       binary: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'
[0-0]     },
[0-0]     webSocketUrl: true
[0-0]   }
[0-0] }

DevTools listening on ws://127.0.0.1:65088/devtools/browser/8da6d81b-09df-45c5-8b6f-2daa53e632d4
[0-0] 2024-08-20T21:14:44.761Z INFO webdriver: Register BiDi handler for session with id 2697f4136dc51941b9848f68f6b903c6
[0-0] 2024-08-20T21:14:44.761Z INFO webdriver: Connect to webSocketUrl ws://127.0.0.1:65083/session/2697f4136dc51941b9848f68f6b903c6
[0-0] 2024-08-20T21:14:44.769Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-08-20T21:14:44.769Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-08-20T21:14:44.770Z INFO webdriver: Connected to WebDriver Bidi interface at ws://127.0.0.1:65083/session/2697f4136dc51941b9848f68f6b903c6
[0-0] 2024-08-20T21:14:44.770Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[761 bytes]>, contexts: undefined }
[0-0] 2024-08-20T21:14:44.772Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.navigationStarted","network.responseCompleted","network.beforeRequestSent","network.fetchError"]}
[0-0] 2024-08-20T21:14:44.772Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.userPromptOpened"]}
[0-0] 2024-08-20T21:14:44.772Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["log.entryAdded"]}
[0-0] 2024-08-20T21:14:44.783Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-08-20T21:14:44.784Z INFO webdriver: [GET] http://localhost:65083/session/2697f4136dc51941b9848f68f6b903c6/window
[0-0] 2024-08-20T21:14:44.785Z INFO webdriver: RESULT CCE158188FF1986C8D25FB378A5E5060
[0-0] 2024-08-20T21:14:44.786Z INFO webdriver: BIDI COMMAND browsingContext.navigate {"context":"CCE158188FF1986C8D25FB378A5E5060","url":"chrome://downloads/","wait":"complete"}
[0-0] 2024-08-20T21:14:44.893Z WARN webdriverio:ShadowRootManager: Expected element with shadow root but found <iron-iconset-svg />
[0-0] 2024-08-20T21:14:44.894Z WARN webdriverio:ShadowRootManager: Expected element with shadow root but found <iron-iconset-svg />
[0-0] 2024-08-20T21:14:44.894Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-iconset /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.8
[0-0] 2024-08-20T21:14:44.894Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-iconset /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.10
[0-0] 2024-08-20T21:14:44.895Z WARN webdriverio:ShadowRootManager: Expected element with shadow root but found <iron-iconset-svg />
[0-0] 2024-08-20T21:14:44.896Z WARN webdriverio:ShadowRootManager: Expected element with shadow root but found <iron-iconset-svg />
[0-0] 2024-08-20T21:14:44.897Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-icon /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.14
[0-0] 2024-08-20T21:14:44.897Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.15
[0-0] 2024-08-20T21:14:44.898Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-icon-button /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.15
[0-0] 2024-08-20T21:14:44.898Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.17
[0-0] 2024-08-20T21:14:44.898Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-toolbar-search-field /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.17
[0-0] 2024-08-20T21:14:44.898Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.19
[0-0] 2024-08-20T21:14:44.899Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.21
[0-0] 2024-08-20T21:14:44.899Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-toolbar /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.19
[0-0] 2024-08-20T21:14:44.899Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-icon /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.23
[0-0] 2024-08-20T21:14:44.899Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-icon-button /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.24
[0-0] 2024-08-20T21:14:44.899Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.24
[0-0] 2024-08-20T21:14:44.899Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.21
[0-0] 2024-08-20T21:14:44.900Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.21
[0-0] 2024-08-20T21:14:44.899Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-action-menu /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.27
[0-0] 2024-08-20T21:14:44.900Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <downloads-toolbar /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.21
[0-0] 2024-08-20T21:14:44.900Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <managed-footnote /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.31
[0-0] 2024-08-20T21:14:44.900Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.29
[0-0] 2024-08-20T21:14:44.900Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.29
[0-0] 2024-08-20T21:14:44.901Z WARN webdriverio:ShadowRootManager: Expected element with shadow root but found <array-selector />
[0-0] 2024-08-20T21:14:44.901Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.29
[0-0] 2024-08-20T21:14:44.901Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <iron-list /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.33
[0-0] 2024-08-20T21:14:44.901Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-toast /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.36
[0-0] 2024-08-20T21:14:44.902Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-toast-manager /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.37
[0-0] 2024-08-20T21:14:44.901Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.37
[0-0] 2024-08-20T21:14:44.902Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.29
[0-0] 2024-08-20T21:14:44.902Z ERROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.29
[0-0] 2024-08-20T21:14:44.902Z WARN webdriverio:ShadowRootManager: Expected element with shadow root but found <dom-if />
[0-0] 2024-08-20T21:14:44.902Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <cr-button /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.40
[0-0] 2024-08-20T21:14:44.902Z INFO webdriverio:ShadowRootManager: Registered new shadow root for element <downloads-manager /> with id f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.29
[0-0] 2024-08-20T21:14:44.905Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-08-20T21:14:44.905Z INFO webdriver: [GET] http://localhost:65083/session/2697f4136dc51941b9848f68f6b903c6/window
[0-0] 2024-08-20T21:14:44.907Z INFO webdriver: RESULT CCE158188FF1986C8D25FB378A5E5060
[0-0] 2024-08-20T21:14:44.908Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"h1"},"context":"CCE158188FF1986C8D25FB378A5E5060","startNodes":[{"sharedId":"f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.1"},{"sharedId":"f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.8"},{"sharedId":"f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.10"},{"sharedId":"f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.29"}]}
[0-0] 2024-08-20T21:14:44.918Z INFO webdriver: COMMAND getWindowHandle()
[... repeating ...]
[0-0] 2024-08-20T21:14:54.609Z INFO webdriver: [GET] http://localhost:65083/session/2697f4136dc51941b9848f68f6b903c6/window
[0-0] 2024-08-20T21:14:54.610Z INFO webdriver: RESULT CCE158188FF1986C8D25FB378A5E5060
[0-0] 2024-08-20T21:14:54.610Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"h1"},"context":"CCE158188FF1986C8D25FB378A5E5060","startNodes":[{"sharedId":"f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.1"},{"sharedId":"f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.8"},{"sharedId":"f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.10"},{"sharedId":"f.CCE158188FF1986C8D25FB378A5E5060.d.3D74E1FF089D7EEC5A223D7012DF7572.e.29"}]}
[0-0] Error in "Chrome page Shadow Root.chrome downloads should work"
Error: Expect $(`h1`) to be existing

Expected: "existing"
Received: "not existing"
    at Context.<anonymous> (D:\dev\forks\shadow-root-test-v9\test\specs\test.e2e.ts:13:34)
    at Context.executeAsync (D:\dev\forks\shadow-root-test-v9\node_modules\.pnpm\@wdio+utils@9.0.5\node_modules\@wdio\utils\build\index.js:1488:20)
    at Context.testFrameworkFnWrapper (D:\dev\forks\shadow-root-test-v9\node_modules\.pnpm\@wdio+utils@9.0.5\node_modules\@wdio\utils\build\index.js:1559:14)
[0-0] 2024-08-20T21:14:55.138Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-08-20T21:14:55.138Z INFO webdriver: [DELETE] http://localhost:65083/session/2697f4136dc51941b9848f68f6b903c6
[0-0] 2024-08-20T21:14:55.172Z INFO webdriver: RESULT null
[0-0] 2024-08-20T21:14:55.173Z INFO webdriver: Kill driver process with PID 10044
[0-0] FAILED in chrome - file:///D:/dev/forks/shadow-root-test-v9/test/specs/test.e2e.ts
2024-08-20T21:14:55.288Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-08-20T21:14:55.288Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:13

2024-08-20T21:14:55.289Z INFO @wdio/local-runner: Shutting down spawned worker
2024-08-20T21:14:55.555Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-08-20T21:14:55.556Z INFO @wdio/local-runner: shutting down
 ELIFECYCLE  Command failed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tkmcmaster** [comment]
This still seems to be broken for id's in 9.0.7. This worked in v8 bug fails in v9. Example:

```
        await browser.url("htts://example.com");

        // Create a shadowDom that we can look for
        const shadowResult = await browser.execute(() => {
          const locatorElement = document.querySelector("body div");
          if (!locatorElement) { return "failed"; }
          const shadowElement = locatorElement.appendChild(document.createElement("div"));
          shadowElement.id = "helloshadow";
          const shadowCreated = shadowElement.attachShadow({ mode: "open"});
          shadowCreated.innerHTML = `
              <p id='shadowelement'>Hello World</p>
              <button id='shadowbutton'>Shadow Button Clickable</button>
              <button id='shadowhidden' style='visibility: hidden;'>Button Hidden</button>
              <button id='shadowdisabled' disabled>Shadow Button Disabled</button>`;
          const shadowExists = document.querySelector("#helloshadow")?.shadowRoot;
          return shadowExists ? "created" : "failed";
        });
        expect(shadowResult, "created: " + JSON.stringify(shadowResult)).to.equal("created");
        const shadowRoot = await browser.execute(() =>
          document.querySelector("#helloshadow")?.shadowRoot != null
        );
        expect(shadowRoot, "shadowRoot: " + JSON.stringify(shadowRoot)).to.equal(true);
        const shadoElement = await browser.execute(() =>
          document.querySelector("#helloshadow")?.shadowRoot?.querySelector("#shadowelement") != null
        );
        log("shadoElement exists: " + shadoElement, LogLevel.WARN, shadoElement);
        expect(shadoElement, "shadowshadoElementRoot: " + JSON.stringify(shadoElement)).to.equal(true);
        await browser.$("#helloshadow").waitForDisplayed();
        await browser.$(">>>#shadowelement").waitForExist();
```

`document.querySelector("#helloshadow")?.shadowRoot?.querySelector("#shadowelement")` succeeds in finding the element but `await browser.$(">>>#shadowelement").waitForExist()` fails (and worked in v8).

**Comment by christian-bromann** [comment]
> `await browser.$(">>>#shadowelement").waitForExist()` fails (and worked in v8).

We don't recommend using the deep `>>>` selector anymore, instead just call `$("#shadowelement").waitForExist()`

**Comment by tkmcmaster** [comment]
Thanks for the reply @christian-bromann. I tried changing it to `await $("#shadowelement").waitForExist();` and I still get `element (\"#shadowelement\") still not existing after 10000ms`.

**Comment by christian-bromann** [comment]
@tkmcmaster can you provide a reproducible example?

**Comment by tkmcmaster** [comment]
Of course. https://github.com/tkmcmaster/webdriverio13429 on the main branch repros the error. I even added a catch to try without the `>>>` deep selector and both fail.

```
$ npm run wdio
...
[0-0] 2024-08-29T14:22:58.322Z INFO webdriverio:ContextManager: Update current context: D0B032B29CD9D44042FA98A029233CD7
[0-0] Error: element (">>>#shadowelement") still not existing after 10000ms
[0-0]     at <anonymous> (/home/mcmaster/webdriverio13429/node_modules/webdriverio/build/index.js:4348:15)
[0-0]     at Element.wrapCommandFn (/home/mcmaster/webdriverio13429/node_modules/@wdio/utils/build/index.js:1368:23)
[0-0]     at Element.elementErrorHandlerCallbackFn (/home/mcmaster/webdriverio13429/node_modules/webdriverio/build/index.js:6573:24)
[0-0]     at Element.wrapCommandFn (/home/mcmaster/webdriverio13429/node_modules/@wdio/utils/build/index.js:1368:23)
[0-0]     at Element.wrapCommandFn (/home/mcmaster/webdriverio13429/node_modules/@wdio/utils/build/index.js:1368:23)
[0-0]     at Element.elementErrorHandlerCallbackFn (/home/mcmaster/webdriverio13429/node_modules/webdriverio/build/index.js:6573:24)
[0-0]     at Element.wrapCommandFn (/home/mcmaster/webdriverio13429/node_modules/@wdio/utils/build/index.js:1368:23)
[0-0]     at Context.<anonymous> (/home/mcmaster/webdriverio13429/test/specs/test.e2e.ts:30:9)
[0-0]     at Context.executeAsync (/home/mcmaster/webdriverio13429/node_modules/@wdio/utils/build/index.js:1488:20)
[0-0]     at Context.testFrameworkFnWrapper (/home/mcmaster/webdriverio13429/node_modules/@wdio/utils/build/index.js:1559:14)
[0-0] Error in "My Login application.should login with valid credentials"
Error: element ("#shadowelement") still not existing after 10000ms
    at <anonymous> (/home/mcmaster/webdriverio13429/test/specs/test.e2e.ts:32:13)
    at Context.<anonymous> (/home/mcmaster/webdriverio13429/test/specs/test.e2e.ts:30:9)
[0-0] FAILED in chrome - file:///test/specs/test.e2e.ts
```

There's also a [webdriverio-v8](https://github.com/tkmcmaster/webdriverio13429/tree/webdriverio-v8) branch that only changes the webdriverIO version to v8 which passes:

```
$ npm run wdio
...
[chrome 127.0.6533.88 linux #0-0] Running: chrome (v127.0.6533.88) on linux
[chrome 127.0.6533.88 linux #0-0] Session ID: 70a872d1391c33be6e76e607411d1d1b
[chrome 127.0.6533.88 linux #0-0]
[chrome 127.0.6533.88 linux #0-0] » /test/specs/test.e2e.ts
[chrome 127.0.6533.88 linux #0-0] My Login application
[chrome 127.0.6533.88 linux #0-0]    ✓ should login with valid credentials
[chrome 127.0.6533.88 linux #0-0]
[chrome 127.0.6533.88 linux #0-0] 1 passing (645ms)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:02  
```

**Comment by christian-bromann** [comment]
@tkmcmaster thanks for pointing this out, we were indeed blind towards this (unusual) case where someone creates a shadow root manually via JS. I raised a PR to address the issue.
