### ISSUE TITLE
Error: Unrecognised test [test name] for suite [suite name]

### ISSUE THREAD

**Issue by nzhenry** [webdriverio/webdriverio#1343]
## The problem

"Error: Unrecognised test [test name] for suite [suite name]" when executing tests. Occurs when all of the following conditions are true:

- There are two suites with the same name
- The first suite has at least one implemented test
- The second suite has at least one pending test
- The second suite has no implemented tests

## Environment

* WebdriverIO version: 4.0.7
* Node.js version: 6.0.0
* [Standalone mode or wdio testrunner]: wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-mocha-framework

## Selenium/WebdriverIO logs

> Error: Unrecognised test [b] for suite [a]
    at Error (native)
    at ReporterStats.getTestStats (/Users/henry/dev/node/flags/test/node_modules/webdriverio/build/lib/utils/ReporterStats.js:292:49)
    at ReporterStats.output (/Users/henry/dev/node/flags/test/node_modules/webdriverio/build/lib/utils/ReporterStats.js:300:22)
    at BaseReporter.<anonymous> (/Users/henry/dev/node/flags/test/node_modules/webdriverio/build/lib/utils/BaseReporter.js:114:25)
    at emitOne (events.js:96:13)
    at BaseReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (/Users/henry/dev/node/flags/test/node_modules/webdriverio/build/lib/utils/BaseReporter.js:286:27)
    at Launcher.messageHandler (/Users/henry/dev/node/flags/test/node_modules/webdriverio/build/lib/launcher.js:471:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)

## Code To Reproduce Issue

[Archive.zip](https://github.com/webdriverio/webdriverio/files/282916/Archive.zip)

**Comment by christian-bromann** [comment]
I think it is because you have an test block without function:

```js
it('d');
```

just fix it like this:

```js
it('d', function() {});
```

**Comment by nzhenry** [comment]
Sorry, I think you've been a bit quick to close this issue. It's not because I have a test block without a function. If I remove the function from the test in the first suite, it works. Mocha should treat tests with only a string and no function passed in as "pending".

If you were suggesting a possible workaround, then you are right, but I think this issue should stay open regardless because it is a valid bug.

**Comment by christian-bromann** [comment]
As you can see I created an issue in a different project where the bug should get fixed. 😉

**Comment by nzhenry** [comment]
OK but your description in the new issue is incomplete. I will add a comment there.

**Comment by christian-bromann** [comment]
I referenced it back to this issue so I should have all information

**Comment by christian-bromann** [comment]
This is fixed by https://github.com/webdriverio/wdio-sync/commit/0fd145b4e8ba086556901dfd4063e5e05bf39d99 I tried running a test with `it("titile");` and it marked the test as pending.
