### ISSUE TITLE
[🐛 Bug]: `$('body')` returns no results in v9

### ISSUE THREAD

**Issue by gethinwebster** [webdriverio/webdriverio#13440]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.7

### Node.js Version

20.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        // capabilities for local browser web tests
        browserName: 'chrome', // or "firefox", "microsoftedge", "safari"
        'goog:chromeOptions': {
            args: ['--headless']
        }
    }],
```

### What happened?

Querying the selector `body` returns no results in v9. Reverting to v8 returns results. Querying using XPath `//body` also returns results.

### How to reproduce the bug.

Create a new project using `npm init wdio@latest`, then try to run the following test

```
import { expect, browser, $ } from '@wdio/globals'

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await browser.url(`https://the-internet.herokuapp.com/login`)

        await expect($('body').getProperty('tagName')).resolves.toBe('BODY');
    })
})
```

Configuration wizard output for reference:

```
🤖 WDIO Configuration Wizard 🧙
===============================

? A project named "wdio-testing" was detected at "/Users/gethinw/webdriver-upgrade/wdio-testing", correct? yes
? What type of testing would you like to do? E2E Testing - of Web or Mobile Applications
? Where is your automation backend located? On my local machine
? Which environment you would like to automate? Web - web applications in the browser
? With which browser should we start? 
? Which framework do you want to use? Mocha (https://mochajs.org/)
? Do you want to use Typescript to write tests? yes
? Do you want WebdriverIO to autogenerate some test files? yes
? What should be the location of your spec files? /Users/gethinw/webdriver-upgrade/wdio-testing/test/specs/**/*.ts
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? no
? Which reporter do you want to use? 
? Do you want to add a plugin to your test setup? 
? Would you like to include Visual Testing to your setup? For more information see https://webdriver.io/docs/visual-testing! no
? Do you want to add a service to your test setup? 
? Do you want me to run `npm install` yes
```

### Relevant log output

```typescript
> wdio
> wdio run ./wdio.conf.ts


Execution of 1 workers started at 2024-08-23T07:33:11.529Z

2024-08-23T07:33:11.552Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-08-23T07:33:11.553Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2024-08-23T07:33:11.555Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
2024-08-23T07:33:11.659Z INFO webdriver: Using Chromedriver v128.0.6613.84 from cache directory /var/folders/2d/t4t0kjks3szgzsn7zw87ys4r0000gr/T
2024-08-23T07:33:11.753Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-08-23T07:33:11.754Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] 2024-08-23T07:33:12.645Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///test/specs/test.e2e.ts
[0-0] 2024-08-23T07:33:12.765Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-08-23T07:33:12.859Z INFO webdriver: Using Chromedriver v128.0.6613.84 from cache directory /var/folders/2d/t4t0kjks3szgzsn7zw87ys4r0000gr/T
[0-0] 2024-08-23T07:33:12.882Z INFO chromedriver: Starting ChromeDriver 128.0.6613.84 (606aa55c7d687518d34b55accc5a71ea0bd28727-refs/branch-heads/6613@{#1335}) on port 50711
[0-0] 2024-08-23T07:33:12.883Z INFO chromedriver: Remote connections are allowed by an allowlist (0.0.0.0).
[0-0] 2024-08-23T07:33:12.883Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[0-0] 2024-08-23T07:33:12.886Z INFO chromedriver: ChromeDriver was started successfully on port 50711.
[0-0] 2024-08-23T07:33:13.875Z INFO @wdio/utils: Started Chromedriver v128.0.6613.84 with params --port=50711 --allowed-origins=* --allowed-ips=0.0.0.0 in 1110ms on port 50711
[0-0] 2024-08-23T07:33:13.894Z INFO webdriver: [POST] http://localhost:50711/session
[0-0] 2024-08-23T07:33:13.894Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'goog:chromeOptions': [Object],
[0-0]       webSocketUrl: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
[0-0]       args: [Array]
[0-0]     },
[0-0]     webSocketUrl: true
[0-0]   }
[0-0] }
[0-0] 2024-08-23T07:33:15.581Z INFO webdriver: Register BiDi handler for session with id ca26957fb23a67c0476d75909f1765ed
[0-0] 2024-08-23T07:33:15.581Z INFO webdriver: Connect to webSocketUrl ws://127.0.0.1:50711/session/ca26957fb23a67c0476d75909f1765ed
[0-0] 2024-08-23T07:33:15.602Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-08-23T07:33:15.602Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-08-23T07:33:15.603Z INFO webdriver: Connected to WebDriver Bidi interface at ws://127.0.0.1:50711/session/ca26957fb23a67c0476d75909f1765ed
[0-0] 2024-08-23T07:33:15.604Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[868 bytes]>, contexts: undefined }
[0-0] 2024-08-23T07:33:15.606Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.navigationStarted","network.responseCompleted","network.beforeRequestSent","network.fetchError"]}
[0-0] 2024-08-23T07:33:15.606Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.userPromptOpened"]}
[0-0] 2024-08-23T07:33:15.606Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.navigationStarted"]}
[0-0] 2024-08-23T07:33:15.607Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["log.entryAdded"]}
[0-0] 2024-08-23T07:33:15.641Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-08-23T07:33:15.642Z INFO webdriver: [GET] http://localhost:50711/session/ca26957fb23a67c0476d75909f1765ed/window
[0-0] 2024-08-23T07:33:15.649Z INFO webdriver: RESULT B907A62AEB23A0CCEEB6335EC9097BDB
[0-0] 2024-08-23T07:33:15.650Z INFO webdriver: BIDI COMMAND browsingContext.navigate {"context":"B907A62AEB23A0CCEEB6335EC9097BDB","url":"https://the-internet.herokuapp.com/login","wait":"complete"}
[0-0] 2024-08-23T07:33:15.670Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-08-23T07:33:15.671Z INFO webdriver: [GET] http://localhost:50711/session/ca26957fb23a67c0476d75909f1765ed/window
[0-0] 2024-08-23T07:33:15.678Z INFO webdriver: RESULT B907A62AEB23A0CCEEB6335EC9097BDB
[0-0] 2024-08-23T07:33:15.678Z INFO webdriverio:ContextManager: Update current context: B907A62AEB23A0CCEEB6335EC9097BDB
[0-0] 2024-08-23T07:33:17.441Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:17.451Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:17.951Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:18.451Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:18.950Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:19.450Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:19.951Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:20.452Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:20.951Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:21.450Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:21.951Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:22.452Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:22.951Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:23.451Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:23.952Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:24.450Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:24.950Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:25.450Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:25.952Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:26.450Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:26.951Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] 2024-08-23T07:33:27.451Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"body"},"context":"B907A62AEB23A0CCEEB6335EC9097BDB"}
[0-0] Error in "My Login application.should login with valid credentials"
Error: expect(received).resolves.toBe()

Received promise rejected instead of resolved
Rejected to value: [Error: Can't call getProperty on element with selector "body" because element wasn't found]
    at expect (/Users/XXX/webdriver-upgrade/wdio-testing/node_modules/expect/build/index.js:113:15)
    at Context.<anonymous> (/Users/XXX/webdriver-upgrade/wdio-testing/test/specs/test.e2e.ts:7:15)
[0-0] 2024-08-23T07:33:27.472Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-08-23T07:33:27.472Z INFO webdriver: [DELETE] http://localhost:50711/session/ca26957fb23a67c0476d75909f1765ed
[0-0] 2024-08-23T07:33:27.583Z INFO webdriver: RESULT null
[0-0] 2024-08-23T07:33:27.583Z INFO webdriver: Kill driver process with PID 45107
[0-0] FAILED in chrome - file:///test/specs/test.e2e.ts
2024-08-23T07:33:27.700Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-08-23T07:33:27.700Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:16  

2024-08-23T07:33:27.701Z INFO @wdio/local-runner: Shutting down spawned worker
2024-08-23T07:33:27.952Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-08-23T07:33:27.952Z INFO @wdio/local-runner: shutting down
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising this issue. It seems that this is a bug in Chrome, I raised an issue with the WebDriver Bidi spec: https://github.com/w3c/webdriver-bidi/issues/764

**Comment by christian-bromann** [comment]
This turned out to be a bug in Chromium and was fixed there. At this point there is nothing we can do about this in WebdriverIO. It may be already resolved using latest Canary build and will be available eventually also in stable Chrome.

**Comment by mo** [comment]
I just upgraded to 9.x and immediately hit this bug as well. I was able to workaround the issue by adding browserVersion: 'canary' to my wdio config though:
![image](https://github.com/user-attachments/assets/0a95cdea-5020-4f28-ac83-07805d5ac056)
