### ISSUE TITLE
Error while running view coverage using @wdio/browser-runner.

### ISSUE THREAD

**Issue by aramya1702** [webdriverio/webdriverio#13441]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.40.2

### Node.js Version

v16

### Mode

Standalone Mode

### What happened?

Hi Team,
we are trying to generate istanbul coverage report for view test cases. 
below is our config file looks like and framework is of Jasmine.
-----
export const config = {
...defaultConfig,
//...
runner:['browser',{
      coverage: {
           enabled: true,
                      }
                  }]
}
-----
while running we have got the below issue. Can anyone please let us know the workaround pr solution to get the coverage report.

Currently only "mocha" is supported as framework when using @wdio/browser-runner.
[test]     at new BrowserRunner (file:///T:/wdio/Web/App/test/node_modules/@wdio/browser-runner/build/index.js:30:19)
[test]     at Launcher.run (file:///T:/wdio/Web/App/test/node_modules/@wdio/cli/build/launcher.js:71:23).

### How to reproduce the bug.

-----
export const config = {
...defaultConfig,
//...
runner:['browser',{
      coverage: {
           enabled: true,
                      }
                  }]
}
-----

### Relevant log output

```typescript
Currently only "mocha" is supported as framework when using @wdio/browser-runner.
[test]     at new BrowserRunner (file:///T:/wdio/Web/App/test/node_modules/@wdio/browser-runner/build/index.js:30:19)
[test]     at Launcher.run (file:///T:/wdio/Web/App/test/node_modules/@wdio/cli/build/launcher.js:71:23).
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Closing due to inactivity.
