### ISSUE TITLE
[🐛 Bug]: Cannot run iOS specs on Browserstack after upgrade to wdio v9

### ISSUE THREAD

**Issue by berekmerilorand** [webdriverio/webdriverio#13477]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.7

### Node.js Version

20.10.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
browserstack: {
        capabilities: [
            {
                exclude: [
                    '../../../e2e/shared/**/*.android.test.ts',
                    '../tests/**/*.android.test.ts',
                ],
                'appium:app': `bs://${BROWSERSTACK_APP_ID}`,
                platformName: DEVICE_OS,
                'appium:deviceName': 'iPhone 15 Pro',
                'appium:newCommandTimeout': Constants.WAIT_TIME_WORKERS_MS,
                'appium:fullReset': true,
                'appium:shouldTerminateApp': true,
                'bstack:options': {
                    projectName: '[e2e] iOS',
                    sessionName: CIRCLE_JOB,
                    buildName: CIRCLE_BRANCH,
                    networkLogs: 'true',
                    appiumVersion: '2.6.0', (highest version provided by BS)
                    midSessionInstallApps: [`bs://${BROWSERSTACK_APP_ID}`],
                },
            },
        ],
    },
```

### What happened?

I'm receiving the below error when I'm trying to run iOS specs on Browserstack. 

* Node `v20.10.0` - tried with older and newer but I met the exact same issue
* Appium `v2.11.3` (latest) - tried with older (the highest version provided by BS is `v2.6.0`)
* xcuitest `7.24.18` (latest) - tried with older
* uiautomator2 `3.7.7` (latest) - tried with older

Local error:
```
[0-0] 2024-08-28T11:49:12.322Z ERROR webdriver: Error: Failed to fetch https://hub-cloud.browserstack.com/wd/hub/session: [object Object]
[0-0]     at FetchRequest._libRequest (/Users/lorandberekmeri/git/node_modules/webdriver/build/index.js:1373:15)
[0-0]     at FetchRequest._request (/Users/lorandberekmeri/git/node_modules/webdriver/build/index.js:1280:20)
[0-0]     at startWebDriverSession (/Users/lorandberekmeri/git/node_modules/webdriver/build/index.js:895:16)
[0-0]     at Function.newSession (/Users/lorandberekmeri/git/node_modules/webdriver/build/index.js:1508:41)
[0-0]     at remote (/Users/lorandberekmeri/git/node_modules/webdriverio/build/index.js:7043:20)
[0-0]     at async Runner._startSession (file:///Users/lorandberekmeri/git/node_modules/@wdio/runner/build/index.js:778:23)
[0-0]     at async Runner._initSession (file:///Users/lorandberekmeri/git/node_modules/@wdio/runner/build/index.js:752:22)
[0-0]     at async Runner.run (file:///Users/lorandberekmeri/git/node_modules/@wdio/runner/build/index.js:659:16)
```

CircleCI job error:
```
[0-0] RUNNING in ios - file:///e2e/tests/specs/ads/ad_cards/verifyAdCard.SwitchLayout.test.ts
[0-0] 2024-08-28T08:53:50.254Z ERROR @wdio/utils:shim: TypeError: fetch failed
[0-0]     at Object.fetch (node:internal/deps/undici/undici:11730:11)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at FetchRequest._libRequest (/home/circleci/project/node_modules/webdriver/build/index.js:1360:24)
[0-0]     at FetchRequest._request (/home/circleci/project/node_modules/webdriver/build/index.js:1280:20)
[0-0]     at Browser.wrapCommandFn (/home/circleci/project/node_modules/@wdio/utils/build/index.js:1368:23)
[0-0]     at Browser.saveScreenshot (/home/circleci/project/node_modules/webdriverio/build/index.js:3745:20)
[0-0]     at Browser.wrapCommandFn (/home/circleci/project/node_modules/@wdio/utils/build/index.js:1368:23)
[0-0]     at Object.afterTest (/home/circleci/project/e2e/config/wdio.base.config.ts:310:17)
[0-0]     at async Promise.all (index 0)
[0-0]     at executeHooksWithArgs (/home/circleci/project/node_modules/@wdio/utils/build/index.js:1351:18)
[0-0] Error in "AfterTest Hook"
```

### How to reproduce the bug.

Upgrade your project to wdio v9 and try running automation specs on BS.

### Relevant log output

```typescript
[0-0] 2024-08-28T11:49:12.322Z ERROR webdriver: Error: Failed to fetch https://hub-cloud.browserstack.com/wd/hub/session: [object Object]
[0-0]     at FetchRequest._libRequest (/Users/lorandberekmeri/git/node_modules/webdriver/build/index.js:1373:15)
[0-0]     at FetchRequest._request (/Users/lorandberekmeri/git/node_modules/webdriver/build/index.js:1280:20)
[0-0]     at startWebDriverSession (/Users/lorandberekmeri/git/node_modules/webdriver/build/index.js:895:16)
[0-0]     at Function.newSession (/Users/lorandberekmeri/git/node_modules/webdriver/build/index.js:1508:41)
[0-0]     at remote (/Users/lorandberekmeri/git/node_modules/webdriverio/build/index.js:7043:20)
[0-0]     at async Runner._startSession (file:///Users/lorandberekmeri/git/node_modules/@wdio/runner/build/index.js:778:23)
[0-0]     at async Runner._initSession (file:///Users/lorandberekmeri/git/node_modules/@wdio/runner/build/index.js:752:22)
[0-0]     at async Runner.run (file:///Users/lorandberekmeri/git/node_modules/@wdio/runner/build/index.js:659:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by jungminjun824** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by berekmerilorand** [comment]
@patrickhousley touch actions are deprecated. you should use https://webdriver.io/docs/api/browser/action/

See an example from my project for `longPress`

```
        await browser
            .action('pointer')
            .move({ x: coordinates.x, y: coordinates.y })
            .down()
            .pause(holdDuration)
            .up()
            .perform();
    }
```

**Comment by Private1647** [comment]
@berekmerilorand - Seems to be working with the following dependencies in package.json when run on LambdaTest ([Repo](https://github.com/LambdaTest/LT-appium-nodejs-webdriverio)) - 

```
"dependencies": {
    "@wdio/cli": "^5.20.1",
    "@wdio/local-runner": "^5.20.1",
    "@wdio/mocha-framework": "^5.18.7",
    "appium": "^1.22.3"
  },
  "devDependencies": {
    "webdriverio": "^9.0.7"
  }
```

Node version - v22.6.0

Let me know if this helps.

**Comment by christian-bromann** [comment]
@Private1647 I strongly discouraged to use different major versions between WebdriverIO packages. This only creates more complicated bugs. We have deprecated v5 of all `@wdio/XXX` packages a while ago.

**Comment by berekmerilorand** [comment]
@Private1647 as @christian-bromann said, it's recommended to use as similar as possible versions between @wdio packages. also, i'm using appium `2.11.3` which came with a lot of differences in the framework, so there's no point of rolling back just to use wdio v9, but I appreciate it, thank you!

**Comment by christian-bromann** [comment]
duplicate of #13425
