### ISSUE TITLE
[🐛 Bug]: wdio v9 issue with selenium grid protected by basic auth

### ISSUE THREAD

**Issue by amardeep2006** [webdriverio/webdriverio#13484]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.7

### Node.js Version

20.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
   capabilities: {
     alwaysMatch: { browserName: 'chrome', webSocketUrl: true },
     firstMatch: [ {} ]
   },
   desiredCapabilities: { browserName: 'chrome', webSocketUrl: true }
 }
```

### What happened?

I have been using the selenium grid with wdio version 8. Now I want to upgrade the wdio to version 9 to adopt bidi protocol.
The default project I created via npm init wdio  throws this error.

`ERROR webdriver: TypeError: Request cannot be constructed from a URL that includes credentials: https://username:secret@seleniumgrid.mydomain.com/wd/hub/session`

based on the error looks like some component in wdio 9 does not like making POST to selenium hub url , probably considering it unsafe.

### What is your expected behavior?

I should be able to test the test with selenium grid that is protected by basic auth.

### How to reproduce the bug.

I am using this config in wdio.conf.ts file to point my tests at selenium grid.

    hostname: 'username:secret@seleniumgrid.mydomain.com',
    port: 443,
    path: '/wd/hub',
    protocol: 'https',

### Relevant log output

```typescript
2024-08-31T16:55:49.668Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-08-31T16:55:49.670Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] 2024-08-31T16:55:53.043Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///C:/Work/Work/Selenium-Grid/tst/features/login.feature
[0-0] 2024-08-31T16:55:56.105Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-08-31T16:55:56.106Z INFO @wdio/utils: Connecting to existing driver at https://username:secret@seleniumgrid.mydomain.com:443/wd/hub
[0-0] 2024-08-31T16:55:56.120Z INFO webdriver: [POST] https://username:secret@seleniumgrid.mydomain.com/wd/hub/session
[0-0] 2024-08-31T16:55:56.120Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', webSocketUrl: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', webSocketUrl: true }
[0-0] }
[0-0] 2024-08-31T16:55:56.124Z ERROR webdriver: TypeError: Request cannot be constructed from a URL that includes credentials: https://username:secret@seleniumgrid.mydomain.com/wd/hub/session
[0-0]     at node:internal/deps/undici/undici:12502:13
[0-0]     at FetchRequest._libRequest (C:\Work\Work\Selenium-Grid\tst\node_modules\webdriver\build\index.js:1360:24)
[0-0]     at FetchRequest._request (C:\Work\Work\Selenium-Grid\tst\node_modules\webdriver\build\index.js:1280:20)
[0-0] 2024-08-31T16:55:56.144Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Request cannot be constructed from a URL that includes credentials: https://username:secret@seleniumgrid.mydomain.com/wd/hub/session
[0-0]     at startWebDriverSession (C:\Work\Work\Selenium-Grid\tst\node_modules\webdriver\build\index.js:899:11)
[0-0]     at Function.newSession (C:\Work\Work\Selenium-Grid\tst\node_modules\webdriver\build\index.js:1508:41)
[0-0]     at remote (C:\Work\Work\Selenium-Grid\tst\node_modules\@wdio\runner\node_modules\webdriverio\build\index.js:7043:20)
[0-0]     at async Runner._startSession (file:///C:/Work/Work/Selenium-Grid/tst/node_modules/@wdio/runner/build/index.js:778:23)
[0-0]     at async Runner._initSession (file:///C:/Work/Work/Selenium-Grid/tst/node_modules/@wdio/runner/build/index.js:752:22)
[0-0]     at async Runner.run (file:///C:/Work/Work/Selenium-Grid/tst/node_modules/@wdio/runner/build/index.js:659:16)
[0-0] FAILED in chrome - file:///C:/Work/Work/Selenium-Grid/tst/features/login.feature
2024-08-31T16:55:56.358Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-08-31T16:55:56.358Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:08
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by amardeep2006** [comment]
Figured it out, as suspected it's not a bug but a security feature as more libraries and frameworks are discouraging basic auth info in url.
We should pass security headers for basic auth instead of passing in hostname.
https://webdriver.io/docs/configuration/#headers

Sample code snippet how I am doing now in case someone faces same error in future and finds this via search engine.

```
import { Buffer } from 'buffer';
// Read the username and password from environment variables
const username = process.env.SELENIUM_GRID_USERNAME;
const password = process.env.SELENIUM_GRID_PASSWORD;

// Combine the username and password with a colon separator
const credentials = `${username}:${password}`;
// Encode the credentials using Base64
const encodedCredentials = Buffer.from(credentials).toString('base64');

```
Then inside config 

```
    hostname: 'seleniumgrid.mydomain.com',
    port: 443,
    path: '/wd/hub',
    protocol: 'https',
     
    // Headers for Grid URL
    headers: {
        Authorization: `Basic ${encodedCredentials}`
    },
```

**Comment by christian-bromann** [comment]
Thanks for providing your solution to the issue, mind raising a PR to our documentation to better guide users? I am happy to help.

**Comment by amardeep2006** [comment]
sure @christian-bromann I can raise PR. Please point to me the section you feel this can be documented. 
Do you what library is causing the error faced by me?

**Comment by amardeep2006** [comment]
Apologies for delay , looks like I missed the chance and some good soul already updated the documentation. 
I will go through the documentation and raise PR if I feel something can be imroved else where.
