### ISSUE TITLE
[🐛 Bug]:  script execution doesn't work

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#13518]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.8

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': {
      args: [
        '--disable-backgrounding-occluded-windows',
        '--window-size=1980,1080',
        '--lang=fr_FR.UTF-8',
        '--disable-search-engine-choice-screen',
      ],
    },
  },
```

### What happened?

When I use browser.execute or use deepselector (>>>), I have the error below:
```
SyntaxError: Unexpected token 'return'
[chrome 128.0.6613.120 Windows 10 #0-0] SyntaxError: Unexpected token 'return'
[chrome 128.0.6613.120 Windows 10 #0-0]     at Browser.execute (c:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriverio/build/index.js:3030:33)
[chrome 128.0.6613.120 Windows 10 #0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[chrome 128.0.6613.120 Windows 10 #0-0]     at Browser.wrapCommandFn (c:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/index.js:1368:23)
[chrome 128.0.6613.120 Windows 10 #0-0]     at Browser.findElement (c:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriverio/build/index.js:6486:16)
[chrome 128.0.6613.120 Windows 10 #0-0]     at Browser.$ (c:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriverio/build/index.js:425:15)
[chrome 128.0.6613.120 Windows 10 #0-0]     at Browser.wrapCommandFn (c:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/index.js:1368:23)
[chrome 128.0.6613.120 Windows 10 #0-0]     at Browser.wrapCommandFn (c:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/index.js:1368:23)
```

### How to reproduce the bug.

```
  await browser.url('https://taskmob.demo.vaadin.com');
  await expect($('#overlay')).toBeDisplayed();
  console.log(await $('>>>#newTaskButton').isDisplayed()); // SyntaxError: Unexpected token 'return'
```

### Relevant log output

```typescript
BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[5465 bytes]>","awaitPromise":true,"arguments":[{"sharedId":"f.E9ED9EAC005B2ED2DE03C689265B14B5.d.45924BE2D7FD472E4A2400F92759B5D4.e.61"}],"target":{"context":"E9ED9EAC005B2ED2DE03C689265B14B5"}}
[0-0] 2024-09-05T12:19:26.415Z DEBUG webdriver: BIDI RESULT {"id":11,"result":{"realm":"-1121069419246494789.-2991111388086926076","result":{"type":"boolean","value":true},"type":"success"},"type":"success"}
[0-0] 2024-09-05T12:19:26.419Z INFO webdriver: COMMAND $(">>>#newTaskButton")
[0-0] 2024-09-05T12:19:26.514Z INFO webdriver: COMMAND getUrl()
[0-0] 2024-09-05T12:19:26.515Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/94845319503d110f780ba21d15b11b59/url
[0-0] 2024-09-05T12:19:26.545Z INFO webdriver: RESULT https://taskmob.demo.vaadin.com/projects/9mlCvrM8
[0-0] Error in "0: Given I test chrome"
SyntaxError: Unexpected token 'return'
    at Browser.execute (c:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriverio/build/index.js:3030:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Browser.wrapCommandFn (c:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/index.js:1368:23)
    at Browser.findElement (c:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriverio/build/index.js:6486:16)
    at Browser.$ (c:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriverio/build/index.js:425:15)
    at Browser.wrapCommandFn (c:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/index.js:1368:23)
    at Browser.wrapCommandFn (c:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/index.js:1368:23)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by lacell75** [comment]
And with snippet code provides, we can reproduce another bug with the elements in shadow root. 
`RROR webdriver: Failed parse WebDriver Bidi message: Couldn't find element with id f.E9ED9EAC005B2ED2DE03C689265B14B5.d.45924BE2D7FD472E4A2400F92759B5D4.e.332`

**Comment by lacell75** [comment]
@christian-bromann , Do you want I create another issue for the problem of detection of elements in shadow roots?

**Comment by christian-bromann** [comment]
@lacell75 yes please, go ahead, thanks!

**Comment by Badisi** [comment]
Also facing the `Couldn't find element with id` error, see #13467.
