### ISSUE TITLE
[🐛 Bug]: Tests not running on grid after upgrading to wdio v9 

### ISSUE THREAD

**Issue by sushantsoni5392** [webdriverio/webdriverio#13519]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.20.4

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome',
        'bstack:options' : {
            seleniumBidi: true,
            seleniumVersion: '4.23.0',
        }
    }],
```

### What happened?

After upgrading the wdio v9, the tests are not running on BrowserStack or Aerokube Moon (both are 3rd party grid solutions). I get the below error 

```
[0-0] 2024-09-05T10:09:38.725Z INFO webdriver: Register BiDi handler for session with id 17b386ee9e2a6f52ac57880107d78e1efcda4c34
[0-0] 2024-09-05T10:09:38.725Z INFO webdriver: Connect to webSocketUrl wss://cdp-euw.browserstack.com:443/session/17b386ee9e2a6f52ac57880107d78e1efcda4c34/se/bidi
[0-0] 2024-09-05T10:09:38.839Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-09-05T10:09:38.840Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-09-05T10:09:38.840Z INFO webdriver: Connected to WebDriver Bidi interface at wss://cdp-euw.browserstack.com:443/session/17b386ee9e2a6f52ac57880107d78e1efcda4c34/se/bidi
[0-0] 2024-09-05T10:09:38.841Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.navigationStarted"]}
[0-0] 2024-09-05T10:09:38.842Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-09-05T10:09:38.843Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["log.entryAdded"]}
[0-0] 2024-09-05T10:09:38.843Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[1265 bytes]>, contexts: undefined }
[0-0] 2024-09-05T10:09:38.844Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.navigationStarted","network.responseCompleted","network.beforeRequestSent","network.fetchError"]}
[0-0] 2024-09-05T10:09:38.844Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.userPromptOpened"]}
[0-0] 2024-09-05T10:09:38.844Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/17b386ee9e2a6f52ac57880107d78e1efcda4c34/window
[0-0] 2024-09-05T10:09:38.846Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-09-05T10:09:38.846Z INFO webdriver: [GET] https://hub.browserstack.com/wd/hub/session/17b386ee9e2a6f52ac57880107d78e1efcda4c34/window
[0-0] 2024-09-05T10:09:38.994Z INFO webdriver: RESULT CDwindow-8BF88F78219C160E6F42B32B4B1D7720
[0-0] 2024-09-05T10:09:38.995Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[374 bytes]>","awaitPromise":true,"arguments":[],"target":{"context":"CDwindow-8BF88F78219C160E6F42B32B4B1D7720"}}
[0-0] 2024-09-05T10:09:39.027Z INFO webdriver: RESULT CDwindow-8BF88F78219C160E6F42B32B4B1D7720
[0-0] 2024-09-05T10:09:39.027Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[343 bytes]>, contexts: ["CDwindow-8BF88F78219C160E6F42B32B4B1D7720"] }
[0-0] 2024-09-05T10:09:39.229Z DEBUG webdriver: BIDI RESULT {"error":"invalid argument","id":1,"message":"Invalid enum value. Expected 'browsingContext.load' | 'browsingContext.domContentLoaded' | 'browsingContext.contextCreated' | 'browsingContext.contextDestroyed' | 'log.entryAdded' | 'cdp.eventReceived', received 'browsingContext.navigationStarted' in \"events\"/0."}
[0-0] 2024-09-05T10:09:39.235Z DEBUG webdriver: BIDI RESULT {"id":2,"result":{}}
[0-0] 2024-09-05T10:09:39.235Z DEBUG webdriver: BIDI RESULT {"error":"unknown command","id":3,"message":"Unknown command 'script.addPreloadScript'."}
[0-0] /Users/x.yy/Documents/xxy/lily/node_modules/.pnpm/webdriver@9.0.8/node_modules/webdriver/build/index.js:141
[0-0]     const failError = new Error(`WebDriver Bidi command "${params.method}" failed`);
[0-0]                       ^
[0-0] 
[0-0] 
[0-0] Error: WebDriver Bidi command "script.addPreloadScript" failed with error: unknown command - Unknown command 'script.addPreloadScript'.
[0-0]     at BidiHandler.send (/Users/x.yy/Documents/xxy/lily/node_modules/.pnpm/webdriver@9.0.8/node_modules/webdriver/build/index.js:141:23)
[0-0]     at BidiHandler.scriptAddPreloadScript (/Users/x.yy/Documents/xxy/lily/node_modules/.pnpm/webdriver@9.0.8/node_modules/webdriver/build/index.js:565:31)
[0-0]     at Browser.wrapCommandFn (/Users/x.yy/Documents/xxy/lily/node_modules/.pnpm/@wdio+utils@9.0.8/node_modules/@wdio/utils/build/index.js:1368:32)
[0-0]     at Browser.<anonymous> (/Users/x.yy/Documents/xxy/lily/node_modules/.pnpm/@wdio+utils@9.0.8/node_modules/@wdio/utils/build/index.js:1480:20)
[0-0]     at ShadowRootManager (/Users/x.yy/Documents/xxy/lily/node_modules/.pnpm/webdriverio@9.0.8/node_modules/webdriverio/build/index.js:4885:13)
[0-0]     at getShadowRootManager (/Users/x.yy/Documents/xxy/lily/node_modules/.pnpm/webdriverio@9.0.8/node_modules/webdriverio/build/index.js:4865:22)
[0-0]     at remote (/Users/x.yy/Documents/xxy/lily/node_modules/.pnpm/webdriverio@9.0.8/node_modules/webdriverio/build/index.js:7197:5)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async Runner._startSession (file:///Users/x.yy/Documents/xxy/lily/node_modules/.pnpm/@wdio+runner@9.0.8/node_modules/@wdio/runner/build/index.js:781:23)
[0-0]     at async Runner._initSession (file:///Users/x.yy/Documents/xxy/lily/node_modules/.pnpm/@wdio+runner@9.0.8/node_modules/@wdio/runner/build/index.js:755:22)
[0-0] 
[0-0] Node.js v18.20.4
```
When I run on a local chrome, it works fine.

### What is your expected behavior?

No errors, tests should run fine.

### How to reproduce the bug.

You can check the example at - https://github.com/sushantsoni5392/wdio-mocha-boilerplate, please replace your BrowserStack username, password in the config.

### Relevant log output

```typescript
check description
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@sushantsoni5392 it seems like BrowserStack doesn't fully support Bidi. Mind reaching out to their support and ask what they are supporting? In the meantime you can disable bidi by setting `'wdio:enforceWebDriverClassic': true` in your capabilities.

**Comment by sushantsoni5392** [comment]
It is fine, I can stay on v8, I wanted to use the BiDi features with v9, hence the upgrade.

But interestingly, it is not only BrowserStack. We use [Aerokube Moon](https://aerokube.com/moon/) for running our tests, and we see the same error. So I can say it is not specific to BrowserStack.
