### ISSUE TITLE
browser.waitForVisible(...).then is not a function

### ISSUE THREAD

**Issue by sugendran** [webdriverio/webdriverio#1358]
## The problem

I've taken the example from `/examples/commands/webdriverio.waitForVisible.js` and changed it to use the `browser` object as I'm using the wdio testrunner. When I run the test I get the following.

```
[17:58:14]  COMMAND     POST     "/wd/hub/session"
[17:58:14]  DATA                {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesA
lerts":true,"rotatable":true,"maxInstances":1,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"re
questOrigins":{"url":"http://webdriver.io","version":"4.0.7","name":"webdriverio"}}}
[17:58:15]  INFO        SET SESSION ID 0d2dc490-e501-4adf-acd2-1ee23154f12f
[17:58:15]  RESULT              {"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"chrom
e":{"chromedriverVersion":"2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4)","userDataDir":"C:\\Users\\SUGEND~1.GA
N\\AppData\\Local\\Temp\\scoped_dir6332_29062"},"takesHeapSnapshot":true,"databaseEnabled":false,"handlesAlerts":true,"h
asTouchScreen":false,"version":"50.0.2661.102","platform":"XP","browserConnectionEnabled":false,"nativeEvents":true,"acc
eptSslCerts":true,"webdriver.remote.sessionid":"0d2dc490-e501-4adf-acd2-1ee23154f12f","locationContextEnabled":true,"web
StorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true}
[17:58:15]  INFO        running...
[17:58:15]  COMMAND     POST     "/wd/hub/session/0d2dc490-e501-4adf-acd2-1ee23154f12f/url"
[17:58:15]  DATA                {"url":"http://www.google.com/"}
[17:58:17]  RESULT              null
[17:58:17]  COMMAND     POST     "/wd/hub/session/0d2dc490-e501-4adf-acd2-1ee23154f12f/elements"
[17:58:17]  DATA                {"using":"xpath","value":"//input[@type=\"submit\"]"}
[17:58:17]  RESULT              [{"ELEMENT":"0"}]
[17:58:17]  COMMAND     GET      "/wd/hub/session/0d2dc490-e501-4adf-acd2-1ee23154f12f/element/0/displayed"
[17:58:17]  DATA                {}
[17:58:17]  RESULT              true
.[17:58:17]  COMMAND    DELETE   "/wd/hub/session/0d2dc490-e501-4adf-acd2-1ee23154f12f"
[17:58:17]  DATA                {}
[17:58:18]  RESULT              null


0 passing (5.20s)
1 failing

1) runs:
Failed: browser.url(...).waitForVisible(...).then is not a function
running chrome
TypeError: browser.url(...).waitForVisible(...).then is not a function
    at Object.<anonymous> (C:\Code\edm-webui-tests\specs\waitfor.js:9:14)
    at Object.executeSync (C:\Code\edm-webui-tests\node_modules\wdio-jasmine-framework\node_modules\wdio-sync\build\inde
x.js:620:12)
    at C:\Code\edm-webui-tests\node_modules\wdio-jasmine-framework\node_modules\wdio-sync\build\index.js:814:34
```

## Environment

* WebdriverIO version: 4.0.7
* Node.js version: 4.2.4
* wdio test runner in sync mode
* testing using jasmine

## Test Case
```
var webdriverio = require('webdriverio');

describe('google example', function () {
    browser.logger.info("running... ");
    it('runs', function () {
        browser
            .url('http://www.google.com/')
            .waitForVisible('//input[@type="submit"]', 5000)
            .then(function(visible){
                browser.logger.info("visible: " + visible);
                expect(visible).toBe(true);
            })
    });
});
```

**Comment by christian-bromann** [comment]
The example uses the standalone version whereas you are using the test runner. Please make sure to read http://webdriver.io/guide/getstarted/modes.html
