### ISSUE TITLE
[🐛 Bug]: Using $("..") in chained elements not working

### ISSUE THREAD

**Issue by SimonRazor** [webdriverio/webdriverio#13652]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.11.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
browserName: 'chrome',
browserVersion: 'stable',
```

### What happened?

In v9 when trying to traverse the DOM using chained element and Xpath expressions it can't find the element.
Changing back to v8 works as expected.

Error:
Can't call $ on element with selector ".." because element wasn't found
Error: Can't call $ on element with selector ".." because element wasn't found
    at implicitWait (C:\Users\Test\Projects\Test\node_modules\webdriverio\build\index.js:49:13)
    at async Element.elementErrorHandlerCallbackFn (C:\Users\Test\Projects\Test\node_modules\webdriverio\build\index.js:6674:23)
    at async Element.wrapCommandFn (C:\Users\Test\Projects\Test\node_modules\@wdio\utils\build\index.js:1368:23)
    at async Element.wrapCommandFn (C:\Users\Test\Projects\Test\node_modules\@wdio\utils\build\index.js:1368:23)
    at async Context.<anonymous> (C:\Users\Test\Projects\Test\test\specs\test.spec.ts:4:28)
    at async Context.executeAsync (C:\Users\Test\Projects\Test\node_modules\@wdio\utils\build\index.js:1488:20)
    at async Context.testFrameworkFnWrapper (C:\Users\Test\Projects\Test\node_modules\@wdio\utils\build\index.js:1559:14)

### How to reproduce the bug.

```
describe('Chaining', () => {
    it('should be true', async () => {
        await browser.url("https://the-internet.herokuapp.com/challenging_dom");
        console.log(await (await $("td=Adipisci1").$("..").$("a=edit")).isDisplayed());
    });
});
```

### Relevant log output

```typescript
Error:
Can't call $ on element with selector ".." because element wasn't found
Error: Can't call $ on element with selector ".." because element wasn't found
    at implicitWait (C:\Users\Test\Projects\Test\node_modules\webdriverio\build\index.js:49:13)
    at async Element.elementErrorHandlerCallbackFn (C:\Users\Test\Projects\Test\node_modules\webdriverio\build\index.js:6674:23)
    at async Element.wrapCommandFn (C:\Users\Test\Projects\Test\node_modules\@wdio\utils\build\index.js:1368:23)
    at async Element.wrapCommandFn (C:\Users\Test\Projects\Test\node_modules\@wdio\utils\build\index.js:1368:23)
    at async Context.<anonymous> (C:\Users\Test\Projects\Test\test\specs\test.spec.ts:4:28)
    at async Context.executeAsync (C:\Users\Test\Projects\Test\node_modules\@wdio\utils\build\index.js:1488:20)
    at async Context.testFrameworkFnWrapper (C:\Users\Test\Projects\Test\node_modules\@wdio\utils\build\index.js:1559:14)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I looked into this issue and found that with WebDriver Bidi, we can't use xPath anymore to access elements that are outside of the scope of the given element. This was working with WebDriver classic. If you like to access the parent element, please use the WebdriverIO method for it, e.g.:

```ts
        await browser.url("https://the-internet.herokuapp.com/challenging_dom");
        console.log(await (await $("td=Adipisci1").parentElement().$("a=edit")).isDisplayed());
```
