### ISSUE TITLE
[🐛 Bug]: BeforeTest hook in sauce-service throws an error `Error in "BeforeTest Hook" Invalid left-hand side in assignment`

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#13670]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.11.1

### Mode

Standalone Mode

### What happened?

When running a test on Sauce the sauce-service updates the name of the test, see [this](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-sauce-service/src/service.ts#L103), with the execute method, see [this](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-sauce-service/src/service.ts#L424).

This now throws an error

```logs
[0-0] 2024-09-30T05:22:33.072Z ERROR @wdio/utils:shim: SyntaxError: Invalid left-hand side in assignment
[0-0]     at new Function (<anonymous>)
[0-0]     at Browser.execute (/Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/webdriverio@9.1.2/node_modules/webdriverio/build/index.js:3032:53)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at Browser.wrapCommandFn (/Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/@wdio+utils@9.1.2/node_modules/@wdio/utils/build/index.js:1380:23)
[0-0]     at async SauceService._setJobName (file:///Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/@wdio+sauce-service@9.1.2/node_modules/@wdio/sauce-service/build/index.js:488:5)
[0-0]     at async SauceService.beforeTest (file:///Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/@wdio+sauce-service@9.1.2/node_modules/@wdio/sauce-service/build/index.js:259:7)
[0-0]     at async Promise.all (index 1)
[0-0]     at executeHooksWithArgs (/Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/@wdio+utils@9.1.2/node_modules/@wdio/utils/build/index.js:1363:18)
[0-0]     at Context.testFrameworkFnWrapper (/Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/@wdio+utils@9.1.2/node_modules/@wdio/utils/build/index.js:1566:39)
[0-0] 2024-09-30T05:22:33.072Z DEBUG @wdio/utils:shim: Finished to run "beforeTest" hook in 0ms
[0-0] Error in "BeforeTest Hook"
Invalid left-hand side in assignment
```

### What is your expected behavior?

The testname can be updated, which works with `"^9.0.7"`

### How to reproduce the bug.

Create a simple test, use the latest `sauce-service` and let it automatically update the test in Sauce

### Relevant log output

```typescript
[0-0] 2024-09-30T05:22:33.072Z ERROR @wdio/utils:shim: SyntaxError: Invalid left-hand side in assignment
[0-0]     at new Function (<anonymous>)
[0-0]     at Browser.execute (/Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/webdriverio@9.1.2/node_modules/webdriverio/build/index.js:3032:53)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at Browser.wrapCommandFn (/Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/@wdio+utils@9.1.2/node_modules/@wdio/utils/build/index.js:1380:23)
[0-0]     at async SauceService._setJobName (file:///Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/@wdio+sauce-service@9.1.2/node_modules/@wdio/sauce-service/build/index.js:488:5)
[0-0]     at async SauceService.beforeTest (file:///Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/@wdio+sauce-service@9.1.2/node_modules/@wdio/sauce-service/build/index.js:259:7)
[0-0]     at async Promise.all (index 1)
[0-0]     at executeHooksWithArgs (/Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/@wdio+utils@9.1.2/node_modules/@wdio/utils/build/index.js:1363:18)
[0-0]     at Context.testFrameworkFnWrapper (/Users/wimselles/Git/wdio/visual-testing/node_modules/.pnpm/@wdio+utils@9.1.2/node_modules/@wdio/utils/build/index.js:1566:39)
[0-0] 2024-09-30T05:22:33.072Z DEBUG @wdio/utils:shim: Finished to run "beforeTest" hook in 0ms
[0-0] Error in "BeforeTest Hook"
Invalid left-hand side in assignment
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by SchroederSteffen** [comment]
We're also seeing this issue with v8 since this weekend.
Can you explain why this issue started occurring?
