### ISSUE TITLE
[🐛 Bug]: Errors report incorrect line number

### ISSUE THREAD

**Issue by therealbrad** [webdriverio/webdriverio#13748]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.1.1

### Node.js Version

20.16.0

### Mode

WDIO Testrunner

### What happened?

After upgrading to v9 I notice error messages do not show the correct line number. For example, I see:
```
Expected: "displayed"
Received: "not displayed"
    at Context.<anonymous> (file:///jenkins_home/workspace/Android/src/android/test/specs/regression/navigation.ts:1:3727)

```

Reports show the error always occurs on line 1 of the spec file.

### What is your expected behavior?

I expect to see something like:
```
Expected: "displayed"
Received: "not displayed"
    at Context.<anonymous> (file:///jenkins_home/workspace/Android/src/android/test/specs/regression/navigation.ts:108:40)
```

Where the line number correctly identifies where the error occurred.

### How to reproduce the bug.

To repo, force an error on any test and review the line number.

### Relevant log output

```typescript
Expected: "displayed"
Received: "not displayed"
    at Context.<anonymous> (file:///jenkins_home/workspace/Android/src/android/test/specs/regression/navigation.ts:1:3727)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by therealbrad** [comment]
I added 
		"sourceMap": true,
to my tsconfig.json to get the correct line number. I guess the update to use tsx required this.
