### ISSUE TITLE
[🐛 Bug]: `switchFrame` does not work with "classic" frames

### ISSUE THREAD

**Issue by torokati44** [webdriverio/webdriverio#13764]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.2.1

### Node.js Version

22

### Mode

WDIO Testrunner

### What happened?

Replaced "switchToFrame" with "switchFrame", test broke.
Workaround: [ruffle-rs/ruffle@`c00bffc` (#17539)](https://github.com/ruffle-rs/ruffle/pull/17539/commits/c00bffcae2bb3929fa53cec8d015940d8efa2d87)

### What is your expected behavior?

Test still works with "switchFrame".

### How to reproduce the bug.

https://github.com/ruffle-rs/ruffle/actions/runs/11326158628/job/31494538767?pr=17539#step:11:1129

### Relevant log output

```typescript
WebdriverBidiExeception: TypeError: Cannot read properties of null (reading 'contentDocument')
    at async Context.<anonymous> (/home/runner/work/ruffle/ruffle/web/packages/selfhosted/test/polyfill/classic_frames_injected/test.ts:45:9)
      45 │             return (/* __wdio script__ */()=>document.querySelector("#test-frame").contentDocument?.body.querySelector("ruffle-object")
         ╵ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at async waitForRuffleObjectInTestFrame (/home/runner/work/ruffle/ruffle/web/packages/selfhosted/test/utils.ts:215:5)
    at async Context.<anonymous> (/home/runner/work/ruffle/ruffle/web/packages/selfhosted/test/polyfill/classic_frames_injected/test.ts:45:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by torokati44** [comment]
Cc: @danielhjacobs

**Comment by christian-bromann** [comment]
Duplicate of #13763
