### ISSUE TITLE
[🐛 Bug]: 'wdio config' fails in the middle of questionnaire if there was no package.json at CWD

### ISSUE THREAD

**Issue by gavvvr** [webdriverio/webdriverio#13771]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v9.2.0

### Node.js Version

v22.6.0

### Mode

Standalone Mode

### What happened?

If I run `npx @wdio/cli config` in an empty directory (without `package.json`), the 1st question is if I want the CLI to create one for me. The default answer is Yes and I agree, but then in the middle of questionnaire (after choosing JS testing framework) it fail with exception (see "Relevant log output")

### How to reproduce the bug.

See "What happened?"

### Relevant log output

```typescript
Error: Could not find project root directory with a package.json
    at getProjectRoot (file:///Users/user/.npm/_npx/c99d4c13e0dee746/node_modules/@wdio/cli/build/index.js:1808:11)
    at async detectCompiler (file:///Users/user/.npm/_npx/c99d4c13e0dee746/node_modules/@wdio/cli/build/index.js:1416:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by gavvvr** [comment]
Broken since v8.20.1. Last successful `wdio config` in empty directory was v8.19.0

**Comment by christian-bromann** [comment]
It seems like the `createPackageJSON` is called way to late and has to be called before `getProjectRoot` is being executed or maybe as part of it. Any contributions are welcome!

**Comment by gavvvr** [comment]
@christian-bromann working on a potential solution for this
