### ISSUE TITLE
[🐛 Bug]: Timeout error with reloadSession API

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#13789]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': {
      args: [
        '--disable-backgrounding-occluded-windows',
        '--window-size=1980,1080',
        '--lang=fr_FR.UTF-8',
        '--disable-search-engine-choice-screen',
      ],
    },
  },

Grid with Selenium-server-4.25.0
```

### What happened?

If reload session is used, the test breaks with a timeout error.

### How to reproduce the bug.

```
  await browser.reloadSession();
  await browser.url(
    'https://webdriver.io/blog/2024/08/15/webdriverio-v9-release'
  );
  await $('[href="/blog"]').waitForDisplayed();
```

### Relevant log output

```typescript
[0-0] 2024-10-22T13:55:30.142Z INFO webdriver: COMMAND deleteSession(<object>)
[0-0] 2024-10-22T13:55:30.143Z INFO webdriver: [DELETE] http://127.0.0.1:4444/wd/hub/session/bff0845355593ed7b100644eaccc694f
[0-0] 2024-10-22T13:55:30.143Z INFO webdriver: DATA { deleteSessionOpts: { shutdownDriver: false } }
[0-0] 2024-10-22T13:55:30.809Z INFO webdriver: RESULT null
[0-0] 2024-10-22T13:55:30.812Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2024-10-22T13:55:30.812Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       'goog:chromeOptions': [Object],
[0-0]       webSocketUrl: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }
[0-0] 2024-10-22T13:55:33.211Z INFO webdriver: BIDI COMMAND browsingContext.navigate {"context":"CE6C5F1343C782BBC3DED3A225FE0C50","url":"https://webdriver.io/blog/2024/08/15/webdriverio-v9-release","wait":"complete"}
[0-0] 2024-10-22T13:56:33.257Z INFO webdriver: COMMAND getUrl()
[0-0] 2024-10-22T13:56:33.258Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/cdbf45f49986aea09d6a6f435e50e69d/url
[0-0] 2024-10-22T13:56:33.278Z INFO webdriver: RESULT about:blank
[0-0] Error: Command browsingContext.navigate with id 9 (with the following parameter: {"context":"CE6C5F1343C782BBC3DED3A225FE0C50","url":"https://webdriver.io/blog/2024/08/15/webdriverio-v9-release","wait":"complete"}) timed out
    at Timeout._onTimeout (C:\2-gitlab\end-to-end-tests-wdio\node_modules\webdriver\build\index.js:246:16)
    at listOnTimeout (node:internal/timers:581:17)
    at process.processTimers (node:internal/timers:519:7)
```
Selenium grid errors
```
 Session request received by the Distributor:
 [Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-backgrounding-occ..., --window-size=1980,1080, --lang=fr_FR.UTF-8, --disable-search-engine-cho...], prefs: {}}, webSocketUrl: true}]
10:11:50.268 INFO [LocalNode.newSession] - Session created by the Node. Id: e65e05edb82b40d7ed9cc92839a42efd, Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 130.0.6723.58, chrome: {chromedriverVersion: 130.0.6723.69 (3ec172b971b9..., userDataDir: C:\Users\FABIEN~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62413}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:cdp: ws://172.23.176.1:4444/sess..., se:cdpVersion: 130.0.6723.58, se:gridWebSocketUrl: ws://localhost:14852/sessio..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webSocketUrl: ws://172.23.176.1:4444/sess..., webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
10:11:50.277 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: e65e05edb82b40d7ed9cc92839a42efd
 Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 130.0.6723.58, chrome: {chromedriverVersion: 130.0.6723.69 (3ec172b971b9..., userDataDir: C:\Users\FABIEN~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62413}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:cdp: ws://172.23.176.1:4444/sess..., se:cdpVersion: 130.0.6723.58, se:gridWebSocketUrl: ws://localhost:14852/sessio..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webSocketUrl: ws://172.23.176.1:4444/sess..., webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
10:11:50.334 INFO [ProxyNodeWebsockets.createWsEndPoint] - Establishing connection to ws://localhost:14852/session/e65e05edb82b40d7ed9cc92839a42efd
10:12:00.244 INFO [LocalSessionMap.remove] - Deleted session from local Session Map, Id: e65e05edb82b40d7ed9cc92839a42efd
10:12:00.247 INFO [GridModel.release] - Releasing slot for session id e65e05edb82b40d7ed9cc92839a42efd
10:12:00.253 INFO [SessionSlot.stop] - Stopping session e65e05edb82b40d7ed9cc92839a42efd
10:12:00.282 INFO [LocalDistributor.newSession] - Session request received by the Distributor:
 [Capabilities {acceptInsecureCerts: true, browserName: chrome, goog:chromeOptions: {args: [--disable-backgrounding-occ..., --window-size=1980,1080, --lang=fr_FR.UTF-8, --disable-search-engine-cho...], prefs: {}}, webSocketUrl: true}]
10:12:02.484 INFO [LocalNode.newSession] - Session created by the Node. Id: 86f60d538758d2e1472e2934bd45bb25, Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 130.0.6723.58, chrome: {chromedriverVersion: 130.0.6723.69 (3ec172b971b9..., userDataDir: C:\Users\FABIEN~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62469}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:cdp: ws://172.23.176.1:4444/sess..., se:cdpVersion: 130.0.6723.58, se:gridWebSocketUrl: ws://localhost:32182/sessio..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webSocketUrl: ws://172.23.176.1:4444/sess..., webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
10:12:02.490 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: 86f60d538758d2e1472e2934bd45bb25
 Caps: Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 130.0.6723.58, chrome: {chromedriverVersion: 130.0.6723.69 (3ec172b971b9..., userDataDir: C:\Users\FABIEN~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62469}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: Windows 10, proxy: Proxy(), se:cdp: ws://172.23.176.1:4444/sess..., se:cdpVersion: 130.0.6723.58, se:gridWebSocketUrl: ws://localhost:32182/sessio..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webSocketUrl: ws://172.23.176.1:4444/sess..., webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
10:12:02.500 WARN [DefaultChannelPipeline.onUnhandledInboundException] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
org.openqa.selenium.WebDriverException: java.io.IOException: Output closed
Build info: version: '4.25.0', revision: '030fcf7918'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '15.0.1'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.send(JdkHttpClient.java:320)
        at org.openqa.selenium.grid.node.ProxyNodeWebsockets.lambda$createWsEndPoint$6(ProxyNodeWebsockets.java:237)
        at org.openqa.selenium.netty.server.WebSocketMessageHandler.lambda$channelRead0$0(WebSocketMessageHandler.java:47)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: Output closed
        at java.net.http/jdk.internal.net.http.websocket.MessageEncoder.encodeText(MessageEncoder.java:136)
        at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:366)
        at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask$1.onText(TransportImpl.java:357)
        at java.net.http/jdk.internal.net.http.websocket.MessageQueue.peek(MessageQueue.java:223)
        at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:545)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
        at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
        at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:184)
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.lambda$send$1(JdkHttpClient.java:271)
        at org.openqa.selenium.remote.http.jdk.JdkHttpClient$4.send(JdkHttpClient.java:310)
        ... 10 more
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by lacell75** [comment]
@christian-bromann, I have an error with 9.3.0 and code above
```
[0-0] 2024-11-21T09:06:51.728Z DEBUG @wdio/utils:shim: Finished to run "beforeScenario" hook in 0ms
[0-0] 2024-11-21T09:06:51.736Z INFO webdriver: COMMAND deleteSession(<object>)
[0-0] 2024-11-21T09:06:51.737Z INFO webdriver: [DELETE] http://127.0.0.1:4444/wd/hub/session/1354fa46c50e5b56a5ec3c8db09acb08
[0-0] 2024-11-21T09:06:51.737Z INFO webdriver: DATA { deleteSessionOpts: { shutdownDriver: false } }
[0-0] 2024-11-21T09:06:52.441Z INFO webdriver: RESULT null
[0-0] 2024-11-21T09:06:52.442Z INFO webdriver: Close Bidi connection to ws://172.28.96.1:4444/session/1354fa46c50e5b56a5ec3c8db09acb08/se/bidi
[0-0] 2024-11-21T09:06:52.452Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2024-11-21T09:06:52.452Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       'goog:chromeOptions': [Object],
[0-0]       webSocketUrl: true,
[0-0]       unhandledPromptBehavior: 'ignore'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }
[0-0] 2024-11-21T09:06:54.726Z INFO webdriver: Reconnect to new Bidi session at ws://172.28.96.1:4444/session/d0e4c2fe30c322967f63d6d788cc0f61/se/bidi
[0-0] 2024-11-21T09:06:54.747Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-11-21T09:06:54.749Z INFO webdriver: BIDI COMMAND browsingContext.navigate {"context":"9537B65607CB19C5B64A74A9C573563D","url":"https://webdriver.io/blog/2024/08/15/webdriverio-v9-release","wait":"complete"}
[0-0] 2024-11-21T09:06:54.771Z INFO webdriver: BIDI RESULT {"error":"no such frame","id":8,"message":"Context 9537B65607CB19C5B64A74A9C573563D not found","type":"error"}
[0-0] 2024-11-21T09:06:54.828Z INFO webdriver: COMMAND getUrl()
[0-0] 2024-11-21T09:06:54.829Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/d0e4c2fe30c322967f63d6d788cc0f61/url
[0-0] 2024-11-21T09:06:54.855Z INFO webdriver: RESULT about:blank
[0-0] Error in "0: Given I test firefox"
Error: WebDriver Bidi command "browsingContext.navigate" failed with error: no such frame - Context 9537B65607CB19C5B64A74A9C573563D not found
    at BidiHandler.send (C:\2-gitlab\insight\quality\end-to-end-tests-wdio\node_modules\webdriver\build\index.js:290:23)
    at BidiHandler.browsingContextNavigate (C:\2-gitlab\insight\quality\end-to-end-tests-wdio\node_modules\webdriver\build\index.js:559:31)
    at Browser.value (C:\2-gitlab\insight\quality\end-to-end-tests-wdio\node_modules\webdriver\build\index.js:1079:26)
    at Browser.wrapCommandFn (C:\2-gitlab\insight\quality\end-to-end-tests-wdio\node_modules\@wdio\utils\build\index.js:884:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Browser.url3 (C:\2-gitlab\insight\quality\end-to-end-tests-wdio\node_modules\webdriverio\build\index.js:4781:24)
    at async Browser.wrapCommandFn (C:\2-gitlab\insight\quality\end-to-end-tests-wdio\node_modules\@wdio\utils\build\index.js:884:23)
    at async World.<anonymous> (file:///C:/2-gitlab/insight/quality/end-to-end-tests-wdio/src/steps/given.js:123:3)
```

**Comment by christian-bromann** [comment]
Thanks for letting me know, I started working on #13906 to mitigate the problem.
