### ISSUE TITLE
Could not add a custom command with name "value"

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1381]
## The problem

```js
'use strict';

/**
 * Асинхронный метод для работы с текстовой нодой
 *
 * @lends browser
 * @param {string} selector
 * @param {string} [value]
 * @param {number} [timeout] — ms
 * @returns {string|Promise}
 */
browser.addCommand('value', function (selector, value, timeout) {
	let element = this.waitForExist(selector, timeout);

	if (value) {
		return element.setValue(selector, value);
	}

	return element.getValue(selector);
});
```

```
timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
running phantomjs
Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
    at Timeout.<anonymous> (/workspace/mail.ru/e.mail.ru-tests/node_modules/mocha/lib/runnable.js:226:19)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

@christian-bromann could you please reproduce my problem?

**Comment by christian-bromann** [comment]
Are you sure this happens because of the custom command?

**Comment by monolithed** [comment]
I don't reproduce it with other command names

**Comment by christian-bromann** [comment]
can you make sure that no command is executed after you call `browser.value(...)`?

**Comment by monolithed** [comment]
In my case,  `browser.value` is not executed at all.

#### commands.js

```js
browser.addCommand('value', function (selector, value, timeout) { });
```

#### config.js

```
let commands = require('./commands');

module.exports = {
   before () {
      commands()
   },

  // ...
}
```

I'll try to make a simple project with my problem, but later...

**Comment by monolithed** [comment]
It's strange, I could not replicate more, sorry.
