### ISSUE TITLE
[🐛 Bug]: Elements (specifically iframes) cannot be found after browser.refresh

### ISSUE THREAD

**Issue by thamp59** [webdriverio/webdriverio#13829]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.2.4

### Node.js Version

v20.18.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  webSocketUrl: true,
}
```

### What happened?

In a test, I am able to initially switch to an iframe and retrieve an element.

Then in that same test, if I were to run browser.refresh(), I would be unable to switch to the same iframe and retrieve the same element.

### What is your expected behavior?

After a browser refresh, I should already be in the iframe I switched to and should be able to retrieve an element in the iframe.

### How to reproduce the bug.

https://github.com/thamp59/wdio-iframe-elements/pull/1

minimal reproduction

### Relevant log output

```typescript
Execution of 2 workers started at 2024-10-29T19:44:20.031Z

2024-10-29T19:44:20.038Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-10-29T19:44:20.039Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2024-10-29T19:44:20.039Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
2024-10-29T19:44:20.150Z INFO webdriver: Using Chromedriver v130.0.6723.91 from cache directory C:\Users\thamp\AppData\Local\Temp
2024-10-29T19:44:20.315Z INFO webdriver: Setting up chrome v130.0.6723.91
2024-10-29T19:44:20.379Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-10-29T19:44:20.380Z INFO @wdio/local-runner: Start worker 0-0 with arg: run wdio.conf.js
[0-0] 2024-10-29T19:44:21.047Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///C:/dev/wdio-iframe-elements/switchFrameTest.spec.js
[0-0] 2024-10-29T19:44:21.116Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-10-29T19:44:21.371Z INFO webdriver: Setting up chrome v130.0.6723.91
[0-0] 2024-10-29T19:44:21.431Z INFO webdriver: Using Chromedriver v130.0.6723.91 from cache directory C:\Users\thamp\AppData\Local\Temp
[0-0] 2024-10-29T19:44:21.446Z INFO chromedriver: Starting ChromeDriver 130.0.6723.91 (53ac076783696778ecc8f360ea31765c29c240ad-refs/branch-heads/6723@{#1517}) on port 54344
[0-0] 2024-10-29T19:44:21.446Z INFO chromedriver: Remote connections are allowed by an allowlist (0.0.0.0).
[0-0] 2024-10-29T19:44:21.446Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[0-0] 2024-10-29T19:44:21.448Z INFO chromedriver: ChromeDriver was started successfully on port 54344.
[0-0] 2024-10-29T19:44:22.439Z INFO @wdio/utils: Started Chromedriver v130.0.6723.91 with params --port=54344 --allowed-origins=* --allowed-ips=0.0.0.0 in 1323ms on port 54344
[0-0] 2024-10-29T19:44:22.447Z INFO webdriver: [POST] http://localhost:54344/session
[0-0] 2024-10-29T19:44:22.447Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       webSocketUrl: true,
[0-0]       'goog:chromeOptions': [Object],
[0-0]       unhandledPromptBehavior: 'ignore'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }

DevTools listening on ws://127.0.0.1:54351/devtools/browser/07094b9c-f296-45f3-88f5-d1bc5661a365
[0-0] 2024-10-29T19:44:23.018Z INFO webdriver: Register BiDi handler for session with id ca2063a231a60f0aa5467d62ed9212fb
[0-0] 2024-10-29T19:44:23.018Z INFO webdriver: Connect to webSocketUrl ws://127.0.0.1:54344/session/ca2063a231a60f0aa5467d62ed9212fb
[0-0] 2024-10-29T19:44:23.022Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-10-29T19:44:23.023Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-10-29T19:44:23.023Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["log.entryAdded","browsingContext.navigationStarted"]}
[0-0] 2024-10-29T19:44:23.024Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[1267 bytes]>, contexts: undefined }
[0-0] 2024-10-29T19:44:23.024Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.navigationStarted","network.responseCompleted","network.beforeRequestSent","network.fetchError"]}
[0-0] 2024-10-29T19:44:23.024Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.userPromptOpened"]}
[0-0] 2024-10-29T19:44:23.024Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-10-29T19:44:23.024Z INFO webdriver: Connected to WebDriver Bidi interface at ws://127.0.0.1:54344/session/ca2063a231a60f0aa5467d62ed9212fb
[0-0] 2024-10-29T19:44:23.024Z INFO webdriver: [GET] http://localhost:54344/session/ca2063a231a60f0aa5467d62ed9212fb/window
[0-0] 2024-10-29T19:44:23.025Z INFO webdriver: [GET] http://localhost:54344/session/ca2063a231a60f0aa5467d62ed9212fb/window
[0-0] 2024-10-29T19:44:23.025Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-10-29T19:44:23.026Z INFO webdriver: [GET] http://localhost:54344/session/ca2063a231a60f0aa5467d62ed9212fb/window
[0-0] 2024-10-29T19:44:23.027Z INFO webdriver: RESULT 98957082E909E42369E9B7CB446EF754
[0-0] 2024-10-29T19:44:23.027Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[220 bytes]>","awaitPromise":true,"arguments":[{"type":"string","value":"var __defProp = Object.defineProperty;var 
__name = function (target, value) { return __defProp(target, 'name', { value: value, configurable: true }); };var __globalThis = (typeof globalThis === 'object' && globalThis) || (typeof window === 'object' && window);__globalThis.__name = __name;"}],"target":{"context":"98957082E909E42369E9B7CB446EF754"}}
[0-0] 2024-10-29T19:44:23.029Z INFO webdriver: RESULT 98957082E909E42369E9B7CB446EF754
[0-0] 2024-10-29T19:44:23.030Z INFO webdriver: RESULT 98957082E909E42369E9B7CB446EF754
[0-0] 2024-10-29T19:44:23.030Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[482 bytes]>, contexts: ["98957082E909E42369E9B7CB446EF754"] }
[0-0] 2024-10-29T19:44:23.036Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["script.message"]}
[0-0] 2024-10-29T19:44:23.037Z INFO webdriverio:PolyfillManager: polyfill script added
[0-0] 2024-10-29T19:44:23.040Z INFO webdriver: BIDI COMMAND browsingContext.navigate {"context":"98957082E909E42369E9B7CB446EF754","url":"https://chips-site-a.glitch.me/","wait":"complete"}
[0-0] 2024-10-29T19:44:24.073Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"iframe"},"context":"98957082E909E42369E9B7CB446EF754"}
[0-0] 2024-10-29T19:44:24.079Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[159 bytes]>","awaitPromise":true,"arguments":[{"sharedId":"f.98957082E909E42369E9B7CB446EF754.d.CA6582CA24EA8173727C2DC00A09BD37.e.6"}],"target":{"context":"98957082E909E42369E9B7CB446EF754"}}
[0-0] 2024-10-29T19:44:24.081Z INFO webdriver: COMMAND switchToFrame(<object>)
[0-0] 2024-10-29T19:44:24.082Z INFO webdriver: [POST] http://localhost:54344/session/ca2063a231a60f0aa5467d62ed9212fb/frame
[0-0] 2024-10-29T19:44:24.082Z INFO webdriver: DATA {
[0-0]   id: {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': 'f.98957082E909E42369E9B7CB446EF754.d.CA6582CA24EA8173727C2DC00A09BD37.e.6'
[0-0]   }
[0-0] }
[0-0] 2024-10-29T19:44:24.091Z INFO webdriver: RESULT null
[0-0] 2024-10-29T19:44:24.092Z INFO webdriver: COMMAND findElement("css selector", "#cookies")
[0-0] 2024-10-29T19:44:24.092Z INFO webdriver: [POST] http://localhost:54344/session/ca2063a231a60f0aa5467d62ed9212fb/element
[0-0] 2024-10-29T19:44:24.092Z INFO webdriver: DATA { using: 'css selector', value: '#cookies' }
[0-0] 2024-10-29T19:44:24.098Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'f.415B050182D3AA5C1577476507A32D2F.d.C927FE3815D996F0B0AD21E7784BC0E9.e.2'
[0-0] }
[0-0] 2024-10-29T19:44:24.100Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#cookies"},"context":"415B050182D3AA5C1577476507A32D2F"}
[0-0] 2024-10-29T19:44:24.103Z INFO webdriver: COMMAND refresh()
[0-0] 2024-10-29T19:44:24.103Z INFO webdriver: [POST] http://localhost:54344/session/ca2063a231a60f0aa5467d62ed9212fb/refresh
[0-0] 2024-10-29T19:44:24.274Z INFO webdriver: RESULT null
[0-0] 2024-10-29T19:44:24.274Z INFO webdriver: COMMAND findElement("css selector", "#cookies")
[0-0] 2024-10-29T19:44:24.274Z INFO webdriver: [POST] http://localhost:54344/session/ca2063a231a60f0aa5467d62ed9212fb/element
[0-0] 2024-10-29T19:44:24.274Z INFO webdriver: DATA { using: 'css selector', value: '#cookies' }
[0-0] 2024-10-29T19:44:24.282Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: 'no such element: Unable to locate element: {"method":"css selector","selector":"#cookies"}\n' +
[0-0]     '  (Session info: chrome=130.0.6723.91)',
[0-0]   stacktrace: '\tGetHandleVerifier [0x00007FF668F93AF5+28005]\n' +
[0-0]     '\t(No symbol) [0x00007FF668EF83F0]\n' +
[0-0]     '\t(No symbol) [0x00007FF668D9580A]\n' +
[0-0]     '\t(No symbol) [0x00007FF668DE5A3E]\n' +
[0-0]     '\t(No symbol) [0x00007FF668DE5D2C]\n' +
[0-0]     '\t(No symbol) [0x00007FF668E2EA97]\n' +
[0-0]     '\t(No symbol) [0x00007FF668E0BA7F]\n' +
[0-0]     '\t(No symbol) [0x00007FF668E2B8B3]\n' +
[0-0]     '\t(No symbol) [0x00007FF668E0B7E3]\n' +
[0-0]     '\t(No symbol) [0x00007FF668DD75C8]\n' +
[0-0]     '\t(No symbol) [0x00007FF668DD8731]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF66928646D+3118813]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF6692D6CC0+3448624]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF6692CCF3D+3408301]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF66905A44B+841403]\n' +
[0-0]     '\t(No symbol) [0x00007FF668F0344F]\n' +
[0-0]     '\t(No symbol) [0x00007FF668EFF4C4]\n' +
[0-0]     '\t(No symbol) [0x00007FF668EFF65D]\n' +
[0-0]     '\t(No symbol) [0x00007FF668EEEBB9]\n' +
[0-0]     '\tBaseThreadInitThunk [0x00007FFA72C1DBE7+23]\n' +
[0-0]     '\tRtlUserThreadStart [0x00007FFA74545A4C+44]\n'
[0-0] }
[0-0] 2024-10-29T19:44:24.284Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#cookies"},"context":"415B050182D3AA5C1577476507A32D2F"}
[0-0] 2024-10-29T19:44:24.285Z WARN webdriverio: Failed to execute browser.browsingContextLocateNodes({ ... }) due to Error: WebDriver Bidi command "browsingContext.locateNodes" failed with error: no such frame - Context 415B050182D3AA5C1577476507A32D2F not found, falling back to regular WebDriver Classic command
[0-0] 2024-10-29T19:44:24.285Z INFO webdriver: COMMAND findElements("css selector", "#cookies")
[0-0] 2024-10-29T19:44:24.286Z INFO webdriver: [POST] http://localhost:54344/session/ca2063a231a60f0aa5467d62ed9212fb/elements
[0-0] 2024-10-29T19:44:24.286Z INFO webdriver: DATA { using: 'css selector', value: '#cookies' }
[0-0] 2024-10-29T19:44:24.291Z INFO webdriver: RESULT []
[0-0] 2024-10-29T19:44:24.292Z INFO webdriver: COMMAND findElement("css selector", "iframe")
[0-0] 2024-10-29T19:44:24.292Z INFO webdriver: [POST] http://localhost:54344/session/ca2063a231a60f0aa5467d62ed9212fb/element
[0-0] 2024-10-29T19:44:24.292Z INFO webdriver: DATA { using: 'css selector', value: 'iframe' }
[0-0] 2024-10-29T19:44:24.298Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'f.98957082E909E42369E9B7CB446EF754.d.0998A7BCE0D140681D092654828E8DDD.e.11'
[0-0] }
[0-0] 2024-10-29T19:44:24.299Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[159 bytes]>","awaitPromise":true,"arguments":[{"sharedId":"f.98957082E909E42369E9B7CB446EF754.d.0998A7BCE0D140681D092654828E8DDD.e.11"}],"target":{"context":"415B050182D3AA5C1577476507A32D2F"}}
[0-0] Error in "should see element text when using browser.switchFrame"
Error: WebDriver Bidi command "script.callFunction" failed with error: no such frame - Context 415B050182D3AA5C1577476507A32D2F not found
    at BidiHandler.send (C:\dev\wdio-iframe-elements\node_modules\webdriver\build\index.js:253:23)
    at BidiHandler.scriptCallFunction (C:\dev\wdio-iframe-elements\node_modules\webdriver\build\index.js:704:31)
    at Browser.value (C:\dev\wdio-iframe-elements\node_modules\webdriver\build\index.js:1033:26)
    at Browser.wrapCommandFn (C:\dev\wdio-iframe-elements\node_modules\@wdio\utils\build\index.js:1380:32)
    at async Browser.execute (C:\dev\wdio-iframe-elements\node_modules\webdriverio\build\index.js:3085:20)
    at async Browser.wrapCommandFn (C:\dev\wdio-iframe-elements\node_modules\@wdio\utils\build\index.js:1380:23)
    at async switchToFrameUsingElement (C:\dev\wdio-iframe-elements\node_modules\webdriverio\build\index.js:4321:17)
    at async Browser.wrapCommandFn (C:\dev\wdio-iframe-elements\node_modules\@wdio\utils\build\index.js:1380:23)
    at async Context.<anonymous> (C:\dev\wdio-iframe-elements\switchFrameTest.spec.js:7:3)
[0-0] 2024-10-29T19:44:24.320Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-10-29T19:44:24.320Z INFO webdriver: [DELETE] http://localhost:54344/session/ca2063a231a60f0aa5467d62ed9212fb
[0-0] 2024-10-29T19:44:24.351Z INFO webdriver: RESULT null
[0-0] 2024-10-29T19:44:24.351Z INFO webdriver: Kill driver process with PID 128332
[0-0] FAILED in chrome - file:///C:/dev/wdio-iframe-elements/switchFrameTest.spec.js
2024-10-29T19:44:24.477Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-10-29T19:44:24.478Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-10-29T19:44:24.478Z INFO @wdio/local-runner: Start worker 0-1 with arg: run wdio.conf.js
[0-1] 2024-10-29T19:44:25.148Z INFO @wdio/local-runner: Run worker command: run
[0-1] RUNNING in chrome - file:///C:/dev/wdio-iframe-elements/switchToFrameTest.spec.js
[0-1] 2024-10-29T19:44:25.216Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-1] 2024-10-29T19:44:25.980Z INFO webdriver: Setting up chrome v130.0.6723.91
[0-1] 2024-10-29T19:44:26.040Z INFO webdriver: Using Chromedriver v130.0.6723.91 from cache directory C:\Users\thamp\AppData\Local\Temp
[0-1] 2024-10-29T19:44:26.054Z INFO chromedriver: Starting ChromeDriver 130.0.6723.91 (53ac076783696778ecc8f360ea31765c29c240ad-refs/branch-heads/6723@{#1517}) on port 52425
[0-1] 2024-10-29T19:44:26.054Z INFO chromedriver: Remote connections are allowed by an allowlist (0.0.0.0).
[0-1] 2024-10-29T19:44:26.054Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[0-1] 2024-10-29T19:44:26.056Z INFO chromedriver: ChromeDriver was started successfully on port 52425.
[0-1] 2024-10-29T19:44:27.054Z INFO @wdio/utils: Started Chromedriver v130.0.6723.91 with params --port=52425 --allowed-origins=* --allowed-ips=0.0.0.0 in 1838ms on port 52425
[0-1] 2024-10-29T19:44:27.062Z INFO webdriver: [POST] http://localhost:52425/session
[0-1] 2024-10-29T19:44:27.062Z INFO webdriver: DATA {
[0-1]   capabilities: {
[0-1]     alwaysMatch: {
[0-1]       browserName: 'chrome',
[0-1]       webSocketUrl: true,
[0-1]       'goog:chromeOptions': [Object],
[0-1]       unhandledPromptBehavior: 'ignore'
[0-1]     },
[0-1]     firstMatch: [ {} ]
[0-1]   }
[0-1] }

DevTools listening on ws://127.0.0.1:52434/devtools/browser/3ba65c5f-817d-47b9-9d0b-3122ba39d949
[0-1] 2024-10-29T19:44:27.629Z INFO webdriver: Register BiDi handler for session with id bf7da795af3be3f78bb31418851b2b49
[0-1] 2024-10-29T19:44:27.629Z INFO webdriver: Connect to webSocketUrl ws://127.0.0.1:52425/session/bf7da795af3be3f78bb31418851b2b49
[0-1] 2024-10-29T19:44:27.633Z INFO webdriver: Connected session to Bidi protocol
[0-1] 2024-10-29T19:44:27.634Z INFO webdriver: COMMAND getWindowHandle()
[0-1] 2024-10-29T19:44:27.634Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["log.entryAdded","browsingContext.navigationStarted"]}
[0-1] 2024-10-29T19:44:27.635Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[1267 bytes]>, contexts: undefined }
[0-1] 2024-10-29T19:44:27.635Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.navigationStarted","network.responseCompleted","network.beforeRequestSent","network.fetchError"]}
[0-1] 2024-10-29T19:44:27.635Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.userPromptOpened"]}
[0-1] 2024-10-29T19:44:27.635Z INFO webdriver: COMMAND getWindowHandle()
[0-1] 2024-10-29T19:44:27.635Z INFO webdriver: Connected to WebDriver Bidi interface at ws://127.0.0.1:52425/session/bf7da795af3be3f78bb31418851b2b49
[0-1] 2024-10-29T19:44:27.635Z INFO webdriver: [GET] http://localhost:52425/session/bf7da795af3be3f78bb31418851b2b49/window
[0-1] 2024-10-29T19:44:27.636Z INFO webdriver: [GET] http://localhost:52425/session/bf7da795af3be3f78bb31418851b2b49/window
[0-1] 2024-10-29T19:44:27.636Z INFO webdriver: COMMAND getWindowHandle()
[0-1] 2024-10-29T19:44:27.636Z INFO webdriver: [GET] http://localhost:52425/session/bf7da795af3be3f78bb31418851b2b49/window
[0-1] 2024-10-29T19:44:27.638Z INFO webdriver: RESULT AE358AB7C24F7EDCD25A4C863B73CAFB
[0-1] 2024-10-29T19:44:27.638Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[220 bytes]>","awaitPromise":true,"arguments":[{"type":"string","value":"var __defProp = Object.defineProperty;var 
__name = function (target, value) { return __defProp(target, 'name', { value: value, configurable: true }); };var __globalThis = (typeof globalThis === 'object' && globalThis) || (typeof window === 'object' && window);__globalThis.__name = __name;"}],"target":{"context":"AE358AB7C24F7EDCD25A4C863B73CAFB"}}
[0-1] 2024-10-29T19:44:27.640Z INFO webdriver: RESULT AE358AB7C24F7EDCD25A4C863B73CAFB
[0-1] 2024-10-29T19:44:27.640Z INFO webdriver: RESULT AE358AB7C24F7EDCD25A4C863B73CAFB
[0-1] 2024-10-29T19:44:27.640Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[482 bytes]>, contexts: ["AE358AB7C24F7EDCD25A4C863B73CAFB"] }
[0-1] 2024-10-29T19:44:27.645Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["script.message"]}
[0-1] 2024-10-29T19:44:27.646Z INFO webdriverio:PolyfillManager: polyfill script added
[0-1] 2024-10-29T19:44:27.649Z INFO webdriver: BIDI COMMAND browsingContext.navigate {"context":"AE358AB7C24F7EDCD25A4C863B73CAFB","url":"https://chips-site-a.glitch.me/","wait":"complete"}
[0-1] 2024-10-29T19:44:28.365Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"iframe"},"context":"AE358AB7C24F7EDCD25A4C863B73CAFB"}
[0-1] 2024-10-29T19:44:28.371Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[159 bytes]>","awaitPromise":true,"arguments":[{"sharedId":"f.AE358AB7C24F7EDCD25A4C863B73CAFB.d.E3239F41CB8ECA87FE0A7B18747CA5DE.e.6"}],"target":{"context":"AE358AB7C24F7EDCD25A4C863B73CAFB"}}
[0-1] 2024-10-29T19:44:28.373Z INFO webdriver: COMMAND switchToFrame(<object>)
[0-1] 2024-10-29T19:44:28.373Z INFO webdriver: [POST] http://localhost:52425/session/bf7da795af3be3f78bb31418851b2b49/frame
[0-1] 2024-10-29T19:44:28.373Z INFO webdriver: DATA {
[0-1]   id: {
[0-1]     'element-6066-11e4-a52e-4f735466cecf': 'f.AE358AB7C24F7EDCD25A4C863B73CAFB.d.E3239F41CB8ECA87FE0A7B18747CA5DE.e.6'
[0-1]   }
[0-1] }
[0-1] 2024-10-29T19:44:28.383Z INFO webdriver: RESULT null
[0-1] 2024-10-29T19:44:28.383Z INFO webdriver: COMMAND findElement("css selector", "#cookies")
[0-1] 2024-10-29T19:44:28.383Z INFO webdriver: [POST] http://localhost:52425/session/bf7da795af3be3f78bb31418851b2b49/element
[0-1] 2024-10-29T19:44:28.383Z INFO webdriver: DATA { using: 'css selector', value: '#cookies' }
[0-1] 2024-10-29T19:44:28.389Z INFO webdriver: RESULT {
[0-1]   'element-6066-11e4-a52e-4f735466cecf': 'f.C8E9FB063B267CF87EE21020ADEBFCDD.d.41BF09C3B2E9A0D8D5E3329AAFA68FA6.e.2'
[0-1] }
[0-1] 2024-10-29T19:44:28.391Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#cookies"},"context":"C8E9FB063B267CF87EE21020ADEBFCDD"}
[0-1] 2024-10-29T19:44:28.394Z INFO webdriver: COMMAND refresh()
[0-1] 2024-10-29T19:44:28.394Z INFO webdriver: [POST] http://localhost:52425/session/bf7da795af3be3f78bb31418851b2b49/refresh
[0-1] 2024-10-29T19:44:28.561Z INFO webdriver: RESULT null
[0-1] 2024-10-29T19:44:28.561Z INFO webdriver: COMMAND findElement("css selector", "#cookies")
[0-1] 2024-10-29T19:44:28.561Z INFO webdriver: [POST] http://localhost:52425/session/bf7da795af3be3f78bb31418851b2b49/element
[0-1] 2024-10-29T19:44:28.561Z INFO webdriver: DATA { using: 'css selector', value: '#cookies' }
[0-1] 2024-10-29T19:44:28.569Z INFO webdriver: RESULT {
[0-1]   error: 'no such element',
[0-1]   message: 'no such element: Unable to locate element: {"method":"css selector","selector":"#cookies"}\n' +
[0-1]     '  (Session info: chrome=130.0.6723.91)',
[0-1]   stacktrace: '\tGetHandleVerifier [0x00007FF668F93AF5+28005]\n' +
[0-1]     '\t(No symbol) [0x00007FF668EF83F0]\n' +
[0-1]     '\t(No symbol) [0x00007FF668D9580A]\n' +
[0-1]     '\t(No symbol) [0x00007FF668DE5A3E]\n' +
[0-1]     '\t(No symbol) [0x00007FF668DE5D2C]\n' +
[0-1]     '\t(No symbol) [0x00007FF668E2EA97]\n' +
[0-1]     '\t(No symbol) [0x00007FF668E0BA7F]\n' +
[0-1]     '\t(No symbol) [0x00007FF668E2B8B3]\n' +
[0-1]     '\t(No symbol) [0x00007FF668E0B7E3]\n' +
[0-1]     '\t(No symbol) [0x00007FF668DD75C8]\n' +
[0-1]     '\t(No symbol) [0x00007FF668DD8731]\n' +
[0-1]     '\tGetHandleVerifier [0x00007FF66928646D+3118813]\n' +
[0-1]     '\tGetHandleVerifier [0x00007FF6692D6CC0+3448624]\n' +
[0-1]     '\tGetHandleVerifier [0x00007FF6692CCF3D+3408301]\n' +
[0-1]     '\tGetHandleVerifier [0x00007FF66905A44B+841403]\n' +
[0-1]     '\t(No symbol) [0x00007FF668F0344F]\n' +
[0-1]     '\t(No symbol) [0x00007FF668EFF4C4]\n' +
[0-1]     '\t(No symbol) [0x00007FF668EFF65D]\n' +
[0-1]     '\t(No symbol) [0x00007FF668EEEBB9]\n' +
[0-1]     '\tBaseThreadInitThunk [0x00007FFA72C1DBE7+23]\n' +
[0-1]     '\tRtlUserThreadStart [0x00007FFA74545A4C+44]\n'
[0-1] }
[0-1] 2024-10-29T19:44:28.570Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#cookies"},"context":"C8E9FB063B267CF87EE21020ADEBFCDD"}
[0-1] 2024-10-29T19:44:28.571Z WARN webdriverio: Failed to execute browser.browsingContextLocateNodes({ ... }) due to Error: WebDriver Bidi command "browsingContext.locateNodes" failed with error: no such frame - Context C8E9FB063B267CF87EE21020ADEBFCDD not found, falling back to regular WebDriver Classic command
[0-1] 2024-10-29T19:44:28.572Z INFO webdriver: COMMAND findElements("css selector", "#cookies")
[0-1] 2024-10-29T19:44:28.572Z INFO webdriver: [POST] http://localhost:52425/session/bf7da795af3be3f78bb31418851b2b49/elements
[0-1] 2024-10-29T19:44:28.572Z INFO webdriver: DATA { using: 'css selector', value: '#cookies' }
[0-1] 2024-10-29T19:44:28.577Z INFO webdriver: RESULT []
[0-1] 2024-10-29T19:44:28.577Z INFO webdriver: COMMAND findElement("css selector", "iframe")
[0-1] 2024-10-29T19:44:28.577Z INFO webdriver: [POST] http://localhost:52425/session/bf7da795af3be3f78bb31418851b2b49/element
[0-1] 2024-10-29T19:44:28.578Z INFO webdriver: DATA { using: 'css selector', value: 'iframe' }
[0-1] 2024-10-29T19:44:28.584Z INFO webdriver: RESULT {
[0-1]   'element-6066-11e4-a52e-4f735466cecf': 'f.AE358AB7C24F7EDCD25A4C863B73CAFB.d.B6B6CBBB2EBA923DDA6A2B4B54B1083F.e.11'
[0-1] }
[0-1] 2024-10-29T19:44:28.585Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[159 bytes]>","awaitPromise":true,"arguments":[{"sharedId":"f.AE358AB7C24F7EDCD25A4C863B73CAFB.d.B6B6CBBB2EBA923DDA6A2B4B54B1083F.e.11"}],"target":{"context":"C8E9FB063B267CF87EE21020ADEBFCDD"}}
[0-1] Error in "should see element exists when using browser.switchToFrame"
Error: WebDriver Bidi command "script.callFunction" failed with error: no such frame - Context C8E9FB063B267CF87EE21020ADEBFCDD not found
    at BidiHandler.send (C:\dev\wdio-iframe-elements\node_modules\webdriver\build\index.js:253:23)
    at BidiHandler.scriptCallFunction (C:\dev\wdio-iframe-elements\node_modules\webdriver\build\index.js:704:31)
    at Browser.value (C:\dev\wdio-iframe-elements\node_modules\webdriver\build\index.js:1033:26)
    at Browser.wrapCommandFn (C:\dev\wdio-iframe-elements\node_modules\@wdio\utils\build\index.js:1380:32)
    at async Browser.execute (C:\dev\wdio-iframe-elements\node_modules\webdriverio\build\index.js:3085:20)
    at async Browser.wrapCommandFn (C:\dev\wdio-iframe-elements\node_modules\@wdio\utils\build\index.js:1380:23)
    at async switchToFrameUsingElement (C:\dev\wdio-iframe-elements\node_modules\webdriverio\build\index.js:4321:17)
    at async Browser.wrapCommandFn (C:\dev\wdio-iframe-elements\node_modules\@wdio\utils\build\index.js:1380:23)
    at async Context.<anonymous> (C:\dev\wdio-iframe-elements\switchToFrameTest.spec.js:7:3)
[0-1] 2024-10-29T19:44:28.606Z INFO webdriver: COMMAND deleteSession()
[0-1] 2024-10-29T19:44:28.606Z INFO webdriver: [DELETE] http://localhost:52425/session/bf7da795af3be3f78bb31418851b2b49
[0-1] 2024-10-29T19:44:28.636Z INFO webdriver: RESULT null
[0-1] 2024-10-29T19:44:28.636Z INFO webdriver: Kill driver process with PID 131568
[0-1] FAILED in chrome - file:///C:/dev/wdio-iframe-elements/switchToFrameTest.spec.js
2024-10-29T19:44:28.766Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-10-29T19:44:28.766Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 130.0.6723.91 windows #0-0] Running: chrome (v130.0.6723.91) on windows
[chrome 130.0.6723.91 windows #0-0] Session ID: ca2063a231a60f0aa5467d62ed9212fb
[chrome 130.0.6723.91 windows #0-0]
[chrome 130.0.6723.91 windows #0-0] (root)
[chrome 130.0.6723.91 windows #0-0] (root)
[chrome 130.0.6723.91 windows #0-0] 1 failing (1.3s)
------------------------------------------------------------------
[chrome 130.0.6723.91 windows #0-1] Running: chrome (v130.0.6723.91) on windows
[chrome 130.0.6723.91 windows #0-1] Session ID: bf7da795af3be3f78bb31418851b2b49
[chrome 130.0.6723.91 windows #0-1]
[chrome 130.0.6723.91 windows #0-1] (root)
[chrome 130.0.6723.91 windows #0-1] (root)
[chrome 130.0.6723.91 windows #0-1] 1 failing (990ms)


Spec Files:      0 passed, 2 failed, 2 total (100% completed) in 00:00:08
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue. I put up a PR with a fix.
