### ISSUE TITLE
[🐛 Bug]:< browser.deleteAllCookies() giving ' Error: function timed out, ensure the promise resolves within 300000 milliseconds'>

### ISSUE THREAD

**Issue by testerdv** [webdriverio/webdriverio#13824]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.25.4

### Node.js Version

14.18.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
from CI server logs:

capabilities: {
   alwaysMatch: {
       browserName: 'chrome',
       acceptInsecureCerts: true,
       'goog:chromeOptions': {
        args: ['--ignore-certificate-errors']
      }
   },
   firstMatch: [ {} ]
}
```

### What happened?

Hi

Upon running browser.deleteAllCookies() command on CI server I am getting following error:

_Error: function timed out, ensure the promise resolves within 300000 milliseconds
16:37:16      at Timeout.<anonymous> (/tmp/workspace/.../node_modules/@wdio/cucumber-framework/node_modules/@cucumber/cucumber/src/time.ts:69:14)
16:37:16      at listOnTimeout (internal/timers.js:557:17)
16:37:16      at processTimers (internal/timers.js:500:7)_

This is working fine locally but when I run on CI server(Jenkins) it is hanging upon browser.deleteAllCookies().

I am using wdio along with cucumber.

**My feature file step:**
And I open a new tab for www landing page

**Step Definition:**
When('I open a new tab for www landing page', async function () {

     await landingPage.openNewTabForLandingPage();
   
});

**PageObject Function:**

async openNewTabForLandingPage(){

       let landingPage = _some_url_;
        console.log(await browser.newWindow(landingPage));
        /*LOCAL will not be defined in CI server at all so maximizeWindow() will not execute on CI server */
        if(process.env.LOCAL){ 
            await browser.maximizeWindow();  _//IT IS ALSO NOT WORKING ON CI SERVER. HANGING HERE_
        }

        await browser.deleteAllCookies();     _//HANGING HERE_
...
}

**My package.json:**

{    ...
    "engines": {
        "node": ">=10.16.0",
        "npm": ">=6.9.0"
    },
    
    "scripts": {
        "test": "wdio wdio.conf.js",
    },
     "dependencies": {
      "@wdio/allure-reporter": "7.25.4",
        "@wdio/cli": "7.25.4",
        "@wdio/config": "7.25.4",
        "@wdio/cucumber-framework": "7.25.4",
        "@wdio/local-runner": "7.25.4",
        "@wdio/runner": "8.9.0",
        "@wdio/selenium-standalone-service": "7.25.4",
        "@wdio/spec-reporter": "7.25.4",
        "allure-commandline": "^2.22.1",
        "chai": "^4.3.7",
        "chromedriver": "^126.0.4",
        "concurrently": "^7.5.0",
        "cucumber-html-reporter": "^7.1.0",
        "jsonpath": "^1.1.1",
        "multiple-cucumber-html-reporter": "^3.4.0",
        "node-fetch": "^3.3.0",
        "node-notifier": "^10.0.1",
        "prettier": "^2.7.1",
        "standard-version": "^9.5.0",
        "wdio-chromedriver-service": "7.3.2",
        "wdio-cucumberjs-json-reporter": "4.4.3",
        "webdriverio": "7.25.4"
    }
   
}

**wdio.conf.js:**
require("dotenv").config();
const _ = require('lodash');
exports.config = _.extend(
  {
    runner: 'local',
    specs: [
     
        'features/**/*.feature',
    ],
    maxInstances: 3,

    capabilities: {
		browserName: 'chrome',
		maxInstances:3,
		acceptInsecureCerts: true,
	       'goog:chromeOptions': {
                     args: ['--ignore-certificate-errors']
               },

          path: '/wd/hub'
	},
    //logLevel: 'silent',
    logLevel: 'trace',
    sync: true,
    //sync: false,
    bail: 0,
    //baseUrl:process.env.appEnv,
    //Env:process.env.Env,
    waitforInterval: 100,
    waitforTimeout: 10000,
    connectionRetryTimeout: 300000,
    connectionRetryCount: 3,
    reporters: [
      'spec',
      
      [
        'allure',
        {
          outputDir: './allure-results/',
          disableWebdriverStepsReporting: false,
          useCucumberStepReporter: true,
        },
      ],
      
    ],
    screenshotPath: './allure-results/',
    disableWebdriverScreenshotsReporting: false,
    framework: 'cucumber',
    automationProtocol: 'webdriver',
    desiredCapabilities: {
       acceptSslCerts: true
     },
    cucumberOpts: {
      requireModule: [
        [
          '@babel/register',
          {
            ignore: [
              filepath =>
                filepath.includes('node_modules')
            ],
          },
        ],
      ],
      require: [
        'step-definitions/**/*.js'
      ],
      backtrace: true,
      failAmbiguousDefinitions: true,
      dryRun: false,
      failFast: false,
      format: ['pretty'],
      colors: true,
      snippets: true,
      source: true,
      profile: [],
      strict: false,
      tagExpression: process.env.tag,
      **timeout: 300000,**
      ignoreUndefinedDefinitions: false,
      tagsInTitle: false,
    },
    services: ['selenium-standalone'],
    
  },

);

**Logs:**
 2024-10-29T11:02:09.353Z INFO webdriver: COMMAND **deleteAllCookies()**
16:32:09  [0-9] 2024-10-29T11:02:09.353Z INFO webdriver: **[DELETE]** **http://localhost:4444/wd/hub/session/e5b023fb91ae0651f88ffbee894939a9/cookie**
...

 **Error: function timed out, ensure the promise resolves within 300000 milliseconds**
16:37:16      at Timeout.<anonymous> (/tmp/workspace/.../node_modules/@wdio/cucumber-framework/node_modules/@cucumber/cucumber/src/time.ts:69:14)
16:37:16      at listOnTimeout (internal/timers.js:557:17)
16:37:16      at processTimers (internal/timers.js:500:7)

The 300000 milliseconds given in above logs are  **timeout: 300000** in cucumberOpts in wdio.conf.js.

### What is your expected behavior?

Should delete the cookies and move towards next command in code.

### How to reproduce the bug.

**My feature file step:**
And I open a new tab for www landing page

**Step Definition:**
When('I open a new tab for www landing page', async function () {

     await landingPage.openNewTabForLandingPage();
   
});

**PageObject Function:**

async openNewTabForLandingPage(){

       let landingPage = _some_url_;
        console.log(await browser.newWindow(landingPage));
        /*LOCAL will not be defined in CI server at all so maximize Window() will not execute on CI server */
        if(process.env.LOCAL){ 
            await browser.maximizeWindow();  _//IT IS ALSO NOT WORKING ON CI SERVER. HANGING HERE_
        }

        await browser.deleteAllCookies();     _//HANGING HERE_
...
}

### Relevant log output

```typescript
**Logs:**
 2024-10-29T11:02:09.353Z INFO webdriver: COMMAND **deleteAllCookies()**
16:32:09  [0-9] 2024-10-29T11:02:09.353Z INFO webdriver: **[DELETE]** **http://localhost:4444/wd/hub/session/e5b023fb91ae0651f88ffbee894939a9/cookie**
...

 **Error: function timed out, ensure the promise resolves within 300000 milliseconds**
16:37:16      at Timeout.<anonymous> (/tmp/workspace/.../node_modules/@wdio/cucumber-framework/node_modules/@cucumber/cucumber/src/time.ts:69:14)
16:37:16      at listOnTimeout (internal/timers.js:557:17)
16:37:16      at processTimers (internal/timers.js:500:7)

The 300000 milliseconds given in above logs are  **timeout: 300000** in cucumberOpts in wdio.conf.js.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by testerdv** [comment]
Hi

What kind of reproducible example you need? I already mentioned my feature file step, step definition, page object function code, package.json and wdio.conf.js. 

I cannot create reproducible example by pushing code into github due to company restrictions on pushing code through company laptop to github. 

I already mentioned that this problem is happening on jenkins CI server not locally. There is also restriction here to what I can run on CI server.

Everything I mentioned in this issue.

**Comment by christian-bromann** [comment]
@testerdv ideally try to create a new project that can reproduce this with the minimal require files as possible.

**Comment by christian-bromann** [comment]
Closing due to inactivity.
