### ISSUE TITLE
[🐛 Bug]: ERROR @wdio/runner: ReferenceError: browser is not defined

### ISSUE THREAD

**Issue by T0mas-H** [webdriverio/webdriverio#13832]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.2.5

### Node.js Version

20.17

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
    {
      browserName: 'chrome',
      'wdio:enforceWebDriverClassic': true,
      'goog:chromeOptions': {
        args: ['--disable-search-engine-choice-screen'],
      },
    },
  ],
```

### What happened?

I am running test for my web page,
on start up I can see error about browser not being defined, same happened when I run native app tests on SauceLabs.
When I replace in my local index.js file line 3008 "browser.isBidi" with false webdriver is initialised and test continues as expected.
<img width="695" alt="image" src="https://github.com/user-attachments/assets/ee7c2bb2-9388-46e3-a986-87e9ec3f8ca6">

### How to reproduce the bug.

start any test
analyse code below from index.js
<img width="689" alt="image" src="https://github.com/user-attachments/assets/a196bd97-7594-4adc-bd9e-a56dc072f641">

### Relevant log output

```typescript
[0-0] 2024-10-29T21:35:59.498Z ERROR @wdio/runner: ReferenceError: browser is not defined
[0-0]     at ContextManager.#isEnabled (/Users/tomas.surname/project_path/node_modules/.pnpm/webdriverio@9.2.5/node_modules/webdriverio/build/index.js:3008:44)
[0-0]     at new ContextManager (/Users/tomas.surname/project_path/node_modules/.pnpm/webdriverio@9.2.5/node_modules/webdriverio/build/index.js:2992:25)
[0-0]     at getContextManager (/Users/tomas.surname/project_path/node_modules/.pnpm/webdriverio@9.2.5/node_modules/webdriverio/build/index.js:2983:22)
[0-0]     at remote (/Users/tomas.surname/project_path/node_modules/.pnpm/webdriverio@9.2.5/node_modules/webdriverio/build/index.js:7483:5)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[0-0]     at async Runner._startSession (file:///Users/tomas.surname/project_path/node_modules/.pnpm/@wdio+runner@9.2.5/node_modules/@wdio/runner/build/index.js:781:23)
[0-0]     at async Runner._initSession (file:///Users/tomas.surname/project_path/node_modules/.pnpm/@wdio+runner@9.2.5/node_modules/@wdio/runner/build/index.js:755:22)
[0-0]     at async Runner.run (file:///Users/tomas.surname/project_path/node_modules/.pnpm/@wdio+runner@9.2.5/node_modules/@wdio/runner/build/index.js:662:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Apology for the inconvenience , I pushed a fix and will release it now.

**Comment by T0mas-H** [comment]
Thank you for your superfast response <3, with version 9.2.6 tests are running as expected
