### ISSUE TITLE
[🐛 Bug]: browser.switchFrame(null) throws TypeError in Webdriver Classic mode

### ISSUE THREAD

**Issue by isc-aray** [webdriverio/webdriverio#13868]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.2.11

### Node.js Version

20.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    "wdio:enforceWebDriverClassic": true
}
```

### What happened?

An error is thrown when attempting to switch to a parent frame using webdriver classic. 

### What is your expected behavior?

The context should be switched to the parent frame.

### How to reproduce the bug.

```js
browser.switchFrame(null);
```

### Relevant log output

```typescript
TypeError: Cannot read properties of null (reading 'getElement')
at isPossiblyUnresolvedElement (.../node_modules/webdriverio/build/index.js:4190:54)
at Browser.switchFrame (.../node_modules/webdriverio/build/index.js:4199:9)
at Browser.wrapCommandFn (.../node_modules/@wdio/utils/build/index.js:884:32)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by isc-aray** [comment]
This issue is caused by the insertion of lines 87 through 93 in [packages/webdriverio/src/commands/browser/switchFrame.ts](https://github.com/webdriverio/webdriverio/commit/2d675daa7ccdfe7cc56229c64bfdfc2a4057ee87#diff-44ebe289e8d61d0e57ebd36f71e0d6084be53ac29fd5005ef3958d8e0c24690a) introduced in 2d675da.
