### ISSUE TITLE
[🐛 Bug]: wdio features breaking with chrome for testing latest stable version 131

### ISSUE THREAD

**Issue by rahuljain-dev** [webdriverio/webdriverio#13918]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.40.6

### Node.js Version

18.18.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
 browserName: 'chrome',
  acceptInsecureCerts: true,
  browserVersion: 'stable',
}
```

### What happened?

wdio automation test cases starts breaking with latest verison of chrome for testing browser 131, till stable version 130 tests are working fine.

another if we remove capabilities( options.w3c = false) that we are also using then we can see some of the features starts to work, but the issue is UI is not intractable  as click options are not working correctly

### What is your expected behavior?

wdio features should work as it is working with chrome for testing browser version till 130.

### How to reproduce the bug.

Steps to Reproduce:
1. Run the wdio feature files as usual in chrome version 131 the test will starts breaking
2. run the same features on chrome 130 it will work

### Relevant log output

```typescript
Error: element ("nuxeo-app:not([unresolved])") still not displayed after 24000ms
    at file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/runner/node_modules/webdriverio/build/commands/browser/waitUntil.js:39:23
    at Element.wrapCommandFn (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/utils/build/shim.js:90:29)
    at Element.elementErrorHandlerCallbackFn (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/runner/node_modules/webdriverio/build/middlewares.js:19:32)
    at Element.wrapCommandFn (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/utils/build/shim.js:90:29)
    at Element.wrapCommandFn (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/utils/build/shim.js:90:29)
    at Element.elementErrorHandlerCallbackFn (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/runner/node_modules/webdriverio/build/middlewares.js:19:32)
    at Element.wrapCommandFn (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/utils/build/shim.js:90:29)
    at Element.wrapCommandFn (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/utils/build/shim.js:90:29)
    at Element.wrapCommandFn (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/utils/build/shim.js:90:29)
    at Element.elementErrorHandlerCallbackFn (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/runner/node_modules/webdriverio/build/middlewares.js:19:32)
    at Element.wrapCommandFn (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/utils/build/shim.js:90:29)
    at /Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/pages/ui.js:112:9
    at World.<anonymous> (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/features/step_definitions/login.js:44:13)
    at wrapPromiseWithTimeout (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/time.ts:55:10)
    at Object.run (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/user_code_runner.ts:86:16)
    at Object.run (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/runtime/step_runner.ts:50:20)
    at TestCaseRunner.invokeStep (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:137:12)
    at TestCaseRunner.runStep (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:334:20)
    at /Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:240:34
    at TestCaseRunner.aroundTestStep (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:170:28)
    at TestCaseRunner.runAttempt (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:218:7)
    at TestCaseRunner.run (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:188:29)
    at Runtime.runTestCase (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/runtime/index.ts:89:20)
    at Runtime.start (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/runtime/index.ts:116:7)
    at runCucumber (/Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@cucumber/cucumber/src/api/run_cucumber.ts:125:19)
    at CucumberAdapter.run (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/cucumber-framework/build/index.js:188:33)
    at Runner.run (file:///Users/rahul.jain5/Downloads/nuxeocode/nuxeo-web-ui/packages/nuxeo-web-ui-ftest/node_modules/@wdio/runner/build/index.js:157:24)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by axeleriksson147** [comment]
Agree, we're seeing the same problems.

**Comment by christian-bromann** [comment]
Closing due to inactivity.
