### ISSUE TITLE
[🐛 Bug]: Wdio can hangs generating allure-report when combining afterAll hook and a leak of startStep

### ISSUE THREAD

**Issue by dprevost-LMI** [webdriverio/webdriverio#13915]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.39.0

### Node.js Version

v18.20.4

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
config {
  "runner": "local",
  "waitforTimeout": 5000,
  "connectionRetryTimeout": 10000,
  "connectionRetryCount": 3,
  "framework": "mocha",
  "specs": [
    "../../src/tests/**/*.test.ts"
  ],
  "mochaOpts": {
    "ui": "bdd",
    "timeout": 240000,
    "retries": 0
  },
  "reporters": [
    [
      "allure",
      {
        "outputDir": "logs/allure-results",
        "addConsoleLogs": true
      }
    ],
    [
      "spec",
      {
        "showPreface": false,
        "realtimeReporting": false
      }
    ]
  ],
  "services": [
    [
      "appium",
      {
        "args": {
          "port": 4723,
          "relaxedSecurity": true,
          "log": "./logs/appium.log",
          "logFilters": "./appiumPasswordLogFilters.json"
        }
      }
    ]
  ],
  "capabilities": [
    {
      "platformName": "Android",
      "appium:udid": "MASKED",
      "appium:automationName": "UiAutomator2",
      "appium:appPackage": "com.mypackage",
      "appium:appActivity": "MainActivity",
      "appium:newCommandTimeout": 240,
      "appium:noReset": true,
      "goto:caps": {
        "isLocalRun": true,
        "iosEnterpriseBuild": false,
        "testUserEmail": "",
        "isDevMode": true
      },
      "appium:settings[allowInvisibleElements]": true,
      "appium:locale": "en_US",
      "appium:language": ""
    }
  ]
}
```

### What happened?

When a precise test structure (see code in next section) combines an `afterAll` hook with an allure `startStep` that was never ended with `endStep`, the allure-reporter throws an error on the `on:suite:end`, and since the `WDIOReporter` does not seem to handle it gracefully, the reporter hangs indefinitely.

This case happened to us precisely because we used the `waitForEnabled` method on a selector, which starts steps without finishing them. Switching to `waitForExist` fixed the `startStep` leaks, and as a consequence, it stopped throwing on the onEndTestSuite, and therefore, the report stopped hanging.

On my side, I added a patch with a try-catch on [this line](https://github.com/webdriverio/webdriverio/blob/bd45bf9b879b4947d2adfa0197ee7b8e2d027774/packages/wdio-reporter/src/index.ts#L204) (on both v8 and v9) with a console log in case we ever get that problem again.

### What is your expected behavior?

Even if a reporter throws on the `on:suite:end`, the `WDIOReporter` should be able to report the error and stop instead of hanging.

### How to reproduce the bug.

To reproduce, create a test file using the information below.
Note: Our real-case scenario is way more complex than the one below, but I was able to simplify it and reach the below.

```typescript
import { startStep } from '@wdio/allure-reporter';

describe('A', function () {
  context('B', () => {
    before(async () => {
      console.log('Before B step');

      this.afterAll(async () => {
        console.log('After all B step');
      });

      try {
        startStep('Before B step');
        console.log('waitForEnabled-before');
        await $('element-no-enalbed').waitForEnabled();
      } catch (error) {
        console.log('waitForEnabled-error');
        // silence error
      }
    });

    context('C', () => {
      it('D', async () => {
        console.log('Test D step');
        expect(true).toBe(true);
      });
    });
  });
});
```

To get the same log output as I set below, a try/catch will be required in the following file `/node_modules/@wdio/reporter/build/index.js#ln165`
```typescript
        this.on('suite:end', /* istanbul ignore next */ (suite) => {
            const suiteStat = this.suites[suite.uid];
            suiteStat.complete();
            this.currentSuites.pop();
            /* added try-catch below */
            try {
                this.onSuiteEnd(suiteStat);
            } catch(e) {
                console.error("@wdio/reporter: Error in onSuiteEnd, potential stepStart not ended. Happens with waitForEnabled use waitForExists instead", e)
            }
        });
```

### Relevant log output

The log below shows that the test hangs forever without the try/cath.
```
RUNNING in Android - file:///src/tests/example/template.test.ts
Before B step
waitForEnabled-before
waitForEnabled-error
Test D step
After all B step <==== last log ever output
```

With the try/catch in `/node_modules/@wdio/reporter/build/index.js#ln165`
```
RUNNING in Android - file:///src/tests/example/template.test.ts
Before B step
waitForEnabled-before
waitForEnabled-error
Test D step
After all B step
@wdio/reporter: Error in onSuiteEnd, potential stepStart not ended. Happens with waitForEnabled use waitForExists instead Error: There isn't any active suite!
    at AllureReporter._endSuite (node_modules/@wdio/allure-reporter/build/reporter.js:80:19)
    at AllureReporter.onSuiteEnd (node_modules/@wdio/allure-reporter/build/reporter.js:307:14)
    at AllureReporter.<anonymous> (node_modules/@wdio/reporter/build/index.js:166:22)
    at AllureReporter.emit (node:events:517:28)
    at AllureReporter.emit (node:domain:489:12)
    at node_modules/@wdio/runner/build/reporter.js:47:56
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (node_modules/@wdio/runner/build/reporter.js:47:25)
    at MochaAdapter.emit (node_modules/@wdio/mocha-framework/build/index.js:162:24)
    at Runner.emit (node:events:529:35)
PASSED in Android - file:///src/tests/example/template.test.ts
Report successfully generated to logs/allure-report
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by dprevost-LMI** [comment]
I just tested on wdio v9 and I reproduce too (`allure-reporter 9.2.14` & `wdio 9.3.1`

**Comment by BorisOsipov** [comment]
>This case happened to us precisely because we used the waitForEnabled method on a selector, which starts steps without finishing them.

This should be fixed. Would you mind creating a separate issue for it?

**Comment by dprevost-LMI** [comment]
> This should be fixed. Would you mind creating a separate issue for it?

Because I spent 8 hours understanding why the report hangs, and as mentioned, I would expect the framework to be more resilient and not bug be cause of that!

**Comment by BorisOsipov** [comment]
@dprevost-LMI 

Thank you very much. I suspect that there are not only `waitForEnabled` commands with such strange behavior. If we can figure out why `waitForEnabled` behaves this way, we might be able to identify and fix other similar issues.

Internally, the Allure reporter heavily relies on the order of events. If there is a case where a step starts but does not finish, it breaks the reporter and results in a corrupted report (e.g., [webdriverio/webdriverio#13468](https://github.com/webdriverio/webdriverio/issues/13468)).

**Comment by dprevost-LMI** [comment]
@BorisOsipov, I will try to find more time this weekend to dig the `waitForEnabled` (and enter a separate issue), but to have a more stable framework, does the try/catch I added to make sense? I doubt it since this is the only `on:XXX` needing it to fail correctly. If someone can give me some hints on how to fix this, I will do a PR, and if the try-catch is the way to go, I'll open that in minutes!

**Comment by dprevost-LMI** [comment]
In short, the problem is that we do not have the same number of calls to the `beforeCommand` and `afterCommand`, so the allure-reporter starts more steps than it can end.

The problem is related to the `GET` request of `isElementEnabled` returning a 404 with the error `stale element reference` (See log below). In this case, it throws [an error here](https://github.com/webdriverio/webdriverio/blob/db5eb1b432c0e5a58089a3f725c61ac1cfe82bbe/packages/webdriver/src/request/index.ts#L256) so the `then` of the `request.makeRequest` [here](https://github.com/webdriverio/webdriverio/blob/db5eb1b432c0e5a58089a3f725c61ac1cfe82bbe/packages/webdriver/src/command.ts#L130) will not proceed and will not do the required [emit('result')](https://github.com/webdriverio/webdriverio/blob/db5eb1b432c0e5a58089a3f725c61ac1cfe82bbe/packages/webdriver/src/command.ts#L143) that trigger the `afterCommand`. In consequence, we will lose a endStep

In short, I assume that the `request.makeRequest` [here](https://github.com/webdriverio/webdriverio/blob/db5eb1b432c0e5a58089a3f725c61ac1cfe82bbe/packages/webdriver/src/command.ts#L130) needs a `catch` that will do the `this.emit('result'` for the `afterCommand` to get triggered.

However, by doing so, we will return an error as a `result` that people would not expect, so I wonder about the impact.

Anyway, I added the below catch for fun, which finally made all the `startStep` and `endStep` even.

If someone can guide me on the proper changes, I can try to open a PR. 
The options I'm seeing:
1. Add the catch and emit the error as a result
2. Remove the throws so the `then` can trigger correctly
3. Implement a new emit('error') that would also trigger a new`afterCommandError` that would fix the problem without sending an unexpected error result

```
.catch((err) => {
      log4.error("ERROR", err);
      this.emit("result", { command, method, endpoint, body, result: { error: err } });
      throw err;
    });
```



```
beforeCommand {
  command: 'isElementEnabled',
  method: 'GET',
  endpoint: '/session/:sessionId/element/00000000-0000-1bac-0000-12a400000c98/enabled',
  body: {}
}
response {
  statusCode: 404,
  body: {
    value: {
      error: 'stale element reference',
      message: 'androidx.test.uiautomator.StaleObjectException',
      stacktrace: 'io.appium.uiautomator2.common.exceptions.StaleElementReferenceException: androidx.test.uiautomator.StaleObjectException\n' +
        '\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:63)\n' +
        '\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:259)\n' +
        '\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:253)\n' +
        '\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:77)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n' +
        '\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n' +
        '\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n' +
        '\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n' +
        '\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n' +
        '\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n' +
        '\tat io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n' +
        '\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n' +
        '\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n' +
        '\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n' +
        '\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n' +
        '\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)\n' +
        '\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)\n' +
        '\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n' +
        '\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n' +
        '\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\n' +
        '\tat java.lang.Thread.run(Thread.java:1012)\n' +
        'Caused by: androidx.test.uiautomator.StaleObjectException\n' +
        '\tat androidx.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:1018)\n' +
        '\tat androidx.test.uiautomator.UiObject2.isEnabled(UiObject2.java:450)\n' +
        '\tat io.appium.uiautomator2.model.UiObject2Element.getAttribute(UiObject2Element.java:100)\n' +
        '\tat io.appium.uiautomator2.handler.GetElementAttribute.safeHandle(GetElementAttribute.java:24)\n' +
        '\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n' +
        '\t... 33 more\n'
    }
  }
}
beforeCommand {
  command: 'findElement',
  method: 'POST',
  endpoint: '/session/:sessionId/element',
  body: { using: 'xpath', value: '//android.widget.EditText' }
}
response {
  statusCode: 200,
  body: {
    value: {
      'element-6066-11e4-a52e-4f735466cecf': '00000000-0000-1bac-0000-130200000c98',
      ELEMENT: '00000000-0000-1bac-0000-130200000c98'
    }
  }
}
afterCommand {
  command: 'findElement',
  method: 'POST',
  endpoint: '/session/:sessionId/element',
  body: { using: 'xpath', value: '//android.widget.EditText' },
  result: {
    value: {
      'element-6066-11e4-a52e-4f735466cecf': '00000000-0000-1bac-0000-130200000c98',
      ELEMENT: '00000000-0000-1bac-0000-130200000c98'
    }
  }
}
Nb of steps missing end steps: 1
beforeCommand {
  command: 'isElementEnabled',
  method: 'GET',
  endpoint: '/session/:sessionId/element/00000000-0000-1bac-0000-12a400000c98/enabled',
  body: {}
}
response {
  statusCode: 404,
  body: {
    value: {
      error: 'stale element reference',
      message: "The element 'By.xpath: //android.widget.EditText' is not linked to the same object in DOM anymore",
      stacktrace: "io.appium.uiautomator2.common.exceptions.StaleElementReferenceException: The element 'By.xpath: //android.widget.EditText' is not linked to the same object in DOM anymore\n" +
        '\tat io.appium.uiautomator2.model.ElementsCache.restore(ElementsCache.java:122)\n' +
        '\tat io.appium.uiautomator2.model.ElementsCache.get(ElementsCache.java:153)\n' +
        '\tat io.appium.uiautomator2.handler.GetElementAttribute.safeHandle(GetElementAttribute.java:23)\n' +
        '\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n' +
        '\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:259)\n' +
        '\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:253)\n' +
        '\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:77)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n' +
        '\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n' +
        '\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n' +
        '\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n' +
        '\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n' +
        '\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n' +
        '\tat io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n' +
        '\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n' +
        '\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n' +
        '\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n' +
        '\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n' +
        '\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n' +
        '\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)\n' +
        '\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)\n' +
        '\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n' +
        '\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n' +
        '\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\n' +
        '\tat java.lang.Thread.run(Thread.java:1012)\n'
    }
  }
}
isElementEnabled
beforeCommand {
  command: 'isElementEnabled',
  method: 'GET',
  endpoint: '/session/:sessionId/element/00000000-0000-1bac-0000-130200000c98/enabled',
  body: {}
}
response { statusCode: 200, body: { value: true } }
afterCommand {
  command: 'isElementEnabled',
  method: 'GET',
  endpoint: '/session/:sessionId/element/00000000-0000-1bac-0000-130200000c98/enabled',
  body: {},
  result: { value: true }
}
Nb of steps missing end steps: 2
Starting test:  "before all" hook for given an authenticated user @smoke @androidOnly
Starting test:  should navigate back @smoke
Starting test:  should navigate back @smoke
Test
beforeCommand {
  command: 'terminateApp',
  method: 'POST',
  endpoint: '/session/:sessionId/appium/device/terminate_app',
  body: { appId: 'com.logmein.gotoconnect' }
}
response { statusCode: 200, body: { value: true } }
afterCommand {
  command: 'terminateApp',
  method: 'POST',
  endpoint: '/session/:sessionId/appium/device/terminate_app',
  body: { appId: 'com.logmein.gotoconnect' },
  result: { value: true }
}
Nb of steps missing end steps: 2
```

**Comment by christian-bromann** [comment]
fixed by https://github.com/webdriverio/webdriverio/pull/13958

**Comment by christian-bromann** [comment]
Actually I think the error still exists in the Allure reporter, it just doesn't cause other reporters to fail either.

**Comment by christian-bromann** [comment]
Awesome, thanks a lot @dprevost-LMI 🙏
