### ISSUE TITLE
[🐛 Bug]: browser-runner:vite chokes on missing .map files

### ISSUE THREAD

**Issue by kensternberg-authentik** [webdriverio/webdriverio#13924]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.3

### Node.js Version

20.13.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: "chrome",
    browserVersion: 131,
    operatingSystem: "MacOS Sonoma 14.6.1"
}
```

### What happened?

While running the tests, the browser-runner is throwing this error:

```
2024-11-26T16:24:44.425Z WARN @wdio/browser-runner:vite: Failed to load source map for /Users/ken/projects/dev/web/node_modules/@wdio/browser-runner/build/third_party/mocha.js.
Error: An error occurred while trying to read the map file at mocha.js.map
Error: ENOENT: no such file or directory, open '/Users/ken/projects/dev/web/node_modules/@wdio/browser-runner/build/third_party/mocha.js.map'
    at async open (node:internal/fs/promises:636:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at extractSourcemapFromFile (/Users/ken/projects/dev/web/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:21001:53)
    at loadAndTransform (/Users/ken/projects/dev/web/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51892:27)
```

I can confirm there is no `.map` file at that location.  Vite is clearly expecting it, but it's not included in the vendor bundle included with `@wdio/browser-runner`.

### What is your expected behavior?

That Vite would run without this error.  

### How to reproduce the bug.

Run a unit test with a Typescript-based project, mocha and webdriverIO.

### Relevant log output

```typescript
2024-11-26T16:24:44.425Z WARN @wdio/browser-runner:vite: Failed to load source map for /Users/ken/projects/dev/web/node_modules/@wdio/browser-runner/build/third_party/mocha.js.
Error: An error occurred while trying to read the map file at mocha.js.map
Error: ENOENT: no such file or directory, open '/Users/ken/projects/dev/web/node_modules/@wdio/browser-runner/build/third_party/mocha.js.map'
    at async open (node:internal/fs/promises:636:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at extractSourcemapFromFile (/Users/ken/projects/dev/web/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:21001:53)
    at loadAndTransform (/Users/ken/projects/dev/web/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51892:27)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
These are just warnings and won't effect the test result but we may still want to fix this. I'ld suggest to just have the [testrunner Vite plugin](https://github.com/webdriverio/webdriverio/blob/9e5a7982e900fea1b0b11c95c3654471cd4a2e3a/packages/wdio-browser-runner/src/vite/plugins/testrunner.ts) to return an empty file for this.

Any contributions for this would be appreciated!

**Comment by ProdanSergey** [comment]
I can confirm the same behaviour:

```
2025-01-22T11:50:43.964Z WARN @wdio/browser-runner:vite: Failed to load source map for ***/Documents/Projects/wmi/node_modules/@wdio/browser-runner/build/third_party/mocha.js.
Error: An error occurred while trying to read the map file at mocha.js.map
Error: ENOENT: no such file or directory, open '***/Documents/Projects/wmi/node_modules/@wdio/browser-runner/build/third_party/mocha.js.map'
```

However immediate second run is always successful

**Comment by christian-bromann** [comment]
I pushed a fix that removes the source map reference from the mocha third party script.
