### ISSUE TITLE
[🐛 Bug]: Issue running wdio tests (v8) in aws lambda on CI 

### ISSUE THREAD

**Issue by ZehavitSaban** [webdriverio/webdriverio#13933]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.40.6

### Node.js Version

20

### Mode

WDIO Testrunner

### What happened?

We are running wdio on AWS Lambda Node 20, using the devtools protocol (via devtools-service and puppeteer).

First, we build and deploy lambda with the following dependencies. So, when we invoke the Lambda, it already comes with these dependencies pre-installed on the Lambda.

 "dependencies": {
    "@wdio/cli": "7.33.0",
    "@wdio/devtools-service": "7.33.0",
    "@wdio/local-runner": "7.33.0",
    "@wdio/mocha-framework": "7.33.0",
    "@wdio/spec-reporter": "7.33.0",
    "axios": "1.7.4",
    "chai": "4.3.10",
    "chalk": "4.1.2",
    "@sparticuz/chromium": "130.0.0",
    "dotenv": "16.3.1",
    "lodash": "4.17.21",
    "moment": "2.29.4",
    "node-html-parser": "6.1.11",
    "unzipper": "0.10.14",
    "uuid": "9.0.1",
    "stream": "0.0.2",
    "@aws-sdk/client-s3": "3.465.0"
  },
  "devDependencies": {
    "@dudadev/prettier-config": "1.0.1",
    "prettier": "3.1.0",
    "puppeteer": "23.6.1"
  }

Inside the lambda, we use S3 to get the company's internal automation framework and the test code we want to run. Then, we build the test env inside the lambda, create local configurations, wire things up, wire everything with puppeteer , and start the test.

Basically, with WDIO v7 (7.33.0) it works fine. We can run tests inside the AWS Lambda and then integrate it with our CI/CD.
But, with WDIO v8 it doesn't work. Tests run OK locally in my machine but FAIL on CI.

### How to reproduce the bug.

 
 const wdio = new Launcher('./wdio.conf.js', {
       spec: [process.env.SPEC_FILE],
   });

   try {
       const specStatusCode = await wdio.run();
   } catch (e) {
       console.log('Failed in wdio.run() command');
       console.log(e);
   } 

### Relevant log output

```typescript
"@wdio/cli": "8.40.6",
    "@wdio/devtools-service": "8.40.2",
    "@wdio/local-runner": "8.40.6",
    "@wdio/mocha-framework": "8.40.6",
    "@wdio/spec-reporter": "8.40.6",

Execution of 1 workers started at 2024-11-28T09:27:28.645Z
2024-11-28T09:27:28.700Z DEBUG @wdio/utils:initializeServices: initialize service "devtools" as NPM package
2024-11-28T09:27:29.437Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-11-28T09:27:29.438Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2024-11-28T09:27:29.443Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
2024-11-28T09:27:29.630Z INFO webdriver: Downloading Chromedriver v131.0.6778.85
2024-11-28T09:27:29.664Z INFO webdriver: Setting up chrome v131.0.6778.85
2024-11-28T09:27:30.819Z INFO webdriver: Download of Chromedriver v131.0.6778.85 was successful
2024-11-28T09:27:35.549Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-11-28T09:27:35.549Z INFO @wdio/local-runner: Start worker 0-0 with arg:
2024-11-28T09:27:35.558Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
[0-0] 2024-11-28T09:27:36.741Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2024-11-28T09:27:37.128Z DEBUG @wdio/runner: init remote session
[0-0] 2024-11-28T09:27:37.134Z DEBUG @wdio/utils:initializeServices: initialize service "devtools" as NPM package
[0-0] RUNNING in chrome - file:///out/main/specs/dashboard/custom-domain/create-sites-domain-test.js
[0-0] 2024-11-28T09:27:38.215Z DEBUG @wdio/runner: init remote session
[0-0] 2024-11-28T09:27:38.216Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-11-28T09:27:38.458Z INFO webdriver: Setting up chrome v131.0.6778.85
[0-0] 2024-11-28T09:27:38.459Z INFO webdriver: Using Chromedriver v131.0.6778.85 from cache directory /tmp
[0-0] 2024-11-28T09:27:48.491Z INFO @wdio/utils: Started Chromedriver v131.0.6778.85 with params --port=41385 --allowed-origins=* --allowed-ips=0.0.0.0 in 10116ms on port 41385
[0-0] 2024-11-28T09:27:48.564Z INFO webdriver: [POST] http://127.0.0.1:41385/session
[0-0] 2024-11-28T09:27:48.565Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       'goog:chromeOptions': [Object],
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/tmp/chrome/linux-131.0.6778.85/chrome-linux64/chrome',
[0-0]       args: [Array]
[0-0]     },
[0-0]     browserName: 'chrome',
[0-0]     acceptInsecureCerts: true
[0-0]   }
[0-0] }
[0-0] 2024-11-28T09:27:48.907Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
2024-11-28T09:27:49.022Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///out/main/specs/dashboard/custom-domain/create-sites-domain-test.js
2024-11-28T09:27:49.023Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-11-28T09:27:49.023Z INFO @wdio/cli:launcher: Run onComplete hook
Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:20
2024-11-28T09:27:49.024Z INFO @wdio/local-runner: Shutting down spawned worker
2024-11-28T09:27:49.275Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-11-28T09:27:49.275Z INFO @wdio/local-runner: shutting down
Saving lambdaSpecResultJson to file /tmp/wdio/reports/lambdaSpecResultJson.json
Successfully saved the file.
2024-11-28T09:27:49.295Z
[0-0] 2024-11-28T09:27:48.905Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:41385
[0-0] 2024-11-28T09:27:48.905Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:41385
2024-11-28T09:27:49.295Z
[0-0] at ClientRequest.<anonymous> (file:///tmp/wdio/node_modules/got/dist/source/core/index.js:790:107)
2024-11-28T09:27:49.295Z
[0-0] at Object.onceWrapper (node:events:634:26)
2024-11-28T09:27:49.295Z
[0-0] at ClientRequest.emit (node:events:531:35)
2024-11-28T09:27:49.295Z
[0-0] at ClientRequest.emit (node:domain:488:12)
2024-11-28T09:27:49.295Z
[0-0] at emitErrorEvent (node:_http_client:101:11)
2024-11-28T09:27:49.295Z
[0-0] at Socket.socketErrorListener (node:_http_client:504:5)
2024-11-28T09:27:49.295Z
[0-0] at Socket.emit (node:events:519:28)
2024-11-28T09:27:49.295Z
[0-0] at Socket.emit (node:domain:488:12)
2024-11-28T09:27:49.295Z
[0-0] at emitErrorNT (node:internal/streams/destroy:169:8)
2024-11-28T09:27:49.295Z
[0-0] at emitErrorCloseNT (node:internal/streams/destroy:128:3)
2024-11-28T09:27:49.295Z
[0-0] at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
2024-11-28T09:27:49.295Z
[0-0] 2024-11-28T09:27:48.906Z ERROR @wdio/runner: Error: Failed to create session.
2024-11-28T09:27:49.295Z
[0-0] Unable to connect to "http://127.0.0.1:41385/", make sure browser driver is running on that address.
2024-11-28T09:27:49.295Z
[0-0] It seems like the service failed to start or is rejecting any connections.
2024-11-28T09:27:49.295Z
[0-0] at startWebDriverSession (file:///tmp/wdio/node_modules/webdriver/build/utils.js:69:15)
2024-11-28T09:27:49.295Z
[0-0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-11-28T09:27:49.295Z
[0-0] at async WebDriver.newSession (file:///tmp/wdio/node_modules/webdriver/build/index.js:19:45)
2024-11-28T09:27:49.295Z
[0-0] at async remote (file:///tmp/wdio/node_modules/webdriverio/build/index.js:46:22)
2024-11-28T09:27:49.295Z
[0-0] at async Runner._startSession (file:///tmp/wdio/node_modules/@wdio/runner/build/index.js:241:29)
2024-11-28T09:27:49.295Z
[0-0] at async Runner._initSession (file:///tmp/wdio/node_modules/@wdio/runner/build/index.js:207:25)
2024-11-28T09:27:49.295Z
[0-0] at async Runner.run (file:///tmp/wdio/node_modules/@wdio/runner/build/index.js:88:19)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by ZehavitSaban** [comment]
This is my wdio.conf.js:

```
require('dotenv').config();

const chromeFlags = [
    '--headless',
    '--single-process',
    '--no-sandbox',
];

exports.config = {
    runner: 'local',
    specs: ['./out/main/specs/**/*.js',
        './out/wdio-automation-infra-tests/**/*.js'],
    exclude: [],
    maxInstances: 10,
    capabilities: [
        {
            'goog:chromeOptions': {
                args: chromeFlags,
            },
            maxInstances: 5,
            browserName: 'chrome',
            acceptInsecureCerts: true,
        },
    ],
    logLevel: 'debug',
    bail: 0,
    baseUrl: process.env.BASE_URL,
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['devtools'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 160000,
    },
};
```

**Comment by christian-bromann** [comment]
@ZehavitSaban have you tried updating to WebdriverIO v9? We have fixed a lot of issues since we released v9 and we would strongly recommend to use the latest version of WebdriverIO.

**Comment by ZehavitSaban** [comment]
Hi @christian-bromann ,
I tried to upgrade to v9.
This is my package.json:
```
{
  "name": "duda-wdio-js",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "prettier": "@dudadev/prettier-config",
  "dependencies": {
    "@wdio/cli": "9.4.1",
    "@wdio/devtools-service": "8.40.6",
    "@wdio/local-runner": "9.4.1",
    "@wdio/mocha-framework": "9.2.8",
    "@wdio/spec-reporter": "9.2.14",
    "axios": "1.7.4",
    "chai": "4.3.10",
    "chalk": "4.1.2",
    "@sparticuz/chromium": "130.0.0",
    "dotenv": "16.3.1",
    "lodash": "4.17.21",
    "moment": "2.29.4",
    "node-html-parser": "6.1.11",
    "unzipper": "0.10.14",
    "uuid": "9.0.1",
    "stream": "0.0.2",
    "@aws-sdk/client-s3": "3.465.0"
  },
  "devDependencies": {
    "@dudadev/prettier-config": "1.0.1",
    "prettier": "3.1.0",
    "puppeteer": "23.6.1"
  }
}
```

Node version:20

This is my wdio.conf.js:

require('dotenv').config();

const chromeFlags = [
    '--headless',
    '--single-process',
    '--no-sandbox',
];

exports.config = {
    runner: 'local',
    specs: ['./out/main/specs/**/*.js',
        './out/wdio-automation-infra-tests/**/*.js'],
    exclude: [],
    maxInstances: 10,
    capabilities: [
        {
            'goog:chromeOptions': {
                args: chromeFlags,
            },
            maxInstances: 5,
            browserName: 'chrome',
            acceptInsecureCerts: true,
        },
    ],
    logLevel: 'debug',
    bail: 0,
    baseUrl: process.env.BASE_URL,
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['devtools'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 160000,
    },
};

**Now got this error:**
Execution of 1 workers started at 2024-12-04T10:43:33.358Z
2024-12-04T10:43:33.379Z DEBUG @wdio/utils:initializeServices: initialize service "devtools" as NPM package
2024-12-04T10:43:33.993Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-12-04T10:43:33.994Z INFO @wdio/utils: Setting up browser driver for: chrome@stable
2024-12-04T10:43:34.006Z INFO @wdio/utils: Setting up browser binaries for: chrome@stable
2024-12-04T10:43:34.064Z INFO webdriver: Downloading Chromedriver v131.0.6778.87
2024-12-04T10:43:34.093Z INFO webdriver: Setting up chrome v131.0.6778.87
2024-12-04T10:43:34.733Z INFO webdriver: Download of Chromedriver v131.0.6778.87 was successful
2024-12-04T10:43:38.865Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2024-12-04T10:43:38.866Z INFO @wdio/local-runner: Start worker 0-0 with arg: 
2024-12-04T10:43:38.872Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
[0-0] 2024-12-04T10:43:39.851Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2024-12-04T10:43:40.115Z DEBUG @wdio/runner: init remote session
[0-0] 2024-12-04T10:43:40.120Z DEBUG @wdio/utils:initializeServices: initialize service "devtools" as NPM package
[0-0] RUNNING in chrome - file:///out/main/specs/dashboard/custom-domain/create-sites-domain-test.js
[0-0] 2024-12-04T10:43:41.507Z DEBUG @wdio/runner: init remote session
[0-0] 2024-12-04T10:43:41.509Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-12-04T10:43:41.824Z INFO webdriver: Setting up chrome v131.0.6778.87
[0-0] 2024-12-04T10:43:41.826Z INFO webdriver: Using Chromedriver v131.0.6778.87 from cache directory /tmp
[0-0] 2024-12-04T10:43:51.854Z INFO @wdio/utils: Started Chromedriver v131.0.6778.87 with params --port=44223 --allowed-origins=* --allowed-ips=0.0.0.0 in 10121ms on port 44223
[0-0] 2024-12-04T10:43:51.856Z INFO webdriver: [POST] http://localhost:44223/session
[0-0] 2024-12-04T10:43:51.856Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       'goog:chromeOptions': [Object],
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       webSocketUrl: true,
[0-0]       unhandledPromptBehavior: 'ignore'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }
[0-0] 2024-12-04T10:43:51.872Z INFO webdriver: Retrying 1/3
[0-0] 2024-12-04T10:43:51.872Z INFO webdriver: [POST] http://localhost:44223/session
[0-0] 2024-12-04T10:43:51.872Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       'goog:chromeOptions': [Object],
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       webSocketUrl: true,
[0-0]       unhandledPromptBehavior: 'ignore'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }
[0-0] 2024-12-04T10:43:52.376Z INFO webdriver: Retrying 2/3
[0-0] 2024-12-04T10:43:52.376Z INFO webdriver: [POST] http://localhost:44223/session
[0-0] 2024-12-04T10:43:52.376Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       'goog:chromeOptions': [Object],
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       webSocketUrl: true,
[0-0]       unhandledPromptBehavior: 'ignore'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }
[0-0] 2024-12-04T10:43:53.381Z INFO webdriver: Retrying 3/3
[0-0] 2024-12-04T10:43:53.381Z INFO webdriver: [POST] http://localhost:44223/session
[0-0] 2024-12-04T10:43:53.381Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       'goog:chromeOptions': [Object],
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       webSocketUrl: true,
[0-0]       unhandledPromptBehavior: 'ignore'
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }
[0-0] 2024-12-04T10:43:53.446Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
2024-12-04T10:43:53.567Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///out/main/specs/dashboard/custom-domain/create-sites-domain-test.js
2024-12-04T10:43:53.568Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2024-12-04T10:43:53.569Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:20  

2024-12-04T10:43:53.569Z INFO @wdio/local-runner: Shutting down spawned worker
2024-12-04T10:43:53.820Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2024-12-04T10:43:53.821Z INFO @wdio/local-runner: shutting down
Saving lambdaSpecResultJson to file /tmp/wdio/reports/lambdaSpecResultJson.json
Successfully saved the file.

[0-0] 2024-12-04T10:43:41.834Z WARN chromedriver: /tmp/chromedriver/linux-131.0.6778.87/chromedriver-linux64/chromedriver: error while loading shared libraries: libxcb.so.1: cannot open shared object file: No such file or directory
[0-0] 2024-12-04T10:43:51.872Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "http://localhost:44223/session" with method "POST" and args "{
    "capabilities": {
        "alwaysMatch": {
            "goog:chromeOptions": {
                "binary": "/tmp/chrome/linux-131.0.6778.87/chrome-linux64/chrome",
                "args": [
                    "--headless",
                    "--single-process",
                    "--no-sandbox"
                ]
            },
            "browserName": "chrome",
            "acceptInsecureCerts": true,
            "webSocketUrl": true,
            "unhandledPromptBehavior": "ignore"
        },
        "firstMatch": [
            {}
        ]
    }
}"
[0-0] 2024-12-04T10:43:52.375Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "http://localhost:44223/session" with method "POST" and args "{
    "capabilities": {
        "alwaysMatch": {
            "goog:chromeOptions": {
                "binary": "/tmp/chrome/linux-131.0.6778.87/chrome-linux64/chrome",
                "args": [
                    "--headless",
                    "--single-process",
                    "--no-sandbox"
                ]
            },
            "browserName": "chrome",
            "acceptInsecureCerts": true,
            "webSocketUrl": true,
            "unhandledPromptBehavior": "ignore"
        },
        "firstMatch": [
            {}
        ]
    }
}"
[0-0] 2024-12-04T10:43:53.380Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "http://localhost:44223/session" with method "POST" and args "{
    "capabilities": {
        "alwaysMatch": {
            "goog:chromeOptions": {
                "binary": "/tmp/chrome/linux-131.0.6778.87/chrome-linux64/chrome",
                "args": [
                    "--headless",
                    "--single-process",
                    "--no-sandbox"
                ]
            },
            "browserName": "chrome",
            "acceptInsecureCerts": true,
            "webSocketUrl": true,
            "unhandledPromptBehavior": "ignore"
        },
        "firstMatch": [
            {}
        ]
    }
}"
[0-0] 2024-12-04T10:43:53.383Z ERROR webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "http://localhost:44223/session" with method "POST" and args "{
    "capabilities": {
        "alwaysMatch": {
            "goog:chromeOptions": {
                "binary": "/tmp/chrome/linux-131.0.6778.87/chrome-linux64/chrome",
                "args": [
                    "--headless",
                    "--single-process",
                    "--no-sandbox"
                ]
            },
            "browserName": "chrome",
            "acceptInsecureCerts": true,
            "webSocketUrl": true,
            "unhandledPromptBehavior": "ignore"
        },
        "firstMatch": [
            {}
        ]
    }
}"
[0-0] 2024-12-04T10:43:53.383Z ERROR webdriver: Error: WebDriverError: Request failed with error code ECONNREFUSED when running "http://localhost:44223/session" with method "POST" and args "{
    "capabilities": {
        "alwaysMatch": {
            "goog:chromeOptions": {
                "binary": "/tmp/chrome/linux-131.0.6778.87/chrome-linux64/chrome",
                "args": [
                    "--headless",
                    "--single-process",
                    "--no-sandbox"
                ]
            },
            "browserName": "chrome",
            "acceptInsecureCerts": true,
            "webSocketUrl": true,
            "unhandledPromptBehavior": "ignore"
        },
        "firstMatch": [
            {}
        ]
    }
}"

  | 2024-12-04T10:43:53.840Z | [0-0] at FetchRequest._libRequest (file:///tmp/wdio/node_modules/webdriver/build/node.js:1607:13)
-- | -- | --
  | 2024-12-04T10:43:53.840Z | [0-0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  | 2024-12-04T10:43:53.840Z | [0-0] at async FetchRequest._request (file:///tmp/wdio/node_modules/webdriver/build/node.js:1617:20)
  | 2024-12-04T10:43:53.840Z | [0-0] at async startWebDriverSession (file:///tmp/wdio/node_modules/webdriver/build/node.js:1022:16)
  | 2024-12-04T10:43:53.840Z | [0-0] at async _WebDriver.newSession (file:///tmp/wdio/node_modules/webdriver/build/node.js:1238:41)
  | 2024-12-04T10:43:53.840Z | [0-0] at async remote (/tmp/wdio/node_modules/@wdio/runner/node_modules/webdriverio/build/index.js:7810:20)
  | 2024-12-04T10:43:53.840Z | [0-0] at async Runner._startSession (file:///tmp/wdio/node_modules/@wdio/runner/build/index.js:791:23)
  | 2024-12-04T10:43:53.840Z | [0-0] at async Runner._initSession (file:///tmp/wdio/node_modules/@wdio/runner/build/index.js:765:22)
  | 2024-12-04T10:43:53.840Z | [0-0] at async Runner.run (file:///tmp/wdio/node_modules/@wdio/runner/build/index.js:672:16)
  | 2024-12-04T10:43:53.840Z | [0-0] 2024-12-04T10:43:53.442Z ERROR @wdio/runner: Error: Failed to create session.
  | 2024-12-04T10:43:53.840Z | [0-0] Unable to connect to "http://localhost:44223/", make sure browser driver is running on that address.
  | 2024-12-04T10:43:53.840Z | [0-0] It seems like the service failed to start or is rejecting any connections.
  | 2024-12-04T10:43:53.840Z | [0-0] at startWebDriverSession (file:///tmp/wdio/node_modules/webdriver/build/node.js:1026:11)
  | 2024-12-04T10:43:53.840Z | [0-0] at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  | 2024-12-04T10:43:53.840Z | [0-0] at async _WebDriver.newSession (file:///tmp/wdio/node_modules/webdriver/build/node.js:1238:41)
  | 2024-12-04T10:43:53.840Z | [0-0] at async remote (/tmp/wdio/node_modules/@wdio/runner/node_modules/webdriverio/build/index.js:7810:20)
  | 2024-12-04T10:43:53.840Z | [0-0] at async Runner._startSession (file:///tmp/wdio/node_modules/@wdio/runner/build/index.js:791:23)
  | 2024-12-04T10:43:53.840Z | [0-0] at async Runner._initSession (file:///tmp/wdio/node_modules/@wdio/runner/build/index.js:765:22)
  | 2024-12-04T10:43:53.840Z | [0-0] at async Runner.run (file:///tmp/wdio/node_modules/@wdio/runner/build/index.js:672:16)

**Comment by christian-bromann** [comment]
Can you share the logs from Chromedriver?

**Comment by ZehavitSaban** [comment]
I only see this error:
[0-0] 2024-12-04T15:41:39.505Z WARN chromedriver: /tmp/chromedriver/linux-131.0.6778.87/chromedriver-linux64/chromedriver: error while loading shared libraries: libxcb.so.1: cannot open shared object file: No such file or directory

Can I add something to wdio.conf.js to see all Chrome driver logs?

**Comment by christian-bromann** [comment]
A quick google has gotten me to https://stackoverflow.com/questions/72554450/aws-ec2-linux-cannot-open-shared-object-file which suggests that you should try to run:

```sh
sudo yum install -y libX11
```

I will go ahead and close this as it seems to be an environment issue and not related to WebdriverIO core code. Happy to answer further questions.
