### ISSUE TITLE
[🐛 Bug]: <title> webdriver can not setvalue in time.

### ISSUE THREAD

**Issue by tlqiao** [webdriverio/webdriverio#13984]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.4.1

### Node.js Version

v23.3.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [
        {
            platformName: "Android",
            "wdio:maxInstances": 1,
            // "appium:deviceName": "127.0.0.1:6555",
            // "appium:platformVersion": "11.0",
            "appium:deviceName": "35816d9c",
            "appium:platformVersion": "12.0",
            "appium:orientation": "PORTRAIT",
            "appium:automationName": "uiautomator2",
            "appium:appWaitActivity": "com.xxx.mark.MainActivity",
            // "appium:noReset": true,
            "appium:commandTimeouts": {
                "findElement": 60,
                "click": 60,
            },
            "appium:newCommandTimeout": 300
        },
    ],
```

### What happened?

I test a mobile app with webdriverio, when try to input a email code, sometimes it can not find the element , sometimes, it find the element successfully, but inputting the value is too slow. then encounter timeout error.

Here is my app login screeen.
As you can see, the page is very simple. but why setValue is very slow?
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/b618ba81-2fc7-42c9-a663-d6317e9910cc" />

Here is my selector, I have try xpath strategy or uiselector strategy,it encounter same error.
emailCodeInput: '//android.widget.EditText[@resource-id="com.matrixport.mark:id/et_mark_edit"]'
emailCodeInput: 'andorid=new UiSelector().resourceId("com.matrixport.mark:id/et_mark_edit")',

Here is appium log,as you can see, it has find the element, but it take very long time to setValue, then encounter timeout error.
```
[0-0] 2024-12-16T10:12:12.785Z INFO webdriver: COMMAND findElement("xpath", "//android.widget.EditText[@resource-id="com.matrixport.mark:id/et_mark_edit"]")
[0-0] 2024-12-16T10:12:12.787Z INFO webdriver: [POST] http://127.0.0.1:51457/session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element
[0-0] 2024-12-16T10:12:12.787Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: '//android.widget.EditText[@resource-id="com.matrixport.mark:id/et_mark_edit"]'
[0-0] }
2024-12-16T10:12:12.789Z DEBUG @wdio/appium-service: [afc8dfb9][HTTP] --> POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element {"using":"xpath","value":"//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]"}

2024-12-16T10:12:12.790Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]","afc8dfb9-f66a-4909-b33b-a9cc4624a38b"]

2024-12-16T10:12:12.790Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator

2024-12-16T10:12:12.790Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Waiting up to 0 ms for condition

2024-12-16T10:12:12.791Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Matched '/element' to command name 'findElement'

2024-12-16T10:12:12.791Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/382809dd-9e3a-44e3-b12e-a036745185fb/element] with body: {"strategy":"xpath","selector":"//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]","context":"","multiple":false}

2024-12-16T10:12:22.958Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Got response with status 200: {"sessionId":"382809dd-9e3a-44e3-b12e-a036745185fb","value":{"ELEMENT":"00000000-0000-0ed1-ffff-ffff00000f2d","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0ed1-ffff-ffff00000f2d"}}

2024-12-16T10:12:22.959Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0ed1-ffff-ffff00000f2d","ELEMENT":"00000000-0000-0ed1-ffff-ffff00000f2d"}

2024-12-16T10:12:22.961Z DEBUG @wdio/appium-service: [afc8dfb9][HTTP] <-- POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element 200 10171 ms - 137 

[0-0] 2024-12-16T10:12:22.962Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '00000000-0000-0ed1-ffff-ffff00000f2d',
[0-0]   ELEMENT: '00000000-0000-0ed1-ffff-ffff00000f2d'
[0-0] }
[0-0] 2024-12-16T10:12:22.962Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
[0-0] 2024-12-16T10:12:22.965Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
[0-0] 2024-12-16T10:12:22.965Z INFO webdriver: COMMAND elementSendKeys("00000000-0000-0ed1-ffff-ffff00000f2d", "111111")
[0-0] 2024-12-16T10:12:22.966Z INFO webdriver: [POST] http://127.0.0.1:51457/session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element/00000000-0000-0ed1-ffff-ffff00000f2d/value
[0-0] 2024-12-16T10:**12:22.966Z I**NFO webdriver: DATA { text: '111111' }
2024-12-16T10:12:22.969Z DEBUG @wdio/appium-service: [afc8dfb9][HTTP] --> POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element/00000000-0000-0ed1-ffff-ffff00000f2d/value {"text":"111111"}

2024-12-16T10:12:22.969Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Calling AppiumDriver.setValue() with args: ["111111","00000000-0000-0ed1-ffff-ffff00000f2d","afc8dfb9-f66a-4909-b33b-a9cc4624a38b"]

2024-12-16T10:12:22.975Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Matched '/element/00000000-0000-0ed1-ffff-ffff00000f2d/value' to command name 'setValue'

2024-12-16T10:12:22.975Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Added 'value' property ["1","1","1","1","1","1"] to 'setValue' request body

2024-12-16T10:**12:22.976**Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Proxying [POST /element/00000000-0000-0ed1-ffff-ffff00000f2d/value] to [POST http://127.0.0.1:8200/session/382809dd-9e3a-44e3-b12e-a036745185fb/element/00000000-0000-0ed1-ffff-ffff00000f2d/value] with body: {"elementId":"00000000-0000-0ed1-ffff-ffff00000f2d","text":"111111","replace":false,"value":["1","1","1","1","1","1"]}

[0-0] 2024-12-16T10:12:47.970Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
[0-0] 2024-12-16T10:12:47.971Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
[0-0] 2024-12-16T10:12:47.971Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
[0-0] 2024-12-16T10:12:47.971Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
2024-12-16T10:12:47.971Z DEBUG @wdio/appium-service: [HTTP] <-- POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element/00000000-0000-0ed1-ffff-ffff00000f2d/value - - ms - - 

[0-0] 2024-12-16T10:12:47.971Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
[0-0] Error in "should create limited order successfully.should create BTC/USDT limited buy order successfully"
Error: WebDriverError: **The operation was aborted due to timeout when running "element/00000000-0000-0ed1-ffff-ffff00000f2d/value" with method "POST" and args "{"text":"111111"}"**
[0-0] 2024-12-16T10:12:48.023Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
[0-0] 2024-12-16T10:12:48.023Z INFO webdriver: COMMAND deleteSession()
[0-0] 2024-12-16T10:12:48.023Z INFO webdriver: [DELETE] http://127.0.0.1:51457/session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b
2024-12-16T10:12:48.024Z DEBUG @wdio/appium-service: [afc8dfb9][HTTP] --> DELETE /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b {}

2024-12-16T10:12:48.024Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Calling AppiumDriver.deleteSession() with args: ["afc8dfb9-f66a-4909-b33b-a9cc4624a38b"]

2024-12-16T10:12:48.024Z DEBUG @wdio/appium-service: [afc8dfb9][AppiumDriver@59d2] Event 'quitSessionRequested' logged at 1734343968024 (18:12:48 GMT+0800 (China Standard Time))

2024-12-16T10:12:48.024Z DEBUG @wdio/appium-service: [afc8dfb9][AppiumDriver@59d2] Removing session afc8dfb9-f66a-4909-b33b-a9cc4624a38b from our master session list

2024-12-16T10:12:48.024Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Deleting UiAutomator2 session
```
Here is my app source xml, as you can see, it is very simple page.There is a countdown in the page, I guess if the countdown text is updating from 60,59,58,57....0, Does it affect webdriver to setValue for another element?
The first element is my target element，the second element which show countdown element.

 <android.widget.EditText index="0" package="com.matrixport.mark" class="android.widget.EditText" text="Email Code" resource-id="com.matrixport.mark:id/et_mark_edit" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" long-clickable="true" password="false" scrollable="false" selected="true" bounds="[114,610][886,735]" displayed="true" hint="Email Code" />
                    <android.widget.TextView index="2" package="com.matrixport.mark" class="android.widget.TextView" text="0s" resource-id="com.matrixport.mark:id/tv_mark_edit_right" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="true" bounds="[886,610][966,735]" displayed="true" />

### What is your expected behavior?

Hope it can find the element and setvalue in time.

### How to reproduce the bug.

I attached my app page main source xml, if can put it in demo app. it should can be reproduce the issue.
    <android.widget.LinearLayout index="0" package="com.xxxx.mark" class="android.widget.LinearLayout" text="" resource-id="com.xxxx.mark:id/ll_mark_edit" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="true" bounds="[73,610][1007,735]" displayed="true">
                    <android.widget.EditText index="0" package="com.xxxx.mark" class="android.widget.EditText" text="Email Code" resource-id="com.xxxx.mark:id/et_mark_edit" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="true" long-clickable="true" password="false" scrollable="false" selected="true" bounds="[114,610][886,735]" displayed="true" hint="Email Code" />
                    <android.widget.TextView index="2" package="com.xxxx.mark" class="android.widget.TextView" text="0s" resource-id="com.xxxx.mark:id/tv_mark_edit_right" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="true" bounds="[886,610][966,735]" displayed="true" />

### Relevant log output

```typescript
2024-12-16 10:12:11:114 [afc8dfb9][HTTP] --> POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element {"using":"xpath","value":"//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]"}
2024-12-16 10:12:11:115 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]","afc8dfb9-f66a-4909-b33b-a9cc4624a38b"]
2024-12-16 10:12:11:115 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
2024-12-16 10:12:11:115 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Waiting up to 0 ms for condition
2024-12-16 10:12:11:116 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Matched '/element' to command name 'findElement'
2024-12-16 10:12:11:116 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/382809dd-9e3a-44e3-b12e-a036745185fb/element] with body: {"strategy":"xpath","selector":"//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]","context":"","multiple":false}
2024-12-16 10:12:12:436 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Got response with status 404: {"sessionId":"382809dd-9e3a-44e3-b12e-a036745185fb","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.utils.ElementLocationHelpers.findElement(ElementLocationHelpers.java:156)\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:60)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:259)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:253)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:77)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.Abstr...
2024-12-16 10:12:12:437 [afc8dfb9][W3C] Matched W3C error code 'no such element' to NoSuchElementError
2024-12-16 10:12:12:438 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Users/matrix/project/app_ui_test/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/matrix/project/app_ui_test/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)
    at AndroidUiautomator2Driver.findElement (/Users/matrix/project/app_ui_test/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)
2024-12-16 10:12:12:439 [afc8dfb9][HTTP] <-- POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element 404 1325 ms - 902 
2024-12-16 10:12:12:446 [afc8dfb9][HTTP] --> POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/elements {"using":"xpath","value":"//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]"}
2024-12-16 10:12:12:447 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Calling AppiumDriver.findElements() with args: ["xpath","//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]","afc8dfb9-f66a-4909-b33b-a9cc4624a38b"]
2024-12-16 10:12:12:447 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
2024-12-16 10:12:12:447 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Waiting up to 0 ms for condition
2024-12-16 10:12:12:448 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Matched '/elements' to command name 'findElements'
2024-12-16 10:12:12:448 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Proxying [POST /elements] to [POST http://127.0.0.1:8200/session/382809dd-9e3a-44e3-b12e-a036745185fb/elements] with body: {"strategy":"xpath","selector":"//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]","context":"","multiple":true}
2024-12-16 10:12:12:778 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Got response with status 200: {"sessionId":"382809dd-9e3a-44e3-b12e-a036745185fb","value":[{"ELEMENT":"00000000-0000-0ed1-ffff-ffff00000f2d","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0ed1-ffff-ffff00000f2d"}]}
2024-12-16 10:12:12:779 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Responding to client with driver.findElements() result: [{"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0ed1-ffff-ffff00000f2d","ELEMENT":"00000000-0000-0ed1-ffff-ffff00000f2d"}]
2024-12-16 10:12:12:780 [afc8dfb9][HTTP] <-- POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/elements 200 333 ms - 139 
2024-12-16 10:12:12:789 [afc8dfb9][HTTP] --> POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element {"using":"xpath","value":"//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]"}
2024-12-16 10:12:12:790 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]","afc8dfb9-f66a-4909-b33b-a9cc4624a38b"]
2024-12-16 10:12:12:790 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
2024-12-16 10:12:12:790 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Waiting up to 0 ms for condition
2024-12-16 10:12:12:791 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Matched '/element' to command name 'findElement'
2024-12-16 10:12:12:791 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/382809dd-9e3a-44e3-b12e-a036745185fb/element] with body: {"strategy":"xpath","selector":"//android.widget.EditText[@resource-id=\"com.matrixport.mark:id/et_mark_edit\"]","context":"","multiple":false}
2024-12-16 10:12:22:958 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Got response with status 200: {"sessionId":"382809dd-9e3a-44e3-b12e-a036745185fb","value":{"ELEMENT":"00000000-0000-0ed1-ffff-ffff00000f2d","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0ed1-ffff-ffff00000f2d"}}
2024-12-16 10:12:22:959 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0ed1-ffff-ffff00000f2d","ELEMENT":"00000000-0000-0ed1-ffff-ffff00000f2d"}
2024-12-16 10:12:22:961 [afc8dfb9][HTTP] <-- POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element 200 10171 ms - 137 
2024-12-16 10:12:22:969 [afc8dfb9][HTTP] --> POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element/00000000-0000-0ed1-ffff-ffff00000f2d/value {"text":"111111"}
2024-12-16 10:12:22:969 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Calling AppiumDriver.setValue() with args: ["111111","00000000-0000-0ed1-ffff-ffff00000f2d","afc8dfb9-f66a-4909-b33b-a9cc4624a38b"]
2024-12-16 10:12:22:975 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Matched '/element/00000000-0000-0ed1-ffff-ffff00000f2d/value' to command name 'setValue'
2024-12-16 10:12:22:975 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Added 'value' property ["1","1","1","1","1","1"] to 'setValue' request body
2024-12-16 10:12:22:976 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Proxying [POST /element/00000000-0000-0ed1-ffff-ffff00000f2d/value] to [POST http://127.0.0.1:8200/session/382809dd-9e3a-44e3-b12e-a036745185fb/element/00000000-0000-0ed1-ffff-ffff00000f2d/value] with body: {"elementId":"00000000-0000-0ed1-ffff-ffff00000f2d","text":"111111","replace":false,"value":["1","1","1","1","1","1"]}
2024-12-16 10:12:47:971 [HTTP] <-- POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element/00000000-0000-0ed1-ffff-ffff00000f2d/value - - ms - - 
2024-12-16 10:12:48:024 [afc8dfb9][HTTP] --> DELETE /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b {}
2024-12-16 10:12:48:024 [afc8dfb9][38;5;-193m[AndroidUiautomator2Driver@0d06] Calling AppiumDriver.deleteSession() with args: ["afc8dfb9-f66a-4909-b33b-a9cc4624a38b"]
2024-12-16 10:12:48:024 [afc8dfb9][AppiumDriver@59d2] Event 'quitSessionRequested' logged at 1734343968024 (18:12:48 GMT+0800 (China Standard Time))
2024-12-16 10:12:48:024 [afc8dfb9][AppiumDriver@59d2] Removing session afc8dfb9-f66a-4909-b33b-a9cc4624a38b from our master session list
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> it has find the element, but it take very long time to setValue

According to the provided logs:

```
2024-12-16T10:12:22.959Z DEBUG @wdio/appium-service: [afc8dfb9][AndroidUiautomator2Driver@0d06] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0ed1-ffff-ffff00000f2d","ELEMENT":"00000000-0000-0ed1-ffff-ffff00000f2d"}

2024-12-16T10:12:22.961Z DEBUG @wdio/appium-service: [afc8dfb9][HTTP] <-- POST /session/afc8dfb9-f66a-4909-b33b-a9cc4624a38b/element 200 10171 ms - 137 

[0-0] 2024-12-16T10:12:22.962Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '00000000-0000-0ed1-ffff-ffff00000f2d',
[0-0]   ELEMENT: '00000000-0000-0ed1-ffff-ffff00000f2d'
[0-0] }
```

This looks like Appium spent 2 hrs to resolve the element. This is certainly nothing we can fix in WebdriverIO. I would recommend reaching out to the Appium community to inspect further. Happy to answer further questions.
