### ISSUE TITLE
[🐛 Bug]: browser.actions() with origin 'pointer' doesn't click on desired element after element.moveTo()

### ISSUE THREAD

**Issue by AlenaStan** [webdriverio/webdriverio#13998]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.4.1

### Node.js Version

v22.12.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome',
        browserVersion: 'stable',
        "wdio:enforceWebDriverClassic": true,
        },
        acceptInsecureCerts: true,
        'goog:loggingPrefs': {"performance": "ALL"},
        'goog:chromeOptions': {
          args: [
            '--disable-infobars=true',
            '--remote-allow-origins=*',
            'disable-gpu',
            'disable-dev-shm-usage',
            'ignore-certificate-errors',
            'test-type=browser',
            'disable-notifications',
            'disable-application-cache',
            '-disable-extensions',
            '--disable-dev-shm-usage'
          ],
          excludeSwitches: ['enable-automation'],
          prefs: {
            
            }
          }
```

### What happened?

After the browser.positionClick() method was deprecated, I tried to use browser.actions() to get similar behavior in a scenario with hovering over an element using element.moveTo() and then clicking. 
But I discovered that browser.actions() with origin "pointer" does not click on the desired element. I tried to add move() action and specify offset 0.0 , but unfortunately it did not help. A click on the desired element occurs only if you pass the coordinates of the element in move() action. In addition, origin 'pointer' works the same as origin 'viewport', meaning that if I pass the same coordinates, click is performed on the same place, no matter which type of origin I've specified.
What I've tried:

   ```
  await element.moveTo();
  await browser.actions([
       browser.action('pointer')
           .down()
           .up()
  ]);
await element.moveTo();
 await browser.actions([
     browser.action('pointer')
         .move({ origin: 'pointer', x: 0, y: 0 })
         .down()
         .up()
 ]);

```

### What is your expected behavior?

Expected behavior:
     await element.moveTo();
     await browser.actions([
       browser.action('pointer')
           .down()
           .up()
  ]);
    should perform click on the pointer current position, taking into account the position to which the cursor was moved during element.moveTo()

### How to reproduce the bug.

https://github.com/AlenaStan/wdioActions

### Relevant log output

```typescript
[0-0] RUNNING in chrome - file:///D:/wdioActions/wdioActions/wdio/features/checkbox.feature
[0-0] 2024-12-20T10:13:14.781Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       browserVersion: 'stable',
[0-0]       'wdio:enforceWebDriverClassic': true,
[0-0]       'cjson:metadata': [Object],
[0-0]       acceptInsecureCerts: true,
[0-0]       'goog:loggingPrefs': [Object],
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   }
[0-0] }

DevTools listening on ws://127.0.0.1:64402/devtools/browser/53917445-b3b4-443a-9305-b3d8724ebe51
[0-0] 2024-12-20T10:13:15.471Z INFO webdriver: COMMAND navigateTo("https://the-internet.herokuapp.com/checkboxes")
[0-0] 2024-12-20T10:13:15.471Z INFO webdriver: [POST] http://localhost:64392/session/8953ffc467db36bce1db3fbb33648835/url
[0-0] 2024-12-20T10:13:15.471Z INFO webdriver: DATA { url: 'https://the-internet.herokuapp.com/checkboxes' }
[0-0] 2024-12-20T10:13:17.047Z INFO webdriver: RESULT null
[0-0] 2024-12-20T10:13:17.050Z INFO webdriver: COMMAND findElement("css selector", "#checkboxes input:first-of-type")
[0-0] 2024-12-20T10:13:17.050Z INFO webdriver: [POST] http://localhost:64392/session/8953ffc467db36bce1db3fbb33648835/element
[0-0] 2024-12-20T10:13:17.050Z INFO webdriver: DATA { using: 'css selector', value: '#checkboxes input:first-of-type' }
[0-0] 2024-12-20T10:13:17.067Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'f.0D15566DBC0E3CBB58008FB4292AEA4B.d.0FA988F9994AA705369AFCD5A27825C2.e.3'
[0-0] }
[0-0] 2024-12-20T10:13:17.073Z INFO webdriver: COMMAND performActions(<object>)
[0-0] 2024-12-20T10:13:17.073Z INFO webdriver: [POST] http://localhost:64392/session/8953ffc467db36bce1db3fbb33648835/actions
[0-0] 2024-12-20T10:13:17.073Z INFO webdriver: DATA {
[0-0]   actions: [
[0-0]     {
[0-0]       id: 'action1',
[0-0]       type: 'pointer',
[0-0]       parameters: [Object],
[0-0]       actions: [Array]
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2024-12-20T10:13:17.207Z INFO webdriver: RESULT null
[0-0] 2024-12-20T10:13:17.207Z INFO webdriver: COMMAND releaseActions()
[0-0] 2024-12-20T10:13:17.207Z INFO webdriver: [DELETE] http://localhost:64392/session/8953ffc467db36bce1db3fbb33648835/actions
[0-0] 2024-12-20T10:13:17.210Z INFO webdriver: RESULT null
[0-0] 2024-12-20T10:13:17.212Z INFO webdriver: COMMAND performActions(<object>)
[0-0] 2024-12-20T10:13:17.212Z INFO webdriver: [POST] http://localhost:64392/session/8953ffc467db36bce1db3fbb33648835/actions
[0-0] 2024-12-20T10:13:17.212Z INFO webdriver: DATA {
[0-0]   actions: [
[0-0]     {
[0-0]       id: 'action2',
[0-0]       type: 'pointer',
[0-0]       parameters: [Object],
[0-0]       actions: [Array]
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2024-12-20T10:13:17.226Z INFO webdriver: RESULT null
[0-0] 2024-12-20T10:13:17.226Z INFO webdriver: COMMAND releaseActions()
[0-0] 2024-12-20T10:13:17.226Z INFO webdriver: [DELETE] http://localhost:64392/session/8953ffc467db36bce1db3fbb33648835/actions
[0-0] 2024-12-20T10:13:17.229Z INFO webdriver: RESULT null
[0-0] 2024-12-20T10:13:17.231Z INFO webdriver: COMMAND findElement("css selector", "#checkboxes input:first-of-type")
[0-0] 2024-12-20T10:13:17.231Z INFO webdriver: [POST] http://localhost:64392/session/8953ffc467db36bce1db3fbb33648835/element
[0-0] 2024-12-20T10:13:17.231Z INFO webdriver: DATA { using: 'css selector', value: '#checkboxes input:first-of-type' }
[0-0] 2024-12-20T10:13:17.238Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'f.0D15566DBC0E3CBB58008FB4292AEA4B.d.0FA988F9994AA705369AFCD5A27825C2.e.3'
[0-0] }
[0-0] 2024-12-20T10:13:17.241Z INFO webdriver: COMMAND isElementSelected("f.0D15566DBC0E3CBB58008FB4292AEA4B.d.0FA988F9994AA705369AFCD5A27825C2.e.3")
[0-0] 2024-12-20T10:13:17.241Z INFO webdriver: [GET] http://localhost:64392/session/8953ffc467db36bce1db3fbb33648835/element/f.0D15566DBC0E3CBB58008FB4292AEA4B.d.0FA988F9994AA705369AFCD5A27825C2.e.3/selected
[0-0] 2024-12-20T10:13:17.250Z INFO webdriver: RESULT false
[0-0] Error in "0: Then I should see a checkbox checked"
AssertionError
    + expected - actual

    -false
    +true

    at World.<anonymous> (file:///D:/wdioActions/wdioActions/wdio/features/step-definitions/steps.js:33:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async wrapPromiseWithTimeout (D:\wdioActions\wdioActions\wdio\node_modules\@cucumber\cucumber\src\time.ts:55:10)
    at async Object.run (D:\wdioActions\wdioActions\wdio\node_modules\@cucumber\cucumber\src\user_code_runner.ts:86:16)
    at async Object.run (D:\wdioActions\wdioActions\wdio\node_modules\@cucumber\cucumber\src\runtime\step_runner.ts:51:20)
    at async TestCaseRunner.invokeStep (D:\wdioActions\wdioActions\wdio\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:144:12)
    at async TestCaseRunner.runStep (D:\wdioActions\wdioActions\wdio\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:344:20)
    at async <anonymous> (D:\wdioActions\wdioActions\wdio\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:250:34)
    at async TestCaseRunner.aroundTestStep (D:\wdioActions\wdioActions\wdio\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:177:28)
    at async TestCaseRunner.runAttempt (D:\wdioActions\wdioActions\wdio\node_modules\@cucumber\cucumber\src\runtime\test_case_runner.ts:228:7)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@AlenaStan it seems you are missing to call `perform()` in your example which is important to trigger the action. However in the log I do see it being called. I have this example which works for me:

```ts
await browser.url('https://webdriver.io')
const btn = await browser.$('=Get Started')
await browser.action('pointer')
    .move({ origin: btn })
    .down()
    .pause(100)
    .up()
    .perform()

await browser.pause(1000) // give some time to transition to the new page
console.log(await browser.getTitle()) // returns "Getting Started | WebdriverIO"
```

I think what you are missing is to tell WebdriverIO where to move to. If you say `move({ origin: 'pointer', x: 0, y: 0 })` it moves the mouse to `0,0` because the value of origin is suppose to be an element reference (see my example above). Let me know if you have any further questions.

**Comment by AlenaStan** [comment]
Hi @christian-bromann 

Thanks for the tip.
If I understood correctly, I won't be able to use astions as a replacement for browser.positionClick(). 
Initially, I assumed that 

await $(element-locator).moveTo();
await browser.positionClick()

can be replaced with 

await $(element-locator).moveTo();
await browser.actions([
            browser.action('pointer')
                .down()
                .up()
        ]);
 But as I see from your comment, to click in the right place, I need to specify an element, 
 and if I don't specify it, then probably a click on 0, 0 will occur. I tried to use actions with move and without move action inside the chain, but both options didn't work for me
