### ISSUE TITLE
'wdio-selenium-service' is not in the npm registry

### ISSUE THREAD

**Issue by jamesalbert** [webdriverio/webdriverio#1400]
## The problem

I tried using wdio config package to setup the environment, but it failed when trying to install the standalone selenium service.

## Environment

* WebdriverIO version: 4.0.9
* Node.js version: 6.2.2

## Details

```
./node_modules/webdriverio/bin/wdio 

=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? I have my own Selenium cloud
? What is the IP or URI to your Selenium standalone server? 52.90.169.182
? What is the port which your Selenium standalone server is running on? 4444
? What is the path to your Selenium standalone server? /wd/hub
? Which framework do you want to use? mocha
? Shall I install the framework adapter for you? Yes
? Where are your test specs located? ./test/specs/**/*.js
? Which reporter do you want to use?  junit - https://github.com/webdriverio/wdio-junit-reporter
? Shall I install the reporter library for you? Yes
? Do you want to add a service to your test setup?  selenium-standalone - https://github.com/webdriverio/wdio-selenium-standalone-service
? Shall I install the services for you? Yes
? Level of logging verbosity: error
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://localhost:3000

Installing wdio packages:
pkg: wdio-mocha-framework
pkg: wdio-junit-reporter
pkg: wdio-selenium-service
/Users/jbert/Downloads/demo_tests/node_modules/webdriverio/build/lib/cli.js:270
                    throw err;
                    ^

Error: Command failed: npm i -D wdio-mocha-framework wdio-junit-reporter wdio-selenium-service
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "i" "-D" "wdio-mocha-framework" "wdio-junit-reporter" "wdio-selenium-service"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/wdio-selenium-service
npm ERR! 404 
npm ERR! 404  'wdio-selenium-service' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jbert/Downloads/demo_tests/npm-debug.log

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

**Comment by andriilazebnyi** [comment]
@jamesalbert 
This already known issue https://github.com/webdriverio/webdriverio/issues/1378

**Comment by christian-bromann** [comment]
Yes, that one is fixed and will be released with the next version

**Comment by jamesalbert** [comment]
Sorry for the repost. I searched for the error in the issues and nothing came up. My bad

**Comment by christian-bromann** [comment]
No worries 😉
