### ISSUE TITLE
Invalid element state

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1406]
```js
browser.setValue(selector, value); //  Invalid element state: Element is not currently interactable and may not be manipulated
browser.element(selector).setValue(value) // { value : null, ... }
```

### Problems:

1. The fist example does not work at all. Why?
2. The second example works fine, but result value is `null`. Why?

**Comment by christian-bromann** [comment]
> The fist example does not work at all. Why?

Not sure, looks like a Selenium issue. I doubt it has to do with the way you call setValue. Will need to see the Selenium logs to say more

> The second example works fine, but result value is null. Why?

What you see is the response of elementIdValue which has value: null because it doesn't return anything.

**Comment by monolithed** [comment]
> Will need to see the Selenium logs to say more

```
20:22:26.956 INFO - Executing: [get: https://e.mail.ru/compose])
20:22:29.899 INFO - Done: [get: https://e.mail.ru/compose]
20:22:29.950 INFO - Executing: [find elements: By.cssSelector: .b-compose])
20:22:29.993 INFO - Done: [find elements: By.cssSelector: .b-compose]
20:22:30.004 INFO - Executing: [find elements: By.cssSelector: [data-original-name="To"]])
20:22:30.022 INFO - Done: [find elements: By.cssSelector: [data-original-name="To"]]
20:22:30.034 INFO - Executing: [clear: 2 [[ChromeDriver: chrome on MAC (a1ddc1af7b4967d60226b80a9c3993fe)] -> css selector: [data-original-name="To"]]])
20:22:30.034 INFO - Executing: [clear: 1 [[ChromeDriver: chrome on MAC (a1ddc1af7b4967d60226b80a9c3993fe)] -> css selector: [data-original-name="To"]]])
20:22:30.497 WARN - Exception thrown
org.openqa.selenium.InvalidElementStateException: invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=51.0.2704.103)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 18 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'msk-wire-macbook-pro-a.abashkin.mail.msk', ip: '100.96.162.151', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4), userDataDir=/var/folders/rh/jy6ct8tx1g7_zfcszly83qcc0000gr/T/.org.chromium.Chromium.xGgHJz}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=51.0.2704.103, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a1ddc1af7b4967d60226b80a9c3993fe
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.clear(RemoteWebElement.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:335)
	at com.sun.proxy.$Proxy2.clear(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.clear(EventFiringWebDriver.java:364)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
	at com.sun.proxy.$Proxy3.clear(Unknown Source)
	at org.openqa.selenium.remote.server.handler.ClearElement.call(ClearElement.java:30)
	at org.openqa.selenium.remote.server.handler.ClearElement.call(ClearElement.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
20:22:30.500 WARN - Exception: invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=51.0.2704.103)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 18 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'msk-wire-macbook-pro-a.abashkin.mail.msk', ip: '100.96.162.151', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4), userDataDir=/var/folders/rh/jy6ct8tx1g7_zfcszly83qcc0000gr/T/.org.chromium.Chromium.xGgHJz}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=51.0.2704.103, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: a1ddc1af7b4967d60226b80a9c3993fe
20:22:30.532 INFO - Done: [clear: 1 [[ChromeDriver: chrome on MAC (a1ddc1af7b4967d60226b80a9c3993fe)] -> css selector: [data-original-name="To"]]]
20:22:30.589 INFO - Executing: [send keys: 1 [[ChromeDriver: chrome on MAC (a1ddc1af7b4967d60226b80a9c3993fe)] -> css selector: [data-original-name="To"]], [t, e, s, t]])
20:22:30.592 INFO - Executing: [delete session: 282a74c8-769b-4471-a0f6-be0cff99d412])
20:22:30.674 INFO - Done: [send keys: 1 [[ChromeDriver: chrome on MAC (a1ddc1af7b4967d60226b80a9c3993fe)] -> css selector: [data-original-name="To"]], [t, e, s, t]]
20:22:30.812 INFO - Done: [delete session: 282a74c8-769b-4471-a0f6-be0cff99d412]
```

Not so informative log )

> What you see is the response of elementIdValue which has value: null because it doesn't return anything.

I've no experience with Selenium API. Do you you know what does mean `state`?

**Comment by christian-bromann** [comment]
What's odd here is that two lines

```
20:22:30.034 INFO - Executing: [clear: 2 [[ChromeDriver: chrome on MAC (a1ddc1af7b4967d60226b80a9c3993fe)] -> css selector: [data-original-name="To"]]])
20:22:30.034 INFO - Executing: [clear: 1 [[ChromeDriver: chrome on MAC (a1ddc1af7b4967d60226b80a9c3993fe)] -> css selector: [data-original-name="To"]]])
```

It seems that it want to clear the element twice at the same time. This might be a reason for that error. Usually it appears when an input is in readonly mode. Is this the case here?

**Comment by christian-bromann** [comment]
After some research it might be cause by the clear command. So try `addValue` instead of `setValue`

**Comment by monolithed** [comment]
Oh, thanks, there're two elements (div and textarea) with the same data-attributes on the page.

**Comment by ARenfroe** [comment]
@monolithed 
@ChrisOelmueller 
Hey everyone I am experiencing this issue as well. Did anyone find a fix. 
I have the same 2 commands out to clear the element.  I have tried both `setValue` and `addValue` with no success.  Any help is appreciated. 

**Selenium logs**
```11:58:15.556 INFO - Done: [find elements: By.cssSelector: [data-lftest="element-name-removed-for-post"]]
11:58:15.561 INFO - Executing: [clear: 27 [[ChromeDriver: chrome on MAC ()] -> css selector: [data-lftest="element-name-removed-for-post"]]])
11:58:15.561 INFO - Executing: [clear: 28 [[ChromeDriver: chrome on MAC ()] -> css selector: [data-lftest="element-name-removed-for-post"]]])
11:58:15.854 INFO - Done: [clear: 28 [[ChromeDriver: chrome on MAC ()] -> css selector: [data-lftest="element-name-removed-for-post"]]]
11:58:15.859 INFO - Executing: [send keys: 28 [[ChromeDriver: chrome on MAC ()] -> css selector: [data-lftest="element-name-removed-for-post"]], [1]])
11:58:15.903 INFO - Done: [send keys: 28 [[ChromeDriver: chrome on MAC ()] -> css selector: [data-lftest="element-name-removed-for-post"]], [1]]
11:58:20.828 WARN - Exception thrown
org.openqa.selenium.InvalidElementStateException: invalid element state: Element is not currently interactable and may not be manipulated
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.24.417412 (),platform=Mac OS X 10.12.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 19 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.7.0_79'
Session ID: 
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/v6/hf_yj_5s6k3clftwg5ncr7d40000gn/T/.org.chromium.Chromium.RnXORI, chromedriverVersion=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6)}, networkConnectionEnabled=false, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=54.0.2840.98, pageLoadStrategy=normal, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
        at sun.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
        at org.openqa.selenium.remote.RemoteWebElement.clear(RemoteWebElement.java:140)
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:335)
        at com.sun.proxy.$Proxy2.clear(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.clear(EventFiringWebDriver.java:364)
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
        at com.sun.proxy.$Proxy3.clear(Unknown Source)
        at org.openqa.selenium.remote.server.handler.ClearElement.call(ClearElement.java:30)
        at org.openqa.selenium.remote.server.handler.ClearElement.call(ClearElement.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Webdriver.io reporter error**
```chrome #0a] 1) An admin should be able to do some test:
[chrome #0a] invalid element state: Element is not currently interactable and may not be manipulated
[chrome #0a] Error: invalid element state: Element is not currently interactable and may not be manipulated
[chrome #0a]     at Context.<anonymous> (app/tests/admin/test.spec.js:79:17)
[chrome #0a]     at elementIdValue("28", "1") - setValue.js:46:80
[chrome #0a]
```

**Spec File**
```
browser.setValue(settings.order.Element, '1');
```

**Comment by christian-bromann** [comment]
@ARenfroe not sure what element you try to change but it can't be manipulated for some reason (e.g. it is disabled)

**Comment by ARenfroe** [comment]
@ChrisOelmueller 
The test successfully send the desired value to the text box and just hangs waiting for the second call to come back.

**Comment by christian-bromann** [comment]
@ARenfroe 
1. I am not @ChrisOelmueller 😆 
2. This error comes from the browser driver .. not sure what is happening exactly but the input value you want to change in test.spec.js in line 79 can't be changed

**Comment by ARenfroe** [comment]
@christian-bromann nice I just went with the first drop down haha. 

I have tried passing in the xpath, and other tags but haven't had any success.  Here is the element if you have any suggestions. 

```
<input type="text" class="center ng-pristine ng-valid ng-scope ng-not-empty ng-valid-required ng-touched" min="0" data-lf-select-on-click="" data-lftest="input-order-rx-quantity-new-right" data-ng-blur="orderUtils.zeroAuto('Right', true)" data-ng-change="orderUtils.blockNext = true" data-ng-disabled="order.buyingOptionsPrimary === 'monthly' || (!order.editOrder.editable &amp;&amp; order.editOrder.valid)" data-ng-if="(!valid.plan || prescription.edit) &amp;&amp; tenant.data.services.lensferry.monthlyOrdering &amp;&amp; tenant.data.services.lensferry.individualOrdering" data-ng-model="order.copyOrderRightQtyPrimary" required="">
```

**Comment by burdeasa** [comment]
Not sure if this would help anyone, but I was getting this error when my selector matched multiple input elements; may want to verify that.

**Comment by ARenfroe** [comment]
@burdeasa I was having that issue as well. I grabbed by xpath and that resolved it.

**Comment by anilkoithara** [comment]
I have same issue when I select two dates from the calendar

I am using xpath find element because we are using third party calendar will add my comment if I mange to resolve that .... look's like on first click the calendar element are changing .. element size changed from 2 to 1 after first click.
 
###error:  element not interactable
[chrome #0-0] Error: An element command could not be completed because the element is not visible on the page.

**Comment by TSBgit** [comment]
If there is a situation where the element is located but setValue fails with "ERROR webdriver: Request failed due to Error: element not interactable"
Use doubleClick() istead of click() and addValue:
```
$(vcCell_Input).doubleClick();
$(vcCell_Input).addValue(newValue);
```
