### ISSUE TITLE
commandPromise.then is not a function

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1410]
```js
browser.url('/login');
browser.setCookie(cookie);
browser.url('/messages');
browser.waitForExist(selector);
```

```
commandPromise.then is not a function
running chrome
TypeError: commandPromise.then is not a function
    at Object.url (/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:352:32)
    at Compose.auth (/tests/e.mail.ru/pages/index.js:70:13)
    at Context.it (/tests/e.mail.ru/cases/compose/TESTMAIL-XXXX.js:9:8)
    at Context.executeSync (/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:625:12)
    at /node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:833:34
```

It happens sometimes... Maybe similar problem https://github.com/webdriverio/webdriverio/issues/1408

**Comment by christian-bromann** [comment]
@monolithed can you provide a reproducible example?

**Comment by monolithed** [comment]
Nope, it happens not so often and I don't know the reason.

**Comment by moeadham** [comment]
`commandPromise.then is not a function
running chrome
TypeError: commandPromise.then is not a function
    at Object.getText (---/node_modules/wdio-sync/build/index.js:352:32)
    at Context.it (---/test/selenium/test.js:605:24)
    at Context.executeSync (---/node_modules/wdio-sync/build/index.js:625:12)
    at ---/geocities/node_modules/wdio-sync/build/index.js:833:34
`

**Comment by susu** [comment]
Same error. We notice this error occasionally. The first occurrence was at Jun 29, 2016.

**Comment by christian-bromann** [comment]
I need for information to debug this. Was there an error before? Can you reproduce this?

**Comment by talarari** [comment]
this is happening to me as well.
i have a custom command that looks like this:
```
browser.addCommand('callApi',function async(){ return callApiPromise })
```
im calling it in my before hook in the spec like this:
```
before(function async(){
    return browser.callApi();
})
```
im getting : commandPromise.then is not a function

**Comment by QS-EXT-7NXT** [comment]
It seems like I can reproduce it.

There is no error listed before.

> commandPromise.then is not a function
> running firefox
> TypeError: commandPromise.then is not a function
    at Object.getUrl (/home/zeph/Downloads/Software/webdriverio/7NXT.git/test/PFT/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:352:32)

The line of origin is the last line:
`browser.waitUntil(`
`    function () {`
`        var url = browser.getUrl();`

**Comment by christian-bromann** [comment]
@talarari can bundle a reproducible example for me?

**Comment by talarari** [comment]
Ill try soon
