### ISSUE TITLE
Allure report generation error using mocha.

### ISSUE THREAD

**Issue by ramneek1995** [webdriverio/webdriverio#1432]
## The problem
 Tests run correctly using the default dot error reporter. When I use allure reporter(http://webdriver.io/guide/reporters/allure.html), the json files are created. However when I try to generate an HTML report, I get a NumberFormatException error. The full error is shown:

## Environment

* WebdriverIO version:4.1.1
Synchronous tests.
wdio-allure-reporter

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:453)
    at java.lang.Long.valueOf(Long.java:540)
    at com.sun.xml.internal.bind.DatatypeConverterImpl._parseLong(DatatypeConverterImpl.java:114)
    at ru.yandex.qatools.allure.model.Step_JaxbXducedAccessor_stop.parse(TransducedAccessor_field_Long.java:48)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:194)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:537)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:516)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:125)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:203)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:181)
    at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:235)
    at javax.xml.bind.JAXB.unmarshal(JAXB.java:242)
    at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:59)
    at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:50)
    at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:40)
    at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:48)
    at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:1)
    at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.nextSuite(TestCaseReader.java:46)
    at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.hasNext(TestCaseReader.java:56)
    at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:57)
    at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
    at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
Command aborted due to exception {}.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
    at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
    at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
    at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)

```

**Comment by christian-bromann** [comment]
@ramneek1995 are you running the latest version of your framework?

**Comment by ramneek1995** [comment]
Yes
wdio-allure-reporter 1.2.2;
mocha 2.5.3;

**Comment by ramneek1995** [comment]
Sorry,
wdio-allure-reporter 0.1.1

**Comment by christian-bromann** [comment]
What is the version of your `wdio-mocha-framework` package?

**Comment by ramneek1995** [comment]
wdio-mocha-framework : 0.3.4

**Comment by christian-bromann** [comment]
Please update that package and try again

**Comment by ramneek1995** [comment]
Updated to wdio-mocha-framework : 0.3.5
Still getting the same error.
Allure seems to work when using 3-4 test cases. When I increase them, this error returns.

**Comment by alcaneo** [comment]
Hi,

Got the same issue and I think I put the finger on something that might cause this issue (Anyway it should not crash like this).

I figured out that some tests were run before the previous were done, I could see it by setting the `logLevel: 'verbose'` in the wdio.conf.js.
I saw clearly that some "COMMAND" got executed again before getting the "RESULT", then I would get two "RESULT" in a row and a warning from Allure: _allure-js-commons: Unexpected endStep(). There is no any steps running_

When this warning occurs from Allure, then the stacktrace mentioned above is fired when generating the reports.

What I tried to change in the config is to set `connectionRetryCount: 0`, then it seemed to prevent this issue to raise on my tests, but still sometime it happens.
My understanding is that the test is re-run (for sure it's the same test re-run) but as I use promises the first one is still pending and gets executed eventually which seem to create the mess.

@ramneek1995 do you have kind of the same behaviour on your tests?
I use CucumberJS and not Mocha but I don't think this is related to Mocha as I have the same issue as well and I don't use it.

Any idea on why and how my test gets re-run would help me investigating deeper.
At the moment each time it happens I get an "Undefined" error and an "Undefined" stacktrace which drives me crazy as I don't know how to debug it.

**Comment by ramneek1995** [comment]
As recommended by @alcaneo, I turned `connectionRetryCount : 0`, and` loglevel:verbose`. I made some changes to my code and stopped getting the allure warning : `allure-js-commons: Unexpected endStep(). There is no any steps running`. 
However, still the `allure generate` command is giving the same error.
Normally, the commands occur synchronously in the order of COMMAND, DATA, RESULT. However in the `waitForExist` command, it fires the COMMAND repeatedly without waiting for the result. This results in 2 RESULT coming together(when the element is found). Here are my logs : 
```
[1;30m[12:02:27] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session/b71e8f40-3e67-4a39-a5db-932fc13e63d2/elements"
[1;30m[12:02:27] [0m [0;33mDATA		[0m{"using":"xpath","value":"//h3[contains(., \"bag(s) found\")]"}
[1;30m[12:02:27] [0m [0;36mRESULT		[0m[]
[1;30m[12:02:28] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session/b71e8f40-3e67-4a39-a5db-932fc13e63d2/elements"
[1;30m[12:02:28] [0m [0;33mDATA		[0m{"using":"xpath","value":"//h3[contains(., \"bag(s) found\")]"}
[1;30m[12:02:28] [0m [0;36mRESULT		[0m[]
[1;30m[12:02:28] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session/b71e8f40-3e67-4a39-a5db-932fc13e63d2/elements"
[1;30m[12:02:28] [0m [0;33mDATA		[0m{"using":"xpath","value":"//h3[contains(., \"bag(s) found\")]"}
[1;30m[12:02:28] [0m [0;36mRESULT		[0m[]
․[1;30m[12:02:29] [0m [0;35mCOMMAND	[0mPOST 	 "/wd/hub/session/b71e8f40-3e67-4a39-a5db-932fc13e63d2/elements"
[1;30m[12:02:29] [0m [0;33mDATA		[0m{"using":"xpath","value":"//h3[contains(., \"bag(s) found\")]"}
[1;30m[12:02:29] [0m [0;35mCOMMAND	[0mDELETE 	 "/wd/hub/session/b71e8f40-3e67-4a39-a5db-932fc13e63d2"
[1;30m[12:02:29] [0m [0;33mDATA		[0m{}
[1;30m[12:02:29] [0m [0;36mRESULT		[0m[]
[1;30m[12:02:29] [0m [0;36mRESULT		[0mnull
```
When the element is found, the previous command results in null. This probably causes the error.
One more thing, there are many POST commands which give result null (like opening of a URL in browser). Do you think they also contribute to this NumberFormatException error?

**Comment by ramneek1995** [comment]
Allure report generation works if I remove these `waitForExist` commands and replace them with an approximate pause command. Also if I search for an element that changes on the page (a timer etc), the synchronous chain of COMMAND,RESULT,DATA is broken as wdio searches multiple times asynchronously for the changing element, due to which allure gives the same error.
If I remove these commands from my test cases, allure seems to work.
Thank you @alcaneo, @christian-bromann, for your help!!

**Comment by christian-bromann** [comment]
@ramneek1995 ohh I see what happened: during a waitForExist call a timeout was triggered and forced webdriverio to close the session. While the session got closed, the waitForExist call respond. That is why we have two RESULT at the end. I will open an issue in the allure reporter to fix that.

@ramneek1995 I would recommend to continue using waitForExist. Your tests become flaky if you use pause commands.

**Comment by alcaneo** [comment]
I add a bit more information as I moved forward in my investigation.

First, question, @ramneek1995 do you use CucumberJS as well ?
You mentioned Mocha but I don't think this is related to that library.

I figured out that the cucumberJS tests have a 5s timeout, and the eCommerce website I'm testing is not always that fast (that's bad I know).

Basically I figured out that cucumberJS timeouts before the rest and that created the problem.
Here is how to extend the timeout ( @ramneek1995 that should probably fix your tests with waitFor* if you use cucumberJS):
`this.setDefaultTimeout(30 * 1000);`
More info here: https://github.com/cucumber/cucumber-js#timeouts

Waiting for the newly created issue to be fixed.

Cheers

**Comment by christian-bromann** [comment]
> I figured out that the cucumberJS tests have a 5s timeout, and the eCommerce website I'm testing is not always that fast (that's bad I know).

You should be able to increase that timeout in the config too

**Comment by ramneek1995** [comment]
Thanks @christian-bromann and @alcaneo .
Increasing the timeout doesn't make a change in error status. Even if all the tests are completed well within the timeout period and all waitFor* commands are executed completely, still allure fails to generate reports.
I'll also wait for the issue to be fixed. Till then I could use pause commands.

**Comment by williamsm1** [comment]
@ramneek1995 are you still experiencing this error after the following issues were addressed?
- https://github.com/webdriverio/wdio-allure-reporter/issues/24
- https://github.com/webdriverio/webdriverio/pull/1461

I've been keeping an eye on this issue since it was raised as I'm running into the same error after attempting to implement Allure for our project.  We're using Jasmine instead of Mocha.

## Environment
- `wdio-jasmine-framework` 0.2.5
- `webdriverio` 4.2.3
- `wdio-allure-reporter` 0.1.1

@christian-bromann - Should this issue be re-opened?

After a test run, I have one test that's failing on a waitForExist command with a 10sec timeout.  The testrunner then outputs `allure-js-commons: Unexpected endStep(). There is no any steps running` and then the test result
```
WaitUntilTimeoutError: element (_element_) still not existing after 10000ms
    at Object.<anonymous> (_test-filepath_)
    at new Promise (node_modules/core-js/modules/es6.promise.js:191:7)
    at saveScreenshot("errorShots/ERROR_firefox_2016-07-26T18-18-35.944Z.png") - safeExecute.js:28:24
```

After running `allure generate allure-results && allure report open`, I then get the following
```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.valueOf(Long.java:803)
	at com.sun.xml.internal.bind.DatatypeConverterImpl._parseLong(DatatypeConverterImpl.java:118)
	at ru.yandex.qatools.allure.model.TestCaseResult_JaxbXducedAccessor_stop.parse(TransducedAccessor_field_Long.java:50)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:195)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276)
	at javax.xml.bind.JAXB.unmarshal(JAXB.java:242)
	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:59)
	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:50)
	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:40)
	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:48)
	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:1)
	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.nextSuite(TestCaseReader.java:46)
	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.hasNext(TestCaseReader.java:56)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:61)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
Command aborted due to exception {}.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
	at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
```

Let me know if there is any further information that I can provide.  Thanks

**Comment by just-boris** [comment]
The commit that was intended to fix this issue is still not released. But it will be in the next version.

**Comment by williamsm1** [comment]
@just-boris - thanks for the update.  Where can I watch for next version release?

**Comment by techyguy78** [comment]
@just-boris -- I have the same issue. Any timeline for next allure version ? thank you

**Comment by just-boris** [comment]
Currently releasing this is kinda blocked, because we can't test this properly.
See https://github.com/webdriverio/webdriverio/pull/1461 to details

**Comment by adobe-scripting** [comment]
I am one more person experiencing this issue and am eagerly awaiting a release.

**Comment by itaimalek** [comment]
One more - experiencing the exact same thing....

**Comment by Efefefef** [comment]
Moved writing selenium tests from java to nodejs. 
Please guys fix this problem, it happens that webdriverio + allure is unusable now

**Comment by christian-bromann** [comment]
@Efefefef are you running latest webdriverio/wdio-allure-reporter/(mocha|cucumber|jasmine)-framework? For me this is fixed.

**Comment by acailly** [comment]
Same issue here, with last versions

**Comment by Efefefef** [comment]
@christian-bromann yeah, i'm running 
`"webdriverio": "^4.2.8",
    "wdio-mocha-framework": "^0.4.0",
    "wdio-allure-reporter": "^0.1.1"`
It crashes during `allure generate` with the subject error since i introduced `waitForVisible()` in my very first page object

**Comment by dezdem0na** [comment]
```
    "wdio-allure-reporter": "^0.1.1",
    "wdio-mocha-framework": "^0.4.1",
    "webdriverio": "^4.2.11"
```

And I get the same error... 
`$ allure generate allure-results && allure report open`

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:601)
	at java.lang.Long.valueOf(Long.java:803)
	at com.sun.xml.internal.bind.DatatypeConverterImpl._parseLong(DatatypeConverterImpl.java:118)
	at ru.yandex.qatools.allure.model.Step_JaxbXducedAccessor_stop.parse(TransducedAccessor_field_Long.java:50)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:195)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:221)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:276)
	at javax.xml.bind.JAXB.unmarshal(JAXB.java:242)
	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:59)
	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:50)
	at ru.yandex.qatools.allure.commons.AllureFileUtils.unmarshal(AllureFileUtils.java:40)
	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:48)
	at ru.yandex.qatools.allure.data.io.TestSuiteReader$TestSuiteResultIterator.next(TestSuiteReader.java:1)
	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.nextSuite(TestCaseReader.java:46)
	at ru.yandex.qatools.allure.data.io.TestCaseReader$TestCaseResultIterator.hasNext(TestCaseReader.java:56)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:57)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
	at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
Command aborted due to exception {}.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at ru.yandex.qatools.allure.command.ReportGenerate.runUnsafe(ReportGenerate.java:48)
	at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.java:52)
	at ru.yandex.qatools.allure.CommandLine.main(CommandLine.java:46)
```

**Comment by just-boris** [comment]
Hello, @dezdem0na
Unfortunately, I can't help you by the attached stacktrace, because it is very generic and can be caused by various reasons.

To locate the exact issue, could you find where do you have attribute with empty string value, like `some-attr=""` and provide surrounding part of xml. you can find xml-files in the `allure-results` folder.

**Comment by christian-bromann** [comment]
Let's continue the conversation https://github.com/webdriverio/wdio-allure-reporter/issues/26
