### ISSUE TITLE
Unhandled Iterator Error When using Spec reporter

### ISSUE THREAD

**Issue by dcypherthis** [webdriverio/webdriverio#1454]
## The problem

I keep seeing errors like this crop up while using the spec reporter.  This Issue may better serve there, but it the stack trace includes the baseReporter lib so I thought I would start here.  

```bash
/Users/jcypher/projects/auto-regress-test-suite/node_modules/webdriverio/build/lib/utils/BaseReporter.js:323
                        throw _iteratorError;
                        ^

TypeError: Cannot read property 'split' of undefined
    at /Users/jcypher/projects/auto-regress-test-suite/node_modules/wdio-spec-reporter/build/reporter.js:267:43
    at Array.forEach (native)
    at SpecReporter.getFailureList (/Users/jcypher/projects/auto-regress-test-suite/node_modules/wdio-spec-reporter/build/reporter.js:265:22)
    at SpecReporter.getSuiteResult (/Users/jcypher/projects/auto-regress-test-suite/node_modules/wdio-spec-reporter/build/reporter.js:318:28)
    at SpecReporter.printSuiteResult (/Users/jcypher/projects/auto-regress-test-suite/node_modules/wdio-spec-reporter/build/reporter.js:326:30)
    at SpecReporter.<anonymous> (/Users/jcypher/projects/auto-regress-test-suite/node_modules/wdio-spec-reporter/build/reporter.js:109:18)
    at emitOne (events.js:77:13)
    at SpecReporter.emit (events.js:169:7)
    at BaseReporter.handleEvent (/Users/jcypher/projects/auto-regress-test-suite/node_modules/webdriverio/build/lib/utils/BaseReporter.js:311:35)
    at Launcher.messageHandler (/Users/jcypher/projects/auto-regress-test-suite/node_modules/webdriverio/build/lib/launcher.js:519:28)
```
## Environment

* WebdriverIO version: 4.2.1
* Node.js version: 5.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): 
- wdio-cucumber-framework: 0.2.1
- chomedriver 2.22
- wdio-spec reporter 0.0.2

## Details

I see this happen locally and on Travis CI.  On local browsers and on sauce labs.

this occurs anytime I get a timeout-related error,  from a `waitUntil` or a `waitForVisible` command.

The entire feature will execute past the error, but I receive that message when it is ready to process it for the spec reporter.  It also forces the test runner to fail and no other feature files are run after that feature is complete.  

After further investigation, I isolated an offending test. When Only using the **dot** reporter this is the error I get, and it doesn't kill the test runner like the previously stated behavior:

```bash
element (#back-to-editor-button) still not visible after 30000ms
running Chrome (v51) on Windows 10
Error: element (#back-to-editor-button) still not visible after 30000ms
    at World.<anonymous> (test/support/stepDefinitions/then.steps.js:422:17)
    at new WaitUntilTimeoutError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:121:12)
    at Object.<anonymous> (node_modules/webdriverio/build/lib/commands/waitForVisible.js:105:19)
    at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
    at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:171:29)
    at node_modules/webdriverio/build/lib/webdriverio.js:446:32
    at _rejected (node_modules/q/q.js:830:24)
    at node_modules/q/q.js:856:30
    at Promise.when (node_modules/q/q.js:1108:31)
    at Promise.promise.promiseDispatch (node_modules/q/q.js:774:41)
    at node_modules/q/q.js:590:44
```

There seems to be an issue with how these type of errors are handled by the spec reporter.

## Code To Reproduce Issue [ Good To Have ]

`browser.waitForVisible(elementThatIsNotVisibleInTimeoutPeriod);`

**Comment by timbru31** [comment]
I'm stumbled across this issue, too. Seems like it's possible that there are errors without stacktraces: https://github.com/cucumber/cucumber-js/blob/7d7ba96262031b4fb7ab83216f474817d3892f3f/lib/cucumber/listener/summary_formatter.js#L87

Guess https://github.com/webdriverio/wdio-spec-reporter/blob/master/lib/reporter.js#L212 needs to be guarded like https://github.com/webdriverio/webdriverio/blob/master/lib/utils/BaseReporter.js#L135

**Comment by dcypherthis** [comment]
👍

**Comment by christian-bromann** [comment]
Let's move convo to wdio-spec-reporter project
