### ISSUE TITLE
A timeout in a test causes the synchronous chaining behaviour in the remainder of the suite to break.

### ISSUE THREAD

**Issue by andyboyne** [webdriverio/webdriverio#1466]
## The problem

A timeout that occurs during a test will break other tests within that suite.  

## Environment

* WebdriverIO version: 4.2.1 (and 4.0.9)
* Node.js version: 5.3.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio runner with ChromeDriver
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-mocha-framework

## Details
I have two tests.  In the first test I have forced a timeout.  The second test tries to chain commands off a selector on the WebDriverIO page.  These commands fail with e.g.:

browser.elements(...).getText is not a function.
browser.elements(...).value.getAttribute is not a function.

Once a timeout has occured the remaining tests will fail within that suite.  Additional suites recover.

If you run the second test only, it works.  Only when the previous test has timed out does the issue occur.

## Link to Selenium/WebdriverIO logs
Apologies, firewall prevents access to gist:

```
[11:16:55]  COMMAND	POST 	 "/wd/hub/session"
[11:16:55]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"Chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.2.1","name":"webdriverio"}}}
[11:16:56]  INFO	SET SESSION ID 0fc9133cff992b930e271d61371a908e
[11:16:56]  RESULT		{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"userDataDir":"C:\\sandbox\\tmp\\scoped_dir8160_21694"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"platform":"Windows NT","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"version":"51.0.2704.106","webStorageEnabled":true}
[11:16:56]  COMMAND	POST 	 "/wd/hub/session/0fc9133cff992b930e271d61371a908e/url"
[11:16:56]  DATA		{"url":"http://webdriver.io/"}
[11:16:58]  RESULT		null
[11:17:03]  COMMAND	POST 	 "/wd/hub/session/0fc9133cff992b930e271d61371a908e/url"
[11:17:03]  DATA		{"url":"http://webdriver.io/"}
[11:17:03]  RESULT		null
[11:17:03]  COMMAND	POST 	 "/wd/hub/session/0fc9133cff992b930e271d61371a908e/elements"
[11:17:03]  DATA		{"using":"css selector","value":"article"}
[11:17:03]  RESULT		[{"ELEMENT":"0.637462882229858-1"},{"ELEMENT":"0.637462882229858-2"},{"ELEMENT":"0.637462882229858-3"},{"ELEMENT":"0.637462882229858-4"},{"ELEMENT":"0.637462882229858-5"},{"ELEMENT":"0.637462882229858-6"},{"ELEMENT":"0.637462882229858-7"},{"ELEMENT":"0.637462882229858-8"}]
[11:17:03]  COMMAND	DELETE 	 "/wd/hub/session/0fc9133cff992b930e271d61371a908e"
[11:17:03]  DATA		{}
```

## Code To Reproduce Issue

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Sample code to reproduce the issue:

**wdio.conf.js**
```
exports.config = {   
    specs: ['./test/specs/**/*.js'],    
    exclude: [],
    maxInstances: 1,
    capabilities: [{                
        browserName: 'Chrome',        
        chromeOptions: {            
            extensions: [],                        
            args: ['start-maximized', 'disable-plugins', 'disable-plugins-discovery', 'disable-web-security']
        }
    }],
    sync: true,    
    logLevel: 'silent',    
    coloredLogs: true,    
    screenshotPath: './errorShots/',    
    baseUrl: 'http://localhost',    
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: 'mocha',
    reporters: ['dot'],
    mochaOpts: {
        ui: 'bdd',
        timeout:5000   // this timeout will be triggered on the first test
    },
    port: 9515
}
```

**bug.js**
```
'use strict';

describe('webdriver.io page', function() {
	beforeEach(function(){
		browser.url('http://webdriver.io/');
	})

    it('should timeout', function(){    	
    	browser.pause(8000);
    });

    it('should not throw an error', function () {       
		let elements = browser.elements('article');		       
        let text = elements.getText(); // any command here will fail., e.g. getAttribute               
    });
});
```

**output**
```
..

0 passing (9.00s)
2 failing

1) webdriver.io page should timeout:
timeout of 5000ms exceeded. Ensure the done() callback is being called in this t
est.
running Chrome
Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in
 this test.
    at null.<anonymous> (C:\sandbox\wdio_bug\node_modules\mocha\lib\runnable.js:
226:19)
    at Timer.listOnTimeout (timers.js:92:15)

2) webdriver.io page should not throw an error:
elements.getText is not a function
running Chrome
TypeError: elements.getText is not a function
    at Context.<anonymous> (C:\sandbox\wdio_bug\test\specs\bug.js:14:29)
    at Context.executeSync (C:\sandbox\wdio_bug\node_modules\wdio-sync\build\ind
ex.js:625:12)
    at C:\sandbox\wdio_bug\node_modules\wdio-sync\build\index.js:833:34
```

**Comment by christian-bromann** [comment]
Thanks for reporting, will investigate.

**Comment by christian-bromann** [comment]
fixed, please update your framework adapter once we have updated them.

**Comment by andyboyne** [comment]
:thumbsup: 

Very impressive response time, many thanks for this.

**Comment by khushi84throne** [comment]
Your HTML Page
    1) "before all" hook


  0 passing (2s)
  1 failing

  1) Your HTML Page "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at Timeout.<anonymous> (D:\2-Unfinished\Code School\Working\HelloCodeSchoolProject\node_modules\mocha\lib\runnable.js:226:19)



npm ERR! Test failed.  See above for more details.
