### ISSUE TITLE
Not clickable even after scrolling

### ISSUE THREAD

**Issue by jrmalin** [webdriverio/webdriverio#1495]
The following succeeds:
```
describe('init.js', function() {
    it('Check homepage', function () {
        browser.home();
    });
    it('Play F4L Video (not logged in)', function() {
        browser.exist('.NavBar__link___3kcZW=Football for Life');
  });
});
```

However, when I add this last line, it fails: 
```
describe('init.js', function() {
    it('Check homepage', function () {
        browser.home();
    });
    it('Play F4L Video (not logged in)', function() {
        browser.exist('.NavBar__link___3kcZW=Football for Life');
        browser.click('.NavBar__link___3kcZW=Football for Life');
  });
});
```
With error: 
```
Test Initializing

․․․․․[16:03:16]  	Saved screenshot: ERROR_firefox_2016-07-27T20-03-16.797Z.png
[16:03:17]  	Saved screenshot: ERROR_firefox_2016-07-27T20-03-17.196Z.png
[16:03:17]  	Saved screenshot: ERROR_firefox_2016-07-27T20-03-17.607Z.png
F

5 passing (8.30s)
1 failing

1) init.js Play F4L Video (not logged in):
Element is not clickable at point (391.566650390625, 24). Other element would receive the click: <gif>
Command duration or timeout: 71 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'jrmalin.local', ip: '10.207.100.45', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 2ef15868-0010-4243-ac17-24c9b00cc312
running firefox
RuntimeError: Element is not clickable at point (391.566650390625, 24). Other element would receive the click: <gif>
    at Context.<anonymous> (tests/init.js:7:17)
    Command duration or timeout: 71 milliseconds
    Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
    System info: host: 'jrmalin.local', ip: '10.207.100.45', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_92'
    Driver info: org.openqa.selenium.firefox.FirefoxDriver
    Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
    Session ID: 2ef15868-0010-4243-ac17-24c9b00cc312
    at elementIdClick("5") - click.js:20:22



Test Terminating

```
So, I try to scroll to that element first before clicking on it by adding the following line between `.exist()` and `.click()`: `browser.scroll('.NavBar__link___3kcZW=Football for Life');`

And I receive the following error: 

```
Test Initializing

․[16:06:51]  	Saved screenshot: ERROR_firefox_2016-07-27T20-06-51.658Z.png
․[16:06:52]  	Saved screenshot: ERROR_firefox_2016-07-27T20-06-52.084Z.png
[16:06:52]  	Saved screenshot: ERROR_chrome_2016-07-27T20-06-52.360Z.png
[16:06:52]  	Saved screenshot: ERROR_firefox_2016-07-27T20-06-52.488Z.png
F[16:06:52]  	Saved screenshot: ERROR_chrome_2016-07-27T20-06-52.741Z.png
[16:06:53]  	Saved screenshot: ERROR_chrome_2016-07-27T20-06-53.112Z.png
F․․

4 passing (30.30s)
2 failing

1) init.js Play F4L Video (not logged in):
Element is not clickable at point (391.566650390625, 24). Other element would receive the click: <gif>
Command duration or timeout: 68 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'jrmalin.local', ip: '10.207.100.45', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: c6c4246b-92aa-f943-b098-3ae134e6452c
running firefox
RuntimeError: Element is not clickable at point (391.566650390625, 24). Other element would receive the click: <gif>
    at Context.<anonymous> (tests/init.js:8:17)
    Command duration or timeout: 68 milliseconds
    Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
    System info: host: 'jrmalin.local', ip: '10.207.100.45', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_92'
    Driver info: org.openqa.selenium.firefox.FirefoxDriver
    Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
    Session ID: c6c4246b-92aa-f943-b098-3ae134e6452c
    at elementIdClick("5") - click.js:20:22

2) init.js Play F4L Video (not logged in):
unknown error: Element is not clickable at point (631, 24). Other element would receive the click: <gif>
running chrome
RuntimeError: unknown error: Element is not clickable at point (631, 24). Other element would receive the click: <gif>
    at Context.<anonymous> (tests/init.js:8:17)
    at elementIdClick("5") - click.js:20:22



Test Terminating

```

**Comment by christian-bromann** [comment]
You don't have to scroll in order to click on an element (unless you have some kind of parallax effect on your page). If you read the error message you will see that a different element (`<gif>`) is receiving the click because it is lying over your desired element. This is not a bug in WebdriverIO.
