### ISSUE TITLE
Error when starting webdriver.io for 4.2.6

### ISSUE THREAD

**Issue by psylence303** [webdriverio/webdriverio#1544]
## The problem

When starting tests using the latest version (4.2.6) I get an error:

```
module.js:341
    throw err;
    ^

Error: Cannot find module '../build/lib/cli.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ale/dev/auctionata-com/acceptance_tests/node_modules/webdriverio/bin/wdio:5:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
npm ERR! Test failed.  See above for more details.
```

Reverting to 4.2.5 fixed the issue.

## Environment

* WebdriverIO version: 4.2.6
* Node.js version: 5.12.0, npm 3.8.6
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): WDIO
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-junit-reporter, wdio-mocha-framework, wdio-selenium-standalone-service, wdio-spec-reporter

**Comment by christian-bromann** [comment]
Unpublished version. Looking into it.

**Comment by paazmaya** [comment]
Strange that the `build` directory is anyhow included in the package...

**Comment by paazmaya** [comment]
#1545

**Comment by christian-bromann** [comment]
Let's continue convo there
