### ISSUE TITLE
Running 2 different database script in web driver io with jasmine framework

### ISSUE THREAD

**Issue by 21suman-verma** [webdriverio/webdriverio#1567]
## The problem

I am trying to run 2 queries one after another at one go for different database(SQL Workbench and Oracle database) using my webdriverio script and jasmine framework.
but only first one runs and other one gives below error.
If i run them them separately, they successfully returns correct output, but together they yield below error message.
There is no issue in the code as separately they give correct output.The problem arrives only if they are run together.

## Error message
```
{ [Error: Could not find class oracle.jdbc.driver.OracleDriver
java.lang.NoClassDefFoundError: oracle/jdbc/driver/OracleDriver
Caused by: java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
] cause: {} }
{ [Error: Could not find class oracle.jdbc.driver.OracleDriver
java.lang.NoClassDefFoundError: oracle/jdbc/driver/OracleDriver
Caused by: java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
] cause: {} }
{ [Error: Error running static method
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:udm3_user/professionalappleudmuser@kasidy.corp.apple.com:1722:edsd
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
] cause: {} }
{ [Error: Error running static method
java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:udm3_user/professionalappleudmuser@kasidy.corp.apple.com:1722:edsd
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
] cause: {} }
```
## Code To Reproduce Issue [ Good To Have ]

```
it('TC_OOO2- Populate DataBase(TeraData) data ; Logged in user: ' + runData['userName'] + '; Browser: ' + runData['browser'] + '; DataBase: ' + runData['dataBase'], function (done) {
        try {     
                //console.log('Query Executed:', sql[runData.dbQuery].tdUiData);
                //console.log(dbCon[runData.dbConfig]);
               aLib.db_execute(dbCon[runData.dbConfig],sql[runData.dbQuery].tdUpdatedBy, function (dbTdTable){
                  console.log(dbTdTable);
            });
             client.pause(12000);
        } catch (e) {
            expect(false).toBe(true);
            throw new Error('testcase case failed because of exception : ' + e);
        }
        client.call(done);
    },250000);
    //Completed
    it('TC_OOO3- Populate DataBase(Oracle) DS_ID data ; Logged in user:' + runData['userName'] + '; Browser: ' + runData['browser'] + '; DataBase: ' + runData['dataBase'], function (done) {
        try { 
           // console.log('Query Executed for oracle DB:', sql.oracleQuery.DS_ID);
           // aLib.db_execute(dbCon.oracleConfig, sql.oracleQuery.DS_ID, function (dbOrTable){
                 // console.log(dbOrTable);
           // });
           aLib.db_execute(dbCon.oracleConfig, sql.oracleQuery.abc, function (dbOrTable1){
                  console.log(dbOrTable1);
            });
            client.pause(12000);

        } catch (e) {
            expect(false).toBe(true);
            throw new Error('testcase case failed because of exception : ' + e);
        }
        client.call(done);
    },250000); 
```

**Comment by christian-bromann** [comment]
Why is that an issue with WebdriverIO? Looks more like a race condition with the database.
