### ISSUE TITLE
wdio.conf.ejs not created

### ISSUE THREAD

**Issue by Wats0ns** [webdriverio/webdriverio#1568]
## The problem

So I just installed webdriverio and I can't create the wdio.conf.ejs file. Every time I get through the question interface, I get the following error:
```

=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? mocha
? Shall I install the framework adapter for you? Yes
? Where are your test specs located? ./test/specs/**/*.js
? Which reporter do you want to use?  dot - https://github.com/webdriverio/wdio-dot-reporter
? Shall I install the reporter library for you? Yes
? Do you want to add a service to your test setup?  firefox-profile - https://github.com/webdriverio/wdio-firefox-profile-service
? Shall I install the services for you? Yes
? Level of logging verbosity verbose
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://site.lan

Installing wdio packages:
pkg: wdio-mocha-framework
pkg: wdio-dot-reporter
pkg: wdio-firefox-profile-service

Packages installed successfully, creating configuration file...
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/qwebify/Entrup/unit/node_modules/webdriverio/build/lib/helpers/wdio.conf.ejs'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at renderConfigurationFile (/home/user/project/unit/node_modules/webdriverio/build/lib/cli.js:286:28)
    at /home/user/project/unit/node_modules/webdriverio/build/lib/cli.js:276:17
    at /home/user/project/unit/node_modules/npm-install-package/index.js:29:5
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
```

## Environment

* WebdriverIO version: 4.2.10
* Node.js version: 4.2.6
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): WDIO testrunner

**Comment by bmsoko** [comment]
Same here +1! 
```
nvm --version : 0.31.1
npm --version : 2.14.12
node --version : v4.3.0
```

**Comment by Wats0ns** [comment]
Not at all, I tried with different params, I always get the same result :cry:

**Comment by christian-bromann** [comment]
Sorry, we didn't put the ejs template into the package, will release a new version asap

**Comment by christian-bromann** [comment]
Just published `webdriverio@4.2.11` with the fix.
Sorry, last time that I touch that npmignore .. promise 😉

**Comment by bmsoko** [comment]
@christian-bromann thanks! worked now! Much appreciated!

**Comment by aztack** [comment]
same problem.
```json
"dependencies": {
    "wdio-sync": "^0.6.14",
    "webdriverio": "^4.8.0"
  },
```
node v6.0.0
mac os 10.12
when I try to use `wdio config` I got following error. 
files in `node_modules/webdriverio` is deleted and only a empty `node_modules/webdriverio/node_modules`  is there.
wdio in `node_modules/.bin` is also missing.

![image](https://user-images.githubusercontent.com/782871/28398903-3afea836-6d3c-11e7-923f-0afc4f516ce3.png)

I think there is something wrong when installing framework adapter, cause no error reported when I skip installing framework adapter:
![image](https://user-images.githubusercontent.com/782871/28399062-5466b95c-6d3d-11e7-8984-3936acafd30d.png)

**Comment by bennypowers** [comment]
Same problem:

os x

```
yarn add -D webdriverio
yarn wdio -- config
$ "/Users/bennyp/Documents/elastic/eve-frontend/node_modules/.bin/wdio" "config"

=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? mocha
? Shall I install the framework adapter for you? Yes
? Where are your test specs located? ./test/specs/**/*.js
? Which reporter do you want to use?  dot - https://github.com/webdriverio/wdio-dot-re
porter
? Shall I install the reporter library for you? Yes

? Do you want to add a service to your test setup?
? Level of logging verbosity silent
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://localhost

Installing wdio packages:

Packages installed successfully, creating configuration file...
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/bennyp/Documents/elastic/eve-fr
ontend/node_modules/webdriverio/build/lib/helpers/wdio.conf.ejs'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at renderConfigurationFile (/Users/bennyp/Documents/elastic/eve-frontend/node_modu
les/webdriverio/build/lib/cli.js:292:28)
    at /Users/bennyp/Documents/elastic/eve-frontend/node_modules/webdriverio/build/lib
/cli.js:282:17
    at /Users/bennyp/Documents/elastic/eve-frontend/node_modules/npm-install-package/i
ndex.js:31:5
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
error Command failed with exit code 1.
```
