### ISSUE TITLE
Intermittent Reporting of Failure in Mocha suiteSetup

### ISSUE THREAD

**Issue by fijijavis** [webdriverio/webdriverio#1591]
## The problem

When a failure occurs in a Mocha suiteSetup intermittently the failure is not bubbling up properly.  
## Environment
- WebdriverIO version: 4.2.11
- Node.js version: 4.4.7
- [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
- if wdio testrunner, running synchronous or asynchronous tests: sync
- Additional wdio packages used (if applicable): package.json is attached
## Details

When a Mocha suiteSetup fails I am seeing intermittent behavior with reporting of the failure.  In some instances all I see the full results and others all I am seeing is part of the results.

Example Full Result:

```
0 passing (12.00s)                                                                                                                                    
1 failing                                                                                                                                             

1) sample suite "before all" hook:                                                                                                                    
element (#thisshouldfail) still not visible after 5000ms                                                                                              
running chrome on ANY                                                                                                                                 
Error: element (#thisshouldfail) still not visible after 5000ms                                                                                       
    at Context.<anonymous> (tests/sample.test.js:13:17)                                                                                               
    at elements("#thisshouldfail") - isVisible.js:54:17                                                                                               
    at isVisible("#thisshouldfail") - waitForVisible.js:37:22                    `

Example Partial Result
`0 passing (12.00s)`
```

I'm thinking this is an issue with waiting for screen prints to be captured. When the screenshotPath in my conf file is a "real" path the percentage of time when I don't get a full report is over 90%.  However if I set the screenshotPath to something like "/dev/null" the percentage of time when I don't get a full report drops to like 30%.
## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!
## Code To Reproduce Issue [ Good To Have ]

Attached package.json, conf.js and spec.js

[Archive.zip](https://github.com/webdriverio/webdriverio/files/472219/Archive.zip)

**Comment by msegado** [comment]
I can reproduce this in a regular test too, not just in a suiteSetup (formula seems to be timeouts + errorShots = no reporting; can you change the issue title to reflect?). Here are my test file and config:

```js
/* file: test.js */
describe('It doesn\'t report with errorShots enabled', () => {
  it('should fail on this spec', () => {
    browser.url('/login');
    browser.waitForVisible('#does-not-exist');
  });
});

/* file: wdio.conf.js */
exports.config = {
  specs: ['./test.js'],
  capabilities: [{ browserName: 'phantomjs' }],
  sync: true,
  logLevel: 'debug',
  coloredLogs: true,
  screenshotPath: './errorShots/',  // <= works fine if this is commented out
  baseUrl: 'http://localhost:8000',
  waitforTimeout: 3000,
  services: ['phantomjs'],
  framework: 'mocha',
  reporters: ['spec'],
  mochaOpts: { ui: 'bdd' },
};
```

Result with `screenshotPath`:
```
=======================================================================================
Selenium 2.0 / webdriver protocol bindings implementation with helper commands in nodejs.
For a complete list of commands, visit http://webdriver.io/api.html.
=======================================================================================

[16:11:08]  	Saved screenshot: ERROR_phantomjs_2016-10-04T20-11-07.800Z.png
my-bash-prompt$ 
```


Results without `screenshotPath`:
```
=======================================================================================
Selenium 2.0 / webdriver protocol bindings implementation with helper commands in nodejs.
For a complete list of commands, visit http://webdriver.io/api.html.
=======================================================================================

------------------------------------------------------------------
[phantomjs #0a] Session ID: 450e1d00-8a6d-11e6-8f59-cfb293cd49e1
[phantomjs #0a] Spec: [snipped]/test.js
[phantomjs #0a] Running: phantomjs
[phantomjs #0a]
[phantomjs #0a]   It doesn't report with errorShots enabled
[phantomjs #0a]       1) should fail on this spec
[phantomjs #0a]
[phantomjs #0a]
[phantomjs #0a] 1 failing (4s)
[phantomjs #0a]
[phantomjs #0a] 1) It doesn't report with errorShots enabled should fail on this spec:
[phantomjs #0a] element (#does-not-exist) still not visible after 3000ms
[phantomjs #0a] Error: element (#does-not-exist) still not visible after 3000ms
[phantomjs #0a]     at Context.it (test-1.js:4:13)
[phantomjs #0a]     at elements("#does-not-exist") - isVisible.js:54:17
[phantomjs #0a]     at isVisible("#does-not-exist") - waitForVisible.js:37:22
[phantomjs #0a]

my-bash-prompt$ 
```
My environment:
- WebdriverIO version: **4.2.16**
- Node.js version: **6.5.0**
- Standalone mode or wdio testrunner: **wdio**
- if wdio testrunner, running synchronous or asynchronous tests: **sync**
- Additional wdio packages used (if applicable):
   - "wdio-mocha-framework": "^0.4.3",
   - "wdio-phantomjs-service": "^0.1.0",
   - "wdio-spec-reporter": "0.0.3",

**Comment by martynjarvis** [comment]
I'm also seeing this problem. I can confirm that commenting out `screenshotPath` also seems to fix it.

## Environment

* WebdriverIO version: v4.2.16
* Node.js version: v4.2.6
* wdio test runner running synchronous
* Additional wdio packages used:
```
    "wdio-phantomjs-service": "^0.2.2",
    "wdio-spec-reporter": "0.0.3",
    "webdriverio": "^4.2.16",
    "wdio-dot-reporter": "0.0.6",
    "wdio-mocha-framework": "^0.4.3"
```

## Link to Selenium/WebdriverIO logs

With dot reporter: https://gist.github.com/martynjarvis/994b2be705ae1f02af2e50a8e8de8b49

Where there are actually 6 test cases being run, but the reporter reports only 5.

## Code To Reproduce Issue

A minimal test case that is causing the issue is:

```
describe('Enter search term', function () {
    it('test case', function () {
        // perform some action
        browser.waitUntil(function () {
            return browser.getHTML('#this exists', false) == 'this will not match';
        }, 5000, 'expected text to be different after 5s');
    });
});
```

**Comment by monolithed** [comment]
I could reproduce my [issue](https://github.com/webdriverio/webdriverio/issues/1760) anymore since wdio-mocha-framework@0.5.5 has been released:

```diff
diff --git a/lib/adapter.js b/lib/adapter.js
index 2ef8fe2..2ca1349 100644
--- a/lib/adapter.js
+++ b/lib/adapter.js
@@ -22,6 +22,7 @@ const EVENTS = {
 }
 
 const NOOP = function () {}
+const SETTLE_TIMEOUT = 5000
 
 /**
  * Mocha runner
@@ -47,6 +48,15 @@ class MochaAdapter {
             mochaOpts: {}
         }, config)
         this.runner = {}
+
+        this.sentMessages = 0 // number of messages sent to the parent
+        this.receivedMessages = 0 // number of messages received by the parent
+        this.messageCounter = 0
+        this.messageUIDs = {
+            suite: {},
+            hook: {},
+            test: {}
+        }
     }
 
     options (options, context) {
@@ -104,6 +114,8 @@ class MochaAdapter {
             this.runner.suite.afterAll(this.wrapHook('afterSuite'))
         })
         await executeHooksWithArgs(this.config.after, [result, this.capabilities, this.specs])
+        await this.waitUntilSettled()
+
         return result
     }
 
@@ -213,13 +225,77 @@ class MochaAdapter {
             this.runner.lastError = err
         }
 
+        let {uid, parentUid} = this.generateUID(message)
+        message.uid = uid
+        message.parent = parentUid
+
         // When starting a new test, propagate the details to the test runner so that
         // commands, results, screenshots and hooks can be associated with this test
         if (event === 'test:start') {
             this.sendInternal(event, message)
         }
 
-        this.send(message)
+        this.send(message, null, {}, () => ++this.receivedMessages)
+        this.sentMessages++
+    }
+
+    generateUID (message) {
+        var uid, parentUid
+
+        switch (message.type) {
+        case 'suite:start':
+            uid = this.getUID(message.title, 'suite', true)
+            parentUid = uid
+            break
+
+        case 'suite:end':
+            uid = this.getUID(message.title, 'suite')
+            parentUid = uid
+            break
+
+        case 'hook:start':
+            uid = this.getUID(message.title, 'hook', true)
+            parentUid = this.getUID(message.parent, 'suite')
+            break
+
+        case 'hook:end':
+            uid = this.getUID(message.title, 'hook')
+            parentUid = this.getUID(message.parent, 'suite')
+            break
+
+        case 'test:start':
+            uid = this.getUID(message.title, 'test', true)
+            parentUid = this.getUID(message.parent, 'suite')
+            break
+
+        case 'test:pending':
+        case 'test:end':
+        case 'test:pass':
+        case 'test:fail':
+            uid = this.getUID(message.title, 'test')
+            parentUid = this.getUID(message.parent, 'suite')
+            break
+
+        default:
+            throw new Error(`Unknown message type : ${message.type}`)
+        }
+
+        return {
+            uid,
+            parentUid
+        }
+    }
+
+    getUID (title, type, start) {
+        if (start !== true && this.messageUIDs[type][title]) {
+            return this.messageUIDs[type][title]
+        }
+
+        let uid = title + this.messageCounter++
+
+        this.messageUIDs[type][title] = uid
+
+        return uid
     }
 
     sendInternal (event, message) {
@@ -233,6 +309,22 @@ class MochaAdapter {
         return process.send.apply(process, args)
     }
 
+    /**
+     * wait until all messages were sent to parent
+     */
+    waitUntilSettled () {
+        return new Promise((resolve) => {
+            const start = (new Date()).getTime()
+            const interval = setInterval(() => {
+                const now = (new Date()).getTime()
+
+                if (this.sentMessages !== this.receivedMessages && now - start < SETTLE_TIMEOUT) return
+                clearInterval(interval)
+                resolve()
+            }, 100)
+        })
+    }
+
     load (name, context) {
         try {
             module.context = context
```

**Comment by christian-bromann** [comment]
@fijijavis can you update your packages and retry?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
