### ISSUE TITLE
Intermittent errors: Uncaught TypeError: Cannot read property 'sessionId' of undefined

### ISSUE THREAD

**Issue by ragulka** [webdriverio/webdriverio#160]
Probably 3-5 times out of ten, when I try to run my selenium tests, I get the following error:

```
Uncaught TypeError: Cannot read property 'sessionId' of undefined
      at RequestHandler.setSessionID (/Sites/myapp/node_modules/webdriverjs/lib/utils/RequestHandler.js:53:26)
      at RequestHandler.<anonymous> (/Sites/myapp/node_modules/webdriverjs/lib/utils/RequestHandler.js:170:18)
      at Request.self.callback (/Sites/myapp/node_modules/webdriverjs/node_modules/request/request.js:122:22)
      at Request.EventEmitter.emit (events.js:98:17)
      at Request.<anonymous> (/Sites/myapp/node_modules/webdriverjs/node_modules/request/request.js:888:14)
      at Request.EventEmitter.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/Sites/myapp/node_modules/webdriverjs/node_modules/request/request.js:839:12)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickDomainCallback (node.js:459:13)
```

It's weird because I can't really understand why it's happening. I am using selenium-standalone package to start the selenium server (and its running just fine). Selenium server is at 2.40 and chromedriver is at 2.9. webdriverjs is 1.3.1

Any ideas what may cause this? It's simply annoying not being able to run the tests almost half of the times I try.

**Comment by mucaho** [comment]
I agree, would you kindly point us to documentation for using WebdriverIO programmatically (standalone)? Most of the documentation focuses on the built-in testrunner, which imposes the choice of the test framework (I want to use `QUnit`).
