### ISSUE TITLE
Firefox 49 does nothing after start

### ISSUE THREAD

**Issue by Kureev** [webdriverio/webdriverio#1605]
## The problem

I'm trying to run a "Hello, World!" example from the title page of your website. I updated my ff version to 49 (latest stable available today), but it seems that nothing happens after opening a blank ff window (no navigation to http://google.com).

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 5.8.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): standalone
* if wdio testrunner, running synchronous or asynchronous tests: -
* Additional wdio packages used (if applicable): -

## Link to Selenium/WebdriverIO logs

<details>
```
5:15:24.362 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1bc27488, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.2.16, url=http://webdriver.io}}]])
15:15:24.363 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1bc27488, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.2.16, url=http://webdriver.io}}]
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":null,"icons":{},"iconURL":"chrome://web2pdfextension/skin/C_AdobeLogo_48x48.png","icon64URL":"chrome://web2pdfextension/skin/C_AdobeLogo_64x64.png","defaultLocale":{"name":"Adobe Acrobat DC - Create PDF","description":"Converts a web page to PDF","creator":"Adobe Systems Incorporated","homepageURL":"http://www.adobe.com/"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/web2pdfextension@web2pdf.adobedotcom","installDate":1470758818000,"updateDate":1470758818000,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":167926,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"4.0","maxVersion":"46.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1474463725542  	DeferredSave.extensions.json   	DEBUG  	Save changes
1474463725542  	addons.xpi     	DEBUG  	Updating database with changes to installed add-ons
1474463725542  	addons.xpi-utils       	DEBUG  	Updating add-on states
1474463725543  	addons.xpi-utils       	DEBUG  	Writing add-ons list
1474463725544  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1474463725545  	addons.xpi     	DEBUG  	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1474463725545  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1474463725545  	addons.xpi     	DEBUG  	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1474463725546  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1474463725546  	addons.xpi     	DEBUG  	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1474463725549  	addons.manager 	DEBUG  	Registering shutdown blocker for XPIProvider
1474463725549  	addons.manager 	DEBUG  	Provider finished startup: XPIProvider
1474463725550  	addons.manager 	DEBUG  	Starting provider: LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Registering shutdown blocker for LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Provider finished startup: LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Starting provider: GMPProvider
1474463725557  	addons.manager 	DEBUG  	Registering shutdown blocker for GMPProvider
1474463725558  	addons.manager 	DEBUG  	Provider finished startup: GMPProvider
1474463725558  	addons.manager 	DEBUG  	Starting provider: PluginProvider
1474463725558  	addons.manager 	DEBUG  	Registering shutdown blocker for PluginProvider
1474463725559  	addons.manager 	DEBUG  	Provider finished startup: PluginProvider
1474463725559  	addons.manager 	DEBUG  	Completed startup sequence
1474463725663  	addons.manager 	DEBUG  	Starting provider: <unnamed-provider>
1474463725663  	addons.manager 	DEBUG  	Registering shutdown blocker for <unnamed-provider>
1474463725664  	addons.manager 	DEBUG  	Provider finished startup: <unnamed-provider>
1474463725969  	DeferredSave.extensions.json   	DEBUG  	Write succeeded
1474463725969  	addons.xpi-utils       	DEBUG  	XPI Database saved, setting schema version preference to 17
1474463725969  	DeferredSave.extensions.json   	DEBUG  	Starting timer
1474463725974  	addons.repository      	DEBUG  	No addons.json found.
1474463725974  	DeferredSave.addons.json       	DEBUG  	Save changes
1474463725979  	DeferredSave.addons.json       	DEBUG  	Starting timer
1474463726021  	addons.manager 	DEBUG  	Starting provider: PreviousExperimentProvider
1474463726021  	addons.manager 	DEBUG  	Registering shutdown blocker for PreviousExperimentProvider
1474463726021  	addons.manager 	DEBUG  	Provider finished startup: PreviousExperimentProvider
1474463726033  	DeferredSave.extensions.json   	DEBUG  	Starting write
1474463726036  	DeferredSave.addons.json       	DEBUG  	Starting write
1474463726059  	DeferredSave.extensions.json   	DEBUG  	Write succeeded
1474463726063  	DeferredSave.addons.json       	DEBUG  	Write succeeded

       	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
       	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
       	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
       	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
       	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
       	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:129)
       	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
       	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:91)
       	at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:68)
       	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
       	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
       	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
       	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)
15:16:10.138 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'MacBook-Pro-3.local', ip: '192.168.0.11', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_60'
Driver info: driver.version: unknown
       	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
       	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
       	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
       	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
       	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
       	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
       	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
       	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
       	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
       	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
       	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
       	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
       	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
       	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
       	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
       	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
       	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
       	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
       	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
       	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
       	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
       	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
       	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
       	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
       	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
       	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'MacBook-Pro-3.local', ip: '192.168.0.11', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_60'
Driver info: driver.version: unknown
       	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:101)
       	at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:68)
       	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
       	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
       	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
       	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
       	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
       	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:91)
       	... 9 more
Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows:
":null,"icons":{},"iconURL":"chrome://web2pdfextension/skin/C_AdobeLogo_48x48.png","icon64URL":"chrome://web2pdfextension/skin/C_AdobeLogo_64x64.png","defaultLocale":{"name":"Adobe Acrobat DC - Create PDF","description":"Converts a web page to PDF","creator":"Adobe Systems Incorporated","homepageURL":"http://www.adobe.com/"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/web2pdfextension@web2pdf.adobedotcom","installDate":1470758818000,"updateDate":1470758818000,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":167926,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"4.0","maxVersion":"46.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1474463725542  	DeferredSave.extensions.json   	DEBUG  	Save changes
1474463725542  	addons.xpi     	DEBUG  	Updating database with changes to installed add-ons
1474463725542  	addons.xpi-utils       	DEBUG  	Updating add-on states
1474463725543  	addons.xpi-utils       	DEBUG  	Writing add-ons list
1474463725544  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1474463725545  	addons.xpi     	DEBUG  	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1474463725545  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1474463725545  	addons.xpi     	DEBUG  	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1474463725546  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1474463725546  	addons.xpi     	DEBUG  	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1474463725549  	addons.manager 	DEBUG  	Registering shutdown blocker for XPIProvider
1474463725549  	addons.manager 	DEBUG  	Provider finished startup: XPIProvider
1474463725550  	addons.manager 	DEBUG  	Starting provider: LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Registering shutdown blocker for LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Provider finished startup: LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Starting provider: GMPProvider
1474463725557  	addons.manager 	DEBUG  	Registering shutdown blocker for GMPProvider
1474463725558  	addons.manager 	DEBUG  	Provider finished startup: GMPProvider
1474463725558  	addons.manager 	DEBUG  	Starting provider: PluginProvider
1474463725558  	addons.manager 	DEBUG  	Registering shutdown blocker for PluginProvider
1474463725559  	addons.manager 	DEBUG  	Provider finished startup: PluginProvider
1474463725559  	addons.manager 	DEBUG  	Completed startup sequence
1474463725663  	addons.manager 	DEBUG  	Starting provider: <unnamed-provider>
1474463725663  	addons.manager 	DEBUG  	Registering shutdown blocker for <unnamed-provider>
1474463725664  	addons.manager 	DEBUG  	Provider finished startup: <unnamed-provider>
1474463725969  	DeferredSave.extensions.json   	DEBUG  	Write succeeded
1474463725969  	addons.xpi-utils       	DEBUG  	XPI Database saved, setting schema version preference to 17
1474463725969  	DeferredSave.extensions.json   	DEBUG  	Starting timer
1474463725974  	addons.repository      	DEBUG  	No addons.json found.
1474463725974  	DeferredSave.addons.json       	DEBUG  	Save changes
1474463725979  	DeferredSave.addons.json       	DEBUG  	Starting timer
1474463726021  	addons.manager 	DEBUG  	Starting provider: PreviousExperimentProvider
1474463726021  	addons.manager 	DEBUG  	Registering shutdown blocker for PreviousExperimentProvider
1474463726021  	addons.manager 	DEBUG  	Provider finished startup: PreviousExperimentProvider
1474463726033  	DeferredSave.extensions.json   	DEBUG  	Starting write
1474463726036  	DeferredSave.addons.json       	DEBUG  	Starting write
1474463726059  	DeferredSave.extensions.json   	DEBUG  	Write succeeded
1474463726063  	DeferredSave.addons.json       	DEBUG  	Write succeeded

Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'MacBook-Pro-3.local', ip: '192.168.0.11', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_60'
Driver info: driver.version: FirefoxDriver
       	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:124)
       	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
       	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
       	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
       	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
       	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:129)
       	... 14 more
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":null,"icons":{},"iconURL":"chrome://web2pdfextension/skin/C_AdobeLogo_48x48.png","icon64URL":"chrome://web2pdfextension/skin/C_AdobeLogo_64x64.png","defaultLocale":{"name":"Adobe Acrobat DC - Create PDF","description":"Converts a web page to PDF","creator":"Adobe Systems Incorporated","homepageURL":"http://www.adobe.com/"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/web2pdfextension@web2pdf.adobedotcom","installDate":1470758818000,"updateDate":1470758818000,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":167926,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"4.0","maxVersion":"46.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1474463725542  	DeferredSave.extensions.json   	DEBUG  	Save changes
1474463725542  	addons.xpi     	DEBUG  	Updating database with changes to installed add-ons
1474463725542  	addons.xpi-utils       	DEBUG  	Updating add-on states
1474463725543  	addons.xpi-utils       	DEBUG  	Writing add-ons list
1474463725544  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1474463725545  	addons.xpi     	DEBUG  	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1474463725545  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1474463725545  	addons.xpi     	DEBUG  	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1474463725546  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1474463725546  	addons.xpi     	DEBUG  	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1474463725549  	addons.manager 	DEBUG  	Registering shutdown blocker for XPIProvider
1474463725549  	addons.manager 	DEBUG  	Provider finished startup: XPIProvider
1474463725550  	addons.manager 	DEBUG  	Starting provider: LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Registering shutdown blocker for LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Provider finished startup: LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Starting provider: GMPProvider
1474463725557  	addons.manager 	DEBUG  	Registering shutdown blocker for GMPProvider
1474463725558  	addons.manager 	DEBUG  	Provider finished startup: GMPProvider
1474463725558  	addons.manager 	DEBUG  	Starting provider: PluginProvider
1474463725558  	addons.manager 	DEBUG  	Registering shutdown blocker for PluginProvider
1474463725559  	addons.manager 	DEBUG  	Provider finished startup: PluginProvider
1474463725559  	addons.manager 	DEBUG  	Completed startup sequence
1474463725663  	addons.manager 	DEBUG  	Starting provider: <unnamed-provider>
1474463725663  	addons.manager 	DEBUG  	Registering shutdown blocker for <unnamed-provider>
1474463725664  	addons.manager 	DEBUG  	Provider finished startup: <unnamed-provider>
1474463725969  	DeferredSave.extensions.json   	DEBUG  	Write succeeded
1474463725969  	addons.xpi-utils       	DEBUG  	XPI Database saved, setting schema version preference to 17
1474463725969  	DeferredSave.extensions.json   	DEBUG  	Starting timer
1474463725974  	addons.repository      	DEBUG  	No addons.json found.
1474463725974  	DeferredSave.addons.json       	DEBUG  	Save changes
1474463725979  	DeferredSave.addons.json       	DEBUG  	Starting timer
1474463726021  	addons.manager 	DEBUG  	Starting provider: PreviousExperimentProvider
1474463726021  	addons.manager 	DEBUG  	Registering shutdown blocker for PreviousExperimentProvider
1474463726021  	addons.manager 	DEBUG  	Provider finished startup: PreviousExperimentProvider
1474463726033  	DeferredSave.extensions.json   	DEBUG  	Starting write
1474463726036  	DeferredSave.addons.json       	DEBUG  	Starting write
1474463726059  	DeferredSave.extensions.json   	DEBUG  	Write succeeded
1474463726063  	DeferredSave.addons.json       	DEBUG  	Write succeeded

       	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
       	... 19 more
15:16:10.142 WARN - Exception: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":null,"icons":{},"iconURL":"chrome://web2pdfextension/skin/C_AdobeLogo_48x48.png","icon64URL":"chrome://web2pdfextension/skin/C_AdobeLogo_64x64.png","defaultLocale":{"name":"Adobe Acrobat DC - Create PDF","description":"Converts a web page to PDF","creator":"Adobe Systems Incorporated","homepageURL":"http://www.adobe.com/"},"visible":true,"active":false,"userDisabled":true,"appDisabled":false,"descriptor":"/Library/Application Support/Mozilla/Extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/web2pdfextension@web2pdf.adobedotcom","installDate":1470758818000,"updateDate":1470758818000,"applyBackgroundUpdates":1,"bootstrap":false,"skinnable":false,"size":167926,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"4.0","maxVersion":"46.0"}],"targetPlatforms":[],"multiprocessCompatible":false,"signedState":2,"seen":true}
1474463725542  	DeferredSave.extensions.json   	DEBUG  	Save changes
1474463725542  	addons.xpi     	DEBUG  	Updating database with changes to installed add-ons
1474463725542  	addons.xpi-utils       	DEBUG  	Updating add-on states
1474463725543  	addons.xpi-utils       	DEBUG  	Writing add-ons list
1474463725544  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
1474463725545  	addons.xpi     	DEBUG  	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
1474463725545  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
1474463725545  	addons.xpi     	DEBUG  	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
1474463725546  	addons.xpi     	DEBUG  	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
1474463725546  	addons.xpi     	DEBUG  	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
1474463725549  	addons.manager 	DEBUG  	Registering shutdown blocker for XPIProvider
1474463725549  	addons.manager 	DEBUG  	Provider finished startup: XPIProvider
1474463725550  	addons.manager 	DEBUG  	Starting provider: LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Registering shutdown blocker for LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Provider finished startup: LightweightThemeManager
1474463725550  	addons.manager 	DEBUG  	Starting provider: GMPProvider
1474463725557  	addons.manager 	DEBUG  	Registering shutdown blocker for GMPProvider
1474463725558  	addons.manager 	DEBUG  	Provider finished startup: GMPProvider
1474463725558  	addons.manager 	DEBUG  	Starting provider: PluginProvider
1474463725558  	addons.manager 	DEBUG  	Registering shutdown blocker for PluginProvider
1474463725559  	addons.manager 	DEBUG  	Provider finished startup: PluginProvider
1474463725559  	addons.manager 	DEBUG  	Completed startup sequence
1474463725663  	addons.manager 	DEBUG  	Starting provider: <unnamed-provider>
1474463725663  	addons.manager 	DEBUG  	Registering shutdown blocker for <unnamed-provider>
1474463725664  	addons.manager 	DEBUG  	Provider finished startup: <unnamed-provider>
1474463725969  	DeferredSave.extensions.json   	DEBUG  	Write succeeded
1474463725969  	addons.xpi-utils       	DEBUG  	XPI Database saved, setting schema version preference to 17
1474463725969  	DeferredSave.extensions.json   	DEBUG  	Starting timer
1474463725974  	addons.repository      	DEBUG  	No addons.json found.
1474463725974  	DeferredSave.addons.json       	DEBUG  	Save changes
1474463725979  	DeferredSave.addons.json       	DEBUG  	Starting timer
1474463726021  	addons.manager 	DEBUG  	Starting provider: PreviousExperimentProvider
1474463726021  	addons.manager 	DEBUG  	Registering shutdown blocker for PreviousExperimentProvider
1474463726021  	addons.manager 	DEBUG  	Provider finished startup: PreviousExperimentProvider
1474463726033  	DeferredSave.extensions.json   	DEBUG  	Starting write
1474463726036  	DeferredSave.addons.json       	DEBUG  	Starting write
1474463726059  	DeferredSave.extensions.json   	DEBUG  	Write succeeded
1474463726063  	DeferredSave.addons.json       	DEBUG  	Write succeeded
```
</details>

## Code To Reproduce Issue [ Good To Have ]

You can use an example code from the title page

**Comment by christian-bromann** [comment]
Latest Firefox version don't work with Selenium standalone v2.x anymore. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
