### ISSUE TITLE
Stale Reference Error

### ISSUE THREAD

**Issue by si-mikey** [webdriverio/webdriverio#1635]
## The problem

I seem to be getting a stale reference error even when using page objects. The reason seems to be that when clicking a button on a page, the page refreshes ( and before the load has completed ) wdio using ( cucumber ) the next step continues and in this next step I am checking for text on the refreshed page. Essentially if there was a hook or some way to tell wdio to not execute the next step until the browser has finished loading then this would be avoided. Is there some way to detect browser hasn't finished loading?

## Environment

* WebdriverIO version: 4.2.16
* Node.js version: 4.0.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): cucumber package

**Comment by christian-bromann** [comment]
@si-mikey WebdriverIO detects stale element errors and refetches the elements, can you check in the Selenium logs if this is happening?

> checking for text on the refreshed page

The element you already fetched isn't working on the refreshed page. However wdio should refetch it.

Please paste your logs in here so we can investigate

**Comment by si-mikey** [comment]
Thank for quick response on this, noticed a few others are having a similar issue. 

In feature file I got this
```bash
When I click the "accept_button"
Then I expect the "assignment_status" text to change to "ASSIGNED"
```
In step def I got this
```bash
// this works (refreshes the page)
 this.When(/^I click on the "(.+)"$/, function (element) {
    this.loginPage[element].click()
  });

 // before the page has finished loading this step happens and in the retry I also get a stale ref err
 this.When(/^I expect the "(.+)" text to change to "(.+)"$/, { retry: 2} , function(element, text){
   let el = this.loginPage[element];
   browser.waitUntil(function() {
     return el.getText() == text;
   }, 5000, 'text has not changed');


 });
```

```bash 
Session ID: 6b95569d-c5c8-a747-a76d-6ff79863630e
17:10:17.607 INFO - Executing: [get text: 4 [[FirefoxDriver: firefox on MAC (6b95569d-c5c8-a747-a76d-6ff79863630e)] -> css selector: .assignment-status]])
17:10:17.686 INFO - Done: [take screenshot]
17:10:17.714 INFO - Executing: [delete session: 6cef811d-23e1-4f1a-ad05-b7ac40383f81])
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.
JavaScript error: , line 0: TypeError: NetworkError when attempting to fetch resource.
17:10:17.908 WARN - Exception thrown
org.openqa.selenium.StaleElementReferenceException: The element reference is stale. Either the element is no longer attached to the DOM or the page has been refreshed.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:29:23 -0700'
System info: host: 'ip-192-168-20-112.ec2.internal', ip: '192.168.20.112', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{raisesAccessibilityExceptions=false, loggingPrefs={driver=ALL, browser=ALL}, appBuildId=20160922113459, platform=MAC, requestOrigins={name=webdriverio, version=4.2.16, url=http://webdriver.io}, specificationLevel=0, acceptSslCerts=false, processId=60826, browserVersion=49.0.1, platformVersion=15.4.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, maxInstances=4, platformName=darwin, rotatable=false, firefoxOptions={args=[], profile=UEsDBBQACAgIAEGJRkkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51X227jNhB971cUfmqBmsht20X7lGZToMCiKdYI9pGgqJHFmCJZXqz47zukpPgmUU6eYikz5FzOmTkKDiw1FqqfFoXVLT4RxypIv4Vak4bJllkgoFghoVz88mPFpIOf//gh7D1L5tHGaOujSw1M+rp7Jmi0FXzGX4Fvtd2Q2ntDTC1cvVvGfxvm3FKCWvsaHW8+fTp2GwK2wEr8U4IH7qH8S1jn7zEWLgHdvA2n4eoG83qlvLa6Aeq4FcZTGxT1ookut1fjF3lWOILlUE/qQWoH49kM1qVuldSsxLsUW8fC1rr9XoNaYbVipcbdDQZlvIuX0UaXTM7UHrZea+kIWKst18ppeVju8/SdWCutsGoNNAXYVXp0+VwcOCfQymvEggUXsG4VBkq5Za7O+0qhNkQbUBRePVjFZGzmuxFUxbZ+C2r8shaK0ootPjPOAdsZFGbuEA6Ug/VutBJvnRLOSLaD8vH6avWPRuTE1t6NG+Or8kl9Fwr7666viMCL9PO3r+ixYIUO/vdCMrVZnGOuS4gyKemLw2LEOEVX+vPYXo3AcqMtaWvhQQrn8YD/grBTSIgw2AhPejYNqMPkIhayBZAMG4MEyEPNRdwGQ2pkjcGzaQuSRwYFG1u6OEk5dlsl1JBgsMFAFJa22j2jycQFwIMVfpc4RrcCWkQDbcQrlIk8VCs+QboMgIKJLHzMZjZcXAkJ+Is4bwX3VFuxFooaLQXf5VGuoEXGkr4UGSAcBdqdTOLLVSgakVj2b3p5n3B82cgdPSab8Rux+57GfqLlxODbUxjTbBP0zzn8RkEi9Zp0P9FqeXN999vd59tf7z4f2+uqwnNhyYxxBIGO/S12tISKBenHJ9fQJu5MD9VLgAQK0R2R1ALbjDucYzXLhIFqyEucot7uSDe1k/3NnG326Erz4AbuenAed8A4eSeSTK9hji9DZx+fv96TW8L2YDu/6IVtWbcks3vlFFLDmMjz4bw8Fl7SHs9e0tEtHj8zs46KJIFtL6/RAShY8PpLN0hXHIkQZ/b11QT+aRcRVczjI4Ut9ia/gA6ExROybDacQmq+SSvhw8m/ewLPCQRmed2TZ04XNaSbIaQMjcliCmfDRYQ8nj39Tbnhc4R/jY5WzNFs2A2nS+F2XMx2HF4OUw5Z4cOMyuptJyZ+r1rn5eqBFnJJqe21EG6GkAqTLXVE+3gQB6NAd+Ilkehv9dAJz9GTj+Q9prBElaqQ4tF9acAuo8RLUZ1SKjvipsvUSx6aNlYZkk/UAO9eFpdOUVcDCjVeA9986fbXn28QfKeQIqwsRSwNmxESo59rH/1MQ9as48v++yErHQ7mUMr4ATcfTrpCyFhEJda1lxNi6bjULkoVT1HnZvp5cNsQ5EeWEB04Thr8iEkcW8QPH7x2SnfH7yTkLH7tzAjv/QyUlQumE517Sfw/UEsHCOXwzdoxBAAAYw8AAFBLAQIUABQACAgIAEGJRknl8M3aMQQAAGMPAAAHAAAAAAAAAAAAAAAAAAAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAAGYEAAAAAA==}, handlesAlerts=true, version=49.0.1, proxy={}, command_id=1, locationContextEnabled=true, takesElementScreenshot=true, device=desktop, firefox_profile=UEsDBBQACAAIAEGpRkkAAAAAAAAAA...}]
Session ID: 6b95569d-c5c8-a747-a76d-6ff79863630e
	at sun.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:126)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:93)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:42)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:284)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:168)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:331)
	at com.sun.proxy.$Proxy5.getText(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.getText(EventFiringWebDriver.java:381)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
	at com.sun.proxy.$Proxy6.getText(Unknown Source)
	at org.openqa.selenium.remote.server.handler.GetElementText.call(GetElementText.java:30)
	at org.openqa.selenium.remote.server.handler.GetElementText.call(GetElementText.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
17:10:17.908 WARN - Exception: The element reference is stale. Either the element is no longer attached to the DOM or the page has been refreshed.
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.0.0-beta4', revision: '3169782', time: '2016-09-29 10:29:23 -0700'
System info: host: 'ip-192-168-20-112.ec2.internal', ip: '192.168.20.112', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{raisesAccessibilityExceptions=false, loggingPrefs={driver=ALL, browser=ALL}, appBuildId=20160922113459, platform=MAC, requestOrigins={name=webdriverio, version=4.2.16, url=http://webdriver.io}, specificationLevel=0, acceptSslCerts=false, processId=60826, browserVersion=49.0.1, platformVersion=15.4.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, maxInstances=4, platformName=darwin, rotatable=false, firefoxOptions={args=[], profile=UEsDBBQACAgIAEGJRkkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51X227jNhB971cUfmqBmsht20X7lGZToMCiKdYI9pGgqJHFmCJZXqz47zukpPgmUU6eYikz5FzOmTkKDiw1FqqfFoXVLT4RxypIv4Vak4bJllkgoFghoVz88mPFpIOf//gh7D1L5tHGaOujSw1M+rp7Jmi0FXzGX4Fvtd2Q2ntDTC1cvVvGfxvm3FKCWvsaHW8+fTp2GwK2wEr8U4IH7qH8S1jn7zEWLgHdvA2n4eoG83qlvLa6Aeq4FcZTGxT1ookut1fjF3lWOILlUE/qQWoH49kM1qVuldSsxLsUW8fC1rr9XoNaYbVipcbdDQZlvIuX0UaXTM7UHrZea+kIWKst18ppeVju8/SdWCutsGoNNAXYVXp0+VwcOCfQymvEggUXsG4VBkq5Za7O+0qhNkQbUBRePVjFZGzmuxFUxbZ+C2r8shaK0ootPjPOAdsZFGbuEA6Ug/VutBJvnRLOSLaD8vH6avWPRuTE1t6NG+Or8kl9Fwr7666viMCL9PO3r+ixYIUO/vdCMrVZnGOuS4gyKemLw2LEOEVX+vPYXo3AcqMtaWvhQQrn8YD/grBTSIgw2AhPejYNqMPkIhayBZAMG4MEyEPNRdwGQ2pkjcGzaQuSRwYFG1u6OEk5dlsl1JBgsMFAFJa22j2jycQFwIMVfpc4RrcCWkQDbcQrlIk8VCs+QboMgIKJLHzMZjZcXAkJ+Is4bwX3VFuxFooaLQXf5VGuoEXGkr4UGSAcBdqdTOLLVSgakVj2b3p5n3B82cgdPSab8Rux+57GfqLlxODbUxjTbBP0zzn8RkEi9Zp0P9FqeXN999vd59tf7z4f2+uqwnNhyYxxBIGO/S12tISKBenHJ9fQJu5MD9VLgAQK0R2R1ALbjDucYzXLhIFqyEucot7uSDe1k/3NnG326Erz4AbuenAed8A4eSeSTK9hji9DZx+fv96TW8L2YDu/6IVtWbcks3vlFFLDmMjz4bw8Fl7SHs9e0tEtHj8zs46KJIFtL6/RAShY8PpLN0hXHIkQZ/b11QT+aRcRVczjI4Ut9ia/gA6ExROybDacQmq+SSvhw8m/ewLPCQRmed2TZ04XNaSbIaQMjcliCmfDRYQ8nj39Tbnhc4R/jY5WzNFs2A2nS+F2XMx2HF4OUw5Z4cOMyuptJyZ+r1rn5eqBFnJJqe21EG6GkAqTLXVE+3gQB6NAd+Ilkehv9dAJz9GTj+Q9prBElaqQ4tF9acAuo8RLUZ1SKjvipsvUSx6aNlYZkk/UAO9eFpdOUVcDCjVeA9986fbXn28QfKeQIqwsRSwNmxESo59rH/1MQ9as48v++yErHQ7mUMr4ATcfTrpCyFhEJda1lxNi6bjULkoVT1HnZvp5cNsQ5EeWEB04Thr8iEkcW8QPH7x2SnfH7yTkLH7tzAjv/QyUlQumE517Sfw/UEsHCOXwzdoxBAAAYw8AAFBLAQIUABQACAgIAEGJRknl8M3aMQQAAGMPAAAHAAAAAAAAAAAAAAAAAAAAAAB1c2VyLmpzUEsFBgAAAAABAAEANQAAAGYEAAAAAA==}, handlesAlerts=true, version=49.0.1, proxy={}, command_id=1, locationContextEnabled=true, takesElementScreenshot=true, device=desktop, firefox_profile=UEsDBBQACAAIAEGpRkkAAAAAAAAAA...}]
Session ID: 6b95569d-c5c8-a747-a76d-6ff79863630e
[Child 60827] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-m64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2052
[Child 60827] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-rel-m64-00000000000000000000/build/src/ipc/glue/MessageChannel.cpp, line 2052
17:10:18.034 INFO - Done: [delete session: 6cef811d-23e1-4f1a-ad05-b7ac40383f81]
17:26:40.059 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1fa30b89, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, maxInstances=4, firefox_profile=UEsDBBQACAAIAFOrRkkAAAAAAAAAA..., requestOrigins={name=webdriverio, version=4.2.16, url=http://webdriver.io}}]])
17:26:40.060 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1fa30b89, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, maxInstances=4, firefox_profile=UEsDBBQACAAIAFOrRkkAAAAAAAAAA..., requestOrigins={name=webdriverio, version=4.2.16, url=http://webdriver.io}}]
17:26:40.074 INFO - Attempting bi-dialect session, assuming Postel's Law holds true on the ...
```

**Comment by christian-bromann** [comment]
The stale element handler was not able to catch the problem when you query and element and refresh the website. This patch will fix the issue.

**Comment by si-mikey** [comment]
Unrelated to this but, how can I get this patch in my code? I did npm install webdriverio, but this change is not available?

**Comment by christian-bromann** [comment]
We haven't released this version yet.

**Comment by erm3nda** [comment]
@si-mikey For a quick workaround, just find again `element` and you'll be able to interact with it's new reference. What matters at all is the item elements, not the internal reference at all.

**Comment by si-mikey** [comment]
@erm3nda that really only works when your not using page objects, in my case I am using page objects.

**Comment by erm3nda** [comment]
Well, fix those page objects to be populated again in case of StaleElementReferenceException. No matter what you have, the fix is barely to locate the element again based on what it is, instead of references (webdriver object of any nature) cuz your reference no longer exists. Case you don't have ids, a reliable way is xpath, but any kind of locator method should work.
