### ISSUE TITLE
Issue with `node-fibers` on CI env (CircleCI)

### ISSUE THREAD

**Issue by simonwilbert** [webdriverio/webdriverio#1666]
## The problem

I'm unable to do a test run on circleci on 64-bit linux

## Environment

* WebdriverIO version:4.2.11
* Node.js version: 5.1.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner mode
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): 
    "wdio-cucumber-framework": "~0.2.4",
    "wdio-phantomjs-service": "~0.1.0",
    "wdio-selenium-standalone-service": "~0.0.6",
    "wdio-spec-reporter": "~0.0.3",
    "webdriverio": "~4.2.11"

## Details

Build fails to start on CircleCI

## Link to Selenium/WebdriverIO logs

npm run testdev

> e2etests@1.0.0 testdev /home/ubuntu/e2etests
> wdio wdio.dev.conf.js

## There is an issue with `node-fibers` ##
`/home/ubuntu/e2etests/node_modules/wdio-cucumber-framework/node_modules/wdio-sync/node_modules/fibers/bin/linux-x64-47/fibers.node` is missing.

Try running this to fix the issue: /opt/circleci/nodejs/v5.1.0/bin/node /home/ubuntu/e2etests/node_modules/wdio-cucumber-framework/node_modules/wdio-sync/node_modules/fibers/build
ERROR: Couldn't initialise framework "wdio-cucumber-framework".
Error: Missing binary. See message above.
    at Object.<anonymous> (/home/ubuntu/e2etests/node_modules/wdio-cucumber-framework/node_modules/wdio-sync/node_modules/fibers/fibers.js:20:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/ubuntu/e2etests/node_modules/wdio-cucumber-framework/node_modules/wdio-sync/node_modules/fibers/future.js:2:13)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

    at Runner.initialiseFramework (/home/ubuntu/e2etests/node_modules/webdriverio/build/lib/runner.js:372:27)
    at Runner._callee$ (/home/ubuntu/e2etests/node_modules/webdriverio/build/lib/runner.js:86:55)
    at tryCatch (/home/ubuntu/e2etests/node_modules/webdriverio/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/ubuntu/e2etests/node_modules/webdriverio/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/ubuntu/e2etests/node_modules/webdriverio/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/home/ubuntu/e2etests/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/ubuntu/e2etests/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/home/ubuntu/e2etests/node_modules/webdriverio/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at Runner.<anonymous> (/home/ubuntu/e2etests/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Runner.run (/home/ubuntu/e2etests/node_modules/webdriverio/build/lib/runner.js:255:29)

npm ERR! Linux 3.13.0-91-generic
npm ERR! argv "/opt/circleci/nodejs/v5.1.0/bin/node" "/opt/circleci/nodejs/v5.1.0/bin/npm" "run" "testdev"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! e2etests@1.0.0 testdev: `wdio wdio.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the e2etests@1.0.0 testdev script 'wdio wdio.dev.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the e2etests package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     wdio wdio.dev.conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls e2etests
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/e2etests/npm-debug.log
## Code To Reproduce Issue [ Good To Have ]

# circle.yml file is 

machine:
  node:
    version: 5.1.0
test:
  override:
    - npm run testdev

# npm dependancies
"dependencies": {
    "babel-preset-es2015": "~6.14.0",
    "babel-register": "~6.14.0",
    "chai": "~3.5.0",
    "cucumber": "~1.2.2",
    "fibers": "^1.0.15",
    "wdio-cucumber-framework": "~0.2.4",
    "wdio-phantomjs-service": "~0.1.0",
    "wdio-selenium-standalone-service": "~0.0.6",
    "wdio-spec-reporter": "~0.0.3",
    "webdriverio": "~4.2.11"
  },
  "devDependencies": {
    "eslint": "~3.4.0",
    "eslint-config-airbnb-base": "~5.0.3",
    "http-server": "~0.9.0",
    "selenium-standalone": "~5.6.2"
  },
  "scripts": {
    "test": "wdio wdio.conf.js",
    "testdev": "wdio wdio.dev.conf.js"
  },

**Comment by christian-bromann** [comment]
@simonwilbert please file this issue in the fibers project. Thanks!
