### ISSUE TITLE
Tests have stopped working with latest chrome Version 54.x

### ISSUE THREAD

**Issue by SachaMPS** [webdriverio/webdriverio#1674]
Hi there
i am very sorry if this isn't the right place for the issue. Actually i couldn't nail it down which component in the stack is causing the trouble - but we can't even get the most simple setup running with the latest version of chrome on OSX.

chromedriver 2.25
chrome Version 54.x 
selenium-server-standalone- 2.42.2 up to 2.53.1

I know this might not webdriver.io specific but actually it might be erveything and i whished i knew it better right now :) So sorry for any circumstances.

So what i am trying right now in a test folder:
Get the latest chromedriver, save and unpack it in the folder from:
http://chromedriver.storage.googleapis.com/index.html?path=2.25/

Get the latest selenium server standalone
```
$ curl -O http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.50.0.jar
```

Get webdriverio form npm
```
npm install webdriverio
```

And create a test.js file:
```
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'chrome',
        logLevel: 'verbose'
    }
};
var client = webdriverio.remote(options);

client
    .init()
    .url('http://www.google.com')
    .getTitle().then(function(title) {
        console.log('Title was: ' + title);
    })
    .end();
```

So now when I start the selenium-server via 
```
$ java -jar selenium-server-standalone-2.53.1.jar
```
And in another terminal window run the test.js file:
```
$ node test.js
```

**The follwoing exception is thrown most of the times and the browser quits or the browser does nothing**

```
Starting ChromeDriver 2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1) on port 21504
Only local connections are allowed.
[0.757][SEVERE]: Bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":18382,121229}}
16:50:32.192 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Air', ip: '192.168.178.20', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_60'
Driver info: driver.version: unknown
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
    at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
    at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
    at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:124)
    at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
    at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
    at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
    at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:79)
    at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:204)
    at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:166)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
    at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:132)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
    at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
    at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
    at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
    at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
    at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
    at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
    at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
    at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
    at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
    at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
    at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Air', ip: '192.168.178.20', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_60'
Driver info: driver.version: unknown
    at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:113)
    at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:97)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:103)
    ... 9 more
Caused by: org.openqa.selenium.SessionNotCreatedException: session not created exception
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":18382,121229}}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.0 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 849 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Air', ip: '192.168.178.20', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.chrome.ChromeDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170)
    at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:138)
    ... 14 more
16:50:32.201 WARN - Exception: session not created exception
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":18382,121229}}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.0 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 849 milliseconds
```

**Comment by SachaMPS** [comment]
Any help would be really appreciated!

**Comment by christian-bromann** [comment]
@SachaMPS Selenium can't find your chromedriver. The easiest solution is to put the chromedriver binary somewhere where you've defined your `PATH`, e.g. `/usr/bin` , so that if you call in your terminal `$ which chromedriver` it should find the binary.

Let me know if you have any further questions.

**Comment by SachaMPS** [comment]
@christian-bromann 
Added it to the path but still get the same error - and in the logs from my previous post it seems it found the chromedriver - at least it knew which version (Driver info: chromedriver=2.25.426935)

```
17:02:47.062 WARN - Exception: session not created exception
from unknown error: bad inspector message: {"method":"Page.loadEventFired","params":{"timestamp":19116,986672}}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.0 x86_64) (WARNING: The server did not provide any stacktrace information)
```

**Comment by SachaMPS** [comment]
Its definetly a chromedriver problem... Get the same failure in a pure python setup...

**Comment by SachaMPS** [comment]
For anyone interested and may stumble over this issue.
If you are using iTerm or may have changed your locale this might fix it:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1552#c27

**Comment by pebie** [comment]
Working for me @SachaMPS :)

**Comment by monolithed** [comment]
Yep, we have got the same issue. `export LC_ALL=en_US.UTF-8` works well

**Comment by krasimir** [comment]
We have the same issue.
chrome: 54
webdirverio: 3.3.0

It's interesting that the same issue exists with Firefox when we use:
```
"desiredCapabilities": {
  "browserName": "firefox"
}
```

**Comment by monolithed** [comment]
@krasimir, it's true, we have got the same problem with FF

**Comment by krasimir** [comment]
@monolithed is `LC_ALL=en_US.UTF-8` fixing your issue. Looks like it is working for your Chrome (as per your last comment) ;)

**Comment by SachaMPS** [comment]
@krasimir @monolithed  These may be two different problems as far as i know. I think the latest versions of Firefox may need another driver. Maybe your find some useful information here 
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by krasimir** [comment]
Just for the record: I fixed the issue on my machine by getting the latest version of `selenium-standalone` module and running `/node_modules/selenium-standalone/bin/selenium-standalone install` so I get the latest `chromedriver` and `geckodriver`. After that everything got back to normal.
