### ISSUE TITLE
browser.alertText() not working with error "no alert open"

### ISSUE THREAD

**Issue by prasanjitmohanty** [webdriverio/webdriverio#1679]
## The problem

browser.alertText() not working with error "no alert open". There is a valid alert present in the page.
Even tried wrapping the check inside waitUntil. Same issue exists for alertDismiss and alertAccept

browser.waitUntil(function() {
expect('message').to.be.equal(browser.alertText());
            browser.alertDismiss();
}, 15000);

## Environment

* WebdriverIO version:4.0.5
* Node.js version:v6.8.0
* [wdio testrunner]
* wdio testrunner, running synchronous  tests:
* Additional wdio packages - cucumber, browserstack
## Details

Error - no alert open
running
Error: no alert open
    at Object.alertText (C:\src\JMAutomation\node_modules\wdio-sync\build\index.
js:431:27)
    at World.<anonymous> (C:\src\JMAutomation\test\JMConsumerFeatures\step_defin
itions\signUp.steps.js:42:21)
    at C:\src\JMAutomation\node_modules\wdio-sync\build\index.js:678:26
    at World.executeSync (C:\src\JMAutomation\node_modules\wdio-sync\build\index
.js:676:12)
    at C:\src\JMAutomation\node_modules\wdio-sync\build\index.js:322:29
    at alertText() -     at C:\src\JMAutomation\node_modules\wdio-sync\build\at
Object.wait (C:\src\JMAutomation\node_modules\fibers\future.js:449:15)

**Comment by christian-bromann** [comment]
How does the alert look like? Are you sure you are on the right tab (window handle)? Note that only native browser alerts (opened by executing `window.alert` function) are supported. If you expect an alert box from e.g. bootstrap you need to check for its element. This is definitely not an issue with WebdriverIO, therefor I gonna close this but I am happy to help figuring out the issue.

**Comment by prasanjitmohanty** [comment]
Definitely a native alert as If I try do anything else without closing alert I get this error.

unexpected alert open: {Alert text : Thank you for subscribing to our mailing li
st}
running
Error: unexpected alert open: {Alert text : Thank you for subscribing to our mai
ling list}
    at Object.wait (C:\src\JMAutomation\node_modules\fibers\future.js:449:15)
    at Object.elementActive (C:\src\JMAutomation\node_modules\wdio-sync\build\in
dex.js:388:31)
    at Object.<anonymous> (C:\src\JMAutomation\test\JMConsumerFeatures\step_defi
nitions\signUp.steps.js:44:43)
    at C:\src\JMAutomation\node_modules\wdio-sync\build\index.js:322:29
    - - - - -
    at elementActive() - C:\src\JMAutomation\node_modules\wdio-sync\build\index.
js:375:37
    at elementActive() - C:\src\JMAutomation\node_modules\wdio-sync\build\index.
js:375:37
    at elementActive() - C:\src\JMAutomation\node_modules\wdio-sync\build\index.
js:375:37
    at elementActive() - C:\src\JMAutomation\node_modules\wdio-sync\build\index.
js:375:37
    at elementActive() - C:\src\JMAutomation\node_modules\wdio-sync\build\index.
js:375:37
    at elementActive() - C:\src\JMAutomation\node_modules\wdio-sync\build\index.
js:375:37
    at elementActive() - C:\src\JMAutomation\node_modules\wdio-sync\build\index.
js:375:37
    at waitUntil(<Function>, 15000) -     at C:\src\JMAutomation\node_modules\wd
io-sync\build\index.js:409:3
