### ISSUE TITLE
Webdriver io screenshot in v4

### ISSUE THREAD

**Issue by bertyhell** [webdriverio/webdriverio#1685]
## The problem

I'm trying to take a screenshot and send it as a response in a express node service http request. When i execute the saveScreenshot command i get back an object that doesn't seem to be a buffer.

## Environment

* WebdriverIO version: 4.2
* Node.js version: 6.4.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone mode

## Details

My current code:
```js
  console.log('Rendering screenshot for %s', url);

  let size = {
    width:  parseInt(req.query.width)  || 1024,
    height: parseInt(req.query.height) || 768
  };

  let client = webdriver
    .remote(config)
    .init();

  let errorHandler = (err: any) => {
    console.error(err.body.value.class);
    console.error(err.body.value.message);
    client.end();
  };

  client.on('error', errorHandler);
  client.timeouts('page load', 15000);
  client.timeouts('script', 10000);
  client.setViewportSize(size, true);
  client.url('http://www.github.com');
  let screenshot = client.saveScreenshot();
  client.end();
  res.set('Content-Type', 'image/png');
  res.end(<any>screenshot);
  console.log('done');

  // let screenshot = client.saveScreenshot().then(function(data: any) {
  //   res.set('Content-Type', 'image/png');
  //   res.end(data);
  //   console.log('done');
  // });
  // client.end();
```

I also tried an async approach (more like v3), but the then clause doesn't seem to be executed at all.

The output:
```
Listening on port 64100
Rendering screenshot for http://google.com

=======================================================================================
Selenium 2.0 / webdriver protocol bindings implementation with helper commands in nodejs.
For a complete list of commands, visit http://webdriver.io/api.html.
=======================================================================================

[13:09:35]  COMMAND	POST 	 "/wd/hub/session"
[13:09:35]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.3.0","name":"webdriverio"}}}
TypeError: First argument must be a string or Buffer
   at ServerResponse.OutgoingMessage.end (_http_outgoing.js:543:11)
   at ...\repos\screenshot-service-2\server\index.js:39:9
   at Layer.handle [as handle_request] (...\repos\screenshot-service-2\node_modules\express\lib\router\layer.js:95:5)
   at next (...\repos\screenshot-service-2\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (...\repos\screenshot-service-2\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (...\repos\screenshot-service-2\node_modules\express\lib\router\layer.js:95:5)
   at ...\repos\screenshot-service-2\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (...\repos\screenshot-service-2\node_modules\express\lib\router\index.js:330:12)
   at next (...\repos\screenshot-service-2\node_modules\express\lib\router\index.js:271:10)
   at expressInit (...\repos\screenshot-service-2\node_modules\express\lib\middleware\init.js:33:5)
```

**Comment by christian-bromann** [comment]
It's a base64 buffer, see https://github.com/webdriverio/webdriverio/blob/master/lib/commands/saveScreenshot.js#L36-L42. 
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by bertyhell** [comment]
```js
  client.on('error', errorHandler);
  client.timeouts('page load', 15000);
  client.timeouts('script', 10000);
  client.setViewportSize(size, true);
  client.url('http://www.github.com');
  client.screenshot().then((data: any) => {
    console.log('Screenshot promise resolved----------------');
    res.set('Content-Type', 'image/png');
    res.end(new Buffer(data.value, 'base64'));
    console.log('done');
  }).end();
```

The issue is that if i implement this using the async code (the one you linked me), the screenshot promise never gets resolved.

If i put breapoints on line:
` client.screenshot().then((data: any) => {'
and
`    console.log('Screenshot promise resolved----------------');`

Only the first one gets hit. The second one never gets hit.

**Comment by christian-bromann** [comment]
@bertyhell because you can't stream the screenshot into the express response. Also you are using all commands as if they were synchronous but they aren't.

**Comment by bertyhell** [comment]
So this section is only talking about the test runner part of webdriver.io and not about the standalone part?
http://webdriver.io/guide/getstarted/v4.html#It’s-all-synchronous

Then this code should get to the console log, right? But it still doesn't.
```js
  client
      .on('error', errorHandler)
      .timeouts('page load', 15000)
      .timeouts('script', 10000)
      .setViewportSize(size, true)
      .url('http://www.github.com')
      .screenshot().then((data: any) => {
        console.log('Screenshot promise resolved----------------');
      })
      .end();
```

**Comment by christian-bromann** [comment]
> So this section is only talking about the test runner part of webdriver.io and not about the standalone part?

Yes: `handles async in the wdio testrunner now`

> Then this code should get to the console log, right? But it still doesn't.

Probably because it fails before somewhere and you haven't catched the error, do:
```js
client
      .on('error', errorHandler)
      .timeouts('page load', 15000)
      .timeouts('script', 10000)
      .setViewportSize(size, true)
      .url('http://www.github.com')
      .screenshot().then((data: any) => {
        console.log('Screenshot promise resolved----------------');
      })
      .end().catch((e) => console.log(e))
```

**Comment by bertyhell** [comment]
This also doesn't output anything

I made a minimal (non)working example without express
```js
let config = {
    host: 'localhost',
    desiredCapabilities: {
        browserName: 'chrome'
    }
};
console.log('getting screenshot');
webdriver
    .remote(config)
    .init()
    .on('error', (error) => console.log('error occurred: ', error))
    .timeouts('page load', 15000)
    .timeouts('script', 10000)
    .setViewportSize({ width: 1024, height: 768 }, true)
    .url('http://www.google.com')
    .screenshot().then((data) => {
        console.log('Received screenshot data');
    })
    .end()
    .catch((e) => console.log(e));
```

The console output:
```js
getting screenshot
```

**Comment by christian-bromann** [comment]
Do you see any errors in the selenium server logs?

**Comment by bertyhell** [comment]
It seems to be an issue with the setup of selenium and webdriverio on my development machine. (Windows 10 x64). It was setup inside a vagrant VM and that might be causing the issue.

When i deployed my code to our amazon ec2 instance (Ubuntu) everything works as expected.

Thank you for the help though.

In the future I'll use the chat like you suggested
