### ISSUE TITLE
browser.switchTab() is not switching command to new tab

### ISSUE THREAD

**Issue by prasanjitmohanty** [webdriverio/webdriverio#1720]
## The problem

browser.switchTab() is not switching command to new tab. Not able to find any element in the new tab. The execution shows it successfully switches to new tab but the command still points to first tab.

```
let handles = browser.windowHandles();
       
console.log('TabId 1:'+browser.getCurrentTabId());
browser.switchTab(handles[1]).pause(2000);
console.log('TabId 2:'+browser.getCurrentTabId());
```

output :
TabId 1:CDwindow-842b73b5-9875-415d-b5da-203d54f98f83
TabId 2:CDwindow-842b73b5-9875-415d-b5da-203d54f98f83

## Environment

* WebdriverIO version:4.4
* Node.js version:6.9.1
* [wdio testrunner]
* if wdio testrunner, synchronous

**Comment by christian-bromann** [comment]
Have you tried

```js
let handles = browser.windowHandles();
       
console.log('TabId 1:'+browser.getCurrentTabId());
browser.switchTab(handles[0]).pause(2000);
console.log('TabId 2:'+browser.getCurrentTabId());
```

**Comment by christian-bromann** [comment]
Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have any further questions or issues.

**Comment by prasanjitmohanty** [comment]
Still no changes. SwitchTab() not switching the context. I am currently getting the link href and then opening it as a new window.

**Comment by prasanjitmohanty** [comment]
[switchtab_log.txt](https://github.com/webdriverio/webdriverio/files/627741/switchtab_log.txt)

**Comment by prasanjitmohanty** [comment]
[switchtab_log.txt](https://github.com/webdriverio/webdriverio/files/627771/switchtab_log.txt)

**Comment by prasanjitmohanty** [comment]
[switchtab_log.txt](https://github.com/webdriverio/webdriverio/files/627779/switchtab_log.txt)

**Comment by christian-bromann** [comment]
@prasanjitmohanty as mentioned on Gitter, you not switched the tab because you applied the same window handle you currently on, see logs:

```
2016-12-2 17:8:22:709 REQUEST [2016-12-2 17:8:22:709] GET /session/3ca27b6400a9d6fe21734678bbd93dbc4f7541c8/window_handles {}
2016-12-2 17:8:22:716 RESPONSE {"state":"success","sessionId":"3ca27b6400a9d6fe21734678bbd93dbc4f7541c8","hCode":11732073,"value":["CDwindow-f0b11f84-eed4-4417-a2c8-26feaf56e485","CDwindow-39dc845a-a4f7-45b6-ab4c-23aa99f9b16a"],"class":"org.openqa.selenium.remote.Response","status":0}

2016-12-2 17:8:22:762 REQUEST [2016-12-2 17:8:22:762] GET /session/3ca27b6400a9d6fe21734678bbd93dbc4f7541c8/window_handle {}
2016-12-2 17:8:22:769 RESPONSE {"state":"success","sessionId":"3ca27b6400a9d6fe21734678bbd93dbc4f7541c8","hCode":8932417,"value":"CDwindow-f0b11f84-eed4-4417-a2c8-26feaf56e485","class":"org.openqa.selenium.remote.Response","status":0}

2016-12-2 17:8:22:801 REQUEST [2016-12-2 17:8:22:801] GET /session/3ca27b6400a9d6fe21734678bbd93dbc4f7541c8/window_handles {}
2016-12-2 17:8:22:809 RESPONSE {"state":"success","sessionId":"3ca27b6400a9d6fe21734678bbd93dbc4f7541c8","hCode":18408770,"value":["CDwindow-f0b11f84-eed4-4417-a2c8-26feaf56e485","CDwindow-39dc845a-a4f7-45b6-ab4c-23aa99f9b16a"],"class":"org.openqa.selenium.remote.Response","status":0}

2016-12-2 17:8:22:838 REQUEST [2016-12-2 17:8:22:838] POST /session/3ca27b6400a9d6fe21734678bbd93dbc4f7541c8/window {"name":"CDwindow-f0b11f84-eed4-4417-a2c8-26feaf56e485"}
2016-12-2 17:8:22:861 RESPONSE {"state":"success","sessionId":"3ca27b6400a9d6fe21734678bbd93dbc4f7541c8","hCode":6464412,"value":null,"class":"org.openqa.selenium.remote.Response","status":0}

2016-12-2 17:8:24:923 REQUEST [2016-12-2 17:8:24:923] GET /session/3ca27b6400a9d6fe21734678bbd93dbc4f7541c8/window_handle {}
2016-12-2 17:8:24:930 RESPONSE {"state":"success","sessionId":"3ca27b6400a9d6fe21734678bbd93dbc4f7541c8","hCode":13637973,"value":"CDwindow-f0b11f84-eed4-4417-a2c8-26feaf56e485","class":"org.openqa.selenium.remote.Response","status":0}
```

**Comment by adiwon9555** [comment]
I used this and it worked for all browsers:- Try this code:-

   `var tab_handles =await driver.getAllWindowHandles();
    let number_of_tabs = tab_handles.length;
    let new_tab_index = number_of_tabs-1;
    await driver.switchTo().window(tab_handles[new_tab_index]); ` 

That was using await instead of Promise for async functions.

If you want to use Promise then try this code:-
    `driver.getAllWindowHandles().then((tab_handles)=>{`
    let number_of_tabs = tab_handles.length;
    let new_tab_index = number_of_tabs-1;
    driver.switchTo().window(tab_handles[new_tab_index]);
    });`

**Comment by lttrung112** [comment]
@christian-bromann 
I have got a failure when running **browser.getTabIds(); API in IE11**, could you please have some advice?
Script:
    browser.url('http://webdriver.io');
    var tabIds = browser.getTabIds();
    console.log(tabIds);
-------------
Error:
running internet explorer (v11)
Error: Remote end send an unknown status code.
-------------------------
Log from Hub:
-------------------
C:\GRID>java -jar selenium-server-standalone-3.11.0.jar -role hub
18:27:04.900 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision: 'e59cfb3'
18:27:04.903 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
2018-07-30 18:27:05.264:INFO::main: Logging initialized @617ms to org.seleniumhq.jetty9.util.log.StdErrLog
18:27:05.417 INFO [Hub.start] - Selenium Grid hub is up and running
18:27:05.417 INFO [Hub.start] - Nodes should register to http://10.192.8.5:4444/grid/register/
18:27:05.418 INFO [Hub.start] - Clients should connect to http://10.192.8.5:4444/wd/hub
18:27:10.052 INFO [DefaultGridRegistry.add] - Registered a node http://10.192.8.5:7777
18:27:27.545 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: internet explorer, handlesAlerts: true, javascriptEnabled: true, locationC
ontextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 1, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true, vers
ion: 11}
18:27:27.549 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {webdriver.ie.driver=C:/Program Files (x86)/Internet Explorer/iexplore.exe, server:CONFIG_UUID=d
37349c2-3ae3-4564-9ab0-9e8c120be56a, seleniumProtocol=WebDriver, browserName=internet explorer, ignoreProtectedModeSettings=true, maxInstances=10, platformName=WINDOWS, version=11, plat
form=WINDOWS}


Log from Node:
------------------
C:\GRID>java -Dwebdriver.ie.driver="C:/GRID/IEDriverServer.exe" -jar selenium-server-standalone-3.11.0.jar -role node -hub http://10.192.8.5:4444/grid/register -nodeConfig "C:/GRID/node
config_IE11_local.json"
18:27:09.523 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision: 'e59cfb3'
18:27:09.525 INFO [GridLauncherV3$3.launch] - Launching a Selenium Grid node on port 7777
2018-07-30 18:27:09.657:INFO::main: Logging initialized @419ms to org.seleniumhq.jetty9.util.log.StdErrLog
18:27:09.777 INFO [SeleniumServer.boot] - Welcome to Selenium for Workgroups....
18:27:09.777 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 7777
18:27:09.778 INFO [GridLauncherV3$3.launch] - Selenium Grid node is up and ready to register to the hub
18:27:09.782 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
18:27:09.782 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://10.192.8.5:4444/grid/register
18:27:10.059 INFO [SelfRegisteringRemote.registerToHub] - Updating the node configuration from the hub
18:27:10.099 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
18:27:27.662 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: internet explorer, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: tr
ue, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 1, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true, version: 11}
18:27:27.664 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.ie.InternetExplorerDr
iverService)
Started InternetExplorerDriver server (32-bit)
3.8.0.0
Listening on port 9497
Only local connections are allowed
18:27:29.768 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
18:27:29.787 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session e9c2ef50-4fd0-4855-a8cd-8d08430029b0 (org.openqa.selenium.ie.InternetExplorerDriverService)
18:27:33.677 INFO [ActiveSessions$1.onStop] - Removing session e9c2ef50-4fd0-4855-a8cd-8d08430029b0 (org.openqa.selenium.ie.InternetExplorerDriverService)
18:27:43.213 INFO [OsProcess.destroy] - Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
        at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
        at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:181)
        at org.openqa.selenium.os.OsProcess.destroy(OsProcess.java:135)
        at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
        at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:222)
        at org.openqa.selenium.remote.server.ServicedSession.stop(ServicedSession.java:83)
        at org.openqa.selenium.remote.server.ActiveSessions.lambda$new$1(ActiveSessions.java:55)
        at com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1810)
        at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3457)
        at com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3433)
        at com.google.common.cache.LocalCache$Segment.remove(LocalCache.java:3067)
        at com.google.common.cache.LocalCache.remove(LocalCache.java:4228)
        at com.google.common.cache.LocalCache$LocalManualCache.invalidate(LocalCache.java:4892)
        at org.openqa.selenium.remote.server.ActiveSessions.invalidate(ActiveSessions.java:102)
        at org.openqa.selenium.remote.server.WebDriverServlet.handle(WebDriverServlet.java:275)
        at org.openqa.selenium.remote.server.WebDriverServlet.doDelete(WebDriverServlet.java:144)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
        at org.openqa.selenium.remote.server.WebDriverServlet.service(WebDriverServlet.java:125)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Unknown Source)
18:27:43.217 ERROR [OsProcess.destroy] - Unable to kill process java.lang.ProcessImpl@3ab97803

**Comment by vipgr** [comment]
getting error ,  "browser.switchTab is not a function" ,below is my code , am not sure why it was throwing this error , can anyone help me out please


describe("Verify webdriver university contact submission correctly", function submitContactUS() {
    it("loading the webdriveruniversity contact page from home page", function () {
        browser.url('http://www.webdriveruniversity.com/');
        const title = browser.getTitle();
        console.log('Title for the home page :- ' + title);
        var contactLink = $('#contact-us');
        contactLink.click();
        var tabIds = browser.getTabIDs();
        console.log(tabIds);
        browser.switchTab(tabIds);
        const newContactTitle = browser.getTitle();
        console.log('Title for the Contact page :- ' + newContactTitle);
        var firstName = $('input[name = "first_name"]');
        firstName.setValue('QATEst');
        browser.pause(3000);

    })

})

**Comment by adewharlay** [comment]
const switchTab = await browser.getWindowHandles();
        await browser.switchToWindow(switchTab[1]);
Depending on the tab location input the array value
