### ISSUE TITLE
waitForVisible - error isn't thrown when element doesn't exist

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1752]
## The problem

```js
{
    waitforTimeout: 30 * 1000,

    mochaOpts: {
       'timeout': 15 * (60 * 1000),
    }
}
```

```js
browser.waitForVisible('unknown_element');

// or

browser.waitForVisible('unknown_element', 2000);
```

```
[17:42:24]  COMMAND	POST 	 "/wd/hub/session/c8f4c900-9166-41ad-b11d-3f885fee845e/elements"
[17:42:24]  DATA		{"using":"css selector","value":"foo"}
[17:57:24]  COMMAND	DELETE 	 "/wd/hub/session/c8f4c900-9166-41ad-b11d-3f885fee845e"
[17:57:24]  DATA		{}
(node:55105) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]
(node:55105) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[17:57:25]  RESULT		null
------------------------------------------------------------------
[chrome #0-0] Session ID: c8f4c900-9166-41ad-b11d-3f885fee845e
[chrome #0-0] Spec: /Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/cases/addressbook/MAIL-50877/TESTMAIL-33934.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0]   TESTMAIL-33934
[chrome #0-0]       1) Адресная книга. Общая АК домена. Проверка, что контакты сразу удаляются из групп без обновления страницы.
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 failing (15m, 8s)
[chrome #0-0]
[chrome #0-0] 1) TESTMAIL-33934 Адресная книга. Общая АК домена. Проверка, что контакты сразу удаляются из групп без обновления страницы.:
[chrome #0-0] timeout of 900000ms exceeded. Ensure the done() callback is being called in this test.
[chrome #0-0] Error: timeout of 900000ms exceeded. Ensure the done() callback is being called in this test.
[chrome #0-0]     at Timeout.<anonymous> (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/mocha/lib/runnable.js:232:19)
[chrome #0-0]     at ontimeout (timers.js:365:14)
[chrome #0-0]     at tryOnTimeout (timers.js:237:5)
[chrome #0-0]     at Timer.listOnTimeout (timers.js:207:5)
[chrome #0-0]
```

## Environment

* WebdriverIO version: latest
* Node.js version: 7
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): testrunner

I expect to see something like **The element "unknown_element" still not visible after 30000ms** rather than **timeout of 900000ms exceeded**

**Comment by christian-bromann** [comment]
Not reproducible, see https://gist.github.com/christian-bromann/b54e158b9ebfa0f3a42bda6732f14a80

**Comment by monolithed** [comment]
@christian-bromann, could you try with Chrome?

**Comment by christian-bromann** [comment]
same result

**Comment by monolithed** [comment]
it is being a "floating" bug. I could not reproduce it today.

**Comment by monolithed** [comment]
@christian-bromann, see a reproducible example:
[1752.zip](https://github.com/webdriverio/webdriverio/files/639093/1752.zip)

The problem is being solved by removing `screenshotPath`!

**Comment by monolithed** [comment]
@christian-bromann, see the screencast http://g.recordit.co/67xMC8JcyX.gif ))
