### ISSUE TITLE
Webdriver crashing 

### ISSUE THREAD

**Issue by dimirey** [webdriverio/webdriverio#1770]
## The problem

When running an automated suite the suite is unable to finish due to the webdriver crashing. After the webdriver crashes the remaining tests time out.

Stacktrace:

```
/Users/dimitrireynaga/git/cucumber_js_automation/node_modules/webdriverio/build/lib/utils/ReporterStats.js:419
            if (runner.err && runner.err.message.indexOf(message) > -1) {
                                                ^

TypeError: Cannot read property 'indexOf' of undefined
    at ReporterStats.testFail (/Users/dimitrireynaga/git/cucumber_js_automation/node_modules/webdriverio/build/lib/utils/ReporterStats.js:419:49)
    at BaseReporter.<anonymous> (/Users/dimitrireynaga/git/cucumber_js_automation/node_modules/webdriverio/build/lib/utils/BaseReporter.js:159:25)
    at emitOne (events.js:96:13)
    at BaseReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (/Users/dimitrireynaga/git/cucumber_js_automation/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)
    at Launcher.messageHandler (/Users/dimitrireynaga/git/cucumber_js_automation/node_modules/webdriverio/build/lib/launcher.js:609:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
Error: channel closed
    at process.target.send (internal/child_process.js:540:16)
    at /Users/dimitrireynaga/git/cucumber_js_automation/node_modules/webdriverio/build/lib/runner.js:410:25
    at execHook (/Users/dimitrireynaga/git/cucumber_js_automation/node_modules/wdio-sync/build/index.js:259:35)
Error: channel closed
    at Object.wait (/Users/dimitrireynaga/git/cucumber_js_automation/node_modules/fibers/future.js:449:15)
    at Object.execute (/Users/dimitrireynaga/git/cucumber_js_automation/node_modules/wdio-sync/build/index.js:394:31)
    at SauceService.beforeScenario (/Users/dimitrireynaga/git/cucumber_js_automation/node_modules/wdio-sauce-service/build/sauce-service.js:98:28)
    at execHook (/Users/dimitrireynaga/git/cucumber_js_automation/node_modules/wdio-sync/build/index.js:259:35)
    - - - - -
```

## Environment

* WebdriverIO version: webdriverio@4.5.0
* Node.js version: v6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): cucumber, spec

**Comment by alek75** [comment]
It is the same issue i wrote in the  Gitter Chat. Couple of things to add:
1. For my automation i am using Windows Server 2012 and TFS build server
2. Before the update (4.4 version) I have issues to run tests against Firefox (all latest versions, geckodriver set up correctly). It crashed in AfterScenario (I am using Cucumber 1.3.1 abd latest wdio-cucumber) but i did not have ant code there. I thought that it might have an incompatibility cucumber version and wdio-cucumber version. Tried a lot of combinations, none of them worked for firefox
3. On version 4.5 Chrome and Firefox crashing the same way. I've gave a try on BrowserStack - same situation
4. After downgrade to 4.4 only firefox continue to crash this way (very strange)
