### ISSUE TITLE
TypeError: seleniumStack.orgStatusMessage.match is not a function

### ISSUE THREAD

**Issue by jesusMT** [webdriverio/webdriverio#1793]
## The problem
I'm trying to test an iOS app and I'm getting this error:

     TypeError: seleniumStack.orgStatusMessage.match is not a function
         at new ErrorHandler (/Users/jumz/proyectos/woody-test/node_modules/orchard-webdriverio-plugin/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:71:86)
         at new RuntimeError (/Users/jumz/proyectos/woody-test/node_modules/orchard-webdriverio-plugin/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:136:12)
         at Request._callback (/Users/jumz/proyectos/woody-test/node_modules/orchard-webdriverio-plugin/node_modules/webdriverio/build/lib/utils/RequestHandler.js:269:39)
         at Request.self.callback (/Users/jumz/proyectos/woody-test/node_modules/orchard-webdriverio-plugin/node_modules/request/request.js:187:22)
         at emitTwo (events.js:106:13)
         at Request.emit (events.js:191:7)
         at Request.<anonymous> (/Users/jumz/proyectos/woody-test/node_modules/orchard-webdriverio-plugin/node_modules/request/request.js:1044:10)
         at emitOne (events.js:96:13)
         at Request.emit (events.js:188:7)
         at IncomingMessage.<anonymous> (/Users/jumz/proyectos/woody-test/node_modules/orchard-webdriverio-plugin/node_modules/request/request.js:965:12)

## Environment
* WebdriverIO version: 4.4.0
* Node.js version: 6.9.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: synchronous

## Details
When I run a test for Android, it's all ok but when I run the same test for iOS I have the error.
In ErrorHandler.js, I print the value of seleniumStack with console.log(seleniumStack) and it returns a value that should not:
    { status: 27,
    type: 'NoAlertOpenError',
    message: 'An attempt was made to operate on a modal dialog when one was not open.',
    orgStatusMessage: {} }

The step that fails is in accesoLogin.feature(line:9). Previously in accesoLogin.feature(line:5), the same step is running correctly.

## Code To Reproduce Issue [ Good To Have ]
https://gist.github.com/jesusMT/8f21614677e38de39dd4f932d224fa18

**Comment by christian-bromann** [comment]
Thanks for reporting @jesusMT. This looks indeed like an issue we could fix.
