### ISSUE TITLE
Show more informative stack trace 

### ISSUE THREAD

**Issue by monolithed** [webdriverio/webdriverio#1842]
## The problem

**test.js**

```js
let page = require('./page');

describe('test', () => {
	it('test', () => page());
});
```

**page.js**

```js
module.exports = () => {
	browser.url('https://e.mail.ru/login');
	browser.alertText();
};
```

## Actual

```
[chrome #0-0] Session ID: ec6a556d-0074-4b8d-9f28-537090c1fd7d
[chrome #0-0] Spec: /test.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0]   test
[chrome #0-0]
[chrome #0-0]   test
[chrome #0-0]       1) test
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 failing (6s)
[chrome #0-0]
[chrome #0-0] 1) test test:
[chrome #0-0] Timeout of 3000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
[chrome #0-0] Error: Timeout of 3000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
[chrome #0-0]     at Timeout.<anonymous> (/node_modules/mocha/lib/runnable.js:232:19)
[chrome #0-0]     at ontimeout (timers.js:365:14)
[chrome #0-0]     at tryOnTimeout (timers.js:237:5)
[chrome #0-0]     at Timer.listOnTimeout (timers.js:207:5)
[chrome #0-0]
```

## Expected

```
[chrome #0-0] Session ID: ec6a556d-0074-4b8d-9f28-537090c1fd7d
[chrome #0-0] Spec: /tests/1788/test.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0]   test
[chrome #0-0]
[chrome #0-0]   test
[chrome #0-0]       1) test
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 failing (6s)
[chrome #0-0]
[chrome #0-0] 1) test test:
[chrome #0-0] Something about its real error and place
[chrome #0-0]     at module.exports (/page.js:3:8) 
[chrome #0-0]     at Context.it (/test.js:4:19)
```

## assert

```js
assert(0, 'Something went wrong');
```

```
[chrome #0-0] Something went wrong
[chrome #0-0] AssertionError: Something went wrong
[chrome #0-0]     at module.exports (/page.js:6:2)
[chrome #0-0]     at Context.it (/test.js:4:19)
[chrome #0-0]
```

## throw

```js
throw new Error('Something went wrong');
```

```
[chrome #0-0] Something went wrong
[chrome #0-0]     at module.exports (/page.js:3:8) 
[chrome #0-0]     at Context.it (/test.js:4:19)
[chrome #0-0]
```

## webdriverio api

```js
browser.alertText();
```

```
[chrome #0-0]     at Timeout.<anonymous> (/tests/1788/node_modules/mocha/lib/runnable.js:232:19)
[chrome #0-0]     at ontimeout (timers.js:365:14)
[chrome #0-0]     at tryOnTimeout (timers.js:237:5)
[chrome #0-0]     at Timer.listOnTimeout (timers.js:207:5)
```

## Environment

* WebdriverIO version: 4.0.0-4.6.2
* Selenium version: any
* Node.js version: 6-7
* Mocha version: 2-3

## Code To Reproduce Issue

[__test__.zip](https://github.com/webdriverio/webdriverio/files/729282/__test__.zip)

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-sync#45
