### ISSUE TITLE
Multiremote configuration stops wdio visual regression service from recognizing compare method in wdio.conf.js

### ISSUE THREAD

**Issue by ohheyitsjeffrey** [webdriverio/webdriverio#1858]
## The problem

When wdio.conf.js is configured for multiremote, it no longer recognizes visual regression service's compare in wdio.conf.js

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.9.4
* wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-visual-regression-service

## Details

I am trying to set up both visual regression service, and multiremote for various tests.  I can get each to work, but when i modify the capabilities key as advised in the documentation, it stops recognizing the visual regression compare method.

Error Thrown

```Error: Please provide a visualRegression configuration with a compare method in your wdio-conf.js!
    at VisualRegressionLauncher.validateConfig (/media/morespace/Codes/webdriver_examples/wd1/node_modules/wdio-visual-regression-service/lib/VisualRegressionLauncher.js:210:15)
    at VisualRegressionLauncher.before$ (/media/morespace/Codes/webdriver_examples/wd1/node_modules/wdio-visual-regression-service/lib/VisualRegressionLauncher.js:83:20)
    at tryCatch (/media/morespace/Codes/webdriver_examples/wd1/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/media/morespace/Codes/webdriver_examples/wd1/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/media/morespace/Codes/webdriver_examples/wd1/node_modules/regenerator-runtime/runtime.js:116:21)
    at tryCatch (/media/morespace/Codes/webdriver_examples/wd1/node_modules/regenerator-runtime/runtime.js:64:40)
    at invoke (/media/morespace/Codes/webdriver_examples/wd1/node_modules/regenerator-runtime/runtime.js:154:20)
    at /media/morespace/Codes/webdriver_examples/wd1/node_modules/regenerator-runtime/runtime.js:201:11
    at callInvokeWithMethodAndArg (/media/morespace/Codes/webdriver_examples/wd1/node_modules/regenerator-runtime/runtime.js:200:16)
    at AsyncIterator.enqueue (/media/morespace/Codes/webdriver_examples/wd1/node_modules/regenerator-runtime/runtime.js:223:13)
## Code To Reproduce Issue [ Good To Have ]


````
wdio.conf.js settings 

```
exports.config: {
//...
  capabilities:  {
        browserA: {
            desiredCapabilities: {
                browserName: 'chrome',
                    maxInstances: 5
            }
        },
        browserB: {
            desiredCapabilities: {
                browserName: 'chrome',
                maxInstances: 5
            }
        }
    },

// ...
  services: ['visual-regression'],

  visualRegression: {
    compare: new VisualRegressionCompare.LocalCompare({
      referenceName: getScreenshotName(path.join(process.cwd(), 'screenshots/reference')),
      screenshotName: getScreenshotName(path.join(process.cwd(), 'screenshots/taken')),
      diffName: getScreenshotName(path.join(process.cwd(), 'screenshots/diff')),
    }),
    viewportChangePause: 500,
    widths: [1280, 1600],
    // orientations: ['landscape', 'portrait'],
    orientations: ['landscape'],

  },

```

**Comment by christian-bromann** [comment]
There is no reason to run visual regression tests in multiremote mode. Multiremote tests are for testing chat applications where multiple actors are required. Besides this is something that the visual regression service has to support.

**Comment by kontrollanten** [comment]
@christian-bromann I think visual regression can be useful when testing video streams with multiremote. I would be really happy if support for visual regression could be supported in multiremote.
