### ISSUE TITLE
Errors shown in test output

### ISSUE THREAD

**Issue by gavin-johnson84** [webdriverio/webdriverio#1870]
## The problem

I'm receiving the following errors after running a test, I'm unsure wherever or not it's a setup issue or a code problem:
```
> wdio wdio.conf.js 

ERROR: Cannot find module 'tap'
chrome
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gavin/path/to/modules/node_modules/asn1/tst/ber/writer.test.js:3:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

ERROR: Cannot find module 'tap'
chrome
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gavin/path/to/modules/node_modules/asn1/tst/ber/reader.test.js:3:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

------------------------------------------------------------------
[chrome #0-2] Session ID: b918dfb6-9253-41ce-aed0-defafc54e417
[chrome #0-2] Spec: /Users/gavin/path/to/test/general-settings.test.js
[chrome #0-2] Running: chrome
[chrome #0-2]
[chrome #0-2]   webdriver.io page
[chrome #0-2]
[chrome #0-2]   webdriver.io page
[chrome #0-2]       ✓ should have the right title - the fancy generator way
[chrome #0-2]
[chrome #0-2]
[chrome #0-2] 1 passing (4s)
[chrome #0-2]
```
I've installed the tap module, this has removed the errors above, but I don't see why I need to install another test runner in order to remove the errors displayed.

## Environment

* WebdriverIO version: `4.6.2`
* Node.js version: `v7.2.1`
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): `wdio testrunner`
* if wdio testrunner, running synchronous or asynchronous tests: `synchronous`
* Additional wdio packages used (if applicable):
`"wdio-browserstack-service": "^0.1.4"`
`"wdio-mocha-framework": "^0.5.8"`
`"wdio-selenium-standalone-service": "^0.0.8"`
`"wdio-spec-reporter": "^0.0.5"`

## Details

I'm also using `"mocha: ^3.2.0"`

The packages listed in environment and details is pretty much the contents in my `package.json`

## Link to Selenium/WebdriverIO logs

Contents of my `npm-debug.log`
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@3.10.9
3 info using node@v7.2.1
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle e2e@0.0.1~pretest: e2e@0.0.1
6 silly lifecycle e2e@0.0.1~pretest: no script for pretest, continuing
7 info lifecycle e2e@0.0.1~test: e2e@0.0.1
8 verbose lifecycle e2e@0.0.1~test: unsafe-perm in lifecycle true
9 verbose lifecycle e2e@0.0.1~test: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/gavin/Code/triptease/test-drive/e2e/node_modules/.bin:/usr/local/Cellar/node/7.2.1/bin:/Users/gavin/.selenium:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle e2e@0.0.1~test: CWD: /Users/gavin/Code/directory-here/directory-here/directory-here
11 silly lifecycle e2e@0.0.1~test: Args: [ '-c', 'wdio wdio.conf.js ' ]
12 silly lifecycle e2e@0.0.1~test: Returned: code: 1  signal: null
13 info lifecycle e2e@0.0.1~test: Failed to exec test script
14 verbose stack Error: e2e@0.0.1 test: `wdio wdio.conf.js `
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid e2e@0.0.1
16 verbose cwd /Users/gavin/Code/directory-here/directory-here/directory-here
17 error Darwin 16.4.0
18 error argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "run" "test"
19 error node v7.2.1
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error e2e@0.0.1 test: `wdio wdio.conf.js `
22 error Exit status 1
23 error Failed at the e2e@0.0.1 test script 'wdio wdio.conf.js '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the e2e package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     wdio wdio.conf.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs e2e
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls e2e
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## Code To Reproduce Issue [ Good To Have ]

Please see my `wdio-conf.js` file below for reference:
```
exports.config = {
    
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called. Notice that, if you are calling `wdio` from an
    // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
    // directory is where your package.json resides, so `wdio` will be called from there.
    //
    specs: [
        '**/*.test.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome'
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // By default WebdriverIO commands are executed in a synchronous way using
    // the wdio-sync package. If you still want to run your tests in an async way
    // e.g. using promises you can set the sync option to false.
    sync: true,
    //
    // Level of logging verbosity: silent | verbose | command | data | result | error
    logLevel: 'silent',
    //
    // Enables colors for log output.
    coloredLogs: true,
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Saves a screenshot to a given path if a command fails.
    // screenshotPath: './errorShots/',
    //
    // Set a base URL in order to shorten url command calls. If your url parameter starts
    // with "/", then the base url gets prepended.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Initialize the browser instance with a WebdriverIO plugin. The object should have the
    // plugin name as key and the desired plugin options as properties. Make sure you have
    // the plugin installed before running any tests. The following plugins are currently
    // available:
    // WebdriverCSS: https://github.com/webdriverio/webdrivercss
    // WebdriverRTC: https://github.com/webdriverio/webdriverrtc
    // Browserevent: https://github.com/webdriverio/browserevent
    // plugins: {
    //     webdrivercss: {
    //         screenshotRoot: 'my-shots',
    //         failedComparisonsRoot: 'diffs',
    //         misMatchTolerance: 0.05,
    //         screenWidth: [320,480,640,1024]
    //     },
    //     webdriverrtc: {},
    //     browserevent: {}
    // },
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: [
      // 'browserstack',
      'selenium-standalone'
    ],
    //
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: http://webdriver.io/guide/testrunner/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: http://webdriver.io/guide/testrunner/reporters.html
    reporters: ['spec'],
    
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd'
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    //
    // Gets executed once before all workers get launched.
    // onPrepare: function (config, capabilities) {
    // },
    //
    // Gets executed just before initialising the webdriver session and test framework. It allows you
    // to manipulate configurations depending on the capability or spec.
    // beforeSession: function (config, capabilities, specs) {
    // },
    //
    // Gets executed before test execution begins. At this point you can access all global
    // variables, such as `browser`. It is the perfect place to define custom commands.
    // before: function (capabilities, specs) {
    // },
    //
    // Hook that gets executed before the suite starts
    // beforeSuite: function (suite) {
    // },
    //
    // Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
    // beforeEach in Mocha)
    // beforeHook: function () {
    // },
    //
    // Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
    // afterEach in Mocha)
    // afterHook: function () {
    // },
    //
    // Function to be executed before a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
    // beforeTest: function (test) {
    // },
    //
    // Runs before a WebdriverIO command gets executed.
    // beforeCommand: function (commandName, args) {
    // },
    //
    // Runs after a WebdriverIO command gets executed
    // afterCommand: function (commandName, args, result, error) {
    // },
    //
    // Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
    // afterTest: function (test) {
    // },
    //
    // Hook that gets executed after the suite has ended
    // afterSuite: function (suite) {
    // },
    //
    // Gets executed after all tests are done. You still have access to all global variables from
    // the test.
    // after: function (result, capabilities, specs) {
    // },
    //
    // Gets executed right after terminating the webdriver session.
    // afterSession: function (config, capabilities, specs) {
    // },
    //
    // Gets executed after all workers got shut down and the process is about to exit. It is not
    // possible to defer the end of the process using a promise.
    // onComplete: function(exitCode) {
    // }
}
```

Also, here's the test I'm running:
```
var assert = require('assert');

var assert = require('assert');
describe('webdriver.io page', function() {
  it('should have the right title - the fancy generator way', function () {
    browser.url('http://webdriver.io');
    var title = browser.getTitle();
    assert.equal(title, 'WebdriverIO - Selenium 2.0 javascript bindings for nodejs');
  });
});
```
Could you advise please?

Many thanks

**Comment by christian-bromann** [comment]
Not sure what this is, seems to be an issue of a node module called `asn1`. This seems not to be WebdriverIO related. Not sure where the error comes from. Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
