### ISSUE TITLE
Cannot Build wdio-jasmine-framework in travis

### ISSUE THREAD

**Issue by kariasbolster** [webdriverio/webdriverio#1901]
## The problem

Hi, I was trying to integrate my webdriverio tests in Travis CI and during npm installation I encountered a build problem for wdio-jasmine-framework

```
make: Leaving directory `/home/travis/.nvm/versions/node/v7.5.0/lib/node_modules/wdio-jasmine-framework/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-103-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v7.5.0/bin/node" "/home/travis/.nvm/versions/node/v7.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/travis/.nvm/versions/node/v7.5.0/lib/node_modules/wdio-jasmine-framework/node_modules/fibers
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: 1: nodejs: not found
/home/travis/.nvm/versions/node/v7.5.0/lib
└── (empty)
npm ERR! Linux 3.13.0-103-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v7.5.0/bin/node" "/home/travis/.nvm/versions/node/v7.5.0/bin/npm" "install" "-g" "wdio-jasmine-framework"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.15 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/jkentreynes/apiary-testing/npm-debug.log
The command "npm install -g wdio-jasmine-framework" failed and exited with 1 during .
Your build has been stopped.
```
Can someone help me with this?

**Comment by christian-bromann** [comment]
Please read the error message, it is all in there 😉 

```
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
```

Make sure you have the necessary dependencies to install node-fibers.

**Comment by kariasbolster** [comment]
@christian-bromann Okay. Thank you.

**Comment by kariasbolster** [comment]
@christian-bromann Hi, sorry I am a noob at these stuffs and is still starting in this endeavor. I still can't seem to install wdio-jasmine-framework. Can you help me with my problem?

my travis operating system is 

Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise

this is my travis.yml file
language: 
  node_js
node_js:
  - '7.5.0'
sudo: 
  required
install: 
  - sudo apt-get install g++ build-essential
  - npm install -g webdriverio
  - npm install -g newman
  - npm install -g wdio-jasmine-framework
before_script:
  - chmod +x ./deploy.sh
script:
  ./deploy.sh

addons:
  sauce_connect:
    username: "nedved"
    access_key: "6d31c524-7dc8-40f3-84da-c92c9ffc1514"

**Comment by christian-bromann** [comment]
> I still can't seem to install wdio-jasmine-framework

Any error messages when you install it? Or a link to the travis job?
