### ISSUE TITLE
Unable to perform any actions using an element

### ISSUE THREAD

**Issue by trigun539** [webdriverio/webdriverio#1925]
## Unable to perform any actions with an element

```javascript
var someElement = $$('#menu li')[0];

someElement.click(); // click is not a function
someElement.getAttribute('class'); // getAttribute is not a function```

## Environment

* WebdriverIO version: 4.5.2
* Node.js version: 6.9.2
* Standalone mode, running selenium-webdriver 3.x
* Chrome 56.0.2924.87 (64-bit)
* Windows 7 64 bit
* Additional wdio packages used:
- wdio-mocha-framework: 0.4.6

## Selenium/WebdriverIO logs:

1) Navigation :: should go to subject areas:
item.getAttribute is not a function
running chrome
TypeError: item.getAttribute is not a function
    at Context.<anonymous> (E:/apps/emr/emr-fe/test-ui/containe
igation.spec.js:64:20)
    at E:\apps\emr\node_modules\wdio-sync\build\index.js:678:26
    at Context.executeSync (E:\apps\emr\node_modules\wdio-sync\
6:12)
    at E:\apps\emr\node_modules\wdio-sync\build\index.js:902:34

**Comment by christian-bromann** [comment]
> Standalone mode, running selenium-webdriver 3.x

This only works with WebdriverIO not selenium-webdriver using the wdio testrunner. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
