### ISSUE TITLE
Couldn't get screenshot on Android emulator

### ISSUE THREAD

**Issue by starostin** [webdriverio/webdriverio#1960]
## The problem

I am writing tests for cordova app. And when test fails, I do screenshot. This feature works fine in browser and iOS emulator, but Android emulator just stuck on saveScreenshot method.

## Environment

* WebdriverIO version: 4.6.2
* Node.js version: 6.7.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): 
"wdio-allure-reporter": "^0.1.2",
"wdio-appium-service": "^0.2.3",
"wdio-jasmine-framework": "^0.3.0",

## Link to Selenium/WebdriverIO logs
```
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/oleg/Library/Android/sdk/build-tools/19.1.0/aapt
[ADB] Extracting package and launch activity from manifest
[debug] [ADB] badging package: aaa
[debug] [ADB] badging act: aaa.MainActivity
[debug] [AndroidDriver] Parsed package and activity are: aaa/aaa.MainActivity
[AndroidDriver] Remote apk path is /data/local/tmp/b9d008a213519e8daa8e9495c27b750d.apk
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","ls","/data/local/tmp/b9d008a213519e8daa8e9495c27b750d.apk"]
[debug] [AndroidDriver] Checking if app is installed
[debug] [ADB] Getting install status for aaa
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","aaa"]
[debug] [ADB] App is installed
[debug] [AndroidDriver] Extracting strings from apk ./builds/DEV/aaa.apk null /var/folders/s5/xhbv6txs39jgk8f7sr9y71600000gp/T/aaa
[debug] [ADB] Extracting strings for language: default
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","persist.sys.locale"]
[debug] [ADB] Current device property 'persist.sys.locale': 
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.product.locale"]
[debug] [ADB] Current device property 'ro.product.locale': en-US
[debug] [ADB] No strings.xml for language 'en', getting default strings.xml
[debug] [ADB] Reading strings from converted strings.json
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","push","/var/folders/s5/xhbv6txs39jgk8f7sr9y71600000gp/T/aaa/strings.json","/data/local/tmp"]
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","push","/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar","/data/local/tmp/"]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","aaa","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Getting connected devices...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window"]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","am","start","-W","-n","aaa/aaa.MainActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Waiting for pkg: 'aaa' and activity: 'aaa.MainActivity' to be focused
[debug] [ADB] Possible activities, to be checked: aaa.MainActivity, aaa.MainActivity
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'aaa' and fully qualified activity name : 'aaa.MainActivity'
[AndroidDriver] Setting auto webview to context 'WEBVIEW_aaa' with timeout 2000ms
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_4795 mapped to pid 4795
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/oleg/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 4795 pkg:aaa!
[debug] [AndroidDriver] from: u0_a56,4795,1228,1931272,151536,binder_thr,b7398ee6,S,aaa
[debug] [AndroidDriver] returning process name: aaa
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_aaa"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_aaa"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_aaa'
[debug] [AndroidDriver] A port was not given, using random port: 8004
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: ./tests/configs/chromedriver
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "./tests/configs/chromedriver.*--port=8004"
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: ./tests/configs/chromedriver --url-base=wd/hub --port=8004 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver (v2.9.248307) on port 8004
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8004/wd/hub/status] with no body
[Chromedriver] [STDERR] [warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.12.3\"}}}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8004/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"aaa","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"9f733a6443732d973fab61455b0bf02c","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"javascriptEnabled":true,"locationContextEnabled":true,"nativeEvents":true,"platform":"ANDROID","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"version":"44.0.2403.119","webStorageEnabled":true}}
[debug] [Chromedriver] Changed state to 'online'
[Appium] New AndroidDriver session created successfully, session b460ee01-0db1-4b81-b3fd-a97c3eb4af95 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1490946732384 (10:52:12 GMT+0300 (EEST))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":true,"warnings":{},"desired":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"","automationName":"Appium","chromedriverExecutable":"./tests/configs/chromedriver","platformName":"Android","autoWebview":true,"noReset":true,"deviceName":"Nexus6","app":"./builds/DEV/aaa.apk","requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}},"handlesAlerts":true,"rotatable":true,"browserName":"","automationName":"Appium","chromedriverExecutable":"./tests/configs/chromedriver","platformName":"Android","autoWebview":true,"noReset":true,"deviceName":"emulator-5554","app":"./builds/DEV/aaa.apk","requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"},"deviceUDID":"emulator-...
[HTTP] <-- POST /wd/hub/session 200 28033 ms - 1399 
[HTTP] --> POST /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/element {"using":"id","value":"login"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/element] to [POST http://127.0.0.1:8004/wd/hub/session/9f733a6443732d973fab61455b0bf02c/element] with body: {"using":"id","value":"login"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"9f733a6443732d973fab61455b0bf02c","status":0,"value":{"ELEMENT":"0.8422711584717035-1"}}
[JSONWP Proxy] Replacing sessionId 9f733a6443732d973fab61455b0bf02c with b460ee01-0db1-4b81-b3fd-a97c3eb4af95
[HTTP] <-- POST /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/element 200 6551 ms - 106 
[HTTP] --> POST /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/element/0.8422711584717035-1/click {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/element/0.8422711584717035-1/click] to [POST http://127.0.0.1:8004/wd/hub/session/9f733a6443732d973fab61455b0bf02c/element/0.8422711584717035-1/click] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"9f733a6443732d973fab61455b0bf02c","status":0,"value":null}
[JSONWP Proxy] Replacing sessionId 9f733a6443732d973fab61455b0bf02c with b460ee01-0db1-4b81-b3fd-a97c3eb4af95
[HTTP] <-- POST /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/element/0.8422711584717035-1/click 200 1998 ms - 76 
[HTTP] --> GET /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/screenshot] to [GET http://127.0.0.1:8004/wd/hub/session/9f733a6443732d973fab61455b0bf02c/screenshot] with body: {}
[HTTP] <-- GET /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[HTTP] <-- GET /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/screenshot] to [GET http://127.0.0.1:8004/wd/hub/session/9f733a6443732d973fab61455b0bf02c/screenshot] with body: {}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:343:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- GET /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/b460ee01-0db1-4b81-b3fd-a97c3eb4af95/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy


```

## Code To Reproduce Issue [ Good To Have ]
```
'use strict';
var constants = require('./configs/constants');

describe('Login page', function () {
  // Set the timeout in the framework

  beforeEach(function () {
    if (browser.desiredCapabilities.browserName) {
      browser.url(constants.startUrl);
    }
  });

  it('Empty email field', function () {
    var notification;
    browser.click('#login');
    browser.saveScreenshot('aaa.png')
    notification = browser.getText('.notification__title');
    expect(notification).toEqual('Email can\'t be empty');
  });

});

```

Android configs

```
exports.config = merge(wdioConf.config, {
  hostname: 'localhost',
  port: 4723,
  services: ['appium'],
  capabilities: [{
    automationName: 'Appium',
    chromedriverExecutable: './tests/configs/chromedriver',
    browserName: '',
    platformName: 'Android',
    autoWebview: true,
    noReset: true,
    deviceName: 'Nexus6',
    app: 'app.apk'
  }]
});


```

Chromedriver v2.9 (I have installed 2.28, but I got error when used it). Android Emulator with Android 6.0.

Thanks in advance!

**Comment by christian-bromann** [comment]
@starostin this is an Appium issue, please fill a ticket there. Thanks

**Comment by ianrenauld** [comment]
@starostin Did you ever file an issue with Appium about this? I have the same issue, Cordova app, can't get screenshots for Android (either emulator or real devices), but works fine on iOS...

**Comment by olivierschmid** [comment]
@starostin I found a solution: Set nativeWebScreenshot to 'true' in the capabilities. This will use adb instead of browser for screenshotting
