### ISSUE TITLE
Webdriverio reports a generic error for lower level request issues. 

### ISSUE THREAD

**Issue by deployable** [webdriverio/webdriverio#2036]
## The problem

Webdriver reports a generic `Couldn't connect to selenium server` with a type of `ECONNREFUSED` error when other request error types have occurred. 

## Environment

* WebdriverIO version: 4.7.1
* Node.js version: 7.9.0
* Standalone mode

## Details

The webdriverio request handler reports a generic `RuntimeError` with a message of `'Couldn\'t connect to selenium server'` which provides no insight into the cause of the request issue. 

Digging further into the error object reveals a `seleniumStack` property with a type of `ECONNREFUSED`.  This is generated in the [RequestHandler](https://github.com/webdriverio/webdriverio/blob/10adef34ba0810f86e8c07c0893b3cb33802a723/lib/utils/RequestHandler.js#L234-L239) as a default. 

```
  dply:page:page wd error { Error: Couldn't connect to selenium server
    at promise (/clones/node-deployable-page/lib/page.js:241:29)
    at Page.initWebdriver (/clones/node-deployable-page/lib/page.js:244:12)
    at promise.Promise.each.i (/clones/node-deployable-page/lib/page.js:195:55)
    at done (/clones/node-deployable-page/node_modules/needle/lib/needle.js:432:14)
    at PassThrough.<anonymous> (/clones/node-deployable-page/node_modules/needle/lib/needle.js:671:11)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
From previous event:
    at Page.initAsync (/clones/node-deployable-page/lib/page.js:195:28)
    at new Page (/clones/node-deployable-page/lib/page.js:141:12)
    at Context.<anonymous> (/clones/node-deployable-page/test/int_page_spec.js:64:16)
    at callFn (/.ndenv/versions/v6.10.2/lib/node_modules/mocha/lib/runnable.js:345:21)
    at Hook.Runnable.run (/.ndenv/versions/v6.10.2/lib/node_modules/mocha/lib/runnable.js:337:7)
    at next (/.ndenv/versions/v6.10.2/lib/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/.ndenv/versions/v6.10.2/lib/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
  message: 'Couldn\'t connect to selenium server',
  type: 'RuntimeError',
  seleniumStack: 
   { status: -1,
     type: 'ECONNREFUSED',
     message: 'Couldn\'t connect to selenium server',
     orgStatusMessage: 'Couldn\'t connect to selenium server' } } +3ms
```

Adding debug to the webdriverio RequestHandler, the original request issue was:
```
  webdriver:requesthandler: error { Error: getaddrinfo ENOTFOUND undefined undefined:44446
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined',
  host: 'undefined',
  port: '444' } +1ms
```

The main issues are, 

1. Details of the underlying error are lost
2. The error message could be made more obvious 
3. `ECONNREFUSED` has a very specific meaning of a response from the destination refusing the connection (which normally means the host is up and the process is down, or a firewall) and shouldn't be a default. 
4. No useful stack is available from the original error.

## Link to Selenium/WebdriverIO logs

n/a

## Code To Reproduce Issue [ Good To Have ]

DNS

    webdriverio.remote({host: 'somehostthatdoesntexist' }).init()

Unreachable

    webdriverio.remote({host: '10.99.19.239' }).init()

**Comment by deployable** [comment]
Using [bluebird](http://bluebirdjs.com) to construct the promise that houses the request results in a stack that highlights the origin of the error.

```
  dply:page:page wd error { Error: Couldn't connect to selenium server
    at RequestHandler.request (/clones/node-deployable-page/node_modules/webdriverio/build/lib/utils/RequestHandler.js:234:20)
    at Request._callback (/clones/node-deployable-page/node_modules/webdriverio/build/lib/utils/RequestHandler.js:302:28)
    at self.callback (/clones/node-deployable-page/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/clones/node-deployable-page/node_modules/request/request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  message: 'Couldn\'t connect to selenium server',
  type: 'RuntimeError',
  seleniumStack: 
   { status: -1,
     type: 'ECONNREFUSED',
     message: 'Couldn\'t connect to selenium server',
     orgStatusMessage: 'Couldn\'t connect to selenium server' } } +1ms
```

**Comment by deployable** [comment]
Something like this... https://github.com/deployable/webdriverio/tree/issue_2036

There's a unit test failing in the master branch this was forked from #2037

**Comment by christian-bromann** [comment]
@deployable thanks for reporting. I found a slightly shorter solution. Let me know if that works for you. This script:

```js
var client = require('./build').remote({
    host: 'foobar',
    desiredCapabilities: { browserName: 'chrome' }
});

client.init().url('http://google.com').end().catch(console.log)
```

now returns:

```
{ [Error: Error: getaddrinfo ENOTFOUND foobar foobar:4444
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)]
  message: 'Error: getaddrinfo ENOTFOUND foobar foobar:4444\n    at errnoException (dns.js:26:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)',
  type: 'RuntimeError',
  seleniumStack:
   { status: -1,
     type: 'ENOTFOUND',
     message: 'Couldn\'t connect to selenium server: getaddrinfo ENOTFOUND foobar foobar:4444',
     orgStatusMessage: 'Error: getaddrinfo ENOTFOUND foobar foobar:4444\n    at errnoException (dns.js:26:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)' } }
```

**Comment by thebarty** [comment]
Do you guys have a tip where to find logs on WHY selenium is NOT available?

**Comment by christian-bromann** [comment]
> on WHY selenium is NOT available?

@thebarty first of all this has nothing to do with Selenium. You need to make sure that you have a browser driver running or a Selenium standalone server setup.

> Do you guys have a tip where to find logs

To which logs your are referring to?
