### ISSUE TITLE
Bug report: Extra space from getAttribute(***, 'textContent') since v4.7.0

### ISSUE THREAD

**Issue by mondwan** [webdriverio/webdriverio#2063]
## The problem

Since v4.7.0, there is a bug from **getAttribute()**, it returns an extra space at the end from a table cell. For the rest, see code to reproduce below.

## Environment

* WebdriverIO version: v4.6.2, v4.7.0, v4.7.1, v4.8.0
* Node.js version: v6.10.1
* OS: Ubuntu 16.04
* Environment constructed by instructions from [cucumber-boilerplate][1]

[1]: https://github.com/webdriverio/cucumber-boilerplate

## Details

See code to reproduce below

## Code To Reproduce Issue [ Good To Have ]

* git clone cucumber-boilerplate
* `npm install`
* `rm src/featrues/*`
* edit `src/feature/textComparison.feature` with following content

```
Feature: Test text contents of elements
    As a developer
    I want to be able to test the text inside a element against the text inside
    another element

    Background:
        Given I open the site "/"

    Scenario: Input containing the same text
        Then I expect that element "#abc" contains the text "WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1"
```

* edit `demo-app/index.html` with following content

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>DEMO APP</title>
        <link href="/favicon.png" rel="icon" type="image/png"/>

        <!-- Reset CSS -->
        <link rel="stylesheet" href="http://meyerweb.com/eric/tools/css/reset/reset.css">

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <style type="text/css">
        .spacer {
            height: 500px;
        }
        </style>
    </head>
    <body>
        <div class="container">
<table id="packetForward" class="table table-bordered"><thead><tr><th>Local Subnet</th><th>Outgoing Inteface</th></tr></thead><tbody><tr id="packetForward.wan"><td><span><!-- react-text: 128 -->LAN1<!-- /react-text --><!-- react-text: 129 -->: <!-- /react-text --><!-- react-text: 130 -->172.16.0.1/24<!-- /react-text --><br></span></td><td><span><!-- react-text: 134 -->WAN<!-- /react-text --><br></span><span><!-- react-text: 137 -->Global IP Address: <!-- /react-text --><!-- react-text: 138 -->10.240.0.108/16<!-- /react-text --><br></span><span><!-- react-text: 141 -->Gateway: <!-- /react-text --><!-- react-text: 142 -->10.240.0.1<!-- /react-text --><!-- react-text: 143 --> <!-- /react-text --><!-- react-text: 144 --><!-- /react-text --></span></td></tr></tbody></table>
        </div>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <!-- jQuery cookie plugin -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

        <script src="inc/script.js"></script>
    </body>
</html>
```

* edit `src/support/check/checkContainsText.js` with following content

```javascript
/**
 * Check if the given elements contains text
 * @param  {String}   type          Type of element (inputfield or element)
 * @param  {String}   element       Element selector
 * @param  {String}   falseCase     Whether to check if the content contains
 *                                  the given text or not
 * @param  {String}   expectedText  The text to check against
 * @param  {Function} done          Function to execute when finished
 */
module.exports = (type, element, falseCase, expectedText, done) => {
    /**
     * The command to perform on the browser object
     * @type {String}
     */
    const command = (type !== 'inputfield') ? 'getText' : 'getValue';

    /**
     * False case
     * @type {Boolean}
     */
    let boolFalseCase;

    /**
     * The expected text
     * @type {String}
     */
    let stringExpectedText = expectedText;

    /**
     * Callback to trigger when done
     * @type {Function}
     */
    let doneCallback = done;

    /**
     * The text of the element
     * @type {String}
     */
    const text = browser.getAttribute('//*[@id="packetForward.wan"]//td[2]', 'textContent');
    console.error('outputText', text);

    if (typeof expectedText === 'function') {
        doneCallback = expectedText;
        stringExpectedText = falseCase;
        boolFalseCase = false;
    } else {
        boolFalseCase = (falseCase === ' not');
    }

    if (boolFalseCase) {
        expect(text).to.not.equal(stringExpectedText);
    } else {
        expect(text).to.equal(stringExpectedText);
    }

    doneCallback();
};

```

* Start webserver `npm run-script local-webserver`
* Somehow starts a selenium server with chromdriver

## for webdriverio v4.6.2 (GOOD CASE)

* npm rm webdriverio
* npm install webdriverio@4.6.2
* run node_modules/.bin/wdio

```
mondwan@mondwan-All-Series:~/Documents/codeTest/cucumber-boilerplate$ node_modules/.bin/wdio --version
v4.6.2
mondwan@mondwan-All-Series:~/Documents/codeTest/cucumber-boilerplate$ node_modules/.bin/wdio 
outputText WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1
------------------------------------------------------------------
[chrome #0-0] Session ID: 92063fd1-8679-4eaa-b8a5-26ecbd502303
[chrome #0-0] Spec: /home/mondwan/Documents/codeTest/cucumber-boilerplate/src/features/textComparison.feature
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] Test text contents of elements
[chrome #0-0]
[chrome #0-0]     Input containing the same text
[chrome #0-0]       ✓ I open the site "/"
[chrome #0-0]       ✓ I expect that element "#abc" contains the text "WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1"
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 2 passing (2s)
[chrome #0-0]
```

## for webdriverio 4.7.0 4.7.2 4.8.0 (BAD CASE)

* npm rm webdriverio
* npm install webdriverio@4.7.0
* run node_modules/.bin/wdio

```
mondwan@mondwan-All-Series:~/Documents/codeTest/cucumber-boilerplate$ npm list webdriverio@4.7.0
cucumber-boilerplate@1.1.1 /home/mondwan/Documents/codeTest/cucumber-boilerplate
└── webdriverio@4.7.0  invalid

npm ERR! invalid: webdriverio@4.7.0 /home/mondwan/Documents/codeTest/cucumber-boilerplate/node_modules/webdriverio
mondwan@mondwan-All-Series:~/Documents/codeTest/cucumber-boilerplate$ node_modules/.bin/wdio --version
v4.6.2
mondwan@mondwan-All-Series:~/Documents/codeTest/cucumber-boilerplate$ node_modules/.bin/wdio 
outputText WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1 
------------------------------------------------------------------
[chrome #0-0] Session ID: 7cc7aafa-0c7e-46ed-83b0-f27d0cca3aec
[chrome #0-0] Spec: /home/mondwan/Documents/codeTest/cucumber-boilerplate/src/features/textComparison.feature
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] Test text contents of elements
[chrome #0-0]
[chrome #0-0]     Input containing the same text
[chrome #0-0]       ✓ I open the site "/"
[chrome #0-0]       1) I expect that element "#abc" contains the text "WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1"
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 passing (2s)
[chrome #0-0] 1 failing
[chrome #0-0]
[chrome #0-0] 1) Input containing the same text9 I expect that element "#abc" contains the text "WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1":
[chrome #0-0] expected 'WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1 ' to equal 'WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1'
[chrome #0-0] AssertionError: expected 'WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1 ' to equal 'WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1'
[chrome #0-0]     at World.module.exports (/home/mondwan/Documents/codeTest/cucumber-boilerplate/src/support/check/checkContainsText.js:53:25)
[chrome #0-0]     at Promise.F (/home/mondwan/Documents/codeTest/cucumber-boilerplate/node_modules/core-js/library/modules/_export.js:35:28)
[chrome #0-0]
```
As you can see, there is an extra space at the end.

```
[chrome #0-0] expected 'WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1 ' to equal 'WANGlobal IP Address: 10.240.0.108/16Gateway: 10.240.0.1'
```

**Comment by christian-bromann** [comment]
Please see https://github.com/webdriverio/webdriverio/issues/1885. We don't trim results anymore. You will have to do it in your step definitions if you encounter this.

**Comment by mondwan** [comment]
Hello, thanks for the quick update.

One more question

What do you mean by driver? Do you mean the extra spaces sources from
selenium or chrome?

In chrome, I have checked out that there is no such white space. However, I
am not sure how to debug that space in selenium.

2017年5月11日 16:02，"Christian Bromann" <notifications@github.com>寫道：

**Comment by christian-bromann** [comment]
> What do you mean by driver?

I meant Chromedriver which is used by Selenium to automate Chrome.

**Comment by monolithed** [comment]
@mondwan, 

First of all, I believe we shouldn't trim any spaces due to this behaviour is not documented in the standard WebDriver protocol.

So, 

1. Create a minimal reproducible example without any abstractions.
2. Try to run your example using ChromeDriver
3. Try to get your text using `browser.execute`:

```ts
let text = browser.selectorExecute(<YOUR_SELECTOR>, element => element.textContent());
```

And compare the results

**Comment by mondwan** [comment]
Great. I will try about that. Thanks for the hints

2017年5月11日 17:11，"Alexander Abashkin" <notifications@github.com>寫道：
