### ISSUE TITLE
Examples: please add documentation for usage and expected output

### ISSUE THREAD

**Issue by zmorris** [webdriverio/webdriverio#2087]
## The problem

Hi, I am working through [the examples](https://github.com/webdriverio/webdriverio/tree/master/examples) and having trouble getting many of them to work.  I think the code is likely correct but without seeing exact usage I am struggling.  This requires the user to understand a great deal of context, especially for those who are new to Node.js.

## Environment

* WebdriverIO version: (Please add `./node_modules/.bin/wdio -v` here) v4.6.2
* Node.js version: (Please add `node -v` here) v6.10.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): both
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): N/A

## Link to Selenium/WebdriverIO logs

Please mention that this is the output from running a command like `selenium-standalone start`

### Install [Homebrew](https://brew.sh/)
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
### Install [Yarn](https://yarnpkg.com/en/) (a faster alternative to [NPM](https://www.npmjs.com/))
```
brew update && brew upgrade
brew install yarn
```
### Change Yarn prefix to match NPM so that `yarn global add` works
```
yarn config set prefix /usr/local/
```

### Install [selenium-standalone](https://github.com/vvo/selenium-standalone)
```
yarn global add selenium-standalone@latest
selenium-standalone install
```

### Run selenium-standalone
```
selenium-standalone start
# ...
# Started ServerConnector@5442a311{HTTP/1.1,[http/1.1]}{0.0.0.0:4444}
# ...
# ^^^ selenium default is localhost or 127.0.0.1 port 4444
```

### Install [WebDriverIO](http://webdriver.io/)
```
git clone git@github.com:webdriverio/webdriverio.git
cd ./webdriverio
yarn
yarn build
```

### Run examples

```
########## Cloudservices ##########

export SAUCE_USERNAME="username"
export SAUCE_ACCESS_KEY="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
node examples/cloudservices/webdriverio.saucelabs.js
<no output, nothing in https://saucelabs.com/beta/archives>

export BROWSERSTACK_USERNAME="username"
export BROWSERSTACK_ACCESS_KEY="XXXXXXXXXXXXXXXXXXXX"
node examples/cloudservices/webdriverio.browserstack.js
<no output, nothing in https://www.browserstack.com/automate>

# skipping webdriverio.testingbot.js because I don't have an account
#export TESTINGBOT_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#export TESTINGBOT_SECRET="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
#node examples/cloudservices/webdriverio.testingbot.js

########## Commands ##########

node examples/commands/webdriverio.addCommand.js
WARNING: the "keys" command will be deprecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
WARNING: the "keys" command will be deprecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
# selenium-standalone opened chrome window with https://www.google.com/?gws_rd=ssl

node examples/commands/webdriverio.externalAddCommandHelper.js
# no output, no selenium-standalone activity

node examples/commands/webdriverio.selectBy.js
# selenium-standalone opened chrome window with http://thenostalgiamachine.com/

node examples/commands/webdriverio.selectorExecute.js
29 divs on the page
# selenium-standalone opened chrome window with https://news.ycombinator.com/

node examples/commands/webdriverio.selectorExecuteAsync.js
WARNING: the "timeoutsAsyncScript" command will be deprecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
29 divs on the page
# selenium-standalone opened chrome window with https://news.ycombinator.com/

node examples/commands/webdriverio.waitForVisible.js
true
# selenium-standalone opened chrome window with https://www.google.com/?gws_rd=ssl

node examples/multiremote/webdriverio.multiremote.chat.js
~/webdriverio/examples/multiremote/webdriverio.multiremote.chat.js:18
describe('multiremote example', function() {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (~/webdriverio/examples/multiremote/webdriverio.multiremote.chat.js:18:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
# no selenium-standalone activity

node examples/multiremote/webdriverio.multiremote.js
# selenium-standalone opened chrome window with https://appr.tc/r/88048345650

node examples/multiremote/webdriverio.multiremote.chat.js
~/webdriverio/examples/multiremote/webdriverio.multiremote.chat.js:18
describe('multiremote example', function() {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (~/webdriverio/examples/multiremote/webdriverio.multiremote.chat.js:18:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
# no selenium-standalone activity

./node_modules/.bin/mocha examples/multiremote/webdriverio.multiremote.chat.js --timeout 9999999
~/webdriverio/node_modules/mocha/lib/suite.js:340
  test.timeout(this.timeout());
                    ^

TypeError: this.timeout is not a function
    at Suite.addTest (~/webdriverio/node_modules/mocha/lib/suite.js:340:21)
    at context.it.context.specify (~/webdriverio/node_modules/mocha/lib/interfaces/bdd.js:88:13)
    at Suite.<anonymous> (~/webdriverio/examples/multiremote/webdriverio.multiremote.chat.js:22:5)
    at Object.create (~/webdriverio/node_modules/mocha/lib/interfaces/common.js:114:19)
    at context.describe.context.context (~/webdriverio/node_modules/mocha/lib/interfaces/bdd.js:44:27)
    at Object.<anonymous> (~/webdriverio/examples/multiremote/webdriverio.multiremote.chat.js:18:1)
    at Module._compile (module.js:570:32)
    at loader (~/webdriverio/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (~/webdriverio/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at ~/webdriverio/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (~/webdriverio/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (~/webdriverio/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (~/webdriverio/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
# no selenium-standalone activity

########## Page Object Example ##########

./bin/wdio examples/pageobject/wdio.conf.js

pattern ./specs/*.spec.js did not match any file
# no selenium-standalone activity

########## Standalone ##########

node examples/standalone/webdriverio.with.mocha.js
~/webdriverio/examples/standalone/webdriverio.with.mocha.js:4
describe('my webdriverio tests', function(){
^

ReferenceError: describe is not defined
    at Object.<anonymous> (~/webdriverio/examples/standalone/webdriverio.with.mocha.js:4:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
# no selenium-standalone activity

# skipping remaining standalone tests

########## WDIO ##########

yarn add wdio-cucumber-framework
./bin/wdio examples/wdio/wdio.cucumber.conf.js

․WARNING: the "elementIdSize" command will be deprecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
․․WARNING: the "elementIdSize" command will be deprecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
․․F․F․WARNING: the "elementIdSize" command will be deprecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
․․F

9 passing (6.30s)
3 failing

1) Get title of website10 should the title of the page be "How people build software · GitHub":
 title is "The world's leading software development platform · GitHub" but should be "How people build software · GitHub
running phantomjs
running chrome
running firefox
AssertionError:  title is "The world's leading software development platform · GitHub" but should be "How people build software · GitHub
    at World.<anonymous> (~/webdriverio/examples/wdio/runner-specs/cucumber/step-definitions.js:29:16)
    at Promise.F (~/webdriverio/node_modules/core-js/library/modules/_export.js:35:28)
# selenium-standalone opened chrome window with https://github.com/

./bin/wdio examples/wdio/wdio.customreporter.conf.js
~/webdriverio/build/lib/launcher.js:158
                        throw _iteratorError;
                        ^

Error: Custom reporters must export a unique 'reporterName' property
    at Launcher.initReporters (~/webdriverio/build/lib/launcher.js:128:35)
    at new Launcher (~/webdriverio/build/lib/launcher.js:69:31)
    at Object.<anonymous> (~/webdriverio/build/lib/cli.js:424:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
# no selenium-standalone activity

yarn add wdio-jasmine-framework
./bin/wdio examples/wdio/wdio.jasmine.conf.js

let's go
․․․

3 passing (6.50s)


that's it
# selenium-standalone opened chrome window with http://webdriver.io/

yarn add wdio-mocha-framework
./bin/wdio examples/wdio/wdio.mocha.conf.js

let's go
․․․․․․

3 passing (6.40s)
3 skipped


that's it
# selenium-standalone opened chrome window with http://webdriver.io/

./bin/wdio examples/wdio/wdio.multiremote.conf.js

․FWARNING: the "keys" command will be deprecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
WARNING: the "keys" command will be deprecated soon. Please use a different command in order to avoid failures in your test after updating WebdriverIO.
․FF․

3 passing (7.40s)
3 failing

1) multiremote example should login the browser:
An element could not be located on the page using the given search parameters (".usernameInput").
running
Error: An element could not be located on the page using the given search parameters (".usernameInput").
    at Context.<anonymous> (examples/wdio/runner-specs/mocha.multiremote.test.js:7:18)
    at Promise.F (node_modules/core-js/library/modules/_export.js:35:28)

2) multiremote example should post something in browserA:
An element could not be located on the page using the given search parameters (".inputMessage").
running
Error: An element could not be located on the page using the given search parameters (".inputMessage").
    at Context.<anonymous> (examples/wdio/runner-specs/mocha.multiremote.test.js:17:18)
    at Promise.F (node_modules/core-js/library/modules/_export.js:35:28)

3) multiremote example should read the message in browserB:
An element could not be located on the page using the given search parameters (".messageBody*=My name is").
running
Error: An element could not be located on the page using the given search parameters (".messageBody*=My name is").
    at Context.<anonymous> (examples/wdio/runner-specs/mocha.multiremote.test.js:23:32)
    at Promise.F (node_modules/core-js/library/modules/_export.js:35:28)
# selenium-standalone opened chrome window with http://chat.socket.io/

yarn add webdrivercss
yarn add wdio-webdrivercss-framework
yarn add v0.23.4
[1/4] 🔍  Resolving packages...
error Couldn't find package "wdio-webdrivercss-framework" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
./bin/wdio examples/wdio/wdio.webdrivercss.conf.js

ERROR: Couldn't find plugin "webdrivercss". You need to install it with `$ npm install webdrivercss`!
Error: Cannot find module 'webdrivercss'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Runner.initialisePlugins (~/webdriverio/build/lib/runner.js:614:34)
    at Runner._callee$ (~/webdriverio/build/lib/runner.js:102:38)
    at tryCatch (~/webdriverio/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (~/webdriverio/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (~/webdriverio/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (~/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)

    at Runner.initialisePlugins (~/webdriverio/build/lib/runner.js:620:31)
    at Runner._callee$ (~/webdriverio/build/lib/runner.js:102:38)
    at tryCatch (~/webdriverio/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (~/webdriverio/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (~/webdriverio/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (~/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at ~/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
ERROR: Couldn't find plugin "webdrivercss". You need to install it with `$ npm install webdrivercss`!
Error: Cannot find module 'webdrivercss'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Runner.initialisePlugins (~/webdriverio/build/lib/runner.js:614:34)
    at Runner._callee$ (~/webdriverio/build/lib/runner.js:102:38)
    at tryCatch (~/webdriverio/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (~/webdriverio/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (~/webdriverio/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (~/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)

    at Runner.initialisePlugins (~/webdriverio/build/lib/runner.js:620:31)
    at Runner._callee$ (~/webdriverio/build/lib/runner.js:102:38)
    at tryCatch (~/webdriverio/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (~/webdriverio/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (~/webdriverio/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (~/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at ~/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
# no selenium-standalone activity
```

### GitHub gist:

https://gist.github.com/zmorris/e4bbc42334f4d58bf5eade8faeca1cf6

I decided to include the full output due to the bug/feature of GitHub that doesn't seem to allow embedding gists in issues via their [embed markup](https://help.github.com/articles/about-gists/#embedding-gists).

To illustrate why it's so dangerous to hide content behind links (which prevents it from being searched), here is a link to [the guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) to this repository:

https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md

**It explains how to run tests.**  I didn't notice it until I was proofreading this post.  I've lost about 4-8 hours troubleshooting how to run the examples so hopefully this summary will help others in the future.  If you get time, it would be helpful if you added a **comprehensive test** to run all of your example tests that people could use for reference.

Sorry for being direct, I just think that WebDriverIO is a really exceptional and promising testing framework and that the examples deserve top priority for documentation (just like your well-written [Developer Guide](http://webdriver.io/guide.html)).  Thanks and please keep up the good work.

**Comment by christian-bromann** [comment]
> ########## Cloudservices ##########

Fixed the scripts, apparently some nodes on google.com have changed so that the selectors had to be updated.

> node examples/commands/webdriverio.addCommand.js

Same here, updated

> node examples/commands/webdriverio.externalAddCommandHelper.js

This file is just a helper file and should not be executed. Moved it into a helper directory.

> node examples/commands/webdriverio.selectBy.js

That script had no output, it will now output that it ran successfully

> node examples/multiremote/webdriverio.multiremote.js

That script had no output but it will no return that it ran successfully.

> node examples/multiremote/webdriverio.multiremote.chat.js

As stated in [README](https://github.com/webdriverio/webdriverio/tree/master/examples/multiremote#webdriveriomultiremotechatjs) it should get executed with mocha binary

> ./node_modules/.bin/mocha examples/multiremote/webdriverio.multiremote.chat.js --timeout 9999999
> ~/webdriverio/node_modules/mocha/lib/suite.js:340
>   test.timeout(this.timeout());

Not sure why this was failing, it runs also without setting timeout. Removed timeout param in readme.

> ########## Page Object Example ##########

That example had to be executed within the directory of the example. I made this more flexible.

> node examples/standalone/webdriverio.with.mocha.js
> ~/webdriverio/examples/standalone/webdriverio.with.mocha.js:4
> describe('my webdriverio tests', function(){
> ^
> 
> ReferenceError: describe is not defined

You need to run all these with the desired framework binary.

> AssertionError:  title is "The world's leading software development platform · GitHub" but should be "How people build software · GitHub

This assertion was outdated, fixed it

> Error: Custom reporters must export a unique 'reporterName' property

Fixed.

> ./bin/wdio examples/wdio/wdio.multiremote.conf.js

The url was not available anymore, fixed!

> ./bin/wdio examples/wdio/wdio.webdrivercss.conf.js

I am not sure if that ever run, maybe with v3. I removed these files.

Thanks for looking into it. Like all examples in all frameworks they outdate from time to time. That is where I want to see the community jumping in and update them. It is a great way to start contributing.
