### ISSUE TITLE
unable to get screenshots and wdio session is not terminated properly BaseReporter.js:336

### ISSUE THREAD

**Issue by straweb** [webdriverio/webdriverio#2149]
## unable to get screenshots and wdio session is not terminated properly
```
project\node_modules\webdriverio\build\lib\utils\BaseReporter.js:336
                        throw _iteratorError;
                        ^
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at AllureReporter.<anonymous> (project\node_modules\wdio-allure-reporter\build\reporter.js:134:52)
    at emitOne (events.js:96:13)
    at AllureReporter.emit (events.js:188:7)
    at BaseReporter.handleEvent (project\node_modules\webdriverio\build\lib\utils\BaseReporter.js:324:35)
    at Launcher.messageHandler (project\node_modules\webdriverio\build\lib\launcher.js:623:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
[01:29:37]      Failed to take screenshot on reject:     {"message":"no such window: target window already closed\nfrom unknown error: web view not found","type":"RuntimeError","seleniumStack":{"status":23,"type":"NoSuchWindow","message":"A request to switch to a different window could not be satisfied because the window could not be found.","orgStatusMessage":"no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=58.0.3029.110)\n  (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc56791 ... (1134 more bytes)"}}
```

## Environment

* WebdriverIO version: 4.4.0
* Node.js version: v6.9.4 npm 3.10.10
* wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):

## Details
Earlier I can see error screenshots but in parent folder instead of taking .errorShots/ folder location which is given in config. for some errors its not taking errorshots at all and terminating.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-allure-reporter#44
