### ISSUE TITLE
windows 10 - The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.

### ISSUE THREAD

**Issue by hajarghaem** [webdriverio/webdriverio#2153]
It is not really an isuue for me any more but I wanted to described my way of fixing this issue for others.
## The problem

The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.

## Environment

* Node.js version:
* windows 10
* Following: http://webdriver.io/guide.html
## Details

In windows 10 I followed http://webdriver.io/guide.html
Then I found that it does not work on Firefox for me. So changed "firefox" to "Chrome" then I needed to setup "chromedriver" https://sites.google.com/a/chromium.org/chromedriver/getting-started.
But it still did work,
**1- I had to put my chromedrive into the "webdriverio-test" folder
2- in step 4. Start selenium standalone server:**
I used: **java -jar -Dwebdriver.chrome.driver="chromedriver_win32\chromedriver.exe" selenium-server-standalone-3.0.1.jar**

Then it worked.

**Comment by christian-bromann** [comment]
Similar too Geckodriver you have to specify the Chromedriver too. Or have both driver within your PATH.

**Comment by hajarghaem** [comment]
Hi @christian-bromann,

I use webdriveio in node.js in windows 10.
I could not yet set up it working with Firefox.
Could you please let me know if there is a straightforward instruction documentation for it?
Erros:
09:31:29.858 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
09:31:29.897 INFO - Executing: [new session: Capabilities [{rotatable=true, marionette=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1a8b7a39, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}]])
09:31:29.904 INFO - Creating a new session for Capabilities [{rotatable=true, marionette=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1a8b7a39, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}]
1498203090389   geckodriver     INFO    Listening on 127.0.0.1:46434
09:31:30.895 INFO - Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
1498203090975   geckodriver::marionette INFO    Starting browser \\?\C:\Program Files (x86)\Mozilla Firefox\firefox.exe with args ["-marionette"]
1498203091411   addons.manager  ERROR   startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VAJLUE)a v[anSscIrFiiplte .ecrrreoart:e ]r"e s onusrrce://gre/meosduullte:s /"A0dxd8o0n0M7an0a0g5e7r .(jNsSm_,E RlRiOnRe_ I1L6L5E7GA:L _NVSA_LEURER)O"R _ NlOoTc_aItNiIoTnI:A L"IJZSE D: AddonManager is not firnaimtei a:l:i zrede
ource://gre/modules/FileUtils.jsm :: FileUtils_getDir :: line 70"  data: no] Stack trace: FileUtils_getDir()@resource://gre/modules/FileUtils.jsm:70 < FileUtils_getFile()@resource://gre/modules/FileUtils.jsm:42 < validateBlocklist()@resource://gre/modules/AddonManager.jsm:674 < startup()@resource://gre/modules/AddonManager.jsm:837 < startup()@resource://gre/modules/AddonManager.jsm:3145 < observe()@resource://gre/components/addonManager.js:65
[GFX1]: Potential driver version mismatch ignored due to missing DLLs igd10umd32 v= and igd10iumd32.dll v=0.0.0.0
1498203093541   Marionette      INFO    Listening on port 59573
JavaScript error: resource://gre/modules/AddonManager.jsm, line 2572: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
09:31:34.141 INFO - Falling back to original OSS JSON Wire Protocol.
09:31:34.145 INFO - Falling back to straight W3C remote end connection
09:31:34.155 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'DESKTOP-6CTUPFQ', ip: '192.168.21.178', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:131)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:189)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'DESKTOP-6CTUPFQ', ip: '192.168.21.178', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:96)
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:64)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:86)
        ... 9 more
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{rotatable=true, marionette=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1a8b7a39, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@2e0f66d8, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@2e0f66d8, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'DESKTOP-6CTUPFQ', ip: '192.168.21.178', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:259)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:247)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:242)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135)
        ... 14 more
09:31:34.170 WARN - Exception: Unable to create new remote session. desired capabilities = Capabilities [{rotatable=true, marionette=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1a8b7a39, firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@2e0f66d8, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@2e0f66d8, requestOrigins={name=webdriverio, version=4.6.2, url=http://webdriver.io}}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'DESKTOP-6CTUPFQ', ip: '192.168.21.178', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver



Thanks in advance,
Kind regards,
Hajar

**Comment by hajarghaem** [comment]
@christian-bromann,
selenium-server-standalone-3.0.1.jar in Windows just work with Chrome and not Firefox.
But
selenium-server-standalone-3.4.0.jar in Windows just work with both **Chrome** (java -jar -Dwebdriver.chrome.driver="C:\chromedriver_win32\chromedriver.exe" selenium-server-standalone-3.4.0.jar) and **Firefox** (java -jar -Dwebdriver.gecko.driver=geckodriver.exe selenium-server-standalone-3.4.0.jar).

It might be better of yo change step4 in http://webdriver.io/guide.html into:
java -jar -Dwebdriver.gecko.driver=./geckodriver selenium-server-standalone-3.4.0.jar
