### ISSUE TITLE
click toggle switch using click method is not working

### ISSUE THREAD

**Issue by rsugirthan** [webdriverio/webdriverio#2177]
the HTML Element looks like

`<div class="toggleButton" ng-class="{checked: settings.$storage.enabledApps[app.name]}" ng-click="settings.apps.toggleApp(app.name)"><input class="workplayEnabled switch" type="checkbox" ng-checked="settings.$storage.enabledApps[app.name]"></div>`

i tried `browser.click('.toggleButton .switch')` and `browser.click('.toggleButton')` and `browser.click(' .switch')` 

but it's not working
it throws the error as element not visible

whereas if i try `browser.isSelected('.toggleButton .switch')` and `browser.isSelected('.toggleButton')` and `browser.isSelected(' .switch')` it returns false

**Comment by christian-bromann** [comment]
Can you provide some Selenium logs please?

**Comment by rsugirthan** [comment]
@christian-bromann Here is the log

I have directly used the xpath to click it

23:44:25.702 INFO - Executing: [find element: By.xpath: /html/body/div[2]/div/div[1]/div/div[1]/div/div[1]/div[3]/input])
23:44:25.749 INFO - Done: [find element: By.xpath: /html/body/div[2]/div/div[1]/div/div[1]/div/div[1]/div[3]/input]
23:44:25.757 INFO - Executing: [click: 0 [[ChromeDriver: chrome on MAC (2cd2444ce5baa4469d317948e7d99f86)] -> xpath: /html/body/div[2]/div/div[1]/div/div[1]/div/div[1]/div[3]/input]])
23:44:27.446 WARN - Exception thrown
org.openqa.selenium.ElementNotVisibleException: element not visible
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 33 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'SRAMACHANDRAN-MBP', ip: 'fe80:0:0:0:1000:8bf3:56cb:cd48%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262), userDataDir=/var/folders/qw/r1by6c694ml9660x5t1xdy4m0000gp/T/.org.chromium.Chromium.c1simR}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 2cd2444ce5baa4469d317948e7d99f86
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:272)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:332)
	at com.sun.proxy.$Proxy5.click(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.click(EventFiringWebDriver.java:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
	at com.sun.proxy.$Proxy6.click(Unknown Source)
	at org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:30)
	at org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
23:44:27.448 WARN - Exception: element not visible
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 33 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'SRAMACHANDRAN-MBP', ip: 'fe80:0:0:0:1000:8bf3:56cb:cd48%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262), userDataDir=/var/folders/qw/r1by6c694ml9660x5t1xdy4m0000gp/T/.org.chromium.Chromium.c1simR}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.115, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: 2cd2444ce5baa4469d317948e7d99f86
23:44:27.637 INFO - Executing: [delete session: 04b5777a-6bd9-491f-b0ee-196f9c638067])
23:44:27.710 INFO - Done: [delete session: 04b5777a-6bd9-491f-b0ee-196f9c638067]

**Comment by christian-bromann** [comment]
Are you sure the element is indeed visible?

**Comment by christian-bromann** [comment]
If the element is not visible (display:none or visibility:hidden) chrome can't click on it

**Comment by rsugirthan** [comment]
Yeah...element is not visible, so closing the task, thanks @christian-bromann
