### ISSUE TITLE
wdio wdio.conf.js not working node 8.1.3 windows 8.

### ISSUE THREAD

**Issue by gowram** [webdriverio/webdriverio#2211]
When i try to run wdio i am getting below error logs, although i installed "wdio-mocha-framework", its not getting recognized. 
 

```txt
ERROR: Couldn't load "wdio-mocha-framework" framework. You need to install it with `$ npm install wdio-mocha-framework`!
Error: Cannot find module 'wdio-mocha-framework'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Runner.initialiseFramework (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\build\lib\runner.js:517:24)
    at Runner._callee$ (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\build\lib\runner.js:100:55)
    at tryCatch (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)

    at Runner.initialiseFramework (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\build\lib\runner.js:523:23)
    at Runner._callee$ (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\build\lib\runner.js:100:55)
    at tryCatch (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\r.venkatachalam\AppData\Roaming\npm\node_modules\webdriverio\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13

```

This is my wdio.conf.js file 

```js
exports.config = {  
    specs: [
        './test/specs/**/*.js'
    ],  
    maxInstances: 10,    
    capabilities: [{
        maxInstances: 5,
        browserName: 'firefox'
    }],   
    sync: true,   
    logLevel: 'silent',   
    coloredLogs: true,    
    bail: 0,   
    screenshotPath: './errorShots/',   
    baseUrl: 'http://localhost',    
    waitforTimeout: 10000,   
    connectionRetryTimeout: 90000,   
    connectionRetryCount: 3,   
    mochaOpts: {
        ui: 'bdd'
    }   
}
```

**Comment by christian-bromann** [comment]
Please use node v7 until we published the new node fibers version to wdio-sync. Thanks!
