### ISSUE TITLE
wdio.conf.ejs not created

### ISSUE THREAD

**Issue by sarahdayan** [webdriverio/webdriverio#2215]
## The problem

I experienced the exact same problem as [#1568](https://github.com/webdriverio/webdriverio/issues/1568) that was closed back then but reported again by [aztack](https://github.com/aztack).

When I try to configure Webdriver IO after installing it, I get an error just after going through the question interface:

```
=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? mocha
? Shall I install the framework adapter for you? Yes
? Where are your test specs located? ./test/*.js
? Which reporter do you want to use?  spec - https://github.com/webdriverio/wdio-spec-reporter
? Shall I install the reporter library for you? Yes
? Do you want to add a service to your test setup?  selenium-standalone - https://github.com/webdriverio/wdio-selenium-standalone
-service
? Shall I install the services for you? Yes
? Level of logging verbosity command
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://localhost

Installing wdio packages:

Packages installed successfully, creating configuration file...
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/sarahdayan/Projets/communitytalk.com/node_modules/webdriverio/build/lib/helpers/wdio.conf.ejs'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at renderConfigurationFile (/Users/sarahdayan/Projets/communitytalk.com/node_modules/webdriverio/build/lib/cli.js:292:28)
    at /Users/sarahdayan/Projets/communitytalk.com/node_modules/webdriverio/build/lib/cli.js:282:17
    at /Users/sarahdayan/Projets/communitytalk.com/node_modules/npm-install-package/index.js:31:5
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
npm ERR! Test failed.  See above for more details.
```

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.1.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Standalone

## Detail

I managed to curcumvent the problem by saying no to framework installation and skipping the selection of a reporter and adding a service to my test setup:

```
? Shall I install the framework adapter for you? No
? Which reporter do you want to use?
? Do you want to add a service to your test setup?
```

I then installed them and edited the `wdio.conf.js` manually but that's not ideal.

Thanks in advance!

**Comment by christian-bromann** [comment]
Can you try with Node v7.x?

**Comment by sarahdayan** [comment]
@christian-bromann Just tried with several versions of Node (v6.11.1, v7.0.0, v8.1.3, v8.2.1) and oddly, all passed 😶 Maybe something was wrong with my local copy of Node when I tried it the first time.

I guess anyone with the same problem would only need to reinstall or upgrade Node and that should do it.

**Comment by jtheodore-rent** [comment]
I'm getting the same issue - using node v8.1.2

**Comment by istana** [comment]
I bumped into the same problem: node 8.2.1+yarn  doesn't work v0.27.5, node 8.2.1 + npm 5.3.0 works, node 7.10.1 + yarn works. Any ideas where the problem can be?

```
=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? cucumber
? Shall I install the framework adapter for you? Yes
? Where are your feature files located? ./features/**/*.feature
? Where are your step definitions located? ./features/step-definitions
? Which reporter do you want to use?  spec - https://github.com/webdriverio/wdio-spec-reporter
? Shall I install the reporter library for you? Yes
? Do you want to add a service to your test setup?  selenium-standalone - https://github.com/webdriverio/wdio-selenium-standalone-service,  phantomjs - https://github.com/cognitom/wdio-phantomjs-serv
ice
? Shall I install the services for you? Yes
? Level of logging verbosity silent
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://localhost
```

the error is the same
