### ISSUE TITLE
WebDriverIO + PhantomJS - An element could not be located

### ISSUE THREAD

**Issue by HouCoder** [webdriverio/webdriverio#2264]
## The problem

Unable to locate element even the page is fully loaded, element is exist and visible in PhantomJS.

## Environment

* WebdriverIO version: v4.6.2
* Node.js version: v6.11.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): The WDIO Testrunner
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous
* Additional wdio packages used (if applicable): None

## Link to Selenium/WebdriverIO logs

Log detail:

```
[phantomjs #0-1] Session ID: 0c90e270-8e02-11e7-bc78-8d79367915fe
[phantomjs #0-1] Spec: /home/Tonni/TonniProjects/ui-library/tests/webdriver.io/tasks/slider/default.js
[phantomjs #0-1] Running: phantomjs
[phantomjs #0-1]
[phantomjs #0-1] default slider
[phantomjs #0-1]   1) scroll right and left
[phantomjs #0-1]
[phantomjs #0-1]
[phantomjs #0-1] 1 failing (9s)
[phantomjs #0-1]
[phantomjs #0-1] 1) default slider scroll right and left:
[phantomjs #0-1] An element could not be located on the page using the given search parameters (".slick-arrow[data-action="next"]").
[phantomjs #0-1] Error: An element could not be located on the page using the given search parameters (".slick-arrow[data-action="next"]").
[phantomjs #0-1]     at Promise.F (node_modules/core-js/library/modules/_export.js:35:28)
[phantomjs #0-1]     at click() - at Context.it (tests/webdriver.io/tasks/slider/default.js:34:15)
[phantomjs #0-1]
```

## Code To Reproduce Issue [ Good To Have ]

This is the test code snippet I used:

```js
it('scroll right and left', () => {
    const next = '.slick-arrow[data-action="next"]';
    const previous = '.slick-arrow[data-action="previous"]';

    const $next = $(next);
    const $previous = $(previous);

    browser.waitUntil(
        () => {
            // Use regular function declaration for browser compatibility issues.
            // eslint-disable-next-line prefer-arrow-callback
            const state = browser.execute(function getReadState() {
                return document.readyState;
            });
            return state.value === 'complete';
        },
        60000
    );

    browser.waitUntil(
        () => {
            return $next.isExisting() && $next.isVisible();
        },
        60000
    );

    // Error: An element could not be located...
    $next.click();
});
```

**Comment by christian-bromann** [comment]
```js
it('scroll right and left', () => {
    const next = '.slick-arrow[data-action="next"]';
    browser.waitForVisible(next)
    $(next).click();
});
```

will work. It is not needed to wait for the document ready state. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by HouCoder** [comment]
thanks for your answer. @ChrisOelmueller
