### ISSUE TITLE
Module not found: step-definitions

### ISSUE THREAD

**Issue by echonox** [webdriverio/webdriverio#2286]
## The problem

When running a feature i am getting module not found issue, it can't find the step definitions

## Environment

* WebdriverIO version: latest
* Node.js version:  v6.11.3
* webdriverio testrunner
* sync tests
* wdio-cucumber-framework, wdio-selenium-standalone-service

## Details

When I run my feature file i get module not found, it says that it can't find the step definitions but the step definitions are there, my project worked fine, and no suddenly i am getting this error:

ERROR: Cannot find module 'C:\Users\jack-\Documents\Klender\selenium\features\step-definitions'

    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\build\adapter.js:226:46
    at Array.forEach (native)
    at CucumberAdapter.loadSpecFiles (C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\build\adapter.js:218:39)
    at CucumberAdapter._callee$ (C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\build\adapter.js:129:38)
    at tryCatch (C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\node_modules\regenerator-runtime\runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\node_modules\regenerator-runtime\runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at Promise.F (C:\Users\jack-\Documents\Klender\selenium\node_modules\core-js\library\modules\_export.js:35:28)
    at CucumberAdapter.<anonymous> (C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)
    at CucumberAdapter.run (C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\build\adapter.js:193:29)
    at Object._callee2$ (C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\build\adapter.js:328:40)
    at tryCatch (C:\Users\jack-\Documents\Klender\selenium\node_modules\wdio-cucumber-framework\node_modules\regenerator-runtime\runtime.js:65:40)
√ 0 passed
× 0 failed
. 0 pending

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test-single" "--" "--spec" "./features/single/personal.feature"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! klender@1.3.0 test-single: `wdio wdio.conf.single.js "--spec" "./features/single/personal.feature"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the klender@1.3.0 test-single script 'wdio wdio.conf.single.js "--spec" "./features/single/personal.feature"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the klender package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     wdio wdio.conf.single.js "--spec" "./features/single/personal.feature"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs klender
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls klender
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jack-\Documents\Klender\selenium\npm-debug.log

**Comment by christian-bromann** [comment]
Please see https://github.com/webdriverio/wdio-cucumber-framework#require

**Comment by ehtesham1981** [comment]
@christian-bromann The path you have shared is not solving the problem. I have also started facing same situation on CircleCI. Although my scripts are working fine on local windows machine but on CircleCI is says ```module not found``` for steps definition. Although step definition file location is available and shown in error message as well but not sure that is preventing webdriverio to read it.

**Comment by christian-bromann** [comment]
@ehtesham1981 you are probably running two different wdio-cucumber-framework versions in both environments.

**Comment by echonox** [comment]
@cagdastulek sorry i didn't notice there was a new major upgrade, so i was using old config with the latest version

**Comment by ehtesham1981** [comment]
@ChrisOelmueller Thanks. Is there a way to compare these versions? So far I can only see wdio version which is identical on both environments i.e. v4.6.2

**Comment by ChrisOelmueller** [comment]
Probably looking to ping @christian-bromann instead ;-)

**Comment by christian-bromann** [comment]
please see my comment above

**Comment by walternolasco** [comment]
@christian-bromann Hello, Can you please give me a hand on this. I have no globbing in the require for the step definitions and it is always throwing me the described error at the beginning of this post.
some related info of my environment:
cucumberOpts: {
require: ['./runner-specs/cucumber/features/step_definitions/']
}
on the Json package:
"devDependencies": {
    "cucumber": "^3.0.4",
    "wdio-cucumber-framework": "^1.0.2",
    "wdio-selenium-standalone-service": "0.0.9",
    "webdriverio": "^4.8.0"
  }

Thanks in advance!

**Comment by junzhuang** [comment]
I have been struggling with the same issue @walternolasco reported for about a week. 

If i only provide the folder containing the step definitions, ./features/step-definitions, I got the "ERROR: Cannot find module 'C:\Automation\features\stepDefinitions' (I run .\node_modules\.bin\wdio wdio.conf.js from the Automation dir).  If I provide the step definition file, ./features/step_definitions/xyx.steps.js, it complains the steps were not defined. I run on Windows 10.

Please help.
Jun

**Comment by walternolasco** [comment]
@junzhuang Please see this post for solution:
https://github.com/webdriverio/wdio-cucumber-framework/issues/79

Also, try to update the syntax of the step definitionsfiles to last one. (That's what I did and I got it working now.)
New syntax example here:
https://github.com/amiya-pattnaik/webdriverIO-with-cucumberBDD

**Comment by junzhuang** [comment]
@walternolasco Thanks for the quick response. I added the helper but it's still not finding the step definition files.

// Following few lines are from https://github.com/webdriverio/wdio-cucumber-framework/issues/79
const stepsFolder = './step-definitions';
const fs = require('fs');

var stepDefinitionFiles = [];
fs.readdirSync(stepsFolder).forEach(file => {
    step = stepsFolder + '/' + file;
    stepDefinitionFiles.push(step);
  });

cucumberOpts: {
       require: stepDefinitionFiles, ...}

### This is my folder structure $$$
C:\Automation
   - node_modeules
   - features
   - step-definitions
the wdio.conf.js is in the Automation dir.

### Execution output ###
C:\Automation>.\node_modules\.bin\wdio wdio.conf.js

[14:38:48]  COMMAND     POST     "/wd/hub/session"
[14:38:48]  DATA                {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":5,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.9.11","name":"webdriverio"}}}
[14:38:51]  INFO        SET SESSION ID 0246074a14659957a944ff88a41edd7d
[14:38:51]  RESULT              {"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":false,"chrome":{"chromedriverVersion":"2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f)","userDataDir":"C:\\Users\\JUN~1.ZHU\\AppData\\Local\\Temp\\scoped_dir13368_12155"},"takesHeapSnapshot":true,"pageLoadStrategy":"normal","databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"version":"63.0.3239.84","platform":"Windows NT","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true,"setWindowRect":true,"unexpectedAlertBehaviour":""}
FFFFFF[14:38:51]  COMMAND       DELETE   "/wd/hub/session/0246074a14659957a944ff88a41edd7d"
[14:38:51]  DATA                {}


0 passing (6.00s)
6 failing

1) Item added to grocery list6 I have an empty grocery list:
Step "I have an empty grocery list" is not defined. You can ignore this error by setting
                              cucumberOpts.ignoreUndefinedDefinitions as true.
running chrome
C:\Automation\features\add-item.feature:7

**Comment by walternolasco** [comment]
@junzhuang Understood. 
You can try to update the syntax code of the step definitions files. 
New syntax example here:
https://github.com/amiya-pattnaik/webdriverIO-with-cucumberBDD
Or you can download that boilerplate ^^ and use it according to your needs.
