### ISSUE TITLE
ELIFECYCLE while running webdriverio mocha test

### ISSUE THREAD

**Issue by Gobliins** [webdriverio/webdriverio#2367]
The error:
```
npm ERR! Linux 4.4.4-200.fc22.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "wdio-test"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! wekan@0.10.1 wdio-test: `wdio tests/config/wdio.mocha.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wekan@0.10.1 wdio-test script 'wdio tests/config/wdio.mocha.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wekan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     wdio tests/config/wdio.mocha.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wekan
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wekan
npm ERR! There is likely additional logging output above.
```

The log:
```
11 silly lifecycle wekan@0.10.1~wdio-test: Args: [ '-c', 'wdio tests/config/wdio.mocha.conf.js' ]
12 silly lifecycle wekan@0.10.1~wdio-test: Returned: code: 1  signal: null
13 info lifecycle wekan@0.10.1~wdio-test: Failed to exec wdio-test script
14 verbose stack Error: wekan@0.10.1 wdio-test: `wdio tests/config/wdio.mocha.conf.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

My config:
```js
exports.config = {

  /*** server configurations*/
  host: '0.0.0.0',
  port: 32772,
  mongoUrl: 'mongodb://127.0.0.1:24001/meteor',

  /*** specify test files */
  specs: [
    './tests/wdio/ui/**',
    './tests/wdio/unit/**',
  ],
  exclude: [
  ],

  /*** capabilities */
  capabilities: [{
    browserName: 'chrome',
  }],

  /*** test configurations */
  logLevel: 'info',
  coloredLogs: true,
  screenshotPath: 'shots',
  waitforTimeout: 10000,

  reporters: ['dot', 'junit'],
  reporterOptions: {
    junit: {
      outputDir: './test_results',
    },
  },

  mochaOpts: {
    ui: 'bdd',
    compilers: ['js:babel-register'],
    require: ['babel-polyfill'],
  },

  /**hooks*/
  onPrepare: function() {
    console.log('let\'s go');
  },
  onComplete: function() {
    console.log('that\'s it');
  }
};
```

Packages:
`"wdio-junit-reporter": "^0.3.1",
 "wdio-mocha-framework": "^0.5.11",
 "webdriverio": "^4.8.0"` 

The tests run all and end with an outprint of "that's it" but then i get the ELIFECYCLE....

Why am i getting this error?

**Comment by christian-bromann** [comment]
Not sure why that is. Do you have any other logs or can you create a reproducible example?

**Comment by christian-bromann** [comment]
Closing due to inactivity
