### ISSUE TITLE
My local webdriverio build doesn't work

### ISSUE THREAD

**Issue by codiophile** [webdriverio/webdriverio#2401]
## The problem

1. I checked out my fork of `webdriverio`.
2. I made some changes to my fork.
3. I built `webdriverio` and installed it as a dependency of my project.
4. I ran my project and it crashed.
5. I repeated the above, without my changes and with `v4.8.0`, so that everything should be the same, but I had the same problem.
6. I ran a diff and it turns out that my version is quite different from the one downloaded from `npm`.

I've never attempted something like this before, so maybe I'm doing something wrong? Please have a look at my code to reproduce and tell me if there is something missing.

I can share the error I'm getting with you, if you think that is relevant, but I feel like the problem is simply that I'm not able to reproduce the build from `npm`.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: 8.7.0
* npm version: 5.5.1

## Code To Reproduce Issue

    git clone git@github.com:webdriverio/webdriverio.git
    cd webdriverio
    git checkout v4.8.0
    npm install
    npm run build
    npm pack

This produces a file named `webdriverio-4.8.0.tgz`. I change the `package.json` file of my project to depend on this file rather than `webdriverio` from `npm`. Like so:

    "webdriverio": "file:../webdriverio/webdriverio-4.8.0.tgz",

Running `npm install` in my project, updates `webdriverio` in `node_modules` as expected, except my version is different from the `npm` version, despite presumably being based on the same code.

I've never built a node module before, so I appreciate that I might have missed something, but the resources I've found online seem to indicate that the above should be enough. Also if there is a better way to accomplish what I'm trying to accomplish, I'd appreciate the feedback.

**Comment by christian-bromann** [comment]
> I can share the error I'm getting with you, if you think that is relevant

This is the only relevant thing I need. Please share

**Comment by codiophile** [comment]
Here's the error:

    65457 Sun Nov 05 2017 15:57:05 GMT+0000 INFO
    /Users/user/git/project/node_modules/webdriverio/build/lib/utils/BaseReporter.js:336
                            throw _iteratorError;
                            ^

    TypeError: Cannot read property 'start' of undefined
        at JsonReporter.combineJsons (/Users/user/git/project/node_modules/wdio-json-reporter/build/reporter.js:296:42)
        at JsonReporter.<anonymous> (/Users/user/git/project/node_modules/wdio-json-reporter/build/reporter.js:105:23)
        at emitOne (events.js:115:13)
        at JsonReporter.emit (events.js:210:7)
        at BaseReporter.handleEvent (/Users/user/git/project/node_modules/webdriverio/build/lib/utils/BaseReporter.js:324:35)
        at Launcher.endHandler (/Users/user/git/project/node_modules/webdriverio/build/lib/launcher.js:651:28)
        at emitTwo (events.js:125:13)
        at ChildProcess.emit (events.js:213:7)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

    Process finished with exit code 1

I thought it wasn't relevant, because I thought the problem was simply that I couldn't reproduce the build.

**Comment by christian-bromann** [comment]
@codiophile I think the way you checked out the package and bundled it was fine. It has a problem with the json reporter for some reasons. Probably just a flake. Definitely not a bug.

**Comment by codiophile** [comment]
@christian-bromann Did you try it yourself? If I do a diff between the webdriverio I built and the one downloaded from npm, there are a lot of differences. I could share this as well, but the diff file is over 500 lines. I might as well: https://gist.github.com/codiophile/0ba8e8c6e9eaa158c866f53c3ee41ac0

I can see why there are differences in `package.json`, considering that it saves the source of the module, but other than that I don't think there should be any differences, unless webdriverio 4.8.0 wasn't built from the tag `v4.8.0`.

Either way, this is blocking me from testing my webdriverio changes in my project, so I would appreciate if you could help me fix this. I have the same problem when I checkout `master`. The reporter only works when when I use `4.8.0` from `npm`.

**Comment by christian-bromann** [comment]
@codiophile not sure why this error appears. Just don't use the json reporter while you are testing this.

**Comment by codiophile** [comment]
@christian-bromann  Just FYI, I managed to break my environment. Not exactly sure how, but after reinstalling node, cloning everything again, and  reinstalling the dependencies, the above worked as expected.

**Comment by christian-bromann** [comment]
@codiophile I am glad it worked for you. I am just moments away from publishing v4.9.0 but stuck in meetings so far

**Comment by codiophile** [comment]
@christian-bromann I tried the tip of master today with our framework and it didn't work, but it does work with the v4.8.0 tag. I'm not on my work computer now, so I don't have the logs here, but I can get them if you're interested. I would assume that 4.9.0 isn't supposed to have any breaking changes.

**Comment by christian-bromann** [comment]
nope

**Comment by codiophile** [comment]
Alright, I see that you've made some changes since then, so I'll try with latest master and we'll see if it works.

**Comment by codiophile** [comment]
@christian-bromann  Here's the error:

    91472 Wed Nov 08 2017 17:29:40 GMT+0000 INFO ERROR: Protocol "https:" not supported. Expected "http:"
    91472 Wed Nov 08 2017 17:29:40 GMT+0000 INFO 
    91472 Wed Nov 08 2017 17:29:40 GMT+0000 INFO     at new RuntimeError (/Users/user/sandbox/project/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
        at Request._callback (/Users/user/sandbox/project/node_modules/webdriverio/build/lib/utils/RequestHandler.js:315:43)
        at self.callback (/Users/user/sandbox/project/node_modules/webdriverio/node_modules/request/request.js:186:22)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:191:7)
        at Request.start (/Users/user/sandbox/project/node_modules/webdriverio/node_modules/request/request.js:750:10)
        at Request.write (/Users/user/sandbox/project/node_modules/webdriverio/node_modules/request/request.js:1498:10)
        at end (/Users/user/sandbox/project/node_modules/webdriverio/node_modules/request/request.js:546:18)
        at Immediate.<anonymous> (/Users/user/sandbox/project/node_modules/webdriverio/node_modules/request/request.js:575:7)
        at runCallback (timers.js:672:20)

Will rerun soon with latest master. I'll open a separate issue if it persists.

**Comment by codiophile** [comment]
@christian-bromann Actually, it was the latest. The commit that came in after only changed documentation. So I guess the tests are a bit flaky, if that commit fails the build?

**Comment by codiophile** [comment]
@christian-bromann Created issue #2417

**Comment by nithya2murali** [comment]
@christian-bromann  
I am using node version : v11.10.1 & npm is 6.7.0
Is it possible to let me know which version of node and npm currently resolves the same issue . /node_modules/webdriverio/build/lib/utils/BaseReporter.js:336
                        throw _iteratorError;
                        ^

TypeError: Cannot read property 'includes' of undefined
    at WdioMochawesomeReporter.<anonymous> (/Users/mselvanambi/projectsrepo/e4c-integration/node_modules/wdio-mochawesome-reporter/build/reporter.js:102:56)
    at emitOne (events.js:116:13)
    at WdioMochawesomeReporter.emit (events.js:211:7)
    at BaseReporter.handleEvent (/Users/mselvanambi/projectsrepo/e4c-integration/node_modules/webdriverio/build/lib/utils/BaseReporter.js:324:35)
    at Launcher.endHandler (/Users/mselvanambi/projectsrepo/e4c-integration/node_modules/webdriverio/build/lib/launcher.js:618:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! e4c-integration@1.0.0 test: `./node_modules/webdriverio/bin/wdio .wdio.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the e4c-integration@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
