### ISSUE TITLE
4.9.2 doesn't support https

### ISSUE THREAD

**Issue by codiophile** [webdriverio/webdriverio#2417]
## The problem

I checked out the latest master to make sure that it was working with our framework and it tells me that `Protocol "https:" not supported. Expected "http:"`. 4.8.0 did no have this problem.

Tested this on 4.9.2 on a different system and the problem persists.

## Environment

* WebdriverIO version: 4.9.2
* Node.js version: 7.10.1
* wdio testrunner mode
* synchronous

## Logs

    91472 Wed Nov 08 2017 17:29:40 GMT+0000 INFO ERROR: Protocol "https:" not supported. Expected "http:"
    91472 Wed Nov 08 2017 17:29:40 GMT+0000 INFO 
    91472 Wed Nov 08 2017 17:29:40 GMT+0000 INFO     at new RuntimeError (/Users/user/sandbox/project/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
        at Request._callback (/Users/user/sandbox/project/node_modules/webdriverio/build/lib/utils/RequestHandler.js:315:43)
        at self.callback (/Users/user/sandbox/project/node_modules/webdriverio/node_modules/request/request.js:186:22)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:191:7)
        at Request.start (/Users/user/sandbox/project/node_modules/webdriverio/node_modules/request/request.js:750:10)
        at Request.write (/Users/user/sandbox/project/node_modules/webdriverio/node_modules/request/request.js:1498:10)
        at end (/Users/user/sandbox/project/node_modules/webdriverio/node_modules/request/request.js:546:18)
        at Immediate.<anonymous> (/Users/user/sandbox/project/node_modules/webdriverio/node_modules/request/request.js:575:7)
        at runCallback (timers.js:672:20)

## Code To Reproduce Issue 

I suppose the key is to set the protocol to https:

    config.protocol = 'https';

**Comment by christian-bromann** [comment]
@codiophile what is the way to reproduce this issue?

**Comment by codiophile** [comment]
@christian-bromann Well, for me I just run our framework with latest webdriverio. It runs against perfecto over https. I assumed simply using https causes this issue, but I haven't tried it in isolation. Could be that the framework is doing something else as well, that causes this. I'll see if I can reproduce it in isolation. Does it not reproduce for you?

**Comment by christian-bromann** [comment]
> Does it not reproduce for you?

Never had this error before

**Comment by codiophile** [comment]
It seems to be a bug in `/lib/utils/RequestHandler.js`. Using `https.Agent` instead of `http.Agent` solves the problem.

A colleague of mine is working on a fix.
