### ISSUE TITLE
wdio 'wizard' fails to install dependencies

### ISSUE THREAD

**Issue by leegee** [webdriverio/webdriverio#2420]
Fresh install via npm, and run `wdio`, fails to install dependencies.
```

C:\Users\User\src\izel (master)
λ wdio

=========================
WDIO Configuration Helper
=========================

? Where do you want to execute your tests? On my local machine
? Which framework do you want to use? mocha
? Shall I install the framework adapter for you? Yes
? Where are your test specs located? ./tests/wd/**/*.js
? Which reporter do you want to use?  spec - https://github.com/webdriverio/wdio-spec-reporter
? Shall I install the reporter library for you? Yes
? Do you want to add a service to your test setup?
? Level of logging verbosity silent
? In which directory should screenshots gets saved if a command fails? ./errorShots/
? What is the base url? http://localhost

Installing wdio packages:

Packages installed successfully, creating configuration file...

Configuration file was created successfully!
To run your tests, execute:

$ wdio wdio.conf.js


C:\Users\User\src\izel (master)
λ wdio wdio.conf.js
C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:158
                        throw _iteratorError;
                        ^

Error: reporter "wdio-spec-reporter" is not installed. Error: Error: Cannot find module 'wdio-spec-reporter'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Launcher.initReporters (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:133:40)
    at new Launcher (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:69:31)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\cli.js:424:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at Launcher.initReporters (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:135:35)
    at new Launcher (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:69:31)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\cli.js:424:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)

C:\Users\User\src\izel (master)
λ
```

So I tried to install it:

```
C:\Users\User\src\izel (master)
λ npm install wdio-spec-reporter
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\User\src\izel\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\User\src\izel\package.json'
npm WARN izel No description
npm WARN izel No repository field.
npm WARN izel No README data
npm WARN izel No license field.

+ wdio-spec-reporter@0.1.2
updated 1 package in 1.257s

C:\Users\User\src\izel (master)
λ wdio wdio.conf.js
C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:158
                        throw _iteratorError;
                        ^

Error: reporter "wdio-spec-reporter" is not installed. Error: Error: Cannot find module 'wdio-spec-reporter'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Launcher.initReporters (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:133:40)
    at new Launcher (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:69:31)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\cli.js:424:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at Launcher.initReporters (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:135:35)
    at new Launcher (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\launcher.js:69:31)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\webdriverio\build\lib\cli.js:424:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
```

**Comment by christian-bromann** [comment]
@leegee could be that you have WebdriverIO installed globally? You need to run the local installed wdio command that is in your node modules.
