### ISSUE TITLE
webdriverio turns webpack plugins into plain objects

### ISSUE THREAD

**Issue by ianwremmel** [webdriverio/webdriverio#2427]
## The problem

Somewhere greater than 4.8.0 and less than or equal to 4.9.5, full compatibility with the wdio-webpack-service broke. Specifically, it looks like something is causing instantiated webpack plugins to turn into plain objects, thus producing the following error:

```
TypeError: arguments[i].apply is not a function
    at Compiler.apply (/Users/iremmel/projects/spark-js-sdk/node_modules/tapable/lib/Tapable.js:381:16)
    at webpack (/Users/iremmel/projects/spark-js-sdk/node_modules/webpack/lib/webpack.js:33:19)
    at StaticServerLauncher.onPrepare (/Users/iremmel/projects/spark-js-sdk/node_modules/wdio-webpack-service/build/launcher.js:121:45)
    at /Users/iremmel/projects/spark-js-sdk/node_modules/webdriverio/build/lib/launcher.js:402:66
    at Array.map (native)
    at Launcher._callee2$ (/Users/iremmel/projects/spark-js-sdk/node_modules/webdriverio/build/lib/launcher.js:400:71)
    at tryCatch (/Users/iremmel/projects/spark-js-sdk/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/iremmel/projects/spark-js-sdk/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/iremmel/projects/spark-js-sdk/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/iremmel/projects/spark-js-sdk/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
```

## Environment

* WebdriverIO version: >=4.8.0
* Node.js version: 7.2.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asynchronous tests:
* Additional wdio packages used (if applicable):
```
   "wdio-junit-reporter": "^0.3.1",
    "wdio-mocha-framework": "^0.5.11",
    "wdio-sauce-service": "^0.4.0",
    "wdio-selenium-standalone-service": "0.0.9",
    "wdio-spec-reporter": "^0.1.2",
    "wdio-static-server-service": "^1.0.1",
    "wdio-webpack-service": "^1.0.1",
    "webdriverio": "4.8.0",
```

## Details

`TypeError: arguments[i].apply is not a function` is supposed to be an instance of a plugin (in my case, the webpack EnvironmentPlugin), but somehow gets turned into a plain object by webdriverio.

## Link to Selenium/WebdriverIO logs

See error above, nothing else gets printed before that failure.

## Code To Reproduce Issue [ Good To Have ]

A webpack config with a non-empty plugins array and a wdio config that includes `{webpackConfig: ...}`

**Comment by christian-bromann** [comment]
probably related to #2428

**Comment by christian-bromann** [comment]
#2428 is merged and I will make a release now.
