### ISSUE TITLE
knownScreenshotCommands.includes is not a function webdriverio/build/lib/utils/ReporterStats.js:396

### ISSUE THREAD

**Issue by ViaMay** [webdriverio/webdriverio#2439]
## The problem
try run autotest. Have a error:
[08:40:06]  COMMAND	POST 	 "/wd/hub/session"
[08:40:07][Step 5/6] [08:40:06]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":1,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.9.6","name":"webdriverio"}}}
[08:40:10][Step 5/6] [08:40:09]  INFO	SET SESSION ID 18e5e9c88935f1225fda6213c1eda065
[08:40:10][Step 5/6] [08:40:09]  RESULT		{"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":false,"chrome":{"chromedriverVersion":"2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4)","userDataDir":"/home/ubuntu/BuildAgent/temp/buildTmp/.org.chromium.Chromium.H2SaKy"},"takesHeapSnapshot":true,"pageLoadStrategy":"normal","databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"version":"60.0.3112.90","platform":"Linux","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true,"setWindowRect":true,"unexpectedAlertBehaviour":""}
[08:40:10][Step 5/6] discover test (running for 4s)
[08:40:10][discover test] discover checked song cards (5s)
[08:40:10][Step 5/6] [08:40:10]  COMMAND	POST 	 "/wd/hub/session/18e5e9c88935f1225fda6213c1eda065/url"
[08:40:10][Step 5/6] [08:40:10]  DATA		{"url":"https://staging.songline.fm/staging/"}
[08:40:12][Step 5/6] /home/ubuntu/BuildAgent/work/aa3f0c1998b88593/node_modules/webdriverio/build/lib/utils/ReporterStats.js:396
[08:40:12][Step 5/6]             } else if (type === 'aftercommand' && knownScreenshotCommands.includes(runner.command)) {
[08:40:12][Step 5/6]                                                                           ^
[08:40:12][Step 5/6] 
[08:40:12][Step 5/6] TypeError: knownScreenshotCommands.includes is not a function
[08:40:12][Step 5/6]     at ReporterStats.output (/home/ubuntu/BuildAgent/work/aa3f0c1998b88593/node_modules/webdriverio/build/lib/utils/ReporterStats.js:396:75)
[08:40:12][Step 5/6]     at BaseReporter.<anonymous> (/home/ubuntu/BuildAgent/work/aa3f0c1998b88593/node_modules/webdriverio/build/lib/utils/BaseReporter.js:123:25)
[08:40:12][Step 5/6]     at emitOne (events.js:90:13)
[08:40:12][Step 5/6]     at BaseReporter.emit (events.js:182:7)
[08:40:12][Step 5/6]     at BaseReporter.handleEvent (/home/ubuntu/BuildAgent/work/aa3f0c1998b88593/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)
[08:40:12][Step 5/6]     at Launcher.messageHandler (/home/ubuntu/BuildAgent/work/aa3f0c1998b88593/node_modules/webdriverio/build/lib/launcher.js:624:28)
[08:40:12][Step 5/6]     at emitTwo (events.js:100:13)
[08:40:12][Step 5/6]     at ChildProcess.emit (events.js:185:7)
[08:40:12][Step 5/6]     at handleMessage (internal/child_process.js:718:10)
[08:40:12][Step 5/6]     at Pipe.channel.onread (internal/child_process.js:444:11)
[08:40:12][Step 5/6] npm ERR! Test failed.  See above for more details.

![screenshot_21](https://user-images.githubusercontent.com/10914859/32716914-9f49e0e2-c879-11e7-9f55-57550db2394e.png)

## Environment
* WebdriverIO version: version":"4.9.6"
* Node.js version: v5.12.0
* my wdio.conf.js [wdio.conf.txt](https://github.com/webdriverio/webdriverio/files/1465980/wdio.conf.txt)
* linux ubuntu 64 (headless)
* chrome chrome64_61.0.3163.79.deb "version":"60.0.3112.90"
* selenium-server-standalone-3.6.0.jar (start on: xvfb-run --server-args="-screen 0, 1024x740x24" ./node_modules/.bin/selenium-standalone start)
* "chromedriverVersion":"2.33.506092"

## Details
this is an error when running tests appeared recently. About 5 days ago. The launch code did not change.

## Link to Selenium/WebdriverIO logs
log TC 
[SongLine_Auto_tests-Webdriver_Run_Auto_test_1238.log](https://github.com/webdriverio/webdriverio/files/1466098/SongLine_Auto_tests-Webdriver_Run_Auto_test_1238.log)

**Comment by christian-bromann** [comment]
This issue was fixed and published with v4.9.8

**Comment by ViaMay** [comment]
@christian-bromann  when to wait for the update?
I have the "webdriverio" setting: "^ 4.6.2" in package.json

but when I run npm install I download webdriverio@4.9.6
![screenshot_24](https://user-images.githubusercontent.com/10914859/32723982-4edc2364-c891-11e7-9165-655dce50395c.png)

**Comment by ViaMay** [comment]
@christian-bromann I find - we had release 1 house ago
