### ISSUE TITLE
browser.toggleWiFi( ): encountered internal error running the command

### ISSUE THREAD

**Issue by glovertd** [webdriverio/webdriverio#2442]
## The problem

browser.toggleWiFi( ) is giving me an internal error when running the command.  Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined

## Environment

* WebdriverIO version: 4.8.0 , appium 1.7.1
* Node.js version: 8.9.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): Testrunner
* if wdio testrunner, running synchronous or asynchronous tests: Asynchronous
* Additional wdio packages used (if applicable): 
"dependencies": {
    "appium": "^1.6.5",
    "blink-diff": "^1.0.13",
    "chai": "^4.0.2",
    "cucumber": "^2.3.1",
    "lodash": "^4.17.4",
    "moment": "^2.19.1",
    "node-rest-client": "~3.1.0",
    "request": "^2.81.0",
    "request-promise": "^4.2.1",
    "wdio-appium-service": "^0.2.3",
    "wdio-cucumber-framework": "^0.3.1",
    "wdio-junit-reporter": "^0.3.0",
    "wdio-sauce-service": "^0.4.0",
    "wdio-spec-reporter": "^0.1.0",
    "webdriverio": "^4.8.0",
    "inquirer": "^3.3.0"
  }

## Details

[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/1cdb65e2-4c25-4424-a780-7acd7c16c678/appium/device/toggle_wifi] to [POST http://localhost:8200/wd/hub/session/a961cac9-5420-47e5-9ed7-a088db62be14/appium/device/toggle_wifi] with body: {}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:384:13)
    at tryCatch (/Users/glovt007/.npm-packages/es/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/glovt007/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/glovt007/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/glovt007/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>

## Link to Selenium/WebdriverIO logs

[appium.log](https://github.com/webdriverio/webdriverio/files/1467649/appium.log)

## Code To Reproduce Issue [ Good To Have ]

this.When (/^I toggle wifi$/, () => {
    // toggle wifi on/off
    browser.toggleWiFi ();
  });

**Comment by christian-bromann** [comment]
@glovertd this is not an issue of WebdriverIO and should be reported in the Appium project.
