### ISSUE TITLE
New version is broken when running in nodemon (or any other wrapper).

### ISSUE THREAD

**Issue by SzybkiSasza** [webdriverio/webdriverio#2491]
## The problem

When running the launcher programatically from within the code that is run in dev mode (or any other mode using wrappers like `nodemon`) args are passed incorrectly that causes the code to break on babelified version of the code.

Example error:
```
 TypeError: Invalid attempt to destructure non-iterable instance
    at /Users/bartek/Desktop/tenfold/repos/att/node_modules/babel-runtime/helpers/slicedToArray.js:49:13
    at Launcher.startInstance (/Users/bartek/Desktop/tenfold/repos/att/node_modules/webdriverio/build/lib/launcher.js:565:78)
    at Launcher.runSpecs (/Users/bartek/Desktop/tenfold/repos/att/node_modules/webdriverio/build/lib/launcher.js:504:22)
    at /Users/bartek/Desktop/tenfold/repos/att/node_modules/webdriverio/build/lib/launcher.js:354:47
    at new Promise (<anonymous>)
    at new F (/Users/bartek/Desktop/tenfold/repos/att/node_modules/core-js/library/modules/_export.js:35:28)
    at Launcher._callee$ (/Users/bartek/Desktop/tenfold/repos/att/node_modules/webdriverio/build/lib/launcher.js:348:40)
    at tryCatch (/Users/bartek/Desktop/tenfold/repos/att/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/bartek/Desktop/tenfold/repos/att/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/bartek/Desktop/tenfold/repos/att/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/bartek/Desktop/tenfold/repos/att/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/bartek/Desktop/tenfold/repos/att/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>

```

## Environment

* WebdriverIO version: 4.9.11
* Node.js version: 8.9.1
* wdio testrunner: sync mode

## Details

I believe this error was introduced by this exact commit:

https://github.com/webdriverio/webdriverio/commit/f878fbaa78f8d083e6fe0dacad5f770166b7ff96

The simplest fix would include changing this line:
```
let [, type, host] = process.execArgv[i].match('--(debug|inspect)(?:-brk)?(?:=(.*):)?')
```

to something like that:

```
let matchingArgs = process.execArgv[i].match('--(debug|inspect)(?:-brk)?(?:=(.*):)?')
if (matchingArgs) { // or check for the array
   let [, type, host] = matchingArgs;
}
```

**Comment by SzybkiSasza** [comment]
Confirmed - providing the fix mentioned above fixes the issue.

**Comment by SzybkiSasza** [comment]
This is PR fixing the issue: 
https://github.com/webdriverio/webdriverio/pull/2492/commits

**Comment by christian-bromann** [comment]
PR is merged and will be released asap

**Comment by albertogasparin** [comment]
@christian-bromann Can we get a new release with this fix please?
