### ISSUE TITLE
wdio failed to start ( connect ECONNREFUSED 127.0.0.1:4444 )

### ISSUE THREAD

**Issue by zjh1943** [webdriverio/webdriverio#2517]
## The problem

When network is good, wdio works well.
When network is bad, I can't start wdio. It shows:
```shell
[18:11:31] Using gulpfile ~/Project/ones/ones-ai-web/gulpfile.js
[18:11:31] Starting 'e2e'...
A service failed in the 'onPrepare' hook
Error: Could not request headers from https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-macos.tar.gz: Error: socket hang up
    at Request.<anonymous> (/Users/zjh/Project/ones/ones-ai-web/node_modules/selenium-standalone/lib/install.js:552:8)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/zjh/Project/ones/ones-ai-web/node_modules/selenium-standalone/node_modules/request/request.js:845:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at TLSSocket.emit (events.js:221:7)

Continue...
[18:11:33]  COMMAND	POST 	 "/wd/hub/session"
[18:11:33]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":5,"browserName":"chrome","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.9.11","name":"webdriverio"}}}
ERROR: connect ECONNREFUSED 127.0.0.1:4444
chrome
    at new RuntimeError (/Users/zjh/Project/ones/ones-ai-web/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:144:12)
    at Request._callback (/Users/zjh/Project/ones/ones-ai-web/node_modules/webdriverio/build/lib/utils/RequestHandler.js:327:43)
    at self.callback (/Users/zjh/Project/ones/ones-ai-web/node_modules/webdriverio/node_modules/request/request.js:186:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/zjh/Project/ones/ones-ai-web/node_modules/webdriverio/node_modules/request/request.js:878:8)
    at emitOne (events.js:130:20)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)

[18:11:33] 'e2e' errored after 2.11 s
[18:11:33] Error in plugin 'gulp-shell'
Message:
    Command `./node_modules/.bin/wdio wdio.conf.js` failed with exit code 1
```

## Environment

* WebdriverIO version: 4.2.3
* Node.js version: v9.0.0
* wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: not reached.
* Additional wdio packages used (if applicable): mocha chai

## Details

It fetch the header of  `https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-macos.tar.gz` every time when I start the wdio. I think it is absolutely not necessary. Can't it be cached ? Is there anyway to close the function of fetching at every starting. Or if it failed to fetch header, just ignore it ?

---
addtion:

I see the log. It involves `selenium-standalone install` at the starting. Cant it just involve `selenium-standalone start` after installed?

## Link to Selenium/WebdriverIO logs

Log is above. All is there.

**Comment by christian-bromann** [comment]
Please report this issue here: https://github.com/vvo/selenium-standalone

**Comment by zjh1943** [comment]
@christian-bromann Can you please say something more about it ? About why you think it is the problem of `selenium-standalone`. It is the `selenium-stantalone` who invoke `selenium-stantalone install` at every starting? No the fault of `wdio` ? Thank you. Someone post this issue on repository of `selenium-standalone`. They said it is the fault of `wdio`. I'm so confused...

**Comment by christian-bromann** [comment]
> Someone post this issue on repository of selenium-standalone

Can you reference a link to it?

IMO it is the responsibility of the `selenium-standalone` package to check if it already installed its driver dependencies and don't do it again.

**Comment by zjh1943** [comment]
@christian-bromann What is `IMO` ?  Sorry, I'm a Chinese developer, not that good at English.

**Comment by christian-bromann** [comment]
IMO stands for "in my opinion". I think this issue should get addressed in the selenium-standalone package not in WebdriverIO

**Comment by zjh1943** [comment]
@christian-bromann OK, thank you very much for your help.
