### ISSUE TITLE
add support for session retries

### ISSUE THREAD

**Issue by dalimian** [webdriverio/webdriverio#2521]
we been using mocha's suite retries as mentioned in http://webdriver.io/guide/testrunner/retry.html and they have been great, they stabilized our CD pipeline alot.

There are cases, however, that are not caught with the above. we're using browserstack, but have had similar issues with saucelabs, - every once in a while there is an issue like session could not start, browser couldn't start, browser froze, session died, a before() block failed, etc, and these issues are not caught by any of retries in http://webdriver.io/guide/testrunner/retry.html . now these issues are rare, say 1/100, but when you run 300 specs that's 30% chance of false positive.

to work around this in my project we made a wrapper to run wdio programatically, and rerun failed specs/sessions . this has proved to be helpful, reduced 30% down to almost 0% false positives. I would be happy to share that code here but i think this should be integrated into core wdio, something like a `--sessionRetries` or `--specRetries` param.

**Comment by christian-bromann** [comment]
@dalimian you can retry the whole spec in Mocha if you apply `retries: x` in your mocha opts. Can you try this?

**Comment by christian-bromann** [comment]
Closing due to inactivity

**Comment by dalimian** [comment]
@christian-bromann sorry been busy then vacation. I tried retries:x in mocha options, it does same as calling this.retries() from the test - they retry only the the failed `it()` blocks so the `before()` does not run on retry for example. the sol i above does that and more importantly it creates a new browserstack/saucelab session

**Comment by christian-bromann** [comment]
> they retry only the the failed it() blocks so the before() does not run on retry for example

The Mocha retry functionality actual should do that, at least the last time I tested it

**Comment by jbartek25** [comment]
The Mocha retry functionality unfortunately doesn't re-run before(): https://mochajs.org/#retry-tests. We've been struggling with occasional transient failures in Sauce Labs and it would help greatly to have the ability to retry failed session as @dalimian suggested.

**Comment by fijijavis** [comment]
We are experiencing the same problem.  Just yesterday it happened probably 4-5 times.  If I happen to figure anything out I’ll reply here.

**Comment by dalimian** [comment]
@fijijavis, @jbartek25, to run the `before()` on retries try this workaround - https://github.com/mochajs/mocha/issues/3077

then if u want session retries on top of that, feel free to try running wdio via this wrapper (for the time being until this is part of wdio core)

1.  add the following reporter to your wdio config - (for more info http://webdriver.io/guide/testrunner/reporters.html)
```
/**
 * failed-suite-reporter.js
 */
const events = require('events');
const path = require('path');
const fs = require('fs');
const mkdirp = require('mkdirp');

/**
 * Webdriver.io reporter.
 * @param baseReporter reporter
 * @param config config
 * @param options options
 * @constructor constructor
 */
class FailedSuiteReporter extends events.EventEmitter {
  static get reporterName() {
    return 'FailedSuiteReporter';
  }

  constructor(baseReporter, config, options = {}) {
    super();
    this.failures = [];
    this.outputDir = options.outputDir || './reports/';

    this.on('test:fail', (data) => {
      this.failures.push(data);
    });

    this.on('end', () => {
      const dir = path.resolve(this.outputDir);
      const filepath = path.join(dir, 'failed-suite-reporter.json');
      mkdirp.sync(dir);
      fs.writeFileSync(filepath, JSON.stringify(this.failures));
      console.log('Wrote report to ', filepath);
    });
  }
}
  - 
/**
 * Expose Custom Reporter
 */
module.exports = FailedSuiteReporter;
exports = module.exports;
```

then, add the following to your wdio config file:
```
const FailedSuiteReporter = require('./failed-suite-reporter');

exports.config = {
  // ...
  reporters: [FailedSuiteReporter]
}

```

2. run wdio through this wrapper

```
/**
 * wdio-runner.js
 * this is a wrapper for running wdio programatically instead of directly via shell
 * http://webdriver.io/guide/testrunner/gettingstarted.html#Run-the-test-runner-programmatically
 * purpose of this wrapper is so that it re-runs wdio for failed specs
 *
 * you may invoke this from shell the same way you do wdio except instead of
 * $ wdio <wdio params>
 * you would do
 * node wdio-runner.js <wdio params> --spec_retries 2
 * 
 * note: this wrapper depends on wdio being configured with failed-suite-reporter.js 
 */
const fs = require('fs');
const { Launcher } = require('webdriverio');
const path = require('path');
const { argv } = require('yargs');

const buildNumber = argv.build_number;

const retries = 'spec_retries' in argv ? argv.spec_retries : 0;

if ('spec' in argv) {
  delete argv.suite; // workaround for https://github.com/webdriverio/webdriverio/issues/2514
}

const configPath = argv._[0];
const { config } = require(path.resolve(configPath));

const reporterDir = path.resolve(config.reporterOptions.outputDir);

function getFailedSpecs() {
  const filepath = path.join(reporterDir, 'failed-suite-reporter.json');
  try {
    const failures = JSON.parse(fs.readFileSync(filepath));
    let files = [];
    failures.forEach((failure) => { files = files.concat(failure.specs); });
    return [...new Set(files)]; // remove duplicates
  } catch (e) {
    return false;
  }
}

let runAttempt = 1;

function getOptionsForRetry() {
  const files = getFailedSpecs();
  if (!(files && files.length)) {
    return argv;
  }
  console.log(`[wdio-runner] ${files.length} specs failed:\n${files.join('\n')}`);
  const { site_module, spec, suite, ...optionsForRetry } = argv;
  // optionsForRetry gets all props from option except site_module, spec, suite
  optionsForRetry.spec = files.join(',');
  if (optionsForRetry.build_number) {
    runAttempt += 1;
    optionsForRetry.build_number = `${buildNumber}-attempt-${runAttempt}`;
  }
  return optionsForRetry;
}

/**
 * starts wdio and returns a Promise that resolves when the task completes
 * http://webdriver.io/guide/testrunner/gettingstarted.html#Run-the-test-runner-programmatically
 * @param options cmd line arguments
 * @returns Promise
 */
function run(options) {
  if (options.build_number) {
    process.env.BUILD_NUMBER = options.build_number;
    delete require.cache[path.resolve(configPath)];
  }
  const wdio = new Launcher(configPath, options);
  return wdio.run();
}

(function loop(options, retriesLeft) {
  console.log('[wdio-runner] starting wdio');
  run(options)
    .then((exitCode) => {
      if (exitCode === 0) { // success
        console.log('[wdio-runner] wdio completed, exit code', exitCode);
        process.exit(0);
      }
      return Promise.reject(exitCode);
    })
    .catch((error) => {
      console.log('[wdio-runner] wdio failed with exit code/error:', error, '\nretries left: ', retriesLeft);
      if (retriesLeft <= 0) {
        process.exit(typeof error === 'number' ? error : 1);
      }
      const optionsForRetry = getOptionsForRetry();
      if (optionsForRetry.spec && optionsForRetry.spec.split(',').length > 10) {
        console.log('[wdio-runner] failed specs will not be retried because over 10');
        process.exit(typeof error === 'number' ? error : 1);
      }
      loop(optionsForRetry, retriesLeft - 1);
    });
}(argv, retries));


```

**Comment by jbartek25** [comment]
Thank you @dalimian. I'll check it out.

**Comment by logakarthi** [comment]
@jbartek25 
Where to keep the above failed-suite-reporter.js & wdio-runnjer.js files in the project. And also how to mention spec_retries in the command to run the suite test case 

Anyone knows means, please tell me.
Thanks.

**Comment by anthonypdawson** [comment]
I think this is still a problem and would be useful to have session retries built into WDIO.  I can't change to use a custom wrapper without breaking many other things.

**Comment by christian-bromann** [comment]
@anthonypdawson we have session retries now: https://webdriver.io/docs/retry/#add-retries-on-a-per-specfile-basis

**Comment by mainak-basu22** [comment]
The retry specified in  https://webdriver.io/docs/retry/#add-retries-on-a-per-specfile-basis is helpful, but still somehow being able to retry a session creation only will be more helpful. Below is a scenario -

The test tries to connect to a dynamic selenium grid running in Kubernetes, and for some reason the API gateway throws a Gateway timeout error , maybe because the grid took a while to spin up a new pod. In this case, just retrying a session creation is more helpful, while having "specFileRetries" enabled will retry any failure which might not always be the intent.

**Comment by christian-bromann** [comment]
> just retrying a session creation is more helpful, while having "specFileRetries" enabled will retry any failure which might not always be the intent.

@mainak-basu22 WDIO already retries every WebDriver request at least 3 times, due to the https://webdriver.io/docs/configuration#connectionretrycount setting. Do you have this enabled?

**Comment by mainak-basu22** [comment]
@christian-bromann  Yes I do have the following in my config file, but also I do not see any retry happening for this step where it fails. It does trigger on other scenarios.

  **connectionRetryTimeout: 150000,
  connectionRetryCount: 3,**



**Error from Wdio Run logs**

[0-11] ERROR webdriver: Error: WebDriverError: Unexpected token '<', "<html>
[0-11] <h"... is not valid JSON when running "https://someurl/services/selenium-grid/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"cjson:metadata":{"device":"Linux","platform":{"name":"Linux","version":"5.15.0-1079-azure"},"buildUrl":"https:/jenkinsurl/123/“,”workerId":"0-11","spec":"file:///home/jenkins/agent/workspace/abc/dist/tmp/test.feature"},"browserName":"chrome","goog:chromeOptions":{"excludeSwitches":["enable-automation"],"useAutomationExtension":false,"args":["--no-sandbox","--disable-dev-shm-usage","--disable-web-security","--test-type=browser","--disable-gpu","--disable-features=NetworkService,DownloadBubble,DownloadBubbleV2,InterestFeedContentSuggestions,Translate","--ignore-certificate-errors","--allow-running-insecure-content","--disable-extensions","--disable-component-extensions-with-background-pages","--disable-default-apps","--no-default-browser-check","--disable-client-side-phishing-detection","--ash-no-nudges","--disable-background-networking"]},"webSocketUrl":true,"unhandledPromptBehavior":"ignore"},"firstMatch":[{}]}}"
[0-11]     at FetchRequest._libRequest (file:///home/jenkins/agent/workspace/abc/node_modules/webdriver/build/node.js:1756:13)
[0-11]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-11]     at async FetchRequest._request (file:///home/jenkins/agent/workspace/abc/node_modules/webdriver/build/node.js:1766:20)
[0-11]     at async startWebDriverSession (file:///home/jenkins/agent/workspace/abc/node_modules/webdriver/build/node.js:1098:16)
[0-11]     at async _WebDriver.newSession (file:///home/jenkins/agent/workspace/abc/node_modules/webdriver/build/node.js:1336:41)
[0-11]     at remote (/home/jenkins/agent/workspace/abc/node_modules/webdriverio/build/node.js:8730:20)
[0-11]     at async Runner._startSession (file:///home/jenkins/agent/workspace/abc/node_modules/@wdio/runner/build/index.js:815:23)
[0-11]     at async Runner._initSession (file:///home/jenkins/agent/workspace/abc/node_modules/@wdio/runner/build/index.js:789:22)
[0-11]     at async Runner.run (file:///home/jenkins/agent/workspace/abc/node_modules/@wdio/runner/build/index.js:696:16)



As in the logs, the errro is not for all the workers in aparallel run, but only for few when selenium hub returns the below Gateway time out error and more so because Keda takes a while to spin up new pods under heavy load

```
<html>
<head>
	<title>504 Gateway Time-out</title>
</head>
<body>
	<center>
		<h1>504 Gateway Time-out</h1>
	</center>
	<hr>
	<center>nginx</center>
</body>
</html>
```

**Comment by mainak-basu22** [comment]
@christian-bromann  Sure, below is a simple example 

Mimic a gateway timeout error from a api gateway behind which is the selenium grid. I am using a simple server using express, with an endpoint /wd/hub which will throw the error. The timeout is not  necessarily required.

`
// A simple express.js server with an endpoint /wd/hub/session that mimics a gateway timeout error
import express from 'express';
const app = express();

// Simulate a Gateway Timeout error
app.post('/wd/hub/session', (req, res) => {
  console.log('POST /wd/hub/session');
  // Simulate a delay
  setTimeout(() => {
    res.status(504).send(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>504 Gateway Time-out</title>
      </head>
      <body>
        <center>
          <h1>504 Gateway Time-out</h1>
        </center>
        <hr>
        <center>nginx</center>
      </body>
      </html>
    `);
  }, 10000); 
});

app.get('/', (req, res) => {
  res.send('Welcome to the API Gateway Timeout Simulator!');
});

const PORT = 3000;
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
`

We can use a simple starter project generated by the wdio init command. I am using cucumber. In the wdio.conf.js add the host name to point to our mock server

`
    hostName: 'localhost',
    port: 3000,
    path: '/wd/hub',
    protocol: 'http',
`

You can then either run it using the wdio run ./wdio.conf.js or even using the Launcher code below

`
import { Launcher } from "@wdio/cli";
const wdio = new Launcher(`${process.cwd()}/wdio.conf.js`);

wdio.run().then((code) => {
    process.exit(code);
});
`


In the case where the server returns a json instead of the html the connectionRetry does trigger, but when an html is sent, like one that nginx ingress will send incase of a timeout the connection retry does not trigger and the execption is thrown.

**Comment by robgonnella** [comment]
I'm experiencing the same issue even when the the server returns JSON. This can be reproduced by running against a remote grid and setting timeouts as follows

```
{
...
  connectionRetryTimeout: 2000,
  connectionRetryCount: 10
...
}
```

With this setup I see the following error during session initialization and no retries

```
[0-0] 2025-06-07T23:01:22.077Z DEBUG @wdio/runner: init remote session
[0-0] 2025-06-07T23:01:22.079Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2025-06-07T23:01:22.079Z INFO @wdio/utils: Connecting to existing driver at http://grid:4444/wd/hub
[0-0] 2025-06-07T23:01:22.080Z INFO webdriver: [POST] http://grid:4444/wd/hub/session
[0-0] 2025-06-07T23:01:24.084Z ERROR webdriver: Error: WebDriverError: The operation was aborted due to timeout when running "http://grid:4444/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"chrome","moon:options":{"name":"1"},"goog:chromeOptions":{"args":["headless","disable-gpu"]},"webSocketUrl":true,"unhandledPromptBehavior":"ignore"},"firstMatch":[{}]}}"
[0-0]     at FetchRequest._libRequest (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1918:13)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async FetchRequest._request (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1928:20)
[0-0]     at async startWebDriverSession (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1059:16)
[0-0]     at async _WebDriver.newSession (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1497:41)
[0-0]     at remote (/app/node_modules/webdriverio/build/node.js:8775:20)
[0-0]     at async Runner._startSession (file:///app/node_modules/@wdio/runner/build/index.js:818:23)
[0-0]     at async Runner._initSession (file:///app/node_modules/@wdio/runner/build/index.js:792:22)
[0-0]     at async Runner.run (file:///app/node_modules/@wdio/runner/build/index.js:699:16)
[0-0] 2025-06-07T23:01:24.119Z ERROR @wdio/runner: Error: WebDriverError: The operation was aborted due to timeout when running "http://grid:4444/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"chrome","moon:options":{"name":"1"},"goog:chromeOptions":{"args":["headless","disable-gpu"]},"webSocketUrl":true,"unhandledPromptBehavior":"ignore"},"firstMatch":[{}]}}"
[0-0]     at startWebDriverSession (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1063:11)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async _WebDriver.newSession (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1497:41)
[0-0]     at remote (/app/node_modules/webdriverio/build/node.js:8775:20)
[0-0]     at async Runner._startSession (file:///app/node_modules/@wdio/runner/build/index.js:818:23)
[0-0]     at async Runner._initSession (file:///app/node_modules/@wdio/runner/build/index.js:792:22)
[0-0]     at async Runner.run (file:///app/node_modules/@wdio/runner/build/index.js:699:16)
[0-0] 2025-06-07T23:01:24.119Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
2025-06-07T23:01:24.236Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///src/selenium/bots/cm-dma-realtime.bot.ts
2025-06-07T23:01:24.236Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2025-06-07T23:01:24.236Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
```

Similarly, if I run locally (no remote grid) using same timeout, I see the same error with no retries

```
[0-0] 2025-06-07T23:02:26.398Z DEBUG @wdio/runner: init remote session
[0-0] 2025-06-07T23:02:26.399Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2025-06-07T23:02:26.783Z INFO webdriver: Setting up chrome v137.0.7151.68
[0-0] 2025-06-07T23:02:26.784Z INFO webdriver: Using Chromedriver v137.0.7151.68 from cache directory /var/folders/fh/ths0gpyj3hvg09sy3qjvyjgr0000gn/T
[0-0] 2025-06-07T23:02:27.055Z INFO chromedriver: Starting ChromeDriver 137.0.7151.68 (2989ffee9373ea8b8623bd98b3cb350a8e95cadc-refs/branch-heads/7151@{#1873}) on port 57420
[0-0] 2025-06-07T23:02:27.056Z INFO chromedriver: Remote connections are allowed by an allowlist (0.0.0.0).
[0-0] 2025-06-07T23:02:27.056Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[0-0] 2025-06-07T23:02:27.057Z INFO chromedriver: ChromeDriver was started successfully on port 57420.
[0-0] 2025-06-07T23:02:27.097Z INFO @wdio/utils: Started Chromedriver v137.0.7151.68 with params --port=57420 --allowed-origins=* --allowed-ips=0.0.0.0 in 633ms on port 57420
[0-0] 2025-06-07T23:02:27.100Z INFO webdriver: [POST] http://localhost:57420/session
[0-0] 2025-06-07T23:02:29.100Z ERROR webdriver: Error: WebDriverError: The operation was aborted due to timeout when running "http://localhost:57420/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"chrome","moon:options":{"name":"billId"},"goog:chromeOptions":{"binary":"/var/folders/fh/ths0gpyj3hvg09sy3qjvyjgr0000gn/T/chrome/mac_arm-137.0.7151.68/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing","prefs":{"profile.password_manager_leak_detection":false}},"webSocketUrl":true,"unhandledPromptBehavior":"ignore"},"firstMatch":[{}]}}"
[0-0]     at FetchRequest._libRequest (file:///Users/robert/code/papaya-pay/autopay/node_modules/webdriverio/node_modules/webdriver/build/node.js:1918:13)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async FetchRequest._request (file:///Users/robert/code/papaya-pay/autopay/node_modules/webdriverio/node_modules/webdriver/build/node.js:1928:20)
[0-0]     at async startWebDriverSession (file:///Users/robert/code/papaya-pay/autopay/node_modules/webdriverio/node_modules/webdriver/build/node.js:1059:16)
[0-0]     at async _WebDriver.newSession (file:///Users/robert/code/papaya-pay/autopay/node_modules/webdriverio/node_modules/webdriver/build/node.js:1497:41)
[0-0]     at remote (/Users/robert/code/papaya-pay/autopay/node_modules/webdriverio/build/node.js:8775:20)
[0-0]     at async Runner._startSession (file:///Users/robert/code/papaya-pay/autopay/node_modules/@wdio/runner/build/index.js:818:23)
[0-0]     at async Runner._initSession (file:///Users/robert/code/papaya-pay/autopay/node_modules/@wdio/runner/build/index.js:792:22)
[0-0]     at async Runner.run (file:///Users/robert/code/papaya-pay/autopay/node_modules/@wdio/runner/build/index.js:699:16)
[0-0] 2025-06-07T23:02:29.139Z ERROR @wdio/runner: Error: WebDriverError: The operation was aborted due to timeout when running "http://localhost:57420/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"chrome","moon:options":{"name":"billId"},"goog:chromeOptions":{"binary":"/var/folders/fh/ths0gpyj3hvg09sy3qjvyjgr0000gn/T/chrome/mac_arm-137.0.7151.68/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing","prefs":{"profile.password_manager_leak_detection":false}},"webSocketUrl":true,"unhandledPromptBehavior":"ignore"},"firstMatch":[{}]}}"
[0-0]     at startWebDriverSession (file:///Users/robert/code/papaya-pay/autopay/node_modules/webdriverio/node_modules/webdriver/build/node.js:1063:11)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async _WebDriver.newSession (file:///Users/robert/code/papaya-pay/autopay/node_modules/webdriverio/node_modules/webdriver/build/node.js:1497:41)
[0-0]     at remote (/Users/robert/code/papaya-pay/autopay/node_modules/webdriverio/build/node.js:8775:20)
[0-0]     at async Runner._startSession (file:///Users/robert/code/papaya-pay/autopay/node_modules/@wdio/runner/build/index.js:818:23)
[0-0]     at async Runner._initSession (file:///Users/robert/code/papaya-pay/autopay/node_modules/@wdio/runner/build/index.js:792:22)
[0-0]     at async Runner.run (file:///Users/robert/code/papaya-pay/autopay/node_modules/@wdio/runner/build/index.js:699:16)
[0-0] 2025-06-07T23:02:29.139Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
2025-06-07T23:02:29.254Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///src/selenium/bots/cm-dma-realtime.bot.ts
2025-06-07T23:02:29.254Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2025-06-07T23:02:29.255Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
```

It would be great to have a timeout option just for the initial connection as the time it takes to get an open slot from a remote grid is likely significantly longer than the timeout you'd want applied to all other requests. Another option / workaround would be to allow changing the `connectionRetryTimeout` in hooks. This way you could set a longer timeout in `beforeSession` hook and then set back to a sane default in `before` hook.

Also although I have the timeout set to something too short for any session, I experience the exact same errors and behavior with a timeout of 120000ms (2min) and then using up all available slots in my remote grid for 5min.

**Comment by Nyaran** [comment]
Hi,

I'm getting the error "504 Gateway Time-out" sometimes too and as our Selenium server is behind an nginx server, it returned an HTML, causing the request not being retried.

This only happens on WebdriverIO v9, with v7 and v8 is not happening.

Actually working on a fix, I hope I can make a PR soon.
