### ISSUE TITLE
Cannot go any more with commands, IE Driver

### ISSUE THREAD

**Issue by amado-saladino** [webdriverio/webdriverio#2540]
## The problem
I'm running the same code with Chrome, Firefox and IE, all test pass and work fine with Chrome and Firefox but IE.
Here is the error I get everytime I try to run webdriverIO

> running internet explorer
Error: A request to switch to a different window could not be satisfied because the window could not
 be found.
    at Object.url (C:\Users\Ahmed\Documents\NodeJs\WebdriverIO-demo\node_modules\wdio-sync\build\ind
ex.js:349:27)
    at LoginPage.open (C:\Users\Ahmed\Documents\NodeJs\WebdriverIO-demo\library\BasePage.js:7:11)
    at Context.<anonymous> (C:\Users\Ahmed\Documents\NodeJs\WebdriverIO-demo\test\login.test.js:22:1
9)
    at C:\Users\Ahmed\Documents\NodeJs\WebdriverIO-demo\node_modules\wdio-sync\build\index.js:590:26

    at Promise.F (C:\Users\Ahmed\Documents\NodeJs\WebdriverIO-demo\node_modules\core-js\library\modu
les\_export.js:35:28)
    at Context.executeSync (C:\Users\Ahmed\Documents\NodeJs\WebdriverIO-demo\node_modules\wdio-sync\
build\index.js:588:12)
    at C:\Users\Ahmed\Documents\NodeJs\WebdriverIO-demo\node_modules\wdio-sync\build\index.js:759:42

    at url("login") -     at C:\Users\Ahmed\Documents\NodeJs\WebdriverIO-demo\node_modules\wdio-sync
\build\at Object.wait (C:\Users\Ahmed\Documents\NodeJs\WebdriverIO-demo\node_modules\fibers\future.j
s:449:15)

`browser.waitForExist(selector);
return browser.element(selector);`

**Comment by christian-bromann** [comment]
@amado-saladino thanks for raising the issue. Unfortunately this is not a WebdriverIO issue. Please file an issue in the IEDriver project, Thanks! If you have further questions join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).
