### ISSUE TITLE
`--spec` does not work as documented for filtering by a word in a spec

### ISSUE THREAD

**Issue by zeljkofilipin** [webdriverio/webdriverio#2657]
## The problem

According to [Organizing Test Suites > Run Selected Tests](http://webdriver.io/guide/testrunner/organizesuite.html#Run-Selected-Tests), one should be able to run specs filtered by a word. I have noticed that it does not work in all cases.

## Environment

* WebdriverIO version: v4.12.0
* Node.js version: v9.8.0

## Details

Running all tests in `examples/pageobject` works fine.

```
webdriverio/webdriverio$ ./bin/wdio examples/pageobject/wdio.conf.js 
------------------------------------------------------------------
[chrome #0-0] Session ID: 3ebd3cf1a74127b138819daf6d3d1499
[chrome #0-0] Spec: /Users/z/Documents/github/webdriverio/webdriverio/examples/pageobject/specs/checkbox.spec.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] checkboxes
[chrome #0-0]   ✓ checkbox 2 should be enabled
[chrome #0-0]   ✓ checkbox 1 should be enabled after clicking on it
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 2 passing (4s)
[chrome #0-0]

------------------------------------------------------------------
[chrome #0-2] Session ID: 119333f5ba07f6fd5fdb1f6fe62d1031
[chrome #0-2] Spec: /Users/z/Documents/github/webdriverio/webdriverio/examples/pageobject/specs/form.spec.js
[chrome #0-2] Running: chrome
[chrome #0-2]
[chrome #0-2] auth form
[chrome #0-2]   ✓ should deny access with wrong creds
[chrome #0-2]   ✓ should allow access with correct creds
[chrome #0-2]
[chrome #0-2]
[chrome #0-2] 2 passing (6s)
[chrome #0-2]

------------------------------------------------------------------
[chrome #0-1] Session ID: 6576d88b2712119de002a6eeea1420fa
[chrome #0-1] Spec: /Users/z/Documents/github/webdriverio/webdriverio/examples/pageobject/specs/dynamic.spec.js
[chrome #0-1] Running: chrome
[chrome #0-1]
[chrome #0-1] dynamic loading
[chrome #0-1]   ✓ should be an button on the page
[chrome #0-1]
[chrome #0-1]
[chrome #0-1] 1 passing (9s)
[chrome #0-1]



==================================================================
Number of specs: 3


5 passing (9.50s)
```

Running just one file works fine.

```
webdriverio/webdriverio$ ./bin/wdio examples/pageobject/wdio.conf.js --spec examples/pageobject/specs/dynamic.spec.js 
------------------------------------------------------------------
[chrome #0-0] Session ID: 78d1c2c7212ea951d6b7ffd8cc25f4e6
[chrome #0-0] Spec: /Users/z/Documents/github/webdriverio/webdriverio/examples/pageobject/specs/dynamic.spec.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] dynamic loading
[chrome #0-0]   ✓ should be an button on the page
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 passing (8s)
[chrome #0-0]
```

There is a test called `dynamic loading`. Filtering by `dynamic` works as expected.

```
webdriverio/webdriverio$ ./bin/wdio examples/pageobject/wdio.conf.js --spec dynamic
------------------------------------------------------------------
[chrome #0-0] Session ID: a4c2cea58cb170533442780c60cc4829
[chrome #0-0] Spec: /Users/z/Documents/github/webdriverio/webdriverio/examples/pageobject/specs/dynamic.spec.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] dynamic loading
[chrome #0-0]   ✓ should be an button on the page
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 1 passing (7s)
[chrome #0-0]
```

Filtering by `loading` does not work. 😕

```
webdriverio/webdriverio$ ./bin/wdio examples/pageobject/wdio.conf.js --spec loading
/Users/z/Documents/github/webdriverio/webdriverio/build/lib/utils/ConfigParser.js:274
                        throw new Error(`spec file ${object.spec} not found`);
                        ^

Error: spec file loading not found
    at /Users/z/Documents/github/webdriverio/webdriverio/build/lib/utils/ConfigParser.js:274:31
    at ConfigParser.merge (/Users/z/Documents/github/webdriverio/webdriverio/build/lib/utils/ConfigParser.js:278:19)
    at new Launcher (/Users/z/Documents/github/webdriverio/webdriverio/build/lib/launcher.js:71:27)
    at launch (/Users/z/Documents/github/webdriverio/webdriverio/build/lib/cli.js:441:24)
    at Object.<anonymous> (/Users/z/Documents/github/webdriverio/webdriverio/build/lib/cli.js:458:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

## Link to Selenium/WebdriverIO logs

I do no think logs are required, since the problem is easy to reproduce using `webdriverio/webdriverio` repository, but I can provide them if needed.

## Code To Reproduce Issue [ Good To Have ]

The problem is reproducible using `webdriverio/webdriverio` repository. The only change I have made is changing `dot` to `spec` reporter, for easier debugging.

**Comment by zeljkofilipin** [comment]
`dynamic loading` feature has one test, `should be an button on the page`. I was expecting I would be able to filter by a string from the tests, but it does not work. 😢

```
$ ./bin/wdio examples/pageobject/wdio.conf.js --spec button
/Users/z/Documents/github/webdriverio/webdriverio/build/lib/utils/ConfigParser.js:274
                        throw new Error(`spec file ${object.spec} not found`);
                        ^

Error: spec file button not found
    at /Users/z/Documents/github/webdriverio/webdriverio/build/lib/utils/ConfigParser.js:274:31
    at ConfigParser.merge (/Users/z/Documents/github/webdriverio/webdriverio/build/lib/utils/ConfigParser.js:278:19)
    at new Launcher (/Users/z/Documents/github/webdriverio/webdriverio/build/lib/launcher.js:71:27)
    at launch (/Users/z/Documents/github/webdriverio/webdriverio/build/lib/cli.js:441:24)
    at Object.<anonymous> (/Users/z/Documents/github/webdriverio/webdriverio/build/lib/cli.js:458:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by kmnaid** [comment]
Is it intentional that the pattern matching is being done only on the spec file name and not the file contents?

**Comment by christian-bromann** [comment]
@zeljkofilipin the answer of @kmnaid is correct. Thanks!

**Comment by kmnaid** [comment]
@christian-bromann : It would be nice to update the document to be clear that it matches the spec file name and not the spec.

**Comment by christian-bromann** [comment]
> It would be nice to update the document to be clear that it matches the spec file name and not the spec.

Good idea, feel free to propose a PR
