### ISSUE TITLE
Appium multiremote selectors not working if they differ by device

### ISSUE THREAD

**Issue by zmorris** [webdriverio/webdriverio#2663]
## The problem

(Possibly a feature request) generally can't use `browser.element(<selector>)` with cross-platform apps running on Android and iOS under Appium because selectors to similar-looking elements are often different.  That makes using the [page object pattern](http://webdriver.io/guide/testrunner/pageobjects.html) difficult because we can only use setters like:

```
MyPageObject.clickSomeElement();
```

Rather than getters like:

```
let myElement = MyPageObject.getSomeElement();

myElement.click();
```

The simplest example of this is that getting a WebElement for the `back` button for both Android/iOS is not currently possible.

## Environment

* WebdriverIO version: v4.12.0
* Node.js version: v9.8.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable):
    "chai": "~4.0.1",
    "chai-webdriverio": "^0.4.3",
    "wdio": "^1.0.3",
    "wdio-appium-service": "^0.2.3",
    "wdio-mocha-framework": "^0.5.13",
    "wdio-spec-reporter": "^0.1.4"

## Details

See code section below.

## Link to Selenium/WebdriverIO logs

Skipping logs because the issue might be due to capabilities that aren't implemented yet.

## Code To Reproduce Issue [ Good To Have ]

`package.json`

```
{
  "name": "-",
  "version": "1.0.0",
  "description": "WebDriverIO Appium test",
  "main": "index.js",
  "repository": "-",
  "author": "Zack Morris",
  "license": "MIT",
  "devDependencies": {
    "chai": "~4.0.1",
    "chai-webdriverio": "^0.4.3",
    "wdio": "^1.0.3",
    "wdio-appium-service": "^0.2.3",
    "wdio-mocha-framework": "^0.5.13",
    "wdio-spec-reporter": "^0.1.4"
  }
}
```

`wdio.conf.js`:

```
{
    specs: [
        "./specs/**/*.js"
    ],
    host: "0.0.0.0",
    port: 4723,
    capabilities: {
//     	web: {
//             desiredCapabilities: {
//                 port: 4444,
// 				// maxInstances can get overwritten per capability. So if you have an in-house Selenium
// 				// grid with only 5 firefox instances available you can make sure that not more than
// 				// 5 instances get started at a time.
// 				maxInstances: 5,
// 				browserName: "firefox"
//             }
//         },

        android: {
            port: 4723,
            desiredCapabilities: {
                sessionOverride: true,
                debugLogSpacing: true,
                nativeInstrumentsLib: true,
                isolateSimDevice: true,

                avd: "Galaxy_Nexus_API_19",
                platformName: "Android",
                platformVersion: "4.4",
                deviceName: "Android Emulator",
                app: "<path_to>/Appium-Android-Example.apk"
            }
        },

        ios: {
            port: 4723,
            desiredCapabilities: {
                sessionOverride: true,
                debugLogSpacing: true,
                nativeInstrumentsLib: true,
                isolateSimDevice: true,

                showIosLog: true,
                platformName: "iOS",
                platformVersion: "11.2",
                deviceName: "iPhone 5s",
                app: "<path_to>/Appium-iOS-Example.app"
            }
        },
    },
    sync: true,
    logLevel: "silent",
    coloredLogs: true,
    deprecationWarnings: true,
    bail: 0,
    baseUrl: "http://localhost",
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ["appium"],
    appium: {
        args: {
        }
    },
    framework: "mocha",
    reporters: ["spec"],
    mochaOpts: {
        ui: "bdd"
    },
}
```

`example.js`

```
const chai = require('chai');
const expect = chai.expect; // global.expect = chai.expect;
const chaiWebdriver = require('chai-webdriverio').default;

chai.use(chaiWebdriver(browser));

if ('android' in browser.contexts()) {
    chai.use(chaiWebdriver(browser.select('android')));
}

if ('ios' in browser.contexts()) {
    chai.use(chaiWebdriver(browser.select('ios')));
}

describe('Simple cases', function() {
    this.timeout(300000);

    before(function() {});

    describe("Test native App", function() {
        it("test-function", function() {
            var element = browser.element("~Second");

            console.log(element);

            const androidElement = browser.select('android').element("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.View/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ListView/android.widget.LinearLayout[1]");

            console.log(androidElement);

            const iosElement = browser.select('ios').element("~Second");

            console.log(iosElement);

            element = Object.assign(element, {
                android: androidElement,
                ios: iosElement
            });

            element.click();

            browser.pause(3000);
        });
    });

    after(function() {});
});

```

Output:

```
{ android: 
   { type: 'NoSuchElement',
     message: 'An element could not be located on the page using the given search parameters.',
     state: 'failure',
     sessionId: '94847876-e44d-4a1e-9083-2ddd2fc244bb',
     value: null,
     selector: '~Second' },
  ios: 
   { value: 
      { ELEMENT: 'FE35E1AB-7860-4EA2-A32B-9514C96915F5',
        'element-6066-11e4-a52e-4f735466cecf': 'FE35E1AB-7860-4EA2-A32B-9514C96915F5' },
     sessionId: 'e17fb0f8-38cb-4c0b-ad38-9896da81ab94',
     selector: '~Second',
     _status: 0 } }
------------------------------------------------------------------
[undefined #0-0] Spec: <path_to>/specs/example.js
[undefined #0-0] Running: undefined
[undefined #0-0]
[undefined #0-0] Simple cases
[undefined #0-0]
[undefined #0-0]     Test native App
[undefined #0-0]       1) test-function
[undefined #0-0]
[undefined #0-0]
[undefined #0-0] 1 failing (11s)
[undefined #0-0]
[undefined #0-0] 1) Test native App test-function:
[undefined #0-0] Cannot read property 'ELEMENT' of null
[undefined #0-0] TypeError: Cannot read property 'ELEMENT' of null
[undefined #0-0]     at Object.element (node_modules/webdriverio/build/lib/protocol/element.js:58:44)
[undefined #0-0]     at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
[undefined #0-0]     at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:191:29)
[undefined #0-0]     at lastPromise.then.resolve.call.depth (node_modules/webdriverio/build/lib/webdriverio.js:486:32)
[undefined #0-0]     at _fulfilled (node_modules/webdriverio/node_modules/q/q.js:854:54)
[undefined #0-0]     at self.promiseDispatch.done (node_modules/webdriverio/node_modules/q/q.js:883:30)
[undefined #0-0]     at Promise.promise.promiseDispatch (node_modules/webdriverio/node_modules/q/q.js:816:13)
[undefined #0-0]     at node_modules/webdriverio/node_modules/q/q.js:570:49
[undefined #0-0]     at runSingle (node_modules/webdriverio/node_modules/q/q.js:137:13)
[undefined #0-0]     at flush (node_modules/webdriverio/node_modules/q/q.js:125:13)
[undefined #0-0]
```

What's happening here is that the first call to `browser.element("~Second")` works but the `WebElement JSON object` returned from [element()](http://webdriver.io/api/protocol/element.html) throws a `Cannot read property 'ELEMENT' of null` TypeError in the next call to `browser.select('android').element()`.  The delayed exception could be due to the async nature of the test runner internally, but I'm not positive about that.

The interesting thing is that the WebElement already contains the `android` and `ios` capability contexts specified in `wdio.conf.js`.  This makes sense for multiremote elements and I practically clapped out loud when I discovered that.  So I tried to manually override those by setting them with the results of `browser.select('android').element()` and `browser.select('ios').element()`.  Unfortunately that fails because I think that the `WebElement` contains private properties or ignores the `android` and `ios` properties when `element.click()` is called.

So this feels like a partially implemented feature that might work in the next version of WebDriverIO?

After reading about [selectors](http://webdriver.io/guide/usage/selectors.html) I need to do something like the following (specifying separate selectors for Android and iOS in order to retrieve a single element reference):

```
let myElement = browser.element({
"android=/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.View/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ListView/android.widget.LinearLayout[1]",
"ios=~Second"
})

console.log(myElement);

myElement.click();
```

The above would allow me to implement cross-platform page objects and test Android/iOS simultaneously.

My only option at this point is to write a wrapper or monkey patch wdio to examine the `android` and `ios` properties and run the corresponding `browser.select('android').click(element.android.value.ELEMENT)` and `browser.select('ios').click(element.ios.value.ELEMENT)` for each context but this sounds quite painful.  It's also risky because we can't rely on QA testers to always call the wrapper and they'll probably get confused when tests crash due to missing element selectors that look like they should be there (at least on one of the platforms).

Do you know of any possible way to do this in the meantime?  I've looked at a dozen test runners, including low-level ones like [The Intern](https://theintern.io/) but WebDriverIO is by far the most mature.  We'd really like to use it for our Appium testing but without page objects that would be very painful.  We'd also really like to be able to run tests simultaneously to save time.  I'm happy to stub something out that mimics planned functionality until then.

Thanks very much in advance for any help you can provide and keep up the great work.

**Comment by zmorris** [comment]
Apologies for my late reply, I come from a PHP background and have been learning Node.js.  I went ahead and bit the bullet and wrote a multiremote extension that implements the functionality I need.  Here's what I have so far:

multiremote.js:
```
const hasElementResult = require('webdriverio/build/lib/helpers/hasElementResultHelper');
const implementedCommands = require('webdriverio/build/lib/helpers/getImplementedCommands')(); // get non-promisified list of WebDriverIO commands

/**
 * Similar to Lodash's wrap() but avoids dependency https://lodash.com/docs#wrap
 *
 * @param {Function} orig Method to wrap.
 * @param {Function} newDef Method that replaces original functionality.
 * @return {Function} Returns the new method.
 */
function wrap(orig, newDef) {
    return function(...args) {
        return newDef.apply(this, [orig].concat(args));
    };
}

/**
 * Similar to Lodash's map() but avoids dependency https://lodash.com/docs#map
 *
 * @param  {Object}   object   The object to iterate over.
 * @param  {Function} callback The function invoked per iteration.
 * @param  {Object}   context  Optional "this" context.
 * @return {Object}            Newly mapped object.
 */
function map(object, callback, context) {
    if (object instanceof Array) {
        return object.map(callback, context);
    }

    context = context || this;

    let result = {};

    for (const key in object) {
        result[key] = callback.call(context, object[key], key, object);
    }

    return result;
}

/**
 * Returns all object methods, including those which aren't enumerable.
 *
 * @param  {Object} object Object to inspect.
 * @return {Array} Array of all method names on the specified object.
 */
function allMethods(object) {
    let o = object;
    var props = [];

    do {
        props = props.concat(Object.getOwnPropertyNames(o));
    } while ((o = Object.getPrototypeOf(o)) && o != Object.prototype);

    return props.sort().filter(function(e, i, arr) {
        return e != arr[i + 1] && typeof object[e] == 'function';
    });

    // return Object.getOwnPropertyNames(object).filter(function(property) {
    //     return object[property] instanceof Function;
    // });
}

/**
 * Returns the specified function's argument names.
 * See https://stackoverflow.com/questions/1007981/how-to-get-function-parameter-names-values-dynamically
 *
 * @param  {Function|String} func Function or string describing function.
 * @return {Array} Array of argument names.
 */
function getArguments(func) {
    const ARROW = true;
    const FUNC_ARGS = ARROW ? /^(function)?\s*[^\(]*\(\s*([^\)]*)\)/m : /^(function)\s*[^\(]*\(\s*([^\)]*)\)/m;
    const FUNC_ARG_SPLIT = /,/;
    const FUNC_ARG = /^\s*(_?)(.+?)\1\s*$/;
    const STRIP_COMMENTS = /((\/\/.*$)|(\/\*[\s\S]*?\*\/))/mg;

    return ((func || '').toString().replace(STRIP_COMMENTS, '').match(FUNC_ARGS) || ['', '', ''])[2]
        .split(FUNC_ARG_SPLIT)
        .map(function(arg) {
            return arg.replace(FUNC_ARG, function(all, underscore, name) {
                return name.split('=')[0].trim();
            });
        })
        .filter(String);
}

/**
 * Private class for mimicking Selenium.WebElement class.
 */
class WebElement {
    constructor(object) {
        for (let key in object) {
            this[key] = object[key];
        }
    }
}

/**
 * Returns a cached copy of the clients in browser.contexts() so that they can be called via getClients()[client].method().
 * Note that the browser parameter is only required for the first call, after which no parameters are required.
 *
 * @param  {Object} browser Global browser instance.
 * @return {Object} Object mapping client name to client.
 */
const getClients = (function() {
    let clients;

    return function(browser) {
        if (clients == undefined && browser.contexts instanceof Function && browser.select instanceof Function) {
            clients = {};

            for (let clientName in browser.contexts()) {
                clients[clientName] = browser.select(clientName); // memoize clients
            }
        }

        return clients;
    }
})();

/**
 * Assigns methods from a Selenium.WebElement instance to our WebElement base class.
 *
 * @param  {Object} element Selenium.WebElement instance.
 */
function assignPrototypes(element) {
    if (WebElement.element || !element.element) {
        return; // just return if prototypes have been assigned to WebElement or element is not a Selenium.WebElement
    }

    allMethods(element).map(function(method) {
        WebElement.prototype[method] = element[method]; // copy Selenium.WebElement methods to our WebElement base class
    });

    Multiremote.extend(WebElement.prototype); // extend WebElement with support for multiremote, just like with the global browser instance
}

/**
 * Wraps a WebDriverIO command result in our WebElement base class if it contains any Selenium.WebElement instances.
 *
 * @param  {Object} result A WebDriverIO command result.
 * @return {Object}        A WebElement instance or the original result if it doesn't contain any Selenium.WebElement instances.
 */
function wrapElementResult(result) {
    for (let key in result) {
        switch (hasElementResult(result[key])) {
            case 1:
                assignPrototypes(result[key]); // must call every time for now (since no way to retrieve a WebElement instance at initialization)
                break;

            case 2:
                assignPrototypes(result[key][0]); // first element guaranteed to exist since all values are WebElements if true, handle like case 1
                break;

            default:
                continue;
        }

        return new WebElement(result); // wrap result in WebElement so that it can be chained like browser.element({...}).element({...}).click()
    }

    return result; // don't wrap result in WebElement if it doesn't contain Selenium.WebElement
}

/**
 * Class for extending a global WebDriverIO.browser or Selenium.WebElement with additional functionality for multiremote selectors.
 */
class Multiremote {
    /**
     * Returns a copy of a WebDriverIO.browser or Selenium.WebElement instance with additional functionality for multiremote selectors.
     *
     * @param  {Object} object WebDriverIO.browser or Selenium.WebElement instance to extend.
     * @return {Object} Extended WebDriverIO.browser or Selenium.WebElement instance.
     */
    static extend(object) {
        object = Object.assign(object); // copy browser/element (note that copies of prototypes affect original prototype)

        allMethods(object).map(function(method) {
            if (!(method in implementedCommands) || method == 'contexts' || method == 'select') {
                return;
            }

            object[method] = wrap(object[method], function(orig, ...args) {
                if (typeof getClients(object) === 'undefined') {
                    throw 'First call to Multiremote.extend() must pass the global browser instance';
                }

                const caller = this instanceof WebElement ? this : getClients();
                const selectorIndex = getArguments(implementedCommands[method]).indexOf('selector');
                let clientArgs;

                if (selectorIndex >= 0) {
                    const selectors = args[selectorIndex] instanceof Object ?
                        args[selectorIndex] :
                        map(getClients(), function(client, clientName, clients) {
                            return args[selectorIndex];
                        }); // ensure that selectors is of the form {..., client1: selector, client2: selector, ...} even if args[selectorIndex] is a string

                    clientArgs = map(selectors, function(client, clientName) {
                        let result = args.slice();

                        result.splice(selectorIndex, 1, selectors[clientName]); // convert [..., [selector, selector], ...] to [..., selector, ...]

                        return result;
                    });
                } else {
                    clientArgs = map(getClients(), function(client, clientName) {
                        return args;
                    });
                }

                return wrapElementResult(map(clientArgs, function(args, clientName) {
                    return caller[clientName][method](...args);
                }));
            });
        });

        return object;
    }
}

module.exports = Multiremote;
```

usage in example.js:
```
const Multiremote = require('../utils/multiremote');
const chai = require('chai');
const expect = chai.expect; // global.expect = chai.expect;
const chaiWebdriver = require('chai-webdriverio').default;

global.browser = Multiremote.extend(browser);	// either extend browser at top of file or in before() but not both

chai.use(chaiWebdriver(browser));

if ('android' in browser.contexts()) {
    chai.use(chaiWebdriver(browser.select('android')));
}

if ('ios' in browser.contexts()) {
    chai.use(chaiWebdriver(browser.select('ios')));
}

describe('Simple cases', function() {
    this.timeout(300000);

    before(function() {
    	// global.browser = Multiremote.extend(browser);	// either extend browser at top of file or in before() but not both
    });

    describe("Test native App", function() {
        it("test-function", function() {
            let element = browser.element("~Second"); // requires that both apps have a common selector

            console.log(element);

            element = browser.element({
                android: "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.View/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ListView/android.widget.LinearLayout[1]",
                ios: "~Second"
            });

            console.log(element);

            element.click();

            console.log(browser.getOrientation());

            browser.pause(3000);
        });
    });

    after(function() {});
});
```

The way this works is, it calls `Multiremote.extend()` which adds multiremote selector functionality to a copy of the global browser instance and then replaces it in the global scope (that's just me being paranoid because changing the original browser object works fine as well).  It also copies the methods from the first web element response onto the WebElement base class prototype so that all of the commands like `element()`, `click()`, etc work with both the global browser and web element responses.

After that, you can pass `{android: "path", ios: "path"}` selectors to the browser and web elements any place that string selectors are accepted.  It passes the corresponding selectors to `browser.select('android').element()` and `browser.select('ios').element()`, as well as all of the other commands like `click()` etc.

If you pass an ordinary selector path, it generates the `{android: "path", ios: "path"}` internally and follows the same logic from there.  I attempted to optimize it to call `browser.element("path")` but realized that command chaining could lead to permutations where the result's selectors and ids no longer matched.  So it always calls clients separately for now.

Any web element and web element arrays get returned wrapped in the WebElement class for chaining like:

```
browser.element({android: "path", ios: "path"}).element({android: "path", ios: "path"}).click()
```

For commands like `browser.getOrientation()` that normally return a string or number, the result is wrapped in a simple key-value object, for example `{ android: 'portrait', ios: 'portrait' }`.  So test suites would likely require some minor modification to handle them but it should be minimal.

This is about the simplest way I could think to do it but there is still quite a bit going on in `Multiremote.extend()` so if you have any questions, please let me know.  I really hope something like this could be useful for WebDriverIO because it would greatly simplify the page object pattern for cross-platform apps with Appium.  Maybe this could be made into a service or plugin but I'm not really sure how to do that.  Hope this helps someone.

**Comment by christian-bromann** [comment]
Thanks for sharing. This is definitely useful and necessary for running multiremote tests on mobile devices. Thanks for sharing! If anyone wants to propose a PR for this please do, thanks!

**Comment by mgrybyk** [comment]
@zmorris hey,
Note sure about v4, however in v5 if you have capabilities like
```
        android: {
            desiredCapabilities: {
                platformName: "Android",
                ...
            }
        },
        ios: {
            desiredCapabilities: {
                platformName: "iOS",
                ...
            }
        },
```
You can use `browser` object to interact with both instances and `android` or `ios` to interact with specific instance.
So,
`browser.$('foo').click()` is an equivalent to
```
android.$('foo').click()
ios.$('foo').click()
```
So, you can have a wrapper for `$` that accepts either string `('foo')` or an object `{ android: 'foo', ios: 'bar' }`.
Underneath this wrapper can do something like
```
if (typeof arg === 'string' || /* or function */) {
    browser.$(arg)
} else {
    // of course you might need to play around with promises, etc
    Object.entries(arg).forEach((i, selector) => browser[i].$(selector))
}
```

Is this something you are looking for?

**Comment by mgrybyk** [comment]
closing due to inactivity, feel free to re-open if it still an issue.
