### ISSUE TITLE
Unable to pass multiple args to process when starting instance in debug mode

### ISSUE THREAD

**Issue by antkazam** [webdriverio/webdriverio#2677]
## The problem

Unable to launch wdio with debug options.

## Environment

* WebdriverIO version: `4.9.11`
* Node.js version: `v8.9.1`
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): `wdio`
* if wdio testrunner, running synchronous or asynchronous tests: `sync`
* Additional wdio packages used (if applicable):

## Details

I would like to be able to launch wdio using the `--inspect=<port>` and `--nolazy` options but it chokes on `--nolazy`.

I'm not sure if `--nolazy` is required, I have been having trouble without it. In either case I don't think the launcher should be attempting to parse a host:port out of every arg.

## Link to Selenium/WebdriverIO logs

```
TypeError: Invalid attempt to destructure non-iterable instance
slicedToArray.js:48
    at /Users/user/workspace/reponame/node_modules/webdriverio/node_modules/babel-runtime/helpers/slicedToArray.js:48:13
    at Launcher.startInstance (/Users/user/workspace/reponame/node_modules/webdriverio/build/lib/launcher.js:563:74)
    at Launcher.runSpecs (/Users/user/workspace/reponame/node_modules/webdriverio/build/lib/launcher.js:504:22)
    at Launcher.value._regenerator2.default.mark._regenerator2.default.wrap.exitCode (/Users/user/workspace/reponame/node_modules/webdriverio/build/lib/launcher.js:354:47)
    at new Promise (<anonymous>)
    at new F (/Users/user/workspace/reponame/node_modules/core-js/library/modules/_export.js:35:28)
    at Launcher._callee$ (/Users/user/workspace/reponame/node_modules/webdriverio/build/lib/launcher.js:348:40)
    at tryCatch (/Users/user/workspace/reponame/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/user/workspace/reponame/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.forEach.prototype.(anonymous function) [as next] (/Users/user/workspace/reponame/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:114:21)

```

## Code To Reproduce Issue [ Good To Have ]

VSCode launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "E2E Tests",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/node_modules/.bin/wdio",
            "windows": {
                "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/wdio.cmd"
            },
            "args": [
                "wdio.conf.js"
            ],
            "internalConsoleOptions": "openOnSessionStart",
            "runtimeArgs": [
                  "--inspect-brk=127.0.0.1:9229",
                  "--nolazy"
            ],
            "envFile": "${workspaceFolder}/.env",
            "env": {
                "DEBUG": "true",
                "NODE_ENV": "development",
            },
            "sourceMaps": true
        }
    ]
}
```
Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by antkazam** [comment]
This was already fixed in a later version.
