### ISSUE TITLE
getText not returning a String?

### ISSUE THREAD

**Issue by basickarl** [webdriverio/webdriverio#2712]
```
        const text = await browser
            .click('.fa-question-circle')
            .waitForText('.version')
            .getText('.version')
            .toUpperCase();
```
Results in:
```
     TypeError: browser.click(...).waitForText(...).getText(...).toUpperCase is not a function
      at Context.it (test-client/test_one.js:245:14)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

I read the documentation and getText is supposed to return a String?

**Comment by basickarl** [comment]
I apologise, the getText was returning an empty String.
