### ISSUE TITLE
problem running on winodws, see stacktrace

### ISSUE THREAD

**Issue by ravi005e** [webdriverio/webdriverio#2717]
.\node_modules\.bin\wdio:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (.\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at Object.<anonymous> (.\node_modules\babel-cli\lib\_babel-node.js:154:22)
error Command failed with exit code 1.

**Comment by christian-bromann** [comment]
Not sure where 
```
basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')")
```

comes from but it is definitely not from wdio. Do you have a reproducible example?
