### ISSUE TITLE
Error while running a webdriver io test - mocha ERROR: Couldn't load "wdio-mocha-framework" framework. You need to install it with `$ npm install wdio-mocha-framework`! Error: Cannot find module 'wdio-mocha-framework'

### ISSUE THREAD

**Issue by sriramkukkadapu** [webdriverio/webdriverio#2784]
## The problem

Facing bellow error while running webdriver io tests using command "wdio wdio.conf.js"

ERROR: Couldn't load "wdio-mocha-framework" framework. You need to install it with `$ npm install wdio-mocha-framework`!
Error: Cannot find module 'wdio-mocha-framework'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Runner.initialiseFramework (/usr/local/lib/node_modules/webdriverio/build/lib/runner.js:531:24)
    at Runner._callee$ (/usr/local/lib/node_modules/webdriverio/build/lib/runner.js:101:55)
    at tryCatch (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/webdriverio/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)

## Environment

* WebdriverIO version: 4.13.1
* Node.js version: 8.11.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): - 
* if wdio testrunner, running synchronous or asynchronous tests: synchronus
* Additional wdio packages used (if applicable):

Packages Installed are below:

/usr/local/lib
├── appium@1.8.1
├── appium-doctor@1.4.3
├── core-js@2.3.0
├── es6-promise@3.0.2
├── jszip@3.1.5
├── npm@5.6.0
├── readable-stream@2.0.6
├── wdio-mocha-framework@5.0.0-alpha.7
└── UNMET PEER DEPENDENCY webdriverio@4.13.1

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Selenium/WebdriverIO logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by sriramkukkadapu** [comment]
Hello Maycon. It worked like a charm, really thanks for your solution :)
