### ISSUE TITLE
Tests give me an error when wdio-mocha-framework and wdio-spec-reporter were updated to 5.0.0-alpha.7

### ISSUE THREAD

**Issue by JulsRicketti** [webdriverio/webdriverio#2787]
## The problem
Can't run my tests after update for `wdio-mocha-framework` and `wdio-spec-reporter` were updated to `5.0.0-alpha.7`

## Environment

* WebdriverIO version: 4.13.1
* Node.js version: 8.9.4
* if wdio testrunner, running synchronous or asynchronous tests: mostly synchronous
* Additional wdio packages used (if applicable):
wdio-mocha-framework: 5.0.0-alpha.7
wdio-selenium-standalone-service: 0.0.10
wdio-spec-reporter: 5.0.0-alpha.7

## Details

My tests are run with the following command:

> "test:e2e": "node -r dotenv/config ./node_modules/.bin/wdio wdio/wdio.conf.js"

There were no problems previously and if I put the versions back to as they previously were (which is 0.5.13 for wdio-mocha-framework and 0.1.4 for wdio-spec-reporter), the tests run normally.

If I do run with both of the packages on `5.0.0-alpha.7` I get the error message stating that the `wdio-spec-reporter` module could not be found. If I revert it back to `0.1.4` I will then get an error with a message stating that `wdio-mocha-framework` couldn't be loaded.

Finally it works as expected once I revert both packages back to the previous versions being used.

Keep in mind that I have double, triple and quadruple checked that the packages have been installed prior to running it.

### Full logs for when both packages are at `5.0.0-alpha.7`:
```
node -r dotenv/config ./node_modules/.bin/wdio wdio/wdio.conf.js

local conf not found
/Workspace/MyProject/node_modules/webdriverio/build/lib/launcher.js:163
                        throw _iteratorError;
                        ^

Error: reporter "wdio-spec-reporter" is not installed. Error: Error: Cannot find module 'wdio-spec-reporter'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Launcher.initReporters (/Workspace/MyProject/node_modules/webdriverio/build/lib/launcher.js:138:40)
    at new Launcher (/Workspace/MyProject/node_modules/webdriverio/build/lib/launcher.js:73:31)
    at launch (/Workspace/MyProject/node_modules/webdriverio/build/lib/cli.js:452:24)
    at Object.<anonymous> (/Workspace/MyProject/node_modules/webdriverio/build/lib/cli.js:485:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Launcher.initReporters (/Workspace/MyProject/node_modules/webdriverio/build/lib/launcher.js:140:35)
    at new Launcher (/Workspace/MyProject/node_modules/webdriverio/build/lib/launcher.js:73:31)
    at launch (/Workspace/MyProject/node_modules/webdriverio/build/lib/cli.js:452:24)
    at Object.<anonymous> (/Workspace/MyProject/node_modules/webdriverio/build/lib/cli.js:485:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
```
### Full logs for when just `wdio-mocha-framework` has been updated:

```
> node -r dotenv/config ./node_modules/.bin/wdio wdio/wdio.conf.js

local conf not found
local conf not found
ERROR: Couldn't load "wdio-mocha-framework" framework. You need to install it with `$ npm install wdio-mocha-framework`!
Error: Cannot find module 'wdio-mocha-framework'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Runner.initialiseFramework (/Workspace/MyProject/node_modules/webdriverio/build/lib/runner.js:531:24)
    at Runner._callee$ (/Workspace/MyProject/node_modules/webdriverio/build/lib/runner.js:101:55)
    at tryCatch (/Workspace/MyProject/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Workspace/MyProject/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Workspace/MyProject/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Workspace/MyProject/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)

    at Runner.initialiseFramework (/Workspace/MyProject/node_modules/webdriverio/build/lib/runner.js:537:23)
    at Runner._callee$ (/Workspace/MyProject/node_modules/webdriverio/build/lib/runner.js:101:55)
    at tryCatch (/Workspace/MyProject/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Workspace/MyProject/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Workspace/MyProject/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Workspace/MyProject/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Workspace/MyProject/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by BorisOsipov** [comment]
@JulsRicketti wdio-mocha-framework and wdio-spec-reporter 5.0.0-alpha.7 aren't compatible with WebdriverIO version: 4.13.1. If you want to try it you must use 5.0.0-alpha.6

**Comment by JulsRicketti** [comment]
Now I get this following error:

```
module.js:540
    throw err;
    ^

Error: Cannot find module '../build'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```

Did I miss something else?

**Comment by BorisOsipov** [comment]
>Now I get this following error:

what does it mean now? explain what you did

**Comment by JulsRicketti** [comment]
Sorry, I meant I did what you proposed me to do so, so changed `webdriverio` to `5.0.0-alpha.6` and this is the new error I got.

**Comment by BorisOsipov** [comment]
Thanks, we will need to have look into this.
Please, share your package.json or example project on github.

**Comment by JulsRicketti** [comment]
I'll have to create an example project later today. For now, here is how my `package.json` looks:

```
{
  "name": "MyProject",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "main": "index.js",
  "scripts": {
    "dev": "node -r dotenv/config server.js",
    "build": "next build",
    "start": "node server.js",
    "test:e2e": "node -r dotenv/config ./node_modules/.bin/wdio wdio/wdio.conf.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/core": "7.0.0-beta.51",
    "@babel/register": "7.0.0-beta.51",
    "@zeit/next-css": "0.2.0",
    "@zeit/next-sass": "0.2.0",
    "create-react-class": "15.6.3",
    "css-loader": "0.28.11",
    "express": "4.16.3",
    "file-loader": "1.1.11",
    "glob": "7.1.2",
    "history": "4.7.2",
    "isomorphic-fetch": "2.2.1",
    "moment": "2.22.2",
    "next": "6.1.1",
    "node-sass": "4.9.0",
    "prop-types": "15.6.2",
    "qs": "6.5.2",
    "raw-loader": "0.5.1",
    "react": "16.4.1",
    "react-dom": "16.4.1",
    "react-scrollspy": "3.3.5",
    "react-spinners": "0.3.2",
    "recompose": "0.27.1",
    "sass-loader": "7.0.3"
  },
  "standard": {
    "parser": "babel-eslint"
  },
  "devDependencies": {
    "babel-eslint": "8.2.5",
    "dotenv": "6.0.0",
    "eslint": "5.0.1",
    "eslint-config-standard": "11.0.0",
    "eslint-plugin-import": "2.13.0",
    "eslint-plugin-node": "6.0.1",
    "eslint-plugin-promise": "3.8.0",
    "eslint-plugin-react": "7.10.0",
    "eslint-plugin-standard": "3.1.0",
    "mocha": "5.2.0",
    "nodemon": "1.17.5",
    "selenium-standalone": "6.15.1",
    "sinon": "6.0.1",
    "superagent": "3.8.3",
    "wdio-mocha-framework": "5.0.0-alpha.7",
    "wdio-selenium-standalone-service": "0.0.10",
    "wdio-spec-reporter": "5.0.0-alpha.7",
    "webdriverio": "5.0.0-alpha.6"
  }
}
```

**Comment by christian-bromann** [comment]
v5 is on alpha and not stable yet meaning that we will publish packages constantly and will definitely break things. Once we go into beta you should expect to have it running stable. Please don't use v5 yet since a lot of commands have changed and are not documented at all.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/v5#80
