### ISSUE TITLE
Using Proxy with firefox not working

### ISSUE THREAD

**Issue by Randyklose** [webdriverio/webdriverio#2809]
## The problem
Hey,
Im trying to implement our system to use a proxy server with firefox.

i'm trying to add the proxy config to the desiredCapabilities like so : 

`options.desiredCapabilities['proxy'] = {
          proxyType: 'MANUAL',
          httpProxy: proxy,
          sslProxy: proxy,
          autodetect: false
}`

When i try to run it i get the following error
```
   err: {
      "name": "RuntimeError",
      "message": "RuntimeError\n     (SessionNotCreatedException:33) A new session could not be created.\n     Problem: InvalidArgumentError: Expected [object Undefined] undefined to be an integer\nBuild info: version: '3.4.0', revision: 'unknown', time: 'unknown'\nSystem info: host: 'Randys-MacBook-Pro', ip: 'fe80:0:0:0:1088:b732:54e1:fe2%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_121'\nDriver info: driver.version: FirefoxDriver\nremote stacktrace: stack backtrace:\n   0:        0x1071c182e - backtrace::backtrace::trace::h76b688ec9dd0c4e2\n   1:        0x1071c1f6c - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc\n   2:        0x1071749cf - webdriver::error::WebDriverError::new::h7184d15bc5556898\n   3:        0x107184ffb - geckodriver::marionette::MarionetteSession::response::h3a41c0cc62e59c56\n   4:        0x107182e93 - _$LT$geckodriver..marionette..MarionetteHandler$u20$as$u20$webdriver..server..WebDriverHandler$LT$geckodriver..marionette..GeckoExtensionRoute$GT$$GT$::handle_command::hcb53484f0f6d535e\n   5:        0x107174e60 - webdriver::server::start::_$u7b$$u7b$closure$u7d$$u7d$::he6d10c2fe3c7e795\n   6:        0x10714aa5d - std::panicking::try::do_call::hd7b79b66c427c537\n   7:        0x1072ecd1a - __rust_maybe_catch_panic\n   8:        0x10715779a - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hde402662965177dc\n   9:        0x1072eb174 - std::sys::imp::thread::Thread::new::thread_start::hca57ad22492f366f\n  10:     0x7fff5fea3660 - _pthread_body\n  11:     0x7fff5fea350c - _pthread_start\u001b[1;30m\n\n     Callstack:\n     -> init()\n"
    }
```
## Environment

The project runs node 0.10 , webdriverio 2.4.5 and geckodriver 1.6.1.

## Link to Selenium/WebdriverIO logs

```
10:21:37 selenium.1                 | 10:21:37.520 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
10:21:37 selenium.1                 | 10:21:37.560 INFO - Executing: [new session: Capabilities [{rotatable=true, proxy={autodetect=false, httpProxy=104.165.77.1:60000, proxyType=MANUAL, sslProxy=104.165.77.1:60000}, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
10:21:37 selenium.1                 | 10:21:37.593 INFO - Creating a new session for Capabilities [{rotatable=true, proxy={autodetect=false, httpProxy=104.165.77.1:60000, proxyType=MANUAL, sslProxy=104.165.77.1:60000}, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
10:21:38 selenium.1                 | 1531837298054	geckodriver	INFO	Listening on 127.0.0.1:19408
10:21:38 selenium.1                 | 1531837298441	geckodriver::marionette	INFO	Starting browser /Applications/Firefox.app/Contents/MacOS/firefox-bin with args ["-marionette"]
10:21:38 selenium.1                 | 1531837298796	addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1596"  data: no] Stack trace: loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1596 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1631 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3152 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2246 < callProvider()@resource://gre/modules/AddonManager.jsm:271 < _startProvider()@resource://gre/modules/AddonManager.jsm:741 < startup()@resource://gre/modules/AddonManager.jsm:908 < startup()@resource://gre/modules/AddonManager.jsm:3122 < observe()@jar:file:///Applications/Firefox.app/Contents/Resources/omni.ja!/components/addonManager.js:65
10:21:39 selenium.1                 | 1531837299127	Marionette	INFO	Enabled via --marionette
10:21:40 selenium.1                 | 2018-07-17 10:21:40.250 plugin-container[72097:4219018] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xaa3b, name = 'com.apple.tsm.portname'
10:21:40 selenium.1                 | See /usr/include/servers/bootstrap_defs.h for the error codes.
10:21:40 selenium.1                 | 1531837300581	Marionette	INFO	Listening on port 61455
10:21:40 selenium.1                 | JavaScript error: chrome://marionette/content/server.js, line 337: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]
10:21:40 selenium.1                 | 10:21:40.732 WARN - Exception thrown
10:21:40 selenium.1                 | java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
10:21:40 selenium.1                 | Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
10:21:40 selenium.1                 | System info: host: 'Randys-MacBook-Pro', ip: 'fe80:0:0:0:1088:b732:54e1:fe2%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_121'
10:21:40 selenium.1                 | Driver info: driver.version: unknown
10:21:40 selenium.1                 | 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
10:21:40 selenium.1                 | 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:131)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:190)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
10:21:40 selenium.1                 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
10:21:40 selenium.1                 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:543)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1228)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:481)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1130)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:320)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:112)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
10:21:40 selenium.1                 | 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
10:21:40 selenium.1                 | 	at java.lang.Thread.run(Thread.java:745)
10:21:40 selenium.1                 | Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
10:21:40 selenium.1                 | Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
10:21:40 selenium.1                 | System info: host: 'Randys-MacBook-Pro', ip: 'fe80:0:0:0:1088:b732:54e1:fe2%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_121'
10:21:40 selenium.1                 | Driver info: driver.version: unknown
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:89)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:63)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
10:21:40 selenium.1                 | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
10:21:40 selenium.1                 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
10:21:40 selenium.1                 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
10:21:40 selenium.1                 | 	... 1 more
10:21:40 selenium.1                 | Caused by: java.lang.reflect.InvocationTargetException
10:21:40 selenium.1                 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10:21:40 selenium.1                 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
10:21:40 selenium.1                 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10:21:40 selenium.1                 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:81)
10:21:40 selenium.1                 | 	... 9 more
10:21:40 selenium.1                 | Caused by: org.openqa.selenium.SessionNotCreatedException: InvalidArgumentError: Expected [object Undefined] undefined to be an integer
10:21:40 selenium.1                 | Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
10:21:40 selenium.1                 | System info: host: 'Randys-MacBook-Pro', ip: 'fe80:0:0:0:1088:b732:54e1:fe2%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_121'
10:21:40 selenium.1                 | Driver info: driver.version: FirefoxDriver
10:21:40 selenium.1                 | remote stacktrace: stack backtrace:
10:21:40 selenium.1                 |    0:        0x1071c182e - backtrace::backtrace::trace::h76b688ec9dd0c4e2
10:21:40 selenium.1                 |    1:        0x1071c1f6c - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
10:21:40 selenium.1                 |    2:        0x1071749cf - webdriver::error::WebDriverError::new::h7184d15bc5556898
10:21:40 selenium.1                 |    3:        0x107184ffb - geckodriver::marionette::MarionetteSession::response::h3a41c0cc62e59c56
10:21:40 selenium.1                 |    4:        0x107182e93 - _$LT$geckodriver..marionette..MarionetteHandler$u20$as$u20$webdriver..server..WebDriverHandler$LT$geckodriver..marionette..GeckoExtensionRoute$GT$$GT$::handle_command::hcb53484f0f6d535e
10:21:40 selenium.1                 |    5:        0x107174e60 - webdriver::server::start::_$u7b$$u7b$closure$u7d$$u7d$::he6d10c2fe3c7e795
10:21:40 selenium.1                 |    6:        0x10714aa5d - std::panicking::try::do_call::hd7b79b66c427c537
10:21:40 selenium.1                 |    7:        0x1072ecd1a - __rust_maybe_catch_panic
10:21:40 selenium.1                 |    8:        0x10715779a - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hde402662965177dc
10:21:40 selenium.1                 |    9:        0x1072eb174 - std::sys::imp::thread::Thread::new::thread_start::hca57ad22492f366f
10:21:40 selenium.1                 |   10:     0x7fff5fea3660 - _pthread_body
10:21:40 selenium.1                 |   11:     0x7fff5fea350c - _pthread_start
10:21:40 selenium.1                 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10:21:40 selenium.1                 | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
10:21:40 selenium.1                 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10:21:40 selenium.1                 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$22(ProtocolHandshake.java:365)
10:21:40 selenium.1                 | 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
10:21:40 selenium.1                 | 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
10:21:40 selenium.1                 | 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
10:21:40 selenium.1                 | 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
10:21:40 selenium.1                 | 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
10:21:40 selenium.1                 | 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
10:21:40 selenium.1                 | 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
10:21:40 selenium.1                 | 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
10:21:40 selenium.1                 | 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:368)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:159)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:250)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:236)
10:21:40 selenium.1                 | 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:137)
10:21:40 selenium.1                 | 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:191)
10:21:40 selenium.1                 | 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:108)
10:21:40 selenium.1                 | 	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:137)
10:21:40 selenium.1                 | 	... 14 more
10:21:40 selenium.1                 | 10:21:40.736 WARN - Exception: InvalidArgumentError: Expected [object Undefined] undefined to be an integer
10:21:40 selenium.1                 | Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
10:21:40 selenium.1                 | System info: host: 'Randys-MacBook-Pro', ip: 'fe80:0:0:0:1088:b732:54e1:fe2%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '1.8.0_121'
10:21:40 selenium.1                 | Driver info: driver.version: FirefoxDriver
10:21:40 selenium.1                 | remote stacktrace: stack backtrace:
10:21:40 selenium.1                 |    0:        0x1071c182e - backtrace::backtrace::trace::h76b688ec9dd0c4e2
10:21:40 selenium.1                 |    1:        0x1071c1f6c - backtrace::capture::Backtrace::new::hb5a725a088a2a2fc
10:21:40 selenium.1                 |    2:        0x1071749cf - webdriver::error::WebDriverError::new::h7184d15bc5556898
10:21:40 selenium.1                 |    3:        0x107184ffb - geckodriver::marionette::MarionetteSession::response::h3a41c0cc62e59c56
10:21:40 selenium.1                 |    4:        0x107182e93 - _$LT$geckodriver..marionette..MarionetteHandler$u20$as$u20$webdriver..server..WebDriverHandler$LT$geckodriver..marionette..GeckoExtensionRoute$GT$$GT$::handle_command::hcb53484f0f6d535e
10:21:40 selenium.1                 |    5:        0x107174e60 - webdriver::server::start::_$u7b$$u7b$closure$u7d$$u7d$::he6d10c2fe3c7e795
10:21:40 selenium.1                 |    6:        0x10714aa5d - std::panicking::try::do_call::hd7b79b66c427c537
10:21:40 selenium.1                 |    7:        0x1072ecd1a - __rust_maybe_catch_panic
10:21:40 selenium.1                 |    8:        0x10715779a - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::hde402662965177dc
10:21:40 selenium.1                 |    9:        0x1072eb174 - std::sys::imp::thread::Thread::new::thread_start::hca57ad22492f366f
10:21:40 selenium.1                 |   10:     0x7fff5fea3660 - _pthread_body
10:21:40 selenium.1                 |   11:     0x7fff5fea350c - _pthread_start
```

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

**Comment by christian-bromann** [comment]
> The project runs node 0.10 , webdriverio 2.4.5 and geckodriver 1.6.1.

Can you please update all these?

Also please see https://github.com/mozilla/geckodriver#proxy-object. WebdriverIO passes the data along to the driver. If it fails it is unlikely an issue in this project. You should reach out to the folks of the geckodriver project: https://github.com/mozilla/geckodriver#proxy-object
