### ISSUE TITLE
Error: Unrecognised hook ["before each" hook] for suite

### ISSUE THREAD

**Issue by amjadalibb** [webdriverio/webdriverio#2816]
## The problem occurs only on Ubuntu 16.04.5 LTS

Error: Unrecognised hook ["before each" hook] for suite [Standard Importer :: Article :: Fallback Rules - Without teaserTitle attribute]
    at ReporterStats.getHookStats (/tmp/app/node_modules/webdriverio/build/lib/utils/ReporterStats.js:362:47)
    at ReporterStats.hookEnd (/tmp/app/node_modules/webdriverio/build/lib/utils/ReporterStats.js:332:34)
    at BaseReporter.<anonymous> (/tmp/app/node_modules/webdriverio/build/lib/utils/BaseReporter.js:147:25)
    at BaseReporter.emit (events.js:182:13)
    at BaseReporter.EventEmitter.emit (domain.js:442:20)
    at BaseReporter.handleEvent (/tmp/app/node_modules/webdriverio/build/lib/utils/BaseReporter.js:300:27)
    at Launcher.messageHandler (/tmp/app/node_modules/webdriverio/build/lib/launcher.js:688:28)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at emit (internal/child_process.js:811:12)

## Environment

* OS: Ubuntu 16.04.5 LTS
* WebdriverIO version: 4.13.1
* Node.js version: 10.7.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio test runner
* if wdio testrunner, running synchronous or asynchronous tests: synchronous
* Additional wdio packages used (if applicable): wdio-phantomjs-servicen wdio-spec-reporter, wdio-mochawesome-reporter

**Comment by christian-bromann** [comment]
@amjadalibb can you provide a minimal reproducible example?
