### ISSUE TITLE
browser.getTabIds() API is not working in IE11

### ISSUE THREAD

**Issue by lttrung112** [webdriverio/webdriverio#2828]
## The problem
browser.getTabIds() API is not working in IE11

## Environment

* WebdriverIO version: 4.11.0
* Node.js version: 6.11.0
* wdio testrunner synchronous test
* Driver: IEDriverServer.exe: 3.8

## Details

I have got a failure when running browser.getTabIds(); API in IE11, could you please have some advice?
Script:
browser.url('http://webdriver.io');
var tabIds = browser.getTabIds();
console.log(tabIds);

Note: Same issue with browser.switchTab()
-------------
Error:
running internet explorer (v11)
Error: Remote end send an unknown status code.

-------------------------
Log from Hub:
-------------------
<details>
C:\GRID>java -jar selenium-server-standalone-3.11.0.jar -role hub
18:27:04.900 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision: 'e59cfb3'
18:27:04.903 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
2018-07-30 18:27:05.264:INFO::main: Logging initialized @617ms to org.seleniumhq.jetty9.util.log.StdErrLog
18:27:05.417 INFO [Hub.start] - Selenium Grid hub is up and running
18:27:05.417 INFO [Hub.start] - Nodes should register to http://10.192.8.5:4444/grid/register/
18:27:05.418 INFO [Hub.start] - Clients should connect to http://10.192.8.5:4444/wd/hub
18:27:10.052 INFO [DefaultGridRegistry.add] - Registered a node http://10.192.8.5:7777
18:27:27.545 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: internet explorer, handlesAlerts: true, javascriptEnabled: true, locationC
ontextEnabled: true, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 1, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true, vers
ion: 11}
18:27:27.549 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {webdriver.ie.driver=C:/Program Files (x86)/Internet Explorer/iexplore.exe, server:CONFIG_UUID=d
37349c2-3ae3-4564-9ab0-9e8c120be56a, seleniumProtocol=WebDriver, browserName=internet explorer, ignoreProtectedModeSettings=true, maxInstances=10, platformName=WINDOWS, version=11, plat
form=WINDOWS}
</details>

Log from Node:
------------------
<details>
C:\GRID>java -Dwebdriver.ie.driver="C:/GRID/IEDriverServer.exe" -jar selenium-server-standalone-3.11.0.jar -role node -hub http://10.192.8.5:4444/grid/register -nodeConfig "C:/GRID/node
config_IE11_local.json"
18:27:09.523 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision: 'e59cfb3'
18:27:09.525 INFO [GridLauncherV3$3.launch] - Launching a Selenium Grid node on port 7777
2018-07-30 18:27:09.657:INFO::main: Logging initialized @419ms to org.seleniumhq.jetty9.util.log.StdErrLog
18:27:09.777 INFO [SeleniumServer.boot] - Welcome to Selenium for Workgroups....
18:27:09.777 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 7777
18:27:09.778 INFO [GridLauncherV3$3.launch] - Selenium Grid node is up and ready to register to the hub
18:27:09.782 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
18:27:09.782 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://10.192.8.5:4444/grid/register
18:27:10.059 INFO [SelfRegisteringRemote.registerToHub] - Updating the node configuration from the hub
18:27:10.099 INFO [SelfRegisteringRemote.registerToHub] - The node is registered to the hub and ready to use
18:27:27.662 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: internet explorer, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: tr
ue, loggingPrefs: org.openqa.selenium.logging..., maxInstances: 1, requestOrigins: {name: webdriverio, url: http://webdriver.io, version: 4.13.1}, rotatable: true, version: 11}
18:27:27.664 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.ie.InternetExplorerDr
iverService)
Started InternetExplorerDriver server (32-bit)
3.8.0.0
Listening on port 9497
Only local connections are allowed
18:27:29.768 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
18:27:29.787 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session e9c2ef50-4fd0-4855-a8cd-8d08430029b0 (org.openqa.selenium.ie.InternetExplorerDriverService)
18:27:33.677 INFO [ActiveSessions$1.onStop] - Removing session e9c2ef50-4fd0-4855-a8cd-8d08430029b0 (org.openqa.selenium.ie.InternetExplorerDriverService)
18:27:43.213 INFO [OsProcess.destroy] - Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
        at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
        at org.apache.commons.exec.PumpStreamHandler.stop(PumpStreamHandler.java:181)
        at org.openqa.selenium.os.OsProcess.destroy(OsProcess.java:135)
        at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
        at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:222)
        at org.openqa.selenium.remote.server.ServicedSession.stop(ServicedSession.java:83)
        at org.openqa.selenium.remote.server.ActiveSessions.lambda$new$1(ActiveSessions.java:55)
        at com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1810)
        at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3457)
        at com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3433)
        at com.google.common.cache.LocalCache$Segment.remove(LocalCache.java:3067)
        at com.google.common.cache.LocalCache.remove(LocalCache.java:4228)
        at com.google.common.cache.LocalCache$LocalManualCache.invalidate(LocalCache.java:4892)
        at org.openqa.selenium.remote.server.ActiveSessions.invalidate(ActiveSessions.java:102)
        at org.openqa.selenium.remote.server.WebDriverServlet.handle(WebDriverServlet.java:275)
        at org.openqa.selenium.remote.server.WebDriverServlet.doDelete(WebDriverServlet.java:144)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
        at org.openqa.selenium.remote.server.WebDriverServlet.service(WebDriverServlet.java:125)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
        at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
        at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
        at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
        at java.lang.Thread.run(Unknown Source)
18:27:43.217 ERROR [OsProcess.destroy] - Unable to kill process java.lang.ProcessImpl@3ab97803
</details>

**Comment by lttrung112** [comment]
@christian-bromann 
I have raised an issue to [()](https://github.com/SeleniumHQ/selenium/issues/6229)  IEDriver project, but they suggest the issue belong to Webdriverio, and I also try with selenium webdriver with below script, It work well and return a Windowhandler , so I think it will be great if you would consider to fix.

Try with Selenium webdriver for IE11 browser:
<details>
let webdriver = require("selenium-webdriver");

let cbtHub = "http://localhost:5555";
// let cbtHub = "http://localhost:9515";
let caps = {
    'browserName': 'internet explorer',
};

let driver = new webdriver.Builder()
    .usingServer(cbtHub)
    .withCapabilities(caps)
    .build();
driver.get('https://google.com');
driver.getAllWindowHandles().then((tab_handles)=>{ let number_of_tabs = tab_handles.length;
let new_tab_index = number_of_tabs-1;
console.log(tab_handles);
driver.switchTo().window(tab_handles[new_tab_index]); });

==> console log:  [ 'c012bffc-88d6-4826-83c2-f21ec4b15138' ]
</details>

**Comment by DarkKnight711** [comment]
@christian-bromann I want to add few details on this. 

The error started appearing on IEDriverServer version > 3.4. 

Here's the change log of IEDriverServer from 3.4 to 3.5 - 

IEDriverServer Version 3.4.1 adds the remote protocol end points and handling of commands as required by the W3C WebDriver Specification for the IE driver.

v3.5.0.0
========
 * Release to synchronize with release of Selenium project.
 * Updates to JavaScript automation atoms.
 * To successfully use this version of the IE driver, you should be using
   version 3.5 or above of the language bindings. Those are the only versions
   of language bindings that will understand the payload required to be sent
   during the creation of a new session. Earlier versions of the language
   bindings are not guaranteed to be fully compatible with this release of
   the IE driver.

v3.4.0.1
========
 * This release **adds the remote protocol end points and handling of commands
   as required by the W3C WebDriver Specification for the IE driver**. It
   deprecates and mostly removes behavior that is at odds with the
   specification, but may have been the proper behavior under the open-source
   dialect of the protocol. Issues arising from this version of the driver
   that appeared to work in previous versions will only be addressed if a
   simple test case is provided that demonstrates it working in a prior
   version of the driver and failing in this one. Reported issues lacking
   such a test case will be summarily closed.

v3.4.0.0
========
 * Release to synchronize with release of Selenium project.

source:[](https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriverserver/CHANGELOG)

@lttrung112 You can use IEDriverServer 3.4 to avoid the problem.

**Comment by lttrung112** [comment]
@DarkKnight711 
Thank you for your information.

**Comment by savsav** [comment]
As @DarkKnight711 has pointed out, IE driver > 3.4 has started using the WebDriver Wire Protocol, instead of the JSON Wire Protocol. WebdriverIO is trying to handle such issues - here is an extract from **windowHandles.js** which is used by the **getTabIds()** command:

```javascript
return this.requestHandler.create('/session/:sessionId/window_handles').catch(function (err) {
        /**
         * jsonwire command not supported try webdriver endpoint
         */
        if (err.message.match(/did not match a known command/)) {
            return _this.requestHandler.create('/session/:sessionId/window/handles');
        }

        throw err;
    });
```

If the JSON wire request fails, it attempts a request to the W3C WebDriver compliant endpoint. However, this fails for IE11 as the err object is different. If you change the condition to:
```javascript
if (err.message.match(/did not match a known command/) || ('seleniumStack' in err && err.seleniumStack.message.match(/Remote end send an unknown status code/))) {
    // ...
}
```
then it works properly.

There are a lot of commands where this can be applied, however if you take a look at https://github.com/webdriverio/webdriverio/issues/1841#issuecomment-285678194, it seems that this work has already been planned for WebdriverIO v5 (https://github.com/webdriverio/v5).

@christian-bromann , should I send you a PR with the error message retrieved properly for IE driver and all such commands - that is until v5 is released?

**Comment by christian-bromann** [comment]
> should I send you a PR with the error message retrieved properly for IE driver and all such commands

Yes please! Thanks for checking
