### ISSUE TITLE
ERROR: Cannot find module

### ISSUE THREAD

**Issue by noelayan** [webdriverio/webdriverio#3010]
I got this error message below when I tried to run the script. I guess my require() function is correct. 
This is my code structure which I think is correct. See screenshot.
https://monosnap.com/file/OER4L0ygJ5kbpBMrPpK87QOyMfx6XR#embed
https://monosnap.com/file/stVyopBwAR0vUkIazS78R0aTCJwZN4

**ERROR: Cannot find module './Page'**
chrome
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\webdriverio-pageobject\test\pageobjects\login.page.js:2:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[13:39:16]  COMMAND     DELETE   "/wd/hub/session/a0890f506a62b0fb3c9632567b8c444d"

**ERROR: Cannot find module '../pageobjects/login.page'**
chrome
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\webdriverio-pageobject\test\login.spec.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[13:39:16]  COMMAND     DELETE   "/wd/hub/session/d361549322bf8b1f2c81b657ef2ce30c"

[13:39:17]  COMMAND     DELETE   "/wd/hub/session/9728a6b89b38cdd346d57448466a0d31"

==================================================================
Number of specs: 3
npm ERR! Test failed.  See above for more details.

**Comment by christian-bromann** [comment]
I am not sure what you trying to run here. Please make sure that if you copy the example page object project that all paths are correct.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by noelayan** [comment]
I copied all the paths. But it looks like the path provided is incorrect, so, I changed it and its fixed now. I thought its an issue. Thanks!

**Comment by christian-bromann** [comment]
Yes and no. That examples is intended to be run when being in the `https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject` directory and running `npm test` they could be more flexible but the intention of these examples is more to show of how you can build page objects.

**Comment by ianFar96** [comment]
Hi guys, I'm facing the same issue, could you add some details on how you managed to solve it please?

**Comment by christian-bromann** [comment]
@ianFar96 this issue is 5 years old, you are likely facing a different issue.
