### ISSUE TITLE
Browser send key combo of 'Enter' and 'NULL' failing for Safari

### ISSUE THREAD

**Issue by jeffhoang** [webdriverio/webdriverio#3020]
We're testing a feature in our app that requires a combo send key of an 'Enter' and 'NULL', but it's failing for Safari.   This same code works fine with Chrome though.

Code:

``
sender.browser.keys(['Enter',` 'NULL']);
``

Exception:

> Error: Encountered key input source with invalid 'value' in payload: {
    actions =     (
    {
    type = keyDown;
    value = "\Ue007";
    },
    {
    type = keyDown;
    value = "\Ue000";
    },
    {
    type = keyUp;
    value = "\Ue007";
    },
    {
    type = keyUp;
    value = "\Ue000";
    }
    );
    id = keys;
    type = key;
    }
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'XXX-M-J37C', ip: '10.114.52.144', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.6', java.version: '10.0.1'
    Driver info: driver.version: unknown
    at new RuntimeError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)
>

**Comment by christian-bromann** [comment]
This is usually a sign that something is up with how Safaridriver handles that command. Please create an issue in that project. For more questions, please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!
