### ISSUE TITLE
[Win10] Only test passes but suite fails w/ TypeError: this._redirectLogStream is not a function

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#3069]
**Environment:**
 - **WebdriverIO version:5.0.0-beta.10**
 - **Mode: WDIO Testrunner**
 - **Running sync**
 - **Node.js version: 8.9.0 or 10.13.0**
 - **NPM version: 6.4.1**
 - **Browser name and version: N/A**
 - **Platform name and version: Windows 10**
 - **Additional wdio packages used (if applicable): N/A**

**Config of WebdriverIO**
```
const path = require('path');

const LOG_PATH = path.join(__dirname, 'logs');

exports.config = {
    runner: 'local',
    specs: ['./tests/e2e/steps/*'],
    maxInstances: 10,
    capabilities: [{
        browserName: 'firefox',
    }],
    sync: true,
    logLevel: 'debug',
    deprecationWarnings: true,
    bail: 0,
    baseUrl: 'http://google.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: [
        'selenium-standalone',
    ],//
    framework: 'mocha',
    reporters: [
        //"@wdio/concise-reporter",
        //"@wdio/dot-reporter",
        //"@wdio/junit-reporter",
        "@wdio/spec-reporter"
    ],
    mochaOpts: {
        ui: 'bdd',
        timeout: 30000,
        compilers: ['js:babel-core/register']
    },
};
```

**Describe the bug**
All tests pass and yet the suite overall still fails.

**To Reproduce**
Simple Mocha test just opening a URL. 

```
import { expect } from 'chai'

describe('Test', () => {
    it('test', () => {
        browser.url('/');
    })
});
```

**Expected behavior**
Test suite should pass along with the single test.

**Log**
`wdio.log`
```
2018-11-23T08:42:27.883Z DEBUG wdio-config: wdio-sync found, running tests synchronous
2018-11-23T08:42:28.870Z DEBUG wdio-cli:run: Run suite with config ./tests/e2e/configs/wdio.conf.js and params { _: [ './tests/e2e/configs/wdio.conf.js' ],
  spec: [ '.\\tests\\e2e\\steps\\visual.js' ],
  '$0': 'node_modules\\@wdio\\cli\\bin\\wdio.js' }
2018-11-23T08:42:29.076Z INFO wdio-cli:Launcher: Run onPrepare hook
2018-11-23T08:42:30.932Z ERROR wdio-cli:utils: A service failed in the 'onPrepare' hook
TypeError: this._redirectLogStream is not a function
    at Object.onPrepare (C:\Users\[REDACTED]\IntelliJIDEAProjects\wdio-base-e2e\node_modules\@wdio\selenium-standalone-service\src\launcher.js:26:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Continue...
2018-11-23T08:42:30.935Z INFO wdio-local-runner: Start worker 0-0 with arg: ./tests/e2e/configs/wdio.conf.js,--spec,.\tests\e2e\steps\visual.js
2018-11-23T08:42:39.012Z DEBUG wdio-local-runner: Runner 0-0 finished with exit code 1
2018-11-23T08:42:39.123Z INFO wdio-cli:Launcher: Run onComplete hook

```

**Additional context**
`Output`
```
"@wdio/spec-reporter" Reporter:
    ------------------------------------------------------------------
[firefox 10.0 windows #0-0] Spec: C:\Users\[REDACTED]\IntelliJIDEAProjects\wdio-base-e2e\tests\e2e\steps\visual.js
[firefox 10.0 windows #0-0] Running: firefox (v10.0) on windows
[firefox 10.0 windows #0-0]
[firefox 10.0 windows #0-0] Test
[firefox 10.0 windows #0-0]    ✓ Simple test
[firefox 10.0 windows #0-0]
[firefox 10.0 windows #0-0] 1 passing (3.2s)

Stdout:
    [0-0] Hello

Stderr:
(node:20644) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[0-0] (node:19996) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Test Suites:     0 passed, 1 failed, 1 total (100% completed)
Time:            🕛  10.23s

Ended WebDriver sessions gracefully after a SIGINT signal was received!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wdio-base-e2e@0.0.1 test:e2e: `wdio ./tests/e2e/configs/wdio.conf.js "--spec" ".\test\e2e\steps\visual.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wdio-base-e2e@0.0.1 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[REDACTED]\AppData\Roaming\npm-cache\_logs\2018-11-23T08_42_39_178Z-debug.log
```

**Comment by christian-bromann** [comment]
@nextlevelbeard can you provide a minimal reproducible example?

**Comment by christian-bromann** [comment]
I don't see any cookie command or whatever being called.

**Comment by nextlevelbeard** [comment]
@christian-bromann With `5.0.0-beta.12`, the suite does not fail. But the error
```
ERROR wdio-cli:utils: A service failed in the 'onPrepare' hook
TypeError: this._redirectLogStream is not a function
    at Object.onPrepare (C:\Users\[REDACTED]\IntelliJIDEAProjects\wdio-base-e2e\node_modules\@wdio\selenium-standalone-service\src\launcher.js:26:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Continue...
```
remains in the logs.

**Comment by christian-bromann** [comment]
This is not reproducible. Not sure what you did with `support.js` but you can't run commands like that. Maybe that is what triggered. this error.

**Comment by smarigowda** [comment]
I am seeing this issue with v5.0

**Comment by christian-bromann** [comment]
@smarigowda this doesn't help much .. please provide a reproducible example.

**Comment by stsvilik** [comment]
@christian-bromann I think I found the issue, it may have to do with https://github.com/webdriverio/webdriverio/blob/fcb6a3decec4adb1d7dc94cc5ca08f8247ce3ae1/packages/wdio-cli/src/utils.js#L23
When you destructure methods from service, they loose scope of the class they are part of. To fix this you need to bind them explicitly to a service object.

**Comment by christian-bromann** [comment]
@stsvilik mind making a PR?

**Comment by stsvilik** [comment]
@christian-bromann I'll give it a shot ;)

**Comment by stsvilik** [comment]
@christian-bromann https://github.com/webdriverio/webdriverio/pull/3315/files
