### ISSUE TITLE
The `attach` method in the WebDriverIO 5 beta returns a browser without the URL info (all remote calls break)

### ISSUE THREAD

**Issue by thesunny** [webdriverio/webdriverio#3098]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.0.0-beta.10
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** n/a
 - **Node.js version:** 8.11.1
 - **NPM version:** yarn 1.7.0
 - **Browser name and version:** Chrome 70.0.3538.110
 - **Platform name and version:** Mac OSX High Sierra 10.13.2
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
```js
// capabilities
const capabilities = {
  browserName: "chrome",
  chromeOptions: {
    args: ["--window-size-1024,768"],
  },
}
```

**Describe the bug**
This is in the new version 5 beta. It does not throw an error when I `attach` to an existing session but it throws an error as soon as I call a method on that attached session. It appears that none of the URL parts are correctly set in the `attach`ed session as it is logging a `[POST]` that looks like this:

```
  console.info node_modules/@wdio/logger/build/node.js:96
    2018-12-04T17:55:45.140Z INFO webdriver: COMMAND navigateTo("https://www.google.ca/")

  console.info node_modules/@wdio/logger/build/node.js:96
    2018-12-04T17:55:45.140Z INFO webdriver: [POST] undefined://undefined/:undefinedundefined/session/acb829cb16e2177c514ed4fd6237488c/url

  console.info node_modules/@wdio/logger/build/node.js:96
    2018-12-04T17:55:45.140Z INFO webdriver: DATA { url: 'https://www.google.ca/' }
```

Notice that the host, port, path, etc all say `undefined`.

**To Reproduce**

I'm running this from within a `jest` test but it should work identically from any nodejs program
```js
    const capabilities = {
      browserName: "chrome",
      chromeOptions: {
        args: ["--window-size-1024,768"],
      },
    }
    const browser = await remote({ capabilities })
    await browser.url("https://news.ycombinator.com/") // this works
    const attachedBrowser = await attach({ sessionId: browser.sessionId })
    await attachedBrowser.url("https://www.google.ca/") // this fails
```

Note: It was run within an async `it` block. You will have to surround the code like this to run it in nodejs.

```js
(async function () {
   // code goes here
})()
```

Here is the error message I see (along with the logging info I posted above)
```
  console.error node_modules/@wdio/logger/build/node.js:96
    2018-12-04T18:06:14.371Z ERROR webdriver: Request failed after retry due to Error: Error: Invalid protocol: undefined:
        at Request._callback (/Users/sunnyhirai/Projects/kb/node_modules/webdriver/src/request.js:85:27)
        at self.callback (/Users/sunnyhirai/Projects/kb/node_modules/request/request.js:186:22)
        at emitOne (events.js:116:13)
        at Request.emit (events.js:211:7)
        at Request.Object.<anonymous>.Request.init (/Users/sunnyhirai/Projects/kb/node_modules/request/request.js:455:17)
        at new Request (/Users/sunnyhirai/Projects/kb/node_modules/request/request.js:128:8)
        at request (/Users/sunnyhirai/Projects/kb/node_modules/request/index.js:53:10)
        at Promise (/Users/sunnyhirai/Projects/kb/node_modules/webdriver/src/request.js:84:49)
        at new Promise (<anonymous>)
        at WebDriverRequest._request (/Users/sunnyhirai/Projects/kb/node_modules/webdriver/src/request.js:84:16)
        at WebDriverRequest.makeRequest (/Users/sunnyhirai/Projects/kb/node_modules/webdriver/src/request.js:39:21)
        at Browser.<anonymous> (/Users/sunnyhirai/Projects/kb/node_modules/webdriver/src/command.js:80:24)
        at Browser.url (/Users/sunnyhirai/Projects/kb/node_modules/webdriverio/src/commands/browser/url.js:47:17)
        at Object.<anonymous> (/Users/sunnyhirai/Projects/kb/imports/wd5/test/wd5.client.test.js:32:27)
        at Generator.next (<anonymous>)
        at step (/Users/sunnyhirai/Projects/kb/imports/wd5/test/wd5.client.test.js:5:191)
        at /Users/sunnyhirai/Projects/kb/imports/wd5/test/wd5.client.test.js:5:361
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
Note: I think the more telling information is in the logs above with the `undefined` showing up within the portions of the URL.

**Expected behavior**
I expect that the `attachedBrowser.url("https://www.google.ca/")` would navigate the existing browser to the Google website. In the earlier method call to the newly created browser session, the browser was successfully navigated to the Hacker News website.

**Log**
If applicable, add logs to help explain your problem.

Pasted the logs above...

**Additional context**

This code was run within the `jest` testing framework but that should not have any effect on the way the code ran. Everything was run within a single test (i.e. `it` statement).

**Comment by christian-bromann** [comment]
Try
```js
    const capabilities = {
      browserName: "chrome",
      chromeOptions: {
        args: ["--window-size-1024,768"],
      },
    }
    const browser = await remote({ capabilities })
    await browser.url("https://news.ycombinator.com/") // this works
    const attachedBrowser = await attach(browser)
    await attachedBrowser.url("https://www.google.ca/") // this will work now
```
It would be definitely good to add a docs page for this to show the API. Please reach out in the [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/v5?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) channel if you have more question.
