### ISSUE TITLE
Installed latest version of WebdriverIO and faced Multiple cucumber report related Basereporter.js issue and when stopped using this reporter then faced ERROR: Unable to create new service: ChromeDriverService

### ISSUE THREAD

**Issue by gurunanakdevji** [webdriverio/webdriverio#3121]
I have installed latest version of webdriverio ("webdriverio": "^4.14.1")  and my node version is v8.11.3 and I am using testrunner. After completing the complete installation i tried running the test through test runner and  faced below multiple cucumber report issue and then i stopped using this reporting and then again tried running the test then i faced the issue "ERROR: Unable to create new service: ChromeDriverService". Detail of both the issues is mentioned below.

BASE REPORTER ISSUE:

```
C:\NotBackedUp\test-project-wdf-automation\node_modules\webdriverio\build\lib\utils\BaseReporter.js:336
                        throw _iteratorError;
                       ^

TypeError: Cannot read property 'browserName' of undefined
    at MultipleCucumberHtmlReporter.determineMetadata (C:\NotBackedUp\test-project-wdf-automation\node_modules\wdio-mult
iple-cucumber-html-reporter\build\reporter.js:375:54)
    at MultipleCucumberHtmlReporter.runnerResult (C:\NotBackedUp\test-project-wdf-automation\node_modules\wdio-multiple-
cucumber-html-reporter\build\reporter.js:145:47)
    at emitOne (events.js:116:13)
    at MultipleCucumberHtmlReporter.emit (events.js:211:7)
    at BaseReporter.handleEvent (C:\NotBackedUp\test-project-wdf-automation\node_modules\webdriverio\build\lib\utils\Bas
eReporter.js:324:35)
    at Launcher.messageHandler (C:\NotBackedUp\test-project-wdf-automation\node_modules\webdriverio\build\lib\launcher.j
s:688:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
```

> wdfautomation@1.3.2 test C:\NotBackedUp\test-project-wdf-automation
> wdio wdio.conf.js

CHROME DRIVER SERVER ISSUE :
```
ERROR: Unable to create new service: ChromeDriverService
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'LC85B76AB136A', ip: '150.122.115.4', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java
.version: '1.8.0_111'
Driver info: driver.version: unknown
chrome.69_0_3497_100
    at new RuntimeError (C:\NotBackedUp\test-project-wdf-automation\node_modules\webdriverio\build\lib\utils\ErrorHandle
r.js:143:12)
    at Request._callback (C:\NotBackedUp\test-project-wdf-automation\node_modules\webdriverio\build\lib\utils\RequestHan
dler.js:318:39)
    at Request.self.callback (C:\NotBackedUp\test-project-wdf-automation\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\NotBackedUp\test-project-wdf-automation\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\NotBackedUp\test-project-wdf-automation\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wdfautomation@1.3.2 test: `wdio wdio.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wdfautomation@1.3.2 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\NotBackedUp\npm-cache\_logs\2018-12-12T04_13_03_348Z-debug.log
```

 "wdio-cucumber-framework": "^2.2.8",
    "wdio-multiple-cucumber-html-reporter": "^0.3.2",
    "wdio-selenium-standalone-service": "0.0.11",
    "wdio-spec-reporter": "^0.1.5",
    "webdriverio": "^4.14.1"

**Comment by christian-bromann** [comment]
> TypeError: Cannot read property 'browserName' of undefined
    at MultipleCucumberHtmlReporter.determineMetadata (C:\NotBackedUp\test-project-wdf-automation\node_modules\wdio-mult
iple-cucumber-html-reporter\build\reporter.js:375:54)

This error was thrown in wdio-multiple-cucumber-html-reporter. You might want to create an issue there.

> ERROR: Unable to create new service: ChromeDriverService

Also this service is not part of core WebdriverIO so you should raise an issue there as well.
