### ISSUE TITLE
Cannot read property 'default' of .... error when services key is empty

### ISSUE THREAD

**Issue by srghma** [webdriverio/webdriverio#3139]
Environment (please complete the following information):**
 - **WebdriverIO version:** 5.0.0-beta.15
 - **Mode:** [Standalone mode or WDIO Testrunner] -- dont know, local
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] -- sync
 - **Node.js version: [e.g. 8.9.1] -- v10.14.2
 - **NPM version:** [e.g. 5.8.0] -- 6.4.1

Full errror https://pastebin.com/wE6DLNVu
Full package.json https://pastebin.com/HkmnDz5u
Full package-lock.json https://pastebin.com/vaAXjwmh
Full wdio.conf.js https://pastebin.com/k3pLyiy8

## How to reproduce:

In wdio.conf.js

If you comment `// services: [],` or make it `[]` - `wdio wdio.conf.js` will throw error

```
[0-0] 2018-12-17T17:23:57.713Z ERROR wdio-local-runner: Failed launching test session: TypeError: Cannot read property 'default' of null
    at initialisePlugin (/app/node_modules/@wdio/config/src/utils.js:98:23)
    at BaseReporter.initReporter (/app/node_modules/@wdio/runner/src/reporter.js:150:29)
    at Array.map (<anonymous>)
    at new map (/app/node_modules/@wdio/runner/src/reporter.js:20:43)
    at Runner.run (/app/node_modules/@wdio/runner/src/index.js:54:25)
    at process.on.m (/app/node_modules/@wdio/local-runner/src/run.js:17:5)
    at process.emit (events.js:187:15)
    at process.emit (/app/node_modules/source-map-support/source-map-support.js:461:21)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I think this is error because `services` is non-required field - I dont need any service, I just want to connect to my `elgalu/selenium` docker container that has chrome and selenium installed

**Comment by abjerstedt** [comment]
An empty array is still a valid value; and services IS a required field. I think its probably better to make they property exist, even if empty - just to avoid potential confusion.

**Comment by christian-bromann** [comment]
@srghma can you provide a minimal reproducible example? I can for example easily run https://github.com/webdriverio/webdriverio/tree/master/examples/wdio/mocha which also has no service option.

**Comment by christian-bromann** [comment]
Closing due to inactivity .. happy to reopen if a reproducible example can be provided

**Comment by hunzai** [comment]
@christian-bromann Here are steps to reproduce

1. Follow the instructions to setup on https://webdriver.io/docs/gettingstarted.html
2. Make sure you choose `local` runner 
3. Add sample test provided at https://webdriver.io/docs/gettingstarted.html
4. Run `./node_modules/.bin/wdio wdio.conf.js ` 

Expected:
Test should run or provide proper error (like what capabilities are missing)

Actual:
```   'Error: unhandled request\n    at getErrorFromResponseBody (/projects/sync-app-e2e/node_modules/webdriver/build/utils.js:343:12)\n    at Request._callback (/sync-app-e2e/node_modules/webdriver/build/request.js:121:64)\n    at Request.self.callback (/projects/sync-app-e2e/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:189:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at Request.<anonymous> (/projects/sync-app-e2e/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:189:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at IncomingMessage.<anonymous> (//projects/sync-app-e2e/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:277:13)' }
[0-0] 2019-06-18T11:00:57.183Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/projects/sync-app-e2e/node_modules/@wdio/runner/build/index.js:91:74)
    at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by industral** [comment]
had exactly the same issue

**Comment by industral** [comment]
if somebody has the same issue - just remove `path: '/'`. At least it made a trick for me.

**Comment by rajjeet** [comment]
> if somebody has the same issue - just remove `path: '/'`. At least it made a trick for me.

Made no difference. Still getting the following error: 
```bash
ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/home/raj/dev/try-wdio/node_modules/@wdio/runner/build/index.js:68:74)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```
I'm trying to bootstrap this library off a fresh empty project. Initializing the config using `./node_modules/.bin/wdio config` followed by `./node_modules/.bin/wdio config`. Here's the npm packages in `package.json`:
```js
    "@wdio/cli": "^5.12.5",
    "@wdio/local-runner": "^5.12.5",
    "@wdio/mocha-framework": "^5.12.1",
    "@wdio/spec-reporter": "^5.12.1",
    "@wdio/sync": "^5.12.3",
    "chromedriver": "^76.0.1",
    "wdio-chromedriver-service": "^5.0.2",
    "wdio-selenium-standalone-service": "0.0.12"
```
