### ISSUE TITLE
unable to run command ./node_modules/.bin/wdio config

### ISSUE THREAD

**Issue by rajivnw** [webdriverio/webdriverio#3167]
1. Install wdio-cli v5 using command : npm i wdio-cli --save-dev
2. Run command ./node_modules/.bin/wdio config
getting below error -
$ ./node_modules/.bin/wdio config
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../build'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/rajiv/Desktop/appiumIO/node_modules/wdio-cli/bin/wdio.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

-----------
package.json

{
  "name": "wdiocli",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "wdio-cli": "^5.0.0-alpha.7"
  }
}

**Comment by WillBrock** [comment]
@rajivnw the packages maintained by wdio are now scoped to ```@wdio``` so you just need to run this:

```npm i --save-dev @wdio/cli```

**Comment by sgarine-pk** [comment]
Thank you will. you made my day
