### ISSUE TITLE
removeApp is not working in v5

### ISSUE THREAD

**Issue by DavertMik** [webdriverio/webdriverio#3172]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.0.0
 - **Mode:** standalone
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 8.x
 - **NPM version:** 5.8.0
 - **Browser name and version:** Android
 - **Platform name and version:** Android

**Describe the bug**

I'm trying to call `removeApp` the way It was possible in webdriverio v4, providing only bundleId parameter. However, it's not possible. Validation asks to app parameter to be filled in, empty array or null is not accepted.

```
https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/protocol/appium.json#L320
```
I think it's a bug as appId is iOS parameter while bundleId is for Android...
And I can't have them both.

Tried to send null and empty array. 

**To Reproduce**
Try to remove app on Android

```
```

**Expected behavior**
App is removed

**Log**

```
     Error: Malformed type for "appId" parameter of command removeApp
Expected: string[]
Actual: object

For more info see http://appium.io/docs/en/commands/device/app/remove-app/

```

**Comment by christian-bromann** [comment]
according to the [protocol](https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L436) both are required. What you can do is to call `removeApp([], ["mybundleid"])`

**Comment by mirao** [comment]
What's the proper way how to remove app with new Appium/WebDriver?
I cannot get it working after upgrade to CodeceptJS to 2.0.x and WebDriver 5
```
    I remove app "com.basistablet.android.beta"
2019-03-01T15:12:20.952Z ERROR webdriver: Request failed due to invalid argument: Parameters were incorrect. We wanted {"required":[["appId"],["bundleId"]],"optional":["options","sessionId","id"]} and you sent ["appId","bundleId"]
    at getErrorFromResponseBody (/mnt/c/Workspace/codeceptjs/node_modules/webdriver/build/utils.js:343:10)
    at Request._callback (/mnt/c/Workspace/codeceptjs/node_modules/webdriver/build/request.js:116:64)
    at Request.self.callback (/mnt/c/Workspace/codeceptjs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/mnt/c/Workspace/codeceptjs/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/mnt/c/Workspace/codeceptjs/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
  ✖ FAILED in 2638ms
```

**Comment by christian-bromann** [comment]
> I cannot get it working after upgrade to CodeceptJS to 2.0.x

If you use ConceptJS, raise an issue in that project

**Comment by mirao** [comment]
OK, thanks

**Comment by mirao** [comment]
@marthinus-engelbrecht I can confirm that `{ "bundleId": "myapp.android" }` sent to the REST API endpoint works (Android). IMHO it doesn't correspond with definition of `remove_app` in https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/protocol/appium.json.

**Comment by mirao** [comment]
Issue created for CodeceptJS: https://github.com/Codeception/CodeceptJS/issues/1535
