### ISSUE TITLE
failing assertions and all exceptions are ignored when using jasmine framework on webdriver 5.x

### ISSUE THREAD

**Issue by mo** [webdriverio/webdriverio#3177]
After upgrading to webdriver 5.x I noticed that the jasmine framework support doesn't work any more.

How to reproduce bug:
1. git clone git@github.com:mo/wdio-v5-jasmine-bug-repro-example.git
2. run "npm test"

The following testcase passed despite having expect(true).toBe(false) and also throwing exceptions both in the main testcase and in the beforeAll() section.

```js
describe('webdriver.io page', () => {
    beforeAll(() => {
        console.log("111111111111111111111111111111 beforeAll starting")
        expect(true).toBe(false)
        throw Error('wtf')
        console.log("222222222222222222222222222222 beforeAll ending")
    })
    it('should have the right title', () => {
        console.log("333333333333333333333333333333 testcase starting")
        browser.url('https://webdriver.io');
        expect(true).toBe(false)
        throw "not correct at all"
        console.log("444444444444444444444444444444 testcase ending")
    });
});
```

The project has been setup by using "wdio config" and picking everything as default exception picking "jasmine" framework, "spec" reporter.

I also noted bug #3084 but the above testcase shows that this issue affects not just beforeAll, but also normal testcases and not just exceptions but all regular expect(x).toBe(y) failures.

**Comment by mo** [comment]
@christian-bromann huge thanks for taking a look at this so quickly!

I tried to test the patch to see if it solves my issue, but I was not able to get it to work unfortunately.

What I did was that I checked out "webdriverio" from master and then I did this:

```
npm install
npm run setup
git merge origin/cb-jasmine-error-fix
npm run build
cd packages/wdio-jasmine-framework/
npm link
```

and finally, in the bug repro project I did:

```
npm link @wdio/jasmine-framework
npm test
```

But this reported "success" despite the failed expect() calls etc. Perhaps I did something wrong in the above?

**Comment by carlos-gva** [comment]
@christian-bromann I was testing this issue with the today's **v5.1.0** and it seems to be still happening.

I injected a ```expect(true).toEqual(false);``` on my test after a clean *npm install* but the report still returns that all tests passed. 🤔 

I also printed the `test` object on the afterTest hook to be sure about this and it has the attribute `passed: true`.

**Comment by carlos-gva** [comment]
@mo Can I reopen the issue, I mean, can you also reproduce it?

**Comment by christian-bromann** [comment]
@carlos-gva for me it is not reproducible on current master when running the example wdio suite from the repo. Could you try with that one?

**Comment by carlos-gva** [comment]
@christian-bromann Yes, I think so. Let me check that.

**Comment by carlos-gva** [comment]
@christian-bromann Trying that example on *master*, everything goes as expected.
The test fails when using ```expect(true).toEqual(false)```.

```
[chrome 71.0.3578.98 Mac OS X #0-0] Running: chrome (v71.0.3578.98) on Mac OS X
[chrome 71.0.3578.98 Mac OS X #0-0]
[chrome 71.0.3578.98 Mac OS X #0-0] webdriver.io page
[chrome 71.0.3578.98 Mac OS X #0-0]    ✖ should have the right title
[chrome 71.0.3578.98 Mac OS X #0-0]
[chrome 71.0.3578.98 Mac OS X #0-0] 1 failing (3s)
[chrome 71.0.3578.98 Mac OS X #0-0]
[chrome 71.0.3578.98 Mac OS X #0-0] 1) webdriver.io page should have the right title
[chrome 71.0.3578.98 Mac OS X #0-0] Expected true to equal false.
```

So, this just happens when using the published version of the wdio framework.

**Comment by christian-bromann** [comment]
@carlos-gva these versions should be identical.

**Comment by carlos-gva** [comment]
@mo
```
git clone git@github.com:webdriverio/webdriverio.git
cd ./webdriverio
npm install
npm run setup
```

```
$ cd ./examples/wdio
```

```
$ npm run test:jasmine
```

**Comment by christian-bromann** [comment]
@carlos-gva @mo I've resolved and released the issue in #3240

**Comment by carlos-gva** [comment]
@christian-bromann True! 🙏 

It's working now, but I can't update the **@wdio/cli** from **v5.2.0** to **v5.2.1** because when running the tests, it seems that the logger is waiting for the dependency you removed in this update.

```
Error: Cannot find module 'source-map-support/register'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/carlos.gouveia/repos/wedriverio/node_modules/@wdio/logger/build/index.js:8:1)
```

Do you want me to open an issue with this?

**Comment by christian-bromann** [comment]
> Do you want me to open an issue with this?

No, I want you do update to `v5.2.2` 😉

**Comment by carlos-gva** [comment]
😁 
Many thanks! 🙏 
All good now!
💪 💪

**Comment by mo** [comment]
I can confirm that 5.2.2 fixes the bug for me too. Thanks a lot for the fix.
