### ISSUE TITLE
Not Getting Started [OS/X]

### ISSUE THREAD

**Issue by goofballLogic** [webdriverio/webdriverio#3182]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.0.3
 - **Mode:** Standalone
 - **Node.js version:** 11.4.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** FireFox 64.0 (64-bit)
 - **Platform name and version:** macOS 10.13.6
 - **Additional wdio packages used (if applicable):** none

**Config of WebdriverIO**
Followed the Getting started guide:
1. npm install webdriverio
2. Creat the specified test file

**Describe the bug**
running `node test` results in the following:

```
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'source-map-support/register'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/webdriverio/build/index.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**To Reproduce**
Follow the getting started guide: https://webdriver.io/docs/gettingstarted.html

**Expected behavior**
this should output the following:

`Title was: WebdriverIO · Next-gen WebDriver test framework for Node.js`

**Additional context**
I tried to resolve this issue by manually installing source-map-support. This allowed the test to execute for the first time. However, I then receive a different problem. Happy to break this out into another bug report if necessary.

**Logs after manually installing source-map-support**

***webdriver***
```
node test
2018-12-26T10:50:35.157Z DEBUG wdio-config: wdio-sync not found, running tests asynchronous
Title was: WebdriverIO · Next-gen WebDriver test framework for Node.js
2018-12-26T10:50:49.773Z ERROR webdriver: Request failed due to Error: {}DELETE /session/6f533b1f-2320-eb4b-b1a9-79ddf52406e6 did not match a known command
    at Request._callback (/Users/andrewgibson/src/webdriverio-test/node_modules/webdriver/src/request.js:86:27)
    at Request.self.callback (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
Error: {}DELETE /session/6f533b1f-2320-eb4b-b1a9-79ddf52406e6 did not match a known command
    at Request._callback (/Users/andrewgibson/src/webdriverio-test/node_modules/webdriver/src/request.js:86:27)
    at Request.self.callback (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
```

***selenium log***

```
./geckodriver --port 4444
1545821406466	geckodriver	INFO	geckodriver 0.21.0
1545821406473	geckodriver	INFO	Listening on 127.0.0.1:4444
1545821435477	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-foreground" "-no-remote" "-profile" "/var/folders/gv/r39k1_4s3r5gyrmbcmrrnp8r0000gn/T/rust_mozprofile.j1Ka9sN7y6p8"
1545821436308	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: resource://pdf.js/
1545821436308	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid host permission: about:reader*
1545821436454	Marionette	DEBUG	Received observer notification profile-after-change
1545821436575	Marionette	DEBUG	Received observer notification command-line-startup
1545821436575	Marionette	DEBUG	Received observer notification nsPref:changed
1545821436575	Marionette	DEBUG	Init aborted (running=false, enabled=true, finalUIStartup=false)
1545821436797	Marionette	DEBUG	Received observer notification toplevel-window-ready
Can't find symbol 'GetGraphicsResetStatus'.
1545821437813	Marionette	DEBUG	Received observer notification sessionstore-windows-restored
1545821437813	Marionette	DEBUG	Waiting for delayed startup...
1545821438036	Marionette	DEBUG	Setting recommended pref app.update.disabledForTesting to true
1545821438036	Marionette	DEBUG	Setting recommended pref security.turn_off_all_security_so_that_viruses_can_take_over_this_computer to true
1545821438037	Marionette	DEBUG	Setting recommended pref apz.content_response_timeout to 60000
1545821438037	Marionette	DEBUG	Setting recommended pref browser.contentblocking.introCount to 99
1545821438037	Marionette	DEBUG	Setting recommended pref browser.download.panel.shown to true
1545821438037	Marionette	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1545821438038	Marionette	DEBUG	Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1545821438038	Marionette	DEBUG	Setting recommended pref browser.search.update to false
1545821438038	Marionette	DEBUG	Setting recommended pref browser.tabs.disableBackgroundZombification to false
1545821438039	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1545821438039	Marionette	DEBUG	Setting recommended pref browser.tabs.warnOnOpen to false
1545821438039	Marionette	DEBUG	Setting recommended pref browser.usedOnWindows10.introURL to 
1545821438039	Marionette	DEBUG	Setting recommended pref browser.urlbar.suggest.searches to false
1545821438040	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1545821438040	Marionette	DEBUG	Setting recommended pref dom.disable_beforeunload to true
1545821438040	Marionette	DEBUG	Setting recommended pref dom.disable_open_during_load to false
1545821438040	Marionette	DEBUG	Setting recommended pref dom.file.createInChild to true
1545821438040	Marionette	DEBUG	Setting recommended pref dom.max_chrome_script_run_time to 0
1545821438040	Marionette	DEBUG	Setting recommended pref dom.max_script_run_time to 0
1545821438040	Marionette	DEBUG	Setting recommended pref extensions.getAddons.cache.enabled to false
1545821438041	Marionette	DEBUG	Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1545821438041	Marionette	DEBUG	Setting recommended pref network.http.prompt-temp-redirect to false
1545821438041	Marionette	DEBUG	Setting recommended pref network.http.speculative-parallel-limit to 0
1545821438041	Marionette	DEBUG	Setting recommended pref security.fileuri.strict_origin_policy to false
1545821438041	Marionette	DEBUG	Setting recommended pref security.notification_enable_delay to 0
1545821438041	Marionette	DEBUG	Setting recommended pref signon.autofillForms to false
1545821438041	Marionette	DEBUG	Setting recommended pref signon.rememberSignons to false
1545821438041	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1545821438092	Marionette	INFO	Listening on port 55241
1545821438092	Marionette	DEBUG	Remote service is active
1545821438137	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:55270
1545821438141	Marionette	TRACE	0 -> [0,1,"WebDriver:NewSession",{"browserName":"firefox","capabilities":{"desiredCapabilities":{"browserName":"firefox"}}}]
1545821438206	Marionette	DEBUG	[4294967297] Frame script loaded
1545821438208	Marionette	DEBUG	[4294967297] Frame script registered
1545821438216	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"6f533b1f-2320-eb4b-b1a9-79ddf52406e6","capabilities":{"browserName":"firefox","browserVersion":"64.0" ... ecCompliantPointerOrigin":false,"moz:webdriverClick":true,"capabilities":{"desiredCapabilities":{"browserName":"firefox"}}}}]
1545821438234	Marionette	TRACE	0 -> [0,2,"WebDriver:Navigate",{"url":"https://webdriver.io"}]
1545821438245	Marionette	DEBUG	[4294967297] Received DOM event beforeunload for about:blank
1545821438767	Marionette	DEBUG	[4294967297] Received DOM event pagehide for about:blank
1545821441278	Marionette	DEBUG	[4294967297] Received DOM event DOMContentLoaded for https://webdriver.io/
1545821449271	Marionette	DEBUG	[4294967297] Received observer notification outer-window-destroyed
1545821449271	Marionette	DEBUG	[4294967297] Received observer notification outer-window-destroyed
1545821449274	Marionette	DEBUG	[4294967297] Received observer notification outer-window-destroyed
1545821449751	Marionette	DEBUG	[4294967297] Received DOM event pageshow for https://webdriver.io/
1545821449752	Marionette	TRACE	0 <- [1,2,null,{"value":null}]
1545821449759	Marionette	TRACE	0 -> [0,3,"WebDriver:GetTitle",{}]
1545821449760	Marionette	TRACE	0 <- [1,3,null,{"value":"WebdriverIO · Next-gen WebDriver test framework for Node.js"}]
console.error: BroadcastService: 
  receivedBroadcastMessage: handler for
  remote-settings/monitor_changes
  threw error:
  Message: Error: Polling for changes failed: NetworkError when attempting to fetch resource..
  Stack:
    remoteSettingsFunction/remoteSettings.pollChanges@resource://services-settings/remote-settings.js:750:13
```

**Comment by cuki** [comment]
Have the same issue.

@goofballLogic What worked for me as workaround, was to run in the project root `npm install source-map-support`, although this should be installed with the package accordingly when installing it.

**Comment by goofballLogic** [comment]
I think we just need to add this as a dependency for the standalone package. Happy to submit a PR for that if you agree @christian-bromann ?

**Comment by christian-bromann** [comment]
> I think we just need to add this as a dependency for the standalone package.

see #3205

**Comment by dolanmiu** [comment]
Happening on Windows too, not just OS/X

**Comment by christian-bromann** [comment]
the `source-map-support` issue was resolved today

**Comment by dolanmiu** [comment]
@christian-bromann how do i use the fix then? 

I have currently installed `source-map-support` on `@wdio/cli` `5.2.1`, which "fixes" it

**Comment by christian-bromann** [comment]
@dolanmiu in the latest release sourcemap got disabled, you don't need that package anymore.

**Comment by cuki** [comment]
@christian-bromann It seems that wdio-logger@5.0.3 still has the problematic code, all packages need to be republished without `source-map-support/register`.

**Comment by christian-bromann** [comment]
let me do that

**Comment by christian-bromann** [comment]
`v5.2.2` should have a fix for it

**Comment by cuki** [comment]
Works like a charm now, thanks @christian-bromann!
