### ISSUE TITLE
Not Getting Started 2 (Using test runner)

### ISSUE THREAD

**Issue by goofballLogic** [webdriverio/webdriverio#3183]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.0.3
 - **Mode:** Standalone
 - **Node.js version:** 11.4.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** FireFox 64.0 (64-bit)
 - **Platform name and version:** macOS 10.13.6
 - **Additional wdio packages used (if applicable):** none

**Config of WebdriverIO**
Followed the instructions on the Getting Started page to create this:

```
exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
    // on a remote machine).
    runner: 'local',

    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called. Notice that, if you are calling `wdio` from an
    // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
    // directory is where your package.json resides, so `wdio` will be called from there.
    //
    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'firefox'
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error
    logLevel: 'info',
    //
    // Warns when a deprecated command is used
    deprecationWarnings: true,
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Initialize the browser instance with a WebdriverIO plugin. The object should have the
    // plugin name as key and the desired plugin options as properties. Make sure you have
    // the plugin installed before running any tests. The following plugins are currently
    // available:
    // WebdriverCSS: https://github.com/webdriverio/webdrivercss
    // WebdriverRTC: https://github.com/webdriverio/webdriverrtc
    // Browserevent: https://github.com/webdriverio/browserevent
    // plugins: {
    //     webdrivercss: {
    //         screenshotRoot: 'my-shots',
    //         failedComparisonsRoot: 'diffs',
    //         misMatchTolerance: 0.05,
    //         screenWidth: [320,480,640,1024]
    //     },
    //     webdriverrtc: {},
    //     browserevent: {}
    // },
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    // services: [],//
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: http://webdriver.io/docs/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: http://webdriver.io/docs/dot-reporter.html
    reporters: ['dot'],

    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // beforeSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },

    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    // beforeTest: function (test) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function () {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function () {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    // afterTest: function (test) {
    // },
    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },

    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // }
}

```

**Describe the bug**
Running the command as instructed produces an error because the generated configuration is incorrect for the geckodriver being used

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
```
Stdout:
2018-12-26T12:42:11.345Z INFO wdio-cli:Launcher: Run onPrepare hook
2018-12-26T12:42:11.348Z INFO wdio-local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2018-12-26T12:42:11.719Z INFO wdio-local-runner: Run worker command: run
[0-0] 2018-12-26T12:42:11.781Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.781Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
[0-0] 2018-12-26T12:42:11.799Z INFO webdriver: Retrying 1/3
[0-0] 2018-12-26T12:42:11.800Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.800Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
[0-0] 2018-12-26T12:42:11.803Z INFO webdriver: Retrying 2/3
[0-0] 2018-12-26T12:42:11.803Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.803Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
[0-0] 2018-12-26T12:42:11.805Z INFO webdriver: Retrying 3/3
[0-0] 2018-12-26T12:42:11.805Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.805Z INFO webdriver: DATA { capabilities:

Stdout:
2018-12-26T12:42:11.345Z INFO wdio-cli:Launcher: Run onPrepare hook
2018-12-26T12:42:11.348Z INFO wdio-local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2018-12-26T12:42:11.719Z INFO wdio-local-runner: Run worker command: run
[0-0] 2018-12-26T12:42:11.781Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.781Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
[0-0] 2018-12-26T12:42:11.799Z INFO webdriver: Retrying 1/3
[0-0] 2018-12-26T12:42:11.800Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.800Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
[0-0] 2018-12-26T12:42:11.803Z INFO webdriver: Retrying 2/3
[0-0] 2018-12-26T12:42:11.803Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.803Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
[0-0] 2018-12-26T12:42:11.805Z INFO webdriver: Retrying 3/3
[0-0] 2018-12-26T12:42:11.805Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.805Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },

Stdout:
2018-12-26T12:42:11.345Z INFO wdio-cli:Launcher: Run onPrepare hook
2018-12-26T12:42:11.348Z INFO wdio-local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2018-12-26T12:42:11.719Z INFO wdio-local-runner: Run worker command: run
[0-0] 2018-12-26T12:42:11.781Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.781Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
[0-0] 2018-12-26T12:42:11.799Z INFO webdriver: Retrying 1/3
[0-0] 2018-12-26T12:42:11.800Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.800Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
[0-0] 2018-12-26T12:42:11.803Z INFO webdriver: Retrying 2/3
[0-0] 2018-12-26T12:42:11.803Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.803Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
[0-0] 2018-12-26T12:42:11.805Z INFO webdriver: Retrying 3/3
[0-0] 2018-12-26T12:42:11.805Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2018-12-26T12:42:11.805Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
2018-12-26T12:42:11.933Z DEBUG wdio-local-runner: Runner 0-0 finished with exit code 1

Stderr:
[0-0] 2018-12-26T12:42:11.799Z WARN webdriver: Request failed due to POST /wd/hub/session did not match a known command
[0-0] 2018-12-26T12:42:11.802Z WARN webdriver: Request failed due to POST /wd/hub/session did not match a known command
[0-0] 2018-12-26T12:42:11.804Z WARN webdriver: Request failed due to POST /wd/hub/session did not match a known command
[0-0] 2018-12-26T12:42:11.806Z ERROR webdriver: Request failed due to Error: POST /wd/hub/session did not match a known command
    at Request._callback (/Users/andrewgibson/src/webdriverio-test/node_modules/webdriver/src/request.js:86:27)
    at Request.self.callback (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
[0-0] 2018-12-26T12:42:11.815Z ERROR wdio-runner: Error: POST /wd/hub/session did not match a known command
    at Request._callback (/Users/andrewgibson/src/webdriverio-test/node_modules/webdriver/src/request.js:86:27)
    at Request.self.callback (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)

Worker Error:
Error: POST /wd/hub/session did not match a known command
    at Request._callback (/Users/andrewgibson/src/webdriverio-test/node_modules/webdriver/src/request.js:86:27)
    at Request.self.callback (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/andrewgibson/src/webdriverio-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)

Test Suites:	 0 passed, 1 failed, 1 total (100% completed)
Time:		 🕘  0.73s
```

**Additional context**
It turns out that Geckodriver requires a "path" of "/" to be added to the configuration file. This isn't indicated anywhere on the Getting Started page and I eventually tracked it down in an old closed bug report within the webdriverio repo ( #2528  )

**Comment by christian-bromann** [comment]
In the getting started guide you can see in the example that the path is set:
```js
    const browser = await remote({
        logLevel: 'error',
        path: '/',
        capabilities: {
            browserName: 'firefox'
        }
    });
```

**Comment by goofballLogic** [comment]
@christian-bromann there are two sections to the getting started guide. This bug occurs when you _generate_ the above configuration file in the _[Let's Get Serious](https://webdriver.io/docs/gettingstarted.html#let-s-get-serious)_ section of the getting started guide.

I think we just need to add a note that the generated file doesn't contain the necessary tweak to work with geckodriver? Happy to submit a PR if you agree
