### ISSUE TITLE
TypeError: Cannot read property 'appium-version' of undefined (on version 5.0.3)

### ISSUE THREAD

**Issue by yanplu** [webdriverio/webdriverio#3186]
**//browser2.test.js :**
```js
var webdriverio = require('webdriverio'); //webdriver
var expect = require('chai'); //assert
var assert = require('assert'); //assert
var should = require('should');//assert
var browser;
var options = {
    desiredCapabilities: {
        //chrome、safari、firefox
        browserName: 'chrome',
        chromeOptions: {
            args: [
                // 'headless',
                // Use --disable-gpu to avoid an error from a missing Mesa
                // library, as per
                // https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md
                // 'disable-gpu',
                "--start-maximized",
                "allow-running-insecure-content",
                "--test-type"
            ],
        },
    }
};

describe('browser test suite', function () {
    beforeEach('beforeEach test',async function () {
        browser = webdriverio
            .remote(options)
            .init();
            await browser.url('https://www.baidu.com/')
            .setValue('#kw', 'mocha')
            .click('#su')
            .pause(5000);
    })

    afterEach('afterEach test', function (done) {
        browser.end(done())
    })


    it('test title ', async () => {
        var title = await browser.getTitle();
        console.log('Title was: ' + title);
        assert.equal(title, "mocha_百度搜索");   
    });

    
    it('test $$',() => {         
        const text = browser.$('#1');
        console.log(text.$$('div')[2].$('a').getText()); // outputs        
    });   
});
```
----------------------------------------------------------
**//package.json**
```
{
  "name": "browser-test",
  "version": "1.0.0",
  "description": "webdriverio-brower-funcation",
  "main": "baidu_search_page.js",
  "scripts": {
    "test": "mocha --recursive --reporter mochawesome --timeout 6000000",
    "jar": "java -jar selenium-server-standalone-3.5.3.jar"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "allure-commandline": "^2.8.1",
    "assert": "^1.4.1",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "found": "^0.3.14",
    "mocha": "^5.2.0",
    "mochawesome": "^3.1.1",
    "selenium-standalone": "^6.15.4",
    "selenium-webdriver": "^4.0.0-alpha.1",
    "should": "^13.2.3",
    "source-map-support": "^0.5.9",
    "wdio": "^3.0.0",
    "wdio-allure-reporter": "^0.8.3",
    "wdio-mocha-framework": "^0.6.4",
    "wdio-mochawesome-reporter": "^2.0.1",
    "wdio-spec-reporter": "^0.1.5",
    "webdriverio": "^5.0.3"
  }
}
```
------------------------------------------------
```
PS C:\Work\workspace\Nodejs\js-autotest-framework\Mocha\base\test> mocha .\browser2.test.js
2018-12-27T09:44:57.531Z DEBUG wdio-config: wdio-sync not found, running tests asynchronous


  browser test suite
    1) "before each" hook: beforeEach test for "test title "
    2) "after each" hook: afterEach test for "test title "


  0 passing (76ms)
  2 failing

  1) browser test suite
       "before each" hook: beforeEach test for "test title ":
     **TypeError: Cannot read property 'appium-version' of undefined**
      at mobileDetector (C:\Work\workspace\Nodejs\js-autotest-framework\Mocha\base\node_modules\webdriverio\src\utils.js:199:21)
      at Object.remote (C:\Work\workspace\Nodejs\js-autotest-framework\Mocha\base\node_modules\webdriverio\src\index.js:35:29)
      at Context.<anonymous> (browser2.test.js:28:14)

  2) browser test suite
       "after each" hook: afterEach test for "test title ":
     TypeError: Cannot read property 'end' of undefined
      at Context.<anonymous> (browser2.test.js:37:17)
      at process.topLevelDomainCallback (domain.js:121:23)
```
------------------------------------
The same code is executed correctly on  webdriverio 4.14.1

**Comment by christian-bromann** [comment]
There are bunch of breaking changes in v5 that doesn't allow a seamless upgrade. Please check the [docs](https://webdriver.io/blog/#how-to-upgrade-to-v5) for more information.
