### ISSUE TITLE
Safaridriver fails due to incorrect 'Content-length' header send for empty body

### ISSUE THREAD

**Issue by cuki** [webdriverio/webdriverio#3187]
**Environment:**
 - **WebdriverIO version:** 5.0.3
 - **Mode:** Standalone
 - **Node.js version:** 10.14.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Safari 12.0.2
 - **Platform name and version:** macOS 10.13.6

**Describe the bug**
When communicating directly with Safaridriver using webdriverio, it was unable to successfully process GET/DELETE requests, as every GET/DELETE [response](https://github.com/webdriverio/webdriverio/blob/c6b345ce2aaa128dfd15f6ad25ace0a2769de382/packages/webdriver/src/utils.js#L16) returned an `undefined` body with __400__ status code (BAD_REQUEST).

**To Reproduce**
Basically the same steps as the [Getting Started guide](https://webdriver.io/docs/gettingstarted.html), just using Safaridriver instead of Geckodriver:

1. Install webdriverio
```
npm install webdriverio@5.0.3
```
2. Create simple example file (e.g. example.js)
```js
const { remote } = require('webdriverio');

(async () => {
    const browser = await remote({
        logLevel: 'debug',
        path: '/',
        capabilities: {
            browserName: 'safari'
        }
    });

    await browser.url('https://webdriver.io');

    const title = await browser.getTitle();
    console.log('Title was: ' + title);

    await browser.deleteSession();
})().catch((e) => console.error(e));
```
3. Start SafariDriver
```
safaridriver --enable
safaridriver -p 4444
```
4. Run simple example file within node
```
node example.js
```

**Expected behavior**
Able to run the simple example file defined in reproduction step 2 without any errors.

**Log**
Output when running above specified example file:
```
$ node example.js
2018-12-27T10:06:06.111Z DEBUG wdio-config: wdio-sync not found, running tests asynchronous
2018-12-27T10:06:06.368Z INFO webdriver: [POST] http://0.0.0.0:4444/session
2018-12-27T10:06:06.368Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'safari' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'safari' } }
2018-12-27T10:06:06.989Z INFO webdriver: COMMAND navigateTo("https://webdriver.io")
2018-12-27T10:06:06.989Z INFO webdriver: [POST] http://0.0.0.0:4444/session/45386EF4-015B-46F8-8410-FB5419E9C3EA/url
2018-12-27T10:06:06.989Z INFO webdriver: DATA { url: 'https://webdriver.io' }
2018-12-27T10:06:08.638Z INFO webdriver: COMMAND getTitle()
2018-12-27T10:06:08.638Z INFO webdriver: [GET] http://0.0.0.0:4444/session/45386EF4-015B-46F8-8410-FB5419E9C3EA/title
2018-12-27T10:06:08.641Z DEBUG webdriver: request failed due to missing body
2018-12-27T10:06:08.641Z WARN webdriver: Request failed due to
2018-12-27T10:06:08.641Z INFO webdriver: Retrying 1/2
2018-12-27T10:06:08.641Z INFO webdriver: [GET] http://0.0.0.0:4444/session/45386EF4-015B-46F8-8410-FB5419E9C3EA/title
2018-12-27T10:06:08.643Z DEBUG webdriver: request failed due to missing body
2018-12-27T10:06:08.644Z WARN webdriver: Request failed due to
2018-12-27T10:06:08.644Z INFO webdriver: Retrying 2/2
2018-12-27T10:06:08.644Z INFO webdriver: [GET] http://0.0.0.0:4444/session/45386EF4-015B-46F8-8410-FB5419E9C3EA/title
2018-12-27T10:06:08.645Z DEBUG webdriver: request failed due to missing body
2018-12-27T10:06:08.645Z ERROR webdriver: Request failed due to Error
    at Request._callback (/project/node_modules/webdriver/src/request.js:86:27)
    at Request.self.callback (/project/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/project/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/project/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
Error
    at Request._callback (/project/node_modules/webdriver/src/request.js:86:27)
    at Request.self.callback (/project/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/project/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/project/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
```

Running same "getTitle" request with CURL, which returns the desired title when using Safaridriver:
```
$ curl http://0.0.0.0:4444/session/45386EF4-015B-46F8-8410-FB5419E9C3EA/title
{"value":"WebdriverIO · Next-gen WebDriver test framework for Node.js"
```

**Additional context**
Problem seems to be that `Content-length: 2` header is send when making a GET/DELETE request, ideally __no__ body is specified when making a GET/DELETE request.

For example when changing this snippet:
https://github.com/webdriverio/webdriverio/blob/c6b345ce2aaa128dfd15f6ad25ace0a2769de382/packages/webdriver/src/request.js#L81-L83

To the following:
```js
if (fullRequestOptions.body && Object.keys(fullRequestOptions.body).length) {
    log.info('DATA', fullRequestOptions.body)
} else {
    delete fullRequestOptions.body
}
```

Will resolve the issue and allows the example file to be successfully executed.
However I'm not certain whether you want to always delete/unset body for all request methods or just GET/DELETE.

**Comment by cuki** [comment]
In response to my previous remark about whether we should always delete/unset body for all request methods, it seems geckodriver does not like it when you send POST request without body:
```
$ curl -X POST http://localhost:4444/session/317daefb-0b94-2f41-a436-31093e566053/back
{"value":{"error":"invalid argument","message":"Failed to decode request as JSON: ","stacktrace":"Syntax error at :1:0"}}
```

**Comment by link89** [comment]
I can still find this issue on `webdriver.io@6.6.6`.  And the fix provided by @cuki works well. The fix is used by me in another project to fix this issue.  https://github.com/link89/selenium-federation/commit/b798d12bd3056fa9406f2e2086b0bf70017bf3db

But I think this project is the right place to fix this issue.

**Comment by christian-bromann** [comment]
@link89 I was running the example above with Safaridriver and did not receive any error. Can you post a reproducible example?

**Comment by link89** [comment]
Start the webdriver service  `safaridriver --port=4444`. And then running the following script

```typescript
import { remote } from "webdriverio";
const host = 'localhost';
const opt = {
  hostname: host,
  port: 4444,
  path: '/wd/hub',
  capabilities: {
    browserName: 'safari',
  }
};

const url = "https://github.com";
void (async () => {
  const driver = await remote(opt);
  await driver.navigateTo(url);
  await driver.deleteSession();
})();

```

**Comment by christian-bromann** [comment]
This example can't work. If you start `safaridriver --port=4444` with it will listen on path `/` and not `/wd/hub`. Fixing that and running the script was fine for me.

**Comment by link89** [comment]
My fault. Remove the `path` field.

**Comment by christian-bromann** [comment]
@link89 I can run that script successfully then.

**Comment by mgrybyk** [comment]
Works for me ax well however, I tried with selenium standalone

**Comment by link89** [comment]
My Safari's version is 12. It works well on Safari 13 though.
