### ISSUE TITLE
Migrating PhantomJS capabilities from webdriverio v4 to v5

### ISSUE THREAD

**Issue by jlchereau** [webdriverio/webdriverio#3198]
#### Environment:

WebdriverIO version: 5.0.3
Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: sync
Node.js version: 11.6.0
NPM version: 6.5.0
Browser name and version: MicrosoftEdge v44.17763.1.0
Platform name and version: Windows 10 v1809
Additional wdio packages used (if applicable): @wdio/selenium-standalone service
Config of WebdriverIO

#### Describe the bug

The following configuration was working with v4:

```
capabilities: [{
  maxInstances: 1,
  browserName: 'phantomjs',
  // Without the path, phantomJS is not found on Windows
  'phantomjs.binary.path': path.join(__dirname, './node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs.exe')
}],
```

With v5, this configuration triggers:

```
[0-1] 2018-12-28T15:38:30.968Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [phantomjs.binary.path]
[0-1] 2018-12-28T15:38:30.973Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [phantomjs.binary.path]
[0-1] 2018-12-28T15:38:30.977Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [phantomjs.binary.path]
[0-1] 2018-12-28T15:38:30.981Z ERROR webdriver: Request failed due to Error: Illegal key values seen in w3c capabilities: [phantomjs.binary.path]
    at Request._callback (.\node_modules\webdriver\src\request.js:86:27)
    at Request.self.callback (.\node_modules\request\request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (.\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (.\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
[0-1] 2018-12-28T15:38:30.986Z ERROR wdio-runner: Error: Illegal key values seen in w3c capabilities: [phantomjs.binary.path]
    at Request._callback (.\node_modules\webdriver\src\request.js:86:27)
    at Request.self.callback (.\node_modules\request\request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (.\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (.\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
```

I have therefore tried:

```
capabilities: [{
  maxInstances: 1,
  browserName: 'phantomjs'
}],
```

which triggers:

```
Error: Unable to create session from {
  "desiredCapabilities": {
    "browserName": "phantomjs"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "phantomjs"
      }
    ]
  }
}
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'DESK', ip: '192.68.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
    at Request._callback (.\node_modules\webdriver\src\request.js:86:27)
    at Request.self.callback (.\node_modules\request\request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (.\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (.\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
```

#### Expected behaviour

Any capabilities configuration that works.

Note this might be related to #3196.

**Comment by christian-bromann** [comment]
It is actually the same issue as #3196 .. closing. This will be fixed with `v5.1.0`

**Comment by jlchereau** [comment]
Thx

**Comment by jlchereau** [comment]
Please note v5.1.0 has not fixed this issue. Logs are exactly the same as above with v5.0.3.

**Comment by christian-bromann** [comment]
It seems that you haven’t downloaded phantom js .. please download it and make it accessible in $PATH

**Comment by jlchereau** [comment]
It is downloaded and available in PATH. It is working with webdriverio v4 in the same environment. I am migrating an existing project from v4 to v5 where all features and all drivers work in v4.

**Comment by christian-bromann** [comment]
@jlchereau can you provide phantomjs logs?
