### ISSUE TITLE
Support for direct use of IE Webdriver with v4x

### ISSUE THREAD

**Issue by estk** [webdriverio/webdriverio#3293]
## Summary

IE immediately exits when a webdriver execute command is sent from wdio v4x. The problem is that the IE driver has a bug where the error is put into the Allow header [see the issue here](https://github.com/SeleniumHQ/selenium/issues/6828). As in [this pr](https://github.com/webdriverio/webdriverio/pull/2846) I would like to work around the issue by acknowledging the error and  trying to fall back to the old protocol. I'm opening this as an issue because I do not see an acceptable branch to open a pr for. Perhaps a 4x branch is appropriate for backported fixes?

### My fix

My fix is here: https://github.com/estk/webdriverio/tree/direct_ie_unknown_command
I have branched off of the v4.14.1 tag and would hope that a merge would result in v4.14.2.

## Steps to Reproduce
```
var options = {
    debug: true,
    host: '0.0.0.0',
    desiredCapabilities: {
        browserName: 'internet explorer',
    },
};
var client = webdriverio.remote(options);
client.init()
    .saveScreenshot('./screenshot.png')
    .execute("return navigator.userAgent")
    .then(function(agent) {
        console.log("Agent " + JSON.stringify(agent));
    })
    .catch(function (e) {
      console.log('Local catch called', e);
    })
    .end();
```

## Expected behavior
I would expect that webdriver.io should retry with the old protocol as in the issue linked above.

## Log of client
I added a bit of logging in the RequestHandler and when I run the above code I get:

```
request was error res: {"statusCode":405,"headers":{"allow":"Command not found: POST /session/6de2a1e7-8694-4c7b-962c-7e6b2258061d/execute","content-length":"0","content-type":"application/json","date":"Wed, 09 Jan 2019 23:13:35 GMT"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"13.92.126.30:4444","port":"4444","hostname":"13.92.126.30","hash":null,"search":null,"query":null,"pathname":"/wd/hub/session/6de2a1e7-8694-4c7b-962c-7e6b2258061d/execute","path":"/wd/hub/session/6de2a1e7-8694-4c7b-962c-7e6b2258061d/execute","href":"http://13.92.126.30:4444/wd/hub/session/6de2a1e7-8694-4c7b-962c-7e6b2258061d/execute"},"method":"POST","headers":{"Connection":"keep-alive","Accept":"application/json","User-Agent":"webdriverio/webdriverio/4.14.1","Content-Type":"application/json; charset=UTF-8","Content-Length":49}}}
request was error body: undefined
Execute Fail { Error: Couldn't connect to selenium server (ECONNREFUSED:-1)
    at new RuntimeError (/Users/evan/git/selenoid-test/test-script/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/Users/evan/git/selenoid-test/test-script/node_modules/webdriverio/build/lib/utils/RequestHandler.js:350:39)
    at Request.self.callback (/Users/evan/git/selenoid-test/test-script/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/evan/git/selenoid-test/test-script/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/evan/git/selenoid-test/test-script/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
  details: undefined,
  message: "Couldn't connect to selenium server (ECONNREFUSED:-1)",
  type: 'RuntimeError' }
Local catch called { Error: Couldn't connect to selenium server (ECONNREFUSED:-1)
    at screenshot() - saveScreenshot.js:52:17
    at title() - getTitle.js:31:28
    at end() - main.js:48:6
  details: undefined,
  message: "Couldn't connect to selenium server (ECONNREFUSED:-1)",
  type: 'RuntimeError' }
```

## Log of IE Driver
```
D 2019-01-10 00:36:12:415 c:\projects\webdriver\cpp\webdriver-server\server.cc(416) Response: { "value" : { "error" : "unknown method", "message" : "Command not found: GET /favicon.ico" }
T 2019-01-10 00:36:12:415 c:\projects\webdriver\cpp\webdriver-server\server.cc(469) Entering Server::SendResponseToClient
T 2019-01-10 00:36:12:415 c:\projects\webdriver\cpp\webdriver-server\response.cc(30) Entering Response::Deserialize
T 2019-01-10 00:36:12:415 c:\projects\webdriver\cpp\webdriver-server\server.cc(604) Entering Server::SendHttpMethodNotAllowed
```

**Comment by christian-bromann** [comment]
@estk please make a PR to the v4 repo.

**Comment by zol** [comment]
@ChrisOelmueller I'm also looking at this. Could you please point me to the v4 repo?

**Comment by shilman** [comment]
@zol It's here: https://github.com/webdriverio-boneyard/v4

See https://github.com/webdriverio/webdriverio/issues/3056 for details

**Comment by zol** [comment]
I've opened https://github.com/webdriverio-boneyard/v4/pull/10 in the boneyard. This issue can now be closed.

**Comment by christian-bromann** [comment]
PR was merged.
