### ISSUE TITLE
@wdio/firefox-profile-service 5.2.2 throwing errors

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#3297]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.2.8
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** `8.12.0`
 - **NPM version:** `6.4.1`
 - **Browser name and version:** Firefox
 - **Platform name and version:** OSX
 - **Additional wdio packages used (if applicable):** `"@wdio/firefox-profile-service": "^5.2.2"`

**Config of WebdriverIO**
```js
exports.config = {
  // ====================
  // Runner Configuration
  // ====================
  runner: 'local',

  // ===================
  // Test Configurations
  // ===================
  sync: true,
  logLevel: 'silent',
  coloredLogs: true,
  deprecationWarnings: true,
  screenshotPath: './.tmp/errorShots/',
  baseUrl: 'https://the-internet.herokuapp.com/',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,

  // ==============
  // Test Framework
  // ==============
  framework: 'jasmine',
  reporters: [ 'spec' ],
  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  },

  // =======
  // Firefox
  // =======
  services: [ 'firefox-profile' ],
  // For the options see
  // http://kb.mozillazine.org/Firefox_:_FAQs_:_About:config_Entries
  firefoxProfile: {
    'browser.download.dir': '.tmp/chromeDownloadFolder',
    'browser.download.folderList': 2,
    // Check the allowed MIME types here
    // https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
    'browser.helperApps.neverAsk.saveToDisk': 'application/octet-stream',
  },
  capabilities: [ { browserName: 'firefox', }, ],

  // =====
  // Hooks
  // =====
  beforeSession: (config, capabilities, specs) => {
    require('babel-register');
  },
};
```

**Describe the bug**
Tests fail during running because the FF-profile is not set, see the logs for the error

**To Reproduce**
Use the config and start a simple test

**Expected behavior**

**Log**
```shell
Stderr:
2019-01-10T13:27:50.947Z ERROR wdio-cli:utils: A service failed in the 'onPrepare' hook
TypeError: this._setPreferences is not a function
    at Object.onPrepare (/Users/wimselles/Sauce/Git/webdriverio-down-upload/node_modules/@wdio/firefox-profile-service/build/launcher.js:27:10)
    at Promise.all.launcher.map.service (/Users/wimselles/Sauce/Git/webdriverio-down-upload/node_modules/@wdio/cli/build/utils.js:87:33)
    at Array.map (<anonymous>)
    at runServiceHook (/Users/wimselles/Sauce/Git/webdriverio-down-upload/node_modules/@wdio/cli/build/utils.js:85:39)
    at Launcher.run (/Users/wimselles/Sauce/Git/webdriverio-down-upload/node_modules/@wdio/cli/build/launcher.js:75:37)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Continue...
```

**Additional context**
When I disable calling `this._setPreferences` it will fail on `this._buildExtension`. It looks like something is wrong in calling the class itself. I don't got the skills to debug it more, sorry

**Comment by abjerstedt** [comment]
I cannot reproduce the error outlined above in 5.7.0; however, this plugin is COMPLETELY broke for modern selenium-standalone users.

**Comment by abjerstedt** [comment]
This plugin is also broken for users of firefox <= 55.
