### ISSUE TITLE
upgrade to webdriverio  to version 5.2.8 didn't work with Appium service

### ISSUE THREAD

**Issue by LayMuiToh** [webdriverio/webdriverio#3304]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** v 5.2.8
 - **Mode:** WDIO Testrunner]
 - **If WDIO Testrunner, running sync
 - **Node.js version:**9.1.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Nil
 - **Platform name and version:** iOS 12.1
 - **Additional wdio packages used (if applicable):**
**Config of WebdriverIO**
An example of how you configured WebdriverIO config
"@wdio/cli": "^5.2.8",
    "@wdio/local-runner": "^5.2.8",
    "@wdio/mocha-framework": "^5.2.8",
    "@wdio/sync": "^5.2.8",
*Describe the bug**
Test could not run after upgrade from v.4 to v.5.2.8
**To Reproduce**
node_modules/.bin/wdio wdio.conf.js --spec ./test/spec/app.ts.carousel.questions.spec.js

Include code or an example repository that can easily be set up]
wdio.config.js:
```exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
    // on a remote machine).
    runner: 'local',
    
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called. Notice that, if you are calling `wdio` from an
    // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
    // directory is where your package.json resides, so `wdio` will be called from there.
    //
    specs: [
        './test/specs/**/*.js'
    ],
     // define specific suites
     suites: {
        noattr: [
            './test/spec/app.ts.noattr.text.spec.js',
            './test/spec/app.ts.noattr.voice.spec.js',
            './test/spec/app.ts.carousel.questions.spec.js',
            './test/spec.app.ts.topics.spec.js'
        ],

    },
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 1,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        browserName: '',
        appiumVersion: '1.9.1',
        platformVersion: '12.1',
        platformName: 'iOS',
        deviceName: 'Lay muis iPhone',
        udid: 'a12510a8c8ec79876d8e10f38da17fb97dc720c3',
        app: '/Users/tohlaymui/Desktop/performance_analyst_test/performance_analyst-dev.ipa',
        bundleId: 'ai.telepathy.performanceanalyst-dev',
        automationName: 'XCUITests',
        noReset: false,
        usePrebuiltWDA: true,
        autoLaunch: true,
        newCommandTimeout: 7000,
        printPageSourceOnFindFailure: true
                        
    }],        
    
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error
    sync: true,
    //
    // Level of logging verbosity: silent | verbose | command | data | result | error
    logLevel: 'error',
    outputDir: './logs',
    //
    // Warns when a deprecated command is used
    deprecationWarnings: true,
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    //baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    // services: [],//
    services: ['appium'],

    appium: {
        args: {
            address: '127.0.0.1',
            commandTimeout: '11000',
            sessionOverride: true,
            debugLogSpacing: true,
            platformVersion: '12.1',
            platformName: 'iOS',
            showIosLog: true,
            deviceName: 'iPhone 6s',
            nativeInstrumentsLib: true,
            app: '/Users/tohlaymui/Desktop/performance_analyst_test/performance_analyst-dev.ipa',
        },
    },

    
    // Default port for Appium
    port: 4723,
    maxInstances: 1,

    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter.html
    // reporters: ['dot'],
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000,
        compilers: ['js:babel-register'],
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // beforeSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    before: function (capabilities, specs) {
        var chai = require('chai');
        global.expect = chai.expect;
        chai.Should();
    },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    // beforeTest: function (test) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function () {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function () {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    // afterTest: function (test) {
    // },
    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // }
}
```
**Expected behavior**
test should run as in v.4.14.1

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**
```Worker Error:
Error: An unknown server-side error occurred while processing the command. Original error: No logs of type 'performance' found.
    at Request._callback (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/webdriver/build/request.js:113:21)
    at Request.self.callback (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/request/request.js:186:22)
    at emitTwo (events.js:135:13)
    at Request.emit (events.js:224:7)
    at Request.<anonymous> (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/request/request.js:1163:10)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at IncomingMessage.<anonymous> (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:322:30)
    at emitNone (events.js:120:20)

Test Suites:	 0 passed, 1 failed, 1 total (100% completed)
Time:		 🕑  103.36s
```
> Please use the correct markdown

**Comment by christian-bromann** [comment]
> No logs of type 'performance' found

See this error message. You are trying to get some sort of performance logs that are not supported by your appium backend. I am not sure if this is an actual bug in WebdriverIO since you haven't posted a minimal reproducible example.
