### ISSUE TITLE
WebdriverIO v.5 work with a teamcity report? TypeError: ReporterClass is not a constructor

### ISSUE THREAD

**Issue by ViaMay** [webdriverio/webdriverio#3305]
**Describe your question with as much detail as possible**
WebdriverIO v.5 work with a teamcity report?

**If it's about a specific piece of code, try and include some of it to support your question.**
wdio.conf.js:
reporters: ['teamcity'],
![image](https://user-images.githubusercontent.com/10914859/51020036-18b4db80-159f-11e9-9e98-d47f22050e81.png)

**Environment (please complete the following information):**
 - **WebdriverIO version:** "webdriverio": "^5.2.5"
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:  v8.11.1
 - **NPM version:** v6.5.0
 - **Browser name and version:** 71.0.3578.98 (64-bit)
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]
![image](https://user-images.githubusercontent.com/10914859/51020015-0044c100-159f-11e9-92c7-92d0999b5ebd.png)

**Additional context**
try run, then we have a arror:
[0-0] 2019-01-11T07:46:43.759Z ERROR wdio-local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor
    at BaseReporter.initReporter (C:\FirstProject\node_modules\@wdio\runner\build\reporter.js:193:14)
    at Array.map (<anonymous>)
    at Array.map (<anonymous>)
    at new BaseReporter (C:\FirstProject\node_modules\@wdio\runner\build\reporter.js:34:39)
    at Runner.run (C:\FirstProject\node_modules\@wdio\runner\build\index.js:76:21)
    at process.on.m (C:\FirstProject\node_modules\@wdio\local-runner\build\run.js:37:20)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
![image](https://user-images.githubusercontent.com/10914859/51020092-41d56c00-159f-11e9-8d01-cf9a30c95d40.png)

**Comment by christian-bromann** [comment]
see https://github.com/sullenor/wdio-teamcity-reporter/issues/12
