### ISSUE TITLE
Using WDIO standalone service with geckodriver.

### ISSUE THREAD

**Issue by gomkat** [webdriverio/webdriverio#3307]
**Describe your question with as much detail as possible**
Hi, I am currently using Webdriver.io + cucumber for one of my projects. I use the library `wdio-selenium-standalone-service` to start selenium service automatically but I have encountered issues when running tests against firefox version > 62. I read the documentation and I tried to add the path to geckodriver by adding the parameter `path` in the config file to the root folder where the driver is (my config file is inside a subfolder in the project root); the thing is when I run the tests I get the error `connection refused` and the browser never opens.

Is there another thing I need to do? Am I doing something wrong?

**Environment (please complete the following information):**
 - **WebdriverIO version:** v4.13.2
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version: v8.12.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Firefox 64.0.2
 - **Platform name and version:** MacOS Mojave 10.14.2
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service

**Additional context**
Without the geckodriver the standalone service initiates and the browser opens but no tests actions occur.

**Comment by abjerstedt** [comment]
@gomkat I will need additional context in order to help you with this. Please provide your package.json, as well as well as let me know exactly what is in your services array.

Please note: If you execute both the standalone geckodriver at the same time as selenium-standalone service you WILL have connection issues. These services are mutually exclusive and should not be ran at the same time.

**Comment by christian-bromann** [comment]
Closing due to inactivity

**Comment by AdeelZahir** [comment]
@gomkat could you solve this issue?

**Comment by AdeelZahir** [comment]
@christian-bromann I get the following error whenever I set `maxInstance:` greater than 2. The tests works fine for chrome browsers. But fails on firefox.

```
ERROR: connection refused
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: '03d6bba7311d', ip: '192.168.64.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1043-aws', java.version: '11.0.4'
Driver info: driver.version: unknown
remote stacktrace: 
firefox
    at new RuntimeError (/home/circleci/project/frontend/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/home/circleci/project/frontend/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)
    at Request.self.callback (/home/circleci/project/frontend/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/circleci/project/frontend/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/circleci/project/frontend/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```


```
maxInstances: 10,
capabilities: [
        {
            browserName: 'chrome',
        },
        {
            browserName: 'firefox',
        },
    ],
```

```
"wdio-mocha-framework": "^0.6.4",
    "wdio-selenium-standalone-service": "0.0.11",
    "wdio-spec-reporter": "^0.1.5",
    "wdio-visual-regression-service": "^0.9.0",
    "web-app-manifest-loader": "^0.1.1",
    "webdriverio": "4.14.1",
```

**Comment by christian-bromann** [comment]
Please update to v5 as we don't support v4 anymore.

**Comment by AdeelZahir** [comment]
Will `"wdio-visual-regression-service": "^0.9.0",` work with v5?

**Comment by christian-bromann** [comment]
No, please see https://webdriver.io/blog/2019/05/18/visual-regression-for-v5.html
