### ISSUE TITLE
this.takeElementScreenshot is not a function

### ISSUE THREAD

**Issue by tfiwm** [webdriverio/webdriverio#3370]
The saveScreenshot functionality of an element seems to be broken.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.5
 - **Mode:** CodeceptJS
 - **Node.js version:** 10.8.0
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** Puppeteer latest
 - **Platform name and version:** Mac OS Mojave

**Config of WebdriverIO**
standard config

**Describe the bug**
The saveScreenshot function based on an element is not working because of an missing function.

**To Reproduce**
const element = browser.$('some css selector of an element');
element.saveScreenshot('./somepath.png');

**Expected behavior**
Screenshot of the given selector is saved and returned as Base64

**Log**
```bash
this.takeElementScreenshot is not a function
 TypeError: this.takeElementScreenshot is not a function
      at Element.saveScreenshot (node_modules/webdriverio/build/commands/element/saveScreenshot.js:52:35)
      at Element.<anonymous> (node_modules/webdriverio/build/middlewares.js:55:41)
      at VisualKnight.<anonymous> (node_modules/@visual-knight/codeceptjs/lib/codeceptjs.js:175:46)
      at Generator.next (<anonymous>)
      at node_modules/@visual-knight/codeceptjs/lib/codeceptjs.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@visual-knight/codeceptjs/lib/codeceptjs.js:3:12)
      at VisualKnight.makeScreenshotForWebdriverIO (node_modules/@visual-knight/codeceptjs/lib/codeceptjs.js:172:16)
      at VisualKnight.<anonymous> (node_modules/@visual-knight/codeceptjs/lib/codeceptjs.js:162:47)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/@visual-knight/codeceptjs/lib/codeceptjs.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
**Additional context**
Using with CodeceptJS and Visual Knight

Small search inside the build npm package doesn't find any function with this name

**Comment by christian-bromann** [comment]
This function is only available if the driver supports the command. It is not up to WebdriverIO. I assume you use Chrome which has no full W3C WebDriver support yet.
