### ISSUE TITLE
Appium error when using WebdriverIO with Browserstack

### ISSUE THREAD

**Issue by jpmontez** [webdriverio/webdriverio#3396]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find us on Gitter](https://gitter.im/webdriverio/webdriverio)

I'm getting an error message when trying to run WebdriverIO with BrowserStack. I'm using the bare-minimum configuration for iOS devices, but I'm receiving the following:
```
ERROR webdriver: Request failed due to Error: Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
```

It seems that WebdriverIO is attempting to unnecessarily retrieve logs:
```
[0-0] 2019-01-23T16:48:50.299Z DEBUG wdio-runner: Fetching logs for syslog, crashlog, performance, server, safariConsole, safariNetwork
[0-0] 2019-01-23T16:48:50.300Z INFO webdriver: COMMAND getLogs("syslog")
[0-0] 2019-01-23T16:48:50.301Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.301Z INFO webdriver: DATA { type: 'syslog' }
```

This behavior was introduced in WebdriverIO version 5. I was unable to reproduce it with the same capabilities in version 4.

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

https://github.com/webdriverio/webdriverio/blob/369f83ba17b4f8091c6e44d74922351a311db86e/packages/wdio-runner/src/index.js#L191-L231

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.3.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v11.7.0
 - **NPM version:** 6.5.0
 - **Browser name and version:** iPhone 12.1
 - **Platform name and version:** iPhone XS
 - **Additional wdio packages used (if applicable):** N/A

**Additional context**
The tests are passing upstream in BrowserStack, it's just this exception that's being returned that's causing the runner to fail.

**Comment by christian-bromann** [comment]
@jpmontez can you provide more logs and stacktraces please?

**Comment by jpmontez** [comment]
```
2019-01-23T16:48:31.538Z INFO wdio-cli:Launcher: Run onPrepare hook
2019-01-23T16:48:31.540Z INFO wdio-local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2019-01-23T16:48:31.652Z DEBUG wdio-config: @wdio/sync found, running tests synchronous
[0-0] 2019-01-23T16:48:31.783Z INFO wdio-local-runner: Run worker command: run
[0-0] 2019-01-23T16:48:31.903Z DEBUG wdio-local-runner:utils: init remote session
[0-0] 2019-01-23T16:48:31.936Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session
[0-0] 2019-01-23T16:48:31.937Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { os_version: '12.1',
        device: 'iPhone XS',
        real_mobile: 'true',
        'browserstack.local': 'false' },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { os_version: '12.1',
     device: 'iPhone XS',
     real_mobile: 'true',
     'browserstack.local': 'false' } }
[0-0] 2019-01-23T16:48:41.043Z INFO webdriver: COMMAND navigateTo("https://www.<redacted>.com/")
[0-0] 2019-01-23T16:48:41.044Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/url
[0-0] 2019-01-23T16:48:41.044Z INFO webdriver: DATA { url: 'https://www.<redacted>.com/' }
[0-0] 2019-01-23T16:48:42.975Z INFO webdriver: COMMAND getTitle()
[0-0] 2019-01-23T16:48:42.976Z INFO webdriver: [GET] http://hub.browserstack.com:80/wd/hub/session/<redacted>/title
[0-0] 2019-01-23T16:48:46.434Z INFO webdriver: RESULT <redacted>
[0-0] 2019-01-23T16:48:46.439Z INFO webdriver: COMMAND navigateTo("https://www.<redacted>.com/")
[0-0] 2019-01-23T16:48:46.439Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/url
[0-0] 2019-01-23T16:48:46.439Z INFO webdriver: DATA { url: 'https://www.<redacted>.com/' }
[0-0] 2019-01-23T16:48:48.320Z INFO webdriver: COMMAND findElement("css selector", "#drift-widget-container")
[0-0] 2019-01-23T16:48:48.320Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/element
[0-0] 2019-01-23T16:48:48.321Z INFO webdriver: DATA { using: 'css selector', value: '#drift-widget-container' }
[0-0] 2019-01-23T16:48:49.176Z INFO webdriver: RESULT { ELEMENT: '5000' }
[0-0] 2019-01-23T16:48:49.218Z INFO webdriver: COMMAND isElementDisplayed("5000")
[0-0] 2019-01-23T16:48:49.219Z INFO webdriver: [GET] http://hub.browserstack.com:80/wd/hub/session/<redacted>/element/5000/displayed
[0-0] 2019-01-23T16:48:49.672Z INFO webdriver: RESULT true
[0-0] 2019-01-23T16:48:49.673Z INFO webdriver: COMMAND isElementDisplayed("5000")
[0-0] 2019-01-23T16:48:49.673Z INFO webdriver: [GET] http://hub.browserstack.com:80/wd/hub/session/<redacted>/element/5000/displayed
[0-0] 2019-01-23T16:48:49.985Z INFO webdriver: RESULT true
[0-0] 2019-01-23T16:48:49.988Z INFO webdriver: COMMAND getLogTypes()
[0-0] 2019-01-23T16:48:49.988Z INFO webdriver: [GET] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log/types
[0-0] 2019-01-23T16:48:50.299Z INFO webdriver: RESULT [ 'syslog',
  'crashlog',
  'performance',
  'server',
  'safariConsole',
  'safariNetwork' ]
[0-0] 2019-01-23T16:48:50.299Z DEBUG wdio-runner: Fetching logs for syslog, crashlog, performance, server, safariConsole, safariNetwork
[0-0] 2019-01-23T16:48:50.300Z INFO webdriver: COMMAND getLogs("syslog")
[0-0] 2019-01-23T16:48:50.301Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.301Z INFO webdriver: DATA { type: 'syslog' }
[0-0] 2019-01-23T16:48:50.302Z INFO webdriver: COMMAND getLogs("crashlog")
[0-0] 2019-01-23T16:48:50.302Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.302Z INFO webdriver: DATA { type: 'crashlog' }
[0-0] 2019-01-23T16:48:50.303Z INFO webdriver: COMMAND getLogs("performance")
[0-0] 2019-01-23T16:48:50.303Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.303Z INFO webdriver: DATA { type: 'performance' }
[0-0] 2019-01-23T16:48:50.304Z INFO webdriver: COMMAND getLogs("server")
[0-0] 2019-01-23T16:48:50.304Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.304Z INFO webdriver: DATA { type: 'server' }
[0-0] 2019-01-23T16:48:50.304Z INFO webdriver: COMMAND getLogs("safariConsole")
[0-0] 2019-01-23T16:48:50.305Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.305Z INFO webdriver: DATA { type: 'safariConsole' }
[0-0] 2019-01-23T16:48:50.305Z INFO webdriver: COMMAND getLogs("safariNetwork")
[0-0] 2019-01-23T16:48:50.305Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.305Z INFO webdriver: DATA { type: 'safariNetwork' }
[0-0] 2019-01-23T16:48:50.576Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.580Z INFO webdriver: Retrying 1/3
[0-0] 2019-01-23T16:48:50.581Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.581Z INFO webdriver: DATA { type: 'syslog' }
[0-0] 2019-01-23T16:48:50.617Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.617Z INFO webdriver: Retrying 1/3
[0-0] 2019-01-23T16:48:50.617Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.617Z INFO webdriver: DATA { type: 'server' }
[0-0] 2019-01-23T16:48:50.620Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.621Z INFO webdriver: Retrying 1/3
[0-0] 2019-01-23T16:48:50.621Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.621Z INFO webdriver: DATA { type: 'safariNetwork' }
[0-0] 2019-01-23T16:48:50.667Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.670Z INFO webdriver: Retrying 1/3
[0-0] 2019-01-23T16:48:50.670Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.670Z INFO webdriver: DATA { type: 'crashlog' }
[0-0] 2019-01-23T16:48:50.671Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.672Z INFO webdriver: Retrying 1/3
[0-0] 2019-01-23T16:48:50.672Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.672Z INFO webdriver: DATA { type: 'safariConsole' }
[0-0] 2019-01-23T16:48:50.680Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.682Z INFO webdriver: Retrying 1/3
[0-0] 2019-01-23T16:48:50.682Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.682Z INFO webdriver: DATA { type: 'performance' }
[0-0] 2019-01-23T16:48:50.926Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.927Z INFO webdriver: Retrying 2/3
[0-0] 2019-01-23T16:48:50.927Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.927Z INFO webdriver: DATA { type: 'syslog' }
[0-0] 2019-01-23T16:48:50.943Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.944Z INFO webdriver: Retrying 2/3
[0-0] 2019-01-23T16:48:50.944Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.944Z INFO webdriver: DATA { type: 'server' }
[0-0] 2019-01-23T16:48:50.957Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.960Z INFO webdriver: Retrying 2/3
[0-0] 2019-01-23T16:48:50.960Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.960Z INFO webdriver: DATA { type: 'performance' }
[0-0] 2019-01-23T16:48:50.977Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.978Z INFO webdriver: Retrying 2/3
[0-0] 2019-01-23T16:48:50.979Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.979Z INFO webdriver: DATA { type: 'safariConsole' }
[0-0] 2019-01-23T16:48:50.988Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.989Z INFO webdriver: Retrying 2/3
[0-0] 2019-01-23T16:48:50.989Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.989Z INFO webdriver: DATA { type: 'safariNetwork' }
[0-0] 2019-01-23T16:48:50.997Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:50.997Z INFO webdriver: Retrying 2/3
[0-0] 2019-01-23T16:48:50.997Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:50.997Z INFO webdriver: DATA { type: 'crashlog' }
[0-0] 2019-01-23T16:48:51.345Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.346Z INFO webdriver: Retrying 3/3
[0-0] 2019-01-23T16:48:51.346Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:51.346Z INFO webdriver: DATA { type: 'server' }
[0-0] 2019-01-23T16:48:51.348Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.348Z INFO webdriver: Retrying 3/3
[0-0] 2019-01-23T16:48:51.348Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:51.348Z INFO webdriver: DATA { type: 'safariConsole' }
[0-0] 2019-01-23T16:48:51.359Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.359Z INFO webdriver: Retrying 3/3
[0-0] 2019-01-23T16:48:51.359Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:51.359Z INFO webdriver: DATA { type: 'crashlog' }
[0-0] 2019-01-23T16:48:51.367Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.368Z INFO webdriver: Retrying 3/3
[0-0] 2019-01-23T16:48:51.368Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:51.368Z INFO webdriver: DATA { type: 'syslog' }
[0-0] 2019-01-23T16:48:51.449Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.450Z INFO webdriver: Retrying 3/3
[0-0] 2019-01-23T16:48:51.450Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:51.451Z INFO webdriver: DATA { type: 'performance' }
[0-0] 2019-01-23T16:48:51.453Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.454Z INFO webdriver: Retrying 3/3
[0-0] 2019-01-23T16:48:51.454Z INFO webdriver: [POST] http://hub.browserstack.com:80/wd/hub/session/<redacted>/log
[0-0] 2019-01-23T16:48:51.454Z INFO webdriver: DATA { type: 'safariNetwork' }
[0-0] 2019-01-23T16:48:51.656Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.659Z INFO webdriver: COMMAND deleteSession()
[0-0] 2019-01-23T16:48:51.659Z INFO webdriver: [DELETE] http://hub.browserstack.com:80/wd/hub/session/<redacted>
[0-0] 2019-01-23T16:48:51.660Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.713Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.797Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.845Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:48:51.849Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-01-23T16:49:02.990Z INFO webdriver: RESULT
2019-01-23T16:49:03.128Z DEBUG wdio-local-runner: Runner 0-0 finished with exit code 1

Stderr:
[0-0] 2019-01-23T16:48:50.580Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.617Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.621Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.669Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.672Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.681Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.927Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.944Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.959Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.978Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.989Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:50.997Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:51.346Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:51.348Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:51.359Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:51.367Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:51.450Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:51.454Z WARN webdriver: Request failed due to Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
[0-0] 2019-01-23T16:48:51.657Z ERROR webdriver: Request failed due to Error: Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
    at getErrorFromResponseBody (<redacted>/webdriverio/node_modules/webdriver/build/utils.js:340:10)
    at Request._callback (<redacted>/webdriverio/node_modules/webdriver/build/request.js:113:64)
    at Request.self.callback (<redacted>/webdriverio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at Request.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at IncomingMessage.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
[0-0] 2019-01-23T16:48:51.658Z ERROR wdio-runner: Error: Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
    at getErrorFromResponseBody (<redacted>/webdriverio/node_modules/webdriver/build/utils.js:340:10)
    at Request._callback (<redacted>/webdriverio/node_modules/webdriver/build/request.js:113:64)
    at Request.self.callback (<redacted>/webdriverio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at Request.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at IncomingMessage.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
[0-0] 2019-01-23T16:48:51.662Z ERROR webdriver: Request failed due to Error: Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
    at getErrorFromResponseBody (<redacted>/webdriverio/node_modules/webdriver/build/utils.js:340:10)
    at Request._callback (<redacted>/webdriverio/node_modules/webdriver/build/request.js:113:64)
    at Request.self.callback (<redacted>/webdriverio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at Request.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at IncomingMessage.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
[0-0] 2019-01-23T16:48:51.714Z ERROR webdriver: Request failed due to Error: Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
    at getErrorFromResponseBody (<redacted>/webdriverio/node_modules/webdriver/build/utils.js:340:10)
    at Request._callback (<redacted>/webdriverio/node_modules/webdriver/build/request.js:113:64)
    at Request.self.callback (<redacted>/webdriverio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at Request.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at IncomingMessage.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
[0-0] 2019-01-23T16:48:51.798Z ERROR webdriver: Request failed due to Error: Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
    at getErrorFromResponseBody (<redacted>/webdriverio/node_modules/webdriver/build/utils.js:340:10)
    at Request._callback (<redacted>/webdriverio/node_modules/webdriver/build/request.js:113:64)
    at Request.self.callback (<redacted>/webdriverio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at Request.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at IncomingMessage.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
[0-0] 2019-01-23T16:48:51.846Z ERROR webdriver: Request failed due to Error: Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
    at getErrorFromResponseBody (<redacted>/webdriverio/node_modules/webdriver/build/utils.js:340:10)
    at Request._callback (<redacted>/webdriverio/node_modules/webdriver/build/request.js:113:64)
    at Request.self.callback (<redacted>/webdriverio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at Request.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at IncomingMessage.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
[0-0] 2019-01-23T16:48:51.850Z ERROR webdriver: Request failed due to Error: Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
    at getErrorFromResponseBody (<redacted>/webdriverio/node_modules/webdriver/build/utils.js:340:10)
    at Request._callback (<redacted>/webdriverio/node_modules/webdriver/build/request.js:113:64)
    at Request.self.callback (<redacted>/webdriverio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at Request.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at IncomingMessage.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)

Worker Error:
Error: Appium error: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'apply' of undefined
    at getErrorFromResponseBody (<redacted>/webdriverio/node_modules/webdriver/build/utils.js:340:10)
    at Request._callback (<redacted>/webdriverio/node_modules/webdriver/build/request.js:113:64)
    at Request.self.callback (<redacted>/webdriverio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at Request.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:439:20)
    at IncomingMessage.<anonymous> (<redacted>/webdriverio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)

Test Suites:     0 passed, 1 failed, 1 total (100% completed)
Time:            🕙  31.72s

npm ERR! Test failed.  See above for more details.
```
@christian-bromann

**Comment by jpmontez** [comment]
That's everything that the test runner outputted, minus the redacted information, of course.
