### ISSUE TITLE
Error appears undefined 'then' in Timer.js file

### ISSUE THREAD

**Issue by AlekseyAlready** [webdriverio/webdriverio#3448]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync:** [e.g. sync/async]
 - **Node.js version:** [e.g. 11.8.8]
 - **NPM version:** [e.g. 6.7.01]
 - **Browser name and version:** [e.g. Chrome 70]
 - **Platform name and version:** [e.g. Mint 4.15.0-20-generic]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**

**To Reproduce**

Launch test

if we use this code

if (_config.hasWdioSyncSupport && !fn.name.includes('async')) {
      this._fn = () => (0, _config.runFnInFiberContext)(fn)();
    }
we'll get an error, and after comment 

if (_config.hasWdioSyncSupport && !fn.name.includes('async')) {
      //this._fn = () => (0, _config.runFnInFiberContext)(fn)();
    }

test will be ok

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

Cannot read property 'then' of undefined
[chrome #0-0] TypeError: Cannot read property 'then' of undefined
[chrome #0-0]     at Timer.tick (/home/alexey/ui-test/node_modules/@wdio/runner/node_modules/webdriverio/build/utils/Timer.js:86:23)
[chrome #0-0]     at Timer.start (/home/alexey/ui-test/node_modules/@wdio/runner/node_modules/webdriverio/build/utils/Timer.js:51:12)
[chrome #0-0]     at new Timer (/home/alexey/ui-test/node_modules/@wdio/runner/node_modules/webdriverio/build/utils/Timer.js:42:10)
[chrome #0-0]     at Element._default (/home/alexey/ui-test/node_modules/@wdio/runner/node_modules/webdriverio/build/commands/browser/waitUntil.js:65:15)
[chrome #0-0]     at Element.runCommand (/home/alexey/ui-test/node_modules/@wdio/sync/build/wrapCommand.js:32:32)
[chrome #0-0]     at processTicksAndRejections (internal/process/next_tick.js:81:5)

**Additional context**

> Please use the correct markdown

**Comment by xlenz** [comment]
can you provide with the way to reproduce it?

**Comment by abjerstedt** [comment]
@AlekseyAlready I'm confused:

You have the version listed at 4.13.2, but reference @wdio/selenium-standalone-service and @wdio/spec-reporter which are v5 plugins. V5 plugins and v4 wdio are mutually exclusive.
