### ISSUE TITLE
Error 500 java.lang.IllegalArgumentException: No enum constant org.openqa.selenium.Platform.macOS 10.12

### ISSUE THREAD

**Issue by krishna596** [webdriverio/webdriverio#3454]
**Describe your question with as much detail as possible**
The issue is coming when i run script in my localhost. if i use sauce service it's working fine.

**If it's about a specific piece of code, try and include some of it to support your question.**
> @PriceView/AutomationTest@1.0.0 bySpec /Users/a1422952/Work/pricing-feat
> wdio --spec ./features/$filePath

[16:26:05]  COMMAND	POST 	 "/wd/hub/session"
[16:26:05]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"chrome","platform":"macOS 10.12","version":"latest","build":"MAC_CHROME","pageLoadStrategy":"normal","acceptSslCerts":true,"_":"7 more keys: [\"acceptInsecureCerts\",\"unexpectedAlertBehaviour\",\"mobileEmulationEnabled\",\"tags\",\"default_content_setting_values\",\"loggingPrefs\",\"requestOrigins\"]"}}
ERROR: <html>
<head>
<title>Error 500 java.lang.IllegalArgumentException: No enum constant org.openqa.selenium.Platform.macOS 10.12</title>
</head>
<body>
<h2>HTTP ERROR: 500</h2><pre>java.lang.IllegalArgumentException: No enum constant org.openqa.selenium.Platform.macOS 10.12</pre>
<p>RequestURI=/wd/hub/session</p>
<p><i><small><a href="http://jetty.mortbay.org">Powered by Jetty://</a></small></i></p>
                                                
</body>
</html>

chrome.latest.macos10_12
    at new RuntimeError (/Users/a1422952/Work/pricing-feat/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
    at Request._callback (/Users/a1422952/Work/pricing-feat/node_modules/webdriverio/build/lib/utils/RequestHandler.js:302:39)
    at Request.self.callback (/Users/a1422952/Work/pricing-feat/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/a1422952/Work/pricing-feat/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/a1422952/Work/pricing-feat/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

Wrote xunit report "WDIO.xunit.chrome.latest.macos10_12.0-0.xml" to [reports/junit-reporter].
View WDIO HTML Report at: ./wdio-report.html
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @PriceView/AutomationTest@1.0.0 bySpec: `wdio --spec ./features/$filePath`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @PriceView/AutomationTest@1.0.0 bySpec script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/a1422952/.npm/_logs/2019-01-29T22_26_05_537Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @PriceView/AutomationTest@1.0.0 itemPrice: `CAPS=MacChrome TAGS=@lv ENVIRONMENT=test filePath=pricing/itemPrice.feature npm run bySpec`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @PriceView/AutomationTest@1.0.0 itemPrice script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

My capabailities: 
// Mac OSX 10.12
	if (browsers.includes('MacChrome')) {
		caps.push({
			browserName: 'chrome',
			platform: 'macOS 10.12',
			version: 'latest',
			build: 'MAC_CHROME',
			locationContextEnabled: true,
			handlesAlerts: true,
			pageLoadStrategy: 'normal',
			acceptSslCerts: true,
			acceptInsecureCerts: true,
			unexpectedAlertBehaviour: 'accept',
			mobileEmulationEnabled: true,
			tags: [
				'@lv'
			],
			default_content_setting_values: { geolocation: 1 }
		});

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.15.0]
 - **NPM version:** [e.g. 6.4.1]
 - **Browser name and version:** [e.g. Chrome 71]
 - **Platform name and version:** [e.g. MAC os  10.13]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Additional context**

**Comment by christian-bromann** [comment]
Please provide all available wdio logs otherwise this is impossible to look into it.

**Comment by caoxu2000** [comment]
@krishna596 try w/o space in your platform something like 'mac10.12'
