### ISSUE TITLE
unable to use applitool services with webdriverio v.4.14.1

### ISSUE THREAD

**Issue by LayMuiToh** [webdriverio/webdriverio#3456]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:**  4.14.1
 - **Mode:** [Standalone mode or WDIO Testrunner]: wdio testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 9.1.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Nil
 - **Platform name and version:** iOS 12.1
 - **Additional wdio packages used (if applicable):** 

**Config of WebdriverIO**
beforeSession: function (config, capabilities, specs) {
       // const { Eyes } = require('@applitools/eyes.webdriverio');
      //  Eyes.setApiKey('3xTFh8pyaJr2TEgwPnOb55f7QeF5iPejd0pmBAppl108c110');

        var Eyes = require("@applitools/eyes.webdriverio").Eyes;
        var eyes = new Eyes();
        eyes.setApiKey("3xTFh8pyaJr2TEgwPnOb55f7QeF5iPejd0pmBAppl108c110");
        
    },

services: ['appium'],

    appium: {
        args: {
            address: '127.0.0.1',
            commandTimeout: '11000',
            sessionOverride: true,
            debugLogSpacing: true,
            platformVersion: '12.1',
            platformName: 'iOS',
            showIosLog: true,
            deviceName: 'iPhone 6s',
            nativeInstrumentsLib: true,
            //app: '/Users/tohlaymui/Desktop/performance_analyst_test/performance_analyst-dev.ipa',
            app: '/Users/tohlaymui/Library/Developer/Xcode/DerivedData/performance_analyst-exzmnafxweexfvdwtpbkbseqplub/Build/Products/Debug-iphonesimulator/performance_analyst.app',
        },
    },

....
...
    services: ['applitools'],
    
    applitools: {
    // options
    // ...
    },

    
    // Default port for Appium
    port: 4723,
    maxInstances: 1,

**Describe the bug**
when running the test, I got the error
node_modules/.bin/wdio wdio.conf.js --spec ./test/spec.app.ts.topics.spec.js

Error in beforeSession: Error: Applitools API key must be set
    at ApplitoolService.beforeSession (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/wdio-applitools-service/lib/applitools-service.js:20:13)
    at /Users/tohlaymui/Desktop/performance_analyst_test/node_modules/webdriverio/build/lib/runner.js:729:28
**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**
in package.json: 
"devDependencies": {
    "@applitools/eyes.webdriverio": "^2.0.0",
    "appium": "^1.10.1",
    "babel-cli": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2015-node": "^6.1.1",
    "babel-preset-react-native": "^4.0.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "eyes.selenium": "^3.6.2",
    "node-wav-player": "^0.1.0",
    "wdio-appium-service": "^0.2.3",
    "wdio-applitools-service": "^0.2.2",
    "wdio-mocha-framework": "^0.6.4",
    "wdio-sync": "^0.7.3",
    "webdriverio": "^4.14.1"
  },

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Can you provide driver logs?

**Comment by LayMuiToh** [comment]
https://ghe.exm-platform.com/gist/laymui-toh/b85479c7326395ebfa4080b11b7127a4

**Comment by LayMuiToh** [comment]
Hi Christian, are you able to access the above link to the driver.log file?

**Comment by christian-bromann** [comment]
> Hi Christian, are you able to access the above link to the driver.log file?

No, I don't have log in data for it. Can you just put it into a secret gist?

**Comment by LayMuiToh** [comment]
https://ghe.exm-platform.com/gist/laymui-toh/3947de4800a645ed9b0cd1c7a9793c4a

**Comment by christian-bromann** [comment]
This is the same link and I said I don't have access to that, please post everything here: https://gist.github.com/

**Comment by LayMuiToh** [comment]
I think it is enterprise level so it's closed to others 
please see this https://gist.github.com/LayMuiToh/dddfdd5ffd97013a5bb42b1032749c11

**Comment by christian-bromann** [comment]
those are just the sys logs I need all other logs too.

**Comment by LayMuiToh** [comment]
On my test window, I got this error message:
what is the API to call?
1) Options test should able to select sales icon and go to the Sales page:
browser.takeSnapshot is not a function
running
TypeError: browser.takeSnapshot is not a function
    at Context.<anonymous> (/Users/tohlaymui/Desktop/performance_analyst_test/test/spec/app.tc.topics.spec.js:18:15)
    at new Promise (<anonymous>)
    at new F (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/core-js/library/modules/_export.js:36:28)

**Comment by LayMuiToh** [comment]
I take from the example usage in this link https://webdriver.io/docs/applitools-service.html#installation
