### ISSUE TITLE
TypeError: client.contexts is not a function

### ISSUE THREAD

**Issue by avshub** [webdriverio/webdriverio#3471]
I am trying to automate a hybrid app with Webview using **Cucumber js, webdriverio, and Appium**.

Below is the code for the step definition in javascript file.

    `var webdriverio = require('webdriverio');
	var config = require('./helpers/desiredCapabilities').options;
	var client = webdriverio.remote(config);
	const {Given, Then, When} = require('cucumber');

	Given('I launch app', function () {
		 
		 setTimeout(function()
		 {
			let contexts = client.contexts();
			client.context(contexts[1]);
			 //client.waitForExist()
			return client.click('android=new UiSelector().resourceId("signupButton")');
			
			 //return client.findElement(By.id("signupButton")).click();
			 //element('id:txtSignupEmail').setValue("shubha");
		 },200000); 
		
	});`

My package.json file looks like below

`{
  "name": "prnodetestand",
  "version": "1.0.0",
  "description": "pr test",
  "main": "index.js",
  "scripts": {
    "cucumber": "cucumber-js ./features -r ./steps"
  },
  "keywords": [
    "cucumber"
  ],
  "author": "shubha",
  "license": "ISC",
  "dependencies": {
    "appium": "^1.10.1",
    "appium-uiautomator2-driver": "^1.28.1",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "mocha": "^5.2.0",
    "selenium-webdriver": "^4.0.0-alpha.1",
    "wd": "^1.11.1",
    "webdriverio": "^5.4.8"
  },
  "devDependencies": {
    "cucumber": "^5.1.0",
    "wdio-appium-service": "^0.2.3",
    "wdio-cucumber-framework": "^2.2.8",
    "wdio-mocha-framework": "^0.6.4"
  }
}`

My Appium version is **1.10.0.**
I am getting an error while using any function on client variable that it is not a function.

`C:\Users\...\PRNodeTestAnd\steps\webdriverio-calcu.js:26
                        let contexts = client.contexts();
                                              ^

**TypeError: client.contexts is not a function**
    at Timeout._onTimeout (C:\Users\...\PRNodeTestAnd\steps\webdriverio-calcu.js:26:26)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prnodetestand@1.0.0 cucumber: `cucumber-js ./features -r ./steps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prnodetestand@1.0.0 cucumber script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2019-01-31T10_59_33_049Z-debug.log`

I am new to automation and have no idea what might be causing the error. 
Please help me with the problem.

**Comment by mgrybyk** [comment]
There ia no contexts method in wdio 5, please see braking changes in changelog. Use getContext(s) instead.

**Comment by christian-bromann** [comment]
> cucumber-js ./features -r ./steps

Well it doesn't seem like you are using webdriverio at all. Please check out the docs there are boilerplate examples you can use that get you started.

**Comment by avshub** [comment]
> > cucumber-js ./features -r ./steps
> 
> Well it doesn't seem like you are using webdriverio at all. Please check out the docs there are boilerplate examples you can use that get you started.

Can you please help me out? I want to use both cucumber js and webdriverio. How can i modify the script?
