### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by just-boris** [webdriverio/webdriverio#3539]
**Environment (please complete the following information):**
 - **WebdriverIO version:** v5.4.17
 - **Mode:** standalone
 - **If WDIO Testrunner, running sync/async:** n/a
 - **Node.js version:** 8.9.4
 - **NPM version:** 6.4.1
 - **Browser name and version:** n/a
 - **Platform name and version:** n/a
 - **Additional wdio packages used (if applicable):** n/a

**Describe the bug**
When a custom command throws an exception it produces `UnhandledPromiseRejectionWarning` to the console:

```
(node:8292) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: for test
(node:8292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

```js
const { remote } = require('webdriverio');

(async () => {
  const browser = await remote({
    logLevel: 'trace',
    capabilities: {
      browserName: 'chrome'
    }
  });

  browser.addCommand('shouldThrow', async () => {
    throw new Error('for test');
  });

  try {
    await browser.shouldThrow();
  } finally {
    await browser.deleteSession();
  }
})().catch(e => console.error(e));

```

**Expected behavior**
This code should not produce any warnings

**Additional context**
According to my research, [this promise](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriver/src/monad.js#L105) stays unhandled when is rejected. Adding a catch block there fixed the warning for my code example.

**Comment by mgrybyk** [comment]
@just-boris can you please provide stacktrace or confirm that you have something like
```
 at Browser.runCommand (/Users/m/sources/ag/e2e/node_modules/@wdio/sync/build/wrapCommand.js:35:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
in log?

**Comment by just-boris** [comment]
My example does not use `@wdio/sync`, but the error looks similar:
```
Error: for test
    at Browser.browser.addCommand (/Users/just-boris/coding/index.js:12:11)
    at Browser.shouldThrow (/Users/just-boris/coding/node_modules/@wdio/config/build/shim.js:65:31)
    at Browser.next [as shouldThrow] (/Users/just-boris/coding/node_modules/webdriver/build/monad.js:120:27)
    at /Users/just-boris/coding/index.js:16:19
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

<details>
<summary>Full console output</summary>

```
2019-02-13T08:27:22.037Z DEBUG wdio-config: @wdio/sync not found, running tests asynchronous
2019-02-13T08:27:22.267Z INFO webdriver: [POST] http://0.0.0.0:4444/wd/hub/session
2019-02-13T08:27:22.267Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' } }
2019-02-13T08:27:25.362Z INFO webdriver: COMMAND shouldThrow()
2019-02-13T08:27:25.364Z INFO webdriver: COMMAND deleteSession()
2019-02-13T08:27:25.365Z INFO webdriver: [DELETE] http://0.0.0.0:4444/wd/hub/session/7693b56cd197fd6af1b209454752e597
(node:14125) UnhandledPromiseRejectionWarning: Error: for test
    at Browser.browser.addCommand (/Users/just-boris/coding/index.js:12:11)
    at Browser.shouldThrow (/Users/just-boris/coding/node_modules/@wdio/config/build/shim.js:65:31)
    at Browser.next [as shouldThrow] (/Users/just-boris/coding/node_modules/webdriver/build/monad.js:120:27)
    at /Users/just-boris/coding/index.js:16:19
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:14125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14125) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
</details>

**Comment by xlenz** [comment]
@just-boris thanks!

**Comment by WhoAteDaCake** [comment]
Is the reason, why `"no such element"` error also causes the crash of the whole problem?

**Comment by just-boris** [comment]
Yes, it might, if you have a custom command that does `this.$` calls.

**Comment by mgrybyk** [comment]
@WhoAteDaCake might be but not likely. You may rise another ticket for you problem or use channel in gitter and ask it if you are not sure
