### ISSUE TITLE
Connection Reset by Peer

### ISSUE THREAD

**Issue by arivas191** [webdriverio/webdriverio#3614]
I am running tests using WebdriverIO and only **sometimes** I get the following error: 
`Error: Promise was rejected with the following reason: java.net.SocketException: Connection reset by peer (connect failed)
      at new WaitUntilTimeoutError (node_modules/webdriverio/build/lib/utils/ErrorHandler.js:149:12)
      at /Users/augusto/hushapp-tests/node_modules/webdriverio/build/lib/commands/waitUntil.js:36:15
      at <anonymous>
`

Yes, I have seen some posts around here talking about this issue too, but none of them seem to come to a definitive solution. I am particularly intrigued by one of the posts saying that this happens when multiple calls are being sent to the selenium server and that it is not capable of handling this. However, like I said, I only get this error every now and then, and I'm always running the same or more calls to the server, so I don't think this makes sense in my case.

For example, this line: 
`await browser.waitForVisible('#tx-sent li', 10000)`
Is one of the places where the test fails and throws the promise rejection provided. According to one of the posts, if there are too many 'li' elements (in this case) the exception will be thrown. However, in my case, the 'li' elements are always increasing in number and this exception doesn't always occur. In other words, if I run this test 10 times, each run will add an 'li' element and only 4 (estimate) out of the 10 will fail. 

Could someone please provide some ideas or solutions as to what can I improve here to get rid of that annoying exception? I am using webdriverio 4.14.0.

**Comment by christian-bromann** [comment]
> Could someone please provide some ideas or solutions as to what can I improve here to get rid of that annoying exception?

Update to v5 where we have request retries that should fix these issues. Also in v5 there are less concurrent requests to browser drivers due to the nature of the API. We don't actively working on fixes for v4 anymore however if you can take a stab at it to fix this problem we are happy to merge and release it.

**Comment by arivas191** [comment]
I updated to v5 and now I can't run any of my tests, it looks like my syntax is not compatible with v5. Is there a quick fix to this? 

Errors: 

> Upload files and make transfers between internal users
    1) "before each" hook for "1. Should successfully upload, send and register file sent to an internal user"
(node:92205) UnhandledPromiseRejectionWarning: Error: Required option "capabilities" is missing
    at validateConfig (/Users/augusto/hushapp-tests/node_modules/@wdio/config/build/utils.js:109:13)
    at Object.remote (/Users/augusto/hushapp-tests/node_modules/webdriverio/build/index.js:30:45)
    at Context.beforeEach (/Users/augusto/hushapp-tests/web/1_uploadFile.js:35:14)
    at callFn (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runnable.js:372:21)
    at Hook.Runnable.run (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runnable.js:364:7)
    at next (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runner.js:317:10)
    at Immediate.<anonymous> (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runner.js:347:5)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
(node:92205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:92205) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    2) "after each" hook for "1. Should successfully upload, send and register file sent to an internal user"

  Upload files and make transfers between external users
    3) "before all" hook
(node:92205) UnhandledPromiseRejectionWarning: Error: Required option "capabilities" is missing
    at validateConfig (/Users/augusto/hushapp-tests/node_modules/@wdio/config/build/utils.js:109:13)
    at Object.remote (/Users/augusto/hushapp-tests/node_modules/webdriverio/build/index.js:30:45)
    at Context.before (/Users/augusto/hushapp-tests/web/1_uploadFile.js:166:14)
    at callFn (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runnable.js:372:21)
    at Hook.Runnable.run (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runnable.js:364:7)
    at next (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runner.js:317:10)
    at Immediate.<anonymous> (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runner.js:347:5)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
(node:92205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
    4) "after all" hook

  Upload files and make transfers between internal and external users
    5) "before each" hook for "1. Should successfully upload, send and register file sent to an internal and external user"
(node:92205) UnhandledPromiseRejectionWarning: Error: Required option "capabilities" is missing
    at validateConfig (/Users/augusto/hushapp-tests/node_modules/@wdio/config/build/utils.js:109:13)
    at Object.remote (/Users/augusto/hushapp-tests/node_modules/webdriverio/build/index.js:30:45)
    at Context.beforeEach (/Users/augusto/hushapp-tests/web/1_uploadFile.js:293:14)
    at callFn (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runnable.js:372:21)
    at Hook.Runnable.run (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runnable.js:364:7)
    at next (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runner.js:317:10)
    at Immediate.<anonymous> (/Users/augusto/hushapp-tests/node_modules/mocha/lib/runner.js:347:5)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
(node:92205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

>  1) Upload files and make transfers between internal users
       "before each" hook for "1. Should successfully upload, send and register file sent to an internal user":
     TypeError: webDriver.remote(...).init is not a function
      at Context.beforeEach (web/1_uploadFile.js:36:14)

  2) Upload files and make transfers between internal users
       "after each" hook for "1. Should successfully upload, send and register file sent to an internal user":
     TypeError: Cannot read property 'end' of null
      at Context.afterEach (web/1_uploadFile.js:41:17)

  3) Upload files and make transfers between external users
       "before all" hook:
     TypeError: webDriver.remote(...).init is not a function
      at Context.before (web/1_uploadFile.js:167:14)

  4) Upload files and make transfers between external users
       "after all" hook:
     TypeError: Cannot read property 'end' of null
      at Context.after (web/1_uploadFile.js:177:17)

  5) Upload files and make transfers between internal and external users
       "before each" hook for "1. Should successfully upload, send and register file sent to an internal and external user":
     TypeError: webDriver.remote(...).init is not a function
      at Context.beforeEach (web/1_uploadFile.js:294:14)

**Comment by arivas191** [comment]
This comes from here, where I initialize my browser:
`let browser = webDriver.remote(options).init()
        browser.windowHandleMaximize()`
And options is:
`let options = {
    desiredCapabilities: {
        browserName: env.web.browser
    }
}`

**Comment by christian-bromann** [comment]
@arivas191 you can't just update a major version and expect everything to work fine .. see https://webdriver.io/blog/2018/12/19/webdriverio-v5-released.html

**Comment by arivas191** [comment]
Just to be clear, are you guaranteeing that this issue doesn't occur in v5? My test suite is pretty big and if I upgrade I would have to change a significant amount of syntax in my tests in order for v5 to run them, and I want to make sure it will actually be worth the trouble.

**Comment by christian-bromann** [comment]
> and I want to make sure it will actually be worth the trouble.

We don't actively fix bugs in v4 anymore and v5 is much more advanced than v4 so the upgrade is definitely worthwhile.

**Comment by arivas191** [comment]
I'm sure it's more advanced, but the only issue I'm having with v4 is this one. So, do you know for a fact that this issue has been permanently fixed in v5?

**Comment by christian-bromann** [comment]
> So, do you know for a fact that this issue has been permanently fixed in v5?

I haven't heart about any such issues since v5
