### ISSUE TITLE
isDisplayed doesn't work properly because of refetch

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#3700]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.1

**Describe the bug**
isDisplayed fails once element is no longer exists

**To Reproduce**
```
// assuming element exists
const el = $('foo')
el.isDisplayed() // true/false
// remove element
el.isDisplayed() 
```

[Include code or an example repository that can easily be set up]

**Expected behavior**
el.isDisplayed() should return false immediately if element doesn't exist without refetching it.

**Log**
```
Error: Can't call isElementDisplayed on element with selector "input[type='submit']" because element wasn't found
     at implicitWait (/e2e/node_modules/webdriverio/build/utils/implicitWait.js:34:13)
     at Element.isDisplayed (/e2e/node_modules/webdriverio/build/commands/element/isDisplayed.js:89:19)
```

**Comment by mgrybyk** [comment]
had to change regex to match isElementDisplayed as well
https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/utils/implicitWait.js#L14
`if (!currentElement.elementId && !commandName.match(/(waitUntil|waitFor|isExisting|is?\w+Displayed)/)) {`
changed `isDisplayed` to `is?\w+Displayed`
