### ISSUE TITLE
 @wdio/config:ConfigParser: Failed loading configuration file: C:\Users\hp\test\node_modules\.bin\wdio.config.js: Cannot find module 'C:\Users\hp\test\node_modules\.bin\wdio.config.js

### ISSUE THREAD

**Issue by Storagecenter** [webdriverio/webdriverio#3704]
Error: Cannot find module 'C:\Users\hp\test\node_modules\.bin\wdio.config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at ConfigParser.addConfigFile (C:\Users\hp\test\node_modules\@wdio\config\build\lib\ConfigParser.js:51:48)
    at new Launcher (C:\Users\hp\test\node_modules\@wdio\cli\build\launcher.js:31:23)
    at launch (C:\Users\hp\test\node_modules\@wdio\cli\build\run.js:92:20)
    at run (C:\Users\hp\test\node_modules\@wdio\cli\build\run.js:68:12)
    at Object.run (C:\Users\hp\test\node_modules\@wdio\cli\build\index.js:45:20)
    at Object.<anonymous> (C:\Users\hp\test\node_modules\@wdio\cli\bin\wdio.js:11:21)

Iam facing this issue while lauching my 1st test script in V5

**Comment by mgrybyk** [comment]
@Storagecenter please provide:
- webdriverio version
- your package json
- your wdio config
- the way how are you running your tests

**Comment by christian-bromann** [comment]
I think something is up with the path to your wdio.conf.js. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have more questions.

**Comment by swagatik** [comment]
HI All i am facing the above issue . Need help to fix 

"devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-env": "^7.14.4",
    "@babel/register": "^7.13.16",
    "@wdio/cli": "^7.6.1",
    "@wdio/local-runner": "^7.6.1",
    "@wdio/mocha-framework": "^7.6.0",
    "@wdio/spec-reporter": "^7.6.1",
    "chromedriver": "^90.0.1",
    "wdio-chromedriver-service": "^7.1.0"
  },
  "dependencies": {
    "@wdio/sync": "^7.6.1"
