### ISSUE TITLE
Allure config.reporters throwing  _iterationError 

### ISSUE THREAD

**Issue by VinceBarresi** [webdriverio/webdriverio#3728]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [wdio-cucumber-framework 2.2.0]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** [10.9.0]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [n/a]
 - **Platform name and version:** [n/a]
 - **Additional wdio packages used (if applicable):** ["@wdio/allure-reporter": "^5.0.0", "@wdio/cli": "^5.7.2","@wdio/local-runner": "^5.7.2",  "@wdio/sauce-service": "^5.7.2", "wdiocucumber-framework": "~2.2.0","wdio-phantomjs-service": "~0.2.2","wdio-selenium-standalone-service": "~0.0.9",]

**Config of WebdriverIO**
```
exports.config = {
 
    services: ['sauce'],
  	user: process.env.SAUCE_USERNAME,
  	key: process.env.SAUCE_ACCESS_KEY,
  	region: 'us',
  	sauceConnect: true,
 
    specs: [
        './src/features/**/*.feature',
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 10,
   
    capabilities: [{
    
        platform: "macOS 10.12",
        browserName: "chrome",
        version: 61
  
    },
    {
    	platform: "macOS 10.12",
        browserName: "safari",
        version: 10.0
    }
    	
    ],
    bail: 0,  
    waitforTimeout: 10000,
    connectionRetryCount: 3,  
 framework: 'cucumber',
    reporters: [['allure', {
        outputDir: 'allure-results',
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: false,
    }]],
    cucumberOpts: {
    	backtrace: false,
    	compiler: [
    		'js:babel-register',
	    ],
        failAmbiguousDefinitions: true,
        failFast: false,
        ignoreUndefinedDefinitions: false,
        name: [],
        snippets: true,
        source: true,
        profile: [],
        require: [
            './integration_tests/cucumber-boilerplate/src/steps/given.js',
            './integration_tests/cucumber-boilerplate/src/steps/then.js',
            './integration_tests/cucumber-boilerplate/src/steps/when.js',
        ],
        snippetSyntax: undefined,
        strict: true,
        tagExpression: 'not @Pending',
        tagsInTitle: false,
        timeout: 20000,
    },
    before: function before() {
        const chai = require('chai');
        global.expect = chai.expect;
        global.assert = chai.assert;
        global.should = chai.should();
    },

    afterTest: function(test) {
    	if (test.error !== undefined) {
      		browser.takeScreenshot();
    	}
  	}

}
```

**Describe the bug**
I followed this https://webdriver.io/docs/allure-reporter.html to set up allure and when I run my conf file I see the stack thrown below.

**To Reproduce**
` ./node_modules/.bin/wdio wdio.SAUCE.conf.js`

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
```
10:23 $ ./node_modules/.bin/wdio wdio.SAUCE.conf.js
/Users/barresiv/Workspace/msg-wdio-cucumber-framework/node_modules/webdriverio/build/lib/launcher.js:163
                        throw _iteratorError;
                        ^

Error: config.reporters must be an array of strings or functions, but got 'object': allure,[object Object]
    at Launcher.initReporters (/Users/barresiv/Workspace/msg-wdio-cucumber-framework/node_modules/webdriverio/build/lib/launcher.js:145:31)
    at new Launcher (/Users/barresiv/Workspace/msg-wdio-cucumber-framework/node_modules/webdriverio/build/lib/launcher.js:73:31)
    at launch (/Users/barresiv/Workspace/msg-wdio-cucumber-framework/node_modules/webdriverio/build/lib/cli.js:452:24)
    at Object.<anonymous> (/Users/barresiv/Workspace/msg-wdio-cucumber-framework/node_modules/webdriverio/build/lib/cli.js:485:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```
**Additional context**

> Please use the correct markdown

**Comment by VinceBarresi** [comment]
I got this to work by modifying the code to - 

``` reporters: ['spec','allure'],
		reporterOptions: {
			outputDir: 'allure-results',
        	disableWebdriverStepsReporting: true,
        	disableWebdriverScreenshotsReporting: false,
	},
```

**Comment by WillBrock** [comment]
I think you are running v4 of webdriverIO, even though the packages you listed are for v5 and cucumber is not supported in v5 yet. 

The v4 docs are here:
http://v4.webdriver.io/
