### ISSUE TITLE
Multiremote issue when calling async functions

### ISSUE THREAD

**Issue by kevinmcdonnell** [webdriverio/webdriverio#3745]
**Environment (please complete the following information):**
 - **WebdriverIO version:** v5.7.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync
 - **Node.js version:** v8
 - **NPM version:** v5.6.0
 - **Browser name and version:** chrome
 - **Platform name and version:** mac
 - **Additional wdio packages used (if applicable):**n/a

**Config of WebdriverIO**
```
    capabilities: {
        managerOne: {
            capabilities: {
                browserName: 'chrome',
                'goog:chromeOptions': {
                    args: chromeArgs,
                }
            }
        },
        employeeOne: {
            capabilities: {
                browserName: 'chrome',
                'goog:chromeOptions': {
                    args: chromeArgs,
                }
            }
        }
    },

    before: async function () {
        browser.url('http://google.com');
        async function apiCall() {
        }

        console.log(`1: ${browser.$('body').getValue()}`);
        await apiCall();
        console.log(`2: ${browser.$('body').getValue()}`);

    }
```

**Describe the bug**
Calling an async function causes issues with subsequent commands

```
[0-0] 2019-03-20T22:29:31.850Z ERROR @wdio/sync: TypeError: browser.$(...).getValue is not a function
    at Object.before (/Users/kevinmcdonnell/dev/src/github.com/deputyapp/test-web/wdio.debug.js:50:45)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
Only affects multiremote

**To Reproduce**

run the above `wdio.conf.js`

**Expected behavior**
I would expect both logs to the console to be successful.

**Comment by christian-bromann** [comment]
If you use sync mode don't use async await and instead use the call command to resolve promises of 3rd parties, e.g.
```js
    before: function () {
        browser.url('http://google.com');
        async function apiCall() {
        }

        console.log(`1: ${browser.$('body').getValue()}`);
        browser.call(apiCall);
        console.log(`2: ${browser.$('body').getValue()}`);

    }
```
