### ISSUE TITLE
Testrunner does not connect to proper SauceLabs url

### ISSUE THREAD

**Issue by rolandjitsu** [webdriverio/webdriverio#3754]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.2
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 8.15.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 73
 - **Platform name and version:** macOS 10.14
 - **Additional wdio packages used (if applicable):** @wdio/cli, @wdio/jasmine-framework, @wdio/local-runner, @wdio/sauce-service, @wdio/spec-reporter

**Config of WebdriverIO**
See [wdio.conf.js](https://github.com/rolandjitsu/wdio-sl/blob/master/wdio.conf.js).

**Describe the bug**
It seems that when using the wdio test runner, SauceLabs connection is setup wrong. It looks like it's trying to connect to a local instance of Selenium instead of the remote one.

**To Reproduce**

Clone [wdio-sl](https://github.com/rolandjitsu/wdio-sl) and follow the steps in the [README](https://github.com/rolandjitsu/wdio-sl/blob/master/README.md).

**Expected behavior**
The test runner should connect to a remove instance of Selenium at SauceLabs.

**Log**
Check [9fef47d](https://gist.github.com/rolandjitsu/9fef47d1bfb88467e00b63b806ce6f1d).

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Connecting to `localhost:4445` is correct. Your problem is that you are using async/await not consequently, see:

```js
expect(node.getText()).toBe('Test')
```
should be
```js
expect(await node.getText()).toBe('Test')
```

For exactly this reason WebdriverIO provides a complete synchronous test execution. I advise to use that instead of async/await.

**Comment by rolandjitsu** [comment]
That is not the problem, please see [88f44d5](https://app.saucelabs.com/tests/88f44d550a294930afcb2c7c62a021dc) test results. You will see that it actually never reaches the localhost server and the test fails.

If I run `remote({ user, key, ... })` myself, it works just fine and connects directly to saucelabs.

Please try the repo and hopefully you'll see that there is a problem that is not what you suggest.

**Comment by christian-bromann** [comment]
The issue I outlined above was actually a problem in your code. Now you are describing a different problem. I am happy to fix issues when identified but I don't have the capabilities to find out problems for others. Sorry!

**Comment by rolandjitsu** [comment]
I was describing the same problem, but in any case, I'm not sure why I get the 500. The only difference I see when using the test runner vs standalone is the POST for creating a session. When using the standalone remote, it creates a session directly with SL, but when using the test runner, it creates a session with localhost.

That's the issue I'm trying to describe. And the repo illustrates that problem. But I'm not sure if I'm just an idiot and I messed up the config or there is an actual problem.

Of course I understand you're not just gonna fix other ppl's issues, but I think it's worth giving it a try to see if it's an actual issue. I'm more than happy to keep digging if you point me in the right direction.

**Comment by wswebcreation** [comment]
Hi @rolandjitsu 

I've checked your project and I see the following.

```log
"spec" Reporter:
------------------------------------------------------------------
[safari 12.0 macOS 10.14 #1-0] Spec: /Users/wimselles/Git/wdio-sl/e2e/next.spec.js
[safari 12.0 macOS 10.14 #1-0] Running: safari (v12.0) on macOS 10.14
[safari 12.0 macOS 10.14 #1-0]
[safari 12.0 macOS 10.14 #1-0] next.js integration
[safari 12.0 macOS 10.14 #1-0]    ✖ should work
[safari 12.0 macOS 10.14 #1-0]
[safari 12.0 macOS 10.14 #1-0] 1 failing (3.2s)
[safari 12.0 macOS 10.14 #1-0]
[safari 12.0 macOS 10.14 #1-0] 1) next.js integration should work
[safari 12.0 macOS 10.14 #1-0] Error:
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'itako2848.prod.miso', ip: 'fe80:0:0:0:107d:3d35:a20f:3917%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '9.0.4'
Driver info: driver.version: unknown
[safari 12.0 macOS 10.14 #1-0] Error:
[safari 12.0 macOS 10.14 #1-0] For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
[safari 12.0 macOS 10.14 #1-0] Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
[safari 12.0 macOS 10.14 #1-0] System info: host: 'itako2848.prod.miso', ip: 'fe80:0:0:0:107d:3d35:a20f:3917%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '9.0.4'
[safari 12.0 macOS 10.14 #1-0] Driver info: driver.version: unknown
[safari 12.0 macOS 10.14 #1-0]     at Request.emit (events.js:189:13)
[safari 12.0 macOS 10.14 #1-0]     at Request.EventEmitter.emit (domain.js:441:20)
[safari 12.0 macOS 10.14 #1-0]     at Request.emit (events.js:189:13)
[safari 12.0 macOS 10.14 #1-0]     at Request.EventEmitter.emit (domain.js:441:20)
[safari 12.0 macOS 10.14 #1-0]     at Object.onceWrapper (events.js:277:13)
------------------------------------------------------------------
[internet explorer 11.285 Windows 10 #4-0] Spec: /Users/wimselles/Git/wdio-sl/e2e/next.spec.js
[internet explorer 11.285 Windows 10 #4-0] Running: internet explorer (v11.285) on Windows 10
[internet explorer 11.285 Windows 10 #4-0]
[internet explorer 11.285 Windows 10 #4-0] next.js integration
[internet explorer 11.285 Windows 10 #4-0]    ✓ should work
[internet explorer 11.285 Windows 10 #4-0]
[internet explorer 11.285 Windows 10 #4-0] 1 passing (4.6s)
------------------------------------------------------------------
[MicrosoftEdge 18.17763 Windows 10 #3-0] Spec: /Users/wimselles/Git/wdio-sl/e2e/next.spec.js
[MicrosoftEdge 18.17763 Windows 10 #3-0] Running: MicrosoftEdge (v18.17763) on Windows 10
[MicrosoftEdge 18.17763 Windows 10 #3-0]
[MicrosoftEdge 18.17763 Windows 10 #3-0] next.js integration
[MicrosoftEdge 18.17763 Windows 10 #3-0]    ✓ should work
[MicrosoftEdge 18.17763 Windows 10 #3-0]
[MicrosoftEdge 18.17763 Windows 10 #3-0] 1 passing (3.3s)
------------------------------------------------------------------
[firefox 65.0 macOS 10.14 #2-0] Spec: /Users/wimselles/Git/wdio-sl/e2e/next.spec.js
[firefox 65.0 macOS 10.14 #2-0] Running: firefox (v65.0) on macOS 10.14
[firefox 65.0 macOS 10.14 #2-0]
[firefox 65.0 macOS 10.14 #2-0] next.js integration
[firefox 65.0 macOS 10.14 #2-0]    ✖ should work
[firefox 65.0 macOS 10.14 #2-0]
[firefox 65.0 macOS 10.14 #2-0] 1 failing (5.8s)
[firefox 65.0 macOS 10.14 #2-0]
[firefox 65.0 macOS 10.14 #2-0] 1) next.js integration should work
[firefox 65.0 macOS 10.14 #2-0] Error: Unable to locate element: .test
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'itako3295.prod.miso', ip: 'fe80:0:0:0:c7c:da1d:3510:9b79%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '9.0.4'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=/var/folders/5k/_tslnm4n2y5_8w99pfpl7qzh0000kr/T/rust_mozprofile.151ohxcfMA3N, rotatable=false, moz:geckodriverVersion=0.23.0, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss and notify, strictFileInteractability=false, moz:headless=false, platform=ANY, proxy=Proxy(pac: http://127.0.0.1:19876/pac.js), moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=65.0, moz:shutdownTimeout=60000.0, platformVersion=18.0.0, moz:processID=4863.0, browserName=firefox, javascriptEnabled=true, platformName=mac, setWindowRect=true, moz:webdriverClick=true}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX58797bb9
*** Element info: {Using=css selector, value=.test}
[firefox 65.0 macOS 10.14 #2-0] Error: Unable to locate element: .test
[firefox 65.0 macOS 10.14 #2-0] For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
[firefox 65.0 macOS 10.14 #2-0] Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
[firefox 65.0 macOS 10.14 #2-0] System info: host: 'itako3295.prod.miso', ip: 'fe80:0:0:0:c7c:da1d:3510:9b79%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14', java.version: '9.0.4'
[firefox 65.0 macOS 10.14 #2-0] Driver info: org.openqa.selenium.firefox.FirefoxDriver
[firefox 65.0 macOS 10.14 #2-0] Capabilities [{moz:profile=/var/folders/5k/_tslnm4n2y5_8w99pfpl7qzh0000kr/T/rust_mozprofile.151ohxcfMA3N, rotatable=false, moz:geckodriverVersion=0.23.0, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss and notify, strictFileInteractability=false, moz:headless=false, platform=ANY, proxy=Proxy(pac: http://127.0.0.1:19876/pac.js), moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=65.0, moz:shutdownTimeout=60000.0, platformVersion=18.0.0, moz:processID=4863.0, browserName=firefox, javascriptEnabled=true, platformName=mac, setWindowRect=true, moz:webdriverClick=true}]
[firefox 65.0 macOS 10.14 #2-0] Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX58797bb9
[firefox 65.0 macOS 10.14 #2-0] *** Element info: {Using=css selector, value=.test}
[firefox 65.0 macOS 10.14 #2-0]     at Request.emit (events.js:189:13)
[firefox 65.0 macOS 10.14 #2-0]     at Request.EventEmitter.emit (domain.js:441:20)
[firefox 65.0 macOS 10.14 #2-0]     at Request.emit (events.js:189:13)
[firefox 65.0 macOS 10.14 #2-0]     at Request.EventEmitter.emit (domain.js:441:20)
[firefox 65.0 macOS 10.14 #2-0]     at Object.onceWrapper (events.js:277:13)
------------------------------------------------------------------
[chrome 73.0 macOS 10.14 #0-0] Spec: /Users/wimselles/Git/wdio-sl/e2e/next.spec.js
[chrome 73.0 macOS 10.14 #0-0] Running: chrome (v73.0) on macOS 10.14
[chrome 73.0 macOS 10.14 #0-0]
[chrome 73.0 macOS 10.14 #0-0] next.js integration
[chrome 73.0 macOS 10.14 #0-0]    ✖ should work
[chrome 73.0 macOS 10.14 #0-0]
[chrome 73.0 macOS 10.14 #0-0] 1 failing (11.5s)
[chrome 73.0 macOS 10.14 #0-0]
[chrome 73.0 macOS 10.14 #0-0] 1) next.js integration should work
[chrome 73.0 macOS 10.14 #0-0] Error: Timeout - Async callback was not invoked within 10000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
[chrome 73.0 macOS 10.14 #0-0] Error: Timeout - Async callback was not invoked within 10000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
[chrome 73.0 macOS 10.14 #0-0]     at <Jasmine>
[chrome 73.0 macOS 10.14 #0-0]     at ontimeout (timers.js:436:11)
[chrome 73.0 macOS 10.14 #0-0]     at tryOnTimeout (timers.js:300:5)
[chrome 73.0 macOS 10.14 #0-0]     at listOnTimeout (timers.js:263:5)
[chrome 73.0 macOS 10.14 #0-0]     at Timer.processTimers (timers.js:223:10)


Stdout:
2019-03-23T06:20:17.742Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "sauce"
2019-03-23T06:20:17.775Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-03-23T06:20:32.723Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
2019-03-23T06:20:32.734Z INFO @wdio/local-runner: Start worker 1-0 with arg: wdio.conf.js
2019-03-23T06:20:32.743Z INFO @wdio/local-runner: Start worker 2-0 with arg: wdio.conf.js
2019-03-23T06:20:32.752Z INFO @wdio/local-runner: Start worker 3-0 with arg: wdio.conf.js
2019-03-23T06:20:32.766Z INFO @wdio/local-runner: Start worker 4-0 with arg: wdio.conf.js
2019-03-23T06:20:46.199Z DEBUG @wdio/local-runner: Runner 1-0 finished with exit code 1
2019-03-23T06:20:51.492Z DEBUG @wdio/local-runner: Runner 4-0 finished with exit code 0
2019-03-23T06:20:53.493Z DEBUG @wdio/local-runner: Runner 2-0 finished with exit code 1
2019-03-23T06:20:53.498Z DEBUG @wdio/local-runner: Runner 3-0 finished with exit code 0
2019-03-23T06:20:53.846Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
2019-03-23T06:20:53.847Z INFO @wdio/cli:Launcher: Run onComplete hook

Test Suites:	 2 passed, 3 failed, 5 total (100% completed)
Time:		 🕓  53.87s
```

It looks like the tunnel is not working on Mac, but it works on the Windows VM's when the tunnel is started with WebdriverIO

When I start a manual tunnel manual I get the same issue on Mac and not on Windows. Please contact the Sauce Labs helpdesk for this.

To give you some feedback on your question. First of all thanks for the sample repo. The question itself, see this

> It seems that when using the wdio test runner, SauceLabs connection is setup wrong. It looks like it's trying to connect to a local instance of Selenium instead of the remote one.

is not really describing the issue you are facing. You get a 500 error on Mac accessing a local hosted page with the tunnel and not on Windows. 

As said, file this issue with the _proper_ info and steps what you already did (like it's working on Windows, but not on Mac, even when you start a manual tunnel) and see if they can help you

**Comment by wswebcreation** [comment]
@rolandjitsu and @christian-bromann 

This is a _mac issue_ not being able to connect to the localhost. If you use your internal ip address of the machine like this `http://123.456.789.01:3000/` everything will work. This could be a restriction in OSX that `localhost` always goes to the internal localhost. 


```log
 ------------------------------------------------------------------
[internet explorer 11.285 Windows 10 #4-0] Spec: /Users/wimselles/Git/wdio-sl/e2e/next.spec.js
[internet explorer 11.285 Windows 10 #4-0] Running: internet explorer (v11.285) on Windows 10
[internet explorer 11.285 Windows 10 #4-0]
[internet explorer 11.285 Windows 10 #4-0] next.js integration
[internet explorer 11.285 Windows 10 #4-0]    ✓ should work
[internet explorer 11.285 Windows 10 #4-0]
[internet explorer 11.285 Windows 10 #4-0] 1 passing (4.1s)
[internet explorer 11.285 Windows 10 #4-0]
[internet explorer 11.285 Windows 10 #4-0] Check out job at https://app.saucelabs.com/tests/7aa3345f1a924fc3afb96f70f5bef729
------------------------------------------------------------------
[safari 12.0 macOS 10.14 #1-0] Spec: /Users/wimselles/Git/wdio-sl/e2e/next.spec.js
[safari 12.0 macOS 10.14 #1-0] Running: safari (v12.0) on macOS 10.14
[safari 12.0 macOS 10.14 #1-0]
[safari 12.0 macOS 10.14 #1-0] next.js integration
[safari 12.0 macOS 10.14 #1-0]    ✓ should work
[safari 12.0 macOS 10.14 #1-0]
[safari 12.0 macOS 10.14 #1-0] 1 passing (3.5s)
[safari 12.0 macOS 10.14 #1-0]
[safari 12.0 macOS 10.14 #1-0] Check out job at https://app.saucelabs.com/tests/495356e731814515a2362336d209c323
------------------------------------------------------------------
[chrome 73.0 macOS 10.14 #0-0] Spec: /Users/wimselles/Git/wdio-sl/e2e/next.spec.js
[chrome 73.0 macOS 10.14 #0-0] Running: chrome (v73.0) on macOS 10.14
[chrome 73.0 macOS 10.14 #0-0]
[chrome 73.0 macOS 10.14 #0-0] next.js integration
[chrome 73.0 macOS 10.14 #0-0]    ✓ should work
[chrome 73.0 macOS 10.14 #0-0]
[chrome 73.0 macOS 10.14 #0-0] 1 passing (3.4s)
[chrome 73.0 macOS 10.14 #0-0]
[chrome 73.0 macOS 10.14 #0-0] Check out job at https://app.saucelabs.com/tests/c44d5d0b69a14840a178bbedf0e4fb79
------------------------------------------------------------------
[firefox 65.0 macOS 10.14 #2-0] Spec: /Users/wimselles/Git/wdio-sl/e2e/next.spec.js
[firefox 65.0 macOS 10.14 #2-0] Running: firefox (v65.0) on macOS 10.14
[firefox 65.0 macOS 10.14 #2-0]
[firefox 65.0 macOS 10.14 #2-0] next.js integration
[firefox 65.0 macOS 10.14 #2-0]    ✓ should work
[firefox 65.0 macOS 10.14 #2-0]
[firefox 65.0 macOS 10.14 #2-0] 1 passing (3.4s)
[firefox 65.0 macOS 10.14 #2-0]
[firefox 65.0 macOS 10.14 #2-0] Check out job at https://app.saucelabs.com/tests/798e4b33b2a5495c945a9975ae7b3234
------------------------------------------------------------------
[MicrosoftEdge 18.17763 Windows 10 #3-0] Spec: /Users/wimselles/Git/wdio-sl/e2e/next.spec.js
[MicrosoftEdge 18.17763 Windows 10 #3-0] Running: MicrosoftEdge (v18.17763) on Windows 10
[MicrosoftEdge 18.17763 Windows 10 #3-0]
[MicrosoftEdge 18.17763 Windows 10 #3-0] next.js integration
[MicrosoftEdge 18.17763 Windows 10 #3-0]    ✓ should work
[MicrosoftEdge 18.17763 Windows 10 #3-0]
[MicrosoftEdge 18.17763 Windows 10 #3-0] 1 passing (4s)
[MicrosoftEdge 18.17763 Windows 10 #3-0]
[MicrosoftEdge 18.17763 Windows 10 #3-0] Check out job at https://app.saucelabs.com/tests/95498a0c9120488a85601638c16c6a1c


Stdout:
2019-03-23T13:48:22.619Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "sauce"
2019-03-23T13:48:22.647Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-03-23T13:48:22.650Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
2019-03-23T13:48:22.658Z INFO @wdio/local-runner: Start worker 1-0 with arg: wdio.conf.js
2019-03-23T13:48:22.665Z INFO @wdio/local-runner: Start worker 2-0 with arg: wdio.conf.js
2019-03-23T13:48:22.669Z INFO @wdio/local-runner: Start worker 3-0 with arg: wdio.conf.js
2019-03-23T13:48:22.679Z INFO @wdio/local-runner: Start worker 4-0 with arg: wdio.conf.js
2019-03-23T13:48:39.283Z DEBUG @wdio/local-runner: Runner 4-0 finished with exit code 0
2019-03-23T13:48:40.016Z DEBUG @wdio/local-runner: Runner 1-0 finished with exit code 0
2019-03-23T13:48:43.037Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 0
2019-03-23T13:48:43.288Z DEBUG @wdio/local-runner: Runner 2-0 finished with exit code 0
2019-03-23T13:48:43.608Z DEBUG @wdio/local-runner: Runner 3-0 finished with exit code 0
2019-03-23T13:48:43.610Z INFO @wdio/cli:Launcher: Run onComplete hook

Test Suites:	 5 passed, 5 total (100% completed)
Time:		 🕛  21.02s
```

**Comment by rolandjitsu** [comment]
@wswebcreation thanks for taking a look at this, I appreciate it. I wasn't actually aware that it was working on Windows but not macOS. I only tried to change the browsers.

I'm curious if Linux has the same issue.

So one would have to use some node ip lib to get the current ip address and set that in the config. As long as it works, it wouldn't be so bad. But I wonder if this is the way it is or it's a bug. Because it should probably document somewhere for future reference.

**Comment by wswebcreation** [comment]
Hi @rolandjitsu,

I checked with our support and it's a bug in our Mac machine's. If you use Mac 10.13 and below it will work. 
So the workaround is to or use 10.13 or use the local up of the machine that hosts the site.

There's currently not yet an estimate when this will be fixed.

**Comment by Farfurix** [comment]
@wswebcreation 

Thanks, it works for me:
```js
{
    browserName: 'safari',
    platform:    'macOS 10.13',
    version:     '12.1'
}
```
