### ISSUE TITLE
waitForDisplayed() don't work for IE11 browser

### ISSUE THREAD

**Issue by miadzvedski-dzmitry** [webdriverio/webdriverio#3755]
**Environment:**
 - **WebdriverIO version:** [5.7.3]
 - **Mode:** [WDIO Testrunner]
 - **Node.js version:** [8.12.0]
 - **NPM version:** [6.4.1]
 - **Browser name and version:** [IE11]
 - **Platform name and version:** [Windows 8.1]

**Describe the bug**
When I try to use waitForDisplayed() function, it doesn't wait the timeout time I set, just wait around 10 seconds or less then failed with "Request failed due to Error: Unable to find element with css selector".

Request failed due to Error: Unable to find element with css selector

at getErrorFromResponseBody (/node_modules/webdriver/build/utils.js:343:10)
    at Request._callback (/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/node_modules/request/request.js:1157:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:313:30)

**Comment by christian-bromann** [comment]
I don't think this is a problem with WebdriverIO. It seems that the element indeed can not be found after 10s.

**Comment by miadzvedski-dzmitry** [comment]
@christian-bromann But why it waits only 10 seconds when i passed waitForDisplayed(30000). Other browsers wait 30000 in this case?

**Comment by christian-bromann** [comment]
@miadzvedski-dzmitry that is impossible to say without being able to see any logs 🤷‍♂️
