### ISSUE TITLE
Command not found: Get session log types

### ISSUE THREAD

**Issue by beatrichartz** [webdriverio/webdriverio#3834]
**Describe your question with as much detail as possible**
When running tests on IE10, after a passing test we get this error:
```
Worker Error:
Error: Command not found: GET /session/8dbb4082-c940-4723-ad32-d2e759091c93/log/types
Command duration or timeout: 6 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: '207-254-56-57', ip: '207.254.56.57', os.name: 'windows', os.arch: 'x86', os.version: '6.2', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=10, platform=WINDOWS, nativeEvents=true, ie.ensur
eCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=about:blank, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedMod
eSettings=true, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: 8dbb4082-c940-4723-ad32-d2e759091c93
    at getErrorFromResponseBody (/project/node_modules/webdriver/build/utils.js:343:10)
    at Request._callback (/project/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/project/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:481:20)
    at Request.<anonymous> (/project/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:481:20)
    at IncomingMessage.<anonymous> (/project/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:285:20)
```

We believe that IE driver does not respond to the log types request with a 501 Not Implemented as other drivers. Instead, it sends a "Command not found", thereby triggering the error in Webdriver. We tried excluding the driver logs or disabling the logs, but the error keeps happening.

Is there a way to either fix this or work around it?

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 11.12.0
 - **NPM version:** Yarn 1.15.2, npm 6.7.0
 - **Browser name and version:** IE10
 - **Platform name and version:** Windows 8
 - **Additional wdio packages used (if applicable):** @wdio/cli

**Comment by christian-bromann** [comment]
> Is there a way to either fix this or work around it?

Can you provide the the output of `browser.capabilities`?

**Comment by mgrybyk** [comment]
It might be happening here https://github.com/webdriverio/webdriverio/blob/0c22df0b407bf913e836b689456157276752a621/packages/wdio-runner/src/index.js#L221

@beatrichartz may I ask you to remove `outputDir` from your wdio.config and let us know if you are still getting this error? 
Also please provide output of `browser.capabilities` as mentioned above

**Comment by pmerwin** [comment]
We are seeing this issue as well with IE over sauce

console.log(JSON.stringify(browser.capabilities, null, 4)); returns:
```
[0-0] {
     "takesScreenshot": true,
     "version": "11",
     "ie.forceShellWindowsApi": false,
     "unexpectedAlertBehaviour": "dismiss",
     "ie.browserCommandLineSwitches": "",
     "browserAttachTimeout": 0,
     "ie.ensureCleanSession": false,
     "ignoreProtectedModeSettings": false,
     "platform": "WINDOWS",
     "webdriver.remote.sessionid": "fb7c05a28f864c4f982cef514255cb25",
     "ignoreZoomSetting": false,
     "nativeEvents": true,
     "ie.enableFullPageScreenshot": true,
     "javascriptEnabled": true,
     "requireWindowFocus": false,
     "browserName": "internet explorer",
     "hasMetadata": true,
     "initialBrowserUrl": "about:blank",
     "enableElementCacheCleanup": true,
     "cssSelectorsEnabled": true,
     "ie.fileUploadDialogTimeout": 3000,
     "elementScrollBehavior": 0,
     "enablePersistentHover": true,
     "pageLoadStrategy": "normal",
     "ie.forceCreateProcessApi": false
}

Worker Error:
Error: Command not found: GET /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3/log/types
Command duration or timeout: 0 milliseconds
```

**Comment by pmerwin** [comment]
the wdio log:

```
2019-04-10T23:22:21.481Z INFO @wdio/local-runner: Run worker command: run
2019-04-10T23:22:21.622Z INFO webdriver: [POST] https://ondemand.saucelabs.com:443/wd/hub/session
2019-04-10T23:22:21.622Z INFO webdriver: DATA { capabilities: 
   { alwaysMatch: 
      { browserName: 'internet explorer',
        platformVersion: 'Windows 10',
        browserVersion: '11.0' },
     firstMatch: [ {} ] },
  desiredCapabilities: 
   { browserName: 'internet explorer',
     platformVersion: 'Windows 10',
     browserVersion: '11.0' } }
2019-04-10T23:22:33.475Z INFO webdriver: COMMAND executeScript("sauce:context=WebdriverIO Example - should not throw error", <object>)
2019-04-10T23:22:33.476Z INFO webdriver: [POST] https://ondemand.saucelabs.com:443/wd/hub/session/fb7c05a28f864c4f982cef514255cb25/execute
2019-04-10T23:22:33.476Z INFO webdriver: DATA { script: 'sauce:context=WebdriverIO Example - should not throw error',
  args: [] }
2019-04-10T23:22:33.705Z INFO webdriver: RESULT 
2019-04-10T23:22:33.710Z INFO webdriver: COMMAND navigateTo("https://www.google.com/")
2019-04-10T23:22:33.710Z INFO webdriver: [POST] https://ondemand.saucelabs.com:443/wd/hub/session/fb7c05a28f864c4f982cef514255cb25/url
2019-04-10T23:22:33.710Z INFO webdriver: DATA { url: 'https://www.google.com/' }
2019-04-10T23:22:37.054Z INFO @wdio/sauce-service: Update job with sessionId fb7c05a28f864c4f982cef514255cb25, status: passing
2019-04-10T23:22:37.287Z INFO webdriver: COMMAND getLogTypes()
2019-04-10T23:22:37.288Z INFO webdriver: [GET] https://ondemand.saucelabs.com:443/wd/hub/session/fb7c05a28f864c4f982cef514255cb25/log/types
2019-04-10T23:22:37.439Z WARN webdriver: Request failed due to Command not found: GET /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3/log/types
Command duration or timeout: 0 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'sauce-win10', ip: '172.20.44.70', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=about:blank, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3
2019-04-10T23:22:37.439Z INFO webdriver: Retrying 1/3
2019-04-10T23:22:37.439Z INFO webdriver: [GET] https://ondemand.saucelabs.com:443/wd/hub/session/fb7c05a28f864c4f982cef514255cb25/log/types
2019-04-10T23:22:37.576Z WARN webdriver: Request failed due to Command not found: GET /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3/log/types
Command duration or timeout: 0 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'sauce-win10', ip: '172.20.44.70', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=about:blank, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3
2019-04-10T23:22:37.576Z INFO webdriver: Retrying 2/3
2019-04-10T23:22:37.576Z INFO webdriver: [GET] https://ondemand.saucelabs.com:443/wd/hub/session/fb7c05a28f864c4f982cef514255cb25/log/types
2019-04-10T23:22:37.718Z WARN webdriver: Request failed due to Command not found: GET /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3/log/types
Command duration or timeout: 16 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'sauce-win10', ip: '172.20.44.70', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=about:blank, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3
2019-04-10T23:22:37.718Z INFO webdriver: Retrying 3/3
2019-04-10T23:22:37.718Z INFO webdriver: [GET] https://ondemand.saucelabs.com:443/wd/hub/session/fb7c05a28f864c4f982cef514255cb25/log/types
2019-04-10T23:22:37.901Z ERROR webdriver: Request failed due to Error: Command not found: GET /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3/log/types
Command duration or timeout: 0 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'sauce-win10', ip: '172.20.44.70', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=about:blank, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3
    at getErrorFromResponseBody (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/webdriver/build/utils.js:348:10)
    at Request._callback (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
2019-04-10T23:22:37.904Z ERROR @wdio/runner: Error: Command not found: GET /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3/log/types
Command duration or timeout: 0 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'sauce-win10', ip: '172.20.44.70', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=about:blank, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXb20f18b3
    at getErrorFromResponseBody (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/webdriver/build/utils.js:348:10)
    at Request._callback (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/request/request.js:185:22)
    at Request.<anonymous> (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/request/request.js:1161:10)
    at IncomingMessage.<anonymous> (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/request/request.js:1083:12)
    at Runner._fetchDriverLogs (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/@wdio/runner/build/index.js:264:91)
    at Runner.run (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/@wdio/runner/build/index.js:170:18)
    at <anonymous>
2019-04-10T23:22:37.904Z INFO webdriver: COMMAND deleteSession()
2019-04-10T23:22:37.905Z INFO webdriver: [DELETE] https://ondemand.saucelabs.com:443/wd/hub/session/fb7c05a28f864c4f982cef514255cb25
2019-04-10T23:22:38.220Z INFO webdriver: RESULT 

```

**Comment by mgrybyk** [comment]
Can you please outputDir from your wdio.config and try if it helps, please?

**Comment by christian-bromann** [comment]
This should be fixed with https://github.com/webdriverio/webdriverio/pull/3832 .. could you please update all wdio packages try again?

**Comment by pmerwin** [comment]
I confirmed I am running "version": "5.7.12"

with IE I see:

```
[0-0] {
     "takesScreenshot": true,
     "version": "11",
     "ie.forceShellWindowsApi": false,
     "unexpectedAlertBehaviour": "dismiss",
     "ie.browserCommandLineSwitches": "",
     "browserAttachTimeout": 0,
     "ie.ensureCleanSession": false,
     "ignoreProtectedModeSettings": false,
     "platform": "WINDOWS",
     "webdriver.remote.sessionid": "1a078a736943429b8bae7ad418b86aa3",
     "ignoreZoomSetting": false,
     "nativeEvents": true,
     "ie.enableFullPageScreenshot": true,
     "javascriptEnabled": true,
     "requireWindowFocus": false,
     "browserName": "internet explorer",
     "hasMetadata": true,
     "initialBrowserUrl": "about:blank",
     "enableElementCacheCleanup": true,
     "cssSelectorsEnabled": true,
     "ie.fileUploadDialogTimeout": 3000,
     "elementScrollBehavior": 0,
     "enablePersistentHover": true,
     "pageLoadStrategy": "normal",
     "ie.forceCreateProcessApi": false
}

Stderr:
[0-0] (node:24217) ExperimentalWarning: The http2 module is an experimental API.

Worker Error:
Error: Command not found: GET /session/XXXXXXXX-XXXX-XXXX-XXXX-XXXX40ac7e4f/log/types
```
and when I remark out ouPuDir from my config it does not throw an error @mgrybyk 
Edge does seem to work now, fyi.

**Comment by christian-bromann** [comment]
I guess the best thing to do here is to catch the `getLogTypes` call after all. The capabilities above are definitely jsonwire ones but it seems that IE still doesn't support that command.

**Comment by pmerwin** [comment]
FYI: same issue with safari:

```

Command duration or timeout: 4 milliseconds
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'itako4543.prod.miso', ip: 'fe80:0:0:0:4d6:335c:869a:c8c2%en0', os.name: 'Mac OS X', os.arch: 'x86
_64', os.version: '10.12.6', java.version: '9.0.4'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12604
.5.6.1.1, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, b
rowserName=safari, javascriptEnabled=true, platformName=macOS, cssSelectorsEnabled=true}]
Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX5975C654
```

**Comment by naddison** [comment]
I can only reproduce this error on internet explorer and windows against sauce labs when I set an outputDir on either the config or a junit-unit-reporter.

```javascript
capabilities: [
    {
      browserName: 'internet explorer',
      platform: 'windows'
    }
  ],
```
