### ISSUE TITLE
Firefox Nightly / Dev Edition crashes after 45 seconds

### ISSUE THREAD

**Issue by vladikoff** [webdriverio/webdriverio#387]
Here is an example repo to reproduce this error: https://github.com/vladikoff/test-wdio/tree/master

Using Selenium 2.44 and latest stable webdriverio

To test run with a nightly or dev edition variable: `FIREFOX_BIN=/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin npm start`

Is this a Selenium issue?

**FULL ERROR OUTPUT**
```
➜  test-wdio  FIREFOX_BIN=/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin npm start

> test-wdio@1.0.0 start /Users/vladikoff/dev/test-wdio
> node index.js


RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: Unable to connect to host 127.0.0.1 on port 7056 after 45000 ms. Firefox console output:
20565412773	addons.xpi-utils	DEBUG	shutdown
1420565412774	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1420565412774	addons.manager	DEBUG	Calling shutdown blocker for OpenH264Provider
1420565412775	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1420565412817	DeferredSave.extensions.json	DEBUG	Write succeeded
1420565412817	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 16
1420565412818	addons.xpi	DEBUG	Notifying XPI shutdown observers
1420565412820	addons.manager	DEBUG	Async provider shutdown done
1420565413070	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1420565413072	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1420565413075	addons.xpi	DEBUG	startup
1420565413075	addons.xpi	INFO	Mapping fxdriver@googlecode.com to /var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous7326826338437365565webdriver-profile/extensions/fxdriver@googlecode.com
1420565413075	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous7326826338437365565webdriver-profile/extensions/webdriver-staging
1420565413076	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /Applications/FirefoxNightly.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
1420565413076	addons.xpi	DEBUG	Skipping unavailable install location app-system-share
1420565413077	addons.xpi	DEBUG	checkForChanges
1420565413077	addons.xpi	DEBUG	Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"/var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous7326826338437365565webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1420565411000,"mt":1420565411000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/FirefoxNightly.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"37.0a1","st":1420052210000,"mt":1420052200000}}}
1420565413078	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1420565413081	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1420565413081	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous7326826338437365565webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1420565411000,"mt":1420565411000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/FirefoxNightly.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"37.0a1","st":1420052210000,"mt":1420052200000}}}
1420565413082	addons.xpi	DEBUG	No changes found
1420565413085	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1420565413085	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1420565413087	addons.manager	DEBUG	Registering shutdown blocker for OpenH264Provider
1420565413087	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
JavaScript error: file:///var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous7326826338437365565webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
*** Blocklist::_preloadBlocklistFile: blocklist is disabled
1420565414103	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
JavaScript error: file:///var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous7326826338437365565webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined


     Callstack:
     -> init()


npm ERR! test-wdio@1.0.0 start: `node index.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the test-wdio@1.0.0 start script.
npm ERR! This is most likely a problem with the test-wdio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls test-wdio
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/Users/vladikoff/npmlocal/bin/npm" "start"
npm ERR! cwd /Users/vladikoff/dev/test-wdio
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/vladikoff/dev/test-wdio/npm-debug.log
npm ERR! not ok code 0
➜  test-wdio  FIREFOX_BIN=/Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox-bin npm start
```

**Comment by christian-bromann** [comment]
Hi @vladikoff have you tried using standalone v2.43.x?

**Comment by vladikoff** [comment]
Hey, 

Yeap just tried, same error. Here is the 2.43 log output:
```
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'vladikoff', ip: '192.168.1.174', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_67'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
	... 14 more
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
erredSave.extensions.json	DEBUG	Starting write
1420567012457	addons.manager	DEBUG	shutdown
1420567012457	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1420567012458	addons.xpi	DEBUG	shutdown
1420567012458	addons.xpi-utils	DEBUG	shutdown
1420567012458	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1420567012458	addons.manager	DEBUG	Calling shutdown blocker for OpenH264Provider
1420567012459	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1420567012502	DeferredSave.extensions.json	DEBUG	Write succeeded
1420567012503	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 16
1420567012503	addons.xpi	DEBUG	Notifying XPI shutdown observers
1420567012505	addons.manager	DEBUG	Async provider shutdown done
1420567012756	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1420567012757	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1420567012760	addons.xpi	DEBUG	startup
1420567012761	addons.xpi	INFO	Mapping fxdriver@googlecode.com to /var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous4787829424919036944webdriver-profile/extensions/fxdriver@googlecode.com
1420567012761	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous4787829424919036944webdriver-profile/extensions/webdriver-staging
1420567012761	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /Applications/FirefoxDeveloperEdition.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
1420567012762	addons.xpi	DEBUG	Skipping unavailable install location app-system-share
1420567012762	addons.xpi	DEBUG	checkForChanges
1420567012763	addons.xpi	DEBUG	Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"/var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous4787829424919036944webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1420567011000,"mt":1420567011000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/FirefoxDeveloperEdition.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"36.0a2","st":1420018877000,"mt":1420016652000}}}
1420567012763	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1420567012766	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1420567012767	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous4787829424919036944webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1420567011000,"mt":1420567011000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/FirefoxDeveloperEdition.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"36.0a2","st":1420018877000,"mt":1420016652000}}}
1420567012768	addons.xpi	DEBUG	No changes found
1420567012770	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1420567012771	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1420567012772	addons.manager	DEBUG	Registering shutdown blocker for OpenH264Provider
1420567012772	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
JavaScript error: file:///var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous4787829424919036944webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
*** Blocklist::_preloadBlocklistFile: blocklist is disabled
1420567013812	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	... 19 more
12:57:37.690 WARN - Exception: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
erredSave.extensions.json	DEBUG	Starting write
1420567012457	addons.manager	DEBUG	shutdown
1420567012457	addons.manager	DEBUG	Calling shutdown blocker for XPIProvider
1420567012458	addons.xpi	DEBUG	shutdown
1420567012458	addons.xpi-utils	DEBUG	shutdown
1420567012458	addons.manager	DEBUG	Calling shutdown blocker for LightweightThemeManager
1420567012458	addons.manager	DEBUG	Calling shutdown blocker for OpenH264Provider
1420567012459	addons.manager	DEBUG	Calling shutdown blocker for PluginProvider
1420567012502	DeferredSave.extensions.json	DEBUG	Write succeeded
1420567012503	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 16
1420567012503	addons.xpi	DEBUG	Notifying XPI shutdown observers
1420567012505	addons.manager	DEBUG	Async provider shutdown done
1420567012756	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/addons/XPIProvider.jsm: ["XPIProvider"]
1420567012757	addons.manager	DEBUG	Loaded provider scope for resource://gre/modules/LightweightThemeManager.jsm: ["LightweightThemeManager"]
1420567012760	addons.xpi	DEBUG	startup
1420567012761	addons.xpi	INFO	Mapping fxdriver@googlecode.com to /var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous4787829424919036944webdriver-profile/extensions/fxdriver@googlecode.com
1420567012761	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous4787829424919036944webdriver-profile/extensions/webdriver-staging
1420567012761	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /Applications/FirefoxDeveloperEdition.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
1420567012762	addons.xpi	DEBUG	Skipping unavailable install location app-system-share
1420567012762	addons.xpi	DEBUG	checkForChanges
1420567012763	addons.xpi	DEBUG	Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"/var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous4787829424919036944webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1420567011000,"mt":1420567011000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/FirefoxDeveloperEdition.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"36.0a2","st":1420018877000,"mt":1420016652000}}}
1420567012763	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1420567012766	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1420567012767	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous4787829424919036944webdriver-profile/extensions/fxdriver@googlecode.com","e":true,"v":"2.43.1","st":1420567011000,"mt":1420567011000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/Applications/FirefoxDeveloperEdition.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"36.0a2","st":1420018877000,"mt":1420016652000}}}
1420567012768	addons.xpi	DEBUG	No changes found
1420567012770	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1420567012771	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1420567012772	addons.manager	DEBUG	Registering shutdown blocker for OpenH264Provider
1420567012772	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
JavaScript error: file:///var/folders/_z/8gy7l13n7yx4mdtmz4_xz_j00000gn/T/anonymous4787829424919036944webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]
*** Blocklist::_preloadBlocklistFile: blocklist is disabled
1420567013812	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>

^C%                                                                                                                                                   
➜  mozilla  java -jar selenium-server-standalone-2.43.1.jar
```

**Comment by christian-bromann** [comment]
I just checked the Selenium issue tracker and it is definitely a Selenium issue that already happened multiple times. :-/
