### ISSUE TITLE
Extended debugging over sauce is not working with w3c chrome capabilities

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#3932]
When passing w3c caps to saucelabs for chrome, trying to use extended debugging fails:

invalid argument: unrecognized capability: extendedDebugging
     at getErrorFromResponseBody 

Environment (please complete the following information):

WebdriverIO version: [5.8.1]
Mode: [ WDIO Testrunner]
If WDIO Testrunner, running sync/async: [sync]
Node.js version: [8.10]
NPM version: [6.5.0]
Browser name and version: [chrome latest]
Platform name and version: [osx]
Additional wdio packages used (if applicable): [@wdio/sauce]

**Config of WebdriverIO**
```
{
            browserName: 'googlechrome',
            platformName: 'Windows 10',
            browserVersion: 'latest',
            **extendedDebugging: true,**
            'sauce:options': {
                ...defaultBrowserSauceOptions,
            },
            ...chromeOptions,
        },
```

===
```
   { alwaysMatch: 
      { browserName: 'googlechrome',
        platformName: 'Windows 10',
        browserVersion: 'latest',
        extendedDebugging: true,
        'sauce:options': [Object],
        'goog:chromeOptions': [Object] },
     firstMatch: [ {} ] },
  desiredCapabilities: 
   { browserName: 'googlechrome',
     platformName: 'Windows 10',
     browserVersion: 'latest',
     extendedDebugging: true,
     'sauce:options': { screenResolution: '1600x1200', seleniumVersion: '3.141.59' },
     'goog:chromeOptions': { w3c: true } } }
```
**Describe the bug**
ExtendedDebugging is not working with w3c protocal for chrome over saucelabs:

```
{"value":{"error":"invalid argument","message":"unrecognized capability: extendedDebugging","stacktrace":"Backtrace:\n\tOrdinal0 [0x0114DB63+1432419]\n\tOrdinal0 [0x010C8D81+888193]\n\tOrdinal0 [0x0106B9D1+506321]\n\tOrdinal0 [0x00FF640B+25611]\n\tOrdinal0 [0x0101FC33+195635]\n\tOrdinal0 [0x01020268+197224]\n\tOrdinal0 [0x0102006D+196717]\n\tOrdinal0 [0x0101E8AB+190635]\n\tOrdinal0 [0x01005F16+89878]\n\tOrdinal0 [0x0100757A+95610]\n\tOrdinal0 [0x01007474+95348]\n\tGetHandleVerifier [0x012ADE7C+1274156]\n\tGetHandleVerifier [0x011FB6D9+543113]\n\tGetHandleVerifier [0x011FB4E0+542608]\n\tOrdinal0 [0x0115B508+1488136]\n\tGetHandleVerifier [0x011FBC86+544566]\n\tOrdinal0 [0x010DEEC5+978629]\n\tOrdinal0 [0x010EB35B+1028955]\n\tOrdinal0 [0x010EB49F+1029279]\n\tOrdinal0 [0x010EA445+1025093]\n\tBaseThreadInitThunk [0x75CF38F4+36]\n\tRtlUnicodeStringToInteger [0x77555E13+595]\n\tRtlUnicodeStringToInteger [0x77555DDE+542]\n"}}
```

**To Reproduce**
pass extendedDebugging: true in caps for chrome to sauce labs

**Expected behavior**
extendedDebugging needs to work for w3c chrome over sauce.

**Log**
sauce vm:
https://app.saucelabs.com/tests/122e52b7ca0a4e3381d859ae63bbf5b8

```
2019-05-06T16:48:27.556Z ERROR webdriver: Request failed due to invalid argument: unrecognized capability: extendedDebugging
    at getErrorFromResponseBody (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/webdriver/build/utils.js:349:10)
    at Request._callback (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/pmerwin/Projects/qa/WDIO-5/lib-webdriverio-nodejs-v2/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)

```

**Comment by wswebcreation** [comment]
@pmerwin 

The `extendedDebugging` needs to be part of the `sauce:options`, see [here](https://wiki.saucelabs.com/display/DOCS/Selenium+W3C+Capabilities+Support+-+Beta)

See also this execution https://app.eu-central-1.saucelabs.com/tests/6aae1af48d194defa93f9c3339f1e8b7

**Comment by pmerwin** [comment]
Ooops my bad, yep that works!  Thanks!

**Comment by wswebcreation** [comment]
No problem
