### ISSUE TITLE
Locator Strategy '-ios uiautomation' is not supported for this session

### ISSUE THREAD

**Issue by dsharapkou** [webdriverio/webdriverio#3981]
Hi there!
We have some issue with iOS locator strategy on our project when tried to upgrade to the latest versions of libraries.
We use stack of codeceptjs, webdriver, appium for iOS hybrid testing automation.

Here are dependencies of working tests:
```
"dependencies": {
    "appium": "^1.8.1",
    "codeceptjs": "^1.4.6",
    "selenium-standalone": "^6.15.0",
    "webdriverio": "^4.14.0"
}
```
After we updated all libs to newest versions we've got such error: 
```
I grab number of visible elements "ios=chain=**/XCUIElementTypeStaticText[`name == "dev-testing-client"`]"
2019-05-16T09:35:21.113Z ERROR webdriver: Request failed due to invalid selector: Locator Strategy '-ios uiautomation' is not supported for this session

```
Here are dependencies of updated tests:
```
"dependencies": {
    "appium": "^1.13.0",
    "codeceptjs": "^2.1.2",
    "webdriver": "^5.8.3",
    "selenium-standalone": "^6.15.0",
    "webdriverio": "^5.8.4"
}
```
Here are logs:
```
0|appium   | [HTTP] {"using":"-ios uiautomation","value":"chain=**/XCUIElementTypeStaticText[`name == \"dev-client-automation\"`]"}
0|appium   | [debug] [W3C (3d262bfa)] Calling AppiumDriver.findElements() with args: ["-ios uiautomation","chain=**/XCUIElementTypeStaticText[`name == \"dev-client-automation\"`]","3d262bfa-5afc-44ab-8b4a-e9b00567a97e"]
0|appium   | [debug] [XCUITest] Executing command 'findElements'
0|appium   | [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
0|appium   | [debug] [W3C (3d262bfa)] Encountered internal error running command: InvalidSelectorError: Locator Strategy '-ios uiautomation' is not supported for this session
0|appium   | [debug] [W3C (3d262bfa)]     at XCUITestDriver.validateLocatorStrategy (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:362:13)
0|appium   | [debug] [W3C (3d262bfa)]     at XCUITestDriver.validateLocatorStrategy (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:963:11)
0|appium   | [debug] [W3C (3d262bfa)]     at XCUITestDriver.validateLocatorStrategy [as findElOrElsWithProcessing] (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:32:8)
0|appium   | [debug] [W3C (3d262bfa)]     at XCUITestDriver.findElOrElsWithProcessing [as findElements] (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/commands/find.js:64:21)
0|appium   | [debug] [W3C (3d262bfa)]     at curCommandCancellable._bluebird.default.resolve.then (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:301:66)
0|appium   | [debug] [W3C (3d262bfa)]     at tryCatcher (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/bluebird/js/release/util.js:16:23)
0|appium   | [debug] [W3C (3d262bfa)]     at Promise._settlePromiseFromHandler (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/bluebird/js/release/promise.js:512:31)
0|appium   | [debug] [W3C (3d262bfa)]     at Promise._settlePromise (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/bluebird/js/release/promise.js:569:18)
0|appium   | [debug] [W3C (3d262bfa)]     at Promise._settlePromiseCtx (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/bluebird/js/release/promise.js:606:10)
0|appium   | [debug] [W3C (3d262bfa)]     at _drainQueueStep (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/bluebird/js/release/async.js:142:12)
0|appium   | [debug] [W3C (3d262bfa)]     at _drainQueue (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/bluebird/js/release/async.js:131:9)
0|appium   | [debug] [W3C (3d262bfa)]     at Async._drainQueues (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/bluebird/js/release/async.js:147:5)
0|appium   | [debug] [W3C (3d262bfa)]     at Immediate.Async.drainQueues (/Users/dsharapkou/Documents/workspace/client_testing_automation/node_modules/appium/node_modules/bluebird/js/release/async.js:17:14)
0|appium   | [debug] [W3C (3d262bfa)]     at processImmediate (timers.js:632:19)
0|appium   | [debug] [W3C (3d262bfa)]     at process.topLevelDomainCallback (domain.js:120:23)
```

Maybe you have any idea what's the problem is there?

**Comment by mgrybyk** [comment]
@dsharapkou Looks like you have wrong selector in your code, an example would be helpful.

Please see https://webdriver.io/docs/selectors.html

```
const selector = '**/XCUIElementTypeCell[`name BEGINSWITH "D"`]/**/XCUIElementTypeButton';
const Button = $(`-ios class chain:${selector}`);
Button.click();
```

**Comment by christian-bromann** [comment]
@dsharapkou what are your capabilities? Can you provide more logs?

**Comment by dsharapkou** [comment]
> @dsharapkou Looks like you have wrong selector in your code, an example would be helpful.
> 
> Please see https://webdriver.io/docs/selectors.html
> 
> ```
> const selector = '**/XCUIElementTypeCell[`name BEGINSWITH "D"`]/**/XCUIElementTypeButton';
> const Button = $(`-ios class chain:${selector}`);
> Button.click();
> ```

Here is the function that is called:

```
  async selectCluster(cluster = appium.cluster) {
    const clusterLocator = `ios=chain=**/XCUIElementTypeStaticText[\`name == "${cluster}"\`]`;
    I.switchToNative();
    I.waitForVisible('~Select Workspace', 75);
    I.tap('~Select Workspace');
    let counter = 0;
    while ((await I.grabNumberOfVisibleElements(clusterLocator) === 0) && (counter < 6)) {
      counter += 1;
      I.executeScript(
        'mobile: dragFromToForDuration',
        { duration: 1.0, fromX: 400, fromY: 500, toX: 400, toY: 300 },
      );
    }
    I.tap(clusterLocator);
  },
```

and it fails on `await I.grabNumberOfVisibleElements(clusterLocator)`

**Comment by mgrybyk** [comment]
@dsharapkou  Please update your selector according to doc

**Comment by dsharapkou** [comment]
wow, tried today and changed locators starting from
`ios=chain=`
to `-ios class chain:`
and it works now

thank you!

**Comment by subashinih** [comment]
Hi everyone, I am trying to run a multiremote test with chrome browser and iOS app. When I run the tests, browser is opening and app is being launched. But, when trying to click an element on iOS app, I am seeing TypeError: elem.click is not a function
and for the other option I tried, seeing as invalid argument locator. Please let me know if any inputs on these errors ? Screenshot of code attached. Thanks.
<img width="694" alt="Screen Shot 2021-07-22 at 10 29 56 PM" src="https://user-images.githubusercontent.com/11250574/126742944-749a766d-915d-4cc8-ac78-af1d15f4a56e.png">
