### ISSUE TITLE
Cannot make execute calls from custom client function with single parameter

### ISSUE THREAD

**Issue by dylancwood** [webdriverio/webdriverio#404]
# Summary
The following error will occur if calling a custom command (a method added via client.addCommand) that calls `this.execute`. The error only occurs when calling the custom command with a single input param. Calling the command with two or more input parameters does not result in an error. 
```
RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: customCb is not defined
```

# Discussion
This might be an issue with the `chainit` library, as that is where the function signature in the output below can be found (see `chainit/index.js`, line 124 (https://github.com/vvo/chainit/blob/master/index.js#L124)).

# Test
The following script will replicate the issue quickly. Be sure to have __webdriverio__ installed globally or somewhere that npm can get to it.
```js
/**
 * webdriverio addCommand with single param, and call to this.execute test script
 * This script should replicate an error that occurs when using a custom command that calls
 *   this.execute(), and calling that command with a single input parameter.
 * Calling the command with more than one input parameters fixes the problem
 */
var Webdriverio = require('webdriverio');

var webdriverUrl = 'https://github.com/webdriverio/webdriverio';
var options = {
    desiredCapabilities: {
        browserName: 'firefox'
    }
};

var client = Webdriverio.remote(options);

var browserConditionFunction = function() {
    return window.location.hostname;
};


client.addCommand('customExecute', function(condition, foo) {
    //do nothing with foo
    var self = this;
    var count = 0;
    return self.execute(condition,
        function handleConditionResults(err, ret) {
            if (err) {
                throw err;
            }
            console.log(ret.value);
        }
    );
});
// This fails
client.init()
    .url(webdriverUrl)
    .customExecute(browserConditionFunction)
    .end();
/*
// This works (if the call to waitForCondition above is commented out)
client.init()
    .url(webdriverUrl)
    .customExecute(browserConditionFunction, 'foo')
    .end();
*/
```

### Expected output:
Running the above script results in the following output:

````
17:17:41.937 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
17:17:41.949 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
17:17:51.357 INFO - Done: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]]
17:17:51.373 INFO - Executing: [get: https://github.com/webdriverio/webdriverio])
17:18:07.842 INFO - Done: [get: https://github.com/webdriverio/webdriverio]
17:18:07.851 INFO - Executing: [execute script: return (function () {
          var cbArgs = arguments,
              err = arguments[0];

          if (err instanceof Error && typeof err.addToCallStack === 'function') {
            err.addToCallStack({
              name: fnName,
              args: niceArgs(callArguments)
            });
          } else if (err instanceof Error) {
            err.message = '[' + fnName + niceArgs(callArguments) + '] <= \n ' + err.message;
          }

          if (customCb) {
            customCb.apply(ctx, cbArgs);
          } else if (err instanceof Error) {
            // throw error if it isn't handled by a custom callback
            throw err;
          }

          cb();
        }).apply(null, arguments);, []])
17:18:08.743 WARN - Exception thrown
org.openqa.selenium.WebDriverException: customCb is not defined
Command duration or timeout: 125 milliseconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'harmony.local', ip: '192.168.0.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=35.0.1, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 659fde8d-0c05-c041-a70c-9240f49d3414
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:508)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
	at com.sun.proxy.$Proxy1.executeScript(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.executeScript(EventFiringWebDriver.java:213)
	at org.openqa.selenium.remote.server.handler.ExecuteScript.call(ExecuteScript.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:169)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: customCb is not defined
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'harmony.local', ip: '192.168.0.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_25'
Driver info: driver.version: unknown
	at <anonymous class>.anonymous/<(https://github.com/webdriverio/webdriverio line 68 > Function:14:1)
	at <anonymous class>.anonymous(https://github.com/webdriverio/webdriverio line 68 > Function:1:1)
	at <anonymous class>.handleEvaluateEvent(https://github.com/webdriverio/webdriverio:68:20)
17:18:08.745 WARN - Exception: customCb is not defined
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'harmony.local', ip: '192.168.0.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_25'
Driver info: driver.version: unknown

RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: customCb is not defined
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'harmony.local', ip: '192.168.0.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_25'
Driver info: driver.version: unknown

     Callstack:
     -> execute([Function])
```

Commenting out the first call to `custsomExecute` and uncommenting the second results in the following output:
```
17:15:12.702 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
17:15:12.767 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
17:15:28.279 INFO - Done: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]]
17:15:28.341 INFO - Executing: [get: https://github.com/webdriverio/webdriverio])
17:15:48.163 INFO - Done: [get: https://github.com/webdriverio/webdriverio]
17:15:48.178 INFO - Executing: [execute script: return (function () {
    return window.location.hostname;
}).apply(null, arguments);, []])
17:15:48.219 INFO - Done: [execute script: return (function () {
    return window.location.hostname;
}).apply(null, arguments);, []]
github.com
```

**Comment by christian-bromann** [comment]
@dylancwood great issue report!

The solution is simple: if you create a custom command you need to specify when that command is done. Therefor you will get a callback function as last parameter you need to call once that is the case. So change your code in the following way:

```js
client.addCommand('customExecute', function(condition, foo) {
    //do nothing with foo
    var self = this;
    var count = 0;
    var done = arguments[arguments.length - 1];
    return self.execute(condition,
        function handleConditionResults(err, ret) {
            if (err) {
                throw err;
            }
            console.log(ret.value);
        }
    ).call(done);
});
```

**Comment by dylancwood** [comment]
Thanks for the fast reply!
