### ISSUE TITLE
@wdio/devtools-service: Couldn't connect to chrome: Error: Exactly one of browserWSEndpoint, browserURL or transport must be passed to puppeteer.connect

### ISSUE THREAD

**Issue by smarkows** [webdriverio/webdriverio#4040]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.9.4
 - **Mode:** WDIO TestRunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 74
 - **Platform name and version:** Mac OSX Mojave
 - **Additional wdio packages used (if applicable):** @wdio/devtools-service:5.9.3

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

```
exports.config = {
	port: 9515,
	path: '/',
    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 10,
    capabilities: [{
		browserName: 'chrome',
        chromeOptions: { args: ['remote-debugging-port=9222'] }
    }],
    sync: true,
    logLevel: 'trace',
    logLevels: {
        '@wdio/devtools-service': 'trace'
    },
    baseUrl: 'https://webdriver.io',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['devtools', 'chromedriver'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
}

```

**Describe the bug**
When running the application with the devtools-service and trying to use devtools-service, the functions `browser.getPerformanceMetrics` and `browser.getSpeedIndex` cause an error saying:
```
browser.getPerformanceMetrics is not a function
browser.getSpeedIndex is not a function
```
Additionally (related) in the wdio logs you can see the error (below in logs section).

**To Reproduce**
```
git clone https://github.com/christian-bromann/webdriverio-performance-testing.git 
npm install
npm run test:local
```

**Expected behavior**
The performance testing should complete and the `browser.getPageWeight` function should return values instead of `0` for everything.

**Log**
```
...
2019-05-30T14:13:04.178Z INFO @wdio/devtools-service:DevToolsDriver: Connect to http://localhost:49569
2019-05-30T14:13:04.180Z ERROR @wdio/devtools-service: Couldn't connect to chrome: Error: Exactly one of browserWSEndpoint, browserURL or transport must be passed to puppeteer.connect
    at assert (/Users/smarkowski1/Documents/webdriverio-performance-testing/node_modules/puppeteer-core/lib/helper.js:231:11)
    at Launcher.connect (/Users/smarkowski1/Documents/webdriverio-performance-testing/node_modules/puppeteer-core/lib/Launcher.js:275:5)
    at module.exports.connect (/Users/smarkowski1/Documents/webdriverio-performance-testing/node_modules/puppeteer-core/lib/Puppeteer.js:45:27)
    at Function.attach (/Users/smarkowski1/Documents/webdriverio-performance-testing/node_modules/@wdio/devtools-service/build/driver.js:31:50)
    at DevToolsService.before (/Users/smarkowski1/Documents/webdriverio-performance-testing/node_modules/@wdio/devtools-service/build/index.js:71:51)
...
```

**Comment by smarkows** [comment]
I have traced the issue to the way @wdio/devtools-service calls puppeteer here: https://github.com/webdriverio/webdriverio/blob/5e1fccabc4d2e0b584065ea41ec8d36889876e21/packages/wdio-devtools-service/src/driver.js#L24.

Based on https://pptr.dev/#?product=Puppeteer&version=v1.17.0&show=api-puppeteerconnectoptions, the option needs be converted from:
```
const browser = await puppeteer.connect({
    url,
    defaultViewport: null
})
```
to
```
const browser = await puppeteer.connect({
    browserURL: url,
    defaultViewport: null
})
```

I updated this locally in the package and it corrects the error.
