### ISSUE TITLE
Webdriver: request failed due to missing body

### ISSUE THREAD

**Issue by dherault** [webdriverio/webdriverio#4051]
When using webdriverio with testingbot I get this error : 
```
2019-06-02T16:00:17.482Z INFO webdriver: [POST] http://hub.testingbot.com:80/wd/hub/session
2019-06-02T16:00:17.484Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { browsername: 'chrome',
        platform: 'WIN10',
        version: '74',
        'screen-resolution': '1920x1080',
        name: 'vidiff - Vidiff-demo-website tour',
        screenrecorder: false,
        'selenium-version': '3.14.0' },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { browsername: 'chrome',
     platform: 'WIN10',
     version: '74',
     'screen-resolution': '1920x1080',
     name: 'vidiff - Vidiff-demo-website tour',
     screenrecorder: false,
     'selenium-version': '3.14.0' } }
2019-06-02T16:00:47.958Z DEBUG webdriver: request failed due to missing body
2019-06-02T16:00:47.958Z ERROR webdriver: Request failed due to Error: unknown error
    at getErrorFromResponseBody (C:\Users\dhera\Documents\dev\vidiff\services\node_modules\webdriver\build\utils.js:346:12)
    at Request._callback (C:\Users\dhera\Documents\dev\vidiff\services\node_modules\webdriver\build\request.js:121:64)
    at Request.self.callback (C:\Users\dhera\Documents\dev\vidiff\services\node_modules\request\request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:446:20)
    at Request.<anonymous> (C:\Users\dhera\Documents\dev\vidiff\services\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:197:13)
    at Request.EventEmitter.emit (domain.js:446:20)
    at IncomingMessage.<anonymous> (C:\Users\dhera\Documents\dev\vidiff\services\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
    at IncomingMessage.emit (events.js:202:15)
    at IncomingMessage.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Environment:**
 - **WebdriverIO version:** 5.9.6
 - **Mode:** Standalone mode
 - **Node.js version:** v11.10.0
 - **NPM version:** 6.9.0

I cannot find a fix for it, is it normal ?

**Comment by dherault** [comment]
I fixed it! It seems Testingbot responds an empty body when the capability is not included in the free trial.

**Comment by myfashionhub** [comment]
@dherault Can you elaborate more on how you fixed it? I'm running into the same issue.

**Comment by giri-gonzai** [comment]
Yes, can you please elaborate on how you fixed it??

**Comment by dherault** [comment]
Some capabilities are not included in the free trial.
So before you request them, make sure they are included in it.
The list of included capabilities is not displayed anywhere.

**Comment by shashidharus** [comment]
Could you provide an example?

**Comment by Christopher-Hayes** [comment]
Btw, for anyone that isn't using the free plan and is running into this error. If you copy the `wdio.config.js` file from the WebDriver.io setup guide you will get this error because it changes chromedriver service path:

    path: '/'

That changes the crowserbrowsertesting request to `hub.crossbrowsertesting.com:80/session` when it is expecting `hub.crossbrowsertesting.com:80/wd/hub/session`. So, to fix just comment it and everything should run.

    // path: '/'

**Comment by christian-bromann** [comment]
@Christopher-Hayes with v6 we will set the default value for path to `/`

**Comment by Christopher-Hayes** [comment]
@christian-bromann good to know, thanks.
