### ISSUE TITLE
browser.setWindowSize attempts to call 'setWindowRect' in Edge which is not supported

### ISSUE THREAD

**Issue by raarceoml** [webdriverio/webdriverio#4058]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.9.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15
 - **NPM version:** 5.6
 - **Browser name and version:** Edge 17
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**

```
    before: function (capabilities, specs) {
      // set browser resolution
      browser.setWindowSize(parseInt(resolution.width), parseInt(resolution.height));
    },
```

Saucelabs portion:
```
case 'windows-10-edge' : {
            logger.debug('Adding test run capabilities for Windows 10 - Edge');
            capabilities.push({
              'os': 'Windows',
              'os_version': '10',
              'browser': 'Edge',
              'browser_version': '17.0',
              'resolution': bsDesktopResolution,
              'build': `${winName}_${edgeBrowser}_${this.build}`,
              'project': this.project,

              'browserName': 'MicrosoftEdge',
              'platform': 'Windows 10',
              'version': '17.17134',
              'screenResolution': bsDesktopResolution,
              'name': this.project,
            });
            break;
          }
```

**Describe the bug**
Automation opens connection to BrowserStack on Windows 10 with Edge 17. As part of the setup in the `before` hook, the browser is resized to desired size. Function does not throw exception. 
Edge in BrowserStack responds with unknown command.

**To Reproduce**
Target Browser stack

BrowserStack capabilities:
```
var capabilities = {
	'bstack:options' : {
		'os' : 'Windows',
		'osVersion' : '10',
		'resolution' : '1920x1080',
		'local' : 'false',
		'seleniumVersion' : '3.7.0',
		'userName' : 'XXXX',
		'accessKey' : 'XXXX',
	},
	'browserName' : 'Edge',
	'browserVersion' : '17.0',
}

```

**Expected behavior**
Expect Edge to open in default size and be able to resize to desired size.

**Log**

```
2019-06-05T01:28:46.107Z INFO @wdio/local-runner: Run worker command: run
2019-06-05T01:28:46.487Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "browserstack"
2019-06-05T01:28:46.491Z DEBUG @wdio/local-runner:utils: init remote session
2019-06-05T01:28:46.527Z INFO webdriver: [POST] http://hub-cloud.browserstack.com:80/wd/hub/session
2019-06-05T01:28:46.527Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { os: 'Windows',
        os_version: '10',
        browser: 'Edge',
        browser_version: '17.0',
        resolution: '1920x1080',
        build: 'WIN_ED_20190605_2c954316b5fdef1e0bd68ea17527d76315763131',
        project: 'BrowserStackApplitoolsWDIOV5',
        browserName: 'MicrosoftEdge',
        platform: 'Windows 10',
        version: '17.17134',
        screenResolution: '1920x1080',
        name: 'BrowserStackApplitoolsWDIOV5' },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { os: 'Windows',
     os_version: '10',
     browser: 'Edge',
     browser_version: '17.0',
     resolution: '1920x1080',
     build: 'WIN_ED_20190605_2c954316b5fdef1e0bd68ea17527d76315763131',
     project: 'BrowserStackApplitoolsWDIOV5',
     browserName: 'MicrosoftEdge',
     platform: 'Windows 10',
     version: '17.17134',
     screenResolution: '1920x1080',
     name: 'BrowserStackApplitoolsWDIOV5' } }
2019-06-05T01:28:55.576Z INFO webdriver: COMMAND setWindowRect(null, null, 1920, 1080)
2019-06-05T01:28:55.577Z INFO webdriver: [POST] http://hub-cloud.browserstack.com:80/wd/hub/session/745420193cb0d09d81546bbd88000c5586dd9def/window/rect
2019-06-05T01:28:55.577Z INFO webdriver: DATA { x: null, y: null, width: 1920, height: 1080 }
2019-06-05T01:28:55.749Z INFO @wdio/browserstack-service: MicrosoftEdge 42.17134.1.0 session: https://automate.browserstack.com/builds/e8e1fdb7b4ed606593d4bb90f055d39d5933e510/sessions/745420193cb0d09d81546bbd88000c5586dd9def
2019-06-05T01:28:55.907Z DEBUG webdriver: request failed due to status 9
2019-06-05T01:28:55.907Z WARN webdriver: Request failed due to Unknown command
2019-06-05T01:28:55.907Z INFO webdriver: Retrying 1/3
2019-06-05T01:28:55.907Z INFO webdriver: [POST] http://hub-cloud.browserstack.com:80/wd/hub/session/745420193cb0d09d81546bbd88000c5586dd9def/window/rect
2019-06-05T01:28:55.907Z INFO webdriver: DATA { x: null, y: null, width: 1920, height: 1080 }
2019-06-05T01:28:56.145Z DEBUG webdriver: request failed due to status 9
2019-06-05T01:28:56.145Z WARN webdriver: Request failed due to Unknown command
2019-06-05T01:28:56.145Z INFO webdriver: Retrying 2/3
2019-06-05T01:28:56.145Z INFO webdriver: [POST] http://hub-cloud.browserstack.com:80/wd/hub/session/745420193cb0d09d81546bbd88000c5586dd9def/window/rect
2019-06-05T01:28:56.145Z INFO webdriver: DATA { x: null, y: null, width: 1920, height: 1080 }
2019-06-05T01:28:56.383Z DEBUG webdriver: request failed due to status 9
2019-06-05T01:28:56.384Z WARN webdriver: Request failed due to Unknown command
2019-06-05T01:28:56.384Z INFO webdriver: Retrying 3/3
2019-06-05T01:28:56.384Z INFO webdriver: [POST] http://hub-cloud.browserstack.com:80/wd/hub/session/745420193cb0d09d81546bbd88000c5586dd9def/window/rect
2019-06-05T01:28:56.384Z INFO webdriver: DATA { x: null, y: null, width: 1920, height: 1080 }
2019-06-05T01:28:56.645Z DEBUG webdriver: request failed due to status 9
2019-06-05T01:28:56.646Z ERROR webdriver: Request failed due to Error: Unknown command
    at getErrorFromResponseBody (/opt/atlassian/pipelines/agent/build/node_modules/webdriver/build/utils.js:349:10)
    at Request._callback (/opt/atlassian/pipelines/agent/build/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/opt/atlassian/pipelines/agent/build/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
2019-06-05T01:28:56.647Z ERROR @wdio/sync: Error: Unknown command
    at getErrorFromResponseBody (/opt/atlassian/pipelines/agent/build/node_modules/webdriver/build/utils.js:349:10)
    at Request._callback (/opt/atlassian/pipelines/agent/build/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/opt/atlassian/pipelines/agent/build/node_modules/request/request.js:185:22)
    at Request.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/request/request.js:1161:10)
    at IncomingMessage.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/request/request.js:1083:12)
    at Object.before (/opt/atlassian/pipelines/agent/build/node_modules/@ml-vv-test-framework-core/core/lib/wdio.conf.js:227:13)
```

**Comment by wswebcreation** [comment]
@raarceoml 

You are using the JSONWP command, I don't know why it is not ported correctly by WDIO / why Edge driver is not handeling this correct, but when you run is like this 

```js
// See https://webdriver.io/docs/api/webdriver.html#setwindowrect
// and see https://w3c.github.io/webdriver/#dfn-set-window-rect
browser.setWindowRect(0, 0, 1366, 768);
```

it should work, see also this

https://app.eu-central-1.saucelabs.com/tests/ed87b3f432d043f8aa50f04782b61845

**Comment by wswebcreation** [comment]
@christian-bromann 

When I provide `null` for `x` and `y` I get this error in the logs, according to our docs it should work, is this a Edge driver issue? If so then @raarceoml should use the above mentioned workaround

```log
[0-0] 2019-06-06T06:02:43.903Z INFO webdriver: DATA { x: null, y: null, width: 1366, height: 768 }
[0-0] 2019-06-06T06:02:43.963Z DEBUG webdriver: request failed due to status 13
[0-0] 2019-06-06T06:02:43.963Z ERROR webdriver: Request failed due to unknown error: null value in entry: x=null
    at getErrorFromResponseBody (/Users/wimselles/Git/sample-app-web-jenkins/node_modules/webdriver/build/utils.js:349:10)
    at Request._callback (/Users/wimselles/Git/sample-app-web-jenkins/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/Users/wimselles/Git/sample-app-web-jenkins/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/wimselles/Git/sample-app-web-jenkins/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/wimselles/Git/sample-app-web-jenkins/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
```

**Comment by christian-bromann** [comment]
@wswebcreation it was set in this PR #3216, according to the [spec](https://w3c.github.io/webdriver/#dfn-set-window-rect) it should be possible to set `null`:

    Let x be the result of getting a property named x from the parameters argument, else let it be null.
    
    Let y be the result of getting a property named y from the parameters argument, else let it be null.

**Comment by wswebcreation** [comment]
@christian-bromann 

May we draw the conclusion that this is a driver issue then? Or should we fix this by setting the default to 0,0 and not `null, null`?

**Comment by christian-bromann** [comment]
> May we draw the conclusion that this is a driver issue then?

I would say so. I think setting `x` and `y` properties to `0` doesn't hurt the user. PRs welcome.

**Comment by raarceoml** [comment]
The function exposed to the user does not support passing a value to `x` and `y`

https://webdriver.io/docs/api/browser/setWindowSize.html
https://github.com/webdriverio/webdriverio/blob/c48a433cec39e9c688941bf22d214e36706b4697/packages/webdriverio/src/commands/browser/setWindowSize.js#L22

```
export default function setWindowSize(width, height) {
... 
```

**Comment by christian-bromann** [comment]
> The function exposed to the user does not support passing a value to `x` and `y`

Yes, because the command is not suppose to change the x and y position of the window.

**Comment by lukaszfryc** [comment]
I'm having an issue resizing Edge 18 on LambdaTest. About 50% of time, the browser window is not resized. I'm using: `browser.setWindowSize(1440, 900);`

Is there a way to fix it?

**Comment by christian-bromann** [comment]
> Is there a way to fix it?

This is most likely a driver issue and needs to be reported in the Edgedriver project.

**Comment by christian-bromann** [comment]
Closing as this seems to be an issue with Edgedriver that can't be fixed in the WebdriverIO project.
