### ISSUE TITLE
Object #<Object> has no method 'readdirSync'

### ISSUE THREAD

**Issue by lwhorton** [webdriverio/webdriverio#407]
Perhaps I'm just being stupid, but I don't understand why I'm getting this error when trying to `require('webdriverio')`. I have tried running the tests via Mocha and Node directly, but it always barks at me with that error... here's a skeleton of the spec I'm trying to run.

```javascript
    beforeEach(function () {
        var webdriver = require('webdriverio')
            , opts = {
                desiredCapabilities: {
                    browserName: 'chrome'
                }
            }
        sut = require('./sign-in-page-model.js')(webdriver, opts)
        sut = new sut()
        return sut.start()
    })
```

Is `webdriverio` not registered under that npm module name? I have tried installing it globally, as well as with just a devDependency. Digging into the source, I see that the error comes from `fs.readdirSync` inside the buildPrototype/extendProto function, and it's almost like `require('fs')` isn't returning the standard node module? Any thoughts?

**Comment by christian-bromann** [comment]
Could you provide the whole stack trace and that part of `sign-in-page-model.js` that creates the instance via `remote`?

**Comment by christian-bromann** [comment]
FYI WebdriverIO has a [boilerplate project](https://github.com/webdriverio/cucumber-boilerplate)(using WebdriverIO + Cucumber + Mocha) that helps you getting started quickly. If you don't mind using Cucumber, give it a try ;-)

**Comment by lwhorton** [comment]
Here is the simple PageModel object:

```javascript
'use strict';

module.exports = SignInPageModel

function SignInPageModel(webdriver, opts) {
    console.log('constructed')
    this.client = webdriver.remote(opts)
}
SignInPageModel.prototype.start = function () {
    return this.client.init()
        .then(function (it) { <-- not yet sure if promises are supported off init
            this.client = it
            return this
        })
}
```

And this is the stack:
```
  SignIn Smoke
    when signing in
      given valid credentials
        1) "before each" hook


  0 passing (18ms)
  1 failing

  1) SignIn Smoke "before each" hook:
     TypeError: Object #<Object> has no method 'readdirSync'
      at extendProto (/Users/lwhorton/dev/work/ensign/build/tests/smokes.js:33194:10)
      at Array.reduce (native)
      at buildPrototype (/Users/lwhorton/dev/work/ensign/build/tests/smokes.js:33186:17)
      at Object.<anonymous> (/Users/lwhorton/dev/work/ensign/build/tests/smokes.js:33283:1)
      at Object../helpers/isMobile (/Users/lwhorton/dev/work/ensign/build/tests/smokes.js:33389:4)
      at s (/Users/lwhorton/dev/work/ensign/build/tests/smokes.js:1:316)
      at /Users/lwhorton/dev/work/ensign/build/tests/smokes.js:1:367
      at Object../lib/utils/ErrorHandler (/Users/lwhorton/dev/work/ensign/build/tests/smokes.js:32270:19)
      at s (/Users/lwhorton/dev/work/ensign/build/tests/smokes.js:1:316)
      at /Users/lwhorton/dev/work/ensign/build/tests/smokes.js:1:367
      at Context.<anonymous> (/Users/lwhorton/dev/work/ensign/build/tests/smokes.js:26:25)
      at callFn (/Users/lwhorton/.nvm/v0.10.32/lib/node_modules/mocha/lib/runnable.js:251:21)
      at Hook.Runnable.run (/Users/lwhorton/.nvm/v0.10.32/lib/node_modules/mocha/lib/runnable.js:244:7)
      at next (/Users/lwhorton/.nvm/v0.10.32/lib/node_modules/mocha/lib/runner.js:259:10)
      at Object._onImmediate (/Users/lwhorton/.nvm/v0.10.32/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by christian-bromann** [comment]
What is `smoke.js` doing?

**Comment by lwhorton** [comment]
Aha. I was being stupid. It was a concat file that pulled in all my necessary spec support, but there was some unnecessary/broken cruft. Error on my end, thanks for the help @christian-bromann.

**Comment by christian-bromann** [comment]
:+1:
