### ISSUE TITLE
Client Object has no method 'addCommand'

### ISSUE THREAD

**Issue by iwanjunaid** [webdriverio/webdriverio#412]
I try to create custom command

```javascript
var client = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'firefox'
    }
};

client.addCommand('counting', function(num, cb) {
    for (i = 0; i < num; i++)
        console.log(num);

    cb(null);
});

client
    .remote(options)
    .init()
    .url('http://www.google.com')
    .windowHandleMaximize('current')
    .title(function(err, res) {
        console.log('Title was: ' + res.value);
    })
    .end();
```

but got following error

```javascript
client.addCommand('counting', function(num, cb) {
       ^
TypeError: Object #<Object> has no method 'addCommand'
    at Object.<anonymous> (/home/iwan/dev/project/webdriver-io/app.js:8:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by christian-bromann** [comment]
Hi @iwanjunaid 

you need to initialise your client object first by calling the `remote` method. Try

```js
var options = {
    desiredCapabilities: {
        browserName: 'firefox'
    }
};
var client = require('webdriverio').remote(options);

client.addCommand('counting', function(num, cb) {
    for (i = 0; i < num; i++)
        console.log(num);

    cb(null);
});

client
    .init()
    .url('http://www.google.com')
    .windowHandleMaximize('current')
    .title(function(err, res) {
        console.log('Title was: ' + res.value);
    })
    .end();
```

**Comment by iwanjunaid** [comment]
thank you
