### ISSUE TITLE
switchToWindow() throws error using Chrome and npx

### ISSUE THREAD

**Issue by snfinnegan** [webdriverio/webdriverio#4187]
I found that when I tried to use browser.switchToWindow() I was always getting the following error `'handle' must be a string` when using Chrome. I didn't get it with Firefox. It works as expected
I looked into it further and also got it with browser.newWindow() or browser.switchWindow() which both in turn call browser.switchToWindow().
So I can distill getting the error with the following lines

`browser.url('https://google.com')`
`browser.newWindow('http://www.bbc.com')`

I further found that if I ran my test using `npm test` instead of `npx` I nolonger got the error. 

**Environment (please complete the following information):**
 - "webdriverio": "^5.10.7" & v5.11.4
 - **Mode:** [Standalone mode or WDIO Testrunner] I cloned an existing project. How do I find out?
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] I cloned an existing project. How do I find out?
 - **Node.js version:**v12.2.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome Version 75.0.3770.100 (Official Build) (64-bit)
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

Error detail
 invalid argument: 'handle' must be a string(Session infochrome=75.0.3770.100)
[chrome 75.0.3770.100 Windows NT #0-0]     at getErrorFromResponseBody (C:\artisan\qa-front-ui\node_modules\webdriver\build\utils.js:371:10)

**Comment by christian-bromann** [comment]
@snfinnegan please provide WebdriverIO as well as driver logs!

**Comment by snfinnegan** [comment]
> @snfinnegan please provide WebdriverIO as well as driver logs!
@christian-bromann 
Are you looking for the WebdriverIO version? - I've reproduced with both v5.10.7 & v5.11.4
Which log can I provide you with? I've attached a json file (changed file ending to .txt to attach) from the reports folder. Is the stacktrace what you're after?

```[chrome 75.0.3770.100 Windows NT #0-0] 'handle' must be a string(Session infochrome=75.0.3770.100)
[chrome 75.0.3770.100 Windows NT #0-0] invalid argument: 'handle' must be a string(Session infochrome=75.0.3770.100)
[chrome 75.0.3770.100 Windows NT #0-0]     at getErrorFromResponseBody (C:\artisan\qa-front-ui\node_modules\webdriver\build\utils.js:371:10)
[chrome 75.0.3770.100 Windows NT #0-0]     at Request._callback (C:\artisan\qa-front-ui\node_modules\webdriver\build\request.js:122:64)
[chrome 75.0.3770.100 Windows NT #0-0]     at Request.self.callback (C:\artisan\qa-front-ui\node_modules\request\request.js:185:22)
[chrome 75.0.3770.100 Windows NT #0-0]     at Request.<anonymous> (C:\artisan\qa-front-ui\node_modules\request\request.js:1161:10)
[chrome 75.0.3770.100 Windows NT #0-0]     at IncomingMessage.<anonymous> (C:\artisan\qa-front-ui\node_modules\request\request.js:1083:12)
[chrome 75.0.3770.100 Windows NT #0-0] Error:
[chrome 75.0.3770.100 Windows NT #0-0]     at Browser.runCommand (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\wrapCommand.js:31:24)
[chrome 75.0.3770.100 Windows NT #0-0]     at Browser.<anonymous> (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\wrapCommand.js:53:31)
[chrome 75.0.3770.100 Windows NT #0-0]     at Browser.newWindow (C:\artisan\qa-front-ui\node_modules\webdriverio\build\commands\browser\newWindow.js:61:14)
[chrome 75.0.3770.100 Windows NT #0-0]     at processTicksAndRejections (internal/process/task_queues.js:89:5)
[chrome 75.0.3770.100 Windows NT #0-0]     at Browser.runCommand (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\wrapCommand.js:37:23)
[chrome 75.0.3770.100 Windows NT #0-0]     at Context.newWindow (C:\artisan\qa-front-ui\test\specs\learner/google.test.js:4:13)
[chrome 75.0.3770.100 Windows NT #0-0]     at C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\index.js:65:22
[chrome 75.0.3770.100 Windows NT #0-0]     at Context.executeSync (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\index.js:63:10)
[chrome 75.0.3770.100 Windows NT #0-0]     at C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\index.js:209:70```

[results-0-0.[object Object].txt](https://github.com/webdriverio/webdriverio/files/3391696/results-0-0.object.Object.txt)

**Comment by christian-bromann** [comment]
@snfinnegan can you provide the whole logs and not only the stack trace? Also it would be helpful if you could share the test code that is failing!

**Comment by snfinnegan** [comment]
@christian-bromann 
```describe('Basic Learner Login', () => {
  it('should display the login page title', async () => {
    browser.url('https://google.com')
    browser.newWindow('http://www.bbc.com')    
  })
  it('should display the login page title', async () => {
    browser.pause(5000)
  })
})```

Browser.newWindow() above is enough to trigger the error. Or any method that in turn calls switchToWindow() e.g. switchWindow() or switchToWindow() 

Hopefully this below covers the logging you are looking for 

```C:\artisan\qa-front-ui>npx wdio ./config-wdio/local.js --spec google.test
WARNING: NODE_ENV value of 'test' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode

Execution of 1 spec files started at 2019-07-15T09:22:48.744Z

2019-07-15T09:22:48.746Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
2019-07-15T09:22:49.073Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-07-15T09:22:51.542Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./config-wdio/local.js,--spec,google.test
[0-0] RUNNING in chrome - C:\artisan\qa-front-ui\test\specs\learner\google.test.js
[0-0] 2019-07-15T09:22:52.120Z INFO @wdio/local-runner: Run worker command: run
[0-0] WARNING: NODE_ENV value of 'test' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
[0-0] 2019-07-15T09:22:52.183Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
[0-0] 2019-07-15T09:22:52.314Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2019-07-15T09:22:52.940Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-07-15T09:22:52.940Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': { w3c: true } }
}
[0-0] 2019-07-15T09:22:58.192Z INFO webdriver: COMMAND _setWindowSize(1366, 768)
[0-0] 2019-07-15T09:22:58.193Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/window/current/size
2019-07-15T09:22:58.193Z INFO webdriver: DATA { width: 1366, height: 768 }
[0-0] 2019-07-15T09:23:01.975Z INFO webdriver: COMMAND navigateTo("https://google.com/")
[0-0] 2019-07-15T09:23:01.975Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/url
2019-07-15T09:23:01.976Z INFO webdriver: DATA { url: 'https://google.com/' }
[0-0] 2019-07-15T09:23:02.617Z INFO webdriver: COMMAND executeScript("return (function newWindow(url, windowName = 'new window', windowFeatures = '') {
  window.open(url, windowName, windowFeatures);
}).apply(null, arguments)", <object>)
[0-0] 2019-07-15T09:23:02.618Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/execute
2019-07-15T09:23:02.618Z INFO webdriver: DATA {
  script: "return (function newWindow(url, windowName = 'new " +
    "window', windowFeatures = '') {\n  window.open(url, " +
    'windowName, windowFeatures);\n}).apply(null, ' +
    'arguments)',
  args: [ 'http://www.bbc.com', 'New Window', '' ]
}
[0-0] 2019-07-15T09:23:02.719Z INFO webdriver: COMMAND getWindowHandles()
[0-0] 2019-07-15T09:23:02.720Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/window_handles
[0-0] 2019-07-15T09:23:02.740Z INFO webdriver: RESULT [
  'CDwindow-AD8550F4DB5C82D667783F56998406F4',
  'CDwindow-11508209B48228CF682122A101BEEAE2'
]
[0-0] 2019-07-15T09:23:02.742Z INFO webdriver: COMMAND switchToWindow("CDwindow-11508209B48228CF682122A101BEEAE2")
2019-07-15T09:23:02.743Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/window
2019-07-15T09:23:02.744Z INFO webdriver: DATA { name: 'CDwindow-11508209B48228CF682122A101BEEAE2' }
[0-0] 2019-07-15T09:23:02.770Z WARN webdriver: Request failed due to 'handle' must be a string(Session infochrome=75.0.3770.100)
[0-0] 2019-07-15T09:23:02.769Z DEBUG webdriver: request failed due to response error: invalid argument
2019-07-15T09:23:02.770Z INFO webdriver: Retrying 1/5
2019-07-15T09:23:02.770Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/window
2019-07-15T09:23:02.771Z INFO webdriver: DATA { name: 'CDwindow-11508209B48228CF682122A101BEEAE2' }
[0-0] 2019-07-15T09:23:02.784Z WARN webdriver: Request failed due to 'handle' must be a string(Session infochrome=75.0.3770.100)
[0-0] 2019-07-15T09:23:02.784Z DEBUG webdriver: request failed due to response error: invalid argument
2019-07-15T09:23:02.785Z INFO webdriver: Retrying 2/5
2019-07-15T09:23:02.786Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/window
2019-07-15T09:23:02.787Z INFO webdriver: DATA { name: 'CDwindow-11508209B48228CF682122A101BEEAE2' }
2019-07-15T09:23:02.807Z DEBUG webdriver: request failed due to response error: invalid argument
2019-07-15T09:23:02.809Z INFO webdriver: Retrying 3/5
2019-07-15T09:23:02.809Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/window
2019-07-15T09:23:02.810Z INFO webdriver: DATA { name: 'CDwindow-11508209B48228CF682122A101BEEAE2' }
[0-0] 2019-07-15T09:23:02.808Z WARN webdriver: Request failed due to 'handle' must be a string(Session infochrome=75.0.3770.100)
[0-0] 2019-07-15T09:23:02.824Z DEBUG webdriver: request failed due to response error: invalid argument
[0-0] 2019-07-15T09:23:02.825Z WARN webdriver: Request failed due to 'handle' must be a string(Session infochrome=75.0.3770.100)
[0-0] 2019-07-15T09:23:02.825Z INFO webdriver: Retrying 4/5
2019-07-15T09:23:02.826Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/window
2019-07-15T09:23:02.826Z INFO webdriver: DATA { name: 'CDwindow-11508209B48228CF682122A101BEEAE2' }
2019-07-15T09:23:02.862Z DEBUG webdriver: request failed due to response error: invalid argument
2019-07-15T09:23:02.865Z INFO webdriver: Retrying 5/5
2019-07-15T09:23:02.865Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/window
2019-07-15T09:23:02.866Z INFO webdriver: DATA { name: 'CDwindow-11508209B48228CF682122A101BEEAE2' }
[0-0] 2019-07-15T09:23:02.863Z WARN webdriver: Request failed due to 'handle' must be a string(Session infochrome=75.0.3770.100)
[0-0] 2019-07-15T09:23:02.882Z DEBUG webdriver: request failed due to response error: invalid argument
[0-0] 2019-07-15T09:23:02.883Z ERROR webdriver: Request failed due to invalid argument: 'handle' must be a string(Session infochrome=75.0.3770.100)
    at getErrorFromResponseBody (C:\artisan\qa-front-ui\node_modules\webdriver\build\utils.js:371:10)
    at Request._callback (C:\artisan\qa-front-ui\node_modules\webdriver\build\request.js:122:64)
    at Request.self.callback (C:\artisan\qa-front-ui\node_modules\request\request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (C:\artisan\qa-front-ui\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:196:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (C:\artisan\qa-front-ui\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:284:20)
[0-0] invalid argument in "Basic Learner Login should display the login page title"
'handle' must be a string(Session infochrome=75.0.3770.100)
[0-0] 2019-07-15T09:23:02.938Z INFO webdriver: COMMAND takeScreenshot()
2019-07-15T09:23:02.941Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f/screenshot
[0-0] 2019-07-15T09:23:03.460Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAABUYAAAJ8CAYAAAAyB3skAAAAAXNSR0IArs4c6...
[0-0] 2019-07-15T09:23:03.469Z ERROR @wdio/sync: TypeError: this.context.push is not a function
    at module.exports.addScreenshotContext (C:\artisan\qa-front-ui\node_modules\wdio-mochawesome-reporter\src\test.js:70:22)
    at WdioMochawesomeReporter.onAfterCommand (C:\artisan\qa-front-ui\node_modules\wdio-mochawesome-reporter\src\index.js:42:27)
    at C:\artisan\qa-front-ui\node_modules\@wdio\runner\build\reporter.js:61:49
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (C:\artisan\qa-front-ui\node_modules\@wdio\runner\build\reporter.js:61:20)
    at EventEmitter.<anonymous> (C:\artisan\qa-front-ui\node_modules\@wdio\runner\build\index.js:235:50)
    at Browser.runCommand (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\wrapCommand.js:31:24)
    at Browser.<anonymous> (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\wrapCommand.js:53:31)
    at Browser.saveScreenshot (C:\artisan\qa-front-ui\node_modules\webdriverio\build\commands\browser\saveScreenshot.js:45:35)
    at Browser.runCommand (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\wrapCommand.js:37:32)
    at Object.afterTest (C:\artisan\qa-front-ui\config-wdio\base.js:227:17)
    at execHook (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\executeHooksWithArgs.js:46:23)
[0-0] 2019-07-15T09:23:08.475Z INFO webdriver: COMMAND deleteSession()
[0-0] 2019-07-15T09:23:08.476Z INFO webdriver: [DELETE] http://127.0.0.1:4444/wd/hub/session/0b4ede67077860c0d4a70bb1b1d3366f
2019-07-15T09:23:08.925Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - C:\artisan\qa-front-ui\test\specs\learner\google.test.js
2019-07-15T09:23:08.932Z INFO @wdio/cli:Launcher: Run onComplete hook
2019-07-15T09:23:08.933Z INFO @wdio/selenium-standalone-service: shutting down all browsers

 "spec" Reporter:
------------------------------------------------------------------
[chrome 75.0.3770.100 Windows NT #0-0] Spec: C:\artisan\qa-front-ui\test\specs\learner\google.test.js
[chrome 75.0.3770.100 Windows NT #0-0] Running: chrome (v75.0.3770.100) on Windows NT
[chrome 75.0.3770.100 Windows NT #0-0]
[chrome 75.0.3770.100 Windows NT #0-0] Basic Learner Login
[chrome 75.0.3770.100 Windows NT #0-0]    ✖ should display the login page title
[chrome 75.0.3770.100 Windows NT #0-0]    ✓ should display the login page title
[chrome 75.0.3770.100 Windows NT #0-0]
[chrome 75.0.3770.100 Windows NT #0-0] 1 passing (10.6s)
[chrome 75.0.3770.100 Windows NT #0-0] 1 failing
[chrome 75.0.3770.100 Windows NT #0-0]
[chrome 75.0.3770.100 Windows NT #0-0] 1) Basic Learner Login should display the login page title
[chrome 75.0.3770.100 Windows NT #0-0] 'handle' must be a string(Session infochrome=75.0.3770.100)
[chrome 75.0.3770.100 Windows NT #0-0] invalid argument: 'handle' must be a string(Session infochrome=75.0.3770.100)
[chrome 75.0.3770.100 Windows NT #0-0]     at getErrorFromResponseBody (C:\artisan\qa-front-ui\node_modules\webdriver\build\utils.js:371:10)
[chrome 75.0.3770.100 Windows NT #0-0]     at Request._callback (C:\artisan\qa-front-ui\node_modules\webdriver\build\request.js:122:64)
[chrome 75.0.3770.100 Windows NT #0-0]     at Request.self.callback (C:\artisan\qa-front-ui\node_modules\request\request.js:185:22)
[chrome 75.0.3770.100 Windows NT #0-0]     at Request.<anonymous> (C:\artisan\qa-front-ui\node_modules\request\request.js:1161:10)
[chrome 75.0.3770.100 Windows NT #0-0]     at IncomingMessage.<anonymous> (C:\artisan\qa-front-ui\node_modules\request\request.js:1083:12)
[chrome 75.0.3770.100 Windows NT #0-0] Error:
[chrome 75.0.3770.100 Windows NT #0-0]     at Browser.runCommand (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\wrapCommand.js:31:24)
[chrome 75.0.3770.100 Windows NT #0-0]     at Browser.<anonymous> (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\wrapCommand.js:53:31)
[chrome 75.0.3770.100 Windows NT #0-0]     at Browser.newWindow (C:\artisan\qa-front-ui\node_modules\webdriverio\build\commands\browser\newWindow.js:61:14)
[chrome 75.0.3770.100 Windows NT #0-0]     at processTicksAndRejections (internal/process/task_queues.js:89:5)
[chrome 75.0.3770.100 Windows NT #0-0]     at Browser.runCommand (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\wrapCommand.js:37:23)
[chrome 75.0.3770.100 Windows NT #0-0]     at Context.newWindow (C:\artisan\qa-front-ui\test\specs\learner/google.test.js:4:13)
[chrome 75.0.3770.100 Windows NT #0-0]     at C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\index.js:65:22
[chrome 75.0.3770.100 Windows NT #0-0]     at Context.executeSync (C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\index.js:63:10)
[chrome 75.0.3770.100 Windows NT #0-0]     at C:\artisan\qa-front-ui\node_modules\@wdio\sync\build\index.js:209:70


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:20```

**Comment by nextlevelbeard** [comment]
@snfinnegan Try to remove the `w3c: true`  in your goog:chromeOptions.
This is a bug with latest chrome. It now supports the W3C spec by default and there is no need to pass that option. If it is passed, this bug occurs.

Removing that option fixed it for me.

**Comment by snfinnegan** [comment]
Thanks @nextlevelbeard. I can confirm removing the `w3c: true` worked.

**Comment by plffy** [comment]
> @snfinnegan Try to remove the `w3c: true` in your goog:chromeOptions.
> This is a bug with latest chrome. It now supports the W3C spec by default and there is no need to pass that option. If it is passed, this bug occurs.
> 
> Removing that option fixed it for me.

How can we remove `w3c: true`? In my project I did not set the goog:chromeOptions explicitly but I am also getting this error on .switchToWindow().

**Comment by SagarOnline** [comment]
Thanks @nextlevelbeard  . Disabling w3c dialect (`w3c : false`) also worked for me. I would like to share the java code to disable w3c dialect.

`ChromeOptions options = new ChromeOptions();`
`options.setExperimentalOption("w3c", false);`
`DesiredCapabilities capability = DesiredCapabilities.chrome();`
`capability.setCapability(ChromeOptions.CAPABILITY, options);`
`.....`
`.....`

**Comment by aamee** [comment]
I am still Facing this issue.
Caused by: org.openqa.selenium.InvalidArgumentException: invalid argument: 'handle' must be a string
  (Session info: chrome=86.0.4240.111)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'AZAPSEAUTOP48', ip: '10.174.37.141', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_212'
Driver info: driver.version: unknown
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'PENNBCORP428', ip: '10.112.243.138', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_212'
Driver info: driver.version: unknown
I am using remoteWebDriver for executing test

**Comment by wilmargutierrez** [comment]
My regression tests were working fine on BrowserStack with Chrome v80.0. But then I had this crazy idea of upgrading the Chrome version to something more up-to-date (current version is number 86). Then I was faced with this error, which I couldn't reproduce with Chrome via custom driver nor Firefox via both driver alternatives. Adding the Chrome option has indeed solved the problem for me:

```
options.setCapability("browser_version", "84.0"); // just a precaution from my side (don't like using the latest version on BS).
options.setExperimentalOption("w3c", false);
```

Thanks a lot!

**Comment by PranavHanwante** [comment]
Actually i am using selenide so how do i add .setExperimentalOption("w3c", false); ?

**Comment by cameronscottseequent** [comment]
Just for anyone still having this issuse in 2022. The response here fixed my issue, but it took a while to figure out exactly WHERE to put this setting

explicitly specifying `chromeOptions: { w3c: false }` in desired capabilities / capabilities fixed this issue for me

`test_settings: {
        default: {
            launch_url: 'http://localhost',
            selenium_port: 4444,
            selenium_host: 'localhost',
            silent: true,
            live_output: true,
            persist_globals: true,
            screenshots: {
                enabled: true,
                path: './screenshots',
                on_failure: true,
                on_error: true,
            },
            desiredCapabilities: {
                ...CHROME_CONFIG.desiredCapabilities,
                marionette: true,
                chromeOptions: {
                    w3c: false
                }
            },
            globals: {
                waitForConditionTimeout: 20000,
            },
            end_session_on_fail: false,
            skip_testcases_on_fail: false,
        },
        chrome: CHROME_CONFIG,
        firefox: FIREFOX_CONFIG,
        edge: EDGE_CONFIG,
        safari: SAFARI_CONFIG,
    },` inside `nightwatch.conf.js
    
chromedriver: 97
selenium 4.0.0
