### ISSUE TITLE
devtools-service: UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'cancel' of undefined

### ISSUE THREAD

**Issue by Carn1val** [webdriverio/webdriverio#4203]
**Environment :**
 - **WebdriverIO version:** 5.11.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 75.0.3770.100
 - **Platform name and version:** Ubuntu 19.04
 - **Additional wdio packages used:** @wdio/devtools-service

**Config of WebdriverIO**
Part with devtools service : 
`services: ['chromedriver', 'devtools']`

**Describe the bug**
Deprecation error with devtools in services. 

[0-0] (node:6196) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'cancel' of undefined
    at TraceGatherer.onFrameNavigated (/home/user/workspace/project/node_modules/@wdio/devtools-service/build/gatherer/trace.js:102:36)
    at CDPSession.emit (events.js:203:13)
    at CDPSession.EventEmitter.emit (domain.js:471:20)
    at CDPSession._onMessage (/home/user/workspace/project/node_modules/puppeteer-core/lib/Connection.js:200:12)
    at Connection._onMessage (/home/user/workspace/project/node_modules/puppeteer-core/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/home/user/workspace/project/node_modules/puppeteer-core/lib/WebSocketTransport.js:41:24)
    at WebSocket.onMessage (/home/user/workspace/project/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:203:13)
    at WebSocket.EventEmitter.emit (domain.js:471:20)
    at Receiver.receiverOnMessage (/home/user/workspace/project/node_modules/ws/lib/websocket.js:789:20)
[0-0] (node:6196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**To Reproduce**
- Add devtools to services in wdio.conf.js
- Add @wdio/devtools-service and install packages
- Open any website with response errors in multiple tests with delay.
- Last test must have some delay

It worked well without warning with wdio version 5.9.4. I don't change anything else except wdio packages version.

**Comment by christian-bromann** [comment]
Can you provide a reproducible example?

**Comment by Carn1val** [comment]
To reproduce with my example: 
1) clone https://github.com/Carn1val/bug_4203
2) yarn install
3) ./run.sh

Conditions: 
1) Add devtools to services in wdio.conf.js
2) Add @wdio/devtools-service and install packages
3) Open any website with response errors in multiple tests with delay. 
4) Second test must have some delay 

![Screenshot from 2019-07-16 17-27-00](https://user-images.githubusercontent.com/11799985/61302766-05edbe80-a7ef-11e9-9a63-18688f6c33be.png)

**Comment by Raulster24** [comment]
I think a reproducible example is now given, can we remove the label.

**Comment by mgrybyk** [comment]
Closing according to https://github.com/webdriverio/webdriverio/pull/4296
