### ISSUE TITLE
Getting 'There is not device that matches your criteria' when running on Saucelabs

### ISSUE THREAD

**Issue by jaFerrazza** [webdriverio/webdriverio#4209]
**Environment:**
 - **WebdriverIO version:** [e.g. 5.10.9]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** [e.g. 8.12.0]
 - **NPM version:** [e.g. 6.4.1]
 - **Platform name and version:** Mac OS
 - **Additional wdio packages used (if applicable):** 
  "@wdio/appium-service": "^5.0.0",
    "@wdio/cli": "^5.10.9",
    "@wdio/local-runner": "^5.10.9",
    "@wdio/sauce-service": "^5.11.1",
    "@wdio/spec-reporter": "^5.9.3",
    "@wdio/sync": "^5.10.8",

**Additional context**
I followed the boiler plate tutorial, set up my keys and everything on my config file, but I'm getting the following error:

```
[0-0] 2019-07-16T23:37:27.159Z ERROR webdriver: Request failed due to Error: There is no device that matches your criteria. DesiredCapabilities: {deviceName=Google_Pixel_2_XL_real_us, platformVersion=9, platformName=Android, automationName=UiAutomator2, testobject_app_id=2.0, testobject_api_key=7705823380DB4C4793087180776C3F1E, testobject_test_name=Default Appium Test, appiumVersion=1.13.0, testobject_device=Google_Pixel_2_XL_real_us, testobject_appium_version=1.13.0, testobject_platform_name=Android}
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Sauce Labs RDC', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-119-generic', java.version: '1.8.0_191'
Driver info: driver.version: unknown
    at getErrorFromResponseBody (/Users/jacopoferrazzagbh/Desktop/qa-appium/node_modules/webdriver/build/utils.js:351:10)
    at Request._callback (/Users/jacopoferrazzagbh/Desktop/qa-appium/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/Users/jacopoferrazzagbh/Desktop/qa-appium/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/jacopoferrazzagbh/Desktop/qa-appium/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/jacopoferrazzagbh/Desktop/qa-appium/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
```

Config file:
```
const defaults = require("./wdio-android.config.js");


defaults.specs = [
    'tests/**/LoginSuccessful.js'
],

defaults.capabilities = [{
    deviceName: 'Google_Pixel_2_XL_real_us', //Name of the device or emulator
    platformVersion: '9', 
    platformName: 'Android',
    automationName: 'UiAutomator2',
    testobject_app_id: 2,
    testobject_api_key: 'my API key',
    testobject_test_name: 'Default Appium Test'
}],
defaults.services = ['sauce']


delete defaults.port;

exports.config = defaults;
```

**Comment by christian-bromann** [comment]
> Request failed due to Error: There is no device that matches your criteria. DesiredCapabilities: {deviceName=Google_Pixel_2_XL_real_us

This is not a problem in WebdriverIO. It tried to request the session given the capabilities but was unable to do so due to this error from the backend. Please reach out to their support team. Cheers!

**Comment by wswebcreation** [comment]
@jaFerrazza 

Can you check your config that you are not connecting to the EU, it works for me based on your config when I don't have the `region` set to `eu` / when I remove that one based on the boilerplate, see https://github.com/webdriverio/appium-boilerplate/blob/master/config/saucelabs/wdio.android.rdc.app.conf.js#L47
