### ISSUE TITLE
Cucumber Scenario Outlines - Cannot read property \'steps\' of undefined

### ISSUE THREAD

**Issue by popescunsergiu** [webdriverio/webdriverio#4274]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [5.11.10]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [ssync]
 - **Node.js version:** [v10.16.0]
 - **NPM version:** [6.9.0]
 - **Browser name and version:** [Any]
 - **Platform name and version:** [Any]
 - **Additional wdio packages used (if applicable):** [
   - "@wdio/cucumber-framework": "5.11.10"
]

**Config of WebdriverIO**
Default config

**Describe the bug**
```
Scenario Outline fails to execute if part of the examples are tagged
```

**To Reproduce**
1. Have a Scenario as the folloring:
```
Scenario Outline: Demo scenario
 Given <type> step
 When 2nd <type> step
 Then 3rd <type> step
  @smoke
  Examples:
   | type |
   | demo |
  Examples:
   | type |
   | another type |
```

[Include code or an example repository that can easily be set up]

**Expected behavior**
Steps shall be executed and filtered based on tags

**Log**
```
{ name: 'TypeError',
  message: 'Cannot read property \'steps\' of undefined',
  stack:
   'TypeError: Cannot read property \'steps\' of undefined\n    at CucumberEventListener.onTestCasePrepared (/Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/@wdio/cucumber-framework/build/cucumberEventListener.js:132:42)\n    at EventEmitter.emit (events.js:203:15)\n    at EventEmitter.emit (domain.js:448:20)\n    at TestCaseRunner.emit (/Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/cucumber/lib/runtime/test_case_runner.js:85:27)\n    at TestCaseRunner.emitPrepared (/Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/cucumber/lib/runtime/test_case_runner.js:127:10)\n    at /Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/cucumber/lib/runtime/test_case_runner.js:208:14\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/cucumber/lib/runtime/test_case_runner.js:22:103)\n    at _next (/Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/cucumber/lib/runtime/test_case_runner.js:24:194)\n    at /Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/cucumber/lib/runtime/test_case_runner.js:24:364\n    at new Promise (<anonymous>)\n    at /Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/cucumber/lib/runtime/test_case_runner.js:24:97\n    at TestCaseRunner.run (/Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/cucumber/lib/runtime/test_case_runner.js:228:7)\n    at /Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/cucumber/lib/runtime/index.js:91:51\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/Users/spopescu/ModusCreate/RoboDomo/e2e-tests/node_modules/cucumber/lib/runtime/index.js:26:103)' }
```

**Additional context**

> Please use the correct markdown

**Comment by mgrybyk** [comment]
@popescunsergiu the issue is not reproducible for me, please upgrade to the latest version and try again.

**Comment by mgrybyk** [comment]
feature
```
Feature: Foobar
    Scenario Outline: Demo scenario
        Given 1st <type> step
        When 2nd <type> step
        Then 3rd <type> step
        @smoke
        Examples:
            | type |
            | demo |
        Examples:
            | type         |
            | another type |
```

step definitions
```
Given(/^1st (.*) step$/, function (type) {
    console.log(type)
})

Given(/^2nd (.*) step$/, function (type) {
    console.log(type)
})

Given(/^3rd (.*) step$/, function (type) {
    console.log(type)
})
```

result
```
[0-0] demo
[0-0] demo
[0-0] demo
[0-0] another type
[0-0] another type
[0-0] another type
```

**Comment by mgrybyk** [comment]
Feel free to reopen or rise another issue if you still seeing the problem
