### ISSUE TITLE
Instead of moving to next action, wdio-appium automatically delete session

### ISSUE THREAD

**Issue by learningandworking** [webdriverio/webdriverio#4307]
**Environment (please complete the following information):**
 - **WebdriverIO version:
   `   "@wdio/appium-service": "^5.11.4",
    "@wdio/cli": "^5.11.10",
    "@wdio/local-runner": "^5.11.10",
    "@wdio/mocha-framework": "^5.11.0",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/spec-reporter": "^5.11.7",
    "@wdio/sync": "^5.11.10",
  `
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.10.1
 - **Platform name and version:** Windows 10 
 - **Android emulator: ** Pixel (Android 8.1)

**Config of WebdriverIO**
```
capabilities: [
    {
        platformName: 'Android',
        maxInstances: 1,
        // For W3C the appium capabilities need to have an extension prefix
        // http://appium.io/docs/en/writing-running-appium/caps/
        // This is `appium:` for all Appium Capabilities which can be found here
        'appium:deviceName': 'Pixel_8.1',
        'appium:platformVersion': '8.1',
        'appium:orientation': 'PORTRAIT',
        // `automationName` will be mandatory, see
        // https://github.com/appium/appium/releases/tag/v1.13.0
        'appium:automationName': 'UiAutomator2',
        // The path to the app
        'appium:app': join(process.cwd(), './apps/duckduckgo.apk'),
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        'appium:noReset': true,
        'appium:newCommandTimeout': 240,
    }

```

**Describe the bug**
 - Instead of moving to next step, wdio-appium calls delete session

**To Reproduce**
  Manual steps:
 - As a client, I open app and click on 3-dot icon at the top-right screen
 - When the pop-up displays, I choose option "Favorite"
 - Then I can see the Favorite setting screen with text "FAVORITE STORIES".

Test case file

```
import {expect} from "chai";
import SearchHome from "../specs/screenobjects/app.searchhome";

describe("Search Home Page", async () => {
    it.only("Verify that client can go to Favorite Setting screen", async () => {
         await SearchHome().goToConfigScreen("Favorites");
        browser.pause(3000);
    })
})
```

app.search.home
```
import { expect } from 'chai';
import Utils from '../helper/utils.js'
import SearchResult from './app.searchresult';
import FavoriteScreen from './app.favoritescreen';
var constants = require('../../constants');



export default function SearchHome() {

    let utils = Utils();


    /**
     * define locator on Search Home screen.
     */

    const SELECTOR = {
        SEARCH_BAR: 'new UiSelector().resourceId("com.duckduckgo.mobile.android:id/searchEditText")',
        CONFIGURE_3DOT_ICON: 'new UiSelector().resourceId("com.duckduckgo.mobile.android:id/overflow")',
        CONFIGURE_POPUP: 'new UiSelector().className("android.widget.ListView")',
        ITEMS_IN_CONFIGURE_POPUP: 'new UiSelector().className("android.widget.TextView")',
    };

    /**
     * define properties of Search Home screen 
     */

    const ItemsInConfigPopUp = ["Stories", "Favorites", "Recents", "Settings", "Help & Feedback"];

    /**
     * Self Verification
     */

    function isAt() {
        let searchBarPlaceHolder = utils.getLoc(SELECTOR.SEARCH_BAR);
        expect(searchBarPlaceHolder.getText()).to.equal("Search DuckDuckGo")
        browser.pause(3000);
    };
    isAt();

    return {
        search: function (value) {
            utils.getLoc(SELECTOR.SEARCH_BAR).click();
            utils.getLoc(SELECTOR.SEARCH_BAR).setValue(value);
            expect(utils.getLoc(SELECTOR.SEARCH_BAR).getText()).to.equal(value);
            browser.pressKeyCode(constants.KEY_CODE.ENTER);
            return SearchResult();

        },

        /**
         * 
         * @param {String} "Stories", "Favorites", "Recents", "Settings", "Help & Feedback" 
         */
        goToConfigScreen: async function (option) {
            utils.getLoc(SELECTOR.CONFIGURE_3DOT_ICON).click();
            switch (option) {
                case "Stories":
                    await utils.getElFromList(SELECTOR.ITEMS_IN_CONFIGURE_POPUP, 0).click();
                    break;
                case "Favorites":
                    await utils.getElFromList(SELECTOR.ITEMS_IN_CONFIGURE_POPUP, 1).click();
                    return FavoriteScreen();
            }
        }
    }
}
```
app.favoritescreen.js
```
import { expect } from "chai";
import Utils from '../helper/utils.js'


let utils;
export default function FavoriteScreen() {

    utils = Utils();
    const SELECTOR = {
        FAVOR_STORIES_TAB: '*//android.widget.TextView[@text="FAVORITE STORIES"]',
        FAVOR_SEARCH_TAB: '*//android.widget.TextView[@text="FAVORITE SEARCHES"]',
        NO_TITLE: 'new UiSelector().resourceId("com.duckduckgo.mobile.android:id/empty_title")',
        SEARCH_BAR: 'new UiSelector().resourceId("com.duckduckgo.mobile.android:id/searchEditText")'
    }

    async function isAt() {
        try {
            console.log("==============Favorite Screen is loading ====================");
            let favorSearchTab = await utils.getLoc(SELECTOR.FAVOR_SEARCH_TAB, true);
            await favorSearchTab.click();
            browser.pause(4000);          
        } catch (error) {
            console.log("Error name: ", error.name);
            console.log("Error message: ", error.message);
            throw(error)
        }
        
    };

    isAt();
}
```

utils.js

```
function Utils() {
    return {
        getLoc: function (SELECTOR, isXpath = false) {
            try {

                if (isXpath) {
                    return $(SELECTOR);
                }
                return $(`android=${SELECTOR}`);
                
            } catch (error) {
                throw (error)
            }
        },

        getListLocs: function (SELECTOR) {

            try {
                return $$(`android=${SELECTOR}`)
            } catch (error) {
                throw (error)
            }
        },

        getElFromList: function (listELements, index) {

            let lst = this.getListLocs(listELements);
            return lst[index]
        },

        getTextFromEl: function (el) {
            return this.getLoc(el).getText();
        },

        getTextFromList: function (listELements, index) {
            return this.getElFromList(listELements, index).getText()
        }

    }
}

export default Utils;
```

[Include code or an example repository that can easily be set up]

**Expected behavior**
Search Tab is be clicked, and there is a keyboard showing

**Log**
```

D:\practice\wdio\webdriverio-mobile (master -> origin) (webdriverio-mobile@1.0.0)
λ .\node_modules\.bin\wdio --spec tests\specs\app.searchHomePage.spec.js

Execution of 1 spec files started at 2019-08-04T10:40:34.928Z

2019-08-04T10:40:34.931Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
2019-08-04T10:40:34.998Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "appium"
2019-08-04T10:40:35.010Z INFO @wdio/cli:Launcher: Run onPrepare hook
OnPrepare: setup library
2019-08-04T10:40:35.067Z DEBUG @wdio/appium-service: Will spawn Appium process: appium.cmd
2019-08-04T10:40:37.676Z ERROR @wdio/appium-service: Appium exited before timeout (exit code: 2)
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.

2019-08-04T10:40:37.678Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Appium exited before timeout (exit code: 2)
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.

    at ChildProcess.process.once.exitCode (D:\practice\wdio\webdriverio-mobile\node_modules\@wdio\appium-service\build\launcher.js:85:16)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)

Continue...
2019-08-04T10:40:37.682Z INFO @wdio/local-runner: Start worker 0-0 with arg: --spec,tests\specs\app.searchHomePage.spec.js
[0-0] RUNNING in Android - D:\practice\wdio\webdriverio-mobile\tests\specs\app.searchHomePage.spec.js
[0-0] 2019-08-04T10:40:38.550Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2019-08-04T10:40:38.564Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "selenium-standalone"
[0-0] 2019-08-04T10:40:38.717Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "appium"
[0-0] 2019-08-04T10:40:38.729Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2019-08-04T10:40:38.733Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
[0-0] 2019-08-04T10:40:38.733Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { platformName: 'Android',
        'appium:deviceName': 'Pixel_8.1',
        'appium:platformVersion': '8.1',
        'appium:orientation': 'PORTRAIT',
        'appium:automationName': 'UiAutomator2',
        'appium:app':
         'D:\\practice\\wdio\\webdriverio-mobile\\apps\\duckduckgo.apk',
        'appium:noReset': true,
        'appium:newCommandTimeout': 240 },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { platformName: 'Android',
     'appium:deviceName': 'Pixel_8.1',
     'appium:platformVersion': '8.1',
     'appium:orientation': 'PORTRAIT',
     'appium:automationName': 'UiAutomator2',
     'appium:app':
      'D:\\practice\\wdio\\webdriverio-mobile\\apps\\duckduckgo.apk',
     'appium:noReset': true,
     'appium:newCommandTimeout': 240 } }
[0-0] 2019-08-04T10:40:55.045Z INFO webdriver: COMMAND findElement("-android uiautomator", "new UiSelector().resourceId("com.duckduckgo.mobile.android:id/searchEditText")")
[0-0] 2019-08-04T10:40:55.046Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/a93a9926-a92c-4f21-abe0-9478c7ab6507/element
2019-08-04T10:40:55.046Z INFO webdriver: DATA { using: '-android uiautomator',
  value:
   'new UiSelector().resourceId("com.duckduckgo.mobile.android:id/searchEditText")' }
[0-0] 2019-08-04T10:40:55.137Z INFO webdriver: RESULT { 'element-6066-11e4-a52e-4f735466cecf': '45c00947-3c17-4c09-810a-f335806647e4',
  ELEMENT: '45c00947-3c17-4c09-810a-f335806647e4' }
[0-0] 2019-08-04T10:40:55.147Z INFO webdriver: COMMAND getElementText("45c00947-3c17-4c09-810a-f335806647e4")
[0-0] 2019-08-04T10:40:55.147Z INFO webdriver: [GET] http://127.0.0.1:4723/wd/hub/session/a93a9926-a92c-4f21-abe0-9478c7ab6507/element/45c00947-3c17-4c09-810a-f335806647e4/text
[0-0] 2019-08-04T10:40:55.210Z INFO webdriver: RESULT Search DuckDuckGo
[0-0] 2019-08-04T10:40:58.214Z INFO webdriver: COMMAND findElement("-android uiautomator", "new UiSelector().resourceId("com.duckduckgo.mobile.android:id/overflow")")
[0-0] 2019-08-04T10:40:58.215Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/a93a9926-a92c-4f21-abe0-9478c7ab6507/element
2019-08-04T10:40:58.215Z INFO webdriver: DATA { using: '-android uiautomator',
  value:
   'new UiSelector().resourceId("com.duckduckgo.mobile.android:id/overflow")' }
[0-0] 2019-08-04T10:40:58.404Z INFO webdriver: RESULT { 'element-6066-11e4-a52e-4f735466cecf': '16da02d9-f2ff-44ec-aa82-ee18385aa8bd',
  ELEMENT: '16da02d9-f2ff-44ec-aa82-ee18385aa8bd' }
[0-0] 2019-08-04T10:40:58.414Z INFO webdriver: COMMAND elementClick("16da02d9-f2ff-44ec-aa82-ee18385aa8bd")
[0-0] 2019-08-04T10:40:58.415Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/a93a9926-a92c-4f21-abe0-9478c7ab6507/element/16da02d9-f2ff-44ec-aa82-ee18385aa8bd/click
[0-0] 2019-08-04T10:40:59.558Z INFO webdriver: RESULT true
[0-0] 2019-08-04T10:40:59.561Z INFO webdriver: COMMAND findElements("-android uiautomator", "new UiSelector().className("android.widget.TextView")")
[0-0] 2019-08-04T10:40:59.562Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/a93a9926-a92c-4f21-abe0-9478c7ab6507/elements
2019-08-04T10:40:59.563Z INFO webdriver: DATA { using: '-android uiautomator',
  value: 'new UiSelector().className("android.widget.TextView")' }
[0-0] 2019-08-04T10:40:59.849Z INFO webdriver: RESULT [ { 'element-6066-11e4-a52e-4f735466cecf': 'b7e872a2-a558-4072-ba01-0e883d8adc74',
    ELEMENT: 'b7e872a2-a558-4072-ba01-0e883d8adc74' },
  { 'element-6066-11e4-a52e-4f735466cecf': 'ad6531f5-174d-4409-bd4d-08b66a1b72af',
    ELEMENT: 'ad6531f5-174d-4409-bd4d-08b66a1b72af' },
  { 'element-6066-11e4-a52e-4f735466cecf': 'ff7d002b-e4ca-4165-9d2e-74f15d73f45c',
    ELEMENT: 'ff7d002b-e4ca-4165-9d2e-74f15d73f45c' },
  { 'element-6066-11e4-a52e-4f735466cecf': 'ea35a055-64a0-4fef-b99d-539edf224370',
    ELEMENT: 'ea35a055-64a0-4fef-b99d-539edf224370' },
  { 'element-6066-11e4-a52e-4f735466cecf': '589ce8ec-824e-4187-954d-566b50e8de4a',
    ELEMENT: '589ce8ec-824e-4187-954d-566b50e8de4a' } ]
[0-0] 2019-08-04T10:40:59.875Z INFO webdriver: COMMAND elementClick("ad6531f5-174d-4409-bd4d-08b66a1b72af")
[0-0] 2019-08-04T10:40:59.875Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/a93a9926-a92c-4f21-abe0-9478c7ab6507/element/ad6531f5-174d-4409-bd4d-08b66a1b72af/click
[0-0] 2019-08-04T10:41:01.160Z INFO webdriver: RESULT true
[0-0] ==============Favorite Screen is loading ====================
2019-08-04T10:41:01.162Z INFO webdriver: COMMAND findElement("xpath", "*//android.widget.TextView[@text="FAVORITE SEARCHES"]")
2019-08-04T10:41:01.162Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/a93a9926-a92c-4f21-abe0-9478c7ab6507/element
[0-0] 2019-08-04T10:41:01.163Z INFO webdriver: DATA { using: 'xpath',
  value: '*//android.widget.TextView[@text="FAVORITE SEARCHES"]' }
[0-0] 2019-08-04T10:41:01.168Z INFO webdriver: COMMAND deleteSession()
[0-0] 2019-08-04T10:41:01.169Z INFO webdriver: [DELETE] http://127.0.0.1:4723/wd/hub/session/a93a9926-a92c-4f21-abe0-9478c7ab6507
2019-08-04T10:41:01.592Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 0
[0-0] PASSED in Android - D:\practice\wdio\webdriverio-mobile\tests\specs\app.searchHomePage.spec.js
2019-08-04T10:41:01.595Z INFO @wdio/cli:Launcher: Run onComplete hook
2019-08-04T10:41:01.595Z INFO @wdio/selenium-standalone-service: shutting down all browsers

 "spec" Reporter:
------------------------------------------------------------------
[emulator-5554 LINUX 8.1.0 #0-0] Spec: D:\practice\wdio\webdriverio-mobile\tests\specs\app.searchHomePage.spec.js
[emulator-5554 LINUX 8.1.0 #0-0] Running: emulator-5554 on LINUX 8.1.0 executing D:\practice\wdio\webdriverio-mobile\apps\duckduckgo.apk
[emulator-5554 LINUX 8.1.0 #0-0]
[emulator-5554 LINUX 8.1.0 #0-0] Search Home Page
[emulator-5554 LINUX 8.1.0 #0-0]    ✓ Verify search enginee returns >= 1 results related to input
[emulator-5554 LINUX 8.1.0 #0-0]
[emulator-5554 LINUX 8.1.0 #0-0] 1 passing (8.2s)


Spec Files:      1 passed, 1 total (100% completed) in 00:00:26
```

**Additional context**

> Please use the correct markdown

**Comment by mgrybyk** [comment]
Please don't mix sync and async functions when using wdio/sync.
You have to remove all async await from your code. If you need to run something async use browser call.

Also, please upgrade to the latest version.
If the issue persists after you have fixed your code, feel free to reopen

**Comment by learningandworking** [comment]
Thanks @mgrybyk , I think this issue is fixed as your suggestion
