### ISSUE TITLE
moveTo() without arguments throws out of bounds error for scrolled page on MS Edge

### ISSUE THREAD

**Issue by igerasimov23** [webdriverio/webdriverio#4317]
Cloned from https://github.com/webdriverio/webdriverio/issues/4206

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.13
 - **Mode:** Standalone mode 
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Ms Edge 18
 - **Platform name and version:** Windows 10. Browser version from SauceLab `"browserVersion": "44.17763.1.0"`

**Config of WebdriverIO**
Does not matter

**Describe the bug**
In W3C mode, when use element's function moveTo without any arguments and page is scrolled down more than page height, `The target for mouse interaction is not in the browser's viewport and cannot be brought into that viewport` is thrown.

**To Reproduce**
element.scrollIntoView();
element.moveTo();

**Expected behavior**
No errors should be thrown and mouse over event should happen

**Log**
```
0-0] 2019-08-05T15:44:15.976Z WARN webdriver: Request failed due to The target for mouse interaction is not in the browser's viewport and cannot be brought into that viewport.
[0-0] 2019-08-05T15:44:16.109Z WARN webdriver: Request failed due to The target for mouse interaction is not in the browser's viewport and cannot be brought into that viewport.
[0-0] 2019-08-05T15:44:16.245Z WARN webdriver: Request failed due to The target for mouse interaction is not in the browser's viewport and cannot be brought into that viewport.
[0-0] 2019-08-05T15:44:16.358Z ERROR webdriver: Request failed due to move target out of bounds: The target for mouse interaction is not in the browser's viewport and cannot be brought into that viewport.
    at getErrorFromResponseBody (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/webdriver/build/utils.js:215:10)
    at Request._callback (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/webdriver/build/request.js:103:64)
    at Request.self.callback (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/Users/208821/Projects/np-cooking/api/test/e2e/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[0-0] move target out of bounds in "test recipedetails Verify if nutrition information displayed and Edamam link is working on RDP -env dev -feature RDP-layout -devices tablet,mobile"
The target for mouse interaction is not in the browser's viewport and cannot be brought into that viewport. 
```

> Please use the correct markdown

**Comment by mgrybyk** [comment]
Do you have a link nearby on how to upgrade edge 17 to edge 18?

**Comment by igerasimov23** [comment]
I was using SauceLab service to test on MS Edge

**Comment by mgrybyk** [comment]
MoveTo doesn't work in Edge because `getElementRect` works differently comparing to chrome/safari/firefox/ie11. It doesn't respect scrollX and scrollY position.
https://www.w3.org/TR/webdriver1/#get-element-rect

**Comment by tung-dang** [comment]
How about in Firefox and Safari? For my case, `browser.moveTo` does not work in 3 browsers: Firefox, Safari and MS Edge.

**Comment by mgrybyk** [comment]
It works for me in chrome and firefox, not sure about your case

**Comment by deekshachaudhary** [comment]
We are having the same issue in Firefox (v69.0) with BrowserStack where moveTo throws "move target out of bounds in...
(633, 1422) is out of bounds of viewport width (1908) and height (1119)" error. It works in Chrome. It works in Firefox when we add scrollIntoView.

**Comment by Nick46368** [comment]
"webdriverio": "^5.23.0" have the same problem. 
element.moveTo() don't scroll

**Comment by christian-bromann** [comment]
Closing due to inactivity.
