### ISSUE TITLE
cucumber + custom allure report :  ERROR @wdio/runner: TypeError: Cannot set property 'currentTest' of undefined

### ISSUE THREAD

**Issue by gtilekar** [webdriverio/webdriverio#4333]
@wdio/spec-reporter": "^5.11.7",
    "@wdio/allure-reporter": "^5.11.0",
    "@wdio/cli": "^5.11.12",
    "@wdio/cucumber-framework": "^5.11.12",
    "@wdio/local-runner": "^5.11.12",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/sync": "^5.11.0",
    "@wdio/config": "^5.11.0",
    "webdriverio": "^5.11.12",

[0-0] 2019-08-07T19:37:37.496Z ERROR @wdio/runner: TypeError: Cannot set property 'currentTest' of undefined
    at Allure.startCase (C:\...\...\node_modules\allure-js-commons\index.js:44:23)
    at customReporter.<anonymous> (C:\...\...\wdio-custom-reporter\customReporter.js:51:22)
    at customReporter.emit (events.js:189:13)
    at customReporter.EventEmitter.emit (domain.js:441:20)
    at reporters.forEach.reporter (C:\...\...\node_modules\@wdio\runner\build\reporter.js:38:49)
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (C:\...\...\node_modules\@wdio\runner\build\reporter.js:38:20)
    at CucumberReporter.emit (C:\...\...\node_modules\@wdio\cucumber-framework\build\reporter.js:179:19)
    at CucumberReporter.handleBeforeFeature (C:\...\...\node_modules\@wdio\cucumber-framework\build\reporter.js:34:10)
    at CucumberEventListener.emit (events.js:189:13)
    at CucumberEventListener.EventEmitter.emit (domain.js:441:20)
    at CucumberEventListener.onGherkinDocument (C:\...\...\node_modules\@wdio\cucumber-framework\build\cucumberEventListener.js:34:10)
    at EventEmitter.emit (events.js:194:15)
    at EventEmitter.emit (domain.js:441:20)
    at events.forEach.event (C:\...\...\node_modules\cucumber\lib\cli\helpers.js:114:24)
    at Array.forEach (<anonymous>)
0-0 worker error { name: 'TypeError',
  message: 'Cannot set property \'currentTest\' of undefined',
  stack:
   'TypeError: Cannot set property \'currentTest\' of undefined\n    at Allure.startCase (C:\\...\\...\\node_modules\\allure-js-commons\\index.js:44:23)\n    at customReporter.<ano
nymous> (C:\\...\\...\\wdio-custom-reporter\\customReporter.js:51:22)\n    at customReporter.emit (events.js:189:13)\n    at customReporter.EventEmitter.emit (domain.js:441:20)\n
  at reporters.forEach.reporter (C:\\...\\...\\node_modules\\@wdio\\runner\\build\\reporter.js:38:49)\n    at Array.forEach (<anonymous>)\n    at BaseReporter.emit (C:\\Web_automat
ion\\...\\node_modules\\@wdio\\runner\\build\\reporter.js:38:20)\n    at CucumberReporter.emit (C:\\...\\...\\node_modules\\@wdio\\cucumber-framework\\build\\rep
orter.js:179:19)\n    at CucumberReporter.handleBeforeFeature (C:\\...\\...\\node_modules\\@wdio\\cucumber-framework\\build\\reporter.js:34:10)\n    at CucumberEventListener.emit (
events.js:189:13)\n    at CucumberEventListener.EventEmitter.emit (domain.js:441:20)\n    at CucumberEventListener.onGherkinDocument (C:\\...\\...\\node_modules\\@wdio\\cucumber-fr
amework\\build\\cucumberEventListener.js:34:10)\n    at EventEmitter.emit (events.js:194:15)\n    at EventEmitter.emit (domain.js:441:20)\n    at events.forEach.event (C:\\...\\...
\\node_modules\\cucumber\\lib\\cli\\helpers.js:114:24)\n    at Array.forEach (<anonymous>)' }
[0-0] 2019-08-07T19:37:37.501Z INFO webdriver: COMMAND deleteSession()
.
.
.
[0-0] 2019-08-07T19:37:37.760Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2019-08-07T19:37:37.861Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2019-08-07T19:37:37.963Z INFO @wdio/runner: Wait for 1 reporter to synchronise

customReporter.js (snippet):
let util = require('util'),
    events = require('events'),
    Allure = require('allure-js-commons'),
    id = 0,
    allures = {}
.
.
.
   this.on('suite:start', function (suit) {
        const reporter = getAllure(suit.cid)
        if (suit.parent === null) {
            reporter.startSuite(suit.title)
        } else {
            reporter.startCase(suit.title + ' ' + id)  <----- Fails on this line(line 51)
            const currentTest = reporter.getCurrentTest()

When running cucumber test with custom allure report it shows above error

**Comment by mgrybyk** [comment]
Looks like there are some problems with your custom reporter. 

Can you please provide with reproducible example to make sure that problem is caused by wdio and not your project configuration or reporter implementation. 

Thank you

**Comment by gtilekar** [comment]
Hi,
   The custom reporter used to work fine on below modules.

     wdio-allure-reporter": "0.1.2",
    "wdio-browserstack-service": "0.1.4",
    "wdio-cucumber-framework": "1.0.2",
    "wdio-dot-reporter": "0.0.8",
    "wdio-spec-reporter": "^0.1.0",
    "webdriverio": "4.13.1",
    "allure-js-commons": "^1.3.1",

But after upgrade it started giving error.

It you want a cucumber example we can still take the login one 

Scenario Outline: Bar
    Given User <userId> with <password> is logged in

    @first
    Examples:
        | userId    | password |
        | 123       | pwd      |
        | 456       | pwd123   |

with a step definition like:

Given(/^User (.*) with (.*) is logged in/g, {}, function (userId, password) {
    console.log(userId, password)
})

Just wanted to know if we need to do any changes in reporter after moving to wdio 5
Thanks

**Comment by mgrybyk** [comment]
this is webdriverio v5 issue tracker, you may try asking people in gitter channel to help

**Comment by mgrybyk** [comment]
If you have some issues in v5, please remove all v4 related modules and reopen issue if it is still actual.
I'd suggest to use some examples of custom reporter first

**Comment by gtilekar** [comment]
I got rid of the ERROR @wdio/runner: TypeError: Cannot set property 'currentTest' of 

with change  "this.on('suite:start', function (suit) {"  to "this.on('suiteStart', function (suit) {" and did the same for rest

but now i get error 
0-0] 2019-08-08T13:37:13.170Z ERROR @wdio/local-runner: Failed launching test session: Error: Some reporters are still unsynced: customReporter
    at Timeout.setInterval (C:\..\..\node_modules\@wdio\runner\build\reporter.js:86:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
2019-08-08T13:37:13.191Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1

Any pointers on when we get this error

**Comment by mgrybyk** [comment]
Reading docs should be helpful

**Comment by mgrybyk** [comment]
Your reporter is runner asynchronously, you need to sync it first. To do that, before calling async command set this.isSynchronising to false, after everything is resolved set it back to true, ex in on runner end hook

**Comment by gtilekar** [comment]
Can you point to any documentation or example of same.

**Comment by mgrybyk** [comment]
```
const WDIOReporter = require("@wdio/reporter").default;

module.exports = class MyCustomReporter extends WDIOReporter {
    constructor(options) {
        super(Object.assign(options, { stdout: true }))
        this.isSynchronising = true
    }

    async onRunnerEnd() {
        this.isSynchronising = false
        // await some async stuff
        this.isSynchronising = true
    }

    get isSynchronised() {
        return this.isSynchronising
    }
}
```

**Comment by gtilekar** [comment]
Hi 

below is the structure of our current custom reporter

customReport.js

let util = require('util'),
    events = require('events'),
    Allure = require('allure-js-commons'),
    id = 0,
    allures = {}

function getTags (tags, string = false) {
    
}

const customReporter = function (options) {
    function getAllure (cid) {
        
    }


    function isAnyTestRunning (allure) {
    }

    this.on('suitStart', function (suit) {
        
    })

    this.on('suiteEnd', function (suit) {
       
    })

    this.on('testStart', function (test) {
    })

    this.on('testPass', (test) => {
    })

    this.on('testFail', function (test) {
        
    })

    this.on('runnerResult', (command) => {
    })
}

util.inherits(customReporter, events.EventEmitter)

module.exports = customReporter

If I have to use the code you gave .I will have to put all the above stuff in class which extends it to WDIOReporter 

I tried that ,but then it start to through error on  Allure.startCase 
Error:
[0-0] 2019-08-09T08:23:56.768Z ERROR @wdio/runner: TypeError: Cannot set property 'currentTest' of undefined

**Comment by mgrybyk** [comment]
You can take a look at wdio implementation of allure reporter. 
You are missing lots of stuff

**Comment by mgrybyk** [comment]
Maybe it make sense to enhance wdio allure reporter?

**Comment by mgrybyk** [comment]
I'd better enhance wdio allure reporter to work properly with multiple examples.
I think it might be useful for everyone

**Comment by gtilekar** [comment]
Yup

**Comment by gtilekar** [comment]
I was looking at file .\node_modules\@wdio\allure-reporter\build\index.js and did not see any isSynchronising stuff.

was wondering how does allure report handle it.

**Comment by mgrybyk** [comment]
It's not needed there if there is no such

**Comment by gtilekar** [comment]
I have tried my code with wdio allure reporter but it fail on suitestart with same error.

onSuiteStart (suite) {
        if (suite.type === null) {
            this.allure.startSuite(suite.title)
        } else {
            this.allure.startCase(suite.title ) <--- line where it fails
            const currentTest = this.allure.getCurrentTest()            
        }
    }

0-0] 2019-08-09T11:12:20.441Z ERROR @wdio/runner: TypeError: Cannot set property 'currentTest' of undefined
    at Allure.startCase (C:\...\...\node_modules\allure-js-commons\index.js:44:23)
    at customReporter.onSuiteStart (C:\...\...\wdio-custom-reporter\customReporter.js:65:38)
    at customReporter.WDIOReporter.on.params (C:\...\...\node_modules\@wdio\reporter\build\index.js:76:12)
    at customReporter.emit (events.js:189:13)
    at customReporter.EventEmitter.emit (domain.js:441:20)
    at reporters.forEach.reporter (C:\...\...\node_modules\@wdio\runner\build\reporter.js:38:49)
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (C:\...\...\node_modules\@wdio\runner\build\reporter.js:38:20)
    at CucumberReporter.emit (C:\...\...\node_modules\@wdio\cucumber-framework\build\reporter.js:179:19)
    at CucumberReporter.handleBeforeFeature (C:\...\...\node_modules\@wdio\cucumber-framework\build\reporter.js:34:10)
    at CucumberEventListener.emit (events.js:189:13)
    at CucumberEventListener.EventEmitter.emit (domain.js:441:20)
    at CucumberEventListener.onGherkinDocument (C:\...\...\node_modules\@wdio\cucumber-framework\build\cucumberEventListener.js:34:10)
    at EventEmitter.emit (events.js:194:15)
    at EventEmitter.emit (domain.js:441:20)
    at events.forEach.event (C:\...\...\node_modules\cucumber\lib\cli\helpers.js:114:24)

**Comment by gtilekar** [comment]
can we expect multiple example support for allure soon ? :)

**Comment by mgrybyk** [comment]
you may submit feature request, don't hesitate to help with it.

**Comment by gtilekar** [comment]
https://github.com/webdriverio/webdriverio/issues/4348
