### ISSUE TITLE
NPE when get element in browser

### ISSUE THREAD

**Issue by sgauruseu** [webdriverio/webdriverio#4337]
My chrome is updated today to  76.0.3809.100 
I have got the exception : `Error: java.lang.NullPointerException` 
`node_modules\webdriverio\node_modules\webdriver\build\utils.js:215:10)`
`node_modules\webdriverio\node_modules\webdriver\build\request.js:103:64)`
`node_modules\request\request.js:185:22)`
`node_modules\request\request.js:1161:10)`

**Environment**
 - **WebdriverIO version:** 5.7.15 and 5.11.13
 -  selenium-server-standalone-3.9.0
-    ChromeDriver 76.0.3809.68
 - **Mode:** Standalone mode 

 - **Node.js version:** [e.g. 8.9.1]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name Chrome Version 76.0.3809.100 
 - **Platform  Windows 10

**Additional context**

**Comment by mgrybyk** [comment]
Please provide with reproducible example

**Comment by sgauruseu** [comment]
let options = {
            logLevel: "error",
            capabilities: {
                browserName: browser_name,
                platform: platform_name,
                binary: chromeBinPath,
                chromeOptions: makeChromeOptions(isHeadless, width)
            }
        };
            _this.browser = await webdriverio.remote(options);

this.browser.$('input[id^='username-input']')

**Comment by mgrybyk** [comment]
May you please provide with some code snippet that can be executed straight away. I have no issues with running wdio programmatically. More complete example would help

**Comment by sgauruseu** [comment]
example.js

**Comment by sgauruseu** [comment]
[code.zip](https://github.com/webdriverio/webdriverio/files/3480756/code.zip)

**Comment by sgauruseu** [comment]
Error: java.lang.NullPointerException
    at getErrorFromResponseBody (testing\node_modules\webdriverio\node_modules\webdriver\build\utils.js:215:10)
    at Request._callback (testing\node_modules\webdriverio\node_modules\webdriver\build\request.js:103:64)
    at Request.self.callback (testing\node_modules\request\request.js:185:22)
    at Request.<anonymous> (testing\node_modules\request\request.js:1161:10)
    at IncomingMessage.<anonymous> (testing\node_modules\request\request.js:1083:12)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by sgauruseu** [comment]
it is my dependencies:
"devDependencies": {
    "assert": "^1.5.0",
    "chai": "^3.5.0",
    "chai-as-promised": "7.1.1",
    "globby": "^9.0.0",
    "mocha": "^5.2.0",
    "mocha-multi-reporters": "1.1.5",
    "mochawesome": "4.0.1",
    "properties-reader": "0.0.15",
    "selenium-standalone": "^6.16.0",
    "webdriverio": "^5.11.13"
  }

**Comment by sgauruseu** [comment]
[test.zip](https://github.com/webdriverio/webdriverio/files/3480812/test.zip)

**Comment by sgauruseu** [comment]
It is my project.
1. Unpack it .
2. /test npm install
3. /test npm test

**Comment by sgauruseu** [comment]
[standalone.zip](https://github.com/webdriverio/webdriverio/files/3480861/standalone.zip)

**Comment by sgauruseu** [comment]
2019-08-08T09:54:49.877Z INFO webdriver: COMMAND navigateTo("https://www.google.com/")
2019-08-08T09:54:49.877Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/02ff622e-a06d-4b85-b5ea-c32759042afc/url
2019-08-08T09:54:49.878Z INFO webdriver: DATA { url: 'https://www.google.com/' }
2019-08-08T09:54:50.801Z INFO webdriver: COMMAND findElement("xpath", "//input[@name='q']")
2019-08-08T09:54:50.802Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/02ff622e-a06d-4b85-b5ea-c32759042afc/element
2019-08-08T09:54:50.802Z INFO webdriver: DATA { using: 'xpath', value: '//input[@name=\'q\']' }
2019-08-08T09:54:50.833Z INFO webdriver: RESULT { ELEMENT: '0' }
2019-08-08T09:54:50.839Z INFO webdriver: COMMAND isElementEnabled("0")
2019-08-08T09:54:50.840Z INFO webdriver: [GET] http://localhost:4444/wd/hub/session/02ff622e-a06d-4b85-b5ea-c32759042afc/element/0/enabled
2019-08-08T09:54:50.855Z INFO webdriver: RESULT true
2019-08-08T09:54:50.856Z INFO webdriver: COMMAND elementClear("0")
2019-08-08T09:54:50.856Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/02ff622e-a06d-4b85-b5ea-c32759042afc/element/0/clear
2019-08-08T09:54:50.897Z INFO webdriver: COMMAND elementSendKeys("0", "hello")
2019-08-08T09:54:50.898Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/02ff622e-a06d-4b85-b5ea-c32759042afc/element/0/value
2019-08-08T09:54:50.898Z INFO webdriver: DATA { text: 'hello' }
2019-08-08T09:54:50.905Z INFO webdriver: Retrying 1/3
2019-08-08T09:54:50.905Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/02ff622e-a06d-4b85-b5ea-c32759042afc/element/0/value
2019-08-08T09:54:50.905Z INFO webdriver: DATA { text: 'hello' }
2019-08-08T09:54:50.904Z WARN webdriver: Request failed due to java.lang.NullPointerException
2019-08-08T09:54:50.915Z INFO webdriver: Retrying 2/3
2019-08-08T09:54:50.915Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/02ff622e-a06d-4b85-b5ea-c32759042afc/element/0/value
2019-08-08T09:54:50.915Z INFO webdriver: DATA { text: 'hello' }
2019-08-08T09:54:50.915Z WARN webdriver: Request failed due to java.lang.NullPointerException
2019-08-08T09:54:50.925Z WARN webdriver: Request failed due to java.lang.NullPointerException
2019-08-08T09:54:50.925Z INFO webdriver: Retrying 3/3
2019-08-08T09:54:50.926Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/02ff622e-a06d-4b85-b5ea-c32759042afc/element/0/value
2019-08-08T09:54:50.926Z INFO webdriver: DATA { text: 'hello' }
2019-08-08T09:54:50.932Z ERROR webdriver: Request failed due to Error: java.lang.NullPointerException

**Comment by sgauruseu** [comment]
browser.setWindowSize(width, height)   does not  work as well

**Comment by mgrybyk** [comment]
you have configured project incorrectly, passing wrong capabilities

**Comment by mgrybyk** [comment]
There are no such capabilities as `platform` and `chromeOptions` in w3c specification, you have to removed redundant ones and pass vendor specific capabilities according to specification, in this case "goog:chromeOptions".

After fixing that I'm able to run your project.
However, I'd recommend you to use webdriverio runner instead, it would make your life way easier.

Please use gitter for such questions

**Comment by sgauruseu** [comment]
I passed vendor specific capabilities:   ` 'goog:chromeOptions': makeChromeOptions(isHeadless, width)`
But  it was not the cause of this NPE. 
I got exception when  test tried to set value in text-input:

![image](https://user-images.githubusercontent.com/3728712/62699981-6684ab80-b9e9-11e9-919e-7f44f8a7a61d.png)

**Comment by mgrybyk** [comment]
I have no npe exceptions at all with your project

**Comment by mgrybyk** [comment]
I have no npe exceptions at all with your project

**Comment by mgrybyk** [comment]
The error is not caused by wdio, it is an error returned from your selenium server. Try debugging it, maybe you have wrong java version? 

Anyway, if you can use a recommended approach to you'd get such errors

**Comment by sgauruseu** [comment]
Thanks! Great! It works now! 
Strange, but my chrome-options worked fine with the previous version of chrome browser and selenium-server. I updated my selenium server and fixed my chrome options - no problems with running tests now.
I do not use `webdriverio runner` because it is impossible to debug tests in the Idea IDE.
So I using `mocha-runner` - no problems with running tests in Idea IDE in this case.

**Comment by mgrybyk** [comment]
It is possible to debug! There are some issues with fibers in sync mode, of course, maybe we'll solve it one day somehow
