### ISSUE TITLE
Regressions from version 5.12.1

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#4364]
**Environment:**
 - **WebdriverIO version:** 5.12.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.4.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome,Firefox
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**: Any

**Describe the bugs**
After nuking my modules and updating to 5.12.1, my project is throwing errors all around:

1. Can no longer access Cucumber World in step definitions after populating World in the (Cucumber) hooks (Before, After, etc). `this` in step definitions is `undefined`

```js
Given(/^I am logged in$/, function() {
  console.log(`Step definition: ${JSON.stringify(this, null, 4)}`); //Prints undefined
});
```
2. `browser.execute` is returning an empty object when executed in certain hooks (_afterScenario_?)

**To Reproduce**

Script (within a hook):

  ```js
const execResult = browser.execute(function() {
    return {
      screen,
      window: {
        innerHeight: window.innerHeight,
        innerWidth: window.innerWidth
      },
      devicePixelRatio: window.devicePixelRatio
    };
  });
  console.log(JSON.stringify(`Exec result: ${execResult}`, null, 4)); // Prints {}
  const { screen, window, devicePixelRatio = 1.0 } = execResult;

  console.log(screen.width); // ERROR @wdio/config: TypeError: Cannot read property 'width' of undefined
```

**Log**
```none
2019-08-15T09:39:26.120Z INFO webdriver: COMMAND executeScript("return (function () {
    return {
      screen: screen,
      window: {
        innerHeight: window.innerHeight,
        innerWidth: window.innerWidth
      },
      devicePixelRatio: window.devicePixelRatio
    };
  }).apply(null, arguments)", <object>)
2019-08-15T09:39:26.121Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/[SESSION-ID]/execute
2019-08-15T09:39:26.121Z INFO webdriver: DATA {
  script: 'return (function () {\n    return {\n      screen: screen,\n     ' +
    ' window: {\n        innerHeight: window.innerHeight,\n        ' +
    'innerWidth: window.innerWidth\n      },\n      ' +
    'devicePixelRatio: window.devicePixelRatio\n    };\n  ' +
    '}).apply(null, arguments)',
  args: []
}
2019-08-15T09:39:26.124Z ERROR @wdio/config: TypeError: Cannot read property 'width' of undefined
    at width (C:\Users\[REDACTED]\repos\wdio-e2e\tests\e2e\support/platform.js:54:43)
    at getResolutionInfo (C:\Users\[REDACTED]\repos\wdio-e2e\tests\e2e\support/platform.js:65:30)
    at buildDeviceInfoString (C:\Users\[REDACTED]\repos\wdio-e2e\tests\e2e\support/platform.js:109:61)
    at Object.afterScenario (C:\Users\[REDACTED]\repos\wdio-e2e\tests\e2e\hooks/afterScenario.hook.js:12:22)
    at C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\@wdio\config\build\shim.js:29:21
    at new Promise (<anonymous>)
    at C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\@wdio\config\build\shim.js:25:29
    at Array.map (<anonymous>)
    at executeHooksWithArgsShim (C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\@wdio\config\build\shim.js:25:17)
    at World.wdioHookAfterScenario (C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\@wdio\cucumber-framework\build\index.js:159:47)
    at C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\cucumber\lib\user_code_runner.js:42:23
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\cucumber\lib\user_code_runner.js:18:103)
    at _next (C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\cucumber\lib\user_code_runner.js:20:194)
    at C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\cucumber\lib\user_code_runner.js:20:364
    at new Promise (<anonymous>)
    at C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\cucumber\lib\user_code_runner.js:20:97
    at Function.run (C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\cucumber\lib\user_code_runner.js:109:7)
    at Object.<anonymous> (C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\cucumber\lib\runtime\step_runner.js:59:54)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\cucumber\lib\runtime\step_runner.js:20:103)
    at _next (C:\Users\[REDACTED]\repos\wdio-e2e\node_modules\cucumber\lib\runtime\step_runner.js:22:194)
2019-08-15T09:39:26.130Z INFO webdriver: COMMAND getUrl()
```

**Comment by mgrybyk** [comment]
I can fix second issue, we can deal with first one a bit later

**Comment by mgrybyk** [comment]
let's proceed convo in PR, gonna fix both issues
