### ISSUE TITLE
browser.switchToFrame doesn't work for Edge browser

### ISSUE THREAD

**Issue by yuriieasternpeak** [webdriverio/webdriverio#4387]
- **WebdriverIO version:** browser.switchToFrame
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.9
 - **NPM version:** 6.9.0
 - **Browser name and version:** Edge
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service

**Config of WebdriverIO**
see git repo (https://github.com/yuriieasternpeak/wdio-edge-switchtoframe/blob/master/wdio.conf.js)
I use browser stack because of mac os, but you can use local edge if you have windows

**Describe the bug**
browser.switchToFrame throws - Request failed due to The specified frame was not found in the current frame or window.

**To Reproduce**
clone https://github.com/yuriieasternpeak/wdio-edge-switchtoframe
install modules using yarn or npm
run npm test

**Expected behavior**
switchToFrame should not throw an exception

**Comment by christian-bromann** [comment]
Can you provide some logs from WebdriverIO __and__ your Edgedriver?

**Comment by yuriieasternpeak** [comment]
[0-0] 2019-08-20T14:31:10.676Z INFO webdriver: COMMAND switchToFrame(<object>)
[0-0] 2019-08-20T14:31:10.676Z INFO webdriver: [POST] https://hub.browserstack.com:443/wd/hub/session/bea434f1cbaa14956cd99b21fb4b6bb195413473/frame
[0-0] 2019-08-20T14:31:10.676Z INFO webdriver: DATA { id: 
   Element {
     sessionId: 'bea434f1cbaa14956cd99b21fb4b6bb195413473',
     elementId: '56bad900-af57-4d10-b839-fd13bb4ab8e3',
     'element-6066-11e4-a52e-4f735466cecf': '56bad900-af57-4d10-b839-fd13bb4ab8e3',
     selector: '<iframe />',
     parent: 
      Browser {
        sessionId: 'bea434f1cbaa14956cd99b21fb4b6bb195413473',
        capabilities: [Object],
        addCommand: [Function],
        overwriteCommand: [Function],
        config: [Object],
        _NOT_FIBER: true },
     index: 0,
     emit: [Function: bound ],
     addCommand: [Function],
     overwriteCommand: [Function] } }
[0-0] 2019-08-20T14:31:10.951Z WARN webdriver: Request failed due to The specified frame was not found in the current frame or window.
[0-0] 2019-08-20T14:31:10.951Z INFO webdriver: Retrying 1/3
2019-08-20T14:31:10.951Z INFO webdriver: [POST] https://hub.browserstack.com:443/wd/hub/session/bea434f1cbaa14956cd99b21fb4b6bb195413473/frame
[0-0] 2019-08-20T14:31:10.951Z INFO webdriver: DATA { id: 
   Element {
     sessionId: 'bea434f1cbaa14956cd99b21fb4b6bb195413473',
     elementId: '56bad900-af57-4d10-b839-fd13bb4ab8e3',
     'element-6066-11e4-a52e-4f735466cecf': '56bad900-af57-4d10-b839-fd13bb4ab8e3',
     selector: '<iframe />',
     parent: 
      Browser {
        sessionId: 'bea434f1cbaa14956cd99b21fb4b6bb195413473',
        capabilities: [Object],
        addCommand: [Function],
        overwriteCommand: [Function],
        config: [Object],
        _NOT_FIBER: true },
     index: 0,
     emit: [Function: bound ],
     addCommand: [Function],
     overwriteCommand: [Function] } }
[0-0] 2019-08-20T14:31:11.328Z INFO webdriver: Retrying 2/3
2019-08-20T14:31:11.329Z INFO webdriver: [POST] https://hub.browserstack.com:443/wd/hub/session/bea434f1cbaa14956cd99b21fb4b6bb195413473/frame
[0-0] 2019-08-20T14:31:11.329Z INFO webdriver: DATA { id: 
   Element {
     sessionId: 'bea434f1cbaa14956cd99b21fb4b6bb195413473',
     elementId: '56bad900-af57-4d10-b839-fd13bb4ab8e3',
     'element-6066-11e4-a52e-4f735466cecf': '56bad900-af57-4d10-b839-fd13bb4ab8e3',
     selector: '<iframe />',
     parent: 
      Browser {
        sessionId: 'bea434f1cbaa14956cd99b21fb4b6bb195413473',
        capabilities: [Object],
        addCommand: [Function],
        overwriteCommand: [Function],
        config: [Object],
        _NOT_FIBER: true },
     index: 0,
     emit: [Function: bound ],
     addCommand: [Function],
     overwriteCommand: [Function] } }
[0-0] 2019-08-20T14:31:11.328Z WARN webdriver: Request failed due to The specified frame was not found in the current frame or window.
[0-0] [0-0] 2019-08-20T14:31:11.684Z 2019-08-20T14:31:11.684ZWARN  INFO webdriver: Request failed due to The specified frame was not found in the current frame or window.
webdriver: Retrying 3/3
[0-0] 2019-08-20T14:31:11.684Z INFO webdriver: [POST] https://hub.browserstack.com:443/wd/hub/session/bea434f1cbaa14956cd99b21fb4b6bb195413473/frame
[0-0] 2019-08-20T14:31:11.684Z INFO webdriver: DATA { id: 
   Element {
     sessionId: 'bea434f1cbaa14956cd99b21fb4b6bb195413473',
     elementId: '56bad900-af57-4d10-b839-fd13bb4ab8e3',
     'element-6066-11e4-a52e-4f735466cecf': '56bad900-af57-4d10-b839-fd13bb4ab8e3',
     selector: '<iframe />',
     parent: 
      Browser {
        sessionId: 'bea434f1cbaa14956cd99b21fb4b6bb195413473',
        capabilities: [Object],
        addCommand: [Function],
        overwriteCommand: [Function],
        config: [Object],
        _NOT_FIBER: true },
     index: 0,
     emit: [Function: bound ],
     addCommand: [Function],
     overwriteCommand: [Function] } }
[0-0] 2019-08-20T14:31:11.856Z ERROR webdriver: Request failed due to no such frame: The specified frame was not found in the current frame or window.
    at getErrorFromResponseBody (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/node_modules/webdriver/build/utils.js:215:10)
    at Request._callback (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/node_modules/webdriver/build/request.js:103:64)
    at Request.self.callback (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
[0-0] Error: { no such frame: The specified frame was not found in the current frame or window.
    at Context.it (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/test/test.js:12:21)
    at <anonymous> name: 'no such frame' }
[0-0] 2019-08-20T14:31:11.859Z INFO webdriver: COMMAND deleteSession()

**Comment by yuriieasternpeak** [comment]
> Can you provide some logs from WebdriverIO **and** your Edgedriver?

added WebdriverIO logs, how can I find Edgedriver logs?

**Comment by christian-bromann** [comment]
> how can I find Edgedriver logs?

Depends how you run Edgedriver. There should be options that allow you to dump the  logs into a file.

**Comment by yuriieasternpeak** [comment]
> > how can I find Edgedriver logs?
> 
> Depends how you run Edgedriver. There should be options that allow you to dump the logs into a file.

I use browser stack to run edge

**Comment by christian-bromann** [comment]
Looked into the code example, you are doing:
```js
const frames = await browser.$$('<iframe />');
await browser.switchToFrame(frames[0]);
```
Which doesn't work and never worked before. Please see docs: https://webdriver.io/docs/api/webdriver.html#switchtoframe where the parameter is defined as

> one of three possible types: null: this represents the top-level browsing context (i.e., not an iframe), a Number, representing the index of the window object corresponding to a frame, a string representing an element id that can be received using findElement.

Therefor you need to do:

```js
await browser.switchToFrame(frames[0].elementId)
```

cc @mgrybyk

**Comment by yuriieasternpeak** [comment]
> Looked into the code example, you are doing:
> 
> ```js
> const frames = await browser.$$('<iframe />');
> await browser.switchToFrame(frames[0]);
> ```
> 
> Which doesn't work and never worked before. Please see docs: https://webdriver.io/docs/api/webdriver.html#switchtoframe where the parameter is defined as
> 
> > one of three possible types: null: this represents the top-level browsing context (i.e., not an iframe), a Number, representing the index of the window object corresponding to a frame, a string representing an element id that can be received using findElement.
> 
> Therefor you need to do:
> 
> ```js
> await browser.switchToFrame(frames[0].elementId)
> ```
> 
> cc @mgrybyk

[0-0] 2019-08-20T14:41:37.683Z INFO webdriver: [POST] https://hub.browserstack.com:443/wd/hub/session/ea2415898be0d2552436e8d599f4e97eda89b1b2/elements
[0-0] 2019-08-20T14:41:37.683Z INFO webdriver: DATA { using: 'tag name', value: 'iframe' }
[0-0] 2019-08-20T14:41:38.617Z INFO webdriver: RESULT [ { ELEMENT: 'e9ffb389-a52e-4701-b6e2-62b211e59f9d',
    'element-6066-11e4-a52e-4f735466cecf': 'e9ffb389-a52e-4701-b6e2-62b211e59f9d' } ]
[0-0] 2019-08-20T14:41:38.622Z INFO webdriver: COMMAND switchToFrame("e9ffb389-a52e-4701-b6e2-62b211e59f9d")
[0-0] 2019-08-20T14:41:38.622Z INFO webdriver: [POST] https://hub.browserstack.com:443/wd/hub/session/ea2415898be0d2552436e8d599f4e97eda89b1b2/frame
[0-0] 2019-08-20T14:41:38.622Z INFO webdriver: DATA { id: 'e9ffb389-a52e-4701-b6e2-62b211e59f9d' }
[0-0] [0-0] 2019-08-20T14:41:39.283Z2019-08-20T14:41:39.283Z  WARNINFO  webdriverwebdriver: Request failed due to The specified frame was not found in the current frame or window.
: Retrying 1/3
2019-08-20T14:41:39.283Z INFO webdriver: [POST] https://hub.browserstack.com:443/wd/hub/session/ea2415898be0d2552436e8d599f4e97eda89b1b2/frame
[0-0] 2019-08-20T14:41:39.284Z INFO webdriver: DATA { id: 'e9ffb389-a52e-4701-b6e2-62b211e59f9d' }
[0-0] 2019-08-20T14:41:39.478Z WARN webdriver: Request failed due to The specified frame was not found in the current frame or window.
[0-0] 2019-08-20T14:41:39.478Z INFO webdriver: Retrying 2/3
[0-0] 2019-08-20T14:41:39.479Z INFO webdriver: [POST] https://hub.browserstack.com:443/wd/hub/session/ea2415898be0d2552436e8d599f4e97eda89b1b2/frame
[0-0] 2019-08-20T14:41:39.479Z INFO webdriver: DATA { id: 'e9ffb389-a52e-4701-b6e2-62b211e59f9d' }
[0-0] [0-0] 2019-08-20T14:41:39.661Z 2019-08-20T14:41:39.661ZINFO  WARNwebdriver webdriver: Retrying 3/3
: Request failed due to The specified frame was not found in the current frame or window.
[0-0] 2019-08-20T14:41:39.661Z INFO webdriver: [POST] https://hub.browserstack.com:443/wd/hub/session/ea2415898be0d2552436e8d599f4e97eda89b1b2/frame
[0-0] 2019-08-20T14:41:39.661Z INFO webdriver: DATA { id: 'e9ffb389-a52e-4701-b6e2-62b211e59f9d' }
[0-0] 2019-08-20T14:41:39.751Z ERROR webdriver: Request failed due to no such frame: The specified frame was not found in the current frame or window.
    at getErrorFromResponseBody (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/node_modules/webdriver/build/utils.js:215:10)
    at Request._callback (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/node_modules/webdriver/build/request.js:103:64)
    at Request.self.callback (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
[0-0] Error: { no such frame: The specified frame was not found in the current frame or window.
    at Context.it (/Users/yurii/WebstormProjects/wdio-edge-switchToFrame/test/test.js:12:21)
    at <anonymous> name: 'no such frame' }
[0-0] 2019-08-20T14:41:39.758Z INFO webdriver: COMMAND deleteSession()
[0-0] 2019-08-20T14:41:39.758Z INFO webdriver: [DELETE] https://hub.browserstack.com:443/wd/hub/session/ea2415898be0d2552436e8d599f4e97eda89b1b2
