### ISSUE TITLE
Firefox stuck on a page with server-sent event

### ISSUE THREAD

**Issue by emerikool** [webdriverio/webdriverio#440]
I'm testing a page using server-sent event. 
Everything works fine with chrome but on firefox, webdriverio is stuck just after the url command. 
Shuting down the sse server makes webdriverio continues the test.

Is there a workaround for this ?

Testing with mocha on ubuntu 14 and firefox 33, 34, 35 and 36.

**Comment by christian-bromann** [comment]
@emerikool could you provide some selenium logs?

**Comment by christian-bromann** [comment]
closing due to inactivity. If this problem still occurs feel free to reopen the issue. Cheers

**Comment by emerikool** [comment]
Sorry for the delay, the problem still occurs but I can't reopen it since you close it.

Here is the selenium logs:
```
10:38:47.139 INFO - Executing: [get: http://192.168.220.130:8080/umbrella/index.php/monitor])
10:38:48.732 INFO - Done: [get: http://192.168.220.130:8080/umbrella/index.php/monitor]
10:38:48.736 INFO - Executing: [set script timeoutt: 500])
10:39:02.126 INFO - Executing: [find element: By.selector: #monitoring-tabs a[href="#node-list"]])
10:39:17.772 INFO - Executing: [get: http://192.168.220.130:8080/umbrella/index.php/auth/logout])
10:39:17.794 INFO - Done: [set script timeoutt: 500]
10:39:17.797 INFO - Executing: [execute async script: return (function (selector, reverse) {

    var cb = arguments[arguments.length - 1],
        db = document.body,
        dde = document.documentElement;

    var documentDimension = {
        width: Math.max(db.scrollTop || 0, dde.scrollTop || 0, db.offsetwidth || 0, dde.offsetWidth || 0, db.clientWidth || 0, dde.clientWidth || 0),
        height: Math.max(db.scrollheight || 0, dde.scrollHeight || 0, db.offsetHeight || 0, dde.offsetHeight || 0, db.clientHeight || 0, dde.clientHeight || 0)
    };

    var interval = setInterval(function() {

        /**
         * query element in every interval in case it gets inserted into
         * the DOM
         */
        var elements = document.querySelectorAll(selector);

        for (var i = 0; i < elements.length; ++i) {
            var elem = elements[i],
                elemDimension = elem.getBoundingClientRect(),
                elemComputedStyle = window.getComputedStyle(elem);

            if (
                // check if element is visible
                (!reverse &&
                elemComputedStyle.display !== 'none' &&
                elemComputedStyle.visibility === 'visible' &&
                parseFloat(elemComputedStyle.opacity, 10) > 0 &&
                elemDimension.bottom >= 0 &&
                elemDimension.top <= documentDimension.height &&
                elemDimension.right >= 0 &&
                elemDimension.left <= documentDimension.width) ||
                // check if element is invisible
                (reverse &&
                (elemComputedStyle.display === 'none' ||
                elemComputedStyle.visibility === 'invisible' ||
                parseFloat(elemComputedStyle.opacity, 10) === 0 ||
                elemDimension.bottom < 0 ||
                elemDimension.top > documentDimension.height ||
                elemDimension.right < 0 ||
                elemDimension.left > documentDimension.width))) {
                window.clearInterval(interval);
                return cb(true);
            }
        }

    }, 100);
}).apply(null, arguments);, [#summary-info, false]])
10:39:17.820 INFO - Done: [find element: By.selector: #monitoring-tabs a[href="#node-list"]]
10:39:17.824 INFO - Executing: [click: 4 [[FirefoxDriver: firefox on LINUX (0d1272e4-1add-43b8-aae1-114c1fb2c94d)] -> css selector: #monitoring-tabs a[href="#node-list"]]])
10:39:18.295 INFO - Done: [get: http://192.168.220.130:8080/umbrella/index.php/auth/logout]
10:39:18.817 WARN - Exception thrown
org.openqa.selenium.TimeoutException: Timed out waiting for async script result after 501ms
Command duration or timeout: 521 milliseconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'ubuntu', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-24-generic', java.version: '1.7.0_65'
Session ID: 0d1272e4-1add-43b8-aae1-114c1fb2c94d
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=34.0}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
        at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:526)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
        at com.sun.proxy.$Proxy1.executeAsyncScript(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver.executeAsyncScript(EventFiringWebDriver.java:225)
        at org.openqa.selenium.remote.server.handler.ExecuteAsyncScript.call(ExecuteAsyncScript.java:55)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.TimeoutException: Timed out waiting for async script result after 501ms
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'ubuntu', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-24-generic', java.version: '1.7.0_65'
Driver info: driver.version: unknown
        at <anonymous class>.handleEvaluateEvent/timeoutId<(http://192.168.220.130:8080/umbrella/index.php/auth/login:75:1)
10:39:18.825 WARN - Exception: Timed out waiting for async script result after 501ms
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'ubuntu', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-24-generic', java.version: '1.7.0_65'
Driver info: driver.version: unknown
10:39:18.858 WARN - Exception thrown
org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
Command duration or timeout: 36 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'ubuntu', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-24-generic', java.version: '1.7.0_65'
Session ID: 0d1272e4-1add-43b8-aae1-114c1fb2c94d
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=34.0}]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
        at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:331)
        at com.sun.proxy.$Proxy2.click(Unknown Source)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.click(EventFiringWebDriver.java:344)
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:63)
        at com.sun.proxy.$Proxy3.click(Unknown Source)
        at org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:29)
        at org.openqa.selenium.remote.server.handler.ClickElement.call(ClickElement.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.StaleElementReferenceException: Element not found in the cache - perhaps the page has changed since it was looked up
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'ubuntu', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-24-generic', java.version: '1.7.0_65'
Driver info: driver.version: unknown
        at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web-element-cache.js:8329:1)
        at <anonymous class>.Utils.getElementAt(file:///tmp/anonymous2774245058298533827webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:7922:10)
        at <anonymous class>.fxdriver.preconditions.visible(file:///tmp/anonymous2774245058298533827webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:8957:11)
        at <anonymous class>.DelayedCommand.prototype.checkPreconditions_(file:///tmp/anonymous2774245058298533827webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11618:15)
        at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///tmp/anonymous2774245058298533827webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11635:11)
        at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///tmp/anonymous2774245058298533827webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11640:7)
        at <anonymous class>.DelayedCommand.prototype.execute/<(file:///tmp/anonymous2774245058298533827webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11582:5)
10:39:18.864 WARN - Exception: Element not found in the cache - perhaps the page has changed since it was looked up
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'ubuntu', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-24-generic', java.version: '1.7.0_65'
Driver info: driver.version: unknown
```
Cheers
