### ISSUE TITLE
Using Cucumber Tags on Multiple Examples Tables throws Error

### ISSUE THREAD

**Issue by pyxis828** [webdriverio/webdriverio#4405]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner:  sync
 - **Node.js version:** 10.16.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 76
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable): @wdio/spec reporter, @wdio/selenium-standalone service, @wdio/allure-reporter, @wdio/cucumber-framework, @wdio/cli, @wdio/sync

**Config of WebdriverIO**
```
exports.config={

    "specs": [
        //feature files
        "./features/Settings_General.feature",
        // './features/Setup.feature',
        // "./features/User.feature"
    ],
    "capabilities": [{
        "browserName": "chrome",
        "goog:chromeOptions": {
            args: ['--start-maximized', '--disable-browser-side-navigation',],
            excludeSwitches: ['enable-automation', 'load-extension']
        },
        "maxInstances": 1,
        "timeouts": {
            "implicit": 10000,
            "pageLoad": 30000
        }
    }],
    //trace, debug, info, warn, error, silent
    "logLevel": "warn",
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub',
    services: ['selenium-standalone'],
    seleniumLogs: 'logs',
    seleniumInstallArgs: {
        version : "3.9.1",
        baseURL : "https://selenium-release.storage.googleapis.com",
        drivers : {
          chrome : {
            version : "76.0.3809.68",
            arch    : process.arch,
            baseURL : "https://chromedriver.storage.googleapis.com",
          }
        }
      },
    framework: 'cucumber',
    cucumberOpts: {
        require: ['./steps/*.js'],        // <string[]> (file/dir) require files before executing features
        backtrace: false,   // <boolean> show full backtrace for errors
        compiler: [],       // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        dryRun: false,      // <boolean> invoke formatters without executing steps
        failFast: false,    // <boolean> abort the run on first failure
        format: ['pretty'], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        colors: true,       // <boolean> disable colors in formatter output
        snippets: true,     // <boolean> hide step definition snippets for pending steps
        source: true,       // <boolean> hide source URIs
        profile: [],        // <string[]> (name) specify the profile to use
        strict: false,      // <boolean> fail if there are any undefined or pending steps
        name: [],           // Only execute the scenarios with name matching the expression (repeatable)
        tagsInTitle: [],    //add tag to you feature name in reports
        // tagExpression: [],   // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: "@run",
        timeout: 1000000,      // <number> timeout for step definitions
        ignoreUndefinedDefinitions: false, // <boolean> Enable this config to treat undefined definitions as warnings.
    },
    reporters: ['spec',
        ['allure', {
        outputDir: './reports/allure-results',
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: true,
        useCucumberStepReporter: true
    }]
]  

}
```
**Describe the bug**
When adding multiple Examples tables to a scenario outline in order to add different tags to examples, when trying to run, it throws an error about "steps" being a property of an undefined variable. 

**To Reproduce**
Create a scenario outline  with 2 or more Examples tables, and add tags to the tables like:

Scenario Outline:  Search
Given the user is on the "google homepage"
When the user searches "<search_term>"
Then search results for "<search_term>" are displayed

@penguins
Examples:
| search_term |
| penguins      |

@bears 
Examples:
| search_term |
| polar bears   |
| brown bears |

**Expected behavior**
Expected to be able to add tags to example tables as above and then be able to run the scenario with selected tag.

**Log**
```0-0] 2019-08-26T15:37:36.069Z ERROR @wdio/runner: TypeError: Cannot read property 'steps' of undefined
    at CucumberEventListener.onTestCasePrepared (C:\Workspace\webdriverio-test\sf3_tests\node_modules\@wdio\cucumber-framework\build\cucumberEventListener.js:132:42)
    at EventEmitter.emit (events.js:203:15)
    at EventEmitter.emit (domain.js:448:20)
    at TestCaseRunner.emit (C:\Workspace\webdriverio-test\sf3_tests\node_modules\cucumber\lib\runtime\test_case_runner.js:85:27)
    at TestCaseRunner.emitPrepared (C:\Workspace\webdriverio-test\sf3_tests\node_modules\cucumber\lib\runtime\test_case_runner.js:127:10)
    at C:\Workspace\webdriverio-test\sf3_tests\node_modules\cucumber\lib\runtime\test_case_runner.js:208:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Workspace\webdriverio-test\sf3_tests\node_modules\cucumber\lib\runtime\test_case_runner.js:22:103)
    at _next (C:\Workspace\webdriverio-test\sf3_tests\node_modules\cucumber\lib\runtime\test_case_runner.js:24:194)
    at C:\Workspace\webdriverio-test\sf3_tests\node_modules\cucumber\lib\runtime\test_case_runner.js:24:364
    at new Promise (<anonymous>)
    at C:\Workspace\webdriverio-test\sf3_tests\node_modules\cucumber\lib\runtime\test_case_runner.js:24:97
    at TestCaseRunner.run (C:\Workspace\webdriverio-test\sf3_tests\node_modules\cucumber\lib\runtime\test_case_runner.js:228:7)
    at C:\Workspace\webdriverio-test\sf3_tests\node_modules\cucumber\lib\runtime\index.js:91:51
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Workspace\webdriverio-test\sf3_tests\node_modules\cucumber\lib\runtime\index.js:26:103)
0-0 worker error { name: 'TypeError',
  message: 'Cannot read property \'steps\' of undefined',
  stack:
   'TypeError: Cannot read property \'steps\' of undefined\n    at CucumberEventListener.onTestCasePrepared (C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\@wdio\\cucumber-framework\\build\\cucumberEventListener.js:132:42)\n    at EventEmitter.emit (events.js:203:15)\n    at EventEmitter.emit (domain.js:448:20)\n    at TestCaseRunner.emit (C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:85:27)\n    at TestCaseRunner.emitPrepared (C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:127:10)\n    at C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:208:14\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:22:103)\n    at _next (C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:194)\n    at C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:364\n    at new Promise (<anonymous>)\n    at C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:97\n    at TestCaseRunner.run (C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:228:7)\n    at C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\cucumber\\lib\\runtime\\index.js:91:51\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (C:\\Workspace\\webdriverio-test\\sf3_tests\\node_modules\\cucumber\\lib\\runtime\\index.js:26:103)' }
[0-0] FAILED in chrome - C:\Workspace\webdriverio-test\sf3_tests\features\Settings_General.feature
```

**Comment by gtilekar** [comment]
@pyxis828 can you check on latest version of wdio. I had similar issue and it was fixed in build 5.11.12

**Comment by pyxis828** [comment]
@gtilekar I just updated to version 5.12.3, and this fixed my issue, unfortunately it also killed my screenshots in my afterStep hook as "result" is now "undefined" as per this https://github.com/BorisOsipov/wdio-reportportal-reporter/issues/80  Sigh

**Comment by gtilekar** [comment]
I am using below code for screenshot after failure

afterStep: function (uri, feature, { error, result }) {
if(error) browser.takeScreenshot()
},

apparantly if the scripts passes error returns nothing.

**Comment by pyxis828** [comment]
@gtilekar Thanks, that is working for me -- when I tried logging "error" I was getting undefined, but my test was passing at the time;  I forced a failure, and got my screenshot.
