### ISSUE TITLE
lib/commands/ Exception-Handling, sessions are empty, timeoutsAsyncScript

### ISSUE THREAD

**Issue by SerkanSipahi** [webdriverio/webdriverio#441]
hi @christian-bromann 

##### Infos
webdriverio v2.4.5
webdrivercss v1.0.6

subscriber: @rojaro

##### First issue:
We are testing over Browserstack and sometimes contains the response object nothing, its undefined! Do you have any Exception-Handling for this without aborting the test script? I think that includes all commands :(
```
TypeError: Cannot read property 'value' of undefined
    at /srv/cu-next/node_modules/webdriverio/lib/commands/getTitle.js:43:37
```
The same Probem
```
/srv/cu-next/node_modules/webdriverio/lib/commands/endAll.js:29
            res.value.forEach(function(session) {
                      ^
TypeError: Cannot call method 'forEach' of undefined
```

##### Second issue:

The Session Object is always empty !?!?! What we do wrong?

```js
    client
        .init()
        .timeoutsAsyncScript(3000)
        .url('https://www.cu-camper.com')
        .webdrivercss('startpage'+setting.device_id, {
            name: 'main-wrapper'+setting.device_id,
            elem: '.main-wrapper'
        })
        .getTitle(function(error, title) {
            console.log('Title was: ' + title);
        })
        .getCssProperty('#footer', 'color', function(err, color) {
            console.log(color);
        })
        .sessions(function(err, sessions) {
            console.log('1 sessions', sessions);
        })
        .end()
        .sessions(function(err, sessions) {
            console.log('2 sessions', sessions);
        });
```

```
1 sessions { status: 0,
  orgStatusMessage: 'The command executed successfully.' }
==== next ====>
2 sessions { status: 0,
  orgStatusMessage: 'The command executed successfully.' }
```

##### Third issue:

What does that mean? 

```
Timed out waiting for an asynchronous script result after 2 ms (WARNING: The server did not provide any stacktrace information)
```

Solved but is that the right way?

```
    client
        .init()
        .timeoutsAsyncScript(3000) // this is the solution
        .url('https://www.cu-camper.com')
        ....
        ....
        ....

```

Information about: asynchronous script result after 2 ms...
http://stackoverflow.com/questions/11646586/unable-to-execute-selenium-asynchronous-script

**Comment by christian-bromann** [comment]
@SerkanSipahi 

> TypeError: Cannot read property 'value' of undefined
>     at /srv/cu-next/node_modules/webdriverio/lib/commands/getTitle.js:43:37

This happens when you don't get any result back. There seems to be an error executing that command on BrowserStack. Could you check the `error` argument?

> The Session Object is always empty !?!?! What we do wrong?

Seems that BrowserStack doesn't support that command on their cloud machines. Sauce Labs also has no support for these kind of command (session and session return nothing). Why do you need to know your session IDs?

> What does that mean?
> 
> Timed out waiting for an asynchronous script result after 2 ms (WARNING: The server did not provide any stacktrace information)

Selenium has a default timeout (2s) for async execute commands. If your script needs longer then this it will throw an error. The `timeoutsAsyncScript` allows you to manage this timeout.

**Comment by christian-bromann** [comment]
Closing due to inactivity. Feel free to reopen the issue if this is still a problem. Cheers
