### ISSUE TITLE
Navigation fails with "Execution context was destroyed"

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4443]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.5 
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **Browser name and version:** Chrome 76

**Config of WebdriverIO**
Add `devtools` package from master (pre-release version).
Then enable devtools: `automationProtocol: 'devtools'`

**Describe the bug**
Test fails after clicking on link

**To Reproduce**
```
describe("main suite", () => {
    beforeEach(() => {
        browser.url("https://webdriver.io/")
        console.log(browser.getTitle())
    })

    it("foobar test", () => {
        $(".nav-site a[href*='api']").click()
        console.log(browser.getTitle())

        $(".post a[href*='CONTRIBUTING']").click()
        console.log(browser.getTitle())
    })
})
```

**Expected behavior**
should work same as without `automationProtocol: 'devtools'`

**Log**
```
Execution context was destroyed, most likely because of a navigation.
    at Frame.<anonymous> (/e2e/node_modules/puppeteer-core/lib/helper.js:111:15)
    at Page.title (/e2e/node_modules/puppeteer-core/lib/Page.js:995:29)
    at Page.<anonymous> (/e2e/node_modules/puppeteer-core/lib/helper.js:112:23)
    at DevToolsDriver.getTitle (/e2e/node_modules/devtools/build/commands/getTitle.js:10:15)
    at Browser.<anonymous> (/e2e/node_modules/devtools/build/devtoolsdriver.js:83:47)
```

**Comment by christian-bromann** [comment]
Fixed by #4459
