### ISSUE TITLE
isDisplayed is not working as expected in headless mode

### ISSUE THREAD

**Issue by mgrybyk** [webdriverio/webdriverio#4447]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.5 
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10
 - **Browser name and version:** Chrome 76

**Config of WebdriverIO**
Add `devtools` package from master (pre-release version).
Then enable devtools: `automationProtocol: 'devtools'`

**Describe the bug**
isDisplayed is not working as expected in headless mode if element appeared outside of viewport.

**To Reproduce**
```
describe("main suite", () => {
    it("some test", () => {
        browser.url("http://guinea-pig.webdriver.io")

        browser.execute(function () {
            this.setTimeout(() => {
                const mySpan = this.document.createElement("span")
                mySpan.id = 'foobarTest'
                mySpan.innerText = 'displayed!'
                this.document.querySelector('body').appendChild(mySpan)
            }, 2000);
        })

        $('#foobarTest').waitForDisplayed(4000)
    })
})
```

**Expected behavior**
should work same as without `automationProtocol: 'devtools'` or same as without headless mode.

**Log**
```
2019-09-03T14:38:40.060Z INFO devtools: RESULT Error: Element with selector "#foobarTest" not found
    at DevToolsDriver.findElement (/Users/mygr/sources/e2e/node_modules/devtools/build/utils.js:99:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-09-03T14:38:40.858Z INFO devtools: COMMAND findElement("css selector", "#foobarTest")
2019-09-03T14:38:40.861Z INFO devtools: RESULT Error: Element with selector "#foobarTest" not found
    at DevToolsDriver.findElement (/Users/mygr/sources/e2e/node_modules/devtools/build/utils.js:99:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-09-03T14:38:41.657Z INFO devtools: COMMAND findElement("css selector", "#foobarTest")
2019-09-03T14:38:41.660Z INFO devtools: RESULT { 'element-6066-11e4-a52e-4f735466cecf': 'ELEMENT-1' }
2019-09-03T14:38:41.664Z INFO devtools: COMMAND isElementDisplayed("ELEMENT-1")
2019-09-03T14:38:41.668Z INFO devtools: RESULT false
2019-09-03T14:38:42.456Z INFO devtools: COMMAND isElementDisplayed("ELEMENT-1")
2019-09-03T14:38:42.459Z INFO devtools: RESULT false
2019-09-03T14:38:43.256Z INFO devtools: COMMAND isElementDisplayed("ELEMENT-1")
2019-09-03T14:38:43.279Z INFO devtools: RESULT false
2019-09-03T14:38:43.280Z INFO devtools: COMMAND takeScreenshot()
```

**Comment by mgrybyk** [comment]
it is fixed by the PR
