### ISSUE TITLE
Add HTML Reporter Throws Error

### ISSUE THREAD

**Issue by awhisler** [webdriverio/webdriverio#4450]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.11.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Platform name and version:** Appium/Xcode
 - **Additional wdio packages used (if applicable):** @rpii/wdio-html-reporter

**Config of WebdriverIO**
`reporters: ['spec',
        ['@rpii/wdio-html-reporter', {
            debug: true,
            outputDir: './reports/html-reports/',
            filename: 'report.html',
            reportTitle: 'Nutrien GFA',
            showInBrowser: true,
            // templateFilename: path.resolve(__dirname, '../src/wdio-html-reporter-alt-template.hbs'),            
        }
        ]
    ]`

**Describe the bug**
When I add the HTML Reporter, it throws an error. As soon as I remove the htmlreporter dependency and go back to just "spec" as the reporter, no errors occur.

`[0-0] 2019-09-03T17:25:52.904Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'default' of null
    at initialisePlugin (/Users/ali.whisler/nutrien-gfa/node_modules/@wdio/utils/build/initialisePlugin.js:41:19)
    at BaseReporter.initReporter (/Users/ali.whisler/nutrien-gfa/node_modules/@wdio/runner/build/reporter.js:198:51)
    at Array.map (<anonymous>)
    at new BaseReporter (/Users/ali.whisler/nutrien-gfa/node_modules/@wdio/runner/build/reporter.js:44:39)
    at Runner.run (/Users/ali.whisler/nutrien-gfa/node_modules/@wdio/runner/build/index.js:91:21)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)`

**Comment by christian-bromann** [comment]
Please report the issue in the [`wdio-html-reporter`](https://github.com/rpii/wdio-html-reporter) project. Cheers!
