### ISSUE TITLE
'browser.getLogs' unknown command:

### ISSUE THREAD

**Issue by AlexeyCL** [webdriverio/webdriverio#4526]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Node.js version:** 8.16
 - **NPM version:** 6.9
 - **Browser name and version:**Chrome 77
 - **Platform name and version:** MacOS
 - **Additional wdio packages used (if applicable):** 
  "@wdio/dot-reporter": "5.7.8",
        "@wdio/local-runner": "^5.13.1",
        "@wdio/selenium-standalone-service": "^5.12.1",
 "@wdio/allure-reporter": "^5.12.1",
        "@wdio/cli": "^5.12.5",
        "@wdio/mocha-framework": "^5.12.1",
        "@wdio/sync": "^5.12.3",

**Config of WebdriverIO**
selenium

**Describe the bug**
When calling 
```
browser.getLogs('browser')
```
appear following error:
 ERROR webdriver: Request failed due to Error: unknown command: session/bb3d82dbd3473e43c568efb90e8c1846/se/log

**To Reproduce**
```
browser.getLogs('browser').then(console.log)
```

**Log**

**Comment by christian-bromann** [comment]
> * **WebdriverIO version:** [e.g. 4.13.2]

Please update to v5 where this issue is fixed. We don't maintain v4 anymore.

**Comment by AlexeyCL** [comment]
@christian-bromann it is     "webdriverio": "^5.12.5"

**Comment by AlexeyCL** [comment]
> > * **WebdriverIO version:** [e.g. 4.13.2]
> 
> Please update to v5 where this issue is fixed. We don't maintain v4 anymore.

updated my issue. We'r using 5

**Comment by christian-bromann** [comment]
I was not able to reproduce this running either Chromedriver directly or via Selenium Standalone. What is your setup?

**Comment by AlexeyCL** [comment]
> I was not able to reproduce this running either Chromedriver directly or via Selenium Standalone. What is your setup?

Selenium Standalone service

**Comment by AlexeyCL** [comment]
@christian-bromann actually, I found 
```
With Chrome 75 the driver switched to w3c as default protocol where this command doesn't exist anymore. There is not really a replacement for it. You might want to use the @wdio/devtools-service to receive network and performance logs.
```
I suppose due to using chrome 76 I can't use getLogs

**Comment by mgrybyk** [comment]
@AlexeyCL works fine for me with chrome 77
```
const logTypes = browser.getLogTypes()
logTypes.forEach(logType => console.log(logType, browser.getLogs(logType)))
```

**Comment by AlexeyCL** [comment]
@mgrybyk @christian-bromann 
Now I tried to build a new project from scratch and browser.getLogs() doesn't works
my package.json:
```
"devDependencies": {
    "@wdio/cli": "^5.14.3",
    "@wdio/local-runner": "^5.14.3",
    "@wdio/mocha-framework": "^5.14.3",
    "@wdio/spec-reporter": "^5.13.2",
    "@wdio/sync": "^5.14.3",
    "@wdio/selenium-standalone-service": "^5.13.2",
    "webdriverio": "^5.14.3"
```
my wdio.conf.js:
```
exports.config = {

    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],

    maxInstances: 10,

    capabilities: [{

        maxInstances: 5,
        //
        browserName: 'chrome',

    }],

    bail: 0,

    baseUrl: 'http://localhost',

    waitforTimeout: 10000,

    connectionRetryTimeout: 90000,

    connectionRetryCount: 3,

    services: ['selenium-standalone'],


    framework: 'mocha',

    reporters: ['spec'],


    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },

}
```

**Comment by christian-bromann** [comment]
@AlexeyCL please always provide error messages with stack trace and log files otherwise _"doesn't works"_ doesn't mean anything

**Comment by mgrybyk** [comment]
@AlexeyCL I think it might happen because you are using outdated versions of chrome and chromedriver. 
By default selenium standalone uses some very very old chromedriver version

**Comment by AlexeyCL** [comment]
> @AlexeyCL please always provide error messages with stack trace and log files otherwise _"doesn't works"_ doesn't mean anything

@christian-bromann 
here is trace:
```
[0-0] 2019-10-02T12:45:11.130Z INFO @wdio/local-runner: Ignore message for worker: { origin: 'debugger',
    name: 'eval',
    content: { cmd: 'browser.getLogs(\'browser\')\n' } }
[0-0] 2019-10-02T12:45:11.132Z INFO webdriver: COMMAND getLogs("browser")
    [0-0] 2019-10-02T12:45:11.133Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/63559cddc69cafb8e891ef21be0fef90/se/log
    [0-0] 2019-10-02T12:45:11.133Z INFO webdriver: DATA { type: 'browser' }
[0-0] 2019-10-02T12:45:11.138Z DEBUG webdriver: request failed due to missing body
    [0-0] 2019-10-02T12:45:11.138Z WARN webdriver: Request failed due to unknown command: session/63559cddc69cafb8e891ef21be0fef90/se/log
    [0-0] 2019-10-02T12:45:11.139Z INFO webdriver: Retrying 1/3
    [0-0] 2019-10-02T12:45:11.139Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/63559cddc69cafb8e891ef21be0fef90/se/log
    [0-0] 2019-10-02T12:45:11.139Z INFO webdriver: DATA { type: 'browser' }
[0-0] 2019-10-02T12:45:11.142Z DEBUG webdriver: request failed due to missing body
    [0-0] 2019-10-02T12:45:11.142Z WARN webdriver: Request failed due to unknown command: session/63559cddc69cafb8e891ef21be0fef90/se/log
    [0-0] 2019-10-02T12:45:11.143Z INFO webdriver: Retrying 2/3
    [0-0] 2019-10-02T12:45:11.143Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/63559cddc69cafb8e891ef21be0fef90/se/log
    [0-0] 2019-10-02T12:45:11.143Z INFO webdriver: DATA { type: 'browser' }
[0-0] 2019-10-02T12:45:11.146Z DEBUG webdriver: request failed due to missing body
    [0-0] 2019-10-02T12:45:11.146Z WARN webdriver: Request failed due to unknown command: session/63559cddc69cafb8e891ef21be0fef90/se/log
    [0-0] 2019-10-02T12:45:11.146Z INFO webdriver: Retrying 3/3
    [0-0] 2019-10-02T12:45:11.147Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/63559cddc69cafb8e891ef21be0fef90/se/log
    [0-0] 2019-10-02T12:45:11.147Z INFO webdriver: DATA { type: 'browser' }
[0-0] 2019-10-02T12:45:11.150Z DEBUG webdriver: request failed due to missing body
    [0-0] 2019-10-02T12:45:11.150Z ERROR webdriver: Request failed due to Error: unknown command: session/63559cddc69cafb8e891ef21be0fef90/se/log
at getErrorFromResponseBody (  webdriverio-test/node_modules/webdriver/build/utils.js:168:12)
at Request._callback (  webdriverio-test/node_modules/webdriver/build/request.js:110:64)
at Request.self.callback (  webdriverio-test/node_modules/request/request.js:185:22)
at emitTwo (events.js:126:13)
at Request.emit (events.js:214:7)
at Request.<anonymous> (  webdriverio-test/node_modules/request/request.js:1161:10)
at emitOne (events.js:116:13)
at Request.emit (events.js:211:7)
at IncomingMessage.<anonymous> (  webdriverio-test/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:313:30)
[0-0] (node:86448) UnhandledPromiseRejectionWarning: TypeError: (0 , _serializeError.default) is not a function
at repl.eval (  webdriverio-test/node_modules/webdriverio/build/commands/browser/debug.js:69:44)
at WDIORepl._runCmd (  webdriverio-test/node_modules/@wdio/repl/build/index.js:59:14)
at webdriverio-test/node_modules/@wdio/repl/build/index.js:46:57
at webdriverio-test/node_modules/@wdio/sync/build/runFnInFiberContext.js:18:27
    [0-0] (node:86448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:86448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    [0-0] › browser.getLogs()
    [0-0] Error in "webdriver.io page should have the right title"
Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (  webdriverio-test/test/specs/basic.js)
[0-0] 2019-10-02T12:45:32.355Z INFO webdriver: COMMAND deleteSession()
    [0-0] 2019-10-02T12:45:32.355Z INFO webdriver: [DELETE] http://127.0.0.1:4444/wd/hub/session/63559cddc69cafb8e891ef21be0fef90
    2019-10-02T12:45:32.526Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
    [0-0] FAILED in chrome - /test/specs/basic.js
2019-10-02T12:45:32.527Z INFO @wdio/cli:launcher: Run onComplete hook
2019-10-02T12:45:32.527Z INFO @wdio/selenium-standalone-service: shutting down all browsers
```

**Comment by AlexeyCL** [comment]
@mgrybyk by default it uses the last version of chrome and chromedriver 76

**Comment by christian-bromann** [comment]
I think at this point the only thing that would help us is a reproducible exmaple.

**Comment by AlexeyCL** [comment]
@christian-bromann I build a new project according to webdriverio guide, but instead of chromedriver I use selenium-standalone service. Can I open a new issue with full description?

**Comment by mgrybyk** [comment]
@AlexeyCL no need, please specify chromedriver version for selenium standalone. 
It's 2.43 by default

**Comment by AlexeyCL** [comment]
@mgrybyk 
ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442})

**Comment by mgrybyk** [comment]
Yes, and by default it's old. 
You have to specify proper version. Please refer to docs

**Comment by WilliamNurmi** [comment]
Did you guys manage to fix or work around the issue? Despite updating chromedriver with `selenium-standalone install --drivers.chrome.version=77.0.3865.40` I'm still getting the same error when calling `browser.getLogs` or `browser.getLogTypes`:

```
Running: chrome (v77.0.3865.120) on Mac OS X
unknown command: session/eee7e97eebeba1d36e03d7ba5370e7fb/se/log
```

Package.json
```
"webdriverio": "^5.14.4",
"@wdio/selenium-standalone-service": "^5.13.2",
```

**Comment by christian-bromann** [comment]
@WilliamNurmi can you provide a minimal reproducible example?

**Comment by mgrybyk** [comment]
@WilliamNurmi its not enough to install chromedriver you should also use it.

**Comment by WilliamNurmi** [comment]
Thanks for the link! I came into the same conclusion myself this. For anyone else googling this issue and scrolling straight down this fixed `browser.getLogs` for me:

```
// wdio.conf.js
exports.config = {
  // ...
  services: ['selenium-standalone'],
  seleniumInstallArgs: {
    drivers: {
      chrome: {
        version: '77.0.3865.40',
        arch: process.arch,
        baseURL: 'https://chromedriver.storage.googleapis.com',
      },
    },
  },
  seleniumArgs: {
    drivers: {
      chrome: { version: '77.0.3865.40' },
    },
  },
  // ...
```
};

However, this version broke `sendKeys` (which can be worked around with `getActiveElement` and `elementSendKeys`)
