### ISSUE TITLE
Getting error: @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null

### ISSUE THREAD

**Issue by pk-saxena** [webdriverio/webdriverio#4538]
I am trying to run webdriverio tests using selenium grid.
**Environment:** 
WebdriverIO version: 5.11.0 
Mode: WDIO Testrunner (sync) 
Browser name and version: IE 11 
Host machine: Mac 10.13.6
 Windows machine: 64 bit windows server 2019 
selenium standalone: selenium-server-standalone-3.141.59.jar
 IE driver: 32 bit 3.14.0

**Config of WebdriverIO:**
host: 'windows machine ip',
port: 4444,
path: '/wd/hub',
specs: [${pathToTests}*.js],
deprecationWarnings: false,
maxInstances: 1,
capabilities: [
{
browserName: 'internet explorer',
version: 11,
platform: 'WINDOWS',
platformName: 'WINDOWS',
logLevel: debug,
'se:ieOptions': {
'ie.ensureCleanSession': true,
ignoreZoomSetting: true,
ignoreProtectedModeSettings: true
}
}
]
sync: true

**Issue Description:**
 Unable to execute webdriverio tests on IE using selenium grid. The browser itself is not launched.
My application is running locally on mac host port 3000. From Mac host, I have established reverse ssh tunnel to a windows machine hosted on aws.
I tested successfully that there is no issue with ssh tunnel since I can access my application on port 3000 inside windows machine. selenium grid is launched on windows machine.
When I trigger tests from my local mac host, I see an exception inside selenium hub.

**Selenium hub logs:** 
2019-09-26 12:48:17.446:WARN:osjs.HttpChannel:qtp21880137-15: /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"capabilities":{"alwaysMatch":{"browserName":"internet explorer","version":11,"platform":"WINDOWS","platformName":"WINDOWS","se:ieOptions":{"ie.ensureCleanSession":true,"ignoreZoomSetting":true,"ignoreProtectedModeSettings":true}},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"internet explorer","version":11,"platform":"WINDOWS","platformName":"WINDOWS","se:ieOptions":{"ie.ensureCleanSession":true,"ignoreZoomSetting":true,"ignoreProtectedModeSettings":true}}}

The test runner fails with error: `ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null`

**Selenium hub config:**
browserTimeout: 0

debug: false

host: 172.31.31.173

port: 5555

role: node

timeout: 1800

cleanUpCycle: 5000

maxSession: 5

capabilities: Capabilities {browserName: internet explorer, platform: WINDOWS, platformName: WINDOWS, seleniumProtocol: WebDriver, server:CONFIG_UUID: b626910a-b79d-4d5d-a431-87d..., version: 11}

downPollingLimit: 2

hub: http://localhost:4444/grid/register

id: http://172.31.31.173:5555

nodePolling: 5000

nodeStatusCheckTimeout: 5000

proxy: org.openqa.grid.selenium.proxy.DefaultRemoteProxy

register: true

registerCycle: 5000

remoteHost: http://172.31.31.173:5555

unregisterIfStillDownAfter: 60000

**Expected behavior :**
IE browser should get launched on running test

**Actual behavior:**
 Getting the exception mentioned above.

Any idea what could be the reason behind the exception?

**Comment by christian-bromann** [comment]
Please check the logs, it seems that the session couldn't be created.

**Comment by pk-saxena** [comment]
@christian-bromann Yes the session could not be created. I set the logLevel to `trace` and see the following output:
```
[0-0] 2019-09-26T15:24:35.058Z INFO webdriver: [POST] http://xx.xx.xxx.xxx:4444/wd/hub/session
[0-0] 2019-09-26T15:24:35.058Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { browserName: 'internet explorer',
        version: 11,
        platform: 'WINDOWS',
        platformName: 'WINDOWS',
        'se:ieOptions': [Object] },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { browserName: 'internet explorer',
     version: 11,
     platform: 'WINDOWS',
     platformName: 'WINDOWS',
     'se:ieOptions':
      { 'ie.ensureCleanSession': true,
        ignoreZoomSetting: true,
        ignoreProtectedModeSettings: true } } }
[0-0] 2019-09-26T15:24:35.160Z DEBUG webdriver: request failed due to missing body
[0-0] 2019-09-26T15:24:35.160Z ERROR webdriver: Request failed due to Error: Response has empty body
    at getErrorFromResponseBody (/Users/prateeksaxena/work/jobz_web_employer/node_modules/webdriver/build/utils.js:360:12)
    at Request._callback (/Users/prateeksaxena/work/jobz_web_employer/node_modules/webdriver/build/request.js:122:64)
    at Request.self.callback (/Users/prateeksaxena/work/jobz_web_employer/node_modules/request/request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (/Users/prateeksaxena/work/jobz_web_employer/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (/Users/prateeksaxena/work/jobz_web_employer/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:273:13)
[0-0] 2019-09-26T15:24:35.161Z ERROR @wdio/runner: Error: Response has empty body
    at getErrorFromResponseBody (/Users/prateeksaxena/work/jobz_web_employer/node_modules/webdriver/build/utils.js:360:12)
    at Request._callback (/Users/prateeksaxena/work/jobz_web_employer/node_modules/webdriver/build/request.js:122:64)
    at Request.self.callback (/Users/prateeksaxena/work/jobz_web_employer/node_modules/request/request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Request.<anonymous> (/Users/prateeksaxena/work/jobz_web_employer/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:182:13)
    at Request.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.<anonymous> (/Users/prateeksaxena/work/jobz_web_employer/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:273:13)
0-0 worker error { name: 'Error',
  message: 'Response has empty body',
  stack:
   'Error: Response has empty body\n    at getErrorFromResponseBody (/Users/prateeksaxena/work/jobz_web_employer/node_modules/webdriver/build/utils.js:360:12)\n    at Request._callback (/Users/prateeksaxena/work/jobz_web_employer/node_modules/webdriver/build/request.js:122:64)\n    at Request.self.callback (/Users/prateeksaxena/work/jobz_web_employer/node_modules/request/request.js:186:22)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:442:20)\n    at Request.<anonymous> (/Users/prateeksaxena/work/jobz_web_employer/node_modules/request/request.js:1163:10)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:442:20)\n    at IncomingMessage.<anonymous> (/Users/prateeksaxena/work/jobz_web_employer/node_modules/request/request.js:1085:12)\n    at Object.onceWrapper (events.js:273:13)' }
[0-0] 2019-09-26T15:24:35.162Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/Users/prateeksaxena/work/jobz_web_employer/node_modules/@wdio/runner/build/index.js:91:74)
```
I have also specified selenium hub logs in original query.

**Comment by mgrybyk** [comment]
@pk-saxena 
Hub doesn't support capabilities other than default. 
Remove version and platform from capabilities. 
It's documented here https://www.w3.org/TR/webdriver/#capabilities

**Comment by pk-saxena** [comment]
Thanks @mgrybyk for clearing that up for me.
