### ISSUE TITLE
REPL not working -  using selector.endpoints throws TypeError $(...).{endpoint} is not a function.

### ISSUE THREAD

**Issue by tobeliketree** [webdriverio/webdriverio#4562]
**Environment:**
 - **WebdriverIO version:** 5.13.2
 - **Mode:**  Testrunner
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Node.js version:**  v10.16.3
 - **NPM version:** 6.9.0
 - **Browser name and version:** 77.0.3865.90 (Official Build) (64-bit)
 - **Platform name and version:**  macOS 10.13.6
 - **Additional wdio packages used (if applicable):** 
    "@wdio/cli": "^5.14.3",
    "@wdio/local-runner": "^5.14.3",
    "@wdio/mocha-framework": "^5.14.3",
    "@wdio/spec-reporter": "^5.13.2",
    "@wdio/sync": "^5.14.3",
    "chromedriver": "^77.0.0",
    "wdio-chromedriver-service": "^5.0.2",
    "webdriverio": "^5.13.2"

**Config of WebdriverIO**
This is using a bare bones config using the Getting Started help documentation found [here.](https://webdriver.io/docs/gettingstarted.html)

**Describe the bug**
REPL is findings elements using $('#selector') but when you try and chain the element with an wdio endpoint like $('#selector').click();  it will thrown an error.   I am seeing this on .click() .getText(). isDisplayed() to name a few. 

`TypeError: $(...).click is not a function
    at evalmachine.<anonymous>:1:14
    at Script.runInContext (vm.js:133:20)
    at Object.runInContext (vm.js:311:6)
    at WDIORepl._runCmd (/Users/werk/Git_Repositories/webdriverio-test/node_modules/@wdio/repl/build/index.js:54:34)
    at /Users/werk/Git_Repositories/webdriverio-test/node_modules/@wdio/repl/build/index.js:46:57
    at /Users/werk/Git_Repositories/webdriverio-test/node_modules/@wdio/sync/build/runFnInFiberContext.js:18:27
`

**To Reproduce**
Using the getting started instructions or clone any of the wdio boilerplate projects like https://github.com/luuizeduardo/wdio-automation found [here](https://webdriver.io/docs/boilerplate.html). 

Step1
`npm install`

Step2
`./node_modules/.bin/wdio repl chrome`

Step3
`browser.url('https://www.google.com');`

Step4
Get selector for "I'm feeling lucky" button and try and click. 

`$('#gbqfbb').click();`

will return 

TypeError: $(...).click is not a function
    at evalmachine.<anonymous>:1:14
    at Script.runInContext (vm.js:133:20)
    at Object.runInContext (vm.js:311:6)
    at WDIORepl._runCmd (/Users/werk/Git_Repositories/webdriverio-test/node_modules/@wdio/repl/build/index.js:54:34)
    at /Users/werk/Git_Repositories/webdriverio-test/node_modules/@wdio/repl/build/index.js:46:57
    at /Users/werk/Git_Repositories/webdriverio-test/node_modules/@wdio/sync/build/runFnInFiberContext.js:18:27

I tried to to assign the selector to a variable but that had no impact. 

`let foo = $('#gbqfbb');`

`foo.click();`

TypeError: foo.click is not a function
    at evalmachine.<anonymous>:1:5
    at Script.runInContext (vm.js:133:20)
    at Object.runInContext (vm.js:311:6)
    at WDIORepl._runCmd (/Users/werk/Git_Repositories/webdriverio-test/node_modules/@wdio/repl/build/index.js:54:34)
    at /Users/werk/Git_Repositories/webdriverio-test/node_modules/@wdio/repl/build/index.js:46:57
    at /Users/werk/Git_Repositories/webdriverio-test/node_modules/@wdio/sync/build/runFnInFiberContext.js:18:27
› foo.getText();
Thrown:
evalmachine.<anonymous>:1
foo.getText();

Step5

I've confirmed that REPL will find the element. 

 $('#gbqfbb');
2019-10-03T13:19:38.452Z INFO webdriver: COMMAND findElement("css selector", "#gbqfbb")
2019-10-03T13:19:38.453Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/c282aa9b321ab9c5e760caec09ba8aca/element
2019-10-03T13:19:38.454Z INFO webdriver: DATA { using: 'css selector', value: '#gbqfbb' }
2019-10-03T13:19:38.483Z INFO webdriver: RESULT { ELEMENT: '0.1947180627275884-1' }
Element {
  sessionId: 'c282aa9b321ab9c5e760caec09ba8aca',
  elementId: '0.1947180627275884-1',
  ELEMENT: '0.1947180627275884-1',
  selector: '#gbqfbb',
  parent:
   Browser {
     sessionId: 'c282aa9b321ab9c5e760caec09ba8aca',
     capabilities:
      { acceptInsecureCerts: false,
        acceptSslCerts: false,
        applicationCacheEnabled: false,
        browserConnectionEnabled: false,
        browserName: 'chrome',
        chrome: [Object],
        cssSelectorsEnabled: true,
        databaseEnabled: false,
        'goog:chromeOptions': [Object],
        handlesAlerts: true,
        hasTouchScreen: false,
        javascriptEnabled: true,
        locationContextEnabled: true,
        mobileEmulationEnabled: false,
        nativeEvents: true,
        networkConnectionEnabled: false,
        pageLoadStrategy: 'normal',
        platform: 'Mac OS X',
        rotatable: false,
        setWindowRect: true,
        takesHeapSnapshot: true,
        takesScreenshot: true,
        unexpectedAlertBehaviour: '',
        version: '77.0.3865.90',
        webStorageEnabled: true,
        'webdriver.remote.sessionid': 'c282aa9b321ab9c5e760caec09ba8aca' },
     addCommand: [Function],
     overwriteCommand: [Function] },
  emit: [Function: bound ],
  isReactElement: false,
  addCommand: [Function],
  overwriteCommand: [Function] 

**Expected behavior**
REPL should find the element and allow you to pass the selector to an wdio endpoint for interaction.

**Comment by mcosta74** [comment]
I just started to play with `webdriverio` and facing the same issue. 
Does anyone know if there's a workaround (maybe installing older version)?

**Comment by mgrybyk** [comment]
Will try to let you know soon

**Comment by dirathea** [comment]
Hi! I saw this issue is already closed, and deployed to latest version of webdriverio.
but I still encounter this error..

@wdio/cli (v5.22.3)

on REPL console the error still occur
```bash
› $('//*[text()="LANJUT BELANJA"]').click()
2020-03-21T08:28:28.318Z INFO webdriver: COMMAND findElement("xpath", "//*[text()="LANJUT BELANJA"]")
2020-03-21T08:28:28.318Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/fbf124a90d9ea5e8dd6091ba1bef1d66/element
2020-03-21T08:28:28.318Z INFO webdriver: DATA { using: 'xpath', value: '//*[text()="LANJUT BELANJA"]' }
Thrown:
evalmachine.<anonymous>:1
$('//*[text()="LANJUT BELANJA"]').click()
                                  ^

TypeError: $(...).click is not a function
    at evalmachine.<anonymous>:1:35
    at Script.runInContext (vm.js:127:20)
    at Object.runInContext (vm.js:290:6)
    at WDIORepl._runCmd (/Users/aldiraraharja/.nvm/versions/node/v12.13.1/lib/node_modules/@wdio/cli/node_modules/@wdio/repl/build/index.js:54:34)
    at WDIORepl.eval (/Users/aldiraraharja/.nvm/versions/node/v12.13.1/lib/node_modules/@wdio/cli/node_modules/@wdio/repl/build/index.js:49:17)
    at REPLServer.config.eval (/Users/aldiraraharja/.nvm/versions/node/v12.13.1/lib/node_modules/@wdio/cli/node_modules/@wdio/repl/build/index.js:104:58)
    at bound (domain.js:419:14)
    at REPLServer.runBound [as eval] (domain.js:432:12)
    at REPLServer.onLine (repl.js:715:10)
    at REPLServer.emit (events.js:210:5)
› 2020-03-21T08:28:28.331Z INFO webdriver: RESULT { ELEMENT: '0.8178823193537632-1' }
```

is anything that I'm missed?

**Comment by christian-bromann** [comment]
> Should this dependency installed on cli, or just update the docs about this?

It should be up to the user to decide whether `@wdio/sync` is desired to be used or not. This is why we didn't made it a dependency of any package.

**Comment by dirathea** [comment]
Alright, I think I get it about not include `@wdio/sync` as dependency.
So it's a matter of documents then? Because the gif demo shows the sync command example, while on documentation there's no mention about this libs.

**Comment by christian-bromann** [comment]
We have it documented here: https://webdriver.io/docs/sync-vs-async.html
