### ISSUE TITLE
Unable to run script inside IE11 in Browserstack

### ISSUE THREAD

**Issue by vrockai** [webdriverio/webdriverio#4619]
**Environment (please complete the following information):**
 - **WebdriverIO version: ^5.15.0**
 - **Mode: WDIO Testrunner**
 - **If WDIO Testrunner, running: sync**
 - **Node.js version: v10.16.3**
 - **NPM version: 6.12.0**
 - **Browser name and version: IE11**
 - **Platform name and version: Windows 10**
 - **Additional wdio packages used (if applicable): @wdio/browserstack-service**

**Config of WebdriverIO**
https://github.com/vrockai/browserstack_ie11_error/blob/master/wdio.conf.js

**Describe the bug**
I'm unable to run a script with `browser.execute` inside IE11 in Browserstack. It throws an error. Unable to execute _any_ script, not even an empty function.

**To Reproduce**
Checkout the code from my repo:
https://github.com/vrockai/browserstack_ie11_error

To replicate the error:
1. Export ENV variables `BROWSER_STACK_USERNAME` and `BROWSER_STACK_ACCESS_KEY`.
2. `npm install`
3. `npm run wdio`

**Expected behavior**
The script should be executed and not errored out.

**Log**
```
[0-0] 2019-10-14T09:39:28.166Z ERROR webdriver: Request failed due to Error: JavaScript error
    at getErrorFromResponseBody (/home/vrockai/workspace/browsertstack_ie11_error/node_modules/webdriver/build/utils.js:175:10)
    at Request._callback (/home/vrockai/workspace/browsertstack_ie11_error/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/home/vrockai/workspace/browsertstack_ie11_error/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/home/vrockai/workspace/browsertstack_ie11_error/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/home/vrockai/workspace/browsertstack_ie11_error/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
```

**Comment by christian-bromann** [comment]
Can you provide browserstack logs?

**Comment by vrockai** [comment]
```
2019-10-14 9:39:19:411 REQUEST [2019-10-14 9:39:19:411] POST /session {"desiredCapabilities":{"browser":"IE","browser_version":"11.0","browserstack.local":true,"acceptSslCert":false,"detected_language":"webdriver/5.15.0"}}
2019-10-14 9:39:19:411 START_SESSION 
2019-10-14 9:39:19:411 REQUEST [2019-10-14 9:39:19:411] GET /session/c48d92e6d76529d86dddc85e6b0b907677f463be
2019-10-14 9:39:19:411 RESPONSE {"status":0,"sessionId":"c48d92e6d76529d86dddc85e6b0b907677f463be","value":{"browserAttachTimeout":0,"browserName":"internet explorer","cssSelectorsEnabled":true,"elementScrollBehavior":0,"enableElementCacheCleanup":true,"enablePersistentHover":true,"handlesAlerts":true,"ie.browserCommandLineSwitches":"","ie.ensureCleanSession":false,"ie.forceCreateProcessApi":false,"ie.usePerProcessProxy":false,"ignoreProtectedModeSettings":false,"ignoreZoomSetting":false,"initialBrowserUrl":"about:blank","javascriptEnabled":true,"nativeEvents":true,"platform":"WINDOWS","requireWindowFocus":false,"takesScreenshot":true,"unexpectedAlertBehaviour":"dismiss","version":"11","webdriver.remote.sessionid":"c48d92e6d76529d86dddc85e6b0b907677f463be"}}
2019-10-14 9:39:20:228 REQUEST [2019-10-14 9:39:20:228] POST /session/c48d92e6d76529d86dddc85e6b0b907677f463be/url {"url":"https://webdriver.io/"}
2019-10-14 9:39:27:360 RESPONSE {"sessionId":"c48d92e6d76529d86dddc85e6b0b907677f463be","status":0,"value":null}
2019-10-14 9:39:27:484 REQUEST [2019-10-14 9:39:27:484] POST /session/c48d92e6d76529d86dddc85e6b0b907677f463be/execute {"script":"return (() => {\n      // No contents needed\n    }).apply(null, arguments)","args":[]}
2019-10-14 9:39:27:537 RESPONSE {"sessionId":"c48d92e6d76529d86dddc85e6b0b907677f463be","status":17,"value":{"message":"JavaScript error","screen":"https://s3.amazonaws.com/testautomation/c48d92e6d76529d86dddc85e6b0b907677f463be/screenshot-35157c78b4.jpeg"}}
2019-10-14 9:39:27:660 REQUEST [2019-10-14 9:39:27:660] POST /session/c48d92e6d76529d86dddc85e6b0b907677f463be/execute {"script":"return (() => {\n      // No contents needed\n    }).apply(null, arguments)","args":[]}
2019-10-14 9:39:27:716 RESPONSE {"sessionId":"c48d92e6d76529d86dddc85e6b0b907677f463be","status":17,"value":{"message":"JavaScript error","screen":"https://s3.amazonaws.com/testautomation/c48d92e6d76529d86dddc85e6b0b907677f463be/screenshot-9c701360a4.jpeg"}}
2019-10-14 9:39:27:842 REQUEST [2019-10-14 9:39:27:842] POST /session/c48d92e6d76529d86dddc85e6b0b907677f463be/execute {"script":"return (() => {\n      // No contents needed\n    }).apply(null, arguments)","args":[]}
2019-10-14 9:39:27:891 RESPONSE {"sessionId":"c48d92e6d76529d86dddc85e6b0b907677f463be","status":17,"value":{"message":"JavaScript error","screen":"https://s3.amazonaws.com/testautomation/c48d92e6d76529d86dddc85e6b0b907677f463be/screenshot-60f797e735.jpeg"}}
2019-10-14 9:39:28:54 REQUEST [2019-10-14 9:39:28:54] POST /session/c48d92e6d76529d86dddc85e6b0b907677f463be/execute {"script":"return (() => {\n      // No contents needed\n    }).apply(null, arguments)","args":[]}
2019-10-14 9:39:28:145 RESPONSE {"sessionId":"c48d92e6d76529d86dddc85e6b0b907677f463be","status":17,"value":{"message":"JavaScript error","screen":"https://s3.amazonaws.com/testautomation/c48d92e6d76529d86dddc85e6b0b907677f463be/screenshot-6ffc96e273.jpeg"}}
2019-10-14 9:39:30:11 STOP_SESSION {"status":0,"sessionId":"c48d92e6d76529d86dddc85e6b0b907677f463be","value":{"message":"CLIENT_STOPPED_SESSION"},"errorStack":{}}
```

**Comment by wswebcreation** [comment]
@vrockai 

You are injecting an _arrow_ function into IE11, they don't support that, see https://github.com/vrockai/browserstack_ie11_error/blob/master/test/specs/basic.js#L8

**Comment by vrockai** [comment]
You are right @wswebcreation, thank you!
