### ISSUE TITLE
wdio --watch fails due to disconnected ${browser}driver

### ISSUE THREAD

**Issue by vobu** [webdriverio/webdriverio#4636]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12.x - 5.15.0
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** lts/dubnium (10.16.3)
 - **NPM version:** 6.9.0
 - **Browser name and version:** Chrome 77
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** 
   - "@wdio/local-runner": "^5.15.0",
    - "@wdio/mocha-framework": "^5.15.0",
    - "@wdio/selenium-standalone-service": "^5.15.0",
    - "@wdio/spec-reporter": "^5.14.5",
    - "@wdio/sync": "^5.14.4",
    - "chromedriver": "^77.0.0",
    - "wdio-chromedriver-service": "^5.0.2"

**Config of WebdriverIO**  
out-of-the-box default local runner config with `capabilities.browserName: 'chrome'` and `services: ['chromedriver']`

**Describe the bug**  
`wdio run wdio.conf.js --watch` (with the example test from https://webdriver.io/docs/gettingstarted.html) executes **fine on initial run**, then **fails on subsequent ones** due to 
```console
webdriver: Request failed due to Error: connect ECONNREFUSED 127.0.0.1:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[0-0] 2019-10-15T19:42:06.620Z ERROR @wdio/local-runner: Failed launching test session: Error: connect ECONNREFUSED 127.0.0.1:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
    at Runner.endSession (/Users/demo/node_modules/@wdio/runner/build/index.js:241:26)
[0-0] FAILED
```

When 
- `chromedriver --port=4444` is launched manually
- both `capabilities.browserName: 'chrome'` and `services: ['chromedriver']` are commented out,  
the behaviour is the same (fine on 1st run, fails on subsequent ones),  
but with a different error message:

first run:
```console
[0-0] 2019-10-15T19:46:27.917Z INFO webdriver: [DELETE] http://127.0.0.1:4444/session/8e03ec7d423abe05433dde25783ce0e7
2019-10-15T19:46:27.986Z INFO @wdio/local-runner: Waiting for 1 to shut down gracefully
[0-0] 2019-10-15T19:46:28.031Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'waitForSync' of undefined
    at Runner._shutdown (/Users/demo/node_modules/@wdio/runner/build/index.js:207:25)
    at Runner.endSession (/Users/demo/node_modules/@wdio/runner/build/index.js:254:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[0-0] FAILED
```

subsequent run:
```console
[undefined #0-0] invalid session id
[undefined #0-0] invalid session id
[undefined #0-0]     at Context.it (/Users/demo/test/specs/basic.js:48:17)
```

**_PLEASE NOTE_**  
With the above setup  
(`chromedriver` started manually, `wdio.conf.js` w/o any browser or service defs),  
but with `@wdio/cli` downgraded to `5.11.14`, **things work as expected**:  

> `wdio wdio.conf.js --watch`: 1st test runs fine, changes on `test/specs/**/*.js` trigger a re-run fine!

> With any version >`5.11.14`, the watch feature is broken (tested with the latest `5.(12,13,14)`.

_**BUT**_  
With the default setup  
(`wdio.conf.js` with `capabilities.browserName: 'chrome'` and `services: ['chromedriver']`),  
the watch task in `5.11.14` errors out similarly as with `5.15.0`,  
but not identical:
1st run is fine, subsequents runs yield:
```console
[0-0] 2019-10-15T19:57:33.685Z INFO webdriver: [POST] http://127.0.0.1:4444/session/7f70c675cdd07f54029e88cf2ef9dbf9/url
[0-0] 2019-10-15T19:57:33.685Z INFO webdriver: DATA { url: 'https://webdriver.io/' }
[0-0] 2019-10-15T19:57:33.712Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:4444
[0-0] 2019-10-15T19:57:33.712Z INFO webdriver: Retrying 1/3
[0-0] 2019-10-15T19:57:33.713Z INFO webdriver: [POST] http://127.0.0.1:4444/session/7f70c675cdd07f54029e88cf2ef9dbf9/url
[0-0] 2019-10-15T19:57:33.713Z INFO webdriver: DATA { url: 'https://webdriver.io/' }
[0-0] 2019-10-15T19:57:33.717Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:4444
[0-0] 2019-10-15T19:57:33.718Z INFO webdriver: Retrying 2/3
[0-0] 2019-10-15T19:57:33.718Z INFO webdriver: [POST] http://127.0.0.1:4444/session/7f70c675cdd07f54029e88cf2ef9dbf9/url
[0-0] 2019-10-15T19:57:33.718Z INFO webdriver: DATA { url: 'https://webdriver.io/' }
[0-0] 2019-10-15T19:57:33.720Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:4444
[0-0] 2019-10-15T19:57:33.721Z INFO webdriver: Retrying 3/3
[0-0] 2019-10-15T19:57:33.721Z INFO webdriver: [POST] http://127.0.0.1:4444/session/7f70c675cdd07f54029e88cf2ef9dbf9/url
[0-0] 2019-10-15T19:57:33.721Z INFO webdriver: DATA { url: 'https://webdriver.io/' }
[0-0] 2019-10-15T19:57:33.723Z ERROR webdriver: Request failed due to Error: connect ECONNREFUSED 127.0.0.1:4444
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[0-0] Error in "webdriver.io page should have the right title"
connect ECONNREFUSED 127.0.0.1:4444

 "spec" Reporter:
------------------------------------------------------------------
[chrome #0-0] Spec: /Users/demo/test/specs/basic.js
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0] webdriver.io page
[chrome #0-0]    ✖ should have the right title
[chrome #0-0]
[chrome #0-0] 1 failing (67ms)
[chrome #0-0]
[chrome #0-0] 1) webdriver.io page should have the right title
[chrome #0-0] connect ECONNREFUSED 127.0.0.1:4444
[chrome #0-0] Error: connect ECONNREFUSED 127.0.0.1:4444
[chrome #0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[chrome #0-0]     at Context.it (/Users/demo/test/specs/basic.js:50:17)
```

**=> SUMMARY**
- `@wdio/cli` `5.11.14` `--watch` works fine with manual `chromedriver` start and no browser and services entry in `wdio.conf.js`
-  `@wdio/cli` `5.11.14` `--watch` errors with default `wdio.conf.js` (`chrome`, service `chromedriver`)
- `@wdio/cli` `5.12.x` - `5.15.0` `--watch` is broken both with manual `driver` start and default default `wdio.conf.js` (`chrome`, service `chromedriver`)

**To Reproduce**
```bash
$> npm i @wdio/cli

$> node_modules/.bin/wdio config #choose default local options

# create test/specs/basic.js w/ test code sample from https://webdriver.io/docs/gettingstarted.html

$> node_modules/.bin/wdio run wdio.conf.js --watch
```

only working version:
```bash
$> brew install chromedriver

$> chromedriver --port=4444

# open new shell
$> npm i @wdio/cli@5.11.14

# edit wdio.conf.js and comment out capabilities.browserName and services

$> node_modules/.bin/wdio wdio.conf.js --watch
```

**Expected behavior**  
With all the defaults for a local test env and wdio runner in place, `--watch` should trigger a rerun upon save on any `test/specs/**/*.js`

**Comment by mgrybyk** [comment]
gonna be fixed with the PR and released afterwards, cheers!

**Comment by vobu** [comment]
just confirming that `@wdio/cli@5.15.1` fixed this, hooray 👍

**Comment by mgrybyk** [comment]
Glad to hear that!
