### ISSUE TITLE
How to run webdriver-io Getting started example on firefox?

### ISSUE THREAD

**Issue by elfia** [webdriverio/webdriverio#4642]
**Describe your question with as much detail as possible**
I can't run the getting started example with firefox :(. Chrome runs and test completes, but Firefox won't even start. I have both - firefox and chrome installed on my machine

**Environment (please complete the following information):**
 - **WebdriverIO version:** ^1.0.2
 - **Node.js version:** v9.2.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Firefox 69.0.3
 - **Platform name and version:** macOS Mojave 10.14.1 
 - **Additional wdio packages used (if applicable):**"geckodriver": "^1.19.0",
    "wdio-geckodriver-service": "^1.0.2"

package.json
```
"devDependencies": {
    "@wdio/cli": "^5.15.0",
    "@wdio/local-runner": "^5.15.0",
    "@wdio/mocha-framework": "^5.15.0",
    "@wdio/spec-reporter": "^5.14.5",
    "@wdio/sync": "^5.14.4",
    "chromedriver": "^77.0.0",
    "geckodriver": "^1.19.0",
    "wdio-chromedriver-service": "^5.0.2",
    "wdio-geckodriver-service": "^1.0.2"
  }
```

wdio.conf.js
```
exports.config = {
  runner: 'local',
  path: '/',
  specs: [
    './test/specs/**/*.js'
  ],
  exclude: [
  ],
  maxInstances: 10,
  capabilities: [{
    maxInstances: 5,
    browserName: 'firefox',
  }],
  logLevel: 'info',
  bail: 0,
  baseUrl: 'http://localhost',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  services: ['geckodriver'],
  framework: 'mocha',
  reporters: ['spec'],
  mochaOpts: {
    ui: 'bdd',
    timeout: 60000
  },
}
```

Error:
```
[0-0] 2019-10-16T15:58:22.366Z INFO webdriver: Retrying 3/3
[0-0] 2019-10-16T15:58:22.366Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
[0-0] 2019-10-16T15:58:22.366Z INFO webdriver: DATA { capabilities: { alwaysMatch: { browserName: 'firefox' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'firefox' } }
[0-0] 2019-10-16T15:58:22.368Z ERROR webdriver: Request failed due to Error: HTTP method not allowed
    at getErrorFromResponseBody (/Users/ehristova/work/webdriverio-test/node_modules/webdriver/build/utils.js:168:12)
    at Request._callback (/Users/ehristova/work/webdriverio-test/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/ehristova/work/webdriverio-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/ehristova/work/webdriverio-test/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/ehristova/work/webdriverio-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
[0-0] 2019-10-16T15:58:22.368Z ERROR @wdio/runner: Error: HTTP method not allowed
    at getErrorFromResponseBody (/Users/ehristova/work/webdriverio-test/node_modules/webdriver/build/utils.js:168:12)
    at Request._callback (/Users/ehristova/work/webdriverio-test/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/ehristova/work/webdriverio-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/ehristova/work/webdriverio-test/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/ehristova/work/webdriverio-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
0-0 worker error { name: 'Error',
  message: 'HTTP method not allowed',
  stack: 'Error: HTTP method not allowed\n    at getErrorFromResponseBody (/Users/ehristova/work/webdriverio-test/node_modules/webdriver/build/utils.js:168:12)\n    at Request._callback (/Users/ehristova/work/webdriverio-test/node_modules/webdriver/build/request.js:110:64)\n    at Request.self.callback (/Users/ehristova/work/webdriverio-test/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:159:13)\n    at Request.<anonymous> (/Users/ehristova/work/webdriverio-test/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:159:13)\n    at IncomingMessage.<anonymous> (/Users/ehristova/work/webdriverio-test/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:254:19)\n    at IncomingMessage.emit (events.js:164:20)\n    at endReadableNT (_stream_readable.js:1054:12)' }
[0-0] 2019-10-16T15:58:22.369Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/Users/ehristova/work/webdriverio-test/node_modules/@wdio/runner/build/index.js:68:74)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[0-0] FAILED in firefox - /test/specs/basic.js
2019-10-16T15:58:22.380Z INFO @wdio/cli:launcher: Run onComplete hook
```

What am I missing?

**Comment by mgrybyk** [comment]
It's known issue, gonna be fixed in next release. That happens because path in wdio config is ignored. 
Anyway I'd not recommend using gecko driver service because it doesn't support parallel test execution. 

If you need running tests in chrome and firefox it's way better to use selenium standalone service that works just fine in both cases

**Comment by mgrybyk** [comment]
https://github.com/webdriverio/webdriverio/pull/4637
