### ISSUE TITLE
Unknown capability name in Firefox

### ISSUE THREAD

**Issue by ilyubin** [webdriverio/webdriverio#4717]
We run tests with `name` field in capabilities. In Chrome it works fine.

But in FireFox I've got error:
```
0-0 worker error { name: 'invalid argument',
  message:
   'name is not the name of a known capability or extension capability',
  stack:
   'invalid argument: name is not the name of a known capability or extension capability\n    at getErrorFromResponseBody (/Users/ilyubin/go/src/gitlab.ozon.ru/bx-fe/ui-tests/node_modules/webdriver/build/utils.js:175:10)\n    at Request._callback (/Users/ilyubin/go/src/gitlab.ozon.ru/bx-fe/ui-tests/node_modules/webdriver/build/request.js:110:64)\n    at Request.self.callback (/Users/ilyubin/go/src/gitlab.ozon.ru/bx-fe/ui-tests/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at Request.<anonymous> (/Users/ilyubin/go/src/gitlab.ozon.ru/bx-fe/ui-tests/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:182:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at IncomingMessage.<anonymous> (/Users/ilyubin/go/src/gitlab.ozon.ru/bx-fe/ui-tests/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:273:13)' }
[0-0] FAILED in firefox - /src/specs/cart/add-to-favorites.spec.ts
```
My wdio config:
```
  hostname: cfg.MOON_HOST,
  port: Number(cfg.MOON_PORT),
  capabilities: [
    {
      maxInstances: 50,
      browserName: 'firefox',
      name: cfg.CI_JOB_URL, // <--------- Problem with this field
    },
  ],
```
This field we need for debug tests in moon:
https://aerokube.com/moon/latest/#_custom_test_name_name

*Question* can you fix it?

**Environment:**
 - **WebdriverIO version:**
```
    "@wdio/allure-reporter": "^5.6.3",
    "@wdio/browserstack-service": "^5.7.2",
    "@wdio/cli": "^5.6.3",
    "@wdio/concise-reporter": "^5.7.8",
    "@wdio/devtools-service": "^5.13.2",
    "@wdio/dot-reporter": "^5.6.0",
    "@wdio/local-runner": "^5.6.3",
    "@wdio/mocha-framework": "^5.6.3",
    "@wdio/spec-reporter": "^5.6.0",
    "@wdio/sync": "^5.6.3",
```

 - **Node.js version:** v10.15.0
 - **NPM version:** 6.11.3
 - **Browser name and version:** 
```
      os: 'Windows',
      os_version: '10',
      resolution: '1440x900',
      browserName: 'chrome',
      browserVersion: '73.0',
```

**Comment by mgrybyk** [comment]
Well, name is not w3c capability, you may add vendor prefix if you like. See https://www.w3.org/TR/webdriver/#capabilities

**Comment by ilyubin** [comment]
vendor prefix? what is that?
why in Chrome `name` capability works?

**Comment by mgrybyk** [comment]
See link above, this is how webdriver protocol works.

**Comment by mgrybyk** [comment]
https://www.w3.org/TR/webdriver/#dfn-extension-capability

You may add whatever you like, ex moon:name

**Comment by ilyubin** [comment]
```
  capabilities: [
    {
      maxInstances: 50,
      // screenResolution: '1440x900',
      browserName: 'firefox',
      'moon:name': cfg.CI_JOB_URL,
    },
  ],
```
it not works, moon do not catch this. 
And here in moon interface, I do not see the name
https://screencast.com/t/qxtjLVGk2F

**Comment by mgrybyk** [comment]
Great news @ilyubin 

Did you get that from moon docs?

**Comment by mgrybyk** [comment]
Ah, I see
