### ISSUE TITLE
android and browser in multiremote configuration,  maxInstances illegal key

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#4725]
**Describe your question with as much detail as possible**
Multiremote chrome and android keys 
`'Illegal key values seen in w3c capabilities: [deviceName, maxInstances]',`

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.9.1]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Additional context**

```
var wdioConfig = { config: {
    capabilities: {
        browser: { capabilities: { browserName: 'chrome' } },
        androidClient:
            { capabilities:
                 
                {
                platformName: 'android',
                maxInstances: 1,
                deviceName: process.env.ANDROID_DEVICE,
                'appium:automationName': "Espresso",
                'appium:nativeWebScreenshot': true,
                'appium:appActivity': "com.here.hnod.app.MainActivity",
                'appium:appPackage': process.env.ANDROID_APP_PACKAGE,
                'appium:autoWebview': true,
                'appium:autoGrantPermissions': true,
                'appium:clearSystemFiles': true,
                'appium:newCommandTimeout': 300000,
                }}
    },
```

trying to run and the following error is raised

```
$ yarn test:cucumber
yarn run v1.13.0
$ yarn clean && yarn build && wdio wdio.conf.js
$ rimraf build
$ tsc -p tsconfig.json

Execution of 1 spec files started at 2019-11-04T10:05:41.466Z

[0-0] RUNNING in MultiRemote - /features/multiremote.feature
0-0 worker error { name: 'unknown error',
  message:
   'Illegal key values seen in w3c capabilities: [deviceName, maxInstances]',
  stack:
   'unknown error: Illegal key values seen in w3c capabilities: [deviceName, maxInstances]\n    at getErrorFromResponseBody (/Users/x/webdriverio-test/node_modules/webdriver/build/utils.js:175:10)\n    at Request._callback (/Users/x/webdriverio-test/node_modules/webdriver/build/request.js:110:64)\n    at Request.self.callback (/Users/x/webdriverio-test/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:189:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at Request.<anonymous> (/Users/x/webdriverio-test/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:189:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at IncomingMessage.<anonymous> (/Users/x/webdriverio-test/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:277:13)' }
```

**Comment by mgrybyk** [comment]
@fege

```
        androidClient: {
            maxInstances: 1, // move it here
            capabilities: {
                platformName: 'android',
                deviceName: process.env.ANDROID_DEVICE,
            }
}
```

**Comment by fege** [comment]
@mgrybyk  thanks a lot
