### ISSUE TITLE
wdio --watch fails 

### ISSUE THREAD

**Issue by nothingismagick** [webdriverio/webdriverio#4761]
Possibly related to: https://github.com/webdriverio/webdriverio/issues/4748

**Environment:**
 - **WebdriverIO version:** 5.16.4
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** [async]
 - **Node.js version:** 10.17.0
 - **NPM version:** 6.11.3
 - **Browser name and version:** Chrome, Firefox, Safari
 - **Platform name and version:** MacOS 10.12
 - **Additional wdio packages used (if applicable):** @wdio/spec-reporter, @wdio/selenium-standalone-service, a few others - but notably, I am not using cucumber
 
**Config of WebdriverIO**
I am using a local selenium server, video reporter, image-comparison, jasmine, spec reporter, allure reporter.

**Describe the bug**
The first run works as expected, tests pass or fail like they are written. But when I change a spec, wdio throws a type error.

**To Reproduce**
$ wdio wdio.conf.js --watch

**Expected behavior**
I would not expect that anything related to cucumber would be hooking. On a hunch I replaced 
```
function isCucumberFeatureWithLineNumber(patterns) {
  return patterns.find(pattern => pattern.includes(':'));
} 
```
in `node_modules/@wdio/config/build/utils.js` with:
```
function isCucumberFeatureWithLineNumber(patterns) {
  return;
} 
```
And I was magically able to watch files and the `--watch` flag became usable.

**Additional context**
Stack trace for just chrome:
```
2019-11-09T11:02:43.782Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js,--watch
[0-0] 2019-11-09T11:02:44.603Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2019-11-09T11:02:44.770Z ERROR @wdio/local-runner: Failed launching test session: TypeError: patterns.find is not a function
    at isCucumberFeatureWithLineNumber ([redacted]/node_modules/@wdio/config/build/utils.js:42:19)
    at ConfigParser.merge ([redacted]/node_modules/@wdio/config/build/lib/ConfigParser.js:79:73)
    at Runner.run ([redacted]/node_modules/@wdio/runner/build/index.js:64:23)
    at process.on.m [redacted]/node_modules/@wdio/local-runner/build/run.js:37:20)
    at process.emit (events.js:203:15)
    at process.EventEmitter.emit (domain.js:448:20)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[0-0] FAILED in chrome - /test/validation.spec.js
```

**Comment by mgrybyk** [comment]
@nothingismagick you are right, it's a regression

**Comment by mgrybyk** [comment]
gonna be fixed with the PR
