### ISSUE TITLE
@wdio/cli (v5.16.7) Error: something went wrong during setup: null

### ISSUE THREAD

**Issue by cdesch** [webdriverio/webdriverio#4781]
**Environment (please complete the following information):**
 - **WebdriverIO version:** webdriverio@5.16.7
 - **Mode:** CLI
 - **Node.js version:** v12.6.0
 - **NPM version:** 6.13.0
 - **Platform name and version:** MacOS 10.14.6
 - **Additional wdio packages used (if applicable):** @wdio/cli (v5.16.7)

**Describe the bug**
Run `./node_modules/.bin/wdio` in a new project to create the run configuration `wdio.config.js` file. After setting up the config, the command errors out and does not create `wdio.config.js`

**To Reproduce**

run `./node_modules/.bin/wdio`

Results in

**Expected behavior**

Expected to produce `wdio.config.js` and not error out

**Log**
```
cjs-MBP15:my_project cj$ ./node_modules/.bin/wdio config

=========================
WDIO Configuration Helper
=========================

? Where should your tests be launched? local
? Where is your automation backend located? On my local machine
? Which framework do you want to use? jasmine
? Do you want to run WebdriverIO commands synchronous or asynchronous? sync
? Where are your test specs located? ./test/specs/**/*.js
? Which reporter do you want to use? spec
? Do you want to add a service to your test setup? appium
? What is the base url? http://localhost
/bin/sh: appium: command not found

Installing wdio packages:
- @wdio/local-runner
- @wdio/jasmine-framework
- @wdio/spec-reporter
- @wdio/appium-service
- @wdio/sync
- appium
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated core-js@2.6.5: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated github@9.3.1: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated topo@1.1.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated uws@8.14.0: New code is available at github.com/uNetworking/uWebSockets.js
npm WARN notsup Unsupported engine for fibers_node_v8@3.1.5: wanted: {"node":">=8.0.0 <10.0.0"} (current: {"node":"12.6.0","npm":"6.13.0"})
npm WARN notsup Not compatible with your version of node/npm: fibers_node_v8@3.1.5

npm ERR! code EISGIT
npm ERR! path /Users/cj/WebstormProjects/my_project/node_modules/react-native-push-notification
npm ERR! git /Users/cj/WebstormProjects/my_project/node_modules/react-native-push-notification: Appears to be a git repo or submodule.
npm ERR! git     /Users/cj/WebstormProjects/my_project/node_modules/react-native-push-notification
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cj/.npm/_logs/2019-11-15T05_05_34_897Z-debug.log
wdio config

Initialize WebdriverIO and setup configuration in your current project.

Options:
  --version             Show version number                            [boolean]
  --watch               Run WebdriverIO in watch mode                  [boolean]
  --hostname, -h        automation driver host address                  [string]
  --port, -p            automation driver port                          [number]
  --path                path to WebDriver endpoints (default /wd/hub)   [string]
  --user, -u            username if using a cloud service as automation backend
                                                                        [string]
  --key, -k             corresponding access key to the user            [string]
  --logLevel, -l        level of logging verbosity
                  [choices: "trace", "debug", "info", "warn", "error", "silent"]
  --bail                stop test runner after specific amount of tests have
                        failed                                          [number]
  --baseUrl             shorten url command calls by setting a base url [string]
  --waitforTimeout, -w  timeout for all waitForXXX commands             [number]
  --framework, -f       defines the framework (Mocha, Jasmine or Cucumber) to
                        run the specs                                   [string]
  --reporters, -r       reporters to print out the results on stdout     [array]
  --suite               overwrites the specs attribute and runs the defined
                        suite                                            [array]
  --spec                run only a certain spec file - overrides specs piped
                        from stdin                                       [array]
  --exclude             exclude certain spec file from the test run - overrides
                        exclude piped from stdin                         [array]
  --mochaOpts           Mocha options
  --jasmineNodeOpts     Jasmine options
  --cucumberOpts        Cucumber options
  --yarn                Install packages via yarn package manager.
                                                      [boolean] [default: false]
  --yes, -y             will fill in all config defaults without prompting
                                                      [boolean] [default: false]
  --help                Show help                                      [boolean]

Documentation: https://webdriver.io
@wdio/cli (v5.16.7)

Error: something went wrong during setup: null
    at runConfig (/Users/cj/WebstormProjects/my_project/node_modules/@wdio/cli/build/commands/config.js:79:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Object.handler (/Users/cj/WebstormProjects/my_project/node_modules/@wdio/cli/build/commands/config.js:116:5)
    at Object.handler (/Users/cj/WebstormProjects/my_project/node_modules/@wdio/cli/build/commands/config.js:118:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Log Dump:  https://gist.github.com/cdesch/19705f2bebdcce143c1fcd8907496955

**Comment by cdesch** [comment]
Removing the package `react-native-push-notification` fixed the issue

`yarn remove react-native-push-notification`
