### ISSUE TITLE
how do I use wdio-cucumberjs-json-reporter in Multiremote

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#4784]
**Describe your question with as much detail as possible**
Be able to use https://webdriver.io/docs/wdio-cucumberjs-json-reporter.html in multiremote scenario

**If it's about a specific piece of code, try and include some of it to support your question.**
following the example I added `cjson:metadata` in both of the browsers 

```
capabilities: {
        webClient: {
            maxInstances: 1, 
            browserName: 'chrome',
            capabilities: { 
                browserName: 'chrome',
                'cjson:metadata': {
                  browser: {
                      name: 'chrome',
                      version: '58',
                  },
              }
            }},
        androidClient: { 
            maxInstances: 1,
            port: appiumPort,
            platformName: 'android',
            browserName: 'android',
            capabilities:
                {
                ......
                'cjson:metadata': {
                  device: process.env.ANDROID_DEVICE,
                  app: {name: path.resolve(process.env.ANDROID_APP_PATH)},
                }
            }
```

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.9.1]
 - **NPM version:** [e.g. 5.8.0]
 - **Browser name and version:** [e.g. Chrome 68]
 - **Platform name and version:** [e.g. Windows 10]
 - **Additional wdio packages used (if applicable):** "wdio-cucumberjs-json-reporter": "^1.1.2"

**Additional context**
from this page https://webdriver.io/docs/wdio-cucumberjs-json-reporter.html
I defined the reporter

```
 reporters: [
      [ 'cucumberjs-json', { 
        jsonFolder: "./build/reports/",
        },
      ]]
```

**logs**
```

2019-11-18T13:10:07.392Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { 'goog:chromeOptions': [Object],
        browserName: 'chrome',
        'cjson:metadata': [Object] },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { 'goog:chromeOptions': { args: [Array] },
     browserName: 'chrome',
     'cjson:metadata': { browser: [Object] } } }
2019-11-18T13:10:07.398Z INFO webdriverio: Initiate new session using the webdriver protocol
2019-11-18T13:10:07.399Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
2019-11-18T13:10:07.399Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { 'appium:automationName': 'Espresso',
        'appium:nativeWebScreenshot': true,
        'appium:forceEspressoRebuild': true,
        'appium:appActivity': 'com.here.hnod.app.MainActivity',
        'appium:autoWebview': true,
        'appium:autoGrantPermissions': true,
        'appium:clearDeviceLogsOnStart': true,
        'appium:newCommandTimeout': 300000,
        'appium:deviceName': 'Samsung',
        'appium:app': '/Users/mosca/Downloads/app-internal-_node_-debug-2.apk',
        'appium:browserName': 'android',
        'cjson:metadata': [Object] },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { 'appium:automationName': 'Espresso',
     'appium:nativeWebScreenshot': true,
     'appium:forceEspressoRebuild': true,
     'appium:appActivity': 'com.here.hnod.app.MainActivity',
     'appium:autoWebview': true,
     'appium:autoGrantPermissions': true,
     'appium:clearDeviceLogsOnStart': true,
     'appium:newCommandTimeout': 300000,
     'appium:deviceName': 'Samsung',
     'appium:app': '/Users/mosca/Downloads/app-internal-_node_-debug-2.apk',
     'appium:browserName': 'android',
     'cjson:metadata':
      { device: 'Samsung',
        platform: [Object],
        app: [Object],
        browser: [Object] } } }
2019-11-18T13:10:28.653Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'cjson:metadata' of undefined
    at Object.determineMetadata (/Users/mosca/runtime/test/system/node_modules/wdio-cucumberjs-json-reporter/build/metadata.js:45:45)
    at CucumberJsJsonReporter.onRunnerStart (/Users/mosca/runtime/test/system/node_modules/wdio-cucumberjs-json-reporter/build/reporter.js:86:49)
    at CucumberJsJsonReporter.WDIOReporter.on.runner (/Users/mosca/runtime/test/system/node_modules/@wdio/reporter/build/index.js:64:12)
    at CucumberJsJsonReporter.emit (events.js:189:13)
    at CucumberJsJsonReporter.EventEmitter.emit (domain.js:441:20)
    at reporters.forEach.reporter (/Users/mosca/runtime/test/system/node_modules/@wdio/runner/build/reporter.js:38:49)
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (/Users/mosca/runtime/test/system/node_modules/@wdio/runner/build/reporter.js:38:20)
    at Runner.run (/Users/mosca/runtime/test/system/node_modules/@wdio/runner/build/index.js:113:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by wswebcreation** [comment]
Closing this one because it's an issue in `wdio-cucumberjs-json-reporter`
