### ISSUE TITLE
javascript error: javascript error: circular reference

### ISSUE THREAD

**Issue by lakatostamas** [webdriverio/webdriverio#4817]
**Environment:**
 - **WebdriverIO version:** 5.16.9
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** -
 - **Node.js version:** 10.15.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** chrome=78.0.3904.108
 - **Platform name and version:** macOS Mojave
 - **Additional wdio packages used (if applicable):** @wdio/cli, @wdio/local-runner, @wdio-mocha-framework, @wdio/spec-reporter, @wdio/sync

**Config of WebdriverIO**
I did not modify the generated config.

**Describe the bug**
I tried to run `browser.execute` method and I encountered the following error:
```
[0-0] 2019-11-26T11:42:15.035Z ERROR webdriver: Request failed due to javascript error: javascript error: circular reference
  (Session info: chrome=78.0.3904.108)
    at getErrorFromResponseBody (/playground/webdio/node_modules/webdriver/build/utils.js:124:10)
    at Request._callback (/playground/webdio/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/playground/webdio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/playground/webdio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/playground/webdio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
```

If I remove this line: https://github.com/lakatostamas/webdio/blob/master/test/specs/basic.js#L6 then it works perfectly.

**To Reproduce**
https://github.com/lakatostamas/webdio please checkout this repository and run  `./node_modules/.bin/wdio wdio.conf.js` after `npm install`

**Expected behavior**
Execute the test without throwing an exception

**Additional context**
I read about Chrome v76 where a very similar bug was introduced but it should be fixed in the v78, right?
https://stackoverflow.com/questions/57492625/chromedriver-76-breaks-my-test-suite-javascript-error-circular-reference
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2995

**Comment by mgrybyk** [comment]
If it's a chromedriver defect there is nothing can be done on webdriverio.

Another point here is why would you need to return window in execute script?  
And running then command on window object absolutely makes no sense.

If you have more questions feel free to ask, closing for now

**Comment by christian-bromann** [comment]
To elaborate on that: you can't serialize the window object to transfer it from the browser environment to your WebdriverIO Node.js script. Just interact with the object in the `execute` command and only return primitives back.

**Comment by lakatostamas** [comment]
Thanks a lot for you replies! We made it work with your help 🙇  🎉

**Comment by swavij-git** [comment]
Hi  @christian-bromann, I am new to webdriverio. Could you please give an example of what you mean by primitives? and how to use window to return it back?
