### ISSUE TITLE
WDIO, Multiremote, sync-mode returning pending promise instead of element.

### ISSUE THREAD

**Issue by janmatura** [webdriverio/webdriverio#4870]
**Describe your question with as much detail as possible**
WDIO, Multiremote, sync-mode returning pending promise instead of element. Almost every element behave like this now.

**If it's about a specific piece of code, try and include some of it to support your question.**

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.11.0
 - **NPM version:**using Yarn
 - **Browser name and version:** Chrome
 - **Platform name and version:** Windows 10, Mas OS
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service, mocha, allure-reporter, lodash 

**Additional context**
Using multiremote to run 3 - 6 instances of chrome. 

**PAGE file example:**
`dmiSelecet` just wrapping everywhere repeating attribute name string.
```
import { Page } from 'pages';

export class InboxPageClass extends Page {
  private modalEmailSelect = (mluviiId: string) => {
		return this.browser.$(`[data-mluvii-id*="emailModal"] [data-mluvii-id="${mluviiId}"]`);
  }

  get unassignedEmailsList() {
    return this.dmiSelect('section.emails', 'unassignedThreadList');
  }

  get assignedEmailsList() {
    return this.dmiSelect('section.emails', 'assignedThreadList');
  }

  get newEmailBtn() {
    return this.dmiSelect('section.emails', 'new');
  }
```

**STEPS file example**
```
import { expect } from 'chai';
import { InboxPageClass } from 'pages';
import { log, blink } from 'helpers';

export class InboxStepsClass {
	inboxPageClass: InboxPageClass;

	constructor(private selectedBrowser: WebdriverIO.BrowserObject) {
		this.inboxPageClass = new InboxPageClass(selectedBrowser);
	}
        unAssignMail(){
		this.inboxPageClass.emailUnassignBtn.waitAndClick();
	};

	makeResponse(messageText: string){
		this.inboxPageClass.editInputBody.setValue(messageText);
		this.inboxPageClass.sendEmail.waitForEnabled();
	};
```

**SPEC file example**

```
...declaring more steps classes above

import { LoginStepsClass } from 'steps/login.steps';
const LoginStepsOpe = new LoginStepsClass(Browser_3);

describe('S7 Mails', () => {
 it('C276 Change email inbox, reply to email', () => {
    LoginStepsOpe.open();
    LoginStepsOpe.logInAs('o1');

    InboxStepsOpe.goToInbox();
    InboxStepsOpe.acceptMailBySubject(subject4);
    InboxStepsOpe.changeInbox(1);
    InboxStepsOpe.makeResponse('Test message 123456789/*-');
    InboxStepsOpe.sendResponse();
})
```
**ERROR is getting here in STEPS file for instance**

```
unAssignMail(){
		this.inboxPageClass.emailUnassignBtn.waitAndClick();
	};
```
the element returning pending promise if I log it.

**ERROR log**
```
[MultiremoteBrowser #0-0] this.inboxPageClass.editInputBody.setValue is not a function
[MultiremoteBrowser #0-0] TypeError: this.inboxPageClass.editInputBody.setValue is not a function
[MultiremoteBrowser #0-0]     at InboxStepsClass.makeResponse (C:\Users\Testovaci\OnOpChat\OnOpChat\WdioUiTests\steps\emails\inbox.steps.ts:76:37)
[MultiremoteBrowser #0-0]     at Context.<anonymous> (C:\Users\Testovaci\OnOpChat\OnOpChat\WdioUiTests\test\desktop\s7_Mails.spec.ts:121:19)
[MultiremoteBrowser #0-0]     at Context.executeSync (C:\Users\Testovaci\OnOpChat\OnOpChat\WdioUiTests\node_modules\@wdio\sync\build\index.js:56:18)
[MultiremoteBrowser #0-0]     at C:\Users\Testovaci\OnOpChat\OnOpChat\WdioUiTests\node_modules\@wdio\sync\build\index.js:141:70 
```
Two last rows refers to some promise handling at @wdio/sync if I got it right.

**Workaround**
In STEPS we can do workaround by getting element without method frstly, then it works:
```
unAssignMail(){
                this.inboxPageClass.emailUnassignBtn
		this.inboxPageClass.emailUnassignBtn.waitAndClick();
	};
```
`browser.pause(xx)` before step also works

**Comment by christian-bromann** [comment]
Can you please specify which part is returning promises. Can you provide a minimal reproducible example?

**Comment by janmatura** [comment]
Sorry, was missclick, i have pubslished undone. What about now?

**Comment by christian-bromann** [comment]
Try move
```js
const LoginStepsOpe = new LoginStepsClass(Browser_3);
```
into the mocha `before` hook. You can only call wdio commands in a synchronous fashion within hooks and tests.

Closing as this is likely resolve the issue. Happy to assist further.

**Comment by janmatura** [comment]
Thank you, but it doesn' t work.

We have try to put selector directly to test (to replace "makeResponse" method). It behaves the same way. So it looks like the problem is only at "spec file" level.

`bowser.pause(250)` helps

```
it('C276 Change email inbox, reply to email', () => {

    LoginStepsOpe.open();
    LoginStepsOpe.logInAs('o1');

    InboxStepsOpe.goToInbox();
    InboxStepsOpe.acceptMailBySubject(subject4);
    InboxStepsOpe.changeInbox(1);
    // InboxStepsOpe.makeResponse('Test message 123456789/*-');
    // browser.pause(250);
    Browser_3.$('[data-mluvii-id*="emails:thread-view-email-editor-toolbar"]  > :nth-child(2) > div > div').setValue('Test message 123456789/*-');
    Browser_3.$('[data-mluvii-id="submit-email"]').waitForEnabled();

    InboxStepsOpe.sendResponse();

    //---- Admin checks

    LoginStepsAdmin.open()
    LoginStepsAdmin.logInAs('tsa')

    AllMailsStepsAdmin.goToAllMails();
    AllMailsStepsAdmin.filterBySubjectAndCheck(subject4);

  })
```

**Comment by christian-bromann** [comment]
> Thank you, but it doesn' t work.

Please be specific! Do you still receive promises? Also please make sure you use the latest version of WebdriverIO.

**Comment by janmatura** [comment]
Sure,
Webdriver 5.16.7 updated today using Yarn.

yes, still getting pending promise.

**Workaround as I stated above is to use the element firsttime without method. Then it works. Like this...**
```
it('C276 Change email inbox, reply to email', () => {

    LoginStepsOpe.open();
    LoginStepsOpe.logInAs('o1');

    InboxStepsOpe.goToInbox();
    InboxStepsOpe.acceptMailBySubject(subject4);
    InboxStepsOpe.changeInbox(1);
    //InboxStepsOpe.makeResponse('Test message 123456789/*-');
    // browser.pause(250);
    
    Browser_3.$('[data-mluvii-id*="emails:thread-view-email-editor-toolbar"]  > :nth-child(2) > div > div')
    Browser_3.$('[data-mluvii-id*="emails:thread-view-email-editor-toolbar"]  > :nth-child(2) > div > div').setValue('Test message 123456789/*-');
   
  })
```
**So I logged the element two times like this:**
```
 it('C276 Change email inbox, reply to email', () => {

    LoginStepsOpe.open();
    LoginStepsOpe.logInAs('o1');

    InboxStepsOpe.goToInbox();
    InboxStepsOpe.acceptMailBySubject(subject4);
    InboxStepsOpe.changeInbox(1);
    //InboxStepsOpe.makeResponse('Test message 123456789/*-');
    // browser.pause(250);
    console.log('LogElement_01',Browser_3.$('[data-mluvii-id*="emails:thread-view-email-editor-toolbar"]  > :nth-child(2) > div > div'))
    console.log('LogElement_02',Browser_3.$('[data-mluvii-id*="emails:thread-view-email-editor-toolbar"]  > :nth-child(2) > div > div'))
    
  })
```
**And I got this in logs:**

The first one returns promise.
The second one really returns the element.
```
[0-0] LogElement_01 Promise { <pending> }
[0-0] 2019-12-12T12:24:42.176Z INFO webdriver: COMMAND findElement("css selector", "[data-mluvii-id*="emails:thread-view-email-editor-toolbar"]  > :nth-child(2) > div > div")
[0-0] 2019-12-12T12:24:42.177Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/b203308e97484d0bf4c9fdf27aea2a2a/element
2019-12-12T12:24:42.177Z INFO webdriver: DATA {
  using: 'css selector',
  value: '[data-mluvii-id*="emails:thread-view-email-editor-toolbar"]  > :nth-child(2) > div > div'
}
[0-0] 2019-12-12T12:24:42.188Z INFO webdriver: RESULT { ELEMENT: '0.9598724250859891-23' }
[0-0] LogElement_02 Element {
  sessionId: 'b203308e97484d0bf4c9fdf27aea2a2a',
  elementId: '0.9598724250859891-23',
  ELEMENT: '0.9598724250859891-23',
  selector: '[data-mluvii-id*="emails:thread-view-email-editor-toolbar"]  > :nth-child(2) > div > div',
  parent: Browser {
    sessionId: 'b203308e97484d0bf4c9fdf27aea2a2a',
    capabilities: {
      acceptInsecureCerts: false,
      acceptSslCerts: false,
      applicationCacheEnabled: false,
      browserConnectionEnabled: false,
      browserName: 'chrome',
      chrome: [Object],
      cssSelectorsEnabled: true,
      databaseEnabled: false,
      'goog:chromeOptions': [Object],
      handlesAlerts: true,
      hasTouchScreen: false,
      javascriptEnabled: true,
      locationContextEnabled: true,
      mobileEmulationEnabled: false,
      nativeEvents: true,
      networkConnectionEnabled: false,
      pageLoadStrategy: 'normal',
      platform: 'Windows NT',
      rotatable: false,
      setWindowRect: true,
      takesHeapSnapshot: true,
      takesScreenshot: true,
      unexpectedAlertBehaviour: '',
      version: '78.0.3904.108',
      webStorageEnabled: true,
      'webdriver.remote.sessionid': 'b203308e97484d0bf4c9fdf27aea2a2a'
    },
    addCommand: [Function],
    overwriteCommand: [Function],
    _NOT_FIBER: false
  },
  emit: [Function: bound ],
  addCommand: [Function],
  overwriteCommand: [Function]
}

```
**Report Error is** (If there is no workaroud and console.log)
```
[MultiremoteBrowser #0-0] Browser_3.$(...).setValue is not a function
[MultiremoteBrowser #0-0] TypeError: Browser_3.$(...).setValue is not a function
[MultiremoteBrowser #0-0]     at Context.<anonymous> (C:\Users\Testovaci\OnOpChat\OnOpChat\WdioUiTests\test\desktop\s7_Mails.spec.ts:157:109)
[MultiremoteBrowser #0-0]     at Context.executeSync (C:\Users\Testovaci\OnOpChat\OnOpChat\WdioUiTests\node_modules\@wdio\sync\build\index.js:56:18)
[MultiremoteBrowser #0-0]     at C:\Users\Testovaci\OnOpChat\OnOpChat\WdioUiTests\node_modules\@wdio\sync\build\index.js:141:70
```

**Comment by christian-bromann** [comment]
mhm .. this is odd. Can you provide a minimal reproducible example that I can run on my machine?

**Comment by janmatura** [comment]
We had few packages out-to-date, due to some package.json issue. Thank you so much for forcing us to check it again. Now it seem work well.

**Comment by palash2601** [comment]
@janmatura,
Can you please share the version of the wdio packages which fixed this issue for you? I am facing this issue with latest version of wdio v5

```
"@wdio/cli": "^5.0.0",
    "@wdio/cucumber-framework": "^5.0.0",
    "@wdio/dot-reporter": "^5.0.0",
    "@wdio/local-runner": "^5.0.0",
    "@wdio/selenium-standalone-service": "^5.0.0",
    "@wdio/spec-reporter": "^5.0.0",
    "@wdio/sync": "^5.0.0",
```
