### ISSUE TITLE
How to override default socketTimeout for RemoteWebDriver instance?

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#4904]
**Describe your question with as much detail as possible**
How to override default socketTimeout of 60s for webdriver instance via selenium node?
- My problem : Some tests failed with a SO_TIMEOUT error after 60s when a page takes more than 60s to load (Many CPU ressources of VM are used and the VM no longer responds for 90s)
- Environment : Selenium Grid v.3.141.59 + Selenium Node  v.3.141.59 
- Selenium node is a remote VMware  (Windows 10 + Edge)

---> I can't increase the VM's ressources. So, the only solution is to increase the socket timeout to 120s , How to do this? 

**If it's about a specific piece of code, try and include some of it to support your question.**
I configured the browser timeouts:
```
  browser.setTimeout({
    implicit: 300000,
    pageLoad: 300000,
    script: 300000,
  });
```
And I tried to add a timeout(requestOptions.timeout = 120000) in node_modules/webdriver/build/request.js but but it had no effect. 

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.15
 - **Mode:** WDIO
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Edge
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^5.16.15",
    "@wdio/cucumber-framework": "^5.16.15",
    "@wdio/dot-reporter": "^5.16.5",
    "@wdio/local-runner": "^5.16.15",
    "@wdio/mocha-framework": "^5.16.5",
    "@wdio/spec-reporter": "^5.16.5",
    "@wdio/sync": "^5.16.15",

**Additional context**
I use a selenium node with VM windows 10 + Edge  with capabilities 

```
{
  "capabilities":
  [
	{
      "browserName": "MicrosoftEdge",
      "platform": "WINDOWS",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 1,
  "browserTimeout": 60,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "timeout": 60,
  "hub": "http://xxxxx:4444",
  "nodeStatusCheckTimeout": 180000,
  "nodePolling": 3000000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}
```
Error displayed : 

```
[1-38] [90m2019-12-19T04:40:03.854Z[39m [31mERROR[39m [97mwebdriver[39m: Request failed due to Error: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.13.12</center>
</body>
</html>

    at getErrorFromResponseBody (/builds/insight/quality/end-to-end-tests-wdio/node_modules/webdriver/build/utils.js:117:12)
    at Request._callback (/builds/insight/quality/end-to-end-tests-wdio/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/builds/insight/quality/end-to-end-tests-wdio/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at Request.<anonymous> (/builds/insight/quality/end-to-end-tests-wdio/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:475:20)
    at IncomingMessage.<anonymous> (/builds/insight/quality/end-to-end-tests-wdio/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[0-0] 2019-12-19T08:03:49.756Z ERROR webdriver: Request failed due to unknown error: Session [3954D046-6890-43BA-A9AE-108D57A08588] was terminated due to SO_TIMEOUT
    at getErrorFromResponseBody (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\webdriver\build\utils.js:124:10)
    at Request._callback (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\webdriver\build\request.js:115:64)
    at Request.self.callback (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\request\request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\request\request.js:1181:10)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\request\request.js:1103:12)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at IncomingMessage.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by christian-bromann** [comment]
It might be related to https://github.com/SeleniumHQ/selenium/issues/5344. That said, this is something that needs to get configured on the Selenium Standalone Node side and can't be done via WebdriverIO. Please fill this issue in the Selenium project. Thanks!

**Comment by lacell75** [comment]
I found the solution with timeout and browserTimeout. I configure the node with this values : 

```
{
  "capabilities":
  [
	{
      "browserName": "MicrosoftEdge",
      "platform": "WINDOWS",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 1,
  "browserTimeout": 310,
  "timeout": 300,
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "timeout": 60,
  "hub": "http://xxxxx:4444",
  "nodeStatusCheckTimeout": 180000,
  "nodePolling": 3000000,
  "role": "node",
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false,
  "servlets" : [],
  "withoutServlets": [],
  "custom": {}
}
```
