### ISSUE TITLE
Chrome session fails to create with Illegal key values seen in w3c capabilities: [maxInstances]

### ISSUE THREAD

**Issue by joshden** [webdriverio/webdriverio#4934]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.15.3
 - **NPM version:** 6.1.0
 - **Browser name and version:** Chrome 79
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone-service@5.16.10

**Config of WebdriverIO**
```
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
    }],
```

**Describe the bug**
Failure to create browser session when I have a `maxInstances` in one of my capabilities objects.

```
[0-0] Error: Failed to create session.
Illegal key values seen in w3c capabilities: [maxInstances]
Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities.
See more https://www.w3.org/TR/webdriver/#capabilities
```

**To Reproduce**
1. Set the configuration as above
2. `npx wdio`

[Include code or an example repository that can easily be set up]

**Expected behavior**
Browser session to be created and tests to run without error

**Log**
```
2020-01-02T23:43:01.726Z INFO @wdio/local-runner: Run worker command: run
2020-01-02T23:43:02.592Z DEBUG @wdio/local-runner:utils: init remote session
2020-01-02T23:43:02.594Z INFO webdriverio: Initiate new session using the webdriver protocol
2020-01-02T23:43:02.596Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
2020-01-02T23:43:02.597Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { maxInstances: 1, browserName: 'chrome' },
     firstMatch: [ {} ] },
  desiredCapabilities: { maxInstances: 1, browserName: 'chrome' } }
2020-01-02T23:43:02.686Z DEBUG webdriver: request failed due to status 13
2020-01-02T23:43:02.686Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [maxInstances]
2020-01-02T23:43:02.686Z INFO webdriver: Retrying 1/3
2020-01-02T23:43:02.686Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
2020-01-02T23:43:02.686Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { maxInstances: 1, browserName: 'chrome' },
     firstMatch: [ {} ] },
  desiredCapabilities: { maxInstances: 1, browserName: 'chrome' } }
2020-01-02T23:43:02.701Z DEBUG webdriver: request failed due to status 13
2020-01-02T23:43:02.701Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [maxInstances]
2020-01-02T23:43:02.701Z INFO webdriver: Retrying 2/3
2020-01-02T23:43:02.701Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
2020-01-02T23:43:02.702Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { maxInstances: 1, browserName: 'chrome' },
     firstMatch: [ {} ] },
  desiredCapabilities: { maxInstances: 1, browserName: 'chrome' } }
2020-01-02T23:43:02.712Z DEBUG webdriver: request failed due to status 13
2020-01-02T23:43:02.712Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [maxInstances]
2020-01-02T23:43:02.712Z INFO webdriver: Retrying 3/3
2020-01-02T23:43:02.712Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session
2020-01-02T23:43:02.712Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { maxInstances: 1, browserName: 'chrome' },
     firstMatch: [ {} ] },
  desiredCapabilities: { maxInstances: 1, browserName: 'chrome' } }
2020-01-02T23:43:02.721Z DEBUG webdriver: request failed due to status 13
2020-01-02T23:43:02.721Z ERROR webdriver: Request failed due to unknown error: Illegal key values seen in w3c capabilities: [maxInstances]
    at getErrorFromResponseBody (C:\Users\Josh\edge-platform-test-taall\node_modules\webdriver\build\utils.js:124:10)
    at Request._callback (C:\Users\Josh\edge-platform-test-taall\node_modules\webdriver\build\request.js:111:64)
    at Request.self.callback (C:\Users\Josh\edge-platform-test-taall\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (C:\Users\Josh\edge-platform-test-taall\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (C:\Users\Josh\edge-platform-test-taall\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
2020-01-02T23:43:02.725Z ERROR webdriver: unknown error: Illegal key values seen in w3c capabilities: [maxInstances]
    at getErrorFromResponseBody (C:\Users\Josh\edge-platform-test-taall\node_modules\webdriver\build\utils.js:124:10)
    at Request._callback (C:\Users\Josh\edge-platform-test-taall\node_modules\webdriver\build\request.js:111:64)
    at Request.self.callback (C:\Users\Josh\edge-platform-test-taall\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (C:\Users\Josh\edge-platform-test-taall\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (C:\Users\Josh\edge-platform-test-taall\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
2020-01-02T23:43:02.725Z ERROR @wdio/runner: Error: Failed to create session.
Illegal key values seen in w3c capabilities: [maxInstances]
Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities.
See more https://www.w3.org/TR/webdriver/#capabilities
    at startWebDriverSession (C:\Users\Josh\edge-platform-test-taall\node_modules\webdriver\build\utils.js:45:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
**Additional context**
@christian-bromann requested an issue report for this https://gitter.im/webdriverio/webdriverio?at=5e0e7c9929e8167dcf73e7b1

**Comment by henrywang** [comment]
I have the same issue. I comment out the `maxInstances: 1,` as workaround temporarily.

**Comment by christian-bromann** [comment]
A [fix](https://github.com/webdriverio/webdriverio/pull/4923) for this has been merged and release. Therefor closing the issue.
