### ISSUE TITLE
Webdriverio v5 and "wdio-xray-json-reporter": "0.0.1" do not work together.

### ISSUE THREAD

**Issue by flexin777** [webdriverio/webdriverio#4985]
Hello
I need to add export junit reports to xray. Tried to use 
"wdio-xray-json-reporter": "0.0.1" package. After run I see next error
```
[0-2] 2020-01-31T10:22:25.916Z ERROR @wdio/local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor
    at BaseReporter.initReporter (D:\vadym\e2e-tests\node_modules\@wdio\runner\build\reporter.js:124:14)
    at Array.map (<anonymous>)
    at new BaseReporter (D:\vadym\e2e-tests\node_modules\@wdio\runner\build\reporter.js:32:39)
    at Runner.run (D:\vadym\e2e-tests\node_modules\@wdio\runner\build\index.js:77:21)
    at process.on.m (D:\vadym\e2e-tests\node_modules\@wdio\local-runner\build\run.js:37:20)
    at process.emit (events.js:203:15)
    at process.EventEmitter.emit (domain.js:448:20)
    at emit (internal/child_process.js:832:12)
```

**Comment by christian-bromann** [comment]
@flexin777 please create a bug report in the wdio-xray-json-reporter project. It currently doesn't support v5. Thanks.
