### ISSUE TITLE
ESOCKETTIMEDOUT error when running Appium tests in RDC on SauceLabs

### ISSUE THREAD

**Issue by jaFerrazza** [webdriverio/webdriverio#4999]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.15.0
 - **Mode:** sauce
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.8.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** N/A
 - **Platform name and version:** Android 10, Android 9 - iOS 13
 - **Additional wdio packages used (if applicable):** 
       - "@wdio/appium-service": "^5.0.0",
       - "@wdio/cli": "^5.10.9",
       - "@wdio/local-runner": "^5.10.9",
       - "@wdio/mocha-framework": "^5.11.0",
       - "@wdio/sauce-service": "^5.11.1",
       - "@wdio/spec-reporter": "^5.9.3",
       - "@wdio/sync": "^5.10.8",

**Config of WebdriverIO**
    
  ```
      deviceName: "Motorola.*", //It will locate any Motorola device in SC
      platformName: "Android",
      platformVersion: "9",
      maxInstances: 1,
      autoGrantPermissions: true,
      testobject_api_key: process.env.TESTOBJECT_API_KEY_ANDROID, //The API Key provided by SC
      testobject_suite_name: "",
      testobject_test_name: "Android Tests",
      region: "eu" 
```

**Description of the issue**
There might be the possibility that this is not a bug but I'm publishing it here since I didn't find any docs or issues related to the error I'm facing. 
It only happens when I run my tests in the RDC on SauceLabs, if I run the tests locally it doesn't happen, when I see the video attached to the session it just shows how the app is open up then it just stays there and does nothing.
I'm using the App Center integration with SauceLabs, hence, I don't need to pass the app capability. 

**Log**
[0-1] 2020-02-07T14:30:05.489Z WARN webdriver: Request failed due to ESOCKETTIMEDOUT
[0-1] 2020-02-07T14:31:35.623Z WARN webdriver: Request failed due to ESOCKETTIMEDOUT
[0-1] 2020-02-07T14:33:05.823Z WARN webdriver: Request failed due to ESOCKETTIMEDOUT
[0-1] 2020-02-07T14:34:36.024Z ERROR webdriver: Request failed due to Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/circleci/qa-appium/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:291:20)
    at ClientRequest.emit (events.js:203:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:680:40)
    at Object.onceWrapper (events.js:291:20)
    at TLSSocket.emit (events.js:203:13)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at TLSSocket.Socket._onTimeout (net.js:434:8)
    at listOnTimeout (internal/timers.js:531:17)
[0-1] 2020-02-07T14:34:36.024Z ERROR webdriver: Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/circleci/qa-appium/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:291:20)
    at ClientRequest.emit (events.js:203:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at TLSSocket.emitRequestTimeout (_http_client.js:680:40)
    at Object.onceWrapper (events.js:291:20)
    at TLSSocket.emit (events.js:203:13)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at TLSSocket.Socket._onTimeout (net.js:434:8)
    at listOnTimeout (internal/timers.js:531:17)
[0-1] 2020-02-07T14:34:36.025Z ERROR @wdio/runner: Error: Failed to create session.
ESOCKETTIMEDOUT
    at startWebDriverSession (/home/circleci/qa-appium/node_modules/webdriver/build/utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[0-1] Error: Failed to create session.

**Additional context**
The same issue is happening when running the tests through CircleCI.

**Comment by wswebcreation** [comment]
@jaFerrazza 

It's better to contact customer support of Sauce Labs. This is not related to WebdriverIO and 9-10 times related to a specific command / appium version that is used. Also provide them the logs of you execution in the Sauce Labs cloud

**Comment by tomasfly** [comment]
I am experiencing the same issue but when running Appium tests on AWS. @jaFerrazza Any updates?

**Comment by jaFerrazza** [comment]
@tomasfly hey there, I changed the Appium version that my tests were using in SauceLabs to reflect the version that I had on my project. I also changed the device pool to use devices that are not requested frequently in the queue (Motorola, Blue, etc). I'm using Appium version 1.15.0 on both, my project and SauceLabs. Let me know if this fix works for you.
