### ISSUE TITLE
$(...).waitForExist is not a function

### ISSUE THREAD

**Issue by Andrew-Archon** [webdriverio/webdriverio#5000]
**Describe your question with as much detail as possible**
When I try to run element.waitForExist(), I'm receiving an error that says `ERROR @wdio/runner: TypeError: $(...).waitForExist is not a function`.  I'm running WebdriverIO in synchronous mode and I'm using Appium and UIAutomator2 to run the tests on an Android emulator in Android Studio.  When I run the test spec, the app is installed and opened on the emulator correctly, but as soon as the appActivity is loaded, the test fails immediately on the waitForExist() call due to a type error.  Also of note is that I run web based tests using webdriverio in synchronous mode, using the exact same package.json and tsconfig.json files and they run correctly.

**If it's about a specific piece of code, try and include some of it to support your question.**
Test spec:
```
import LoginScreen from "../shared/screens/login.screen";

describe("Logged in tests", function () {
  describe("Login", () => {      
    LoginScreen.waitForPageLoad()
  })

```
Page object:
```
class LoginScreenImpl {
  waitForPageLoad() {    
      $("~Log In").waitForExist()
  }
}
const LoginScreen = new LoginScreenImpl()
export default LoginScreen
```

**Environment (please complete the following information):**
 - **WebdriverIO version:**
5.18.6
 - **Mode:** [Standalone mode or WDIO Testrunner]
WDIO Testrunner + Appium
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
Synchronous
 - **Node.js version:** [e.g. 8.9.1]
v10.15.3
 - **NPM version:** [e.g. 5.8.0]
Yarn v1.17.3
 - **Browser name and version:** [e.g. Chrome 68]
Android native app
 - **Platform name and version:** [e.g. Windows 10]
Android 9 (Android Studio on Windows 10)
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]
```
"dependencies": {
    "@wdio/appium-service": "5.18.2",
    "@wdio/cli": "5.18.6",
    "@wdio/local-runner": "5.18.6",
    "@wdio/mocha-framework": "5.18.6",
    "@wdio/selenium-standalone-service": "5.16.10",
    "@wdio/sync": "5.18.6",
    "appium": "1.16.0",
    "better-npm-run": "0.1.1",
    "proper-lockfile": "4.1.1"
  },
  "devDependencies": {
    "ts-node": "8.6.2",
    "tsconfig-paths": "3.9.0"
  }
```

**Additional context**
```
tsconfig:
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitThis": false,
    "noImplicitReturns": false,
    "esModuleInterop": true,
    "noEmit": true,
    "allowJs": false,
    "jsx": "react",
    "types": [
      "@wdio/appium-service",
      "@wdio/mocha-framework",
      "@wdio/sync",
      "node"
    ]
  },
  "include": [
    "**/*",
    "../mobile/**/*", <=the test spec is in mobile/tests/test.spec.ts
    "../shared/**/*",
    "../packages/tests-common/**/*",
    "../web/**/*.constants.ts"
  ],
  "exclude": [
    "bin",
    "node_modules"
  ]
}
```

**Comment by Andrew-Archon** [comment]
Logs
```
Executing script: android:local

to be executed: ""./node_modules/.bin/wdio" mobile/local.android.js"

Execution of 1 spec files started at 2020-02-09T17:16:39.632Z

2020-02-09T17:16:39.654Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-02-09T17:16:41.342Z INFO @wdio/local-runner: Start worker 0-0 with arg: mobile/local.android.js
[0-0] 2020-02-09T17:16:41.975Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in com.inflowinventory.mobile.MainActivity - C:\inflow\online\tests\mobile\tests\index.spec.ts
[0-0] 2020-02-09T17:16:43.633Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-02-09T17:16:43.635Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
[0-0] 2020-02-09T17:16:43.636Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { automationName: 'UiAutomator2',
        platformName: 'Android',
        platformVersion: '9',
        deviceName: 'Pixel 2 API 28',
        app:
         'C:\\Users\\A\\Downloads\\app-develop-com.inflowdevelop.mobile-1.94.1074-alpha.apk',
        appWaitActivity: 'com.inflowinventory.mobile.MainActivity' },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { automationName: 'UiAutomator2',
     platformName: 'Android',
     platformVersion: '9',
     deviceName: 'Pixel 2 API 28',
     app:
      'C:\\Users\\A\\Downloads\\app-develop-com.inflowdevelop.mobile-1.94.1074-alpha.apk',
     appWaitActivity: 'com.inflowinventory.mobile.MainActivity' } }
[0-0] 2020-02-09T17:16:55.504Z INFO webdriver: COMMAND findElement("accessibility id", "Log In")
[0-0] 2020-02-09T17:16:55.504Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session/cfe548f2-742b-49d6-b45b-5beaf1a0e5df/element
2020-02-09T17:16:55.505Z INFO webdriver: DATA { using: 'accessibility id', value: 'Log In' }
[0-0] 2020-02-09T17:16:55.505Z ERROR @wdio/runner: TypeError: $(...).waitForExist is not a function
    at LoginScreenImpl.waitForPageLoad (C:\inflow\online\tests\mobile\shared\screens\login.screen.ts:10:20)
    at Suite.describe (C:\inflow\online\tests\mobile\tests\index.spec.ts:20:17)
    at Object.create (C:\inflow\online\tests\node_modules\mocha\lib\interfaces\common.js:140:19)
    at context.describe.context.context (C:\inflow\online\tests\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Suite.describe (C:\inflow\online\tests\mobile\tests\index.spec.ts:19:3)
    at Object.create (C:\inflow\online\tests\node_modules\mocha\lib\interfaces\common.js:140:19)
    at context.describe.context.context (C:\inflow\online\tests\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Object.<anonymous> (C:\inflow\online\tests\mobile\tests\index.spec.ts:10:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (C:\inflow\online\tests\node_modules\ts-node\src\index.ts:814:23)
[0-0] Error: $(...).waitForExist is not a function
[0-0] 2020-02-09T17:16:55.553Z INFO webdriver: COMMAND deleteSession()
2020-02-09T17:16:55.553Z INFO webdriver: [DELETE] http://127.0.0.1:4723/wd/hub/session/cfe548f2-742b-49d6-b45b-5beaf1a0e5df
[0-0] 2020-02-09T17:16:55.691Z INFO webdriver: RESULT { error: 'no such element',
  message:
   'An element could not be located on the page using the given search parameters.',
  stacktrace:
   'NoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (C:\\inflow\\online\\tests\\node_modules\\appium-android-driver\\lib\\commands\\find.js:75:11)' }
[0-0] FAILED in com.inflowinventory.mobile.MainActivity - C:\inflow\online\tests\mobile\tests\index.spec.ts
2020-02-09T17:16:56.449Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:16

2020-02-09T17:16:56.457Z INFO @wdio/local-runner: Shutting down spawned worker
2020-02-09T17:16:56.710Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-02-09T17:16:56.712Z INFO @wdio/local-runner: shutting down
error Command failed with exit code 1.
```

**Comment by Andrew-Archon** [comment]
The only related issue I found was: https://github.com/webdriverio/webdriverio/issues/4403, but I am using strictly sync so it didn't seem to apply.

**Comment by christian-bromann** [comment]
@Andrew-Archon are you sure you have `@wdio/sync` installed properly? Can you check what:

```js
console.log($("~Log In"))
```

returns?

**Comment by Andrew-Archon** [comment]
It returns `Promise { <pending> }`

**Comment by christian-bromann** [comment]
@Andrew-Archon this means that you don't run WebdriverIO in sync mode. Please have a read on https://webdriver.io/docs/sync-vs-async.html. If you want to run commands synchronously you need to install `@wdio/sync` otherwise you have to use `async/await`. 

Closing as it doesn't seem an issue in WebdriverIO.

**Comment by Andrew-Archon** [comment]
@wdio/sync is installed, as you can see in the package.json file.

**Comment by christian-bromann** [comment]
@Andrew-Archon looking at your test you've used a wrong function, it should be

```js
describe("Logged in tests", function () {
  it("Login", () => {      
    LoginScreen.waitForPageLoad()
  })
```
You can not run WebdriverIO commands within `describe` blocks, only in `it` blocks or hooks.

**Comment by Andrew-Archon** [comment]
Well, that was definitely it.  Can I suggest that you add some more specific error messaging for this error?

**Comment by christian-bromann** [comment]
> Can I suggest that you add some more specific error messaging for this error?

I am not sure how this would look like and how feasible it is to technically implement it.
