### ISSUE TITLE
8 silly fetchPackageMetaData error for @wdio/cli@latest 401 Unauthorized: @wdio/cli@latest

### ISSUE THREAD

**Issue by adamchenwei** [webdriverio/webdriverio#5008]
When I try to follow tutorial do npm i --save-dev @wdio/cli I got 401

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '--save-dev',
1 verbose cli   '@wdio/cli' ]
2 info using npm@6.4.1
3 info using node@v8.14.1
4 verbose npm-session 86a6d046037c49e2
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 401 https://chewyinc.jfrog.io/chewyinc/api/npm/npm-cache/@wdio%2fcli 160ms
8 silly fetchPackageMetaData error for @wdio/cli@latest 401 Unauthorized: @wdio/cli@latest
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 361ms
11 verbose stack Error: 401 Unauthorized: @wdio/cli@latest
11 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at runCallback (timers.js:810:20)
11 verbose stack     at tryOnImmediate (timers.js:768:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
11 verbose stack From previous event:
11 verbose stack     at regFetch (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:36:6)
11 verbose stack     at fetchPackument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:81:10)
11 verbose stack     at getManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:37:10)
11 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:10)
11 verbose stack     at Object.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/index.js:12:12)
11 verbose stack     at Object.Fetcher#manifest [as manifest] (/usr/local/lib/node_modules/npm/node_modules/genfun/lib/genfun.js:15:38)
11 verbose stack     at manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetch.js:16:18)
11 verbose stack     at pinflight (/usr/local/lib/node_modules/npm/node_modules/pacote/manifest.js:24:12)
11 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24
11 verbose stack From previous event:
11 verbose stack     at _inflight (/usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)
11 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14
11 verbose stack     at runCallback (timers.js:810:20)
11 verbose stack     at tryOnImmediate (timers.js:768:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
11 verbose stack From previous event:
11 verbose stack     at inflight (/usr/local/lib/node_modules/npm/node_modules/promise-inflight/inflight.js:14:40)
11 verbose stack     at Object.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/manifest.js:22:10)
11 verbose stack     at fetchPackageMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:58:10)
11 verbose stack     at limited (/usr/local/lib/node_modules/npm/node_modules/call-limit/call-limit.js:29:10)
11 verbose stack     at fs.stat (/usr/local/lib/node_modules/npm/lib/install/deps.js:224:20)
11 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
11 verbose stack     at FSReqWrap.oncomplete (fs.js:152:21)
12 verbose cwd /Users/achenwei/www/lab/adamchenwei/playground-webdriverio
13 verbose Darwin 18.0.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "@wdio/cli"
15 verbose node v8.14.1
16 verbose npm  v6.4.1
17 error code E401
18 error 401 Unauthorized: @wdio/cli@latest
19 verbose exit [ 1, true ]
```

**Comment by baruchvlz** [comment]
It seems like your NPM registry is pointing to a jfrog cache which you're not authorized to use. Sincerely, there's nothing we can do about this. You might have to change your registry to the default NPM registry.
