### ISSUE TITLE
Unable to use sauce connect due to hash error

### ISSUE THREAD

**Issue by Geloloboy** [webdriverio/webdriverio#5014]
I'm getting this error when I try running my tests on saucelabs with sauceConnect enabled:
```2020-02-13T04:21:20.411Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "sauce"
2020-02-13T04:21:20.521Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-02-13T04:21:20.539Z DEBUG @wdio/sauce-service: Missing Sauce Connect local proxy, downloading dependency
2020-02-13T04:21:20.539Z DEBUG @wdio/sauce-service: This will only happen once.
2020-02-13T04:21:21.172Z DEBUG @wdio/sauce-service: Downloading NaNMB
2020-02-13T04:22:20.698Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Checksum of the downloaded archive (18e5a160c10b48c032372966e8423f16e318078d) doesn't match (67d05407c31dc00ee60b8ab65d7ced93d6fa610f).
    at Hash.<anonymous> (/Users/angelod/Dev/other/demo-js/appium-examples/wdio5/mocha-framework/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:169:17)
    at Hash.emit (events.js:316:22)
    at Hash.EventEmitter.emit (domain.js:483:12)
    at finishMaybe (_stream_writable.js:707:14)
    at endWritable (_stream_writable.js:724:3)
    at Hash.Writable.end (_stream_writable.js:644:5)
    at ReadStream.onend (_stream_readable.js:727:10)
    at Object.onceWrapper (events.js:410:28)
    at ReadStream.emit (events.js:316:22)
    at ReadStream.EventEmitter.emit (domain.js:483:12)```

Looks like its trying to download a sauce proxy with a different version than latest.

**Comment by christian-bromann** [comment]
@Geloloboy can you try to remove all your node dependencies and try again?

**Comment by wswebcreation** [comment]
@Geloloboy 

And maybe also your `package-lock.json`/ `yarn.lock` to get the latest versions in

**Comment by christian-bromann** [comment]
@Geloloboy did the comments help with your issue?

**Comment by Geloloboy** [comment]
@christian-bromann @wswebcreation 
To answer your question, yes I did try doing that. I nuked my modules and package-lock.json but the error still happens.

I'm unable to replicate the issue though when I tried doing the same thing on another project. I can't pinpoint what I did differently unfortunately.
