### ISSUE TITLE
How to use mocha framework with imports and activated specFiltering?

### ISSUE THREAD

**Issue by pako88** [webdriverio/webdriverio#5079]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.18.7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** see package.json

**Demo Project:**
https://github.com/pako88/WebdriverIO_v5_TypeScript

**Additional context**
I have set up two branches in this project:
- https://github.com/pako88/WebdriverIO_v5_TypeScript/tree/wo-pom
- https://github.com/pako88/WebdriverIO_v5_TypeScript/tree/with-pom

Run the tests with `npm run test`

**branch wo-pom**
- executed tests are without imports -> specFiltering is working fine
- only one browser is spin up
```
Execution of 2 spec files started at 2020-03-10T06:09:42.442Z

[0-1] RUNNING in chrome - D:\Repos\WebdriverIO_v5_TypeScript\test\login-wo-import.spec.ts
[0-1] PASSED in chrome - D:\Repos\WebdriverIO_v5_TypeScript\test\login-wo-import.spec.ts

 "spec" Reporter:
------------------------------------------------------------------
[chrome 80.0.3987.132 Windows NT #0-1] Spec: D:\Repos\WebdriverIO_v5_TypeScript\test\login-wo-import.spec.ts
[chrome 80.0.3987.132 Windows NT #0-1] Running: chrome (v80.0.3987.132) on Windows NT
[chrome 80.0.3987.132 Windows NT #0-1] Session ID: 6877b304fec1fe8543cabb9dcc69f416
[chrome 80.0.3987.132 Windows NT #0-1]
[chrome 80.0.3987.132 Windows NT #0-1] Login page
[chrome 80.0.3987.132 Windows NT #0-1]    ✓ displays message with invalid credentials
[chrome 80.0.3987.132 Windows NT #0-1]
[chrome 80.0.3987.132 Windows NT #0-1] 1 passing (23s)


Spec Files:      1 passed, 1 skipped, 2 total (100% completed) in 00:00:32
```

**branch with-pom**
- executed tests are with imports -> specFiltering is not working fine. two browser spins up, one closes directly. this behaviour is explained in the blog post https://webdriver.io/blog/2019/11/01/spec-filtering.html and in the issue https://github.com/webdriverio/webdriverio/pull/4531

```
Execution of 2 spec files started at 2020-03-10T07:16:43.187Z

[0-0] RUNNING in chrome - D:\Repos\WebdriverIO_v5_TypeScript\test\dropdown.spec.ts
[0-0] PASSED in chrome - D:\Repos\WebdriverIO_v5_TypeScript\test\dropdown.spec.ts
[0-1] RUNNING in chrome - D:\Repos\WebdriverIO_v5_TypeScript\test\login.spec.ts
[0-1] PASSED in chrome - D:\Repos\WebdriverIO_v5_TypeScript\test\login.spec.ts

 "spec" Reporter:
------------------------------------------------------------------
[chrome 80.0.3987.132 Windows NT #0-1] Spec: D:\Repos\WebdriverIO_v5_TypeScript\test\login.spec.ts
[chrome 80.0.3987.132 Windows NT #0-1] Running: chrome (v80.0.3987.132) on Windows NT
[chrome 80.0.3987.132 Windows NT #0-1] Session ID: f07d701619a646a2e4c6970d3079bc0c
[chrome 80.0.3987.132 Windows NT #0-1]
[chrome 80.0.3987.132 Windows NT #0-1] Login page
[chrome 80.0.3987.132 Windows NT #0-1]    ✓ displays message with invalid credentials
[chrome 80.0.3987.132 Windows NT #0-1]    ✓ should allow access with correct credentials
[chrome 80.0.3987.132 Windows NT #0-1]    ✓ using config values specified in src/config
[chrome 80.0.3987.132 Windows NT #0-1]
[chrome 80.0.3987.132 Windows NT #0-1] 3 passing (22.1s)


Spec Files:      2 passed, 2 total (100% completed) in 00:00:37
```

Error Message in logs:
```
2020-03-10T07:16:49.090Z INFO @wdio/local-runner: Run worker command: run
2020-03-10T07:16:49.100Z DEBUG @wdio/local-runner:utils: init remote session
2020-03-10T07:16:49.102Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
2020-03-10T07:16:50.529Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): D:\Repos\WebdriverIO_v5_TypeScript\test\dropdown.spec.ts
 Error:  D:\Repos\WebdriverIO_v5_TypeScript\test\dropdown.spec.ts:1
import {expect} from 'chai';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at D:\Repos\WebdriverIO_v5_TypeScript\node_modules\@wdio\mocha-framework\node_modules\mocha\lib\mocha.js:311:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (D:\Repos\WebdriverIO_v5_TypeScript\node_modules\@wdio\mocha-framework\node_modules\mocha\lib\mocha.js:308:14)
```

How can i get specFiltering up and running with mocha and imports in the spec files?

**Comment by pako88** [comment]
related to https://github.com/webdriverio/webdriverio/pull/4531

**Comment by wswebcreation** [comment]
Hi @mgrybyk 

I've assigned you to the issue, reason for that is that I've been looking into this one together with @pako88  and we walked through all steps for TypeScript and the `specFiltering` option. With the PO's we still get the `browser` error, even if we remove the `browser` commands from the PO's.

Do you have a working example with Mocha/Jasmine with PO's where this is working?

**Comment by pako88** [comment]
One additional comment: the error also appears when importing only chai at the tests. so it seems to be a general error with imports on test level

**Comment by christian-bromann** [comment]
I was able to run the framework with the following changes:
```
diff --git a/package.json b/package.json
index e151b62..b4b8dad 100644
--- a/package.json
+++ b/package.json
@@ -25,9 +25,9 @@
     "allure-commandline": "^2.13.0",
     "chai": "^4.2.0",
     "mocha": "^5.2.0",
-    "ts-node": "^7.0.1",
+    "ts-node": "^8.6.2",
     "tsconfig-paths": "^3.9.0",
     "tslint": "^5.20.1",
     "typescript": "^3.8.2",
     "webdriverio": "^5.18.7"
   }
diff --git a/src/pages/DropdownPage.ts b/src/pages/DropdownPage.ts
index 6203484..33f8f0c 100644
--- a/src/pages/DropdownPage.ts
+++ b/src/pages/DropdownPage.ts
@@ -1,4 +1,4 @@
-import BasePage from 'src/pages/BasePage';
+import BasePage from './BasePage';
 
 class DropdownPage extends BasePage {
     get open() {
diff --git a/src/pages/LogInPage.ts b/src/pages/LogInPage.ts
index 3b8bbf7..8d9fab0 100644
--- a/src/pages/LogInPage.ts
+++ b/src/pages/LogInPage.ts
@@ -1,4 +1,4 @@
-import BasePage from 'src/pages/BasePage';
+import BasePage from './BasePage';
 
 class LoginPage extends BasePage {
 
diff --git a/test/dropdown.spec.ts b/test/dropdown.spec.ts
index 623f9e0..d85cb3b 100644
--- a/test/dropdown.spec.ts
+++ b/test/dropdown.spec.ts
@@ -1,5 +1,5 @@
 import {expect} from 'chai';
-import DropdownPage from 'src/pages/DropdownPage';
+import DropdownPage from '../src/pages/DropdownPage';
 
 describe('Dropdown', () => {
     it('can be set using selectByVisibleText', () => {
diff --git a/test/login.spec.ts b/test/login.spec.ts
index c062627..86975f7 100644
--- a/test/login.spec.ts
+++ b/test/login.spec.ts
@@ -1,6 +1,6 @@
 import {expect} from 'chai';
-import {config} from 'src/config';
-import LoginPage from 'src/pages/LogInPage';
+import {config} from '../src/config';
+import LoginPage from '../src/pages/LogInPage';
 
 describe('Login page', () => {
     it('displays message with invalid credentials', () => {
diff --git a/wdio.conf.js b/wdio.conf.js
index d164713..ea499d2 100644
--- a/wdio.conf.js
+++ b/wdio.conf.js
@@ -117,12 +117,11 @@ exports.config = {
     // Options to be passed to Mocha.
     // See the full list at http://mochajs.org/
     mochaOpts: {
-      compilers: [
-        'tsconfig-paths/register'
-      ],
-        ui: 'bdd',
-        timeout: timeout,
-        grep: "Login"
+      require: 'ts-node/register',
+      extension: ["ts"],
+      ui: 'bdd',
+      timeout: timeout,
+      grep: "Login"
     },
 
     featureFlags: {
```

There seems to be an issue with the TypeScript setup. I will update the docs and make an issue in the boilerplate repo.

**Comment by christian-bromann** [comment]
You can actually keep using `tsconfig-path` here is the better patch:
```git
diff --git a/package.json b/package.json
index e151b62..cad6fcd 100644
--- a/package.json
+++ b/package.json
@@ -25,7 +25,7 @@
     "allure-commandline": "^2.13.0",
     "chai": "^4.2.0",
     "mocha": "^5.2.0",
-    "ts-node": "^7.0.1",
+    "ts-node": "^8.6.2",
     "tsconfig-paths": "^3.9.0",
     "tslint": "^5.20.1",
     "typescript": "^3.8.2",
diff --git a/wdio.conf.js b/wdio.conf.js
index d164713..97331c5 100644
--- a/wdio.conf.js
+++ b/wdio.conf.js
@@ -117,12 +117,13 @@ exports.config = {
     // Options to be passed to Mocha.
     // See the full list at http://mochajs.org/
     mochaOpts: {
+      require: 'ts-node/register',
       compilers: [
         'tsconfig-paths/register'
       ],
-        ui: 'bdd',
-        timeout: timeout,
-        grep: "Login"
+      ui: 'bdd',
+      timeout: timeout,
+      grep: "Login"
     },
 
     featureFlags: {
@@ -159,9 +160,8 @@ exports.config = {
      * @param {Array.<Object>} capabilities list of capabilities details
      * @param {Array.<String>} specs List of spec file paths that are to be run
      */
-    before: function (capabilities, specs) {
-      require('ts-node').register({ files: true });
-    },
+    // before: function (capabilities, specs) {
+    // },
     /**
      * Runs before a WebdriverIO command gets executed.
      * @param {String} commandName hook command name

```

**Comment by pako88** [comment]
yes , that works. thanks @christian-bromann 
so to summarize the main problem was the `require('ts-node').register({ files: true });` in the before hook
this has to move in the mochaOpts.

Thank you!

**Comment by simonDominos** [comment]
@pako88 where did you set { files:true } once it is moved to mochaOpts? i need to use { files: true, logError: false, transpileOnly: true } but cant work out how...

**Comment by mgrybyk** [comment]
@simonDominos it's better to use typed configuration, see https://webdriver.io/docs/typescript.html#typed-configuration
