### ISSUE TITLE
Sample Multiremote tests are failing with keySequence.map is not a function

### ISSUE THREAD

**Issue by dimkin-eu** [webdriverio/webdriverio#5087]
- **WebdriverIO version:** 5.19.0 
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** MacOS Catalina

**Describe the bug**

**To Reproduce**
as described [here](https://github.com/webdriverio/webdriverio/blob/master/examples/README.md)
- git clone git@github.com:webdriverio/webdriverio.git
- cd ./webdriverio
- npm install
- npm run setup

- cd /examples/wdio
- npm run test:multiremote

**Expected behavior**
tests are passing 

**Actual behavior**
3 tests are failing

**Log**
```
% cd ~/test/webdriverio/examples/wdio
% npm run test:multiremote

> @ test:multiremote /Users/dm/test/webdriverio/examples/wdio
> ../../packages/wdio-cli/bin/wdio.js ./multiremote/wdio.conf.js

Execution of 1 spec files started at 2020-03-11T12:40:32.814Z

[0-0] RUNNING in MultiRemote - /multiremote/mocha.test.js
[0-0] TypeError in "multiremote example should login the browser"
keySequence.map is not a function
[0-0] TypeError in "multiremote example should post something in browserA"
keySequence.map is not a function
[0-0] Error in "multiremote example should read the message in browserB"
Can't call getText on element with selector ".messageBody*=My name is" because element wasn't found
[0-0] FAILED in MultiRemote - /multiremote/mocha.test.js

 "spec" Reporter:
------------------------------------------------------------------
[MultiremoteBrowser #0-0] Spec: /Users/dm/test/webdriverio/examples/wdio/multiremote/mocha.test.js
[MultiremoteBrowser #0-0] Running: MultiremoteBrowser
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] multiremote example
[MultiremoteBrowser #0-0]    ✓ should open chat application
[MultiremoteBrowser #0-0]    ✖ should login the browser
[MultiremoteBrowser #0-0]    ✖ should post something in browserA
[MultiremoteBrowser #0-0]    ✖ should read the message in browserB
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] 1 passing (8.3s)
[MultiremoteBrowser #0-0] 3 failing
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] 1) multiremote example should login the browser
[MultiremoteBrowser #0-0] keySequence.map is not a function
[MultiremoteBrowser #0-0] TypeError: keySequence.map is not a function
[MultiremoteBrowser #0-0]     at Browser.apply (/Users/dm/test/webdriverio/packages/webdriverio/src/commands/browser/keys.js:55:40)
[MultiremoteBrowser #0-0]     at Browser.runCommandWithHooks (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:114:34)
[MultiremoteBrowser #0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[MultiremoteBrowser #0-0]     at Browser.apply (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:107:24)
[MultiremoteBrowser #0-0]     at Browser.wrapCommandFn (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:72:44)
[MultiremoteBrowser #0-0]     at map (/Users/dm/test/webdriverio/packages/webdriverio/src/multiremote.js:97:65)
[MultiremoteBrowser #0-0]     at Array.map (<anonymous>)
[MultiremoteBrowser #0-0]     at MultiRemoteDriver.apply (/Users/dm/test/webdriverio/packages/webdriverio/src/multiremote.js:97:43)
[MultiremoteBrowser #0-0]     at MultiRemoteDriver.runCommandWithHooks (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:114:34)
[MultiremoteBrowser #0-0]     at MultiRemoteDriver.apply (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:107:24)
[MultiremoteBrowser #0-0]     at MultiRemoteDriver.wrapCommandFn (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:72:44)
[MultiremoteBrowser #0-0]     at Context.apply (/Users/dm/test/webdriverio/examples/wdio/multiremote/mocha.test.js:9:17)
[MultiremoteBrowser #0-0]     at Context.call (/Users/dm/test/webdriverio/packages/wdio-sync/src/index.js:33:22)
[MultiremoteBrowser #0-0]     at /Users/dm/test/webdriverio/packages/wdio-sync/src/index.js:68:33
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] 2) multiremote example should post something in browserA
[MultiremoteBrowser #0-0] keySequence.map is not a function
[MultiremoteBrowser #0-0] TypeError: keySequence.map is not a function
[MultiremoteBrowser #0-0]     at Browser.apply (/Users/dm/test/webdriverio/packages/webdriverio/src/commands/browser/keys.js:55:40)
[MultiremoteBrowser #0-0]     at Browser.runCommandWithHooks (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:114:34)
[MultiremoteBrowser #0-0]     at Browser.apply (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:107:24)
[MultiremoteBrowser #0-0]     at Browser.wrapCommandFn (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:72:44)
[MultiremoteBrowser #0-0]     at Context.apply (/Users/dm/test/webdriverio/examples/wdio/multiremote/mocha.test.js:16:18)
[MultiremoteBrowser #0-0]     at Context.call (/Users/dm/test/webdriverio/packages/wdio-sync/src/index.js:33:22)
[MultiremoteBrowser #0-0]     at /Users/dm/test/webdriverio/packages/wdio-sync/src/index.js:68:33
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] 3) multiremote example should read the message in browserB
[MultiremoteBrowser #0-0] Can't call getText on element with selector ".messageBody*=My name is" because element wasn't found
[MultiremoteBrowser #0-0] Error: Can't call getText on element with selector ".messageBody*=My name is" because element wasn't found
[MultiremoteBrowser #0-0]     at implicitWait (/Users/dm/test/webdriverio/packages/webdriverio/src/utils/implicitWait.js:27:19)
[MultiremoteBrowser #0-0]     at Element.apply (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:107:24)
[MultiremoteBrowser #0-0]     at Element.apply (/Users/dm/test/webdriverio/packages/wdio-sync/src/wrapCommand.js:72:44)
[MultiremoteBrowser #0-0]     at Element.elementErrorHandlerCallback (/Users/dm/test/webdriverio/packages/webdriverio/src/middlewares.js:41:12)
[MultiremoteBrowser #0-0]     at Context.apply (/Users/dm/test/webdriverio/examples/wdio/multiremote/mocha.test.js:26:42)
[MultiremoteBrowser #0-0]     at Context.call (/Users/dm/test/webdriverio/packages/wdio-sync/src/index.js:33:22)
[MultiremoteBrowser #0-0]     at /Users/dm/test/webdriverio/packages/wdio-sync/src/index.js:68:33
[MultiremoteBrowser #0-0]
[MultiremoteBrowser #0-0] 
[MultiremoteBrowser #0-0] 

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:18 
``` 

Could be nice to have passing sample tests as a release acceptance criteria

**Comment by Photonios** [comment]
This issue seems to have been introduced with this change:

https://github.com/webdriverio/webdriverio/commit/49eda5119d6b7504d25de1ac17e9b60e6f24f419

I reproduced the issue locally and `this.isDevTools` is `true`. This means that `checkUnicode` returns the value as is. Down the line, where the crash happens, it expects `keySequence` to be an array. If `this.isDevTools` is `false`, the value gets converted to a sequence of Unicode characters and everything works. I believe the fix is to make sure `checkUnicode` returns an array, regardless of where `isDevTools` is `true` or not.

I'll submit a PR shortly.

**Comment by christian-bromann** [comment]
> This issue seems to have been introduced with this change:

If you use v5 of WebdriverIO this should not be the cause of the bug as we haven't backported it. Note that everything in master is v6 and we just backport patches that are compatible with v5.

**Comment by Photonios** [comment]
The report is against master. The steps to reproduce descibre cloning directly from Git and running the example. Like this, I was also able to reproduce the issue.

The commit I linked _did_ introduce the issue on master. The bug also doesn't reproduce against v5.
