### ISSUE TITLE
can't run tests with sauce service and https protocol in v6

### ISSUE THREAD

**Issue by pako88** [webdriverio/webdriverio#5116]
**Environment (please complete the following information):**
 - **WebdriverIO version:** v6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 80
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/sauce-service

**Config of WebdriverIO**
-

**Describe the bug**
When running the tests with chromedriver service, everythings working as expected.  
As soon as i run the tests with sauce service, i got following errors:  

```
Execution of 49 spec files started at 2020-03-19T16:27:14.060Z

[0-0] b-4d70-ab2a-d72b619af6ee
For help, see: https://nodejs.org/en/docs/inspector
[0-0] Using aws.proda env file. Method: environment variables
[0-0] Using default/import file.
[0-0] RUNNING in googlechrome - D:\Repos\webdriverio-common\test\specs\example\smoke.ts
[0-0]  Error:  Failed to create session.
Unable to connect to "https://ondemand.eu-central-1.saucelabs.com:443/wd/hub", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-0] ..
```

**Log**
```
2020-03-19T16:27:17.403Z INFO @wdio/local-runner: Run worker command: run
2020-03-19T16:27:20.977Z DEBUG @wdio/local-runner:utils: init remote session
2020-03-19T16:27:20.980Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
2020-03-19T16:27:23.139Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
2020-03-19T16:27:24.527Z DEBUG @wdio/local-runner:utils: init remote session
2020-03-19T16:27:24.528Z INFO webdriverio: Initiate new session using the webdriver protocol
2020-03-19T16:27:24.530Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session
2020-03-19T16:27:24.531Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      'sauce:options': [Object],
      browserName: 'googlechrome',
      browserVersion: 'latest',
      platformName: 'Windows 10',
      'goog:chromeOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    'sauce:options': {
      build: 'wdio AWS:PRODA:Test default - LocalRun:19 Mar 2020 16:27:13',
      extendedDebugging: true,
      idleTimeout: 90,
      maxDuration: 1800,
      seleniumVersion: '3.141.59',
      screenResolution: '1600x1200'
    },
    browserName: 'googlechrome',
    browserVersion: 'latest',
    platformName: 'Windows 10',
    'goog:chromeOptions': { w3c: true }
  }
}
2020-03-19T16:27:25.590Z ERROR webdriver: GotError: connect ECONNREFUSED 127.0.0.1:443
    at onError (D:\Repos\webdriverio-common\node_modules\got\dist\source\request-as-event-emitter.js:140:29)
    at handleRequest (D:\Repos\webdriverio-common\node_modules\got\dist\source\request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
2020-03-19T16:27:25.591Z ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "https://ondemand.eu-central-1.saucelabs.com:443/wd/hub", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
    at startWebDriverSession (D:\Repos\webdriverio-common\node_modules\webdriver\build\utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by pako88** [comment]
looks like this one: https://github.com/sindresorhus/got/issues/951

**Comment by pako88** [comment]
setting following configs works:
```
config.protocol = 'http';
config.port = 80;
```

-> there's definitively a problem in running tests in https with sauce in v6

**Comment by christian-bromann** [comment]
This will be fixed by #5124

**Comment by Xotabu4** [comment]
Getting same issue, but for my own ggr+selenoid cluster. Creating session with curl works fine.

It seems like issue with https-proxy-agent lib (v5.0.0) - somehow it tries connect to localhost:443



WebdriverIO version: v7
Mode: WDIO Testrunner
If WDIO Testrunner, running sync/async: sync
Node.js version: v12.22
NPM version: 6.14.11

        "@wdio/allure-reporter": "^7.5.7",
        "@wdio/cli": "^7.5.7",
        "@wdio/local-runner": "^7.5.7",
        "@wdio/mocha-framework": "^7.5.3",
        "@wdio/spec-reporter": "^7.5.7",

```
  runner: 'local',
  protocol: 'https',
  user: 'test',
  key: '123456',
  hostname: 'ggr.my.server.com',
  port: 443,
  path: '/wd/hub/',
```


```
[0-0] 2021-06-18T11:32:49.065Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:443
[0-0]     at ClientRequest.<anonymous> (/Users/.../Documents/project/web-tests-wdio/node_modules/got/dist/source/core/index.js:956:111)
[0-0]     at Object.onceWrapper (node:events:476:26)
[0-0]     at ClientRequest.emit (node:events:381:22)
[0-0]     at ClientRequest.emit (node:domain:470:12)
[0-0]     at ClientRequest.origin.emit (/Users/.../Documents/project/web-tests-wdio/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
[0-0]     at TLSSocket.socketErrorListener (node:_http_client:472:9)
[0-0]     at TLSSocket.emit (node:events:369:20)
[0-0]     at TLSSocket.emit (node:domain:470:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:188:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:153:3)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1138:16)

[0-0] 2021-06-18T11:32:49.065Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "https://ggr.my.server.com:443/wd/hub/", make sure browser driver is running on that address.
[0-0] If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-0]     at Object.startWebDriverSession (/Users/.../web-tests-wdio/node_modules/webdriver/build/utils.js:68:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:94:5)
[0-0]     at Function.newSession (/Users/.../web-tests-wdio/node_modules/webdriver/build/index.js:58:45)
[0-0]     at Object.remote (/Users/.../web-tests-wdio/node_modules/webdriverio/build/index.js:67:22)
[0-0]     at Runner._startSession (/Users/.../web-tests-wdio/node_modules/@wdio/runner/build/index.js:216:56)
[0-0]     at Runner._initSession (/Users/.../web-tests-wdio/node_modules/@wdio/runner/build/index.js:172:25)
[0-0]     at Runner.run (/Users/.../web-tests-wdio/node_modules/@wdio/runner/build/index.js:87:19)
```

**Comment by christian-bromann** [comment]
@Xotabu4 do you have any services running? Can you try without?

**Comment by Xotabu4** [comment]
@christian-bromann no services running

**Comment by Xotabu4** [comment]
@christian-bromann probably some workaround might be suggested? Unfortunately i can't place my Selenoid test farm behind http

**Comment by christian-bromann** [comment]
@Xotabu4 can you raise a new issue with a detailed explanation?

**Comment by Xotabu4** [comment]
@christian-bromann 
I figured out:


For someone that will be looking for solution in future:

In my project in some deep files i had (we are currently in migration phase)

    import { browser } from 'protractor'

For some reason, some of protractor dependencies, or protractor itself changes behaviour of how webdriverio connects to remote https selenoid, and gives pretty unclear error `ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:443`

Avoid working with dependenices that change global http/https modules behaviour.

This issue pointed that i should check my dependencies: https://github.com/sindresorhus/got/issues/1572
