### ISSUE TITLE
Master build fails due to `Aborted (core dumped)`

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#5146]
Currently our master branch is broken due to a Travis issue where the build breaks due to:

```
Aborted (core dumped)
```

Example: https://travis-ci.org/github/webdriverio/webdriverio/jobs/667206528#L627

I have no idea yet where this comes from and will investigate.

**Comment by christian-bromann** [comment]
Logging the heap size clearly shows how it increases and breaks when 1Gig is reached:

```
PASS packages/wdio-cucumber-framework/tests/reporter.test.js (99 MB heap size)
PASS packages/wdio-allure-reporter/tests/allureFeatures.test.js (139 MB heap size)
PASS packages/wdio-cli/tests/launcher.test.js (107 MB heap size)
PASS packages/wdio-reporter/tests/reporter.listeners.test.js (126 MB heap size)
PASS packages/wdio-spec-reporter/tests/index.test.js (147 MB heap size)
PASS packages/[secure]/tests/utils.test.js (210 MB heap size)
...
PASS packages/[secure]/tests/commands/element/getValue.test.js (962 MB heap size)
PASS packages/[secure]/tests/commands/browser/reactElement.test.js (973 MB heap size)
PASS packages/wdio-local-runner/tests/replQueue.test.js (982 MB heap size)
PASS packages/[secure]/tests/commands/element/setValue.test.js (995 MB heap size)
Aborted (core dumped)
npm ERR! code ELIFECYCLE
```

So  there is some sort of memory leak.

**Comment by jdavis61** [comment]
Hello @christian-bromann, 

Building WebdriverIO on an AWS t3.small EC2 instance fails with the below error. Changing  `--parallel` to `--concurrency 10` in package.json allows the build succeeded.  

Maybe limiting the number of parallel builds will resolve this issue.

**Possible root cause**
```
11 silly lifecycle webdriverio-monorepo@~build-full: Returned: code: 1  signal: null
```

**Debug log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ec2-user/.nvm/versions/node/v10.19.0/bin/node',
1 verbose cli   '/home/ec2-user/.nvm/versions/node/v10.19.0/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-full' ]
2 info using npm@6.13.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild-full', 'build-full', 'postbuild-full' ]
5 info lifecycle webdriverio-monorepo@~prebuild-full: webdriverio-monorepo@
6 info lifecycle webdriverio-monorepo@~build-full: webdriverio-monorepo@
7 verbose lifecycle webdriverio-monorepo@~build-full: unsafe-perm in lifecycle true
8 verbose lifecycle webdriverio-monorepo@~build-full: PATH: /home/ec2-user/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ec2-user/
environment/webdriverio/node_modules/.bin:/home/ec2-user/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ec2-user/environment/webdri
verio/node_modules/.bin:/home/ec2-user/.nvm/versions/node/v10.19.0/bin:/home/ec2-user/.rvm/gems/ruby-2.6.3/bin:/home/ec2-user/.rvm/gems/ruby-2.6.3@global/bin:/home/ec2-user/.rvm/r
ubies/ruby-2.6.3/bin:/home/ec2-user/.rvm/gems/ruby-2.6.3/bin:/home/ec2-user/.rvm/gems/ruby-2.6.3@global/bin:/home/ec2-user/.rvm/rubies/ruby-2.6.3/bin:/home/ec2-user/.rvm/gems/ruby
-2.6.3/bin:/home/ec2-user/.rvm/gems/ruby-2.6.3@global/bin:/home/ec2-user/.rvm/rubies/ruby-2.6.3/bin:/usr/local/bin:/bin:/usr/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/home
/ec2-user/.rvm/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/home/ec2-user/.rvm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/
usr/bin/google-chrome-stable:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/home/ec2-user/.rvm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/bin/google-chrome-
stable
9 verbose lifecycle webdriverio-monorepo@~build-full: CWD: /home/ec2-user/environment/webdriverio
10 silly lifecycle webdriverio-monorepo@~build-full: Args: [ '-c', 'lerna run --parallel build' ]
11 silly lifecycle webdriverio-monorepo@~build-full: Returned: code: 1  signal: null
12 info lifecycle webdriverio-monorepo@~build-full: Failed to exec build-full script
13 verbose stack Error: webdriverio-monorepo@ build-full: `lerna run --parallel build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid webdriverio-monorepo@
15 verbose cwd /home/ec2-user/environment/webdriverio
16 verbose Linux 4.14.165-103.209.amzn1.x86_64
17 verbose argv "/home/ec2-user/.nvm/versions/node/v10.19.0/bin/node" "/home/ec2-user/.nvm/versions/node/v10.19.0/lib/node_modules/npm/bin/npm-cli.js" "run" "build-full"
18 verbose node v10.19.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error webdriverio-monorepo@ build-full: `lerna run --parallel build`
22 error Exit status 1
23 error Failed at the webdriverio-monorepo@ build-full script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jdavis61** [comment]
Building WebdriverIO on an AWS EC2 m5.large instance with the `--parallel` switch enabled works perfectly.

AWS specs (for everyone's reference)
t3.small: 2 vCPUs, 2 GiB of memory 
m5.large: 2 vCPUs, 8 GiB of memory

**Comment by christian-bromann** [comment]
@jdavis61 thanks for investigating. The large code base definitely requires some memory to build. The problem stated in this issue is about the Jest unit tests in the Travis pipeline.

**Comment by christian-bromann** [comment]
It seems that the build is passing again thanks to some global cleanups in the tests, see https://github.com/webdriverio/webdriverio/commit/ec9b6c4c3d4dbad44ce100f228dbb3c45be85a7c
