### ISSUE TITLE
Tests failed via Mocha afterEach conditional failure reported as passed *and* failed!

### ISSUE THREAD

**Issue by GCHQDeveloper911** [webdriverio/webdriverio#5181]
**Environment (please complete the following information):**
 - **WebdriverIO version: 6.0.5
 - **Mode: Testrunner
 - **If WDIO Testrunner, running sync/async: Sync
 - **Node.js version: 10.19.0
 - **NPM version: 6.13.4
 - **Browser name and version: Chrome 80.0.3987.149
 - **Platform name and version: CentOS 8
 - **Additional wdio packages used (if applicable): node_modules/@wdio contains: cli  config  local-runner  logger  mocha-framework  protocols  repl  reporter  runner  spec-reporter  sync  utils

**Config of WebdriverIO**
wdio.conf.js as generated, plus hooks:
```
    before: function() {
        const chai = require('chai');
        global.expect = chai.expect;
        chai.Should();
    },

    beforeTest: function (test, context) {
        browser.config.specErrors = [];
    },
```

**Describe the bug**
The above test uses try/catch to allow ALL errors in a mocha test, rather than fail on first, and uses a conditional fail at the end as advised here: https://github.com/mochajs/mocha/wiki/HOW-TO:-Conditionally-fail-a-test-after-completion

It works fine, except that WDIO output reports the test as both failed AND passed!....
```
------------------------------------------------------------------
[chrome  linux #0-0] Spec: /home/user/dev/WDIO/test/specs/main.js
[chrome  linux #0-0] Running: chrome on linux
[chrome  linux #0-0] Session ID: 7602b29963a51e412dc07dab542274cd
[chrome  linux #0-0]
[chrome  linux #0-0] suite definition
[chrome  linux #0-0]    ✖ spec definition 1
[chrome  linux #0-0]
[chrome  linux #0-0] 1 passing (138ms)
[chrome  linux #0-0] 1 failing
[chrome  linux #0-0]
[chrome  linux #0-0] 1) suite definition spec definition 1
[chrome  linux #0-0] just because
[chrome  linux #0-0] Error: just because
[chrome  linux #0-0]     at Context.<anonymous> (/home/user/dev/WDIO/test/specs/main.js:7:25)
[chrome  linux #0-0]     at callFn (/home/user/dev/WDIO/node_modules/mocha/lib/runnable.js:395:21)
[chrome  linux #0-0]     at Hook.Runnable.run (/home/user/dev/WDIO/node_modules/mocha/lib/runnable.js:382:7)
[chrome  linux #0-0]     at next (/home/user/dev/WDIO/node_modules/mocha/lib/runner.js:389:10)
[chrome  linux #0-0]     at Immediate._onImmediate (/home/user/dev/WDIO/node_modules/mocha/lib/runner.js:433:5)
[chrome  linux #0-0]     at runCallback (timers.js:705:18)
[chrome  linux #0-0]     at tryOnImmediate (timers.js:676:5)
[chrome  linux #0-0]     at processImmediate (timers.js:658:5)
[chrome  linux #0-0]     at process.topLevelDomainCallback (domain.js:126:23)


Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:01 


```

**To Reproduce**

Sample spec:
```

describe('suite definition', function () {

    this.afterEach(function () {
        this.test.error(new Error('just because'));
    })

    it('spec definition 1', function () {
        expect(1).to.equal(1);
    })

})
```

**Expected behavior**
The tests are being failed, which is correct - and the summary report at the end of the run is correct. However, it appears the count of passed tests is erroneously being incremented. This should not happen. In the above example, 0 tests should be reported as passed.

**Log**
If applicable, add logs to help explain your problem.
N/A - above should be sufficient

**Additional context**
None

**Comment by christian-bromann** [comment]
Well described! Any help on this would be appreciated.

**Comment by GCHQDeveloper911** [comment]
Hi Christian, I did a bit of digging, and I think it's an issue with Mocha, rather than WebdriverIO.... I'd appreciate someone confirming though....

Away from my WebdriverIO setup, I created an empty folder, and installed Mocha on it's own. Created a test:

```
var assert = require('assert');

    afterEach(function () {
            this.test.error(new Error('test'));
    })

describe('Simple suite', function() {
    it('compares 1 to 1', function() {
      assert.equal(1,1);
  });
});
```

And output was similar to the bug above:
```
$ ./node_modules/.bin/mocha 

  Simple suite
    ✓ compares 1 to 1
    1) compares 1 to 1

  1 passing (4ms)
  1 failing

  1) Simple suite
       compares 1 to 1:
     Error: test
      at Context.<anonymous> (test/test.js:4:29)

```

Thoughts?

**Comment by christian-bromann** [comment]
@GCHQDeveloper911 interesting. So it seems to me that Mocha reports this test twice (as test pass and test hook failure). We can address this by enhancing the [spec reporter](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-spec-reporter/src/index.js) to mitigate this.

**Comment by BorisOsipov** [comment]
@GCHQDeveloper911 is this reproducible with wdio v5? I kindly ask you check it or share simple project to play with this. I am wondering how other reporters deal with it.

**Comment by GCHQDeveloper911** [comment]
@BorisOsipov I first encountered it with 5, then moved to 6 to see if it was resolved. To reproduce / play with it, please just set up a simple WDIO testrunner project, and see the sample spec code above. Please do report back anything you find in other reporters, where I do think you make a valid point.... @christian-bromann Am I misunderstanding something, but would enhancing the spec reporter not just "leave other reporters behind" with the same issue? 

I'm talking to the guys that work on Mocha. They have acknowledged that the test end event fires before afterEach hooks are executed.... I'm hoping to persuade them that what is "by historical design" could and should be changed, and as such work on any WDIO reporters etc would not be necessary.

**Comment by christian-bromann** [comment]
@GCHQDeveloper911 awesome, can you link the Mocha issue here so we can follow along?

> but would enhancing the spec reporter not just "leave other reporters behind" with the same issue?

Not sure if other reporters deal with this in the similar fashion. It could be that we can fix it at a more central position, e.g. in the `@wdio/reporter` package to fix it for all reporters.

**Comment by pmerwin** [comment]
FWIW, I ran the example spec with my vs 6 library and I am seeing:

```
 "spec" Reporter:
------------------------------------------------------------------
[HeadlessChrome 19.4.0 darwin #0-0] Spec: /Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/self_tests/mocha.passing.spec.js
[HeadlessChrome 19.4.0 darwin #0-0] Running: HeadlessChrome (v19.4.0) on darwin
[HeadlessChrome 19.4.0 darwin #0-0] Session ID: a3e3ce2a-a1ab-4130-8385-2d65083eee5a
[HeadlessChrome 19.4.0 darwin #0-0]
[HeadlessChrome 19.4.0 darwin #0-0] suite definition
[HeadlessChrome 19.4.0 darwin #0-0]    ✖ spec definition 1
[HeadlessChrome 19.4.0 darwin #0-0]
[HeadlessChrome 19.4.0 darwin #0-0] 2 failing (272ms)
[HeadlessChrome 19.4.0 darwin #0-0]
[HeadlessChrome 19.4.0 darwin #0-0] 1) suite definition spec definition 1
[HeadlessChrome 19.4.0 darwin #0-0] just because
[HeadlessChrome 19.4.0 darwin #0-0] Error: just because
[HeadlessChrome 19.4.0 darwin #0-0]     at Context.<anonymous> (/Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/self_tests/mocha.passing.spec.js:15:25)
```

my config:

```
{
  hostname: undefined,
  port: undefined,
  protocol: undefined,
  path: undefined,
  specs: [ './self_tests/mocha.passing.spec.js' ],
  suites: {},
  exclude: [],
  outputDir: './data/wdio-logs',
  logLevel: 'trace',
  logLevels: {},
  excludeDriverLogs: [],
  bail: 0,
  waitforInterval: 500,
  waitforTimeout: 15000,
  framework: 'mocha',
  reporters: [ [ 'json', [Object] ], 'spec' ],
  services: [],
  maxInstances: 5,
  maxInstancesPerCapability: 100,
  filesToWatch: [],
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  execArgv: [],
  runnerEnv: {},
  runner: 'local',
  mochaOpts: {
    timeout: 840000,
    ui: 'bdd',
    compilers: [ 'js:@babel/register' ],
    bail: true
  },
  jasmineNodeOpts: { defaultTimeoutInterval: 10000 },
  cucumberOpts: { timeout: 10000 },
  onPrepare: [],
  onWorkerStart: [],
  before: [ [Function: bound ] ],
  beforeSession: [ [Function: bound ] ],
  beforeSuite: [],
  beforeHook: [],
  beforeTest: [ [Function: bound ] ],
  beforeCommand: [],
  afterCommand: [],
  afterTest: [ [Function: bound ] ],
  afterHook: [],
  afterSuite: [],
  afterSession: [],
  after: [],
  onComplete: [],
  onReload: [],
  beforeFeature: [],
  beforeScenario: [],
  beforeStep: [],
  afterStep: [],
  afterScenario: [],
  afterFeature: [],
  automationProtocol: 'devtools',
  logDir: './data/wdio-logs',
  seleniumLogs: './data/wdio-logs',
  screenshotPath: './data/report/errors',
  baseUrl: 'https://www.cbtnuggets.com',
  specFileRetries: 0,
  ignoredWorkerServices: [],
  specFileRetryAttempts: 0
}
```

packages:

```
  "devDependencies": {
    "@wdio/dot-reporter": "^6.0.11",
    "@wdio/selenium-standalone-service": "^6.0.11",
    "@wdio/spec-reporter": "^6.0.11",
    "eslint": "^6.8.0",
    "eslint-config-cbtnuggets": "^8.2.1"
  },
  "dependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "@babel/register": "^7.9.0",
    "@cbtnuggets/lib-service-test-utils-nodejs": "^2.3.35",
    "@cbtnuggets/lib-test-manage-user-pool-client-nodejs": "^1.2.1",
    "@wdio/cli": "^6.0.11",
    "@wdio/devtools-service": "^6.0.11",
    "@wdio/local-runner": "^6.0.11",
    "@wdio/logger": "^6.0.11",
    "@wdio/mocha-framework": "^6.0.11",
    "@wdio/sauce-service": "^6.0.11",
    "@wdio/sync": "^6.0.11",
    "chai": "^4.2.0",
    "commander": "4.1.1",
    "deepmerge": "^4.2.2",
    "devtools": "^6.0.11",
    "dogapi": "^2.8.3",
    "expect": "^25.2.4",
    "expect-webdriverio": "^1.0.0",
    "fs-extra": "^9.0.0",
    "lodash": "^4.17.15",
    "mailosaur": "^6.0.5",
    "moment": "^2.24.0",
    "puppeteer-core": "2.1.1",
    "q": "^1.5.1",
    "random-name": "^0.1.2",
    "sauce-connect-launcher": "^1.3.1",
    "superagent": "^5.2.2",
    "wdio-intercept-service": "^4.1.0",
    "wdio-json-reporter": "^1.4.0",
    "webdriverio": "^6.0.11"
  }
}
```

**Comment by GCHQDeveloper911** [comment]
Hi Christian, no issue raised in mocha, just a gitter chat. I offered to raise a ticket, and the response was "No, I'm not planning to change this design. It's more complex than just a quick one-liner, and I don't see a strong reason to take that risk at the moment."

I wonder how many other tools that use Mocha are affected too?! Oh well...

Anyway, I guess it's back to your proposed changes to @wdio/reporter?! :)

**Comment by christian-bromann** [comment]
> Anyway, I guess it's back to your proposed changes to @wdio/reporter?! :)

Yes, let's do the change there.

**Comment by GCHQDeveloper911** [comment]
@pmerwin  Sorry, missed your comment before. Not sure why/how it's ok for you.... 

My packages:
```
  "dependencies": {
    "@wdio/cli": "^6.0.13"
  },
  "devDependencies": {
    "@wdio/local-runner": "^6.0.13",
    "@wdio/mocha-framework": "^6.0.13",
    "@wdio/spec-reporter": "^6.0.12",
    "@wdio/sync": "^6.0.12",
    "chai": "^4.2.0",
    "chromedriver": "^80.0.2",
    "wdio-chromedriver-service": "^6.0.1"
  }

```

My config:
```
exports.config = {
    debug: true,
    execArgv: ['--inspect-brk=127.0.0.1:9229'],
    runner: 'local',
    path: '/',
    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [
    ],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: ['--headless']
        }
    }],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://google.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 900000,
        bail: true
    },
    before: function() {
        const chai = require('chai');
        global.expect = chai.expect;
        chai.Should();
    },
    beforeTest: function (test, context) {
        browser.config.specErrors = [];
    },
}
```

**Comment by GCHQDeveloper911** [comment]
Hi @christian-bromann 
Just been looking into this a bit.... I think unfortunately any mitigation code *will* have to go in the spec-reporter (and other reporters?), rather than the top level reporter... The reason being simply because in the top level reporter, this.on('test:end')... gets called before the afterEach hook... so the pass/fail counts that go forward to spec reporter etc are already 'set' before the afterEach hook triggers the fail.

I think the solution / change to be made in the spec-reporter (and I assume similar in other reporters) is to update onTestPass and onTestFail something like:

```
  onTestPass() {
    this.stateCounts.prevPassed = this.stateCounts.passed;
    this.stateCounts.passed++;
  }

  onTestFail() {
    this.stateCounts.failed++;
    if (this.stateCounts.prevPassed == this.stateCounts.passed - 1) {
        this.stateCounts.passed--;
    }
  }
```
ie use a 'prevPassed' count to track whether 'passed' was incremented erronously, and revert it if required?

If you're happy with this suggestion, I'll look to get a PR in later this week.

**Comment by christian-bromann** [comment]
> If you're happy with this suggestion, I'll look to get a PR in later this week.

This sounds good to me!

**Comment by pmerwin** [comment]
> @pmerwin Sorry, missed your comment before. Not sure why/how it's ok for you....
> 
> My packages:
> 
> ```
>   "dependencies": {
>     "@wdio/cli": "^6.0.13"
>   },
>   "devDependencies": {
>     "@wdio/local-runner": "^6.0.13",
>     "@wdio/mocha-framework": "^6.0.13",
>     "@wdio/spec-reporter": "^6.0.12",
>     "@wdio/sync": "^6.0.12",
>     "chai": "^4.2.0",
>     "chromedriver": "^80.0.2",
>     "wdio-chromedriver-service": "^6.0.1"
>   }
> ```
> 
> My config:
> 
> ```
> exports.config = {
>     debug: true,
>     execArgv: ['--inspect-brk=127.0.0.1:9229'],
>     runner: 'local',
>     path: '/',
>     specs: [
>         './test/specs/**/*.js'
>     ],
>     exclude: [
>     ],
>     maxInstances: 10,
>     capabilities: [{
>         maxInstances: 5,
>         browserName: 'chrome',
>         'goog:chromeOptions': {
>             args: ['--headless']
>         }
>     }],
>     logLevel: 'info',
>     bail: 0,
>     baseUrl: 'http://google.com',
>     waitforTimeout: 10000,
>     connectionRetryTimeout: 90000,
>     connectionRetryCount: 3,
>     services: ['chromedriver'],
>     framework: 'mocha',
>     reporters: ['spec'],
>     mochaOpts: {
>         ui: 'bdd',
>         timeout: 900000,
>         bail: true
>     },
>     before: function() {
>         const chai = require('chai');
>         global.expect = chai.expect;
>         chai.Should();
>     },
>     beforeTest: function (test, context) {
>         browser.config.specErrors = [];
>     },
> }
> ```

Looks like you are using chrome driver and I am using devtools back end ?  Maybe that is the difference?

**Comment by erwinheitzman** [comment]
@BorisOsipov I think we might have already indirectly resolved this, do you know if this is still a valid case?
