### ISSUE TITLE
Error in browserstack service(v6.0.6) while intiating browserstack local binary

### ISSUE THREAD

**Issue by anandhaprakash04** [webdriverio/webdriverio#5186]
**Environment (please complete the following information):**
 - **WebdriverIO version:*6.0.6* 
 - **Mode: *WDIO Testrunner*
 - **If WDIO Testrunner, running sync/async:*Sync* 
 - **Node.js version:*10.16.3*
 - **NPM version:*6.9.0*
 - **Browser name and version:*Chrome 80*
 - **Platform name and version:*Mac*
 - **Additional wdio packages used (if applicable):
```
"devDependencies": {
    "@types/jasmine": "3.5.10",
    "@wdio/allure-reporter": "6.0.6",
    "@wdio/browserstack-service": "6.0.6",
    "@wdio/cli": "6.0.6",
    "@wdio/config": "6.0.6",
    "@wdio/jasmine-framework": "6.0.6",
    "@wdio/local-runner": "6.0.6",
    "@wdio/logger": "6.0.6",
    "@wdio/repl": "6.0.6",
    "@wdio/selenium-standalone-service": "6.0.6",
    "@wdio/spec-reporter": "6.0.6",
    "@wdio/sync": "6.0.6",
    "@wdio/utils": "6.0.6",
    "dotenv": "^8.2.0",
    "typescript": "^3.7.5",
    "webdriverio": "^5.18.6",
    "yargs": "^15.1.0"
  },
```

**Config of WebdriverIO**
https://github.com/anandhaprakash04/wdio-test-project/blob/master/wdio.conf.ts

**Describe the bug**

Getting below error when running the test with service as browserstack and local as true
```

Execution of 1 spec files started at 2020-03-31T17:59:05.481Z

2020-03-31T17:59:05.513Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-03-31T17:59:05.517Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
TypeError: this.addArgs is not a function
    at Local.start (/Users/amani/github_repos/wdio-test-project/node_modules/browserstack-local/lib/Local.js:31:10)
    at Promise (internal/util.js:274:30)
    at new Promise (<anonymous>)
    at internal/util.js:273:12
    at BrowserstackLauncherService.onPrepare (/Users/amani/github_repos/wdio-test-project/node_modules/@wdio/browserstack-service/build/launcher.js:67:76)
    at Promise.all.launcher.map.service (/Users/amani/github_repos/wdio-test-project/node_modules/@wdio/cli/build/utils.js:51:33)
    at Array.map (<anonymous>)
    at runServiceHook (/Users/amani/github_repos/wdio-test-project/node_modules/@wdio/cli/build/utils.js:49:39)
    at Launcher.run (/Users/amani/github_repos/wdio-test-project/node_modules/@wdio/cli/build/launcher.js:79:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Continue...
2020-03-31T17:59:05.519Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-03-31T17:59:05.520Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.ts
[0-0] 2020-03-31T17:59:06.107Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-03-31T17:59:06.177Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in chrome - /dist/src/specs/basic.js
[0-0] 2020-03-31T17:59:06.491Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-03-31T17:59:06.503Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session

```

**To Reproduce**

I have created this project https://github.com/anandhaprakash04/wdio-test-project for you to reproduce. 

Please follow the read me file to execute and get the error.

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
https://gist.github.com/anandhaprakash04/0fe33db40b5cd7cd3da83f51f41ae60b

**Comment by ctavan** [comment]
@anandhaprakash04 I am experiencing the same problem and I _think_ that #5187 should fix this issue.

**Comment by christian-bromann** [comment]
Let's move conversation to #5187
