### ISSUE TITLE
Can not upload file over 5 MB on Selenium standalone and selenoid using browser.uploadFile

### ISSUE THREAD

**Issue by Foduch** [webdriverio/webdriverio#5208]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.13
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** chrome (v80.0.3987.149)
 - **Platform name and version:** Linux Ubuntu
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone-service, @wdio/local-runner, @wdio/mocha-framework, @wdio/spec-reporter, 

**Config of WebdriverIO**
~~~~
exports.config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [
    ],
    maxInstances: 10,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
    }],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['selenium-standalone'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
}

~~~~

**Describe the bug**
When try to upload file 5 MB size or larger by browser.uploadFile, throws `RangeError Maximum call stack size exceeded`
Files less 3MB  uploaded correctly
wdio 5.* do not throws this error on same size files

**To Reproduce**
- clone repository
- run `npm i`
- make `./node_modules/.bin/selenium-standalone install`
- run test `./node_modules/.bin/wdio`

[Test repository](https://github.com/Foduch/uploadFile)

**Expected behavior**
Expected full path of uploaded file

**Log**
~~~~
Execution of 1 spec files started at 2020-04-03T12:55:06.049Z

2020-04-03T12:55:06.113Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-04-03T12:55:08.318Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-04-03T12:55:08.319Z INFO @wdio/local-runner: Start worker 0-0 with arg: 
[0-0] 2020-04-03T12:55:08.529Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-04-03T12:55:08.535Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in chrome - /test/specs/uploadFile/test.js
[0-0] 2020-04-03T12:55:08.650Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-04-03T12:55:08.651Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2020-04-03T12:55:08.651Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' }
}
[0-0] RangeError in "Upload file Should upload file over 5 MB"
Maximum call stack size exceeded
[0-0] 2020-04-03T12:55:09.593Z INFO webdriver: COMMAND deleteSession()
[0-0] 2020-04-03T12:55:09.593Z INFO webdriver: [DELETE] http://localhost:4444/wd/hub/session/b7fef273bb17b4929a35d63bd16c8b58
[0-0] FAILED in chrome - /test/specs/uploadFile/test.js
2020-04-03T12:55:09.756Z INFO @wdio/cli:launcher: Run onComplete hook
2020-04-03T12:55:09.757Z INFO @wdio/selenium-standalone-service: shutting down all browsers

 "spec" Reporter:
------------------------------------------------------------------
[chrome 80.0.3987.149 Linux #0-0] Spec: /home/chigarkin/MyProjects/uploadFile/test/specs/uploadFile/test.js
[chrome 80.0.3987.149 Linux #0-0] Running: chrome (v80.0.3987.149) on Linux
[chrome 80.0.3987.149 Linux #0-0] Session ID: b7fef273bb17b4929a35d63bd16c8b58
[chrome 80.0.3987.149 Linux #0-0]
[chrome 80.0.3987.149 Linux #0-0] Upload file
[chrome 80.0.3987.149 Linux #0-0]    ✖ Should upload file over 5 MB
[chrome 80.0.3987.149 Linux #0-0]
[chrome 80.0.3987.149 Linux #0-0] 1 failing (359ms)
[chrome 80.0.3987.149 Linux #0-0]
[chrome 80.0.3987.149 Linux #0-0] 1) Upload file Should upload file over 5 MB
[chrome 80.0.3987.149 Linux #0-0] Maximum call stack size exceeded
[chrome 80.0.3987.149 Linux #0-0] RangeError: Maximum call stack size exceeded
[chrome 80.0.3987.149 Linux #0-0]     at RegExp.test (<anonymous>)
[chrome 80.0.3987.149 Linux #0-0]     at isBase64 (/home/chigarkin/MyProjects/uploadFile/node_modules/is-base64/is-base64.js:30:50)
[chrome 80.0.3987.149 Linux #0-0]     at /home/chigarkin/MyProjects/uploadFile/node_modules/@wdio/utils/build/utils.js:64:63
[chrome 80.0.3987.149 Linux #0-0]     at Array.map (<anonymous>)
[chrome 80.0.3987.149 Linux #0-0]     at commandCallStructure (/home/chigarkin/MyProjects/uploadFile/node_modules/@wdio/utils/build/utils.js:61:25)
[chrome 80.0.3987.149 Linux #0-0]     at Browser.protocolCommand (/home/chigarkin/MyProjects/uploadFile/node_modules/webdriver/build/command.js:69:57)
[chrome 80.0.3987.149 Linux #0-0]     at Browser.wrapCommandFn (/home/chigarkin/MyProjects/uploadFile/node_modules/@wdio/sync/build/wrapCommand.js:54:17)
[chrome 80.0.3987.149 Linux #0-0]     at Archiver.<anonymous> (/home/chigarkin/MyProjects/uploadFile/node_modules/webdriverio/build/commands/browser/uploadFile.js:30:127)
[chrome 80.0.3987.149 Linux #0-0]     at Archiver.emit (events.js:311:20)
[chrome 80.0.3987.149 Linux #0-0]     at Archiver.EventEmitter.emit (domain.js:482:12)


Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:03 
~~~~

**Comment by tawfiknouri** [comment]
Webdriverio use an external library https://github.com/miguelmota/is-base64 in to check base64 validity 

https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-utils/src/utils.js

The "RangeError Maximum call stack size exceeded" exception is raised by "is-base64" library

**Comment by christian-bromann** [comment]
@tawfiknouri so a `.length` check would fix this issue. Mind making a PR for this?

**Comment by tawfiknouri** [comment]
@christian-bromann 
I'm not sure if the .length check is the better way ...
I think it will be more clean if we can find a fixe for "is-base64" library or replace this lib with a simple function and limiting external dependencies

**Comment by christian-bromann** [comment]
@tawfiknouri sounds reasonable to me

**Comment by tawfiknouri** [comment]
issue is created, so waiting update from miguelmota
https://github.com/miguelmota/is-base64/issues/10

And this function work fine for me without "is-base64" library 

```
function isBase64(str) {
    var notBase64 = /[^A-Z0-9+\/=]/i;
    const isString = (typeof str === 'string' || str instanceof String);

    if (!isString) {
      let invalidType;
      if (str === null) {
        invalidType = 'null';
      } else {
        invalidType = typeof str;
        if (invalidType === 'object' && str.constructor && str.constructor.hasOwnProperty('name')) {
          invalidType = str.constructor.name;
        } else {
          invalidType = `a ${invalidType}`;
        }
      }
      throw new TypeError(`Expected string but received ${invalidType}.`);
    }

    const len = str.length;
    if (!len || len % 4 !== 0 || notBase64.test(str)) {
      return false;
    }
    const firstPaddingChar = str.indexOf('=');
    return firstPaddingChar === -1 ||
      firstPaddingChar === len - 1 ||
      (firstPaddingChar === len - 2 && str[len - 1] === '=');

  }
```

**Comment by christian-bromann** [comment]
@tawfiknouri would you mind providing a PR?

**Comment by tawfiknouri** [comment]
https://github.com/webdriverio/webdriverio/pull/5260

**Comment by christian-bromann** [comment]
Let's move convo there.
