### ISSUE TITLE
Webdriver IO & Appium: invalid argument: 'url' must be a string while navigating to website on mobile browser

### ISSUE THREAD

**Issue by Vardhan18** [webdriverio/webdriverio#5230]
**Environment :**
 - **WebdriverIO version:** [6.0.13]
 - **Mode:** [Appium Customer server http://xxxxx:80/appium]
 - **Node.js version:** [v 12.13.1]
 - **NPM version:** [6.12.1]
 - **Browser name and version:** [chrome 80]
 - **Platform name and version:** [Windows 10]
 - **Additional wdio packages used (if applicable):** ["@wdio/cli": "^6.0.13",
		"@wdio/local-runner": "^6.0.13",
		"@wdio/cucumber-framework": "^6.0.13",
		"@wdio/allure-reporter": "^6.0.12",
		"chromedriver": "^80.0.2",
		"wdio-chromedriver-service": "^6.0.1",
		"@wdio/sauce-service": "^6.0.13",
		"@wdio/jasmine-framework": "^6.0.13"]

**Config of WebdriverIO**
WebdriverIO config
```js
exports.config = {
    runner: 'local',
    hostname: 'xx.xx.xx.xx',
    port: 80,
    path: '/Appium',
    specs: ['tests/features/*.feature'],
    maxInstances: 10,
    capabilities: [{
      deviceConnectUsername: "XXXXX",
      deviceConnectApiKey: "XXXX",
      deviceConnectDevice: "XXXX",
      browserName: "chrome",
      acceptInsecureCerts : true,
      automationName: "UiAutomator2"
    }],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'https://www.github.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: 'cucumber',
     cucumberOpts: {
        requireModule: ['@babel/register'],
        require: ["./tests/steps/*.steps.js"],
        backtrace: true,
        compiler: [],
        dryRun: false,
        failFast: false,
        format: ['pretty'],
        colors: true,
        snippets: true,
        source: true,
        profile: [],
        strict: false,
        tags: [],
        timeout: 100000,
        ignoreUndefinedDefinitions: false,
        tagExpression: 'not @skip',
    },
} 
```
**Describe the bug**
Receiving following error while navigating to the url in Appium logs
```log
[debug] [WD Proxy] Matched '/wd/hub/session/ddd7089c-bddd-4df2-9a64-9e9de630cf51/url' to command name 'setUrl' 
 [debug] [WD Proxy] Proxying [POST /wd/hub/session/ddd7089c-bddd-4df2-9a64-9e9de630cf51/url] to [POST http://127.0.0.1:23260/wd/hub/session/3c62c83ce331d49ffc8ff00186d89366/url] with body: {"{\"url\":\"https://www.github.com/\"}":""}
 [WD Proxy] Got an unexpected response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: 'url' must be a string\n
```

**Cucumber Step File Content**

```js
const { Given,When,Then } = require('cucumber');

Given(/^I go on the website "([^"]*)"$/, async function(url) {
    await browser.url(url);

});
```

**Expected behavior**
URL should be launched on the mobile browser

**Log**
**WebDriverIo Logs:**
```log
 INFO webdriver: DATA { url: 'https://github.com/' }
[0-0] ERROR webdriver: Request failed due to Error: invalid argument: 'url' must be a string  (Session info: chrome=80.0.3987.149)
    at getErrorFromResponseBody (C:\U\Hello\node_modules\webdriver\build\utils.js:124:10)
    at WebDriverRequest._request (C:\U\Hello\node_modules\webdriver\build\request.js:118:56)    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Browser.wrapCommandFn (C:\U\Hello\node_modules\@wdio\utils\build\shim.js:74:23)
    at Browser.wrapCommandFn (C:\U\Hello\node_modules\@wdio\utils\build\shim.js:74:23)
    at World.<anonymous> (C:\U\Hello\tests\steps\/abcd.steps.js:5:5)
    at World.executeAsync (C:\U\Hello\node_modules\@wdio\utils\build\shim.js:123:12)
    at World.testFrameworkFnWrapper (C:\U\Hello\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:57:14)
[0-0] Error in "Example feature: Get size of an element: Given I go on the website "https://github.com/""
invalid argument: 'url' must be a string
  (Session info: chrome=80.0.3987.149)
[0-0] 2020-04-07T11:52:18.799Z INFO webdriver: COMMAND deleteSession()
```
 
**APPIUM logs:**
```log
[2020-04-07 07:52:40.3112, 26912] [HTTP] <-- POST /wd/hub/session 200 6277 ms - 1298
[2020-04-07 07:52:40.3112, 26912] [HTTP]
[2020-04-07 07:52:41.7949, 26912] [HTTP] --> POST /wd/hub/session/76dfd7df-dffd-4e2c-b287-10b67029c880/url
[2020-04-07 07:52:41.7950, 26912] [HTTP] {"{\"url\":\"https://github.com/\"}":""}
[2020-04-07 07:52:41.7971, 26912] [MJSONWP (76dfd7df)] Driver proxy active, passing request on via HTTP proxy
[2020-04-07 07:52:41.7976, 26912] [debug] [WD Proxy] Matched '/wd/hub/session/76dfd7df-dffd-4e2c-b287-10b67029c880/url' to command name 'setUrl'
[2020-04-07 07:52:41.7978, 26912] [debug] [WD Proxy] Proxying [POST /wd/hub/session/76dfd7df-dffd-4e2c-b287-10b67029c880/url] to [POST http://127.0.0.1:23266/wd/hub/session/332bee14d185b4173a5661043bba6ad7/url] with body: {"{\"url\":\"https://github.com/\"}":""}
[2020-04-07 07:52:41.8257, 26912] [WD Proxy] Got an unexpected response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: 'url' must be a string\n  (Session info: chrome=80.0.3987.149)","stacktrace":"0   chromedriver-79.0.3945.36-79to79    0x000000010d687e29 chromedriver-79.0.3945.36-79to79 + 3817001\n1   chromedriver-79.0.3945.36-79to79    0x000000010d61bf33 chromedriver-79.0.3945.36-79to79 + 3374899\n2   chromedriver-79.0.3945.36-79to79    0x000000010d39c8bf chromedriver-79.0.3945.36-79to79 + 755903\n3   chromedriver-79.0.3945.36-79to79    0x000000010d3321e1 chromedriver-79.0.3945.36-79to79 + 319969\n4   chromedriver-79.0.3945.36-79to79    0x000000010d325192 chromedriver-79.0.3945.36-79to79 + 266642\n5   chromedriver-79.0.3945.36-79to79    0x000000010d331c1b chromedriver-79.0.3945.36-79to79 + 318491\n6   chromedriver-79.0.3945.36-79to79    0x000000010d3254a3 chromedriver-79.0.3945.36-79to79 + 267427\n7   chromedriver-79.0.3945.36-79to79    0x000000010d2fec0d chromedriver-79.0.3945.36-79to79 + 109581\n8   chromedriver-79.0.3945.36-79to79    0x000000010d2ffba5 ...
[2020-04-07 07:52:41.8474, 26912] [debug] [MJSONWP (76dfd7df)] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: 400 - {"value":{"error":"invalid argument","message":"invalid argument: 'url' must be a string\n  (Session info: chrome=80.0.3987.149)","stacktrace":"0   chromedriver-79.0.3945.36-79to79    0x000000010d687e29 chromedriver-79.0.3945.36-79to79 + 3817001\n1   chromedriver-79.0.3945.36-79to79    0x000000010d61bf33 chromedriver-79.0.3945.36-79to79 + 3374899\n2   chromedriver-79.0.3945.36-79to79    0x000000010d39c8bf chromedriver-79.0.3945.36-79to79 + 755903\n3   chromedriver-79.0.3945.36-79to79    0x000000010d3321e1 chromedriver-79.0.3945.36-79to79 + 319969\n4   chromedriver-79.0.3945.36-79to79    0x000000010d325192 chromedriver-79.0.3945.36-79to79 + 266642\n5   chromedriver-79.0.3945.36-79to79    0x000000010d331c1b chromedriver-79.0.3945.36-79to79 + 318491\n6   chromedriver-79.0.3945.36-79to79    0x000000010d3254a3 chromedriver-79.0.3945.36-79to79 + 267427\n7   chromedriver-79.0.3945.36-79to79    0x000000010d2fec0d chromedriver-79.0.3945.36-79to79 + 109581\n8   chromedriver-79.0.3945.36-79to79    0x000000010d2ffba5 chromedriver-79.0.3945.36-79to79 + 113573\n9   chromedriver-79.0.3945.36-79to79    0x000000010d649f6f chromedriver-79.0.3945.36-79to79 + 3563375\n10  chromedriver-79.0.3945.36-79to79    0x000000010d656e3a chromedriver-79.0.3945.36-79to79 + 3616314\n11  chromedriver-79.0.3945.36-79to79    0x000000010d656bf7 chromedriver-79.0.3945.36-79to79 + 3615735\n12  chromedriver-79.0.3945.36-79to79    0x000000010d629699 chromedriver-79.0.3945.36-79to79 + 3430041\n13  chromedriver-79.0.3945.36-79to79    0x000000010d657692 chromedriver-79.0.3945.36-79to79 + 3618450\n14  chromedriver-79.0.3945.36-79to79    0x000000010d63de17 chromedriver-79.0.3945.36-79to79 + 3513879\n15  chromedriver-79.0.3945.36-79to79    0x000000010d66cfe4 chromedriver-79.0.3945.36-79to79 + 3706852\n16  chromedriver-79.0.3945.36-79to79    0x000000010d68dfc7 chromedriver-79.0.3945.36-79to79 + 3841991\n17  libsystem_pthread.dylib             0x00007fff5e3f12eb _pthread_body + 126\n18  libsystem_pthread.dylib             0x00007fff5e3f4249 _pthread_start + 66\n19  libsystem_pthread.dylib             0x00007fff5e3f040d thread_start + 13\n"}}
[2020-04-07 07:52:41.8475, 26912] [debug] [MJSONWP (76dfd7df)]     at JWProxy.proxy (/usr/local/deviceconnect/Appium/dc-appium-1.16.0-beta.1/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:222:13)
[2020-04-07 07:52:41.8475, 26912] [debug] [W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
```

**Comment by wswebcreation** [comment]
@Vardhan18 

This works with my local setup of Appium, did you also try that?

**Comment by Vardhan18** [comment]
@wswebcreation this is working fine with my local setup(Appium v1.15.1 and Android emulator) too but when i try with cloud appium server receiving the above error

**Comment by christian-bromann** [comment]
> when i try with cloud appium server receiving the above error

This looks like an issue in your cloud appium server. It doesn't properly parses the body: `{"{\"url\":\"https://github.com/\"}":""}`. I don't think WebdriverIO is doing something wrong here as it seems to send it correctly: `INFO webdriver: DATA { url: 'https://github.com/' }`

**Comment by Vardhan18** [comment]
@christian-bromann 
Thanks for response. shall i move this issue information to appium ?

**Comment by christian-bromann** [comment]
Sounds good to me.

**Comment by christian-bromann** [comment]
Thanks! Closing then.
