### ISSUE TITLE
When assertion failed from expect-webdriverio, Test status is broken instead of failed in @wdio/allure-reporter

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#5291]
*Environment (please complete the following information):**
 - **WebdriverIO version:** 6.0.16
 - **Mode:** WDIO
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Any
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^6.0.16",
    "@wdio/cucumber-framework": "^6.0.16",
    "@wdio/dot-reporter": "^6.0.16",
    "@wdio/local-runner": "^6.0.16",
    "@wdio/mocha-framework": "^6.0.16",
    "@wdio/selenium-standalone-service": "^6.0.16",
    "@wdio/spec-reporter": "^6.0.16",
    "@wdio/sync": "^6.0.16",
    "@wdio/allure-reporter": "^6.0.14",
    "@wdio/sync": "^6.0.16",
     "expect": "^25.3.0",
    "expect-webdriverio": "^1.0.0",

**Describe the bug**
When assertion failed with expect-webdriverio, Test status is BROKEN in allure-report because expect pacakge throw an Error and not an AssertionError.  Allure report should be improved to taken in account this new Error.
**To Reproduce**

```
Feature: Test
My description feature

Scenario: Test
  Given I fail test

```

```
Given(
  'I fail test', () => {
    expect(false).toBeEnabled();
  }
);
```

**Expected behavior**
Test status should be FAILED in allure xml report instead of BROKEN

**wdio.config file:**
```
const expect = require('expect');
require('expect-webdriverio').setOptions({ wait: 30000 });
 framework: 'cucumber',

  reporters: ['spec',
    ['allure', {
      outputDir: 'report/allure-results',
      disableWebdriverStepsReporting: false,
      disableWebdriverScreenshotsReporting: false,
      useCucumberStepReporter: true,
    }]],
  cucumberOpts: {
    // <boolean> show full backtrace for errors
    backtrace: false,
    // <string[]> module used for processing required features
    requireModule: ['@babel/register'],
    // <boolean< Treat ambiguous definitions as errors
    failAmbiguousDefinitions: true,
    // <boolean> invoke formatters without executing steps
    // dryRun: false,
    // <boolean> abort the run on first failure
    failFast: false,
    // <boolean> Enable this config to treat undefined definitions as
    // warnings
    ignoreUndefinedDefinitions: false,
    // <string[]> ("extension:module") require files with the given
    // EXTENSION after requiring MODULE (repeatable)
    name: [],
    // <boolean> hide step definition snippets for pending steps
    snippets: true,
    // <boolean> hide source uris
    source: true,
    // <string[]> (name) specify the profile to use
    profile: [],
    // <string[]> (file/dir) require files before executing features
    require: [
      './src/steps/given.js',
      './src/steps/then.js',
      './src/steps/when.js',
      './src/steps/after.js',
      // Or search a (sub)folder for JS files with a wildcard
      // works since version 1.1 of the wdio-cucumber-framework
      // './src/**/*.js',
    ],
    // <string> specify a custom snippet syntax
    snippetSyntax: undefined,
    // <boolean> fail if there are any undefined or pending steps
    strict: true,
    // <string> (expression) only execute the features or scenarios with
    // tags matching the expression, see
    // https://docs.cucumber.io/tag-expressions/
    tagExpression: 'not @Pending',
    // <boolean> add cucumber tags to feature or scenario name
    tagsInTitle: true,
    // <number> timeout for step definitions
    timeout: 99999999,
  },
```

**Log**
Content of testsuite xml file
```
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1587302774479' stop='1587304082630'>
    <name>Test</name>
    <title>Test</title>
    <test-cases>
        <test-case start='1587302774636' status='broken' stop='1587304081256'>
            <name>Test</name>
            <title>Test</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome'/>
            </parameters>
            <steps>
                <step start='1587302774645' status='broken' stop='1587304081255'>
                    <name>Given I fail test</name>
                    <title>Given I fail test</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <failure>
                <message>Expect  to be enabled
                
                Expected: "enabled"
                Received: "not enabled"</message>
                <stack-trace>Error: Expect  to be enabled
                
                Expected: "enabled"
                Received: "not enabled"
                    at World.&lt;anonymous> (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\src\steps\/given.js:43:19)
                    at World.executeSync (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\@wdio\sync\build\index.js:56:18)
                    at C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\@wdio\sync\build\index.js:82:70</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>
```

**Comment by lacell75** [comment]
i will do a PR coming soon
