### ISSUE TITLE
browser.getLogs() stopped working when upgrade to 6.x

### ISSUE THREAD

**Issue by mo** [webdriverio/webdriverio#5318]
I created a minimal example here:

1. check out: https://github.com/mo/e2e-get-logs-unknown-command.git
2. go back to 5.x version where test passes "git reset --hard 7a491e2" and run the test using "npm run test-chrome"
3. git pull so you get d794a6d where the testcase is upgraded to 6.x and the bug repro when you run "npm run test-chrome"

Note: chromedriver is pinned to 81.0.4044.69 on both commits (see wdio.conf.js)

The error I get when running "npm run test-chrome" on commit d794a6d is this:

```
[0-0] RUNNING in chrome - /tests/main.uitest.js
[0-0] 2020-04-24T13:35:31.276Z ERROR webdriver: Request failed with status 404 due to Error: unknown command: session/198b9a07f28dfb7dfc42befb0e57d02b/se/log
[0-0] Error in "main testsuite repro the bug"
Error: unknown command: session/198b9a07f28dfb7dfc42befb0e57d02b/se/log
[0-0] FAILED in chrome - /tests/main.uitest.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 81.0.4044.122 Linux #0-0] Spec: /home/molsson/dv/e2e-get-logs-unknown-command/tests/main.uitest.js
[chrome 81.0.4044.122 Linux #0-0] Running: chrome (v81.0.4044.122) on Linux
[chrome 81.0.4044.122 Linux #0-0] Session ID: 198b9a07f28dfb7dfc42befb0e57d02b
[chrome 81.0.4044.122 Linux #0-0]
[chrome 81.0.4044.122 Linux #0-0] main testsuite
[chrome 81.0.4044.122 Linux #0-0]    ✖ repro the bug
[chrome 81.0.4044.122 Linux #0-0]
[chrome 81.0.4044.122 Linux #0-0] 1 failing (108ms)
[chrome 81.0.4044.122 Linux #0-0]
[chrome 81.0.4044.122 Linux #0-0] 1) main testsuite repro the bug
[chrome 81.0.4044.122 Linux #0-0] Error: unknown command: session/198b9a07f28dfb7dfc42befb0e57d02b/se/log
[chrome 81.0.4044.122 Linux #0-0] Error: unknown command: session/198b9a07f28dfb7dfc42befb0e57d02b/se/log
[chrome 81.0.4044.122 Linux #0-0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[chrome 81.0.4044.122 Linux #0-0]     at UserContext.<anonymous> (/home/molsson/dv/e2e-get-logs-unknown-command/tests/main.uitest.js:6:15)

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:02 
```

**Comment by erwinheitzman** [comment]
works fine here with the latest chrome and chromedriver using:
```js
describe('a', () => {
    it('b', () => {
        browser.url('https://www.google.com');
        browser.execute(() => console.error('heya!'))
        console.log(browser.getLogs('browser'));
    })
})
```
logs the following:
```js
[0-0] [
  {
    level: 'SEVERE',
    message: 'console-api 2:46 "heya!"',
    source: 'console-api',
    timestamp: 1587736264362
  }
]
```

**Comment by mo** [comment]
@erwinheitzman hmm, were those browser.url + console.log calls the only changes you made and other than that you just ran "npm run test-chrome" from my example?

What chrome version are you using? I ran the test in chrome 81.0.4044.122

**Comment by christian-bromann** [comment]
Closing due to inactivity. Happy to re-open once a reproducible example is available.

**Comment by kevinmcdonnell** [comment]
@christian-bromann Im seeing the same. Looks like theres an additional `/se/` in the request path? is this expected?

```
Request failed with status 404 due to unknown command: session/2962a0a2d633dce979009bfaa83bb677/se/log
```

**Comment by kevinmcdonnell** [comment]
Okay i needed to update services, likely chromedriver issue

```
    services: [
        ['selenium-standalone', {
            logPath: 'logs',
            installArgs: {
                drivers: {
                    chrome: { version: '83.0.4103.39' }
                }
            },
            args: {
                drivers: {
                    chrome: { version: '83.0.4103.39' }
                }
            },
        }]
    ],```

**Comment by rsshilli** [comment]
If you are using a recent version of Chrome and find that you only get warning and error messages in your logs, but you want INFO as well, add the following into your `wdio.conf.js`:
```
exports.config = {
  capabilities: [{
    ...
    "goog:loggingPrefs": {   // <-- Add this
      browser: "ALL",
    },
  }],
};
```
