### ISSUE TITLE
devtools: Transpiled luancher.js is importing puppeteer-core/DeviceDescriptors incorrectly, crashing wdio cli

### ISSUE THREAD

**Issue by mikol-styra** [webdriverio/webdriverio#5367]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.8
 - **Mode:** standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.13.1
 - **NPM version:** 6.14.5
 - **Browser name and version:** Google Chrome 81.0.4044.138
 - **Platform name and version:** macOS 10.14.6
 - **Additional wdio packages used (if applicable):**  @wdio/cli @wdio/local-runner @wdio/mocha-framework @wdio/reporter @wdio/sync expect-webdriverio
 - **Additional packages:** puppeteer-core 3.0.3

**Config of WebdriverIO**

```js
{
  runner: 'local',
  path: '/',
  specs: [
    './test/**/*.test.js'
  ],
  exclude: [],
  maxInstances: 1,
  capabilities: [
    {
      browserName: 'chrome',
      'goog:chromeOptions': {
        args: [
          '--disable-gpu',
          '--headless',
          '--ignore-certificate-errors'
        ]
      }
    }
  ],
  logLevel: 'silent',
  bail: 0,
  baseUrl: 'https://webdriverio.styra.com',
  waitforTimeout: process.env.WAIT_FOR_TIMEOUT
    ? parseInt(process.env.WAIT_FOR_TIMEOUT, 10)
    : 30000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  services: [[Service]],
  framework: 'mocha',
  specFileRetries: 0,
  reporters: [[Reporter, {}]],
  mochaOpts: {
    ui: 'bdd',
    timeout: 30000
  },
  before: function () {
    require('expect-webdriverio')
    browser.url('')
  }
}
```

**Describe the bug**

The wdio cli crashes with “TypeError: Cannot convert undefined or null to object”.

```
(node:22119) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.<anonymous> (/.../node_modules/devtools/build/launcher.js:31:29)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/.../node_modules/devtools/build/index.js:28:40)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
(node:22119) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22119) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

Run wdio. For example: npx wdio --help

This issue is caused in node_modules/devtools/build/launcher.js:

```js
var _DeviceDescriptors = _interopRequireDefault(require("puppeteer-core/DeviceDescriptors"));

var _logger = _interopRequireDefault(require("@wdio/logger"));

var _finder = _interopRequireDefault(require("./finder"));

var _utils = require("./utils");

var _constants = require("./constants");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function ownKeys(object, enumerableOnly) { var keys = Object.keys(object); if (Object.getOwnPropertySymbols) { var symbols = Object.getOwnPropertySymbols(object); if (enumerableOnly) symbols = symbols.filter(function (sym) { return Object.getOwnPropertyDescriptor(object, sym).enumerable; }); keys.push.apply(keys, symbols); } return keys; }

function _objectSpread(target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i] != null ? arguments[i] : {}; if (i % 2) { ownKeys(Object(source), true).forEach(function (key) { _defineProperty(target, key, source[key]); }); } else if (Object.getOwnPropertyDescriptors) { Object.defineProperties(target, Object.getOwnPropertyDescriptors(source)); } else { ownKeys(Object(source)).forEach(function (key) { Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key)); }); } } return target; }

function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

const log = (0, _logger.default)('devtools');
const DEVICE_NAMES = Object.values(_DeviceDescriptors.default).map(device => device.name);
```

Specifically, the last line above is trying to reference `_DeviceDescriptors.default`, but `_DeviceDescriptors` doesn’t have a `default` property (despite the interop wrapper on the first line):

```js
_DeviceDescriptors = {
  devicesMap: {
    'Blackberry PlayBook': [Object],
    'Blackberry PlayBook landscape': [Object],
    'BlackBerry Z30': [Object],
    'BlackBerry Z30 landscape': [Object],
    'Galaxy Note 3': [Object],
    'Galaxy Note 3 landscape': [Object],
    'Galaxy Note II': [Object],
    'Galaxy Note II landscape': [Object],
    'Galaxy S III': [Object],
    'Galaxy S III landscape': [Object],
    'Galaxy S5': [Object],
    'Galaxy S5 landscape': [Object],
    iPad: [Object],
    'iPad landscape': [Object],
    'iPad Mini': [Object],
    'iPad Mini landscape': [Object],
    'iPad Pro': [Object],
    'iPad Pro landscape': [Object],
    'iPhone 4': [Object],
    'iPhone 4 landscape': [Object],
    'iPhone 5': [Object],
    'iPhone 5 landscape': [Object],
    'iPhone 6': [Object],
    'iPhone 6 landscape': [Object],
    'iPhone 6 Plus': [Object],
    'iPhone 6 Plus landscape': [Object],
    'iPhone 7': [Object],
    'iPhone 7 landscape': [Object],
    'iPhone 7 Plus': [Object],
    'iPhone 7 Plus landscape': [Object],
    'iPhone 8': [Object],
    'iPhone 8 landscape': [Object],
    'iPhone 8 Plus': [Object],
    'iPhone 8 Plus landscape': [Object],
    'iPhone SE': [Object],
    'iPhone SE landscape': [Object],
    'iPhone X': [Object],
    'iPhone X landscape': [Object],
    'iPhone XR': [Object],
    'iPhone XR landscape': [Object],
    'JioPhone 2': [Object],
    'JioPhone 2 landscape': [Object],
    'Kindle Fire HDX': [Object],
    'Kindle Fire HDX landscape': [Object],
    'LG Optimus L70': [Object],
    'LG Optimus L70 landscape': [Object],
    'Microsoft Lumia 550': [Object],
    'Microsoft Lumia 950': [Object],
    'Microsoft Lumia 950 landscape': [Object],
    'Nexus 10': [Object],
    'Nexus 10 landscape': [Object],
    'Nexus 4': [Object],
    'Nexus 4 landscape': [Object],
    'Nexus 5': [Object],
    'Nexus 5 landscape': [Object],
    'Nexus 5X': [Object],
    'Nexus 5X landscape': [Object],
    'Nexus 6': [Object],
    'Nexus 6 landscape': [Object],
    'Nexus 6P': [Object],
    'Nexus 6P landscape': [Object],
    'Nexus 7': [Object],
    'Nexus 7 landscape': [Object],
    'Nokia Lumia 520': [Object],
    'Nokia Lumia 520 landscape': [Object],
    'Nokia N9': [Object],
    'Nokia N9 landscape': [Object],
    'Pixel 2': [Object],
    'Pixel 2 landscape': [Object],
    'Pixel 2 XL': [Object],
    'Pixel 2 XL landscape': [Object]
  }
}
```

**Expected behavior**

Run wdio cli without crashing.

**Log**

N/A

**Additional context**

N/A

**Comment by mikol-styra** [comment]
**Workaround:** Lock the `puppeteer-core` version:

```
npm install --save-dev --save-exact puppeteer-core@3.0.0
```

**Comment by christian-bromann** [comment]
Puppeteers last release broke the way we imported the device descriptors. I patch for it is on its way: #5369
