### ISSUE TITLE
Update of puppeteer-core breaks the launcher

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#5368]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.8
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.14.4

**Describe the bug**
Puppeteer has moved away from Javascript and is now fully converted to Typescript.
This change broke some of the functionality in the launcher by throwing the following error: `TypeError: Cannot convert undefined or null to object`

**To Reproduce**
```
mkdir some-dir
cd some-dir
npm init -y
npm i @wdio/cli
npx wdio config
```

**Log**
```
(node:50622) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.<anonymous> (/Users/erwinheitzman/Documents/temp/ts-test/node_modules/devtools/build/launcher.js:31:29)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/erwinheitzman/Documents/temp/ts-test/node_modules/devtools/build/index.js:28:40)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
(node:50622) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:50622) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by christian-bromann** [comment]
Let's continue conversations in #5369
