### ISSUE TITLE
(node:36760) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by meruga92** [webdriverio/webdriverio#5370]
**Environment (please complete the following information):**
 - **WebdriverIO version:6.1.8** 
 - **Mode:Standalone mode**
 - **If WDIO Testrunner, running sync/async: sync** 
 - **Node.js version:12.16.1**
 - **NPM version:6.13.4**
 - **Browser name and version: appium(1.16.0) **
 - **Platform name and version: Mac **

package.json
```javascript
  "dependencies": {
    "@applitools/eyes-selenium": "^4.33.10",
    "@applitools/eyes-webdriverio": "^5.9.7",
    "appium": "1.16.0",
    "chai": "4.2.0",
    "cucumber": "^6.0.5",
    "currency.js": "^1.2.2",
    "faker": "4.1.0",
    "glob": "^7.1.4",
    "image-size": "^0.7.4",
    "jimp": "^0.6.4",
    "jsqr": "^1.2.0",
    "moment": "^2.24.0",
    "node-tesseract-ocr": "0.1.0",
    "node-vibrant": "^3.1.4",
    "otpauth": "^5.0.1",
    "proper-lockfile": "^4.1.1",
    "request-promise": "^4.2.5",
    "shelljs": "0.8.3",
    "xml-writer": "^1.7.0",
    "wdio-video-reporter": "^2.0.0"
  },
  "devDependencies": {
    "@wdio/allure-reporter": "^6.0.14",
    "@wdio/appium-service": "^6.0.12",
    "@wdio/cli": "^6.0.14",
    "@wdio/cucumber-framework": "^6.0.14",
    "@wdio/local-runner": "^6.0.14",
    "@wdio/spec-reporter": "^6.0.14",
    "@wdio/sync": "^6.0.14",
    "eslint": "^6.3.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-plugin-import": "^2.18.2"
  },
```

**Config of WebdriverIO**
```javascript
global.CONFIG_PATH = `${process.cwd()}/config`;
global.SUPPORT_PATH = `${process.cwd()}/test/support`;
global.faker = require('faker');
const { Eyes, StitchMode } = require('@applitools/eyes-webdriverio');

let appiumPort;
if (process.env.IOS === 'true') {
  // Generate random appium port between 4723 and 5723 for IOS
  appiumPort = Math.floor(Math.random() * (7723 - 4723 + 1)) + 4723;
} else {
  // Generate random appium port between 4723 and 5723 for local and ANDROID
  appiumPort = Math.floor(Math.random() * (9723 - 7725 + 1)) + 7725;
}

exports.config = {
  //
  // ====================
  // Runner Configuration
  // ====================
  //
  // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
  // on a remote machine).
  runner: 'local',
  //
  // ==================
  // Specify Test Files
  // ==================
  // Define which test specs should run. The pattern is relative to the directory
  // from which `wdio` was called. Notice that, if you are calling `wdio` from an
  // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
  // directory is where your package.json resides, so `wdio` will be called from there.
  //
  // // Patterns to exclude.
  // exclude: [
  //     // 'path/to/excluded/files'
  // ],
  specs: [
    './test/features/**/*.feature',
  ],
  //
  // ============
  // Capabilities
  // ============
  // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
  // time. Depending on the number of capabilities, WebdriverIO launches several test
  // sessions. Within your capabilities you can overwrite the spec and exclude options in
  // order to group specific specs to a specific capability.
  //
  // First, you can define how many instances should be started at the same time. Let's
  // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
  // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
  // files and you set maxInstances to 10, all spec files will get tested at the same time
  // and 30 processes will get spawned. The property handles how many capabilities
  // from the same test should run tests.
  //
  maxInstances: 1,
capabilities: [{
    platformVersion: '13.3',
    deviceName:'iPhone 11',
    app: appPath,
    platformName: 'iOS',
    wdaLocalPort: Math.floor(Math.random() * (8200 - 8100 + 1)) + 8100,
  }],
  //
  // If you have trouble getting all important capabilities together, check out the
  // Sauce Labs platform configurator - a great tool to configure your capabilities:
  // https://docs.saucelabs.com/reference/platforms-configurator
  //
  //
  // ===================
  // Test Configurations
  // ===================
  // Define all options that are relevant for the WebdriverIO instance here
  //
  // Level of logging verbosity: trace | debug | info | warn | error | silent
  logLevel: 'error',
  //
  // Set specific log levels per logger
  // loggers:
  // - webdriver, webdriverio
  // - @wdio/applitools-service, @wdio/browserstack-service,
  // @wdio/devtools-service, @wdio/sauce-service
  // - @wdio/mocha-framework, @wdio/jasmine-framework
  // - @wdio/local-runner, @wdio/lambda-runner
  // - @wdio/sumologic-reporter
  // - @wdio/cli, @wdio/config, @wdio/sync, @wdio/utils
  // Level of logging verbosity: trace | debug | info | warn | error | silent
  // logLevels: {
  //     webdriver: 'info',
  //     '@wdio/applitools-service': 'info'
  // },
  //
  // If you only want to run your tests until a specific amount of tests have failed use
  // bail (default is 0 - don't bail, run all tests).
  bail: 0,
  //
  // Set a base URL in order to shorten url command calls. If your `url` parameter starts
  // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
  // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
  // gets prepended directly.
  // baseUrl: 'http://localhost',
  //
  // Default timeout for all waitFor* commands.
  waitforTimeout: 10000,
  //
  // Default timeout in milliseconds for request
  // if browser driver or grid doesn't send response
  connectionRetryTimeout: 180000,
  //
  // Default request retries count
  connectionRetryCount: 3,
  //
  // Test runner services
  // Services take over a specific job you don't want to take care of. They enhance
  // your test setup with almost no effort. Unlike plugins, they don't add new
  // commands. Instead, they hook themselves up into the test process.
  services: [['appium', {
    logPath: './',
    args: {
      address: '127.0.0.1',
      port: parseInt(appiumPort),
    },
  }]],

  // Appium Service config
  // see details: https://webdriver.io/docs/appium-service.html
  port: parseInt(appiumPort),
  // Appium Service config
  // see details: https://webdriver.io/docs/appium-service.html
  //
  // Framework you want to run your specs with.
  // The following are supported: Mocha, Jasmine, and Cucumber
  // see also: https://webdriver.io/docs/frameworks.html
  //
  // Make sure you have the wdio adapter package for the specific framework installed
  // before running any tests.
  framework: 'cucumber',
  //
  // The number of times to retry the entire specfile when it fails as a whole
  // specFileRetries: 1,
  //
  // Whether or not retried specfiles should
  // be retried immediately or deferred to the end of the queue
  // specFileRetriesDeferred: false,
  //
  // Test reporter for stdout.
  // The only one supported by default is 'dot'
  // see also: https://webdriver.io/docs/dot-reporter.html
  reporters: ['spec', ['allure', {
    outputDir: 'allure-results',
    disableWebdriverStepsReporting: true,
    disableWebdriverScreenshotsReporting: true,
    useCucumberStepReporter: true,
  }],
  [video, {
    saveAllVideos: false, // If true, also saves videos for successful test cases
    videoSlowdownMultiplier: 6, // Higher to get slower videos,
    // lower for faster videos [Value 1-100]
  }],
  ],

  //
  // If you are using Cucumber you need to specify the location of your step definitions.
  cucumberOpts: {
    require: [
      './test/support/common/step_definitions/*.js',
      './test/support/common/pages/**/*.js',
      './test/support/common/api/**/*.js',
    ], // <string[]> (file/dir) require files before executing features
    backtrace: false, // <boolean> show full backtrace for errors
    requireModule: [], // <string[]> ("extension:module") require
    // files with the given EXTENSION after requiring MODULE (repeatable)
    dryRun: false, // <boolean> invoke formatters without executing steps
    failFast: false, // <boolean> abort the run on first failure
    format: ['pretty'], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
    colors: true, // <boolean> disable colors in formatter output
    snippets: true, // <boolean> hide step definition snippets for pending steps
    source: true, // <boolean> hide source uris
    profile: [], // <string[]> (name) specify the profile to use
    strict: false, // <boolean> fail if there are any undefined or pending steps
    tagExpression: '@automated', // <string> (expression) only
    // execute the features or scenarios with tags matching the expression
    timeout: 300000, // <number> timeout for step definitions
    ignoreUndefinedDefinitions: false, // <boolean> Enable this config
    // to treat undefined definitions as warnings.
  },

  //
  // =====
  // Hooks
  // =====
  // WebdriverIO provides several hooks
  // you can use to interfere with the test process in order to enhance
  // it and to build services around it. You can either apply a single function or an array of
  // methods to it.
  // If one of them returns with a promise, WebdriverIO will wait until that promise got
  // resolved to continue.
  /**
   * Gets executed once before all workers get launched.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   */
  // onPrepare: function (config, capabilities) {
  // },
  /**
   * Gets executed before a worker process is spawned and can be used to initialise specific service
   * for that worker as well as modify runtime environments in an async fashion.
   * @param  {String} cid      capability id (e.g 0-0)
   * @param  {[type]} caps
   * object containing capabilities for session that will be spawn in the worker
   * @param  {[type]} specs    specs to be run in the worker process
   * @param  {[type]} args
   * object that will be merged with the main configuration once worker is initialised
   * @param  {[type]} execArgv list of string arguments passed to the worker process
   */
  // onWorkerStart: function (cid, caps, specs, args, execArgv) {
  // },
  /**
   * Gets executed just before initialising the webdriver session and test framework. It allows you
   * to manipulate configurations depending on the capability or spec.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that are to be run
   */
  // beforeSession: function (config, capabilities, specs) {
  // },
  /**
   * Gets executed before test execution begins. At this point you can access to all global
   * variables like `browser`. It is the perfect place to define custom commands.
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that are to be run
   */
  // eslint-disable-next-line
  async before(capabilities, specs) {
    const chai = require('chai');
    // eslint-disable-next-line
    const mobileCommands = require(`${SUPPORT_PATH}/util/mobileCommands.js`);
    // eslint-disable-next-line
    const mobileSelectors = require(`${SUPPORT_PATH}/util/mobileSelectors.js`);
    global.expect = chai.expect;
    global.assert = chai.assert;
    global.should = chai.should();

    const eyes = new Eyes();
    eyes.setApiKey(process.env.APPLITOOLSKEY);
    eyes.setForceFullPageScreenshot(true);
    eyes.setHideScrollbars(true);
    eyes.setIgnoreCaret(true);
    eyes.setStitchMode(StitchMode.SCROLL);
    eyes.setBatch(`NM ${env.toUpperCase()} APP`, new Date().toISOString());
    browser.eyes = eyes;
  },
  /**
   * Runs before a WebdriverIO command gets executed.
   * @param {String} commandName hook command name
   * @param {Array} args arguments that command would receive
   */
  // beforeCommand: function (commandName, args) {
  // },
  /**
   * Runs before a Cucumber feature
   */
  // eslint-disable-next-line
  beforeFeature(uri, feature, scenarios) {
  },
  /**
   * Runs before a Cucumber scenario
   */
  // beforeScenario: function (uri, feature, scenario, sourceLocation) {
  // },
  /**
   * Runs before a Cucumber step
   */
  // beforeStep: function ({ uri, feature, step }, context) {
  // },
  /**
   * Runs after a Cucumber step
   */
  // afterStep: function ({ uri, feature, step },
  // context, { error, result, duration, passed, retries }) {
  // },
  /**
   * Runs after a Cucumber scenario
   */
  // eslint-disable-next-line
  async afterScenario(uri, feature, scenario, result, sourceLocation) {
  // Takes screenshot when test failed
    if (result.status === 'failed') {
      await browser.attachScreenshotToReport();
    }
    await browser.eyes.abortIfNotClosed();
  },
  /**
   * Runs after a Cucumber feature
   */
  // afterFeature: function (uri, feature, scenarios) {
  // },

  /**
   * Runs after a WebdriverIO command gets executed
   * @param {String} commandName hook command name
   * @param {Array} args arguments that command would receive
   * @param {Number} result 0 - command success, 1 - command error
   * @param {Object} error error object if any
   */
  // afterCommand: function (commandName, args, result, error) {
  // },
  /**
   * Gets executed after all tests are done. You still have access to all global variables from
   * the test.
   * @param {Number} result 0 - test pass, 1 - test fail
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that ran
   */
  // after: function (result, capabilities, specs) {
  // },
  /**
   * Gets executed right after terminating the webdriver session.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that ran
   */
  // afterSession: function (config, capabilities, specs) {
  // },
  /**
   * Gets executed after all workers got shut down and the process is about to exit. An error
   * thrown in the onComplete hook will result in the test run failing.
   * @param {Object} exitCode 0 - success, 1 - fail
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {<Object>} results object containing test results
   */
  // onComplete: function(exitCode, config, capabilities, results) {
  // },
  /**
   * Gets executed when a refresh happens.
   * @param {String} oldSessionId session ID of the old session
   * @param {String} newSessionId session ID of the new session
   */
  // onReload: function(oldSessionId, newSessionId) {
  // }
};

```

**Describe the bug**
I updated webdriverIO recently and when i try to run the test i got the following error
even if i try to run ```./node_modules/.bin/wdio``` i am getting following error

```
(node:36760) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.<anonymous> (/Users/mer2350/test-mobile-nmcx/node_modules/devtools/build/launcher.js:31:29)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/mer2350/test-mobile-nmcx/node_modules/devtools/build/index.js:28:40)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
(node:36760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by christian-bromann** [comment]
This was fixed by #5369, making a release now.
