### ISSUE TITLE
[0-0] (node:18488) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pageUrl' of undefined     at new Auditor

### ISSUE THREAD

**Issue by hisisirdas** [webdriverio/webdriverio#5382]
Please find the package setup details. which is the latest version of below packages:-
"dependencies": {
"@babel/cli": "^7.2.3",
"@babel/core": "^7.2.2",
"@babel/preset-env": "^7.3.1",
"@babel/register": "^7.0.0",
"@wdio/devtools-service": "^5.9.0",
"@wdio/local-runner": "^5.9.1",
"@wdio/mocha-framework": "^5.9.1",
"@wdio/spec-reporter": "^5.8.0",
"@wdio/sync": "^5.9.1",
"chai": "^4.1.2",
"chromedriver": "^83.0.0",
"clear-logs": "^1.0.0",
"mocha": "^7.1.1",
"wdio-chromedriver-service": "^5.0.1",
"webdriverio": "^5.23.0"
},
"devDependencies": {
"@wdio/cli": "^5.22.4",
"chakram": "^1.5.0"
}
Please find the url loops page
describe('Performance metrics', () => {
before(() => {
browser.enablePerformanceAudits()
})
for(var i =1 ; i <= 5; i++){
// it('page a', () => {
// browser.url('https://www.youtube.com')
// console.log(browser.getMetrics())
// })

// it('page b', () => {
//   browser.url('https://www.facebook.com/')
//   console.log(browser.getMetrics())
// })

it('Page metrics', () => {
  browser.url('https://twitter.com')
  console.log(browser.getMetrics())
})
}
after(() => {
browser.disablePerformanceAudits()
})
})

**Comment by hisisirdas** [comment]
I am trying to iterate inside loop and navigate to each url get the metrics and back to home page and do the same for all urls but getting pageUrl of undefined. below is my code..

it('Internal Boards of DRZ REDZONE ',  () => {   
       // navigate to a new URL
    browser.url('https://test-ms.azurewebsites.net/?token='+refreshtoken)
    const links =$$('(//div[contains(@class,"BoardsList_cardsList")]/div)');
    console.log(links.length)
    for (var i=1; i<links.length; i++) {
        console.log('inside loop..');
        internal = $('(//div[contains(@class,"BoardsList_cardsList")]/div)['+i+']');
        browser.execute("arguments[0].click();", internal);
        browser.url(browser.getUrl())
        console.log('GEt metrics', browser.getMetrics());
        browser.back();
    } 
      
     })

**Comment by christian-bromann** [comment]
It would be helpful if you could post the whole stack trace.

**Comment by hisisirdas** [comment]
Hi Christian, Please find the below logs..I am looping the urls to check metrics of each page. below is error.
Metrics are  {
  estimatedInputLatency: 16,
  timeToFirstByte: 570,
  domContentLoaded: 14312,
  firstVisualChange: 416,
  firstPaint: 8419,
  firstContentfulPaint: 9030,
  firstMeaningfulPaint: 17518,
  lastVisualChange: 7431,
  firstCPUIdle: 17518,
  firstInteractive: 17498,
  load: 14909,
  speedIndex: 486
}
[0-0] (node:10232) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pageUrl' of undefined
    at new Auditor (E:\sisir\code\develop-branch\node_modules\@wdio\devtools-service\build\auditor.js:57:26)
    at TraceGatherer.<anonymous> (E:\sisir\code\develop-branch\node_modules\@wdio\devtools-service\build\index.js:112:23)
    at Object.onceWrapper (events.js:417:26)
    at TraceGatherer.emit (events.js:322:22)
    at TraceGatherer.EventEmitter.emit (domain.js:482:12)
    at TraceGatherer.onFrameNavigated (E:\sisir\code\develop-branch\node_modules\@wdio\devtools-service\build\gatherer\trace.js:90:12)
    at CDPSession.emit (events.js:310:20)
    at CDPSession.EventEmitter.emit (domain.js:482:12)
    at CDPSession._onMessage (E:\sisir\code\develop-branch\node_modules\puppeteer-core\lib\Connection.js:200:12)
    at Connection._onMessage (E:\sisir\code\develop-branch\node_modules\puppeteer-core\lib\Connection.js:112:17)
[0-0] (node:10232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by christian-bromann** [comment]
It seems like no looping over multiple pages is causing some instability when capturing tracelogs which causes this error.

**Comment by hisisirdas** [comment]
I am using devtool-service to capturing the metrics of each URLs. but in some URL it gets the below error..   
[0-0] (node:10232) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pageUrl' of undefined
at new Auditor (branch\node_modules@wdio\devtools-service\build\auditor.js:57:26)
at TraceGatherer. (branch\node_modules@wdio\devtools-service\build\index.js:112:23)

**Comment by christian-bromann** [comment]
@hisisirdas you already mentioned that. Any help resolving this issue would be much appreciated.

**Comment by hisisirdas** [comment]
@christian-bromann It is working only when we are using browser.pause(20000). so my question is =>
Can we use the browser.pause method() as in the documentation it is mentioned not to use this as there are alternative methods are there.

**Comment by christian-bromann** [comment]
I think for this use case it might make sense. For tests you shouldn't use it because WebdriverIO provides explicit waits. This race condition seems to not be in WebdriverIO related and more a conjunction of WebdriverIO -> Chrome -> Ligthouse.

**Comment by hisisirdas** [comment]
When opening multiple URLs in one spec file to get metrics then this issue is occurring.

**Comment by christian-bromann** [comment]
@hisisirdas can you please update your WebdriverIO versions? As I mentioned the error seems to be a race condition or just plain inability to capture the performance of some of the pages. This could be technically an error in WebdriverIO but it seems to be also related to Lighthouse and they way we integrated it into WebdriverIO.

To set clear expectations: it's unlikely that someone from the core maintainer team will look into this as the problem seems very complex. I will keep it open for visibility but might close it eventually if no one can provide more details and information about what causes this. We would appreciate any contributions that can resolve this issue.

**Comment by hisisirdas** [comment]
> @hisisirdas can you please update your WebdriverIO versions? As I mentioned the error seems to be a race condition or just plain inability to capture the performance of some of the pages. This could be technically an error in WebdriverIO but it seems to be also related to Lighthouse and they way we integrated it into WebdriverIO.
> 
> To set clear expectations: it's unlikely that someone from the core maintainer team will look into this as the problem seems very complex. I will keep it open for visibility but might close it eventually if no one can provide more details and information about what causes this. We would appreciate any contributions that can resolve this issue.

We are using the latest versions of webdriverIO. Instead looping the URLs, We are dynamically generating the JS spec file for each url page and get the metrics. In that case it ends all sessions as well as the test and starts a fresh test in next Urls to get metrics. We tried all ways to make it  possible but no luck a you(@christian-bromann ) said this is a race conjunction between chrome driver and lighthouse then light house gives up on waiting.

**Comment by erwinheitzman** [comment]
@hisisirdas a good start is to provide a reproducible example that we can run, we cannot access that site and the loop is missing here for example so like Christian already said, it's unlikely that anyone is going to look into this without the proper details / information that we can look into.

**Comment by hisisirdas** [comment]
> @hisisirdas a good start is to provide a reproducible example that we can run, we cannot access that site and the loop is missing here for example so like Christian already said, it's unlikely that anyone is going to look into this without the proper details / information that we can look into.

Please find the package setup details. which is the latest version of below packages:-
  "dependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.3.1",
    "@babel/register": "^7.0.0",
    "@wdio/devtools-service": "^5.9.0",
    "@wdio/local-runner": "^5.9.1",
    "@wdio/mocha-framework": "^5.9.1",
    "@wdio/spec-reporter": "^5.8.0",
    "@wdio/sync": "^5.9.1",
    "chai": "^4.1.2",
    "chromedriver": "^83.0.0",
    "clear-logs": "^1.0.0",
    "mocha": "^7.1.1",
    "wdio-chromedriver-service": "^5.0.1",
    "webdriverio": "^5.23.0"
  },
  "devDependencies": {
    "@wdio/allure-reporter": "^6.0.14",
    "@wdio/cli": "^5.22.4",
    "chakram": "^1.5.0"
  }
Please find the url loops page 
describe('Performance metrics', () => {
    before(() => {
      browser.enablePerformanceAudits()
    })
  for(var i =1 ; i <= 5; i++){
    // it('page a', () => {
    //   browser.url('https://www.youtube.com')
    //   console.log(browser.getMetrics())
    // })
  
    // it('page b', () => {
    //   browser.url('https://www.facebook.com/')
    //   console.log(browser.getMetrics())
    // })
  
    it('Page metrics', () => {
      browser.url('https://twitter.com')
      console.log(browser.getMetrics())
    })
}
    after(() => {
      browser.disablePerformanceAudits()
    })
  })

Error Details - 
DevTools listening on ws://IPaddress:port/devtools/browser/8f56ed0e-df03-4c59-8d9b-f72ccd0d8577
[0-0] {
  estimatedInputLatency: 19,
  timeToFirstByte: 578,
  domContentLoaded: 4507,
  firstVisualChange: 1242,
  firstPaint: 1308,
  firstContentfulPaint: 1308,
  firstMeaningfulPaint: 4721,
  lastVisualChange: 9566,
  firstCPUIdle: 8792,
  firstInteractive: 11505,
  load: 9537,
  speedIndex: 8381
}
[0-0] (node:16420) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pageUrl' of undefined
    at new Auditor (D:\Performance metrics\node_modules\@wdio\devtools-service\build\auditor.js:57:26)
    at TraceGatherer.<anonymous> (D:\Performance metrics\node_modules\@wdio\devtools-service\build\index.js:112:23)
    at Object.onceWrapper (events.js:417:26)
    at TraceGatherer.emit (events.js:310:20)
    at TraceGatherer.EventEmitter.emit (domain.js:482:12)
    at TraceGatherer.onFrameNavigated (D:\Performance metrics\node_modules\@wdio\devtools-service\build\gatherer\trace.js:90:12)
    at CDPSession.emit (events.js:310:20)
    at CDPSession.EventEmitter.emit (domain.js:482:12)
    at CDPSession._onMessage (D:\Performance metrics\node_modules\puppeteer-core\lib\Connection.js:200:12)
    at Connection._onMessage (D:\Performance metrics\node_modules\puppeteer-core\lib\Connection.js:112:17)
[0-0] (node:16420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0-0] {
  estimatedInputLatency: 19,
  timeToFirstByte: 578,
  domContentLoaded: 4507,
  firstVisualChange: 1242,
  firstPaint: 1308,
  firstContentfulPaint: 1308,
  firstMeaningfulPaint: 4721,
  lastVisualChange: 9566,
  firstCPUIdle: 8792,
  firstInteractive: 11505,
  load: 9537,
  speedIndex: 8381
}
[0-0] {
  estimatedInputLatency: 19,
  timeToFirstByte: 578,
  domContentLoaded: 4507,
  firstVisualChange: 1242,
  firstPaint: 1308,
  firstContentfulPaint: 1308,
  firstMeaningfulPaint: 4721,
  lastVisualChange: 9566,
  firstCPUIdle: 8792,
  firstInteractive: 11505,
  load: 9537,
  speedIndex: 8381
}
[0-0] {
  estimatedInputLatency: 19,
  timeToFirstByte: 578,
  domContentLoaded: 4507,
  firstVisualChange: 1242,
  firstPaint: 1308,
  firstContentfulPaint: 1308,
  firstMeaningfulPaint: 4721,
  lastVisualChange: 9566,
  firstCPUIdle: 8792,
  firstInteractive: 11505,
  load: 9537,
  speedIndex: 8381
}

[0-0] {
  estimatedInputLatency: 19,
  timeToFirstByte: 578,
  domContentLoaded: 4507,
  firstVisualChange: 1242,
  firstPaint: 1308,
  firstContentfulPaint: 1308,
  firstMeaningfulPaint: 4721,
  lastVisualChange: 9566,
  firstCPUIdle: 8792,
  firstInteractive: 11505,
  load: 9537,
  speedIndex: 8381
}
[0-0] PASSED in chrome - D:\Performance metrics\tests\index.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome  windows #0-0] Spec: D:\Performance metrics\index.js
[chrome  windows #0-0] Running: chrome on windows
[chrome  windows #0-0] Session ID: da1fa157418712c3a71f9ad0ad050d68
[chrome  windows #0-0]
[chrome  windows #0-0] 
[chrome  windows #0-0] 5 passing (29.5s)
Spec Files:      1 passed, 1 total (100% completed) in 00:00:33

Let me know if you need more details. After setup please use any url inside loop and get metrics then it will through above error.

**Comment by syedasadulhaq** [comment]
Hey! I'm using the latest version of devtools-service ("@wdio/devtools-service": "6.4.0"). I'm getting the following console error (don't know the impact yet): 

UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_id' of null
    at TraceGatherer.onFrameLoadFail (<my_path>/node_modules/@wdio/devtools-service/build/gatherer/trace.js:135:41)
    at <my_path>/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (<my_path>/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:43)
    at Page.emit (<my_path>/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at <my_path>/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:167:106
    at <my_path>/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (<my_path>/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:43)
    at NetworkManager.emit (<my_path>/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at NetworkManager._onLoadingFailed (<my_path>/node_modules/puppeteer-core/lib/cjs/puppeteer/common/NetworkManager.js:262:14)
    at <my_path>/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (<my_path>/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:43)
    at CDPSession.emit (<my_path>/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onMessage (<my_path>/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:225:18)

**Comment by dprevost-LMI** [comment]
Potentially fixed by https://github.com/webdriverio/webdriverio/pull/5984, reopen if not. Thanks!
