### ISSUE TITLE
Update of puppeteer-core breaks the launcher II

### ISSUE THREAD

**Issue by dimkin-eu** [webdriverio/webdriverio#5396]
Looks like something is not fixed in https://github.com/webdriverio/webdriverio/issues/5368 https://github.com/webdriverio/webdriverio/pull/5369
```
    "@wdio/browserstack-service": "6.1.10",
    "@wdio/cli": "6.1.11",
    "@wdio/dot-reporter": "6.1.9",
    "@wdio/local-runner": "6.1.11",
    "@wdio/mocha-framework": "6.1.8",
    "@wdio/sync": "6.1.8”,
```
```
09:28:24 (node:5498) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
09:28:24     at Function.values (<anonymous>)
09:28:24     at Object.<anonymous> (/var/opt/jenkins-slave/workspace/(somesecretpath)/node_modules/devtools/build/launcher.js:31:29)
09:28:24     at Module._compile (internal/modules/cjs/loader.js:1158:30)
09:28:24     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
09:28:24     at Module.load (internal/modules/cjs/loader.js:1002:32)
09:28:24     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
09:28:24     at Module.require (internal/modules/cjs/loader.js:1044:19)
09:28:24     at require (internal/modules/cjs/helpers.js:77:18)
```

wdio downgrade to pre 6.1 version helps
```
    "@wdio/browserstack-service": "6.0.17",
    "@wdio/cli": "6.0.18",
    "@wdio/dot-reporter": "6.0.16",
    "@wdio/local-runner": "6.0.18",
    "@wdio/mocha-framework": "6.0.16",
    "@wdio/sync": "6.0.18",
```

As an important note - this works perfectly on the local machine ( macOS Catalina 10.15.4 (19E287) ), but fails on Jenkins ( Jenkins ver. 2.190.3 )
node and npm versions are the same
 npm  6.13.4
 node 12.16.1

workspace if wiped out after each build, if it makes sense 
Also, fail in that stage, doesn't fail the whole suite, but this looks the same as https://github.com/webdriverio/webdriverio/issues/5398

**Comment by erwinheitzman** [comment]
Important to note is that you do not have this issue when running it locally. This also means that any additional information about this would be very helpful since people have reported the fix to work.

**Comment by erwinheitzman** [comment]
The only explanation I can think of is that the Jenkins slave (the machine) has got the dependencies cached somewhere

**Comment by dimkin-eu** [comment]
workspace if wiped out after each build if it makes sense

**Comment by christian-bromann** [comment]
@dimkin-eu can you check out the Puppeteer version that is in your node_modules directory. Could be the NPM cache or package-lock preventing a version mismatch. Also a minimal reproducible example could be helpful.

**Comment by dimkin-eu** [comment]
@christian-bromann not sure if i did it in a right way , but fast one gives this
```
14:29:33 $ cat ./node_modules/puppeteer/package.json | grep version && cat ./node_modules/puppeteer-core/package.json | grep version
14:29:33   "version": "3.0.4",
14:29:33     "tsc": "tsc --version && tsc -p . && cp src/protocol.d.ts lib/",
14:29:33     "apply-next-version": "node utils/apply_next_version.js",
14:29:33     "test-types": "node utils/doclint/generate_types && tsc --version && tsc -p utils/doclint/generate_types/test/",
14:29:33   "version": "3.0.2",
14:29:33     "tsc": "tsc --version && tsc -p . && cp src/protocol.d.ts lib/ && cp src/externs.d.ts lib/",
14:29:33     "apply-next-version": "node utils/apply_next_version.js",
14:29:33     "test-types": "node utils/doclint/generate_types && tsc --version && tsc -p utils/doclint/generate_types/test/",
14:29:33 Done in 0.14s.
```

**Comment by christian-bromann** [comment]
@dimkin-eu can you please provide a minimal reproducible example?

**Comment by dimkin-eu** [comment]
@christian-bromann I will try, but can't promise :( I totally understand the need in this.
Maybe there is any other additional info, which could help?

**Comment by christian-bromann** [comment]
> Maybe there is any other additional info, which could help?

Not really. I pretty sure it is your environment because devtools tests are passing for me in CI and locally.

**Comment by christian-bromann** [comment]
Closing due to inactivity. Please update all your dependencies and try again. I am happy to re-open if someone can provide a reproducible example.

**Comment by dimkin-eu** [comment]
@christian-bromann JFYI - I've bumped versions one more time and issue disappeared. 
So it could be some transitive dependency. 
Probably I would try to pinpoint which dependency did that ( as there are too many in project :( )
