### ISSUE TITLE
Error 404 during mobile execution on BrowserStack

### ISSUE THREAD

**Issue by qvalero** [webdriverio/webdriverio#5433]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.13
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 13.12.0
 - **NPM version:** 6.14.4
 - **Platform name and version:** iOS and Android
 - **Additional wdio packages used (if applicable):** @wdio/browserstack-service 6.1.10

**Describe the bug**
Each time I run my mobile tests on CircleCi using browserstack service, I have this issue:

```
[0-7] 2020-05-26T11:48:40.488Z INFO before session: Using app capability "bs://e43529d46f51926ff4e3c1097a655fd348a106c9"
[0-7] 2020-05-26T11:49:06.186Z ERROR @wdio/sync: HTTPError: Response code 404 (Not Found)
    at onResponse (/home/circleci/project/node_modules/@wdio/browserstack-service/node_modules/got/dist/source/as-promise/index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[0-7] (node:236) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at onResponse (/home/circleci/project/node_modules/@wdio/browserstack-service/node_modules/got/dist/source/as-promise/index.js:124:28)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[0-7] (node:236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0-7] 2020-05-26T11:50:27.948Z ERROR @wdio/sync: HTTPError: Response code 404 (Not Found)
    at onResponse (/home/circleci/project/node_modules/@wdio/browserstack-service/node_modules/got/dist/source/as-promise/index.js:124:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```
My capabilities are like this: 

```
        {
            maxInstances: 1,
            platformName: 'Android',
            os: 'android',
            device: 'Google Pixel 3',
            deviceName: 'Google Pixel 3',
            'os_version': '9.0',
            'appium:automationName': 'UIAutomator2',
            'appium:noReset': true,
            'browserstack.appium_version' : '1.17.1',
            excludeDriverLogs: [ '*' ],
            app: path/to/app,
            disableAnimations: true
        }
```

**Expected behavior**
No error during execution

**Comment by christian-bromann** [comment]
Can you provide the WebdriverIO logs?

**Comment by qvalero** [comment]
Is it what you need? 

[logs.txt](https://github.com/webdriverio/webdriverio/files/4682457/logs.txt)

**Comment by christian-bromann** [comment]
No, these are the Appium logs. I need the WebdriverIO logs to understand which command has caused this error.

**Comment by qvalero** [comment]
Ok I can see errors on those ones:
[logs.txt](https://github.com/webdriverio/webdriverio/files/4682787/logs.txt)

**Comment by christian-bromann** [comment]
@qvalero I am not sure what these logs and errors are. Maybe reach out to the BS support team. I don't see really how I can support you here :-/

**Comment by qvalero** [comment]
Ok I will contact them and keep you updated if I can have an answer !
Thanks for looking at it!
