### ISSUE TITLE
After BrowserStackLocal runner app update wdio fails to run local BrowserStack server

### ISSUE THREAD

**Issue by dimkin-eu** [webdriverio/webdriverio#5455]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1
 - **Mode:** [ WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [ sync ]
 - **Node.js version:** [v12.16.1]
 - **NPM version:** [6.14.5]
 - **Browser name and version:** [Chrome 83]
 - **Platform name and version:** [macOS Catalina 10.15.5]
 - **Additional wdio packages used (if applicable):** 
```
    "@wdio/allure-reporter": "6.1.14",
    "@wdio/browserstack-service": "6.1.15",
    "@wdio/cli": "6.1.15",
    "@wdio/dot-reporter": "6.1.14",
    "@wdio/local-runner": "6.1.14",
    "@wdio/mocha-framework": "6.1.14",
    "@wdio/spec-reporter": "6.1.14",
    "@wdio/sync": "6.1.14",
```

**Config of WebdriverIO**
common things, apart this
```
    user: process.env.BROWSERSTACK_USERNAME,
    key: process.env.BROWSERSTACK_ACCESS_KEY,
    capabilities: [
        {
            "bstack:options": {
                "os": "Windows",
                "osVersion": "10",
                "resolution": "1920x1080",
                "networkLogs": "true",
                "video": "false",
                "seleniumVersion": "3.141.59"
            },
            "browserName": "Chrome",
            "goog:chromeOptions": {
                excludeSwitches: ["enable-automation", "load-extension"]
            }
        }
    ],

    services: [["browserstack", { browserstackLocal: true }]],

    onPrepare(config, capabilities) {
        bsLocal = new browserstack.Local();

        return new Promise(function (resolve) {
            bsLocal.start({ "key": process.env.BROWSERSTACK_ACCESS_KEY }, function (error) {
                if (error) {
                    console.log(error);
                } else {
                    resolve();
                }
            });
        });
    },
```

**Describe the bug**
BrowserStack dropped old app, and the new app creates problems for running

**To Reproduce**
1. install new local testing app https://www.browserstack.com/local-testing/live - this need for manual testing via browser
2. try to run wdio test using BrowserStack

**Expected behavior**
test runs

**Log**
```
LocalError: Either another browserstack local client is running on your machine or some server is listening on port 45690
    at /Users/.../node_modules/browserstack-local/lib/Local.js:65:20
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  name: 'LocalError',
  message: 'Either another browserstack local client is running on your machine or some server is listening on port 45690',
  extra: undefined
}
```

**For a workaround** is not enough to uninstall the app or just kill running processes - you need to kill both ( app is pretty smart :) )

```
 % ps -ax | grep BrowserStackLocal
31261 ??         0:00.01 bash /Applications/BrowserStackLocal.app/Contents/Resources/public/start_binary.sh
31266 ??         0:00.63 BrowserStackLocal --app --app-version 2.0   
31268 ??         0:00.71 BrowserStackLocal --app --app-version 2.0   
```

**Comment by christian-bromann** [comment]
Closing as it seems that this should be handled by [`browserstack-local`](https://github.com/browserstack/browserstack-local-nodejs). Please raise an issue there. The BS service should only call `start` and `stop` and should not deal with pending processes.

**Comment by dimkin-eu** [comment]
https://github.com/browserstack/browserstack-local-nodejs/issues/105
