### ISSUE TITLE
Click fails with 'element not found' when loading a new page

### ISSUE THREAD

**Issue by romovs** [webdriverio/webdriverio#5456]
**Environment:**
 - **WebdriverIO version:** 6.1.15
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.17.0
 - **NPM version:** 6.13.7
 - **Browser name and version:** Chrome 83
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** 
    "@wdio/cli": "^6.1.15",
    "@wdio/local-runner": "^6.1.14",
    "@wdio/mocha-framework": "^6.1.14",
    "@wdio/spec-reporter": "^6.1.14",
    "@wdio/static-server-service": "^6.1.14",
    "@wdio/sync": "^6.1.14",
    "wdio-chromedriver-service": "^6.0.3"

**Describe the bug**
When `click` command triggers loading of a new page (e.g. clicking an `a` element) and the `load` event is delayed due to one of the external resources not loading (e.g. a slowly loading <script>) then click will eventually fail with `no such element: Unable to locate element`.

This behavior is rather unexpected, since the page does actually loads and the element is found initially.

**To Reproduce**

1. Clone the sample project from here https://github.com/oxygenhq/wdio-page-loading-click
2. `npm install -g deelay && deelay` deelay is used to simulate resource loading delay. It requires local port 4567 to be available.
4. `npx wdio wdio.conf.js` to execute the project

**Log**
```
Execution of 1 spec files started at 2020-06-02T18:28:41.190Z

2020-06-02T18:28:41.194Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
2020-06-02T18:28:41.209Z DEBUG @wdio/utils:initialiseServices: initialise service "static-server" as NPM package
2020-06-02T18:28:41.303Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-06-02T18:28:41.314Z INFO @wdio/static-server-service: Mounting folder `C:\Users\rom\projects\webdriverio-test\html` at `/html`
2020-06-02T18:28:41.321Z INFO @wdio/static-server-service: Static server running at http://localhost:4569
Starting ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2020-06-02T18:28:41.830Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-06-02T18:28:41.838Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2020-06-02T18:28:42.309Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-06-02T18:28:42.318Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-06-02T18:28:42.321Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in chrome - C:\Users\rom\projects\webdriverio-test\test.js
[0-0] 2020-06-02T18:28:42.466Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
[0-0] 2020-06-02T18:28:42.481Z DEBUG @wdio/utils:initialiseServices: initialise service "static-server" as NPM package
[0-0] 2020-06-02T18:28:42.581Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-06-02T18:28:42.583Z INFO webdriverio: Initiate new session using the webdriver protocol
2020-06-02T18:28:42.585Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2020-06-02T18:28:42.585Z INFO webdriver: DATA { capabilities:
   { alwaysMatch: { browserName: 'chrome' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'chrome' } }
[0-0] (node:9148) DeprecationWarning: Got: "options.rejectUnauthorized" is now deprecated, please use "options.https.rejectUnauthorized"

DevTools listening on ws://127.0.0.1:51555/devtools/browser/8f1ea33e-d97b-4d05-b5e7-f9609913c9b9
[12000:13984:0602/212843.411:ERROR:device_event_log_impl.cc(208)] [21:28:43.479] Bluetooth: bluetooth_adapter_winrt.cc:1060 Getting Default Adapter failed.
[0-0] 2020-06-02T18:28:44.555Z INFO webdriver: COMMAND navigateTo("http://localhost:4569/html/test.html")
[0-0] 2020-06-02T18:28:44.556Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/url
[0-0] 2020-06-02T18:28:44.560Z INFO webdriver: DATA { url: 'http://localhost:4569/html/test.html' }
[0-0] 2020-06-02T18:28:44.780Z INFO webdriver: COMMAND findElement("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:28:44.780Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/element
2020-06-02T18:28:44.780Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:28:44.807Z INFO webdriver: RESULT { 'element-6066-11e4-a52e-4f735466cecf': '6344e068-993c-4385-bbec-f4a733686447' }
[0-0] 2020-06-02T18:28:44.812Z INFO webdriver: COMMAND elementClick("6344e068-993c-4385-bbec-f4a733686447")
[0-0] 2020-06-02T18:28:44.812Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/element/6344e068-993c-4385-bbec-f4a733686447/click
[0-0] 2020-06-02T18:30:42.941Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2020-06-02T18:30:42.942Z INFO webdriver: Retrying 1/3
2020-06-02T18:30:42.942Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/element/6344e068-993c-4385-bbec-f4a733686447/click
[0-0] 2020-06-02T18:30:43.049Z DEBUG webdriver: request failed due to response error: stale element reference
[0-0] 2020-06-02T18:30:43.049Z WARN webdriver: Request encountered a stale element - terminating request
[0-0] 2020-06-02T18:30:43.050Z INFO webdriver: COMMAND findElement("xpath", "<Screenshot[base64]>")
2020-06-02T18:30:43.050Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/element
2020-06-02T18:30:43.050Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:43.067Z INFO webdriver: RESULT { error: 'no such element',
  message:
   'no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/a"}\n  (Session info: chrome=83.0.4103.61)',
  stacktrace:
   'Backtrace:\n\tOrdinal0 [0x015F9563+2725219]\n\tOrdinal0 [0x014F8551+1672529]\n\tOrdinal0 [0x013E0359+525145]\n\tOrdinal0 [0x01379755+104277]\n\tOrdinal0 [0x013953C0+218048]\n\tOrdinal0 [0x0138AAD0+174800]\n\tOrdinal0 [0x01393D7C+212348]\n\tOrdinal0 [0x0138A94B+174411]\n\tOrdinal0 [0x01372528+75048]\n\tOrdinal0 [0x013735A0+79264]\n\tOrdinal0 [0x01373539+79161]\n\tOrdinal0 [0x0150D607+1758727]\n\tGetHandleVerifier [0x01716546+1050150]\n\tGetHandleVerifier [0x01716291+1049457]\n\tGetHandleVerifier [0x017210D7+1094071]\n\tGetHandleVerifier [0x01716B46+1051686]\n\tOrdinal0 [0x01505B06+1727238]\n\tOrdinal0 [0x0150EB7B+1764219]\n\tOrdinal0 [0x0150ECE3+1764579]\n\tOrdinal0 [0x01524C05+1854469]\n\tBaseThreadInitThunk [0x74F40419+25]\n\tRtlGetAppContainerNamedObjectPath [0x778D66DD+237]\n\tRtlGetAppContainerNamedObjectPath [0x778D66AD+189]\n' }
2020-06-02T18:30:43.068Z DEBUG webdriverio: command elementClick was called on an element ("/html/body/a") that wasn't found, waiting for it...
2020-06-02T18:30:43.070Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
2020-06-02T18:30:43.070Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:43.070Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:43.089Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:43.571Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:43.571Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:43.572Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:43.590Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:44.069Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:44.070Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:44.070Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:44.084Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:44.569Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:44.570Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:44.570Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:44.581Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:45.069Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:45.070Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:45.071Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:45.088Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:45.570Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:45.571Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:45.571Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:45.587Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:46.074Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:46.075Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:46.075Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:46.103Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:46.569Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:46.570Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:46.570Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:46.584Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:47.079Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:47.080Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:47.081Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:47.106Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:47.569Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:47.570Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:47.571Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:47.600Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:48.070Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:48.070Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:48.071Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:48.079Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:48.570Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:48.571Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:48.571Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:48.602Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:49.069Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:49.070Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:49.070Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:49.081Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:49.569Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:49.569Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:49.569Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:49.581Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:50.070Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:50.070Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:50.070Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:50.081Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:50.570Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:50.570Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:50.570Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:50.582Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:51.070Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:51.070Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:51.070Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:51.081Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:51.570Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:51.570Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:51.570Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:51.581Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:52.069Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:52.070Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:52.070Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:52.084Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:52.570Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:52.571Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:52.571Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] 2020-06-02T18:30:52.595Z INFO webdriver: RESULT []
[0-0] 2020-06-02T18:30:53.070Z INFO webdriver: COMMAND findElements("xpath", "<Screenshot[base64]>")
[0-0] 2020-06-02T18:30:53.070Z INFO webdriver: [POST] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e/elements
2020-06-02T18:30:53.070Z INFO webdriver: DATA { using: 'xpath', value: '/html/body/a' }
[0-0] Error in "click issue repro example should load correctly"
Can't call elementClick on element with selector "/html/body/a" because element wasn't found
[0-0] 2020-06-02T18:30:53.078Z INFO webdriver: COMMAND deleteSession()
[0-0] 2020-06-02T18:30:53.079Z INFO webdriver: [DELETE] http://localhost:9515/session/ba80a2c9d202c2b8b7637a5b3e4c357e
[0-0] 2020-06-02T18:30:53.089Z INFO webdriver: RESULT []
2020-06-02T18:30:53.301Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - C:\Users\rom\projects\webdriverio-test\test.js
2020-06-02T18:30:53.306Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 83.0.4103.61 windows #0-0] Spec: C:\Users\rom\projects\webdriverio-test\test.js
[chrome 83.0.4103.61 windows #0-0] Running: chrome (v83.0.4103.61) on windows
[chrome 83.0.4103.61 windows #0-0] Session ID: ba80a2c9d202c2b8b7637a5b3e4c357e
[chrome 83.0.4103.61 windows #0-0]
[chrome 83.0.4103.61 windows #0-0] click issue repro example
[chrome 83.0.4103.61 windows #0-0]    ✖ should load correctly
[chrome 83.0.4103.61 windows #0-0]
[chrome 83.0.4103.61 windows #0-0] 1 failing (2m 8.7s)
[chrome 83.0.4103.61 windows #0-0]
[chrome 83.0.4103.61 windows #0-0] 1) click issue repro example should load correctly
[chrome 83.0.4103.61 windows #0-0] Can't call elementClick on element with selector "/html/body/a" because element wasn't found
[chrome 83.0.4103.61 windows #0-0] Error: Can't call elementClick on element with selector "/html/body/a" because element wasn't found
[chrome 83.0.4103.61 windows #0-0]     at implicitWait (C:\Users\rom\projects\webdriverio-test\node_modules\webdriverio\build\utils\implicitWait.js:22:13)
[chrome 83.0.4103.61 windows #0-0]     at Element.runCommandWithHooks (C:\Users\rom\projects\webdriverio-test\node_modules\@wdio\sync\build\wrapCommand.js:82:22)
[chrome 83.0.4103.61 windows #0-0]     at Element.wrapCommandFn (C:\Users\rom\projects\webdriverio-test\node_modules\@wdio\sync\build\wrapCommand.js:59:40)
[chrome 83.0.4103.61 windows #0-0]     at Element.elementErrorHandlerCallback (C:\Users\rom\projects\webdriverio-test\node_modules\webdriverio\build\middlewares.js:40:8)
[chrome 83.0.4103.61 windows #0-0]     at Context.it (C:\Users\rom\projects\webdriverio-test\test.js:4:27)
[chrome 83.0.4103.61 windows #0-0]     at Context.executeSync (C:\Users\rom\projects\webdriverio-test\node_modules\@wdio\sync\build\index.js:56:18)
[chrome 83.0.4103.61 windows #0-0]     at C:\Users\rom\projects\webdriverio-test\node_modules\@wdio\sync\build\index.js:82:70


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:02:12

2020-06-02T18:30:53.317Z INFO @wdio/local-runner: Shutting down spawned worker
2020-06-02T18:30:53.571Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-06-02T18:30:53.574Z INFO @wdio/local-runner: shutting down
```

**Comment by christian-bromann** [comment]
Thanks for filing the issue and the reproducible example. Any help on this matter would be highly appreciated. If someone wants to look into this should have a look into the [WebdriverIO middleware](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/middlewares.js#L11-L44) where element refetching is handled.

**Comment by Ravi-Kishore-M** [comment]
`If the click causes a new page to load, the Click() method will attempt to block until the page has loaded.` [refer this](https://www.selenium.dev/selenium/docs/api/dotnet/html/M_OpenQA_Selenium_IWebElement_Click.htm)
Since it's taking time to get response from Click command , we're getting `ETIMEDOUT` response code and web driver will retry to send a click command to server but we get an error `no such element: Unable to locate element` since the second page has already loaded.
Set capability `pageLoadStrategy` to `none` to make it work in your case.

**Comment by erwinheitzman** [comment]
@christian-bromann I'd like to update the middleware to retry on any error, what do you think about that? It would for example also fix any issues where elements might not be clickable due to an animation, it not being interactible (yet), etc.

**Comment by christian-bromann** [comment]
I am not sure if we should retry on every error given that e.g. an element not found is also seen as an error and would retry it which is not desired as we want to allow lazy loading.

**Comment by erwinheitzman** [comment]
@christian-bromann did you verify this is not working? for me this is working with the latest version

**Comment by Ravi-Kishore-M** [comment]
@erwinheitzman have you started `deelay` service before running the test ?

**Comment by erwinheitzman** [comment]
@Ravi-Kishore-M I removed the comment since I apparently it wasn't running indeed. pretty fun tool and easy to use but is it possible to delay it only a little since I don't want to wait 2 minutes to find out if it worked or not :)

**Comment by Ravi-Kishore-M** [comment]
@erwinheitzman  Yes you can update the delay time [here](https://github.com/oxygenhq/wdio-page-loading-click/blob/989a1bd9829fbcd68844c135277ab1d976333ff1/html/2.html#L8), Currently it is 150000milliseconds (2.5 minutes) 
I guess there is no bug here, this is the expected behaviour. click command is throwing an error since the redirected page is taking more time to load.

**Comment by erwinheitzman** [comment]
@Ravi-Kishore-M if you change the timeout to 15 seconds and change the assertion to:
```js
expect($('#verify')).toHaveText('ok');
```
the test passes as expected, would you say there's still something we should look into?

**Comment by erwinheitzman** [comment]
@Ravi-Kishore-M after some more trail and error it's actually the connectionRetryTimeout timing out! if you would increase that number (not the retry count) it will actually pass, is it this that caused the particular error :)

**Comment by Ravi-Kishore-M** [comment]
it's throwing `connectionRetryTimeout` since the redirected page is taking time to load. we can ignore this bye setting the capability `pageLoadStrategy` to `none`.

**Comment by christian-bromann** [comment]
I revisited this issue and couldn't find any problem. The test was wrong and should be this:

```js
describe('click issue repro example', () => {
    it('should load correctly', () => {
        browser.url('http://localhost:4569/html/test.html')
        $('/html/body/a').click();
        expect($('#verify')).toHaveText('ok');
    })
})
```
then it passes.
