### ISSUE TITLE
Bug in @wdio/cucumber-framework with dataTable single row and DocString ERROR @wdio/runner: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by ccsuperstar** [webdriverio/webdriverio#5484]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.17
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v13.13.0
 - **NPM version:** 6.14.4
 - **Browser name and version:** Chrome 83
 - **Platform name and version:** OSX 10.15.3
 - **Additional wdio packages used (if applicable):** @wdio/allure-reporter, @wdio/browserstack-service, @wdio/cli, @wdio/cucumber-framework, @wdio/devtools-service, @wdio/junit-reporter, @wdio/local-runner, @wdio/logger, @wdio/mocha-framework, @wdio/spec-reporter, @wdio/sync

**Config of WebdriverIO**
```
exports.config = {
  runner: 'local',
  specs: [
       'src/features/**/*.feature',
  ],
  hostname: 'localhost',
  port: 4444,
  path: '/',
  services: [ 'intercept', 'devtools', 'chromedriver' ],  
  framework: 'cucumber',

...
```

**Describe the bug**
Following the upgrade of the @wdio/cucumber-framework package to version 6.1.17, and the fix "Fix data table variable values in Cucumber scenario outlines", in a scenario with a dataTable having only one column and a DocString, I have the following error:
```
ERROR @wdio/runner: TypeError: Cannot read property 'forEach' of undefined
    at /Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/@wdio/cucumber-framework/build/utils.js:226:27
    at Array.forEach (<anonymous>)
    at enhanceStepWithPickleData (/Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/@wdio/cucumber-framework/build/utils.js:225:28)
    at /Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/@wdio/cucumber-framework/build/utils.js:202:14
    at Array.map (<anonymous>)
    at getTestCaseSteps (/Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/@wdio/cucumber-framework/build/utils.js:190:45)
    at CucumberEventListener.onTestCaseStarted (/Users/carolinebuzenet/Documents/Projects/e2e_jt_tests/node_modules/@wdio/cucumber-framework/build/cucumberEventListener.js:56:53)
    at EventEmitter.emit (events.js:315:20)
    at EventEmitter.emit (domain.js:485:12)
    at TestCaseRunner.emit (/Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/cucumber/lib/runtime/test_case_runner.js:92:27)
    at TestCaseRunner.run (/Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/cucumber/lib/runtime/test_case_runner.js:210:12)
    at Runtime.runTestCase (/Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/cucumber/lib/runtime/index.js:76:49)
    at tryCatcher (/Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/Users/ccsuperstar/Documents/Projects/e2e_jt_tests/node_modules/bluebird/js/release/util.js:16:23)
[0-0]  Error:  Cannot read property 'forEach' of undefined
```
Looks like the source is this line: https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-cucumber-framework/src/utils.js#L226

To Reproduce
**To Reproduce**
For example
```
When the user publishes a "message"
    | message                                     |
    | Hello! This is my first message |
Then the user sees the message
When the user searches for the message with:
    """
    first message
    """
Then the user sees the message
```
[Include code or an example repository that can easily be set up]

**Expected behavior**
There shouldn't be this error thrown with DocString or DataTable with a single row

> Please use the correct markdown

**Comment by mgrybyk** [comment]
@ccsuperstar can you please provide with the minimal steps to reproduce?
Feature file along with step definition(s)

**Comment by mgrybyk** [comment]
The PR fixes issue with DocString however I'm not able to reproduce the issue "DataTable with a single row"
