### ISSUE TITLE
TypeError: Expected the `options.agent` properties to be `http`, `https` or `http2`, got `options`

### ISSUE THREAD

**Issue by Saikrishna99** [webdriverio/webdriverio#5491]
**Environment:**
 - **WebdriverIO version:** 6.1.17
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.18.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome: latest
 - **Platform name and version:** Mac OS 10.15
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/sauce-service, @wdio/mocha-framework, @wdio/local-runner, @wdio/sync

**Config of WebdriverIO**
Sauce labs run

**Describe the bug**
Upgraded from v5 to v6 latest. With an internal proxy under corporate net in the config file seeing the below error.

2020-06-15T03:32:04.663Z ERROR @wdio/utils:initialiseServices: TypeError: Expected the `options.agent` properties to be `http`, `https` or `http2`, got `options`
    at Function.normalizeArguments (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/got/dist/source/core/index.js:561:27)

**To Reproduce**
- Install wdio as its mentioned at https://webdriver.io/docs/gettingstarted.html
- Install @wdio/sauce-service
- Provide a proxy in the wdio.conf.js along with sauce labs credentials

**Expected behavior**
No errors

**Log**
Execution of 1 spec files started at 2020-06-15T03:32:04.592Z

2020-06-15T03:32:04.663Z ERROR @wdio/utils:initialiseServices: TypeError: Expected the `options.agent` properties to be `http`, `https` or `http2`, got `options`
    at Function.normalizeArguments (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/got/dist/source/core/index.js:561:27)
    at Function.normalizeArguments (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/got/dist/source/as-promise/core.js:34:31)
    at mergeOptions (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/got/dist/source/as-promise/core.js:108:47)
    at Function.got.extend.instancesOrOptions [as extend] (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/got/dist/source/create.js:127:22)
    at new SauceLabs (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/saucelabs/build/index.js:46:32)
    at new SauceLauncher (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/@wdio/sauce-service/build/launcher.js:28:16)
    at initialiseLauncherService (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/@wdio/utils/build/initialiseServices.js:61:31)
    at Launcher.run (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/@wdio/cli/build/launcher.js:73:48)
    at launch (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/@wdio/cli/build/commands/run.js:138:19)
    at handler (/Users/s0g04rg/Documents/SourceCode/star/_mine/wdio/node_modules/@wdio/cli/build/commands/run.js:171:12)

**Additional context**
As this error pops up, @wdio/saucelabs doesn't update the test name (sauce.context step/script)
`(COMMAND executeScript("sauce:context=webdriver.io page - should have the right title", <object>))`

**Comment by christian-bromann** [comment]
Moving issue to https://github.com/saucelabs/node-saucelabs/issues/87
