### ISSUE TITLE
Unable to run test using Firefox with Jasmine V6.1.17 and other lower version of 6 series

### ISSUE THREAD

**Issue by ayyamuthutechnical** [webdriverio/webdriverio#5501]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 6.1.17]
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 12.16.3]
 - **NPM version:** [e.g. 6.14.4]
 - **Browser name and version:** [e.g.Firefox 77.0.1]
 - **Platform name and version:** [e.g. MacOS Mojave V10.14.6]
 - **Additional wdio packages used (if applicable):** [
"@wdio/jasmine-framework": "^5.23.0",
    "@wdio/local-runner": "^5.3.5",
    "@wdio/selenium-standalone-service": "^5.2.2",
    "@wdio/spec-reporter": "^6.1.14",
    "@wdio/sync": "^6.1.14",
    "chai": "^4.2.0",
    "cross-env": "^7.0.2",
    "dotenv": "^8.2.0",
    "eslint": "^6.8.0",
    "grunt": "^1.0.3",
    "grunt-cli": "^1.3.2",
    "grunt-jasmine": "^0.1.0",
    "grunt-webdriver": "^3.0.0",
    "rimraf": "^3.0.2",
    "ts-node": "^8.6.2",
    "typescript": "^3.8.3",
    "wdio-chromedriver-service": "^6.0.3",
    "webdriverio": "^5.3.5"]

**Config of WebdriverIO**
  'maxInstances': 1,
  'browserName': 'firefox',
  'moz:firefoxOptions': {
    args: [
    ]
  },

**Describe the bug**
Firefox browser is not launching or running the tests when we are using Jasmine V6.1.17 and other lower version.

**To Reproduce**
1. Write sample test using Jasmine V6.1.17
2. Run the test using Firefox browser
3. Check the browser will be initiated but not opened and test will not be running 

[Include code or an example repository that can easily be set up]
https://github.com/amiya-pattnaik/webdriverIO-with-jasmineBDD
Change the jasmine version from 5 to 6 and run the test.

**Expected behavior**
Firefox browser should open and run the test.

**Log**
2020-06-15T13:43:53.233Z INFO @automation: Starting tests...
Execution of 2 spec files started at 2020-06-15T13:43:53.253Z
2020-06-15T13:43:53.381Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-06-15T13:43:56.155Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-06-15T13:43:56.157Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2020-06-15T13:43:56.421Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-06-15T13:43:57.574Z INFO @automation: Starting tests...
[0-0] 2020-06-15T13:43:57.582Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] 2020-06-15T13:43:57.604Z WARN @wdio/jasmine-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): /Users/rtj/Documents/UI/JasmineWebdriverIO/src/specs/Testjson.js
 Error:  /Users/rtj/Documents/UI/JasmineWebdriverIO/src/specs/Testjson.js:1
import { openWebsite } from "../commonkeywords/action/openWebsite";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at /Users/rtj/Documents/UI/JasmineWebdriverIO/node_modules/jasmine/lib/jasmine.js:89:5
    at Array.forEach (<anonymous>)
    at Jasmine.loadSpecs (/Users/rtj/Documents/UI/JasmineWebdriverIO/node_modules/jasmine/lib/jasmine.js:88:18)
[0-0] RUNNING in firefox - /src/specs/Testjson.js
[0-0] 2020-06-15T13:43:57.830Z INFO webdriverio: Initiate new session using the devtools protocol
[0-0] 2020-06-15T13:43:58.084Z INFO devtools: Launch /Applications/Firefox.app/Contents/MacOS/firefox-bin with config: {"product":"firefox","executablePath":"/Applications/Firefox.app/Contents/MacOS/firefox-bin","defaultViewport":{"width":1200,"height":900},"args":["--no-sandbox","--window-size=1920,1080"]}
[0-0] 2020-06-15T13:44:28.144Z ERROR @wdio/runner: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.
    at Timeout.onTimeout (/Users/rtj/Documents/UI/JasmineWebdriverIO/node_modules/puppeteer-core/lib/launcher/BrowserRunner.js:170:20)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[0-0]  Error:  Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.
[0-0] FAILED in firefox - /src/specs/Testjson.js
2020-06-15T13:44:28.264Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-06-15T13:44:28.265Z INFO @wdio/local-runner: Start worker 0-1 with arg: wdio.conf.js
[0-1] 2020-06-15T13:44:28.552Z INFO @wdio/local-runner: Run worker command: run
[0-1] 2020-06-15T13:44:29.640Z INFO @automation: Starting tests...
[0-1] 2020-06-15T13:44:29.647Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-1] 2020-06-15T13:44:29.671Z WARN @wdio/jasmine-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): /Users/rtj/Documents/UI/JasmineWebdriverIO/src/specs/Testxlsx.js
 Error:  /Users/rtj/Documents/UI/JasmineWebdriverIO/src/specs/Testxlsx.js:1
import { openWebsite } from "../commonkeywords/action/openWebsite";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at /Users/rtj/Documents/UI/JasmineWebdriverIO/node_modules/jasmine/lib/jasmine.js:89:5
    at Array.forEach (<anonymous>)
    at Jasmine.loadSpecs (/Users/rtj/Documents/UI/JasmineWebdriverIO/node_modules/jasmine/lib/jasmine.js:88:18)
[0-1] RUNNING in firefox - /src/specs/Testxlsx.js
[0-1] 2020-06-15T13:44:29.898Z INFO webdriverio: Initiate new session using the devtools protocol
[0-1] 2020-06-15T13:44:30.164Z INFO devtools: Launch /Applications/Firefox.app/Contents/MacOS/firefox-bin with config: {"product":"firefox","executablePath":"/Applications/Firefox.app/Contents/MacOS/firefox-bin","defaultViewport":{"width":1200,"height":900},"args":["--no-sandbox","--window-size=1920,1080"]}
[0-1] 2020-06-15T13:45:00.220Z ERROR @wdio/runner: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.
    at Timeout.onTimeout (/Users/kumar/Documents/UI/JasmineWebdriverIO/node_modules/puppeteer-core/lib/launcher/BrowserRunner.js:170:20)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[0-1]  Error:  Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision rlatest is guaranteed to work.
[0-1] FAILED in firefox - /src/specs/Testxlsx.js
2020-06-15T13:45:00.339Z INFO @wdio/cli:launcher: Run onComplete hook
2020-06-15T13:45:00.339Z INFO @wdio/selenium-standalone-service: shutting down all browsers
Spec Files:      0 passed, 2 failed, 2 total (100% completed) in 00:01:07 
2020-06-15T13:45:00.340Z INFO @wdio/local-runner: Shutting down spawned worker
2020-06-15T13:45:00.592Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-06-15T13:45:00.592Z INFO @wdio/local-runner: shutting down
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriverio@1.0.0 test:run: `wdio wdio.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webdriverio@1.0.0 test:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
> Change the jasmine version from 5 to 6 and run the test.

You can't just update the package version of a single package. WebdriverIO pins the versions to each other so you need to make sure that every package is on the same version number. So if you want to upgrade to v6 you need to upgrade your whole setup to v6.
