### ISSUE TITLE
After update to v6 Multiremote start browser on the device instead of the host

### ISSUE THREAD

**Issue by fege** [webdriverio/webdriverio#5508]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.17
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** Chrome 83
 - **Platform name and version:** Mac / android
 - **Additional wdio packages used (if applicable):** 
"@wdio/allure-reporter": "^6.0.4",
    "@wdio/appium-service": "6.1.16",
    "@wdio/cli": "^6.1.17",
    "@wdio/cucumber-framework": "^6.1.18",
    "@wdio/dot-reporter": "^5.12.1",
    "@wdio/junit-reporter": "5.0.0",
    "@wdio/local-runner": "^6.1.17",
    "@wdio/selenium-standalone-service": "^6.1.14",
    "@wdio/spec-reporter": "^5.0.0",
    "@wdio/sync": "^6.1.14",

**Config of WebdriverIO**
```
var wdioConfig = {
  config: {
    maxInstances: 1,
    capabilities: {
      webClient: {
        maxInstances: 1,
        capabilities: {
          "goog:chromeOptions": {
            args: [
              "--ignore-certificate-errors",
              "--no-cache",
              "--no-sandbox",
              "--allow-insecure-localhost",
              "--allow-sxg-certs-without-extension",
              "--disable-web-security",
              "--disable-popup-blocking",
              "--disable-default-apps",
              "--window-size=1920,1080"
            ],
            binary: (execSync("uname -s").includes("Linux")) ? "/usr/bin/google-chrome" : "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
          },
          browserName: "chrome"
        }
      },
      androidClient: {
        maxInstances: 1,
        platformName: "android",
        browserName: "android",
        capabilities: {
          "appium:automationName": "Espresso",
          "appium:nativeWebScreenshot": true,
          "appium:forceEspressoRebuild": true,
          "appium:unicodeKeyboard": true,
          "appium:resetKeyboard": true,
          "appium:appActivity": process.env.ANDROID_APP_ACTIVITY ? process.env.ANDROID_APP_ACTIVITY : "com.here.hnod.app.activities.MainActivity",
          "appium:appPackage": process.env.ANDROID_APP_PACKAGE,
          "appium:autoGrantPermissions": true,
          "appium:clearDeviceLogsOnStart": true,
          "appium:newCommandTimeout": 300000,
          "appium:deviceName": process.env.ANDROID_DEVICE,
          "appium:app": path.resolve(process.env.ANDROID_APP_PATH)
        }
      }
    },

...

 services: [
      ["selenium-standalone", {
        logPath: "./build/reports/",
        installArgs: {
          version: "3.141.59",
          drivers: {
            chrome: {
              version: "83.0.4103.39",
              arch: process.arch
            }
          }
        },
        args: {
          port: seleniumPort,
          version: "3.141.59",
          drivers: {
            chrome: {
              version: "83.0.4103.39",
              arch: process.arch
            }
          }
        }
      }],
      ["appium", {
        args: {
          port: appiumPort,
          commandTimeout: 7200,
          relaxedSecurity: true,
          platformName: "android",
          tmp: tmpPath,
          chromedriverExecutable: path.resolve("./node_modules/.bin/chromedriver")
        }
      }]
    ],
```
**Describe the bug**
when lunching the test the browser is opened on the android device instead that on the host as it was doing with webdiverio v5

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**
start browser on the host and apk on the device

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@fege can you set `hostname` and `port` in your capability matrix? You are using the Appium and Selenium Standalone service at the same time and need to tell which capability should connect to which service.

**Comment by fege** [comment]
@christian-bromann added port and hostname but now it is failing to create the session
```
capabilities: {
      webClient: {
        port: seleniumPort,
        hostname: "127.0.0.1",
        maxInstances: 1,
        capabilities: {
          "goog:chromeOptions": {
            args: [
              "--ignore-certificate-errors",
              "--no-cache",
              "--no-sandbox",
              "--allow-insecure-localhost",
              "--allow-sxg-certs-without-extension",
              "--disable-web-security",
              "--disable-popup-blocking",
              "--disable-default-apps",
              "--window-size=1920,1080"
            ],
            binary: (execSync("uname -s").includes("Linux")) ? "/usr/bin/google-chrome" : "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
          },
          browserName: "chrome"
        }
      },
      androidClient: {
        maxInstances: 1,
        port: appiumPort,
        hostname: "192.168.178.33",
        platformName: "android",
        browserName: "android",
```

https://gist.github.com/fege/12b6c65bbed4a9ed796488ba3d6f519a

**Comment by christian-bromann** [comment]
Can you check if the selenium server was started? Could be that the `path` is set to `/wd/hub`. So you can try to also add `path: "/wd/hub"`

**Comment by fege** [comment]
I added `seleniumArgs` in the services 


```
   services: [
      ["selenium-standalone", {
        logPath: "./build/reports/",
        installArgs: {
          //version: "3.141.59",
          drivers: {
            chrome: {
              version: "83.0.4103.39",
              arch: process.arch
            }
          }
        },
        args: {
          version: "3.141.59",
          seleniumArgs: ['-host', '127.0.0.1','-port', seleniumPort],
          drivers: {
            chrome: {
              version: "83.0.4103.39",
              arch: process.arch
            }
          }
        }
```

and I got 

`It seems you are running a Selenium Standalone server and point to a wrong path. Please set `path: '/wd/hub'` in your wdio.conf.js!`

but I tried both setting the path and not but the message is always the same



https://gist.github.com/fege/7de6126e4e9ba1ff7334cddfe1377632

**Comment by fege** [comment]
Add the path in the capabilities matrix helped 

```
webClient: {
        port: seleniumPort,
        path: '/wd/hub',
```

@christian-bromann is something changed on the `reloadSession()` we are calling that for both chrome and device, and while there are no problem for the first I get 

```
020-06-18T14:29:50.051Z DEBUG webdriver: request failed due to response error: invalid session id
2020-06-18T14:29:50.051Z WARN webdriver: Request failed with status 404 due to A session is either terminated or not started
2020-06-18T14:29:50.051Z INFO webdriver: Retrying 1/3
2020-06-18T14:29:50.051Z INFO webdriver: [GET] http://localhost:52733/session/5d813689-57e6-496a-9161-3ca0921d39bd/source
2020-06-18T14:29:50.054Z INFO webdriver: COMMAND takeScreenshot()
2020-06-18T14:29:50.054Z INFO webdriver: [GET] http://localhost:52733/session/5d813689-57e6-496a-9161-3ca0921d39bd/screenshot
2020-06-18T14:29:50.062Z DEBUG webdriver: request failed due to response error: invalid session id
2020-06-18T14:29:50.062Z WARN webdriver: Request failed with status 404 due to A session is either terminated or not started
2020-06-18T14:29:50.062Z INFO webdriver: Retrying 1/3
2020-06-18T14:29:50.062Z INFO webdriver: [GET] http://localhost:52733/session/5d813689-57e6-496a-9161-3ca0921d39bd/screenshot
2020-06-18T14:29:50.064Z ERROR @wdio/sync: RequestError: socket hang up
    at ClientRequest.<anonymous> (/Users/mosca/runtime/test/system/node_modules/got/dist/source/core/index.js:826:25)
    at ClientRequest.origin.emit (/Users/mosca/runtime/test/system/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketOnEnd (_http_client.js:460:9)
    at endReadableNT (_stream_readable.js:1204:12)
    at connResetException (internal/errors.js:604:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at Object.afterStep (/Users/mosca/runtime/test/system/config/wdio.conf.js:393:56)

```

**Comment by fege** [comment]
if someone have the same problem about `reloadSession()` I changed the one for android in `reset()` and seems to work.
@christian-bromann can be close I assume
