### ISSUE TITLE
a TypeError when trying to handle a result in an error

### ISSUE THREAD

**Issue by HananArgov** [webdriverio/webdriverio#5518]
looking at the code, i'm seeing that when there's an err, an exception will be thrown since it's trying to access result, which is undefined

https://github.com/webdriverio/webdriverio/blob/0dcc25cce0dcd537195d31836317c857cc2713a9/packages/wdio-devtools-service/src/commands.js#L51

this is the exception i'm getting:
```
TypeError: Cannot read property 'message' of undefined
    at client.(anonymous function).(anonymous function) (/Users/hananargov/Documents/TS/node_modules/@wdio/devtools-service/build/commands.js:49:66)
    at _ws.send (/Users/hananargov/Documents/TS/node_modules/chrome-remote-interface/lib/chrome.js:285:21)
    at sendAfterClose (/Users/hananargov/Documents/TS/node_modules/ws/lib/websocket.js:733:5)
    at WebSocket.send (/Users/hananargov/Documents/TS/node_modules/ws/lib/websocket.js:339:7)
    at Chrome._enqueueCommand (/Users/hananargov/Documents/TS/node_modules/chrome-remote-interface/lib/chrome.js:281:18)
    at Chrome.send (/Users/hananargov/Documents/TS/node_modules/chrome-remote-interface/lib/chrome.js:83:18)
    at Object.handler [as enable] (/Users/hananargov/Documents/TS/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at Promise (/Users/hananargov/Documents/TS/node_modules/@wdio/devtools-service/build/commands.js:47:73)
    at new Promise (<anonymous>)
    at CommandHandler.cdp (/Users/hananargov/Documents/TS/node_modules/@wdio/devtools-service/build/commands.js:47:12)
```

**Comment by christian-bromann** [comment]
@HananArgov can you provide a minimal reproducible example?

**Comment by HananArgov** [comment]
i don't think there's a need for an example, since it's a syntax issue (not handling the correct argument)
but here's the example spec:
```
describe('simple test', () => {
  it(`Simple test verification`, () => {
    browser.reloadSession();

    // @ts-ignore: browser.config does not have the property in types
    browser.cdp('Runtime', 'enable');
  });
});
```

**Comment by christian-bromann** [comment]
I would not say it is a syntax issue. The cdp command is returning an unexpected result (`undefined`) and it would be helpful to see where this comes from.

Any help on investigating this issue would be appreciated.

**Comment by HananArgov** [comment]
just ran the spec above, and got the exception you saw.
when i changed `result.message` to `err.message` the exception became:
```
Error: Chrome DevTools Error: WebSocket is not open: readyState 3 (CLOSED)
    at client.(anonymous function).(anonymous function) (/Users/hananargov/Documents/TS/node_modules/@wdio/devtools-service/build/commands.js:49:23)
    at _ws.send (/Users/hananargov/Documents/TS/node_modules/chrome-remote-interface/lib/chrome.js:285:21)
    at sendAfterClose (/Users/hananargov/Documents/TS/node_modules/ws/lib/websocket.js:733:5)
    at WebSocket.send (/Users/hananargov/Documents/TS/node_modules/ws/lib/websocket.js:339:7)
    at Chrome._enqueueCommand (/Users/hananargov/Documents/TS/node_modules/chrome-remote-interface/lib/chrome.js:281:18)
    at Chrome.send (/Users/hananargov/Documents/TS/node_modules/chrome-remote-interface/lib/chrome.js:83:18)
    at Object.handler [as enable] (/Users/hananargov/Documents/TS/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at Promise (/Users/hananargov/Documents/TS/node_modules/@wdio/devtools-service/build/commands.js:47:73)
    at new Promise (<anonymous>)
    at CommandHandler.cdp (/Users/hananargov/Documents/TS/node_modules/@wdio/devtools-service/build/commands.js:47:12)
```
which I think is more informative

**Comment by christian-bromann** [comment]
@HananArgov would you mind creating a PR making the proposed change? I will create a new issue to fix the original problem.

**Comment by HananArgov** [comment]
this is my first time in this, should i fork the repo, and after the change create a PR? sorry for the first timer question

**Comment by pjcalvo** [comment]
@hakubo You can read the `contributing guidelines. ` [here](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and yes you need to fork and create a PR from ur repo.

**Comment by christian-bromann** [comment]
> sorry for the first timer question

Don't apologise , we are here to help you! Let us know if you have any further questions!

**Comment by christian-bromann** [comment]
Let's continue convo in #5526
