### ISSUE TITLE
unable to initiate appium session after upgrading to wdio 6.1.19

### ISSUE THREAD

**Issue by Amrkamel1** [webdriverio/webdriverio#5520]
**Environment (please complete the following information):**
 - **WebdriverIO version:**  6.1.19
 - **Mode:** standalone
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.13.4
 - **Browser name and version:** N/A
 - **Platform name and version:** ubuntu
 - **Additional wdio packages used (if applicable):** 
```
"dependencies": {
    "@wdio/cli": "^6.1.19"
  },
  "devDependencies": {
    "@wdio/local-runner": "^6.1.19",
    "@wdio/mocha-framework": "^6.1.19",
    "@wdio/selenium-standalone-service": "^6.1.14",
    "@wdio/spec-reporter": "^6.1.14",
    "@wdio/sync": "^6.1.14"
  }
```

**Config of WebdriverIO**
```
 let { join } = require('path');
exports.config = {
    runner: 'local',
    port: 4723,
    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 1,
    capabilities: [{
        platformName: 'Android',
        'appium:deviceName': 'Pixel',
        'appium:avd': 'Pixel',
        'appium:app': join(process.cwd(), 'src/resources/test.apk')
    }],
    logLevel: 'error',
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['selenium-standalone'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
}
```

**Describe the bug**
after upgrading to 6.1.19 i start to have the following error,

```
Execution of 1 spec files started at 2020-06-21T15:13:47.730Z

[0-0] RUNNING in Android - /test/specs/01_Login_Suite.js
[0-0] 2020-06-21T15:13:51.799Z ERROR webdriver: Request failed with status 500 due to session not created: Unable to create session from {
  "desiredCapabilities": {
    "platformName": "Android",
    "appium:deviceName": "Pixel",
    "appium:avd": "Pixel",
    "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk"
  },
  "capabilities": {
    "firstMatch": [
      {
        "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk",
        "appium:avd": "Pixel",
        "appium:deviceName": "Pixel",
        "platformName": "android"
      },
      {
        "platformName": "Android",
        "appium:deviceName": "Pixel",
        "appium:avd": "Pixel",
        "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk"
      }
    ]
  }
}

```
 knowing that same code is working fine with version 5.16.10

**To Reproduce**
upgrade to 6.1.19

[Include code or an example repository that can easily be set up]

**Expected behavior**
Appium session will be initiated and test will start

**Log**

```
Execution of 1 spec files started at 2020-06-21T15:13:47.730Z

[0-0] RUNNING in Android - /test/specs/01_Login_Suite.js
[0-0] 2020-06-21T15:13:51.799Z ERROR webdriver: Request failed with status 500 due to session not created: Unable to create session from {
  "desiredCapabilities": {
    "platformName": "Android",
    "appium:deviceName": "Pixel",
    "appium:avd": "Pixel",
    "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk"
  },
  "capabilities": {
    "firstMatch": [
      {
        "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk",
        "appium:avd": "Pixel",
        "appium:deviceName": "Pixel",
        "platformName": "android"
      },
      {
        "platformName": "Android",
        "appium:deviceName": "Pixel",
        "appium:avd": "Pixel",
        "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk"
      }
    ]
  }
}
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'warrior', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-37-generic', java.version: '1.8.0_251'
Driver info: driver.version: unknown
[0-0] 2020-06-21T15:13:51.800Z ERROR webdriver: session not created: Unable to create session from {
  "desiredCapabilities": {
    "platformName": "Android",
    "appium:deviceName": "Pixel",
    "appium:avd": "Pixel",
    "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk"
  },
  "capabilities": {
    "firstMatch": [
      {
        "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk",
        "appium:avd": "Pixel",
        "appium:deviceName": "Pixel",
        "platformName": "android"
      },
      {
        "platformName": "Android",
        "appium:deviceName": "Pixel",
        "appium:avd": "Pixel",
        "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk"
      }
    ]
  }
}
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'warrior', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-37-generic', java.version: '1.8.0_251'
Driver info: driver.version: unknown
    at getErrorFromResponseBody (/home/amrka/Desktop/work/appium_js/node_modules/webdriver/build/utils.js:121:10)
    at WebDriverRequest._request (/home/amrka/Desktop/work/appium_js/node_modules/webdriver/build/request.js:149:56)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startWebDriverSession (/home/amrka/Desktop/work/appium_js/node_modules/webdriver/build/utils.js:41:16)
    at async Function.newSession (/home/amrka/Desktop/work/appium_js/node_modules/webdriver/build/index.js:44:23)
    at async remote (/home/amrka/Desktop/work/appium_js/node_modules/webdriverio/build/index.js:66:20)
    at async Runner._startSession (/home/amrka/Desktop/work/appium_js/node_modules/@wdio/runner/build/index.js:206:50)
    at async Runner._initSession (/home/amrka/Desktop/work/appium_js/node_modules/@wdio/runner/build/index.js:175:21)
    at async Runner.run (/home/amrka/Desktop/work/appium_js/node_modules/@wdio/runner/build/index.js:93:15)
2020-06-21T15:13:51.800Z ERROR @wdio/runner: Error: Failed to create session.
Unable to create session from {
  "desiredCapabilities": {
    "platformName": "Android",
    "appium:deviceName": "Pixel",
    "appium:avd": "Pixel",
    "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk"
  },
  "capabilities": {
    "firstMatch": [
      {
        "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\test.apk",
        "appium:avd": "Pixel",
        "appium:deviceName": "Pixel",
        "platformName": "android"
      },
      {
        "platformName": "Android",
        "appium:deviceName": "Pixel",
        "appium:avd": "Pixel",
        "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\test.apk"
      }
    ]
  }
}
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'warrior', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-37-generic', java.version: '1.8.0_251'
Driver info: driver.version: unknown
    at startWebDriverSession (/home/amrka/Desktop/work/appium_js/node_modules/webdriver/build/utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0]  Error:  Failed to create session.
Unable to create session from {
  "desiredCapabilities": {
    "platformName": "Android",
    "appium:deviceName": "Pixel",
    "appium:avd": "Pixel",
    "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk"
  },
  "capabilities": {
    "firstMatch": [
      {
        "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk",
        "appium:avd": "Pixel",
        "appium:deviceName": "Pixel",
        "platformName": "android"
      },
      {
        "platformName": "Android",
        "appium:deviceName": "Pixel",
        "appium:avd": "Pixel",
        "appium:app": "\u002fhome\u002famrka\u002fDesktop\u002fwork\u002fappium_js\u002fsrc\u002fresources\u002ftest.apk"
      }
    ]
  }
}
Build info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'
System info: host: 'warrior', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-37-generic', java.version: '1.8.0_251'
Driver info: driver.version: unknown
[0-0] FAILED in Android - /test/specs/01_Login_Suite.js

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:04 
```

**Comment by Amrkamel1** [comment]
solved by 

```
  "dependencies": {
    "@wdio/cli": "^6.1.20"
  },
  "devDependencies": {
    "@wdio/appium-service": "^6.1.16",
    "@wdio/local-runner": "^6.1.20",
    "@wdio/mocha-framework": "^6.1.19",
    "@wdio/selenium-standalone-service": "^6.1.14",
    "@wdio/spec-reporter": "^6.1.14",
    "@wdio/sync": "^6.1.14",
    "chai": "^4.2.0"
  }
```

```
 services: [['appium',{
        command : 'appium',
        args: {
            // ...
            debugLogSpacing: true,
            // platformName: 'Android',
            port: 4723, // ...
        }
    }],
```
