### ISSUE TITLE
Calling browser.clearLocalStorage() results in error

### ISSUE THREAD

**Issue by raditotev** [webdriverio/webdriverio#5548]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.1.12
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.20.1
 - **NPM version:** 6.14.4
 - **Browser name and version:** Safari 12.1
 - **Platform name and version:** iOS 12.1
 - **Additional wdio packages used (if applicable):** 
    "@wdio/appium-service": "^6.1.0",
    "@wdio/cli": "^6.1.11",
    "@wdio/jasmine-framework": "^6.1.8",
    "@wdio/junit-reporter": "^6.1.9",
    "@wdio/local-runner": "^6.1.11",
    "@wdio/spec-reporter": "^6.1.9",
    "@wdio/sync": "^6.1.8",

**Config of WebdriverIO**
N/A

**Describe the bug**
Executing `browser.clearLocalStorage()` in webview context results in an error:
```
ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 400 - undefined
```

**To Reproduce**
Start test on iOS device, switch to webview context and try `browser.clearLocalStorage()`
```
[0-0] › driver.switchContext('WEBVIEW_XXXX.X')
[0-0] 2020-06-26T07:42:49.266Z INFO webdriver: COMMAND switchContext("WEBVIEW_XXXX.X")
[0-0] 2020-06-26T07:42:49.269Z INFO webdriver: [POST] http://localhost:4723/session/ab4bbe39-4ec2-4e4e-b609-04da018b7e23/context
[0-0] 2020-06-26T07:42:49.269Z INFO webdriver: DATA { name: 'WEBVIEW_XXXX.X' }
null
[0-0] › driver.clearLocalStorage();
```

**Expected behavior**
Expected local storage to be empty and command not to raise an error

**Log**
```
[0-0] › driver.getContext() # Check current context is webview
[0-0] 2020-06-26T07:42:30.816Z INFO webdriver: COMMAND getContext()
[0-0] 2020-06-26T07:42:30.817Z INFO webdriver: [GET] http://localhost:4723/session/ab4bbe39-4ec2-4e4e-b609-04da018b7e23/context
[0-0] 2020-06-26T07:42:30.820Z INFO webdriver: RESULT WEBVIEW_XXXX.X
'WEBVIEW_XXXX.X'
[0-0] › driver.clearLocalStorage();
[0-0] 2020-06-26T07:42:53.539Z INFO webdriver: COMMAND clearLocalStorage()
[0-0] 2020-06-26T07:42:53.539Z INFO webdriver: [DELETE] http://localhost:4723/session/ab4bbe39-4ec2-4e4e-b609-04da018b7e23/local_storage
[0-0] 2020-06-26T07:42:53.554Z DEBUG webdriver: request failed due to response error: unknown error
[0-0] 2020-06-26T07:42:53.554Z INFO webdriver: Retrying 1/3
2020-06-26T07:42:53.554Z INFO webdriver: [DELETE] http://localhost:4723/session/ab4bbe39-4ec2-4e4e-b609-04da018b7e23/local_storage
[0-0] 2020-06-26T07:42:53.554Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 400 - undefined
[0-0] 2020-06-26T07:42:53.568Z DEBUG webdriver: request failed due to response error: unknown error
[0-0] 2020-06-26T07:42:53.569Z INFO webdriver: Retrying 2/3
2020-06-26T07:42:53.569Z INFO webdriver: [DELETE] http://localhost:4723/session/ab4bbe39-4ec2-4e4e-b609-04da018b7e23/local_storage
[0-0] 2020-06-26T07:42:53.569Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 400 - undefined
[0-0] 2020-06-26T07:42:53.584Z DEBUG webdriver: request failed due to response error: unknown error
[0-0] 2020-06-26T07:42:53.584Z INFO webdriver: Retrying 3/3
2020-06-26T07:42:53.585Z INFO webdriver: [DELETE] http://localhost:4723/session/ab4bbe39-4ec2-4e4e-b609-04da018b7e23/local_storage
[0-0] 2020-06-26T07:42:53.584Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 400 - undefined
[0-0] 2020-06-26T07:42:53.598Z DEBUG webdriver: request failed due to response error: unknown error
[0-0] 2020-06-26T07:42:53.599Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 400 - undefined
Thrown:
/Users/user.name/Projects/ft-app/node_modules/@wdio/sync/build/wrapCommand.js:76
      throw e;
      ^

unknown error: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 400 - undefined
    at evalmachine.<anonymous>:1:8
    at Script.runInContext (vm.js:133:20)
    at Object.runInContext (vm.js:311:6)
    at WDIORepl._runCmd (/Users/user.name/Projects/project/node_modules/@wdio/repl/build/index.js:54:34)
    at /Users/user.name/Projects/user.name/node_modules/@wdio/repl/build/index.js:46:57
```

**Comment by wswebcreation** [comment]
@raditotev 

This looks like a 3rd-party issue with Appium not with WDIO. Which version of Appium are you using?

The workaround would be to inject a script with something like this

```js
//clears everything in localStorage
browser.execute('localStorage.clear()')

//removes only the specific property "test123"
browser.execute('localStorage.clear("localStorage.removeItem(\"test123\")")')
```

**Comment by christian-bromann** [comment]
I second @wswebcreation , Appium doesn't support this command. The workaround is to use the execute command as Wim mentioned.

**Comment by raditotev** [comment]
@wswebcreation thanks for your comment. This is what I have done in my test.
@christian-bromann is it possible to update `clearLocalStorage` so that it executes `localStorage.clear()`?
I am not very familiar with the code base so excuse me if my question is too naive.

**Comment by christian-bromann** [comment]
> is it possible to update `clearLocalStorage` so that it executes `localStorage.clear()`?

The implementation of `clearLocalStorage` is within the driver and not in WebdriverIO.

**Comment by wswebcreation** [comment]
@raditotev 

You might be able to do that yourself by overwriting the native command with this https://webdriver.io/docs/customcommands.html#overwriting-native-commands

Then you can call it like you would normally do but implement something customer when `driver.isMobile` is true

**Comment by raditotev** [comment]
Thank you both 👍
