### ISSUE TITLE
Get Internet Explorer to run using Standalone runner

### ISSUE THREAD

**Issue by Westsaid** [webdriverio/webdriverio#5576]
## 💬 Questions and Help
Hello guys, anyone got IEDriver to run when using wdio standalone?
I receive following error: "The value of the 'parameter' attribute is not a JSON object", idk why but it seems like wdio does not send any parameters to the ie server... 
### Error Log:
`.\IEDriverServer.exe --port=4448 --log-level=DEBUG
I 2020-07-06 16:59:35:051 C:\Projects\webdriver\cpp\webdriver-server\server.cc(87) Starting WebDriver server on port: '4448' on host: ''
I 2020-07-06 16:59:35:051 C:\Projects\webdriver\cpp\iedriver\IEServer.cpp(33) Driver version: 3.150.1.0 (64-bit)
Started InternetExplorerDriver server (64-bit)
3.150.1.0
Listening on port 4448
Log level is set to DEBUG
Only local connections are allowed
D 2020-07-06 16:59:55:258 C:\Projects\webdriver\cpp\webdriver-server\server.cc(338) Command: POST /session 
D 2020-07-06 16:59:55:259 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(60) Mutex acquired for session initalization
D 2020-07-06 16:59:55:266 C:\Projects\webdriver\cpp\iedriver\IESession.cpp(116) Releasing session initialization mutex
D 2020-07-06 16:59:55:266 C:\Projects\webdriver\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" :  }
W 2020-07-06 16:59:55:266 C:\Projects\webdriver\cpp\webdriver-server\command.cc(49) Failed to parse configuration due to * Line 1, Column 59
  Syntax error: value, object or array expected.

JSON command: '{ "name" : "newSession", "locator" : { }, "parameters" :  }'
W 2020-07-06 16:59:55:267 C:\Projects\webdriver\cpp\webdriver-server\command.cc(72) The value of the 'parameters' attribute is not a JSON object. This is invalid for the WebDriver JSON Wire Protocol.
D 2020-07-06 16:59:55:268 C:\Projects\webdriver\cpp\webdriver-server\command.cc(36) Raw JSON command: { "name" : "newSession", "locator" : { }, "parameters" :  }    
W 2020-07-06 16:59:55:268 C:\Projects\webdriver\cpp\webdriver-server\command.cc(49) Failed to parse configuration due to * Line 1, Column 59
  Syntax error: value, object or array expected.

JSON command: '{ "name" : "newSession", "locator" : { }, "parameters" :  }'
W 2020-07-06 16:59:55:269 C:\Projects\webdriver\cpp\webdriver-server\command.cc(72) The value of the 'parameters' attribute is not a JSON object. This is invalid for the WebDriver JSON Wire Protocol.
D 2020-07-06 16:59:55:270 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(935) Setting serialized response to {
        "value" :
        {
                "error" : "invalid argument",
                "message" : "parameters property of command is not a valid JSON object",
                "stacktrace" : ""
        }
}
D 2020-07-06 16:59:55:271 C:\Projects\webdriver\cpp\iedriver\IECommandExecutor.cpp(936) Is waiting flag: 0
D 2020-07-06 16:59:55:281 C:\Projects\webdriver\cpp\webdriver-server\server.cc(421) Response: {
        "value" :
        {
                "error" : "invalid argument",
                "message" : "parameters property of command is not a valid JSON object",
                "stacktrace" : ""
        }
}
`

### Reproducible example
First start [IEDriver](https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver) like this: 
".\IEDriverServer.exe --port=4448 --log-level=DEBUG"

Then run this code:
`const { remote } = require("webdriverio");
let browsers = []

callTests(new Array(10)).then(erg => {
  console.log("Done")
})
async function main(nsc, i) {
    //console.log(`Started test: ${testcase}@${nsc} (${i+1}/${allNSC.length})`)
    const browser = await remote({
        capabilities : {
            browserName: "internet explorer",
        },
        port:4448,
        logLevel: "error",
        outputDir: __dirname + "../../../logs/"
    })
    browsers[i] = browser

    global.browser = browser;
    let url = "https://www.nytimes.com/"
    await browser.url(url)

    await browser.deleteSession()
    await delete browser
    await delete browsers[i]
}

function callTests(arr, i) {
    return new Promise(res => {
        if (i == undefined) i = 0
        let error = false
        main(arr[i], i).catch(async e => {
            console.error(e, arr[i])
            error = e
            await browsers[i].deleteSession();
            await delete browsers[i]
        }).then(async erg => {
            if (i < arr.length - 1) return res(callTests(arr, ++i))
            else res()
        });
    })
}`

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [WebdriverIO Gitter Support Channel](https://gitter.im/webdriverio/webdriverio)
- [#webdriverio channel om SeleniumHQ Slack](https://seleniumhq.slack.com/join/shared_invite/enQtODAwOTUzOTM5OTEwLTZjZjgzN2ExOTBmZGE0NjkwYzA2Nzc0MjczMGYwYjdiNGQ5YjI0ZjdjYjFhMjVlMjFkZWJmNDYyMmU1OTYyM2Y)

**Comment by christian-bromann** [comment]
Can you provide the WebdriverIO logs as well please?

**Comment by Westsaid** [comment]
> Can you provide the WebdriverIO logs as well please?

Hey, sure! There you go:
`2020-07-07T09:23:30.827Z INFO webdriverio: Initiate new session using the webdriver protocol
2020-07-07T09:23:30.838Z INFO webdriver: [POST] http://localhost:4448/session
2020-07-07T09:23:30.838Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'internet explorer' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'internet explorer' }
}
2020-07-07T09:23:30.920Z DEBUG webdriver: request failed due to response error: session not created
2020-07-07T09:23:30.920Z WARN webdriver: Request failed due to Only one session may be created at a time, and a session already exists.
2020-07-07T09:23:30.920Z INFO webdriver: Retrying 1/3
2020-07-07T09:23:30.921Z INFO webdriver: [POST] http://localhost:4448/session
2020-07-07T09:23:30.921Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'internet explorer' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'internet explorer' }
}
2020-07-07T09:23:30.940Z DEBUG webdriver: request failed due to response error: session not created
2020-07-07T09:23:30.941Z WARN webdriver: Request failed due to Only one session may be created at a time, and a session already exists.
2020-07-07T09:23:30.941Z INFO webdriver: Retrying 2/3
2020-07-07T09:23:30.941Z INFO webdriver: [POST] http://localhost:4448/session
2020-07-07T09:23:30.941Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'internet explorer' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'internet explorer' }
}
2020-07-07T09:23:30.958Z DEBUG webdriver: request failed due to response error: session not created
2020-07-07T09:23:30.958Z WARN webdriver: Request failed due to Only one session may be created at a time, and a session already exists.
2020-07-07T09:23:30.959Z INFO webdriver: Retrying 3/3
2020-07-07T09:23:30.960Z INFO webdriver: [POST] http://localhost:4448/session
2020-07-07T09:23:30.960Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'internet explorer' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'internet explorer' }
}
2020-07-07T09:23:30.986Z DEBUG webdriver: request failed due to response error: session not created
2020-07-07T09:23:30.986Z ERROR webdriver: Request failed due to session not created: Only one session may be created at a time, and a session already exists.
    at getErrorFromResponseBody (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\node_modules\webdriverio\node_modules\webdriver\build\utils.js:124:10)
    at WebDriverRequest._request (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\node_modules\webdriverio\node_modules\webdriver\build\request.js:116:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startWebDriverSession (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\node_modules\webdriverio\node_modules\webdriver\build\utils.js:41:16)
    at async Function.newSession (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\node_modules\webdriverio\node_modules\webdriver\build\index.js:46:23)
    at async remote (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\node_modules\webdriverio\build\index.js:58:20)
    at async main (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\test\ieTest.js:9:21)
2020-07-07T09:23:30.987Z ERROR webdriver: session not created: Only one session may be created at a time, and a session already exists.
    at getErrorFromResponseBody (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\node_modules\webdriverio\node_modules\webdriver\build\utils.js:124:10)
    at WebDriverRequest._request (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\node_modules\webdriverio\node_modules\webdriver\build\request.js:116:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async startWebDriverSession (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\node_modules\webdriverio\node_modules\webdriver\build\utils.js:41:16)
    at async Function.newSession (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\node_modules\webdriverio\node_modules\webdriver\build\index.js:46:23)
    at async remote (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\node_modules\webdriverio\build\index.js:58:20)
    at async main (c:\MAZDA2020\qa4ie\qa-Cypress_2020\webdriverio-test\test\ieTest.js:9:21)
`

**Comment by christian-bromann** [comment]
@Westsaid these are the wrong logs. They show that the session wasn't created at all while above you are clearly had created a session.

**Comment by Westsaid** [comment]
> @Westsaid these are the wrong logs. They show that the session wasn't created at all while above you are clearly had created a session.

Oh I'm sorry I messed up... Here is a true on:

[wdio.log](https://github.com/webdriverio/webdriverio/files/4883948/wdio.log)

**Comment by christian-bromann** [comment]
This is the same log :-D

**Comment by Westsaid** [comment]
It's not... Check the first try, only the first 20 lines of the log are important because if the initialization fails, it retries it 2 more times.  

Here are the first 20 lines:
`
2020-07-07T09:31:37.507Z INFO webdriverio: Initiate new session using the webdriver protocol
2020-07-07T09:31:37.522Z INFO webdriver: [POST] http://localhost:4448/session
2020-07-07T09:31:37.523Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'internet explorer' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'internet explorer' }
}
2020-07-07T09:31:37.818Z DEBUG webdriver: request failed due to response error: invalid argument
2020-07-07T09:31:37.819Z WARN webdriver: Request failed due to parameters property of command is not a valid JSON object
2020-07-07T09:31:37.819Z INFO webdriver: Retrying 1/3
2020-07-07T09:31:37.819Z INFO webdriver: [POST] http://localhost:4448/session
2020-07-07T09:31:37.820Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'internet explorer' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'internet explorer' }
}`

**Comment by christian-bromann** [comment]
> This is invalid for the WebDriver JSON Wire Protocol.

It seems that you are using an old IEDriver which doesn't support the WebDriver protocol. The latest WebdriverIO version only runs on WebDriver and doesn't support JSONWireProtocol only at this point.

**Comment by Westsaid** [comment]
Thank you very much, I went from 3.15 => 3.9 and the error disappeared!

**Comment by Westsaid** [comment]
It seems like WDIO fails to pass the parameters to the driver. Does somebody know in which part of the code this actually happens?

**Comment by christian-bromann** [comment]
@Westsaid according to the logs the right data is being send to the driver:

```js
2020-07-07T09:31:37.507Z INFO webdriverio: Initiate new session using the webdriver protocol
2020-07-07T09:31:37.522Z INFO webdriver: [POST] http://localhost:4448/session
2020-07-07T09:31:37.523Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'internet explorer' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'internet explorer' }
}
```

**Comment by Westsaid** [comment]
Hello!

Good news: This bug will be closed in the next release of IEDriver!
