### ISSUE TITLE
ERROR webdriver: Request failed due to Error: unknown command:

### ISSUE THREAD

**Issue by JockVanDallas** [webdriverio/webdriverio#5650]
**Environment:**
 - **WebdriverIO version:** webdriverio@6.1.16
 - **Node.js version:** v12.18.1
 - **NPM version:** 6.14.5
 - **Browser name and version:**  Chrome 84.0.4147.89
 - **Platform name and version:** MacOS Catalina 10.15.5
 - **Additional wdio packages used (if applicable):** 
     "@wdio/allure-reporter": "^5.18.6",
    "@wdio/cli": "^5.11.0",
    "@wdio/config": "^5.11.0",
    "@wdio/cucumber-framework": "^5.18.6",
    "@wdio/devtools-service": "^5.15.1",
    "@wdio/local-runner": "^5.18.6",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/shared-store-service": "^6.1.4",
    "@wdio/spec-reporter": "^5.18.6",
    "@wdio/sync": "^5.18.6",

**Config of WebdriverIO**
```
const path = require('path');
const fs = require('fs-extra');
const { registerCommands } = require('./custom-commands/register-custom-commands');

exports.config = {
  specs: ['./src/features/**/*.feature'],
  maxInstances: 1,
  capabilities: [
    {
      maxInstances: 5,
      browserName: 'chrome',
    },
  ],

  chromeDriverArgs: ['--port=9516', "--url-base='/'"],
  logLevel: 'trace',
  coloredLogs: true,
  screenshotPath: './errorShots/',
  waitforTimeout: 10000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  services: ['devtools', 'selenium-standalone', 'shared-store'],
  outputDir: path.join(__dirname, 'logs'),
  seleniumInstallArgs: {
    baseURL: 'https://****/artifactory/googleapis_selenium-release-cache',
    drivers: {
      chrome: {
        arch: process.arch,
        baseURL: 'https://****/artifactory/googleapis_chromedriver-cache',
      },
      firefox: {
        arch: process.arch,
        baseURL:
          'https://****/artifactory/github-cache/mozilla/geckodriver/releases/download',
      },
    },
  },
  framework: 'cucumber',
  reporters: ['spec'],
  cucumberOpts: {
    backtrace: false,
    requireModule: ['@babel/register'],
    failAmbiguousDefinitions: true,
    failFast: false,
    ignoreUndefinedDefinitions: false,
    name: [],
    snippets: true,
    source: true,
    profile: [],
    port: 9516,
    require: ['./src/**/*.js'],
    snippetSyntax: undefined,
    strict: true,
    tagExpression: '@Test',
    tagsInTitle: false,
    timeout: 1000000,
  },

  before: function before(env, users) {
    const chai = require('chai');

    global.expect = chai.expect;
    global.assert = chai.assert;
    global.should = chai.should();

    registerCommands(browser);

    global.env = env;
    global.users = users;
    global.runId = Math.random();
  },

};
```

**Describe the bug**
When running one of my Cucumber scenarios, I am trying to click a button, but nothing happens.
The test does not fail, but in the logs I see some warnings and errors from webdriver

``` 
When(/^I click the confirm button on the confirmation dialog$/, () => {
  ConfirmationDialog.confirmButton.waitForDisplayed();
  ConfirmationDialog.confirmButton.isDisplayed();
  ConfirmationDialog.confirmButton.isClickable();
  ConfirmationDialog.confirmButton.click();
});
```

The `waitForDisplayed`, `isDisplayed`, `isClickable` all work fine. Except the last one

**Log**
```
2020-07-22T09:31:02.770Z INFO webdriver: COMMAND findElement("css selector", "#dialogConfirmationButton")
2020-07-22T09:31:02.770Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/5251ebfbf5311a9bb08e9ec6a2fca68d/element
2020-07-22T09:31:02.770Z INFO webdriver: DATA { using: 'css selector', value: '#dialogConfirmationButton' }
2020-07-22T09:31:02.775Z INFO webdriver: RESULT { ELEMENT: '0.09538792620397629-27' }
2020-07-22T09:31:02.778Z INFO webdriver: COMMAND elementClick("0.09538792620397629-27")
2020-07-22T09:31:02.778Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/5251ebfbf5311a9bb08e9ec6a2fca68d/element/0.09538792620397629-27/click
2020-07-22T09:31:05.829Z INFO webdriver: COMMAND getLogTypes()
2020-07-22T09:31:05.829Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/5251ebfbf5311a9bb08e9ec6a2fca68d/se/log/types
2020-07-22T09:31:05.832Z DEBUG webdriver: request failed due to missing body
2020-07-22T09:31:05.832Z WARN webdriver: Request failed due to unknown command: session/5251ebfbf5311a9bb08e9ec6a2fca68d/se/log/types
2020-07-22T09:31:05.832Z INFO webdriver: Retrying 1/3
2020-07-22T09:31:05.832Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/5251ebfbf5311a9bb08e9ec6a2fca68d/se/log/types
2020-07-22T09:31:05.834Z DEBUG webdriver: request failed due to missing body
2020-07-22T09:31:05.834Z WARN webdriver: Request failed due to unknown command: session/5251ebfbf5311a9bb08e9ec6a2fca68d/se/log/types
2020-07-22T09:31:05.834Z INFO webdriver: Retrying 2/3
2020-07-22T09:31:05.834Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/5251ebfbf5311a9bb08e9ec6a2fca68d/se/log/types
2020-07-22T09:31:05.835Z DEBUG webdriver: request failed due to missing body
2020-07-22T09:31:05.836Z WARN webdriver: Request failed due to unknown command: session/5251ebfbf5311a9bb08e9ec6a2fca68d/se/log/types
2020-07-22T09:31:05.836Z INFO webdriver: Retrying 3/3
2020-07-22T09:31:05.836Z INFO webdriver: [GET] http://127.0.0.1:4444/wd/hub/session/5251ebfbf5311a9bb08e9ec6a2fca68d/se/log/types
2020-07-22T09:31:05.837Z DEBUG webdriver: request failed due to missing body
2020-07-22T09:31:05.837Z ERROR webdriver: Request failed due to Error: unknown command: session/5251ebfbf5311a9bb08e9ec6a2fca68d/se/log/types
    at getErrorFromResponseBody (/Users/*****/Documents/Projects/ing-app-ipa-portal/node_modules/webdriver/build/utils.js:114:12)
    at Request._callback (/Users/*****/Documents/Projects/ing-app-ipa-portal/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/Users/*****/Documents/Projects/ing-app-ipa-portal/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (/Users/*****/Documents/Projects/ing-app-ipa-portal/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (/Users/*****/Documents/Projects/ing-app-ipa-portal/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-07-22T09:31:05.869Z INFO webdriver: COMMAND deleteSession()
2020-07-22T09:31:05.870Z INFO webdriver: [DELETE] http://127.0.0.1:4444/wd/hub/session/5251ebfbf5311a9bb08e9ec6a2fca68d
```

**Comment by christian-bromann** [comment]
This is an issue with BrowserStack not supporting the endpoint for `/session/:sessionId/se/log/types` which is generally supported by Chromium based browser. There is nothing WebdriverIO can do about this. Please report it to BrowserStack and ignore the error message.

**Comment by JockVanDallas** [comment]
Thanx  for the reply, I will report this with  BrowserStack. 

The only thing is that my button is not clicked. So i cant continue my test

**Comment by christian-bromann** [comment]
The logs don't show any hints that the click failed.

**Comment by KaranAgrawal92** [comment]
@JockVanDallas any solution on this issue? I am facing same issue and not able to proceed.
