### ISSUE TITLE
Can't accept alert in a new tab

### ISSUE THREAD

**Issue by lumyjuwon** [webdriverio/webdriverio#5673]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [4.3.6]
 - **Mode:** [Standalone mode]
 - **Node.js version:** [12.9.1]
 - **Browser name and version:** [Chrome]
 - **Platform name and version:** [MacOS]
 - **Additional wdio packages used (if applicable):** [wdio-chromedriver-service]

**Config of WebdriverIO**
Wdio/Async
I use webdriverio by calling the `webdriverio Remote` Method

capabilities: {
 services: ['chromedriver']
 browserName: 'chrome'
}

**Describe the bug**
The browser can't accept alert When the browser switch to new tab

**To Reproduce**
```
it('test', async() => {
  const tab = await browser.createWindow('tab')    
  await browser.switchToWindow(tab.handle);  
  // Open the developer tool and execute javascript "alert("TEST")"  
  await waitTime(8000) // wait 8 seconds because of executing javascript: alert("TEST")  
  await browser.acceptAlert();
}
```

**Expected behavior**
the browser accepts alert in the new tab

**Log**
after calling the browser.acceptAlert() the logger doesn't write any log and timed out (after 60 seconds)

> Please use the correct markdown

**Comment by lumyjuwon** [comment]
i find the reason that page don't do bind the dialogHanlder

switchToWindow.js (https://github.com/webdriverio/webdriverio/blob/master/packages/devtools/src/commands/switchToWindow.js)
```
/**
 * The Switch To Window command is used to select the current top-level browsing context
 * for the current session, i.e. the one that will be used for processing commands.
 *
 * @alias browser.switchToWindow
 * @see https://w3c.github.io/webdriver/#dfn-switch-to-window
 * @param {string} handle  representing a window handle, should be one of the strings that was returned in a call to getWindowHandles
 */

export default async function switchToWindow ({ handle }) {
    if (!this.windows.has(handle)) {
        throw new Error(`window with handle ${handle} not found`)
    }

    delete this.currentFrame
    this.currentWindowHandle = handle
    const page = this.getPageHandle()
    page.on('dialog', this.dialogHandler.bind(this));
    await page.bringToFront()

    return handle
}
```

add the page.on('dialog', this.dialogHandler.bind(this));

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by ilamparithiNatarajan** [comment]
@christian-bromann / @lumyjuwon  shall I pick this up

**Comment by lumyjuwon** [comment]
@ilamparithiNatarajan 
I finish fixing this bug soon

**Comment by lumyjuwon** [comment]
@christian-bromann 
I run the **npm run test:smoke** but it occurs error
os: windows

### command output

```
PS C:\Users\Juwon\Documents\GitHub\webdriverio> npm run test:smoke mochaTestrunner

> webdriverio-monorepo@ test:smoke C:\Users\Juwon\Documents\GitHub\webdriverio
> babel-node ./tests/smoke.runner.js "mochaTestrunner"


Running smoke tests...


Execution of 4 spec files started at 2020-08-04T15:52:29.598Z

[0-1] FAILED
[0-0] FAILED
[0-2] FAILED
[0-3] FAILED

Spec Files:      0 passed, 4 failed, 4 total (100% completed) in 00:00:02


========== LOG OUPUT wdio-0-0-CustomSmokeTestReporter-reporter.log


========== LOG OUPUT wdio-0-0-smoke-test-reporter.log


========== LOG OUPUT wdio-0-0.log


========== LOG OUPUT wdio-0-1.log


========== LOG OUPUT wdio-0-2.log


========== LOG OUPUT wdio-0-3.log


========== LOG OUPUT wdio.log
2020-08-04T15:52:30.080Z INFO @wdio/local-runner: Start worker 0-0 with arg: mochaTestrunner
2020-08-04T15:52:30.092Z INFO @wdio/local-runner: Start worker 0-1 with arg: mochaTestrunner
2020-08-04T15:52:30.100Z INFO @wdio/local-runner: Start worker 0-2 with arg: mochaTestrunner
2020-08-04T15:52:30.108Z INFO @wdio/local-runner: Start worker 0-3 with arg: mochaTestrunner
2020-08-04T15:52:32.325Z DEBUG @wdio/local-runner: Runner 0-1 finished with exit code 1
2020-08-04T15:52020-08-04T15:52:32.327Z INFO @wdio/cli:launcher: Run onComplete hook
 1
2020-08-04T15:52:32.326Z DEBUG @wdio/local-runner: Runner 0-2 finished with exit code 1
2020-08-04T15:52:32.326Z DEBUG @wdio/local-runner: Runner 0-3 finished with exit code 1
2020-08-04T15:52:32.328Z INFO @wdio/local-runner: Shutting down spawned worker
2020-08-04T15:52:32.580Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully

Error: Smoke test failed
    at launcher.run.then.exitCode (C:\Users\Juwon\Documents\GitHub\webdriverio\tests\helpers\launch.js:39:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriverio-monorepo@ test:smoke: `babel-node ./tests/smoke.runner.js "mochaTestrunner"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webdriverio-monorepo@ test:smoke script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Juwon\AppData\Roaming\npm-cache\_logs\2020-08-04T15_52_32_961Z-debug.log
```

### the log file output as follow as

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:smoke',
1 verbose cli   'mochaTestrunner' ]
2 info using npm@6.14.6
3 info using node@v10.22.0
4 verbose run-script [ 'pretest:smoke', 'test:smoke', 'posttest:smoke' ]
5 info lifecycle webdriverio-monorepo@~pretest:smoke: webdriverio-monorepo@
6 info lifecycle webdriverio-monorepo@~test:smoke: webdriverio-monorepo@
7 verbose lifecycle webdriverio-monorepo@~test:smoke: unsafe-perm in lifecycle true
8 verbose lifecycle webdriverio-monorepo@~test:smoke: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Juwon\Documents\GitHub\webdriverio\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Users\Juwon\AppData\Local\Android\Sdk\platform-tools;;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files\Deps\llvm\bin;C:\Program Files\nodejs\;C:\Users\Juwon\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Juwon\AppData\Local\Programs\Python\Python37\;C:\Users\Juwon\AppData\Local\Programs\Python\Launcher\;"C:\Users\Juwon\AppData\Local\Microsoft\WindowsApps;C:\Users\Juwon\AppData\Local\Programs\Python\Python36;C:\Users\Juwon\AppData\Local\Programs\Python\Python36\Scripts;";C:\Users\Juwon\AppData\Local\GitHubDesktop\bin;C:\Users\Juwon\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Java\jdk1.8.0_191\bin;C:\SDK\flutter\bin;C:\Users\Juwon\.dotnet\tools;C:\Users\Juwon\AppData\Roaming\npm
9 verbose lifecycle webdriverio-monorepo@~test:smoke: CWD: C:\Users\Juwon\Documents\GitHub\webdriverio
10 silly lifecycle webdriverio-monorepo@~test:smoke: Args: [ '/d /s /c',
10 silly lifecycle   'babel-node ./tests/smoke.runner.js "mochaTestrunner"' ]
11 silly lifecycle webdriverio-monorepo@~test:smoke: Returned: code: 1  signal: null
12 info lifecycle webdriverio-monorepo@~test:smoke: Failed to exec test:smoke script
13 verbose stack Error: webdriverio-monorepo@ test:smoke: `babel-node ./tests/smoke.runner.js "mochaTestrunner"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid webdriverio-monorepo@
15 verbose cwd C:\Users\Juwon\Documents\GitHub\webdriverio
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:smoke" "mochaTestrunner"
18 verbose node v10.22.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error webdriverio-monorepo@ test:smoke: `babel-node ./tests/smoke.runner.js "mochaTestrunner"`
22 error Exit status 1
23 error Failed at the webdriverio-monorepo@ test:smoke script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by christian-bromann** [comment]
@lumyjuwon did you set up the project according to the [contribution guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md#set-up-project)?

**Comment by lumyjuwon** [comment]
@christian-bromann 
yes i did it. i'm finding the reason can't run the test

**Comment by christian-bromann** [comment]
@lumyjuwon what is the status of this? Can you create a PR and we can take it from there?

**Comment by christian-bromann** [comment]
PR was merged and released. Closing.
