### ISSUE TITLE
browser.mock() doesnt work on pipeline.

### ISSUE THREAD

**Issue by saisun229** [webdriverio/webdriverio#5713]
**Environment** 

**WebdriverIO version:** 6.4
*Mode: dev tools
**If WDIO Testrunner, running sync/async**: Sync true
**Node.js version:** 12
**NPM version:** 6
**Browser name and version:** Chrome 83
**Platform name and version:** Windows 10
**My Wdio Configuration:**

---------------------------------------------------------------------------------------------------------------------------------------
`const video = require("wdio-video-reporter");
const failedTests = new Set();

exports.config = {

  runner: "local",
  hostname: "127.0.0.1",
  path: "/wd/hub",
  specs: ["./tests/components/*.feature"],
  exclude: [],
  maxInstances: 10,
  capabilities: [
    {
      maxInstances: 10,
      browserName: "chrome",
      acceptInsecureCerts: true,
      proxy: {
        proxyType: "pac",
        proxyAutoconfigUrl: "proxy",
      }
    },
  ],
  
  sync: true,
  logLevel: "error",
  coloredLogs: true,
  bail: 0,
  screenshotPath: "./reports/errorShots/",
   baseUrl: "http://127.0.0.1",

// Default timeout for all waitFor* commands.
  waitforTimeout: 30000,
  //
  // Default timeout in milliseconds for request
  // if Selenium Grid doesn't send response
  connectionRetryTimeout: 90000,
  //
  // Default request retries count
  connectionRetryCount: 3,

  services: ['intercept'],

  framework: "cucumber",

  reporters: ["spec",
    [
      video,
      {
        saveAllVideos: false, // If true, also saves videos for successful test cases
        videoSlowdownMultiplier: 40, // Higher to get slower videos, lower for faster videos [Value 1-100]
        videoRenderTimeout: 45,
      },
    ],
    [
      "allure",
      {
        outputDir: "reports/allure-data/",
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: true,
        useCucumberStepReporter: true,
      },
    ],
    [
      "cucumberjs-json",
      {
        jsonFolder: "reports/json-cucumber-results/",
      },
    ],

  ],
  // If you are using Cucumber you need to specify the location of your step definitions.
  cucumberOpts: {
    backtrace: false, // <boolean> show full backtrace for errors
    requireModule: [
      "tsconfig-paths/register",
      () => {
        require("ts-node").register({ files: true });
      },
    ],
    require: ["./tests/steps/*.ts"], // <string[]> (file/dir) require files before executing features
    dryRun: false, // <boolean> invoke formatters without executing steps
    failFast: false, // <boolean> abort the run on first failure
    format: ["pretty"], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
    colors: true, // <boolean> disable colors in formatter output
    snippets: true, // <boolean> hide step definition snippets for pending steps
    source: true, // <boolean> hide source uris
    profile: [], // <string[]> (name) specify the profile to use
    strict: false, // <boolean> fail if there are any undefined or pending steps
    tagExpression: process.env.CUCUMBER_EXPRESSION || "", // <string> (expression) only execute the features or scenarios with tags matching the expression
    timeout: 60000, // <number> timeout for step definitions
    ignoreUndefinedDefinitions: false, // <boolean> Enable this config to treat undefined definitions as warnings.
  },

  //
  // =====
  // Hooks
  // =====
  // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
  // it and to build services around it. You can either apply a single function or an array of
  // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
  // resolved to continue.
  /**
   * Gets executed once before all workers get launched.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   */
  onPrepare(config, capabilities) {
    if (!config.services.includes("selenium-standalone")) {
      console.info(
        "Tests will be running on: " +
          "https://" +
          config.host +
          ":" +
          config.port +
          "/grid/admin/live?refresh=20",
      );
    } else {
      console.info(
        "Tests will be running on: selenium-standalone,",
        "which is your local machine.",
      );
    }
  },
  

  /**
   * Runs after a Cucumber scenario
   */
  afterScenario(uri, feature, scenario, result, sourceLocation) {
    if(result.status !== 'passed'){
      for (let i = 0; i < scenario.tags.length; i++) {
        if(scenario.tags[i].name.startsWith("@TESTM")){
          failedTests.add(scenario.tags[i].name);
        }
      }
    }
  },

  /**
   * Gets executed right after terminating the webdriver session.
   * @param {Object} config wdio configuration object
   * @param {Array.<Object>} capabilities list of capabilities details
   * @param {Array.<String>} specs List of spec file paths that ran
   */
  afterSession: function (config, capabilities, specs) {
    let message = "~~~To run just failed tests use this command with tag expression:" + config.$0 + " " + config._ + " \"--cucumberOpts.tagExpression\" \"";
    if(failedTests.size > 0) {
      const failedTestsArray = Array.from(failedTests);
      for(let i = 0; i < failedTestsArray.length; i++){
        message += failedTestsArray[i];
        if(i !== (failedTestsArray.length-1)) {
          // Don't include 'or' after last failed test id
          message += " or ";
        }
      }
      console.log("\x1b[43m\x1b[34m%s\"\x1b[0m", message);
    }
  },
  
};`
------------------------------------------------------------------------------------------------------------------------------------------
**Describe the bug**
 browser.mock() works in local perfectly. When code is committed and pushed to staging. Gitlab test runner is throwing the following error. Do I need to create any additional containers? I think the error is from puppeteer

[chrome 78.0.3904.70 linux #0-3] Failed to fetch browser webSocket url from http://localhost:33436/json/version: connect ECONNREFUSED 127.0.0.1:33436
[chrome 78.0.3904.70 linux #0-3] Error: connect ECONNREFUSED 127.0.0.1:33436
[chrome 78.0.3904.70 linux #0-3]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
[chrome 78.0.3904.70 linux #0-3]     at new MockService (/e2e/tests/common/MockService.ts:10:25)
[chrome 78.0.3904.70 linux #0-3]     at Function.UserManagementPage.mockOktaUsers (/e2e/tests/pages/UserManagementPage.ts:39:25)
[chrome 78.0.3904.70 linux #0-3]     at new UserManagementPage (/e2e/tests/pages/UserManagementPage.ts:31:24)
[chrome 78.0.3904.70 linux #0-3]     at Function.PageFactoryCustomerSecure.createCustomerPage (/e2e/tests/pages/common/PageFactoryCustomerSecure.ts:101:16)
[chrome 78.0.3904.70 linux #0-3]     at CommonSecureSteps.createPage (/e2e/tests/steps/CommonSecureSteps.ts:123:38)
[chrome 78.0.3904.70 linux #0-3]     at CommonSecureSteps.navigateToPageWithRealmAndLocaleNaturalLanguage (/e2e/tests/steps/CommonSecureSteps.ts:62:39)
[chrome 78.0.3904.70 linux #0-3]     at World.bindingFunc (/e2e/node_modules/cucumber-tsflow/src/binding-decorator.ts:161:22)

**To Reproduce**
1) Use browser.mock()
2) run In pipeline

**Expected behavior**
I expect the tests to pass in pipeline like in the local

**Comment by christian-bromann** [comment]
> * Gitlab test runner is throwing the following error.

The mocking capabilities only work if you run the browser on the same machine as your tests runs. Is this the case in your GitLab pipeline?

**Comment by christian-bromann** [comment]
Closing due to inactivity. Let me know if you have further questions.

**Comment by nofexio** [comment]
Hi, 
I have a the same bug with saucelabs and browser.mock
Is there a special setting, so that the tests run on the same machine as the browser? I can't figure this out.

**Comment by christian-bromann** [comment]
@nofexio please see the note on the top of the page of https://webdriver.io/docs/mocksandspies.html saying that this is not supported when using cloud vendors.

**Comment by nofexio** [comment]
@christian-bromann 
thanks. Sorry, I didn't see that :)
