### ISSUE TITLE
Auto-generated project with default options fails on Windows 

### ISSUE THREAD

**Issue by rendmath** [webdriverio/webdriverio#5720]
**Environment (please complete the following information):**

 - **WebdriverIO version:** 6.4.0
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.18.3
 - **NPM version:** 6.13.2
 - **Browser name and version:** Doesn't even get there
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** None

**Config of WebdriverIO**

Default CLI config (--yes).

**Describe the bug**

Auto-generated project with default options fails on Windows.

**To Reproduce**

```
npm i @wdio/cli
npx wdio config --yes
npx wdio
```

**Expected behavior**

The test runs successfully.

**Log**

```
[0-0] 2020-08-11T11:51:05.244Z ERROR @wdio/runner: Error: Cannot find module '..pageobjects/login.page'
Require stack:
- C:\sources\training\test3\test\specs\example.e2e.js
- C:\sources\training\test3\node_modules\mocha\lib\mocha.js
- C:\sources\training\test3\node_modules\mocha\index.js
- C:\sources\training\test3\node_modules\@wdio\mocha-framework\build\index.js
- C:\sources\training\test3\node_modules\@wdio\utils\build\utils.js
- C:\sources\training\test3\node_modules\@wdio\utils\build\initialisePlugin.js
- C:\sources\training\test3\node_modules\@wdio\utils\build\index.js
- C:\sources\training\test3\node_modules\@wdio\runner\build\index.js
- C:\sources\training\test3\node_modules\@wdio\local-runner\build\run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\sources\training\test3\test\specs\example.e2e.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
[0-0]  Error:  Cannot find module '..pageobjects/login.page'
Require stack:
- C:\sources\training\test3\test\specs\example.e2e.js
- C:\sources\training\test3\node_modules\mocha\lib\mocha.js
- C:\sources\training\test3\node_modules\mocha\index.js
- C:\sources\training\test3\node_modules\@wdio\mocha-framework\build\index.js
- C:\sources\training\test3\node_modules\@wdio\utils\build\utils.js
- C:\sources\training\test3\node_modules\@wdio\utils\build\initialisePlugin.js
- C:\sources\training\test3\node_modules\@wdio\utils\build\index.js
- C:\sources\training\test3\node_modules\@wdio\runner\build\index.js
- C:\sources\training\test3\node_modules\@wdio\local-runner\build\run.js
```

**Additional context**

A PR has been created already (#5712).

**Comment by christian-bromann** [comment]
Let's continue our discussion in #5712 then.
