### ISSUE TITLE
ERROR @wdio/runner: Error: Failed to create session.

### ISSUE THREAD

**Issue by vikash90** [webdriverio/webdriverio#5724]
0-0] 2020-08-12T14:05:07.101Z ERROR webdriver: RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/apple/Desktop/LoginDemo/test_project/node_modules/got/dist/source/core/index.js:891:25)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at ClientRequest.origin.emit (/Users/apple/Desktop/LoginDemo/test_project/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[0-0] 2020-08-12T14:05:07.102Z ERROR @wdio/runner: Error: Failed to create session.
read ECONNRESET
    at startWebDriverSession (/Users/apple/Desktop/LoginDemo/test_project/node_modules/webdriver/build/utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0]  Error:  Failed to create session.
read ECONNRESET
2020-08-12T14:05:07.216Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in /Users/apple/Desktop/LoginDemo/android/app/build/outputs/apk/debug/app-debug.apk - /test_cases/App.test.js
2020-08-12T14:05:07.217Z INFO @wdio/cli:launcher: Run onComplete hook
2020-08-12T14:05:07.217Z DEBUG @wdio/appium-service: Appium (pid: 10740) killed

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:02 

2020-08-12T14:05:07.218Z INFO @wdio/local-runner: Shutting down spawned worker
2020-08-12T14:05:07.473Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-08-12T14:05:07.473Z INFO @wdio/local-runner: shutting down
npm ERR! Test failed.  See above for more details.

**Comment by Xotabu4** [comment]
Duplicate of #5725 ?
