### ISSUE TITLE
ERROR @wdio/runner: Error: Failed to create session : please any one help me

### ISSUE THREAD

**Issue by vikash90** [webdriverio/webdriverio#5725]
exports.config = {
    services: ['appium'],
    port: 4723,
    runner: 'local',
    specs: [
        './test_cases/**/*.js'
    ],
    capabilities: [{
        maxInstances: 1,
        appiumVersion: '1.18.0',
        platformName: 'Android',
        platformVersion: '9',
        deviceName: 'emulator-5554',
        app: '/Users/apple/Desktop/LoginDemo/android/app/build/outputs/apk/debug/app-debug.apk',
        automationName: 'UiAutomator2'
    }],
    logLevel: 'trace',
    bail: 0,
    waitforTimeout: 50000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
}

**Comment by christian-bromann** [comment]
Without any logs it is impossible to make any assumptions. Please use the issue template properly otherwise it is impossible to help.

**Comment by Chiaro-K** [comment]
You need to add 'chromedriver' (or the equivilent) to your services

**Comment by wildintu** [comment]
I am running into this error as well:

Failed to create session.
The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource
[0-2] FAILED in /Users/airship/Desktop/appium-boilerplate/app-release.apk - /tests/sample.test.js

**Comment by anarra27** [comment]
Can someone please let me know if you guys have any solution for the above problem. I came across the same issue when I run it gitlab cicd. Attached my .gitlab-ci.yml and the error from gitlab.
![Screen Shot 2022-01-20 at 6 55 15 PM](https://user-images.githubusercontent.com/95826918/150451625-d5aa817b-9f68-453e-a40d-6847cf10fafa.png)
<img width="1189" alt="Screen Shot 2022-01-20 at 6 56 18 PM" src="https://user-images.githubusercontent.com/95826918/150451770-b8d121af-fa52-47e0-9e0c-bcaf5727431e.png">

.

**Comment by anabeatrizzz** [comment]
@christian-bromann I'm facing the same error. My logs:
```bash
[0-0] 2022-06-02T14:20:42.373Z ERROR webdriver: RequestError: read ECONNRESET
[0-0]     at ClientRequest.<anonymous> (C:\Users\ana.melo\Documents\my-app\node_modules\got\dist\source\core\index.js:970:111)
[0-0]     at Object.onceWrapper (node:events:642:26)
[0-0]     at ClientRequest.emit (node:events:539:35)
[0-0]     at ClientRequest.emit (node:domain:475:12)
[0-0]     at ClientRequest.origin.emit (C:\Users\ana.melo\Documents\my-app\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
[0-0]     at Socket.socketErrorListener (node:_http_client:454:9)
[0-0]     at Socket.emit (node:events:527:28)
[0-0]     at Socket.emit (node:domain:475:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:157:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[0-0]     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
[0-0] 2022-06-02T14:20:42.374Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] read ECONNRESET
[0-0]     at startWebDriverSession (C:\Users\ana.melo\Documents\my-app\node_modules\webdriver\build\utils.js:72:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Function.newSession (C:\Users\ana.melo\Documents\my-app\node_modules\webdriver\build\index.js:46:45)
[0-0]     at async remote (C:\Users\ana.melo\Documents\my-app\node_modules\webdriverio\build\index.js:77:22)
[0-0]     at async Runner._startSession (C:\Users\ana.melo\Documents\my-app\node_modules\@wdio\runner\build\index.js:223:56)
[0-0]     at async Runner._initSession (C:\Users\ana.melo\Documents\my-app\node_modules\@wdio\runner\build\index.js:176:25)
[0-0]     at async Runner.run (C:\Users\ana.melo\Documents\my-app\node_modules\@wdio\runner\build\index.js:88:19)
2022-06-02T14:20:42.532Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in C:\Users\ana.melo\Downloads\app.apk - C:\Users\ana.melo\Documents\my-app\test\specs\login.test.js
2022-06-02T14:20:42.536Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-06-02T14:20:42.540Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
2022-06-02T14:20:42.541Z INFO @wdio/cli:launcher: Run onComplete hook
2022-06-02T14:20:42.542Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:08

2022-06-02T14:20:42.544Z INFO @wdio/local-runner: Shutting down spawned worker
2022-06-02T14:20:42.798Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-06-02T14:20:42.798Z INFO @wdio/local-runner: shutting down
```
