### ISSUE TITLE
Browser.mock is not a function

### ISSUE THREAD

**Issue by wbigno** [webdriverio/webdriverio#5726]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/master/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.4
 - **Mode:* dev tools
 - **If WDIO Testrunner, running sync/async:** Sync true
 - **Node.js version:** 12
 - **NPM version:** 6
 - **Browser name and version:** Chrome 83
 - **Platform name and version:** Windows 7
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
Copied the script from webdriverio sight for the mock.respond, just changed URL’s and rest api I wanted to mock, when I run the test, it opens the browser. Then throws the error browser.mock is not a function

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by JohnMMcD** [comment]
The first problem is that the webdriver-mock-service is not installed by default. You have to run this command after the `npm i --save-dev @wdio/cli` step:

`npm i --save-dev @wdio/webdriver-mock-service `

The second problem, based on the error message,

```
[0-1] 2020-08-21T02:06:48.039Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): C:\path_to_wdio\test\specs\mock1.js
 Error:  TypeError: browser.mock is not a function
    at Object.<anonymous> (C:\path_to_wdio\test\specs\mock1.js:1:22)
	...

```

is that you'll have to modify the 'before' hook in `wdio.conf.js`, which is on line 180. That said, I don't know what to modify it to. The mock function seems to be initialized in `C:\path_to_wdio\node_modules\@wdio\webdriver-mock-service\build\index.js` but I don't know how to incorporate this file into the `wdio.conf.js`.

**Comment by JohnMMcD** [comment]
Thanks for looking at it, Christian. Here's an example:
```
mkdir wdio64 && cd wdio64
npm init -y
npm i --save-dev @wdio/cli
npx wdio config -y
mkdir -p ./test/specs
# This is the first line of the script at https://webdriver.io/blog/2020/07/10/network-primitives.html 
echo "const mock = browser.mock('https://todo-backend-express-knex.herokuapp.com/')" > test/specs/mock1.js
# To get rid of unrelated errors
rm test/specs/example.e2e.js 
npx wdio wdio.conf.js

Execution of 1 spec files started at 2020-08-23T17:36:55.963Z

2020-08-23T17:36:55.988Z INFO @wdio/cli:launcher: Run onPrepare hook
Starting ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2020-08-23T17:36:56.645Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-08-23T17:36:56.646Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2020-08-23T17:36:57.328Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-08-23T17:36:57.340Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] 2020-08-23T17:36:57.566Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): C:\path_to\wdio64\test\specs\mock1.js
 Error:  TypeError: browser.mock is not a function
    at Object.<anonymous> (C:\path_to\wdio64\test\specs\mock1.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at C:\path_to\wdio64\node_modules\mocha\lib\mocha.js:390:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\path_to\wdio64\node_modules\mocha\lib\mocha.js:387:14)
[0-0] RUNNING in chrome - C:\path_to\wdio64\test\specs\mock1.js
[0-0] 2020-08-23T17:36:57.598Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-08-23T17:36:57.601Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2020-08-23T17:36:57.601Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-0] 2020-08-23T17:37:02.431Z INFO webdriver: COMMAND deleteSession()
[0-0] 2020-08-23T17:37:02.431Z INFO webdriver: [DELETE] http://localhost:9515/session/93826324b099d2ae8f702cf92603cd6d
[0-0] PASSED in chrome - C:\path_to\wdio64\test\specs\mock1.js
2020-08-23T17:37:02.601Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      1 passed, 1 total (100% completed) in 00:00:06

2020-08-23T17:37:02.602Z INFO @wdio/local-runner: Shutting down spawned worker
2020-08-23T17:37:02.854Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-08-23T17:37:02.854Z INFO @wdio/local-runner: shutting down

```

**Comment by christian-bromann** [comment]
@JohnMMcD you can only use API commands within `it` blocks.

For example, this is __wrong__:
```js
const mock = browser.mock('https://todo-backend-express-knex.herokuapp.com/')

describe("my feature", () => {
  it("should do things", () => {
     // ...
  })
})
```

and should be written as follows:

```js
describe("my feature", () => {
  let mock;

  before(() => {
    mock = browser.mock('https://todo-backend-express-knex.herokuapp.com/')
  })

  it("should do things", () => {
     // ...
  })
})
```

Please let me know if there are any further questions!

**Comment by JohnMMcD** [comment]
No further questions, thanks for the explanation!

For those folks who might benefit from seeing a complete file that could be dropped into the test/specs directory, here is one:

```
describe("my feature", () => {
  let mock;

  before(() => {
    mock = browser.mock('https://todo-backend-express-knex.herokuapp.com/')
	
    mock.respond([{
        title: 'Injected (non) completed Todo',
        order: null,
        completed: false
    }, {
        title: 'Injected completed Todo',
        order: null,
        completed: true
    }])
	
  })

  it("mock test", () => {
    browser.url('https://todobackend.com/client/index.html?https://todo-backend-express-knex.herokuapp.com/')

 	$('#todo-list li').waitForExist()
    console.log('Injected items: ' + $$('#todo-list li').map(el => el.getText()))

  })
})
```
