### ISSUE TITLE
browser.addCommand() doesn't work WebdriverIO 6 + Typescript

### ISSUE THREAD

**Issue by bersh92** [webdriverio/webdriverio#5731]
**Environment**
 - WebdriverIO version: 6.4.0
 - WDIO Testrunner]
 - Mode sync
 - Node.js version: 14.7.0
 - NPM version: 6.14.7
 - Browser name: Chrome, version: 84.0.4147.105 
 - Mac OS version: 10.15.6

wdio.conf.js file:
```
before: function (capabilities, specs) {
        browser.addCommand("waitAndClick", function () {
        this.waitForDisplayed({timeout: 5000})
        this.click()
     }, true)
 }
```

wdio.d.ts file:
```
declare module WebdriverIO {
    interface Element {
        waitAndClick: () => void
    }
}
```

ts.confg file:

```{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*": [ "./*" ],
      "src/*": ["./src/*"]
    },
    "typeRoots": [
      "./test/types"
    ],
    "types": ["node", "@wdio/sync", "@wdio/mocha-framework"]
  },
  "include": [
    "./test/**/*.ts"
  ]
} 
```

call it like:

`$('.classname').waitAndClick();`

**Describe the bug**
while running my test I am getting the error:
`[0-0]  Error:  ⨯ Unable to compile TypeScript:
test/specs/basic.ts(4,23): error TS2339: Property 'waitAndClick' does not exist on type 'Element'.
`

**To Reproduce**
- Create a new project follow the instructions from here: https://webdriver.io/docs/gettingstarted.html
- Set up TypeScript and add the custom command, follow instructions from here: https://webdriver.io/docs/typescript.html#typed-configuration

**Expected behavior**
Should not fail with an "Unable to compile TypeScript" error

**Similar project structure here**
https://github.com/bersh92/wdio.addCommand

**Log**

Execution of 1 spec files started at 2020-08-15T10:45:18.473Z

2020-08-15T10:45:18.499Z INFO @wdio/cli:launcher: Run onPrepare hook
Starting ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
2020-08-15T10:45:18.624Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-08-15T10:45:18.625Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2020-08-15T10:45:18.933Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-08-15T10:45:18.939Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] 2020-08-15T10:45:20.411Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): /Users/admin/WebstormProjects/wdio/webdriverio-test/test/specs/basic.ts
 Error:  TSError: ⨯ Unable to compile TypeScript:
test/specs/basic.ts(4,23): error TS2339: Property 'waitAndClick' does not exist on type 'Element'.

    at createTSError (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
[0-0] RUNNING in chrome - /test/specs/basic.ts
[0-0] 2020-08-15T10:45:20.450Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-08-15T10:45:20.451Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2020-08-15T10:45:20.451Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
}
[0-0] 2020-08-15T10:45:22.574Z ERROR @wdio/runner: TSError: ⨯ Unable to compile TypeScript:
test/specs/basic.ts(4,23): error TS2339: Property 'waitAndClick' does not exist on type 'Element'.

    at createTSError (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:434:12)
    at reportTSError (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:438:19)
    at getOutput (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:578:36)
    at Object.compile (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:775:32)
    at Module.m._compile (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:858:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/admin/WebstormProjects/wdio/webdriverio-test/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
[0-0]  Error:  ⨯ Unable to compile TypeScript:
test/specs/basic.ts(4,23): error TS2339: Property 'waitAndClick' does not exist on type 'Element'.

[0-0] 2020-08-15T10:45:22.577Z INFO webdriver: COMMAND deleteSession()
[0-0] 2020-08-15T10:45:22.577Z INFO webdriver: [DELETE] http://localhost:9515/session/7a784134a3b19b4310a7bc6b35cc67bf
[0-0] FAILED in chrome - /test/specs/basic.ts
2020-08-15T10:45:22.766Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:04 

2020-08-15T10:45:22.767Z INFO @wdio/local-runner: Shutting down spawned worker
2020-08-15T10:45:23.021Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-08-15T10:45:23.022Z INFO @wdio/local-runner: shutting down
admin@MacBook-Pro-Admin webdriverio-test %

**Comment by hieuxlu** [comment]
I think I replied to this on gitter, you need to add `wdio.d.ts` to `types` property in `tsconfig.json`.
```diff
-      "types": ["node", "@wdio/sync", "@wdio/mocha-framework"]
+      "types": ["node", "@wdio/sync", "@wdio/mocha-framework", "./wdio"]
```

I have the same code as you do and it should work after this change.

**Comment by bersh92** [comment]
@hieuxlu Thank you, now it's clear, finally, I can continue with my tests, I think it would be great to add this to the documentation

**Comment by hieuxlu** [comment]
Great to hear that. This is more like a Typescript specific recipe/boilerplate, and not really related to wdio. But I agree that we can do better, by simply adding a boilerplate wdio typescript reference repo in the Typescript page on wdio documentation site, and add sample for custom command use case for Typescript.

@christian-bromann What do you think?

**Comment by christian-bromann** [comment]
> @christian-bromann What do you think?

@hieuxlu sounds good to me. You want to take a stab at it?

**Comment by hieuxlu** [comment]
@christian-bromann There's already been one on wdio boilerplate page, so I will not reinvent the wheel. https://webdriver.io/docs/boilerplate.html#pako88wdio-mocha-typescripthttpsgithubcompako88wdio-mocha-typescript
@bersh92 FYI.

**Comment by christian-bromann** [comment]
@hieuxlu I think it would be useful to have a small section on our TypeScript documentation page explaining how you can extend the types (like in [this example](https://github.com/bersh92/wdio.addCommand/blob/master/test/types/wdio.d.ts)) when you create custom commands.

**Comment by christian-bromann** [comment]
Created an issue for that: #5766
