### ISSUE TITLE
Cucumber tag expressions in wdio.config not accepting array of tag strings, contrary to documentation

### ISSUE THREAD

**Issue by osmolyar** [webdriverio/webdriverio#5752]
**Environment (please complete the following information):**
    **WebdriverIO version: 6.0.15
    **Mode: Wdio testrunner (npx wdio conf.js)
    **If WDIO Testrunner, running sync/async: Sync
    **Node.js version: 12.9.0
    **NPM version: 6.14.4
    **Browser name and version: Chrome 83
    **Platform name and version:. Windows 10
    **Additional wdio packages used (if applicable): , @wdio/cucumber-framework

**Config of WebdriverIO**
An example of how you configured WebdriverIO config:
tagExpression: '@Sanity and not @Pending',  => Works
tagExpression: ['@Sanity', 'not @Pending'] => doesn't work
tagExpression: ['@Sanity', '@Pending'] => doesn't work

**Describe the bug**
Although the testrunner configuration says the following under cucumberOpts

tagExpression: [],  // <string[]> (expression) only execute the features or scenarios with tags matching the expression

when one of the above string arrays is provided, the following error occurs:

Error: wdio/local-runner: Failed launching test session: TypeError: expr.charAt is not a function
    at tokenize (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\cucumber-tag-expressions\src\tag_expression_parser.ts:86:20)
    at parse (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\cucumber-tag-expressions\src\tag_expression_parser.ts:23:18)
    at new PickleFilter (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\cucumber\lib\pickle_filter.js:28:68)
    at CucumberAdapter.init (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\@wdio\cucumber-framework\build\index.js:59:28)    at Object.adapterFactory.init (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\@wdio\cucumber-framework\build\index.js:288:34)
    at Runner.run (C:\osmolyar_qdtools\qdtools\selenium\webdriverio\cucumber-template-project_v6\node_modules\@wdio\runner\build\index.js:76:43)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

tagExpression: '@Sanity,@Pending' doesn't work either.

**To Reproduce**
As above

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by mgrybyk** [comment]
Hello,

The `tagExpression` accepts string only, it looks like the doc have to be updated.

We would appreciate any help on this so please help us out! Have a look at our contributing guidelines and reach out if you have any questions. Cheers!

**Comment by osmolyar** [comment]
Ok, I'll take a look.
