### ISSUE TITLE
Example using babel to run tests

### ISSUE THREAD

**Issue by michaelBenin** [webdriverio/webdriverio#577]
It would be awesome if there was an example that ran tests using babel.

**Comment by christian-bromann** [comment]
Why would you want to do that?

**Comment by michaelBenin** [comment]
Basically the same reasons you would want to use coffeescript except it's also future proofing your code. 

It's growing in popularity among open source. 

IMO it's much cleaner and debugging is good with sourcemaps. 

This is coming from someone who disliked coffeescript.

**Comment by michaelBenin** [comment]
I'm giving this a whirl today. I'll report my findings or make a pr if it's ok with you.

**Comment by christian-bromann** [comment]
sorry but I still can not follow you. Why would you like to use sourcemaps? Why should that help in debugging things. Could you describe (as precise as possible) a usecase where Babel could help writing integrations tests in node?

**Comment by michaelBenin** [comment]
Aside from babel, I'm actually running into multiple issues running webdriver.io.

I'm using selenium-standalone installed globally. 

When I clone this repo, npm install, npm install selenium-standalone -g, selenium-standalone install, selenium-standalone start, npm run test-desktop

it errors out and I get the following output from selenium:

```
Admins-MacBook-Pro:acceptance-testing-example mbenin$ selenium-standalone start
15:03:44.662 INFO - Launching a standalone server
Setting system property webdriver.chrome.driver to /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver
15:03:44.691 INFO - Java: Oracle Corporation 25.45-b02
15:03:44.692 INFO - OS: Mac OS X 10.10.3 x86_64
15:03:44.698 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
15:03:44.754 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: MAC
15:03:44.777 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
15:03:44.778 INFO - Version Jetty/5.1.x
15:03:44.778 INFO - Started HttpContext[/selenium-server,/selenium-server]
15:03:44.795 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@d7b1517
15:03:44.795 INFO - Started HttpContext[/wd,/wd]
15:03:44.795 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
15:03:44.795 INFO - Started HttpContext[/,/]
15:03:44.798 INFO - Started SocketListener on 0.0.0.0:4444
15:03:44.798 INFO - Started org.openqa.jetty.jetty.Server@7cd84586
Selenium started
15:03:55.511 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
15:03:55.518 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
Starting ChromeDriver 2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f) on port 48119
Only local connections are allowed.
15:04:15.696 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.247', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:109)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:110)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:172)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.247', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
	... 9 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.247', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:593)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
	... 14 more
Caused by: java.lang.IllegalStateException: The process has not exited yet therefore no result is available ...
	at org.apache.commons.exec.DefaultExecuteResultHandler.getException(DefaultExecuteResultHandler.java:74)
	at org.openqa.selenium.os.UnixProcess.checkForError(UnixProcess.java:165)
	at org.openqa.selenium.os.CommandLine.checkForError(CommandLine.java:183)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:170)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:62)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	... 19 more
15:04:15.700 WARN - Exception: The process has not exited yet therefore no result is available ...
15:04:15.717 INFO - Executing: org.openqa.selenium.remote.server.handler.GetAllSessions@7df3def7)
15:04:15.718 INFO - Done: org.openqa.selenium.remote.server.handler.GetAllSessions@7df3def7
```

Also the output from the test runner:

```
> webdriverio@2.4.5 test-desktop /Users/mbenin/Projects/webdriverio
> _ENV=desktop _BROWSER=chrome node ./test/runner.js



  addValue
    1) "before all" hook

  0 passing (20s)
  1 failing

  1) addValue "before all" hook:
     Uncaught RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: The process has not exited yet therefore no result is available ...

     Callstack:
     -> init()

  




npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/mbenin/.nvm/versions/node/v0.12.4/bin/npm" "run" "test-desktop"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE
npm ERR! webdriverio@2.4.5 test-desktop: `_ENV=desktop _BROWSER=chrome node ./test/runner.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webdriverio@2.4.5 test-desktop script '_ENV=desktop _BROWSER=chrome node ./test/runner.js'.
npm ERR! This is most likely a problem with the webdriverio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     _ENV=desktop _BROWSER=chrome node ./test/runner.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls webdriverio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mbenin/Projects/webdriverio/npm-debug.log
```

I'm using Mac Yosemite, node v0.12.4.

Is there a specific version of selenium I need to install?

**Comment by christian-bromann** [comment]
`org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException` always indicates that it can't find the binary file, e.g. if you want to run chrome, you have to have Chromedriver installed on your machine. Same goes for PhantomJS

**Comment by michaelBenin** [comment]
Thanks for the quick response!

**Comment by michaelBenin** [comment]
Hey so I did:

brew install chromedriver

Started up the selenium-standalone. 

Copied this example, ran it. 

```
var webdriverio = require('webdriverio'),
  assert = require('assert');

var client = webdriverio.remote({
  desiredCapabilities: {
    browserName: 'chrome'
  }
});
client.init();


client
  .url('https://github.com/')
  .getElementSize('.header-logo-wordmark', function (err, result) {
    assert(err === undefined);
    assert(result.height === 26);
    assert(result.width === 37);
  })
  .getTitle(function (err, title) {
    assert(err === undefined);
    assert(title === 'GitHub · Build software better, together.');
  })
  .getCssProperty('a[href="/plans"]', 'color', function (err, result) {
    assert(err === undefined);
    assert(result.value === 'rgba(65,131,196,1)');
  })
  .end();
```

```
Admins-MacBook-Pro:acceptance-testing-example mbenin$ node test.js

/Users/mbenin/Projects/playground/acceptance-testing-example/node_modules/webdriverio/lib/utils/PromiseHandler.js:154
                throw error;
                      ^
RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.

```

Not really sure what the issue is here. I followed the steps from the gulp blog post in the readme, tried using the grunt webdriver task which I used a year ago and had working well.

**Comment by michaelBenin** [comment]
Made it even simpler:

```
var webdriverio = require('webdriverio');
var options = {
  desiredCapabilities: {
    browserName: 'chrome'
  }
};

var client = webdriverio.remote(options);

client
  .init()
  .url('http://www.google.com')
  .getTitle()
  .then(function(title) {
    console.log('Title was: ' + title);
  })
  .catch(function(error) {
    console.log('uups something went wrong', error);
  })
  .end();
```

on node v0.12.4

brew install chromedriver
npm i selenium-standalone -g
selenium-standalone install
selenium-standalone start
node test.js

**Comment by christian-bromann** [comment]
@michaelBenin could you paste in the Selenium logs?

**Comment by michaelBenin** [comment]
```
Admins-MacBook-Pro:acceptance-testing-example mbenin$ selenium-standalone start
17:29:45.276 INFO - Launching a standalone server
Setting system property webdriver.chrome.driver to /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver
17:29:45.305 INFO - Java: Oracle Corporation 25.45-b02
17:29:45.305 INFO - OS: Mac OS X 10.10.3 x86_64
17:29:45.311 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
17:29:45.368 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: MAC
17:29:45.391 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
17:29:45.392 INFO - Version Jetty/5.1.x
17:29:45.392 INFO - Started HttpContext[/selenium-server,/selenium-server]
17:29:45.412 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@d7b1517
17:29:45.412 INFO - Started HttpContext[/wd,/wd]
17:29:45.412 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
17:29:45.412 INFO - Started HttpContext[/,/]
17:29:45.415 INFO - Started SocketListener on 0.0.0.0:4444
17:29:45.415 INFO - Started org.openqa.jetty.jetty.Server@7cd84586
Selenium started
^C17:30:15.099 INFO - Shutting down...

```

**Comment by michaelBenin** [comment]
Is selenium-standalone using Windows?

**Comment by michaelBenin** [comment]
Ok I verified this works on firefox. 

This is an issue with selenium-standalone.

**Comment by michaelBenin** [comment]
Ok back to my babel testing with this, using firefox...

Thanks for looking over this with me. I want to help make this stable and create a boiler plate repo from the link in the readme.

**Comment by michaelBenin** [comment]
FYI this is working with babel.

**Comment by michaelBenin** [comment]
Just wanted to update this issue, I was able to get this working with chrome on my personal computer following the installation steps, this is only happening on my work computer which is a brand new macbook air. 

Anyone else having this same issue can follow it here:

https://github.com/SeleniumHQ/selenium/issues/702
