### ISSUE TITLE
TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by binarykitchen** [webdriverio/webdriverio#578]
this stack trace explains

```js
Message:
    Cannot read property 'value' of null
Details:
    domain: [object Object]
    domainThrown: true
Stack:
TypeError: Cannot read property 'value' of null
  at /home/michael-heuberger/Development/xxx-frontend/node_modules/webdriverio/lib/commands/getText.js:79:27
  at Array.map (native)
  at /home/michael-heuberger/Development/xxx-frontend/node_modules/webdriverio/lib/commands/getText.js:78:44
  at /home/michael-heuberger/Development/xxx-frontend/node_modules/webdriverio/node_modules/async/lib/async.js:148:21
  at Chain.<anonymous> (/home/michael-heuberger/Development/xxx-frontend/node_modules/webdriverio/lib/commands/getText.js:64:21)
  at Chain.<anonymous> (/home/michael-heuberger/Development/xxx-frontend/node_modules/webdriverio/lib/utils/PromiseHandler.js:152:26)
  at /home/michael-heuberger/Development/xxx-frontend/node_modules/webdriverio/node_modules/chainit/index.js:137:22
  at RequestHandler.<anonymous> (/home/michael-heuberger/Development/xxx-frontend/node_modules/webdriverio/lib/utils/RequestHandler.js:223:13)
  at Request.self.callback (/home/michael-heuberger/Development/xxx-frontend/node_modules/webdriverio/node_modules/request/request.js:121:22)
```

happens with the latest version on npm

**Comment by christian-bromann** [comment]
Seems that Selenium returned nothing. About to publish `v3` this week where this gets obsolete. Sorry if I don't have any immediate solution.

**Comment by binarykitchen** [comment]
If you publish that this week, then I'm cool with this.
