### ISSUE TITLE
WebdriverIO tests cannot run in safari and chrome (OSX)

### ISSUE THREAD

**Issue by michaelBenin** [webdriverio/webdriverio#579]
Mac:  10.10.3 (14D2134)
Safari: Version 8.0.6 (10600.6.3)

```
Admins-MacBook-Pro:Desktop mbenin$ selenium-standalone start
10:08:52.173 INFO - Launching a standalone server
Setting system property webdriver.chrome.driver to /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver
10:08:52.203 INFO - Java: Oracle Corporation 25.45-b02
10:08:52.203 INFO - OS: Mac OS X 10.10.3 x86_64
10:08:52.210 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
10:08:52.267 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: MAC
10:08:52.291 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
10:08:52.292 INFO - Version Jetty/5.1.x
10:08:52.293 INFO - Started HttpContext[/selenium-server,/selenium-server]
10:08:52.309 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@d7b1517
10:08:52.309 INFO - Started HttpContext[/wd,/wd]
10:08:52.309 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
10:08:52.309 INFO - Started HttpContext[/,/]
10:08:52.312 INFO - Started SocketListener on 0.0.0.0:4444
10:08:52.312 INFO - Started org.openqa.jetty.jetty.Server@7cd84586
Selenium started
10:08:56.562 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=safari, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
10:08:56.569 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, browserName=safari, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
10:08:56.616 INFO - Server started on port 43961
10:08:56.624 INFO - Launching Safari
10:08:56.632 INFO - Waiting for SafariDriver to connect
10:09:06.631 INFO - Shutting down
10:09:06.632 INFO - Stopping Safari
10:09:06.685 INFO - Stopping server
10:09:06.685 INFO - Stopping server
10:09:06.690 INFO - Shutdown complete
10:09:06.691 INFO - Shutting down
10:09:06.691 INFO - Stopping server
10:09:06.691 INFO - Shutdown complete
10:09:06.692 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:109)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:110)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:172)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
	... 9 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10059 ms
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: SafariDriver
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.start(SafariDriverCommandExecutor.java:121)
	at org.openqa.selenium.safari.SafariDriver.startClient(SafariDriver.java:72)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:58)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:51)
	... 14 more
10:09:06.696 WARN - Exception: Failed to connect to SafariDriver after 10059 ms
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: SafariDriver
```

![screen shot 2015-06-19 at 10 07 45 am](https://cloud.githubusercontent.com/assets/521971/8255089/8296b47e-166b-11e5-8774-5cc5ec6fff0b.png)

**Comment by michaelBenin** [comment]
This is how I'm running my test.

I tried this with both the npm selenium-standalone as well as the downloaded jar.

```
var webdriverio = require('webdriverio');
var expect  = require('chai').expect;

describe('FastCompany Homepage Title Test', function() {

  this.timeout(99999999);
  var client = {};

  before(function(done) {

    client = webdriverio.remote({

      desiredCapabilities: {
        browserName: 'safari'
      }

    });

    client.init(done);

  });

  it('FastCompany homepage title.', function (done) {
    client
      .url('http://www.fastcompany.com/')
      .getTitle(function(err, title) {
        expect(title).to.equal('Fast Company | Business + Innovation')
      })
      .call(done);
  });

  after(function(done) {
    client.end(done);
  });
});
```


It's run through gulp:

```
var gulp = require('gulp');
var mocha = require('gulp-mocha');

gulp.task('test', function() {
  return gulp.src(['src/tests/**/*.js'], {
    read: false
  })
    .pipe(mocha());
});
```

**Comment by michaelBenin** [comment]
Chrome Specs:

Chrome: Version 43.0.2357.124 (64-bit)

Output: 

```
Admins-MacBook-Pro:Desktop mbenin$ selenium-standalone start
10:25:17.405 INFO - Launching a standalone server
Setting system property webdriver.chrome.driver to /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver
10:25:17.435 INFO - Java: Oracle Corporation 25.45-b02
10:25:17.435 INFO - OS: Mac OS X 10.10.3 x86_64
10:25:17.442 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
10:25:17.500 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: MAC
10:25:17.522 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
10:25:17.523 INFO - Version Jetty/5.1.x
10:25:17.524 INFO - Started HttpContext[/selenium-server,/selenium-server]
10:25:17.539 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@d7b1517
10:25:17.540 INFO - Started HttpContext[/wd,/wd]
10:25:17.540 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
10:25:17.540 INFO - Started HttpContext[/,/]
10:25:17.543 INFO - Started SocketListener on 0.0.0.0:4444
10:25:17.543 INFO - Started org.openqa.jetty.jetty.Server@7cd84586
Selenium started
10:25:23.663 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
10:25:23.670 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
Starting ChromeDriver 2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f) on port 35078
Only local connections are allowed.
10:25:43.852 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:109)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:110)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:172)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
	... 9 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:593)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
	... 14 more
Caused by: java.lang.IllegalStateException: The process has not exited yet therefore no result is available ...
	at org.apache.commons.exec.DefaultExecuteResultHandler.getException(DefaultExecuteResultHandler.java:74)
	at org.openqa.selenium.os.UnixProcess.checkForError(UnixProcess.java:165)
	at org.openqa.selenium.os.CommandLine.checkForError(CommandLine.java:183)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:170)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:62)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	... 19 more
10:25:43.855 WARN - Exception: The process has not exited yet therefore no result is available ...
```

**Comment by christian-bromann** [comment]
Stuff like this is never caused by WebdriverIO as it only uses the interface Selenium provides. So my guess here is that your safaridriver version is not working well together with the Selenium standalone server. I would try to update both and run again. I know that I had the same problems starting with v2.45

**Comment by michaelBenin** [comment]
I'll try to downgrade to selenium 2.44.

Why is this not addressed in the Readme? 

Do you know when this last ran successfully and under what versions? 

How are people going to use this tool when it doesn't run from the instructions in the readme? 

How can you expect adoption when the tools this project relies on are unstable? 

How can I help?

**Comment by michaelBenin** [comment]
I spent half a day debugging chrome because I followed the instructions in the readme. I'm trying to save other people time who are trying to use this on a mac.

**Comment by michaelBenin** [comment]
"I know that I had the same problems starting with v2.45"

Than why not put this in the documentation?

**Comment by michaelBenin** [comment]
Verfied same issue with version 2.39.0, testing it with an older version of chromedriver now.

**Comment by christian-bromann** [comment]
> Than why not put this in the documentation?

Because these bugs happen and I can't check each driver version if they still working. This is part of the Selenium project not WebdriverIO. It's not the scope of WebdriverIO do deal with those problems.

Maybe these threads will help you out. Apparently it got fixed 10days ago.
https://code.google.com/p/selenium/issues/detail?id=7933
https://github.com/SeleniumHQ/selenium/issues/631

**Comment by michaelBenin** [comment]
OK I've got safari down, this needed to be installed as an extension:

http://selenium-release.storage.googleapis.com/2.45/SafariDriver.safariextz

It's good with selenium 2.45

Can I make a pr with some docs to help other people like me?

**Comment by michaelBenin** [comment]
I'm saying when a new release comes out, we need to have stable versions for people to use.

**Comment by michaelBenin** [comment]
I'm really close to getting chrome down for mac users:

Any help would be greatly appreciated. 

```
Admins-MacBook-Pro:.selenium mbenin$ selenium-standalone start --version=2.45.0 --drivers.chrome.version=2.15
16:29:17.084 INFO - Launching a standalone server
Setting system property webdriver.chrome.driver to /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver
16:29:17.113 INFO - Java: Oracle Corporation 25.45-b02
16:29:17.113 INFO - OS: Mac OS X 10.10.3 x86_64
16:29:17.120 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
16:29:17.176 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match with current platform: MAC
16:29:17.200 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
16:29:17.200 INFO - Version Jetty/5.1.x
16:29:17.201 INFO - Started HttpContext[/selenium-server,/selenium-server]
16:29:17.223 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@d7b1517
16:29:17.223 INFO - Started HttpContext[/wd,/wd]
16:29:17.223 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
16:29:17.223 INFO - Started HttpContext[/,/]
16:29:17.227 INFO - Started SocketListener on 0.0.0.0:4444
16:29:17.227 INFO - Started org.openqa.jetty.jetty.Server@7cd84586
Selenium started
16:31:06.012 INFO - Executing: [new session: Capabilities [{rotatable=true, locationContextEnabled=true, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]])
16:31:06.020 INFO - Creating a new session for Capabilities [{rotatable=true, locationContextEnabled=true, browserName=chrome, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]
Starting ChromeDriver 2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f) on port 10450
Only local connections are allowed.
16:31:26.207 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:109)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:110)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:172)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
	... 9 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Admins-MacBook-Pro.local', ip: '10.197.210.108', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_45'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:593)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:171)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:139)
	... 14 more
Caused by: java.lang.IllegalStateException: The process has not exited yet therefore no result is available ...
	at org.apache.commons.exec.DefaultExecuteResultHandler.getException(DefaultExecuteResultHandler.java:74)
	at org.openqa.selenium.os.UnixProcess.checkForError(UnixProcess.java:165)
	at org.openqa.selenium.os.CommandLine.checkForError(CommandLine.java:183)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:170)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:62)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	... 19 more
16:31:26.210 WARN - Exception: The process has not exited yet therefore no result is available ...
```

**Comment by michaelBenin** [comment]
Seeing if something from this post can help me: 

http://www.kenst.com/2015/03/installing-chromedriver-on-mac-osx/

**Comment by christian-bromann** [comment]
> I'm saying when a new release comes out, we need to have stable versions for people to use.

How do you want to ensure that? WebdriverIO provides all possibilities to modify the session request in a way to can get a Selenium session running. Stuff like this is hard to handle as it behaves different on other OS systems.

What you can do is make a project like selenium-standalone (or contribute in that) so user can be sure that everything is working on their OS.

**Comment by michaelBenin** [comment]
Right now this software is unusable without knowledge of setting up the dependencies.

I would first start with looking at using npm shrinkwrap. Using this makes sure all the dependencies are always versioned off and all users are installing the same thing (npm shrinkwrap --dev). Following this principle of shrinkwrap by installing selenium, drivers, and browser extensions at specific versions, and working examples on Mac OSX Yosemite will most likely increase adoption of people using your software successfully as it will be stable and easy to set up.

**Comment by michaelBenin** [comment]
Conversation continues here:

https://github.com/vvo/selenium-standalone/issues/107

**Comment by michaelBenin** [comment]
@christian-bromann once we get this all running smoothly I will create a boiler plate project based off of http://twin.github.io/selenium-testing-workflow-with-webdriverio/ but works with locked down dependencies and clear instructions for OSX Yosemite then later on Ubuntu and Windows.

**Comment by christian-bromann** [comment]
Sounds good @michaelBenin :+1:

**Comment by michaelBenin** [comment]
BTW - this worked great with saucelabs, awesome work!!!
