### ISSUE TITLE
Chrome not found with fresh install of Chrome 85

### ISSUE THREAD

**Issue by david-sharer** [webdriverio/webdriverio#5793]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.4.5
 - **Mode:** Testrunner
 - **If WDIO Testrunner, running sync/async:** Async
 - **Node.js version:** 12.17.0
 - **NPM version:** Using Yarn 1.22.4
 - **Browser name and version:** Chrome 85
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** 

**Config of WebdriverIO**

```js
// base.conf.js
require("dotenv").config();

exports.config = {
    custom: {
        urls: {
            www: "https://unconfigured-website/",
            strapi: "https://unconfigured-strapi/",
        },
        auth: {
            username: process.env.RETAIL_USER_NAME,
            password: process.env.RETAIL_USER_PASSWORD,
            displayedName: "test",
        },
    },

    runner: 'local',
    specs: [
        './src/**/*.spec.ts'
    ],

    suites: {
        website: [
            './src/pages/website/**/*.spec.ts'
        ],
        strapi: [
            './src/pages/strapi/**/*.spec.ts'
        ],
        warmup: [
            './src/warmup/**/*.spec.ts'
        ]
    },

    exclude: [],
    maxInstances: 1,
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
    }],
    logLevel: 'warn',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10 * 1000,
    connectionRetryTimeout: 120 * 1000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    
    framework: 'mocha',
    reporters: ['spec'],

    mochaOpts: {
        ui: 'bdd',
        timeout: 5 * 60 * 1000,
        require: 'ts-node/register',
        compilers: [
            'tsconfig-paths/register'
        ]
    },
}
```

**Describe the bug**
Chrome 85 is installed in a new location for fresh installs.  
Old installs that have been upgraded to Chrome 85 are still in the same location.

**To Reproduce**
- Install Chrome on a fresh machine
OR
- Uninstall Chrome
- Reinstall Chrome (Should get 85)

```cannot find Chrome Binary```
(full log below)

**Expected behavior**
Chrome should be found on machines where it is freshly installed.

**Log**

```log

Starting ChromeDriver 85.0.4183.38 (9047dbc2c693f044042bbec5c91401c708c7c26a-refs/branch-heads/4183@{#779}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[0-0] RUNNING in chrome - C:\_dev\<snip>\Test\src\pages\strapi\auth.spec.ts
[0-0] 2020-09-02T17:02:34.392Z WARN webdriver: Request failed with status 500 due to unknown error: cannot find Chrome binary
[0-0] 2020-09-02T17:02:34.399Z WARN webdriver: Request failed with status 500 due to unknown error: cannot find Chrome binary
[0-0] 2020-09-02T17:02:34.405Z WARN webdriver: Request failed with status 500 due to unknown error: cannot find Chrome binary
[0-0] 2020-09-02T17:02:34.410Z ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: cannot find Chrome binary
[0-0] 2020-09-02T17:02:34.410Z ERROR webdriver: unknown error: unknown error: cannot find Chrome binary
    at getErrorFromResponseBody (C:\_dev\<snip>\Test\node_modules\webdriver\build\utils.js:121:10)
    at WebDriverRequest._request (C:\_dev\<snip>\Test\node_modules\webdriver\build\request.js:149:56)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at startWebDriverSession (C:\_dev\<snip>\Test\node_modules\webdriver\build\utils.js:41:16)
    at Function.newSession (C:\_dev\<snip>\Test\node_modules\webdriver\build\index.js:44:23)
    at remote (C:\_dev\<snip>\Test\node_modules\webdriverio\build\index.js:75:20)
    at Runner._startSession (C:\_dev\<snip>\Test\node_modules\@wdio\runner\build\index.js:206:50)
    at Runner._initSession (C:\_dev\<snip>\Test\node_modules\@wdio\runner\build\index.js:175:21)
    at Runner.run (C:\_dev\<snip>\Test\node_modules\@wdio\runner\build\index.js:93:15)
[0-0]  Error:  Failed to create session.
unknown error: cannot find Chrome binary
[0-0] 2020-09-02T17:02:34.415Z ERROR @wdio/runner: Error: Failed to create session.
unknown error: cannot find Chrome binary
    at startWebDriverSession (C:\_dev\<snip>\Test\node_modules\webdriver\build\utils.js:45:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0] FAILED in chrome - C:\_dev\<snip>\Test\src\pages\strapi\auth.spec.ts
```

**Additional context**
- https://developercommunity.visualstudio.com/content/problem/1170486/selenium-ui-test-can-no-longer-find-chrome-binary.html

**Comment by christian-bromann** [comment]
@david-sharer I don't think that there is anything we can do in WebdriverIO to resolve this issue. AFAIK ChromeDriver checks for the default installation path and if Chrome was reinstalled in whatever way and moved from this path you have to provide it through the capabilities:

```js
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        'goog:chromeOptions': {
			binary: '...'
		}
    }],
```

**Comment by david-sharer** [comment]
The default installation path has changed.

**Comment by david-sharer** [comment]
The suggested manual specification of the chrome path has worked. Thanks!

Is this package the one that's responsible for locating chrome? https://github.com/giggio/node-chromedriver

**Comment by christian-bromann** [comment]
> Is this package the one that's responsible for locating chrome? [giggio/node-chromedriver](https://github.com/giggio/node-chromedriver)

yes
