### ISSUE TITLE
Log errors for isVisible

### ISSUE THREAD

**Issue by dok** [webdriverio/webdriverio#581]
.isVisible is not throwing any errors when selectors are invalid. perhaps we should make a distinction between when nothing is visible vs. the arguments passed to the method is invalid.

**Comment by christian-bromann** [comment]
@dok I tried:

```js
    it('test isVisible', function() {

        return this.client.url('http://google.com').isVisible('_#3242body').then(function(res) {
            console.log(res);
        });

    });
```

And got:

```
  1) isVisible test:
     Error: SyntaxError: DOM Exception 12
      at new ErrorHandler.RuntimeError (lib/utils/ErrorHandler.js:88:12)
      at RequestHandler.<anonymous> (lib/utils/RequestHandler.js:163:25)
      at _stream_readable.js:919:16
```

So it seems to work again in `v3`. Closing
