### ISSUE TITLE
@wdio/selenium-standalone-service : Failed to download latest version of selenium server's like  4.0.0-alpha-6 : Improper URL constructions

### ISSUE THREAD

**Issue by jagannath13** [webdriverio/webdriverio#5811]
Using latest WDIO 6.4.6

**Config of WebdriverIO**
 
 services: [["selenium-standalone", {
    logPath: './temp',
    skipSeleniumInstall: false,
    installArgs: {
      version: "4.0.0-alpha-6",
      baseURL: "https://selenium-release.storage.googleapis.com",

    },
  }]],

**Describe the bug**

2020-09-09T15:30:14.854Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Could not download https://selenium-release.storage.googleapis.com/4.0-alpha-6/selenium-server-standalone-4.0.0-alpha-6.jar
    at Request.<anonymous> (/Users/jagan/Hub/wdio6/node_modules/selenium-standalone/lib/install.js:374:21)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:486:12)
    at Request.onRequestResponse (/Users/jagan/Hub/wdio6/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at HTTPParser.parserOnIncomingClient (_http_client.js:640:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:314:20)

Continue...

**To Reproduce**

during selenium server install, wrong URL Pattern is called for latest versions of Selenium 

https://selenium-release.storage.googleapis.com/4.0-alpha-6/selenium-server-standalone-4.0.0-alpha-6.jar
**Expected behavior**
Expecting to hit URL :
https://selenium-release.storage.googleapis.com/4.0-alpha-6/selenium-server-4.0.0-alpha-6.jar

**Comment by christian-bromann** [comment]
This issue needs to be reported in the [selenium-standalone](https://github.com/vvo/selenium-standalone). There is nothing we can do in WebdriverIO to fix this.
