### ISSUE TITLE
ERROR @wdio/utils:initialiseServices: TypeError: Cannot read property 'outputDir' of undefined (@wdio/appium-service - related

### ISSUE THREAD

**Issue by janca777** [webdriverio/webdriverio#5887]
**Environment:**
 - **WebdriverIO version: ^5.16.10**
 - **Mode: WDIO Testrunner, running sync** 
 - **Node.js version: 12.16.1**
 - **NPM version: 6.13.4** 
 - **Browser name and version: Chrome 85** 
 - **Platform name and version: Windows 10**
 - **Additional wdio packages used :** 
    "@wdio/appium-service": "^6.4.7",
    "@wdio/local-runner": "^5.16.10",
    "@wdio/mocha-framework": "^5.16.10",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.16.5",
    "@wdio/sync": "^5.16.10"

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**
Error-message is displayed in log after "Execution of 1 spec files started at..."

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
ERROR @wdio/utils:initialiseServices: TypeError: Cannot read property 'outputDir' of undefined
    at new AppiumLauncher (C:\_PROJECTS\Testautomation University\appium-webdriverio-master\node_modules\@wdio\appium-service\build\launcher.js:42:46)
    at initialiseServices (C:\_PROJECTS\Testautomation University\appium-webdriverio-master\node_modules\@wdio\utils\build\initialiseServices.js:53:32)
    at Launcher.run (C:\_PROJECTS\Testautomation University\appium-webdriverio-master\node_modules\@wdio\cli\build\launcher.js:70:54)
    at launch (C:\_PROJECTS\Testautomation University\appium-webdriverio-master\node_modules\@wdio\cli\build\commands\run.js:138:19)
    at handler (C:\_PROJECTS\Testautomation University\appium-webdriverio-master\node_modules\@wdio\cli\build\commands\run.js:171:12)
    at Object.run (C:\_PROJECTS\Testautomation University\appium-webdriverio-master\node_modules\@wdio\cli\build\index.js:47:29)
    at Object.<anonymous> (C:\_PROJECTS\Testautomation University\appium-webdriverio-master\node_modules\@wdio\cli\bin\wdio.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)

**Additional context**

**Comment by christian-bromann** [comment]
You are using `@wdio\appium-service` in v6 while your whole setup is still on v5. I recommend update all packages to v6. Cheers!

**Comment by hazanh** [comment]
That does not seem to solve the problem.
