### ISSUE TITLE
Devtools service is failing to load

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#5924]
Try and load the devtools service:

runner: 'local',
  services: [ 'intercept', 'devtools' ],
  automationProtocol: 'devtools',

```
captureNetworkLogs() {       
        browser.cdp('Network', 'enable');
        browser.on('Network.responseReceived', params => {
            this.reqs.push(params.response);    
            const { timeh, timem, times } = this.getTimeForLog();
            fs.appendFileSync(`${this.customLogDataDir}/${netLog}`, `${timeh}:${timem}:${times}  time now \r\n`);
            fs.appendFileSync(`${this.customLogDataDir}/${netLog}`, `url: ${params.response.url}  statusCode: ${params.response.status}  \r\n`);
            fs.appendFileSync(`${this.customLogDataDir}/${netLog}`, `Entire response=> ${JSON.stringify(params, null, 2)} \r\n`);
        });
    }
```

get error:

```
2020-10-03T19:54:20.330Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "@wdio/devtools-service".
TypeError: Cannot read property 'requestLatencyMs' of undefined
    at Object.<anonymous> (/Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/node_modules/@wdio/devtools-service/build/constants.js:55:52)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module._compile (/Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.newLoader [as .js] (/Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/node_modules/@wdio/devtools-service/build/handler/network.js:8:18)
    at safeRequire (/Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/node_modules/@wdio/utils/build/utils.js:147:11)
    at initialisePlugin (/Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/node_modules/@wdio/utils/build/initialisePlugin.js:20:47)
    at initialiseServices (/Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/node_modules/@wdio/utils/build/initialiseServices.js:34:51)
    at initialiseWorkerService (/Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/node_modules/@wdio/utils/build/initialiseServices.js:82:22)
    at Runner.run (/Users/pmerwin/Projects/qa/WDIO-6/lib-webdriverio-nodejs-v3/node_modules/@wdio/runner/build/index.js:89:40)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I am getting this with the latest breaks all test running locally against chrome or chromium.

**Comment by mgrybyk** [comment]
@pmerwin you have to install latest lighthouse

try running `npm update`.
If that doesn't work, delete `package-lock.json` and re-install modules, it should upgrade lighthouse to 6.4.1.
Alternatively, just install `lighthouse` package and make sure the latest version is installed.

I'll raise a PR soon to set lower possible lighthouse version to 6.4.1

**Comment by pmerwin** [comment]
Its a typo mobileRegluar3G.

**Comment by pmerwin** [comment]
https://github.com/webdriverio/webdriverio/pull/5914/files

Regluar should be Regular

**Comment by pmerwin** [comment]
I am not where I can fix it , I'm sorry

**Comment by mgrybyk** [comment]
https://github.com/webdriverio/webdriverio/pull/5925

**Comment by pmerwin** [comment]
Deleting node modules will not work the typo has to be ^

**Comment by mgrybyk** [comment]
The typo was fixed in lighthouse first and that caused issues to new WebdriverIO users.
We had to fix typo on our side as well but forgot to upgrade lighthouse.

As a workaround it's enough to make sure you have the latest lighthouse version installed, which is `6.4.1`

**Comment by pmerwin** [comment]
Installing LH is not fixing it for me, I think we the the file in devtools service updated?

**Comment by pmerwin** [comment]
Reglua is is still misspelled in node_modules/@wdio/devtools-service/build/constants.js

**Comment by pmerwin** [comment]
I can confirm when I fix that file by hand it resolves the issue for me
