### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Protocol error (Fetch.continueRequest): Invalid InterceptionId

### ISSUE THREAD

**Issue by syedasadulhaq** [webdriverio/webdriverio#5936]
"@wdio/allure-reporter": "6.3.6",
    "@wdio/cli": "6.4.0",
    "@wdio/cucumber-framework": "6.4.0",
    "@wdio/devtools-service": "6.4.0",
    "@wdio/firefox-profile-service": "6.4.0",
    "@wdio/local-runner": "6.4.0",
    "@wdio/selenium-standalone-service": "6.4.0",
    "@wdio/spec-reporter": "6.4.0",
    "@wdio/sync": "6.4.0",

**Happens on chrome (85). Doesn't happen on firefox.** 

[0-11] (node:1008) UnhandledPromiseRejectionWarning: Error: Protocol error (Fetch.continueRequest): Invalid InterceptionId.
    at ***/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (***/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:207:16)
    at ***/node_modules/webdriverio/build/utils/interception/devtools.js:117:21
    at ***/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (***/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (***/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onMessage (***/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:225:18)
    at Connection._onMessage (***/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:101:25)
    at WebSocket.<anonymous> (***/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WebSocketTransport.js:13:32)
    at WebSocket.onMessage (***/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:327:22)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at Receiver.receiverOnMessage (***/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:797:20)
    at Receiver.emit (events.js:315:20)
[0-11] (node:1008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mgrybyk** [comment]
Can you please provide with reproducible example?

**Comment by mgrybyk** [comment]
Can you please provide with reproducible example?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
