### ISSUE TITLE
devtools enable performance throws error in browser.url() in 6.6.0 => @wdio/sync: TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by pmerwin** [webdriverio/webdriverio#5951]
Steps to reproduce:

Update to all latest 6.6.0 packages,
run this test, use sync mode with devtools service and devtools as automation protocol at chrome:

```
const assert = require('assert');

describe('JSON.org page', () => {
    before(() => {
        browser.enablePerformanceAudits();
    });

    it('should load within performance budget', () => {
        browser.url('http://json.org');

        // let metrics = browser.getMetrics();
        // assert.ok(metrics.speedIndex < 1500); // check that speedIndex is below 1.5ms

        // let score = browser.getPerformanceScore(); // get Lighthouse Performance score
        // assert.ok(score >= 0.99); // Lighthouse Performance score is at 99% or higher

        // $('=Esperanto').click();

        // metrics = browser.getMetrics();
        // assert.ok(metrics.speedIndex < 1500);
        // score = browser.getPerformanceScore();
        // assert.ok(score >= 0.99);
    });

    after(() => {
        browser.disablePerformanceAudits();
    });
});
```

when browser.url is called error is thrown, test times out =>

 (node:40878) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'promise' of undefined
    at TraceGatherer.onLoadEventFired (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/devtools-service/build/gatherer/trace.js:95:42)

2020-10-07T19:21:19.879Z INFO @wdio/devtools-service:TraceGatherer: Start tracing frame with url http://json.org
**2020-10-07T19:21:19.881Z ERROR @wdio/sync: TypeError: Cannot read property 'start' of undefined**
    at TraceGatherer.startTracing (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/devtools-service/build/gatherer/trace.js:44:33)
    at DevToolsService.beforeCommand (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/devtools-service/build/index.js:40:35)
    at execHook (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/executeHooksWithArgs.js:21:31)
    at /Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/executeHooksWithArgs.js:35:60
    at new Promise (<anonymous>)
    at /Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/executeHooksWithArgs.js:16:33
    at Array.map (<anonymous>)
    at Object.executeHooksWithArgs [as default] (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/executeHooksWithArgs.js:16:19)
    at Browser.runCommandHook (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/wrapCommand.js:84:45)
    at Browser.runCommandWithHooks (/Users/pmerwin/Projects/pagehealth/lib-page-health-nodejs/node_modules/@wdio/sync/build/wrapCommand.js:66:26)

My options:

{
  "capabilities": {
    "browserName": "chrome",
    "goog:chromeOptions": {
      "args": [
        "--incognito"
      ]
    }
  },
  "logLevel": "trace",
  "connectionPollInterval": 500,
  "connectionRetryCount": 3,
  "requestedCapabilities": {
    "browserName": "chrome",
    "goog:chromeOptions": {
      "args": [
        "--incognito"
      ]
    }
  },
  "automationProtocol": "devtools",
  "specs": [
    "./lib/perf-example.js"
  ],
  "exclude": [],
  "suites": {},
  "baseUrl": "https://www.qanuggets.com",
  "bail": 0,
  "waitforInterval": 500,
  "waitforTimeout": 45000,
  "framework": "mocha",
  "reporters": [
    [
      "json",
      {
        "outputDir": "./data/report"
      }
    ],
    "spec"
  ],
  "services": [
    "devtools"
  ],
  "execArgv": [],
  "maxInstances": 5,
  "maxInstancesPerCapability": 100,
  "outputDir": "./data/wdio-logs",
  "filesToWatch": [],
  "onPrepare": [],
  "onWorkerStart": [],
  "before": [
    null,
    null
  ],
  "beforeSession": [
    null,
    null
  ],
  "beforeSuite": [],
  "beforeHook": [],
  "beforeTest": [
    null
  ],
  "beforeCommand": [
    null
  ],
  "afterCommand": [
    null
  ],
  "afterTest": [
    null
  ],
  "afterHook": [],
  "afterSuite": [],
  "afterSession": [],
  "after": [],
  "onComplete": [],
  "onReload": [
    null
  ],
  "beforeFeature": [],
  "beforeScenario": [],
  "beforeStep": [],
  "afterStep": [],
  "afterScenario": [],
  "afterFeature": [],
  "logLevels": {},
  "connectionRetryTimeout": 90000
}

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by pmerwin** [comment]
I am starting on this today, any suggestions appreciatted.

**Comment by pmerwin** [comment]
The crux of the issue is here:

 log.info(`Start tracing frame with url ${url}`);
        await this.page.tracing.start({
            categories: constants_1.DEFAULT_TRACING_CATEGORIES,
            screenshots: true
        });

this.page.tracing appears to be undefined

**Comment by pmerwin** [comment]
Start tracing frame with url / => url is being passed in as a '/' ...  looking into why.

**Comment by mikrivorot** [comment]
Hi!
I have the same issue, but after *TypeError: Cannot read property 'start' of undefined*

it fails with an error *UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'promise' of undefined*

```
[0-0] (node:889) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'promise' of undefined
    at TraceGatherer.onLoadEventFired (/Users/margarita.krivorot/projects/webdriver-io-performance--error/node_modules/@wdio/devtools-service/build/gatherer/trace.js:95:42)
    at /Users/margarita.krivorot/projects/webdriver-io-performance--error/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/Users/margarita.krivorot/projects/webdriver-io-performance--error/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/Users/margarita.krivorot/projects/webdriver-io-performance--error/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onMessage (/Users/margarita.krivorot/projects/webdriver-io-performance--error/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:225:18)
    at Connection._onMessage (/Users/margarita.krivorot/projects/webdriver-io-performance--error/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:101:25)
    at WebSocket.<anonymous> (/Users/margarita.krivorot/projects/webdriver-io-performance--error/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WebSocketTransport.js:13:32)
    at WebSocket.onMessage (/Users/margarita.krivorot/projects/webdriver-io-performance--error/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:322:22)
[0-0] (node:889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[0-0] Error in "JSON.org page should load within performance budget"
Timeout of 60000ms exceeded. The execution in the test "JSON.org page should load within performance budget" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts.html). (/Users/margarita.krivorot/projects/webdriver-io-performance--error/test/specs/example_failing_performance.e2e.js)
```

Example: https://github.com/mikrivorot/webdriver-io-performance--error

**Comment by pmerwin** [comment]
Any help would be appreciated here, I could use some suggestions.

**Comment by mgrybyk** [comment]
let me fix it
