### ISSUE TITLE
wdio throws filepath error

### ISSUE THREAD

**Issue by saulshanabrook** [webdriverio/webdriverio#597]
```shell
$ npm install --global webdriverio
/usr/local/bin/wdio -> /usr/local/lib/node_modules/webdriverio/bin/wdio
webdriverio@3.0.0 /usr/local/lib/node_modules/webdriverio
├── supports-color@1.3.1
├── css-value@0.0.1
├── co@4.5.4
├── deepmerge@0.2.10
├── rgb2hex@0.1.0
├── wgxpath@1.0.0
├── q@1.3.0
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── url@0.10.3 (punycode@1.3.2, querystring@0.2.0)
├── ejs@2.3.2
├── glob@5.0.13 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@2.0.8)
├── css-parse@2.0.0 (css@2.2.1)
├── archiver@0.14.4 (buffer-crc32@0.2.5, lazystream@0.1.0, async@0.9.2, readable-stream@1.0.33, tar-stream@1.1.5, zip-stream@0.5.2, glob@4.3.5, lodash@3.2.0)
├── request@2.55.0 (caseless@0.9.0, aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@2.4.2, form-data@0.2.0, combined-stream@0.0.7, bl@0.9.4, mime-types@2.0.14, http-signature@0.10.1, tough-cookie@2.0.0, hawk@2.3.1, har-validator@1.8.0)
└── inquirer@0.8.5 (figures@1.3.5, ansi-regex@1.1.1, cli-width@1.0.1, through@2.3.7, readline2@0.1.1, chalk@1.1.0, lodash@3.10.0, rx@2.5.3)
$ wdio
/usr/local/lib/node_modules/webdriverio/lib/utils/ConfigParser.js:38
        throw new Error('addConfigFile requires filepath');
              ^
Error: addConfigFile requires filepath
    at ConfigParser.addConfigFile (/usr/local/lib/node_modules/webdriverio/lib/utils/ConfigParser.js:38:15)
    at Object.init (/usr/local/lib/node_modules/webdriverio/lib/launcher.js:10:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/webdriverio/lib/cli.js:223:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/webdriverio/bin/wdio:5:1)
$ node --version
v0.12.5
```

**Comment by saulshanabrook** [comment]
oh i see it wants a config path. sorry about this false issue....

**Comment by ronaldpetty** [comment]
@saulshanabrook can you explain your revelation here?  Others have the exact same issue, the website should either explain all required settings or shouldn't show a command.

**Comment by saulshanabrook** [comment]
So either you have to generate a new config file with `wdio config` or run the tests from an existing config file with `wdio <file name like wdio.conf.js>`. Does that make sense?
