### ISSUE TITLE
Verify `WebdriverIO.Element` exist when calling `switchToFrame`

### ISSUE THREAD

**Issue by amrsa1** [webdriverio/webdriverio#5996]
**Environment (please complete the following information):**
 - **WebdriverIO version:**6.6.4
 - **Mode:** multiremote
 - **If WDIO Testrunner, running sync/async:**sync
 - **NPM version:** 6.14.4
 - **Browser name and version:** 86.0.4240.75
 - **Platform name and version:** win10
 - **Additional wdio packages used (if applicable):** 
```
"keywords": [],
  "author": "aMr kaMel",
  "license": "ISC",
  "dependencies": {
    "@wdio/browserstack-service": "^6.6.3",
    "@wdio/cli": "^6.6.4",
    "eslint": "^7.11.0",
    "frisby": "^2.1.3",
    "wdio-chromedriver-service": "^6.0.4",
    "webdriverio": "^6.6.4"
  },
  "devDependencies": {
    "@wdio/allure-reporter": "^6.6.3",
    "@wdio/appium-service": "^6.6.3",
    "@wdio/dot-reporter": "^6.6.0",
    "@wdio/local-runner": "^6.6.4",
    "@wdio/mocha-framework": "^6.6.3",
    "@wdio/selenium-standalone-service": "^6.6.5",
    "@wdio/spec-reporter": "^6.6.3",
    "@wdio/sync": "^6.6.4",
    "@wdio/concise-reporter": "^6.6.0",
    "chai": "^4.2.0",
    "mocha": "^8.1.3"
  }
```

**Config of WebdriverIO**

```
exports.config = {
  specs: ['./src/test/specs/CrossPlatform_Suite.js'],

 // capabilities: caps.CrossCaps,
  capabilities: caps.chromeAndBs,



services: [
  ['selenium-standalone', {
      args: {
        seleniumArgs: ['-port', '4444']
      },
  }],  
  ['browserstack'],
  // ['appium',{
  //   command : 'appium',
  //   args: {
  //       debugLogSpacing: true,
  //       sessionOverride: true,
  //       port: 4728,
  //       allowInsecure:'chromedriver_autodownload'
  //   },
  // }]
],
```

**Describe the bug**
console is throwing the following error "invalid argument: 'value' must be a list (Session info: chrome=83.0.4103.106)" when using multiremote feature (browserstack + selenium)
same script working fine when using browserstack service alone or  selenium + appium 

**To Reproduce**
![image](https://user-images.githubusercontent.com/32042806/96191193-e38fa700-0f43-11eb-9781-7b24c0b8353a.png)

**Expected behavior**
shouldnt throw that error 

**Log**
![2020-10-16_00h00_17](https://user-images.githubusercontent.com/32042806/96191222-f2765980-0f43-11eb-9f68-29e023ae3980.png)

**Comment by christian-bromann** [comment]
Hey,
thanks for filing the issue. This seems indeed like bug. We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
Can you provide WebdriverIO logs?

**Comment by Amrkamel1** [comment]
@christian-bromann 

```
[0-0] 2020-10-16T18:36:20.292Z INFO webdriver: [GET] https://hub-cloud.browserstack.com/wd/hub/session/d295761d7a7c6bd6466041eea7e45bfa59f80a2f/element/0.7296777113790149-5/enabled
[0-0] 2020-10-16T18:36:20.463Z INFO webdriver: RESULT true
[0-0] 2020-10-16T18:36:20.463Z INFO webdriver: COMMAND findElement("xpath", "(//input[@type='text'])[4]")
2020-10-16T18:36:20.463Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session/d295761d7a7c6bd6466041eea7e45bfa59f80a2f/element
2020-10-16T18:36:20.464Z INFO webdriver: DATA { using: 'xpath', value: "(//input[@type='text'])[4]" }
[0-0] 2020-10-16T18:36:20.623Z INFO webdriver: RESULT { ELEMENT: '0.7296777113790149-5' }
[0-0] 2020-10-16T18:36:20.630Z INFO webdriver: COMMAND elementClear("0.7296777113790149-5")
[0-0] 2020-10-16T18:36:20.631Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session/d295761d7a7c6bd6466041eea7e45bfa59f80a2f/element/0.7296777113790149-5/clear
[0-0] 2020-10-16T18:36:20.854Z INFO webdriver: COMMAND elementSendKeys("0.7296777113790149-5", "AutomationTest")
[0-0] 2020-10-16T18:36:20.854Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session/d295761d7a7c6bd6466041eea7e45bfa59f80a2f/element/0.7296777113790149-5/value
2020-10-16T18:36:20.854Z INFO webdriver: DATA { text: 'AutomationTest' }
[0-0] 2020-10-16T18:36:21.010Z DEBUG webdriver: request failed due to status 61
[0-0] 2020-10-16T18:36:21.010Z ERROR webdriver: Request failed with status 200 due to Error: invalid argument: 'value' must be a list
  (Session info: chrome=83.0.4103.106)
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 4.1.13-101.fc21.x86_64 x86_64)
[0-0] 2020-10-16T18:36:21.013Z INFO webdriver: COMMAND takeScreenshot()
2020-10-16T18:36:21.014Z INFO webdriver: [GET] https://hub-cloud.browserstack.com/wd/hub/session/d295761d7a7c6bd6466041eea7e45bfa59f80a2f/screenshot
2020-10-16T18:36:21.014Z INFO webdriver: COMMAND takeScreenshot()
2020-10-16T18:36:21.015Z INFO webdriver: [GET] http://localhost:4444/wd/hub/session/853ca26312635f451405984ff2094c1e/screenshot
[0-0] 2020-10-16T18:36:21.318Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAAA6EAAAOCCAYAAACGY9SyAAAAAXNSR0IArs4c6...
[0-0] 2020-10-16T18:36:22.773Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAABDgAAAlgCAYAAABtGofVAACAAElEQVR4AezBC...
[0-0] Error in "Cross platform testing  Cases created on mobile app should be visible on web APP"
invalid argument: 'value' must be a list
  (Session info: chrome=83.0.4103.106)
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 4.1.13-101.fc21.x86_64 x86_64)
[0-0] 2020-10-16T18:36:22.778Z INFO webdriver: COMMAND switchContextTo("web")
2020-10-16T18:36:22.778Z INFO webdriver: COMMAND switchContext("WEBVIEW_com.mobile")
2020-10-16T18:36:22.779Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session/d295761d7a7c6bd6466041eea7e45bfa59f80a2f/context
2020-10-16T18:36:22.779Z INFO webdriver: DATA { name: 'WEBVIEW_com.mobile' }
[0-0] 2020-10-16T18:36:23.070Z INFO webdriver: RESULT null
[0-0] 2020-10-16T18:36:23.071Z INFO webdriver: COMMAND refresh()
2020-10-16T18:36:23.071Z INFO webdriver: [POST] https://hub-cloud.browserstack.com/wd/hub/session/d295761d7a7c6bd6466041eea7e45bfa59f80a2f/refresh
[0-0] 2020-10-16T18:36:23.072Z INFO webdriver: COMMAND refresh()
2020-10-16T18:36:23.072Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/853ca26312635f451405984ff2094c1e/refresh
[0-0] 2020-10-16T18:36:25.825Z ERROR @wdio/sync: HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (C:\Users\amrka\Desktop\Work\Appium-wdio\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0] 2020-10-16T18:36:25.828Z INFO webdriver: COMMAND deleteSession()
2020-10-16T18:36:25.829Z INFO webdriver: [DELETE] https://hub-cloud.browserstack.com/wd/hub/session/d295761d7a7c6bd6466041eea7e45bfa59f80a2f
2020-10-16T18:36:25.830Z INFO webdriver: COMMAND deleteSession()
2020-10-16T18:36:25.831Z INFO webdriver: [DELETE] http://localhost:4444/wd/hub/session/853ca26312635f451405984ff2094c1e
[0-0] 2020-10-16T18:36:26.094Z INFO webdriver: RESULT 
2020-10-16T18:36:26.243Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in MultiRemote - C:\Users\amrka\Desktop\Work\Appium-wdio\src\test\specs\CrossPlatform_Suite.js
2020-10-16T18:36:26.279Z INFO @wdio/cli:launcher: Run onComplete hook
2020-10-16T18:36:26.282Z INFO @wdio/selenium-standalone-service: shutting down all browsers

 "dot" Reporter:
F

 "spec" Reporter:
------------------------------------------------------------------
[MultiremoteBrowser (unknown) #0-0] Spec: C:\Users\amrka\Desktop\Work\Appium-wdio\src\test\specs\CrossPlatform_Suite.js
[MultiremoteBrowser (unknown) #0-0] Running: MultiremoteBrowser on (unknown)
[MultiremoteBrowser (unknown) #0-0]
[MultiremoteBrowser (unknown) #0-0] Cross platform testing
[MultiremoteBrowser (unknown) #0-0]    ✖ Cases created on mobile app should be visible on web APP
[MultiremoteBrowser (unknown) #0-0]
[MultiremoteBrowser (unknown) #0-0] 1 failing (1m 52.7s)
[MultiremoteBrowser (unknown) #0-0]
[MultiremoteBrowser (unknown) #0-0] 1) Cross platform testing  Cases created on mobile app should be visible on web APP
[MultiremoteBrowser (unknown) #0-0] invalid argument: 'value' must be a list
  (Session info: chrome=83.0.4103.106)
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 4.1.13-101.fc21.x86_64 x86_64)
[MultiremoteBrowser (unknown) #0-0] Error: invalid argument: 'value' must be a list
[MultiremoteBrowser (unknown) #0-0]   (Session info: chrome=83.0.4103.106)
[MultiremoteBrowser (unknown) #0-0]   (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 4.1.13-101.fc21.x86_64 x86_64)
[MultiremoteBrowser (unknown) #0-0]     at Object.getErrorFromResponseBody (C:\Users\amrka\Desktop\Work\Appium-wdio\node_modules\webdriver\build\utils.js:94:12)
[MultiremoteBrowser (unknown) #0-0]     at WebDriverRequest._request (C:\Users\amrka\Desktop\Work\Appium-wdio\node_modules\webdriver\build\request.js:133:31)
[MultiremoteBrowser (unknown) #0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[MultiremoteBrowser (unknown) #0-0]     at async Element.elementErrorHandlerCallbackFn (C:\Users\amrka\Desktop\Work\Appium-wdio\node_modules\webdriverio\build\middlewares.js:17:32)
[MultiremoteBrowser (unknown) #0-0]     at async Element.runCommandWithHooks (C:\Users\amrka\Desktop\Work\Appium-wdio\node_modules\@wdio\sync\build\wrapCommand.js:70:25)
[MultiremoteBrowser (unknown) #0-0]     at Element.runCommandWithHooks (C:\Users\amrka\Desktop\Work\Appium-wdio\node_modules\@wdio\sync\build\wrapCommand.js:65:24)
[MultiremoteBrowser (unknown) #0-0]     at Element.wrapCommandFn (C:\Users\amrka\Desktop\Work\Appium-wdio\node_modules\@wdio\sync\build\wrapCommand.js:44:44)
[MultiremoteBrowser (unknown) #0-0]     at Element.elementErrorHandlerCallback (C:\Users\amrka\Desktop\Work\Appium-wdio\node_modules\webdriverio\build\middlewares.js:34:12)
[MultiremoteBrowser (unknown) #0-0]     at DesktopApp.enterAddressAndTag (C:\Users\amrka\Desktop\Work\Appium-wdio\src\test\pages\desktopApp.js:234:23)
[MultiremoteBrowser (unknown) #0-0]     at Context.<anonymous> (C:\Users\amrka\Desktop\Work\Appium-wdio\src\test\specs\CrossPlatform_Suite.js:30:7)
[MultiremoteBrowser (unknown) #0-0]     at Context.executeSync (C:\Users\amrka\Desktop\Work\Appium-wdio\node_modules\@wdio\sync\build\index.js:25:22)
[MultiremoteBrowser (unknown) #0-0]     at C:\Users\amrka\Desktop\Work\Appium-wdio\node_modules\@wdio\sync\build\index.js:46:68
[MultiremoteBrowser (unknown) #0-0]
[MultiremoteBrowser (unknown) #0-0]
[MultiremoteBrowser (unknown) #0-0]
```

**Comment by christian-bromann** [comment]
This seems to be an issue with Browserstack. The [WebDriver specification](https://w3c.github.io/webdriver/#element-send-keys) expects a `text` property. This works with all current browser drivers and should also with one that automates Chrome 83. Please reach out to their support and report this bug.

**Comment by Amrkamel1** [comment]
@christian-bromann 

Thats pretty weird, since its working fine when i run browserstack service alone.

Issue is happening only when combine selenium service using multiremote feature

**Comment by christian-bromann** [comment]
Are you using the latest selenium standalone server? Difficult to say what is going on here but the logs show that the WebdriverIO behavior is correct.

**Comment by Amrkamel1** [comment]
@christian-bromann 

yes im using latest, and same exact script working fine with browserstack alone without combining selenium services

**Comment by cg-tester** [comment]
@christian-bromann 
In my code below, could you pls tell me what is wrong ?  I just want to switch to iframe.
const mainFrame = await $('iframe[name="__privateStripeFrame03022"]')
await browser.switchToFrame(mainFrame)

error log is below
invalid argument: missing 'ELEMENT'

**Comment by christian-bromann** [comment]
@cg-tester make sure the element exists:

```ts
const mainFrame = await $('iframe[name="__privateStripeFrame03022"]')
await mainFrame.waitForExist()
await browser.switchToFrame(mainFrame)
```

**Comment by cg-tester** [comment]
thanks a lot @christian-bromann

**Comment by christian-bromann** [comment]
@cg-tester let's actually make this the default behavior of the command.

**Comment by Delta456** [comment]
Is this issue still relevant? I see `switchToFrame` now deprecated and has become `switchFrame`.

**Comment by cg-tester** [comment]
thank you @Delta456

**Comment by Delta456** [comment]
I think this issue can be closed because `waitForExist` is called internally as we migrated to `switchFrame`.


```js
if (!this.isBidi) {
        if (typeof context === 'function') {
            throw new Error('Cannot use a function to fetch a context in WebDriver Classic')
        }
        if (typeof context === 'string') {
            throw new Error('Cannot use a string to fetch a context in WebDriver Classic')
        }
        if (isPossiblyUnresolvedElement(context)) {
            const element = await context.getElement()
            await element.waitForExist({
                timeoutMsg: `Can't switch to frame with selector ${element.selector} because it doesn't exist`
            })
            return switchToFrame(this, element)
        }
        return switchToFrame(this, context)
    }
    ```

**Comment by cg-tester** [comment]
@Delta456 
are you QA tester?

**Comment by Delta456** [comment]
No, I am not. I was looking at the issue and I feel this issue has been fixed. Can you try with the v9 version?

**Comment by cg-tester** [comment]
What is v9 version?

**Comment by Delta456** [comment]
The lates version

**Comment by cg-tester** [comment]
okay thanks.

**Comment by christian-bromann** [comment]
Thanks for clarifying @Delta456 👏
