### ISSUE TITLE
sauce-service marks failed spec file as successful in Sauce Labs (Legacy RDC)

### ISSUE THREAD

**Issue by IevgenRagulin** [webdriverio/webdriverio#6071]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.7.0
 - **Mode:** Running on Sauce Labs (Legacy RDC)
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12
 - **Platform name and version:** iPhone XS
 - **Additional wdio packages used (if applicable):** @wdio/sauce-service, @wdio/mocha-framework, @wdio/junit-reporter, @wdio/spec-reporter

**Config of WebdriverIO**
Capabilities:
```{
[2020-11-05T17:46:36.594Z]   capabilities: {
[2020-11-05T17:46:36.594Z]     alwaysMatch: {
[2020-11-05T17:46:36.594Z]       useJSONSource: true,
[2020-11-05T17:46:36.594Z]       simpleIsVisibleCheck: true,
[2020-11-05T17:46:36.594Z]       noReset: true,
[2020-11-05T17:46:36.594Z]       newCommandTimeout: 180,
[2020-11-05T17:46:36.594Z]       autoLaunch: false,
[2020-11-05T17:46:36.594Z]       platformName: 'iOS',
[2020-11-05T17:46:36.594Z]       testobject_session_creation_timeout: 600000,
[2020-11-05T17:46:36.594Z]       avoidProxy: true,
[2020-11-05T17:46:36.594Z]       cacheId: 'qxzrc9d71r',
[2020-11-05T17:46:36.594Z]       appiumVersion: '1.18.1',
[2020-11-05T17:46:36.594Z]       phoneOnly: true,
[2020-11-05T17:46:36.594Z]       automationName: 'XCUITest',
[2020-11-05T17:46:36.594Z]       language: 'en',
[2020-11-05T17:46:36.594Z]       locale: 'en_US',
[2020-11-05T17:46:36.594Z]       deviceName: '(iPhone XR)|(iPhone X)|(iPhone XS)|(iPhone 11.*)',
[2020-11-05T17:46:36.594Z]       testobject_suite_name: 'life-extend-ios',
[2020-11-05T17:46:36.594Z]       testobject_api_key: ****,
[2020-11-05T17:46:36.594Z]       testobject_app_id: '891',
[2020-11-05T17:46:36.594Z]       testobject_test_name: 'lxRegression/Nutrition1.test.ts - jenkins-life-extend-PR-4050-123'
[2020-11-05T17:46:36.594Z]     },
[2020-11-05T17:46:36.594Z]     firstMatch: [ {} ]
[2020-11-05T17:46:36.594Z]   ,
```

**Describe the bug**
The test is reported as failed in the logs. The job is marked as successful though in Sauce Labs (I would expect it to be marked as failed)

It used to work before, a couple of month ago, I think we started seeing this after upgrading to 6.7.0 from 6.6.0

**To Reproduce**
Run a test that fails on Sauce Labs. Make sure it fails according to the logs. Go to Sauce Labs UI.
Actual result: test is marked as successful on Sauce Labs
Expected result: test is marked as failed on Sauce Labs

**Log**
Logs:
https://gist.github.com/IevgenRagulin/834986a830b981f0f7b4646c4da98742

**Comment by wswebcreation** [comment]
Hi @IevgenRagulin 

I've been checking your logs and as far as I understand your `beforeAll` hook fails. I ran a simple test on the Legacy RDC with a failing `beforeAll` hook 

```js
import { LOGIN_USERS } from '../../../../configs/e2eConstants';
import LoginPage from '../../../page-objects/LoginPage';
import SwagOverviewPage from '../../../page-objects/SwagOverviewPage';

describe('LoginPage', () => {
    beforeAll(() => {
        browser.url('');
        expect(LoginPage.waitForIsDisplayed()).toEqual(false);
    });

    it('should be able to test loading of login page', () => {
        expect(LoginPage.waitForIsDisplayed()).toEqual(
            true,
            'LoginPage page was not shown',
        );
    });
});
```

and this is the log/result

```log
$ wdio ./test/configs/web/wdio.mobile.chrome.rdc.conf.js --spec=test/web/specs/demo-site/best-practices/login.spec.js --logLevel=debug

Execution of 1 spec files started at 2020-11-06T06:43:19.380Z

2020-11-06T06:43:19.382Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
2020-11-06T06:43:19.433Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-11-06T06:43:19.434Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-11-06T06:43:19.435Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./test/configs/web/wdio.mobile.chrome.rdc.conf.js,--spec=test/web/specs/demo-site/best-practices/login.spec.js,--logLevel=debug
[0-0] 2020-11-06T06:43:19.735Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-11-06T06:43:19.745Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-11-06T06:43:19.746Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in Android - /test/web/specs/demo-site/best-practices/login.spec.js
[0-0] 2020-11-06T06:43:21.610Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
[0-0] 2020-11-06T06:43:21.646Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-11-06T06:43:21.646Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-11-06T06:43:21.648Z INFO webdriver: [POST] https://eu1.appium.testobject.com/wd/hub/session
[0-0] 2020-11-06T06:43:21.649Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      deviceName: 'Samsung Galaxy S[7|8|9]',
      automationName: 'UiAutomator2',
      testobject_api_key: '***',
      testobject_test_name: 'Android - Web',
      platformName: 'Android',
      idleTimeout: 180,
      noReset: true,
      orientation: 'PORTRAIT',
      newCommandTimeout: 180,
      phoneOnly: true,
      tabletOnly: false
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    deviceName: 'Samsung Galaxy S[7|8|9]',
    automationName: 'UiAutomator2',
    testobject_api_key: '***',
    testobject_test_name: 'Android - Web',
    platformName: 'Android',
    idleTimeout: 180,
    noReset: true,
    orientation: 'PORTRAIT',
    newCommandTimeout: 180,
    phoneOnly: true,
    tabletOnly: false
  }
}
[0-0] 2020-11-06T06:43:42.541Z INFO webdriver: COMMAND navigateTo("https://www.saucedemo.com/")
[0-0] 2020-11-06T06:43:42.541Z INFO webdriver: [POST] https://eu1.appium.testobject.com/wd/hub/session/006e432d-0f0c-460a-994f-df7123e54b4c/url
[0-0] 2020-11-06T06:43:42.541Z INFO webdriver: DATA { url: 'https://www.saucedemo.com/' }
[0-0] 2020-11-06T06:43:43.571Z INFO webdriver: COMMAND findElement("css selector", "#login_button_container")
[0-0] 2020-11-06T06:43:43.572Z INFO webdriver: [POST] https://eu1.appium.testobject.com/wd/hub/session/006e432d-0f0c-460a-994f-df7123e54b4c/element
[0-0] 2020-11-06T06:43:43.572Z INFO webdriver: DATA { using: 'css selector', value: '#login_button_container' }
[0-0] 2020-11-06T06:43:43.884Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '0.564555056358041-1',
  ELEMENT: '0.564555056358041-1'
}
[0-0] 2020-11-06T06:43:43.897Z INFO webdriver: COMMAND isElementDisplayed("0.564555056358041-1")
[0-0] 2020-11-06T06:43:43.897Z INFO webdriver: [GET] https://eu1.appium.testobject.com/wd/hub/session/006e432d-0f0c-460a-994f-df7123e54b4c/element/0.564555056358041-1/displayed
[0-0] 2020-11-06T06:43:44.067Z INFO webdriver: RESULT true
[0-0] 2020-11-06T06:43:44.079Z INFO webdriver: COMMAND findElement("css selector", "#login_button_container")
[0-0] 2020-11-06T06:43:44.079Z INFO webdriver: [POST] https://eu1.appium.testobject.com/wd/hub/session/006e432d-0f0c-460a-994f-df7123e54b4c/element
[0-0] 2020-11-06T06:43:44.079Z INFO webdriver: DATA { using: 'css selector', value: '#login_button_container' }
[0-0] 2020-11-06T06:43:44.195Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '0.564555056358041-1',
  ELEMENT: '0.564555056358041-1'
}
[0-0] 2020-11-06T06:43:44.201Z INFO webdriver: COMMAND isElementDisplayed("0.564555056358041-1")
[0-0] 2020-11-06T06:43:44.201Z INFO webdriver: [GET] https://eu1.appium.testobject.com/wd/hub/session/006e432d-0f0c-460a-994f-df7123e54b4c/element/0.564555056358041-1/displayed
[0-0] 2020-11-06T06:43:44.343Z INFO webdriver: RESULT true
[0-0] 2020-11-06T06:43:44.351Z INFO @wdio/sauce-service: Update job with sessionId 006e432d-0f0c-460a-994f-df7123e54b4c, status: passing
[0-0] 2020-11-06T06:43:44.352Z INFO webdriver: COMMAND executeScript("sauce:job-result=true", <object>)
[0-0] 2020-11-06T06:43:44.352Z INFO webdriver: [POST] https://eu1.appium.testobject.com/wd/hub/session/006e432d-0f0c-460a-994f-df7123e54b4c/execute/sync
[0-0] 2020-11-06T06:43:44.352Z INFO webdriver: DATA { script: 'sauce:job-result=true', args: [] }
[0-0] 2020-11-06T06:43:44.443Z INFO webdriver: COMMAND deleteSession()
[0-0] 2020-11-06T06:43:44.444Z INFO webdriver: [DELETE] https://eu1.appium.testobject.com/wd/hub/session/006e432d-0f0c-460a-994f-df7123e54b4c
2020-11-06T06:43:45.023Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 0
[0-0] PASSED in Android - /test/web/specs/demo-site/best-practices/login.spec.js
2020-11-06T06:43:45.024Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[10.102.56.16:16008 Android 10 #0-0] Spec: /Users/wimselles/Sauce/Git/wdio-playground/v6/test/web/specs/demo-site/best-practices/login.spec.js
[10.102.56.16:16008 Android 10 #0-0] Running: 10.102.56.16:16008 on Android 10 executing Chrome
[10.102.56.16:16008 Android 10 #0-0] Session ID: 006e432d-0f0c-460a-994f-df7123e54b4c
[10.102.56.16:16008 Android 10 #0-0]
[10.102.56.16:16008 Android 10 #0-0] LoginPage
[10.102.56.16:16008 Android 10 #0-0]    ✓ should be able to test loading of login page
[10.102.56.16:16008 Android 10 #0-0]    - should be able to login with a standard user
[10.102.56.16:16008 Android 10 #0-0]    - should not be able to login with a locked user
[10.102.56.16:16008 Android 10 #0-0]
[10.102.56.16:16008 Android 10 #0-0] 1 passing (2.3s)
[10.102.56.16:16008 Android 10 #0-0] 2 skipped


Spec Files:      1 passed, 1 total (100% completed) in 00:00:25 

2020-11-06T06:43:45.025Z INFO @wdio/local-runner: Shutting down spawned worker
2020-11-06T06:43:45.280Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-11-06T06:43:45.281Z INFO @wdio/local-runner: shutting down
✨  Done in 27.10s.
```

And with this test

```js
import { LOGIN_USERS } from '../../../../configs/e2eConstants';
import LoginPage from '../../../page-objects/LoginPage';
import SwagOverviewPage from '../../../page-objects/SwagOverviewPage';

describe('LoginPage', () => {
    beforeAll(() => {
        browser.url('');
        LoginPage.waitForIsDisplayed();
    });

    it('should be able to test loading of login page', () => {
        expect(LoginPage.waitForIsDisplayed()).toEqual(
            true,
            'LoginPage page was not shown',
        );
    });
});

I get these logs

```log
$ wdio ./test/configs/web/wdio.mobile.chrome.rdc.conf.js --spec=test/web/specs/demo-site/best-practices/login.spec.js --logLevel=debug

Execution of 1 spec files started at 2020-11-06T06:20:37.192Z

2020-11-06T06:20:37.194Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
2020-11-06T06:20:37.221Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-11-06T06:20:37.223Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-11-06T06:20:37.223Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./test/configs/web/wdio.mobile.chrome.rdc.conf.js,--spec=test/web/specs/demo-site/best-practices/login.spec.js,--logLevel=debug
[0-0] 2020-11-06T06:20:37.516Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-11-06T06:20:37.522Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-11-06T06:20:37.526Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in Android - /test/web/specs/demo-site/best-practices/login.spec.js
[0-0] 2020-11-06T06:20:38.741Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
[0-0] 2020-11-06T06:20:38.780Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-11-06T06:20:38.781Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-11-06T06:20:38.782Z INFO webdriver: [POST] https://eu1.appium.testobject.com/wd/hub/session
[0-0] 2020-11-06T06:20:38.782Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      deviceName: 'Samsung Galaxy S[7|8|9]',
      automationName: 'UiAutomator2',
      testobject_api_key: '***',
      testobject_test_name: 'Android - Web',
      platformName: 'Android',
      idleTimeout: 180,
      noReset: true,
      orientation: 'PORTRAIT',
      newCommandTimeout: 180,
      phoneOnly: true,
      tabletOnly: false
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    deviceName: 'Samsung Galaxy S[7|8|9]',
    automationName: 'UiAutomator2',
    testobject_api_key: '***',
    testobject_test_name: 'Android - Web',
    platformName: 'Android',
    idleTimeout: 180,
    noReset: true,
    orientation: 'PORTRAIT',
    newCommandTimeout: 180,
    phoneOnly: true,
    tabletOnly: false
  }
}
[0-0] 2020-11-06T06:21:09.773Z INFO webdriver: COMMAND navigateTo("https://www.saucedemo.com/")
[0-0] 2020-11-06T06:21:09.773Z INFO webdriver: [POST] https://eu1.appium.testobject.com/wd/hub/session/a810dec1-9f73-4ac6-82ab-30d8070df44d/url
[0-0] 2020-11-06T06:21:09.773Z INFO webdriver: DATA { url: 'https://www.saucedemo.com/' }
[0-0] 2020-11-06T06:21:16.539Z INFO webdriver: COMMAND findElement("css selector", "#login_button_container")
[0-0] 2020-11-06T06:21:16.539Z INFO webdriver: [POST] https://eu1.appium.testobject.com/wd/hub/session/a810dec1-9f73-4ac6-82ab-30d8070df44d/element
[0-0] 2020-11-06T06:21:16.539Z INFO webdriver: DATA { using: 'css selector', value: '#login_button_container' }
[0-0] 2020-11-06T06:21:16.718Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '0.33741321330374063-1',
  ELEMENT: '0.33741321330374063-1'
}
[0-0] 2020-11-06T06:21:16.731Z INFO webdriver: COMMAND isElementDisplayed("0.33741321330374063-1")
[0-0] 2020-11-06T06:21:16.732Z INFO webdriver: [GET] https://eu1.appium.testobject.com/wd/hub/session/a810dec1-9f73-4ac6-82ab-30d8070df44d/element/0.33741321330374063-1/displayed
[0-0] 2020-11-06T06:21:16.877Z INFO webdriver: RESULT true
[0-0] 2020-11-06T06:21:16.878Z INFO webdriver: COMMAND findElement("css selector", "#login_button_container")
[0-0] 2020-11-06T06:21:16.878Z INFO webdriver: [POST] https://eu1.appium.testobject.com/wd/hub/session/a810dec1-9f73-4ac6-82ab-30d8070df44d/element
[0-0] 2020-11-06T06:21:16.878Z INFO webdriver: DATA { using: 'css selector', value: '#login_button_container' }
[0-0] 2020-11-06T06:21:17.005Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '0.33741321330374063-1',
  ELEMENT: '0.33741321330374063-1'
}
[0-0] 2020-11-06T06:21:17.014Z INFO webdriver: COMMAND isElementDisplayed("0.33741321330374063-1")
[0-0] 2020-11-06T06:21:17.014Z INFO webdriver: [GET] https://eu1.appium.testobject.com/wd/hub/session/a810dec1-9f73-4ac6-82ab-30d8070df44d/element/0.33741321330374063-1/displayed
[0-0] 2020-11-06T06:21:17.133Z INFO webdriver: RESULT true
[0-0] Error in "LoginPage should be able to test loading of login page"
Error: Expected true to equal false.
    at <Jasmine>
    at UserContext.<anonymous> (/Users/wimselles/Sauce/Git/wdio-playground/v6/test/web/specs/demo-site/best-practices/login.spec.js:12:48)
[0-0] 2020-11-06T06:21:17.150Z INFO @wdio/sauce-service: Update job with sessionId a810dec1-9f73-4ac6-82ab-30d8070df44d, status: failing
[0-0] 2020-11-06T06:21:17.151Z INFO webdriver: COMMAND executeScript("sauce:job-result=false", <object>)
[0-0] 2020-11-06T06:21:17.151Z INFO webdriver: [POST] https://eu1.appium.testobject.com/wd/hub/session/a810dec1-9f73-4ac6-82ab-30d8070df44d/execute/sync
[0-0] 2020-11-06T06:21:17.151Z INFO webdriver: DATA { script: 'sauce:job-result=false', args: [] }
[0-0] 2020-11-06T06:21:17.239Z INFO webdriver: COMMAND deleteSession()
[0-0] 2020-11-06T06:21:17.239Z INFO webdriver: [DELETE] https://eu1.appium.testobject.com/wd/hub/session/a810dec1-9f73-4ac6-82ab-30d8070df44d
2020-11-06T06:21:17.685Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in Android - /test/web/specs/demo-site/best-practices/login.spec.js
2020-11-06T06:21:17.686Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[10.102.56.21:16008 Android 8.0.0 #0-0] Spec: /Users/wimselles/Sauce/Git/wdio-playground/v6/test/web/specs/demo-site/best-practices/login.spec.js
[10.102.56.21:16008 Android 8.0.0 #0-0] Running: 10.102.56.21:16008 on Android 8.0.0 executing Chrome
[10.102.56.21:16008 Android 8.0.0 #0-0] Session ID: a810dec1-9f73-4ac6-82ab-30d8070df44d
[10.102.56.21:16008 Android 8.0.0 #0-0]
[10.102.56.21:16008 Android 8.0.0 #0-0] LoginPage
[10.102.56.21:16008 Android 8.0.0 #0-0]    ✖ should be able to test loading of login page
[10.102.56.21:16008 Android 8.0.0 #0-0]    - should be able to login with a standard user
[10.102.56.21:16008 Android 8.0.0 #0-0]    - should not be able to login with a locked user
[10.102.56.21:16008 Android 8.0.0 #0-0]
[10.102.56.21:16008 Android 8.0.0 #0-0] 1 failing (7.7s)
[10.102.56.21:16008 Android 8.0.0 #0-0] 2 skipped
[10.102.56.21:16008 Android 8.0.0 #0-0]
[10.102.56.21:16008 Android 8.0.0 #0-0] 1) LoginPage should be able to test loading of login page
[10.102.56.21:16008 Android 8.0.0 #0-0] Expected true to equal false.
[10.102.56.21:16008 Android 8.0.0 #0-0] Error: Expected true to equal false.
[10.102.56.21:16008 Android 8.0.0 #0-0]     at <Jasmine>
[10.102.56.21:16008 Android 8.0.0 #0-0]     at UserContext.<anonymous> (/Users/wimselles/Sauce/Git/wdio-playground/v6/test/web/specs/demo-site/best-practices/login.spec.js:12:48)
[10.102.56.21:16008 Android 8.0.0 #0-0] Expected true to equal false.
[10.102.56.21:16008 Android 8.0.0 #0-0] error properties: Object({ matcherName: 'toEqual', passed: false, expected: [ false, 'LoginPage page was not shown' ], actual: true })
[10.102.56.21:16008 Android 8.0.0 #0-0] Error: Expected true to equal false.
[10.102.56.21:16008 Android 8.0.0 #0-0]     at <Jasmine>
[10.102.56.21:16008 Android 8.0.0 #0-0]     at UserContext.<anonymous> (/Users/wimselles/Sauce/Git/wdio-playground/v6/test/web/specs/demo-site/best-practices/login.spec.js:12:48)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:40 

2020-11-06T06:21:17.687Z INFO @wdio/local-runner: Shutting down spawned worker
2020-11-06T06:21:17.939Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2020-11-06T06:21:17.940Z INFO @wdio/local-runner: shutting down
error Command failed with exit code 1.
```

and as you can see the `beforeAll` hook is not letting the test fail

These are my versions of the services

```json
{
    "@wdio/appium-service": "^6.6.3",
    "@wdio/applitools-service": "^6.7.0",
    "@wdio/cli": "^6.7.2",
    "@wdio/jasmine-framework": "^6.7.2",
    "@wdio/local-runner": "^6.7.2",
    "@wdio/sauce-service": "^6.7.2",
    "@wdio/selenium-standalone-service": "^6.6.5",
    "@wdio/spec-reporter": "^6.7.0",
    "@wdio/sync": "^6.7.2",
}
```

Can you provide a working example where this behaviour is shown?

**Comment by christian-bromann** [comment]
Closing due to inactivity. Happen to re-open if a reproducible example can be provided.
