### ISSUE TITLE
Can't launch three browsers at once

### ISSUE THREAD

**Issue by ljansen97** [webdriverio/webdriverio#6150]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.9.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** 14.15.0
 - **NPM version:** 6.14.8
 - **Browser name and version:** Chrome, Edge and Firefox (latest versions)
 - **Platform name and version:** Windows 10 build 2004
 - **Additional wdio packages used (if applicable):**

```
"devDependencies": {
    "@wdio/cli": "^6.9.1",
    "@wdio/local-runner": "^6.9.1",
    "@wdio/mocha-framework": "^6.8.0",
    "@wdio/sync": "^6.9.1",
    "chromedriver": "^87.0.0",
    "geckodriver": "^1.21.0",
    "msedgedriver": "^86.0.0",
    "wdio-chromedriver-service": "^6.0.4",
    "wdio-edgedriver-service": "^1.2.0",
    "wdio-geckodriver-service": "^1.1.1"
  }
```

**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 30,
    capabilities: [
        {
            maxInstances: 1,
            browserName: 'chrome',
            acceptInsecureCerts: true
        },{
            browserName: 'MicrosoftEdge',
            maxInstances: 1
        }, {
            maxInstances: 1,
            browserName: 'firefox'
        },
    ],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['chromedriver', 'edgedriver', 'geckodriver'],
    framework: 'mocha',
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
}
```

**Describe the bug**
It will never launch the three browsers at once. The order of the services array determines which browsers get launched...

For example:
`services: ['edgedriver', 'chromedriver', 'geckodriver'],` => this launches Chrome and FF
`services: ['geckodriver', 'edgedriver', 'chromedriver'],` => this launches Edge and Chrome

But it never launches all three at the same time. They do work individually.

**Expected behavior**
It should launch all three browsers and do the tests:
```
describe('My Login application', () => {
    it('should login with valid credentials', () => {
        browser.url(`https://google.nl/`);
        expect(browser).toHaveTitle('Google');
    });
});

```

**Log**
```
[1-0] 2020-11-23T20:38:46.683Z ERROR webdriver: Request failed with status 500 due to session not created: Unable to find a matching set of capabilities
[1-0] 2020-11-23T20:38:46.684Z ERROR webdriver: session not created: Unable to find a matching set of capabilities
    at Object.getErrorFromResponseBody (S:\webdriverio-test\node_modules\webdriver\build\utils.js:94:12)
    at WebDriverRequest._request (S:\webdriverio-test\node_modules\webdriver\build\request.js:134:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.startWebDriverSession (S:\webdriverio-test\node_modules\webdriver\build\utils.js:29:20)
    at async Function.newSession (S:\webdriverio-test\node_modules\webdriver\build\index.js:30:45)
    at async Object.exports.remote (S:\webdriverio-test\node_modules\webdriverio\build\index.js:60:22)
    at async Runner._startSession (S:\webdriverio-test\node_modules\@wdio\runner\build\index.js:128:56)
    at async Runner._initSession (S:\webdriverio-test\node_modules\@wdio\runner\build\index.js:108:25)
    at async Runner.run (S:\webdriverio-test\node_modules\@wdio\runner\build\index.js:52:19)
[1-0]  Error:  Failed to create session.
```

**Additional context**
-

**Comment by christian-bromann** [comment]
@ljansen97 these drivers are not maintained by the core WebdriverIO team. Theoretically they should do what you expect but it seems they don't. Services can modify specific capabilities to automatically connect to their drivers so the desired behavior is possible. There is nothing in the core project we can do to fix this besides to recommend to use the standalone-server service. I would also suggest to create this issue in the service projects so they are aware of it and maybe someone could provide a fix.
