### ISSUE TITLE
selenium standalone throwing error: Error: Callback was already called.

### ISSUE THREAD

**Issue by gowthamraj198** [webdriverio/webdriverio#6155]
## 💬 Questions and Help

Hi Team i am trying to run my WDIO tests. When i run the tests in local it is running fine. But when i Try to run in docker (CentOS) below error is thrown.

webdriverio6-appium-mocha-boilerplate@1.0.0 desktopWeb
npx wdio ./config/desktopWeb.config.js

2020-11-24T10:23:21.720Z DEBUG @wdio/sync: Couldn't load fibers package for Node v10 and above

Execution of 1 spec files started at 2020-11-24T10:23:22.338Z

/root/node_modules/selenium-standalone/lib/install.js:626
cb(new Error("Could not request headers from " + url + ": " + err));
^
Error: Callback was already called.
at /root/node_modules/selenium-standalone/node_modules/async/dist/async.js:318:36
at Request.<anonymous> (/root/node_modules/selenium-standalone/lib/install.js:626:7)
at Object.onceWrapper (node:events:436:26)
at Request.emit (node:events:329:20)
at Request.EventEmitter.emit (node:domain:467:12)
at IncomingMessage.<anonymous> (/root/node_modules/request/request.js:1079:12)
at IncomingMessage.emit (node:events:329:20)
at IncomingMessage.EventEmitter.emit (node:domain:467:12)
at TLSSocket.socketCloseListener (node:_http_client:430:13)
at TLSSocket.emit (node:events:341:22)

Config:
config.services = [
    ['selenium-standalone', {
        logPath: 'logs',
        installArgs: { drivers },
        args: { drivers },
    }]
]

config.capabilities = [
    {

            maxInstances: 5,
            browserName: 'chrome',
            acceptInsecureCerts: true,
            'goog:chromeOptions': {
                args: ['--headless', '--disable-gpu', "--no-sandbox", '--window-size=1280,800']
              }
    }
]

**Comment by christian-bromann** [comment]
@gowthamraj198 thanks for filing the issue. This seems to be an issue with the [selenium-standalone](https://github.com/vvo/selenium-standalone) package. I recommend to file the issue there. Thanks!
