### ISSUE TITLE
Error when using takeElementScreenshot in SauceLabs with W3C protocol

### ISSUE THREAD

**Issue by web-padawan** [webdriverio/webdriverio#6165]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.10.0
 - **Mode:** standalone mode via `remote`
 - **Node.js version:** 12.18 LTS
 - **NPM version:** 6.14
 - **Browser name and version:** Chrome, Firefox
 - **Platform name and version:** Windows 10 in SauceLabs

**Config of WebdriverIO**

Configured to use with SauceLabs similarly to how `karma-sauce-launcher` works (see the [processConfig](https://github.com/web-padawan/test-runner-wdio/blob/master/src/sauce/process-config.ts) utility).

**Describe the bug**

In my test runner plugin I have the [following method](https://github.com/web-padawan/test-runner-wdio/blob/0bba7a12dc4619eda2a13408c8d5b84c63c4f8cd/src/wdio/IframeManager.ts#L73-L93) for taking element screenshot:

```ts
  async takeScreenshot(sessionId: string, locator: string): Promise<Buffer> {
    const frameId = this.getFrameId(sessionId);

    const frame = await this.driver.$(`iframe#${frameId}`);

    console.log('frame id:', frame.elementId);

    // TODO: fails with SauceLabs with the error
    // RequestError: The `GET` method cannot be used with a body
    await this.driver.switchToFrame(frame);

    const elementData = (await this.driver.execute(locator, [])) as Element;

    const element = await this.driver.$(elementData);

    const base64 = await this.driver.takeElementScreenshot(element.elementId, true);

    await this.driver.switchToParentFrame();

    return Buffer.from(base64, 'base64');
  }
```

This works when using DevTools protocol, but not in SauceLabs (using W3C protocol).

**To Reproduce**

1. Clone https://github.com/web-padawan/test-runner-wdio

2. Run `npm i && npm run build`

3. Run `npm run test:update` to test that it works

4. Go to `web-test-runner.config.js` and uncomment [Sauce launcher](https://github.com/web-padawan/test-runner-wdio/blob/2021f8a52658ef1035db60bd4521626ace06aeeb/web-test-runner.config.js#L34-L40)

5. Export env variables: `SAUCE_ACCESS_KEY` and `SAUCE_USERNAME`

6. Run `npm run test:update` again and the same code will fail.

**Expected behavior**

The `takeElementScreenshot` method should work the same as it does in DevTools mode using local Chrome.

**Log**

The error stack trace looks like this:

```
RequestError: The `GET` method cannot be used with a body
    at Request._destroy (/Users/sergey/cf/test-runner-wdio/node_modules/got/dist/source/core/index.js:1369:21)
    at Request.destroy (internal/streams/destroy.js:38:8)
    at /Users/sergey/cf/test-runner-wdio/node_modules/got/dist/source/core/index.js:348:26
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Request._finalizeBody (/Users/sergey/cf/test-runner-wdio/node_modules/got/dist/source/core/index.js:707:23)
    at /Users/sergey/cf/test-runner-wdio/node_modules/got/dist/source/core/index.js:327:28
    at new Request (/Users/sergey/cf/test-runner-wdio/node_modules/got/dist/source/core/index.js:351:11)
    at makeRequest (/Users/sergey/cf/test-runner-wdio/node_modules/got/dist/source/as-promise/index.js:35:29)
    at /Users/sergey/cf/test-runner-wdio/node_modules/got/dist/source/as-promise/index.js:147:9
    at /Users/sergey/cf/test-runner-wdio/node_modules/p-cancelable/index.js:61:11
    at new Promise (<anonymous>)
    at new PCancelable (/Users/sergey/cf/test-runner-wdio/node_modules/p-cancelable/index.js:31:19)
    at Object.asPromise [as default] (/Users/sergey/cf/test-runner-wdio/node_modules/got/dist/source/as-promise/index.js:33:21)
    at getPromiseOrStream (/Users/sergey/cf/test-runner-wdio/node_modules/got/dist/source/create.js:43:121) {
  code: undefined,
  timings: undefined
}
```

**Comment by web-padawan** [comment]
Looks like the problem was related to `takeElementScreenshot` second boolean argument.

After I removed it, everything worked: https://github.com/web-padawan/test-runner-wdio/commit/f607b76f084d23371f94692f14cbc3e31a893e7b
