### ISSUE TITLE
Driver crashes when using the elementIdText method

### ISSUE THREAD

**Issue by dimirey** [webdriverio/webdriverio#626]
When I try to access the text within an element using a class accessor the test promptly fails and the driver crashes.

Here is a sample of the code i've written:

```javascript
a = browser.getText('[class="listCntr"]');
  console.log(a);'
```

as well as

```javascript
browser.getText('[class="listCntr"]').then(function(text) {
    console.log(text);
});
```

Here is the error that the selenium log prints:
```
'17:01:20.980 INFO - Done: [click: 4 [[FirefoxDriver: firefox on MAC (3c1cc6a5-bb0d-f945-8806-5234084c5388)] -> css selector: [data-class='home.admin.orgTab']]]
17:01:21.015 INFO - Executing: [delete session: c64692d5-71e6-4999-8e43-d0c9ba6f6ba4])
17:01:21.016 INFO - Executing: [find elements: By.cssSelector: [class="listCntr"]])
17:01:21.175 INFO - Done: [delete session: c64692d5-71e6-4999-8e43-d0c9ba6f6ba4]
17:01:21.762 WARN - Exception thrown
org.openqa.selenium.remote.SessionNotFoundException: The FirefoxDriver cannot be used after quit() was called.
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Dimitris-MacBook-Pro.local', ip: '192.168.1.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.6.0_65'
Driver info: driver.version: EventFiringWebDriver
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:359)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:377)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementsByCssSelector(RemoteWebDriver.java:445)
	at org.openqa.selenium.By$ByCssSelector.findElements(By.java:437)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:340)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
	at com.sun.proxy.$Proxy1.findElements(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElements(EventFiringWebDriver.java:173)
	at org.openqa.selenium.remote.server.handler.FindElements.call(FindElements.java:49)
	at org.openqa.selenium.remote.server.handler.FindElements.call(FindElements.java:1)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
17:01:21.763 WARN - Exception: The FirefoxDriver cannot be used after quit() was called.
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Dimitris-MacBook-Pro.local', ip: '192.168.1.3', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.6.0_65'
Driver info: driver.version: EventFiringWebDriver'
```

**Comment by christian-bromann** [comment]
As you can see in the logs the second line closes the session and after that you want to use the session to get the text of an element. At this point the browser has already closed. I will need more code to see what went wrong.

**Comment by christian-bromann** [comment]
Closing due to inactivity. Let me know if you still have trouble with that.

**Comment by sean-hill** [comment]
@christian-bromann I'm having a similar issue. Basically my flow is I have a chain of commands, but perhaps half way through, an error is thrown, at that point I'd like to delete my session, and close the browser. For example:

client
	.init()
	.url('http://www.google.com')
	.do()
	.something()
	.now()
	.end();

Now assume that in between the commands `do` and `something` I'd like to quit the browser because some test case didn't pass.

If I do

	.do()
	.then(function(testCase){

		if (testCase === 'failed') {
			return this.end();
		}

	})
	.something()
	.now()
	.end();

Webdriver continues to run the commands after it and I get this error repeately over and over till my server runs out of memory:

	23:47:26.111 INFO - Done: [delete session: 485c371e-6003-4801-8ba4-77472ed2871f]
	23:47:26.114 WARN - Exception thrown
	org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?
	Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
	System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_75'
	Driver info: driver.version: RemoteWebDriver
		at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:125)
		at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:66)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
		at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:324)
		at org.openqa.selenium.remote.server.handler.CaptureScreenshot.call(CaptureScreenshot.java:35)
		at org.openqa.selenium.remote.server.handler.CaptureScreenshot.call(CaptureScreenshot.java:1)
		at java.util.concurrent.FutureTask.run(FutureTask.java:262)
		at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:745)
	23:47:26.118 WARN - Exception: Session ID is null. Using WebDriver after calling quit()?
	Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
	System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_75'
	Driver info: driver.version: RemoteWebDriver
	RuntimeError: Session ID is null. Using WebDriver after calling quit()?
	Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
	System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-36-generic', java.version: '1.7.0_75'
	Driver info: driver.version: RemoteWebDriver
	    at safeEnd(true) - biller-scraper.js:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at safeEnd(true) - biller-scraper.js:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at safeEnd(true) - biller-scraper.js:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at safeEnd(true) - biller-scraper.js:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at safeEnd(true) - biller-scraper.js:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at safeEnd(true) - biller-scraper.js:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at safeEnd(true) - biller-scraper.js:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at safeEnd(true) - biller-scraper.js:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at safeEnd(true) - biller-scraper.js:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload
	    at safeEnd(true) - biller-scraper.js:132:7
	NoSessionIdError: A session id is required for this command but wasn't found in the response payload

This would be all right if the error was only thrown once, but it continues to throw it till the node process runs out of memory.
