### ISSUE TITLE
Appium connection failed to initiate from typescript,  due to TypeError for URL

### ISSUE THREAD

**Issue by JonP-xpb** [webdriverio/webdriverio#6315]
- **WebdriverIO version:**  6.11.3
 - **Mode:** Standalone 
 - **Node.js version:** 14.15.1
 - **NPM version:** 6.14.18
 - **Browser name and version:**  XCode Simulator 12.3
 - **Platform name and version:** MacOS 11.0.1
 - **Additional wdio packages used (if applicable):** 
 - 
**Config of WebdriverIO**

let serverConfig = {
    path: '/wd/hub',
    host: 'localhost',
    port: 4723,
    logLevel: 'info'
}
**Describe the bug**
webdriverio.remote() call is failing to create a session with the error "URL is not a constructor"

2021-01-13T16:24:50.203Z ERROR webdriver: TypeError: URL is not a constructor
        at WebDriverRequest._createOptions (/Users/jonpye/tsg/1st/.yarn/cache/webdriver-npm-6.11.0-d2f05358a7-deb22d3f16.zip/node_modules/webdriver/build/request.js:93:30)
        at WebDriverRequest.makeRequest (/Users/jonpye/tsg/1st/.yarn/cache/webdriver-npm-6.11.0-d2f05358a7-deb22d3f16.zip/node_modules/webdriver/build/request.js:63:38)
        at Object.startWebDriverSession (/Users/jonpye/tsg/1st/.yarn/cache/webdriver-npm-6.11.0-d2f05358a7-deb22d3f16.zip/node_modules/webdriver/build/utils.js:29:41)
        at Function.newSession (/Users/jonpye/tsg/1st/.yarn/cache/webdriver-npm-6.11.0-d2f05358a7-deb22d3f16.zip/node_modules/webdriver/build/index.js:35:59)
        at Object.<anonymous>.exports.remote (/Users/jonpye/tsg/1st/.yarn/cache/webdriverio-npm-6.11.3-f267ca72e8-26feadc607.zip/node_modules/webdriverio/build/index.js:53:43)
        at Object.<anonymous> (/Users/jonpye/tsg/1st/client/1stbet-web/src/__test__/safari.test.ts:32:22)
        at _callCircusTest (/Users/jonpye/tsg/1st/.yarn/cache/jest-circus-npm-26.6.3-b5c16d78c9-8ef70b1ccd.zip/node_modules/jest-circus/build/run.js:212:5)
        at _runTest (/Users/jonpye/tsg/1st/.yarn/cache/jest-circus-npm-26.6.3-b5c16d78c9-8ef70b1ccd.zip/node_modules/jest-circus/build/run.js:149:3)
        at _runTestsForDescribeBlock (/Users/jonpye/tsg/1st/.yarn/cache/jest-circus-npm-26.6.3-b5c16d78c9-8ef70b1ccd.zip/node_modules/jest-circus/build/run.js:63:9)
        at _runTestsForDescribeBlock (/Users/jonpye/tsg/1st/.yarn/cache/jest-circus-npm-26.6.3-b5c16d78c9-8ef70b1ccd.zip/node_modules/jest-circus/build/run.js:57:9)

The test code:
> 
let iosWebCapabilities = {
    platformName: 'iOS',
    automationName: 'XCUITest',
    deviceName:  'iPhone 12 Pro Max',
    platformVersion: '14.3',
    browserName: 'Safari',
    safariInitialUrl: 'http://www.google.com',
	safariAllowPopups: true,
	safariIgnoreFraudWarning: true,
	safariOpenLinksInBackground: false,
}

let serverConfig = {
    path: '/wd/hub',
    host: 'localhost',
    port: 4723,
    logLevel: 'info'
}

let iosWebOptions = {
    capabilities: iosWebCapabilities,
    serverConfig
}

describe("safari session", () => {
    it("create and destroy a safari session", async () =>
      {
      const client = await webdriverio.remote(iosWebOptions)
      let url = await client.url('start')
      console.log('url is ' + url)
      let title = await client.getTitle()
      console.log('title is ' + title);
      await client.deleteSession()
      })
    });

**To Reproduce**
write the simple test as above then execute it

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

**Comment by christian-bromann** [comment]
@JonP-xpb please try with latest version `v7.0.2`. I suppose to be fixed. If not please let me know.
