### ISSUE TITLE
Running Specific Tests with MochaOpts - Tests Passed, but execution finished with error.

### ISSUE THREAD

**Issue by paul-gladoon** [webdriverio/webdriverio#6404]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.12.0
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 15.7.0
 - **NPM version:** 7.4.3

**Describe the bug**
Running Specific Tests with MochaOpts - Tests Passed, but execution finished with error.

**To Reproduce**
Run some "it" using grep MochaOpts

**Log**
[0-5] 2021-02-10T07:29:21.242Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot set property 'failures' of undefined
    at AllureReporter.<anonymous> (/Users/administrator/Documents/sp/automation/node_modules/@wdio/reporter/build/index.js:137:38)
    at AllureReporter.emit (node:events:379:20)
    at AllureReporter.EventEmitter.emit (node:domain:470:12)
    at /Users/administrator/Documents/sp/automation/node_modules/@wdio/runner/build/reporter.js:26:56
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (/Users/administrator/Documents/sp/automation/node_modules/@wdio/runner/build/reporter.js:26:25)
    at Runner._shutdown (/Users/administrator/Documents/sp/automation/node_modules/@wdio/runner/build/index.js:164:24)
    at Runner.run (/Users/administrator/Documents/sp/automation/node_modules/@wdio/runner/build/index.js:50:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
2021-02-10T07:29:26.893Z INFO @wdio/cli: [0-5] SKIPPED in chrome - /specs/e2e/wf.spec.ts
2021-02-10T07:29:26.893Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      1 passed, 5 skipped, 6 total (100% completed) in 00:00:38 

2021-02-10T07:29:26.894Z INFO @wdio/local-runner: Shutting down spawned worker
2021-02-10T07:29:27.147Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-02-10T07:29:27.148Z INFO @wdio/local-runner: shutting down
npm ERR! code 1
npm ERR! path /Users/administrator/Documents/sp/automation
npm ERR! command failed
npm ERR! command sh -c wdio ./config/wdio.conf.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/administrator/.npm/_logs/2021-02-10T07_29_27_172Z-debug.log

**Additional context**
22 verbose stack     at ChildProcess.<anonymous> (/Users/administrator/.nvm/versions/node/v15.7.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:379:20)
22 verbose stack     at maybeClose (node:internal/child_process:1069:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:300:5)

> Please use the correct markdown

**Comment by paul-gladoon** [comment]
Hello, any updates here?

**Comment by christian-bromann** [comment]
@paul-gladoon can you provide a minimal reproducible example?

**Comment by paul-gladoon** [comment]
@christian-bromann 
https://webdriver.io/docs/organizingsuites/#running-specific-tests-with-mochaopts
Just use this approach to execute;

I'm using this: 
const mochaOpts = {
    ui: 'bdd',
    timeout: 60000,
    grep: GREP_TEST.replace(/,/gi, '|'),
  }

**Comment by christian-bromann** [comment]
@paul-gladoon this doesn't help. Can you create a simple project that reproduces this?

**Comment by christian-bromann** [comment]
Another attempt to reproduce the issue failed. Closing.
