### ISSUE TITLE
Unable to use TypeScript config file

### ISSUE THREAD

**Issue by RafalSkorka** [webdriverio/webdriverio#6424]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, sync
 - **Node.js version:** 14.15..4
 - **NPM version:** 6.14.10
 - **Browser name and version:** Chrome
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/runner

**Config of WebdriverIO**

filename: wdio.conf.ts <--- note the ts extension

```
import * as path from 'path';
exports.config = {
    before: () => {
        browser.addCommand('logInfo', (message: string) => {
            console.log(message);
        });
    },
    runner: 'local',
    specs: [
        './specs/**/*.ts'
    ],
    capabilities: [{
        browserName: 'chrome',
        acceptInsecureCerts: true
    }],
    services: ['chromedriver'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
    }
};

```

**Describe the bug**
I was trying to update wdio to 7.0 and use a typescripted config file which I previously (in 6.x) required from a .js file with manually called ts-node/register. The config is parsed fine in Launcher, but fails in Runner with 
`ERROR @wdio/config:ConfigParser: Failed loading configuration file: C:\git\testwd\wdio.conf.ts: Cannot use import statement outside a module
`
**To Reproduce**
``npx wdio run wdio.conf.ts``

**Expected behavior**
I would expect runner to also compile and use the TS config.

**Log**
```
[0-0] 2021-02-13T21:52:54.120Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: C:\git\testwd\wdio.conf.ts: Cannot use import statement outside a module
2021-02-13T21:52:54.122Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'emit' of undefined
    at Runner._shutdown (C:\git\testwd\node_modules\@wdio\runner\build\index.js:278:24)
    at Runner.run (C:\git\testwd\node_modules\@wdio\runner\build\index.js:48:25)
    at process.<anonymous> (C:\git\testwd\node_modules\@wdio\local-runner\build\run.js:24:30)
    at process.emit (events.js:327:22)
    at process.EventEmitter.emit (domain.js:467:12)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```
**Additional context**
I see ``autoCompile()`` is run in Launcher before it adds config via ``addConfigFile``, but the compilation step is not done in Runner. It works fine when I added this ``autoCompile()`` there.

**Comment by christian-bromann** [comment]
This has been fixed by https://github.com/webdriverio/webdriverio/pull/6475 and released in `v7.0.7`
