### ISSUE TITLE
wdio-allure-reporter: `TypeError: Cannot read property 'includes' of undefined` and `TypeError: Cannot read property 'split' of undefined` errors

### ISSUE THREAD

**Issue by rickschubert** [webdriverio/webdriverio#6438]
Please find below the full error stack trace for `Cannot read property 'includes' of undefined`: 

```
2021-02-15T11:53:41.988Z ERROR @wdio/runner: TypeError: Cannot read property 'includes' of undefined
    at /Users/rickschubert/Documents/github/app/e2e/cucumber-browser-tests/node_modules/@wdio/allure-reporter/build/utils.js:48:85
    at Array.some (<anonymous>)
    at Object.exports.isMochaEachHooks (/Users/rickschubert/Documents/github/app/e2e/cucumber-browser-tests/node_modules/@wdio/allure-reporter/build/utils.js:48:66)
    at AllureReporter.onHookStart (/Users/rickschubert/Documents/github/app/e2e/cucumber-browser-tests/node_modules/@wdio/allure-reporter/build/index.js:237:56)
    at AllureReporter.<anonymous> (/Users/rickschubert/Documents/github/app/e2e/cucumber-browser-tests/node_modules/@wdio/allure-reporter/node_modules/@wdio/reporter/build/index.js:72:18)
    at AllureReporter.emit (events.js:311:20)
    at AllureReporter.EventEmitter.emit (domain.js:482:12)
    at /Users/rickschubert/Documents/github/app/e2e/cucumber-browser-tests/node_modules/@wdio/runner/build/reporter.js:36:56
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (/Users/rickschubert/Documents/github/app/e2e/cucumber-browser-tests/node_modules/@wdio/runner/build/reporter.js:36:25)
    at CucumberReporter.emit (/Users/rickschubert/Documents/github/app/e2e/cucumber-browser-tests/node_modules/@wdio/cucumber-framework/build/reporter.js:194:24)
    at CucumberReporter.handleBeforeStep (/Users/rickschubert/Documents/github/app/e2e/cucumber-browser-tests/node_modules/@wdio/cucumber-framework/build/reporter.js:57:14)
    at CucumberEventListener.emit (events.js:311:20)
    at CucumberEventListener.EventEmitter.emit (domain.js:482:12)
    at CucumberEventListener.onTestStepStarted (/Users/rickschubert/Documents/github/app/e2e/cucumber-browser-tests/node_modules/@wdio/cucumber-framework/build/cucumberEventListener.js:280:14)
    at EventEmitter.<anonymous> (/Users/rickschubert/Documents/github/app/e2e/cucumber-browser-tests/node_modules/@wdio/cucumber-framework/build/cucumberEventListener.js:40:22)**
```

A similar error occurs with `Cannot read property 'split' of undefined` but I am currently unable to provide a stack trace for this.

The two errors occur in these two lines, `title` is undefined:
- https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/utils.ts#L53
- https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/utils.ts#L61

These are the package versions I was using to reproduce this:

```
"@wdio/allure-reporter": "^7.0.3",
"@wdio/browserstack-service": "^7.0.3",
"@wdio/cli": "^7.0.3",
"@wdio/cucumber-framework": "^7.0.3",
"@wdio/devtools-service": "^7.0.3",
"@wdio/local-runner": "^7.0.3",
"@wdio/selenium-standalone-service": "^7.0.3",
"@wdio/sync": "^7.0.3",
"wdio-browserstack-reporter": "^1.0.0",
"wdio-cucumberjs-json-reporter": "^2.0.2",
"wdio-video-reporter": "^3.1.1",
"webdriverio": "^7.0.3",
```

The project I was using to reproduce this uses the WDIO testrunner and the cucumber framework; I am not using mocha.

**Comment by christian-bromann** [comment]
@rickschubert would you still be interested to take a stab at this?

**Comment by rickschubert** [comment]
Absolutely! I will have a look and see what I can find out.

**Comment by rickschubert** [comment]
I have created a pull request for this here: https://github.com/webdriverio/webdriverio/pull/6441

**Comment by christian-bromann** [comment]
Let's continue our conversation there.
