### ISSUE TITLE
V5: Cucumber - passing param to Scenario name from Examples tables when there are multiple examples tables throws an error

### ISSUE THREAD

**Issue by pyxis828** [webdriverio/webdriverio#6451]
Currently on V5, 

Config:

```
 "capabilities": [{
        "browserName": "chrome",
        "goog:chromeOptions": {
            args: ['--disable-browser-side-navigation', '--start-maximized'],
            excludeSwitches: ['enable-automation', 'load-extension'],
            prefs: {"credentials_enable_service": false, "profile.password_manager_enabled": false}
        },
        "maxInstances": 1,
        "timeouts": {
            "implicit": 5000,
            "pageLoad": 30000
        }
    }],

    //trace, debug, info, warn, error, silent
    "logLevel": "warn",

    waitforTimeout: 5000,

    connectionRetryTimeout: 90000,

    connectionRetryCount: 3,

    hostname: 'localhost',

    port: 4444,

    path: '/wd/hub',

    services: ['selenium-standalone', 'intercept',
        ['image-comparison',
        {
            baselineFolder: './share/data/images/baselines',
            formatImageName: '{tag}-{browserName}-{width}x{height}',
            screenshotPath: './share/data/images/screenshots',
            autoSaveBaseline: true,
            hideScrollBars: true,
            scaleImagesToSameSize: true,
            ignoreAntialiasing: true,
            ignoreAlpha: true
        }]
    ],
    seleniumLogs: 'logs',
    seleniumInstallArgs: {
        version : "3.9.1",
        baseURL : "https://selenium-release.storage.googleapis.com",
        drivers : {
          chrome : {
            version : "87.0.4280.20",
            arch    : process.arch,
            baseURL : "https://chromedriver.storage.googleapis.com",
          }
        }
      },
      seleniumArgs: {
        version : "3.9.1",
        drivers : {
          chrome : {
            version : "87.0.4280.20",
            arch    : process.arch,
          }
        }
      },

    framework: 'cucumber',

    cucumberOpts: {
        require: ['./steps/*.js'],        // <string[]> (file/dir) require files before executing features
        backtrace: false,   // <boolean> show full backtrace for errors
        compiler: [],       // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        dryRun: false,      // <boolean> invoke formatters without executing steps
        failFast: false,    // <boolean> abort the run on first failure
        format: ['pretty'], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        colors: true,       // <boolean> disable colors in formatter output
        snippets: true,     // <boolean> hide step definition snippets for pending steps
        source: true,       // <boolean> hide source URIs
        profile: [],        // <string[]> (name) specify the profile to use
        strict: false,      // <boolean> fail if there are any undefined or pending steps
        name: [],           // Only execute the scenarios with name matching the expression (repeatable)
        tagsInTitle: [],    //add tag to your feature name in reports
        // tagExpression: [],   // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: "not @pending and not @broken and not @redundant and not @outdated and not @charge and not @defect",
        timeout: 1000000,      // <number> timeout for step definitions
        ignoreUndefinedDefinitions: false, // <boolean> Enable this config to treat undefined definitions as warnings.
    },

    reporters: ['spec',
        ['allure', {
        outputDir: './reports/allure-results',
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: true,
        useCucumberStepReporter: true
        }]
    ],
```

package.json:

```"devDependencies": {
    "@rpii/wdio-html-reporter": "^0.7.3",
    "@wdio/allure-reporter": "^5.12.1",
    "@wdio/appium-service": "^5.11.4",
    "@wdio/cli": "^5.12.5",
    "@wdio/cucumber-framework": "^5.12.3",
    "@wdio/junit-reporter": "^5.11.0",
    "@wdio/local-runner": "^5.12.5",
    "@wdio/selenium-standalone-service": "^5.12.1",
    "@wdio/spec-reporter": "^5.12.1",
    "@wdio/sync": "^5.12.3",
    "appium": "^1.14.0",
    "secure-env": "^1.2.0",
    "wdio-chromedriver-service": "^5.0.2",
    "wdio-image-comparison-service": "^1.8.0",
    "wdio-intercept-service": "^4.1.2"
  },
  "dependencies": {
    "chai": "^4.2.0",
    "cjson": "^0.5.0",
    "clipboardy": "^2.3.0",
    "dayjs": "^1.9.6",
    "madge": "^4.0.0",
    "node-fetch": "^2.6.1",
    "wdio-video-reporter": "^2.0.0"
  }
```

Sorry I can't provide a working version, but will give a basic example.  

```
Scenario Outline: Search for <search_term>

Given the user is on the "google search" page
When the user searches for "<search_term>" on the "google search" page
Then the search results for "<search_term>" are displayed on the "google search" page

@javascript
Examples:
| search_term |
| javascript     |

@python
Examples:
| search_term |
| python         |
```

Throws the error:

``` 
ERROR @wdio/local-runner: Failed launching test session: TypeError: args[0].endsWith is not a function
    at Object.values.filter.x (C:\Workspace\webdriverio-test\TOMN\node_modules\webdriverio\node_modules\@wdio\logger\build\node.js:63:62)
    at Array.filter (<anonymous>)
    at Logger.args [as error] (C:\Workspace\webdriverio-test\TOMN\node_modules\webdriverio\node_modules\@wdio\logger\build\node.js:63:42)
    at Runner.run (C:\Workspace\webdriverio-test\TOMN\node_modules\@wdio\runner\build\index.js:129:11)
[0-0] FAILED in chrome -<path\to\feature\file>
```

This error occurs even though the scenario runs and passes.  If there is only a single examples table, passing the param in from the examples works as expected with no issues.

**Comment by christian-bromann** [comment]
@pyxis828 I am sorry, we have deprecated v5 and don't support it anymore. We recommend upgrading to v6.
