### ISSUE TITLE
The JUnit Reporter does not contain any testcases for Cucumber tests

### ISSUE THREAD

**Issue by SciWiFi** [webdriverio/webdriverio#6452]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.4
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.13.4
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service, @wdio/junit-reporter, @wdio/cucumber-framework

**Describe the bug**
After the upgrade to v7 of WDIO, the JUnit Report for Cucumber no longer contains test cases.

**To Reproduce**
Run the following commands:
```
npm init -y
npm install @wdio/cli
npx wdio config
```

For the config the following is chosen:
```
? Where is your automation backend located? On my local machine
? Which framework do you want to use? cucumber
? Do you want to run WebdriverIO commands synchronous or asynchronous? sync
? Are you using a compiler? TypeScript (https://www.typescriptlang.org/)
? Where are your feature files located? ./features/**/*.feature
? Where are your step definitions located? ./features/step-definitions/steps.ts
? Do you want WebdriverIO to autogenerate some test files? Yes
? Do you want to use page objects (https://martinfowler.com/bliki/PageObject.html)? (Y/n) Yes
? Where are your page objects located? ./features/pageobjects/**/*.ts
? Which reporter do you want to use? junit
? Do you want to add a service to your test setup? selenium-standalone
? What is the base url? http://localhost
```

The `wdio.conf.js` contains this reporter configuration:
```
reporters: [
        ['junit', {
            outputDir: "./results"
        }]
    ]
```

When running the tests with `npx wdio run wdio.conf.js` the report does not contain any test cases:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="The Internet Guinea Pig Website" timestamp="2021-02-16T17:02:47" time="5.998" tests="0" failures="0" errors="0" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="featureName" value="The Internet Guinea Pig Website"/>
      <property name="capabilities" value="chrome.88_0_4324_150.windows"/>
      <property name="featureFile" value=".\features\login.feature"/>
    </properties>
  </testsuite>
</testsuites>
```

**Expected behavior**
The report should contain `<testcase>` tags inside the `<testsuite>` for each cucumber scenario.

**Comment by AutomationReddy** [comment]
@christian-bromann @SciWiFi I have changed few lines and able to get the results: Need sometime to push the code. 

@SciWiFi Can you paste the example xml file with cucumber results which was working earlier?

```<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Example feature" timestamp="2021-02-17T11:59:39" time="4.978" tests="3" failures="1" errors="1" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="featureName" value="Example feature"/>
      <property name="capabilities" value="chrome.88_0_4324_182.macosx"/>
      <property name="featureFile" value="./cucumber/features/my-feature.feature"/>
    </properties>
    <testcase classname="CucumberJUnitReport-chrome.88_0_4324_182.macosx.Example feature" name="Get size of an element" time="2.689">
      <failure/>
      <error message="Error: [2mexpect([22m[31mreceived[39m[2m).[22mtoBe[2m([22m[32mexpected[39m[2m) // Object.is equality[22m"/>
      <system-out><![CDATA[
✅ I go on the website "https://github.com/"❗ should the element ".header-logged-out a" be 32px wide and 34px high
]]></system-out>
      <system-err><![CDATA[
Error: [2mexpect([22m[31mreceived[39m[2m).[22mtoBe[2m([22m[32mexpected[39m[2m) // Object.is equality[22m

Expected: [32m34[39m
Received: [31m35[39m
    at World.<anonymous> (/Users/vinodreddy/Opensource/webdriverio/examples/wdio/cucumber/step-definitions.js:33:29)
    at World.executeSync (/Users/vinodreddy/Opensource/webdriverio/packages/wdio-sync/src/index.ts:39:22)
    at /Users/vinodreddy/Opensource/webdriverio/packages/wdio-sync/src/index.ts:74:33
]]></system-err>
    </testcase>
    <testcase classname="CucumberJUnitReport-chrome.88_0_4324_182.macosx.Example feature" name="Get title of website" time="0.643">
      <system-out><![CDATA[
✅ I go on the website "https://github.com/"✅ should the title of the page be "GitHub: Where the world builds software · GitHub"
]]></system-out>
    </testcase>
    <testcase classname="CucumberJUnitReport-chrome.88_0_4324_182.macosx.Example feature" name="Data Tables" time="1.628">
      <system-out><![CDATA[
✅ I go on the website "http://todomvc.com/examples/react/#/"✅ I add the following grocieries✅ I should have a list of 4 items
]]></system-out>
    </testcase>
  </testsuite>
</testsuites>
```

**Comment by SciWiFi** [comment]
@AutomationReddy here is the xml (v6.12.1)

```<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="The_Internet_Guinea_Pig_Website" timestamp="2021-02-04T12:44:21" time="8.622" tests="2" failures="0" errors="0" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="featureName" value="The Internet Guinea Pig Website"/>
      <property name="capabilities" value="chrome.88_0_4324_104.windows"/>
      <property name="featureFile" value=".\features\login.feature"/>
    </properties>
    <testcase classname="CucumberJUnitReport-chrome.88_0_4324_104.windows.The_Internet_Guinea_Pig_Website" name="The_Internet_Guinea_Pig_Website.As_a_user_I_can_log_into_the_secure_area" time="6.737">
      <system-out>
        <![CDATA[
✅ Given I am on the login page✅ When I login with tomsmith and SuperSecretPassword!✅ Then I should see a flash message saying You logged into a secure area!
]]>
      </system-out>
    </testcase>
    <testcase classname="CucumberJUnitReport-chrome.88_0_4324_104.windows.The_Internet_Guinea_Pig_Website" name="The_Internet_Guinea_Pig_Website.As_a_user_I_can_log_into_the_secure_area" time="1.871">
      <system-out>
        <![CDATA[
✅ Given I am on the login page✅ When I login with foobar and barfoo✅ Then I should see a flash message saying Your username is invalid!
]]>
      </system-out>
    </testcase>
  </testsuite>
</testsuites>```

**Comment by AutomationReddy** [comment]
@SciWiFi I have also noticed that current version is not reporting the failure count in xml if you have any failures. It only provides you the error=1/2/3 but not failure. I have fixed this as well. Need to add tests.

**Comment by igivon** [comment]
yes the this.suites is in reverse order and feature suite should be first 

![image](https://user-images.githubusercontent.com/7386112/108181418-8fbee580-7110-11eb-97e0-528ddfb02ed8.png)

did anyone commit a fix?

**Comment by wswebcreation** [comment]
There are some changes in the way that Cucumber reports back data. This might be broken for a lot of reporters and we need to look at them one by one.
I've created a [PR](https://github.com/webdriverio/webdriverio/pull/6453) to get at least the keyword back in the logs, which was missing in Allure, Spec and other reporters. We might need to fix more so it would be great to have a sample project that holds a few simple features/scenarios that are working in V6 and not in V7. 
Can someone do that, then I might have some time this/next week to see if we can fix this

**Comment by AutomationReddy** [comment]
Yes, this.suites is the issue. I have fixed it but the solution is not robust (First get the feature and build the xml and then one more call with the same suites to the same method where scenarios will be build)

@wswebcreation @christian-bromann if you are good with this approach, I will make a PR for this:
```
// there should only be one spec file per runner so we can safely take the first element of the array
        const specFileName = runner.specs[0];

        for (let suiteKey of Object.keys(this.suites)) {
            /**
             * ignore root before all
             */
            /* istanbul ignore if  */
            if (suiteKey.match(/^"before all"/)) {
                continue;
            }
            const suite = this.suites[suiteKey];
            if (isCucumberFrameworkRunner && suite.type === `feature`) {
                builder = this._addCucumberFeatureToBuilder(builder, runner, specFileName, suite);
            }
            else if(!isCucumberFrameworkRunner){
                builder = this._addSuiteToBuilder(builder, runner, specFileName, suite);
            }
        }
        if(isCucumberFrameworkRunner){
            for (let suiteKey of Object.keys(this.suites)) {
                if (suiteKey.match(/^"before all"/)) {
                    continue;
                }
                // there should only be one spec file per runner so we can safely take the first element of the array
                const suite = this.suites[suiteKey];
                if(suite.type === `scenario`) {
                    builder = this._addCucumberFeatureToBuilder(builder, runner, specFileName, suite);
                }
            }
        }
        return builder.build();
    }
```

This fix is not included for Given, When and Then keywords.

**Comment by wswebcreation** [comment]
@AutomationReddy 

Yes, if you want you can create a Pr for this. Can you then also add Unit tests to verify this adjusted functionality

**Comment by AutomationReddy** [comment]
#6464

**Comment by christian-bromann** [comment]
Let's continue convo in #6464
