### ISSUE TITLE
Webdriver io v6 throws error for import node.js modules

### ISSUE THREAD

**Issue by yanivyu1** [webdriverio/webdriverio#6463]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.11
 - **Mode:** [Standalone mode or WDIO Testrunner] testrunner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** [e.g. 8.11.2] 12
 - **NPM version:** [e.g. 5.8.0] 7.5
 - **Browser name and version:** [e.g. Chrome 68] chroem 88
 - **Platform name and version:** [e.g. Windows 10] macOs
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service] babel

**Config of WebdriverIO**
mochaOpts: {
        ui: 'bdd',
        timeout: 450000,
        require:['@babel/register']
    },

**Describe the bug**
i have internal node.js modules and i use import statement instead of require, in v5 it's working, in v6 i get this error:
Error: TypeError: Cannot read property 'getIntegrationUserNameAndPassword' of undefined
    at Object.<anonymous> (/Users/yaniv.yungerman/Projects/dozi-apps-web-growui-ng5/e2e/specs/Integration/users.js:11:42)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._compile (/Users/yaniv.yungerman/Projects/dozi-apps-web-growui-ng5/node_modules/pirates/lib/index.js:99:24)
    at Module.m._compile (/Users/yaniv.yungerman/Projects/dozi-apps-web-growui-ng5/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at require.extensions.<computed> (/Users/yaniv.yungerman/Projects/dozi-apps-web-growui-ng5/node_modules/ts-node/src/index.ts:1059:12)
    at Object.newLoader [as .js] (/Users/yaniv.yungerman/Projects/dozi-apps-web-growui-ng5/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at MochaAdapter._loadFiles (/Users/yaniv.yungerman/Projects/dozi-apps-web-growui-ng5/node_modules/@wdio/mocha-framework/build/index.js:66:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**To Reproduce**
use "import from " for node module instead of require

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
This seems to be pretty specific to user code:

```
Error: TypeError: Cannot read property 'getIntegrationUserNameAndPassword' of undefined
    at Object.<anonymous> (/Users/yaniv.yungerman/Projects/dozi-apps-web-growui-ng5/e2e/specs/Integration/users.js:11:42)
```

There is no chance to identify where there can be an issue in WebdriverIO. I ask you to debug this bug and report again once you can identify the bug in WebdriverIO. Major version updates often come with breaking changes. Make sure you read the changelog and understand what has changed. Checkout our [Jasmine boilerplate](https://github.com/webdriverio/jasmine-boilerplate) which uses Babel without issues.
