### ISSUE TITLE
wdio-0-0-allure-reporter.log  under allure-results causing trouble when scripts are executed in Parallel

### ISSUE THREAD

**Issue by UsharaniA** [webdriverio/webdriverio#6542]
Hi,
Am using the allure report for Webdriverio and using the version "@wdio/allure-reporter": "^6.11.0"

wdio.conf.js settings:

 reporters: [['allure',
        {
            outputDir: 'allure-results',
            useCucumberStepReporter: true,
            
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: true,
           issueLinkTemplate:{},
           tmsLinkTemplate:{}
        }]
    ],

when I execute multiple test case in parallel I see the below error message .

I notice the wdio-0-0-allure-reporter.log file gets created at the start of every test case and it gets deleted at the end of execution  also there are no contents inside the log file.
So when multiple test case executes it is trying to create the wdio-0-0-allure-reporter.log file for every test case and throwing below error

Kindly help me how to remove this file creation or rename the file by time stamp.

Error: EPERM: operation not permitted, open 'C:\gitNodeJS\art-automation-test\ATAF\allure-results\wdio-0-0-allure-reporter.log'
Emitted 'error' event at:
    at C:\ATAF\node_modules\@wdio\allure-reporter\node_modules\graceful-fs\graceful-fs.js:303:14
    at C:\ATAF\node_modules\@wdio\allure-reporter\node_modules\graceful-fs\graceful-fs.js:333:16
    at FSReqWrap.oncomplete (fs.js:141:20)

**Comment by christian-bromann** [comment]
Can you provide a reproducible example? Also have you tried running this in v7?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
