### ISSUE TITLE
TypeError: Launcher is not a constructor After upgrade webdriverio from Version4 to version5/v7 

### ISSUE THREAD

**Issue by xinxin11** [webdriverio/webdriverio#6552]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.0.9]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [14.16.0]
 - **NPM version:** [6.14.11]
 - **Browser name and version:** [Chrome 83]
 - **Platform name and version:** [mac os]
 - **Additional wdio packages used (if applicable):** [@wdio/cucumber-framework,@wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

```
exports.config = {
  suites: {
    instanceOverview: [
     './test/features/Test.feature',
    ],
  },
  services: ['selenium-standalone'],
  exclude: [
  ],

  firefoxProfile: {
  //  extensions: ['/path/to/extensionA.xpi', '/path/to/extensionB.xpi'],
  //  'browser.startup.homepage': 'http://webdriver.io'
      'browser.helperApps.neverAsk.openFile': 'application/zip,text/plain,application/vnd.ms-excel,text/csv,text/comma-separated-values,application/octet-stream,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'browser.helperApps.neverAsk.saveToDisk': 'application/zip,text/plain,application/vnd.ms-excel,text/csv,text/comma-separated-values,application/octet-stream,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  },
  //
  // ============
  // Capabilities
  // ============
  // Define your capabilities here. WebdriverIO can run multiple capabilities
  // at the same time. Depending on the number of capabilities, WebdriverIO
  // launches several test sessions. Within your capabilities you can
  // overwrite the spec and exclude options in order to group specific specs
  // to a specific capability.
  //
  // First, you can define how many instances should be started at the same
  // time. Let's say you have 3 different capabilities (Chrome, Firefox, and
  // Safari) and you have set maxInstances to 1; wdio will spawn 3 processes.
  // Therefore, if you have 10 spec files and you set maxInstances to 10, all
  // spec files will get tested at the same time and 30 processes will get
  // spawned. The property handles how many capabilities from the same test
  // should run tests.
  //
  maxInstances: 1,
  //
  // If you have trouble getting all important capabilities together, check
  // out the Sauce Labs platform configurator - a great tool to configure your
  // capabilities: https://docs.saucelabs.com/reference/platforms-configurator
  //
  capabilities: [
    {
 
      browserName: 'chrome',
          'goog:chromeOptions': {
             args: ['--no-sandbox','window-size=2880,1800'],
           },
      },
    },
  ],
  sync: true,
  
  logLevel: 'silent',

  coloredLogs: true,
  
  screenshotPath: './reports/errorShots/',
  
  baseUrl: 'https://console-ondeck.stage1.bluemix.net',
  
  connectionRetryTimeout: 90000,

  connectionRetryCount: 3,
  framework: 'cucumber',
  reporters: ['spec','junit','json-cucumber'],
  reporterOptions: {
    outputDir: 'reports/test/',
    cucumberJsonReporter: {
            silent: false, // true|false - supresses message notifying of report output
            baseDir: './', // Should be your project's root directory, used to determine where your feature files are stored
            deviceName: 'CIS UI test environment' // Meta data for multiple-cucumber-html-reporter
    },
  },
  // If you are using Cucumber you need to specify the location of your step
  // definitions.
  cucumberOpts: {
    require: [
      './test/steps/login.js',
      './test/steps/catalog.js',
      './test/steps/gettingStart.js',
    ], // <string[]> (file/dir) require files before executing features
    backtrace: false, // <boolean> show full backtrace for errors
    compiler: [
      'js:babel-register',
    ], 
    dryRun: false, // <boolean> invoke formatters without executing steps
    failFast: false, // <boolean> abort the run on first failure
    format: ['pretty'], // <string[]> (type[:path]) specify the output
                            // format, optionally supply PATH to redirect
                            // formatter output (repeatable)
    colors: true, // <boolean> disable colors in formatter output
    snippets: true, // <boolean> hide step definition snippets for pending
                        // steps
    source: true, // <boolean> hide source uris
    profile: [], // <string[]> (name) specify the profile to use
    strict: true, // <boolean> fail if there are any undefined or pending
                       // steps
    timeout: 900000,     // <number> timeout for step definitions
    ignoreUndefinedDefinitions: false, // <boolean> Enable this config to
                                           // treat undefined definitions as
                                           // warnings.
  },

  //
  // =====
  // Hooks
  // =====
  // WebdriverIO provides several hooks you can use to interfere with the test
  // process in order to enhance it and to build services around it. You can
  // either apply a single function or an array of methods to it. If one of
  // them returns with a promise, WebdriverIO will wait until that promise got
  // resolved to continue.
  //
  // Gets executed once before all workers get launched.
  onPrepare: function onPrepare(config, capabilities) {
   },
  //
  // Gets executed before test execution begins. At this point you can access
  // all global variables, such as `browser`. It is the perfect place to
  // define custom commands.
  before: function before() {
    // Setup the Chai assertion framework
    const chai = require('chai');
    global.expect = chai.expect;
    global.assert = chai.assert;
    global.should = chai.should();
  },
  
};
```

**Describe the bug**
my UI test automation is running based on WebdriverIO V4.9 and node V6 , But now it need to upgrade to node 14,  Also the WebdriverIO  is need to upgrade to V7, but there is no Launcher in the new WebdriverIO Version,  Could someone can tell how to replace the  Launcher in the new WebdriverIO ? or any other practical solutions？

**To Reproduce**
```
const Launcher = require('webdriverio').Launcher;
......
......

gulp.task('test', () => {
  //console.log("debug");
  return new Launcher(wdioConfig, {
    baseUrl,
    suite: 'instanceOverview',
    cucumberOpts: {
      tags,
    },
  }).run().then((code) => {
    process.exit(code);
  }, (error) => {
    console.error('Launcher failed to start the test', error.stacktrace);
    process.exit(1);
  })
});

```

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

```
> gulp test "-t" "@mini"

[ '@mini' ]
[11:27:44] Using gulpfile ~/UI_E2E/gulpfile.js
[11:27:44] Starting 'test'...
debug
[11:27:44] 'test' errored after 2.9 ms
[11:27:44] TypeError: Launcher is not a constructor
    at /Users/cindy/UI_E2E/gulpfile.js:68:10
    at test (/Users/cindy/UI_E2E/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:413:15)
    at runBound (domain.js:424:12)
    at asyncRunner (/Users/cindy/UI_E2E/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Please see the docs: https://webdriver.io/docs/clioptions/#run-the-test-runner-programmatically
