### ISSUE TITLE
'$' method translates to wrong selector in Android (native app) session.

### ISSUE THREAD

**Issue by bgalamb** [webdriverio/webdriverio#6553]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.10.5 
 - **Mode:** Standalone
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async]
 - **Node.js version:** v15.3.0
 - **NPM version:** 7.0.14
 - **Browser name and version:** 
 - **Platform name and version:** MacOs 10.15.7
 - **Additional wdio packages used (if applicable):** 

**Config of WebdriverIO**
Config for webdriver for appium session.
```
this.client=remote(adr_config)
(...)
export const android_local_config: RemoteOptions = {
	capabilities: {
		platformName: 'Android',
		automationName: 'UiAutomator2',
		app:
			process.env.ADR_APP_PATH ||
			'https://xxxxx.apk',
		optionalIntentArguments:
			"--es customServerName '" +
			process.env.CUSTOM_SERVER_NAME +
			"' --es customServerOrigin '" +
			process.env.CUSTOM_SERVER_ORIGIN +
			"' --es customServerDomain '" +
			process.env.CUSTOM_SERVER_DOMAIN +
			"' --es customServerCookieClientVersion '" +
			process.env.CUSTOM_SERVER_CLIENT_VERSION +
			"' --es customServerCookieClientHost '" +
			process.env.CUSTOM_SERVER_CLIENT_HOST +
			"' --es customServerCookieClientPort '" +
			process.env.CUSTOM_SERVER_CLIENT_PORT +
			"' --es customServerCookieServerName '" +
			process.env.CUSTOM_SERVER_SERVER_NAME +
			"'",
	},
	waitforTimeout: 15000,
	logLevel: 'debug',
	port: 4723,
	path: '/wd/hub',
}
```

**Describe the bug**
It seems that the '$' built in class_name selector is not working for mobile.
The android example from document https://webdriver.io/docs/selectors#class-name does not work as expected.

I have following code, where two searches are chained. As per the code comments, the first gets resolved correctly to find **by_accessibility_id**, but the second search is done **by_ss_selector** which is not implemented in appium and causes the test to fail.

```
newsletter_toggle(): Promise<WebdriverIO.Element> {
        return this.client
            .$('~policy_toggle')   // gets resolved to locator strategy: accessibility selector-> ok
            .then(element => element.$('android.view.ViewGroup'))  //  gets resolved to locator strategy: css selector ?!
    }
```

but the below also fails with the same:
```
await this.client.$('android.view.ViewGroup')
```

Whereas if I send the request with postman then the element is found
```
POST http://localhost:4723/wd/hub/session/ba9b709c-3b67-4dec-88d6-54e44f9a6073/element/2a8f10eb-ab47-4d96-aa6d-9a187f6759be/element

{"using":"class name","value":"android.view.ViewGroup"}

```

So it looks like it is the webdriverio which is sending wrong request:

```
POST http://localhost:4723/wd/hub/session/01ba4674-c772-441f-9520-90220f0c1b09/element/63c7ccc0-fe28-476e-a7d8-d11eef5a58fc/element
{ using: 'css selector', value: 'android.view.ViewGroup' }
```

see logs in logs section.

**To Reproduce**
Install appium
download sample repo: https://github.com/appium/appium/tree/master/sample-code/javascript-webdriverio
and follow instructions.
Change the code to add a find an element by class name with '$' 

**Expected behavior**
I would expect that in case I use:
`await client.$('android.view.ViewGroup').click()` eventually gets translated to HTTP Call:

`COMMAND` findElementFromElement("63c7ccc0-fe28-476e-a7d8-d11eef5a58fc", "class selector", "android.view.ViewGroup")`

**Log**
```
/////LOGS/////
console.info
    2021-03-03T16:40:43.469Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session/01ba4674-c772-441f-9520-90220f0c1b09/element
      at node_modules/@wdio/logger/build/node.js:76:9
  console.info
    2021-03-03T16:40:43.469Z INFO webdriver: DATA { using: 'accessibility id', value: 'policy_toggle' }
      at node_modules/@wdio/logger/build/node.js:76:9
  console.info
    2021-03-03T16:40:43.494Z INFO webdriver: RESULT {
      'element-6066-11e4-a52e-4f735466cecf': '63c7ccc0-fe28-476e-a7d8-d11eef5a58fc',
      ELEMENT: '63c7ccc0-fe28-476e-a7d8-d11eef5a58fc'
    }
      at node_modules/@wdio/logger/build/node.js:76:9
  console.info
    2021-03-03T16:40:43.498Z INFO webdriver: COMMAND findElementFromElement("63c7ccc0-fe28-476e-a7d8-d11eef5a58fc", "css selector", "android.view.ViewGroup")
      at node_modules/@wdio/logger/build/node.js:76:9

  console.info
    2021-03-03T16:40:43.499Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session/01ba4674-c772-441f-9520-90220f0c1b09/element/63c7ccc0-fe28-476e-a7d8-d11eef5a58fc/element
      at node_modules/@wdio/logger/build/node.js:76:9
  console.info
    2021-03-03T16:40:43.499Z INFO webdriver: DATA { using: 'css selector', value: 'android.view.ViewGroup' }
    console.log
    2021-03-03T16:40:43.504Z DEBUG webdriver: request failed due to response error: invalid selector
      at node_modules/@wdio/logger/build/node.js:76:9
  console.warn
    2021-03-03T16:40:43.511Z WARN webdriver: Request failed with status 400 due to Locator Strategy 'css selector' is not supported for this session

      at node_modules/@wdio/logger/build/node.js:76:9
      at Logger.warn (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
      at retry (node_modules/webdriver/build/request.js:121:17)
      at WebDriverRequest._request (node_modules/webdriver/build/request.js:150:16)
      at Element.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:58:29)
      at Element.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:58:29)


```

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@bgalamb currently only a [certain amount](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/utils/findStrategy.ts#L12-L14) of class name prefixes are supported. That list need to be enhanced to include `android.view.`. Any contributions would be appreciated.

**Comment by vishanthQA** [comment]
i would like to pick this issue

**Comment by bgalamb** [comment]
sure, thank you!
