### ISSUE TITLE
Error: Could not find job when running the UI E2E test

### ISSUE THREAD

**Issue by xinxin11** [webdriverio/webdriverio#6561]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.1.0]
 - **Mode:** [Standalone mode]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [14.16.0]
 - **NPM version:** [6.14.11]
 - **Browser name and version:** [Chrome 87]
 - **Platform name and version:** [mac os]
 - **Additional wdio packages used (if applicable):** [@wdio/cli,@wdio/cucumber-framework,@wdio/local-runner": "^6.12.1",
    "@wdio/sauce-service": "^6.3.6",
    "@wdio/selenium-standalone-service": "^6.11.0",
    "@wdio/spec-reporter": "^6.3.6",
    "@wdio/sync": "^7.1.0",]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

```
exports.config = {
  suites: {
    instanceOverview: [
     './test/features/TEST.feature'
    ],
  },
  services: ['selenium-standalone'],
//  services: ['sauce','firefox-profile'],
//  user: 'username',
//  key: 'keyid',
//  sauceConnect: true,
  exclude: [
  ],

  firefoxProfile: {
  //  extensions: ['/path/to/extensionA.xpi', '/path/to/extensionB.xpi'],
  //  'browser.startup.homepage': 'http://webdriver.io'
      'browser.helperApps.neverAsk.openFile': 'application/zip,text/plain,application/vnd.ms-excel,text/csv,text/comma-separated-values,application/octet-stream,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'browser.helperApps.neverAsk.saveToDisk': 'application/zip,text/plain,application/vnd.ms-excel,text/csv,text/comma-separated-values,application/octet-stream,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  },
  //
  // ============
  // Capabilities
  // ============
  // Define your capabilities here. WebdriverIO can run multiple capabilities
  // at the same time. Depending on the number of capabilities, WebdriverIO
  // launches several test sessions. Within your capabilities you can
  // overwrite the spec and exclude options in order to group specific specs
  // to a specific capability.
  //
  // First, you can define how many instances should be started at the same
  // time. Let's say you have 3 different capabilities (Chrome, Firefox, and
  // Safari) and you have set maxInstances to 1; wdio will spawn 3 processes.
  // Therefore, if you have 10 spec files and you set maxInstances to 10, all
  // spec files will get tested at the same time and 30 processes will get
  // spawned. The property handles how many capabilities from the same test
  // should run tests.
  //
  maxInstances: 1,
  //
  // If you have trouble getting all important capabilities together, check
  // out the Sauce Labs platform configurator - a great tool to configure your
  // capabilities: https://docs.saucelabs.com/reference/platforms-configurator
  //
  capabilities: [
    {
      pageLoadStrategy: 'normal', // normal eager none
      // maxInstances can get overwritten per capability. So if you have an
      // in-house Selenium grid with only 5 firefox instance available you can
      // make sure that not more than 5 instance gets started at a time.
      maxInstances: 1,
      browserName: 'chrome',
        //  chromeOptions: {
        //     args: ['--no-sandbox'],
          'goog:chromeOptions': {
             args: ['--no-sandbox','window-size=2880,1800'],
//	       args: ['--no-sandbox','--headless','--disable-gpu','window-size=2880,1800','--start-maximized'],
           },
      // proxy: {
      //   proxyType: 'manual',
      //   httpProxy: 'http://guan-vm2.swg.usma.ibm.com:3128',
      //   sslProxy: 'http://guan-vm2.swg.usma.ibm.com:3128',
      //   noProxy: 'localhost',
      // },
    },
    // {
    //   pageLoadStrategy: 'normal',
    //   maxInstances: 1,
    //   browserName: 'firefox',
    // },
  ],
  sync: true,
  //
  // Level of logging verbosity: silent | verbose | command | data | result |
  // error
  logLevel: 'silent',
  // logOutput: './reports/',
  //
  // Enables colors for log output.
  coloredLogs: true,
  //
  // Saves a screenshot to a given path if a command fails.
  screenshotPath: './reports/errorShots/',
  //
  // Set a base URL in order to shorten url command calls. If your url
  // parameter starts with "/", then the base url gets prepended.
  baseUrl: 'https://console-ondeck.stage1.bluemix.net',
  //
  // Default timeout for all waitFor* commands.
  waitforTimeout: 300000,
  //
  // Default timeout in milliseconds for request
  // if Selenium Grid doesn't send response
  connectionRetryTimeout: 90000,
  //
  // Default request retries count
  connectionRetryCount: 3,
  framework: 'cucumber',
  reporters: ['spec','junit','json-cucumber'],
  reporterOptions: {
    outputDir: 'reports/test/',
    cucumberJsonReporter: {
            silent: false, // true|false - supresses message notifying of report output
            baseDir: './', // Should be your project's root directory, used to determine where your feature files are stored
            deviceName: 'PDNS UI test environment' // Meta data for multiple-cucumber-html-reporter
    },
  },
  specs: [
    './test/steps/login.js',
    './test/steps/gettingStart.js',
],
  // If you are using Cucumber you need to specify the location of your step
  // definitions.
  
  cucumberOpts: {
    require: [
      './test/steps/login.js',
      './test/steps/gettingStart.js',
    ], // <string[]> (file/dir) require files before executing features
    backtrace: false, // <boolean> show full backtrace for errors
    compiler: [
      'js:babel-register',
    ], // <string[]> ("extension:module") require files with the given
           // EXTENSION after requiring MODULE (repeatable)
    dryRun: false, // <boolean> invoke formatters without executing steps
    failFast: false, // <boolean> abort the run on first failure
    format: ['pretty'], // <string[]> (type[:path]) specify the output
                            // format, optionally supply PATH to redirect
                            // formatter output (repeatable)
    colors: true, // <boolean> disable colors in formatter output
    snippets: true, // <boolean> hide step definition snippets for pending
                        // steps
    source: true, // <boolean> hide source uris
    profile: [], // <string[]> (name) specify the profile to use
    strict: true, // <boolean> fail if there are any undefined or pending
                       // steps
    timeout: 900000,     // <number> timeout for step definitions
    ignoreUndefinedDefinitions: false, // <boolean> Enable this config to
                                           // treat undefined definitions as
                                           // warnings.
  },
};

```

**Describe the bug**

When I run the test, I got "Error: Could not find job", I don't know what I missed, Could you help to look at this issue?

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

```

[16:36:14] Using gulpfile ~/Test/e2e/gulpfile.js
[16:36:14] Starting 'test'...
Execution of 6 spec files started at 2021-03-08T08:36:14.975Z
[16:36:26] 'test' errored after 12 s
[16:36:26] Error: Could not find job
    at WDIOCLInterface.clearJob (/Test/e2e/node_modules/@wdio/cli/build/interface.js:127:19)
    at WDIOCLInterface.emit (events.js:315:20)
    at WDIOCLInterface.EventEmitter.emit (domain.js:529:15)
    at Launcher.endHandler (/Test/e2e/node_modules/@wdio/cli/build/launcher.js:222:28)
    at WorkerInstance.emit (events.js:315:20)
    at WorkerInstance.EventEmitter.emit (domain.js:529:15)
    at WorkerInstance._handleExit (/Test/e2e/node_modules/@wdio/local-runner/build/worker.js:93:14)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:529:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

```

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@xinxin11 can you provide a minimal reproducible example?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
