### ISSUE TITLE
json-reporter installation is failed

### ISSUE THREAD

**Issue by DenysBarkan** [webdriverio/webdriverio#6576]
**Environment:**
 - **WebdriverIO version:** 7.1.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.20.1
 - **NPM version:** 7.6.2
 - **Platform name and version:** MacOs 11.2.1
 - **Additional wdio packages used (if applicable):** @wdio/allure-reporter, @wdio/devtools-service, @wdio/local-runner, @wdio/mocha-framework, @wdio/spec-reporter, @wdio/sync, @wdio/types

```
    reporters: [
        'spec',
        ['json', {
            outputDir: './Results',
            outputFileFormat: function (opts) {
                return `results-${opts.cid}.${opts.capabilities}.json`
            }
        }],
    ]
```
**Describe the bug**
Json-reporter installation gives the ERROR:
```
# npm resolution error report
2021-03-10T14:09:32.291Z
While resolving: wdio7_testing@1.0.0
Found: @wdio/cli@7.1.1
node_modules/@wdio/cli
  dev @wdio/cli@"^7.1.1" from the root project
Could not resolve dependency:
peer @wdio/cli@"^6.0.15" from wdio-json-reporter@2.0.0
node_modules/wdio-json-reporter
  dev wdio-json-reporter@"*" from the root project
Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
Raw JSON explanation object:
{
  "code": "ERESOLVE",
  "current": {
    "name": "@wdio/cli",
    "version": "7.1.1",
    "whileInstalling": {
      "name": "wdio7_testing",
      "version": "1.0.0",
      "path": "/Users/denys.barkan/WDIO/wdio7_testing"
    },
    "location": "node_modules/@wdio/cli",
    "dependents": [
      {
        "type": "dev",
        "name": "@wdio/cli",
        "spec": "^7.1.1",
        "from": {
          "location": "/Users/denys.barkan/WDIO/wdio7_testing"
        }
      }
    ]
  },
  "edge": {
    "type": "peer",
    "name": "@wdio/cli",
    "spec": "^6.0.15",
    "error": "INVALID",
    "from": {
      "name": "wdio-json-reporter",
      "version": "2.0.0",
      "whileInstalling": {
        "name": "wdio7_testing",
        "version": "1.0.0",
        "path": "/Users/denys.barkan/WDIO/wdio7_testing"
      },
      "location": "node_modules/wdio-json-reporter",
      "dependents": [
        {
          "type": "dev",
          "name": "wdio-json-reporter",
          "spec": "*",
          "from": {
            "location": "/Users/denys.barkan/WDIO/wdio7_testing"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```

**To Reproduce**
1 way:
install according to the documentation:
`npm install wdio-json-reporter --save-dev`

or grab the project and install all the packages by `npm install`

https://github.com/DenysBarkan/wdio7_testing.git

**Expected behavior**
Installation is completed without issues

**Log**
```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   'wdio-json-reporter',
0 verbose cli   '--save-dev'
0 verbose cli ]
1 info using npm@7.6.2
2 info using node@v12.20.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/denys.barkan/WDIO/wdio7_testing/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/denys.barkan/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session ec41a72396254930
20 timing npm:load Completed in 12ms
21 timing arborist:ctor Completed in 2ms
22 timing idealTree:init Completed in 241ms
23 timing idealTree:userRequests Completed in 2ms
24 silly idealTree buildDeps
25 silly fetch manifest wdio-json-reporter@*
26 timing arborist:ctor Completed in 0ms
27 http fetch GET 304 https://registry.npmjs.org/wdio-json-reporter 702ms (from cache)
28 silly fetch manifest @wdio/cli@^7.1.1
29 http fetch GET 200 https://registry.npmjs.org/@wdio%2fcli 438ms
30 silly fetch manifest @wdio/cli@^6.0.15
31 timing idealTree Completed in 1398ms
32 timing command:install Completed in 1407ms
33 verbose stack Error: unable to resolve dependency tree
33 verbose stack     at Arborist.[failPeerConflict] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1143:25)
33 verbose stack     at Arborist.[loadPeerSet] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1120:34)
33 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:838:11)
33 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
33 verbose stack     at async Promise.all (index 1)
33 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
33 verbose stack     at async Install.install (/usr/local/lib/node_modules/npm/lib/install.js:120:5)
34 verbose cwd /Users/denys.barkan/WDIO/wdio7_testing
35 verbose Darwin 20.3.0
36 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "wdio-json-reporter" "--save-dev"
37 verbose node v12.20.1
38 verbose npm  v7.6.2
39 error code ERESOLVE
40 error ERESOLVE unable to resolve dependency tree
41 error
42 error While resolving: [1mwdio7_testing[22m@[1m1.0.0[22m
42 error Found: [1m@wdio/cli[22m@[1m7.1.1[22m[2m[22m
42 error [2mnode_modules/@wdio/cli[22m
42 error   [33mdev[39m [1m@wdio/cli[22m@"[1m^7.1.1[22m" from the root project
42 error
42 error Could not resolve dependency:
42 error [35mpeer[39m [1m@wdio/cli[22m@"[1m^6.0.15[22m" from [1mwdio-json-reporter[22m@[1m2.0.0[22m[2m[22m
42 error [2mnode_modules/wdio-json-reporter[22m
42 error   [33mdev[39m [1mwdio-json-reporter[22m@"[1m*[22m" from the root project
42 error
42 error Fix the upstream dependency conflict, or retry
42 error this command with --force, or --legacy-peer-deps
42 error to accept an incorrect (and potentially broken) dependency resolution.
42 error
42 error See /Users/denys.barkan/.npm/eresolve-report.txt for a full report.
43 verbose exit 1
```

**Comment by christian-bromann** [comment]
Please see #57

**Comment by DenysBarkan** [comment]
@christian-bromann I'm so sorry I didn't get you. I don't see any solution for the installation of the json-reporter in #54. 
The issue looks like the conflict between the version of the wdio and json-reporter. 
Maybe I miss something.

**Comment by DenysBarkan** [comment]
<img width="583" alt="Screen Shot 2021-03-10 at 4 33 43 PM" src="https://user-images.githubusercontent.com/45456152/110645136-639dfe00-81be-11eb-893d-7b2816c9798d.png">

**Comment by christian-bromann** [comment]
> Maybe I miss something.

Not sure but issues with the json reporter should be solved in that respective repository. Feel free to create a new issue there. Thanks!

**Comment by DenysBarkan** [comment]
@christian-bromann 
the downgrade of the npm version to version 6.14.10 solves the issue.
the installation returns warring but not the error:
`npm WARN wdio-json-reporter@2.0.0 requires a peer of @wdio/cli@^6.0.15 but none is installed. You must install peer dependencies yourself.`

**Comment by christian-bromann** [comment]
> wdio-json-reporter@2.0.0 requires a peer of @wdio/cli@^6.0.15

You are using v7 which is why I was referencing #57. Updating the JSON reporter shouldn't be a problem, would you mind taking a stab at it?
