### ISSUE TITLE
devtools-service does not work when browser.reloadSession() has been called

### ISSUE THREAD

**Issue by flunderpero** [webdriverio/webdriverio#6583]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 7.1.1]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Browser name and version:** [Chrome 89]
 - **Platform name and version:** [OSX Big Sur]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config

**Describe the bug**

**To Reproduce**
devtools-service throws an error on `browser.reloadSession()`:
```
Cannot delete property 'puppeteer' of #<Browser>
TypeError: Cannot delete property 'puppeteer' of #<Browser>
at DevToolsService.onReload (/Users/pero/src/pero/cling-main/node_modules/@wdio/devtools-service/build/index.js:51:21)
at Array.map (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Using the service afterwards (like `browser.emulateDevice`) fails with:

```
Protocol error (Network.setUserAgentOverride): Session closed. Most likely the page has been closed.
Error: Protocol error (Network.setUserAgentOverride): Session closed. Most likely the page has been closed.
at CDPSession.send (/Users/pero/src/pero/cling-main/node_modules/puppeteer-core/src/common/Connection.ts:251:9)
at NetworkManager.setUserAgent (/Users/pero/src/pero/cling-main/node_modules/puppeteer-core/src/common/NetworkManager.ts:184:24)
at Page.setUserAgent (/Users/pero/src/pero/cling-main/node_modules/puppeteer-core/src/common/Page.ts:1117:48)
at Page.emulate (/Users/pero/src/pero/cling-main/node_modules/puppeteer-core/src/common/Page.ts:1390:12)
at DevToolsService._emulateDevice (/Users/pero/src/pero/cling-main/node_modules/@wdio/devtools-service/build/index.js:144:27)
at Browser.next [as emulateDevice] (/Users/pero/src/pero/cling-main/node_modules/@wdio/utils/build/monad.js:149:33)
```

**Comment by BorisOsipov** [comment]
duplicate https://github.com/webdriverio/webdriverio/issues/6405
