### ISSUE TITLE
Unable to run tests against Safari Technology Preview(r122)

### ISSUE THREAD

**Issue by Askarov5** [webdriverio/webdriverio#6621]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6 and 7
 - **Mode:**  WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Node.js version:** 14.16.0
 - **NPM version:** 6.14.11
 - **Browser name and version:** Safari Technology Preview release 122
 - **Platform name and version:** Mac OS Big Sur v11.2.3
 - **Additional wdio packages used (if applicable):** ["@wdio/allure-reporter": "^7.2.1",
    "@wdio/cli": "^7.2.3",
    "@wdio/local-runner": "^7.2.3",
    "@wdio/mocha-framework": "^7.2.1",
    "@wdio/spec-reporter": "^7.2.1",
    "@wdio/sync": "^7.2.3",
    "chromedriver": "^89.0.0",
    "wdio-chromedriver-service": "^7.0.0"]

**Config of WebdriverIO**
capabilities: [{
maxInstances: 1, 
browserName: "safari technology preview", 
port: 4447
}]

**Describe the bug**
Not sure if configurations for Safari TP browser is changed, but it was running like this in webdriverio v6. Now, it's not running even in v6. I'm unable to Test on Safari Preview, because of the following error: 
ERROR webdriver: session not created: Could not create a session: A browser with name 'safari technology preview' version '(null)' could not be found on the system. What version needs to be added since Safari Preview has only release number?

**To Reproduce**
1.Setup configuration to run tests on Safari TP
2. Run them

**Expected behavior**
To run specs against the Safari Technology Preview

**Log**
[0-4] 2021-03-24T17:51:46.395Z INFO webdriver: Retrying 3/3
2021-03-24T17:51:46.395Z INFO webdriver: [POST] http://127.0.0.1:4447/session
[0-4] 2021-03-24T17:51:46.395Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'safari technology preview' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'safari technology preview' }
}
[0-4] 2021-03-24T17:51:46.439Z ERROR webdriver: Request failed with status 500 due to session not created: Could not create a session: A browser with name 'safari technology preview' version '(null)' could not be found on the system.
[0-4] 2021-03-24T17:51:46.439Z ERROR webdriver: session not created: Could not create a session: A browser with name 'safari technology preview' version '(null)' could not be found on the system.
    at Object.getErrorFromResponseBody (/Users/username/Desktop/git/cbd-wd/node_modules/webdriverio/node_modules/webdriver/build/utils.js:189:12)
    at WebDriverRequest._request (/Users/username/Desktop/git/cbd-wd/node_modules/webdriverio/node_modules/webdriver/build/request.js:168:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.startWebDriverSession (/Users/username/Desktop/git/cbd-wd/node_modules/webdriverio/node_modules/webdriver/build/utils.js:63:20)
    at async Function.newSession (/Users/username/Desktop/git/cbd-wd/node_modules/webdriverio/node_modules/webdriver/build/index.js:58:45)
    at async Object.exports.remote (/Users/username/Desktop/git/cbd-wd/node_modules/webdriverio/build/index.js:56:22)
    at async Runner._startSession (/Users/username/Desktop/git/cbd-wd/node_modules/@wdio/runner/build/index.js:202:56)
    at async Runner._initSession (/Users/username/Desktop/git/cbd-wd/node_modules/@wdio/runner/build/index.js:164:25)
    at async Runner.run (/Users/username/Desktop/git/cbd-wd/node_modules/@wdio/runner/build/index.js:87:19)
[0-4] 2021-03-24T17:51:46.440Z ERROR @wdio/runner: Error: Failed to create session.
Could not create a session: A browser with name 'safari technology preview' version '(null)' could not be found on the system.
    at Object.startWebDriverSession (/Users/username/Desktop/git/cbd-wd/node_modules/webdriverio/node_modules/webdriver/build/utils.js:68:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.newSession (/Users/username/Desktop/git/cbd-wd/node_modules/webdriverio/node_modules/webdriver/build/index.js:58:45)
    at async Object.exports.remote (/Users/username/Desktop/git/cbd-wd/node_modules/webdriverio/build/index.js:56:22)
    at async Runner._startSession (/Users/username/Desktop/git/cbd-wd/node_modules/@wdio/runner/build/index.js:202:56)
    at async Runner._initSession (/Users/username/Desktop/git/cbd-wd/node_modules/@wdio/runner/build/index.js:164:25)
    at async Runner.run (/Users/username/Desktop/git/cbd-wd/node_modules/@wdio/runner/build/index.js:87:19)
[0-4] FAILED in safari technology preview - /test/specs/renewWMD.test.js

**Additional context**

> Please use the correct markdown

**Comment by erwinheitzman** [comment]
You have installed the chromedriver, this is a setup for Chrome and not for cross browser testing

**Comment by christian-bromann** [comment]
You can find how to start Safaridriver here: https://webdriver.io/docs/driverbinaries/#safaridriver. Please let us know if you have further questions.

**Comment by Askarov5** [comment]
@erwinheitzman, Tests were running before with the same configurations. I don't know why it start to not working this week. And can you please, give me an example of the right configuration for Safari Technology Preview.
 
@christian-bromann , Safari T. Preview Driver is running on the given port. However, I'm getting the error shown above. I guess, it's not server issue. Looks like, it's a configuration issue. It was working before with the configurations.

**Comment by Askarov5** [comment]
I re-installed the Safari Preview and my previous configuration worked properly.

@erwinheitzman  Just an FYI: When I configured safari t preview capabilities as given [here](https://github.com/webdriverio/webdriverio/issues/4954) I got the following error, even if all safari instances have been closed and there was no any safari browser running in my machine:
[0-0] 2021-03-25T15:17:23.519Z WARN webdriver: Request failed with status 500 due to Could not create a session: The Safari instance is already paired with another WebDriver session.
[0-0] 2021-03-25T15:17:23.519Z INFO webdriver: Retrying 3/3
2021-03-25T15:17:23.519Z INFO webdriver: [POST] http://localhost:4444/session
2021-03-25T15:17:23.519Z INFO webdriver: DATA {
  capabilities: { alwaysMatch: { browserName: 'Safari' }, firstMatch: [ {} ] },
  desiredCapabilities: { browserName: 'Safari' }
}
[0-0] 2021-03-25T15:17:23.529Z ERROR webdriver: Request failed with status 500 due to session not created: Could not create a session: The Safari instance is already paired with another WebDriver session.
[0-0] 2021-03-25T15:17:23.529Z ERROR webdriver: session not created: Could not create a session: The Safari instance is already paired with another WebDriver session.
    at Object.getErrorFromResponseBody (/Users/username/Desktop/automated-tests/cm-webdriverio/node_modules/@wdio/runner/node_modules/webdriver/build/utils.js:94:12)
    at WebDriverRequest._request (/Users/username/Desktop/automated-tests/cm-webdriverio/node_modules/@wdio/runner/node_modules/webdriver/build/request.js:133:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.startWebDriverSession (/Users/username/Desktop/automated-tests/cm-webdriverio/node_modules/@wdio/runner/node_modules/webdriver/build/utils.js:29:20)
    at async Function.newSession (/Users/username/Desktop/automated-tests/cm-webdriverio/node_modules/@wdio/runner/node_modules/webdriver/build/index.js:30:45)
    at async Object.exports.remote (/Users/username/Desktop/automated-tests/cm-webdriverio/node_modules/@wdio/runner/node_modules/webdriverio/build/index.js:60:22)
    at async Runner._startSession (/Users/username/Desktop/automated-tests/cm-webdriverio/node_modules/@wdio/runner/build/index.js:128:56)
    at async Runner._initSession (/Users/username/Desktop/automated-tests/cm-webdriverio/node_modules/@wdio/runner/build/index.js:108:25)
    at async Runner.run (/Users/username/Desktop/automated-tests/cm-webdriverio/node_modules/@wdio/runner/build/index.js:52:19)
