### ISSUE TITLE
devtools service fails to work when switching windows

### ISSUE THREAD

**Issue by spatchamatla** [webdriverio/webdriverio#6627]
- **WebdriverIO version:7.2.3**
 - **@wdio/selenium-standalone-service: 7.2.1**
 - **@wdio/devtools-service: 7.2.3**
 - **Mode: Standalone**
 - **If WDIO Testrunner, running sync/async: sync**
 - **Node.js version:v12.12.0**
 - **NPM version:6.11.3**
 - **Browser name and version:Chrome 89.0.4389.23**
 - **Platform name and version:MacOs Catalina 10.15.7**

**Config of WebdriverIO**
```
services:[
  [
    "devtools"
  ],
  [
    "selenium-standalone",
    {
      "logPath": "logs",
      "installArgs": {
        "drivers": {
          "chrome": true
        }
      },
      "args": {
        "version": "3.141.59",
        "seleniumArgs": [
          "-host",
          "127.0.0.1",
          "-port",
          5555
        ]
      }
    }
  ]
]
```
```
chrome: {
        'maxInstances': 2,
        'browserName': 'chrome',
        'port': 5555,
        'goog:chromeOptions': {
            args: ['--window-size=1200,950', '--enable-automation', '--disable-infobars']
        },
        'wdio:devtoolsOptions': {
            headless: true,
            defaultViewport: {
                width: 800,
                height: 600,
                deviceScaleFactor: 1,
                isMobile: false
            }
        }
    }
```

**Describe the bug**
in our script, driver clicks on a button, which launch a url in different window/tab. devtools not capturing another window's (switched from parent) network calls. its able to capture parent's window, before switching from and after sticking to parent.

**To Reproduce**

```
        // enable devtools
        browser.cdp('Network', 'enable');
        // capture calls
        browser.on('Network.responseReceived', (params) => {
            console.log(`n/w call:\n ${params.response.url}`);
        });
        const getBrowserWindowHandles = browser.getWindowHandles();
        // click on launch button
        this.launchAppButton.click();
        browser.pause(2000);
        browser.switchToWindow(getBrowserWindowHandles[1]);
        // logout of app
        this.logOutOfApp();
        browser.pause(2000);
        browser.switchToWindow(getBrowserWindowHandles[0]);
        this.logOutIcon.click();
```

**Expected behavior**
should be able to capture switched window network calls

**Comment by christian-bromann** [comment]
Can you provide some WebdriverIO logs?

**Comment by spatchamatla** [comment]
im unable to provide actual code, but hope this helps..
```
describe('devtools', () => {
    it('should successfully log another window network logs', () => {
        // enable devtools
        browser.cdp('Network', 'enable');
        // capture calls
        browser.on('Network.responseReceived', (params) => {
            console.log(`n/w call:\n ${params.response.url}`);
        });
        browser.url('http://google.com');
        let getBrowserWindowHandles = browser.getWindowHandles();
        console.log(browser.getTitle()); // outputs: "Google"

        browser.newWindow('https://webdriver.io', 'WebdriverIO window', 'width=420,height=230,resizable,scrollbars=yes,status=1');
        console.log(browser.getTitle()); // outputs: "WebdriverIO · Next-gen browser and mobile automation test framework for Node.js"

        browser.switchToWindow(getBrowserWindowHandles[0]);
        console.log(browser.getTitle()); // outputs: "Google"
        
    });
});
```
 I picked the above code from webdriverio docs and modified to reproduce the issue. as you can see in below console logs, only google tab/window (parent window) network call logs being captured or displayed, but not the webdriverio tab's network calls.

***console logs:***
```
[0-0] n/w call:
 https://www.google.com/?gws_rd=ssl
[0-0] n/w call:
 https://www.google.com/?gws_rd=ssl
[0-0] n/w call:
 data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAYCAMAAAAiV0Z6AAAAPFBMVEVLoEN0wU6CzFKCzFKCzFKCzFKCzFJSo0MSczNDmkCCzFJPoUMTczNdr0gmgziCzFITczMTczMTczMTczPh00jOAAAAFHRSTlPF/+bIsms8Ad///hX+//5/tXw7aMEAx10AAACaSURBVHgBbc4HDoRQCATQ33tbvf9dF9QxaCT9UQaltLHOh/golXKhMs5Xqa0xU1lyoa2fXFyQOsDG38qsLy4TaV+sFislovyhPzLJJrBu6eQOtpW0LjbJkzTuTDLRVNKa3uxJI+VdiRqXSeu6GW+Qxi29eLIi8H7EsYrT42BD+mQtNO5JMjRuC4lSY8V4hsLX0egGijvUSEP9AbylEsOkeCgWAAAAAElFTkSuQmCC
[0-0] n/w call:
 data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAYCAMAAAAiV0Z6AAAAPFBMVEVLoEN0wU6CzFKCzFKCzFKCzFKCzFJSo0MSczNDmkCCzFJPoUMTczNdr0gmgziCzFITczMTczMTczMTczPh00jOAAAAFHRSTlPF/+bIsms8Ad///hX+//5/tXw7aMEAx10AAACaSURBVHgBbc4HDoRQCATQ33tbvf9dF9QxaCT9UQaltLHOh/golXKhMs5Xqa0xU1lyoa2fXFyQOsDG38qsLy4TaV+sFislovyhPzLJJrBu6eQOtpW0LjbJkzTuTDLRVNKa3uxJI+VdiRqXSeu6GW+Qxi29eLIi8H7EsYrT42BD+mQtNO5JMjRuC4lSY8V4hsLX0egGijvUSEP9AbylEsOkeCgWAAAAAElFTkSuQmCC
[0-0] n/w call:
 https://www.google.com/xjs/_/js/k=xjs.s.en_US.PjOhIFeE0xQ.O/ck=xjs.s.C-Xdz8D7pLI.L.W.O/m=cdos,dpf,hsm,jsa,d,csi/am=MIAAAEAICkgAAAAAgAIQFgMCgHgAQIAEFCSBBAAAABPYBwT8NwGACzZxAAAAAAAIgEsCjVIDiYIACAAAAJDV1RIgFIA/d=1/dg=2/br=1/ct=zgms/rs=ACT90oH-zrpUodH_sAGwzyWqKO1Ki8zkTA
[0-0] n/w call:
 https://www.google.com/xjs/_/js/k=xjs.s.en_US.PjOhIFeE0xQ.O/ck=xjs.s.C-Xdz8D7pLI.L.W.O/m=cdos,dpf,hsm,jsa,d,csi/am=MIAAAEAICkgAAAAAgAIQFgMCgHgAQIAEFCSBBAAAABPYBwT8NwGACzZxAAAAAAAIgEsCjVIDiYIACAAAAJDV1RIgFIA/d=1/dg=2/br=1/ct=zgms/rs=ACT90oH-zrpUodH_sAGwzyWqKO1Ki8zkTA
[0-0] n/w call:
 https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
[0-0] n/w call:
 https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
[0-0] n/w call:
 https://www.google.com/images/searchbox/desktop_searchbox_sprites318_hr.webp
[0-0] n/w call:
 https://www.google.com/images/searchbox/desktop_searchbox_sprites318_hr.webp
[0-0] n/w call:
 https://www.gstatic.com/og/_/ss/k=og.qtm.4cwBuE8sxqA.L.W.O/m=qcwid/excm=qaaw,qadd,qaid,qein,qhaw,qhbr,qhch,qhga,qhid,qhin,qhpr/d=1/ed=1/ct=zgms/rs=AA2YrTtzd9o2G7_4ubQDhEQdYOcDq4ZGvQ
[0-0] n/w call:
 https://www.gstatic.com/og/_/ss/k=og.qtm.4cwBuE8sxqA.L.W.O/m=qcwid/excm=qaaw,qadd,qaid,qein,qhaw,qhbr,qhch,qhga,qhid,qhin,qhpr/d=1/ed=1/ct=zgms/rs=AA2YrTtzd9o2G7_4ubQDhEQdYOcDq4ZGvQ
[0-0] n/w call:
 https://www.gstatic.com/og/_/js/k=og.qtm.en_US.JY2N8-i2vv0.O/rt=j/m=qabr,q_d,qcwid,qmutsd,qapid,qald/exm=qaaw,qadd,qaid,qein,qhaw,qhbr,qhch,qhga,qhid,qhin,qhpr/d=1/ed=1/rs=AA2YrTsLmWCFpZtMmUtmnx8wQ4QJ04zvng
[0-0] n/w call:
 https://www.gstatic.com/og/_/js/k=og.qtm.en_US.JY2N8-i2vv0.O/rt=j/m=qabr,q_d,qcwid,qmutsd,qapid,qald/exm=qaaw,qadd,qaid,qein,qhaw,qhbr,qhch,qhga,qhid,qhin,qhpr/d=1/ed=1/rs=AA2YrTsLmWCFpZtMmUtmnx8wQ4QJ04zvng
[0-0] n/w call:
 https://www.google.com/gen_204?s=webhp&t=aft&atyp=csi&ei=hJhiYPLYDsHN_AaezZeQDQ&rt=wsrt.519,aft.287,prt.118&imn=2&ima=2&imad=0&aftp=827&bl=WN6f
[0-0] n/w call:
 https://www.google.com/gen_204?s=webhp&t=aft&atyp=csi&ei=hJhiYPLYDsHN_AaezZeQDQ&rt=wsrt.519,aft.287,prt.118&imn=2&ima=2&imad=0&aftp=827&bl=WN6f
[0-0] n/w call:
 https://www.google.com/xjs/_/js/k=xjs.s.en_US.PjOhIFeE0xQ.O/ck=xjs.s.C-Xdz8D7pLI.L.W.O/am=MIAAAEAICkgAAAAAgAIQFgMCgHgAQIAEFCSBBAAAABPYBwT8NwGACzZxAAAAAAAIgEsCjVIDiYIACAAAAJDV1RIgFIA/d=1/exm=cdos,csi,d,dpf,hsm,jsa/ed=1/dg=2/br=1/ct=zgms/rs=ACT90oH-zrpUodH_sAGwzyWqKO1Ki8zkTA/m=BLvsRb,NBZ7u,aa,abd,async,dvl,fEVMic,ifl,lu,mUpTid,mu,sb_wiz,sf,sonic,spch,xz7cCd?xjs=s1
[0-0] n/w call:
 https://www.google.com/xjs/_/js/k=xjs.s.en_US.PjOhIFeE0xQ.O/ck=xjs.s.C-Xdz8D7pLI.L.W.O/am=MIAAAEAICkgAAAAAgAIQFgMCgHgAQIAEFCSBBAAAABPYBwT8NwGACzZxAAAAAAAIgEsCjVIDiYIACAAAAJDV1RIgFIA/d=1/exm=cdos,csi,d,dpf,hsm,jsa/ed=1/dg=2/br=1/ct=zgms/rs=ACT90oH-zrpUodH_sAGwzyWqKO1Ki8zkTA/m=BLvsRb,NBZ7u,aa,abd,async,dvl,fEVMic,ifl,lu,mUpTid,mu,sb_wiz,sf,sonic,spch,xz7cCd?xjs=s1
[0-0] n/w call:
 https://www.google.com/client_204?&atyp=i&biw=1200&bih=827&dpr=2&ei=hJhiYPLYDsHN_AaezZeQDQ
[0-0] n/w call:
 https://www.google.com/client_204?&atyp=i&biw=1200&bih=827&dpr=2&ei=hJhiYPLYDsHN_AaezZeQDQ
[0-0] n/w call:
 https://www.google.com/xjs/_/js/k=xjs.s.en_US.PjOhIFeE0xQ.O/ck=xjs.s.C-Xdz8D7pLI.L.W.O/am=MIAAAEAICkgAAAAAgAIQFgMCgHgAQIAEFCSBBAAAABPYBwT8NwGACzZxAAAAAAAIgEsCjVIDiYIACAAAAJDV1RIgFIA/d=1/exm=BLvsRb,NBZ7u,aa,abd,async,cdos,csi,d,dpf,dvl,fEVMic,hsm,ifl,jsa,lu,mUpTid,mu,sb_wiz,sf,sonic,spch,xz7cCd/ed=1/dg=2/br=1/ct=zgms/rs=ACT90oH-zrpUodH_sAGwzyWqKO1Ki8zkTA/m=HFyn5c?xjs=s2
[0-0] n/w call:
 https://www.google.com/xjs/_/js/k=xjs.s.en_US.PjOhIFeE0xQ.O/ck=xjs.s.C-Xdz8D7pLI.L.W.O/am=MIAAAEAICkgAAAAAgAIQFgMCgHgAQIAEFCSBBAAAABPYBwT8NwGACzZxAAAAAAAIgEsCjVIDiYIACAAAAJDV1RIgFIA/d=1/exm=BLvsRb,NBZ7u,aa,abd,async,cdos,csi,d,dpf,dvl,fEVMic,hsm,ifl,jsa,lu,mUpTid,mu,sb_wiz,sf,sonic,spch,xz7cCd/ed=1/dg=2/br=1/ct=zgms/rs=ACT90oH-zrpUodH_sAGwzyWqKO1Ki8zkTA/m=HFyn5c?xjs=s2
[0-0] n/w call:
 https://www.google.com/complete/search?q&cp=0&client=gws-wiz&xssi=t&gs_ri=gws-wiz&hl=en&authuser=0&psi=hJhiYPLYDsHN_AaezZeQDQ.1617074308735&nolsbt=1&dpr=2
[0-0] n/w call:
 https://www.google.com/complete/search?q&cp=0&client=gws-wiz&xssi=t&gs_ri=gws-wiz&hl=en&authuser=0&psi=hJhiYPLYDsHN_AaezZeQDQ.1617074308735&nolsbt=1&dpr=2
[0-0] n/w call:
 https://www.google.com/xjs/_/js/k=xjs.s.en_US.PjOhIFeE0xQ.O/ck=xjs.s.C-Xdz8D7pLI.L.W.O/am=MIAAAEAICkgAAAAAgAIQFgMCgHgAQIAEFCSBBAAAABPYBwT8NwGACzZxAAAAAAAIgEsCjVIDiYIACAAAAJDV1RIgFIA/d=1/exm=BLvsRb,HFyn5c,NBZ7u,aa,abd,async,cdos,csi,d,dpf,dvl,fEVMic,hsm,ifl,jsa,lu,mUpTid,mu,sb_wiz,sf,sonic,spch,xz7cCd/ed=1/dg=2/br=1/ct=zgms/rs=ACT90oH-zrpUodH_sAGwzyWqKO1Ki8zkTA/m=NpD4ec,wkrYee?xjs=s2
[0-0] n/w call:
 https://www.google.com/xjs/_/js/k=xjs.s.en_US.PjOhIFeE0xQ.O/ck=xjs.s.C-Xdz8D7pLI.L.W.O/am=MIAAAEAICkgAAAAAgAIQFgMCgHgAQIAEFCSBBAAAABPYBwT8NwGACzZxAAAAAAAIgEsCjVIDiYIACAAAAJDV1RIgFIA/d=1/exm=BLvsRb,HFyn5c,NBZ7u,aa,abd,async,cdos,csi,d,dpf,dvl,fEVMic,hsm,ifl,jsa,lu,mUpTid,mu,sb_wiz,sf,sonic,spch,xz7cCd/ed=1/dg=2/br=1/ct=zgms/rs=ACT90oH-zrpUodH_sAGwzyWqKO1Ki8zkTA/m=NpD4ec,wkrYee?xjs=s2
[0-0] n/w call:
 https://ogs.google.com/widget/app/so?bc=1&origin=https%3A%2F%2Fwww.google.com&cn=app&pid=1&spid=538&hl=en
[0-0] n/w call:
 https://ogs.google.com/widget/app/so?bc=1&origin=https%3A%2F%2Fwww.google.com&cn=app&pid=1&spid=538&hl=en
[0-0] n/w call:
 https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.RrjSsKk8Szw.O/m=gapi_iframes,googleapis_client/rt=j/sv=1/d=1/ed=1/rs=AHpOoo8bhQb3qTfNhmC8kzOOB-dQGGlNzA/cb=gapi.loaded_0
[0-0] n/w call:
 https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.RrjSsKk8Szw.O/m=gapi_iframes,googleapis_client/rt=j/sv=1/d=1/ed=1/rs=AHpOoo8bhQb3qTfNhmC8kzOOB-dQGGlNzA/cb=gapi.loaded_0
[0-0] Google
[0-0] n/w call:
 https://www.google.com/gen_204?atyp=csi&ei=hJhiYPLYDsHN_AaezZeQDQ&s=webhp&t=all&bl=WN6f&imn=2&ima=2&imad=0&aftp=827&adh=&conn=onchange&ime=2&imex=2&imeh=0&imea=0&imeb=0&wh=827&scp=0&net=dl.10000,ect.4g,rtt.150&mem=ujhs.8,tjhs.11,jhsl.4295,dm.8&sto=&sys=hc.8&rt=aft.287,iml.287,prt.118,xjses.308,xjsee.340,xjs.340,dcl.342,ol.1093,wsrt.519,cst.113,dnst.0,rqst.283,rspt.85,sslt.113,rqstt.321,unt.207,cstt.208,dit.639&zx=1617074309469
[0-0] n/w call:
 https://www.google.com/gen_204?atyp=csi&ei=hJhiYPLYDsHN_AaezZeQDQ&s=webhp&t=all&bl=WN6f&imn=2&ima=2&imad=0&aftp=827&adh=&conn=onchange&ime=2&imex=2&imeh=0&imea=0&imeb=0&wh=827&scp=0&net=dl.10000,ect.4g,rtt.150&mem=ujhs.8,tjhs.11,jhsl.4295,dm.8&sto=&sys=hc.8&rt=aft.287,iml.287,prt.118,xjses.308,xjsee.340,xjs.340,dcl.342,ol.1093,wsrt.519,cst.113,dnst.0,rqst.283,rspt.85,sslt.113,rqstt.321,unt.207,cstt.208,dit.639&zx=1617074309469
[0-0] n/w call:
 https://www.google.com/favicon.ico
[0-0] n/w call:
 https://www.google.com/favicon.ico
[0-0] n/w call:
 https://www.google.com/gen_204?atyp=i&ei=hJhiYPLYDsHN_AaezZeQDQ&ct=slh&v=t1&m=HV&pv=0.5660732159412056&me=1:1617074308871,x:1,V,0,0,1200,827:0,N,1,hJhiYPLYDsHN_AaezZeQDQ:0,R,1,1,0,0,1200,827:1,B,827:628,e,B&zx=1617074309501
[0-0] n/w call:
 https://www.google.com/gen_204?atyp=i&ei=hJhiYPLYDsHN_AaezZeQDQ&ct=slh&v=t1&m=HV&pv=0.5660732159412056&me=1:1617074308871,x:1,V,0,0,1200,827:0,N,1,hJhiYPLYDsHN_AaezZeQDQ:0,R,1,1,0,0,1200,827:1,B,827:628,e,B&zx=1617074309501
[0-0] n/w call:
 https://www.google.com/manifest?pwa=webhp
[0-0] n/w call:
 https://www.google.com/manifest?pwa=webhp
[0-0] n/w call:
 https://adservice.google.com/adsid/google/ui
[0-0] n/w call:
 https://adservice.google.com/adsid/google/ui

```
***wdio.log***
```
2021-03-30T03:18:25.027Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-03-30T03:18:25.477Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Missing <*****>/node_modules/selenium-standalone/.selenium/geckodriver/latest-x64-geckodriver
    at <*****>/node_modules/selenium-standalone/lib/check-paths-existence.js:16:29
    at suppressedCallback (fs.js:219:5)
    at FSReqCallback.oncomplete (fs.js:165:23)
    at FSReqCallback.callbackTrampoline (internal/async_hooks.js:129:14)

Continue...
2021-03-30T03:18:25.478Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-03-30T03:18:25.479Z INFO @wdio/local-runner: Start worker 0-0 with arg: --color,--gulpfile,<*****>/gulpfile.js,run:wdio:suite,--suite,apiDebug,--browser=chrome
2021-03-30T03:18:34.061Z INFO @wdio/cli:launcher: Run onComplete hook
2021-03-30T03:18:34.062Z INFO @wdio/local-runner: Shutting down spawned worker
2021-03-30T03:18:34.318Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-03-30T03:18:34.318Z INFO @wdio/local-runner: shutting down
```
***wdio-0-0.log***
```
2021-03-30T03:18:25.977Z INFO @wdio/local-runner: Run worker command: run
2021-03-30T03:18:26.691Z INFO webdriver: Initiate new session using the WebDriver protocol
2021-03-30T03:18:26.691Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session
2021-03-30T03:18:26.692Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      'goog:chromeOptions': [Object],
      'wdio:devtoolsOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': { args: [Array] },
    'wdio:devtoolsOptions': { headless: false, defaultViewport: [Object] }
  }
}
2021-03-30T03:18:27.810Z INFO webdriver: COMMAND setTimeouts(undefined, 30000, undefined)
2021-03-30T03:18:27.810Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/timeouts
2021-03-30T03:18:27.810Z INFO webdriver: DATA { pageLoad: 30000 }
2021-03-30T03:18:27.845Z INFO webdriver: COMMAND cdp("Network", "enable")
2021-03-30T03:18:27.846Z INFO @wdio/devtools-service:CommandHandler: Send command "Network.enable" with args: {}
2021-03-30T03:18:27.847Z INFO webdriver: RESULT {}
2021-03-30T03:18:27.847Z INFO webdriver: COMMAND navigateTo("http://google.com/")
2021-03-30T03:18:27.847Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/url
2021-03-30T03:18:27.847Z INFO webdriver: DATA { url: 'http://google.com/' }
2021-03-30T03:18:29.476Z INFO webdriver: COMMAND getWindowHandles()
2021-03-30T03:18:29.476Z INFO webdriver: [GET] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/window/handles
2021-03-30T03:18:29.479Z INFO webdriver: RESULT [ 'CDwindow-F5CBE59F6582851B1BCD4685190B6445' ]
2021-03-30T03:18:29.479Z INFO webdriver: COMMAND getTitle()
2021-03-30T03:18:29.480Z INFO webdriver: [GET] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/title
2021-03-30T03:18:29.486Z INFO webdriver: RESULT Google
2021-03-30T03:18:29.487Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
2021-03-30T03:18:29.487Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/execute/sync
2021-03-30T03:18:29.487Z INFO webdriver: DATA {
  script: 'return (function newWindow(url, windowName, windowFeatures) {\n' +
    "    window.open(url, windowName || 'new window', windowFeatures || '');\n" +
    '}).apply(null, arguments)',
  args: [ 'https://webdriver.io', 'New Window', '' ]
}
2021-03-30T03:18:29.563Z INFO webdriver: COMMAND getWindowHandles()
2021-03-30T03:18:29.563Z INFO webdriver: [GET] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/window/handles
2021-03-30T03:18:29.569Z INFO webdriver: RESULT [
  'CDwindow-F5CBE59F6582851B1BCD4685190B6445',
  'CDwindow-3C39AF5A25A54644E6713BB5AEF1692C'
]
2021-03-30T03:18:29.570Z INFO webdriver: COMMAND switchToWindow("CDwindow-3C39AF5A25A54644E6713BB5AEF1692C")
2021-03-30T03:18:29.570Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/window
2021-03-30T03:18:29.570Z INFO webdriver: DATA { handle: 'CDwindow-3C39AF5A25A54644E6713BB5AEF1692C' }
2021-03-30T03:18:29.576Z INFO webdriver: COMMAND getTitle()
2021-03-30T03:18:29.576Z INFO webdriver: [GET] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/title
2021-03-30T03:18:33.809Z INFO webdriver: RESULT WebdriverIO · Next-gen browser and mobile automation test framework for Node.js | WebdriverIO
2021-03-30T03:18:33.809Z INFO webdriver: COMMAND switchToWindow("CDwindow-F5CBE59F6582851B1BCD4685190B6445")
2021-03-30T03:18:33.810Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/window
2021-03-30T03:18:33.810Z INFO webdriver: DATA { handle: 'CDwindow-F5CBE59F6582851B1BCD4685190B6445' }
2021-03-30T03:18:33.826Z INFO webdriver: COMMAND getTitle()
2021-03-30T03:18:33.826Z INFO webdriver: [GET] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/title
2021-03-30T03:18:33.862Z INFO webdriver: RESULT Google
2021-03-30T03:18:33.871Z INFO webdriver: COMMAND getLogTypes()
2021-03-30T03:18:33.872Z INFO webdriver: [GET] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/se/log/types
2021-03-30T03:18:33.875Z INFO webdriver: RESULT [ 'browser', 'driver' ]
2021-03-30T03:18:33.875Z INFO webdriver: COMMAND getLogs("driver")
2021-03-30T03:18:33.876Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/se/log
2021-03-30T03:18:33.876Z INFO webdriver: DATA { type: 'driver' }
2021-03-30T03:18:33.876Z INFO webdriver: COMMAND getLogs("browser")
2021-03-30T03:18:33.877Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995/se/log
2021-03-30T03:18:33.877Z INFO webdriver: DATA { type: 'browser' }
2021-03-30T03:18:33.880Z INFO webdriver: RESULT []
2021-03-30T03:18:33.883Z INFO webdriver: RESULT [
  {
    level: 'WARNING',
    message: "https://webdriver.io/ 35 Unrecognized feature: 'web-share'.",
    source: 'other',
    timestamp: 1617074312131
  }
]
2021-03-30T03:18:33.885Z INFO webdriver: COMMAND deleteSession()
2021-03-30T03:18:33.885Z INFO webdriver: [DELETE] http://localhost:5777/wd/hub/session/7b25fdafefe846b0b3f865a8a041d995

```

***wdio-0-0-browser.log***
```
{"level":"WARNING","message":"https://webdriver.io/ 35 Unrecognized feature: 'web-share'.","source":"other","timestamp":1617074312131}
```

**Comment by christian-bromann** [comment]
This is a (kind of) bug within the `devtools` package. If you switch windows you need to re-register the network listener. However I can see the desire to not wanting to do that every time. This is something WebdriverIO could handle. Any contributions appreciated.

**Comment by spatchamatla** [comment]
@christian-bromann sure can help in free time, but need some guidance. never worked with ts.

**Comment by christian-bromann** [comment]
> @christian-bromann sure can help in free time, but need some guidance. never worked with ts.

Sure thing, feel free to book an [Open Office Hours](https://webdriver.io/community/openofficehours) slot if you get stuck

**Comment by christian-bromann** [comment]
fixed by https://github.com/webdriverio/webdriverio/pull/11668
