### ISSUE TITLE
chrome version in wdio config.services selenium args, fails to create new service: ChromeDriverService with 500 status code

### ISSUE THREAD

**Issue by spatchamatla** [webdriverio/webdriverio#6635]
- **WebdriverIO version:7.2.3**
 - **@wdio/selenium-standalone-service: 7.2.1**
 - **@wdio/devtools-service: 7.2.3**
 - **wdio-chromedriver-service: 7.0.0**
 - **chromedriver: 89.0.0**
 - **Mode: Standalone**
 - **If WDIO Testrunner, running sync/async: sync**
 - **Node.js version:v12.12.0**
 - **NPM version:6.11.3**
 - **Browser name and version:Chrome 89.0.4389.23**
 - **Platform name and version:MacOs Catalina 10.15.7**

**Config of WebdriverIO**
```
services:[
  [
    "devtools"
  ],
  [
    "selenium-standalone",
    {
      "logPath": "logs",
      "installArgs": {
        "drivers": {
                chrome : {
                    version : '89.0.4389.23',
                    arch    : process.arch,
                    baseURL : 'https://chromedriver.storage.googleapis.com'
                }
        }
      },
      "args": {
        "version": "3.141.59",
        "seleniumArgs": [
          "-host",
          "127.0.0.1",
          "-port",
          5555
        ]
      }
    }
  ]
]
```
```
chrome: {
        'maxInstances': 2,
        'browserName': 'chrome',
        'port': 5555,
        'goog:chromeOptions': {
            args: ['--window-size=1200,950', '--enable-automation', '--disable-infobars']
        },
        'wdio:devtoolsOptions': {
            headless: true,
            defaultViewport: {
                width: 800,
                height: 600,
                deviceScaleFactor: 1,
                isMobile: false
            }
        }
    }
```
**Describe the bug**
when specs are run, wdio doesn't open a browser. I see the below error in webdriverio logs. in node modules I see the chrome driver. if I gave the chrome args as `chrome: true`, it works fine

**wdio-0-0.log**
```
2021-03-30T03:42:21.324Z INFO @wdio/local-runner: Run worker command: run
2021-03-30T03:42:22.218Z INFO webdriver: Initiate new session using the WebDriver protocol
2021-03-30T03:42:22.218Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session
2021-03-30T03:42:22.218Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      'goog:chromeOptions': [Object],
      'wdio:devtoolsOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': { args: [Array] },
    'wdio:devtoolsOptions': { headless: false, defaultViewport: [Object] }
  }
}
2021-03-30T03:42:22.260Z WARN webdriver: Request failed with status 500 due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>', ip: '192.168.0.13', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
2021-03-30T03:42:22.260Z INFO webdriver: Retrying 1/3
2021-03-30T03:42:22.260Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session
2021-03-30T03:42:22.260Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      'goog:chromeOptions': [Object],
      'wdio:devtoolsOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': { args: [Array] },
    'wdio:devtoolsOptions': { headless: false, defaultViewport: [Object] }
  }
}
2021-03-30T03:42:22.273Z WARN webdriver: Request failed with status 500 due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>', ip: '192.168.0.13', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
2021-03-30T03:42:22.273Z INFO webdriver: Retrying 2/3
2021-03-30T03:42:22.273Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session
2021-03-30T03:42:22.273Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      'goog:chromeOptions': [Object],
      'wdio:devtoolsOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': { args: [Array] },
    'wdio:devtoolsOptions': { headless: false, defaultViewport: [Object] }
  }
}
2021-03-30T03:42:22.285Z WARN webdriver: Request failed with status 500 due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>', ip: '192.168.0.13', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
2021-03-30T03:42:22.285Z INFO webdriver: Retrying 3/3
2021-03-30T03:42:22.286Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session
2021-03-30T03:42:22.286Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      'goog:chromeOptions': [Object],
      'wdio:devtoolsOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    'goog:chromeOptions': { args: [Array] },
    'wdio:devtoolsOptions': { headless: false, defaultViewport: [Object] }
  }
}
2021-03-30T03:42:22.304Z ERROR webdriver: Request failed with status 500 due to session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>', ip: '192.168.0.13', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
2021-03-30T03:42:22.304Z ERROR webdriver: session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>', ip: '192.168.0.13', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
    at Object.getErrorFromResponseBody (<*******>/node_modules/webdriver/build/utils.js:189:12)
    at WebDriverRequest._request (<*******>/node_modules/webdriver/build/request.js:168:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.startWebDriverSession (<*******>/node_modules/webdriver/build/utils.js:63:20)
    at async Function.newSession (<*******>/node_modules/webdriver/build/index.js:58:45)
    at async Object.exports.remote (<*******>/node_modules/webdriverio/build/index.js:56:22)
    at async Runner._startSession (<*******>/node_modules/@wdio/runner/build/index.js:202:56)
    at async Runner._initSession (<*******>/node_modules/@wdio/runner/build/index.js:164:25)
    at async Runner.run (<*******>/node_modules/@wdio/runner/build/index.js:87:19)
2021-03-30T03:42:22.304Z ERROR @wdio/runner: Error: Failed to create session.
Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>', ip: '192.168.0.13', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
    at Object.startWebDriverSession (<*******>/node_modules/webdriver/build/utils.js:68:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.newSession (<*******>/node_modules/webdriver/build/index.js:58:45)
    at async Object.exports.remote (<*******>/node_modules/webdriverio/build/index.js:56:22)
    at async Runner._startSession (<*******>/node_modules/@wdio/runner/build/index.js:202:56)
    at async Runner._initSession (<*******>/node_modules/@wdio/runner/build/index.js:164:25)
    at async Runner.run (<*******>/node_modules/@wdio/runner/build/index.js:87:19)

```
***wdio.log***
```
2021-03-30T03:18:25.027Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-03-30T03:18:25.477Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: Missing <*****>/node_modules/selenium-standalone/.selenium/geckodriver/latest-x64-geckodriver
    at <*****>/node_modules/selenium-standalone/lib/check-paths-existence.js:16:29
    at suppressedCallback (fs.js:219:5)
    at FSReqCallback.oncomplete (fs.js:165:23)
    at FSReqCallback.callbackTrampoline (internal/async_hooks.js:129:14)

Continue...
2021-03-30T03:18:25.478Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-03-30T03:18:25.479Z INFO @wdio/local-runner: Start worker 0-0 with arg: --color,--gulpfile,<*****>/gulpfile.js,run:wdio:suite,--suite,apiDebug,--browser=chrome
2021-03-30T03:18:34.061Z INFO @wdio/cli:launcher: Run onComplete hook
2021-03-30T03:18:34.062Z INFO @wdio/local-runner: Shutting down spawned worker
2021-03-30T03:18:34.318Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-03-30T03:18:34.318Z INFO @wdio/local-runner: shutting down
```

**Expected behavior**
wdio installs and run only on specified version of the browser

**Comment by christian-bromann** [comment]
If you define a specific version within the install args you need to define the same version for the driver args, I was able to run the example with the following service config:
```js
[
        [
          "devtools"
        ],
        [
          "selenium-standalone",
          {
            "logPath": "logs",
            "installArgs": {
              "drivers": {
                      chrome : {
                          version : '89.0.4389.23',
                          arch    : process.arch,
                          baseURL : 'https://chromedriver.storage.googleapis.com'
                      }
              }
            },
            "args": {
              "version": "3.141.59",
              "drivers": {
                  chrome: {
                      version: '89.0.4389.23'
                  }
              },
              "seleniumArgs": [
                "-host",
                "127.0.0.1",
                "-port",
                5555
              ]
            }
          }
        ]
    ]
```

Let me know if you have further questions.

**Comment by spatchamatla** [comment]
@christian-bromann im going to reopen this, I tried the below `service`
```
['selenium-standalone', {
        logPath: 'logs',
        installArgs: {
            drivers : {
                chrome : {
                    version : '89.0.4389.23',
                    arch    : process.arch,
                    baseURL : 'https://chromedriver.storage.googleapis.com'
                }
            }
        },
        args: {
            // selenium-standalone version is needed due to latest changes in wdio/selenium args
            // refer wdio https://webdriver.io/docs/selenium-standalone-service.html
            version: '3.141.59',
            drivers: {
                chrome: {
                    version: '89.0.4389.23'
                }
            },
            seleniumArgs: ['-host', '127.0.0.1', '-port', SELENIUM_PORT]
        },
    }]
```

and seeing the same issue
```
2021-04-07T16:04:13.092Z INFO @wdio/local-runner: Run worker command: run
2021-04-07T16:04:14.738Z INFO webdriver: Initiate new session using the WebDriver protocol
2021-04-07T16:04:14.739Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session
2021-04-07T16:04:14.739Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': { args: [Array] } }
}
2021-04-07T16:04:14.792Z WARN webdriver: Request failed with status 500 due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>-mac-2.local', ip: '<*******>', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
2021-04-07T16:04:14.792Z INFO webdriver: Retrying 1/3
2021-04-07T16:04:14.792Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session
2021-04-07T16:04:14.792Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': { args: [Array] } }
}
2021-04-07T16:04:14.802Z WARN webdriver: Request failed with status 500 due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>-mac-2.local', ip: '<*******>', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
2021-04-07T16:04:14.802Z INFO webdriver: Retrying 2/3
2021-04-07T16:04:14.802Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session
2021-04-07T16:04:14.802Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': { args: [Array] } }
}
2021-04-07T16:04:14.812Z WARN webdriver: Request failed with status 500 due to Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>-mac-2.local', ip: '<*******>', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
2021-04-07T16:04:14.812Z INFO webdriver: Retrying 3/3
2021-04-07T16:04:14.812Z INFO webdriver: [POST] http://localhost:5777/wd/hub/session
2021-04-07T16:04:14.812Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': { args: [Array] } }
}
2021-04-07T16:04:14.822Z ERROR webdriver: Request failed with status 500 due to session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>-mac-2.local', ip: '<*******>', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
2021-04-07T16:04:14.822Z ERROR webdriver: session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>-mac-2.local', ip: '<*******>', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
    at Object.getErrorFromResponseBody (<*******>/node_modules/webdriver/build/utils.js:189:12)
    at WebDriverRequest._request (<*******>/node_modules/webdriver/build/request.js:168:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.startWebDriverSession (<*******>/node_modules/webdriver/build/utils.js:63:20)
    at async Function.newSession (<*******>/node_modules/webdriver/build/index.js:58:45)
    at async Object.exports.remote (<*******>/node_modules/webdriverio/build/index.js:56:22)
    at async Runner._startSession (<*******>/node_modules/@wdio/runner/build/index.js:202:56)
    at async Runner._initSession (<*******>/node_modules/@wdio/runner/build/index.js:164:25)
    at async Runner.run (<*******>/node_modules/@wdio/runner/build/index.js:87:19)
2021-04-07T16:04:14.823Z ERROR @wdio/runner: Error: Failed to create session.
Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '<*******>-mac-2.local', ip: '<*******>', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '10.0.2'
Driver info: driver.version: unknown
    at Object.startWebDriverSession (<*******>/node_modules/webdriver/build/utils.js:68:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.newSession (<*******>/node_modules/webdriver/build/index.js:58:45)
    at async Object.exports.remote (<*******>/node_modules/webdriverio/build/index.js:56:22)
    at async Runner._startSession (<*******>/node_modules/@wdio/runner/build/index.js:202:56)
    at async Runner._initSession (<*******>/node_modules/@wdio/runner/build/index.js:164:25)
    at async Runner.run (<*******>/node_modules/@wdio/runner/build/index.js:87:19)

```

**Comment by christian-bromann** [comment]
The service is correctly starting the selenium standalone server. The issue is within your configuration, see also: https://stackoverflow.com/a/48838878/765174

**Comment by spatchamatla** [comment]
in that there no accepted solutions, if setting chrome driver path is required for selenium args, where should I set it?

**Comment by christian-bromann** [comment]
The service setting you have [posted above](https://github.com/webdriverio/webdriverio/issues/6635#issuecomment-815036778) works for me. There must be some other configuration issue.

**Comment by spatchamatla** [comment]
@christian-bromann do we need to setup driver path in browser capabilities? like `webdriver.chrome.driver` in `goog:chromeOptions`

**Comment by christian-bromann** [comment]
no, it should work as is
