### ISSUE TITLE
selectors doesn't work.

### ISSUE THREAD

**Issue by manodupont** [webdriverio/webdriverio#668]
Hi,

I am not sure if I am using webdriver well or not ...

The selectors seems to be pretty weird to work with. For example, I can easily access whatever method of the API using simple selectors like id or a simple css class. But as long as I don't know the id AND that the css class are dynamically put into my dom, i want to use tags. Which should be as any other jQuery call isn't it ?! Cause this, never worked.

i.e

if I have this

<div id='myId'>
<input type="text" value="test" id="<dynamicId">
<input type="text" value="test2" id="<dynamicId2">
<input type="text" value="test3" id="<dynamicId3">
</div>

And I want to setValue or (whatever API calls).

client.setValue('#myId input:first') <----- doesn't work
client.setValue('#myId input') <----- returns all input. That's not what I want.
client.setValue('#myId input:eq(0)') <----- doesn't work

*doesn't works means : 

Error
    at Domain.handleException (d:\mdupont091912\Projects\bespoke\amt-java\amt\client\node_modules\ez-build-test\node_modules\gulp-mocha\index.js:44:26
)
    at Domain.emit (events.js:107:17)
    at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
    at process._fatalException (node.js:233:33)

How am I supposed to solve this ?!

Thanks.

**Comment by christian-bromann** [comment]
mhm this error doesn't look like a Selenium/WebdriverIO error. Do you have a code snippet I can take a look at? There is also a bunch of other [selector strategies](http://webdriver.io/guide/usage/selectors.html) you can make use of. For input elements I think the name selector strategy (`[name="username“]`) would be the best. I also don't know why these selectors aren't working for you. Selenium should support CSS3 selectors (depending on what browser you test on).

**Comment by manodupont** [comment]
Well. I am testing angular app and a lot of elements are created dynamically based on directives implementation. Ids, names etc are not known in the test domain.  So i wanted to use classic css3 selectors but it doesnt seem to work. I always get a Domain.handleException

**Comment by christian-bromann** [comment]
Could you paste in the Selenium error message?

**Comment by manodupont** [comment]
Actually you may be right.

The exception that I often get is related to mocha.

[11:30:12] ERROR: CommandError in plugin 'gulp-mocha'
Error
    at Domain.handleException (d:\mdupont091912\Projects\bespoke\amt-java\amt\client\node_modules\gulp-mocha\index.js:44:26
)
    at Domain.emit (events.js:107:17)
    at Domain.errorHandler [as _errorHandler] (domain.js:102:19)
    at process._fatalException (node.js:233:33)

**Comment by christian-bromann** [comment]
Ok, closing this. Feel free to reopen if this turns out to be WebdriverIO related.

**Comment by iongion** [comment]
Just encountered this today using gulp-mocha 2.2.0 and webdriverio 4.0.3
```
Error
    at Domain.handleException (W:\Workspace\myproject\node_modules\gulp-mocha\index.js:46:24)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)
    at emitError (domain.js:66:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:126:16)
    at process._fatalException (node.js:253:33)
```

It alternates with this:
```
Message:
    EEXIST: file already exists, mkdir 'W:\Workspace\myproject'
Details:
    errno: -4075
    code: EEXIST
    syscall: mkdir
    path: W:\Workspace\myproject
    domain: [object Object]
    domainThrown: true
Stack:
Error: EEXIST: file already exists, mkdir 'W:\Workspace\myproject'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:842:18)
    at sync (W:\Workspace\myproject\node_modules\webdriverio\node_modules\mkdirp\index.js:71:13)
    at sync (W:\Workspace\myproject\node_modules\webdriverio\node_modules\mkdirp\index.js:77:24)
    at sync (W:\Workspace\myproject\node_modules\webdriverio\node_modules\mkdirp\index.js:78:17)
    at sync (W:\Workspace\myproject\node_modules\webdriverio\node_modules\mkdirp\index.js:78:17)
    at sync (W:\Workspace\myproject\node_modules\webdriverio\node_modules\mkdirp\index.js:78:17)
    at sync (W:\Workspace\myproject\node_modules\webdriverio\node_modules\mkdirp\index.js:78:17)
    at sync (W:\Workspace\myproject\node_modules\webdriverio\node_modules\mkdirp\index.js:78:17)
    at sync (W:\Workspace\myproject\node_modules\webdriverio\node_modules\mkdirp\index.js:78:17)
```

Did you notice something in relation to how it got fixed by itself ?

**Comment by iongion** [comment]
I just noticed a relation to the screenshotPath, where
```
{
...
screenshotPath: path.join(settings.project.root, 'temp/testing/webdriver/screenshots')
}
```
This meaning that screenshotPath is and absolute path that computes to: ```'W:\Workspace\myproject\temp\testing\webdriver\screenshots'```.

I've noticed the errors by logging the exception caught at line 71 *mkdirp/index.js*:
```
could not { [Error: ENOENT: no such file or directory, mkdir 'W:\Workspace\myproject\W:']
```

So screenshotPath is processed later and somehow mkdirp tries to create **W:\Workspace\myproject\W:**

Noticed the **W:** at the end of the path, that one is invalid.

If I change to:
```
"screenshotPath": "temp/testing/webdriver/screenshots"
```

Then the error becomes:
```
[11:09:43] TypeError in plugin 'gulp-mocha'
Message:
    Cannot read property 'info' of undefined
Details:
    domain: [object Object]
    domainThrown: true
Stack:
TypeError: Cannot read property 'info' of undefined
    at Object.reject (W:\Workspace\myproject\node_modules\webdriverio\build\lib\webdriverio.js:287:20)
    at Object.callErrorHandlerAndReject (W:\Workspace\myproject\node_modules\webdriverio\build\lib\webdriverio.js:217:27)
    at W:\Workspace\myproject\node_modules\webdriverio\build\lib\webdriverio.js:192:58
    at run (W:\Workspace\myproject\node_modules\webdriverio\node_modules\core-js\library\modules\es6.promise.js:104:47)
    at W:\Workspace\myproject\node_modules\webdriverio\node_modules\core-js\library\modules\es6.promise.js:115:28
    at flush (W:\Workspace\myproject\node_modules\webdriverio\node_modules\core-js\library\modules\$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13)
```
