### ISSUE TITLE
Incorrectly detect w3c protocol for appium with chromedriver@2.40

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#6689]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.1.0
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.18.1
 - **NPM version:** 6.14.5
 - **Browser name and version:** chrome mobile 67
 - **Platform name and version:** linux

**Describe the bug**
I run tests in android emulator with chrome@67 and appium@1.20.2. With chrome@67 I use chromedriver@2.40 which does not fully support W3C protocol. But wdio think that it does.

**To Reproduce**
Simple test on wdio:
```
const {remote} = require('webdriverio')

let client;

(async function () {
    client = await remote({
        protocol: 'http',
        hostname: 'MY_GRID_URL',
        port: 4444,
        path: '/wd/hub',
        automationProtocol: 'webdriver',
        capabilities: {
            platformName: 'Android',
            deviceName: 'android',
            version: 'phone-67.1',
            browserName: 'chrome',
            automationName: 'UiAutomator2'
        }
    });

    await client.url('https://yandex.ru');

    console.log('client.isW3C:', client.isW3C);

    await client.performActions([{
        type: 'key',
        id: 'keyboard',
        actions: [
            {type: 'keyDown', value: 'a'},
            {type: 'keyUp', value: 'a'},
        ]
    }]);

    await client.deleteSession();
})()
    .catch(async (e) => {
        console.error(e.stack)
        await client.deleteSession()
    });
```

**Expected behavior**
I expect that wdio connect jsonwp commands isteand w3c.

**Log**
https://gist.github.com/DudaGod/f660cb14dec1e86e32959c8a7a27a7d1

Wdio logs from console:
```
node ./issue_appium_w3c.js
2021-04-12T09:48:18.847Z INFO webdriver: Initiate new session using the WebDriver protocol
2021-04-12T09:48:18.853Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session
2021-04-12T09:48:18.853Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'android',
      version: 'phone-67.1',
      browserName: 'chrome',
      automationName: 'UiAutomator2'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'android',
    version: 'phone-67.1',
    browserName: 'chrome',
    automationName: 'UiAutomator2'
  }
}
2021-04-12T09:48:36.966Z INFO webdriver: COMMAND navigateTo("https://yandex.ru/")
2021-04-12T09:48:36.967Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/f6eae119280f7f6ad0ea26d8d5edba73acae996f-2736-4920-97e7-636a5652123c/url
2021-04-12T09:48:36.967Z INFO webdriver: DATA { url: 'https://yandex.ru/' }
client.isW3C: true
2021-04-12T09:48:38.990Z INFO webdriver: COMMAND performActions(<object>)
2021-04-12T09:48:38.991Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/f6eae119280f7f6ad0ea26d8d5edba73acae996f-2736-4920-97e7-636a5652123c/actions
2021-04-12T09:48:38.993Z INFO webdriver: DATA { actions: [ { type: 'key', id: 'keyboard', actions: [Array] } ] }
2021-04-12T09:48:39.179Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
2021-04-12T09:48:39.180Z INFO webdriver: Retrying 1/3
2021-04-12T09:48:39.180Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/f6eae119280f7f6ad0ea26d8d5edba73acae996f-2736-4920-97e7-636a5652123c/actions
2021-04-12T09:48:39.180Z INFO webdriver: DATA { actions: [ { type: 'key', id: 'keyboard', actions: [Array] } ] }
2021-04-12T09:48:39.308Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
2021-04-12T09:48:39.308Z INFO webdriver: Retrying 2/3
2021-04-12T09:48:39.308Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/f6eae119280f7f6ad0ea26d8d5edba73acae996f-2736-4920-97e7-636a5652123c/actions
2021-04-12T09:48:39.308Z INFO webdriver: DATA { actions: [ { type: 'key', id: 'keyboard', actions: [Array] } ] }
2021-04-12T09:48:39.428Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
2021-04-12T09:48:39.428Z INFO webdriver: Retrying 3/3
2021-04-12T09:48:39.428Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/f6eae119280f7f6ad0ea26d8d5edba73acae996f-2736-4920-97e7-636a5652123c/actions
2021-04-12T09:48:39.428Z INFO webdriver: DATA { actions: [ { type: 'key', id: 'keyboard', actions: [Array] } ] }
2021-04-12T09:48:39.572Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
unknown error: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Request failed with status code 501
    at Object.getErrorFromResponseBody (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriver/build/utils.js:189:12)
    at WebDriverRequest._request (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriver/build/request.js:168:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Browser.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/@wdio/utils/build/shim.js:79:29)
    at async /Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/issue_appium_w3c.js:25:5
2021-04-12T09:48:39.573Z INFO webdriver: COMMAND deleteSession()
2021-04-12T09:48:39.573Z INFO webdriver: [DELETE] http://MY_GRID_URL:4444/wd/hub/session/f6eae119280f7f6ad0ea26d8d5edba73acae996f-2736-4920-97e7-636a5652123c
```

Looks like the problem is here - https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-utils/src/envDetector.ts#L23-L33. I don't understand why appium considered as fully support w3c protocol.

**Comment by christian-bromann** [comment]
Can you provide what the session capabilities are that Appium returns? Currently we assume W3C WebDriver for all Appium sessions but in your case this would be wrong, causing your error. If Appium gives us more information what is being run we might can adjust that.

Can you post what:
```js
console.log(browser.capabilties)
```

returns?

**Comment by DudaGod** [comment]
Yes, of course:
```
client.capabilities: {
  androidNaturalOrientation: true,
  appActivity: 'com.google.android.apps.chrome.Main',
  appPackage: 'com.android.chrome',
  automationName: 'UiAutomator2',
  browserName: 'chrome',
  databaseEnabled: false,
  desired: {
    androidNaturalOrientation: true,
    automationName: 'UiAutomator2',
    browserName: 'chrome',
    deviceName: 'android',
    platformName: 'Android',
    version: 'phone-67.1'
  },
  deviceApiLevel: 23,
  deviceManufacturer: 'unknown',
  deviceModel: 'Android SDK built for x86',
  deviceName: 'emulator-5554',
  deviceScreenDensity: 320,
  deviceScreenSize: '720x1280',
  deviceUDID: 'emulator-5554',
  javascriptEnabled: true,
  locationContextEnabled: false,
  networkConnectionEnabled: true,
  pixelRatio: 2,
  platform: 'LINUX',
  platformName: 'Android',
  platformVersion: '6.0',
  statBarHeight: 48,
  takesScreenshot: true,
  version: 'phone-67.1',
  viewportRect: { height: 1136, left: 0, top: 48, width: 720 },
  warnings: {},
  webStorageEnabled: false
}
```

**Comment by christian-bromann** [comment]
@DudaGod sorry, maybe we could create an issue in Appium to help populate this information. Another option would be to use an older version of WebdriverIO where JSONWP is default. Please let me know if upgrading the Chrome version on the device resolves the issue. Cheers!

**Comment by wswebcreation** [comment]
@christian-bromann 

Isn't this strange, it should **not** detect W3C in the first place because the requested ones don't have W3C compliant caps, or is this in the way his grid handles the responses?

@DudaGod 

Have you tried adding this to your caps

```js
"goog:chromeOptions": {
            "w3c": false
      }
```
I'm not 100% sure if ChromeDriver 2.40 can handle this, but Appium should be able to pass this to the driver so the driver knows that the command you are sending needs to handled as a JSOWP command

**Comment by christian-bromann** [comment]
> Isn't this strange, it should **not** detect W3C in the first place because the requested ones don't have W3C compliant caps, or is this in the way his grid handles the responses?

Currently WebdriverIO decides based on the session response wether WebDriver is used or not. For Appium we default to `true` because it is in general compliant. However if Appium uses a driver that is not, there is currently no way of telling that this is the case. Therefor your suggestion won't work because the Chromedriver version being used is using JSONWP already (I don't think it even knows W3C WebDriver). The problem though is that Appium doesn't give us any clue that the underlying Chromedriver is an old one.

**Comment by wswebcreation** [comment]
ok, that makes sense @christian-bromann , thanks
