### ISSUE TITLE
elementSendKeys: throws with "Malformed type for "text" parameter of command elementSendKeys" [JSONWP]

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#6690]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.1.0
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.18.1
 - **NPM version:** 6.14.5
 - **Browser name and version:** chrome mobile 67
 - **Platform name and version:** linux

**Describe the bug**
Initially I faced with problem that when run tests in android emulator with chrome@67 and chromedriver@2.40 it does not work correctly because wdio thinks that each chromedriver version inside appium supports w3c - https://github.com/webdriverio/webdriverio/issues/6689. Then I fix it using `attach` and redefine `isW3C` to `false`.
It that case command `elementSendKeys` fails with error when calling `setValue` or `addValue`:
```
Malformed type for "text" parameter of command elementSendKeys
Expected: string
Actual: object

For more info see https://w3c.github.io/webdriver/#dfn-element-send-keys
```

**To Reproduce**

Simple test on wdio:
```
const {remote, attach} = require('webdriverio');
const {sessionEnvironmentDetector} = require('@wdio/utils');

let client, client2;

const opts = {
    protocol: 'http',
    hostname: 'MY_GRID_URL',
    port: 4444,
    path: '/wd/hub',
    automationProtocol: 'webdriver',
    capabilities: {
        platformName: 'Android',
        deviceName: 'android',
        version: 'phone-67.1',
        browserName: 'chrome',
        automationName: 'UiAutomator2',
    }
};

(async function () {
    client = await remote(opts);

    const opts2 = sessionEnvironmentDetector({capabilities: client.capabilities, requestedCapabilities: opts.capabilities});

    client2 = await attach({
        sessionId: client.sessionId,
        ...opts,
        ...opts2,
        isW3C: false
    });

    console.log('client2.isW3C:', client2.isW3C);

    await client2.url('https://yandex.ru');

    const elem = await client2.$('.mini-suggest__input');
    await elem.setValue('some text');

    await client.deleteSession();
})()
    .catch(async (e) => {
        console.error(e.stack)
        await client.deleteSession()
    });
```

**Expected behavior**
`elementSendKeys` works correctly and pass string instead array with jsonwp protocol.

**Log**
Session log - https://gist.github.com/DudaGod/2676ebfe796c4bcaea5955c3361b1699.
Wdio log from console:
```
node ./issue_appium_elementSendKeys.js
2021-04-12T10:33:05.120Z INFO webdriver: Initiate new session using the WebDriver protocol
2021-04-12T10:33:05.125Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session
2021-04-12T10:33:05.125Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'Android',
      deviceName: 'android',
      version: 'phone-67.1',
      browserName: 'chrome',
      automationName: 'UiAutomator2'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'Android',
    deviceName: 'android',
    version: 'phone-67.1',
    browserName: 'chrome',
    automationName: 'UiAutomator2'
  }
}
ENV DETECTOR VARIABLES: {
  isW3C: true,
  isChrome: false,
  isMobile: true,
  isIOS: false,
  isAndroid: true,
  isSauce: false,
  isSeleniumStandalone: false
}
client2.isW3C: false
2021-04-12T10:33:27.880Z INFO webdriver: COMMAND navigateTo("https://yandex.ru/")
2021-04-12T10:33:27.881Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/4ca15c2f547f751dcb658eecf1389543131d6db2-333c-46e8-b1d6-925b05441120/url
2021-04-12T10:33:27.881Z INFO webdriver: DATA { url: 'https://yandex.ru/' }
2021-04-12T10:33:29.679Z INFO webdriver: COMMAND findElement("css selector", ".mini-suggest__input")
2021-04-12T10:33:29.679Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/4ca15c2f547f751dcb658eecf1389543131d6db2-333c-46e8-b1d6-925b05441120/element
2021-04-12T10:33:29.680Z INFO webdriver: DATA { using: 'css selector', value: '.mini-suggest__input' }
2021-04-12T10:33:29.828Z INFO webdriver: RESULT {
  'element-6066-11e4-a52e-4f735466cecf': '0.48465860170567665-1',
  ELEMENT: '0.48465860170567665-1'
}
2021-04-12T10:33:29.841Z INFO webdriver: COMMAND elementClear("0.48465860170567665-1")
2021-04-12T10:33:29.841Z INFO webdriver: [POST] http://MY_GRID_URL:4444/wd/hub/session/4ca15c2f547f751dcb658eecf1389543131d6db2-333c-46e8-b1d6-925b05441120/element/0.48465860170567665-1/clear
Error: Malformed type for "text" parameter of command elementSendKeys
Expected: string
Actual: object

For more info see https://w3c.github.io/webdriver/#dfn-element-send-keys

    at Element.protocolCommand (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriver/build/command.js:53:23)
    at Element.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/@wdio/utils/build/shim.js:79:38)
    at Element.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/@wdio/utils/build/shim.js:79:38)
    at Element.elementErrorHandlerCallbackFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriverio/build/middlewares.js:23:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Element.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/@wdio/utils/build/shim.js:79:29)
    at async Element.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/@wdio/utils/build/shim.js:79:29)
    at async Element.elementErrorHandlerCallbackFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/webdriverio/build/middlewares.js:23:32)
    at async Element.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/@wdio/utils/build/shim.js:79:29)
    at async Element.wrapCommandFn (/Users/dudkevich/job/projects/dudkevich-scripts/FEI-20461.wdio_6/node_modules/@wdio/utils/build/shim.js:79:29)
2021-04-12T10:33:30.002Z INFO webdriver: COMMAND deleteSession()
2021-04-12T10:33:30.003Z INFO webdriver: [DELETE] http://MY_GRID_URL:4444/wd/hub/session/4ca15c2f547f751dcb658eecf1389543131d6db2-333c-46e8-b1d6-925b05441120
```

It looks like the problem is here - https://github.com/webdriverio/webdriverio/blob/9d2220e89144b0ca69232737957ad5fc32ca1300/packages/webdriverio/src/commands/element/addValue.ts#L40

**Comment by christian-bromann** [comment]
It seems that your workaround didn't work as the WebDriver protocol is still applied to the WebdriverIO object. I suggest to continue conversations in  #6689
