### ISSUE TITLE
v7.4.0 Error: Cannot find module '../build'

### ISSUE THREAD

**Issue by zarko-tg** [webdriverio/webdriverio#6705]
Just tried upgrading from 7.3.1 to 7.4.0 and tests won't run at all now.

**Environment:**
 - **WebdriverIO version:** 7.4.0
 - **Mode:** WDIO Testrunner / local
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.22.1
 - **NPM version:** 6.14.12
 - **Browser name and version:** Chrome 89 / stable
 - **Platform name and version:** MacOS Big Sur
 - **Additional wdio packages used (if applicable):** @wdio/cli @wdio/jasmine-framework @wdio/local-runner @wdio/spec-reporter @wdio/sync

**Describe the bug**
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../build'
Require stack:
- /Users/foo/bar/node_modules/@wdio/cli/bin/wdio.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/foo/bar/node_modules/@wdio/cli/bin/wdio.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/foo/bar/node_modules/@wdio/cli/bin/wdio.js' ]
}
```

**Comment by adong** [comment]
Second this. The same error is happening to us.

**Comment by BorisOsipov** [comment]
@christian-bromann smth wrong with release build. see log https://github.com/webdriverio/webdriverio/runs/2336069116?check_suite_focus=true#step:8:45

**Comment by christian-bromann** [comment]
Sorry about that, fixing right now

**Comment by christian-bromann** [comment]
A new release was triggered: https://github.com/webdriverio/webdriverio/runs/2336971321?check_suite_focus=true

**Comment by christian-bromann** [comment]
Without being certain but it seems that NPM v7 is defaulting to workspaces which we don't have setup properly as we still use Lerna for managing the monorepo. I think it is time to switch to Yarn or stay and use NPM workspaces.

**Comment by BorisOsipov** [comment]
@christian-bromann 
```
2021-04-13T19:58:28.3201234Z lerna info Looking for changed packages since v7.4.0
2021-04-13T19:58:28.5407685Z lerna success No changed packages to publish 
```
Seems nothing new published

**Comment by christian-bromann** [comment]
Yeah, had to rerun with `--force-publish`

**Comment by christian-bromann** [comment]
`v7.4.1` published with build directory. I will close this and create an issue for moving to NPM/Yarn workspaces. Sorry all for the inconvenience. Please let if this error still occurs.
