### ISSUE TITLE
Interaction with chrome browser gets stopped when running tests in parallel

### ISSUE THREAD

**Issue by chanchow88** [webdriverio/webdriverio#6764]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.2.3
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v12.16.1
 - **NPM version:** 6.14.5
 - **Browser name and version:** Chrome 90
 - **Platform name and version:** Mac Catalina
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
 I did download and use https://github.com/WarleyGabriel/demo-webdriverio-mocha. The only change I did was to set maxInstances to 6 in wdio.config.js

**Describe the bug**
When I am trying to run mocha tests with maxInstances of 6 or greater, I am seeing the following
```
[2021-04-26T19:23:42.952Z INFO webdriver: RESULT true
[2021-04-26T19:23:44.283Z] events.js:288
[2021-04-26T19:23:44.283Z]       throw er; // Unhandled 'error' event
[2021-04-26T19:23:44.283Z]       ^
[2021-04-26T19:23:44.283Z] 
[2021-04-26T19:23:44.283Z] Error [ERR_STREAM_WRITE_AFTER_END]: write after end
[2021-04-26T19:23:44.283Z]     at writeAfterEnd (_stream_writable.js:264:14)
[2021-04-26T19:23:44.283Z]     at RunnerStream.Writable.write (_stream_writable.js:313:5)
[2021-04-26T19:23:44.283Z]     at RunnerTransformStream.ondata (_stream_readable.js:714:22)
[2021-04-26T19:23:44.283Z]     at RunnerTransformStream.emit (events.js:311:20)
[2021-04-26T19:23:44.283Z]     at RunnerTransformStream.EventEmitter.emit (domain.js:482:12)
[2021-04-26T19:23:44.283Z]     at addChunk (_stream_readable.js:294:12)
[2021-04-26T19:23:44.283Z]     at readableAddChunk (_stream_readable.js:275:11)
[2021-04-26T19:23:44.283Z]     at RunnerTransformStream.Readable.push (_stream_readable.js:209:10)
[2021-04-26T19:23:44.283Z]     at RunnerTransformStream.Transform.push (_stream_transform.js:152:32)
[2021-04-26T19:23:44.283Z]     at RunnerTransformStream._transform (/var/lib/jenkins/workspace/Engage-UI-Regression/node_modules/@wdio/local-runner/build/transformStream.js:26:10)
[2021-04-26T19:23:44.283Z] Emitted 'error' event on RunnerStream instance at:
[2021-04-26T19:23:44.283Z]     at errorOrDestroy (internal/streams/destroy.js:108:12)
[2021-04-26T19:23:44.283Z]     at writeAfterEnd (_stream_writable.js:266:3)
[2021-04-26T19:23:44.283Z]     at RunnerStream.Writable.write (_stream_writable.js:313:5)
[2021-04-26T19:23:44.283Z]     [... lines matching original stack trace ...]
[2021-04-26T19:23:44.283Z]     at RunnerTransformStream.Transform.push (_stream_transform.js:152:32) {
[2021-04-26T19:23:44.283Z]   code: 'ERR_STREAM_WRITE_AFTER_END'`
```
**To Reproduce**
Try to run a project with multiple spec files with maxInstances > 6.

[https://github.com/chanchow88/test-project1]

**Expected behavior**
Tests should either fail or pass.

**Log**
If applicable, add logs to help explain your problem.
Create a [<script src="https://gist.github.com/chanchow88/9b0d2fc204a7df1afa8a6051534a6c14.js"></script>]

**Additional context**
This doesn't happen when you try to run single threaded. Just happens when you run on multiple instances and leaves behind the chrome browsers.

> Please use the correct markdown

**Comment by christian-bromann** [comment]
@chanchow88 thanks for filing the issue, when running the [example project](https://github.com/chanchow88/test-project1) everything passed for me. Can you provide a reproducible example?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
