### ISSUE TITLE
'Session closed. Most likely the page has been closed' error seen when browser.mock called after browser.sessionReload

### ISSUE THREAD

**Issue by johnson-tyl** [webdriverio/webdriverio#6786]
**Environment:**
 - **WebdriverIO version:** v7 (but seen on v6 as well)
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.18.3
 - **NPM version:** 6.14.11
 - **Browser name and version:** Chrome 90
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** 
    - @wdio/cucumber-framework
    - @wdio/local-runner
    - @wdio/selenium-standalone-service
    - @wdio/sync 

**Config of WebdriverIO**: Its nothing bespoke, we run a cucumber based framework and since its a E2E framework we have a few applications on different domain and reloading session (closing & opening browser) helps us reset the state better.
```javascript
    afterScenario: function (world) {
        browser.reloadSession();
    },
```

**Describe the bug**
When using `browser.mock()` after calling `browser.sessionReload()`, I am seeing the below error message:

```javascript
Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (C:\Users\user\workspace\node.js\browser.mock-defect\node_modules\puppeteer-core\src\common\Connection.ts:251:9)
    at ExecutionContext._evaluateInternal (C:\Users\user\workspace\node.js\browser.mock-defect\node_modules\puppeteer-core\src\common\ExecutionContext.ts:252:44)
    at ExecutionContext.evaluate (C:\Users\user\workspace\node.js\browser.mock-defect\node_modules\puppeteer-core\src\common\ExecutionContext.ts:138:23)
    at DOMWorld.evaluate (C:\Users\user\workspace\node.js\browser.mock-defect\node_modules\puppeteer-core\src\common\DOMWorld.ts:163:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Browser.runCommandWithHooks (C:\Users\user\workspace\node.js\browser.mock-defect\node_modules\@wdio\sync\build\wrapCommand.js:100:24)
    at Browser.wrapCommandFn (C:\Users\user\workspace\node.js\browser.mock-defect\node_modules\@wdio\sync\build\wrapCommand.js:67:44)
    at World.<anonymous> (C:\Users\user\workspace\node.js\browser.mock-defect\features\step-definitions\steps.js:11:29)
    at World.executeSync (C:\Users\user\workspace\node.js\browser.mock-defect\node_modules\@wdio\sync\build\index.js:38:22)
    at C:\Users\user\workspace\node.js\browser.mock-defect\node_modules\@wdio\sync\build\index.js:69:68
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup two scenarios that use `browser.mock()` to spy on a network request
2. Now in the wdio.conf.js file, in `afterScenario()` hook call `browser.sessionReload()`
3. When you run these tests, the first test will pass but the 2nd will fail with the error seen above.

**Expected behaviour**
It should work like the first test.

**Log**
https://gist.github.com/johnson-tyl/e50752561d577f0e88c11f11528eefed

I have attached a sample project where you can see this happening:
[browser.mock-defect.zip](https://github.com/webdriverio/webdriverio/files/6406927/browser.mock-defect.zip)
You can run `npm i` followed by `npm test` to run the test zip file.

**NOTE**: The first test also fails in the sample project but the reason for that is different, there not much to spy on on this page, so probably it goes too quickly for mock to detect its already come back with 200.

**Comment by lawynnj** [comment]
Hello @christian-bromann, do you mind if I take stab at this?

**Comment by christian-bromann** [comment]
@lawynnj sure! Please let me know if I can help you in any way.

**Comment by jonn-set** [comment]
@lawynnj @christian-bromann any update on this, please?

**Comment by jonn-set** [comment]
I have pushed a fix, please review. Thanks
