### ISSUE TITLE
Devtools Error on Selenium 4 Grid

### ISSUE THREAD

**Issue by th0car** [webdriverio/webdriverio#6816]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.5.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.18.1
 - **NPM version:**  6.14.5
 - **Browser name and version:** Chrome 90
 - **Platform name and version:** Selenium Grid 4.0.0-beta-3 is running on Openshift/Kubernetes 1.19, Tests are executed from Windows 10 
 - **Additional wdio packages used (if applicable):**   @wdio/devtools-service 7.5.3

**Config of WebdriverIO**
conf:
```
exports.config = {
  runner: "local",

  hostname: "selenium4-router.mydomain.com",
  port: 443,
  protocol: "https",
  
  specs: ["./test/specs/**/*.js"],
 
  maxInstances: 1,
  capabilities: [
    {
      maxInstances: 1,
      //
      browserName: "chrome",
      platformName: "LINUX",
      "goog:chromeOptions": {
        args: [
          "--allow-insecure-localhost"
        ],
     },
    acceptInsecureCerts: true,
    },
  ],
  logLevel: "debug",
  bail: 0,
  baseUrl: "https://front.mydomain.com/",
  waitforTimeout: 10000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  
  services: ["devtools"],

  framework: "mocha",
  
  reporters: ["spec"],

  mochaOpts: {
    ui: "bdd",
    timeout: 60000,
  },
 };
```

package.json:
```
{
  "name": "wdio7gettingstarted",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@wdio/cli": "^7.5.3"
  },
  "devDependencies": {
    "@wdio/local-runner": "^7.5.5",
    "@wdio/mocha-framework": "^7.5.3",
    "@wdio/spec-reporter": "^7.5.3",
    "chromedriver": "^90.0.0",
    "wdio-chromedriver-service": "^7.0.0",
    "@wdio/devtools-service": "^7.5.3"
  }
}
```

**Describe the bug**
When trying to execute a test using devtools functions (for example emulateDevice) on a Selenium 4 Grid tests fail with this error: 

> ERROR @wdio/utils:shim: Error: Using DevTools capabilities is not supported for this session. This feature is only supported for local testing on Chrome, Firefox and Chromium Edge.

(full log below)

**To Reproduce**

1. Fresh install of wdio
2. Run config (Answer NO to compiler question)
3. Install @wdio/devtools-service 
4. Modify conf (add devtools as Service and modify capabilities)
5. Create spec (code below) 
6. Run test locally using chromedriver - Test passes 
7. Modify conf to use Selenium grid - Test fails

spec:
```
describe('Front Page', () => {
    it('should have correct title', async () => {
        await browser.emulateDevice('iPhone X');
        await browser.url("https://foo.mydomain.com/")
        await expect(await browser.getTitle()).toBe('foo');
     });
});
```

**Expected behavior**
devtools emulateDevice function should be supported on Selenium 4 grid and test should pass. 

**Log**
```
2021-05-05T11:22:31.494Z DEBUG @wdio/utils:initialiseServices: initialise service "devtools" as NPM package
2021-05-05T11:22:32.362Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-05-05T11:22:32.364Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-05-05T11:22:32.366Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./grid.conf.js
[0-0] 2021-05-05T11:22:33.612Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2021-05-05T11:22:33.616Z DEBUG @wdio/config:ConfigParser: No compiler found, continue without compiling files
[0-0] 2021-05-05T11:22:33.619Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-05-05T11:22:33.623Z DEBUG @wdio/utils:initialiseServices: initialise service "devtools" as NPM package
[0-0] 2021-05-05T11:22:34.535Z DEBUG @wdio/utils:shim: Finished to run "beforeSession" hook in 0ms
[0-0] RUNNING in chrome - C:\WS\wdio7GettingStarted\test\specs\front.test.js
[0-0] 2021-05-05T11:22:34.847Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-05-05T11:22:34.848Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-05-05T11:22:34.851Z INFO webdriver: [POST] https://selenium4-router.mydomain.com/session
[0-0] 2021-05-05T11:22:34.851Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       platformName: 'LINUX',
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     platformName: 'LINUX',
[0-0]     'goog:chromeOptions': { args: [Array], acceptInsecureCerts: true }
[0-0]   }
[0-0] }
[0-0] 2021-05-05T11:22:36.157Z DEBUG @wdio/utils:shim: Finished to run "beforeCommand" hook in 0ms
[0-0] 2021-05-05T11:22:36.157Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
[0-0] 2021-05-05T11:22:36.158Z ERROR @wdio/utils:shim: Error: Using DevTools capabilities is not supported for this session. This feature is only supported for local testing on Chrome, Firefox and Chromium Edge.
[0-0]     at Browser.getPuppeteer (C:\WS\wdio7GettingStarted\node_modules\webdriverio\build\commands\browser\getPuppeteer.js:117:11)
[0-0]     at Browser.wrapCommandFn (C:\WS\wdio7GettingStarted\node_modules\@wdio\utils\build\shim.js:78:38)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0]     at async DevToolsService._setupHandler (C:\WS\wdio7GettingStarted\node_modules\@wdio\devtools-service\build\index.js:173:27)
[0-0]     at async Promise.all (index 0)
[0-0]     at async Object.executeHooksWithArgsShim (C:\WS\wdio7GettingStarted\node_modules\@wdio\utils\build\shim.js:49:20)
[0-0]     at async Runner.run (C:\WS\wdio7GettingStarted\node_modules\@wdio\runner\build\index.js:95:9)
[0-0] 2021-05-05T11:22:36.158Z DEBUG @wdio/utils:shim: Finished to run "before" hook in 1ms
[0-0] TypeError in "Front Page should have correct title"
TypeError: browser.emulateDevice is not a function
    at Context.<anonymous> (C:\WS\wdio7GettingStarted\test\specs\front.test.js:5:23)
    at Context.executeAsync (C:\WS\wdio7GettingStarted\node_modules\@wdio\utils\build\shim.js:136:25)
    at Context.testFrameworkFnWrapper (C:\WS\wdio7GettingStarted\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:45:32)
[0-0] 2021-05-05T11:22:36.166Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
2021-05-05T11:22:36.300Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - C:\WS\wdio7GettingStarted\test\specs\front.test.js
2021-05-05T11:22:36.302Z INFO @wdio/cli:launcher: Run onComplete hook
```

**Additional context**
Selenium 4 grid is set up using the [Distributed Mode](https://www.selenium.dev/documentation/en/grid/grid_4/setting_up_your_own_grid/#distributed-mode) deloyed to OpenShift and the router is accessed using SSL / port 443

**Comment by BorisOsipov** [comment]
@th0car can you show logs from `console.log(browser.capabilities)` ?

e.g.

```
describe('foo', () => {
    it('bar', async () => {
		console.log(browser.capabilities)
     });
});
```

**Comment by th0car** [comment]
@BorisOsipov - This is how it looks after correcting capabilities ("acceptInsecureCerts: true," was misplaced). Problem is still the same though:

```
[0-0] ## START browser capabilities
[0-0] {
[0-0]   acceptInsecureCerts: true,
[0-0]   browserName: 'chrome',
[0-0]   browserVersion: '90.0.4430.85',
[0-0]   chrome: {
[0-0]     chromedriverVersion: '90.0.4430.24 (4c6d850f087da467d926e8eddb76550aed655991-refs/branch-heads/4430@{#429})',
[0-0]     userDataDir: '/tmp/.com.google.Chrome.FXtFGX'
[0-0]   },
[0-0]   'goog:chromeOptions': { debuggerAddress: 'localhost:37133' },
[0-0]   networkConnectionEnabled: false,
[0-0]   pageLoadStrategy: 'normal',
[0-0]   platformName: 'LINUX',
[0-0]   proxy: {},
[0-0]   'se:cdp': 'http://10.7.117.176:5555/session/5088e1101da7941bff01c7612e14f98c/se/cdp',
[0-0]   'se:cdpVersion': '90.0.4430.85',
[0-0]   setWindowRect: true,
[0-0]   strictFileInteractability: false,
[0-0]   timeouts: { implicit: 0, pageLoad: 300000, script: 30000 },
[0-0]   unhandledPromptBehavior: 'dismiss and notify',
[0-0]   'webauthn:extension:largeBlob': true,
[0-0]   'webauthn:virtualAuthenticators': true
[0-0] }
[0-0] ## END browser capabilities
```

**Comment by BorisOsipov** [comment]
@th0car Thanks. At first sight all seems to be correct. We handle CDP connection for grid here
https://github.com/webdriverio/webdriverio/blob/24cfb104a95a9d9df73d8dee39cf6dae2f19b7c4/packages/webdriverio/src/commands/browser/getPuppeteer.ts#L55-L62

and it should work for your setup. Idk what is wrong and how to fix without access to Selenium 4 grid setup.

**Comment by BorisOsipov** [comment]
and not related to this issue but may be important for you.
`'se:cdp': 'http://10.7.117.176:5555/session/5088e1101da7941bff01c7612e14f98c/se/cdp',` - `10.7.117.176:5555` - seems to be selenium node ip not selenium server. So won't able to connect to it. Probably you can fix it by step from [issue/9202](https://github.com/SeleniumHQ/selenium/issues/9202#issuecomment-799435392)

**Comment by th0car** [comment]
Thank you @BorisOsipov  - You are right about the IP - it belongs to a node on the grid. I will have a look at 9202! 

For anyone else looking into this:
The goog:chromeOptions was incorrectly set which I noted when logging browser.capabilities. After fixing this the "TypeError: browser.emulateDevice is not a function" error still occurs as well as the "ERROR @wdio/utils:shim: undefined" 
The error concerning "@wdio/utils:shim: Error: Using DevTools capabilities is not supported for this session. This feature is only supported for local testing on Chrome" and all mentions of errors regarding Puppeteer are now gone from the log. 

This is the log now (so please disregard the original log above):

```
2021-05-05T12:46:38.227Z DEBUG @wdio/utils:initialiseServices: initialise service "devtools" as NPM package
2021-05-05T12:46:39.540Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-05-05T12:46:39.543Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-05-05T12:46:39.545Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./grid.conf.js
[0-0] 2021-05-05T12:46:41.062Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2021-05-05T12:46:41.067Z DEBUG @wdio/config:ConfigParser: No compiler found, continue without compiling files
[0-0] 2021-05-05T12:46:41.072Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-05-05T12:46:41.079Z DEBUG @wdio/utils:initialiseServices: initialise service "devtools" as NPM package
[0-0] 2021-05-05T12:46:42.202Z DEBUG @wdio/utils:shim: Finished to run "beforeSession" hook in 0ms
[0-0] RUNNING in chrome - C:\WS\wdio7GettingStarted\test\specs\front.test.js
[0-0] 2021-05-05T12:46:42.516Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-05-05T12:46:42.517Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-05-05T12:46:42.518Z INFO webdriver: [POST] https://omni-selenium-router.sebshift.dev.sebank.se/session
[0-0] 2021-05-05T12:46:42.519Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       platformName: 'LINUX',
[0-0]       'goog:chromeOptions': [Object],
[0-0]       acceptInsecureCerts: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     platformName: 'LINUX',
[0-0]     'goog:chromeOptions': { args: [Array] },
[0-0]     acceptInsecureCerts: true
[0-0]   }
[0-0] }
[0-0] 2021-05-05T12:46:44.406Z DEBUG @wdio/utils:shim: Finished to run "beforeCommand" hook in 0ms
[0-0] 2021-05-05T12:47:05.415Z DEBUG @wdio/utils:shim: Finished to run "afterCommand" hook in 0ms
**[0-0] 2021-05-05T12:47:05.417Z ERROR @wdio/utils:shim: undefined**
[0-0] 2021-05-05T12:47:05.418Z DEBUG @wdio/utils:shim: Finished to run "before" hook in 21012ms
[0-0] TypeError in "Front Page should have correct title"
**TypeError: browser.emulateDevice is not a function**
    at Context.<anonymous> (C:\WS\wdio7GettingStarted\test\specs\front.test.js:5:23)
    at Context.executeAsync (C:\WS\wdio7GettingStarted\node_modules\@wdio\utils\build\shim.js:136:25)
    at Context.testFrameworkFnWrapper (C:\WS\wdio7GettingStarted\node_modules\@wdio\utils\build\test-framework\testFnWrapper.js:45:32)

```

**Comment by BorisOsipov** [comment]
@th0car `browser.emulateDevice()` commands added here
https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-devtools-service/src/index.ts#L279

you can debug with few `console.log(smth)` to fing why service skipped adding command.

**Comment by th0car** [comment]
New findings:
I have tried to configure my environments so that I can have NODE_TLS_REJECT_UNAUTHORIZED set to 1 for all my testprojects (including those that use the same Selenium grid and test target host as in the sample above) However the project that use devtools apparantly requires some additional certificate at some point where the other tests don't since setting  NODE_TLS_REJECT_UNAUTHORIZED to 0 "fixes" the problem in this issue.

I understand that this is most likely an internal infrastructure problem at my company or in my config, but I can't be sure that it it's not also connected to devtools acting differently in a way that is not correct. I haven't been able to find exactly where in the code the problem occurs. Unfortunately my Openshift Selenium Grid Router cannot be set to use http (instead of https as it does now) which would have been an interesting experiment.

**Comment by th0car** [comment]
Problem was solved by setting NODE_EXTRA_CA_CERTS to the path to a self signed cert that seems to be required by devtools at some stage.

**Comment by shweta-ai** [comment]
@th0car I'm facing same issue when trying to use `browser.cdp()` in grid. I tried adding a self signed certificate like you have suggested here but I'm still facing same issue . Can you add detailed steps or blog post on how you added self signed certificate and set up NODE_EXTRA_CA_CERTS in tests?

**Comment by th0car** [comment]
1. I created a folder in my test project root named 'cert' and copied the certificate to this folder
2. Before running my tests I set NODE_EXTRA_CA_CERTS in the terminal using Powershell:
`$env:NODE_EXTRA_CA_CERTS='c:/WS/testproject/cert/CertName.pem'`

It should be noted that setting SE_NODE_GRID_URL for your chrome nodes in your Selenium4 Grid (as described in [https://github.com/SeleniumHQ/selenium/issues/9202#issuecomment-799435392](https://github.com/SeleniumHQ/selenium/issues/9202#issuecomment-799435392)) is also essential.
