### ISSUE TITLE
[M1 Mac]Only x64 architecture is available for chromium edge driver for mac

### ISSUE THREAD

**Issue by vjmaiky** [webdriverio/webdriverio#6923]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.6.1
 - **Mode:** selenium-standalone
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 15.13.0
 - **NPM version:** 7.8.0
 - **Browser name and version:** Chrome Version 90.0.4430.212 (Official Build) (arm64)
 - **Platform name and version:** M1 Mac Big Sur 11.3.1
 - **Additional wdio packages used (if applicable):** 

```
  "devDependencies": {
    "@wdio/dot-reporter": "^7.6.0",
    "@wdio/local-runner": "^7.6.1",
    "@wdio/mocha-framework": "^7.6.0",
    "@wdio/selenium-standalone-service": "^7.6.0",
    "@wdio/spec-reporter": "^7.6.1",
    "chai": "^4.3.4",
    "chai-webdriverio": "^1.0.0",
    "local-runner": "*",
    "webdriverio": "^7.6.1"
  },
  "dependencies": {
    "@wdio/cli": "^7.6.1"
  }
```

**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    specs: [
        './test/**/*.js'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 10,
     capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true
    }],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://the-internet.herokuapp.com/',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['selenium-standalone'],
    framework: 'mocha',
    reporters: ['spec','dot'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
      beforeTest: function (test, context) {
        const chai = require('chai')
        const chaiWebdriver = require('chai-webdriverio').default
        chai.use(chaiWebdriver(browser))
        global.assert = chai.assert
        global.shoul = chai.should
        global.expect = chai.expect
    }
}
```

**Describe the bug**
Error: Only x64 architecture is available for chroimum edge driver for mac when trying to run a simple mock test.

**To Reproduce**
run the test

[Include code or an example repository that can easily be set up]
```
describe("interacting with elements", () => {
    it('Get text for element', () => {
        browser.url('/');
        let text = $("h2").getText();
        console.log(text);
    })
})
```

**Expected behavior**
To run the test?

**Log**
```
Execution of 5 workers started at 2021-05-27T05:57:00.113Z

2021-05-27T05:57:00.114Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
2021-05-27T05:57:00.140Z INFO @wdio/cli:launcher: Run onPrepare hook
/Users/Shared/Cypress/webDriverIo/node_modules/selenium-standalone/lib/compute-download-urls.js:312
    throw new Error('Only x64 architecture is available for chroimum edge driver for mac');
          ^

Error: Only x64 architecture is available for chroimum edge driver for mac
    at getMacChromiumEdgeDriverArchitecture (/Users/Shared/Cypress/webDriverIo/node_modules/selenium-standalone/lib/compute-download-urls.js:312:11)
    at getChromiumEdgeDriverArchitecture (/Users/Shared/Cypress/webDriverIo/node_modules/selenium-standalone/lib/compute-download-urls.js:290:16)
    at computeDownloadUrls (/Users/Shared/Cypress/webDriverIo/node_modules/selenium-standalone/lib/compute-download-urls.js:107:9)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async install (/Users/Shared/Cypress/webDriverIo/node_modules/selenium-standalone/lib/install.js:91:16)
lmihai@EN1410924 webDriverIo % 
```

**Comment by christian-bromann** [comment]
This is an issue with the [`vvo/selenium-standalone`](https://github.com/vvo/selenium-standalone/blob/master/lib/compute-download-urls.js#L309-L316) project. Please file an issue there. Thank you!
