### ISSUE TITLE
browser.enablePerformanceMetrics() network tracing never reports complete page load  

### ISSUE THREAD

**Issue by esaari** [webdriverio/webdriverio#6932]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:**  7.6.1
 - **Mode:** [Standalone mode or WDIO Testrunner] wdio testrunner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:**  14.16.0
 - **NPM version:** 7.12.0
 - **Browser name and version:** Chrome 91
 - **Platform name and version:** Mac Big Sur
 - **Additional wdio packages used (if applicable):** @wdio/devtools-service

**Config of WebdriverIO**
```
{
  "name": "wdio7",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@wdio/cli": "7.6.1",
    "@wdio/devtools-service": "7.6.1",
    "@wdio/local-runner": "^7.6.1",
    "@wdio/mocha-framework": "^7.6.0",
    "@wdio/spec-reporter": "^7.6.1",
    "@wdio/sync": "^7.6.1",
    "chromedriver": "^90.0.1",
    "wdio-chromedriver-service": "^7.1.0",
    "webdriverio": "^7.6.1"
  }
}
```

**Describe the bug**
In my example, the network tracer never seems to acknowledge the page load is complete.  This is using the same script in the example at https://webdriver.io/docs/devtools-service/#performance-testing

**To Reproduce**
1. unzip my example
2. `npm install`
3. `npx wdio desktop-chrome.conf.js`

**Expected behavior**
Test runs and passes, as per the example in the documentation.

**Log**
See stacktrace.log for full trace, but gist of the exception is:
```
...
[0-0] 2021-05-28T13:51:09.737Z DEBUG @wdio/devtools-service: cdp event: Page.lifecycleEvent with params {"frameId":"CD2B0BBAE52E25E1248B97730B9623A2","loaderId":"F1DAE83AB441003EAB34B88721CE56D7","name":"networkIdle","timestamp":159420.459974}
[0-0] 2021-05-28T13:51:23.424Z DEBUG @wdio/devtools-service: cdp event: event with params undefined
[0-0] 2021-05-28T13:51:23.425Z INFO @wdio/devtools-service:TraceGatherer: Driver CPU has been idle for 14551.700000017881 ms
[0-0] 2021-05-28T13:51:23.931Z DEBUG @wdio/devtools-service: cdp event: event with params undefined
[0-0] 2021-05-28T13:51:23.932Z INFO @wdio/devtools-service:TraceGatherer: Driver CPU has been idle for 15059.09999999404 ms
[0-0] Error in "JSON.org page should load within performance budget"
Error: Timeout of 30000ms exceeded. The execution in the test "JSON.org page should load within performance budget" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/Users/ericsaari/code/wdio6/test.js)
    at createTimeoutError (/Users/ericsaari/code/wdio6/node_modules/mocha/lib/errors.js:498:15)
    at Test.Runnable._timeoutError (/Users/ericsaari/code/wdio6/node_modules/mocha/lib/runnable.js:431:10)
    at Timeout.<anonymous> (/Users/ericsaari/code/wdio6/node_modules/mocha/lib/runnable.js:246:24)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Additional context**
In the Cucumber framework that I normally work with, I seem to be getting a more detailed stacktrace (I'm honestly not sure why I cannot get this in the simple example I provided, perhaps it's Cucumber vs. Mocha). I'm providing it here as it may give some clues as to where the problem lies...
```
[0-0] (node:84000) UnhandledPromiseRejectionWarning: TypeError: networkStatusMonitor.is2Idle is not a function
[0-0]     at domContentLoadedListener (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/@wdio/devtools-service/build/gatherer/trace.js:280:38)
[0-0]     at onceHandler (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/puppeteer-core/src/common/EventEmitter.ts:114:7)
[0-0]     at /Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/puppeteer-core/vendor/mitt/src/index.ts:88:75
[0-0]     at Array.map (<anonymous>)
[0-0]     at Object.emit (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/puppeteer-core/vendor/mitt/src/index.ts:88:56)
[0-0]     at CDPSession.emit (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/puppeteer-core/src/common/EventEmitter.ts:102:18)
[0-0]     at CDPSession.ProtocolSession.session.emit (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/lighthouse/lighthouse-core/fraggle-rock/gather/session.js:25:27)
[0-0]     at CDPSession._onMessage (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/puppeteer-core/src/common/Connection.ts:299:12)
[0-0]     at Connection._onMessage (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/puppeteer-core/src/common/Connection.ts:137:28)
[0-0]     at WebSocket.<anonymous> (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/puppeteer-core/src/node/NodeWebSocketTransport.ts:41:42)
[0-0]     at WebSocket.onMessage (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:132:16)
[0-0]     at WebSocket.emit (events.js:327:22)
[0-0]     at WebSocket.EventEmitter.emit (domain.js:467:12)
[0-0]     at Receiver.receiverOnMessage (/Users/ericsaari/code/jwplayer-commercial/test/jwp-wdio/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:834:20)
[0-0]     at Receiver.emit (events.js:315:20)
[0-0]     at Receiver.EventEmitter.emit (domain.js:467:12)
[0-0] (Use `node --trace-warnings ...` to show where the warning was created)
...
(this repeats until the script terminates) 
```

**Comment by esaari** [comment]
[wdio7.zip](https://github.com/webdriverio/webdriverio/files/6561516/wdio7.zip)
