### ISSUE TITLE
I can't open firefox on v7.6.1 

### ISSUE THREAD

**Issue by hieutrandn9889** [webdriverio/webdriverio#6942]
Today, I run firefox but it doesn't work

// wdio.conf.js
const drivers = {
    firefox: { version: '0.29.1' }, // https://github.com/mozilla/geckodriver/releases
}

export.config = {
                  capabilities: [{
                          maxInstances: 5,
                          browserName: 'firefox',
                          acceptInsecureCerts: true,
                      }],
                services: [
                    ['selenium-standalone', {
                        logPath: 'logs',
                        installArgs: { drivers }, // drivers to install
                        args: { drivers } // drivers to use
                    }]
                ],
};

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.6.1
 - **Mac:**

**Comment by christian-bromann** [comment]
Can you provide log messages?

**Comment by hieutrandn9889** [comment]
@christian-bromann  pls check log:
[0-0] RUNNING in firefox - /features/feature/login.feature
[0-0] 2021-05-31T10:00:51.552Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-0] 2021-05-31T10:00:56.464Z ERROR @wdio/runner: Error: Couldn't find executable for browser
[0-0]     at launchBrowser (/Users/tranhieu/Desktop/webdriverio_cucumber/node_modules/devtools/build/launcher.js:126:15)
[0-0]     at Object.launch [as default] (/Users/tranhieu/Desktop/webdriverio_cucumber/node_modules/devtools/build/launcher.js:167:16)
[0-0]     at Function.newSession (/Users/tranhieu/Desktop/webdriverio_cucumber/node_modules/devtools/build/index.js:50:49)
[0-0]     at Object.remote (/Users/tranhieu/Desktop/webdriverio_cucumber/node_modules/webdriverio/build/index.js:67:43)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0]     at Runner._startSession (/Users/tranhieu/Desktop/webdriverio_cucumber/node_modules/@wdio/runner/build/index.js:216:56)
[0-0]     at Runner._initSession (/Users/tranhieu/Desktop/webdriverio_cucumber/node_modules/@wdio/runner/build/index.js:172:25)
[0-0]     at Runner.run (/Users/tranhieu/Desktop/webdriverio_cucumber/node_modules/@wdio/runner/build/index.js:87:19)
[0-0] FAILED in firefox - /features/feature/login.feature

**Comment by hieutrandn9889** [comment]
@christian-bromann  Did you see the log ?

**Comment by AutomationReddy** [comment]
@hieutrandn9889 It started throwing this error recently. Please add Firefox options within capabilities and pass binary explicitly. It should work.

```js
capabilities: [{
       browserName: 'firefox',
       'moz:firefoxOptions': {
               binary: 'path/to/firefox/binary'
        }
}]
```

**Comment by hieutrandn9889** [comment]
But the config doesn't work :(
// wdio.conf.js
const drivers = {
firefox: { version: '0.29.1' }, // https://github.com/mozilla/geckodriver/releases
}

**Comment by christian-bromann** [comment]
> [0-0] 2021-05-31T10:00:51.552Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol

The logs mention that you are using Puppeteer instead of WebDriver. Have you actually set any driver in your config?

**Comment by christian-bromann** [comment]
Closing due to inactivity. Please let me know if I can further help.
