### ISSUE TITLE
Webdriverio CLI above v.7xx not working with cloud grid. (LambdaTest).  

### ISSUE THREAD

**Issue by prateekLambda** [webdriverio/webdriverio#6968]
Here is the capabilities what I am using.

` capabilities: [

    {
      platformName: "Windows 10",
      browserName: "chrome",
      browserVersion: "90.0",
      name: 'Test1',
      build: 'parallelwdio',

      "goog:chromeOptions": {
        // Install upon starting browser in order to launch it
        extensions: [
          // Entry should be a base64-encoded packed Chrome app (.crx)
          require('fs').readFileSync('crx file path').toString('base64')
        ]
      }
    }
  ],

`

### **Error message:-**

`Execution of 1 spec files started at 2021-06-03T16:17:16.108Z

2021-06-03T16:17:16.394Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-06-03T16:17:16.397Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-06-03T16:17:16.403Z INFO @wdio/local-runner: Start worker 0-0 with arg: conf/single.conf.js
[0-0] 2021-06-03T16:17:17.280Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - E:\webdriver\webdriverio-selenium-sample-master\tests\specs\single_test.js
[0-0] 2021-06-03T16:17:17.879Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-06-03T16:17:17.880Z ERROR @wdio/runner: Error: Invalid or unsupported WebDriver capabilities found ("name", "build"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).
[0-0]     at Object.startWebDriverSession (E:\webdriver\webdriverio-selenium-sample-master\node_modules\@wdio\runner\node_modules\webdriver\build\utils.js:38:19)
[0-0]     at Function.newSession (E:\webdriver\webdriverio-selenium-sample-master\node_modules\@wdio\runner\node_modules\webdriver\build\index.js:58:59)    
[0-0]     at Object.remote (E:\webdriver\webdriverio-selenium-sample-master\node_modules\@wdio\runner\node_modules\webdriverio\build\index.js:67:43)        
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[0-0]     at Runner._startSession (E:\webdriver\webdriverio-selenium-sample-master\node_modules\@wdio\runner\build\index.js:216:56)
[0-0]     at Runner._initSession (E:\webdriver\webdriverio-selenium-sample-master\node_modules\@wdio\runner\build\index.js:172:25)
[0-0]     at Runner.run (E:\webdriver\webdriverio-selenium-sample-master\node_modules\@wdio\runner\build\index.js:87:19)
[0-0] FAILED in chrome - E:\webdriver\webdriverio-selenium-sample-master\tests\specs\single_test.js
2021-06-03T16:17:17.998Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:01

2021-06-03T16:17:18.001Z INFO @wdio/local-runner: Shutting down spawned worker
2021-06-03T16:17:18.254Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-06-03T16:17:18.255Z INFO @wdio/local-runner: shutting down`

### **Another Catch if I use always match object with the capabilities in my configuration than it works fine.  
Capabilities with alwaysMatch:-**

` capabilities: [

    {
      alwaysMatch:{
      platformName: "Windows 10",
      browserName: "chrome",
      browserVersion: "90.0",
      name: 'Test1',
      build: 'parallelwdio',

      "goog:chromeOptions": {
        // Install upon starting browser in order to launch it
        extensions: [
          // Entry should be a base64-encoded packed Chrome app (.crx)
          require('fs').readFileSync('crx file path').toString('base64')
        ]
      }
    }
  }
  ],` 

### **Here is the output of it**

`2021-06-03T16:24:22.960Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-06-03T16:24:22.963Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-06-03T16:24:22.969Z INFO @wdio/local-runner: Start worker 0-0 with arg: conf/single.conf.js
[0-0] 2021-06-03T16:24:23.866Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in undefined - E:\webdriver\webdriverio-selenium-sample-master\tests\specs\single_test.js
[0-0] 2021-06-03T16:24:24.441Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-06-03T16:24:24.465Z INFO webdriver: [POST] http://hub.lambdatest.com/wd/hub/session
[0-0] 2021-06-03T16:24:24.465Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       platformName: 'Windows 10',
[0-0]       browserName: 'chrome',
[0-0]       browserVersion: '90.0',
[0-0]       name: 'Test1',
[0-0]       build: 'parallelwdio',
[0-0]       'goog:chromeOptions': [Object]
[0-0]     }
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     platformName: 'Windows 10',
[0-0]     browserName: 'chrome',
[0-0]     browserVersion: '90.0',
[0-0]     name: 'Test1',
[0-0]     build: 'parallelwdio',
[0-0]     'goog:chromeOptions': { extensions: [Array] }
[0-0]   }
[0-0] }`

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.5.7
 - **Mode:** WDIO Testrunner]
 -
 - **Node.js version:** v14.16.0
 - **NPM version:** 6.14.11
 - **Browser name and version:** Chrome
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
An example of how you configured WebdriverIO config
`exports.config = {
  services: [
    [
      "lambdatest",
      {
        tunnel: false,
        lambdatestOpts: {
          logFile: "tunnel.log"
        }
      }
    ]
  ],
  user: process.env.LT_USERNAME,
  key: process.env.LT_ACCESS_KEY,
  specs: ["./tests/specs/single_test.js"],
  exclude: [],
  capabilities: [

    {
      alwaysMatch:{
      platformName: "Windows 10",
      browserName: "chrome",
      browserVersion: "90.0",
      name: 'Test1',
      build: 'parallelwdio',

      "goog:chromeOptions": {
        // Install upon starting browser in order to launch it
        extensions: [
          // Entry should be a base64-encoded packed Chrome app (.crx)
          require('fs').readFileSync('path of crx file').toString('base64')
        ]
      }
    }
  }
  ],
 logLevel: "info",
  coloredLogs: true,
  screenshotPath: "./errorShots/",
  baseUrl: "",
  waitforTimeout: 100000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 1,
  path: "/wd/hub",
  hostname: "hub.lambdatest.com",
  port: 80,
  framework: "mocha",
  mochaOpts: {
    ui: "bdd"
  }
};
`

**Describe the bug**
The error message come across after adding google chrome option capabilities in my configuration file. 
I am currently using wdio/cli version @wdio/cli --> "version": "7.5.7",
If I downgrade the @wdio/cli v.6xx it works perfectly fine. 

**To Reproduce**
Mentioned Above 

**Expected behavior**
All Custom capabilities should work without adding alwaysMatch object

**Comment by christian-bromann** [comment]
Your capabilities contain the following attributes:

```
  name: 'Test1',
  build: 'parallelwdio',
```

these aren't valid W3C caps and WebdriverIO in v7 now strictly asserts this. Please check if your vendor provides vendor capabilities extensions, e.g.:

```
'lambda:opts': {
  name: 'Test1',
  build: 'parallelwdio'
}
```

Happy to answer follow up question you might have.
