### ISSUE TITLE
wdio-junit-reporter - extra <failure/> tag breaks CircleCI from error message reporting

### ISSUE THREAD

**Issue by unickq** [webdriverio/webdriverio#7053]
# After upgrading from wdio6 to wdio7 found that CircleCI stopped displayed error messages.

The test:
```js
describe("A", () => {
  it("B", () => {
    expect("A").toBe("B");
  });
});
```

## wdio6 xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="A" timestamp="2021-06-24T16:15:46" time="0.231" tests="1" failures="0" errors="1" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="suiteName" value="A"/>
      <property name="capabilities" value="chrome.91_0_4472_114.windows"/>
      <property name="file" value=".\x.spec.ts"/>
    </properties>
    <testcase classname="chrome.91_0_4472_114.windows.A" name="B" time="0.231" file="wdio6">
      <error message="[2mexpect([22m[31mreceived[39m[2m).[22mtoBe[2m([22m[32mexpected[39m[2m) // Object.is equality[22m&#xA;&#xA;Expected: [32m&quot;B&quot;[39m&#xA;Received: [31m&quot;A&quot;[39m"/>
      <system-out>
       ...
      </system-out>
      <system-err>
        <![CDATA[
Error: [2mexpect([22m[31mreceived[39m[2m).[22mtoBe[2m([22m[32mexpected[39m[2m) // Object.is equality[22m

Expected: [32m"B"[39m
Received: [31m"A"[39m
    at Context.<anonymous> (C:\Git\integration-tests\x.spec.ts:3:17)
    at Context.executeSync (C:\Git\integration-tests\node_modules\@wdio\sync\build\index.js:25:22)
    at C:\Git\integration-tests\node_modules\@wdio\sync\build\index.js:46:68
]]>
      </system-err>
    </testcase>
  </testsuite>
</testsuites>
```

## wdio7 xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="A" timestamp="2021-06-24T16:16:57" time="0.217" tests="1" failures="1" errors="1" skipped="0">
    <properties>
      <property name="specId" value="0"/>
      <property name="suiteName" value="A"/>
      <property name="capabilities" value="chrome.91_0_4472_114.windows"/>
      <property name="file" value=".\x.spec.ts"/>
    </properties>
    <testcase classname="wdio7" name="B" time="0.216" file="wdio7">
      <failure/>
      <error message="[2mexpect([22m[31mreceived[39m[2m).[22mtoBe[2m([22m[32mexpected[39m[2m) // Object.is equality[22m&#xA;&#xA;Expected: [32m&quot;B&quot;[39m&#xA;Received: [31m&quot;A&quot;[39m"/>
      <system-out>
       ...
      </system-out>
      <system-err><![CDATA[
Error: [2mexpect([22m[31mreceived[39m[2m).[22mtoBe[2m([22m[32mexpected[39m[2m) // Object.is equality[22m

Expected: [32m"B"[39m
Received: [31m"A"[39m
    at Context.<anonymous> (C:\Git\integration-tests\x.spec.ts:3:17)
    at Context.executeSync (C:\Git\integration-tests\node_modules\@wdio\sync\build\index.js:38:22)
    at C:\Git\integration-tests\node_modules\@wdio\sync\build\index.js:69:68
]]></system-err>
    </testcase>
  </testsuite>
</testsuites>
```

# The only one difference is <failure/> tag in wdio7

## with <failure/> tag
![image](https://user-images.githubusercontent.com/6696821/123273229-22322400-d50b-11eb-98ba-088497376e1c.png)

## without <failure/> tag
![image](https://user-images.githubusercontent.com/6696821/123273295-35dd8a80-d50b-11eb-91ad-878a9019dd0b.png)

**Comment by unickq** [comment]
Never mind, looks like it's related to the new https://webdriver.io/docs/junit-reporter/#erroroptions

```json
        errorOptions: {
          error: "message",
          failure: "message",
          stacktrace: "stack",
        },
```

**Comment by unickq** [comment]
Just one question @christian-bromann 
what are these `[22m [22m [31m` etc?

**Comment by BorisOsipov** [comment]
@unickq ascii color characters. it is from `expect` lib

**Comment by unickq** [comment]
@BorisOsipov 
is there a way to disable it?

**Comment by BorisOsipov** [comment]
@unickq I guess, no. Only by PR like this https://github.com/webdriverio/webdriverio/pull/6662/files
