### ISSUE TITLE
Cannot start chromedriver service with appium service

### ISSUE THREAD

**Issue by praveendvd** [webdriverio/webdriverio#7055]
**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 4.13.2]  : 7.4.6
 - **Mode:** [Standalone mode or WDIO Testrunner] test runner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] async
 - **Node.js version:** [e.g. 8.11.2] : 16.3.0
 - **NPM version:** [e.g. 5.8.0] 6.14.10
 - **Browser name and version:** [e.g. Chrome 68] :Chrome 91
 - **Platform name and version:** [e.g. Windows 10]: win10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service] : appium and chrome service

**Describe the bug**
gets below error when i add two services:

```
2021-06-24T10:47:02.936Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
TypeError: Cannot read property 'toLowerCase' of undefined
    at isChrome (D:\MyProjects\Appium\appium_WebDriverIO_Jasmine\appium_WebDriverIO_Jasmine\node_modules\wdio-chromedriver-service\build\launcher.js:37:41)
    at ChromeDriverLauncher._mapCapabilities (D:\MyProjects\Appium\appium_WebDriverIO_Jasmine\appium_WebDriverIO_Jasmine\node_modules\wdio-chromedriver-service\build\launcher.js:118:13)
    at ChromeDriverLauncher.onPrepare (D:\MyProjects\Appium\appium_WebDriverIO_Jasmine\appium_WebDriverIO_Jasmine\node_modules\wdio-chromedriver-service\build\launcher.js:70:10)
    at D:\MyProjects\Appium\appium_WebDriverIO_Jasmine\appium_WebDriverIO_Jasmine\node_modules\@wdio\cli\build\utils.js:28:40
    at Array.map (<anonymous>)
    at Object.runServiceHook (D:\MyProjects\Appium\appium_WebDriverIO_Jasmine\appium_WebDriverIO_Jasmine\node_modules\@wdio\cli\build\utils.js:25:33)
    at Launcher.run (D:\MyProjects\Appium\appium_WebDriverIO_Jasmine\appium_WebDriverIO_Jasmine\node_modules\@wdio\cli\build\launcher.js:86:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**

1. have capability like

```
capabilities: {

        a: {
            "host": "localhost",
            "port": 9515,
            "path": "/",
            capabilities: {
                browserName: 'chrome'
            }
        },
        b: {
            "host": "localhost",
            "port": 4723,
            "path": "/wd/hub",
            capabilities: {
                "platformName": "android",
                "appium:platformVersion": "11",
                "appium:deviceName": "Android Emulator",
                "appium:app": "C:\\Users\\prave\\Downloads\\ApiDemos-debug.apk",
                "appium:automationName": "uiautomator2",
                "appium:avd": "2"
            }
        }
    }
```

2. Add service like:

```
 services: [["chromedriver", {
        port: 9515,
        hostname: "localhost",
        automationProtocol:"webdriver"
    }], ["appium", { port: 4723, hostname: "localhost" , path:"/wd/hub"}]],
```

**Reproducible example:**

[example.zip](https://github.com/webdriverio/webdriverio/files/6711247/example.zip)

**Expected behavior**:

service should start correctly

**Comment by praveendvd** [comment]
@christian-bromann  I have created a pull request for fixing this issue , here i am just validating whether the browsername is present or not

**Comment by christian-bromann** [comment]
Thanks for picking it up, let's continue convo in the PR.
