### ISSUE TITLE
In case element is not found in the middle of the chain, stack trace doesn't show the line of tests code

### ISSUE THREAD

**Issue by bad-white-cat** [webdriverio/webdriverio#7060]
**Environment (please complete the following information):**
 - **WebdriverIO version:**  7.7.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 14.17.1
 - **NPM version:** 6.14.13
 - **Browser name and version:** Chrome 91
 - **Platform name and version:** Windows 10

**Config of WebdriverIO**
```
export const config = {
    runner: 'local',
    specs: [
        './test/specs/**/*.ts'
    ],
    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true
    }],
    logLevel: 'info',
    bail: 0,
    baseUrl: 'https://webdriver.io/',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    }
    }
}
```

**Describe the bug**
In case element is not found in the middle of the chain, stack trace doesn't show the line of tests code.

**To Reproduce**
```
describe('sample spec', () => {
    it('should be logo', async () => {
        browser.url('https://webdriver.io/')
        const content = $('div.main-wrapper222') //there is a mistake in the selector.
        const logo = (await content).$('h1.hero__title')
        await expect(logo).toBeDisplayed()
    });
});
```
Stack trace doesn't show the line of my code wich call lead to error.
```
[chrome 91.0.4472.124 windows #0-0] 1) sample spec should be logo
[chrome 91.0.4472.124 windows #0-0] Can't call $ on element with selector "div.main-wrapper222" because element wasn't found
[chrome 91.0.4472.124 windows #0-0] Error: Can't call $ on element with selector "div.main-wrapper222" because element wasn't found
[chrome 91.0.4472.124 windows #0-0]     at Object.implicitWait [as default] (C:\Projects\sandbox-wdio\node_modules\webdriverio\build\utils\implicitWait.js:34:19)      
[chrome 91.0.4472.124 windows #0-0]     at Element.elementErrorHandlerCallbackFn (C:\Projects\sandbox-wdio\node_modules\webdriverio\build\middlewares.js:19:29)        
[chrome 91.0.4472.124 windows #0-0]     at Element.wrapCommandFn (C:\Projects\sandbox-wdio\node_modules\@wdio\utils\build\shim.js:78:29)
[chrome 91.0.4472.124 windows #0-0]     at Object.executeCommandBe (C:\Projects\sandbox-wdio\node_modules\expect-webdriverio\lib\utils.js:47:16)
[chrome 91.0.4472.124 windows #0-0]     at C:\Projects\sandbox-wdio\node_modules\expect-webdriverio\lib\matchers\element\toBeDisplayed.js:9:24
[chrome 91.0.4472.124 windows #0-0]     at Browser.wrapCommandFn (C:\Projects\sandbox-wdio\node_modules\@wdio\utils\build\shim.js:78:29)
```

**Expected behavior**
Like this: 
```
[chrome 91.0.4472.124 windows #0-0] Error: Expect $(`div.main-wrapper222`) to be displayed
[chrome 91.0.4472.124 windows #0-0]
[chrome 91.0.4472.124 windows #0-0] Expected: "displayed"
[chrome 91.0.4472.124 windows #0-0] Received: "not displayed"
[chrome 91.0.4472.124 windows #0-0]     at C:\Projects\sandbox-wdio\test\specs\example.e2e.ts:6:31 //link to the tests code
[chrome 91.0.4472.124 windows #0-0]     at Generator.next (<anonymous>)
[chrome 91.0.4472.124 windows #0-0]     at fulfilled (C:\Projects\sandbox-wdio\test\specs\example.e2e.ts:4:58)
[chrome 91.0.4472.124 windows #0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Thank you very much for any help.

**Comment by praveendvd** [comment]
```
describe('sample spec', () => {
    it('should be logo', async () => {
        browser.url('https://webdriver.io/')
        const content = await $('div.main-wrapper222') //there is a mistake in the selector.
        const logo = (content).$('h1.hero__title')
        await expect(logo).toBeDisplayed()
    });
});
```

**Comment by olga-potapova** [comment]
I'd like just to clarify, I know that there is some workaround to avoid this issue, like write
```
const content = await $('div.main-wrapper222') 
const logo = content.$('h1.hero__title')
```
but in some cases it's important to have `content` as Promise<WebdriverIO.Element>, not as WebdriverIO.Element.

**Comment by christian-bromann** [comment]
This works now with our improved async API. Update the test to this:
```js
describe('webdriver.io page', () => {
    it('should have the right title', async () => {
        browser.url('https://webdriver.io/')
        await expect($('div.main-wrapper22').$('h1.hero__title')).toBeDisplayed()
    })
})
```
and the stack trace will lead to the origin:
```
 "spec" Reporter:
------------------------------------------------------------------
[Chrome 95.0.4634.3 darwin #0-0] Running: Chrome (v95.0.4634.3) on darwin
[Chrome 95.0.4634.3 darwin #0-0] Session ID: d8ad5e3d-7e37-409b-ad93-b4d315e181bb
[Chrome 95.0.4634.3 darwin #0-0]
[Chrome 95.0.4634.3 darwin #0-0] » /mocha/mocha.test.js
[Chrome 95.0.4634.3 darwin #0-0] webdriver.io page
[Chrome 95.0.4634.3 darwin #0-0]    - should be a pending test
[Chrome 95.0.4634.3 darwin #0-0]    ✖ should have the right title
[Chrome 95.0.4634.3 darwin #0-0]
[Chrome 95.0.4634.3 darwin #0-0] 1 failing (7s)
[Chrome 95.0.4634.3 darwin #0-0] 1 skipped
[Chrome 95.0.4634.3 darwin #0-0]
[Chrome 95.0.4634.3 darwin #0-0] 1) webdriver.io page should have the right title
[Chrome 95.0.4634.3 darwin #0-0] Can't call findElement on element with selector "div.main-wrapper22" because element wasn't found
[Chrome 95.0.4634.3 darwin #0-0] Error: Can't call findElement on element with selector "div.main-wrapper22" because element wasn't found
[Chrome 95.0.4634.3 darwin #0-0]     at Object.implicitWait [as default] (/Users/christianbromann/Sites/WebdriverIO/webdriverio/packages/webdriverio/src/utils/implicitWait.ts:39:19)
[Chrome 95.0.4634.3 darwin #0-0]     at async Element.elementErrorHandlerCallbackFn (/Users/christianbromann/Sites/WebdriverIO/webdriverio/packages/webdriverio/src/middlewares.ts:15:29)
[Chrome 95.0.4634.3 darwin #0-0]     at async Element.wrapCommandFn (/Users/christianbromann/Sites/WebdriverIO/webdriverio/packages/wdio-utils/src/shim.ts:132:29)
[Chrome 95.0.4634.3 darwin #0-0]     at async Element.$ (/Users/christianbromann/Sites/WebdriverIO/webdriverio/packages/webdriverio/src/commands/browser/$.ts:92:17)
[Chrome 95.0.4634.3 darwin #0-0]     at async Element.wrapCommandFn (/Users/christianbromann/Sites/WebdriverIO/webdriverio/packages/wdio-utils/src/shim.ts:132:29)
[Chrome 95.0.4634.3 darwin #0-0]     at async Element.wrapCommandFn (/Users/christianbromann/Sites/WebdriverIO/webdriverio/packages/wdio-utils/src/shim.ts:132:29)
[Chrome 95.0.4634.3 darwin #0-0]     at async Object.executeCommandBe (/Users/christianbromann/Sites/WebdriverIO/webdriverio/packages/wdio-mocha-framework/node_modules/expect-webdriverio/lib/utils.js:47:16)
[Chrome 95.0.4634.3 darwin #0-0]     at async /Users/christianbromann/Sites/WebdriverIO/webdriverio/packages/wdio-mocha-framework/node_modules/expect-webdriverio/lib/matchers/element/toBeDisplayed.js:9:24
[Chrome 95.0.4634.3 darwin #0-0]     at async Browser.wrapCommandFn (/Users/christianbromann/Sites/WebdriverIO/webdriverio/packages/wdio-utils/src/shim.ts:132:29)
[Chrome 95.0.4634.3 darwin #0-0]     at async Context.<anonymous> (/Users/christianbromann/Sites/WebdriverIO/webdriverio/examples/wdio/mocha/mocha.test.js:6:9)
```
