### ISSUE TITLE
Setup fails on current main 

### ISSUE THREAD

**Issue by jlipps** [webdriverio/webdriverio#7108]
When I clone a fresh repo and run:

```
npm install
npm run setup-full
```

I get the following error during the `compile` step:

```
> compile
> node ./scripts/build

npx tsc -b packages/wdio-types/tsconfig.json packages/wdio-protocols/tsconfig.json packages/wdio-logger/tsconfig.json packages/wdio-utils/tsconfig.json packages/wdio-config/tsconfig.json packages/wdio-repl/tsconfig.json packages/webdriver/tsconfig.json packages/devtools/tsconfig.json packages/webdriverio/tsconfig.json packages/wdio-cli/tsconfig.json packages/wdio-reporter/tsconfig.json packages/wdio-runner/tsconfig.json packages/wdio-sync/tsconfig.json packages/wdio-allure-reporter/tsconfig.json packages/wdio-appium-service/tsconfig.json packages/wdio-applitools-service/tsconfig.json packages/wdio-browserstack-service/tsconfig.json packages/wdio-concise-reporter/tsconfig.json packages/wdio-crossbrowsertesting-service/tsconfig.json packages/wdio-cucumber-framework/tsconfig.json packages/wdio-devtools-service/tsconfig.json packages/wdio-dot-reporter/tsconfig.json packages/wdio-firefox-profile-service/tsconfig.json packages/wdio-jasmine-framework/tsconfig.json packages/wdio-junit-reporter/tsconfig.json packages/wdio-local-runner/tsconfig.json packages/wdio-mocha-framework/tsconfig.json packages/wdio-sauce-service/tsconfig.json packages/wdio-selenium-standalone-service/tsconfig.json packages/wdio-shared-store-service/tsconfig.json packages/wdio-smoke-test-reporter/tsconfig.json packages/wdio-smoke-test-service/tsconfig.json packages/wdio-spec-reporter/tsconfig.json packages/wdio-static-server-service/tsconfig.json packages/wdio-sumologic-reporter/tsconfig.json packages/wdio-testingbot-service/tsconfig.json packages/wdio-webdriver-mock-service/tsconfig.json
packages/wdio-cli/src/commands/repl.ts(70,12): error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.
packages/wdio-cli/src/commands/repl.ts(71,12): error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.
packages/wdio-cli/src/commands/repl.ts(72,12): error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.
packages/wdio-browserstack-service/src/launcher.ts(65,48): error TS2345: Argument of type '{ entryTypes: "measure"[]; buffered: boolean; }' is not assignable to parameter of type '{ entryTypes: readonly EntryType[]; } | { type: EntryType; }'.
  Object literal may only specify known properties, and 'buffered' does not exist in type '{ entryTypes: readonly EntryType[]; } | { type: EntryType; }'.
packages/wdio-crossbrowsertesting-service/src/launcher.ts(40,48): error TS2345: Argument of type '{ entryTypes: "measure"[]; buffered: boolean; }' is not assignable to parameter of type '{ entryTypes: readonly EntryType[]; } | { type: EntryType; }'.
  Object literal may only specify known properties, and 'buffered' does not exist in type '{ entryTypes: readonly EntryType[]; } | { type: EntryType; }'.
packages/wdio-sauce-service/src/launcher.ts(87,48): error TS2345: Argument of type '{ entryTypes: "measure"[]; buffered: boolean; }' is not assignable to parameter of type '{ entryTypes: readonly EntryType[]; } | { type: EntryType; }'.
  Object literal may only specify known properties, and 'buffered' does not exist in type '{ entryTypes: readonly EntryType[]; } | { type: EntryType; }'.
packages/wdio-testingbot-service/src/launcher.ts(52,48): error TS2345: Argument of type '{ entryTypes: "measure"[]; buffered: boolean; }' is not assignable to parameter of type '{ entryTypes: readonly EntryType[]; } | { type: EntryType; }'.
  Object literal may only specify known properties, and 'buffered' does not exist in type '{ entryTypes: readonly EntryType[]; } | { type: EntryType; }'.
/Users/jlipps/Code/libs/wdio2/scripts/build.js:71
    throw new Error('Failed compiling TypeScript files!')
    ^

Error: Failed compiling TypeScript files!
    at Object.<anonymous> (/Users/jlipps/Code/libs/wdio2/scripts/build.js:71:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
ERROR: "compile" exited with 1.
ERROR: "build" exited with 1.
```

**Comment by BorisOsipov** [comment]
I ran into the same problem on CI. Issue appears because we have v15 and v16 @types/node in node_modules for some packages. 

The main issue for me that in fact subpackages have its own `package.json` but don't have `package-lock.json` - so we don't have reproducable builds.

**Comment by praveendvd** [comment]
> I ran into the same problem on CI. Issue appears because we have v15 and v16 @types/node in node_modules for some packages.
> 
> The main issue for me that in fact subpackages have its own `package.json` but don't have `package-lock.json` - so we don't have reproducable builds.

same with me cannot run setup-full
