### ISSUE TITLE
How to handle file upload? Is there any alternative ways except browser.uploadFile?

### ISSUE THREAD

**Issue by Askarov5** [webdriverio/webdriverio#7127]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.11.3
 - **Mode:** WDIO Testrunner 6.12.1
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.16.0
 - **NPM version:** 7.7.5
 - **Browser name and version:** Chrome 91.0.4472.114
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @rpii/wdio-html-reporter, chromedriver, wdio-json-reporter

**Config of WebdriverIO**
capabilities: [{maxInstances: 1, browserName: "chrome"}],
services: ["chromedriver"],  

**Describe the bug**
I'm trying to upload a file(as shown in docs) by using browser.upload and getting the following error:
Error: The uploadFile command is not available in Chrome
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Implementation of POM function:
uploadDocuments(){
        let filePath = path.resolve(__dirname, "../data/diagram.jpg");

        this.fileUploadFirstInput.waitForExist();
        let remoteFilePath = browser.uploadFile(filePath);
        console.log("remote Path: " + remoteFilePath);
        this.fileUploadFirstInput.setValue(remoteFilePath);
    }

**To Reproduce**
Try to upload a file
[Include code or an example repository that can easily be set up]

**Expected behavior**
to upload a file, not getting an error message

**Log**
INFO devtools: RESULT iVBORw0KGgoAAAANSUhEUgAAB2wAAARCCAYAAABvtAIbAAABKWlDQ1BTa2lhA...
[0-0] 2021-07-12T14:46:32.812Z DEBUG @wdio/sync: Finished to run "afterTest" hook in 796ms
[0-0] Error in "chrome Update DBA Name:  Step 1: Pre-Zoning - Select SBA"
Error: The uploadFile command is not available in Chrome
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at NblPreZoningPages.uploadDocuments (/Users/orozbekaskarov/Desktop/git/cbd-wd/test/pageobjects/NBL/preZoning.page.js:237:38)
    at Context.<anonymous> (/Users/orozbekaskarov/Desktop/git/cbd-wd/test/specs/nbl.test.js:35:24)
[0-0] 2021-07-12T14:46:32.856Z INFO devtools: COMMAND deleteSession()
[0-0] 2021-07-12T14:46:32.861Z INFO devtools: RESULT null
2021-07-12T14:46:33.254Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - /test/specs/nbl.test.js

**Comment by christian-bromann** [comment]
It seems you don't have Chromedriver set up properly. Please make sure to follow the instruction mentioned in the [docs](https://webdriver.io/docs/wdio-chromedriver-service). Let me know if you have further questions.

**Comment by Askarov5** [comment]
I followed the instructions in docs but still having same the issue. I write down all needed info, can you please take a look?

wdio.conf.js: 
exports.config ={
...
  services: [
      ['chromedriver', {
          logFileName: 'wdio-chromedriver.log', // default
          outputDir: 'driver-logs', // overwrites the config.outputDir
          args: ['--silent']
      }]
  ], 
...
}

package.json :
{
....
"dependencies": {
    "@rpii/wdio-html-reporter": "^7.0.0",
    "@wdio/cli": "^6.12.1",
    "@wdio/spec-reporter": "^6.11.0",
    "babel-plugin-source-map-support": "^2.1.1",
    "source-map-support": "^0.5.19",
    "webdriverio": "^6.11.3",
    "yargs": "^16.2.0"
  },
  "devDependencies": {
    "@rpii/wdio-html-reporter-pdf": "^6.2.3",
    "@wdio/local-runner": "^6.0.3",
    "@wdio/mocha-framework": "^6.10.4",
    "@wdio/sync": "^6.10.4",
    "chromedriver": "^92.0.0",
    "wdio-chromedriver-service": "^6.0.0",
    "wdio-json-reporter": "^0.4.0"
  },
...
}

ERROR Message: 
DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
2021-07-29T22:10:08.358Z 
ERROR @wdio/utils:initialiseServices: Error: Couldn't find plugin "chromedriver" service, neither as wdio scoped package "@wdio/chromedriver-service" nor as community package "wdio-chromedriver-service". Please make sure you have it installed!
    at Object.initialisePlugin [as default] (/usr/local/lib/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialisePlugin.js:41:11)
    at initialiseServices (/usr/local/lib/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialiseServices.js:59:51)
    at Object.initialiseLauncherService (/usr/local/lib/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialiseServices.js:86:26)
    at Launcher.run (/usr/local/lib/node_modules/@wdio/cli/build/launcher.js:81:73)
    at launch (/usr/local/lib/node_modules/@wdio/cli/build/commands/run.js:126:21)
    at Object.handler (/usr/local/lib/node_modules/@wdio/cli/build/commands/run.js:164:16)
    at Object.run (/usr/local/lib/node_modules/@wdio/cli/build/index.js:72:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/@wdio/cli/bin/wdio.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by sravanthi1047** [comment]
Hi, did you get this working. I am also stuck up with similar issue.. not throwing up any error but its not uploading my file. Any help pl..
