### ISSUE TITLE
ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by apinapon** [webdriverio/webdriverio#7138]
**error log**
```
Execution of 8 spec files started at 2021-07-14T06:10:15.225Z

2021-07-14T06:10:15.251Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-07-14T06:10:15.253Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at AppiumLauncher.onPrepare (/home/alvin/SEiT/automation-test/android/node_modules/@wdio/appium-service/build/launcher.js:63:72)
    at Promise.all.launcher.map.service (/home/alvin/SEiT/automation-test/android/node_modules/@wdio/cli/build/utils.js:51:33)
    at Array.map (<anonymous>)
    at runServiceHook (/home/alvin/SEiT/automation-test/android/node_modules/@wdio/cli/build/utils.js:49:39)
    at Launcher.run (/home/alvin/SEiT/automation-test/android/node_modules/@wdio/cli/build/launcher.js:74:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Continue...
2021-07-14T06:10:15.278Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js,--cucumberOpts.tagExpression=@apply-ath
[0-0] 2021-07-14T06:10:15.932Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in com.app.staging - /features/scenarios/apply-cashloan/apply-cashloan.feature
[0-0] 2021-07-14T06:10:16.157Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2021-07-14T06:10:16.159Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
[0-0] 2021-07-14T06:10:16.160Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { platformName: 'Android',
        platformVersion: '8.1',
        deviceName: 'Pixel_XL',
        avd: 'Pixel_XL',
        automationName: 'UiAutomator2',
        appPackage: 'com.app.staging',
        app:
         '/home/alvin/SEiT/automation-test/android/test_apk/507_3.17.3.apk',
        autoGrantPermissions: true },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { platformName: 'Android',
     platformVersion: '8.1',
     deviceName: 'Pixel_XL',
     avd: 'Pixel_XL',
     automationName: 'UiAutomator2',
     appPackage: 'com.app.staging',
     app:
      '/home/alvin/SEiT/automation-test/android/test_apk/507_3.17.3.apk',
     autoGrantPermissions: true } }
[0-0] 2021-07-14T06:10:16.171Z WARN webdriver: Request failed due to connect ECONNREFUSED 127.0.0.1:4723
[0-0] 2021-07-14T06:10:16.171Z INFO webdriver: Retrying 1/1
2021-07-14T06:10:16.172Z INFO webdriver: [POST] http://127.0.0.1:4723/wd/hub/session
[0-0] 2021-07-14T06:10:16.172Z INFO webdriver: DATA { capabilities:
   { alwaysMatch:
      { platformName: 'Android',
        platformVersion: '8.1',
        deviceName: 'Pixel_XL',
        avd: 'Pixel_XL',
        automationName: 'UiAutomator2',
        appPackage: 'com.app.staging',
        app:
         '/home/alvin/SEiT/automation-test/android/test_apk/507_3.17.3.apk',
        autoGrantPermissions: true },
     firstMatch: [ {} ] },
  desiredCapabilities:
   { platformName: 'Android',
     platformVersion: '8.1',
     deviceName: 'Pixel_XL',
     avd: 'Pixel_XL',
     automationName: 'UiAutomator2',
     appPackage: 'com.app.staging',
     app:
      '/home/alvin/SEiT/automation-test/android/test_apk/507_3.17.3.apk',
     autoGrantPermissions: true } }
[0-0] 2021-07-14T06:10:16.174Z ERROR webdriver: Request failed due to Error: connect ECONNREFUSED 127.0.0.1:4723
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
[0-0] 2021-07-14T06:10:16.174Z ERROR webdriver: Error: connect ECONNREFUSED 127.0.0.1:4723
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
[0-0] 2021-07-14T06:10:16.174Z ERROR @wdio/runner: Error: Failed to create session.
Unable to connect to "127.0.0.1:4723", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file.
    at startWebDriverSession (/home/alvin/SEiT/automation-test/android/node_modules/@wdio/runner/node_modules/webdriver/build/utils.js:45:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[0-0] Error: Failed to create session.
Unable to connect to "127.0.0.1:4723", make sure browser driver is running on that address.
If you use services like chromedriver see initialiseServices logs above or in wdio.log file.
[0-0] FAILED in com.app.staging - /features/scenarios/apply-cashloan/apply-cashloan.feature
2021-07-14T06:10:16.292Z INFO @wdio/local-runner: Start worker 0-1 with arg: wdio.conf.js,--cucumberOpts.tagExpression=@apply-ath
[0-1] 2021-07-14T06:10:16.957Z INFO @wdio/local-runner: Run worker command: run
2021-07-14T06:10:17.288Z INFO @wdio/cli: [0-1] SKIPPED in com.app.staging - /features/scenarios/apply-cli/apply-cli.feature
2021-07-14T06:10:17.290Z INFO @wdio/local-runner: Start worker 0-2 with arg: wdio.conf.js,--cucumberOpts.tagExpression=@apply-ath
[0-2] 2021-07-14T06:10:18.042Z INFO @wdio/local-runner: Run worker command: run
2021-07-14T06:10:18.437Z INFO @wdio/cli: [0-2] SKIPPED in com.app.staging - /features/scenarios/apply-ins/apply-ins.feature
2021-07-14T06:10:18.439Z INFO @wdio/local-runner: Start worker 0-3 with arg: wdio.conf.js,--cucumberOpts.tagExpression=@apply-ath
[0-3] 2021-07-14T06:10:19.224Z INFO @wdio/local-runner: Run worker command: run
2021-07-14T06:10:19.556Z INFO @wdio/cli: [0-3] SKIPPED in com.app.staging - /features/scenarios/cleanup/clean-application.feature
2021-07-14T06:10:19.559Z INFO @wdio/local-runner: Start worker 0-4 with arg: wdio.conf.js,--cucumberOpts.tagExpression=@apply-ath
[0-4] 2021-07-14T06:10:20.262Z INFO @wdio/local-runner: Run worker command: run
2021-07-14T06:10:20.598Z INFO @wdio/cli: [0-4] SKIPPED in com.app.staging - /features/scenarios/home-page/home-page.feature
2021-07-14T06:10:20.603Z INFO @wdio/local-runner: Start worker 0-5 with arg: wdio.conf.js,--cucumberOpts.tagExpression=@apply-ath
[0-5] 2021-07-14T06:10:21.306Z INFO @wdio/local-runner: Run worker command: run
2021-07-14T06:10:21.660Z INFO @wdio/cli: [0-5] SKIPPED in com.app.staging - /features/scenarios/login/apptest.feature
2021-07-14T06:10:21.663Z INFO @wdio/local-runner: Start worker 0-6 with arg: wdio.conf.js,--cucumberOpts.tagExpression=@apply-ath
[0-6] 2021-07-14T06:10:22.484Z INFO @wdio/local-runner: Run worker command: run
2021-07-14T06:10:22.843Z INFO @wdio/cli: [0-6] SKIPPED in com.app.staging - /features/scenarios/login/login.feature
2021-07-14T06:10:22.847Z INFO @wdio/local-runner: Start worker 0-7 with arg: wdio.conf.js,--cucumberOpts.tagExpression=@apply-ath
[0-7] 2021-07-14T06:10:23.551Z INFO @wdio/local-runner: Run worker command: run
2021-07-14T06:10:23.898Z INFO @wdio/cli: [0-7] SKIPPED in com.app.staging - /features/scenarios/resume-application/resume-application.feature
2021-07-14T06:10:23.899Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:	 0 passed, 1 failed, 7 skipped, 8 total (100% completed) in 00:00:08 

2021-07-14T06:10:23.900Z INFO @wdio/local-runner: Shutting down spawned worker
2021-07-14T06:10:24.152Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-07-14T06:10:24.153Z INFO @wdio/local-runner: shutting down
npm ERR! Test failed.  See above for more details.
```

**capabilities**
```
platformName: 'Android',
        platformVersion: '8.1',
        deviceName: 'Pixel_XL',
        avd: 'Pixel_XL',
        automationName: 'UiAutomator2',
        appPackage: 'com.app.staging',
        app:
         '/home/alvin/SEiT/automation-test/android/test_apk/507_3.17.3.apk',
        autoGrantPermissions: true },
```

**package.json**
```
{
  "name": "android-automation-test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "wdio wdio.conf.js",
    "cucumber": "./node_modules/.bin/cucumber-js --require features/helpers/api/login"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/android-automation-test.git"
  },
  "keywords": [],
  "author": "SEIT",
  "license": "ISC",
  "devDependencies": {
    "@rpii/wdio-html-reporter": "^0.8.3",
    "@wdio/allure-reporter": "^5.16.16",
    "@wdio/appium-service": "^5.16.11",
    "@wdio/cli": "^5.18.1",
    "@wdio/cucumber-framework": "^5.16.15",
    "@wdio/local-runner": "^5.18.0",
    "@wdio/mocha-framework": "^5.16.15",
    "@wdio/selenium-standalone-service": "^5.16.10",
    "@wdio/spec-reporter": "^5.16.11",
    "@wdio/sync": "^5.17.0",
    "appium": "^1.16.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babelify": "^10.0.0",
    "browserify": "^16.5.1",
    "chai": "^4.2.0",
    "chromedriver": "^78.0.1",
    "cucumber": "^6.0.5",
    "eslint": "^6.8.0",
    "gradle": "^1.0.9",
    "wdio-chromedriver-service": "^5.0.2",
    "wdio-cucumber-reporter": "0.0.2"
  },
  "dependencies": {
    "@babel/core": "^7.10.4",
    "accounting": "^0.4.1",
    "allure": "0.0.0",
    "allure-commandline": "^2.13.0",
    "app-module-path": "^2.2.0",
    "appium-doctor": "^1.12.1",
    "appium-uiautomator2-driver": "^1.42.0",
    "bluebird": "^3.7.2",
    "dotenv": "^8.2.0",
    "io.appium.settings": "^2.16.2",
    "lodash": "^4.17.15",
    "superagent": "^5.1.3",
    "wd": "^1.11.4"
  },
  "description": "Automation test for Android apps",
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "@babel/preset-env"
          ]
        }
      ]
    ]
  }
}
```

**Comment by apinapon** [comment]
I never change anything, suddenly I got this error, it's work before, is there any clue about this?

**Comment by christian-bromann** [comment]
@apinapon thanks for posting the issue. It seems you are using a deprecated version of WebdriverIO. We recommend to upgrade to v7. It is impossible to give any clue given that I don't know what has changed in your environment.
