### ISSUE TITLE
Doesn't Work With Mocha TDD

### ISSUE THREAD

**Issue by saulshanabrook** [webdriverio/webdriverio#714]
When I try to set Mocha to use the TDD user interface with:

```
  mochaOpts: {
    ui: 'tdd'
  },
```

It gives me this error:

```
=======================================================================================
Selenium 2.0/webdriver protocol bindings implementation with helper commands in nodejs.
For a complete list of commands, visit http://webdriver.io/docs.html.
=======================================================================================

[17:31:36]:  COMMAND	POST 	 "/wd/hub/session"
[17:31:36]:  DATA		 {"desiredCapabilities":{"browserName":"chrome","version":"","javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"platform":"ANY","loggingPrefs":{"driver":"INFO","browser":"INFO"},"requestOrigins":{"url":"http://webdriver.io","version":"3.1.0","name":"webdriverio"}}}
[17:31:43]:  SET SESSION ID aa29cfc9-eed1-47ae-9279-1434a25a5ea0
[17:31:43]:  RESULT		 {"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"chrome":{"userDataDir":"/var/folders/g3/g4pj353x25q1bgj53wd2ghbw0000gn/T/.org.chromium.Chromium.F2dOQD"},"takesHeapSnapshot":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"version":"44.0.2403.155","platform":"MAC","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":true,"webdriver.remote.sessionid":"aa29cfc9-eed1-47ae-9279-1434a25a5ea0","locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true}
ERROR: Cannot read property 'skip' of undefined
browserName: "chrome"
Type    at runInGenerator (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/node_modules/webdriverio/lib/frameworks/mocha.js:132:37)
    at Array.forEach (native)
    at Suite.<anonymous> (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/node_modules/webdriverio/lib/frameworks/mocha.js:30:66)
    at Suite.emit (events.js:129:20)
    at /Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/node_modules/mocha/lib/mocha.js:191:11
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/node_modules/mocha/lib/mocha.js:422:31)
    at /Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/node_modules/webdriverio/lib/frameworks/mocha.js:48:28
    at _fulfilled (/Users/saul/projects/go/src/github.com/lucibus/lucibus/caido/node_modules/webdriverio/node_modules/q/q.js:820:54)

```

When I change to `bdd` it works fine. I tried this with a blank test file and both styles of mocha test files. All things I tried worked with `bdd` but gave that error for `tdd`.

**Comment by christian-bromann** [comment]
Fixed. You can now choose between BDD (default) and TDD. I am not sure if it is worth to implement all the other interfaces too. Open for PRs though :wink:

**Comment by saulshanabrook** [comment]
@christian-bromann You are wonderful :)
