### ISSUE TITLE
Cannot use Rule keyword in Cucumber tests

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#7140]
webdriverIO v7 uses a recent cucumberJS version which is capable of processing Gherkin with the Rule keyword and yet tests cannot start when a feature file utilizes it.

I believe Rule was previously supported and working but #6453 might have regressed.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7
 - **Mode:** any
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14
 - **NPM version:** 7

**Config of WebdriverIO**
any

**Describe the bug**
If using the cucumber framework and a feature file has the Rule keyword, the tests fail to start with an error.

**To Reproduce**
Add a Rule Keyword to a feature file and run it
```gherkin
@tag
Feature: Feature

  Background: Background
    Given I do stuff

  Rule: Only something

    Scenario: Doing something
      Given I do even more stuff
```

**Expected behavior**
Tests should start, spec reporter should should group the tests, integration with other reporters should work as normal

**Log**
`addKeywordToStep` [here](https://github.com/webdriverio/webdriverio/blob/2e16e00ff446ec1b0d57f46c782fc6b2538beb34/packages/wdio-cucumber-framework/src/utils.ts#L192) crashes when the gherkin document has `Rule`s.

```js
ERROR @wdio/runner: TypeError: Cannot read property 'find' of undefined
    at /Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/@wdio/cucumber-framework/build/utils.js:177:48
    at Array.find (<anonymous>)
    at /Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/@wdio/cucumber-framework/build/utils.js:175:30
    at Array.map (<anonymous>)
    at Object.addKeywordToStep (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/@wdio/cucumber-framework/build/utils.js:167:18)
    at CucumberEventListener.onTestCaseStarted (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/@wdio/cucumber-framework/build/cucumberEventListener.js:281:38)
    at EventEmitter.<anonymous> (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/@wdio/cucumber-framework/build/cucumberEventListener.js:39:22)
    at EventEmitter.emit (events.js:326:22)
    at EventEmitter.emit (domain.js:486:12)
    at PickleRunner.run (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/@wdio/cucumber-framework/node_modules/@cucumber/cucumber/src/runtime/pickle_runner.ts:303:29)
    at Runtime.runPickle (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/@wdio/cucumber-framework/node_modules/@cucumber/cucumber/src/runtime/index.ts:118:39)
    at tryCatcher (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/Users/[REDACTED]/repos/[REDACTED]/[REDACTED]/node_modules/bluebird/js/release/async.js:15:14)

```
**Additional context**

**Comment by christian-bromann** [comment]
Seems like a bug yes, any contribution are appreciated.

**Comment by praveendvd** [comment]
> Seems like a bug yes, any contribution are appreciated.

@christian-bromann , the below line fixes the issue , but reporters doesn't have any mention about rule, i am not sure if rule should be aded in reporter if so how it should look like 

node_modules\@wdio\cucumber-framework\build\utils.js


```
function addKeywordToStep(steps, feature) {
    return steps.map(step => {
        // Steps without a astNodeIds are hooks
        if (step.astNodeIds && step.astNodeIds.length > 0 && feature.children) {
            // Points to the AST node locations of the pickle. The last one represents the unique id of the pickle.
            // A pickle constructed from Examples will have the first id originating from the Scenario AST node, and
            // the second from the TableRow AST node.
            // See https://github.com/cucumber/cucumber/blob/master/messages/messages.md
            const astNodeId = step.astNodeIds[0];
            const rules  = feature.children.filter((child)=> Object.keys(child)[0]=== "rule")
            feature.children.scenario ? feature.children.scenario.concat((rules.map((child)=>child.rule.children)).flat()) :
            feature.children = (rules.map((child)=>child.rule.children)).flat()
            feature.children.find((child) => 
            // @ts-ignore
            child[Object.keys(child)[0]].steps.find((featureScenarioStep) => {
                if (featureScenarioStep.id === astNodeId.toString()) {
                    step.keyword = featureScenarioStep.keyword;
                }
                return;
            }));
            return step;
        }
        return step;
    });
}

```

**Comment by praveendvd** [comment]
@nextlevelbeard  This is partially fixed now you can use rule keyword,  

ToDo: will need to propagate rule title to reporters

**Comment by praveendvd** [comment]
@christian-bromann  Is there any hooks to check for rule start adn end , i couldn't find any

**Comment by christian-bromann** [comment]
@praveendvd not sure, maybe there are some information in the Cucumber docs.

**Comment by christian-bromann** [comment]
@nextlevelbeard this doesn't seem reproducible to me anymore, therefor closing. Can you verify this? Happy to re-open.

**Comment by praveendvd** [comment]
> @nextlevelbeard this doesn't seem reproducible to me anymore, therefor closing. Can you verify this? Happy to re-open.

The implementation handles rule keyword , but haven't propagated to reporters . We can handle it in a different ticket

**Comment by christian-bromann** [comment]
I definitely didn't see the error happening provided in the stack trace above. You are right that the reporter didn't pick this up. That should be tackled in a different effort.

@praveendvd I suggest to start with the spec reporter, mind creating an issue for it?

**Comment by praveendvd** [comment]
Sure christian , I fixed the former . But for the reporter I will raise a new issue and will look into it really busy months 👏
