### ISSUE TITLE
Tests on browserstack doesn't support `waitForDisplayed` and `scrollIntoView` API ERROR

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [webdriverio/webdriverio#7145]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.7.6
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 12.14.1
 - **NPM version:** 7.7.6
 - **Browser name and version:** Chrome latest
 - **Platform name and version:** Windows 10 (on browserstack)

**Describe the bug**
There are some methods like `waitForDisplayed` and `scrollIntoView` that cannot be run on browserstack

**Configuration**

```
{
  config: {
    runner: 'local',
    hostname: 'hub-cloud.browserstack.com',
    protocol: 'http',
    port: 80,
    screenshotPath: './errorShots/',
    specs: [ './test/selenium/tests/**/*.js' ],
    suites: { smoke: [Array], x: [Array] },
    maxInstances: 3,
    resolution: '1280x1024',
    capabilities: [ { browserName: 'chrome' } ],
    logLevel: 'error',
    logLevels: { webdriver: 'error', '@wdio/sync': 'error' },
    bail: 0,
    baseUrl: 'https://URL.com',
    waitforTimeout: 30000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: [
            'browserstack',
            {
                capabilities: [{
                    'browserstack.local': true,
                    'browserstack.localIdentifier': localIdentifier,
                    name: 'Smoke Tests',
                    project: 'XXXXX',
                    build: process.env.CI_PIPELINE_ID || 'local-pipeline',
                    os: 'Windows',
                    os_version: '10',
                    browser: 'Chrome',
                    browser_version: '91.0',
                    resolution: '1280x1024'
                }],
                maxInstances: 2,
            }
        ],
    framework: 'jasmine',
    reporters: [ 'spec' ],
    jasmineNodeOpts: { defaultTimeoutInterval: 120000 },
    user: '********************',
    key: '********************',
    onPrepare: [Function: onPrepare],
    onComplete: [Function: onComplete]
  }
```

**To Reproduce**
```
it('Renders unit list', () => {
  const unitList = $('.unit-list .bookable-unit-details:first-child');
  unitList.waitForExist();
  unitList.waitForDisplayed({ timeout: 100000 });
});
```

**Log**

```

> ./node_modules/.bin/wdio test/selenium/config/browserstack.conf.js --suite x


Execution of 1 workers started at 2021-07-15T19:06:49.343Z

[0-0] RUNNING in chrome - /test/selenium/tests/productCityPage/productCityPageSmoke.js
[0-0] 2021-07-15T19:07:21.920Z ERROR webdriver: Request failed with status 500 due to unknown command: POST /session/a781d62dbafc436b6e283e4975ee39e90833249c/execute/sync
[0-0] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[0-0] System info: host: '207-254-19-105', ip: '207.254.19.105', os.name: 'windows', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_181'
[0-0] Driver info: driver.version: unknown
[0-0] Error in "PCP Critical Path Navigates to facility page on unit click"
unknown command: POST /session/a781d62dbafc436b6e283e4975ee39e90833249c/execute/sync
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '207-254-19-105', ip: '207.254.19.105', os.name: 'windows', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_181'
Driver info: driver.version: unknown
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at UserContext.<anonymous> (/XXXXXXX/test/selenium/tests/productCityPage/productCityPageSmoke.js:37:19)
[0-0] FAILED in chrome - /test/selenium/tests/productCityPage/productCityPageSmoke.js
Not sending to DataDog

 "spec" Reporter:
------------------------------------------------------------------
[chrome 91.0.4472.106 windows #0-0] Running: chrome (v91.0.4472.106) on windows
[chrome 91.0.4472.106 windows #0-0] Session ID: a781d62dbafc436b6e283e4975ee39e90833249c
[chrome 91.0.4472.106 windows #0-0]
[chrome 91.0.4472.106 windows #0-0] » /test/selenium/tests/productCityPage/productCityPageSmoke.js
[chrome 91.0.4472.106 windows #0-0] PCP Critical Path
[chrome 91.0.4472.106 windows #0-0]    ✓ Has a page title
[chrome 91.0.4472.106 windows #0-0]    ✓ Loads search results
[chrome 91.0.4472.106 windows #0-0]    ✓ Loads the map
[chrome 91.0.4472.106 windows #0-0]    ✓ Navigates to facility page on facility title click
[chrome 91.0.4472.106 windows #0-0]    ✖ Navigates to facility page on unit click
[chrome 91.0.4472.106 windows #0-0]    ✓ Has breadcrumbs
[chrome 91.0.4472.106 windows #0-0]
[chrome 91.0.4472.106 windows #0-0]     Header tests
[chrome 91.0.4472.106 windows #0-0]        ✓ Has phone number in the header
[chrome 91.0.4472.106 windows #0-0]
[chrome 91.0.4472.106 windows #0-0]     Footer Tests
[chrome 91.0.4472.106 windows #0-0]        ✓ Has phone number in the footer
[chrome 91.0.4472.106 windows #0-0]
[chrome 91.0.4472.106 windows #0-0] 7 passing (38.3s)
[chrome 91.0.4472.106 windows #0-0] 1 failing
[chrome 91.0.4472.106 windows #0-0]
[chrome 91.0.4472.106 windows #0-0] 1) PCP Critical Path Navigates to facility page on unit click
[chrome 91.0.4472.106 windows #0-0] unknown command: POST /session/a781d62dbafc436b6e283e4975ee39e90833249c/execute/sync
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '207-254-19-105', ip: '207.254.19.105', os.name: 'windows', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_181'
Driver info: driver.version: unknown
[chrome 91.0.4472.106 windows #0-0] unknown command: POST /session/a781d62dbafc436b6e283e4975ee39e90833249c/execute/sync
[chrome 91.0.4472.106 windows #0-0] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[chrome 91.0.4472.106 windows #0-0] System info: host: '207-254-19-105', ip: '207.254.19.105', os.name: 'windows', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_181'
[chrome 91.0.4472.106 windows #0-0] Driver info: driver.version: unknown
[chrome 91.0.4472.106 windows #0-0]     at processTicksAndRejections (internal/process/task_queues.js:94:5)
[chrome 91.0.4472.106 windows #0-0]     at UserContext.<anonymous> (/XXXXXXX/test/selenium/tests/productCityPage/productCityPageSmoke.js:37:19)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:47 
```

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
This seems like a problem with BS not supporting a valid W3C WebDriver command. I recommend to reach out to their support team. Also note that you should not set capabilities within the browserstack service option, they are not recognised there.

**Comment by MikeVelazcoMtz** [comment]
Just wanted to include the response I've got from the browserstack support:


> Hi Miguel,
> ​
> Thank you for reaching out.
> ​
> I reviewed the shared details and in order to debug this further, could you kindly execute a few more tests with the following capabilities:


```
"browserstack.selenium_version" : "3.141.59",
"browserstack.use_w3c": true
```


> Do try this and let us know in case you are still encountering the same do share the details, we'd be happy to assist you further. 
> 
> Regards,
> Heena Nanwani
> BrowserStack Support
> 

I added those capabilities and solved the issue.

**Comment by christian-bromann** [comment]
@MikeVelazcoMtz thanks for sharing this!
