### ISSUE TITLE
browser.mock is not a function

### ISSUE THREAD

**Issue by chaitrashekar21** [webdriverio/webdriverio#7172]
**Describe the bug**
I am not able to use browser.mock() method. I followed the instructions on the  pagehttps://webdriver.io/docs/api/browser/mock/. Installed devtools and browser-mock-service. When I try to  run it fails saying mock is not a function.

**Log**
2021-07-22T17:36:03.062Z ERROR @wdio/sync: TypeError: Cannot read property 'addCommand' of undefined
    at WebdriverMockService.before (C:\Users\cv\Documents\xxx\node_modules\@wdio\webdriver-mock-service\build\index.js:40:23)
    at execHook (C:\Users\cv\Documents\xxx\node_modules\@wdio\sync\build\executeHooksWithArgs.js:32:23)
2021-07-22T17:36:03.067Z ERROR @wdio/sync: TypeError: Cannot read property 'addCommand' of undefined
    at Object.setUnsupportedCommand (C:\Users\cv\Documents\xxx\node_modules\@wdio\devtools-service\build\utils.js:14:20)
    at DevToolsService._setupHandler (C:\Users\cv\Documents\xxx\node_modules\@wdio\devtools-service\build\index.js:166:28)

    at DevToolsService.before (C:\Users\cveerash1\Documents\westrock\node_modules\@wdio\devtools-service\build\index.js:44:21)
    at execHook (C:\Users\cveerash1\Documents\westrock\node_modules\@wdio\sync\build\executeHooksWithArgs.js:32:23)

**Comment by christian-bromann** [comment]
It seems you are using the `@wdio\webdriver-mock-service` which is as documentation [states](https://webdriver.io/docs/webdriver-mock-service) an internal package for testing purposes. Also here, please provide more information about the environment you are running.

**Comment by christian-bromann** [comment]
Closing due to inactivity.
