### ISSUE TITLE
Unable to run specs by using drivers

### ISSUE THREAD

**Issue by Askarov5** [webdriverio/webdriverio#7228]
Please. do not close this bug right away, I could not solve this issue for a long time. Need this to be solved to handle document upload

**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.11.3
 - **Mode:** Tried both modes: Standalone mode or WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync/async
 - **Node.js version:** v14.16.0
 - **NPM version:** 7.7.5
 - **Browser name and version:**Chrome 92
 - **Platform name and version:** Windows 10, macOS Big Sur 11.5.1
 - **Additional wdio packages used (if applicable):** 
 "dependencies": {
    "@rpii/wdio-html-reporter": "^7.0.0",
    "@wdio/local-runner": "^7.9.0",
    "babel-plugin-source-map-support": "^2.1.1",
    "source-map-support": "^0.5.19",
    "wdio-chromedriver-service": "^7.2.0",
    "webdriverio": "^6.11.3",
    "yargs": "^16.2.0"
  },
  "devDependencies": {
    "@rpii/wdio-html-reporter-pdf": "^6.2.3",
    "@wdio/cli": "^7.9.0",
    "@wdio/mocha-framework": "^6.10.4",
    "@wdio/sync": "^6.10.4",
    "chromedriver": "^92.0.1",
    "@wdio/spec-reporter": "^7.9.0",
    "wdio-json-reporter": "^0.4.0"
  },
**Config of WebdriverIO**
capabilities: [{
maxInstances: 1, 
browserName: "chrome"
}], 
services: ['chromedriver'], 

**Describe the bug**
Unable to run specs by using drivers, getting the following Error message even if I followed documentation and even all plugins are installed.
ERROR @wdio/utils:initialiseServices: Error: Couldn't find plugin "chromedriver" service, neither as wdio scoped package "@wdio/chromedriver-service" nor as community package "wdio-chromedriver-service". Please make sure you have it installed!
    at Object.initialisePlugin [as default] (/usr/local/lib/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialisePlugin.js:41:11)
    at initialiseServices (/usr/local/lib/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialiseServices.js:59:51)
    at Object.initialiseLauncherService (/usr/local/lib/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialiseServices.js:86:26)
    at Launcher.run (/usr/local/lib/node_modules/@wdio/cli/build/launcher.js:73:73)
    at launch (/usr/local/lib/node_modules/@wdio/cli/build/commands/run.js:126:21)
    at Object.handler (/usr/local/lib/node_modules/@wdio/cli/build/commands/run.js:164:16)
    at Object.run (/usr/local/lib/node_modules/@wdio/cli/build/index.js:72:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/@wdio/cli/bin/wdio.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**To Reproduce**
1. Run specs by given configs

**Expected behavior**
Run specs by using drivers(required for document upload)

**Log**
ERROR @wdio/utils:initialiseServices: Error: Couldn't find plugin "chromedriver" service, neither as wdio scoped package "@wdio/chromedriver-service" nor as community package "wdio-chromedriver-service". Please make sure you have it installed!
    at Object.initialisePlugin [as default] (/usr/local/lib/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialisePlugin.js:41:11)
    at initialiseServices (/usr/local/lib/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialiseServices.js:59:51)
    at Object.initialiseLauncherService (/usr/local/lib/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialiseServices.js:86:26)
    at Launcher.run (/usr/local/lib/node_modules/@wdio/cli/build/launcher.js:73:73)
    at launch (/usr/local/lib/node_modules/@wdio/cli/build/commands/run.js:126:21)
    at Object.handler (/usr/local/lib/node_modules/@wdio/cli/build/commands/run.js:164:16)
    at Object.run (/usr/local/lib/node_modules/@wdio/cli/build/index.js:72:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/@wdio/cli/bin/wdio.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
> Error: Couldn't find plugin "chromedriver" service, neither as wdio scoped package "@wdio/chromedriver-service" nor as community package "wdio-chromedriver-service". Please make sure you have it installed!

I think this error says it all, please install the chromedriver service via:

```sh
$ npm install wdio-chromedriver-service
```

**Comment by Askarov5** [comment]
It is installed, but webdriverio can not find it and showing that error

**Comment by christian-bromann** [comment]
@Askarov5 you can try to create a fresh setup in an empty directory:

```sh
$ npm i @wdio/cli
$ npx wdio config --yes
$ npx wdio run wdio.conf.js
```

May I ask why my answer was downvoted? Given your issue description it is the only thing I was able to say. Please note that we can not look into your system and we can only give as much help as the other side provides. My answer could have been better if you could at least provide something like a reproducible example or a better description how your project is setup.

**Comment by erwinheitzman** [comment]
The problem is that you are using "wdio-chromedriver-service": "^7.2.0", with webdriverio V6. Either upgrade WebdriverIO (and any other potential packages) to v7. Or downgrade the chromedriver service to V6.

**Comment by Askarov5** [comment]
The problem was running the scripts by incorrect command: "wdio wdio.conf.js" instead of "npx wdio wdio.conf.js". It was running even safari(which is not through devTool), that's why I did not notice it before.

**Comment by gladykov** [comment]
> @Askarov5 you can try to create a fresh setup in an empty directory:
> 
> ```shell
> $ npm i @wdio/cli
> $ npx wdio config --yes
> $ npx wdio run wdio.conf.js
> ```

This will solve the issue, but create leftover files inside home directory

**Comment by christian-bromann** [comment]
> This will solve the issue, but create leftover files inside home directory

I am not sure which files you are talking about but these are likely NPM cache files and unrelated to WebdriverIO itself.

**Comment by ravleenkaur6284** [comment]
Thanks, this resolved the issue I was facing
