### ISSUE TITLE
devtools(executeAsyncScript): fails with unclear error if pass undefined or null to args

### ISSUE THREAD

**Issue by DudaGod** [webdriverio/webdriverio#7356]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.11.0
 - **Mode:** Standalone mode
 - **Node.js version:** 12.18.1
 - **NPM version:** 6.14.5
 - **Browser name and version:** Chrome 92
 - **Platform name and version:** Linux

**Describe the bug**

I found a strange behaviour in devtools protocol when call `executeAsync` method. But in webdriver protocol everything works fine.
Code to reproduce the problem:

```js
const {remote} = require('webdriverio')
let client;

(async function () {
    client = await remote({
        automationProtocol: 'devtools',
        capabilities: {
            browserName: 'chrome'
        }
    })

    await client.url('https://github.com');

    const result = await client.executeAsync(function(a, done) {
        done(`result_${a}`);
    }, undefined);
    console.log(result);

    await client.deleteSession();
})()
    .catch(async (e) => {
        console.error(e.stack)
        await client.deleteSession()
    });
```

With devtools protocol I get an error:
```
Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of undefined
TypeError: Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of undefined
    at my_project/node_modules/devtools/build/utils.js:153:16
    at Array.map (<anonymous>)
    at DevToolsDriver.transformExecuteArgs (my_project/node_modules/devtools/build/utils.js:152:29)
    at DevToolsDriver.executeAsyncScript (my_project/node_modules/devtools/build/commands/executeAsyncScript.js:31:197)
    at Browser.wrappedCommand (my_project/node_modules/devtools/build/devtoolsdriver.js:102:55)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Browser.wrapCommandFn (my_project/node_modules/webdriverio/node_modules/@wdio/utils/build/shim.js:104:29)
    at async Browser.wrapCommandFn (my_project/node_modules/webdriverio/node_modules/@wdio/utils/build/shim.js:104:29)
    at async my_project/execute-async-devtools.js:21:20
```

**Comment by erwinheitzman** [comment]
It expects an array to be passed

**Comment by DudaGod** [comment]
> It expects an array to be passed

But in docs - https://webdriver.io/docs/api/browser/executeAsync/ I see example with pass args one by one without any array. Moreover it works fine in `webdriver` protocol. I expect it will work in `devtools` protocol with the same API.

**Comment by christian-bromann** [comment]
Created a PR with a fix.
