### ISSUE TITLE
Unable to run tests on BrowserStack after upgrading wdio from v5 to v7

### ISSUE THREAD

**Issue by viralkpanchal** [webdriverio/webdriverio#7457]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** [e.g. 7.12.6]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [e.g. 12.16.1 & 14.16.1]
 - **NPM version:** [e.g. 6.14.12]
 - **Mobile App:** [e.g. iOS & Android]
 - **Platform name and version:** [e.g. iOS version 14.2]
 - **Additional wdio packages used (if applicable):** ["@wdio/allure-reporter": "^7.12.5",
        "@wdio/cli": "^7.12.6",
        "@wdio/local-runner": "^7.12.5",
        "@wdio/mocha-framework": "^7.12.5",
        "@wdio/spec-reporter": "^7.12.5",
        "@wdio/sync": "^7.12.5",
        "assert": "^2.0.0",
        "aws-sdk": "^2.972.0",
        "config": "^1.28.1",
        "eslint": "^7.32.0",
        "eslint-config-airbnb-base": "^14.2.1",
        "eslint-plugin-import": "^2.24.1",
        "eslint-plugin-wdio": "^7.0.0",
        "fs": "0.0.1-security",
        "mocha": "^6.2.3",
        "prettier": "^1.19.1",
        "request": "^2.88.2",
        "request-promise": "^4.2.6",
        "webdriverio": "^7.12.5",
        "xml2js": "^0.4.23",
        "@babel/cli": "^7.14.8",
        "@babel/core": "^7.15.0",
        "@babel/plugin-proposal-class-properties": "^7.14.5",
        "@babel/preset-env": "^7.15.0",
        "@babel/register": "^7.15.3",
        "@wdio/appium-service": "^7.12.5",
        "@wdio/browserstack-service": "^7.12.5"]

**Config of WebdriverIO**
Attached
[iOS.config.txt](https://github.com/webdriverio/webdriverio/files/7209080/iOS.config.txt)
[wdio.config.common.txt](https://github.com/webdriverio/webdriverio/files/7209081/wdio.config.common.txt)
[package.txt](https://github.com/webdriverio/webdriverio/files/7209083/package.txt)

**Describe the bug**
After upgrading a Webdriver IO to version 7 and using W3C capabilities in the configuration files, test cases do not get executed on the BrowserStack. Test execution fails with the error `Error: Failed to create a session. connect ETIMEDOUT 173.234.104.3:4723`

**To Reproduce**
- Upgrade WebdriverIO to version 7 with versions as mentioned above.
- Use BrowserStack to run tests.
- Use W3C capabilities to configure the iOS / Android capabilities.

**Expected behavior**
Test case execution starts on BrowserStack.

**Log**
```
2021-09-22T02:56:11.118Z WARN @wdio/utils:shim: You are running tests with @wdio/sync which will be discontinued starting Node.js v16.Read more on https://github.com/webdriverio/webdriverio/discussions/6702
2021-09-22T02:56:11.481Z INFO @wdio/local-runner: Run worker command: run
2021-09-22T02:57:29.385Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
2021-09-22T02:58:44.877Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
2021-09-22T03:00:00.880Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
2021-09-22T03:01:16.172Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
2021-09-22T03:02:31.447Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
2021-09-22T03:03:46.766Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
2021-09-22T03:05:02.483Z ERROR webdriver: Request failed with status undefined due to RequestError: connect ETIMEDOUT 173.234.104.3:4723
2021-09-22T03:05:02.483Z ERROR webdriver: RequestError: connect ETIMEDOUT 173.234.104.3:4723
    at ClientRequest.<anonymous> (working_directory/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.origin.emit (working_directory/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
2021-09-22T03:05:02.483Z ERROR @wdio/runner: Error: Failed to create session.
connect ETIMEDOUT 173.234.104.3:4723
    at Object.startWebDriverSession (working_directory/node_modules/webdriver/build/utils.js:71:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Function.newSession (working_directory/node_modules/webdriver/build/index.js:58:45)
    at Object.remote (working_directory/node_modules/webdriverio/build/index.js:67:22)
    at Runner._startSession (working_directory/node_modules/@wdio/runner/build/index.js:217:56)
    at Runner._initSession (working_directory/node_modules/@wdio/runner/build/index.js:173:25)
    at Runner.run (working_directory/node_modules/@wdio/runner/build/index.js:87:19)
```

**Interaction with BrowserStack**
- Browserstack engineer mentioned that this issue exists not only with BrowserStack but also with other providers for anyone who uses v7 of WebdriverIO with Appium for mobile app automation. BrowserStack pointed out this issue as a reference: https://github.com/webdriverio/webdriverio/issues/5262
-

**Comment by christian-bromann** [comment]
@viralkpanchal are you running your tests through a proxy? If so please make sure you update the proxy settings as described here: https://webdriver.io/docs/proxy

I will go ahead and close as I am pretty sure it is a proxy configuration issue. Happy to re-open if not.

**Comment by viralkpanchal** [comment]
@christian-bromann - We don't use proxy in our tests. This issue still persist..

**Comment by christian-bromann** [comment]
> 173.234.104.3:4723

If you want to run on BS why is it trying to connect to this IP address?

**Comment by gvozdeva-ira** [comment]
But why it can't reach server and why error log is shown some weird IP when test failed? i tried to run simple test in project with wdio 6 - it was success: no problem to run in iPhone on Browserstack , when i try to do the same with wdio7 - it failed with this ETIMEDOUT error

**Comment by gvozdeva-ira** [comment]
@viralkpanchal are you able to resolve this issue?

**Comment by gvozdeva-ira** [comment]
I found the reason: I had "port:4723" in my wdio config, so after i removed this - everything works smoothly
