### ISSUE TITLE
error of unhandled promise connect ECONNRESET 127.0.0.1:4444 on macOS when .waitForDisplayed() and .click() are called for imported from .obj file selector

### ISSUE THREAD

**Issue by vlad-dargel** [webdriverio/webdriverio#7490]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.13.2
 - **Mode:** Standalone mode ( "@wdio/selenium-standalone-service": "7.13.2")
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** v14.18.0
 - **NPM version:** 6.14.15
 - **Browser name and version:** Chrome 94.0.4606.71
 - **Platform name and version:** macOS 11.6
 - **Additional wdio packages used (if applicable):**  "@wdio/selenium-standalone-service": "7.13.2", "@wdio/spec-reporter": "7.13.2", "@wdio/local-runner": "7.13.2"
 - **typescript:** "4.3.5"

**Config of WebdriverIO**
{
    specs: [
        './features/featureFiles/web/**/*.feature'
    ],
    //Setting for excluding non-used stuff
    exclude: [],
    //Global number of instances for parallel execution, i.e. 10 instances in case of 3 browsers will run 30 tests at once (10 for each browser)
    maxInstances: 1,
    port: 4444,
    path: '/wd/hub',
    
    capabilities: [{
        maxInstances: 1,
        browserName: 'chrome',
        "goog:chromeOptions": {
            args: [
                '--disable-gpu',
                '--disable-dev-shm-usage',
                '--no-sandbox',
                '--remote-debugging-port=0'
            ],
        },
        acceptInsecureCerts: true
    },
    logLevel: 'info',
    bail: 0,
    baseUrl: 'http://localhost',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: [['selenium-standalone', {
        logPath: './temp',
    }]],
    framework: 'cucumber',
    reporters: ['spec', ['allure', {
        outputDir: 'allure-results',
        useCucumberStepReporter: true
    }]],

    cucumberOpts: {
        require: ['./features/stepDefinitions/web/**/*.steps.ts'],
        backtrace: false,
        requireModule: [],
        dryRun: false,
        failFast: false,
        format: ['pretty'],
        snippets: true,
        source: true,
        profile: [],
        strict: false,
        tagExpression: '@vd',
        timeout: 60000,
        ignoreUndefinedDefinitions: false
    },
}

**Describe the bug**
connect ECONNRESET 127.0.0.1:4444 appears on macOS when .waitForDisplayed() and .click() are called for imported from .obj file selector.
It was reproduced some times on Windows too.

After some investigations I noticed that this error is not related to selenium server, but related to Unhandled promise in case when the selector was called from separate .obj.ts file
AND it was called by .waitForDisplayed() and then .click() methods

example:
```
        await loginRepository.signInButton.waitForDisplayed();
        await loginRepository.signInButton.click();
```

where loginRepository - variable with imported selectors from .obj file

```
import { webLoginPageRepository } from "../../objectRepository/web/login.obj";

//Loading object repository
let loginRepository = new webLoginPageRepository;
```

**Expected behavior**
no error

**Comment by christian-bromann** [comment]
Can you provide some logs from the Selenium server?

**Comment by vlad-dargel** [comment]
[0-2] 2021-10-01T08:00:06.574Z INFO webdriver: COMMAND elementClick("e9067cf4-7366-4b8b-981a-676b11082541")
[0-2] 2021-10-01T08:00:06.574Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/579e4b5c9173d5512260a70db1ec846f/element/e9067cf4-7366-4b8b-981a-676b11082541/click
[0-2] (node:2765) UnhandledPromiseRejectionWarning: RequestError: connect ECONNRESET 127.0.0.1:4444
[0-2]     at ClientRequest.<anonymous> (/Users/vladislavdargel/Documents/proj/hq2.automation.tests/node_modules/got/dist/source/core/index.js:956:111)
[0-2]     at Object.onceWrapper (events.js:520:26)
[0-2]     at ClientRequest.emit (events.js:412:35)
[0-2]     at ClientRequest.emit (domain.js:475:12)
[0-2]     at ClientRequest.origin.emit (/Users/vladislavdargel/Documents/proj/hq2.automation.tests/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[0-2]     at Socket.socketErrorListener (_http_client.js:475:9)
[0-2]     at Socket.emit (events.js:400:28)
[0-2]     at Socket.emit (domain.js:475:12)
[0-2]     at emitErrorNT (internal/streams/destroy.js:106:8)
[0-2]     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[0-2]     at processTicksAndRejections (internal/process/task_queues.js:82:21)
[0-2]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[0-2] (node:2765) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 140)
[0-2] Error in "5: And I am on "User Test" Profile page"
RequestError: connect ECONNRESET 127.0.0.1:4444
    at ClientRequest.<anonymous> (/Users/vladislavdargel/Documents/proj/hq2.automation.tests/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.emit (domain.js:475:12)
    at ClientRequest.origin.emit (/Users/vladislavdargel/Documents/proj/hq2.automation.tests/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

> Can you provide some logs from the Selenium server?

**Comment by christian-bromann** [comment]
These are WDIO logs, we need to look into the Selenium server logs to understand why it couldn't start

**Comment by vlad-dargel** [comment]
for some reason I have no logs saved by selenium server by this path 
    services: [['selenium-standalone', {
        logPath: './temp',

**Comment by christian-bromann** [comment]
Can you try to investigate why the server is not starting?

**Comment by vlad-dargel** [comment]
It is started, but for some reason it fails during running tests (e.g. first step passed successfully in tests)

**Comment by christian-bromann** [comment]
> It is started

Can you get the logs then?

**Comment by vlad-dargel** [comment]
After some investigations I noticed that this error is not related to selenium server, but related to Unhandled promise in case when the selector was called from separate .obj.ts file
AND it was called by .waitForDisplayed() and then .click() methods

example:
        await loginRepository.signInButton.waitForDisplayed();
        await loginRepository.signInButton.click();

where loginRepository - variable with imported selectors from .obj file

`import { webLoginPageRepository } from "../../objectRepository/web/login.obj";

//Loading object repository
let loginRepository = new webLoginPageRepository;`

**Comment by christian-bromann** [comment]
@vlad-dargel can you provide a reproducible example then?`

**Comment by christian-bromann** [comment]
Closing due to inactivity.

**Comment by vlad-dargel** [comment]
I managed to fix the problem in this way: 
in a separate .obj file, the selectors were inside the class as variables, when they were called through import, an error sometimes appeared:
![image](https://user-images.githubusercontent.com/90257586/167668721-4ff4f4d1-382e-46e1-aafb-54af6c12de95.png)
making them as an object properties fixed this issue:
![image](https://user-images.githubusercontent.com/90257586/167669051-403a0294-c6d2-4f45-b4cf-c83aac26f0c2.png)
