### ISSUE TITLE
Error in BrowserStack service after scenario

### ISSUE THREAD

**Issue by fogrizovic** [webdriverio/webdriverio#7492]
**Description:**

Added bstack support as described [here](https://webdriver.io/docs/browserstack-service/). After running the tests, getting this error in the logs:

```
[0-0] 2021-10-01T13:58:32.382Z ERROR @wdio/utils:shim: TypeError: Cannot read property 'toLowerCase' of undefined
[0-0]     at BrowserstackService.afterScenario (/node_modules/@wdio/browserstack-service/build/service.js:103:131)
[0-0]     at /node_modules/@wdio/utils/build/shim.js:82:27
[0-0]     at new Promise (<anonymous>)
[0-0]     at /node_modules/@wdio/utils/build/shim.js:79:47
[0-0]     at Array.map (<anonymous>)
[0-0]     at Object.executeHooksWithArgsShim (/node_modules/@wdio/utils/build/shim.js:79:33)
[0-0]     at World.wdioHookAfterScenario (/node_modules/@wdio/cucumber-framework/build/index.js:250:27)
[0-0]     at Object.run (/node_modules/@cucumber/cucumber/src/user_code_runner.ts:38:21)
[0-0]     at Object.run (/node_modules/@cucumber/cucumber/src/runtime/step_runner.ts:53:41)
[0-0]     at TestCaseRunner.invokeStep (/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:131:12)
[0-0]     at TestCaseRunner.runHook (/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:255:12)
[0-0]     at /node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:213:20
[0-0]     at TestCaseRunner.aroundTestStep (/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:164:28)
[0-0]     at TestCaseRunner.run (/node_modules/@cucumber/cucumber/src/runtime/test_case_runner.ts:203:9)
[0-0]     at Runtime.runTestCase (/node_modules/@cucumber/cucumber/src/runtime/index.ts:123:20)
[0-0]     at /node_modules/@cucumber/cucumber/src/runtime/index.ts:153:7
```

**package.json**

"devDependencies": {
    "@wdio/browserstack-service": "^7.13.2",
    "@wdio/cli": "^7.14.0",
    "@wdio/cucumber-framework": "^7.13.2",
    "@wdio/devtools-service": "^7.14.0",
    "@wdio/local-runner": "^7.13.2",
    "@wdio/selenium-standalone-service": "^7.13.2",
    "@wdio/spec-reporter": "^7.13.2",
    "wdio-cucumberjs-json-reporter": "^4.1.4",
    "wdio-docker-service": "^3.1.4",
    "wdio-image-comparison-service": "^3.0.0",
  }

**Comment by christian-bromann** [comment]
Fixed in PR #7507
