### ISSUE TITLE
[Jasmine] Target Closed error on attempt to take a screenshot

### ISSUE THREAD

**Issue by NavyMint** [webdriverio/webdriverio#7520]
**Environment:**
 - **WebdriverIO version:** 7.13.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 15.5.1
 - **NPM version:** 7.3.0
 - **Browser name and version:** Chrome 94.0.4606.71
 - **Platform name and version:** Windows 10 Pro
 - **Additional wdio packages used (if applicable):** 
        - "wdio-teamcity-reporter": "2.3.0",
        - "wdio-chromedriver-service": "7.2.2",
        - "@wdio/cli": "7.14.0",
        - "@wdio/jasmine-framework": "7.13.2",
        - "@wdio/local-runner": "7.13.2",
        - "@wdio/spec-reporter": "7.13.2",
        - "@wdio/types": "7.13.2"

**Config of WebdriverIO**
```
import path from 'path';

export const config: WebdriverIO.Config = {
    baseUrl: 'https://random.org/',
    specs: ['./test/specs/'],
    capabilities: [{
        browserName: 'chrome',
        acceptInsecureCerts: true
        }
    ],
    logLevel: 'debug',
    framework: 'jasmine',
    jasmineOpts: {
        defaultTimeoutInterval: 30000
    },
    reporters: ['spec'],

    afterTest: async (test, context, { error, result, duration, passed }) => {
        if (!passed) {
            const nameBase = `${Date.now()}`;
            const screenshotName = `${nameBase}.png`;
            await browser.saveScreenshot(path.resolve('.', screenshotName));
        }
    }
};
```

**Describe the bug**
Im getting error Target Closed in afterTest hook when we are trying to take screenshot on a failed case. That's happening ocasionally in a big suite. I suppose it happens for last test case when session is about to close (not sure). But I will attach repository where Im able to reproduce this error steadily.

**To Reproduce**
Created repository with 1 test case, where the problem reproduces 
https://github.com/NavyMint/reproduce-screenshot-error

**Expected behavior**
We should be able to take screenshot without errors

**Log**
```
Debugger attached.
2021-10-01T14:45:11.759Z WARN @wdio/config:ConfigParser: pattern ./test/specs/ did not match any file

Execution of 1 workers started at 2021-10-01T14:45:11.818Z

2021-10-01T14:45:12.006Z INFO @wdio/cli:launcher: Run onPrepare hook
on prepare hook
2021-10-01T14:45:12.008Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-10-01T14:45:12.010Z INFO @wdio/local-runner: Start worker 0-0 with arg: C:\reproduce-err-main\wdio.conf.ts,--spec,test/specs/errScreenshots.e2e.ts
[0-0] 2021-10-01T14:45:13.796Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2021-10-01T14:45:14.226Z DEBUG @wdio/config:utils: Found 'ts-node' package, auto-compiling TypeScript files
[0-0] 2021-10-01T14:45:14.326Z WARN @wdio/config:ConfigParser: pattern ./test/specs/ did not match any file
[0-0] 2021-10-01T14:45:14.329Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] RUNNING in chrome - C:\reproduce-err-main\test\specs\errScreenshots.e2e.ts
[0-0] 2021-10-01T14:45:14.746Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-10-01T14:45:14.912Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-0] 2021-10-01T14:45:14.915Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --disable-extensions --auth-server-whitelist="_" ---window-position=0,0 --window-size=1920,1080
[0-0] 2021-10-01T14:45:15.683Z INFO devtools: Connect Puppeteer with browser on port 54825
[0-0] Before hook
[0-0] 2021-10-01T14:45:15.976Z DEBUG @wdio/utils:shim: Finished to run "before" hook in 0ms
[0-0] ##teamcity[testSuiteStarted name='Something' flowId='57b7d107-81d6-405c-8f1b-f3103663f8d5/0-0']
[0-0] ##teamcity[testStarted name='test-2' captureStandardOutput='false' flowId='57b7d107-81d6-405c-8f1b-f3103663f8d5/0-0']
[0-0] 2021-10-01T14:45:16.006Z INFO devtools: COMMAND navigateTo("https://random.org/")
[0-0] 2021-10-01T14:45:17.693Z INFO devtools: RESULT null
[0-0] 2021-10-01T14:45:17.717Z INFO devtools: COMMAND findElement("css selector", "#fakeid")
[0-0] 2021-10-01T14:45:17.725Z INFO devtools: RESULT Error: Element with selector "#fakeid" not found
[0-0]     at DevToolsDriver.findElement (C:\reproduce-err-main\node_modules\devtools\build\utils.js:104:16)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:93:5)
[0-0]     at async Browser.wrappedCommand (C:\reproduce-err-main\node_modules\devtools\build\devtoolsdriver.js:102:26)
[0-0]     at async Browser.wrapCommandFn (C:\reproduce-err-main\node_modules\@wdio\utils\build\shim.js:131:29)
[0-0]     at async Browser.$ (C:\reproduce-err-main\node_modules\webdriverio\build\commands\browser\$.js:88:17)
[0-0]     at async Browser.wrapCommandFn (C:\reproduce-err-main\node_modules\@wdio\utils\build\shim.js:131:29)
[0-0]     at async UserContext.<anonymous> (C:\reproduce-err-main\test\specs\errScreenshots.e2e.ts:5:14)
[0-0] 2021-10-01T14:45:17.741Z INFO devtools: COMMAND findElements("css selector", "#fakeid")
[0-0] 2021-10-01T14:45:17.746Z INFO devtools: RESULT []
[0-0] 2021-10-01T14:45:18.240Z INFO devtools: COMMAND findElements("css selector", "#fakeid")
[0-0] 2021-10-01T14:45:18.246Z INFO devtools: RESULT []
[0-0] 2021-10-01T14:45:18.755Z INFO devtools: COMMAND findElements("css selector", "#fakeid")
[0-0] 2021-10-01T14:45:18.762Z INFO devtools: RESULT []
[0-0] 2021-10-01T14:45:19.250Z INFO devtools: COMMAND findElements("css selector", "#fakeid")
[0-0] 2021-10-01T14:45:19.257Z INFO devtools: RESULT []
[0-0] 2021-10-01T14:45:19.754Z INFO devtools: COMMAND findElements("css selector", "#fakeid")
[0-0] 2021-10-01T14:45:19.759Z INFO devtools: RESULT []
[0-0] 2021-10-01T14:45:20.254Z INFO devtools: COMMAND findElements("css selector", "#fakeid")
[0-0] 2021-10-01T14:45:20.259Z INFO devtools: RESULT []
[0-0] Error in "Something test-2"
Error: element ("#fakeid") still not existing after 3000ms
    at async UserContext.<anonymous> (C:\reproduce-err-main\test\specs\errScreenshots.e2e.ts:5:7)   
[0-0] ##teamcity[testFailed name='test-2' message='Unhandled promise rejection: Error: element ("#fakeid") still not existing after 3000ms' details='Error: element ("#fakeid") still not existing after 3000ms|n    at async UserContext.<anonymous> (C:\reproduce-err-main\test\specs\errScreenshots.e2e.ts:5:7)' flowId='57b7d107-81d6-405c-8f1b-f3103663f8d5/0-0']
[0-0] ##teamcity[testFinished name='test-2' duration='4765' flowId='57b7d107-81d6-405c-8f1b-f3103663f8d5/0-0']
[0-0] 2021-10-01T14:45:20.762Z INFO devtools: COMMAND findElements("css selector", "#fakeid")
[0-0] 2021-10-01T14:45:20.763Z INFO devtools: COMMAND takeScreenshot()
[0-0] ##teamcity[testSuiteFinished name='Something' flowId='57b7d107-81d6-405c-8f1b-f3103663f8d5/0-0']
[0-0] 2021-10-01T14:45:20.788Z INFO devtools: RESULT []
[0-0] 2021-10-01T14:45:20.819Z INFO devtools: COMMAND deleteSession()
[0-0] 2021-10-01T14:45:20.830Z INFO devtools: RESULT null
[0-0] 2021-10-01T14:45:20.879Z ERROR @wdio/utils:shim: Protocol error (Page.captureScreenshot): Target closed.
[0-0] Error: Protocol error (Page.captureScreenshot): Target closed.
[0-0]     at C:\reproduce-err-main\node_modules\puppeteer-core\src\common\Connection.ts:291:57      
[0-0]     at new Promise (<anonymous>)
[0-0]     at CDPSession.send (C:\reproduce-err-main\node_modules\puppeteer-core\src\common\Connection.ts:290:12)
[0-0]     at Page._screenshotTask (C:\reproduce-err-main\node_modules\puppeteer-core\src\common\Page.ts:2691:39)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:93:5)
[0-0] 2021-10-01T14:45:20.886Z DEBUG @wdio/utils:shim: Finished to run "afterTest" hook in 132ms
[0-0] Error in "AfterTest Hook"
Protocol error (Page.captureScreenshot): Target closed.
2021-10-01T14:45:21.102Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - C:\reproduce-err-main\test\specs\errScreenshots.e2e.ts
2021-10-01T14:45:21.104Z INFO @wdio/cli:launcher: Run onComplete hook
On complete hook

 "spec" Reporter:
------------------------------------------------------------------
[Chrome 94.0.4606.71 win32 #0-0] Running: Chrome (v94.0.4606.71) on win32
[Chrome 94.0.4606.71 win32 #0-0] Session ID: 57b7d107-81d6-405c-8f1b-f3103663f8d5
[Chrome 94.0.4606.71 win32 #0-0]    ✖ test-2
[Chrome 94.0.4606.71 win32 #0-0]
[Chrome 94.0.4606.71 win32 #0-0] 1 failing (4.8s)
[Chrome 94.0.4606.71 win32 #0-0]
[Chrome 94.0.4606.71 win32 #0-0] 1) Something test-2
[Chrome 94.0.4606.71 win32 #0-0] Unhandled promise rejection: Error: element ("#fakeid") still not existing after 3000ms
[Chrome 94.0.4606.71 win32 #0-0] Error: element ("#fakeid") still not existing after 3000ms
[Chrome 94.0.4606.71 win32 #0-0]     at async UserContext.<anonymous> (C:\reproduce-err-main\test\specs\errScreenshots.e2e.ts:5:7)


```
**Additional context**
After additional invesigation I found out that if we will add property services: ['chromedriver'] to wdio.conf.ts it will solve the issue with screenshots, but in this case Im getting a lot of failures in the build with error (which is also strange, but not a goal of this topic)

```
Unhandled promise rejection: RequestError: connect ECONNREFUSED 127.0.0.1:9515
error properties: Object({ code: 'ECONNREFUSED', timings: Object({ start: 1633359745983, socket: 1633359745997, lookup: 1633359746035, connect: undefined, secureConnect: undefined, upload: undefined, response: undefined, end: undefined, error: 1633359746050, abort: undefined, phases: Object({ wait: 14, dns: 38, tcp: undefined, tls: undefined, request: undefined, firstByte: undefined, download: undefined, total: 67 }) }) })
RequestError: connect ECONNREFUSED 127.0.0.1:9515
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)
```

**Comment by christian-bromann** [comment]
Thanks for reporting!

It seems that the failing test has impact on the `afterTest` hook here. Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by praveendvd** [comment]
Happens only for puppeteer ,

**Comment by christian-bromann** [comment]
I will go ahead and close this given there hasn't been much development here. If someone can provide a reproducible example that would be fantastic, otherwise I don't see much actionable things here.

@NavyMint thanks for raising the issue anyway.
