### ISSUE TITLE
@wdio/utils:shim: SyntaxError: Unexpected token Y in JSON at position 0

### ISSUE THREAD

**Issue by dmitry-lomakin** [webdriverio/webdriverio#7530]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.9.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 14.17.6
 - **NPM version:** 6.14.15
 - **Browser name and version:** Chrome 91
 - **Platform name and version:** Mac OS Big Sur
 - **Additional wdio packages used (if applicable):** @wdio/devtools-service v7.9.1

**Config of WebdriverIO**
```
    ...
    hostname: '10.0.x.y',
    port: 4444,
    path: '/wd/hub',
    ....
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['devtools', 'rerun'],
    ...
    capabilities: [
    {
        browserName: 'chrome',
        'selenoid:options': { enableVNC: true, enableVideo: false, hostsEntries },
    },
    ],
    ...
],
```

**Describe the bug**
After the `devtool` service activation, error messages like this:
```
[0-0] 2021-10-08T07:49:55.455Z ERROR @wdio/utils:shim: SyntaxError: Unexpected token Y in JSON at position 0
[0-0]     at JSON.parse (<anonymous>)
[0-0]     at IncomingMessage.<anonymous> (/***************/e2e-wd/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:97:28)
[0-0]     at IncomingMessage.emit (events.js:412:35)
[0-0]     at IncomingMessage.emit (domain.js:470:12)
[0-0]     at endReadableNT (internal/streams/readable.js:1317:12)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:82:21)
[0-0] Error in "AfterHook Hook"
Unexpected token Y in JSON at position 0
```
started to appear in the output. I checked the actual request and it indeed attempts to read JSON at `http://10.0.x.y:4444/json/list`. The problem is that this endpoint responds with plaintext `You are using Selenoid 1.10.5!`.

It does not affect the execution of the tests though.

**To Reproduce**

* Use wdio with almost default configuration with `hostname` pointing to a [Selenoid](https://aerokube.com/selenoid/latest/) cluster entry point.

**Expected behavior**
No error messages should appear in the logs.

**Log**

See an example error message above.

**Comment by dmitry-lomakin** [comment]
Your example has the same issue when executed against my Selenoid instance:
```
(base) dmitry.lomakin@dlomakin-mb wdio-selenoid-examples % npm test

> wdio-selenoid-examples@0.0.1 test /Users/dmitry.lomakin/Sources/wdio-selenoid-examples
> wdio


Execution of 1 workers started at 2021-10-08T08:29:15.294Z

2021-10-08T08:29:15.745Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-10-08T08:29:15.747Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-10-08T08:29:15.748Z INFO @wdio/local-runner: Start worker 0-0 with arg:
[0-0] 2021-10-08T08:29:16.204Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - /test/specs/example.e2e.ts
[0-0] 2021-10-08T08:29:17.044Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-10-08T08:29:17.092Z INFO webdriver: [POST] http://10.0.X.Y:4444/wd/hub/session
[0-0] 2021-10-08T08:29:17.092Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       'selenoid:options': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     acceptInsecureCerts: true,
[0-0]     'selenoid:options': { enableVNC: true }
[0-0]   }
[0-0] }
[0-0] 2021-10-08T08:29:19.579Z ERROR @wdio/utils:shim: SyntaxError: Unexpected token Y in JSON at position 0
[0-0]     at JSON.parse (<anonymous>)
[0-0]     at IncomingMessage.<anonymous> (/Users/dmitry.lomakin/Sources/wdio-selenoid-examples/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:97:28)
[0-0]     at IncomingMessage.emit (events.js:412:35)
[0-0]     at IncomingMessage.emit (domain.js:470:12)
[0-0]     at endReadableNT (internal/streams/readable.js:1317:12)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:82:21)
[0-0] 2021-10-08T08:29:19.585Z INFO webdriver: COMMAND navigateTo("https://webdriver.io/")
[0-0] 2021-10-08T08:29:19.585Z INFO webdriver: [POST] http://10.0.X.Y:4444/wd/hub/session/1b42cee1833f22e9622fbe977db8369d/url
[0-0] 2021-10-08T08:29:19.585Z INFO webdriver: DATA { url: 'https://webdriver.io/' }
[0-0] {
[0-0]   Timestamp: 2589521.022378,
[0-0]   Documents: 25,
[0-0]   Frames: 19,
[0-0]   JSEventListeners: 300,
[0-0]   Nodes: 2143,
[0-0]   LayoutCount: 10,
[0-0]   RecalcStyleCount: 22,
[0-0]   LayoutDuration: 0.189904,
[0-0]   RecalcStyleDuration: 0.08845,
[0-0]   ScriptDuration: 0.430856,
[0-0]   TaskDuration: 1.390678,
[0-0]   JSHeapUsedSize: 5730368,
[0-0]   JSHeapTotalSize: 9658368
[0-0] }
[0-0] 2021-10-08T08:29:21.225Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2021-10-08T08:29:21.225Z INFO webdriver: [GET] http://10.0.X.Y:4444/wd/hub/session/1b42cee1833f22e9622fbe977db8369d/window
[0-0] 2021-10-08T08:29:21.283Z INFO webdriver: RESULT CDwindow-49C55A9B76B9BBC4BE8AAD259A4058D6
[0-0] 2021-10-08T08:29:21.454Z INFO webdriver: COMMAND navigateTo("https://todobackend.com/client/index.html?https://todo-backend-spring4-java8.herokuapp.com/todos/")
[0-0] 2021-10-08T08:29:21.454Z INFO webdriver: [POST] http://10.0.X.Y:4444/wd/hub/session/1b42cee1833f22e9622fbe977db8369d/url
[0-0] 2021-10-08T08:29:21.454Z INFO webdriver: DATA {
[0-0]   url: 'https://todobackend.com/client/index.html?https://todo-backend-spring4-java8.herokuapp.com/todos/'
[0-0] }
[0-0] Error in "devtools.should allow use mock feature"
Error: Expect mock to be called 1 time

Expected: 1
Received: 0
    at Context.<anonymous> (/Users/dmitry.lomakin/Sources/wdio-selenoid-examples/test/specs/example.e2e.ts:26:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0] 2021-10-08T08:29:27.562Z INFO webdriver: COMMAND deleteSession()
[0-0] 2021-10-08T08:29:27.562Z INFO webdriver: [DELETE] http://10.0.X.Y:4444/wd/hub/session/1b42cee1833f22e9622fbe977db8369d
[0-0] FAILED in chrome - /test/specs/example.e2e.ts
2021-10-08T08:29:27.806Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 92.0.4515.131 linux #0-0] Running: chrome (v92.0.4515.131) on linux
[chrome 92.0.4515.131 linux #0-0] Session ID: 1b42cee1833f22e9622fbe977db8369d
[chrome 92.0.4515.131 linux #0-0]
[chrome 92.0.4515.131 linux #0-0] » /test/specs/example.e2e.ts
[chrome 92.0.4515.131 linux #0-0] devtools
[chrome 92.0.4515.131 linux #0-0]    ✓ should allow use puppeteer instance
[chrome 92.0.4515.131 linux #0-0]    ✖ should allow use mock feature
[chrome 92.0.4515.131 linux #0-0]
[chrome 92.0.4515.131 linux #0-0] 1 passing (8.1s)
[chrome 92.0.4515.131 linux #0-0] 1 failing
[chrome 92.0.4515.131 linux #0-0]
[chrome 92.0.4515.131 linux #0-0] 1) devtools should allow use mock feature
[chrome 92.0.4515.131 linux #0-0] Expect mock to be called 1 time

Expected: 1
Received: 0
[chrome 92.0.4515.131 linux #0-0] Error: Expect mock to be called 1 time
[chrome 92.0.4515.131 linux #0-0]
[chrome 92.0.4515.131 linux #0-0] Expected: 1
[chrome 92.0.4515.131 linux #0-0] Received: 0
[chrome 92.0.4515.131 linux #0-0]     at Context.<anonymous> (/Users/dmitry.lomakin/Sources/wdio-selenoid-examples/test/specs/example.e2e.ts:26:28)
[chrome 92.0.4515.131 linux #0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)


Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:12

2021-10-08T08:29:27.807Z INFO @wdio/local-runner: Shutting down spawned worker
2021-10-08T08:29:28.058Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-10-08T08:29:28.059Z INFO @wdio/local-runner: shutting down
npm ERR! Test failed.  See above for more details.
```

**Comment by christian-bromann** [comment]
@dmitry-lomakin can you go in here:

> /Users/dmitry.lomakin/Sources/wdio-selenoid-examples/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:97:28

and log the value that Lighthouse is trying to parse?

**Comment by dmitry-lomakin** [comment]
Hi @christian-bromann,

sure, the response is in the description. Here you go:
```
e2e-wd % curl -i http://10.0.X.Y:4444/json/list
HTTP/1.1 200 OK
Date: Fri, 08 Oct 2021 12:40:47 GMT
Content-Length: 30
Content-Type: text/plain; charset=utf-8

You are using Selenoid 1.10.5!
```

**Comment by BorisOsipov** [comment]
@enliltom004 I assume you about https://github.com/aerokube/selenoid/issues/1261. https://github.com/aerokube/selenoid/issues/1023 is closed long time ago.

About 1261 - please follow @vania-pooh's  advices. You have to set the `path` properly

**Comment by vania-pooh** [comment]
@enliltom004 currently we don't pack `devtools` daemon to Edge images. So it is not expected to work. You can create a separate issue in [images](https://github.com/aerokube/images/) repository if you need it.
