### ISSUE TITLE
Unable to create session with chrome version 94 (sometimes it get created and sometime not)

### ISSUE THREAD

**Issue by srivishal1** [webdriverio/webdriverio#7546]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:7
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:**  sync
 - **Node.js version:** 14
 - **NPM version:** 6.14
 - **Browser name and version:**Chrome 94
 - **Platform name and version:** Windows10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
exports.config = {
 runner: 'local',
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub',
 maxInstances: 1,
  
    capabilities: [{
        maxInstances: 1,
        
        browserName: 'chrome',
        // browserVersion: '94.0',
        // acceptInsecureCerts: true,
   
        'goog:chromeOptions': {
            // args: ['--headless', '--disable-gpu'],
            prefs: {
                'directory_upgrade': true,
                'prompt_for_download': false,
                'download.default_directory': downloadDir
            }
        }
    }],

**Describe the bug**
I am running the script using webdriver io on a azure instance. Many time its not able to create the session however if we see in task manager we can see the running instance there.

[Step 3/4] [0-0] 2021-10-13T11:21:36.197Z INFO webdriver: DATA {
[07:21:36][Step 3/4] [0-0]   capabilities: {
[07:21:36][Step 3/4] [0-0]     alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
[07:21:36][Step 3/4] [0-0]     firstMatch: [ {} ]
[07:21:36][Step 3/4] [0-0]   },
[07:21:36][Step 3/4] [0-0]   desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': { prefs: [Object] } }
[07:21:36][Step 3/4] [0-0] }
[07:23:36][Step 3/4] [0-0] 2021-10-13T11:23:36.264Z INFO webdriver: Retrying 1/3
[07:23:36][Step 3/4] [0-0] 2021-10-13T11:23:36.264Z INFO webdriver: [POST] http://localhost:9515/session
[07:23:36][Step 3/4] [0-0] 2021-10-13T11:23:36.263Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[07:23:36][Step 3/4] [0-0] 2021-10-13T11:23:36.264Z INFO webdriver: DATA {
[07:23:36][Step 3/4] [0-0]   capabilities: {
[07:23:36][Step 3/4] [0-0]     alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
[07:23:36][Step 3/4] [0-0]     firstMatch: [ {} ]
[07:23:36][Step 3/4] [0-0]   },
[07:23:36][Step 3/4] [0-0]   desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': { prefs: [Object] } }
[07:23:36][Step 3/4] [0-0] }
[07:25:36][Step 3/4] [0-0] 2021-10-13T11:25:36.286Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[07:25:36][Step 3/4] [0-0] 2021-10-13T11:25:36.286Z INFO webdriver: Retrying 2/3
[07:25:36][Step 3/4] [0-0] 2021-10-13T11:25:36.286Z INFO webdriver: [POST] http://localhost:9515/session
[07:25:36][Step 3/4] [0-0] 2021-10-13T11:25:36.286Z INFO webdriver: DATA {
[07:25:36][Step 3/4] [0-0]   capabilities: {
[07:25:36][Step 3/4] [0-0]     alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
[07:25:36][Step 3/4] [0-0]     firstMatch: [ {} ]
[07:25:36][Step 3/4] [0-0]   },
[07:25:36][Step 3/4] [0-0]   desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': { prefs: [Object] } }
[07:25:36][Step 3/4] [0-0] }
[07:27:36][Step 3/4] [0-0] 2021-10-13T11:27:36.309Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[07:27:36][Step 3/4] [0-0] 2021-10-13T11:27:36.309Z INFO webdriver: Retrying 3/3
[07:27:36][Step 3/4] [0-0] 2021-10-13T11:27:36.309Z INFO webdriver: [POST] http://localhost:9515/session
[07:27:36][Step 3/4] [0-0] 2021-10-13T11:27:36.309Z INFO webdriver: DATA {
[07:27:36][Step 3/4] [0-0]   capabilities: {
[07:27:36][Step 3/4] [0-0]     alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': [Object] },
[07:27:36][Step 3/4] [0-0]     firstMatch: [ {} ]
[07:27:36][Step 3/4] [0-0]   },
[07:27:36][Step 3/4] [0-0]   desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': { prefs: [Object] } }
[07:27:36][Step 3/4] [0-0] }
[07:29:36][Step 3/4] [0-0] 2021-10-13T11:29:36.338Z ERROR webdriver: Request failed with status undefined due to TimeoutError: Timeout awaiting 'request' for 120000ms
[07:29:36][Step 3/4] [0-0] 2021-10-13T11:29:36.339Z ERROR webdriver: RequestError: Timeout awaiting 'request' for 120000ms
[07:29:36][Step 3/4] [0-0]     at ClientRequest.<anonymous> (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\got\dist\source\core\index.js:956:65)
[07:29:36][Step 3/4] [0-0]     at Object.onceWrapper (events.js:520:26)
[07:29:36][Step 3/4] [0-0]     at ClientRequest.emit (events.js:412:35)
[07:29:36][Step 3/4] [0-0]     at ClientRequest.emit (domain.js:475:12)
[07:29:36][Step 3/4] [0-0]     at ClientRequest.origin.emit (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
[07:29:36][Step 3/4] [0-0]     at Socket.socketErrorListener (_http_client.js:475:9)
[07:29:36][Step 3/4] [0-0]     at Socket.emit (events.js:400:28)
[07:29:36][Step 3/4] [0-0]     at Socket.emit (domain.js:475:12)
[07:29:36][Step 3/4] [0-0]     at emitErrorNT (internal/streams/destroy.js:106:8)
[07:29:36][Step 3/4] [0-0]     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[07:29:36][Step 3/4] [0-0]     at Timeout.timeoutHandler [as _onTimeout] (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\got\dist\source\core\utils\timed-out.js:36:25)
[07:29:36][Step 3/4] [0-0]     at listOnTimeout (internal/timers.js:559:11)
[07:29:36][Step 3/4] [0-0]     at processTimers (internal/timers.js:500:7)
[07:29:36][Step 3/4] [0-0] 2021-10-13T11:29:36.339Z ERROR @wdio/runner: Error: Failed to create session.
[07:29:36][Step 3/4] [0-0] Timeout awaiting 'request' for 120000ms
[07:29:36][Step 3/4] [0-0]     at Object.startWebDriverSession (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\webdriver\build\utils.js:71:15)
[07:29:36][Step 3/4] [0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[07:29:36][Step 3/4] [0-0]     at Function.newSession (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\webdriver\build\index.js:58:45)
[07:29:36][Step 3/4] [0-0]     at Object.remote (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\webdriverio\build\index.js:67:22)
[07:29:36][Step 3/4] [0-0]     at Runner._startSession (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\@wdio\runner\build\index.js:220:56)
[07:29:36][Step 3/4] [0-0]     at Runner._initSession (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\@wdio\runner\build\index.js:176:25)
[07:29:36][Step 3/4] [0-0]     at Runner.run (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\@wdio\runner\build\index.js:88:19)
[07:29:36][Step 3/4] [0-0] 2021-10-13T11:29:36.368Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot set property 'failures' of undefined
[07:29:36][Step 3/4] [0-0]     at WdioTeamcityReporter.<anonymous> (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\@wdio\reporter\build\index.js:137:38)
[07:29:36][Step 3/4] [0-0]     at WdioTeamcityReporter.emit (events.js:400:28)
[07:29:36][Step 3/4] [0-0]     at WdioTeamcityReporter.emit (domain.js:475:12)
[07:29:36][Step 3/4] [0-0]     at C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\@wdio\runner\build\reporter.js:36:56
[07:29:36][Step 3/4] [0-0]     at Array.forEach (<anonymous>)
[07:29:36][Step 3/4] [0-0]     at BaseReporter.emit (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\@wdio\runner\build\reporter.js:36:25)
[07:29:36][Step 3/4] [0-0]     at Runner._shutdown (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\@wdio\runner\build\index.js:296:24)
[07:29:36][Step 3/4] [0-0]     at Runner.run (C:\TeamCity\buildAgent4\work\45627977cfadaaca\node_modules\@wdio\runner\build\index.js:95:25)
[07:29:36][Step 3/4] [0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by srivishal1** [comment]
Yeah I understand. Actually I started facing this issue after updating to chrome version 94, before that it was perfectly fine, even I am not facing any issue while running locally on my machine.
Could you just tell me if there is any dependency of Java here, if yes what version it should support

**Comment by srivishal1** [comment]
No luck for me -

[Step 3/4] [0-0] 2021-10-13T13:47:13.086Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[09:47:13][Step 3/4] [0-0] 2021-10-13T13:47:13.086Z INFO webdriver: DATA {
[09:47:13][Step 3/4] [0-0]   capabilities: {
[09:47:13][Step 3/4] [0-0]     alwaysMatch: {
[09:47:13][Step 3/4] [0-0]       browserName: 'chrome',
[09:47:13][Step 3/4] [0-0]       browserVersion: '94.0',
[09:47:13][Step 3/4] [0-0]       acceptInsecureCerts: true,
[09:47:13][Step 3/4] [0-0]       'goog:chromeOptions': [Object]
[09:47:13][Step 3/4] [0-0]     },
[09:47:13][Step 3/4] [0-0]     firstMatch: [ {} ]
[09:47:13][Step 3/4] [0-0]   },
[09:47:13][Step 3/4] [0-0]   desiredCapabilities: {
[09:47:13][Step 3/4] [0-0]     browserName: 'chrome',
[09:47:13][Step 3/4] [0-0]     browserVersion: '94.0',
[09:47:13][Step 3/4] [0-0]     acceptInsecureCerts: true,
[09:47:13][Step 3/4] [0-0]     'goog:chromeOptions': { prefs: [Object] }
[09:47:13][Step 3/4] [0-0]   }
[09:47:13][Step 3/4] [0-0] }

it keeps retrying for 3 time and then fail, sometime its able to create session, So not sure whats wrong going on here
