### ISSUE TITLE
[🐛 Bug]: isExisting calls findElements (multiple), a potentially expensive op

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#7580]
### WebdriverIO Version

latest

### Node.js Version

14

### Mode

WDIO Testrunner

### Which capabilities are you using?

```shell
{
  platformName: "iOS"
}
```

### What happened?

Like the title says, under the hood, webdriverIO calls findElements (multiple) when using `isExisting` and `waitForExist`.
https://github.com/webdriverio/webdriverio/blob/f1313735cd3441dc172d3955479575854e64a306/packages/webdriverio/src/commands/element/isExisting.ts#L58

Only `findElement` (single) calls should be needed to assert whether or not the element / selector exists.

This becomes a problem because `findElements` calls can be quite expensive.
An example would be large scrollable lists on iOS apps, they can take 30+ seconds.

### What is your expected behavior?

No call to `findElements` should be made on isExisting as it is not needed and in fact can needlessly hang the command.

### How to reproduce the bug.

Context:
I'm testing a mobile app with Appium, testing a scrollable list.
Scrollable lists on iOS always possess all the list items, unlike Android which loads the list items into view as you scroll/swipe up and down. Therefore finding multiple elements on iOS can lead to a time consuming operation for large lists. In the same situation however, single findElement call is cheap and fast. Assume a `findElements` call takes 30+ seconds to resolve and we are trying to purposely avoid it

The flow goes something like this:
1. Wait for the (scrollable) list container
2. Then wait for the list items to load within the scrollable list
3. Irrelevant, do whatever else, expectation, whatever

This translates to some code resembling this:

```js
get list() {
  return $('id=list');
}

get items() {
  return $$('id=list-item');
}

waitForItems = (title) => {
  // We previously already waited for the list container
  // We want to wait for the list items to load within the scrollable list
  // Assume they appear instantly

  // Option 1, takes 30+ seconds because of findElements call
  browser.waitUntil(() => this.items.length);

  // Option 2, takes 30+ seconds because of findElements call
  browser.waitUntil(() => $('id=list-item').isExisting());

  // Option 3, takes 30+ seconds because of findElements call
  $('id=list-item').waitForExist();

  // Workaround to save time
  // Option 4, findElements not called, findElement called, 2 seconds
  browser.waitUntil(() => !!$('id=list-item').elementId);
}
```

### Relevant log output

No relevant logs.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by tehhowch** [comment]
@christian-bromann Is there a particular reason to prefer using "find me from my parent" logic whenever the WebdriverIO element has a `selector` vs. the "does my `elementId` still exist in the page"?

Conceivably it could be faster to do something like

```js
if (this.elementId) {
  try {
    await this.getElementTagName(this.elementId);
    return true;
  catch (e /* StaleElementException, hopefully */) {
    if (/** is error a stale element exception? if not, throw it */) throw e;
    if (!this.selector) { // No way to re-find an element that looks like this, ergo false.
      return false;
    }
  }
}
// Only do selector chain lookup now, since the page may have replaced the exact HTML element (e.g. a re-render).
```

In other words: if an element has an elementId (i.e. WDIO has looked it up already / element created by ID reference), check if that elementId is still valid. If not already looked up, or if the elementId is no longer valid, check if some new element satisfies the selector chain.

Probably which is faster is a combination of frontend technology under test (SPA frameworks vs static pages vs native apps) and how one uses WebdriverIO.

Perhaps it makes sense to make the lookup algorithm user-customizable, to support experimentation?

**Comment by christian-bromann** [comment]
> Is there a particular reason to prefer using "find me from my parent" logic whenever the WebdriverIO element has a `selector` vs. the "does my `elementId` still exist in the page"?

Yes, just checking if the `elementId` can still be used has side effects due to stale element exceptions.

> Perhaps it makes sense to make the lookup algorithm user-customizable, to support experimentation?

User can already create their own custom commands for this if they don't prefer the way WebdriverIO suggests. I believe the solution @tmjpedro will implement is reducing the performance cost to a minimal.

**Comment by BorisOsipov** [comment]
I guees we use `findElementS()` because it doesn't care about implicitWait timeout. 
If we change to `findElement()` every find call for unexisting element will cost users implicitWait time - that seems unexpected behaviour that leads to increasing test execution time.

**Comment by christian-bromann** [comment]
Hah, that is a good point. Now I remember the reason why we were using `findElements` in the first place. What are better alternatives?

**Comment by jlipps** [comment]
I'm not sure, but we definitely don't want phantom calls to findElements. As the OP said, this is sometimes quite expensive in the Appium world. I would argue that the very most this command should ever do is perform a single call to findElement. And if users suffer due to having implicit waits set, well, they would suffer in any case. Implicit waits are no longer recommended by anyone.

Generally, IMO I don't particularly like that WDIO defers finding elements until the user tries to do something. Would be cleaner to just get the element ID straightaway from the server. Then this method wouldn't even need to exist. But as it stands, we should at least get rid of the extra call to findElements

**Comment by christian-bromann** [comment]
> Would be cleaner to just get the element ID straightaway from the server. Then this method wouldn't even need to exist.

WebdriverIO initially makes an `findElement` call and only fails if you call a subsequent command on the element object.

**Comment by jlipps** [comment]
Oh right, that's how it is. So @christian-bromann what strategy can I use if I want to throw an exception in my code if an element doesn't exist, with only a single `findElement` call to the server? Do we need a new command like `element.ensureFound` that doesn't make any server calls and just throws an exception if the element wasn't found?

**Comment by jlipps** [comment]
@christian-bromann any ideas here? I'm dealing with a find element call that's expensive (5-10 seconds), and all I want to do is verify that it exists, not interact with it at all. How can I do this with webdriverio such that only a single call is made to the server?

**Comment by christian-bromann** [comment]
> How can I do this with webdriverio such that only a single call is made to the server?

You can always use the protocol command `findElement` like this:

```js
const isElemExisting = await browser.findElement('css selector', '#elem').then(() => true, () => false)
```
or
```js
const elem = (await $('#elem')).elementId
```

**Comment by jlipps** [comment]
ok cool. so calling this:

```js
await browser.findElement('css selector', '#elem')
```

will throw if the element isn't found?

**Comment by christian-bromann** [comment]
> will throw if the element isn't found?

Correct. As far as I remember it would return with a 404 status code which causes WebdriverIO to have this command to fail.

**Comment by jlipps** [comment]
This doesn't actually appear to be true. For example I just ran a test with this line:

```
        player = await driver.findElement('xpath', '//Player')
```

And the server response was:

```
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [W3C (535a9110)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [W3C (535a9110)]     at AndroidUiautomator2Driver.findElOrEls (/Users/jlipps/.appium/appium-uiautomator2-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)
[debug] [W3C (535a9110)]     at runMicrotasks (<anonymous>)
[debug] [W3C (535a9110)]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [W3C (535a9110)]     at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/jlipps/.appium/appium-uiautomator2-driver/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/lib/basedriver/commands/find.js:22:12)
[debug] [W3C (535a9110)]     at AndroidUiautomator2Driver.findElement (/Users/jlipps/.appium/appium-uiautomator2-driver/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/lib/basedriver/commands/find.js:36:10)
[HTTP] <-- POST /session/535a9110-ce06-4717-a8b5-a92b191ea5a1/element 404 109 ms - 982
```

And my test still passed. It wasn't until I tried to do something with `player` that the client code threw an error. So I guess I'm looking for a nice function that will just verify that an element exists and do nothing else :-(

**Comment by jlipps** [comment]
i also tried your other suggestion of looking at properties on the element, with something like this:

```ts
async function findAndValidate(strategy: string, selector: string) {
    const el = await driver.findElement(strategy, selector)
    if (!el.elementId) {
        throw new Error(`Element could not be found with strategy '${strategy}' and selector '${selector}'`)
    }
    return el
}
```

and it didn't work. apparently it doesn't compile with typescript because the property is not on the `ElementReference` type. i also tried it while casting to `any` and indeed, the `elementId` property doesn't exist even in the success case.

**Comment by jlipps** [comment]
ok i did some more digging. something like this works, but is wonky with types since the normal return value is not supposed to have an `error` property:

```ts
async function findAndValidate(strategy: string, selector: string) {
    const el = await driver.findElement(strategy, selector) as ElementReference & {error?: any}
    if (el.error) {
        throw new Error(`Element could not be found with strategy '${strategy}' and selector '${selector}'`)
    }
    return driver.$(el)
}
```

should we make something like this an actual wdio method?

**Comment by christian-bromann** [comment]
> since the normal return value is not supposed to have an `error` property:

This is a bug. We should expose the property through TypeScript as well.

> should we make something like this an actual wdio method?

I would suggest the following: in the `isExisting` command we check if the session is running on Appium, via `isMobile` flag and if so use the `findElement` approach given it is much more expensive there to use.

What do you think?

**Comment by jlipps** [comment]
It seems potentially a little confusing to hide some magic in there, but if that's your suggestion, then I'm happy to work with it. FWIW, I'm using WDIO to help build Appium drivers for lots of platforms beyond mobile, and it seems like having the flexibility to use this new behaviour for any platform might be good. I can also imagine myself wanting this for Selenium if I need more fine-grained control over things.

**Comment by zynp-KC** [comment]
Hi @christian-bromann, I'd like to pick this up.

Quick check before I start: is the isMobile-conditional findElement approach still the preferred direction for v9? I ask because the naive $$→$ switch was set aside earlier (findElements ignoring implicitWait, @BorisOsipov's point), and the issue was later linked to the v9 perf tracker (#14494).

Once you confirm, I'll investigate the current implementation and cover both paths with tests.
