### ISSUE TITLE
[🐛 Bug]: starter project generated with @wdio/cli does not run

### ISSUE THREAD

**Issue by Badisi** [webdriverio/webdriverio#7636]
### WebdriverIO Version

7.16.3

### Node.js Version

14.17.5

### Mode

Standalone Mode

### What happened?

The starter project generated with `@wdio/cli` does not run.

Following the [getting started guide](https://webdriver.io/docs/gettingstarted):
1) Initiate a setup
```sh
npx wdio .
```
<img width="627" alt="Screenshot 2021-11-02 at 11 26 24" src="https://user-images.githubusercontent.com/674862/139829730-5b20e686-8009-4db9-9b99-dfdf3fe11889.png">

2) Run the test
```sh
npx wdio run ./wdio.conf.js
````

This outputs the following error:
> Error: Could not execute "run" due to missing configuration. Would you like to create one? (y/N) 

### Issue

The issue here is that the wizard created a `wdio.conf.ts` and not a `wdio.conf.js` as stated in the doc (or as configured in the package.json script) 

### Attempt 1

Replacing the command with:
```sh
npx wdio run ./wdio.conf.ts
```
gives the following issue:

> SyntaxError: Unexpected token 'export'

### Workaround

Renaming `wdio.conf.ts` to `wdio.conf.js` and editing the file as follow:
```js
// replace:
// export const config: WebdriverIO.Config = {

// with:
exports.config = {
```

### What is your expected behavior?

I expect the starter project to run without issues.

### How to reproduce the bug.

Simply follow the [getting started guide](https://webdriver.io/docs/gettingstarted):
1) Initiate a setup
```sh
npx wdio .
```
2) Run the test
```sh
npx wdio run ./wdio.conf.js
```

### Relevant log output

```typescript
export const config: WebdriverIO.Config = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by praveendvd** [comment]
@Badisi  I just checked it , it works as expected. Do you have any custom tsconfig file in your project ?

you just have to run ,

npx wdio run wdio.conf.ts

**Comment by praveendvd** [comment]
It would be great if you could add the project folder as a zip file so that we could reproduce it
