### ISSUE TITLE
ues 'multiremote'   with 'webdrivercss', Error: Command "sync" is already defined!

### ISSUE THREAD

**Issue by worry127722** [webdriverio/webdriverio#764]
```
var webdriverio = require('webdriverio');
    var client = webdriverio.multiremote(options);
    require('webdrivercss').init(client,{
        screenshotRoot: xpath + '/' + time
    });
    client
        .init()
        .url(url)
        .setViewportSize({
            width: 1280,
            height: 800
        })
        //.saveScreenshot(xpath + '/'+time+'/screenshot.png',function(err, screenshot, response){
        //    console.log("screenShot DONE !");
        //})
        .webdrivercss('screenshot',[
            {
                name: 'screenshot',
                elem: 'body'
            }
        ], function(err, res) {

        }).end();

var options = {
    chrome: {
        desiredCapabilities: {
            browserName: 'chrome'

        }
    },
    firefox: {
        desiredCapabilities: {
            browserName: 'firefox'

        }
    }
  
    }; //chrome  firefox
```

error:
```
test_webd/node_modules/webdriverio/lib/webdriverio.js:257
                throw new ErrorHandler.RuntimeError('Command "' + fnName + '" 
                      ^
Error: Command "sync" is already defined!
    at new ErrorHandler.RuntimeError (/Users/ryan/workspace/test_webd/node_modules/webdriverio/lib/utils/ErrorHandler.js:92:12)
    at Object.client.addCommand (/Users/ryan/workspace/test_webd/node_modules/webdriverio/lib/webdriverio.js:257:23)
    at Object.client.addCommand (/Users/ryan/workspace/test_webd/node_modules/webdriverio/lib/multibrowser.js:174:25)
    at new WebdriverCSS (/Users/ryan/workspace/test_webd/node_modules/webdrivercss/lib/webdrivercss.js:75:19)
    at Object.module.exports.init (/Users/ryan/workspace/test_webd/node_modules/webdrivercss/lib/webdrivercss.js:84:12)
    at capture_webdriverio (/Users/ryan/workspace/test_webd/index2.js:157:29)
    at Object.<anonymous> (/Users/ryan/workspace/test_webd/index2.js:225:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by christian-bromann** [comment]
WebdriverCSS is currently only supported for WebdriverIO v2.4.5
