### ISSUE TITLE
[🐛 Bug]: Your `yarn` method doesn't work

### ISSUE THREAD

**Issue by nonopolarity** [webdriverio/webdriverio#7653]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
just the start up guide
https://webdriver.io/docs/gettingstarted/
```

### What happened?

I simply follow https://webdriver.io/docs/gettingstarted

But instead of `npm init wdio .` I thought I'd go the `yarn` way, which is `yarn init wdio .`

I have been trying for 3 hours, trying different versions of node, 12, 14, 15, 16, 17

Turns out the problem is with the `yarn` line.  If I use the `npm` version, it is set up correctly and I can run the test by `npx wdio run ./wdio.conf.js`

BUT if I use the `yarn` version `yarn init wdio .` and then run the test, I'd get error:

```bash
Config file installed successfully, creating test files...

Configuration file was created successfully!
To run your tests, execute:
$ npx wdio run wdio.conf.js

Adding scripts to package.json
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module '/Users/theusername/code/TryWDIOProject04/run/package.json'
Require stack:
- /Users/theusername/.npm/_npx/471611576716610c/node_modules/wdio/build/index.js
- /Users/theusername/.npm/_npx/471611576716610c/node_modules/wdio/bin/wdio.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at createWebdriverIO (/Users/theusername/.npm/_npx/471611576716610c/node_modules/wdio/build/index.js:81:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/theusername/.npm/_npx/471611576716610c/node_modules/wdio/build/index.js',
    '/Users/theusername/.npm/_npx/471611576716610c/node_modules/wdio/bin/wdio.js'
  ]
}
```

It worked on Intel MacBook Air, but if I used MacBook M1, I could not get it to work using the `npm` or the `yarn` method.  Using M1, the error I got:

```bash
$ npx wdio run ./wdio.conf.js

Execution of 1 workers started at 2021-11-07T23:54:04.076Z

2021-11-07T23:54:04.092Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-11-07T23:54:04.093Z INFO chromedriver: Start Chromedriver (/Users/anotherusername/code/TryWebDriverIO_7_Timing08/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2021-11-07T23:54:04.096Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at spawn (node:child_process:698:9)
    at ChromeDriverLauncher.onPrepare (/Users/anotherusername/code/TryWebDriverIO_7_Timing08/node_modules/wdio-chromedriver-service/build/launcher.js:84:45)
    at /Users/anotherusername/code/TryWebDriverIO_7_Timing08/node_modules/@wdio/cli/build/utils.js:28:40
    at Array.map (<anonymous>)
    at runServiceHook (/Users/anotherusername/code/TryWebDriverIO_7_Timing08/node_modules/@wdio/cli/build/utils.js:25:33)
    at Launcher.run (/Users/anotherusername/code/TryWebDriverIO_7_Timing08/node_modules/@wdio/cli/build/launcher.js:86:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

(later on, I tried on my MacBook Air M1, and it worked using the `npm ...` line. The one having problems was the MacBook Pro M1 Pro... I am not sure if anything is different there.  It is running Node v16.13.0.)

### What is your expected behavior?

that it works

### How to reproduce the bug.

pls see above

### Relevant log output

```typescript
see above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Sorry for the confusion. There was [a bug](https://github.com/facebook/docusaurus/issues/5861) in an underlying dependency. I made an update to be more explicit about this.
