### ISSUE TITLE
[🐛 Bug]: Can't detect element in auto popup new window in headless mode

### ISSUE THREAD

**Issue by Abel0916** [webdriverio/webdriverio#7676]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.7.8

### Node.js Version

12.16.3

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
        {
            maxInstances: 3,
            browserName: 'chrome',
            'goog:chromeOptions': {
                args: [
                    'headless',
                    '--no-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-gpu',
                ],
                prefs: {
                    'download.default_directory': DOWNLOAD_PATH.PATH,
                },
            },
        },
    ],
```

### What happened?

Can't detect new element in new auto popup window when run the same test in headless mode.
It works if I ran the test in non-headless mode.

### What is your expected behavior?

It should works same as in non-headless mode.

### How to reproduce the bug.

One of our function is to open PDF file with browser. So After click the file in our App. it will auto popup new window to open the PDF with brower.

### Relevant log output

```typescript
Some logs as below:
*******************************
2021-11-10T02:24:22.543Z INFO webdriver: COMMAND getWindowHandles()
[0-0] 2021-11-10T02:24:22.544Z INFO webdriver: [GET] http://localhost:4444/wd/hub/session/5ba2e68f518d6c526b9b8452aff90c14/window/handles
[0-0] 2021-11-10T02:24:22.550Z INFO webdriver: RESULT [
[0-0]   'CDwindow-73977486EA0F812B62086D572576D42F',
[0-0]   'CDwindow-2F638BA7FD32FB34F157FD3D704AAC79'
[0-0] ]
[0-0] 2021-11-10T02:24:22.551Z INFO webdriver: COMMAND switchToWindow("CDwindow-2F638BA7FD32FB34F157FD3D704AAC79")
[0-0] 2021-11-10T02:24:22.552Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/5ba2e68f518d6c526b9b8452aff90c14/window
[0-0] 2021-11-10T02:24:22.552Z INFO webdriver: DATA { handle: 'CDwindow-2F638BA7FD32FB34F157FD3D704AAC79' }
[0-0] 2021-11-10T02:24:22.565Z INFO webdriver: COMMAND findElement("css selector", "embed")
[0-0] 2021-11-10T02:24:22.565Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/5ba2e68f518d6c526b9b8452aff90c14/element
[0-0] 2021-11-10T02:24:22.566Z INFO webdriver: DATA { using: 'css selector', value: 'embed' }
[0-0] 2021-11-10T02:24:32.576Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2021-11-10T02:24:32.579Z INFO webdriver: Retrying 1/1
[0-0] 2021-11-10T02:24:32.579Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/5ba2e68f518d6c526b9b8452aff90c14/element
[0-0] 2021-11-10T02:24:32.580Z INFO webdriver: DATA { using: 'css selector', value: 'embed' }
[0-0] 2021-11-10T02:24:42.587Z ERROR webdriver: Request failed with status undefined due to TimeoutError: Timeout awaiting 'request' for 10000ms
[0-0] 2021-11-10T02:24:42.593Z INFO webdriver: COMMAND takeScreenshot()
[0-0] 2021-11-10T02:24:42.594Z INFO webdriver: [GET] http://localhost:4444/wd/hub/session/5ba2e68f518d6c526b9b8452aff90c14/screenshot
[0-0] 2021-11-10T02:24:52.598Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2021-11-10T02:24:52.601Z INFO webdriver: Retrying 1/1
[0-0] 2021-11-10T02:24:52.601Z INFO webdriver: [GET] http://localhost:4444/wd/hub/session/5ba2e68f518d6c526b9b8452aff90c14/screenshot
[0-0] 2021-11-10T02:25:02.608Z ERROR webdriver: Request failed with status undefined due to TimeoutError: Timeout awaiting 'request' for 10000ms
[0-0] 2021-11-10T02:25:02.619Z ERROR @wdio/sync: RequestError: Timeout awaiting 'request' for 10000ms
[0-0]     at ClientRequest.<anonymous> (/Users/tester/demo/node_modules/got/dist/source/core/index.js:956:65)
[0-0]     at ClientRequest.origin.emit (/Users/tester/demo/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[0-0]     at Socket.socketErrorListener (_http_client.js:426:9)
[0-0]     at emitErrorNT (internal/streams/destroy.js:92:8)
[0-0]     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:84:21)
*******************************
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> It works if I ran the test in non-headless mode.

This is unfortunately a Chrome limitation. WebdriverIO can't do anything about it.

**Comment by Abel0916** [comment]
@christian-bromann  Thanks for this information.
