### ISSUE TITLE
[🐛 Bug]: socket hang up with 36 instances since 7.16.4

### ISSUE THREAD

**Issue by lacell75** [webdriverio/webdriverio#7695]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.4
```typescript
  "devDependencies": {
    "@babel/cli": "7.16.0",
    "@babel/core": "7.16.0",
    "@babel/plugin-proposal-export-default-from": "7.16.0",
    "@babel/preset-env": "7.16.0",
    "@babel/register": "7.16.0",
    "@doubletrade/eslint-config-dt-base": "1.4.0",
    "@types/cucumber": "7.0.0",
    "@types/node": "14.17.33",
    "@typescript-eslint/eslint-plugin": "5.3.1",
    "@typescript-eslint/parser": "5.3.1",
    "@wdio/allure-reporter": "7.16.4",
    "@wdio/cli": "7.16.4",
    "@wdio/cucumber-framework": "7.16.4",
    "@wdio/dot-reporter": "7.16.4",
    "@wdio/local-runner": "7.16.4",
    "@wdio/mocha-framework": "7.16.4",
    "@wdio/spec-reporter": "7.16.4",
    "@wdio/sync": "7.16.4",
    "allure-commandline": "2.13.8",
    "babel-jest": "27.3.1",
    "base64-img": "1.0.4",
    "basic-ftp": "4.6.6",
    "chai": "4.3.4",
    "cheerio": "1.0.0-rc.10",
    "chromedriver": "94.0.0",
    "csvtojson": "2.0.10",
    "cucumber-tag-expressions": "2.0.3",
    "deepmerge": "4.2.2",
    "docxtemplater": "3.26.3",
    "eslint": "8.2.0",
    "eslint-config-airbnb-base": "15.0.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-html": "6.2.0",
    "eslint-plugin-import": "2.25.2",
    "eslint-plugin-prettier": "4.0.0",
    "eslint-plugin-wdio": "7.4.2",
    "expect": "27.3.1",
    "expect-webdriverio": "4.0.0",
    "find-unused-exports": "2.0.0",
    "forever": "4.0.1",
    "fs-extra": "10.0.0",
    "full-icu": "1.4.0",
    "geckodriver": "2.0.4",
    "gherkin-lint": "4.2.2",
    "glob": "7.2.0",
    "html2plaintext": "2.1.2",
    "http-server": "14.0.0",
    "husky": "7.0.4",
    "imap-simple": "5.1.0",
    "istanbul": "0.4.5",
    "istanbul-merge": "1.1.1",
    "jest": "27.3.1",
    "jest-resolve-dependencies": "27.3.1",
    "jszip": "3.7.1",
    "lint-staged": "11.2.6",
    "node-fetch": "2.6.6",
    "node-notifier": "10.0.0",
    "npm-run-all": "4.1.5",
    "pizzip": "3.1.1",
    "prettier": "2.4.1",
    "replace-x": "1.7.2",
    "request": "2.88.2",
    "sync-request": "6.1.0",
    "wdio-chromedriver-service": "7.2.2",
    "wdio-geckodriver-service": "2.0.3",
    "wdio-image-comparison-service": "3.0.0",
    "wdio-intercept-service": "4.1.9",
    "wdio-ms-teams-service": "0.1.9",
    "wdio-winappdriver-service": "0.1.1",
    "webdriverio": "7.16.4",
    "xlsx": "0.17.3",
    "xml-js": "1.6.11"
  },
```

### Node.js Version

14.17.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
      {
        maxInstances: 12,
        browserName: 'chrome',
        platformName: 'LINUX',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
          prefs: {
            'download.default_directory': '/tmp',
          },
          args: ['--disable-backgrounding-occluded-windows', '--window-size=1980,1080', '--disable-gpu'],
        },
      },
      {
        maxInstances: 12,
        browserName: 'MicrosoftEdge',
        acceptInsecureCerts: true,
        'ms:edgeOptions': {
          w3c: false,
          args: ['--disable-backgrounding-occluded-windows', '--window-size=1920,1080', '--disable-gpu'],
        },
      },
      {
        maxInstances: 12,
        browserName: 'firefox',
        platformName: 'LINUX',
        acceptInsecureCerts: true,
        'moz:firefoxOptions': {
          prefs: {
            'dom.ipc.processCount': 16,
            'browser.download.folderList': 2,
            'browser.download.dir': '/tmp',
            'browser.download.useDownloadDir': true,
            'browser.helperApps.neverAsk.saveToDisk':
              'application/vnd.ms-excel;application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'nglayout.initialpaint.delay': 0,
          },
          args: ['--width=1980', '--height=1080'],
        },
      },
    ],
```

### What happened?

Since 7.16.4, I can't launch the tests on 36 instances . I have some socket hang up. The memory and CPU are the same between 7.16.3. and 7.16.4.

With 24 instances that works.  I seen that cucumber has been updated to 8.0 in this version, maybe it can come from this package?

### What is your expected behavior?

The 36 intances of tests should be corrected launched without errors.

### How to reproduce the bug.

To reproduce launch a test on 36 instances via selenium hub. 

### Relevant log output

```typescript
Run desktop test suite on environment : dev
[32;1m$ NODE_ICU_DATA=./node_modules/full-icu ENVTOTEST=$ENV COVERAGE=$COVERAGE ./node_modules/.bin/wdio wdio.all.conf.js --suite desktop --color=256[0;m
[1m[22m
[1mExecution of [34m549[39m workers started at[22m 2021-11-10T15:38:39.142Z

[1-3] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/00-myAccount/04-updateMyXLSPreferences.feature
[2-2] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/00-myAccount/03-activateJSONAlertForStatistics.feature
[0-0] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myAccount/01-openMyAccount.feature
[2-1] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/00-myAccount/02-updateMyInformation.feature
[1-2] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/00-myAccount/03-activateJSONAlertForStatistics.feature
[0-1] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myAccount/02-updateMyInformation.feature
[2-0] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/00-myAccount/01-openMyAccount.feature
[1-1] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/00-myAccount/02-updateMyInformation.feature
[1-0] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/00-myAccount/01-openMyAccount.feature
[0-5] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myOrganization/01-configureMyCRM.feature
[0-4] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myAccount/05-creditsHistory.feature
[0-2] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myAccount/03-activateJSONAlertForStatistics.feature
[0-3] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myAccount/04-updateMyXLSPreferences.feature
[1-6] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/00-myOrganization/02-openMyOrganization.feature
[0-7] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myOrganization/03-departmentsList.feature
[2-3] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/00-myAccount/04-updateMyXLSPreferences.feature
[0-6] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myOrganization/02-openMyOrganization.feature
[1-9] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/00-myOrganization/05-createDeleteFavoritePersonalized.feature
[2-9] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/00-myOrganization/05-createDeleteFavoritePersonalized.feature
[0-8] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myOrganization/04-CRMRightsForMyOrganisation.feature
[0-10] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myOrganization/06-licencesCard.feature
[0-11] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myOrganization/07-creditsCard.feature
[2-6] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/00-myOrganization/02-openMyOrganization.feature
[0-9] [1m[36mRUNNING[39m[22m in chrome - /features/02-desktop/00-myOrganization/05-createDeleteFavoritePersonalized.feature
[1-13] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/01-simpleSearch/01a-simpleSearch.feature
[1-14] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/01-simpleSearch/01b-simpleSearchErrorCases.feature
[2-12] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/00-myOrganization/08-creditsHistory.feature
[1-12] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/00-myOrganization/08-creditsHistory.feature
[1-16] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/01-simpleSearch/02-saveQuery.feature
[2-13] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/01-simpleSearch/01a-simpleSearch.feature
[1-15] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/01-simpleSearch/01c-simpleSearchPrescripteur.feature
[2-14] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/01-simpleSearch/01b-simpleSearchErrorCases.feature
[2-17] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/01-simpleSearch/03-detailView.feature
[2-15] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/01-simpleSearch/01c-simpleSearchPrescripteur.feature
[2-16] [1m[36mRUNNING[39m[22m in firefox - /features/02-desktop/01-simpleSearch/02-saveQuery.feature
[1-17] [1m[36mRUNNING[39m[22m in MicrosoftEdge - /features/02-desktop/01-simpleSearch/03-detailView.feature
[0-0] [31mError[39m in "0: Given I am logged on "desktop" as "end2end_1" with password "pass""
[31mRequestError: socket hang up[39m
[31m    at ClientRequest.<anonymous> (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/got/dist/source/core/index.js:956:111)[39m
[31m    at Object.onceWrapper (events.js:520:26)[39m
[31m    at ClientRequest.emit (events.js:412:35)[39m
[31m    at ClientRequest.emit (domain.js:475:12)[39m
[31m    at ClientRequest.origin.emit (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)[39m
[31m    at Socket.socketOnEnd (_http_client.js:499:9)[39m
[31m    at Socket.emit (events.js:412:35)[39m
[31m    at Socket.emit (domain.js:475:12)[39m
[31m    at endReadableNT (internal/streams/readable.js:1334:12)[39m
[31m    at connResetException (internal/errors.js:639:14)[39m
[31m    at Socket.socketOnEnd (_http_client.js:499:23)[39m
[31m    at Socket.emit (events.js:412:35)[39m
[31m    at Socket.emit (domain.js:475:12)[39m
[31m    at endReadableNT (internal/streams/readable.js:1334:12)[39m
[31m    at processTicksAndRejections (internal/process/task_queues.js:82:21)[39m
[0-0] Save a screenshot
[0-0] token:0fed98aa-38af-4dd8-8f13-a05d91658e8f
[0-1] [31mError[39m in "0: Given I am logged on "desktop" as "end2end_4" with password "pass""
[31mRequestError: write EPIPE[39m
[31m    at ClientRequest.<anonymous> (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/got/dist/source/core/index.js:956:111)[39m
[31m    at Object.onceWrapper (events.js:520:26)[39m
[31m    at ClientRequest.emit (events.js:412:35)[39m
[31m    at ClientRequest.emit (domain.js:475:12)[39m
[31m    at ClientRequest.origin.emit (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)[39m
[31m    at Socket.socketErrorListener (_http_client.js:475:9)[39m
[31m    at Socket.emit (events.js:400:28)[39m
[31m    at Socket.emit (domain.js:475:12)[39m
[31m    at emitErrorNT (internal/streams/destroy.js:106:8)[39m
[31m    at emitErrorCloseNT (internal/streams/destroy.js:74:3)[39m
[31m    at afterWriteDispatched (internal/stream_base_commons.js:156:25)[39m
[31m    at writeGeneric (internal/stream_base_commons.js:147:3)[39m
[31m    at Socket._writeGeneric (net.js:798:11)[39m
[31m    at Socket._write (net.js:810:8)[39m
[31m    at writeOrBuffer (internal/streams/writable.js:358:12)[39m
[31m    at Socket.Writable.write (internal/streams/writable.js:303:10)[39m
[31m    at ClientRequest._writeRaw (_http_outgoing.js:351:17)[39m
[31m    at ClientRequest._send (_http_outgoing.js:327:15)[39m
[31m    at ClientRequest.end (_http_outgoing.js:849:10)[39m
[31m    at endRequest (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/got/dist/source/core/index.js:1342:28)[39m
[31m    at Request._final (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/got/dist/source/core/index.js:1352:13)[39m
[31m    at callFinal (internal/streams/writable.js:610:10)[39m
[31m    at processTicksAndRejections (internal/process/task_queues.js:82:21)[39m
[0-1] Save a screenshot
[1-3] [31mError[39m in "0: Given I am logged on "desktop" as "end2end_2" with password "pass""
[31mRequestError: socket hang up[39m
[31m    at ClientRequest.<anonymous> (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/got/dist/source/core/index.js:956:111)[39m
[31m    at Object.onceWrapper (events.js:520:26)[39m
[31m    at ClientRequest.emit (events.js:412:35)[39m
[31m    at ClientRequest.emit (domain.js:475:12)[39m
[31m    at ClientRequest.origin.emit (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)[39m
[31m    at Socket.socketOnEnd (_http_client.js:499:9)[39m
[31m    at Socket.emit (events.js:412:35)[39m
[31m    at Socket.emit (domain.js:475:12)[39m
[31m    at endReadableNT (internal/streams/readable.js:1334:12)[39m
[31m    at connResetException (internal/errors.js:639:14)[39m
[31m    at Socket.socketOnEnd (_http_client.js:499:23)[39m
[31m    at Socket.emit (events.js:412:35)[39m
[31m    at Socket.emit (domain.js:475:12)[39m
[31m    at endReadableNT (internal/streams/readable.js:1334:12)[39m
[31m    at processTicksAndRejections (internal/process/task_queues.js:82:21)[39m
[1-3] Save a screenshot
[2-1] [31mError[39m in "0: Given I am logged on "desktop" as "end2end_4" with password "pass""
[31mRequestError: socket hang up[39m
[31m    at ClientRequest.<anonymous> (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/got/dist/source/core/index.js:956:111)[39m
[31m    at Object.onceWrapper (events.js:520:26)[39m
[31m    at ClientRequest.emit (events.js:412:35)[39m
[31m    at ClientRequest.emit (domain.js:475:12)[39m
[31m    at ClientRequest.origin.emit (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)[39m
[31m    at Socket.socketOnEnd (_http_client.js:499:9)[39m
[31m    at Socket.emit (events.js:412:35)[39m
[31m    at Socket.emit (domain.js:475:12)[39m
[31m    at endReadableNT (internal/streams/readable.js:1334:12)[39m
[31m    at connResetException (internal/errors.js:639:14)[39m
[31m    at Socket.socketOnEnd (_http_client.js:499:23)[39m
[31m    at Socket.emit (events.js:412:35)[39m
[31m    at Socket.emit (domain.js:475:12)[39m
[31m    at endReadableNT (internal/streams/readable.js:1334:12)[39m
[31m    at processTicksAndRejections (internal/process/task_queues.js:82:21)[39m
[2-1] Save a screenshot
[0-7] [31mError[39m in "0: Given I open the url "https://intescia--indemo.lightning.force.com/lightning/r/Quote/0Q06s000000Gq5iCAC/view""
[31mRequestError: socket hang up[39m
[31m    at ClientRequest.<anonymous> (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/got/dist/source/core/index.js:956:111)[39m
[31m    at Object.onceWrapper (events.js:520:26)[39m
[31m    at ClientRequest.emit (events.js:412:35)[39m
[31m    at ClientRequest.emit (domain.js:475:12)[39m
[31m    at ClientRequest.origin.emit (/builds/iqxxq76q/0/insight/quality/end-to-end-tests-wdio/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)[39m
[31m    at Socket.socketOnEnd (_http_client.js:499:9)[39m
[31m    at Socket.emit (events.js:412:35)[39m
[31m    at Socket.emit (domain.js:475:12)[39m
[31m    at endReadableNT (internal/streams/readable.js:1334:12)[39m
[31m    at connResetException (internal/errors.js:639:14)[39m
[31m    at Socket.socketOnEnd (_http_client.js:499:23)[39m
[31m    at Socket.emit (events.js:412:35)[39m
[31m    at Socket.emit (domain.js:475:12)[39m
[31m    at endReadableNT (internal/streams/readable.js:1334:12)[39m
[31m    at processTicksAndRejections (internal/process/task_queues.js:82:21)[39m
[0-7] Save a screenshot
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Are you sure it happens when updating from exact `7.16.3` to `7.16.4.`? It is really hard to say if and how this is related to WebdriverIO. There is nothing really we can do to investigate so we kind of depend on your investigation. We are happy to work on any fixes you propose.

**Comment by lacell75** [comment]
Issue fixes with async mode. I migrated all js in async and issue is not reproduced

**Comment by lacell75** [comment]
I close this issue. I increase memory and CPU from gitlab runner
