### ISSUE TITLE
[🐛 Bug]: cannot run on macOS Monterey

### ISSUE THREAD

**Issue by nonopolarity** [webdriverio/webdriverio#7702]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16

### Mode

WDIO Testrunner

### What happened?

I am following everything everything on your page for a simple project...
On macOS Big Sur, it runs well, but on macOS Monterey, I have been getting:

```bash
$ npm run wdio

> webdriverio-tests@0.1.0 wdio
> wdio run wdio.conf.js


Execution of 5 workers started at 2021-11-15T18:41:44.363Z

2021-11-15T18:41:44.380Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-11-15T18:41:44.381Z INFO chromedriver: Start Chromedriver (/Users/theusername/code/TryWDIO02/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2021-11-15T18:41:44.384Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at spawn (node:child_process:698:9)
    at ChromeDriverLauncher.onPrepare (/Users/theusername/code/TryWDIO02/node_modules/wdio-chromedriver-service/build/launcher.js:84:45)
    at /Users/theusername/code/TryWDIO02/node_modules/@wdio/cli/build/utils.js:28:40
    at Array.map (<anonymous>)
    at runServiceHook (/Users/theusername/code/TryWDIO02/node_modules/@wdio/cli/build/utils.js:25:33)
    at Launcher.run (/Users/theusername/code/TryWDIO02/node_modules/@wdio/cli/build/launcher.js:86:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Continue...
2021-11-15T18:41:44.386Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-11-15T18:41:44.386Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-11-15T18:41:44.386Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js
2021-11-15T18:41:44.390Z INFO @wdio/local-runner: Start worker 0-1 with arg: run,wdio.conf.js
```

### What is your expected behavior?

that it runs

### How to reproduce the bug.

see above

### Relevant log output

```typescript
see above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> I am following everything on your page for a simple project...

Are you saying you were running `npm create wdio /some/path`?

> ```shell
> Error: spawn Unknown system error -86
> ```

The error says you are trying to run Chromedriver x86 even though your are on the new M1 chip correct?

**Comment by christian-bromann** [comment]
I can't reproduce this with the latest version of WebdriverIO and `wdio-chromedriver-service`.
