### ISSUE TITLE
[🐛 Bug]: browser.getMetrics is not a function/Docs on https://webdriver.io/docs/devtools-service/ not working

### ISSUE THREAD

**Issue by 0Leon0** [webdriverio/webdriverio#7778]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.10

### Node.js Version

17.2.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    "name": "webdriverio-tests",
    "version": "0.1.0",
    "private": true,
    "devDependencies": {
        "@wdio/allure-reporter": "^7.16.10",
        "@wdio/cli": "^7.16.10",
        "@wdio/devtools-service": "^7.16.10",
        "@wdio/local-runner": "^7.16.10",
        "@wdio/mocha-framework": "^7.16.6",
        "@wdio/spec-reporter": "^7.16.9",
        "chromedriver": "^96.0.0",
        "wdio-chromedriver-service": "^7.2.2",
        "wdio-video-reporter": "^3.1.3"
    },
    "scripts": {
        "wdio": "wdio run wdio.conf.js"
    }
}

exports.config = {

    specs: [
        './test/specs/**/*.js'
    ],

    exclude: [
    ],

    maxInstances: 10,

    capabilities: [{

        maxInstances: 5,

        browserName: 'chrome',
        acceptInsecureCerts: true

    }],

    logLevel: 'info',

    bail: 0,

    baseUrl: 'http://localhost',

    waitforTimeout: 10000,

    connectionRetryTimeout: 120000,

    connectionRetryCount: 3,

    services: ['chromedriver','devtools'],

    framework: 'mocha',

    reporters: ['spec'],

    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
```

### What happened?

I tried to use the Devtools Service and followed the documentation on: https://webdriver.io/docs/devtools-service
I installed the @wdio/devtools-service service via: `npm install @wdio/devtools-service --save-dev`
and put it into the wdio.conf.js file as described in the docs.

I made a new file where i plugged all the code in and tryed to run it.

### What is your expected behavior?

It should run the code without a an error.

This:

`browser.getMetrics is not a function`

should not happen.

### How to reproduce the bug.

```
const assert = require('assert')

describe('JSON.org page', () => {
    before(() => {
        browser.enablePerformanceAudits()
    })

    it('should load within performance budget', () => {
        /**
         * this page load will take a bit longer as the DevTools service will
         * capture all metrics in the background
         */
        browser.url('http://json.org')

        let metrics = browser.getMetrics()
        assert.ok(metrics.speedIndex < 1500) // check that speedIndex is below 1.5ms

        let score = browser.getPerformanceScore() // get Lighthouse Performance score
        assert.ok(score >= .99) // Lighthouse Performance score is at 99% or higher

        $('=Esperanto').click()

        metrics = browser.getMetrics()
        assert.ok(metrics.speedIndex < 1500)
        score = browser.getPerformanceScore()
        assert.ok(score >= .99)
    })

    after(() => {
        browser.disablePerformanceAudits()
    })
})
```

### Relevant log output

```typescript
TypeError in "JSON.org page.should load within performance budget"
TypeError: browser.getMetrics is not a function
    at Context.<anonymous> (/home/ubuntu/Desktop/WebdriverIO/test_webdriver_linux/test/specs/sample.js:15:31)
    at Context.executeAsync (/home/ubuntu/Desktop/WebdriverIO/test_webdriver_linux/node_modules/@wdio/utils/build/shim.js:325:27)
    at Context.testFrameworkFnWrapper (/home/ubuntu/Desktop/WebdriverIO/test_webdriver_linux/node_modules/@wdio/utils/build/test-framework/testFnWrapper.js:45:32)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
The service documentation doesn't seem to have been updated to use async code examples.
If you are not specifically using sync mode (deprecated) then you should be adding async/await to your code, after doing so, can you let us know if the problem still exists?

**Comment by erwinheitzman** [comment]
Just ran this with with the example made async and it works fine (used the CLI to generate a new plain project for this which I always recommend doing):
```js
describe('JSON.org page', () => {
    before(async () => {
        await browser.enablePerformanceAudits()
    })

    it('should load within performance budget', async () => {
        /**
         * this page load will take a bit longer as the DevTools service will
         * capture all metrics in the background
         */
        await browser.url('http://json.org')

        let metrics = await browser.getMetrics()
        expect(metrics.speedIndex < 1500).toBe(true) // check that speedIndex is below 1.5ms

        let score = await browser.getPerformanceScore() // get Lighthouse Performance score
        expect(score >= .99).toBe(true) // Lighthouse Performance score is at 99% or higher

        await $('=Esperanto').click()

        metrics = await browser.getMetrics()
        expect(metrics.speedIndex < 1500).toBe(true)
        score = await browser.getPerformanceScore()
        expect(score >= .99).toBe(true) 
    })

    after(async () => {
        await browser.disablePerformanceAudits()
    })
})
```

**Comment by 0Leon0** [comment]
Can confirm, it works when you put it into async mode.

I tried only the getMetrics() and getPerformanceScore() commands.

```
describe('JSON.org page', () => {
    before( async () => {
        await browser.enablePerformanceAudits()
    })

    it('should load within performance budget', async() => {

        await browser.url('http://json.org')

        metrics = await browser.getMetrics()
        score = await browser.getPerformanceScore() 
    })

    after( async() => {
        await browser.disablePerformanceAudits()
    })
})
```

Another thing i noticed while tried i some things is that, if you use the video reporter it also tells you that `browser.getMetrics is not a function` for some reason.

**Comment by erwinheitzman** [comment]
You're right, I have been able to find out why this happens but would have to fix the reporter

**Comment by christian-bromann** [comment]
@erwinheitzman can we file an issue for this so we don't forget?`

**Comment by owens-ben** [comment]
I just ran into this issue with the video reporter too @erwinheitzman
