### ISSUE TITLE
[🐛 Bug]: @wdio/sauce-service is throwing updateJob error while updating the test results to Jenkins job

### ISSUE THREAD

**Issue by saranyaeaswaran** [webdriverio/webdriverio#7798]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

14.17.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{"browserName":"chrome","platformName":"macOS 10.14","browserVersion":"latest","sauce:options":{},"path":"/wd/hub"}

Sauce Options are,

{"sauceAgent":{"_events":{},"_eventsCount":0,"timeout":null,"maxFreeSockets":1,"maxSockets":1,"maxTotalSockets":null,"sockets":{},"freeSockets":{},"requests":{},"options":{},"secureProxy":false,"proxy":{"protocol":"http:","slashes":true,"auth":null,"host":"phxappgwe2-vip.phx.aexp.com","port":9090,"hostname":"phxappgwe2-vip.phx.aexp.com","hash":null,"search":null,"query":null,"href":"http://phxappgwe2-vip.phx.aexp.com:9090/"}},"hostname":"ondemand.saucelabs.com","services":[["sauce",{"setJobNameInBeforeSuite":true}]],"user":"xxxxxx","key":"xxxxxx","logLevel":"debug","updateJob":true,"commandTimeout":600,"idleTimeout":90,"maxDuration":10800}
```

### What happened?

Running the tests in Saucelabs from Jenkins is not not updating the test status back to Jenkins job but failing with timeout error, its waiting for around 6 minutes to pass the test result to the job and timing out. Please note that, this is working fine when Sauce is invoked from local but occurs only when invoked from Jenkins.

    "@wdio/cli": "^7.2.3",
    "@wdio/config": "^7.2.1",
    "@wdio/cucumber-framework": "^7.2.1",
    "@wdio/local-runner": "^7.2.3",
    "@wdio/sauce-service": "^7.16.10",

### What is your expected behavior?

Test status should be passed to Jenkins and thejob should be updated with test result.

### How to reproduce the bug.

To reproduce the bug, run tests in Saucelabs from Jenkins.

### Relevant log output

```typescript
[0-0] 2021-12-08T17:46:36.511Z INFO @wdio/sauce-service: Update job with sessionId ef82a431641a47418994a8c00f281b8d, status: passing
[0-0] 2021-12-08T17:46:37.917Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAABAAAAAJtCAYAAACopwI9AAABJmlDQ1BTa2lhA...
[0-0] 2021-12-08T17:53:01.244Z ERROR @wdio/utils:shim: Error: Failed calling updateJob: connect ETIMEDOUT xx.xx.xx.xxx:443, undefined
[0-0]     at SauceLabs._callAPI (/apps/amex/jenkins/workspace/DigitalAcquisitions/eapply-qa-australia/test-job/node_modules/saucelabs/build/index.js:582:13)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0]     at SauceService.updateJob (/apps/amex/jenkins/workspace/DigitalAcquisitions/eapply-qa-australia/test-job/node_modules/@wdio/sauce-service/build/service.js:282:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by saranyaeaswaran** [comment]
Another thing I noted is, the port 443 is not getting appended with the remote session to the saucelabs, due to this the job is failing? How to get this port number append to the session url as in - https://ondemand.saucelabs.com:443/wd/hub/session instead of https://ondemand.saucelabs.com/wd/hub/session
```
[0-0] 2021-12-10T11:01:32.264Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-12-10T11:01:32.265Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-12-10T11:01:32.270Z INFO webdriver: [POST] https://ondemand.saucelabs.com/wd/hub/session
[0-0] 2021-12-10T11:01:32.270Z INFO webdriver: DATA 
```

**Comment by christian-bromann** [comment]
@saranyaeaswaran can you provide a reproducible example?

**Comment by saranyaeaswaran** [comment]
Hi @christian-bromann , for the below sauce options, update job is redirecting us to the URL https://api.us-west-1.saucelabs.com/ instead of https://api.saucelabs.com/ due to which update job is failing for us. Any idea why it's redirecting to this URL?

        host: 'ondemand.saucelabs.com',
        services: ['sauce'],
        user: "xxxxxxx",
        key: "xxxxxxxxxx",

**Comment by wswebcreation** [comment]
Hi @saranyaeaswaran 

Can you share your config here?

@christian-bromann 
Is there a specific reason why the Sauce Service is using the API to update the job status, or can is also be done with the JS executor?

**Comment by saranyaeaswaran** [comment]
Hi @wswebcreation , Below are my sauce options configuration,
```
{"sauceAgent":{"_events":{},"_eventsCount":0,"timeout":null,"maxFreeSockets":1,"maxSockets":1,"maxTotalSockets":null,"sockets":{},"freeSockets":{},"requests":{},"options":{},"secureProxy":false,"proxy":{"protocol":"http:","slashes":true,"auth":null,"host":"xxxxxxxxxxxxxxxx","port":xxxx,"hostname":"xxxxxxxxxxxxxxxx","hash":null,"search":null,"query":null,"href":"xxxxxxxxxxxxxxxx"}},"hostname":"ondemand.saucelabs.com","services":["sauce"],"user":"xxxxxxx","key":"xxxxx"}
```
This is the URL its trying to connect when doing updateJob is https://api.us-west-1.saucelabs.com/rest/v1/node_js/jobs/<session_id> and its failing for me. 

I got this URL but providing a console.log statement in function ---  node_modules > saucelabs > build > index.js > _callAPI, after line number 570.

Below are the logs in Jenkins,
```
[0-0] 2021-12-14T07:41:48.148Z INFO @wdio/sauce-service: Update job with sessionId d1bca4f85651418a8ba1aebb869fxxxx, status: passing
[0-0] SauceOnDemandSessionID=d1bca4f85651418a8ba1aebb869fxxxx job-name=jenkins-xxxxxxxxxx
[0-0] 2021-12-14T07:41:48.953Z INFO webdriver: RESULT iVBORw0KGgoAAAANSUhEUgAABAAAAAJtCAYAAACopwI9AAABJmlDQ1BTa2lhA...
[0-0] 2021-12-14T07:48:13.003Z ERROR @wdio/utils:shim: Error: Failed calling updateJob: connect ETIMEDOUT 66.85.52.255:443, undefined
[0-0]     at SauceLabs._callAPI (/apps/amex/jenkins/workspace/DigitalAcquisitions/eapply-qa-australia/test-job/node_modules/saucelabs/build/index.js:582:13)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0]     at SauceService.updateJob (/apps/amex/jenkins/workspace/DigitalAcquisitions/eapply-qa-australia/test-job/node_modules/@wdio/sauce-service/build/service.js:286:9)
```

Please note that I'm using V7 for all services, my previous projects with V5 are working fine without any issues.
Thanks for your help with this.

**Comment by christian-bromann** [comment]
> Is there a specific reason why the Sauce Service is using the API to update the job status, or can is also be done with the JS executor?

JS Executor would work too.

**Comment by saranyaeaswaran** [comment]
Thanks @christian-bromann for your response, can you suggest what should I do now?

**Comment by christian-bromann** [comment]
@saranyaeaswaran I am not sure why the API call can't connect. AFAIK if a proxy is setup according to [the docs](https://webdriver.io/docs/proxy/) it should be able to connect. Any help on investigating the issue would be much appreciated.

**Comment by saranyaeaswaran** [comment]
Hi @christian-bromann , this is working fine after the proxy setup. Thanks so much for the suggestion. This issue can be closed as not an issue.
