### ISSUE TITLE
[🐛 Bug]: Can't start webdriverio project with TypeScript

### ISSUE THREAD

**Issue by Lucasmiguelmac** [webdriverio/webdriverio#7849]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

14.15.1

### Mode

WDIO Testrunner

### What happened?

Following the docs instructions, I followed this steps:
- Installed wdio cli running `npm i --save-dev @wdio/cli`
- Ran `npx wdio config -y`
- Added `"node", "webdriverio/async", "@wdio/mocha-framework", "expect-webdriverio"` to `tsconfig.json` > `"compilerOptions"` > `"types"`
- Ran `npx wdio run wdio.conf.ts` and the following error happened
![image](https://user-images.githubusercontent.com/49038881/147423659-2fe5f1c8-ec42-4f64-952c-2274ef9d1601.png)

### What is your expected behavior?

I expected the tests included in the conf step to run.

### How to reproduce the bug.

```sh
npm i --save-dev @wdio/cli && npx wdio config -y
```

Include `"node", "webdriverio/async", "@wdio/mocha-framework", "expect-webdriverio"` in your `tsconfig.json` file. Mine ended up looking like this:

```json
{
  "extends": "@tsconfig/svelte/tsconfig.json",
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "types": ["vite/client", "svelte", "node", "webdriverio/async", "@wdio/mocha-framework", "expect-webdriverio"]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.svelte",
    "src/main.js"
  ]
}

```

Try running the tests

```sh
npx wdio run wdio.conf.ts
```

See the error:
![image](https://user-images.githubusercontent.com/49038881/147423985-252facc0-dcca-44f1-82fe-098656f41d36.png)

### Relevant log output

```typescript
2021-12-27T00:45:05.948Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: /home/lucas/Dropbox/Programming/Projects/pomoly/web-app/wdio.conf.ts: Unexpected token 'export'
wdio run <configPath>

Run your WDIO configuration file to initialize your tests. (default)

Options:
      --version             Show version number                        [boolean]
      --watch               Run WebdriverIO in watch mode              [boolean]
  -h, -h, --hostname        automation driver host address              [string]
  -p, -p, --port            automation driver port                      [number]
      --path                path to WebDriver endpoints (default "/")   [string]
  -u, -u, --user            username if using a cloud service as automation
                            backend                                     [string]
  -k, -k, --key             corresponding access key to the user        [string]
  -l, -l, --logLevel        level of logging verbosity
         [choices: "trace", "debug", "info", "warn", "error", "silent", "trace",
                                     "debug", "info", "warn", "error", "silent"]
      --bail                stop test runner after specific amount of tests have
                            failed                                      [number]
      --baseUrl             shorten url command calls by setting a base url
                                                                        [string]
  -w, -w, --waitforTimeout  timeout for all waitForXXX commands         [number]
  -f, -f, --framework       defines the framework (Mocha, Jasmine or Cucumber)
                            to run the specs                            [string]
  -r, -r, --reporters       reporters to print out the results on stdout [array]
      --suite               overwrites the specs attribute and runs the defined
                            suite                                        [array]
      --spec                run only a certain spec file - overrides specs piped
                            from stdin                                   [array]
      --exclude             exclude certain spec file from the test run -
                            overrides exclude piped from stdin           [array]
      --mochaOpts           Mocha options
      --jasmineOpts         Jasmine options
      --cucumberOpts        Cucumber options
      --autoCompileOpts     Auto compilation options
      --help                Show help                                  [boolean]

Examples:
  wdio run wdio.conf.js --suite foobar      Run suite on testsuite "foobar"
  wdio run wdio.conf.js --spec              Run suite on specific specs
  ./tests/e2e/a.js --spec ./tests/e2e/b.js
  wdio run wdio.conf.js                     Run suite with custom Mocha timeout
  --mochaOpts.timeout 60000
  wdio run wdio.conf.js                     Disable auto-loading of ts-node or
  --autoCompileOpts.autoCompile=false       @babel/register
  wdio run wdio.conf.js                     Run suite with ts-node using custom
  --autoCompileOpts.tsNodeOpts.project=con  tsconfig.json
  figs/bdd-tsconfig.json

Documentation: https://webdriver.io
@wdio/cli (v7.16.12)

/home/lucas/Dropbox/Programming/Projects/pomoly/web-app/wdio.conf.ts:1
export const config = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module.m._compile (/home/lucas/Dropbox/Programming/Projects/pomoly/web-app/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/home/lucas/Dropbox/Programming/Projects/pomoly/web-app/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at FileSystemPathService.loadFile (/home/lucas/Dropbox/Programming/Projects/pomoly/web-app/node_modules/@wdio/config/build/lib/FileSystemPathService.js:21:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
It seems that your tsconfig is misconfigured. With a standard config, it works without problems:

```json
{
    "compilerOptions": {
        "types": [
            "node",
            "webdriverio/async",
            "@wdio/mocha-framework",
            "expect-webdriverio"
        ],
        "target": "ES5"
    }
}
```
If you change your `target` configuration it should work as well. Let me know if you need any further assistance.
