### ISSUE TITLE
[🐛 Bug]: Global Variable not being set through cmd when running tests

### ISSUE THREAD

**Issue by wbigno** [webdriverio/webdriverio#7868]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7.16

### Node.js Version

v10

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
browserName: 'chrome',
        'goog:chromeOptions': {
            args: ['--disable-infobars', '--window-size=1920,1440'],
            prefs: {'download.default_directory': 'C:\\Users\\Administrator\\Downloads'}
        }
```

### What happened?

I updated to v7 recently and when I did the baseUrl that I was setting dynamically is no longer working. 

### What is your expected behavior?

baseUrl should be set in the cmd when spec file is started.

### How to reproduce the bug.

In my wdio config file I have this referenced

```js
// set base url to local host by default
let baseUrl = 'https://localhost'

// Set up Enviroments for non-prod and prod testing through environemntal variables
if(process.env.DOMAIN === 'dev_site') {
    baseUrl = 'https://dev.d1e.website.com'
}
if(process.env.DOMAIN === 'int_site') {
    baseUrl = 'https://int.d1e.website.com'
}
```
Then  I also list  in the wdio config
```js
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: baseUrl,
```

and in my wdio before hook I set it like this
```
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    before: function (capabilities, specs) {
        global.baseUrl = baseUrl;
```

then in my cmd I set the baseUrl like this

set DOMAIN=dev_site&&npm run test.local

### Relevant log output

```typescript
> nyl-aem-automation@1.0.0 test.local C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION
> npx wdio wdio.conf.js


Execution of 1 workers started at 2022-01-03T10:53:38.396Z

[0-0]
[0-0]
[0-0]
[0-0] ##############################
[0-0] !!CLEARING!!
[0-0] ##############################
[0-0]
[0-0]
[0-0]
[0-0] RUNNING in chrome - C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\beta-hero-visual-regression.spec.js
[0-0]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\beta-hero-visual-regression.spec.js
Error: ReferenceError: baseUrl is not defined
    at Object.<anonymous> (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\/beta-hero-visual-regression.spec.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._compile (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .js] (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.implementationOfRequireOrImportForUnstableEsm [as requireOrImport] (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\node_modules\mocha\lib\nodejs\esm-utils.js:101:12)
[0-0] FAILED in chrome - C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\beta-hero-visual-regression.spec.js

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:16

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nyl-aem-automation@1.0.0 test.local: `npx wdio wdio.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nyl-aem-automation@1.0.0 test.local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\T85KZFL\AppData\Roaming\npm-cache\_logs\2022-01-03T10_53_55_718Z-debug.log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
You can access the baseUrl you are using via `browser.config.baseUrl`. Read more on this here: https://webdriver.io/docs/browserobject#custom-configurations. 

Let me know if you have any further questions.

**Comment by wbigno** [comment]
So can we no longer use global explicitly? Do we now need to call them via browser.config? Is this a change with v7 over how we called these global variables in v6?

Thanks

**Comment by wbigno** [comment]
@christian-bromann  so douse the3 baseUrl no longer prepend urls as it did previously when set in the wdio? Just trying to understand how we can set this up as previously we just had baseUrl: baseUrl in the wdio config and then could set it dynamically by using some if statements in the wdio config file just outside of the export block, and then set it as a global in the before hook. Is this no longer an options? do we really have to call this in every spec file separately? thanks
