### ISSUE TITLE
[🐛 Bug]: Could not specify custom hostname and port for driver

### ISSUE THREAD

**Issue by Dubrzr** [webdriverio/webdriverio#7921]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.13

### Node.js Version

16.13.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
maxInstances: 1,
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
            args: [
                '--no-sandbox',
                '--disable-infobars',
                '--headless',
                '--disable-gpu',
                '--window-size=1440,735'
            ],
        }
}
```

### What happened?

When specifying custom hostname and port to webdriverio cli it doesn't take them into account: 

```
wdio wdio.conf.js --suite Generics --suite HomePage --suite MyPatients --suite Requests "--hostname myremotehost --port 4242
```

I get an error saying that wdio could not connect to "127.0.0.1:9515": 

```
> wdio wdio.conf.js --suite Generics --suite HomePage --suite MyPatients --suite Requests "--hostname" "selenium__standalone-chrome" "--port" "4242"
Execution of 1 workers started at 2022-01-14T11:26:24.536Z
2022-01-14T11:26:34.575Z ERROR @wdio/cli:utils: A service failed in the 'onPrepare' hook
Error: timeout
    at Timeout.timeoutFunc (/builds/F4G1Zzr5/0/dev/cohort360/intergration-tests/node_modules/tcp-port-used/index.js:204:25)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Continue...
[0-0] RUNNING in chrome - /test/specs/generics/cohort360-SCG01-LeftMenu.js
[0-0] 2022-01-14T11:26:35.379Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:9515
[0-0]     at ClientRequest.<anonymous> (/builds/F4G1Zzr5/0/dev/cohort360/intergration-tests/node_modules/got/dist/source/core/index.js:956:111)
[0-0]     at Object.onceWrapper (node:events:510:26)
[0-0]     at ClientRequest.emit (node:events:402:35)
[0-0]     at ClientRequest.emit (node:domain:475:12)
[0-0]     at ClientRequest.origin.emit (/builds/F4G1Zzr5/0/dev/cohort360/intergration-tests/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[0-0]     at Socket.socketErrorListener (node:_http_client:447:9)
[0-0]     at Socket.emit (node:events:390:28)
[0-0]     at Socket.emit (node:domain:475:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:157:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
[0-0] 2022-01-14T11:26:35.380Z ERROR @wdio/runner: Error: Failed to create session.
```

I tried to specify it directy in  wdio.conf.js but it doesn't work either : 

```
```javascript

exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
    // on a remote machine).
    runner: 'local',
    hostname: 'myremotehost',
    port: 4242,
    path: '/',
    protocol: 'https',
   [...]
```

I tried to search online for a solution, I found a stackoverflow without any solution since May 2020 : https://stackoverflow.com/questions/61718292/webdriverio-selenium-standalone-service-v6-onwards-unable-to-overwrite-the-hos 

And tried the answer, moving 

```
    hostname: 'myremotehost',
    port: 4242,
    path: '/',
    protocol: 'https',
```

to capabilities but it doesn't work either.

I wondered if maybe my wdio was not using my "wdio.conf.js" file but it's using it since when I modify other variables, this is taken into account and has an impact.

I found the detectBackend function that seems to fill variables, but could not find where it is called, neither with what input : 

https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/utils/detectBackend.ts#L47

Could you please help us?
This seems an important bug!

Thanks you!

### How to reproduce the bug.

This is in the "what happened"

### Relevant log output

```typescript
This is in the "what happened"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> I found the detectBackend function that seems to fill variables, but could not find where it is called, neither with what input

Can you add some `console.log` in that function to see which values are passed in?
