### ISSUE TITLE
[🐛 Bug]: New command error 'Can't find variable: __awaiter'

### ISSUE THREAD

**Issue by Betwayqa-techtest** [webdriverio/webdriverio#7979]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### What happened?

I'm trying to add a new click method but when ever I use that method I'm getting a weird error. `WebDriver Error: An unknown server-side error occurred while processing the command. Original error: Can't find variable: __awaiter`. I'm not sure if i'm doing anything wrong  - I've read the documentation and gone through a few examples however I'd appreciate a helping hand 

usage:
`(await this.loginButton).newClick();`

wdio.conf.ts
````
....} as WebdriverIO.CucumberOpts,

  before: function async(capabilities, specs) {
    browser.addCommand("newClick", async function (origClickFunction, {}) {
        if (process.env.PLATFORM.toLowerCase() != "ios") {
          try {
            // attempt to click
            return origClickFunction();
          } catch (err) {
            if (err.message.includes("not clickable at point")) {
              console.warn(
                "WARN: Element",
                this.selector,
                "is not clickable.",
                "Scrolling to it before clicking again."
              );

              // scroll to element and click again
              await this.scrollIntoView();
              return origClickFunction();
            }
            throw err;
          }
        }
        await browser.execute(async (el) => {
          var header = await iosHelper._iosHeader;
          let button = await el;
          var x = await button.getLocation("x");
          var y = await button.getLocation("y");
          await waitHelper.checkPromise(5);
          await iosHelper.SwitchContext("native");
          await waitHelper.checkPromise(10);
          await driver.touchAction({action: "tap", x: x + 5, y: y + header + 5, });
          await iosHelper.SwitchContext("web");
        }, this);
      },
      true
    );
  },
};
````

wdio.d.ts
````declare module WebdriverIO {
    interface Element {
        newClick: () => void
    }
}````

### What is your expected behavior?

_No response_

### How to reproduce the bug.

-

### Relevant log output

```typescript
[0-0] 2022-02-04T16:38:52.938Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2022-02-04T16:38:52.939Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/e4d78c15-1d1d-4717-a166-496b2c2c767b/execute/sync
[0-0] 2022-02-04T16:38:52.939Z INFO webdriver: DATA {
[0-0]   script: 'return (function (el) { return __awaiter(_this, void 0, void 0, function () {\r\n' +
[0-0]     '                                var header, button, x, y;\r\n' +
[0-0]     '                                return __generator(this, function (_a) {\r\n' +
[0-0]     '                                    switch (_a.label) {\r\n' +
[0-0]     '                                        case 0:\r\n' +
[0-0]     '                                            console.log("ARGHHHHHH3");\r\n' +
[0-0]     '                                            return [4 /*yield*/, ios_helper_1.iosHelper._iosHeader];\r\n' +     
[0-0]     '                                        case 1:\r\n' +
[0-0]     '                                            header = _a.sent();\r\n' +
[0-0]     '                                            return [4 /*yield*/, el];\r\n' +
[0-0]     '                                        case 2:\r\n' +
[0-0]     '                                            button = _a.sent();\r\n' +
[0-0]     '                                            return [4 /*yield*/, button.getLocation("x")];\r\n' +
[0-0]     '                                        case 3:\r\n' +
[0-0]     '                                            x = _a.sent();\r\n' +
[0-0]     '                                            return [4 /*yield*/, button.getLocation("y")];\r\n' +
[0-0]     '                                        case 4:\r\n' +
[0-0]     '                                            y = _a.sent();\r\n' +
[0-0]     '                                            return [4 /*yield*/, wait_helper_1.waitHelper.checkPromise(5)];\r\n' +
[0-0]     '                                        case 5:\r\n' +
[0-0]     '                                            _a.sent();\r\n' +
[0-0]     '                                            return [4 /*yield*/, ios_helper_1.iosHelper.SwitchContext("native")];\r\n' +
[0-0]     '                                        case 6:\r\n' +
[0-0]     '                                            _a.sent();\r\n' +
[0-0]     '                                            return [4 /*yield*/, wait_helper_1.waitHelper.checkPromise(10)];\r\n' +
[0-0]     '                                        case 7:\r\n' +
[0-0]     '                                            _a.sent();\r\n' +
[0-0]     '                                            return [4 /*yield*/, driver.touchAction({\r\n' +
[0-0]     '                                                    action: "tap",\r\n' +
[0-0]     '                                                    x: x + 5,\r\n' +
[0-0]     '                                                    y: y + header + 5,\r\n' +
[0-0]     '                                                })];\r\n' +
[0-0]     '                                        case 8:\r\n' +
[0-0]     '                                            _a.sent();\r\n' +
[0-0]     '                                            return [4 /*yield*/, ios_helper_1.iosHelper.SwitchContext("web")];\r\n' +
[0-0]     '                                        case 9:\r\n' +
[0-0]     '                                            _a.sent();\r\n' +
[0-0]     '                                            return [2 /*return*/];\r\n' +
[0-0]     '                                    }\r\n' +
[0-0]     '                                });\r\n' +
[0-0]     '                            }); }).apply(null, arguments)',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': ':wdc:1643992732955',
[0-0]       ELEMENT: ':wdc:1643992732955'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2022-02-04T16:38:53.024Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': ':wdc:1643992732955',
[0-0]   ELEMENT: ':wdc:1643992732955'
[0-0] }
[0-0] 2022-02-04T16:38:53.030Z INFO webdriver: COMMAND elementClick(":wdc:1643992732955")
[0-0] 2022-02-04T16:38:53.030Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session/e4d78c15-1d1d-4717-a166-496b2c2c767b/element/%3Awdc%3A1643992732955/click
[0-0] 2022-02-04T16:38:54.093Z ERROR webdriver: Request failed with status 500 due to WebDriver Error: An unknown server-side error occurred while processing the command. Original error: Can't find variable: __awaiter
[0-0] Error in "0: Given I am on the --sports app"
WebDriver Error: An unknown server-side error occurred while processing the command. Original error: Can't find variable: __awaiter
    at getErrorFromResponseBody (C:\Repos\wdio-mobile-framework\node_modules\webdriver\build\utils.js:196:12)
    at NodeJSRequest._request (C:\Repos\wdio-mobile-framework\node_modules\webdriver\build\request\index.js:157:60)        
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Browser.wrapCommandFn (C:\Repos\wdio-mobile-framework\node_modules\@wdio\utils\build\shim.js:131:29)
    at async Browser.wrapCommandFn (C:\Repos\wdio-mobile-framework\node_modules\@wdio\utils\build\shim.js:131:29)
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
This code:

```ts
        await browser.execute(async (el) => {
          var header = await iosHelper._iosHeader;
          let button = await el;
          var x = await button.getLocation("x");
          var y = await button.getLocation("y");
          await waitHelper.checkPromise(5);
          await iosHelper.SwitchContext("native");
          await waitHelper.checkPromise(10);
          await driver.touchAction({action: "tap", x: x + 5, y: y + header + 5, });
          await iosHelper.SwitchContext("web");
        }, this);
```

is incorrect. You need to run the [`driverScript`](https://webdriver.io/docs/api/appium#driverscript) command to execute WebdriverIO code in the Appium server. Furthermore make sure you have the compiler transpile the script, e.g. by putting it into a module that is being ignored by it.
