### ISSUE TITLE
browser.maximizeWindow() is not working for Chrome: 98.0.4758.102

### ISSUE THREAD

**Issue by arunavachatterjee2021** [webdriverio/webdriverio#8019]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

12.20.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
"selenium-standalone": "^6.23.0",
```

### What happened?

Chrome browser not getting maximized using the command: browser.maximizeWindow()

  duration: 5677000000,
  status: 'failed',
  exception: Error: Command "maximizeWindow" is not yet implemented

### What is your expected behavior?

Browser should get maximized using the command: browser.maximizeWindow()

### How to reproduce the bug.

browser.url('https://amazon.com')
browser.maximizeWindow()

### Relevant log output

```typescript
Chrome browser not getting maximized using the command: browser.maximizeWindow()

  duration: 5677000000,
  status: 'failed',
  exception: Error: Command "maximizeWindow" is not yet implemented
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide some WebdriverIO logs?

> ```ts
>  exception: Error: Command "maximizeWindow" is not yet implemented
> ```

Based on this I suspect you are not using WebDriver but the devtools protocol.

**Comment by tobeliketree** [comment]
We are seeing this too in our repo.  The browser.maximizeWindow() is in the config before hook.  

[0-0] 2022-02-28T17:39:46.804Z ERROR @wdio/sync: Error: Command "maximizeWindow" is not yet implemented
[0-0]     at Browser.retries (/Users/unicorn/Git_Repositories/ui/node_modules/devtools/build/devtoolsdriver.js:63:34)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-0]     at Object.before (/Users/unicorn/Git_Repositories/ui/config/wdio.conf.js:207:17)
