### ISSUE TITLE
[🐛 Bug]: java.net.UnknownHostException: <my operative system> when trying to open allure report

### ISSUE THREAD

**Issue by Lucasmiguelmac** [webdriverio/webdriverio#8031]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.15

### Node.js Version

v14.15.1

### Mode

Standalone Mode

### What happened?

Got the following traceback when running allure open:

java.net.UnknownHostException: artixlinux: artixlinux: Name or service not known

### How to reproduce the bug.

1. Generate a report (ie: running `allure generate`)
2. Run `allure open`
3. See the traceback

### Relevant log output

```typescript
Starting web server...
2022-02-20 14:46:23.526:INFO::main: Logging initialized @380ms to org.eclipse.jetty.util.log.StdErrLog
2022-02-20 14:46:23.647:WARN:oejs.Server:main: 
java.net.UnknownHostException: artixlinux: artixlinux: Name or service not known
        at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1647)
        at org.eclipse.jetty.server.Server.getURI(Server.java:668)
        at io.qameta.allure.Commands.open(Commands.java:151)
        at io.qameta.allure.CommandLine.run(CommandLine.java:173)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.qameta.allure.CommandLine.main(CommandLine.java:92)
Caused by: 
java.net.UnknownHostException: artixlinux: Name or service not known
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
        at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1642)
        at org.eclipse.jetty.server.Server.getURI(Server.java:668)
        at io.qameta.allure.Commands.open(Commands.java:151)
        at io.qameta.allure.CommandLine.run(CommandLine.java:173)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.qameta.allure.CommandLine.main(CommandLine.java:92)
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.desktop/java.awt.Desktop.browse(Desktop.java:532)
        at io.qameta.allure.Commands.openBrowser(Commands.java:220)
        at io.qameta.allure.Commands.open(Commands.java:151)
        at io.qameta.allure.CommandLine.run(CommandLine.java:173)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.qameta.allure.CommandLine.main(CommandLine.java:92)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@Lucasmiguelmac please report this issue in the [Allure project](https://github.com/allure-framework/allure2). I don't see how this is related to WebdriverIO. Thanks!
