### ISSUE TITLE
[🐛 Bug]: Converting visual regression test to async

### ISSUE THREAD

**Issue by wbigno** [webdriverio/webdriverio#8098]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

6.4

### Node.js Version

12.18

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
 
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        //maxInstances: 10,
        //
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: ['--disable-infobars', '--window-size=1920,1440'],
            prefs: {'download.default_directory': 'C:\\Users\\Administrator\\Downloads'}
        }
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
```

### What happened?

updated framework to run async test along with sync test as we work to migrate over to async on all test. Having an issue specifically with the browser.checkElement used for the visual regression. Have tried many variations of adding the await before the function and or the selector and it just keeps throwing different errors. We have been successful on many of our other tests, but this function is not working.

Script: 
describe('401k retirement Calculator Visual Valdation Mobile', () => {
        before(async () => {
            await calculator.openTest();
            await utilities.responsiveBreakpointsAsync('MOBILE');
            await browser.pause(4000);
        });
 
        it.only('should compare current 401k Retirement Calculator landing page image with a baseline Compare Mobile Viewport', async () => {
            await expects(
                browser.checkElement(container.calculatorComponent[0],
                    '401k Retirement Calculator Landing Page-Mobile',{
                    fullPageScrollTimeout: '10000',
                }),
                ).to.be.below(0.1);
        });
 
 
 
/**
* Get the css selector for element.
* @return {object} returns selector for element.
*/
get calculatorComponent() {
return $$('.cmp-calculator-container');
}
 

package.json:
"devDependencies": {
    "@babel/polyfill": "^7.12.1",
    "@babel/cli": "^7.17.6",
    "@babel/core": "^7.17.5",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/preset-env": "^7.16.11",
    "@babel/register": "^7.17.0",
    "@wdio/allure-reporter": "^6.3.6",
    "@wdio/cli": "^6.4.0",
    "@wdio/devtools-service": "^6.4.0",
    "@wdio/junit-reporter": "^6.4.0",
    "@wdio/local-runner": "^6.4.0",
    "@wdio/mocha-framework": "^6.4.0",
    "@wdio/sauce-service": "^6.4.0",
    "@wdio/spec-reporter": "^6.4.0",
    "@wdio/sync": "^6.4.0",
    "allure-commandline": "^2.13.0",
    "babel-eslint": "^10.1.0",
    "chai": "^4.2.0",
    "chai-html": "^1.3.0",
    "chai-match-pattern": "^1.2.0",
    "chromedriver": "^80.0.2",
    "eslint": "^6.8.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-mocha": "^6.3.0",
    "global-agent": "^2.1.12",
    "request-promise": "^4.2.6",
    "wdio-allure-reporter": "^0.8.3",
    "wdio-image-comparison-service": "^1.13.6",
    "webdriverio": "^6.4.0",
    "xml2js": "^0.4.23"
  },

### What is your expected behavior?

Test should run and produces compare a baseline image to the current image and validate it.

### How to reproduce the bug.

running script, 
we have tried it with both $$ and $ selectors to see if that was an issue.
we have tried various await set ups, such as 
1) await browser.checkElement(await $(selector),
2) await browser.checkElement((await component.selector)[0],
3) browser.checkElement(await $(selector),
4) browser.checkElement((await component.selector)[0],
5) browser.checkElement(component.selector[0],
6) browser.checkElement($(selector),

none of these work we either get the browser.checkElement is not a function or cannot read property of 'call' of undefined error on these.

### Relevant log output

```typescript
[0-0] TypeError in "401k retirement Calculator Visual Valdation Mobile should compare current 401k Retirement Calculator landing page image with a baseline Compare Mobile Viewport"
Cannot read property 'call' of undefined
[0-0] FAILED in chrome - C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\beta-calculator-401k-retirement-visual-regression.spec.js
 
"spec" Reporter:
------------------------------------------------------------------
[Chrome 97.0.4692.71 win32 #0-0] Spec: C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\beta-calculator-401k-retirement-visual-regression.spec.js
[Chrome 97.0.4692.71 win32 #0-0] Running: Chrome (v97.0.4692.71) on win32
[Chrome 97.0.4692.71 win32 #0-0] Session ID: 3606ad64-fa62-4275-8158-d997bbbb6d08
[Chrome 97.0.4692.71 win32 #0-0]
[Chrome 97.0.4692.71 win32 #0-0] 401k retirement Calculator Visual Valdation Mobile
[Chrome 97.0.4692.71 win32 #0-0]    ✖ should compare current 401k Retirement Calculator landing page image with a baseline Compare Mobile Viewport
[Chrome 97.0.4692.71 win32 #0-0]
[Chrome 97.0.4692.71 win32 #0-0] 1 failing (8.3s)
[Chrome 97.0.4692.71 win32 #0-0]
[Chrome 97.0.4692.71 win32 #0-0] 1) 401k retirement Calculator Visual Valdation Mobile should compare current 401k Retirement Calculator landing page image with a baseline Compare Mobile Viewport
[Chrome 97.0.4692.71 win32 #0-0] Cannot read property 'call' of undefined
[Chrome 97.0.4692.71 win32 #0-0] TypeError: Cannot read property 'call' of undefined
[Chrome 97.0.4692.71 win32 #0-0]     at _callee2$ (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\/beta-calculator-401k-retirement-visual-regression.spec.js:14:129)
[Chrome 97.0.4692.71 win32 #0-0]     at tryCatch (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\node_modules\regenerator-runtime\runtime.js:63:40)
[Chrome 97.0.4692.71 win32 #0-0]     at Generator.invoke [as _invoke] (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\node_modules\regenerator-runtime\runtime.js:294:22)
[Chrome 97.0.4692.71 win32 #0-0]     at Generator.next (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\node_modules\regenerator-runtime\runtime.js:119:21)
[Chrome 97.0.4692.71 win32 #0-0]     at asyncGeneratorStep (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\beta-calculator-401k-retirement-visual-regression.spec.js:9:103)
[Chrome 97.0.4692.71 win32 #0-0]     at _next (C:\Users\T85KZFL\nyl-aem-automation\NYL.AEM.AUTOMATION\test\specs\nyl\component\test\beta-calculator-401k-retirement-visual-regression.spec.js:11:194)
[Chrome 97.0.4692.71 win32 #0-0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
 
Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:34
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nyl-aem-automation@1.0.0 test.local: `npx wdio wdio.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nyl-aem-automation@1.0.0 test.local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\T85KZFL\AppData\Roaming\npm-cache\_logs\2022-03-11T10_04_13_664Z-debug.log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> 12.18

Please upgrade your Node.js version. WebdriverIO is not expected to work with Node.js v12 anymore.

I would expect your example to work with the following:

```ts
it.only('should compare current 401k Retirement Calculator landing page image with a baseline Compare Mobile Viewport', async () => {
    const elem = await container.calculatorComponent[0];
    const result = await browser.checkElement(
        elem,
        '401k Retirement Calculator Landing Page-Mobile',{
        fullPageScrollTimeout: '10000',
    });
    expects(result).to.be.below(0.1);
});
```

If not please provide a minimal reproducible example, thanks!

**Comment by christian-bromann** [comment]
Closing due to inactivity.
