### ISSUE TITLE
[🐛 Bug]: Stack trace is not showing proper failure lines for few scenarios

### ISSUE THREAD

**Issue by praveendvd** [webdriverio/webdriverio#8106]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.17.4

### Node.js Version

v16.5.0

### Mode

WDIO Testrunner

### What happened?

Stacktrace doesnt show line in spec at which the issue occured :  

### What is your expected behavior?

SHould throw stack trace like : 

```
[chrome 99.0.4844.51 windows #0-0] Error: not implemented
[chrome 99.0.4844.51 windows #0-0] Error: not implemented
[chrome 99.0.4844.51 windows #0-0]     at LoginPage.<anonymous> (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:29:15)
[chrome 99.0.4844.51 windows #0-0]     at step (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:48:23)
[chrome 99.0.4844.51 windows #0-0]     at Object.next (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:29:53)
[chrome 99.0.4844.51 windows #0-0]     at C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:23:71
[chrome 99.0.4844.51 windows #0-0]     at new Promise (<anonymous>)
[chrome 99.0.4844.51 windows #0-0]     at __awaiter (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:19:12)
[chrome 99.0.4844.51 windows #0-0]     at LoginPage.login (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:92:16)
[chrome 99.0.4844.51 windows #0-0]     at C:\Users\prave\Downloads\test\test\specs\example.e2e.ts:8:25
[chrome 99.0.4844.51 windows #0-0]     at step (C:\Users\prave\Downloads\test\test\specs\example.e2e.ts:33:23)
[chrome 99.0.4844.51 windows #0-0]     at Object.next (C:\Users\prave\Downloads\test\test\specs\example.e2e.ts:14:53)
```

showing line in spec that caused the issue

### How to reproduce the bug.

This is the custom typescript project created by wdio, i added a custom error in the **pageObjects/login.page.ts** : 

```
    /**
     * a method to encapsule automation code to interact with the page
     * e.g. to login using username and password
     */
    public async login (username: string, password: string) {
        await this.inputUsername.setValue(username);
        await this.inputPassword.setValue(password);
        await this.btnSubmit.click();
        throw Error('not implemented');
    }

```

**Project:**

[package.zip](https://github.com/webdriverio/webdriverio/files/8239303/package.zip)

**Throws the error :** 

```
[chrome 99.0.4844.51 windows #0-0] Error: not implemented
[chrome 99.0.4844.51 windows #0-0]     at LoginPage.<anonymous> (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:32:15)
[chrome 99.0.4844.51 windows #0-0]     at step (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:48:23)
[chrome 99.0.4844.51 windows #0-0]     at Object.next (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:29:53)
[chrome 99.0.4844.51 windows #0-0]     at fulfilled (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:20:58)
[chrome 99.0.4844.51 windows #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

IF throw error is at start , then it works as expected **pageObjects/login.page.ts** : 

```
    /**
     * a method to encapsule automation code to interact with the page
     * e.g. to login using username and password
     */
    public async login (username: string, password: string) {
        throw Error('not implemented');
        await this.inputUsername.setValue(username);
        await this.inputPassword.setValue(password);
        await this.btnSubmit.click();
    }

```

### Relevant log output

```typescript
Execution of 1 workers started at 2022-03-13T09:36:50.160Z

[0-0] RUNNING in chrome - C:\Users\prave\Downloads\test\test\specs\example.e2e.ts

DevTools listening on ws://127.0.0.1:54006/devtools/browser/b4620724-7a12-43a5-8035-5bf430d825dc
[0-0] Error in "My Login application should login with valid credentials"
Error: not implemented
    at LoginPage.<anonymous> (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:32:15)
    at step (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:48:23)
    at Object.next (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:29:53)
    at fulfilled (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] FAILED in chrome - C:\Users\prave\Downloads\test\test\specs\example.e2e.ts

 "spec" Reporter:
------------------------------------------------------------------
[chrome 99.0.4844.51 windows #0-0] Running: chrome (v99.0.4844.51) on windows
[chrome 99.0.4844.51 windows #0-0] Session ID: 4f8d1fd81098daa69518f20e28e38c9c
[chrome 99.0.4844.51 windows #0-0]
[chrome 99.0.4844.51 windows #0-0] » \test\specs\example.e2e.ts
[chrome 99.0.4844.51 windows #0-0] My Login application
[chrome 99.0.4844.51 windows #0-0]    ✖ should login with valid credentials
[chrome 99.0.4844.51 windows #0-0]
[chrome 99.0.4844.51 windows #0-0] 1 failing (2.1s)
[chrome 99.0.4844.51 windows #0-0]
[chrome 99.0.4844.51 windows #0-0] 1) My Login application should login with valid credentials
[chrome 99.0.4844.51 windows #0-0] Error: not implemented
[chrome 99.0.4844.51 windows #0-0] Error: not implemented
[chrome 99.0.4844.51 windows #0-0]     at LoginPage.<anonymous> (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:32:15)
[chrome 99.0.4844.51 windows #0-0]     at step (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:48:23)
[chrome 99.0.4844.51 windows #0-0]     at Object.next (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:29:53)
[chrome 99.0.4844.51 windows #0-0]     at fulfilled (C:\Users\prave\Downloads\test\test\pageobjects\login.page.ts:20:58)
[chrome 99.0.4844.51 windows #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
If I put the error at the end:
![Screenshot 2022-03-14 at 09 44 17](https://user-images.githubusercontent.com/731337/158136067-1580ea60-6809-4c5c-9e6d-6e14fc8c14d6.png)

I get this stack trace:
```
[0-0] Error in "My Login application.should login with valid credentials"
Error: not implemented
    at LoginPage.<anonymous> (/private/tmp/8108/test/pageobjects/login.page.ts:32:15)
    at step (/private/tmp/8108/test/pageobjects/login.page.ts:48:23)
    at Object.next (/private/tmp/8108/test/pageobjects/login.page.ts:29:53)
    at fulfilled (/private/tmp/8108/test/pageobjects/login.page.ts:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] FAILED in chrome - /test/specs/example.e2e.ts
```

if I put it at the beginning, e.g.:
![Screenshot 2022-03-14 at 09 45 12](https://user-images.githubusercontent.com/731337/158136218-57a85960-9e19-4746-917a-162731c14cbf.png)

I get the following:
```
[0-0] Error in "My Login application.should login with valid credentials"
Error: not implemented
    at LoginPage.<anonymous> (/private/tmp/8108/test/pageobjects/login.page.ts:29:15)
    at step (/private/tmp/8108/test/pageobjects/login.page.ts:48:23)
    at Object.next (/private/tmp/8108/test/pageobjects/login.page.ts:29:53)
    at /private/tmp/8108/test/pageobjects/login.page.ts:23:71
    at new Promise (<anonymous>)
    at __awaiter (/private/tmp/8108/test/pageobjects/login.page.ts:19:12)
    at LoginPage.login (/private/tmp/8108/test/pageobjects/login.page.ts:92:16)
    at /private/tmp/8108/test/specs/example.e2e.ts:8:25
    at step (/private/tmp/8108/test/specs/example.e2e.ts:33:23)
    at Object.next (/private/tmp/8108/test/specs/example.e2e.ts:14:53)
[0-0] FAILED in chrome - /test/specs/example.e2e.ts
```

Both seems to be correct for me. I am on Mac fyi.

**Comment by praveendvd** [comment]
@christian-bromann  have you tried the package.zip i attached with the issue ? i dont get this stack trace for that

**Comment by praveendvd** [comment]
i am using type script , tried with target es2019 and still same issue

**Comment by WillBrock** [comment]
@praveendvd I was able to get the correct stacktrace from your zip file

```js
[chrome 99.0.4844.74 linux #0-0] 1) My Login application should login with valid credentials
[chrome 99.0.4844.74 linux #0-0] Error: not implemented
[chrome 99.0.4844.74 linux #0-0] Error: not implemented
[chrome 99.0.4844.74 linux #0-0]     at LoginPage.login (/home/will/dev/prav-test/test/pageobjects/login.page.ts:32:15)
[chrome 99.0.4844.74 linux #0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[chrome 99.0.4844.74 linux #0-0]     at async UserContext.<anonymous> (/home/will/dev/prav-test/test/specs/example.e2e.ts:8:9)
```

**Comment by praveendvd** [comment]
@WillBrock 

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/45095911/159232851-08dbc324-1774-4568-9abc-2dd8602dceee.png">

This is the out put i get for both mac and windows , i am not sure why we all get 3 different behavior !!

**Comment by christian-bromann** [comment]
@praveendvd how do you think we should proceed with this?

**Comment by praveendvd** [comment]
@christian-bromann I will have a look this week , got busy . Thanks Christian
