### ISSUE TITLE
[🐛 Bug]: <title>

### ISSUE THREAD

**Issue by wbigno** [webdriverio/webdriverio#8150]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v7

### Node.js Version

v14.17

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
const chromeOptions = {
  'goog:chromeOptions': {
    'w3c': true,
    prefs: {
      'download.default_directory': "C:\\Users\\Administrator\\Downloads", 
      'download.prompt_for_download': false,
      'safebrowsing.enabled': true
    }
  },
};
```

### What happened?

Upgraded from v6 to v7, and upgraded from node v12 to v14 as we prepare to convert all of our scripts to async so we can run v16 of node later this year. Since pushing these change I am seeing an error in our Jenkins build that I do not get in my local test execution.

### What is your expected behavior?

Test suite should run as it did prior to upgrades.

### How to reproduce the bug.

package.json
"devDependencies": {
    "@babel/cli": "^7.17.6",
    "@babel/core": "^7.17.5",
    "@babel/preset-env": "^7.16.11",
    "@babel/register": "^7.17.0",
    "@babel/eslint-parser": "^7.17.0",
    "@wdio/allure-reporter": "^7.17.3",
    "@wdio/cli": "^7.17.4",
    "@wdio/devtools-service": "^7.17.4",
    "@wdio/junit-reporter": "^7.17.3",
    "@wdio/local-runner": "^7.17.4",
    "@wdio/mocha-framework": "^7.17.3",
    "@wdio/sauce-service": "^7.17.4",
    "@wdio/spec-reporter": "^7.17.3",
    "@wdio/sync": "^7.17.4",
    "wdio-image-comparison-service": "^1.13.6",
    "webdriverio": "^6.4.0",
    "allure-commandline": "^2.13.0",
    "chai": "^4.2.0",
    "chai-html": "^1.3.0",
    "chai-match-pattern": "^1.2.0",
    "chromedriver": "^99.0.0",
    "eslint": "^8.10.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-babel": "^5.3.1",
    "eslint-plugin-mocha": "^6.3.0",
    "global-agent": "^2.1.12",
    "request-promise": "^4.2.6",
    "request": "^2.34.0",
    "request-promise-core": "^1.1.4",
    "xml2js": "^0.4.23"
  }
wdio file
const sauceConfig = Object.assign(baseConfig, {

  protocol: 'http',
  user: sauce.user,
  key: sauce.key,
  logLevel: 'trace',
  maxInstances: 40,
  region: 'us',
  //
  // Test runner services
  // Services take over a specific job you don't want to take care of. They enhance
  // your test setup with almost no effort. Unlike plugins, they don't add new
  // commands. Instead, they hook themselves up into the test process.
  services: [
    ['sauce', {
      sauceConnect: true,
      sauceConnectOpts: {
      },
      setJobNameInBeforeSuite: true,
    }],
    ['image-comparison', {
      baselineFolder: join(process.cwd(), 'visual-regression/'),
      formatImageName: process.env.DOMAIN + '--{browserName}--{browserVersion}-{tag}',
      screenshotPath: join(process.cwd(), '.tmp/'),
      misMatchTolerance: 0.02,
      savePerInstance: true,
      autoSaveBaseline: true,
      blockOutStatusBar: true,
      blockOutToolBar: true,
    }],
  ],
  // If you have trouble getting all important capabilities together, check out the
  // Sauce Labs platform configurator - a great tool to configure your capabilities:
  // https://docs.saucelabs.com/reference/platforms-configurator
  //
  capabilities: [
    // maxInstances can get overwritten per capability. So if you have an in-house Selenium
    // grid with only 5 firefox instances available you can make sure that not more than
    // 5 instances get started at a time.
    { 'maxInstances': 40, 'browserName': 'googlechrome', 'platformName': 'Windows 10', 'browserVersion': 'latest',
      'sauce:options': {
        ...defaultWindowsBrowserSauceOptions,
      },
      ...chromeOptions,
    },

### Relevant log output

```typescript
2022-03-23T19:19:09.161Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
2022-03-23T19:19:09.407Z DEBUG @wdio/utils:initialiseServices: initialise service "image-comparison" as NPM package
2022-03-23T19:19:09.467Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "wdio-image-comparison-service".
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/canvas/build/Release/canvas.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/pirates/lib/index.js:141:7)
    at safeRequire (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/utils.js:187:15)
    at initialisePlugin (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/initialisePlugin.js:37:44)
    at initialiseServices (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/initialiseServices.js:59:56)
    at initialiseLauncherService (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/utils/build/initialiseServices.js:86:26)
    at Launcher.run (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/cli/build/launcher.js:73:103)
    at launch (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/cli/build/commands/run.js:126:21)
    at Object.handler (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/@wdio/cli/build/commands/run.js:164:16)
    at /prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/yargs/build/index.cjs:1:9054
    at j (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/prod/sys/ws/workspace/Martech/AEM Sites/Automation/INT-BETA-NYL-SAUCELABS-ANALYTICS/NYL.AEM.AUTOMATION/node_modules/yargs/build/index.cjs:1:9023)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> ```ts
> Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found
> ```

This doesn't seem to be related to WebdriverIO and more an issue of a dependency of `wdio-image-comparison-service`. Therefor I will close the issue.

@wswebcreation might be able to chime in here. I would guess that incompatibility with the [`canvas`](https://www.npmjs.com/package/canvas) package.

**Comment by wswebcreation** [comment]
Linked issue https://github.com/wswebcreation/wdio-image-comparison-service/issues/84
