### ISSUE TITLE
[🐛 Bug]: Unable to extend tsconfig to a base level tsconfig - results in "Unexpected token 'export'"

### ISSUE THREAD

**Issue by kerry-afs** [webdriverio/webdriverio#8155]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.1

### Node.js Version

16.14.2

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  maxInstances: 5,
  browserName: 'chrome',
  acceptInsecureCerts: true
}
```

### What happened?

I have created a `webdriverio` project in my `nx` monorepo.

I have attempted to extend the tsconfig to a base level tsconfig at the root of my monorepo. This is important when attempting to use shared functionality from libs in the monorepo and make use of the aliases vs using relative paths (i.e. importing modules using `import { someMethod } from '@testing'` vs `import { someMethod } from '../../../../../libs/testing/src/index'`)

However, when extending the tsconfig to a base level tsconfig file, we get the error when executing the tests:
```
ERROR @wdio/config:ConfigParser: Failed loading configuration file: /Users/<user>/my-sandbox/nx-webdriverio/apps/demo-e2e/wdio.conf.ts: Unexpected token 'export'
wdio run <configPath>

Run your WDIO configuration file to initialize your tests. (default)
```

### What is your expected behavior?

**Expected Behavior:**
We should be able to extend the tsconfig to a base level tsconfig. This is important when attempting to use shared functionality from libs in the monorepo and make use of the aliases vs using relative paths (i.e. importing modules using `import { someMethod } from '@testing'` vs `import { someMethod } from '../../../../../libs/testing/src/index'`)

**Actual Behavior**
When extending the tsconfig to a base level tsconfig file, we get the error:
```
ERROR @wdio/config:ConfigParser: Failed loading configuration file: /Users/<user>/my-sandbox/nx-webdriverio/apps/demo-e2e/wdio.conf.ts: Unexpected token 'export'
wdio run <configPath>

Run your WDIO configuration file to initialize your tests. (default)
```

### How to reproduce the bug.

There is a fully reproducible repo found here: https://github.com/kerry-afs/nx-webdriverio

**Steps to Reproduce:**
1. Clone the repo
2. Start Chromdriver service on port `4444`
3. Execute tests by running `npm run test` -> verify failure
4. Remove line 2 from `apps/demo-e2e/tsconfig.json` (i.e. `"extends": "../../tsconfig.base.json",`)
5. Execute tests by running `nom run test` -> verify tests run successfully

### Relevant log output

```typescript
ERROR @wdio/config:ConfigParser: Failed loading configuration file: /Users/<user>/my-sandbox/nx-webdriverio/apps/demo-e2e/wdio.conf.ts: Unexpected token 'export'
wdio run <configPath>

Run your WDIO configuration file to initialize your tests. (default)

Options:
      --version             Show version number                        [boolean]
      --watch               Run WebdriverIO in watch mode              [boolean]
  -h, -h, --hostname        automation driver host address              [string]
  -p, -p, --port            automation driver port                      [number]
      --path                path to WebDriver endpoints (default "/")   [string]
  -u, -u, --user            username if using a cloud service as automation
                            backend                                     [string]
  -k, -k, --key             corresponding access key to the user        [string]
  -l, -l, --logLevel        level of logging verbosity
         [choices: "trace", "debug", "info", "warn", "error", "silent", "trace",
                                     "debug", "info", "warn", "error", "silent"]
      --bail                stop test runner after specific amount of tests have
                            failed                                      [number]
      --baseUrl             shorten url command calls by setting a base url
                                                                        [string]
  -w, -w, --waitforTimeout  timeout for all waitForXXX commands         [number]
  -f, -f, --framework       defines the framework (Mocha, Jasmine or Cucumber)
                            to run the specs                            [string]
  -r, -r, --reporters       reporters to print out the results on stdout [array]
      --suite               overwrites the specs attribute and runs the defined
                            suite                                        [array]
      --spec                run only a certain spec file - overrides specs piped
                            from stdin                                   [array]
      --exclude             exclude certain spec file from the test run -
                            overrides exclude piped from stdin           [array]
      --mochaOpts           Mocha options
      --jasmineOpts         Jasmine options
      --cucumberOpts        Cucumber options
      --autoCompileOpts     Auto compilation options
      --help                Show help                                  [boolean]

Examples:
  wdio run wdio.conf.js --suite foobar      Run suite on testsuite "foobar"
  wdio run wdio.conf.js --spec              Run suite on specific specs
  ./tests/e2e/a.js --spec ./tests/e2e/b.js
  wdio run wdio.conf.js                     Run suite with custom Mocha timeout
  --mochaOpts.timeout 60000
  wdio run wdio.conf.js                     Disable auto-loading of ts-node or
  --autoCompileOpts.autoCompile=false       @babel/register
  wdio run wdio.conf.js                     Run suite with ts-node using custom
  --autoCompileOpts.tsNodeOpts.project=con  tsconfig.json
  figs/bdd-tsconfig.json

Documentation: https://webdriver.io
@wdio/cli (v7.19.1)

/Users/<user>/my-sandbox/nx-webdriverio/apps/demo-e2e/wdio.conf.ts:1
export const config = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Module.m._compile (/Users/<user>/my-sandbox/nx-webdriverio/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/<user>/my-sandbox/nx-webdriverio/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> 3\. Execute tests by running `npm run test` -> verify failure

Tests were passing for me after clone:

```
❯ g clone git@github.com:kerry-afs/nx-webdriverio.git
Cloning into 'nx-webdriverio'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 65 (delta 2), reused 61 (delta 1), pack-reused 0
Receiving objects: 100% (65/65), 290.05 KiB | 1.01 MiB/s, done.
Resolving deltas: 100% (2/2), done.
❯ cd nx-webdriverio/
❯ npm i
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated

> nx-webdriverio@0.0.0 postinstall
> node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main


 >  NX   Angular CLI has been decorated to enable computation caching.


added 1269 packages, and audited 1270 packages in 27s

135 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
❯ code .
❯ npm run test

> nx-webdriverio@0.0.0 test
> nx test


> nx run demo:test

 PASS   demo  apps/demo/src/app/app.component.spec.ts
  AppComponent
    ✓ should create the app (67 ms)
    ✓ should have as title 'demo' (11 ms)
    ✓ should render title (12 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.892 s
Ran all test suites.

 >  NX   Successfully ran target test for project demo (3s)
```

I also don't see any WebdriverIO config file in the repository. So unable to reproduce this problem. Closing.

**Comment by kerry-afs** [comment]
@christian-bromann apologies, for some reason my WDIO files did not commit to the repository. I have updated it and the issue remains. Can you please revisit?

https://github.com/kerry-afs/nx-webdriverio

**Comment by kerry-afs** [comment]
Thank you @christian-bromann , that helped me move forward. However, I am now experiencing an issue with the actual import of a module from my `lib/testing` library, and have committed to the repository the test that fails on this import.

I would ask in the supplied gitter, but I am not entirely clear if this is a TS configuration issue or an issue that's appropriate here. Apologies in advance if this is not an issue, and I really appreciate your help and insight!

Error message:
```
2022-03-29T17:39:43.286Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-03-29T17:39:43.287Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-03-29T17:39:43.288Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,apps/demo-e2e/wdio.conf.ts,--autoCompileOpts.tsNodeOpts.project=apps/demo-e2e/tsconfig.json
[0-0] 2022-03-29T17:39:43.760Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - /apps/demo-e2e/src/features/login.feature
[0-0] 2022-03-29T17:39:44.773Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-03-29T17:39:44.841Z INFO webdriver: [POST] http://127.0.0.1:4444/session
[0-0] 2022-03-29T17:39:44.841Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] 2022-03-29T17:39:46.586Z ERROR @wdio/runner: Error: Cannot find module '@testing'
[0-0] Require stack:
[0-0] - /Users/userName/user-sandbox/nx-webdriverio/apps/demo-e2e/src/features/login/login.steps.ts
[0-0] - /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/cucumber-framework/build/index.js
[0-0] - /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/utils/build/utils.js
[0-0] - /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/utils/build/initialisePlugin.js
[0-0] - /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/utils/build/index.js
[0-0] - /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/runner/build/index.js
[0-0] - /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/local-runner/build/run.js
[0-0]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[0-0]     at Module._load (node:internal/modules/cjs/loader:778:27)
[0-0]     at Function.hookedLoader [as _load] (/Users/userName/user-sandbox/nx-webdriverio/node_modules/mockery/mockery.js:111:12)
[0-0]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[0-0]     at require (node:internal/modules/cjs/helpers:102:18)
[0-0]     at Object.<anonymous> (/Users/userName/user-sandbox/nx-webdriverio/apps/demo-e2e/src/features/login/login.steps.ts:2:1)
[0-0]     at Module._compile (node:internal/modules/cjs/loader:1103:14)
[0-0]     at Module.m._compile (/Users/userName/user-sandbox/nx-webdriverio/node_modules/ts-node/src/index.ts:1056:23)
[0-0]     at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[0-0]     at Object.require.extensions.<computed> [as .ts] (/Users/userName/user-sandbox/nx-webdriverio/node_modules/ts-node/src/index.ts:1059:12)
[0-0]  Error:  Cannot find module '@testing'
Require stack:
- /Users/userName/user-sandbox/nx-webdriverio/apps/demo-e2e/src/features/login/login.steps.ts
- /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/cucumber-framework/build/index.js
- /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/utils/build/utils.js
- /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/utils/build/initialisePlugin.js
- /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/utils/build/index.js
- /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/runner/build/index.js
- /Users/userName/user-sandbox/nx-webdriverio/node_modules/@wdio/local-runner/build/run.js
```

**Comment by christian-bromann** [comment]
As the error states, you have `import { someMethod } from '@testing';` in your test file (`apps/demo-e2e/src/features/login/login.steps.ts`) which is invalid.

**Comment by christian-bromann** [comment]
I am not a TypeScript expert. Maybe the `@` in `@testing` is a problem? Have you tried to fiddle with the `tsConfigPathsOpts` option? Maybe the path isn't correct.

**Comment by kerry-afs** [comment]
Ah, `tsConfigPathsOpts` was the key here. 

I initially had to add a reference to the base level tsconfig file at the top of the configuration file:
`const tsConfig = require('../../tsconfig.base.json');`

Then add the below tsConfigPathsOpts:
```
    tsConfigPathsOpts: {
      baseUrl: './',
      paths: tsConfig.compilerOptions.paths,
    },
```

I really appreciate your insight here. This was just TypeScript being TypeScript. 😅
