### ISSUE TITLE
xUnit reporter throws TypeError: Object.getOwnPropertyNames called on non-object

### ISSUE THREAD

**Issue by haysclark** [webdriverio/webdriverio#817]
xUnit reporter throwing an error for a simple project. 'dot' and 'spec' reports do NOT throw this error.  Sample project uploaded to GitHub and behavior reproduce on Travis-CI to help illustrate problem.

Error Log
------------
```
/home/travis/build/haysclark/wdio-xunit-error/node_modules/webdriverio/lib/reporter/xunit.js:273
            status: Object.getOwnPropertyNames(test.err).length === 0 ? 'passe
                           ^
TypeError: Object.getOwnPropertyNames called on non-object
    at Function.getOwnPropertyNames (native)
    at /home/travis/build/haysclark/wdio-xunit-error/node_modules/webdriverio/lib/reporter/xunit.js:273:28
    at Array.forEach (native)
    at XUnit.genTestsuite (/home/travis/build/haysclark/wdio-xunit-error/node_modules/webdriverio/lib/reporter/xunit.js:237:11)
    at /home/travis/build/haysclark/wdio-xunit-error/node_modules/webdriverio/lib/reporter/xunit.js:257:18
    at Array.forEach (native)
    at XUnit.genTestsuite (/home/travis/build/haysclark/wdio-xunit-error/node_modules/webdriverio/lib/reporter/xunit.js:237:11)
    at XUnit.genTestsuites (/home/travis/build/haysclark/wdio-xunit-error/node_modules/webdriverio/lib/reporter/xunit.js:189:10)
    at /home/travis/build/haysclark/wdio-xunit-error/node_modules/webdriverio/lib/reporter/xunit.js:128:18
    at Array.forEach (native)
npm ERR! Test failed.  See above for more details.
```

Sample project
-----------------------------
https://github.com/haysclark/wdio-xunit-error

Travis-CI run of sample project
-----------------------------------------
https://travis-ci.org/haysclark/wdio-xunit-error/builds/84022586

**Comment by haysclark** [comment]
#809 also fixes this issue.

**Comment by christian-bromann** [comment]
Let's continue convo in #809 then.
