### ISSUE TITLE
[🐛 Bug]:  Request failed with status 400 due to Unsupported CSS selector with Ionic on mobile

### ISSUE THREAD

**Issue by NisStrom** [webdriverio/webdriverio#8194]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.18.1

### Node.js Version

12.22.7

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        platformName: 'Android',
        maxInstances: 1,
        'appium:autoAcceptAlerts': true,
        'appium:autoDismissAlerts': true,
        'goog:chromeOptions': {
            args: ['--disable-dev-shm-usage', '--no-sandbox', '--disable-setuid-sandbox', '--disable-web-security']
        },
        'appium:deviceName': 'Pixel 4a',
        'appium:platformVersion': '11',
        'appium:orientation': 'PORTRAIT',
        'appium:automationName': 'UiAutomator2',
        framework: 'mocha',
        mochaOpts: {
            ui: 'bdd',
            timeout: 3 * 60 * 1000 // 3min
        }
        reporters: ['spec'],
    }
```

### What happened?

We are migrating tests from Protractor to WebdriverIO. The selectors which used to work with Protractor no longer do so with WebdriverIO. They fail with the following error message: 

```
Request failed with status 400 due to Unsupported CSS selector '*[MyAttribName="myValue"] input'. Reason: 'Error: 'MyAttribName' is not a valid attribute. Supported attributes are 'checkable, checked, clickable, enabled, focusable, focused, long-clickable, scrollable, selected, index, instance, description, resource-id, text, class-name, package-name''
```

We expect the selectors to continue to work with little to no modification, especially since the provided migration script in the migration guide does not alter them.

### What is your expected behavior?

The element should be found and successfully returned.

### How to reproduce the bug.

```js
get myInputElement() {
    return $('*[MyAttribName="myValue"] input');
}
```

### Relevant log output

```typescript
[0-0] 2022-04-07T08:45:53.810Z INFO webdriver: COMMAND findElement("css selector", "*[MyAttribName="myValue"] input")
[0-0] 2022-04-07T08:45:53.811Z INFO webdriver: [POST] http://localhost:4723/session/42ba3bfc-6ab9-4e3f-bbf7-cd9cc8d8f8cd/element
[0-0] 2022-04-07T08:45:53.811Z INFO webdriver: DATA {
[0-0]   using: 'css selector',
[0-0]   value: '*[MyAttribName="myValue"] input'
[0-0] }
[0-0] 2022-04-07T08:45:53.859Z WARN webdriver: Request failed with status 400 due to Unsupported CSS selector '*[MyAttribName="myValue"] input'. Reason: 'Error: 'MyAttribName' is not a valid attribute. Supported attributes are 'checkable, checked, clickable, enabled, focusable, focused, long-clickable, scrollable, selected, index, instance, description, resource-id, text, class-name, package-name''

--- Retrying... then---

[0-0] 2022-04-07T08:45:53.879Z ERROR webdriver: Request failed with status 400 due to invalid selector: Unsupported CSS selector '*[MyAttribName="myValue"] input'. Reason: 'Error: 'MyAttribName' is not a valid attribute. Supported attributes are 'checkable, checked, clickable, enabled, focusable, focused, long-clickable, scrollable, selected, index, instance, description, resource-id, text, class-name, package-name''
[0-0] invalid selector in "WebdriverIO with Test.should be able to do stuff"
invalid selector: Unsupported CSS selector '*[MyAttribName="myValue"] input'. Reason: 'Error: 'MyAttribName' is not a valid attribute. Supported attributes are 'checkable, checked, clickable, enabled, focusable, focused, long-clickable, scrollable, selected, index, instance, description, resource-id, text, class-name, package-name''
    at getErrorFromResponseBody (redacted\e2e\node_modules\webdriver\build\utils.js:197:12)
    at NodeJSRequest._request (redacted\e2e\node_modules\webdriver\build\request\index.js:158:60)
    at async Browser.wrapCommandFn (redacted\e2e\node_modules\@wdio\utils\build\shim.js:137:29)
    at async Browser.$ (redacted\e2e\node_modules\webdriverio\build\commands\browser\$.js:88:17)
    at async Browser.wrapCommandFn (redacted\e2e\node_modules\@wdio\utils\build\shim.js:137:29)
    at async MyPageObject.DoSomething(redacted\e2e\tests\pageobjects\MyPageObject.ts:33:9)
    at async MyPageObject.MyTest(redacted\e2e\tests\pageobjects\MyPageObject.ts:28:9)
    at async Context.<anonymous> (redacted\e2e\tests\specs\test.spec.ts:17:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
How does the HTML source look like of the element you want to fetch?

**Comment by NisStrom** [comment]
@christian-bromann 

I have finally managed to figure this out by myself: We are using Ionic + Capacitor and I forgot to switch the context to WEBVIEW. For any future reader, look [here](https://github.com/webdriverio/appium-boilerplate/blob/main/tests/screenobjects/WebviewScreen.ts), [here](https://github.com/webdriverio/appium-boilerplate/blob/main/tests/helpers/WebView.ts) and [here](https://github.com/webdriverio/appium-boilerplate/blob/main/tests/specs/app.webview.spec.ts) in the [appium-boilerplate](https://github.com/webdriverio/appium-boilerplate).

**Comment by christian-bromann** [comment]
@NisStrom thanks for clarifying!

> It would be great if WebdriverIO would somehow be able to detect this and give a hint accordingly.

Totally! Mind raising an issue for this? I am not too familiar with the mobile environment and not sure how to determine this easily. We have a [place in the codebase](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriver/src/utils.ts#L296-L351) to update and improve error messages from drivers, maybe that adding this edge case would be a good first step?
