### ISSUE TITLE
[🐛 Bug]: Firefox - Passing incorrect browser capabilities argument to browser URL

### ISSUE THREAD

**Issue by jameskip** [webdriverio/webdriverio#8223]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.5

### Node.js Version

14.19.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  acceptInsecureCerts: true,
  browserName: "firefox",
  "moz:firefoxOptions": {
  args: [`--width=1920`, `--height=1080`],
}
```

### What happened?

Given we are running our tests from Firefox
When calling `browser.reloadSession()` from a spec file
Then test fails and the browser never launches.

Started happing around 09:00 CST today, April, 14 2022.
Recent Firefox changes in #8211

### What is your expected behavior?

Test should reload browser session without error.

### How to reproduce the bug.

To reproduce the bug create and run a test like this:
```ts
describe("my test", () => {
  it("step", () => {
    browser.reloadSession();
  });
});
```

Launch with the following browser options:
```sh
{
  acceptInsecureCerts: true,
  browserName: "firefox",
  "moz:firefoxOptions": {
  args: [`--width=1920`, `--height=1080`],
}
```

### Relevant log output

```typescript
Invalid URL: http://localhost:--width=1920

TypeError [ERR_INVALID_URL]: Invalid URL: http://localhost:--width=1920
    at new NodeError (internal/errors.js:322:7)
    at onParseError (internal/url.js:270:9)
    at new URL (internal/url.js:346:5)
    at new URL (internal/url.js:343:22)
    at getWSEndpoint (/home/circleci/project/node_modules/puppeteer-core/src/common/BrowserConnector.ts:118:23)
    at connectToBrowser (/home/circleci/project/node_modules/puppeteer-core/src/common/BrowserConnector.ts:96:33)
    at PuppeteerNode.connect (/home/circleci/project/node_modules/puppeteer-core/src/common/Puppeteer.ts:80:28)
    at PuppeteerNode.connect (/home/circleci/project/node_modules/puppeteer-core/src/node/Puppeteer.ts:105:18)
    at Array.map (<anonymous>)
    at runMicrotasks (<anonymous>)
    at Context.<anonymous> (/home/circleci/project/my/awesome/file.spec.ts)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I can reproduce this, here are the logs:

```
2022-04-19T19:41:50.675Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-04-19T19:41:50.675Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-04-19T19:41:50.676Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js
[0-0] 2022-04-19T19:41:50.837Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in firefox - /test/specs/example.e2e.js
[0-0] 2022-04-19T19:41:50.944Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-0] 2022-04-19T19:41:50.952Z INFO devtools: Launch /Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin with config: {"product":"firefox","executablePath":"/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin","headless":false,"defaultViewport":{"width":1200,"height":900},"args":["--width=1920","--height=1080"]}
[0-0] 2022-04-19T19:41:52.101Z INFO devtools: COMMAND navigateTo("https://the-internet.herokuapp.com/login")
[0-0] 2022-04-19T19:41:54.616Z INFO devtools: RESULT null
[0-0] 2022-04-19T19:41:54.619Z INFO devtools: COMMAND deleteSession()
[0-0] 2022-04-19T19:41:54.943Z INFO devtools: RESULT null
[0-0] 2022-04-19T19:41:54.957Z INFO devtools: Launch /Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin with config: {"product":"firefox","executablePath":"/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin","headless":false,"defaultViewport":{"width":1200,"height":900},"args":["--width=1920","--height=1080"]}
```

Can you provide a minimal reproducible example?
