### ISSUE TITLE
[🐛 Bug]: Cucumber step timeout resulting missing screenshots for execution data in Report Portal

### ISSUE THREAD

**Issue by ztshashi** [webdriverio/webdriverio#8224]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

6.1.14

### Node.js Version

14.18.3

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    maxInstances: 2,
    browserName: 'chrome',
    'goog:chromeOptions': {
      args: ['--headless',
        '--window-size=1600,1200']
    }
  }
```

### What happened?

Cucumber options timeout reached results in hooks not getting executed. This behaviour is causing sreenshots not getting uploaded to the reports. [Report Portal](https://webdriver.io/docs/wdio-reportportal-reporter) is the reporting of test executions.

Sample wdio.conf.js to highlight the timeout referred in bug:
```
exports.config = {
    framework: 'cucumber',
    cucumberOpts: {
        timeout: 20000
    },
}
```

**Sample Hooks**:
```
  afterStep: function (test, context, { error }) {
    if (error) {
      browser.saveScreenshot(failureScreenshotPath);
      screenshot = true;
    }
  },
  afterScenario: function (uri, feature, scenario, result) {
    if (result.status === 'failed' && !screenshot) {
      browser.saveScreenshot(failureScreenshotPath);
    }
  }
```

### What is your expected behavior?

Execution of next steps should continue after cucumber timeouts and failed tests.

### How to reproduce the bug.

Configure timeout in cucumberOpts to a small number e.g. 1000 and execute sample cucumber test using webdriverio.

**Example**:
```
exports.config = {
    framework: 'cucumber',
    cucumberOpts: {
        timeout: 1000
    },
}
```

### Relevant log output

```typescript
Below error message is seen when cucumber step timeout reaches and screenshot is not attached to steps in Report Portal.

Error: function timed out, ensure the promise resolves within 1000 milliseconds
    at Timeout._onTimeout (/app/node_modules/cucumber/lib/user_code_runner.js:76:18)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by ztshashi** [comment]
Logged in wrong bucket
