### ISSUE TITLE
[💡 Feature]: separate connectionRetry parameters for session creation

### ISSUE THREAD

**Issue by felix9** [webdriverio/webdriverio#8227]
### Is your feature request related to a problem?

When talking to a grid like BrowserStack, it sometimes takes 2-3 minutes for a new session to be created, so connectionRetryTimeout needs to be 150000 msec or so, and probably connectionRetryCount should be 1 or more.

However, these parameters apply to every webdriver request. Most requests other than session creation finish very quickly. 5000 msec is a reasonable timeout for those, and retry is pointless, retryCount should be 0.

Applying the longer timeout to all requests means that some types of failures take much longer than necessary to actually fail.

### Describe the solution you'd like.

It would be nice to have separate timeout/retry parameters for session creation vs other protocol requests.

### Describe alternatives you've considered.

Can fake it by setting a long timeout in a `beforeSession()` hook and setting a shorter timeout in a `before()` hook.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by erwinheitzman** [comment]
Nice solution to the problem you experienced.

Another alternative would be to implement this in the respective cloud services instead of implementing it in WebdriverIO itself.

**Comment by christian-bromann** [comment]
@felix9 what would be your suggestion how this should be configured by the user?

**Comment by robgonnella** [comment]
I'm experiencing the same issue and I don't think the workaround mentioned above is valid anymore. If I try to change config options in hooks they don't appear to have any effect. I assume this is because at this point the options have already been applied in some immutable way? Or maybe I'm doing something wrong. 

Either way I imagine this is an issue with any remote grid service as there may not be an available browser slot for some time. Implementing a common way to handle this across most, if not all, remote grids via a separate timeout would be nice. Something like `initialConnectionTimeout` maybe? Also since the timeout originates in the client, I think it makes more sense to implement the solution in WebdriverIO. I confirmed the remote grid is not aborting the connection by setting `connectionRetryTimeout` to 20min and then blocking all the slots in my grid for an hour, the connection aborted at 20 min with the error below and did not perform any retries despite the config settings.

```
[0-0] 2025-06-07T23:01:22.077Z DEBUG @wdio/runner: init remote session
[0-0] 2025-06-07T23:01:22.079Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2025-06-07T23:01:22.079Z INFO @wdio/utils: Connecting to existing driver at http://grid:4444/wd/hub
[0-0] 2025-06-07T23:01:22.080Z INFO webdriver: [POST] http://grid:4444/wd/hub/session
[0-0] 2025-06-07T23:01:24.084Z ERROR webdriver: Error: WebDriverError: The operation was aborted due to timeout when running "http://grid:4444/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"chrome","grid:options":{"name":"1"},"goog:chromeOptions":{"args":["headless","disable-gpu"]},"webSocketUrl":true,"unhandledPromptBehavior":"ignore"},"firstMatch":[{}]}}"
[0-0]     at FetchRequest._libRequest (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1918:13)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async FetchRequest._request (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1928:20)
[0-0]     at async startWebDriverSession (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1059:16)
[0-0]     at async _WebDriver.newSession (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1497:41)
[0-0]     at remote (/app/node_modules/webdriverio/build/node.js:8775:20)
[0-0]     at async Runner._startSession (file:///app/node_modules/@wdio/runner/build/index.js:818:23)
[0-0]     at async Runner._initSession (file:///app/node_modules/@wdio/runner/build/index.js:792:22)
[0-0]     at async Runner.run (file:///app/node_modules/@wdio/runner/build/index.js:699:16)
[0-0] 2025-06-07T23:01:24.119Z ERROR @wdio/runner: Error: WebDriverError: The operation was aborted due to timeout when running "http://grid:4444/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"browserName":"chrome","moon:options":{"name":"1"},"goog:chromeOptions":{"args":["headless","disable-gpu"]},"webSocketUrl":true,"unhandledPromptBehavior":"ignore"},"firstMatch":[{}]}}"
[0-0]     at startWebDriverSession (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1063:11)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async _WebDriver.newSession (file:///app/node_modules/webdriverio/node_modules/webdriver/build/node.js:1497:41)
[0-0]     at remote (/app/node_modules/webdriverio/build/node.js:8775:20)
[0-0]     at async Runner._startSession (file:///app/node_modules/@wdio/runner/build/index.js:818:23)
[0-0]     at async Runner._initSession (file:///app/node_modules/@wdio/runner/build/index.js:792:22)
[0-0]     at async Runner.run (file:///app/node_modules/@wdio/runner/build/index.js:699:16)
[0-0] 2025-06-07T23:01:24.119Z DEBUG @wdio/utils:shim: Finished to run "after" hook in 0ms
2025-06-07T23:01:24.236Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///src/selenium/bots/cm-dma-realtime.bot.ts
2025-06-07T23:01:24.236Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2025-06-07T23:01:24.236Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
```

Another issue I've noticed with `connectionRetryTimeout` and `connectionRetryCount` is that retries do not actually occur if the initial connection times out. This is reproducible even running locally (no remote grid) by setting a timeout that's too short for any session.

```
...
  connectionRetryTimeout: 2000,
  connectionRetryCount: 10,
...
```

I see the same error as above with no retries.

**Comment by ZIMkaRU** [comment]
I have the same and can confirm there are no retries, just one attempt
