### ISSUE TITLE
Screenshot save on error not working with generators

### ISSUE THREAD

**Issue by ryanzec** [webdriverio/webdriverio#825]
So I have this simple test and everything works as expected including the error screenshot:

```javascript
describe('something', function() {
    it('should be tested', function(done) {
        browser.url('/login')
            .getTitle().then(function(title) {
                expect(title).to.equal('Not Right');
            })
            .call(done);
    });
});
```

When I change this test to use generators (using NPM 4.1.2), the test itself fails like expect however the screenshot is not automatically generated:

```javascript
describe('something', function() {
    it('should be tested', function*() {
        yield browser.url('/login')
        var title = yield browser.getTitle();

        expect(title).to.equal('OnForfce');
    });
});
```

Now if I manually add in a `yield browser.saveScreenshot('./ui-tests/screenshots/test.png');` the screenshot is generated as expect, it just does not seems to be doing it automatically on errors when using generators.

Am I missing something or is this in fact a bug?

**Comment by christian-bromann** [comment]
Looks like a bug to me. The error didn't seem to get picked up outside the then scope.

**Comment by mucsi96** [comment]
+1

**Comment by mucsi96** [comment]
I started to investigate it. But it seems rather complex. I added some console logs and traces
```
//lib/webdriverio.js:159
client.next = function (func, args, name) {
    var self = this;

    /**
     * use finally to propagate rejected promises up the chain
     */
    console.trace();
    console.log('fulFilledPromise', self.lastPromise === fulFilledPromise);
    return self.lastPromise.then(function() {
        /**
         * store command into command list so `getHistory` can return it
         */
        commandList.push({
            name: name,
            args: args
        });

        //console.trace();
        console.log(commandList);

        return resolve.call(self, safeExecute(func, args));
    }, function(e) {

        /**
         * reject pending commands in chain
         */
        if(e.isPropagatedError) {
            return self.defer.reject(e);
```
And the output is looks rather strange
```
Trace
    at Object.client.next (/Users/igor/work/node_modules/webdriverio/lib/webdriverio.js:165:21)
    at Object.WebdriverIO.resolve (/Users/igor/work/node_modules/webdriverio/lib/webdriverio.js:117:20)
    at /Users/igor/work/node_modules/webdriverio/lib/webdriverio.js:232:32
    at _rejected (/Users/igor/work/node_modules/q/q.js:830:24)
    at /Users/igor/work/node_modules/q/q.js:856:30
    at Promise.when (/Users/igor/work/node_modules/q/q.js:1108:31)
    at Promise.promise.promiseDispatch (/Users/igor/work/node_modules/q/q.js:774:41)
    at /Users/igor/work/node_modules/q/q.js:590:44
    at runSingle (/Users/igor/work/node_modules/q/q.js:123:13)
    at flush (/Users/igor/work/node_modules/q/q.js:111:13)
fulFilledPromise true
commandList [ { name: 'init', args: [] },
  { name: 'url', args: [ '/' ] },
  { name: 'click', args: [ '[data-test-locator="sign-in"]' ] },
  { name: 'element', args: [ '[data-test-locator="sign-in"]' ] },
  { name: 'saveScreenshot',
    args: [ '/Users/igor/work/.data/e2e-screenshots/ERROR_phantomjs.any_2015-12-02T11-55-26.498Z.png' ] } ]
Trace
    at Object.client.next (/Users/igor/work/node_modules/webdriverio/lib/webdriverio.js:165:21)
    at Object.prototype.(anonymous function) [as saveScreenshot] (/Users/igor/work/node_modules/webdriverio/lib/webdriverio.js:362:20)
    at Object.safeExecute (/Users/igor/work/node_modules/webdriverio/lib/utils/safeExecute.js:19:24)
    at Object.WebdriverIO.resolve (/Users/igor/work/node_modules/webdriverio/lib/webdriverio.js:87:29)
    at /Users/igor/work/node_modules/webdriverio/lib/webdriverio.js:179:32
    at _fulfilled (/Users/igor/work/node_modules/q/q.js:820:54)
    at self.promiseDispatch.done (/Users/igor/work/node_modules/q/q.js:849:30)
    at Promise.promise.promiseDispatch (/Users/igor/work/node_modules/q/q.js:782:13)
    at /Users/igor/work/node_modules/q/q.js:843:14
    at runSingle (/Users/igor/work/node_modules/q/q.js:123:13)
fulFilledPromise true
commandList [ { name: 'init', args: [] },
  { name: 'url', args: [ '/' ] },
  { name: 'click', args: [ '[data-test-locator="sign-in"]' ] },
  { name: 'element', args: [ '[data-test-locator="sign-in"]' ] },
  { name: 'saveScreenshot',
    args: [ '/Users/igor/work/.data/e2e-screenshots/ERROR_phantomjs.any_2015-12-02T11-55-26.498Z.png' ] },
  { name: 'saveScreenshot',
    args: [ '/Users/igor/work/.data/e2e-screenshots/ERROR_phantomjs.any_2015-12-02T11-55-26.498Z.png' ] } ]
```
I looks like the screenshot creation is added twice to the command list

**Comment by mucsi96** [comment]
Also I forget to add that in my case the screenshot file is created but it is 0 byte. (Looks like the file is not closed properly)

**Comment by christian-bromann** [comment]
We fixed that in v4 by using the screenshot that comes with the Selenium response.

**Comment by shadiabuhilal** [comment]
@ryanzec  , you can do it by using `afterTest` function in `wdio.conf.js` file, like this:
```JS
/**
     * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    afterTest: function (test) {
        // if test passed, ignore, else take and save screenshot.
        if (test.passed) {
            return;
        }
        // get current test title and clean it, to use it as file name
        var filename = encodeURIComponent(test.title.replace(/\s+/g, '-'));
        // build file path
        var filePath = this.screenshotPath + filename + '.png';
        // save screenshot
        browser.saveScreenshot(filePath);
        console.log('\n\tScreenshot location:', filePath, '\n');
    },
```
