### ISSUE TITLE
[💡 Feature]: Print selector when invalid selector error

### ISSUE THREAD

**Issue by yogeshgadge** [webdriverio/webdriverio#8352]
### Is your feature request related to a problem?

I am always frustrated when the long stack-trace don't make any sense when it does not give any meaningful information.

At the end of the run I get this error. The error clearly says "invalid selector" but which one ? and where is my line number ?
 
```
0-0] invalid selector: invalid selector: An invalid or illegal selector was specified
[0-0]   (Session info: chrome=101.0.4951.41)
[0-0]     at getErrorFromResponseBody (/Users/REDACTED/node_modules/webdriver/build/utils.js:197:12)
[0-0]     at NodeJSRequest._request (/Users/REDACTED/node_modules/webdriver/build/request/index.js:166:60)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Element.wrapCommandFn (/Users/REDACTED/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.wrapCommandFn (/Users/REDACTED/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.elementErrorHandlerCallbackFn (/Users/REDACTED/node_modules/webdriverio/build/middlewares.js:24:32)
[0-0]     at async Element.wrapCommandFn (/Users/REDACTED/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.$ (/Users/REDACTED/node_modules/webdriverio/build/commands/browser/$.js:91:17)
[0-0]     at async Element.wrapCommandFn (/Users/REDACTED/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Element.elementErrorHandlerCallbackFn (/Users/REDACTED/node_modules/webdriverio/build/middlewares.js:24:32) {
[0-0]   jasmineMessage: 'Uncaught exception: invalid selector: invalid selector: An invalid or illegal selector was specified\n' +
[0-0]     '  (Session info: chrome=101.0.4951.41)'
[0-0] FAILED in chrome - /projects/REDACTED/REDACTED/create.e2e-spec.ts
```

### Describe the solution you'd like.

At least print the selector.

### Describe alternatives you've considered.

Commented out a whole lot of code but still no lunch finding where is this being thrown.

### Additional context

I use async. beforeAll(async() ), nested describes and it(async ()) using jasmine, typescript

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by praveendvd** [comment]
@yogeshgadge  could you provide a reproducible example . IT works fine with xpath

**Comment by praveendvd** [comment]
![image](https://user-images.githubusercontent.com/45095911/169662669-369cb462-aa48-4145-898b-e95faa0ac692.png)

**Comment by yogeshgadge** [comment]
I don't have access to that project anymore. 
But here are the steps:

Use jasmine typescript project.

In beforeAll async function instantiate a typescript object from some class.

Invoke a async function in the beforeAll block.

Use a css selector that is invalid and wait for existence.

I could try to reproduce it next week.

**Comment by christian-bromann** [comment]
I looked into different responses from browser and found the following:

Chrome
```js
{
  value: {
    error: 'invalid selector',
    message: 'invalid selector: An invalid or illegal selector was specified\n' +
      '  (Session info: chrome=102.0.5005.115)',
    stacktrace: '...'
  }
}
```

Firefox
```js
{
  status: 32,
  sessionId: 'e892e6b8b29b476a8bee987976de168f',
  value: {
    hCode: 20667318,
    stackTrace: [...],
    suppressed: [],
    additionalInformation: '\n' +
      'Driver info: org.openqa.selenium.firefox.FirefoxDriver\n' +
      'Capabilities [{moz:profile=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\rust_mozprofileGsaFgu, wdio:devtoolsOptions={headless=true}, moz:geckodriverVersion=0.30.0, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss and notify, strictFileInteractability=false, moz:headless=false, platform=ANY, proxy=Proxy(), moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=101.0, moz:shutdownTimeout=60000.0, platformVersion=6.1, moz:processID=2084.0, browserName=firefox, moz:buildID=20220526203855, javascriptEnabled=true, platformName=windows, setWindowRect=true, moz:webdriverClick=true}]\n' +
      'Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXfaf60275\n' +
      '*** Element info: {Using=css selector, value=!!}',
    localizedMessage: `Given css selector expression "!!" is invalid: InvalidSelectorError: Document.querySelector: '!!' is not a valid selector: "!!"\n` +
      'For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html\n' +
      "Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'\n" +
      "System info: host: 'WIN-R1JBAO1CNPS', ip: '10.119.27.126', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_91'\n" +
      'Driver info: org.openqa.selenium.firefox.FirefoxDriver\n' +
      'Capabilities [{moz:profile=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\rust_mozprofileGsaFgu, wdio:devtoolsOptions={headless=true}, moz:geckodriverVersion=0.30.0, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss and notify, strictFileInteractability=false, moz:headless=false, platform=ANY, proxy=Proxy(), moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=101.0, moz:shutdownTimeout=60000.0, platformVersion=6.1, moz:processID=2084.0, browserName=firefox, moz:buildID=20220526203855, javascriptEnabled=true, platformName=windows, setWindowRect=true, moz:webdriverClick=true}]\n' +
      'Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXfaf60275\n' +
      '*** Element info: {Using=css selector, value=!!}',
    class: 'org.openqa.selenium.InvalidSelectorException',
    buildInformation: {
      buildRevision: 'unknown',
      releaseLabel: '3.4.0',
      hCode: 8922936,
      buildTime: 'unknown',
      class: 'org.openqa.selenium.internal.BuildInfo'
    },
    message: `Given css selector expression "!!" is invalid: InvalidSelectorError: Document.querySelector: '!!' is not a valid selector: "!!"\n` +
      'For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html\n' +
      "Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'\n" +
      "System info: host: 'WIN-R1JBAO1CNPS', ip: '10.119.27.126', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_91'\n" +
      'Driver info: org.openqa.selenium.firefox.FirefoxDriver\n' +
      'Capabilities [{moz:profile=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\rust_mozprofileGsaFgu, wdio:devtoolsOptions={headless=true}, moz:geckodriverVersion=0.30.0, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss and notify, strictFileInteractability=false, moz:headless=false, platform=ANY, proxy=Proxy(), moz:accessibilityChecks=false, moz:useNonSpecCompliantPointerOrigin=false, acceptInsecureCerts=false, browserVersion=101.0, moz:shutdownTimeout=60000.0, platformVersion=6.1, moz:processID=2084.0, browserName=firefox, moz:buildID=20220526203855, javascriptEnabled=true, platformName=windows, setWindowRect=true, moz:webdriverClick=true}]\n' +
      'Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXfaf60275\n' +
      '*** Element info: {Using=css selector, value=!!}',
    systemInformation: "System info: host: 'WIN-R1JBAO1CNPS', ip: '10.119.27.126', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_91'",
    cause: null,
    supportUrl: 'http://seleniumhq.org/exceptions/invalid_selector_exception.html'
  },
  state: 'invalid selector',
  hCode: 14847197,
  class: 'org.openqa.selenium.remote.Response'
}
```

Safari
```
{
    value: {
        error: 'invalid selector',
        message: '',
        stacktrace: ''
    }
}
```

I think we can modify the error message to include the selector here.

**Comment by christian-bromann** [comment]
Implemented in https://github.com/webdriverio/webdriverio/pull/8457
