### ISSUE TITLE
[🐛 Bug]: Mutiremote V6 webdriverio and browserstack local together does not work as expected

### ISSUE THREAD

**Issue by suchitrak** [webdriverio/webdriverio#8373]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

6.12.1

### Node.js Version

v14.17.6

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: {
        userA: {
            capabilities: {
                browserName: 'chrome'
            }
        },
        userB: {
            capabilities: {
                browserName: 'chrome'
            }
        }
    },
```

### What happened?

I see the below error.

```
ERROR @wdio/runner: Error: Required option "capabilities" is missing
```

This only happens on V6 webdriverio version. It works fine if V7 webdriverio is used. 
This also works fine when I don't set browserstacklocal to true with V6 version

node_modules/webdriverio/build/index.js 
    const browserNames = Object.keys(params);
    
The below console.log prints out below: 
console.log(`browserNames = ${browserNames}`)
 browserNames = userA,userB,browserstack.local

### What is your expected behavior?

For webdriverio V6, the following config file should work as expected. 

services: [
        ['browserstack', {
            browserstackLocal: true
        }]
    ],

capabilities: {
        userA: {
            capabilities: {
                browserName: 'chrome'
            }
        },
        userB: {
            capabilities: {
                browserName: 'chrome'
            }
        }
    },

### How to reproduce the bug.

Clone this repository - https://github.com/suchitrak/webdriverioMultiRemoteBrowserstackLocalIssue

execute the wdio test case

yarn wdio

### Relevant log output

```typescript
[0-0] browserNames = userA,userB,browserstack.local
[object Object]
[0-0] {"protocol":"https","hostname":"@hub-cloud.browserstack.com","port":443,"path":"/wd/hub","specs":["./features/login.feature"],"suites":{},"exclude":[],"logLevel":"info","logLevels":{},"excludeDriverLogs":[],"bail":0,"waitforInterval":500,"waitforTimeout":10000,"framework":"cucumber","reporters":["spec"],"services":[["browserstack",{"browserstackLocal":true}]],"maxInstances":10,"maxInstancesPerCapability":100,"filesToWatch":[],"connectionRetryTimeout":120000,"connectionRetryCount":3,"execArgv":[],"runnerEnv":{},"runner":"local","mochaOpts":{"timeout":10000},"jasmineNodeOpts":{"defaultTimeoutInterval":10000},"cucumberOpts":{"timeout":60000,"require":["./features/step-definitions/steps.js"],"backtrace":false,"requireModule":[],"dryRun":false,"failFast":false,"snippets":true,"source":true,"strict":false,"tagExpression":"","ignoreUndefinedDefinitions":false},"onPrepare":[],"onWorkerStart":[],"before":[],"beforeSession":[],"beforeSuite":[],"beforeHook":[],"beforeTest":[],"beforeCommand":[],"afterCommand":[],"afterTest":[],"afterHook":[],"afterSuite":[],"afterSession":[],"after":[],"onComplete":[],"onReload":[],"beforeFeature":[],"beforeScenario":[],"beforeStep":[],"afterStep":[],"afterScenario":[],"afterFeature":[],"user":"suchitrakunnath1","key":"mznjAgAPXLxVfWrRaPSC","baseUrl":"http://localhost","_":["run"],"$0":"FILEPATH/node_modules/.bin/wdio","config-path":"wdio.conf.multiuser.js","ignoredWorkerServices":[],"specFileRetryAttempts":0,"automationProtocol":"./protocol-stub","capabilities":{"browserName":"chrome"}}

[object Object]
[0-0] {"protocol":"https","hostname":"@hub-cloud.browserstack.com","port":443,"path":"/wd/hub","specs":["./features/login.feature"],"suites":{},"exclude":[],"logLevel":"info","logLevels":{},"excludeDriverLogs":[],"bail":0,"waitforInterval":500,"waitforTimeout":10000,"framework":"cucumber","reporters":["spec"],"services":[["browserstack",{"browserstackLocal":true}]],"maxInstances":10,"maxInstancesPerCapability":100,"filesToWatch":[],"connectionRetryTimeout":120000,"connectionRetryCount":3,"execArgv":[],"runnerEnv":{},"runner":"local","mochaOpts":{"timeout":10000},"jasmineNodeOpts":{"defaultTimeoutInterval":10000},"cucumberOpts":{"timeout":60000,"require":["./features/step-definitions/steps.js"],"backtrace":false,"requireModule":[],"dryRun":false,"failFast":false,"snippets":true,"source":true,"strict":false,"tagExpression":"","ignoreUndefinedDefinitions":false},"onPrepare":[],"onWorkerStart":[],"before":[],"beforeSession":[],"beforeSuite":[],"beforeHook":[],"beforeTest":[],"beforeCommand":[],"afterCommand":[],"afterTest":[],"afterHook":[],"afterSuite":[],"afterSession":[],"after":[],"onComplete":[],"onReload":[],"beforeFeature":[],"beforeScenario":[],"beforeStep":[],"afterStep":[],"afterScenario":[],"afterFeature":[],"user":"suchitrakunnath1","key":"mznjAgAPXLxVfWrRaPSC","baseUrl":"http://localhost","_":["run"],"$0":"FILEPATH/node_modules/.bin/wdio","config-path":"wdio.conf.multiuser.js","ignoredWorkerServices":[],"specFileRetryAttempts":0,"automationProtocol":"./protocol-stub","capabilities":{"browserName":"chrome"}}

[object Object]
{"protocol":"https","hostname":"@hub-cloud.browserstack.com","port":443,"path":"/wd/hub","specs":["./features/login.feature"],"suites":{},"exclude":[],"logLevel":"info","logLevels":{},"excludeDriverLogs":[],"bail":0,"waitforInterval":500,"waitforTimeout":10000,"framework":"cucumber","reporters":["spec"],"services":[["browserstack",{"browserstackLocal":true}]],"maxInstances":10,"maxInstancesPerCapability":100,"filesToWatch":[],"connectionRetryTimeout":120000,"connectionRetryCount":3,"execArgv":[],"runnerEnv":{},"runner":"local","mochaOpts":{"timeout":10000},"jasmineNodeOpts":{"defaultTimeoutInterval":10000},"cucumberOpts":{"timeout":60000,"require":["./features/step-definitions/steps.js"],"backtrace":false,"requireModule":[],"dryRun":false,"failFast":false,"snippets":true,"source":true,"strict":false,"tagExpression":"","ignoreUndefinedDefinitions":false},"onPrepare":[],"onWorkerStart":[],"before":[],"beforeSession":[],"beforeSuite":[],"beforeHook":[],"beforeTest":[],"beforeCommand":[],"afterCommand":[],"afterTest":[],"afterHook":[],"afterSuite":[],"afterSession":[],"after":[],"onComplete":[],"onReload":[],"beforeFeature":[],"beforeScenario":[],"beforeStep":[],"afterStep":[],"afterScenario":[],"afterFeature":[],"user":"suchitrakunnath1","key":"mznjAgAPXLxVfWrRaPSC","baseUrl":"http://localhost","_":["run"],"$0":"FILEPATH/node_modules/.bin/wdio","config-path":"wdio.conf.multiuser.js","ignoredWorkerServices":[],"specFileRetryAttempts":0,"automationProtocol":"./protocol-stub"}

[0-0] 2022-05-23T18:31:17.590Z ERROR @wdio/runner: Error: Required option "capabilities" is missing
    at Object.validateConfig (FILEPATH/node_modules/@wdio/config/build/utils.js:117:19)
    at Object.exports.remote (FILEPATH/node_modules/webdriverio/build/index.js:40:29)
    at FILEPATH/node_modules/webdriverio/build/index.js:76:40
    at Array.map (<anonymous>)
    at Object.exports.multiremote (FILEPATH/node_modules/webdriverio/build/index.js:75:36)
    at Object.initialiseInstance (FILEPATH/node_modules/@wdio/runner/build/utils.js:44:41)
    at Runner._startSession (FILEPATH/node_modules/@wdio/runner/build/index.js:123:70)
    at Runner.run (FILEPATH/node_modules/@wdio/runner/build/index.js:38:34)
    at process.<anonymous> (FILEPATH/node_modules/@wdio/local-runner/build/run.js:24:30)
    at process.emit (events.js:412:35)
[0-0] 2022-05-23T18:31:17.605Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot convert undefined or null to object
    at execHook (FILEPATH/node_modules/@wdio/sync/build/executeHooksWithArgs.js:19:27)

FILEPATH/node_modules/@wdio/cli/build/interface.js:127
            throw new Error('Could not find job');
                  ^
Error: Could not find job
    at WDIOCLInterface.clearJob (FILEPATH/node_modules/@wdio/cli/build/interface.js:127:19)
    at WDIOCLInterface.emit (events.js:400:28)
    at WDIOCLInterface.emit (domain.js:470:12)
    at Launcher.endHandler (FILEPATH/node_modules/@wdio/cli/build/launcher.js:222:28)
    at WorkerInstance.emit (events.js:400:28)
    at WorkerInstance.emit (domain.js:470:12)
    at WorkerInstance._handleExit (FILEPATH/node_modules/@wdio/local-runner/build/worker.js:93:14)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:470:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

It seems this error is resolved in v7 of WebdriverIO so I recommend to upgrade to v7. v6 is in maintenance mode so we are happy to merge PRs and release new versions if provided.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
Closing due to inactivity. Happy to re-open if anyone wants to contribute a fix to the [v6](https://github.com/webdriverio/webdriverio/tree/v6) branch.
