### ISSUE TITLE
[🐛 Bug]: V7 - Adding Spec Reporter Options Causes The Tests To Error And Not Execute

### ISSUE THREAD

**Issue by PFaz540** [webdriverio/webdriverio#8375]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.5

### Node.js Version

18.1.0

### Mode

WDIO Testrunner

### What happened?

I noticed that we can pass in options to `reporters` in the `wdio.conf.js` file, but doing so caused it error even when copying the format specified in the docs.

https://webdriver.io/docs/spec-reporter

I'm using Mac OS 11.6
WDIO 7.19.5
Async Mode

### What is your expected behavior?

I should be allowed to pass in options like the below and for them to be handled. In the example below, my console logs should be output and only the failing specs should appear.

```
reporters: [
  "spec",
  {
    onlyFailures: false,
    addConsoleLogs: true,
  },
],
```

### How to reproduce the bug.

The reporters array in my wdio.conf.js has looked like this for years:

```
reporters: [
  "spec"
],
```

However, after reading [this](https://webdriver.io/docs/spec-reporter) I wanted to add some options in to only show the failing tests etc. But that caused the test run to error. I've pasted in the terminal error in one of the below steps. If I remove the new options and revert it back to the above, the tests run fine as usual.

```
reporters: [
  "spec",
  {
    onlyFailures: false,
    addConsoleLogs: true,
  },
],
```

### Relevant log output

```typescript
Execution of 1 workers started at 2022-05-25T16:59:47.437Z

[0-0] 2022-05-25T16:59:49.728Z ERROR @wdio/runner: Error: Type check for option "reporters" failed: a reporter should be either a string in the format "wdio-<reportername>-reporter" or a function/class. Please see the docs for more information on custom reporters (https://webdriver.io/docs/customreporter)
[0-0]     at validateConfig (/Users/paul.farrell/Development/webdriverio-framework/node_modules/@wdio/config/build/utils.js:68:27)
[0-0]     at remote (/Users/paul.farrell/Development/webdriverio-framework/node_modules/webdriverio/build/index.js:58:48)
[0-0]     at initialiseInstance (/Users/paul.farrell/Development/webdriverio-framework/node_modules/@wdio/runner/build/utils.js:64:41)
[0-0]     at Runner._startSession (/Users/paul.farrell/Development/webdriverio-framework/node_modules/@wdio/runner/build/index.js:223:93)
[0-0]     at Runner.run (/Users/paul.farrell/Development/webdriverio-framework/node_modules/@wdio/runner/build/index.js:66:34)
[0-0]     at process.<anonymous> (/Users/paul.farrell/Development/webdriverio-framework/node_modules/@wdio/local-runner/build/run.js:24:30)
[0-0]     at process.emit (node:events:539:35)
[0-0]     at process.emit (node:domain:475:12)
[0-0]     at emit (node:internal/child_process:936:14)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[0-0] 2022-05-25T16:59:49.870Z ERROR @wdio/local-runner: Failed launching test session: Error: Invalid reporters config
[0-0]     at BaseReporter.initReporter (/Users/paul.farrell/Development/webdriverio-framework/node_modules/@wdio/runner/build/reporter.js:166:15)
[0-0]     at Array.map (<anonymous>)
[0-0]     at new BaseReporter (/Users/paul.farrell/Development/webdriverio-framework/node_modules/@wdio/runner/build/reporter.js:22:50)
[0-0]     at Runner.run (/Users/paul.farrell/Development/webdriverio-framework/node_modules/@wdio/runner/build/index.js:78:26)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0] FAILED

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:02
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
It should be:
```ts
reporters: [
  [
    "spec",
    {
      onlyFailures: false,
      addConsoleLogs: true,
    },
  ]
]
```
