### ISSUE TITLE
[🐛 Bug]: Chromium doesn't start

### ISSUE THREAD

**Issue by bormando** [webdriverio/webdriverio#8393]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.7

### Node.js Version

16.13.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chromium'
}
```

### What happened?

I've installed latest Chromium (104.0.5098.0 (Developer Build) (x86_64)) via brew (3.4.11) on MacOS (12.4). I'm unable to run tests if I set this browser in config - I receive an error (please look at the log section for more info).
Also I don't have Google Chrome installed and I'm running tests locally.
Chromium doesn't start neither with DevTools service nor chromedriver.

### What is your expected behavior?

Chromium runs without errors.

### How to reproduce the bug.

1. Install `@wdio/cli`: `npm i -D @wdio/cli`
2. Set up a test project: `npx wdio config`
3. Set Chromium browser in `wdio.conf.js`
4. Run tests.
Here's a repo that you might try: https://github.com/bormando/wdio-chromium-bug

### Relevant log output

```typescript
dmitrii@bormando-mbp wdioch % npm test                                                           

> wdioch@1.0.0 test
> npx wdio wdio.conf.js


Execution of 1 workers started at 2022-06-01T21:02:02.332Z

2022-06-01T21:02:02.372Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-06-01T21:02:02.376Z INFO chromedriver: Start Chromedriver (/Users/dmitrii/Projects/examples/wdioch/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2022-06-01T21:02:02.408Z INFO chromedriver: Starting ChromeDriver 101.0.4951.41 (93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}) on port 9515
2022-06-01T21:02:02.409Z INFO chromedriver: Only local connections are allowed.
2022-06-01T21:02:02.409Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-06-01T21:02:02.411Z INFO chromedriver: ChromeDriver was started successfully.
2022-06-01T21:02:02.503Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-06-01T21:02:02.505Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2022-06-01T21:02:03.105Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chromium - /test/specs/example.e2e.js
[0-0] 2022-06-01T21:02:03.391Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-0] 2022-06-01T21:02:03.392Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900
[0-0] 2022-06-01T21:02:11.591Z ERROR @wdio/runner: Error
[0-0]     at new LauncherError (/Users/dmitrii/Projects/examples/wdioch/node_modules/chrome-launcher/dist/utils.js:26:22)
[0-0]     at new ChromeNotInstalledError (/Users/dmitrii/Projects/examples/wdioch/node_modules/chrome-launcher/dist/utils.js:57:9)
[0-0]     at Launcher.launch (/Users/dmitrii/Projects/examples/wdioch/node_modules/chrome-launcher/dist/chrome-launcher.js:187:23)
[0-0]     at launch (/Users/dmitrii/Projects/examples/wdioch/node_modules/chrome-launcher/dist/chrome-launcher.js:35:20)
[0-0]     at launchChrome (/Users/dmitrii/Projects/examples/wdioch/node_modules/devtools/build/launcher.js:80:55)
[0-0]     at launch (/Users/dmitrii/Projects/examples/wdioch/node_modules/devtools/build/launcher.js:179:16)
[0-0]     at Function.newSession (/Users/dmitrii/Projects/examples/wdioch/node_modules/devtools/build/index.js:54:54)
[0-0]     at remote (/Users/dmitrii/Projects/examples/wdioch/node_modules/webdriverio/build/index.js:77:43)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Runner._startSession (/Users/dmitrii/Projects/examples/wdioch/node_modules/@wdio/runner/build/index.js:223:56)
[0-0] FAILED in chromium - /test/specs/example.e2e.js
2022-06-01T21:02:11.708Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-06-01T21:02:11.709Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:09 

2022-06-01T21:02:11.710Z INFO @wdio/local-runner: Shutting down spawned worker
2022-06-01T21:02:11.962Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-06-01T21:02:11.963Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@bormando to use the Chromium browser you have to set the binary path in the capabilities and use `chrome` as `browserName`, e.g.:

```js
{
  browserName: 'chromium'
  'goog:chromeOptions': {
    binary: '/path/to/chromium'
  }
}
```

Let me know if you have further questions.

**Comment by bormando** [comment]
@christian-bromann thanks, it works fine that way. I couldn't find it on the website or in issues list here. Do we have this trick documented somewhere? If not, I guess I'd need to create a separate issue to update the doc.
OR, even better, is it possible to support a feature just stating browser name 'chromium' in the config without setting the path to it? I guess that's another issue as well.

**Comment by christian-bromann** [comment]
> I guess I'd need to create a separate issue to update the doc.

Or provide a PR with some doc updates? You can find most of our docs [here](https://github.com/webdriverio/webdriverio/tree/main/website/docs). Any contributions are appreciated.

> OR, even better, is it possible to support a feature just stating browser name 'chromium' in the config without setting the path to it?

That would mean you would have to write some logic to find a certain application like Chromium on the users machine (which could be Windows, Mac or various ubuntu distributions). We have something [similar already](https://github.com/webdriverio/webdriverio/tree/main/packages/devtools/src/finder) when running tests on Firefox and Edge using devtools protocol. We use [`chrome-launcher`](https://www.npmjs.com/package/chrome-launcher) to find Chromium which is able to do so but [only on linux](https://github.com/GoogleChrome/chrome-launcher/commit/1c11021a).

When running tests using the WebDriver protocol the browser driver, e.g. chromedriver, is suppose to find the browser for you. I could be convinced to use the same finder logic if the driver doesn't find it but that would be another issue.
