### ISSUE TITLE
[🐛 Bug]: driver.toggleNetworkSpeed is missing a required parameter

### ISSUE THREAD

**Issue by hammzj** [webdriverio/webdriverio#8398]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

14.16.10

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
desiredCapabilities: {
    platformName: 'Android',
    'appium:app': '/Users/zachhamm/Documents/GitHub/PROJECT/apps/<my.app.apk>',
    'appium:locale': 'US',
    'appium:language': 'en',
    'appium:orientation': 'PORTRAIT',
    'appium:automationName': 'UiAutomator2',
    'appium:noReset': false,
    'appium:fullReset': true,
    'appium:allowTestPackages': true,
    'appium:newCommandTimeout': 240,
    'appium:printPageSourceOnFindFailure': true,
    'appium:setWebContentsDebuggingEnabled': true,
    'appium:clearDeviceLogsOnStart': true,
    'appium:logcatFormat': 'brief',
    'goog:chromeOptions': { args: [Array] },
    'appium:deviceName': 'pixel_3a',
    'appium:avd': 'Pixel_3a_API_31',
    'appium:platformVersion': '12.0'
  }
}
```
```


### What happened?

Using the Appium command `driver.toggleNetworkSpeed()` without a parameter gives the following error:
> invalid argument: Parameters were incorrect. We wanted {"required":["netspeed"]} and you sent []


However, I am unable to provide a parameter like `driver.toggleNetworkSpeed('gsm')` or I get an error from WebDriverIO:
> [emulator-5554 Android 12 #0-0] Error: Wrong parameters applied for toggleNetworkSpeed
[emulator-5554 Android 12 #0-0] Usage: toggleNetworkSpeed()
[emulator-5554 Android 12 #0-0]
[emulator-5554 Android 12 #0-0] For more info see http://appium.io/docs/en/commands/device/network/network-speed/



### What is your expected behavior?

I should be able to use `driver.toggleNetworkSpeed(networkSpeed)` and have it change the network type on an Android device.

### How to reproduce the bug.

```js
await driver.toggleNetworkSpeed('lte');
```

### Relevant log output

```typescript
{"timestamp":1654192647086,"level":"ALL","message":"[HTTP] \u001b[37m-->\u001b[39m \u001b[37mPOST\u001b[39m \u001b[37m/wd/hub/session/c8864a2f-5add-4d72-8651-fd6c7e07514a/appium/device/network_speed\u001b[39m"}
{"timestamp":1654192647086,"level":"ALL","message":"[HTTP] \u001b[90m{}\u001b[39m"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)] Encountered internal error running command: BadParametersError: Parameters were incorrect. We wanted {\"required\":[\"netspeed\"]} and you sent []"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at checkParams (/Users/zachhamm/Documents/GitHub/PROJECT/node_modules/appium-base-driver/lib/protocol/protocol.js:144:9)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at asyncHandler (/Users/zachhamm/Documents/GitHub/PROJECT/node_modules/appium-base-driver/lib/protocol/protocol.js:280:7)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at /Users/zachhamm/Documents/GitHub/PROJECT/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at Layer.handle [as handle_request] (/Users/zachhamm/Documents/GitHub/PROJECT/node_modules/express/lib/router/layer.js:95:5)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at next (/Users/zachhamm/Documents/GitHub/PROJECT/node_modules/express/lib/router/route.js:144:13)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at Route.dispatch (/Users/zachhamm/Documents/GitHub/PROJECT/node_modules/express/lib/router/route.js:114:3)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at Layer.handle [as handle_request] (/Users/zachhamm/Documents/GitHub/PROJECT/node_modules/express/lib/router/layer.js:95:5)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at /Users/zachhamm/Documents/GitHub/PROJECT/node_modules/express/lib/router/index.js:284:15"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at param (/Users/zachhamm/Documents/GitHub/Validic/goldengate-automation/node_modules/express/lib/router/index.js:365:14)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at param (/Users/zachhamm/Documents/GitHub/Validic/goldengate-automation/node_modules/express/lib/router/index.js:376:14)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at Function.process_params (/Users/zachhamm/Documents/GitHub/PROJECT/node_modules/express/lib/router/index.js:421:3)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at next (/Users/zachhamm/Documents/GitHub/Validic/goldengate-automation/node_modules/express/lib/router/index.js:280:10)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at logger (/Users/zachhamm/Documents/GitHub/PROJECT/node_modules/morgan/index.js:144:5)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at Layer.handle [as handle_request] (/Users/zachhamm/Documents/GitHub/Validic/goldengate-automation/node_modules/express/lib/router/layer.js:95:5)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at trim_prefix (/Users/zachhamm/Documents/GitHub/PROJECT/node_modules/express/lib/router/index.js:328:13)"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C (c8864a2f)]     at /Users/zachhamm/Documents/GitHub/PROJECT/node_modules/express/lib/router/index.js:286:9"}
{"timestamp":1654192647086,"level":"ALL","message":"[W3C] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {\"required\":[\"netspeed\"]} and you sent []"}
{"timestamp":1654192647086,"level":"ALL","message":"[HTTP] \u001b[37m<-- POST /wd/hub/session/c8864a2f-5add-4d72-8651-fd6c7e07514a/appium/device/network_speed \u001b[39m\u001b[33m400\u001b[39m \u001b[90m38 ms - 2409\u001b[39m"}
{"timestamp":1654192647086,"level":"ALL","message":"[HTTP] \u001b[90m\u001b[39m"}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by hammzj** [comment]
Looking at `wdio-protocols/protocols/appium.json`, I think we just need to change the command for the endpoint `/session/:sessionId/appium/device/network_speed"` to be changed to this:

```json
  "/session/:sessionId/appium/device/network_speed": {
    "POST": {
      "command": "toggleNetworkSpeed",
      "description": "Set network speed (Emulator only)",
      "ref": "http://appium.io/docs/en/commands/device/network/network-speed/",
      "parameters": [{
        "name": "networkType",
        "type": "string",
        "description": "Network type",
        "required": true
      }],
      "support": {
        "android": {
          "UiAutomator": "4.2+"
        }
      }
    }
  },
```

**Comment by christian-bromann** [comment]
@hammzj mind raising a PR? I wanted to do a release tomorrow.

**Comment by hammzj** [comment]
Hey @christian-bromann, seems I made a small mistake by incorrectly typing the parameter required. It wants an object parameter defined as `{"required":["networkType"]}` instead of a string. Right now, it's still sending a string array as `["networkType"]`. 

I'm not used to the json representation used by the protocols, but I'll try to get a new branch out there with the correct typing. I apologize for the inconvienence.

**Comment by christian-bromann** [comment]
Oh no worries! Just send another patch and I can release. Cheers!

**Comment by hammzj** [comment]
I added #8402. Hopefully it resolves what I meant to do, but I tested locally using
```js
     const url = `http://localhost:4723/wd/hub/session/${driver.sessionId}/appium/device/network_speed`
     await axios.post(url, {body: {netspeed: 'lte'}})
```
