### ISSUE TITLE
[🐛 Bug]: Error clicking in "a" element in chromedriver version 103

### ISSUE THREAD

**Issue by carri747** [webdriverio/webdriverio#8482]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.13

### Node.js Version

15.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
browserName: 'chrome',
        'goog:chromeOptions': {
            args: [
                '--disable-infobars',
                '--no-sandbox',
                '--disable-gpu',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--window-size=1920,1080'
            ],
            prefs: {
                ['profile.default_content_setting_values.images']: 2
            }
        }


S.O: Windows 10
```

### What happened?

I updated chromedriver version from 102 to 103 due to chrome updated the version and the behavior that worked before the upgrade not it's not working properly now.

The situation:

1. I open a main page where I have a lot of link to click 
2. I find a specific link with a xpath 
3. I click in the link found previously, no problem to found the xpath.
4. The driver click in the link
5. Open the next page associated to the link 
6. Fail with a timeout because it's not possible to click in the previous link. Make not sense because the driver clicked in the link before

### What is your expected behavior?

No timeout trying to click in the link. The same code works with following version:

- Chrome: 101, Chromedriver 101
- Chrome 102 , Chromederiver 102

### How to reproduce the bug.

In a cucumber step click in  "a" element in html

This is more or less the code to reproduce

```
Scenario: Click in link
 Given I click in link

Given('I select sale {string} on landing page', async function (sale: string) {
    const commonPage = new CommonPageObject();
    await commonPage.clickSaleOnLandingPage(saleData);
});

   async clickSaleOnLandingPage(saleData: IAuctionEvent) {
         await (await this.specificSaleOnLandingPage(saleData)).click();   
    }

  async specificSaleOnLandingPage(saleData: IAuctionEvent): Promise<WebdriverIO.Element> {
        return $(`//a[contains(@href, "/sso?SaleID=${saleData.saleId}&SaleNumber=${saleData.saleNumber}")]`);
    }
```

### Relevant log output

```typescript
1) Sale Page labels in "English" language And I select sale "AUCTIONEVENT-SWITZERLAND" on landing page
[chrome 103.0.5060.66 windows #0-2] Error: Can't call elementClick on element with selector "//a[contains(@href, "/sso?SaleID=28937&SaleNumber=19645")]" because element wasn't found
[chrome 103.0.5060.66 windows #0-2] Error: Can't call elementClick on element with selector "//a[contains(@href, "/sso?SaleID=28937&SaleNumber=19645")]" because element wasn't found
[chrome 103.0.5060.66 windows #0-2]     at implicitWait (C:\Dev\git\Christies\AutomationTest\node_modules\webdriverio\build\utils\implicitWait.js:34:19)
[chrome 103.0.5060.66 windows #0-2]     at async C:\Dev\git\Christies\AutomationTest\node_modules\webdriverio\build\utils\refetchElement.js:29:16
[chrome 103.0.5060.66 windows #0-2]     at async Element.elementErrorHandlerCallbackFn (C:\Dev\git\Christies\AutomationTest\node_modules\webdriverio\build\middlewares.js:41:37)
[chrome 103.0.5060.66 windows #0-2]     at async Element.elementErrorHandlerCallbackFn (C:\Dev\git\Christies\AutomationTest\node_modules\webdriverio\build\middlewares.js:24:32)
[chrome 103.0.5060.66 windows #0-2]     at async Element.runCommandWithHooks (C:\Dev\git\Christies\AutomationTest\node_modules\@wdio\sync\build\wrapCommand.js:105:25)
[chrome 103.0.5060.66 windows #0-2]     at Element.runCommandWithHooks (C:\Dev\git\Christies\AutomationTest\node_modules\@wdio\sync\build\wrapCommand.js:100:24)
[chrome 103.0.5060.66 windows #0-2]     at Element.wrapCommandFn (C:\Dev\git\Christies\AutomationTest\node_modules\@wdio\sync\build\wrapCommand.js:67:44)
[chrome 103.0.5060.66 windows #0-2]     at Element.<anonymous> (C:\Dev\git\Christies\AutomationTest\node_modules\@wdio\utils\build\shim.js:270:24)
[chrome 103.0.5060.66 windows #0-2]     at Element.elementErrorHandlerCallback (C:\Dev\git\Christies\AutomationTest\node_modules\webdriverio\build\middlewares.js:48:12)
[chrome 103.0.5060.66 windows #0-2]     at CommonPageObject.<anonymous> (C:\Dev\git\Christies\AutomationTest\src\pageObject\commonPageObject.ts:35:19)
[chrome 103.0.5060.66 windows #0-2]     at fulfilled (C:\Dev\git\Christies\AutomationTest\src\pageObject\commonPageObject.ts:5:58)
[chrome 103.0.5060.66 windows #0-2]     at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide a reproducible example?

**Comment by carri747** [comment]
Scenario: test
        Given test click


```
Given('test click', async function () {
    await browser.url('https://onlineonly.christies.com/s/marc-chagall-colour-life-prints-artists-books-formerly-artists-estate/lots/3244');

    let commonPage = new CommonPageObject();
    let language = await commonPage.testLanguage();
    await (await $('#onetrust-accept-btn-handler')).click();
    await language.click();
//    await browser.pause(5000);
    await (await $('//a[@lang="en"]')).click();    

});
```


```
export default class CommonPageObject {
  async testLanguage(): Promise<ChainablePromiseElement<Promise<WebdriverIO.Element>>> {
        return $('//a[@lang="zh"]');
    }
}
```
You can see that WDIO click cookie popup to accept and after that change the language page to Chinese and after change the language again to English. Result:
- Page change to English 
- Error timeout wafting the button that I clicked previously 


I try the same with **wdio 7.20.5** changing this Promise<ChainablePromiseElement<Promise<WebdriverIO.Element>>> to this Promise<WebdriverIO.Element>

**Comment by erwinheitzman** [comment]
This works just fine however there are a few noteworthy things:

1. the window size matters, if the window is too small it will not show the language buttons
2. you are using an incorrect selector `//a[@lang="zh"]` should be `//a[@lang="zh-cn"]`
3. there's a privacy dialog that interrupts the test, first wait for the dialog, accept the cookies, then you are free continue

**Comment by erwinheitzman** [comment]
Apologies, I accidentally ran the above with the devtools protocol instead of chromedriver. When using Chromedriver this is indeed an issue and I would say that this seems to be an issue in the Chromedriver and not with WebdriverIO, would you agree @christian-bromann ?

**Comment by christian-bromann** [comment]
@erwinheitzman thanks for investigating. It is unlikely that this is a problem with WebdriverIO but I don't want to be draw any conclusions without knowing more. Do you see any difference how the browser behaves between devtools and webdriver? My assumption is that the xPath (`//a[contains(@href, "/sso?SaleID=28937&SaleNumber=19645")]`) is interpreted differently. Can we try with a different selector?

**Comment by erwinheitzman** [comment]
Sure, I can test this later today and will report the findings here

**Comment by christian-bromann** [comment]
Is the element actually there?

**Comment by erwinheitzman** [comment]
Well yeah because it passes in puppeteer so the element is rendered.

**Comment by mbjaved005** [comment]
I've encountered the same problem described in the 5th and 6th points. The button is clicked and the navigation is successful, but the command(click in this case) times out. Setting the retry timeout a little higher and the pageLoadStrategy to 'none' helps a bit but is definitely not the required solution here. The call still times out when multiple features are executed simultaneously especially using saucelabs.

**Comment by carri747** [comment]
I found the same error in Edge. I don't know but maybe it's something regarding because both of them are base in Chromium

**Comment by praveendvd** [comment]
@christian-bromann and @erwinheitzman 

The issue with this is that chromedriver throws error after clicking the element :

 Request failed with status 500 due to unknown error: cannot determine loading status

and after that it retries to find the element again  but by that time the language changes and element is no longer present

**Comment by praveendvd** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3361 ,

**Comment by praveendvd** [comment]
Just wait for all iframes:


```
        await browser.setWindowSize(2000, 2000);
        await browser.url('https://onlineonly.christies.com/s/marc-chagall-colour-life-prints-artists-books-formerly-artists-estate/lots/3244');
        await $('#onetrust-accept-btn-handler').waitForDisplayed();
        await $('#onetrust-accept-btn-handler').click();
        await $('#onetrust-accept-btn-handler').waitForDisplayed({ reverse: true }); // make sure the dialog is gone before continuing to prevent flakyness
        // let b  = await $('//a[@lang="zh-cn"]')
        await browser.waitUntil(
            async () => await $$('//iframe').length === 5,
            {
                timeout: 60 * 1000, // 60 seconds
                timeoutMsg: 'Message on failure'
            }
        );
        await $('//a[@lang="zh-cn"]').click();
```

**Comment by erwinheitzman** [comment]
@praveendvd that shouldn't be needed though

**Comment by praveendvd** [comment]
@erwinheitzman yes but waiting for iframe or adding an implicit wait fixes the issue , it doesnt seems to be wdio related
