### ISSUE TITLE
[🐛 Bug]: waitForExist(reverse=true) throws exception when element is not found using devtools automationProtocol mode with browser.setTimeout({ 'implicit': xxxx });

### ISSUE THREAD

**Issue by chanyk-joseph** [webdriverio/webdriverio#8521]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        maxInstances: 1,
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
            args: ['--start-maximized', '--no-sandbox', '--ignore-certificate-errors', '--remote-debugging-port=9222'],
            prefs: {
                download: {
                    prompt_for_download: false,
                    default_directory: '/tmp/',
                }
            }
        },

        'wdio:devtoolsOptions': {
            customPort: 9222
        }
    }
```

### What happened?

Querying non-existing element with `reverse=true` throw exception
The issue only happens on `devtools` mode, while `webdriver` mode works fine

```javascript
await $('//*[@class="spinner ng-binding"]').waitForExist({
    timeout: 5000,
    reverse: true,
    timeoutMsg: 'Loading widget does not go away after 5s'
});
```

Errors:
waiting for XPath `//*[@class="spinner ng-binding"]` failed: timeout 2000ms exceeded

### What is your expected behavior?

No exception should be thrown when reverse is set to true while the element does not exist

### How to reproduce the bug.

1. Use devtools mode as 'automationProtocol'
2. go to google and wait for a non-existing element with reverse=true

### Relevant log output

```typescript
waiting for XPath `//*[@class="spinner ng-binding"]` failed: timeout 2000ms exceeded
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
Hi, I'm sorry but I was not able to reproduce this issue.

Can you provide a reproduction path that always works?
I suggest generating a new project using the CLI as follows to test if this is an issue in the latest version:
```
npm init wdio ./path/to/new/project
// example: npm init wdio ./wdio-8521
```
During the configuration, don't install a driver and it will automatically use the CDP, however if you want you can still set the `automationProtocol: 'devtools',` but it won't make a difference.

Replace the testcase with the following:
```js
describe('my example', () => {
    it('shows an issue', async () => {
        await browser.url('https://webdriver.io');
        await $('//*[@class="spinner ng-binding"]').waitForExist({ reverse: true });
    });
});
```

You'll see that the test passes without issues.

**Comment by chanyk-joseph** [comment]
Hi @erwinheitzman ,
I managed to reproduce the issue. It is related to `await browser.setTimeout({ 'implicit': xxxxxxx });`

```
describe('Test', () => {
    it('Without setting browser implicit timeout', async () => {
        await browser.url("https://www.google.com.hk");
        await $('//*[@class="spinner ng-binding"]').waitForExist({
            timeout: 5000,
            reverse: true
        });
    });

    it('Setting browser implicit timeout', async () => {
        console.log('=== Setting Implicit Timeout ===');
        
        await browser.setTimeout({ 'implicit': 5000 });
        await browser.url("https://www.google.com.hk");
        await $('//*[@class="spinner ng-binding"]').waitForExist({
            timeout: 5000,
            reverse: true
        });
    });
});
```

Result:
```
2022-07-15T06:33:12.738Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-07-15T06:33:12.740Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-07-15T06:33:12.741Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js
[0-0] 2022-07-15T06:33:13.054Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - /test/specs/example.e2e.js
[0-0] 2022-07-15T06:33:13.154Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-0] 2022-07-15T06:33:13.154Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --no-sandbox --ignore-certificate-errors --remote-debugging-port=9222
[0-0] 2022-07-15T06:33:13.693Z INFO devtools: Connect Puppeteer with browser on port 9222
[0-0] 2022-07-15T06:33:13.778Z INFO devtools: COMMAND navigateTo("https://www.google.com.hk/")
[0-0] 2022-07-15T06:33:17.276Z INFO devtools: RESULT null
[0-0] 2022-07-15T06:33:17.282Z INFO devtools: COMMAND findElement("xpath", "//*[@class="spinner ng-binding"]")
[0-0] 2022-07-15T06:33:17.287Z INFO devtools: RESULT Error: Element with selector "//*[@class="spinner ng-binding"]" not found
[0-0]     at DevToolsDriver.findElement (/tmp/wdio-test/node_modules/devtools/build/utils.js:104:16)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0]     at async Browser.wrappedCommand (/tmp/wdio-test/node_modules/devtools/build/devtoolsdriver.js:102:26)
[0-0]     at async Browser.wrapCommandFn (/tmp/wdio-test/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async Browser.$ (/tmp/wdio-test/node_modules/webdriverio/build/commands/browser/$.js:91:17)
[0-0]     at async Browser.wrapCommandFn (/tmp/wdio-test/node_modules/@wdio/utils/build/shim.js:137:29)
[0-0]     at async UserContext.<anonymous> (/tmp/wdio-test/test/specs/example.e2e.js:7:9)
[0-0] 2022-07-15T06:33:17.294Z INFO devtools: COMMAND findElements("xpath", "//*[@class="spinner ng-binding"]")
[0-0] 2022-07-15T06:33:17.297Z INFO devtools: RESULT []
[0-0] === Setting Implicit Timeout ===
[0-0] 2022-07-15T06:33:17.304Z INFO devtools: COMMAND setTimeouts(5000, undefined, undefined)
[0-0] 2022-07-15T06:33:17.304Z INFO devtools: RESULT null
[0-0] 2022-07-15T06:33:17.306Z INFO devtools: COMMAND navigateTo("https://www.google.com.hk/")
[0-0] 2022-07-15T06:33:18.064Z INFO devtools: RESULT null
[0-0] 2022-07-15T06:33:18.071Z INFO devtools: COMMAND findElement("xpath", "//*[@class="spinner ng-binding"]")
[0-0] 2022-07-15T06:33:23.075Z INFO devtools: COMMAND takeScreenshot()
[0-0] 2022-07-15T06:33:23.173Z INFO devtools: RESULT iVBORw0KGgoAAAANSUhEUgAABLAAAAMOCAYAAAAORv9EAAAAAXNSR0IArs4c6...
[0-0] Error in "Test Setting browser implicit timeout"
waiting for XPath `//*[@class="spinner ng-binding"]` failed: timeout 5000ms exceeded
TimeoutError: waiting for XPath `//*[@class="spinner ng-binding"]` failed: timeout 5000ms exceeded
[0-0] 2022-07-15T06:33:23.185Z INFO devtools: COMMAND deleteSession()
[0-0] 2022-07-15T06:33:23.186Z INFO devtools: RESULT null
[0-0] FAILED in chrome - /test/specs/example.e2e.js
2022-07-15T06:33:23.294Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-07-15T06:33:23.294Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[Chrome 99.0.4844.82 linux #0-0] Running: Chrome (v99.0.4844.82) on linux
[Chrome 99.0.4844.82 linux #0-0] Session ID: 533c29a9-7ae0-4e3d-a136-02c715ac8371
[Chrome 99.0.4844.82 linux #0-0]
[Chrome 99.0.4844.82 linux #0-0] » /test/specs/example.e2e.js
[Chrome 99.0.4844.82 linux #0-0] Test
[Chrome 99.0.4844.82 linux #0-0]    ✓ Without setting browser implicit timeout
[Chrome 99.0.4844.82 linux #0-0]    ✖ Setting browser implicit timeout
[Chrome 99.0.4844.82 linux #0-0]
[Chrome 99.0.4844.82 linux #0-0] 1 passing (9.4s)
[Chrome 99.0.4844.82 linux #0-0] 1 failing
[Chrome 99.0.4844.82 linux #0-0]
[Chrome 99.0.4844.82 linux #0-0] 1) Test Setting browser implicit timeout
[Chrome 99.0.4844.82 linux #0-0] TimeoutError: waiting for XPath `//*[@class="spinner ng-binding"]` failed: timeout 5000ms exceeded
[Chrome 99.0.4844.82 linux #0-0] waiting for XPath `//*[@class="spinner ng-binding"]` failed: timeout 5000ms exceeded
[Chrome 99.0.4844.82 linux #0-0] TimeoutError: waiting for XPath `//*[@class="spinner ng-binding"]` failed: timeout 5000ms exceeded
```

**Comment by chanyk-joseph** [comment]
The issue happens even the implicit timeout is larger than the timeout in waitForExist, ie.
```
await browser.setTimeout({ 'implicit': 5000 });
await $('//*[@class="spinner ng-binding"]').waitForExist({
          timeout: 2000,
          reverse: true
}); // <==== exception
```

**Comment by christian-bromann** [comment]
We do not recommend to use implicit timeouts at all. I will add a note to the `setTimeout` docs.

**Comment by yogeshgadge** [comment]
I have no implicit timeout but waitForExist({ reverse: true }) fails with devtools

**Comment by gr0l** [comment]
Same here. With or without implicit timeout I get this error when using devtools.
