### ISSUE TITLE
[🐛 Bug]: element click fails with 'javascript error: Cannot read properties of undefined (reading 'defaultView')'

### ISSUE THREAD

**Issue by sezaru** [webdriverio/webdriverio#8588]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.20.7

### Node.js Version

v16.15.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  'goog:loggingPrefs': { browser: 'ALL' },
  'goog:chromeOptions': { binary: '/usr/bin/google-chrome', w3c: false }
}
```

### What happened?

If you have a button element added as a shadow dom via javascript and you try to click on it, the click action will fail with the following error:
```sh
2022-07-25T14:52:26.569Z ERROR webdriver: Request failed with status 500 due to javascript error: javascript error: Cannot read properties of undefined (reading 'defaultView')
```
This only happens if running wdio with the `chromedriver`, running it directly in chrome works fine.

Running the click action using javascript directly works as expected:
```js
await browser.execute("arguments[0].click();", element)
```

### What is your expected behavior?

I expected that the command
```js
await element.click()
```
would simply work.

### How to reproduce the bug.

Since reproducing the bug requires `chromedriver` setup, I created a minimal code project in a repository to make easier, you can clone it here: https://github.com/sezaru/webdriverio_bug

That project contains the `main.js` file which will start the `chromedriver` server, it will load the page, query the button element and try to click.

Also, in the `pages` directory you can find the HTML file used to trigger the bug, as described in the `README.md` you can server it using the command `python3 -m http.server 4000`.

### Relevant log output

```typescript
2022-07-25T14:52:26.535Z WARN webdriver: Request failed with status 500 due to javascript error: Cannot read properties of undefined (reading 'defaultView')
  (Session info: chrome=103.0.5060.134)
2022-07-25T14:52:26.553Z WARN webdriver: Request failed with status 500 due to javascript error: Cannot read properties of undefined (reading 'defaultView')
  (Session info: chrome=103.0.5060.134)
2022-07-25T14:52:26.569Z ERROR webdriver: Request failed with status 500 due to javascript error: javascript error: Cannot read properties of undefined (reading 'defaultView')
  (Session info: chrome=103.0.5060.134)
/home/sezdocs/projects/ssc/gi/wdio/node_modules/webdriver/build/utils.js:198
    return new CustomRequestError(body, requestOptions);
           ^

javascript error: javascript error: Cannot read properties of undefined (reading 'defaultView')
  (Session info: chrome=103.0.5060.134)
    at getErrorFromResponseBody (/home/sezdocs/projects/ssc/gi/wdio/node_modules/webdriver/build/utils.js:198:12)
    at NodeJSRequest._request (/home/sezdocs/projects/ssc/gi/wdio/node_modules/webdriver/build/request/index.js:166:60)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Element.wrapCommandFn (/home/sezdocs/projects/ssc/gi/wdio/node_modules/@wdio/utils/build/shim.js:137:29)
    at async Element.wrapCommandFn (/home/sezdocs/projects/ssc/gi/wdio/node_modules/@wdio/utils/build/shim.js:137:29)
    at async Element.elementErrorHandlerCallbackFn (/home/sezdocs/projects/ssc/gi/wdio/node_modules/webdriverio/build/middlewares.js:24:32)
    at async Element.wrapCommandFn (/home/sezdocs/projects/ssc/gi/wdio/node_modules/@wdio/utils/build/shim.js:137:29)
    at async Element.wrapCommandFn (/home/sezdocs/projects/ssc/gi/wdio/node_modules/@wdio/utils/build/shim.js:137:29)
    at async Element.elementErrorHandlerCallbackFn (/home/sezdocs/projects/ssc/gi/wdio/node_modules/webdriverio/build/middlewares.js:24:32)
    at async Element.wrapCommandFn (/home/sezdocs/projects/ssc/gi/wdio/node_modules/@wdio/utils/build/shim.js:137:29)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting the issue.

It seems this problem has been [already reported](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3684) within the Chromedriver project. There is nothing we can fix within WebdriverIO. I commented on the Chromedriver issue with a reference to this issue. Let's hope it will be fixed soon.
