### ISSUE TITLE
[🐛 Bug]: Click does not work properly in safari on ember drop downs

### ISSUE THREAD

**Issue by rameshkumarj** [webdriverio/webdriverio#8696]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      browserName: 'safari',
        os: 'OS X',
        osVersion: 'Big Sur'
}
```

### What happened?

When trying to click on ember power select dropdowns, either
1. The element is not clicked at all but wdio understands as click complete
2. The click is completed in the application but wdio thinks it is not and starts retrying click

This happens only with safari browser

### What is your expected behavior?

Click should happen properly and work as in chrome or edge

### How to reproduce the bug.

sample repo https://github.com/rameshkumarj/wdioTest/tree/main

### Relevant log output

```typescript
npx wdio wdio.conf.js

Execution of 1 workers started at 2022-08-10T21:12:05.112Z

2022-08-10T21:12:05.114Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-08-10T21:12:05.116Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-08-10T21:12:05.117Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.conf.js
[0-0] 2022-08-10T21:12:05.543Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2022-08-10T21:12:05.546Z DEBUG @wdio/config:ConfigParser: No compiler found, continue without compiling files
[0-0] 2022-08-10T21:12:05.601Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] RUNNING in safari - C:\Users\rames\wdioProject\features\test.feature
[0-0] 2022-08-10T21:12:06.094Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2022-08-10T21:12:06.096Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-08-10T21:12:06.159Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session
[0-0] 2022-08-10T21:12:06.159Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'safari',
[0-0]       os: 'OS X',
[0-0]       osVersion: 'Big Sur',
[0-0]       acceptInsecureCerts: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'safari',
[0-0]     os: 'OS X',
[0-0]     osVersion: 'Big Sur',
[0-0]     acceptInsecureCerts: true
[0-0]   }
[0-0] }
[0-0] 2022-08-10T21:12:12.040Z INFO webdriver: COMMAND setTimeouts(undefined, 90000, 110000)
[0-0] 2022-08-10T21:12:12.041Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/timeouts
[0-0] 2022-08-10T21:12:12.041Z INFO webdriver: DATA { pageLoad: 90000, script: 110000 }
[0-0] 2022-08-10T21:12:12.041Z INFO webdriver: COMMAND maximizeWindow()
[0-0] 2022-08-10T21:12:12.042Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/window/maximize     
[0-0] 2022-08-10T21:12:12.043Z DEBUG @wdio/utils:shim: Finished to run "before" hook in 2ms
[0-0] 2022-08-10T21:12:12.084Z INFO webdriver: COMMAND navigateTo("https://api.emberjs.com/ember/release")
[0-0] 2022-08-10T21:12:12.085Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/url
[0-0] 2022-08-10T21:12:12.085Z INFO webdriver: DATA { url: 'https://api.emberjs.com/ember/release' }
[0-0] 2022-08-10T21:12:12.764Z INFO webdriver: COMMAND findElement("css selector", ".ember-power-select-trigger")
[0-0] 2022-08-10T21:12:12.764Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/element
[0-0] 2022-08-10T21:12:12.764Z INFO webdriver: DATA { using: 'css selector', value: '.ember-power-select-trigger' }
[0-0] 2022-08-10T21:12:12.811Z INFO webdriver: RESULT { y: 25, x: 0, width: 1920, height: 1055 }
[0-0] 2022-08-10T21:12:14.110Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'node-C4B6B44C-8489-4BCA-ADAA-1204E1826475'
[0-0] }
[0-0] 2022-08-10T21:12:14.116Z INFO webdriver: COMMAND elementClick("node-C4B6B44C-8489-4BCA-ADAA-1204E1826475")
[0-0] 2022-08-10T21:12:14.116Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/element/node-C4B6B44C-8489-4BCA-ADAA-1204E1826475/click
[0-0] 2022-08-10T21:12:14.525Z INFO webdriver: COMMAND findElement("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:14.526Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/element
[0-0] 2022-08-10T21:12:14.526Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:14.670Z INFO webdriver: RESULT { error: 'no such element', message: '', stacktrace: '' }
[0-0] 2022-08-10T21:12:14.676Z DEBUG webdriverio: command click was called on an element ("li[data-option-index="3"") that wasn't found, waiting for it...
[0-0] 2022-08-10T21:12:14.678Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:14.678Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:14.678Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:14.766Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:15.186Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:15.186Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:15.186Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:15.241Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:15.687Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:15.688Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:15.688Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:15.769Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:16.186Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:16.186Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:16.186Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:16.248Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:16.685Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:16.685Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:16.685Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:16.756Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:17.186Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:17.187Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:17.187Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:17.346Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:17.686Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:17.686Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:17.686Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:17.742Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:18.184Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:18.185Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:18.185Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:18.241Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:18.686Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:18.686Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:18.687Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:18.743Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:19.192Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:19.193Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:19.193Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:19.251Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:19.688Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:19.688Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:19.688Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:19.971Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:20.187Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:20.187Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:20.187Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:20.256Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:20.690Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:20.691Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:20.691Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:20.797Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:21.187Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:21.187Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:21.188Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:21.254Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:21.688Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:21.689Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:21.689Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:21.783Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:22.179Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:22.179Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:22.179Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:22.264Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:22.680Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:22.680Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:22.680Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:22.739Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:23.188Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:23.188Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:23.188Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:23.253Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:23.684Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:23.684Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:23.684Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:23.803Z INFO webdriver: RESULT []
[0-0] 2022-08-10T21:12:24.177Z INFO webdriver: COMMAND findElements("css selector", "li[data-option-index="3"")
[0-0] 2022-08-10T21:12:24.177Z INFO webdriver: [POST] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957/elements
[0-0] 2022-08-10T21:12:24.177Z INFO webdriver: DATA { using: 'css selector', value: 'li[data-option-index="3"' }
[0-0] 2022-08-10T21:12:24.233Z INFO webdriver: RESULT []
[0-0] Error in "0: Given Launch url and click ember dropdown"
Error: Can't call click on element with selector "li[data-option-index="3"" because element wasn't found
    at implicitWait (C:\Users\rames\wdioProject\node_modules\webdriverio\build\utils\implicitWait.js:34:19)
    at async Element.elementErrorHandlerCallbackFn (C:\Users\rames\wdioProject\node_modules\webdriverio\build\middlewares.js:20:29)
    at async Element.wrapCommandFn (C:\Users\rames\wdioProject\node_modules\@wdio\utils\build\shim.js:137:29)
    at async World.<anonymous> (C:\Users\rames\wdioProject\features\step-definitions\test.steps.js:8:5)
[0-0] 2022-08-10T21:12:24.691Z INFO webdriver: COMMAND deleteSession()
[0-0] 2022-08-10T21:12:24.691Z INFO webdriver: [DELETE] https://hub.browserstack.com/wd/hub/session/a879e22707e83f04915b952e9f39e2d5a4c99957
[0-0] 2022-08-10T21:12:25.568Z INFO webdriver: RESULT 
2022-08-10T21:12:25.681Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in safari - C:\Users\rames\wdioProject\features\test.feature
2022-08-10T21:12:25.683Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-08-10T21:12:25.684Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[Safari 14.1.2 macOS #0-0] Running: Safari (v14.1.2) on macOS
[Safari 14.1.2 macOS #0-0] Session ID: a879e22707e83f04915b952e9f39e2d5a4c99957
[Safari 14.1.2 macOS #0-0]
[Safari 14.1.2 macOS #0-0] » C:\Users\rames\wdioProject\features\test.feature
[Safari 14.1.2 macOS #0-0] Test the ember dropdown
[Safari 14.1.2 macOS #0-0] Verify click of ember dropdown
[Safari 14.1.2 macOS #0-0]    ✖ Given Launch url and click ember dropdown
[Safari 14.1.2 macOS #0-0]
[Safari 14.1.2 macOS #0-0] 1 failing (13.5s)
[Safari 14.1.2 macOS #0-0]
[Safari 14.1.2 macOS #0-0] 1) Verify click of ember dropdown Given Launch url and click ember dropdown
[Safari 14.1.2 macOS #0-0] Error: Can't call click on element with selector "li[data-option-index="3"" because element wasn't found
[Safari 14.1.2 macOS #0-0] Error: Can't call click on element with selector "li[data-option-index="3"" because element wasn't found
[Safari 14.1.2 macOS #0-0]     at implicitWait (C:\Users\rames\wdioProject\node_modules\webdriverio\build\utils\implicitWait.js:34:19)
[Safari 14.1.2 macOS #0-0]     at async Element.elementErrorHandlerCallbackFn (C:\Users\rames\wdioProject\node_modules\webdriverio\build\middlewares.js:20:29) 
[Safari 14.1.2 macOS #0-0]     at async Element.wrapCommandFn (C:\Users\rames\wdioProject\node_modules\@wdio\utils\build\shim.js:137:29)
[Safari 14.1.2 macOS #0-0]     at async World.<anonymous> (C:\Users\rames\wdioProject\features\step-definitions\test.steps.js:8:5)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:20

2022-08-10T21:12:25.691Z INFO @wdio/local-runner: Shutting down spawned worker
2022-08-10T21:12:25.948Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-08-10T21:12:25.949Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
You are missing a closing bracket:
```patch
- await $('li[data-option-index="3"').click()
+ await $('li[data-option-index="3"]').click()
```

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
