### ISSUE TITLE
[🐛 Bug]: Make CLI compatible with v8

### ISSUE THREAD

**Issue by erwinheitzman** [webdriverio/webdriverio#8799]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.14.2

### Mode

WDIO Testrunner

### What happened?

When generating a Typescript project using the CLI of v8, the generated project does not work.

### What is your expected behavior?

I expect to be able to generate working projects with the CLI.

### How to reproduce the bug.

```
npm init wdio ./generate-wdio-v8-project
cd generate-wdio-v8-project
node --loader ts-node/esm ./node_modules/.bin/wdio run test/wdio.conf.ts
```

### Relevant log output

```typescript
> wdiov8@1.0.0 wdio
> node --loader ts-node/esm ./node_modules/.bin/wdio run wdio.conf.ts

(node:29616) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
2022-09-01T16:03:01.888Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/me/Documents/dev/generate-wdio-v8-project/wdio.conf.ts: addConfigEntry requires config key
Error: addConfigEntry requires config key
    at ConfigParser.addConfigFile (file:///Users/me/Documents/dev/generate-wdio-v8-project/node_modules/@wdio/config/build/lib/ConfigParser.js:36:23)
    at async Launcher.run (file:///Users/me/Documents/dev/generate-wdio-v8-project/node_modules/@wdio/cli/build/launcher.js:36:9)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
How did you make sure you were running `v8`?

> npm init wdio ./generate-wdio-v8-project

This downloads the CLI from `v7`.

**Comment by erwinheitzman** [comment]
hey @christian-bromann apoligies I tried to create a short summary but forgot that this installs v7, what I did was the following:
```
mkdir generate-wdio-v8-project
cd generate-wdio-v8-project
npm i @wdio/cli@next
npx wdio/cli config
```

By now it seems like it will give a different issue as this fails earlier.

**Comment by erwinheitzman** [comment]
The packages I used are as follows:
```
    "@wdio/cli": "^8.0.0-alpha.249",
    "@wdio/globals": "^8.0.0-alpha.249",
    "@wdio/local-runner": "^8.0.0-alpha.249",
    "@wdio/mocha-framework": "^8.0.0-alpha.249",
    "@wdio/spec-reporter": "^8.0.0-alpha.249",
    "chromedriver": "^105.0.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.2",
    "wdio-chromedriver-service": "^8.0.0-alpha.1",
    "webdriverio": "^8.0.0-alpha.249"
```

**Comment by erwinheitzman** [comment]
I can also push the repo and link it

**Comment by erwinheitzman** [comment]
Debugged it and the issue of the `addConfigEntry requires config key` is due to the import of the config containing the default property as shown here:
```js
{
  default: {
    config: {
      autoCompileOpts: [Object],
      specs: [Array],
      exclude: [],
      maxInstances: 10,
      capabilities: [Array],
      logLevel: 'info',
      bail: 0,
      baseUrl: 'http://localhost',
      waitforTimeout: 10000,
      connectionRetryTimeout: 120000,
      connectionRetryCount: 3,
      services: [Array],
      framework: 'mocha',
      reporters: [Array],
      mochaOpts: [Object]
    }
  }
}
```

**Comment by erwinheitzman** [comment]
If I change the ConfigParser from
```js
const config = (await this._pathService.loadFile(filePath)).config;
```
to
```js
let config;

const configFile = await this._pathService.loadFile(filePath);

if (configFile.default) {
   config = configFile.default.config;
} else {
   config = configFile.config;
}
```
then it works

**Comment by christian-bromann** [comment]
Fixed with https://github.com/webdriverio/webdriverio/commit/ea33c6a97523a726882fd93515f3de5eceb914ff
