### ISSUE TITLE
[🐛 Bug]: Import statements are throwing errors 

### ISSUE THREAD

**Issue by chidaquest** [webdriverio/webdriverio#8857]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest

### Mode

Standalone Mode

### What happened?

Error:  Cannot use import statement outside a module

This is the error message it is throwing. We have a protractor based project which we are trying to migrate and run in wdio. It contains feature files, step definition files and po ts files.

DevTools listening on ws://127.0.0.1:54487/devtools/browser/d4be1c28-562f-46cf-befc-622577f3ab0d
[0-0] 2022-09-14T12:21:56.237Z ERROR @wdio/runner: *********\steps\login.step.ts5
[0-0]import { HomeScreen } from '../../pages/homeScreen/homeScreen.po';
[0-0] ^^^^^^

Related code snippet:
import { HomeScreen } from '../../pages/homeScreen/homeScreen.po';
let homeScreen : HomeScreen = new HomeScreen();
await homeScreen.clickMobileSettings();

But when we change the import and let statements to the following it works fine.
var homeScreen = require('../pages/homeScreen/homeScreen.po');
it works. 

Codemod is not able to make this change as well. What is the way to use import and let statements in wdio?

### How to reproduce the bug.

login.step.ts file 

import { HomeScreen } from '../../pages/homeScreen/homeScreen.po';
let homeScreen : HomeScreen = new HomeScreen();

When(/^the user navigates to Account Settings page$/,gotoAccountSetting);
async function gotoAccountSetting(){ 
        await homeScreen.clickMobileSettings();
}

### Relevant log output

```typescript
PS C:\code\> npx wdio .\test\wdio-e2e.conf.ts

Execution of 1 spec files started at 2022-09-14T12:21:50.492Z

2022-09-14T12:21:50.637Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-09-14T12:21:50.647Z INFO chromedriver: Start Chromedriver (****\chromedriver\lib\chromedriver\chromedriver.exe) with args --port=9515 --url-base=/
2022-09-14T12:21:50.854Z INFO chromedriver: Starting ChromeDriver 105.0.5195.52 (412c95e518836d8a7d97250d62b29c2ae6a26a85-refs/branch-heads/5195@{#853}) on port 9515
2022-09-14T12:21:50.854Z INFO chromedriver: Only local connections are allowed.
2022-09-14T12:21:50.855Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2022-09-14T12:21:50.867Z INFO chromedriver: ChromeDriver was started successfully.
2022-09-14T12:21:50.918Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-09-14T12:21:50.920Z INFO @wdio/local-runner: Start worker 0-0 with arg: .\test\wdio-e2e.conf.ts
[0-0] 2022-09-14T12:21:51.980Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - ****.feature
[0-0] 2022-09-14T12:21:53.949Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-09-14T12:21:53.959Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2022-09-14T12:21:53.959Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }

DevTools listening on ws://127.0.0.1:54487/devtools/browser/d4be1c28-562f-46cf-befc-622577f3ab0d
[0-0] 2022-09-14T12:21:56.237Z ERROR @wdio/runner: ****\pages\login.po.ts:5
[0-0] import { HomeScreen } from '../../pages/homeScreen/homeScreen.po';
[0-0] ^^^^^^
[0-0]
[0-0] SyntaxError: Cannot use import statement outside a module
[0-0]     at wrapSafe (internal/modules/cjs/loader.js:979:16)
[0-0]     at Module._compile (internal/modules/cjs/loader.js:1027:27)
[0-0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0-0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0-0]     at Module._load (internal/modules/cjs/loader.js:769:14)
[0-0]     at Function.hookedLoader [as _load] (****\mockery\mockery.js:111:12)
[0-0]     at Module.require (internal/modules/cjs/loader.js:952:19)
[0-0]     at require (internal/modules/cjs/helpers.js:88:18)
[0-0]     at Object.<anonymous> (****.step.ts:3:17)
[0-0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0-0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0-0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0-0]     at Module._load (internal/modules/cjs/loader.js:769:14)
[0-0]     at Function.hookedLoader [as _load] (****\node_modules\mockery\mockery.js:111:12)
[0-0]     at Module.require (internal/modules/cjs/loader.js:952:19)
[0-0]     at require (internal/modules/cjs/helpers.js:88:18)
[0-0]  Error:  Cannot use import statement outside a module
[0-0] 2022-09-14T12:21:56.238Z INFO webdriver: COMMAND deleteSession()
[0-0] 2022-09-14T12:21:56.245Z INFO webdriver: [DELETE] http://localhost:9515/session/92a9b65f7107e436962cc6dd382b028f   
[0-0] FAILED in chrome - ****.feature
2022-09-14T12:21:56.780Z INFO @wdio/cli:launcher: Run onComplete hook

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:06

2022-09-14T12:21:56.782Z INFO @wdio/local-runner: Shutting down spawned worker
2022-09-14T12:21:57.035Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-09-14T12:21:57.037Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by skumary** [comment]
> > What is the way to use import and let statements in wdio?
> 
> You currently have to use Babel (see https://webdriver.io/docs/babel) to transpile the code down to CJS. With WebdriverIO v8 which will be released soon you can use this natively with ESM.

It still don't work with the suggestion you're making

**Comment by christian-bromann** [comment]
@skumary please be more specific! My comment refers to the original authors issue which can be totally different from yours.

**Comment by skumary** [comment]
> @skumary please be more specific! My comment refers to the original authors issue which can be totally different from yours.

I have exactly the same issue sire
Im getting this error while trying to import wdio.conf.js to another config file
import { config } from '../wdio.conf.js';
^^^^^^
SyntaxError: Cannot use import statement outside a module

I tried the following so far:
Added require: ["@babel/register"] to mochaOpts

Updated the node version(14) to my current node veersion (18) in the babel.conf.js

Reinstalled @babel/core, @babel/cli, @babel/preset-env, @babel/register along with npm

added this in both wdio.conf.js and then also tried adding it to the conf file Im trying to import it to.
**beforeSession: function (config, capabilities, specs, cid) {
        require('@babel/register');
    }**

**Comment by christian-bromann** [comment]
@skumary can you provide a minimal reproducible example? Have you tried to start a new WebdriverIO project `npm init wdio@latest ./test` and compare the setup with yours?
