### ISSUE TITLE
[🐛 Bug]: ECONNRESET on setCookies 

### ISSUE THREAD

**Issue by egerix** [webdriverio/webdriverio#8866]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.24.0

### Node.js Version

16.10.0

### Mode

Standalone Mode

### What happened?

When using the setCookies method to send a large array of cookies, an error occurs:
```
[chrome 105.0.5195.125 mac os x #0-0] connect ECONNRESET 127.0.0.1:9515
[chrome 105.0.5195.125 mac os x #0-0] RequestError: connect ECONNRESET 127.0.0.1:9515
[chrome 105.0.5195.125 mac os x #0-0]     at ClientRequest.<anonymous> (/Users/egexiii/WebstormProjects/wdio-m1-problem/node_modules/got/dist/source/core/index.js:970:111)
[chrome 105.0.5195.125 mac os x #0-0]     at Object.onceWrapper (events.js:482:26)
[chrome 105.0.5195.125 mac os x #0-0]     at ClientRequest.emit (events.js:387:35)
[chrome 105.0.5195.125 mac os x #0-0]     at ClientRequest.emit (domain.js:470:12)
[chrome 105.0.5195.125 mac os x #0-0]     at ClientRequest.origin.emit (/Users/egexiii/WebstormProjects/wdio-m1-problem/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[chrome 105.0.5195.125 mac os x #0-0]     at Socket.socketErrorListener (_http_client.js:475:9)
[chrome 105.0.5195.125 mac os x #0-0]     at Socket.emit (events.js:375:28)
[chrome 105.0.5195.125 mac os x #0-0]     at Socket.emit (domain.js:470:12)
[chrome 105.0.5195.125 mac os x #0-0]     at emitErrorNT (internal/streams/destroy.js:106:8)
[chrome 105.0.5195.125 mac os x #0-0]     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[chrome 105.0.5195.125 mac os x #0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
```
setCookies internally uses promiseAll, there is no error if the requests are sent sequentially

Most simply the problem is repeated on the macbook m1 but I also get the problem on the macbook i7

### What is your expected behavior?

я думаю метод setCookies не должен использовать Promise.All

### How to reproduce the bug.

```js
describe('Sample to reproduce problem', () => {

    function getCookiesArray() {
        const cookies = [];
        for (let i = 0; i < 60; i++) {
            cookies.push(
                {
                    expires: "2038-01-19T03:14:07.000Z",
                    httponly: true,
                    secure: true,
                    path: '/',
                    domain: '.youtube.com',
                    samesite: 'None',
                    name: 'session' + i,
                    value: '123qwweds1234123REQFASDVER28r0f9udjvijfh2breofjvbcovbhob4orjfbvjhvbh4'
                }
            )
        }
        return cookies;
    }

    // An error appears in this test
    // connect ECONNRESET 127.0.0.1:9515
    it('failed cookies setup', async () => {
        await browser.url(`https://youtube.com`);
        await browser.setCookies(getCookiesArray())
    });

    //this test passes successfully
    it('success cookies setup', async () => {
        await browser.url(`https://youtube.com`);
        for (const cookie of getCookiesArray()) {
            await browser.setCookies(cookie);
        }
    });
});
```

### Relevant log output

```typescript
[chrome 105.0.5195.125 mac os x #0-0] Running: chrome (v105.0.5195.125) on mac os x
[chrome 105.0.5195.125 mac os x #0-0] Session ID: 76a9dd759bfc54f61f9f66a8b608d360
[chrome 105.0.5195.125 mac os x #0-0]
[chrome 105.0.5195.125 mac os x #0-0] » /test/specs/cookiesSetup.js
[chrome 105.0.5195.125 mac os x #0-0] Sample to reproduce problem
[chrome 105.0.5195.125 mac os x #0-0]    ✖ failed cookies setup
[chrome 105.0.5195.125 mac os x #0-0]    ✓ success cookies setup
[chrome 105.0.5195.125 mac os x #0-0]
[chrome 105.0.5195.125 mac os x #0-0] 1 passing (1.2s)
[chrome 105.0.5195.125 mac os x #0-0] 1 failing
[chrome 105.0.5195.125 mac os x #0-0]
[chrome 105.0.5195.125 mac os x #0-0] 1) Sample to reproduce problem failed cookies setup
[chrome 105.0.5195.125 mac os x #0-0] connect ECONNRESET 127.0.0.1:9515
[chrome 105.0.5195.125 mac os x #0-0] RequestError: connect ECONNRESET 127.0.0.1:9515
[chrome 105.0.5195.125 mac os x #0-0]     at ClientRequest.<anonymous> (/Users/egexiii/WebstormProjects/wdio-m1-problem/node_modules/got/dist/source/core/index.js:970:111)
[chrome 105.0.5195.125 mac os x #0-0]     at Object.onceWrapper (events.js:482:26)
[chrome 105.0.5195.125 mac os x #0-0]     at ClientRequest.emit (events.js:387:35)
[chrome 105.0.5195.125 mac os x #0-0]     at ClientRequest.emit (domain.js:470:12)
[chrome 105.0.5195.125 mac os x #0-0]     at ClientRequest.origin.emit (/Users/egexiii/WebstormProjects/wdio-m1-problem/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
[chrome 105.0.5195.125 mac os x #0-0]     at Socket.socketErrorListener (_http_client.js:475:9)
[chrome 105.0.5195.125 mac os x #0-0]     at Socket.emit (events.js:375:28)
[chrome 105.0.5195.125 mac os x #0-0]     at Socket.emit (domain.js:470:12)
[chrome 105.0.5195.125 mac os x #0-0]     at emitErrorNT (internal/streams/destroy.js:106:8)
[chrome 105.0.5195.125 mac os x #0-0]     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
[chrome 105.0.5195.125 mac os x #0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:06 

2022-09-18T16:47:22.099Z INFO @wdio/local-runner: Shutting down spawned worker
2022-09-18T16:47:22.349Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-09-18T16:47:22.349Z INFO @wdio/local-runner: shutting down
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriverio-tests@0.1.0 wdio: `wdio run wdio.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webdriverio-tests@0.1.0 wdio script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

I agree, unfortunately some driver don't like many parallel requests. I suggest to have a simple for loop with a break of 100ms in between these calls.

We would appreciate any help on this so please help us out! Have a look at our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and reach out if you have any questions. Cheers!
