### ISSUE TITLE
[🐛 Bug]: [Appium] "Failed to create session" error is raised after updating to Xcode 14.0 even though everything seems to launch successfully

### ISSUE THREAD

**Issue by JaniJegoroff** [webdriverio/webdriverio#8887]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.24.0

### Node.js Version

v18.8.0 / v18.9.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
// caps on success case: Xcode 13.4.1, iPhone simulator 15.5, node 18.8.0
services: [
        ['appium', {
            args: {
                basePath: '/wd/hub',
                platformName: 'iOS',
                automationName: 'XCUITest',
                deviceName: 'iPhone SE',
                // replace with your iPhone SE UDID
                udid: 'E395C9D4-D21D-4DF8-B4BC-C6C9CF4B4651'
            }
        }]
    ],

// caps on error case: Xcode 14.0, iPhone simulator 16.0, node 18.9.0
services: [
        ['appium', {
            args: {
                basePath: '/wd/hub',
                platformName: 'iOS',
                automationName: 'XCUITest',
                deviceName: 'iPhone SE',
                // replace with your iPhone SE UDID
                udid: 'A96291B6-4485-4B93-A25A-6E4918126744',
                showIosLog: true,
                address: '127.0.0.1'
            }
        }]
    ],
```

### What happened?

1. Given simple example project launching mobile Safari on iPhone SE:
https://github.com/JaniJegoroff/appium-server-launch/tree/main/wdio
```
Running successfully on Xcode 13.4.1, iPhone simulator 15.5, node 18.8.0
```

2. Update Xcode 14.0, iPhone simulator 16.0 and node 18.9.0

Short log:
```shell
[0-0] 2022-09-19T22:48:44.829Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] An unknown server-side error occurred while processing the command. Original error: Mobile Safari cannot open 'http://127.0.0.1:4723/welcome' after 25.761s. Its process com.apple.mobilesafari does not exist in the list of Simulator processes
```

iPhone simulator and browser are launched successfully but still error is raised. See full log for more details.

<img width="1086" alt="Screenshot 2022-09-19 at 23 48 24" src="https://user-images.githubusercontent.com/2363231/191135224-92577788-17ef-4541-9f97-01e29fcc8ab6.png">

### What is your expected behavior?

Example project test case is passing.

### How to reproduce the bug.

```
Checkout example project: https://github.com/JaniJegoroff/appium-server-launch/tree/main/wdio

# Replace simulator udid with your in wdio.conf.js file
xcrun xctrace list devices | grep 'iPhone SE'

npm install

npm run wdio
```

### Relevant log output

```typescript
Full log:

Janis-MBP:wdio janijegoroff$ npm run wdio

> test@1.0.0 wdio
> wdio run wdio.conf.js


Execution of 1 workers started at 2022-09-19T22:48:07.075Z

2022-09-19T22:48:07.079Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
2022-09-19T22:48:07.108Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-09-19T22:48:07.110Z DEBUG @wdio/appium-service: Will spawn Appium process: node /Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/appium/build/lib/main.js --base-path /wd/hub --platform-name iOS --automation-name XCUITest --device-name 'iPhone SE' --udid A96291B6-4485-4B93-A25A-6E4918126744 --show-ios-log --address 127.0.0.1
2022-09-19T22:48:09.001Z DEBUG @wdio/appium-service: Appium started with ID: 52043
2022-09-19T22:48:09.001Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 1892ms
2022-09-19T22:48:09.003Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-09-19T22:48:09.003Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2022-09-19T22:48:09.004Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,wdio.conf.js
[0-0] 2022-09-19T22:48:09.497Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2022-09-19T22:48:09.500Z DEBUG @wdio/config:ConfigParser: No compiler found, continue without compiling files
[0-0] 2022-09-19T22:48:09.503Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2022-09-19T22:48:09.509Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
[0-0] RUNNING in Safari - /test/specs/appium_server.js
[0-0] 2022-09-19T22:48:09.922Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2022-09-19T22:48:09.926Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2022-09-19T22:48:10.011Z INFO webdriver: [POST] http://localhost:4723/wd/hub/session
[0-0] 2022-09-19T22:48:10.011Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'Safari', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'Safari', acceptInsecureCerts: true }
[0-0] }
[0-0] 2022-09-19T22:48:44.828Z DEBUG webdriver: request failed due to response error: unknown error
[0-0] 2022-09-19T22:48:44.828Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Mobile Safari cannot open 'http://127.0.0.1:4723/welcome' after 25.761s. Its process com.apple.mobilesafari does not exist in the list of Simulator processes
[0-0] 2022-09-19T22:48:44.829Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: Mobile Safari cannot open 'http://127.0.0.1:4723/welcome' after 25.761s. Its process com.apple.mobilesafari does not exist in the list of Simulator processes
[0-0]     at getErrorFromResponseBody (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/webdriver/build/utils.js:198:12)
[0-0]     at NodeJSRequest._request (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/webdriver/build/request/index.js:166:60)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async startWebDriverSession (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/webdriver/build/utils.js:68:20)
[0-0]     at async WebDriver.newSession (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/webdriver/build/index.js:46:45)
[0-0]     at async remote (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/webdriverio/build/index.js:77:22)
[0-0]     at async Runner._startSession (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/@wdio/runner/build/index.js:88:19)
[0-0] 2022-09-19T22:48:44.829Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] An unknown server-side error occurred while processing the command. Original error: Mobile Safari cannot open 'http://127.0.0.1:4723/welcome' after 25.761s. Its process com.apple.mobilesafari does not exist in the list of Simulator processes
[0-0]     at startWebDriverSession (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/webdriver/build/utils.js:73:15)
[0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async WebDriver.newSession (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/webdriver/build/index.js:46:45)
[0-0]     at async remote (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/webdriverio/build/index.js:77:22)
[0-0]     at async Runner._startSession (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (/Users/janijegoroff/projects/appium-server-launch/wdio/node_modules/@wdio/runner/build/index.js:88:19)
2022-09-19T22:48:44.945Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in Safari - /test/specs/appium_server.js
2022-09-19T22:48:44.946Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-09-19T22:48:44.946Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
2022-09-19T22:48:44.947Z INFO @wdio/cli:launcher: Run onComplete hook
2022-09-19T22:48:44.947Z DEBUG @wdio/appium-service: Appium (pid: 52043) killed
2022-09-19T22:48:44.947Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms

Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:37

2022-09-19T22:48:44.949Z INFO @wdio/local-runner: Shutting down spawned worker
2022-09-19T22:48:45.202Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-09-19T22:48:45.203Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising an issue.

Unfortunately there is nothing WebdriverIO can do about this. Please report the bug in the Appium project. Thank you!
