### ISSUE TITLE
[🐛 Bug]: WebDriverIO/TS-Node won't transform the module - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by samuelfreiberg** [webdriverio/webdriverio#8892]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.24.0

### Node.js Version

14.20

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    platformName: 'windows',
    'appium:automationName': 'windows',
    'appium:deviceName': 'WindowsPC',
}
```

### What happened?

I understand bugs similar to this one have been filed before. I'm also aware of all the solutions/documentation provided to solve this issue. However, none have worked for me. I've scoured the internet and help forums for days, and I cannot find a solution for this issue. I'd appreciate any help, as I feel like I've hit a brick wall.

### Situation:
I'm using WDIO as a test runner for my React-Native project, written using _TypeScript_ in a Node JS environment.

There are two different types of imports I'd like to highlight:

1. Local Imports (ie. `import PageObject from '../PageObjects/PageObject'`) - **This WORKS**
2. Import External Package (ie. `import { Platform } from 'react-native'`) - This provides an **Error**

### The Error:

Please note, this error is happening in _\node_modules\react-native\index.js_, not in my local spec file that imports it.
```
INFO @wdio/local-runner: Run worker command: run
DEBUG @wdio/config:utils: Found 'ts-node' package, auto-compiling TypeScript files
(node:20596) UnhandledPromiseRejectionWarning: C:\local_path\project\node_modules\react-native\index.js:14
import typeof AccessibilityInfo from 
    './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
     at Module._compile (internal/modules/cjs/loader.js:1049:27)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
     at Module.load (internal/modules/cjs/loader.js:950:32)
     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
     at Module.require (internal/modules/cjs/loader.js:974:19)
     at require (internal/modules/cjs/helpers.js:101:18)
     at Object.<anonymous> (C:\local_path\project\apps\win32\src\test.ts:3:18)
     at Module._compile (internal/modules/cjs/loader.js:1085:14)
     at Module.m._compile (C:\local_path\project\node_modules\ts-node\src\index.ts:858:23)
```

### What I've Tried:

1. Followed WDIO's documentation on integration with TypeScript
2. Followed WDIO's documentation on integration with Babel
3. Cloned WDIO boilerplate projects and tried to use the same import above - all of which give the same errors

### My Setup:

**package.json**
``` 
{
  "main": "src/index.tsx",
  "module": "src/index.tsx",
  "typings": "lib/index.d.ts",
  "scripts": {
    "e2etest": "wdio wdio.win32.conf.ts"
  },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "^0.66.0",
    "tslib": "^2.3.1"
  },
  "devDependencies": {
    "@babel/cli": "^7.18.10",
    "@babel/core": "^7.19.1",
    "@babel/preset-env": "^7.19.1",
    "@babel/register": "^7.18.9",
    "@types/jasmine": "3.5.10",
    "@types/react": "^17.0.2",
    "@types/react-native": "^0.66.0",
    "@wdio/appium-service": "^7.24.0",
    "@wdio/browserstack-service": "^7.24.0",
    "@wdio/cli": "^7.24.0",
    "@wdio/jasmine-framework": "^7.24.0",
    "@wdio/local-runner": "^7.24.0",
    "@wdio/sauce-service": "^7.24.0",
    "@wdio/spec-reporter": "^7.24.0",
    "appium": "2.0.0-beta.41",
    "appium-windows-driver": "2.0.7",
    "react": "17.0.2",
    "react-native": "^0.66.0",
    "ts-node": "^10.8.0",
    "typescript": "^4.6.4",
    "webdriverio": "^7.24.0"
  },
}
```

**tsconfig.json**
```
{
  "compilerOptions": {
    "outDir": "./.tsbuild/",
    "sourceMap": false,
    "target": "es2019",
    "module": "commonjs",
    "removeComments": true,
    "noImplicitAny": true,
    "strictPropertyInitialization": true,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "moduleResolution": "node",
    "types": ["node", "webdriverio/async", "@wdio/jasmine-framework", "expect-webdriverio", "@wdio/sauce-service"]
  },
  "include": [ "src", "./tests/**/*.ts" ]
}
```

**babel.config.js**
```
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 14,
        },
      },
    ],
  ]
};
```

**wdio.conf.ts**
```
export const config: WebdriverIO.Config = {
  runner: 'local',
  specs: ['src/test.ts'],
  capabilities: [
    {
      maxInstances: 1,
      platformName: 'windows',
      'appium:automationName': 'windows',
      'appium:deviceName': 'WindowsPC',
      'appium:app': appPath,
      'appium:appArguments': appArgs,
      'appium:appWorkingDir': appDir,
    },
  ],
  logLevel: 'debug',
  bail: 0,
  waitforTimeout: 45000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,

  port: 4723, // default appium port
  services: [
    [
      'appium',
      {
        logPath: './reports/',
      },
    ],
  ],

  framework: 'jasmine',

  reporters: ['spec'],
  jasmineOpts: {
    defaultTimeoutInterval: 3 * 60 * 1000, // 3min
  },

  autoCompileOpts: {
    autoCompile: true,

    tsNodeOpts: {
      transpileOnly: true,
      project: 'tsconfig.json',
    },
  },
};
```

### What is your expected behavior?

I'm able to use `import { Platform } from 'react-native'` without error.

### How to reproduce the bug.

Open any WDIO project with Appium + TypeScript + Babel:

1. Add the following devDependencies: `"react-native": "^0.66.0"` and `"@types/react-native": "^0.66.0"`
2. In spec file, add `import { Platform } from 'react-native'` (no need for actual logic right now, we just need to figure out how we can run this file)
3. Run WDIO and see "Cannot use import statement outside of module"

Make sure you have tsconfig and babel.config.js above along with:
```
    autoCompileOpts: {
        autoCompile: true,
        tsNodeOpts: {
            transpileOnly: true,
            project: 'tsconfig.json',
        },
```
in your wdio config.

### Relevant log output

```typescript
C:\path\project\apps\win32>yarn e2etest
yarn run v1.22.5
warning package.json: No license field
$ wdio wdio.win32.conf.ts

Execution of 1 workers started at 2022-09-20T18:55:34.331Z

2022-09-20T18:55:34.333Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
2022-09-20T18:55:34.372Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-09-20T18:55:34.373Z DEBUG @wdio/appium-service: Will spawn Appium process: cmd /c node C:\path\project\node_modules\appium\index.js --base-path /
2022-09-20T18:55:40.352Z DEBUG @wdio/appium-service: Appium started with ID: 21000
2022-09-20T18:55:40.353Z DEBUG @wdio/appium-service: Appium logs written to: C:\path\project\apps\win32\reports\wdio-appium.log
2022-09-20T18:55:40.355Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 5982ms
2022-09-20T18:55:40.356Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-09-20T18:55:40.356Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2022-09-20T18:55:40.359Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.win32.conf.ts
[0-0] 2022-09-20T18:55:41.119Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2022-09-20T18:55:41.397Z DEBUG @wdio/config:utils: Found 'ts-node' package, auto-compiling TypeScript files
[0-0] 2022-09-20T18:55:41.492Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2022-09-20T18:55:41.496Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
[0-0] (node:25840) UnhandledPromiseRejectionWarning: C:\path\project\node_modules\react-native\index.js:14
[0-0] import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
[0-0] ^^^^^^
[0-0]
[0-0] SyntaxError: Cannot use import statement outside a module
[0-0]     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
[0-0]     at Module._compile (internal/modules/cjs/loader.js:1049:27)
[0-0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[0-0]     at Module.load (internal/modules/cjs/loader.js:950:32)
[0-0]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[0-0]     at Module.require (internal/modules/cjs/loader.js:974:19)
[0-0]     at require (internal/modules/cjs/helpers.js:101:18)
[0-0]     at Object.<anonymous> (C:\path\project\apps\win32\src\test.ts:3:1)
[0-0]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[0-0]     at Module.m._compile (C:\path\project\node_modules\ts-node\src\index.ts:858:23)
[0-0] (Use `node --trace-warnings ...` to show where the warning was created)
[0-0] (node:25840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[0-0] (node:25840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2022-09-20T18:55:42.203Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 0
2022-09-20T18:55:42.204Z INFO @wdio/cli: [0-0] SKIPPED in windows - C:\path\project\apps\win32\src\test.ts
2022-09-20T18:55:42.204Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-09-20T18:55:42.205Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
2022-09-20T18:55:42.205Z INFO @wdio/cli:launcher: Run onComplete hook
2022-09-20T18:55:42.206Z DEBUG @wdio/appium-service: Appium (pid: 21000) killed
2022-09-20T18:55:42.206Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 1ms

Spec Files:      0 passed, 1 skipped, 1 total (100% completed) in 00:00:07

2022-09-20T18:55:42.207Z INFO @wdio/local-runner: Shutting down spawned worker
2022-09-20T18:55:42.467Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-09-20T18:55:42.467Z INFO @wdio/local-runner: shutting down
Done in 11.06s
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Why do you need to import `Platform` in your tests?

**Comment by samuelfreiberg** [comment]
> Why do you need to import `Platform` in your tests?

It's not just for `Platform`. It's any import from an external package. It doesn't have to be from 'react-native' either. Just an import from an external package.

**Comment by christian-bromann** [comment]
If you use TypeScript, why do you have a `babel.config.js`? Have you tried to delete that one?

**Comment by samuelfreiberg** [comment]
> If you use TypeScript, why do you have a `babel.config.js`? Have you tried to delete that one?

I have tried deleting it along with babel dependencies, but I'm getting the same error. I also saw Babel integrated in this [boilerplate project,](https://github.com/webdriverio/appium-boilerplate/) which is why I added it initially

**Comment by christian-bromann** [comment]
I recommend to set up WebdriverIO using the configuration wizard and pick TypeScript when it asks which compiler to set up (see also https://webdriver.io/docs/gettingstarted#using-npm). Without a minimal reproducible example it is hard to pin point to anything.

**Comment by samuelfreiberg** [comment]
> I recommend to set up WebdriverIO using the configuration wizard and pick TypeScript when it asks which compiler to set up (see also https://webdriver.io/docs/gettingstarted#using-npm). Without a minimal reproducible example it is hard to pin point to anything.

Just tried that and still having the same error. I used the wizard and picked TypeScript. Added minimal config, but still reproducing the error.

**Comment by samuelfreiberg** [comment]
Ugh, ok. I read through all of https://github.com/TypeStrong/ts-node#cli-and-programmatic-options and tried some stuff out.

Turns out I need to add `ignore: ['/node_modules']` in tsNodeOpts.

So it works with:
```
    autoCompileOpts: {
        autoCompile: true,

        tsNodeOpts: {
            transpileOnly: true,
            project: 'tsconfig.json',
            ignore: ['/node_modules']
        }
    },
```

**Comment by samuelfreiberg** [comment]
Hours and hours and hours.... Just for one line, gotta love software engineering :)

**Comment by christian-bromann** [comment]
> Added minimal config

When I run `npm init wdio .` and pick TypeScript and right after call `npm run wdio` all tests pass. What did you modify?

**Comment by samuelfreiberg** [comment]
> > Added minimal config
> 
> When I run `npm init wdio .` and pick TypeScript and right after call `npm run wdio` all tests pass. What did you modify?

I added an import statement at the top of the spec file that imports from an external package

**Comment by samuelfreiberg** [comment]
I would assume that importing from an external package might be common practice? Maybe something should be added at the bottom of the docs about this property?

But then again, if more people aren't posting about this, maybe it's not.

**Comment by christian-bromann** [comment]
When I tried to import `import { Platform } from 'react-native'` I am getting:

>  TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /private/tmp/foobar/test/specs/example.e2e.ts

which is very weird 🤔 other imports seem to work for me.

**Comment by benmneb** [comment]
im getting the same error, on wdio 8.20 and node 16.9 trying to import from react-native

ignoring node modules in tsNodeOpts (it takes regex now not an array) doesnt change anything either

**Comment by tlomozik** [comment]
> im getting the same error, on wdio 8.20 and node 16.9 trying to import from react-native
> 
> ignoring node modules in tsNodeOpts (it takes regex now not an array) doesnt change anything either

any updates here @benmneb, have you been able to resolve it somehow? I get same on wdio 9.0.6 node v22.8.0
