### ISSUE TITLE
[🐛 Bug]: Failures in test body are propagated to subsequent blocks and unexpectedly fails afterAll

### ISSUE THREAD

**Issue by khkchung** [webdriverio/webdriverio#8979]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

14.17.6

### Mode

WDIO Testrunner

### What happened?

When `beforeEach`, `it`, or `afterEach` blocks fail, the error would 'propagate' to subsequent blocks, sometimes including `afterAll` and failing it as well.

### What is your expected behavior?

When either `beforeEach`, `it`, or `afterEach` fails, it should only fail the test case and not `afterAll`.
Also, the error should be reported only once (see sample log output).

### How to reproduce the bug.

**CASE 1 ("after all" hook failed)**
example.e2e.js
```js
describe('example', () => {
    beforeAll(() => {
        console.log('beforeAll');
    });

    beforeEach(() => {
        console.log('beforeEach');
        throw new Error('error in beforeEach');
    });

    it('example', async () => {
        console.log('it');
    });

    afterEach(() => {
        console.log('afterEach');
    });

    afterAll(() => {
        console.log('afterAll');
    });
});
```

**CASE 2 ("after all" hook passed)**
example.e2e.js
```js
describe('example', () => {
    beforeAll(() => {
        console.log('beforeAll');
    });

    beforeEach(() => {
        console.log('beforeEach');
    });

    it('example', async () => {
        console.log('it');
        throw new Error('error in it');
    });

    it('example #2', async () => {
        console.log('it #2');
    });

    afterEach(() => {
        console.log('afterEach');
    });

    afterAll(() => {
        console.log('afterAll');
    });
});
```

### Relevant log output

```typescript
# CASE 1 spec reporter output
...
[Chrome 102.0.5005.61 linux #0-0] » /test/specs/example.e2e.js
[Chrome 102.0.5005.61 linux #0-0] example
[Chrome 102.0.5005.61 linux #0-0]    ✖ example
[Chrome 102.0.5005.61 linux #0-0]    ✖ "after all" hook
[Chrome 102.0.5005.61 linux #0-0]
[Chrome 102.0.5005.61 linux #0-0] 2 failing (198ms)
[Chrome 102.0.5005.61 linux #0-0]
[Chrome 102.0.5005.61 linux #0-0] 1) example example
[Chrome 102.0.5005.61 linux #0-0] Error: error in beforeEach
[Chrome 102.0.5005.61 linux #0-0] Error: error in beforeEach
[Chrome 102.0.5005.61 linux #0-0]     at UserContext.<anonymous> (/vagrant/wdio_test/test/specs/example.e2e.js:9:15)
[Chrome 102.0.5005.61 linux #0-0] Error: error in beforeEach
[Chrome 102.0.5005.61 linux #0-0] error properties: Object({ matcherName: '', passed: false, expected: '', actual: '' })
[Chrome 102.0.5005.61 linux #0-0] Error: error in beforeEach
[Chrome 102.0.5005.61 linux #0-0]     at UserContext.<anonymous> (/vagrant/wdio_test/test/specs/example.e2e.js:9:15)
[Chrome 102.0.5005.61 linux #0-0] Error: error in beforeEach
[Chrome 102.0.5005.61 linux #0-0] error properties: Object({ matcherName: '', passed: false, expected: '', actual: '' })
[Chrome 102.0.5005.61 linux #0-0] Error: error in beforeEach
[Chrome 102.0.5005.61 linux #0-0]     at UserContext.<anonymous> (/vagrant/wdio_test/test/specs/example.e2e.js:9:15)
[Chrome 102.0.5005.61 linux #0-0]
[Chrome 102.0.5005.61 linux #0-0] 2) example "after all" hook
[Chrome 102.0.5005.61 linux #0-0] Error: error in beforeEach
[Chrome 102.0.5005.61 linux #0-0] Error: error in beforeEach
[Chrome 102.0.5005.61 linux #0-0]     at UserContext.<anonymous> (/vagrant/wdio_test/test/specs/example.e2e.js:9:15)

# CASE 2 spec reporter output
...
[Chrome 102.0.5005.61 linux #0-0] » /test/specs/example.e2e.js
[Chrome 102.0.5005.61 linux #0-0] example
[Chrome 102.0.5005.61 linux #0-0]    ✖ example
[Chrome 102.0.5005.61 linux #0-0]    ✓ example #2
[Chrome 102.0.5005.61 linux #0-0]
[Chrome 102.0.5005.61 linux #0-0] 1 passing (81ms)
[Chrome 102.0.5005.61 linux #0-0] 1 failing
[Chrome 102.0.5005.61 linux #0-0]
[Chrome 102.0.5005.61 linux #0-0] 1) example example
[Chrome 102.0.5005.61 linux #0-0] Error: error in it
[Chrome 102.0.5005.61 linux #0-0] Error: error in it
[Chrome 102.0.5005.61 linux #0-0]     at UserContext.<anonymous> (/vagrant/wdio_test/test/specs/example.e2e.js:15:15)
[Chrome 102.0.5005.61 linux #0-0] Error: error in it
[Chrome 102.0.5005.61 linux #0-0] error properties: Object({ matcherName: '', passed: false, expected: '', actual: '' })
[Chrome 102.0.5005.61 linux #0-0] Error: error in it
[Chrome 102.0.5005.61 linux #0-0]     at UserContext.<anonymous> (/vagrant/wdio_test/test/specs/example.e2e.js:15:15)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by bh-shatz** [comment]
We have been facing this issue in our projects, so I done some investigation and I believe that the cause of this bug is the code in [wdio-utils/src/test-framework/testFnWrapper.ts#L92](https://github.com/webdriverio/webdriverio/blob/faacaca9ef30c1575ef0a48258efd8e0699db9d5/packages/wdio-utils/src/test-framework/testFnWrapper.ts#L92) that is trying to be "clever" and do some Jasmine specific logic in a generic util function.

The code in the [wdio-jasmine-framework](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-jasmine-framework/src/index.ts#L312) is already converting the `failedExpectations` into error(s) when creating the message content for hooks.

I have made the change locally to remove the spacial Jasmine handling in wdio-utils/src/test-framework/testFnWrapper.ts and it seems to solve this bug.

**Comment by christian-bromann** [comment]
@bh-shatz thanks for investigating. Mind raising a PR with the changes?

**Comment by PinhoL** [comment]
I've tested your solution @bh-shatz and it seems to fix my problem as well

**Comment by christian-bromann** [comment]
Let's continue conversation in https://github.com/webdriverio/webdriverio/pull/9579
