### ISSUE TITLE
[🐛 Bug]:  WARN webdriver: Request failed with status 500 due to Infrastructure Error -- The Sauce VMs failed to start the browser or device.

### ISSUE THREAD

**Issue by borracciaBlu** [webdriverio/webdriverio#9058]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

14

### Mode

WDIO Testrunner

### What happened?

When running the tests in github action I've got 

```
[15-0] 2022-10-24T10:00:06.963Z ERROR webdriver: Request failed with status 500 due to WebDriver Error: Infrastructure Error -- The Sauce VMs failed to start the browser or device.
[15-0] For more info, please check https://docs.saucelabs.com/dev/error-messages
[15-0] 2022-10-24T10:00:06.963Z ERROR webdriver: WebDriver Error: Infrastructure Error -- The Sauce VMs failed to start the browser or device.
[15-0] For more info, please check https://docs.saucelabs.com/dev/error-messages
[15-0]     at getErrorFromResponseBody (/home/runner/work/dh-classlist/dh-classlist/node_modules/webdriver/build/utils.js:198:12)
[15-0]     at NodeJSRequest._request (/home/runner/work/dh-classlist/dh-classlist/node_modules/webdriver/build/request/index.js:166:60)
[15-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[15-0]     at async startWebDriverSession (/home/runner/work/dh-classlist/dh-classlist/node_modules/webdriver/build/utils.js:68:20)
[15-0]     at async Function.newSession (/home/runner/work/dh-classlist/dh-classlist/node_modules/webdriver/build/index.js:46:45)
[15-0]     at async remote (/home/runner/work/dh-classlist/dh-classlist/node_modules/webdriverio/build/index.js:77:22)
[15-0]     at async Runner._startSession (/home/runner/work/dh-classlist/dh-classlist/node_modules/@wdio/runner/build/index.js:223:56)
[15-0]     at async Runner._initSession (/home/runner/work/dh-classlist/dh-classlist/node_modules/@wdio/runner/build/index.js:176:25)
[15-0]     at async Runner.run (/home/runner/work/dh-classlist/dh-classlist/node_modules/@wdio/runner/build/index.js:88:19)
```

### What is your expected behavior?

no 500 error. Actually, I'm not sure if it's a webdriverio issue or saucelab.

### How to reproduce the bug.

**Repo examples:** 
https://github.com/borracciaBlu/dh-addeventlistener
https://github.com/borracciaBlu/dh-classlist

**Config of WebdriverIO**  
https://github.com/borracciaBlu/dh-classlist/blob/master/wdio.conf.js

after cloning dh-classlist or dh-addeventlistener
env SAUCE_USERNAME="[username]" SAUCE_ACCESS_KEY="[key]" npm run saucelab

### Relevant log output

```typescript
[15-0] 2022-10-24T10:00:06.963Z ERROR webdriver: Request failed with status 500 due to WebDriver Error: Infrastructure Error -- The Sauce VMs failed to start the browser or device.
[15-0] For more info, please check https://docs.saucelabs.com/dev/error-messages
[15-0] 2022-10-24T10:00:06.963Z ERROR webdriver: WebDriver Error: Infrastructure Error -- The Sauce VMs failed to start the browser or device.
[15-0] For more info, please check https://docs.saucelabs.com/dev/error-messages
[15-0]     at getErrorFromResponseBody (/home/runner/work/dh-classlist/dh-classlist/node_modules/webdriver/build/utils.js:198:12)
[15-0]     at NodeJSRequest._request (/home/runner/work/dh-classlist/dh-classlist/node_modules/webdriver/build/request/index.js:166:60)
[15-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[15-0]     at async startWebDriverSession (/home/runner/work/dh-classlist/dh-classlist/node_modules/webdriver/build/utils.js:68:20)
[15-0]     at async Function.newSession (/home/runner/work/dh-classlist/dh-classlist/node_modules/webdriver/build/index.js:46:45)
[15-0]     at async remote (/home/runner/work/dh-classlist/dh-classlist/node_modules/webdriverio/build/index.js:77:22)
[15-0]     at async Runner._startSession (/home/runner/work/dh-classlist/dh-classlist/node_modules/@wdio/runner/build/index.js:223:56)
[15-0]     at async Runner._initSession (/home/runner/work/dh-classlist/dh-classlist/node_modules/@wdio/runner/build/index.js:176:25)
[15-0]     at async Runner.run (/home/runner/work/dh-classlist/dh-classlist/node_modules/@wdio/runner/build/index.js:88:19)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Hey, thanks for filing the issue.

Without having access to the job page it is impossible to say why this test has failed on Sauce Labs. I recommend to check in with their support to check what is going on. I am happy to re-open if it turns out to be an issue with WebdriverIO. Until then I have to close as there is nothing actionable to do here for us maintainer.

Let me know if you have any further questions.
