### ISSUE TITLE
[🐛 Bug]: DevTools Emulation and Network setUserAgentOverride does not work async

### ISSUE THREAD

**Issue by tkmcmaster** [webdriverio/webdriverio#9079]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.25.2

### Node.js Version

16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      browserName: "chrome",
      'goog:chromeOptions': {
        args: ["--headless", "--disable-gpu", "--enable-automation"],
      },
      acceptInsecureCerts: true
    }
```

### What happened?

Calling both `browser.cdp("Emulation", "setUserAgentOverride"...` and `browser.cdp("Network", "setUserAgentOverride", ...` do not seem to work when using async tests/code, only `.then` style.

### What is your expected behavior?

`setUserAgentOverride` should work both async and .then style.

### How to reproduce the bug.

package.json:
```
  "devDependencies": {
    "@types/chai": "^4.3.3",
    "@types/mocha": "^10.0.0",
    "@wdio/cli": "^7.25.2",
    "@wdio/devtools-service": "^7.25.2",
    "@wdio/local-runner": "^7.25.2",
    "@wdio/mocha-framework": "^7.25.2",
    "@wdio/spec-reporter": "^7.25.1",
    "@wdio/types": "^7.25.1",
    "chai": "^4.3.6",
    "chromedriver": "^106.0.1",
    "devtools-protocol": "0.0.1061995",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4",
    "wdio-chromedriver-service": "^8.0.0"
  }
```

wdio.conf.ts:
```js
exports.config = {
  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: {
        transpileOnly: true,
        project: "tsconfig.json"
    }
},
runner: "local",
  specs: [
    "./integration/setUserAgentOverride.spec.ts"
  ],
  maxInstances: 5,
  capabilities: [
    {
      browserName: "chrome",
      'goog:chromeOptions': {
        args: ["--headless", "--disable-gpu", "--enable-automation"],
      },
      acceptInsecureCerts: true
    }
  ],
  logLevel: "warn",
  logLevels: {
    webdriver: "warn",
    "@wdio/devtools-service": "debug",
  },
  services: [
    "chromedriver",
    "devtools", 
  ],
  framework: "mocha",
  reporters: ["spec"],
  mochaOpts: {
    ui: "bdd",
    timeout: 130000
  }
};
```

Test code:
```js
import CDP from "devtools-protocol";
import { expect } from "chai";

describe("setUserAgentOverride", () => {
  let overrideRequestOriginal: CDP.Emulation.SetUserAgentOverrideRequest;

  before(async () => {
    const version: CDP.Browser.GetVersionResponse = await browser.cdp("Browser", "getVersion");
    overrideRequestOriginal = { userAgent: version.userAgent };
  });

  after(() => browser.cdp("Emulation", "setUserAgentOverride", overrideRequestOriginal));

  it("should work with then", (done: Mocha.Done) => {
    const overrideRequest: CDP.Emulation.SetUserAgentOverrideRequest = {
      userAgent: "test user agent done"
    };
    browser.cdp("Emulation", "setUserAgentOverride", overrideRequest).then(() => {
      browser.cdp("Browser", "getVersion").then((version: CDP.Browser.GetVersionResponse) => {
        expect(version, "version").to.not.equal(undefined);
        expect(version.userAgent, "version.userAgent").to.equal(overrideRequest.userAgent);
      }).catch((error) => done(error));
    }).catch((error) => done(error));
  });

  it("should work with async", async () => {
    const overrideRequest: CDP.Emulation.SetUserAgentOverrideRequest = {
      userAgent: "test user agent async"
    };
    await browser.cdp("Emulation", "setUserAgentOverride", overrideRequest);
    const version: CDP.Browser.GetVersionResponse = await browser.cdp("Browser", "getVersion");
    expect(version, "version").to.not.equal(undefined);
    expect(version.userAgent, "version.userAgent").to.equal(overrideRequest.userAgent);
  });
});
```

Run command:
```sh
npx wdio wdio.conf.ts ./node_modules/.bin/
```

### Relevant log output

```typescript
Execution of 1 workers started at 2022-10-24T17:14:09.453Z

[0-0] RUNNING in chrome - /integration/setUserAgentOverride.spec.ts
[0-0] 2022-10-24T17:14:10.549Z INFO @wdio/devtools-service:CommandHandler: Send command "Browser.getVersion" with args: {}
[0-0] 2022-10-24T17:14:10.550Z DEBUG @wdio/devtools-service: cdp event: event with params undefined
[0-0] 2022-10-24T17:14:10.550Z INFO @wdio/devtools-service:CommandHandler: Send command "Emulation.setUserAgentOverride" with args: {"userAgent":"test user agent done"}
[0-0] 2022-10-24T17:14:10.551Z INFO @wdio/devtools-service:CommandHandler: Send command "Emulation.setUserAgentOverride" with args: {"userAgent":"test user agent async"}
[0-0] 2022-10-24T17:14:10.552Z DEBUG @wdio/devtools-service: cdp event: event with params undefined
[0-0] 2022-10-24T17:14:10.552Z INFO @wdio/devtools-service:CommandHandler: Send command "Browser.getVersion" with args: {}
[0-0] 2022-10-24T17:14:10.552Z DEBUG @wdio/devtools-service: cdp event: event with params undefined
[0-0] 2022-10-24T17:14:10.552Z INFO @wdio/devtools-service:CommandHandler: Send command "Browser.getVersion" with args: {}
[0-0] 2022-10-24T17:14:10.553Z DEBUG @wdio/devtools-service: cdp event: event with params undefined
[0-0] 2022-10-24T17:14:10.555Z DEBUG @wdio/devtools-service: cdp event: event with params undefined
[0-0] AssertionError in "setUserAgentOverride.should work with async"
AssertionError: version.userAgent: expected 'Mozilla/5.0 (X11; Linux x86_64) Apple…' to equal 'test user agent async'
    at Context.<anonymous> (/home/mcmaster/active-monitoring-wdiohelper/integration/setUserAgentOverride.spec.ts:33:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] 2022-10-24T17:14:10.561Z INFO @wdio/devtools-service:CommandHandler: Send command "Emulation.setUserAgentOverride" with args: {"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/106.0.5249.119 Safari/537.36"}
[0-0] 2022-10-24T17:14:10.561Z DEBUG @wdio/devtools-service: cdp event: event with params undefined
[0-0] FAILED in chrome - /integration/setUserAgentOverride.spec.ts

 "spec" Reporter:
------------------------------------------------------------------
[chrome 106.0.5249.119 linux #0-0] Running: chrome (v106.0.5249.119) on linux
[chrome 106.0.5249.119 linux #0-0] Session ID: c993aea038ccb8d0d92cf82752ab5960
[chrome 106.0.5249.119 linux #0-0]
[chrome 106.0.5249.119 linux #0-0] » /integration/setUserAgentOverride.spec.ts
[chrome 106.0.5249.119 linux #0-0] setUserAgentOverride
[chrome 106.0.5249.119 linux #0-0]    ✓ should work with then
[chrome 106.0.5249.119 linux #0-0]    ✖ should work with async
[chrome 106.0.5249.119 linux #0-0]
[chrome 106.0.5249.119 linux #0-0] 1 passing (69ms)
[chrome 106.0.5249.119 linux #0-0] 1 failing
[chrome 106.0.5249.119 linux #0-0]
[chrome 106.0.5249.119 linux #0-0] 1) setUserAgentOverride should work with async
[chrome 106.0.5249.119 linux #0-0] version.userAgent: expected 'Mozilla/5.0 (X11; Linux x86_64) Apple…' to equal 'test user agent async'      
      actual expected
      
      'Mozilla/5.0test (X11;user Linuxagent x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/106.0.5249.119 Safari/537.36async'
      
[chrome 106.0.5249.119 linux #0-0] AssertionError: version.userAgent: expected 'Mozilla/5.0 (X11; Linux x86_64) Apple…' to equal 'test user agent async'
[chrome 106.0.5249.119 linux #0-0]     at Context.<anonymous> (/home/mcmaster/active-monitoring-wdiohelper/integration/setUserAgentOverride.spec.ts:33:55)
[chrome 106.0.5249.119 linux #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:01
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@tkmcmaster I am not sure if `await browser.cdp("Browser", "getVersion")` recognises changes to the user agent. Can you try to go on a website where the user agent is printed and see what that one returns?

**Comment by tkmcmaster** [comment]
> @tkmcmaster I am not sure if `await browser.cdp("Browser", "getVersion")` recognises changes to the user agent. Can you try to go on a website where the user agent is printed and see what that one returns?

Interesting. If you'll notice in the `.then()` test cases, the `getVersion()` call does have the updated userAgent. I updated one of the async tests to 
```js
  it("Network.setUserAgentOverride should work with async", async () => {
    const overrideRequest: CDP.Network.SetUserAgentOverrideRequest = {
      userAgent: "test user agent async"
    };
    await browser.cdp("Network", "setUserAgentOverride", overrideRequest);
    await browser.url("http://whatsmyuseragent.org/");
    const text = await browser.$(".intro-text").getText();
    expect(text, "text").to.not.equal(undefined);
    expect(text, "text").to.equal(overrideRequest.userAgent);
  });
```
And it does update the userAgent going out.

**Comment by christian-bromann** [comment]
Great, yeah not sure why that is but if you open a web page the user agent should be changed. Closing.

**Comment by tkmcmaster** [comment]
@christian-bromann This still seems like a bug, possibly in the `Browser.getVersion()` then. It's definitely inconsistent in how it works.

**Comment by christian-bromann** [comment]
I would suggest then to report this to the Puppeteer team I guess because that is out of scope of WebdriverIO as you are using Puppeteer primitives.

**Comment by BorisOsipov** [comment]
@tkmcmaster

just run 
```
it("Network.setUserAgentOverride should work with then", (done: Mocha.Done) => {
    const overrideRequest: CDP.Network.SetUserAgentOverrideRequest = {
      userAgent: "test user agent done"
    };
    browser.cdp("Network", "setUserAgentOverride", overrideRequest).then(() => {
      browser.cdp("Browser", "getVersion").then((version: CDP.Browser.GetVersionResponse) => {
        expect(version, "version").to.not.equal(undefined);
        expect(version.userAgent, "version.userAgent").to.equal(overrideRequest.userAgent);
      }).catch((error) => console.log(error));
    }).catch((error) => console.log(error));
  });
```

and you will see in console log the same `[0-0] AssertionError in "setUserAgentOverride.should work with then"`.

Actually `const version: CDP.Browser.GetVersionResponse = await browser.cdp("Browser", "getVersion");` doesnt know about overrided user-agent and always returns original.

**Comment by tkmcmaster** [comment]
@BorisOsipov That's not what I'm seeing. I've updated https://github.com/tkmcmaster/setuseragentoverride. The only failures are the ones with top level async. In all the non-async tests, `Browser.getVersion()` returns the updated userAgent correctly. I even created a wrapper test that has an async function, but as long as the top level `it()` was not async, it passes with the `Browser.getVersion` returning the updated userAgent.

**Comment by BorisOsipov** [comment]
>I'm not sure why the done(error) were not failing the test, but you're correct.

me too.
