### ISSUE TITLE
[🐛 Bug]: Partial text selector without tag doesn't work

### ISSUE THREAD

**Issue by treet** [webdriverio/webdriverio#9092]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v16.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
Chrome 106 on macOS Monterey, but probably not related.
```

### What happened?

When using `waitForExists()` on an element selected using a partial text without tag (e.g. `$("*=Some text")` the element is never found, the `waitForExists()` timeouts. When changing the selector to include a tag (e.g. `$("div*=Some text")`) it works as expected.

According to the docs partial text selection without a tag should work: https://webdriver.io/docs/selectors/#partial-link-text

This seems to be a regression of a previous bug: https://github.com/webdriverio/webdriverio/issues/2824

### What is your expected behavior?

The element should be found by partial text even when omitting a tag.

### How to reproduce the bug.

Here's a repo with a reproducible case: https://github.com/treet/partial-text-select

Changing `$("*=The complete developer platform")` to `$("p*=The complete developer platform")` makes the test pass.

### Relevant log output

```typescript
[0-0] 2022-10-25T14:42:45.807Z INFO webdriver: RESULT []
[0-0] 2022-10-25T14:42:46.273Z INFO webdriver: COMMAND findElements("partial link text", "The complete developer platform")
[0-0] 2022-10-25T14:42:46.273Z INFO webdriver: [POST] http://localhost:9515/session/28261dbaf5f406ed5e87e76bd1729cb1/elements
[0-0] 2022-10-25T14:42:46.273Z INFO webdriver: DATA {
[0-0]   using: 'partial link text',
[0-0]   value: 'The complete developer platform'
[0-0] }
[0-0] 2022-10-25T14:42:46.312Z INFO webdriver: RESULT []
[0-0] Error in "Repro case.should be able to find by partial text without tag"
Error: element ("*=The complete developer platform") still not existing after 3000ms
    at async Context.<anonymous> (/Users/ete/code/webdriverio-repro/example.test.ts:4:5)
[0-0] 2022-10-25T14:42:46.776Z INFO webdriver: COMMAND deleteSession()
[0-0] 2022-10-25T14:42:46.776Z INFO webdriver: [DELETE] http://localhost:9515/session/28261dbaf5f406ed5e87e76bd1729cb1
[0-0] FAILED in chrome - /example.test.ts
2022-10-25T14:42:46.937Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-10-25T14:42:46.937Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 106.0.5249.119 mac os x #0-0] Running: chrome (v106.0.5249.119) on mac os x
[chrome 106.0.5249.119 mac os x #0-0] Session ID: 28261dbaf5f406ed5e87e76bd1729cb1
[chrome 106.0.5249.119 mac os x #0-0]
[chrome 106.0.5249.119 mac os x #0-0] » /example.test.ts
[chrome 106.0.5249.119 mac os x #0-0] Repro case
[chrome 106.0.5249.119 mac os x #0-0]    ✖ should be able to find by partial text without tag
[chrome 106.0.5249.119 mac os x #0-0]
[chrome 106.0.5249.119 mac os x #0-0] 1 failing (3.7s)
[chrome 106.0.5249.119 mac os x #0-0]
[chrome 106.0.5249.119 mac os x #0-0] 1) Repro case should be able to find by partial text without tag
[chrome 106.0.5249.119 mac os x #0-0] element ("*=The complete developer platform") still not existing after 3000ms
[chrome 106.0.5249.119 mac os x #0-0] Error: element ("*=The complete developer platform") still not existing after 3000ms
[chrome 106.0.5249.119 mac os x #0-0]     at async Context.<anonymous> (/Users/ete/code/webdriverio-repro/example.test.ts:4:5)


Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:00:05 

2022-10-25T14:42:46.938Z INFO @wdio/local-runner: Shutting down spawned worker
2022-10-25T14:42:47.190Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2022-10-25T14:42:47.191Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by BorisOsipov** [comment]
@treet

Not a bug, it works accoring spec.

[Specification](https://www.w3.org/TR/webdriver/#partial-link-text)

The Partial link text strategy is very similar to the Link Text strategy, but rather than matching the entire string, only a substring needs to match. That is, return all ***a*** elements with rendered text that contains the selector expression.

There is no ***a*** with given text at github.com. There is **p***:

```
<p class="f2-mktg col-md-7 col-lg-11 col-xl-10 text-normal text-gray-light-mktg mr-lg-n4 mb-4 position-relative z-2">The complete developer platform to build, scale, and deliver secure software.</p>
```
