### ISSUE TITLE
[🐛 Bug]: After installing @wdio/sauce-service@8.0.2 it stopped working

### ISSUE THREAD

**Issue by borracciaBlu** [webdriverio/webdriverio#9298]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.2 

### Node.js Version

v16.15.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
          "browserName": 'MicrosoftEdge',
          "browserVersion": 'latest',
          "platformName": 'Windows 10',
          'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'chrome',
            browserVersion: '75',
            platformName: 'Windows 10',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'chrome',
            browserVersion: 'latest',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'chrome',
            browserVersion: 'latest',
            platformName: 'macOS 10.15',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'firefox',
            browserVersion: '55',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'firefox',
            browserVersion: 'latest',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'firefox',
            browserVersion: 'latest',
            platformName: 'Windows 10',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'firefox',
            browserVersion: 'latest',
            platformName: 'macOS 10.15',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'safari',
            browserVersion: '11',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'safari',
            browserVersion: '12',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'safari',
            browserVersion: '13',
            platformName: 'Mac 10.15',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'safari',
            browserVersion: '14',
            platformName: 'Mac 11.00',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'safari',
            browserVersion: 'latest',
            platformName: 'macOS 10.15',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'internet explorer',
            browserVersion: '10',
            platformName: 'Windows 2012',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'internet explorer',
            browserVersion: '11',
            platformName: 'Windows 10',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '13',
            platformName: 'Windows 10',
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '14',
            platformName: 'Windows 10',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '15',
            platformName: 'Windows 10',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '16',
            platformName: 'Windows 10',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '17',
            platformName: 'Windows 10',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '18',
            platformName: 'Windows 10',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '79',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '80',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '81',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '84',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '85',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '86',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: '87',
            platformName: 'Mac 10.13',
            'sauce:options': {build: `${now}`, },
        },
        {
            browserName: 'MicrosoftEdge',
            browserVersion: 'latest',
            platformName: 'macOS 10.15',
            'sauce:options': {build: `${now}`, },
        },
        {
            'browserName':'Safari',
            'appium:deviceName':'iPhone XS Simulator',
            'appium:platformVersion':'14.0',
            'platformName':'iOS',
            'sauce:options': {
                build: `${now}`,
                appiumVersion: '1.19.1'
            },
        },
        {
            'browserName':'Safari',
            'appium:deviceName':'iPhone XS Simulator',
            'appium:platformVersion':'12.0',
            'platformName':'iOS',
            'sauce:options': {
                build: `${now}`,
                appiumVersion: '1.9.1'
            },
        },
        {
            browserName: 'browser',
            'appium:platformVersion': '5.1',
            'appium:deviceName': 'Android Emulator',
            platformName: 'Android',
            'sauce:options': {
                build: `${now}`,
                appiumVersion: '1.18.1'
            },
        },
        {
            browserName: 'Chrome',
            'appium:platformVersion': '8.0',
            'appium:deviceName': 'Android Emulator',
            platformName: 'Android',
            'sauce:options': {
                build: `${now}`,
                appiumVersion: '1.18.1'
            },
        },
        {
            browserName: 'Chrome',
            'appium:platformVersion': '11.0',
            'appium:deviceName': 'Android GoogleAPI Emulator',
            platformName: 'Android',
            'sauce:options': {
                build: `${now}`,
                appiumVersion: '1.18.1'
            },
        },
```

### What happened?

**Packages**
```
@borracciablu/dh-classlist@2.0.68 /Code/dh-classlist
├── @borracciablu/banner-cli@0.1.28
├── @wdio/cli@8.0.4
├── @wdio/local-runner@8.0.4
├── @wdio/mocha-framework@8.0.2
├── @wdio/sauce-service@8.0.2
├── @wdio/spec-reporter@8.0.0
├── @wdio/sync@7.27.0
├── assert@2.0.0
├── browserify@17.0.0
├── eslint@8.29.0
├── gh-pages@4.0.0
├── mocha@10.1.0
├── nyc@15.1.0
└── uglify-js@3.17.4
```

**Error**
```
In console

2022-12-05T02:04:33.267Z ERROR @wdio/utils:initialiseServices: TypeError: SauceLabs is not a constructor
    at new SauceLauncher (Code/dh-classlist/node_modules/@wdio/sauce-service/build/launcher.js:23:21)
    at initialiseLauncherService (Code/dh-classlist/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialiseServices.js:94:39)
    at async Launcher.run (Code/dh-classlist/node_modules/@wdio/cli/build/launcher.js:69:65)
```

**Github Actions**
```
https://github.com/borracciaBlu/dh-classlist/actions/runs/3615964301/jobs/6093481943
```

### What is your expected behavior?

to be working as in version 7

### How to reproduce the bug.

Check code in 
- https://github.com/borracciaBlu/dh-classlist/
- https://github.com/borracciaBlu/dh-classlist/actions/runs/3615964301/jobs/6093481943

### Relevant log output

```typescript
2022-12-05T02:04:33.267Z ERROR @wdio/utils:initialiseServices: TypeError: SauceLabs is not a constructor
    at new SauceLauncher (Code/dh-classlist/node_modules/@wdio/sauce-service/build/launcher.js:23:21)
    at initialiseLauncherService (Code/dh-classlist/node_modules/@wdio/cli/node_modules/@wdio/utils/build/initialiseServices.js:94:39)
    at async Launcher.run (Code/dh-classlist/node_modules/@wdio/cli/build/launcher.js:69:65)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Working on it as we speak 😉
