### ISSUE TITLE
[🐛 Bug]: scrollIntoView actions error with Appium with v8 upgrade

### ISSUE THREAD

**Issue by dannyfink** [webdriverio/webdriverio#9320]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8

### Node.js Version

18.12.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    'bstack:options': {
        deviceName: 'iPhone 11 Pro',
        realMobile: true,
        appiumVersion: '1.22.0',
        osVersion: '15',
        acceptInsecureCerts: 'true',
    },
    acceptInsecureCerts: true,
    browserName: 'iPhone',
    'appium:safariIgnoreFraudWarning': true,
}
```

### What happened?

attempting to run the command `await <locator>.scrollIntoView()` on a mobile device as had previously worked in wdio v7 now appears to provide the following error:
```
An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Only actions of '(
    pointer,
    key
)' types are supported. 'wheel' is given instead for action with id 'action1'" UserInfo={NSLocalizedDescription=Only actions of '(
    pointer,
    key
)' types are supported. 'wheel' is given instead for action with id 'action1'}
```

I am not entirely sure if the new actions API changes may require myself to modify how scrolling with appium is handled, but this worked out of the box on webview prior to v8 upgrade.

### What is your expected behavior?

command to work as expected

### How to reproduce the bug.

```typescript
await browser.url('https://webdriver.io')
const footer = await $('footer.footer')
await footer.waitForDisplayed()
await footer.scrollIntoView()
```

### Relevant log output

```typescript
2022-12-05 19:38:35:313 - [HTTP] <-- GET /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/element/%3Awdc%3A1670269115256/displayed 200 15 ms - 14
2022-12-05 19:38:35:313 - [HTTP] 
2022-12-05 19:38:36:449 - [HTTP] --> POST /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/element
2022-12-05 19:38:36:450 - [HTTP] {"using":"css selector","value":"html"}
2022-12-05 19:38:36:450 - [debug] [W3C (1c814dca)] Calling AppiumDriver.findElement() with args: ["css selector","html","1c814dca-ab39-4a02-81f1-eb5207cfccd1"]
2022-12-05 19:38:36:450 - [debug] [XCUITest] Executing command 'findElement'
2022-12-05 19:38:36:450 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
2022-12-05 19:38:36:450 - [debug] [BaseDriver] Waiting up to 0 ms for condition
2022-12-05 19:38:36:451 - [debug] [RemoteDebugger] Executing atom 'find_element' with 'args=["css selector","html",null]; frames='
2022-12-05 19:38:36:451 - [debug] [RemoteDebugger] Executing 'find_element' atom in default context
2022-12-05 19:38:36:451 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var k=this;functi...'
2022-12-05 19:38:36:452 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:19546', page '1', target 'page-20' (id: 100): 'Runtime.evaluate'
2022-12-05 19:38:36:467 - [debug] [RemoteDebugger] Received data response from send (id: 100): '"{\"status\":0,\"value\":{\"ELEMENT\":\":wdc:1670269115257\"}}"'
2022-12-05 19:38:36:467 - [debug] [RemoteDebugger] Sending to Web Inspector took 16ms
2022-12-05 19:38:36:468 - [debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1670269115257"}
2022-12-05 19:38:36:468 - [debug] [W3C (1c814dca)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":":wdc:1670269115257","ELEMENT":":wdc:1670269115257"}
2022-12-05 19:38:36:469 - [HTTP] <-- POST /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/element 200 19 ms - 101
2022-12-05 19:38:36:469 - [HTTP] 
2022-12-05 19:38:36:636 - [HTTP] --> GET /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/element/%3Awdc%3A1670269115257/rect
2022-12-05 19:38:36:636 - [HTTP] {}
2022-12-05 19:38:36:642 - [debug] [W3C (1c814dca)] Calling AppiumDriver.getElementRect() with args: [":wdc:1670269115257","1c814dca-ab39-4a02-81f1-eb5207cfccd1"]
2022-12-05 19:38:36:642 - [debug] [XCUITest] Executing command 'getElementRect'
2022-12-05 19:38:36:642 - [debug] [RemoteDebugger] Executing atom 'get_top_left_coordinates' with 'args=[{"ELEMENT":":wdc:1670269115257"}]; frames='
2022-12-05 19:38:36:644 - [debug] [RemoteDebugger] Executing 'get_top_left_coordinates' atom in default context
2022-12-05 19:38:36:644 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var h,l=this;func...'
2022-12-05 19:38:36:645 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:19546', page '1', target 'page-20' (id: 102): 'Runtime.evaluate'
2022-12-05 19:38:36:657 - [debug] [RemoteDebugger] Received data response from send (id: 102): '"{\"status\":0,\"value\":{\"x\":0,\"y\":0,\"toString\":\"function (){return\\\"(\\\"+this.x+\\\", \\\"+this.y+\\\")\\\"}\",\"ceil\":\"function (){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);r...'
2022-12-05 19:38:36:657 - [debug] [RemoteDebugger] Sending to Web Inspector took 13ms
2022-12-05 19:38:36:657 - [debug] [RemoteDebugger] Received result for atom 'get_top_left_coordinates' execution: {"x":0,"y":0}
2022-12-05 19:38:36:657 - [debug] [RemoteDebugger] Executing atom 'get_size' with 'args=[{"ELEMENT":":wdc:1670269115257"}]; frames='
2022-12-05 19:38:36:658 - [debug] [RemoteDebugger] Executing 'get_size' atom in default context
2022-12-05 19:38:36:658 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var h=this;functi...'
2022-12-05 19:38:36:658 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:19546', page '1', target 'page-20' (id: 104): 'Runtime.evaluate'
2022-12-05 19:38:36:671 - [debug] [RemoteDebugger] Received data response from send (id: 104): '"{\"status\":0,\"value\":{\"width\":375,\"height\":635}}"'
2022-12-05 19:38:36:671 - [debug] [RemoteDebugger] Sending to Web Inspector took 13ms
2022-12-05 19:38:36:672 - [debug] [RemoteDebugger] Received result for atom 'get_size' execution: {"width":375,"height":635}
2022-12-05 19:38:36:672 - [debug] [W3C (1c814dca)] Responding to client with driver.getElementRect() result: {"x":0,"y":0,"width":375,"height":635}
2022-12-05 19:38:36:672 - [HTTP] <-- GET /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/element/%3Awdc%3A1670269115257/rect 200 36 ms - 48
2022-12-05 19:38:36:673 - [HTTP] 
2022-12-05 19:38:36:823 - [HTTP] --> GET /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/element/%3Awdc%3A1670269115256/rect
2022-12-05 19:38:36:823 - [HTTP] {}
2022-12-05 19:38:36:827 - [debug] [W3C (1c814dca)] Calling AppiumDriver.getElementRect() with args: [":wdc:1670269115256","1c814dca-ab39-4a02-81f1-eb5207cfccd1"]
2022-12-05 19:38:36:827 - [debug] [XCUITest] Executing command 'getElementRect'
2022-12-05 19:38:36:828 - [debug] [RemoteDebugger] Executing atom 'get_top_left_coordinates' with 'args=[{"ELEMENT":":wdc:1670269115256"}]; frames='
2022-12-05 19:38:36:828 - [debug] [RemoteDebugger] Executing 'get_top_left_coordinates' atom in default context
2022-12-05 19:38:36:828 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var h,l=this;func...'
2022-12-05 19:38:36:828 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:19546', page '1', target 'page-20' (id: 106): 'Runtime.evaluate'
2022-12-05 19:38:36:842 - [debug] [RemoteDebugger] Received data response from send (id: 106): '"{\"status\":0,\"value\":{\"x\":0,\"y\":-0.015625,\"toString\":\"function (){return\\\"(\\\"+this.x+\\\", \\\"+this.y+\\\")\\\"}\",\"ceil\":\"function (){this.x=Math.ceil(this.x);this.y=Math.ceil(t...'
2022-12-05 19:38:36:842 - [debug] [RemoteDebugger] Sending to Web Inspector took 14ms
2022-12-05 19:38:36:842 - [debug] [RemoteDebugger] Received result for atom 'get_top_left_coordinates' execution: {"x":0,"y":-0.015625}
2022-12-05 19:38:36:843 - [debug] [RemoteDebugger] Executing atom 'get_size' with 'args=[{"ELEMENT":":wdc:1670269115256"}]; frames='
2022-12-05 19:38:36:843 - [debug] [RemoteDebugger] Executing 'get_size' atom in default context
2022-12-05 19:38:36:843 - [debug] [RemoteDebugger] Sending javascript command: '(function(){return function(){var h=this;functi...'
2022-12-05 19:38:36:844 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to app 'PID:19546', page '1', target 'page-20' (id: 108): 'Runtime.evaluate'
2022-12-05 19:38:36:869 - [debug] [RemoteDebugger] Received data response from send (id: 108): '"{\"status\":0,\"value\":{\"width\":375,\"height\":950}}"'
2022-12-05 19:38:36:870 - [debug] [RemoteDebugger] Sending to Web Inspector took 26ms
2022-12-05 19:38:36:870 - [debug] [RemoteDebugger] Received result for atom 'get_size' execution: {"width":375,"height":950}
2022-12-05 19:38:36:870 - [debug] [W3C (1c814dca)] Responding to client with driver.getElementRect() result: {"x":0,"y":-0.015625,"width":375,"height":950}
2022-12-05 19:38:36:871 - [HTTP] <-- GET /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/element/%3Awdc%3A1670269115256/rect 200 47 ms - 56
2022-12-05 19:38:36:871 - [HTTP] 
2022-12-05 19:38:37:043 - [HTTP] --> POST /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/actions
2022-12-05 19:38:37:043 - [HTTP] {"actions":[{"id":"action1","type":"wheel","parameters":{},"actions":[{"type":"scroll","x":0,"y":0,"deltaX":0,"deltaY":-315,"duration":200,"origin":{"element-6066-11e4-a52e-4f735466cecf":":wdc:1670269115256"}}]}]}
2022-12-05 19:38:37:044 - [debug] [W3C (1c814dca)] Calling AppiumDriver.performActions() with args: [[{"id":"action1","type":"wheel","parameters":{},"actions":[{"type":"scroll","x":0,"y":0,"deltaX":0,"deltaY":-315,"duration":200,"origin":{"element-6066-11e4-a52e-4f735466cecf":":wdc:1670269115256"}}]}],"1c814dca-ab39-4a02-81f1-eb5207cfccd1"]
2022-12-05 19:38:37:044 - [debug] [XCUITest] Executing command 'performActions'
2022-12-05 19:38:37:044 - [debug] [XCUITest] Received the following W3C actions: [
2022-12-05 19:38:37:044 - [debug] [XCUITest]   {
2022-12-05 19:38:37:044 - [debug] [XCUITest]     "id": "action1",
2022-12-05 19:38:37:044 - [debug] [XCUITest]     "type": "wheel",
2022-12-05 19:38:37:044 - [debug] [XCUITest]     "parameters": {},
2022-12-05 19:38:37:044 - [debug] [XCUITest]     "actions": [
2022-12-05 19:38:37:044 - [debug] [XCUITest]       {
2022-12-05 19:38:37:044 - [debug] [XCUITest]         "type": "scroll",
2022-12-05 19:38:37:044 - [debug] [XCUITest]         "x": 0,
2022-12-05 19:38:37:044 - [debug] [XCUITest]         "y": 0,
2022-12-05 19:38:37:044 - [debug] [XCUITest]         "deltaX": 0,
2022-12-05 19:38:37:044 - [debug] [XCUITest]         "deltaY": -315,
2022-12-05 19:38:37:044 - [debug] [XCUITest]         "duration": 200,
2022-12-05 19:38:37:045 - [debug] [XCUITest]         "origin": {
2022-12-05 19:38:37:045 - [debug] [XCUITest]           "element-6066-11e4-a52e-4f735466cecf": ":wdc:1670269115256"
2022-12-05 19:38:37:045 - [debug] [XCUITest]         }
2022-12-05 19:38:37:045 - [debug] [XCUITest]       }
2022-12-05 19:38:37:045 - [debug] [XCUITest]     ]
2022-12-05 19:38:37:045 - [debug] [XCUITest]   }
2022-12-05 19:38:37:045 - [debug] [XCUITest] ]
2022-12-05 19:38:37:045 - [debug] [XCUITest] Preprocessed actions: [
2022-12-05 19:38:37:045 - [debug] [XCUITest]   {
2022-12-05 19:38:37:045 - [debug] [XCUITest]     "id": "action1",
2022-12-05 19:38:37:045 - [debug] [XCUITest]     "type": "wheel",
2022-12-05 19:38:37:045 - [debug] [XCUITest]     "parameters": {},
2022-12-05 19:38:37:045 - [debug] [XCUITest]     "actions": [
2022-12-05 19:38:37:045 - [debug] [XCUITest]       {
2022-12-05 19:38:37:045 - [debug] [XCUITest]         "type": "scroll",
2022-12-05 19:38:37:045 - [debug] [XCUITest]         "x": 0,
2022-12-05 19:38:37:045 - [debug] [XCUITest]         "y": 0,
2022-12-05 19:38:37:045 - [debug] [XCUITest]         "deltaX": 0,
2022-12-05 19:38:37:045 - [debug] [XCUITest]         "deltaY": -315,
2022-12-05 19:38:37:046 - [debug] [XCUITest]         "duration": 200,
2022-12-05 19:38:37:046 - [debug] [XCUITest]         "origin": {
2022-12-05 19:38:37:046 - [debug] [XCUITest]           "element-6066-11e4-a52e-4f735466cecf": ":wdc:1670269115256"
2022-12-05 19:38:37:046 - [debug] [XCUITest]         }
2022-12-05 19:38:37:046 - [debug] [XCUITest]       }
2022-12-05 19:38:37:046 - [debug] [XCUITest]     ]
2022-12-05 19:38:37:046 - [debug] [XCUITest]   }
2022-12-05 19:38:37:046 - [debug] [XCUITest] ]
2022-12-05 19:38:37:050 - [debug] [WD Proxy] Matched '/actions' to command name 'performActions'
2022-12-05 19:38:37:051 - [debug] [WD Proxy] Proxying [POST /actions] to [POST http://127.0.0.1:8406/session/112E99D6-45EA-4C70-9F6A-803E1BF20297/actions] with body: {"actions":[{"id":"action1","type":"wheel","parameters":{},"actions":[{"type":"scroll","x":0,"y":0,"deltaX":0,"deltaY":-315,"duration":200,"origin":{"ELEMENT":":wdc:1670269115256","element-6066-11e4-a52e-4f735466cecf":":wdc:1670269115256"}}]}]}
2022-12-05 19:38:37:770 - [WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Only actions of '(\n    pointer,\n    key\n)' types are supported. 'wheel' is given instead for action with id 'action1'\" UserInfo={NSLocalizedDescription=Only actions of '(\n    pointer,\n    key\n)' types are supported. 'wheel' is given instead for action with id 'action1'}","traceback":""},"sessionId":"112E99D6-45EA-4C70-9F6A-803E1BF20297"}
2022-12-05 19:38:37:770 - [debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Only actions of '(
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     pointer,
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     key
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)] )' types are supported. 'wheel' is given instead for action with id 'action1'" UserInfo={NSLocalizedDescription=Only actions of '(
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     pointer,
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     key
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)] )' types are supported. 'wheel' is given instead for action with id 'action1'}
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     at errorFromW3CJsonCode (/nix/store/8j95l4nrfkddk06lqrn6bg0ni7ffspkk-appium-1.22.0/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     at ProxyRequestError.getActualError (/nix/store/8j95l4nrfkddk06lqrn6bg0ni7ffspkk-appium-1.22.0/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     at JWProxy.command (/nix/store/8j95l4nrfkddk06lqrn6bg0ni7ffspkk-appium-1.22.0/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:273:19)
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     at runMicrotasks (<anonymous>)
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     at XCUITestDriver.proxyCommand (/nix/store/8j95l4nrfkddk06lqrn6bg0ni7ffspkk-appium-1.22.0/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
2022-12-05 19:38:37:782 - [debug] [W3C (1c814dca)]     at XCUITestDriver.performActions (/nix/store/8j95l4nrfkddk06lqrn6bg0ni7ffspkk-appium-1.22.0/node_modules/appium-xcuitest-driver/lib/commands/gesture.js:131:10)
2022-12-05 19:38:37:783 - [HTTP] <-- POST /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/actions 500 740 ms - 1804
2022-12-05 19:38:37:783 - [HTTP] 
2022-12-05 19:38:37:985 - [HTTP] --> POST /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/actions
2022-12-05 19:38:37:985 - [HTTP] {"actions":[{"id":"action1","type":"wheel","parameters":{},"actions":[{"type":"scroll","x":0,"y":0,"deltaX":0,"deltaY":-315,"duration":200,"origin":{"element-6066-11e4-a52e-4f735466cecf":":wdc:1670269115256"}}]}]}
2022-12-05 19:38:37:986 - [debug] [W3C (1c814dca)] Calling AppiumDriver.performActions() with args: [[{"id":"action1","type":"wheel","parameters":{},"actions":[{"type":"scroll","x":0,"y":0,"deltaX":0,"deltaY":-315,"duration":200,"origin":{"element-6066-11e4-a52e-4f735466cecf":":wdc:1670269115256"}}]}],"1c814dca-ab39-4a02-81f1-eb5207cfccd1"]
2022-12-05 19:38:37:986 - [debug] [XCUITest] Executing command 'performActions'
2022-12-05 19:38:37:986 - [debug] [XCUITest] Received the following W3C actions: [
2022-12-05 19:38:37:986 - [debug] [XCUITest]   {
2022-12-05 19:38:37:986 - [debug] [XCUITest]     "id": "action1",
2022-12-05 19:38:37:986 - [debug] [XCUITest]     "type": "wheel",
2022-12-05 19:38:37:986 - [debug] [XCUITest]     "parameters": {},
2022-12-05 19:38:37:986 - [debug] [XCUITest]     "actions": [
2022-12-05 19:38:37:986 - [debug] [XCUITest]       {
2022-12-05 19:38:37:986 - [debug] [XCUITest]         "type": "scroll",
2022-12-05 19:38:37:986 - [debug] [XCUITest]         "x": 0,
2022-12-05 19:38:37:986 - [debug] [XCUITest]         "y": 0,
2022-12-05 19:38:37:986 - [debug] [XCUITest]         "deltaX": 0,
2022-12-05 19:38:37:986 - [debug] [XCUITest]         "deltaY": -315,
2022-12-05 19:38:37:986 - [debug] [XCUITest]         "duration": 200,
2022-12-05 19:38:37:986 - [debug] [XCUITest]         "origin": {
2022-12-05 19:38:37:986 - [debug] [XCUITest]           "element-6066-11e4-a52e-4f735466cecf": ":wdc:1670269115256"
2022-12-05 19:38:37:986 - [debug] [XCUITest]         }
2022-12-05 19:38:37:987 - [debug] [XCUITest]       }
2022-12-05 19:38:37:987 - [debug] [XCUITest]     ]
2022-12-05 19:38:37:987 - [debug] [XCUITest]   }
2022-12-05 19:38:37:987 - [debug] [XCUITest] ]
2022-12-05 19:38:37:987 - [debug] [XCUITest] Preprocessed actions: [
2022-12-05 19:38:37:987 - [debug] [XCUITest]   {
2022-12-05 19:38:37:987 - [debug] [XCUITest]     "id": "action1",
2022-12-05 19:38:37:987 - [debug] [XCUITest]     "type": "wheel",
2022-12-05 19:38:37:987 - [debug] [XCUITest]     "parameters": {},
2022-12-05 19:38:37:987 - [debug] [XCUITest]     "actions": [
2022-12-05 19:38:37:987 - [debug] [XCUITest]       {
2022-12-05 19:38:37:987 - [debug] [XCUITest]         "type": "scroll",
2022-12-05 19:38:37:987 - [debug] [XCUITest]         "x": 0,
2022-12-05 19:38:37:987 - [debug] [XCUITest]         "y": 0,
2022-12-05 19:38:37:987 - [debug] [XCUITest]         "deltaX": 0,
2022-12-05 19:38:37:987 - [debug] [XCUITest]         "deltaY": -315,
2022-12-05 19:38:37:987 - [debug] [XCUITest]         "duration": 200,
2022-12-05 19:38:37:987 - [debug] [XCUITest]         "origin": {
2022-12-05 19:38:37:987 - [debug] [XCUITest]           "element-6066-11e4-a52e-4f735466cecf": ":wdc:1670269115256"
2022-12-05 19:38:37:987 - [debug] [XCUITest]         }
2022-12-05 19:38:37:987 - [debug] [XCUITest]       }
2022-12-05 19:38:37:988 - [debug] [XCUITest]     ]
2022-12-05 19:38:37:988 - [debug] [XCUITest]   }
2022-12-05 19:38:37:988 - [debug] [XCUITest] ]
2022-12-05 19:38:37:988 - [debug] [WD Proxy] Matched '/actions' to command name 'performActions'
2022-12-05 19:38:37:989 - [debug] [WD Proxy] Proxying [POST /actions] to [POST http://127.0.0.1:8406/session/112E99D6-45EA-4C70-9F6A-803E1BF20297/actions] with body: {"actions":[{"id":"action1","type":"wheel","parameters":{},"actions":[{"type":"scroll","x":0,"y":0,"deltaX":0,"deltaY":-315,"duration":200,"origin":{"ELEMENT":":wdc:1670269115256","element-6066-11e4-a52e-4f735466cecf":":wdc:1670269115256"}}]}]}
2022-12-05 19:38:37:996 - [WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Only actions of '(\n    pointer,\n    key\n)' types are supported. 'wheel' is given instead for action with id 'action1'\" UserInfo={NSLocalizedDescription=Only actions of '(\n    pointer,\n    key\n)' types are supported. 'wheel' is given instead for action with id 'action1'}","traceback":""},"sessionId":"112E99D6-45EA-4C70-9F6A-803E1BF20297"}
2022-12-05 19:38:37:997 - [debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Only actions of '(
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)]     pointer,
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)]     key
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)] )' types are supported. 'wheel' is given instead for action with id 'action1'" UserInfo={NSLocalizedDescription=Only actions of '(
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)]     pointer,
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)]     key
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)] )' types are supported. 'wheel' is given instead for action with id 'action1'}
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)]     at errorFromW3CJsonCode (/nix/store/8j95l4nrfkddk06lqrn6bg0ni7ffspkk-appium-1.22.0/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)]     at ProxyRequestError.getActualError (/nix/store/8j95l4nrfkddk06lqrn6bg0ni7ffspkk-appium-1.22.0/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)]     at JWProxy.command (/nix/store/8j95l4nrfkddk06lqrn6bg0ni7ffspkk-appium-1.22.0/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:273:19)
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)]     at runMicrotasks (<anonymous>)
2022-12-05 19:38:37:997 - [debug] [W3C (1c814dca)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-12-05 19:38:37:998 - [debug] [W3C (1c814dca)]     at XCUITestDriver.proxyCommand (/nix/store/8j95l4nrfkddk06lqrn6bg0ni7ffspkk-appium-1.22.0/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
2022-12-05 19:38:37:998 - [debug] [W3C (1c814dca)]     at XCUITestDriver.performActions (/nix/store/8j95l4nrfkddk06lqrn6bg0ni7ffspkk-appium-1.22.0/node_modules/appium-xcuitest-driver/lib/commands/gesture.js:131:10)
2022-12-05 19:38:37:998 - [HTTP] <-- POST /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/actions 500 13 ms - 1804
2022-12-05 19:38:37:998 - [HTTP] 
2022-12-05 19:38:38:126 - [HTTP] --> POST /wd/hub/session/1c814dca-ab39-4a02-81f1-eb5207cfccd1/actions
2022-12-05 19:38:38:126 - [HTTP] {"actions":[{"id":"action1","type":"wheel","parameters":{},"actions":[{"type":"scroll","x":0,"y":0,"deltaX":0,"deltaY":-315,"duration":200,"origin":{"element-6066-11e4-a52e-4f735466cecf":":wdc:1670269115256"}}]}]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Unfortunately it seems that Appium doesn't support `wheel` type for WebDriver actions. I'ld suggest to have a fallback here to the old JS execution approach from v7 in case it fails to ensure we stay compatible.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by lacell75** [comment]
I reproduce this issue on Firefox with the latest version and I don't use appium.
https://github.com/webdriverio/webdriverio/issues/9404#issuecomment-1357767786
