### ISSUE TITLE
[🐛 Bug]: <title> Getting protocol error intermediately 

### ISSUE THREAD

**Issue by sunilkumar-cap** [webdriverio/webdriverio#9345]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.24.0

### Node.js Version

14.15.3

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
            args: ['--no-sandbox', '--disable-dev-shm-usage', '--headless']
   }
```

### What happened?

Hi guys 
i'm getting the below error while running the test case on headless mode but this is an intermediate issue,
Protocol error (Runtime.getProperties): Cannot find context with specified id
ProtocolError: Protocol error (Runtime.getProperties): Cannot find context with specified id
    at /usr/wdio/node_modules/puppeteer-core/src/common/Connection.ts:304:16
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/wdio/node_modules/puppeteer-core/src/common/Connection.ts:300:12)
    at JSHandle.getProperties (/usr/wdio/node_modules/puppeteer-core/src/common/JSHandle.ts:237:41)
    at ElementHandle.$x (/usr/wdio/node_modules/puppeteer-core/src/common/JSHandle.ts:1125:42)
    at runMicrotasks (<anonymous>)
    at async DOMWorld.$x (/usr/wdio/node_modules/puppeteer-core/src/common/DOMWorld.ts:199:19)
    at async DevToolsDriver.findElement (/usr/wdio/node_modules/devtools/build/utils.js:86:16)
    at async Browser.wrappedCommand (/usr/wdio/node_modules/devtools/build/devtoolsdriver.js:128:26)
Package.json:
{
  "name": "logcollect",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "Platform": "browser=chrome runId=1 cluster=crm-nightly-new module=insights npx wdio test/wdio.conf.ts --suite smoke"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@rpii/wdio-commands": "^7.0.4",
    "@types/mocha": "^9.1.1",
    "@wdio/cli": "^7.20.7",
    "webdriverio": "^7.24.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.7.4",
    "@wdio/types": "^7.8.0"
  },
  "devDependencies": {
    "@types/supertest": "^2.0.12",
    "@wdio/local-runner": "^7.20.7",
    "@wdio/mocha-framework": "^7.20.7",
    "@wdio/spec-reporter": "^7.20.7",
    "log4js": "^6.6.1",
    "supertest": "^6.2.4",
    "wdio-docker-service": "^3.0.0",
    "wdio-html-nice-reporter": "^8.0.3-beta2"
  }
}

### How to reproduce the bug.

our test cases runs on container every hour and we are seeing this issue 1 or 2 times out of 24 runs

### Relevant log output

```typescript
Assertion: Protocol error (Runtime.getProperties): Cannot find context with specified id

Protocol error (Runtime.getProperties): Cannot find context with specified id
ProtocolError: Protocol error (Runtime.getProperties): Cannot find context with specified id
    at /usr/wdio/node_modules/puppeteer-core/src/common/Connection.ts:304:16
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/wdio/node_modules/puppeteer-core/src/common/Connection.ts:300:12)
    at JSHandle.getProperties (/usr/wdio/node_modules/puppeteer-core/src/common/JSHandle.ts:237:41)
    at ElementHandle.$x (/usr/wdio/node_modules/puppeteer-core/src/common/JSHandle.ts:1125:42)
    at runMicrotasks (<anonymous>)
    at async DOMWorld.$x (/usr/wdio/node_modules/puppeteer-core/src/common/DOMWorld.ts:199:19)
    at async DevToolsDriver.findElement (/usr/wdio/node_modules/devtools/build/utils.js:86:16)
    at async Browser.wrappedCommand (/usr/wdio/node_modules/devtools/build/devtoolsdriver.js:128:26)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@sunilkumar-cap can you provide a reproducible example? I was running the following script a couple of times without issues:

```js
import { remote } from 'webdriverio'

const browser = await remote({
    capabilities: {
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
            args: ['--no-sandbox', '--disable-dev-shm-usage', '--headless']
        }
    }
})

console.log(await browser.url('https://webdriver.io'))
await browser.deleteSession()
```

Please understand that we can't do much if we can't reproduce it. Also note that your are using the devtools protocol for automation, we recommend using WebDriver. Please make sure you have a driver running.

**Comment by christian-bromann** [comment]
Closing due to inactivity.
