### ISSUE TITLE
[🐛 Bug]: Getting ECONNREFUSED when running tests on WDIO v8 with Appium v2

### ISSUE THREAD

**Issue by automationbro** [webdriverio/webdriverio#9357]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.9

### Node.js Version

18.2.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        "platformName": "iOS",
        "appium:platformVersion": "14.5",
        "appium:deviceName": "iPhone 12 Pro",
        "appium:automationName": "XCUITest",
        "appium:app": path.join(process.cwd(), "app/wdioNativeDemoApp.app"),
    }],
```

### What happened?

Unable to run tests with WebdriverIO v8 and Appium 2.0 versions. Same setup worked fine with WebdriverIO v7.  Getting ECONNREFUSED error and Appium is unable to connect to Port 4723.

### What is your expected behavior?

Should be able to run tests (same as v7)

### How to reproduce the bug.

Clone the following repo - https://github.com/sam-022/wdio-appium-v8
Install dependencies and run tests using `npx wdio` 

### Relevant log output

```typescript
[0-0] 2022-12-09T02:44:35.650Z ERROR webdriver: RequestError: connect ECONNREFUSED 127.0.0.1:4723
[0-0]     at ClientRequest.<anonymous> (file:///Users/sam/Desktop/automation/wdio-appium-v8/node_modules/got/dist/source/core/index.js:789:107)
[0-0]     at Object.onceWrapper (node:events:642:26)
[0-0]     at ClientRequest.emit (node:events:539:35)
[0-0]     at ClientRequest.emit (node:domain:475:12)
[0-0]     at Socket.socketErrorListener (node:_http_client:454:9)
[0-0]     at Socket.emit (node:events:527:28)
[0-0]     at Socket.emit (node:domain:475:12)
[0-0]     at emitErrorNT (node:internal/streams/destroy:151:8)
[0-0]     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[0-0]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
[0-0] 2022-12-09T02:44:35.650Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] Unable to connect to "http://127.0.0.1:4723/", make sure browser driver is running on that address.
[0-0] If you use services like chromedriver see initialiseServices logs above or in wdio.log file as the service might had problems to start the driver.
[0-0]     at startWebDriverSession (file:///Users/sam/Desktop/automation/wdio-appium-v8/node_modules/webdriver/build/utils.js:68:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async Function.newSession (file:///Users/sam/Desktop/automation/wdio-appium-v8/node_modules/webdriver/build/index.js:24:45)
[0-0]     at async remote (file:///Users/sam/Desktop/automation/wdio-appium-v8/node_modules/webdriverio/build/index.js:45:22)
[0-0]     at async Runner._startSession (file:///Users/sam/Desktop/automation/wdio-appium-v8/node_modules/@wdio/runner/build/index.js:221:29)
[0-0]     at async Runner._initSession (file:///Users/sam/Desktop/automation/wdio-appium-v8/node_modules/@wdio/runner/build/index.js:187:25)
[0-0]     at async Runner.run (file:///Users/sam/Desktop/automation/wdio-appium-v8/node_modules/@wdio/runner/build/index.js:77:19)
[0-0] FAILED in iOS - file:///test/specs/sample.js
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Fixed in https://github.com/webdriverio/webdriverio/pull/9364
