### ISSUE TITLE
[🐛 Bug]: Export CJS files for Allure Reporter

### ISSUE THREAD

**Issue by bhanuagarwal73** [webdriverio/webdriverio#9406]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.13

### Node.js Version

16.13.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstances: 3,
        browserName: runtimeArgs.browserName,
        acceptInsecureCerts: true,

        "goog:chromeOptions": runtimeArgs.browserName === 'chrome' ? {
            "args": ["user-agent=gcp-automation-test (Windows NT)",
                `${process.env.HEADLESS === 'true' ? '--headless' : undefined}`,
                `${process.env.HEADLESS === 'true' ? '--window-size=1920,1080' : undefined}`
            ]
        } : {},

        "bstack:options": runtimeArgs.service === 'browserstack' ? {
            "projectName": "merx-shopify-automation",
            "buildName": `${runtimeArgs.env} - ${runtimeArgs.brand} - ${runtimeArgs.suite} - ${runtimeArgs.browserName}`,
            "os": runtimeArgs.os,
            "osVersion": runtimeArgs.osVersion,
            "deviceName": runtimeArgs.device,
            "networkLogs": true,
            "consoleLogs": "errors",
            "browserVersion": "latest",
            "local": true
        } : {}
    }],


tsconfig.json
{
    "compilerOptions": {
        "esModuleInterop": true,
        "types": [
            "node",
            "@wdio/globals/types",
            "@wdio/mocha-framework"
        ],
        "target": "ES5",
        "downlevelIteration": true
    }
}
```

### What happened?

2022-12-19T09:36:44.352Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///E:/merx-shopify-automation/wdio.conf.ts: require() of ES Module E:\merx-shopify-automation\node_modules\@wdio\allure-reporter\build\index.js from E:\merx-shopify-automation\wdio.conf.ts not supported. 
Instead change the require of index.js in E:\merx-shopify-automation\wdio.conf.ts to a dynamic import() which is available in all CommonJS modules.    
Error [ERR_REQUIRE_ESM]: require() of ES Module E:\merx-shopify-automation\node_modules\@wdio\allure-reporter\build\index.js from E:\merx-shopify-automation\wdio.conf.ts not supported.
Instead change the require of index.js in E:\merx-shopify-automation\wdio.conf.ts to a dynamic import() which is available in all CommonJS modules.    
    at Object.require.extensions.<computed> [as .js] (E:\merx-shopify-automation\node_modules\ts-node\dist\index.js:851:20)
    at Object.<anonymous> (E:\merx-shopify-automation\wdio.conf.ts:45:41)
    at Module.m._compile (E:\merx-shopify-automation\node_modules\ts-node\dist\index.js:857:29)
    at Object.require.extensions.<computed> [as .ts] (E:\merx-shopify-automation\node_modules\ts-node\dist\index.js:859:16)
    at async Promise.all (index 0)
    at async ConfigParser.addConfigFile (file:///E:/merx-shopify-automation/node_modules/@wdio/config/build/lib/ConfigParser.js:67:36)
    at async ConfigParser.initialize (file:///E:/merx-shopify-automation/node_modules/@wdio/config/build/lib/ConfigParser.js:45:13)
    at async Launcher.run (file:///E:/merx-shopify-automation/node_modules/@wdio/cli/build/launcher.js:37:9) {
  code: 'ERR_REQUIRE_ESM'
}

I am seeing error from allure report that should use import & not require (its expected as we switched to ESM, so need to update the Allure Report)

### What is your expected behavior?

User should able to run the project with allure report generation after upgrading to ESM

### How to reproduce the bug.

Just hit npm run BVT, it should run the cases & shouldn't throw any ESM related errors for allure reports.

### Relevant log output

```typescript
{
    "compilerOptions": {
        "esModuleInterop": true,
        "types": [
            "node",
            "@wdio/globals/types",
            "@wdio/mocha-framework"
        ],
        "target": "ES5",
        "downlevelIteration": true
    }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by NaZaRKIN123** [comment]
I'm facing the same issue.

**Comment by anandhaprakash-mani** [comment]
same
