### ISSUE TITLE
maximizeWindow method is not supported in microsoft edge browser

### ISSUE THREAD

**Issue by tbaruah58** [webdriverio/webdriverio#9432]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.20.7

### Node.js Version

Node.js v16.16.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
 browserName: 'MicrosoftEdge',
 browserVersion: '108.0.1462.54'
}
```

### What happened?

I am getting below exception if I run same my testcases in microsoftedge browser
Error: Command "maximizeWindow" is not yet implemented

Please note that the same set of test cases work fine for chrome and firefox browser.

### How to reproduce the bug.

The browser is launched after executing the test case and as soon as its luanched we try to maximize the window and in this step the test case is failing.

### Relevant log output

```typescript
Execution of 1 workers started at 2022-12-20T14:52:38.373Z

[0-0] Error in "Smoke - MicrosoftEdge.TC001"
Error: Command "maximizeWindow" is not yet implemented
    at Browser.retries (C:\workflow-solutions\web-app\client\application\tests\webdriverio-test\node_modules\devtools\build\devtoolsdriver.js:90:34)      
    at Browser.wrapCommandFn (C:\workflow-solutions\web-app\client\application\tests\webdriverio-test\node_modules\@wdio\utils\build\shim.js:137:38)      
    at LoginPage.openElsevierURL (c:\workflow-solutions\web-app\client\application\tests\webdriverio-test\test\pageObjects\/page.js:56:9)
    at Context.<anonymous> (c:\workflow-solutions\web-app\client\application\tests\webdriverio-test\test\specs\OS_Sanity\Elsevier\/TC001_AddOrderSetToLibraryAndQuickEdit.js:11:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for filing the issue!

It seems you are using the Devtools protocol for that capability where this command is not supported. Puppeteer has limitations changing the window size. I recommend to set up [Edgedriver](https://webdriver.io/docs/wdio-edgedriver-service) if you use the wdio testrunner which makes you run the automation with WebDriver.
