### ISSUE TITLE
[🐛 Bug]: <Unable to use TimelineService>

### ISSUE THREAD

**Issue by ashutoshphalke** [webdriverio/webdriverio#9443]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.0.13

### Node.js Version

18.11.17

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{ 
maxInstances: 5,
browserName: "chrome",
acceptInsecureCerts: true,
}
```

### What happened?

I imported timeline service in wdio.conf.js using below
const { TimelineService } = require("wdio-timeline-reporter/timeline-service");

added below settings in same file
`services: ["chromedriver", "safaridriver", TimelineService],`
`reporters: [
    "spec",
    [
      "allure",
      {
        outputDir: "allure-results",
        disableWebdriverStepsReporting: false,
        disableWebdriverScreenshotsReporting: false,
      },
    ],
    ["timeline", { outputDir: "./report_timeline" }],
  ],`

get below error
`[0-0] 2022-12-23T16:22:31.264Z ERROR @wdio/runner: Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays
[0-0]     at validateConfig (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/config/build/utils.js:62:27)
[0-0]     at remote (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/webdriverio/build/index.js:26:20)
[0-0]     at initialiseInstance (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/utils.js:55:16)
[0-0]     at Runner._startSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:221:35)
[0-0]     at Runner.run (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:58:34)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] RUNNING in chrome - file:///test/specs/testLogin.e2e.ts
[0-0] 2022-12-23T16:22:31.507Z ERROR @wdio/runner: Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays
[0-0]     at validateConfig (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/config/build/utils.js:62:27)
[0-0]     at remote (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/webdriverio/build/index.js:26:20)
[0-0]     at initialiseInstance (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/utils.js:55:16)
[0-0]     at Runner._startSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:221:35)
[0-0]     at Runner._initSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:187:36)
[0-0]     at Runner.run (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:77:30)
[0-0] FAILED in chrome - file:///test/specs/testLogin.e2e.ts`

### How to reproduce the bug.

I imported timeline service in wdio.conf.js using below
const { TimelineService } = require("wdio-timeline-reporter/timeline-service");

added below settings in same file
`services: ["chromedriver", "safaridriver", TimelineService],`
`reporters: [
    "spec",
    [
      "allure",
      {
        outputDir: "allure-results",
        disableWebdriverStepsReporting: false,
        disableWebdriverScreenshotsReporting: false,
      },
    ],
    ["timeline", { outputDir: "./report_timeline" }],
  ],`

### Relevant log output

```typescript
[0-0] 2022-12-23T16:22:31.264Z ERROR @wdio/runner: Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays
[0-0]     at validateConfig (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/config/build/utils.js:62:27)
[0-0]     at remote (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/webdriverio/build/index.js:26:20)
[0-0]     at initialiseInstance (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/utils.js:55:16)
[0-0]     at Runner._startSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:221:35)
[0-0]     at Runner.run (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:58:34)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] RUNNING in chrome - file:///test/specs/testLogin.e2e.ts
[0-0] 2022-12-23T16:22:31.507Z ERROR @wdio/runner: Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays
[0-0]     at validateConfig (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/config/build/utils.js:62:27)
[0-0]     at remote (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/webdriverio/build/index.js:26:20)
[0-0]     at initialiseInstance (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/utils.js:55:16)
[0-0]     at Runner._startSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:221:35)
[0-0]     at Runner._initSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:187:36)
[0-0]     at Runner.run (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:77:30)
[0-0] FAILED in chrome - file:///test/specs/testLogin.e2e.ts
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by ashutoshphalke** [comment]
Can anyone help me in this on urgent basis?

**Comment by ashutoshphalke** [comment]
When i make it as 
services: ["chromedriver", "safaridriver", [TimelineService]],

It generate the html report but shows below compilation error

`Type '[any]' is not assignable to type 'ServiceEntry'.
  Type '[any]' is not assignable to type '[ServiceClass, ServiceOption]'.
    Source has 1 element(s) but target requires 2.ts(2322)`

**Comment by ashutoshphalke** [comment]
Can anyone help me in this on urgent basis?

**Comment by christian-bromann** [comment]
It seems you are using TypeScript but import the package via `require`. Make sure you use `import` statements.

I will go ahead and close and this is not an issue with WebdriverIO.
