### ISSUE TITLE
[🐛 Bug]: Provide CJS version for `@wdio/shared-store-service`

### ISSUE THREAD

**Issue by NaZaRKIN123** [webdriverio/webdriverio#9528]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.1.0

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### What happened?

I updated to WDIO 8, started a test run, and got the below error at the start:
ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/nazar/config/chrome.wdio.config.ts: require() of ES Module

### What is your expected behavior?

Tests should be running.

### How to reproduce the bug.

1. Update to the WDIO 8
2. Install @wdio/shared-store-service package
3. Run tests

### Relevant log output

```typescript
ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/nazar/config/chrome.wdio.config.ts: require() of ES Module /Users/nazar/node_modules/@wdio/shared-store-service/build/index.js from /Users/nazar/src/framework/userMngr.ts not supported.
Instead change the require of index.js in /Users/nazar/src/framework/userMngr.ts to a dynamic import() which is available in all CommonJS modules.
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/nazar/node_modules/@wdio/shared-store-service/build/index.js from /Users/nazar/src/framework/userMngr.ts not supported.
Instead change the require of index.js in /Users/nazar/src/framework/userMngr.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/nazar/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/nazar/src/framework/userMngr.ts:4:32)
    at m._compile (/Users/nazar/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/nazar/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/nazar/config/common.wdio.config.ts:24:23)
    at m._compile (/Users/nazar/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/nazar/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/nazar/config/chrome.wdio.config.ts:8:30)
    at m._compile (/Users/nazar/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/nazar/node_modules/ts-node/dist/index.js:859:16)
    at async Promise.all (index 0)
    at async ConfigParser.addConfigFile (file:///Users/nazar/node_modules/@wdio/config/build/lib/ConfigParser.js:67:36)
    at async ConfigParser.initialize (file:///Users/nazar/node_modules/@wdio/config/build/lib/ConfigParser.js:45:13)
    at async Launcher.run (file:///Users/nazar/node_modules/@wdio/cli/build/launcher.js:37:9)
    at async Module.run (file:///Users/nazar/node_modules/@wdio/cli/build/run.js:63:20) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

Given that users can import methods from the service via, e.g.:
```ts
import { setValue } from '@wdio/shared-store-service'
```
we need a CJS export for this package so folks running CJS projects can use and upgrade to v8.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!
