### ISSUE TITLE
[🐛 Bug]: heap out of memory with async code in before/after each blocks

### ISSUE THREAD

**Issue by bh-sergio-clara** [webdriverio/webdriverio#9564]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.29.1

### Node.js Version

18.7.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
			maxInstances: 1,
			browserName: 'chrome',
			acceptInsecureCerts: true,
			'goog:chromeOptions': {
				args: HEADLESS && [
					'--no-sandbox',
					'--disable-infobars',
					'--headless',
					'--disable-gpu',
					'--window-size=1440,735'
				],
			}
		}
```

### What happened?

Looks like async code in `beforeEach` and `afterEach` blocks gets cross-wired when there are exceptions and/or failed expectations in tests and a "heap out of memory" exception is thrown.

### What is your expected behavior?

A timeout like

```
Error: Timeout - Async function did not complete within 1000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
```

### How to reproduce the bug.

```js
describe('Testing afterEach', () => {
	jasmine.DEFAULT_TIMEOUT_INTERVAL = 1000;

	afterEach(async () => {
		await new Promise(r => setTimeout(r, 2000));
	});

	it('Should fail', async () => {
		await new Promise(r => setTimeout(r, 1));
		expect(false).toBeTrue();
	});
});

describe('Testing beforeEach', () => {
	jasmine.DEFAULT_TIMEOUT_INTERVAL = 1000;

	beforeEach(async () => {
		await new Promise(r => setTimeout(r, 2000));
	});

	it('Should fail', async () => {
		await new Promise(r => setTimeout(r, 1));
		expect(false).toBeTrue();
	});
});
```

### Relevant log output

```typescript
[0-0] <--- Last few GCs --->
[0-0] 
[0-0] [44722:0x7feb3302b000]    65862 ms: Mark-sweep 4035.9 (4141.9) -> 4031.0 (4140.5) MB, 41.4 / 0.0 ms  (average mu = 0.329, current mu = 0.303) allocation failure; scavenge might not succeed
[0-0] [44722:0x7feb3302b000]    65901 ms: Mark-sweep 4033.8 (4143.3) -> 4032.0 (4141.4) MB, 34.3 / 0.0 ms  (average mu = 0.250, current mu = 0.127) allocation failure; scavenge might not succeed
[0-0] 
[0-0] 
[0-0] <--- JS stacktrace --->
[0-0] 
[0-0] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
[0-0]  1: 0x1009b24a8 node::Abort() [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0]  2: 0x1009b3619 node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0]  3: 0x100b0c24d v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0]  4: 0x100b0c1e5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0]  5: 0x100c68097 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0]  6: 0x100c6a89a v8::internal::Heap::ComputeMutatorUtilization(char const*, double, double) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0]  7: 0x100c688aa v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0]  8: 0x100c6664d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0]  9: 0x100c5bd5d v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0] 10: 0x100c5c57d v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0] 11: 0x100c45ecb v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0] 12: 0x100f3c1b2 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0] 13: 0x10080c8b9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0] 14: 0x10088d461 Builtins_StringSlowFlatten [/usr/local/Cellar/node/18.7.0/bin/node]
[0-0] 15: 0x10088d57b Builtins_StringIndexOf [/usr/local/Cellar/node/18.7.0/bin/node]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@bh-sergio-clara I can't reproduce this error. I created a new Jasmine project using `npm init wdio` and I get the following:

```

> wdio run ./wdio.conf.js


Execution of 1 workers started at 2023-01-18T20:34:13.229Z

2023-01-18T20:34:13.248Z INFO chromedriver: Initiate Chromedriver Launcher (v8.0.1)
2023-01-18T20:34:13.249Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-01-18T20:34:13.250Z INFO chromedriver: Start Chromedriver (/private/tmp/9564/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2023-01-18T20:34:13.261Z INFO chromedriver: Starting ChromeDriver 109.0.5414.74 (e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}) on port 9515
2023-01-18T20:34:13.261Z INFO chromedriver: Only local connections are allowed.
2023-01-18T20:34:13.261Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-01-18T20:34:13.262Z INFO chromedriver: ChromeDriver was started successfully.
2023-01-18T20:34:13.361Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-01-18T20:34:13.362Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js
[0-0] 2023-01-18T20:34:13.617Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///test/specs/example.e2e.js
[0-0] 2023-01-18T20:34:13.650Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-01-18T20:34:13.688Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-01-18T20:34:13.688Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', acceptInsecureCerts: true },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', acceptInsecureCerts: true }
[0-0] }
[0-0] Error in "Testing afterEach Should fail"
    at UserContext.<anonymous> (file:///private/tmp/9564/test/specs/example.e2e.js:10:17)
[0-0] Error in "Testing beforeEach Should fail"
    at <Jasmine>
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[0-0] 2023-01-18T20:34:16.695Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-01-18T20:34:16.695Z INFO webdriver: [DELETE] http://localhost:9515/session/9c357015ddae532c2f843214990e542a
[0-0] 2023-01-18T20:34:16.750Z INFO webdriver: RESULT null
[0-0] FAILED in chrome - file:///test/specs/example.e2e.js
2023-01-18T20:34:16.859Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-01-18T20:34:16.859Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 109.0.5414.87 mac os x #0-0] Running: chrome (v109.0.5414.87) on mac os x
[chrome 109.0.5414.87 mac os x #0-0] Session ID: 9c357015ddae532c2f843214990e542a
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] » file:///test/specs/example.e2e.js
[chrome 109.0.5414.87 mac os x #0-0] Testing afterEach
[chrome 109.0.5414.87 mac os x #0-0]    ✖ Should fail
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] » unknown spec file
[chrome 109.0.5414.87 mac os x #0-0] Testing beforeEach
[chrome 109.0.5414.87 mac os x #0-0]    ✖ Should fail
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] 2 failing (2s)
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] 1) Testing afterEach Should fail
[chrome 109.0.5414.87 mac os x #0-0] TypeError: expect(...).toBeTrue is not a function
[chrome 109.0.5414.87 mac os x #0-0]     at UserContext.<anonymous> (file:///private/tmp/9564/test/specs/example.e2e.js:10:17)
[chrome 109.0.5414.87 mac os x #0-0] Error: Timeout - Async function did not complete within 1000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
[chrome 109.0.5414.87 mac os x #0-0]     at <Jasmine>
[chrome 109.0.5414.87 mac os x #0-0]     at listOnTimeout (node:internal/timers:564:17)
[chrome 109.0.5414.87 mac os x #0-0]     at process.processTimers (node:internal/timers:507:7)
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] 2) Testing beforeEach Should fail
[chrome 109.0.5414.87 mac os x #0-0] Error: Timeout - Async function did not complete within 1000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
[chrome 109.0.5414.87 mac os x #0-0]     at <Jasmine>
[chrome 109.0.5414.87 mac os x #0-0]     at listOnTimeout (node:internal/timers:564:17)
[chrome 109.0.5414.87 mac os x #0-0]     at process.processTimers (node:internal/timers:507:7)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:03

2023-01-18T20:34:16.861Z INFO @wdio/local-runner: Shutting down spawned worker
2023-01-18T20:34:17.114Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-01-18T20:34:17.115Z INFO @wdio/local-runner: shutting down
```

Note that by default you are using wdio matchers which are based on `expect` and not Jasmine. After changing the assertions:

```patch
- expect(false).toBeTrue();
+ expect(false).toBe(true);
```

I get:

```
 "spec" Reporter:
------------------------------------------------------------------
[chrome 109.0.5414.87 mac os x #0-0] Running: chrome (v109.0.5414.87) on mac os x
[chrome 109.0.5414.87 mac os x #0-0] Session ID: 7e18cb655a4b92f2e86f124b7702e96e
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] » file:///test/specs/example.e2e.js
[chrome 109.0.5414.87 mac os x #0-0] Testing afterEach
[chrome 109.0.5414.87 mac os x #0-0]    ✖ Should fail
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] » unknown spec file
[chrome 109.0.5414.87 mac os x #0-0] Testing beforeEach
[chrome 109.0.5414.87 mac os x #0-0]    ✖ Should fail
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] 2 failing (2s)
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] 1) Testing afterEach Should fail
[chrome 109.0.5414.87 mac os x #0-0] Error: expect(received).toBe(expected) // Object.is equality

Expected: true
Received: false
[chrome 109.0.5414.87 mac os x #0-0] error properties: Object({ matcherResult: Object({ actual: false, expected: true, message: 'expect(received).toBe(expected) // Object.is equality
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] Expected: true
[chrome 109.0.5414.87 mac os x #0-0] Received: false', name: 'toBe', pass: false }) })
[chrome 109.0.5414.87 mac os x #0-0] Error: expect(received).toBe(expected) // Object.is equality
[chrome 109.0.5414.87 mac os x #0-0] Expected: true
[chrome 109.0.5414.87 mac os x #0-0] Received: false
[chrome 109.0.5414.87 mac os x #0-0]     at UserContext.<anonymous> (file:///private/tmp/9564/test/specs/example.e2e.js:10:17)
[chrome 109.0.5414.87 mac os x #0-0] Error: Timeout - Async function did not complete within 1000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
[chrome 109.0.5414.87 mac os x #0-0]     at <Jasmine>
[chrome 109.0.5414.87 mac os x #0-0]     at listOnTimeout (node:internal/timers:564:17)
[chrome 109.0.5414.87 mac os x #0-0]     at process.processTimers (node:internal/timers:507:7)
[chrome 109.0.5414.87 mac os x #0-0]
[chrome 109.0.5414.87 mac os x #0-0] 2) Testing beforeEach Should fail
[chrome 109.0.5414.87 mac os x #0-0] Error: Timeout - Async function did not complete within 1000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
[chrome 109.0.5414.87 mac os x #0-0]     at <Jasmine>
[chrome 109.0.5414.87 mac os x #0-0]     at listOnTimeout (node:internal/timers:564:17)
[chrome 109.0.5414.87 mac os x #0-0]     at process.processTimers (node:internal/timers:507:7)
```

Nonetheless the heap memory error does not show up! Can you provide a reproducible example?

**Comment by christian-bromann** [comment]
Closing due to inactivity. Happy to re-open if a reproducible example can be provided.
