### ISSUE TITLE
[🐛 Bug]: <Unable to use TimelineService>

### ISSUE THREAD

**Issue by ashutoshphalke** [webdriverio/webdriverio#9577]
Have you read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues)?
 I have read the Contributing Guidelines on issues.
WebdriverIO Version
8.0.13

Node.js Version
18.11.17

Mode
WDIO Testrunner

Which capabilities are you using?
{ 
maxInstances: 5,
browserName: "chrome",
acceptInsecureCerts: true,
}
What happened?
I imported timeline service in wdio.conf.js using below
const { TimelineService } = require("wdio-timeline-reporter/timeline-service");

added below settings in same file
services: ["chromedriver", "safaridriver", TimelineService],
reporters: [ "spec", [ "allure", { outputDir: "allure-results", disableWebdriverStepsReporting: false, disableWebdriverScreenshotsReporting: false, }, ], ["timeline", { outputDir: "./report_timeline" }], ],

get below error
[0-0] 2022-12-23T16:22:31.264Z ERROR @wdio/runner: Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays [0-0]     at validateConfig (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/config/build/utils.js:62:27) [0-0]     at remote (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/webdriverio/build/index.js:26:20) [0-0]     at initialiseInstance (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/utils.js:55:16) [0-0]     at Runner._startSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:221:35) [0-0]     at Runner.run (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:58:34) [0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5) [0-0] RUNNING in chrome - file:///test/specs/testLogin.e2e.ts [0-0] 2022-12-23T16:22:31.507Z ERROR @wdio/runner: Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays [0-0]     at validateConfig (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/config/build/utils.js:62:27) [0-0]     at remote (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/webdriverio/build/index.js:26:20) [0-0]     at initialiseInstance (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/utils.js:55:16) [0-0]     at Runner._startSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:221:35) [0-0]     at Runner._initSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:187:36) [0-0]     at Runner.run (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:77:30) [0-0] FAILED in chrome - file:///test/specs/testLogin.e2e.ts

What is your expected behavior?
No response

How to reproduce the bug.
I imported timeline service in wdio.conf.js using below
const { TimelineService } = require("wdio-timeline-reporter/timeline-service");

added below settings in same file
services: ["chromedriver", "safaridriver", TimelineService],
reporters: [ "spec", [ "allure", { outputDir: "allure-results", disableWebdriverStepsReporting: false, disableWebdriverScreenshotsReporting: false, }, ], ["timeline", { outputDir: "./report_timeline" }], ],

Relevant log output
[0-0] 2022-12-23T16:22:31.264Z ERROR @wdio/runner: Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays
[0-0]     at validateConfig (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/config/build/utils.js:62:27)
[0-0]     at remote (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/webdriverio/build/index.js:26:20)
[0-0]     at initialiseInstance (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/utils.js:55:16)
[0-0]     at Runner._startSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:221:35)
[0-0]     at Runner.run (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:58:34)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] RUNNING in chrome - file:///test/specs/testLogin.e2e.ts
[0-0] 2022-12-23T16:22:31.507Z ERROR @wdio/runner: Error: Type check for option "services" failed: the "services" options needs to be a list of strings and/or arrays
[0-0]     at validateConfig (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/config/build/utils.js:62:27)
[0-0]     at remote (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/webdriverio/build/index.js:26:20)
[0-0]     at initialiseInstance (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/utils.js:55:16)
[0-0]     at Runner._startSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:221:35)
[0-0]     at Runner._initSession (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:187:36)
[0-0]     at Runner.run (file:///Users/ashutosh/MyDrive/MyProjects/POC_WebdriverIO_TS_JasminRnD/node_modules/@wdio/runner/build/index.js:77:30)
[0-0] FAILED in chrome - file:///test/specs/testLogin.e2e.ts

**Comment by ashutoshphalke** [comment]
I am using TypeScript but import the package via import statements.

**Comment by ashutoshphalke** [comment]
TimelineService is mentioned on WebdriverIO documentation and it is not working so either fix it or remove from documentation instead closing this bug
