### ISSUE TITLE
[🐛 Bug]: chrome session not being created with wdio v8.1.3

### ISSUE THREAD

**Issue by spatchamatla** [webdriverio/webdriverio#9591]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.1.3

### Node.js Version

v16.14.2 & v18.12.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    'browserName': 'chrome',
    'port': 7756,
    'acceptInsecureCerts': true,
    'goog:chromeOptions': {
        args: [
            '--headless',
            '--disable-gpu',
            '--no-sandbox',
            '--disable-infobars',
            '--disable-dev-shm-usage',
            '--disable-setuid-sandbox',
            '--window-size=1920x1080'
        ]
    }
}
```

### What happened?

using below packages:
```
"webdriverio": "8.1.3",
"@wdio/allure-reporter": "8.1.2",
"@wdio/appium-service": "8.1.3",
"@wdio/cli": "8.1.3",
"@wdio/devtools-service": "8.1.3",
"@wdio/jasmine-framework": "8.1.3",
"@wdio/local-runner": "8.1.3",
"@wdio/spec-reporter": "8.1.2",
"@wdio/browserstack-service": "8.1.3",
"wdio-chromedriver-service": "8.0.0",
"chromedriver": "108.0.0"
```
Mac m1 v12.6.1

tried with Chromedriver v108/109, during run time it errors with 
`[0-0]  Error:  Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 85`

works fine with `v7.29.1`

### What is your expected behavior?

able to start chrome session.

### How to reproduce the bug.

To reproduce:

1. install chrome driverversion https://chromedriver.storage.googleapis.com/index.html?path=108.0.5359.71/chromedriver_mac_arm64.zip
2. install above packages
3. and run wdio with any spec.

sees below error..
```
Starting ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689}) on port 7756
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[0-0] RUNNING in chrome - /tests/testWDIOV8spec.js
[0-0]  Error:  Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 85
```

in my terminal, when I use
```
chromedriver --version
ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016})
```

I don't have any chrome v85 installed on Mac.

### Relevant log output

```typescript
2023-01-14T02:14:38.692Z INFO @wdio/local-runner: Run worker command: run
2023-01-14T02:14:39.478Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
2023-01-14T02:14:40.483Z INFO webdriverio: Initiate new session using the webdriver protocol
2023-01-14T02:14:40.484Z INFO webdriver: [POST] http://localhost:7756/session
2023-01-14T02:14:40.484Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      acceptInsecureCerts: true,
      'goog:chromeOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': { args: [Array] }
  }
}
2023-01-14T02:14:41.002Z WARN webdriver: Request failed with status 500 due to session not created: This version of ChromeDriver only supports Chrome version 85
2023-01-14T02:14:41.003Z INFO webdriver: Retrying 1/3
2023-01-14T02:14:41.003Z INFO webdriver: [POST] http://localhost:7756/session
2023-01-14T02:14:41.003Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      acceptInsecureCerts: true,
      'goog:chromeOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': { args: [Array] }
  }
}
2023-01-14T02:14:41.342Z WARN webdriver: Request failed with status 500 due to session not created: This version of ChromeDriver only supports Chrome version 85
2023-01-14T02:14:41.342Z INFO webdriver: Retrying 2/3
2023-01-14T02:14:41.342Z INFO webdriver: [POST] http://localhost:7756/session
2023-01-14T02:14:41.342Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      acceptInsecureCerts: true,
      'goog:chromeOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': { args: [Array] }
  }
}
2023-01-14T02:14:41.572Z WARN webdriver: Request failed with status 500 due to session not created: This version of ChromeDriver only supports Chrome version 85
2023-01-14T02:14:41.572Z INFO webdriver: Retrying 3/3
2023-01-14T02:14:41.572Z INFO webdriver: [POST] http://localhost:7756/session
2023-01-14T02:14:41.572Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'chrome',
      acceptInsecureCerts: true,
      'goog:chromeOptions': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'chrome',
    acceptInsecureCerts: true,
    'goog:chromeOptions': { args: [Array] }
  }
}
2023-01-14T02:14:41.857Z ERROR webdriver: Request failed with status 500 due to session not created: session not created: This version of ChromeDriver only supports Chrome version 85
2023-01-14T02:14:41.857Z ERROR webdriver: session not created: session not created: This version of ChromeDriver only supports Chrome version 85
    at getErrorFromResponseBody (<path>/node_modules/webdriver/build/utils.js:121:10)
    at WebDriverRequest._request (<path>/node_modules/webdriver/build/request.js:149:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startWebDriverSession (<path>/node_modules/webdriver/build/utils.js:41:16)
    at async WebDriver.newSession (<path>/node_modules/webdriver/build/index.js:44:23)
    at async remote (<path>/node_modules/webdriverio/build/index.js:75:20)
    at async Runner._startSession (<path>/node_modules/@wdio/runner/build/index.js:204:50)
    at async Runner._initSession (<path>/node_modules/@wdio/runner/build/index.js:173:21)
    at async Runner.run (<path>/node_modules/@wdio/runner/build/index.js:91:15)
2023-01-14T02:14:41.857Z ERROR @wdio/runner: Error: Failed to create session.
session not created: This version of ChromeDriver only supports Chrome version 85
    at startWebDriverSession (<path>/node_modules/webdriver/build/utils.js:45:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebDriver.newSession (<path>/node_modules/webdriver/build/index.js:44:23)
    at async remote (<path>/node_modules/webdriverio/build/index.js:75:20)
    at async Runner._startSession (<path>/node_modules/@wdio/runner/build/index.js:204:50)
    at async Runner._initSession (<path>/node_modules/@wdio/runner/build/index.js:173:21)
    at async Runner.run (<path>/node_modules/@wdio/runner/build/index.js:91:15)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
I am not sure how you did set up your project and why this would work in v7 but as you can see in the Chromedriver error message:

> Failed to create session. session not created: This version of ChromeDriver only supports Chrome version 85

You are trying to automate Chrome 108 with a Chromedriver that only supports v85. Please make sure to update your Chromedriver to support the Chrome version you like to automate. I recommend to use the [`wdio-chromedriver-service`](https://www.npmjs.com/package/wdio-chromedriver-service) to set this up automatically with the wdio testrunner.
