### ISSUE TITLE
[🐛 Bug]: Unable to use any RDC dynamic device allocation pattern for wdio-sauce-service

### ISSUE THREAD

**Issue by jeyneslt** [webdriverio/webdriverio#9594]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19.6

### Node.js Version

16.15.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  "platformName": "iOS",
    "browserName": "Safari",
    "appium:deviceName": "iPhone.*",
    "sauce:options": {
      "extendedDebugging": true,
    }
}
```

### What happened?

Unable to RDC dynamic device allocation for testing with wdio-sauce-service. I've been able to provide a static RD ID, but any pattern that I provide does not work -- even when providing a wildcard only

### What is your expected behavior?

Any iPhone device that is available in the RDC will be allocated to the test session(s)

### How to reproduce the bug.
```typescript
{
  "name": "wdio-ui-test",
  "version": "1.0.0",
  "description": "....",
  "main": "index.js",
  "scripts": {
    "lint": "npx eslint . --ext .ts --fix",
    "crypt": "npx ts-node ./utils/crypto.ts",
    "local": "npx wdio run ./config/profiles/wdio.mocha.local.conf.ts",
    "saucelabs": "npx wdio run ./config/profiles/wdio.mocha.saucelabs.conf.ts",
    "allure": "npx allure generate ./reports/allure-results --clean && allure open -h localhost"
  },
  "license": "ISC",
  "devDependencies": {
    "@types/crypto-js": "^4.0.2",
    "@types/faker": "^5.5.8",
    "@types/mocha": "^9.1.1",
    "@typescript-eslint/eslint-plugin": "^4.26.0",
    "@typescript-eslint/parser": "^4.26.0",
    "@wdio/allure-reporter": "^7.10.1",
    "@wdio/cli": "^7.19.6",
    "@wdio/devtools-service": "^7.25.4",
    "@wdio/globals": "^8.1.3",
    "@wdio/junit-reporter": "7.10.1",
    "@wdio/local-runner": "^7.19.5",
    "@wdio/logger": "^7.7.0",
    "@wdio/mocha-framework": "^7.16.0",
    "@wdio/selenium-standalone-service": "7.10.1",
    "@wdio/shared-store-service": "7.28.0",
    "@wdio/types": "^7.10.1",
    "axios": "^1.2.2",
    "crypto-js": "^4.1.1",
    "dateformat": "^4.5.1",
    "deepmerge": "^4.2.2",
    "dotenv": "^10.0.0",
    "eslint": "^7.32.0",
    "eslint-plugin-filenames": "^1.3.2",
    "eslint-plugin-folders": "^1.0.3",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-mocha": "^10.1.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-unused-imports": "^2.0.0",
    "eslint-plugin-wdio": "^8.0.0",
    "expect-webdriverio": "^3.5.3",
    "faker": "^5.5.3",
    "fs-extra": "^10.0.0",
    "log4js": "^6.3.0",
    "saucelabs": "^7.2.0",
    "tesseract.js": "^3.0.3",
    "tmp": "0.2.1",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "^3.12.0",
    "typescript": "^4.9.3",
    "wdio-allure-ts": "^6.4.2",
    "wdio-intercept-service": "^4.2.2",
    "wdio-sauce-service": "0.4.14"
  },
  "dependencies": {
    "mocha": "^9.2.2"
  }
}
```

```typescript
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "ts-node": {
    "transpileOnly": true,
    "files": true,
  },
  "compilerOptions": {
    "target": "ES2019",
    "module": "CommonJS",
    "composite": true,
    "outDir": "./.tsbuild/",
    "rootDir": ".",
    "removeComments": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "declaration": true,
    "lib": [
      "dom"
    ],
    "types": [
      "@wdio/types",
      "@wdio/mocha-framework",
      "@wdio/devtools-service",
      "@wdio/shared-store-service",
      "@wdio/allure-reporter",
      "@wdio/cli",
      "@wdio/globals",
      "webdriverio/async",
      "wdio-intercept-service",
      "webdriverio",
      "expect-webdriverio",
      "node",
      "mocha",
      "axios",
    ]
  },
  "include": [
    "./**/*.ts",
    "./tests/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

```typescript
exports.config =  {
  headless: false,
  user: Config.saucelabs.user,
  key: Config.saucelabs.key,
  region: Config.saucelabs.region,
  maxInstances: Config.maxInstances,
  capabilities: [{
 'platformName': 'iOS',
    'browserName': 'Safari',
    'appium:deviceName': 'iPhone.*',
    'sauce:options': {
      'extendedDebugging': true,
    }
}],
  services: ['intercept', 'shared-store', 'sauce'],
  specs: ['./tests/**/*.ts'],
  exclude: [],
  suites: {},
  waitforTimeout: 30000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  framework: 'mocha',
  reporters: [
    [
      'junit', {
        outputDir: 'reports/junit'
        outputFileFormat: (options: any) => `results.${options.cid}.xml`,
        errorOptions: {
          error: 'message',
          failure: 'message',
          stacktrace: 'stack',
        },
      },
    ],
    ['allure', {
      outputDir: 'reports/allure',
      disableWebdriverStepsReporting: true,
    }],
  ],
  autoCompileOpts: {
    autoCompile: true,
    tsNodeOpts: {
      transpileOnly: true,
      project: 'tsconfig.json'
    },
  },
  mochaOpts: {
    require: "ts-node/register",
    timeout: 300000,
    ui: 'bdd'
  },
  logLevel: 'error',
}
```

### Relevant log output

```typescript
Execution of 1 workers started at 2023-01-16T00:24:28.091Z

[0-0] RUNNING in Safari - /tests/sign-up.test.ts
[0-0] 2023-01-16T00:24:36.113Z ERROR webdriver: Request failed with status 500 due to WebDriver Error: There is no device that matches your criteria. DesiredCapabilities: {"capabilities":{"firstMatch":[{"browserName":"Safari","platformName":"iOS","appium:deviceName":"iPhone.*","wdio:sharedStoreServicePort":52320.0,"sauce:options":{"extendedDebugging":true}}]}}
[0-0] Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
[0-0] System info: host: 'Sauce Labs RDC', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.133+', java.version: '11.0.17'
[0-0] Driver info: driver.version: unknown
[0-0] 2023-01-16T00:24:36.114Z ERROR webdriver: WebDriver Error: There is no device that matches your criteria. DesiredCapabilities: {"capabilities":{"firstMatch":[{"browserName":"Safari","platformName":"iOS","appium:deviceName":"iPhone.*","wdio:sharedStoreServicePort":52320.0,"sauce:options":{"extendedDebugging":true}}]}}
[0-0] Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
[0-0] System info: host: 'Sauce Labs RDC', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.133+', java.version: '11.0.17'
[0-0] Driver info: driver.version: unknown
[0-0]     at getErrorFromResponseBody (../node_modules/webdriver/build/utils.js:198:12)
[0-0]     at NodeJSRequest._request (../node_modules/webdriver/build/request/index.js:166:60)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async startWebDriverSession (../node_modules/webdriver/build/utils.js:68:20)
[0-0]     at async Function.newSession (../node_modules/webdriver/build/index.js:46:45)
[0-0]     at async remote (../node_modules/webdriverio/build/index.js:78:22)
[0-0]     at async Runner._startSession (../node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (../node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (../node_modules/@wdio/runner/build/index.js:88:19)
[0-0] 2023-01-16T00:24:36.117Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] There is no device that matches your criteria. DesiredCapabilities: {"capabilities":{"firstMatch":[{"browserName":"Safari","platformName":"iOS","appium:deviceName":"iPhone.*","wdio:sharedStoreServicePort":52320.0,"sauce:options":{"extendedDebugging":true}}]}}
[0-0] Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
[0-0] System info: host: 'Sauce Labs RDC', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.133+', java.version: '11.0.17'
[0-0] Driver info: driver.version: unknown
[0-0]     at startWebDriverSession (../node_modules/webdriver/build/utils.js:73:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at async Function.newSession (../node_modules/webdriver/build/index.js:46:45)
[0-0]     at async remote (../node_modules/webdriverio/build/index.js:78:22)
[0-0]     at async Runner._startSession (../node_modules/@wdio/runner/build/index.js:223:56)
[0-0]     at async Runner._initSession (../node_modules/@wdio/runner/build/index.js:176:25)
[0-0]     at async Runner.run (../node_modules/@wdio/runner/build/index.js:88:19)
[0-0] 2023-01-16T00:24:36.121Z ERROR @wdio/utils:shim: TypeError: browser.pause is not a function
[0-0]     at Object.after (../config/profiles/wdio.mocha.base.conf.ts:92:19)
[0-0]     at ..//node_modules/@wdio/utils/build/shim.js:88:27
[0-0]     at new Promise (<anonymous>)
[0-0]     at ../node_modules/@wdio/utils/build/shim.js:85:47
[0-0]     at Array.map (<anonymous>)
[0-0]     at executeHooksWithArgsShim (../node_modules/@wdio/utils/build/shim.js:85:33)
[0-0]     at Runner.run (../node_modules/@wdio/runner/build/index.js:94:52)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] FAILED in Safari - /tests/sign-up.test.ts
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by jeyneslt** [comment]
Closing

**Comment by christian-bromann** [comment]
> I've been able to provide a static RD ID, but any pattern that I provide does not work -- even when providing a wildcard only

I don't see any RD ID being applied. Given I don't know how Sauce RDC service works I recommend to reach out to Sauce support. They should provide you with reference material and should contribute to the service for better integrations when it comes to RDC.
