### ISSUE TITLE
Bug : ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id

### ISSUE THREAD

**Issue by ShanmukhaGajula** [webdriverio/webdriverio#9619]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.11.0

### Node.js Version

16.17.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
services: [
        
        ['chromedriver'
        , {
        port: 9515,
        path: "/wd/hub/",
        chromedriverCustomPath:"./node_modules/electron-chromedriver/bin/chromedriver.exe"
        }
    ]
```

### What happened?

WDIO is throwing below error when interatacting with few elements, however browser is being opened it is not closed 

[0-5] 2023-01-18T09:12:39.363Z ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id
[0-5] [ERROR]: uncaughtException: invalid session id
[0-5] invalid session id: invalid session id
[0-5]     at getErrorFromResponseBody (C:\august\sb-automation\node_modules\webdriver\build\utils.js:198:12)
[0-5]     at NodeJSRequest._request (C:\august\sb-automation\node_modules\webdriver\build\request\index.js:166:60)
[0-5]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-5]     at async Element.wrapCommandFn (C:\august\sb-automation\node_modules\@wdio\utils\build\shim.js:137:29)
[0-5]     at async Element.wrapCommandFn (C:\august\sb-automation\node_modules\@wdio\utils\build\shim.js:137:29)
[0-5]     at async Element.elementErrorHandlerCallbackFn (C:\august\sb-automation\node_modules\webdriverio\build\middlewares.js:24:32)
[0-5]     at async Element.wrapCommandFn (C:\august\sb-automation\node_modules\@wdio\utils\build\shim.js:137:29)
[0-5]     at async Element.wrapCommandFn (C:\august\sb-automation\node_modules\@wdio\utils\build\shim.js:137:29)
[0-5]     at async Element.elementErrorHandlerCallbackFn (C:\august\sb-automation\node_modules\webdriverio\build\middlewares.js:24:32)
[0-5]     at async Element.wrapCommandFn (C:\august\sb-automation\node_modules\@wdio\utils\build\shim.js:137:29)

### How to reproduce the bug.

I am using the electron app and trying to automate, which is throwing an invalid session in between the run.

### Relevant log output

```typescript
[0-5] 2023-01-18T09:12:39.363Z ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id
[0-5] [ERROR]: uncaughtException: invalid session id
[0-5] invalid session id: invalid session id
[0-5]     at getErrorFromResponseBody (C:\august\sb-automation\node_modules\webdriver\build\utils.js:198:12)
[0-5]     at NodeJSRequest._request (C:\august\sb-automation\node_modules\webdriver\build\request\index.js:166:60)
[0-5]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-5]     at async Element.wrapCommandFn (C:\august\sb-automation\node_modules\@wdio\utils\build\shim.js:137:29)
[0-5]     at async Element.wrapCommandFn (C:\august\sb-automation\node_modules\@wdio\utils\build\shim.js:137:29)
[0-5]     at async Element.elementErrorHandlerCallbackFn (C:\august\sb-automation\node_modules\webdriverio\build\middlewares.js:24:32)
[0-5]     at async Element.wrapCommandFn (C:\august\sb-automation\node_modules\@wdio\utils\build\shim.js:137:29)
[0-5]     at async Element.wrapCommandFn (C:\august\sb-automation\node_modules\@wdio\utils\build\shim.js:137:29)
[0-5]     at async Element.elementErrorHandlerCallbackFn (C:\august\sb-automation\node_modules\webdriverio\build\middlewares.js:24:32)
[0-5]     at async Element.wrapCommandFn (C:\august\sb-automation\node_modules\@wdio\utils\build\shim.js:137:29)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by lacell75** [comment]
Hello @ShanmukhaGajula , Did you find a solution? I have the same issue in my side.

**Comment by christian-bromann** [comment]
This error: `invalid session id` means that your test failed, the session was closed but you still call more commands. It is likely due to a missing `await`. There is no general solution to this.

**Comment by lacell75** [comment]
> This error: `invalid session id` means that your test failed, the session was closed but you still call more commands. It is likely due to a missing `await`. There is no general solution to this.

I confirm. I fixed in my side due to a missing await.
