### ISSUE TITLE
[🐛 Bug]: `visibilitychange` event is not triggered in chrome headless mode when switching tabs

### ISSUE THREAD

**Issue by potty** [webdriverio/webdriverio#9694]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.2

### Node.js Version

18.12.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  'browserName': 'chrome',
  'goog:chromeOptions': {
    args: ['--headless', '--no-sandbox'],
  },
  'acceptInsecureCerts': true,
}
```

### What happened?

When I create a new tab and switch to this tab, then switch back to the first tab, I would expect that `visibilitychange` [event](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) would be triggered event in the headless mode. It works as expected in non-headless mode.

### How to reproduce the bug.

Testing spec file:

``` js
describe('My test app', () => {
    it('should test visibility change', async () => {
        await browser.url(`http://localhost:5173`)

        const $visibilityCounter = $('#visibility-counter')
        await expect($visibilityCounter).toHaveTextContaining('visibility count is 0')

        const initialTabId = await browser.getWindowHandle()
        const newTabId = await browser.createWindow('tab')

        await browser.switchToWindow(newTabId.handle)
        await browser.switchToWindow(initialTabId)

        await expect($visibilityCounter).toHaveTextContaining('visibility count is 1')
    })
})
```

On the testing page, I use this simple script to increment counter whenever visibility state changes:

```js
export function setupVisibilityCounter(element: HTMLButtonElement) {
	let visibilityCounter = 0;

	const setCounter = (count: number) => {
		visibilityCounter = count;
		element.innerHTML = `visibility count is ${visibilityCounter}`;
	};
	setCounter(0);

	const visibilityListener = () => {
		if (document.visibilityState === "visible") {
			setCounter(visibilityCounter + 1);
		}
	};

	document.addEventListener("visibilitychange", visibilityListener);
}


### Relevant log output

```typescript
2023-01-30T13:53:02.471Z INFO chromedriver: Initiate Chromedriver Launcher (v8.0.1)
2023-01-30T13:53:02.472Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-01-30T13:53:02.474Z INFO chromedriver: Start Chromedriver (/Users/potty/Projects/webdriverio-test/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2023-01-30T13:53:02.492Z INFO chromedriver: Starting ChromeDriver 109.0.5414.74 (e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}) on port 9515
2023-01-30T13:53:02.493Z INFO chromedriver: Only local connections are allowed.
2023-01-30T13:53:02.493Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-01-30T13:53:02.507Z INFO chromedriver: ChromeDriver was started successfully.
2023-01-30T13:53:02.586Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-01-30T13:53:02.587Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] 2023-01-30T13:53:03.012Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///test/specs/example.e2e.ts
[0-0] 2023-01-30T13:53:03.127Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-01-30T13:53:03.182Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-01-30T13:53:03.182Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'goog:chromeOptions': [Object],
[0-0]       acceptInsecureCerts: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': { args: [Array] },
[0-0]     acceptInsecureCerts: true
[0-0]   }
[0-0] }
[0-0] 2023-01-30T13:53:03.664Z INFO webdriver: COMMAND navigateTo("http://localhost:5173/")
[0-0] 2023-01-30T13:53:03.665Z INFO webdriver: [POST] http://localhost:9515/session/84652f4334be373cd606d94143380148/url
[0-0] 2023-01-30T13:53:03.665Z INFO webdriver: DATA { url: 'http://localhost:5173/' }
[0-0] 2023-01-30T13:53:03.784Z INFO webdriver: RESULT null
[0-0] 2023-01-30T13:53:03.785Z INFO webdriver: COMMAND findElement("css selector", "#visibility-counter")
[0-0] 2023-01-30T13:53:03.785Z INFO webdriver: [POST] http://localhost:9515/session/84652f4334be373cd606d94143380148/element
[0-0] 2023-01-30T13:53:03.786Z INFO webdriver: DATA { using: 'css selector', value: '#visibility-counter' }
[0-0] 2023-01-30T13:53:03.798Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '2adb6681-8956-4e67-87ec-86dd14b9d294'
[0-0] }
[0-0] 2023-01-30T13:53:03.801Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:03.801Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:03.818Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:03.819Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2023-01-30T13:53:03.819Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/window
[0-0] 2023-01-30T13:53:03.821Z INFO webdriver: RESULT CDwindow-5B09C69E41E48FF50D938FD91F701E05
[0-0] 2023-01-30T13:53:03.821Z INFO webdriver: COMMAND createWindow("tab")
[0-0] 2023-01-30T13:53:03.821Z INFO webdriver: [POST] http://localhost:9515/session/84652f4334be373cd606d94143380148/window/new
[0-0] 2023-01-30T13:53:03.821Z INFO webdriver: DATA { type: 'tab' }
[0-0] 2023-01-30T13:53:03.825Z INFO webdriver: RESULT { handle: 'CDwindow-7B00E28C1544BAFF220F019795FF13ED', type: 'tab' }
[0-0] 2023-01-30T13:53:03.825Z INFO webdriver: COMMAND switchToWindow("CDwindow-7B00E28C1544BAFF220F019795FF13ED")
[0-0] 2023-01-30T13:53:03.825Z INFO webdriver: [POST] http://localhost:9515/session/84652f4334be373cd606d94143380148/window
[0-0] 2023-01-30T13:53:03.825Z INFO webdriver: DATA { handle: 'CDwindow-7B00E28C1544BAFF220F019795FF13ED' }
[0-0] 2023-01-30T13:53:03.856Z INFO webdriver: RESULT null
[0-0] 2023-01-30T13:53:03.856Z INFO webdriver: COMMAND switchToWindow("CDwindow-5B09C69E41E48FF50D938FD91F701E05")
[0-0] 2023-01-30T13:53:03.856Z INFO webdriver: [POST] http://localhost:9515/session/84652f4334be373cd606d94143380148/window
[0-0] 2023-01-30T13:53:03.856Z INFO webdriver: DATA { handle: 'CDwindow-5B09C69E41E48FF50D938FD91F701E05' }
[0-0] 2023-01-30T13:53:03.858Z INFO webdriver: RESULT null
[0-0] 2023-01-30T13:53:03.858Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:03.858Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:03.863Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:04.367Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:04.370Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:04.382Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:04.885Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:04.887Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:04.898Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:05.401Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:05.404Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:05.418Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:05.918Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:05.919Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:05.931Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:06.433Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:06.434Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:06.447Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:06.950Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:06.952Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:06.963Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:07.470Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:07.472Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:07.481Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:07.993Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:07.993Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:08.002Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:08.507Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:08.508Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:08.517Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:09.019Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:09.019Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:09.029Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:09.534Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:09.535Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:09.545Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:10.047Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:10.047Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:10.053Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:10.562Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:10.562Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:10.572Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:11.075Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:11.076Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:11.084Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:11.586Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:11.589Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:11.599Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:12.101Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:12.102Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:12.109Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:12.612Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:12.613Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:12.623Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:13.124Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:13.126Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:13.137Z INFO webdriver: RESULT visibility count is 0
[0-0] 2023-01-30T13:53:13.639Z INFO webdriver: COMMAND getElementText("2adb6681-8956-4e67-87ec-86dd14b9d294")
[0-0] 2023-01-30T13:53:13.641Z INFO webdriver: [GET] http://localhost:9515/session/84652f4334be373cd606d94143380148/element/2adb6681-8956-4e67-87ec-86dd14b9d294/text
[0-0] 2023-01-30T13:53:13.652Z INFO webdriver: RESULT visibility count is 0
[0-0] Error in "My test app.should test visibility change"
Error: Expect $(`#visibility-counter`) to have text containing

Expected: "visibility count is 1"
Received: "visibility count is 0"
    at Context.<anonymous> (file:///Users/potty/Projects/webdriverio-test/test/specs/example.e2e.ts:14:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0] 2023-01-30T13:53:14.166Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-01-30T13:53:14.166Z INFO webdriver: [DELETE] http://localhost:9515/session/84652f4334be373cd606d94143380148
[0-0] 2023-01-30T13:53:14.219Z INFO webdriver: RESULT null
[0-0] FAILED in chrome - file:///test/specs/example.e2e.ts
2023-01-30T13:53:14.329Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-01-30T13:53:14.329Z INFO @wdio/cli:launcher: Run onComplete hook

 "spec" Reporter:
------------------------------------------------------------------
[chrome 109.0.5414.119 mac os x #0-0] Running: chrome (v109.0.5414.119) on mac os x
[chrome 109.0.5414.119 mac os x #0-0] Session ID: 84652f4334be373cd606d94143380148
[chrome 109.0.5414.119 mac os x #0-0]
[chrome 109.0.5414.119 mac os x #0-0] » /test/specs/example.e2e.ts
[chrome 109.0.5414.119 mac os x #0-0] My test app
[chrome 109.0.5414.119 mac os x #0-0]    ✖ should test visibility change
[chrome 109.0.5414.119 mac os x #0-0]
[chrome 109.0.5414.119 mac os x #0-0] 1 failing (10.5s)
[chrome 109.0.5414.119 mac os x #0-0]
[chrome 109.0.5414.119 mac os x #0-0] 1) My test app should test visibility change
[chrome 109.0.5414.119 mac os x #0-0] Expect $(`#visibility-counter`) to have text containing

Expected: "visibility count is 1"
Received: "visibility count is 0"
[chrome 109.0.5414.119 mac os x #0-0] Error: Expect $(`#visibility-counter`) to have text containing
[chrome 109.0.5414.119 mac os x #0-0]
[chrome 109.0.5414.119 mac os x #0-0] Expected: "visibility count is 1"
[chrome 109.0.5414.119 mac os x #0-0] Received: "visibility count is 0"
[chrome 109.0.5414.119 mac os x #0-0]     at Context.<anonymous> (file:///Users/potty/Projects/webdriverio-test/test/specs/example.e2e.ts:14:42)
[chrome 109.0.5414.119 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:11 

2023-01-30T13:53:14.331Z INFO @wdio/local-runner: Shutting down spawned worker
2023-01-30T13:53:14.584Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-01-30T13:53:14.584Z INFO @wdio/local-runner: shutting down
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
WebdriverIO is not particularly responsible for this browser feature. I assumption is that switching tabs with WebDriver does not trigger the browser to trigger the API which would be a specification issue. Let's investigate this before we prematurely close it. Any contributions are welcome.

**Comment by potty** [comment]
@christian-bromann can you please direct me, to where should I try to look for it? Could it be chromedriver?

**Comment by christian-bromann** [comment]
Closing as this can't be fixed in WebdriverIO.
