### ISSUE TITLE
[🐛 Bug]: Selenium exited before it could start with code 1

### ISSUE THREAD

**Issue by tbaruah58-elsv** [webdriverio/webdriverio#9798]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^7.20.7

### Node.js Version

14

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
"npm": "^7.24.2",
    "rimraf": "^3.0.2",
    "wdio-docker-service": "^3.2.1",
    "wdio-rerun-service": "^1.7.3",
    "webdriverio": "^7.20.7"
  },
  "devDependencies": {
    "@wdio/selenium-standalone-service": "^7.30.0"
  }
}
```

### What happened?

My testcases are working fine in my local windows machine for all the browser without any issue while using selenium standalone service.
But when I try to run it in Jenkins(EC2) server, it fails with the following error.

Execution of 1 workers started at 2023-02-20T14:02:56.427Z

2023-02-20T14:03:00.039Z ERROR @wdio/selenium-standalone-service: Error: Selenium exited before it could start with code 1
Stdout: 
Stderr: 
    at checkStarted (/var/lib/jenkins/Deleteme2/web-app/client/application/tests/webdriverio-test/node_modules/selenium-standalone/lib/check-started.js:44:13)
    at Object.start (/var/lib/jenkins/Deleteme2/web-app/client/application/tests/webdriverio-test/node_modules/selenium-standalone/lib/start.js:160:3)
Build step 'Execute shell' marked build as failure 

### How to reproduce the bug.

Try to execute testcases in jenkins(Ec2) server using selenium standalone service.

### Relevant log output

```typescript
Execution of 1 workers started at 2023-02-20T14:02:56.427Z

2023-02-20T14:03:00.039Z ERROR @wdio/selenium-standalone-service: Error: Selenium exited before it could start with code 1
Stdout: 
Stderr: 
    at checkStarted (/var/lib/jenkins/Deleteme2/web-app/client/application/tests/webdriverio-test/node_modules/selenium-standalone/lib/check-started.js:44:13)
    at Object.start (/var/lib/jenkins/Deleteme2/web-app/client/application/tests/webdriverio-test/node_modules/selenium-standalone/lib/start.js:160:3)
Build step 'Execute shell' marked build as failure
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> @wdio/selenium-standalone-service: Error: Selenium exited before it could start with code 1
> Stdout:
> Stderr:

This seems to me that the Selenium Standalone server can't be started in your CI. Can you try to run it manually to see if there are more useful information available?

**Comment by tbaruah58-elsv** [comment]
npm install @wdio/selenium-standalone-service --save-dev

added 128 packages, and audited 129 packages in 6s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New major version of npm available! 8.19.2 -> 9.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.0
npm notice Run npm install -g npm@9.5.0 to update!
npm notice

**Comment by christian-bromann** [comment]
@tbaruah58-elsv this shows how you install the package, I was asking about the stdout when you try to run the Java file

**Comment by christian-bromann** [comment]
Closing due to inactivity. Happy to re-open if more information can be provided.
