### ISSUE TITLE
[🐛 Bug]: click event throws error with WinAppDriver Elements

### ISSUE THREAD

**Issue by antpowell** [webdriverio/webdriverio#9868]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.3.11

### Node.js Version

18.14.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  app: 'Root',
  automationName: 'windows',
  deviceName: 'windowsPC'
}
```

### What happened?

I'm working with WinAppDriver, I am able to find the element in the Win32 app but when I try to get the `WebdriverIO.Element` for it the command `findElement("-android datamatcher", "{"ELEMENT":"42.230890640.4.4"}")`, where `"ELEMENT":"42.230890640.4.4"` is the Win32 element found, breaks with a "The selector ___ used with strategy "-android datamatcher" is invalid!"

How I attempted to get the element to allow for the click action:
![image](https://user-images.githubusercontent.com/10569986/222093981-835070ff-a9d4-4252-a1a9-833a64a3b72a.png)

Output of CLI:
![image](https://user-images.githubusercontent.com/10569986/222095456-428bdbc8-dc80-4911-8de2-c3e12c26a603.png)

### How to reproduce the bug.

To reproduce:
```typescript
const capabilities: Capabilities.AppiumCapabilities = {
  app: 'Root',
  automationName: 'windows',
  deviceName: 'windowsPC'
};

const webdriverIoOptions: RemoteOptions = {
  hostname: '127.0.0.1' || 'localhost',
  port: 4723,
  connectionRetryCount: 0,
  capabilities
};

const driver = await remote(webdriverIoOptions);

const continueBtn = await driver.$(await driver.findElement('accessibility id', 'StartButton'));
  continueBtn.click({ button: 'left' });
```

Ensure WinAppDriver is installed and running, should look like this in the terminal:
![image](https://user-images.githubusercontent.com/10569986/222096758-2bfdcb33-caf5-4419-ab88-b1d92250377f.png)

### Relevant log output

```typescript
2023-03-01T09:18:57.917Z INFO webdriver: Initiate new session using the WebDriver protocol
2023-03-01T09:18:58.067Z INFO webdriver: [POST] http://127.0.0.1:4723/session
2023-03-01T09:18:58.067Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: { app: 'Root', automationName: 'windows', deviceName: 'windowsPC' },
    firstMatch: [ {} ]
  },
  desiredCapabilities: { app: 'Root', automationName: 'windows', deviceName: 'windowsPC' }
}
2023-03-01T09:18:58.109Z INFO webdriver: COMMAND findElement("accessibility id", "StartButton")
2023-03-01T09:18:58.110Z INFO webdriver: [POST] http://127.0.0.1:4723/session/093FA550-6202-4A8D-B22F-2876E096C31D/element
2023-03-01T09:18:58.110Z INFO webdriver: DATA { using: 'accessibility id', value: 'StartButton' }
2023-03-01T09:19:10.690Z INFO webdriver: RESULT { ELEMENT: '42.67072.4.104' }
2023-03-01T09:19:10.691Z INFO webdriver: COMMAND findElement("-android datamatcher", "{"ELEMENT":"42.67072.4.104"}")
2023-03-01T09:19:10.691Z INFO webdriver: [POST] http://127.0.0.1:4723/session/093FA550-6202-4A8D-B22F-2876E096C31D/element
2023-03-01T09:19:10.692Z INFO webdriver: DATA {
  using: '-android datamatcher',
  value: '{"ELEMENT":"42.67072.4.104"}'
}
2023-03-01T09:19:10.716Z ERROR webdriver: Request failed with status 400 due to invalid selector: The selector "{"ELEMENT":"42.67072.4.104"}" used with strategy "-android datamatcher" is invalid! For more information on selectors visit the WebdriverIO docs at: https://webdriver.io/docs/selectors
file:///D:/MSFT/node_modules/webdriver/build/utils.js:194
    return new CustomRequestError(body, requestOptions);
           ^
invalid selector: The selector "{"ELEMENT":"42.67072.4.104"}" used with strategy "-android datamatcher" is invalid! For more information on selectors visit the WebdriverIO docs at: https://webdriver.io/docs/selectors
    at getErrorFromResponseBody (file:///D:/MSFT/node_modules/webdriver/build/utils.js:194:12)
    at NodeJSRequest._request (file:///D:/MSFT/node_modules/webdriver/build/request/index.js:164:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Browser.wrapCommandFn (file:///D:/MSFT/node_modules/@wdio/utils/build/shim.js:72:29)
    at async Browser.$ (file:///D:/MSFT/node_modules/webdriverio/build/commands/browser/$.js:89:17)
    at async Browser.wrapCommandFn (file:///D:/MSFT/node_modules/@wdio/utils/build/shim.js:72:29)
    at async win32Login (file:///D:/MSFT/VisualParityTest/login.ts:67:23)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
It seems WinAppDriver returns an invalid element response due to the fact it is not W3C compatible. WebdriverIO has moved on to be standard compliant and can't deal with old JSONWireProtocol responses anymore. Given that I would not recommend to use this driver for automation, looking at the issue list it seems to be a dead project.

I will close as I am not interested fixing bugs for MS legacy tools. If you like to work on PRs that improve this situation I am open to merge them.
