### ISSUE TITLE
[🐛 Bug]: Error line is pointed wrongly by Webdriver.io

### ISSUE THREAD

**Issue by matheusneumannsuiteit** [webdriverio/webdriverio#9877]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.24.0

### Node.js Version

v14.20.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
        platformName: 'Android',
        maxInstances: 1,
        'appium:deviceType': 'phone',
        'appium:orientation': 'PORTRAIT',
        'appium:automationName': 'UiAutomator2',
        'appium:app': join(process.cwd(), '.*******.apk'),
        'appium:noReset': true,
        'appium:newCommandTimeout': 480,
    },
{

    runner: 'local',
    framework: 'cucumber',
    sync: true,
    logLevel: 'trace',
    deprecationWarnings: true,
    outputDir: './test-report/output',
    bail: 0,
    baseUrl: 'http://the-internet.herokuapp.com',
    waitforTimeout: 8000,
    connectionRetryTimeout: 100000,
    connectionRetryCount: 3,
    specs: ['tests/features/**/*.feature'],
    reporters: [
        'spec',
        [
            video,
            {
                saveAllVideos: true,
                videoSlowdownMultiplier: 5,
                videoRenderTimeout: 30,
                maxTestNameCharacters: 500,
            },
        ],
        [
            'allure',
            {
                outputDir: './test-report/allure-result/',
                disableWebdriverStepsReporting: true,
                disableWebdriverScreenshotsReporting: true,
                useCucumberStepReporter: true,
            },
        ],
    ],
    cucumberOpts: {
        requireModule: ['@babel/register'],
        backtrace: false,
        compiler: [],
        dryRun: false,
        failFast: false,
        format: ['pretty'],
        colors: true,
        snippets: true,
        source: true,
        profile: [],
        strict: false,
        tags: [],
        timeout: 10000000,
        ignoreUndefinedDefinitions: false,
        tagExpression: 'not @skip',
    },
    services: [
        'appium',
    ],
    appium: {
        log: false,
        args: {

        },
        command: 'appium',
    },

    port: 4723,
}
```

### What happened?

Evidence with root cause

Error message presented by WebDriver.IO:
[0-0] Error in "12: Then A tela deve apresentar texto, seguindo as informações apresentadas para o usuário"
Error: element ("~Valores em Milhões de reais - Consolidado IFRS") still not displayed after 8000ms
at async World.<anonymous> 

It indicates an error in the app.empresa_balanco.steps.js file, line 263. However, in this line we have "];" : 
![image](https://user-images.githubusercontent.com/112020287/222497642-09d7cb04-acf4-458e-863a-98d7a396ae89.png)

What doesn't match with the error, because the error message indicates that the element "Valores em Milhões de reais - Consolidado IFRS" was not found (still not displayed) even after 8 seconds of waiting.

If you search (Ctrl - Shift - F) for "Valores em Milhões de reais - Consolidado IFRS":
![image](https://user-images.githubusercontent.com/112020287/222498191-db8d409d-ed3b-4403-a24d-1a3bc7f3a8e4.png)
This String value will be found in the FOOTER_TEXT field.

The FOOTER_TEXT field is returned in the get footerText() method.

The get footerText() method is called in the app.empresa_balanco.steps.js file on line 286, unlike the WebDriver.IO log, which erroneously points to line 263.

![image](https://user-images.githubusercontent.com/112020287/222498482-c7902286-41fe-4295-b630-0f17d24b08ae.png)

### What is your expected behavior?

It should point the correct line (286)

### How to reproduce the bug.

Create a project in Javascript with webdriver.io and when a test fails, if you look for the line of the error webdriver.io points you to a wrong line.

### Relevant log output

```typescript
[0-0] Error in "12: Then A tela deve apresentar texto, seguindo as informações apresentadas para o usuário"
Error: element ("~Valores em Milhões de reais - Consolidado IFRS") still not displayed after 8000ms
    at async World.<anonymous> 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> Create a project in Javascript with webdriver.io and when a test fails, if you look for the line of the error webdriver.io points you to a wrong line.

This doesn't reproduce the issue, when creating a failing test like this:
![Screenshot 2023-03-02 at 09 10 34](https://user-images.githubusercontent.com/731337/222501727-3bf7d941-f1fe-4a61-8b29-ebb39c467fc6.png)

I get the correct line:

```
[chrome 110.0.5481.177 mac os x #0-0] Error: Expect $(`#flash`) to have text containing
[chrome 110.0.5481.177 mac os x #0-0]
[chrome 110.0.5481.177 mac os x #0-0] - Expected  - 1
[chrome 110.0.5481.177 mac os x #0-0] + Received  + 2
[chrome 110.0.5481.177 mac os x #0-0]
[chrome 110.0.5481.177 mac os x #0-0] - Let assertion fail
[chrome 110.0.5481.177 mac os x #0-0] + You logged into a secure area!
[chrome 110.0.5481.177 mac os x #0-0] + ×
[chrome 110.0.5481.177 mac os x #0-0]     at Context.<anonymous> (file:///private/tmp/9877/test/specs/example.e2e.js:10:45)
[chrome 110.0.5481.177 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Please provide a reproducible example with a simple setup, thanks!

**Comment by matheusneumannsuiteit** [comment]
Could I attach here a .zip with a small project to be run to reproduce the error?

> > Create a project in Javascript with webdriver.io and when a test fails, if you look for the line of the error webdriver.io points you to a wrong line.
> 
> This doesn't reproduce the issue, when creating a failing test like this: ![Screenshot 2023-03-02 at 09 10 34](https://user-images.githubusercontent.com/731337/222501727-3bf7d941-f1fe-4a61-8b29-ebb39c467fc6.png)
> 
> I get the correct line:
> 
> ```
> [chrome 110.0.5481.177 mac os x #0-0] Error: Expect $(`#flash`) to have text containing
> [chrome 110.0.5481.177 mac os x #0-0]
> [chrome 110.0.5481.177 mac os x #0-0] - Expected  - 1
> [chrome 110.0.5481.177 mac os x #0-0] + Received  + 2
> [chrome 110.0.5481.177 mac os x #0-0]
> [chrome 110.0.5481.177 mac os x #0-0] - Let assertion fail
> [chrome 110.0.5481.177 mac os x #0-0] + You logged into a secure area!
> [chrome 110.0.5481.177 mac os x #0-0] + ×
> [chrome 110.0.5481.177 mac os x #0-0]     at Context.<anonymous> (file:///private/tmp/9877/test/specs/example.e2e.js:10:45)
> [chrome 110.0.5481.177 mac os x #0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> Please provide a reproducible example with a simple setup, thanks!

**Comment by christian-bromann** [comment]
> Could I attach here a .zip with a small project to be run to reproduce the error?

Just create a Github repository for us to clone.

**Comment by matheusneumannsuiteit** [comment]
> > Could I attach here a .zip with a small project to be run to reproduce the error?
> 
> Just create a Github repository for us to clone.

Alright, thank you. I'll create a project on GitHub so you can clone it and try to reproduce the issue.

**Comment by matheusneumannsuiteit** [comment]
Hi, here is the link of the project on github to reproduce the issue: https://github.com/matheusneumanndev/project_to_reproduce_error

![Captura de Tela 2023-03-09 às 13 48 57](https://user-images.githubusercontent.com/112020287/224095242-c9c31039-3f5d-46c9-b46c-c02d6c87e7c7.png)

**Comment by matheusneumannsuiteit** [comment]
I only got this error for mobile testing, I never used it for a browser

**Comment by christian-bromann** [comment]
Gotcha, well please help us to investigate this. I personally don't have the time to set up a mobile environment to investigate this given my current priorities. It would be much easier for me if I can reproduce this with a simple browser test. I am happy to keep this open in case someone likes to help us identify the issue here. I case there will be no activity I tend to close these issues. While this is surely not something you like to hear, the reality unfortunately requires us to proceed this way, given that the project has a lot of other work that need attention and I unfortunately don't have the time to spend half a day investigate something that is not proven to be an actual bug within WebdriverIO. Hope that makes sense.

**Comment by christian-bromann** [comment]
I will close this due to inactivity. If someone can reproduce this, I am happy to re-open.

**Comment by lukerj1988** [comment]
Hi, 

I'm currently having this issue and have reproduced it in the wdio default test files following a completely fresh `npm init wdio`:

![image](https://github.com/webdriverio/webdriverio/assets/149380723/f44360db-23c3-4ab7-ac63-0b85de822a5c)

The log is outputting the fail on line 7, whereas it's on line 10.

```
[chrome 122.0.6261.128 windows #0-0] Running: chrome (v122.0.6261.128) on windows
[chrome 122.0.6261.128 windows #0-0] Session ID: f2a574cb038f6b33d8db5031b3c1d2dc
[chrome 122.0.6261.128 windows #0-0]
[chrome 122.0.6261.128 windows #0-0] » \test\specs\test.e2e.ts
[chrome 122.0.6261.128 windows #0-0] My Login application
[chrome 122.0.6261.128 windows #0-0]    ✖ should login with valid credentials
[chrome 122.0.6261.128 windows #0-0]
[chrome 122.0.6261.128 windows #0-0] 1 failing (617ms)
[chrome 122.0.6261.128 windows #0-0]
[chrome 122.0.6261.128 windows #0-0] 1) My Login application should login with valid credentials
[chrome 122.0.6261.128 windows #0-0] expect(received).toBe(expected) // Object.is equality

Expected: "fail"
Received: "pass"
[chrome 122.0.6261.128 windows #0-0] Error: expect(received).toBe(expected) // Object.is equality
[chrome 122.0.6261.128 windows #0-0]
[chrome 122.0.6261.128 windows #0-0] Expected: "fail"
[chrome 122.0.6261.128 windows #0-0] Received: "pass"
[chrome 122.0.6261.128 windows #0-0]     at Context.<anonymous> (file:///C:/Users/cs1lrj/Documents/automation/test/test/specs/test.e2e.ts:7:30)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:06
```

WebdriverIO Version: 8.33.1
NodeJS Version: 20.11.1

**Comment by christian-bromann** [comment]
@lukerj1988 can you do me a favor and raise a new issue with a reproducible example? Thanks!

**Comment by PatsevPavel** [comment]
I am having the same issue for a new project on WebdriverIO 8 and typescript
