### ISSUE TITLE
[🐛 Bug]: browser.getLogs is not a function

### ISSUE THREAD

**Issue by ShootingKing-AM** [webdriverio/webdriverio#9886]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.13.2

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        acceptInsecureCerts: true,
        // 'goog:chromeOptions': {
        //     args: [
        //         '--no-sandbox',
        //         '--disable-infobars',
        //         '--headless',
        //         '--disable-gpu',
        //         '--window-size=1440,735'
        //     ],
        // }
        'goog:chromeOptions': {
            // binary: '/squashfs-root/obsidian', // Path to your Electron binary
            args: [
                '--no-sandbox',
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--disable-software-rasterizer',
                '--window-size=1440,735'
            ],
            debuggerAddress: '127.0.0.1:8888'
            // args: [/* cli arguments */] // Optional, perhaps 'app=' + /path/to/your/app/
        }
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
```

### What happened?

```sh
$ npm run wdio

> obsidian-sample-plugin@0.9.7 wdio
> wdio run ./wdio.conf.ts


Execution of 1 workers started at 2023-03-05T13:25:44.841Z

2023-03-05T13:25:44.903Z INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)
2023-03-05T13:25:44.904Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-03-05T13:25:44.906Z INFO chromedriver: Start Chromedriver (D:\Users\Documents\GitHub\Obsidian_to_Anki\node_modules\chromedriver\lib\chromedriver\chromedriver.exe) with args --silent --port=9515 --url-base=/
2023-03-05T13:25:45.029Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-03-05T13:25:45.031Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] 2023-03-05T13:25:46.148Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///D:/Users/Documents/GitHub/Obsidian_to_Anki/tests/specs/example.e2e.ts
[0-0] 2023-03-05T13:25:46.481Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-0] 2023-03-05T13:25:51.682Z INFO devtools: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-03-05T13:25:51.701Z INFO devtools: COMMAND executeScript("return (() => function () { return [...document.querySelectorAll('button')].find(btn => btn.textContent.includes('Trust')).click(); }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.704Z INFO devtools: RESULT {}
[0-0] 2023-03-05T13:25:51.707Z INFO devtools: COMMAND executeScript("return (() => function () { return dispatchEvent(new KeyboardEvent('keydown', { 'key': 'Escape' })); }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.710Z INFO devtools: RESULT {}
[0-0] 2023-03-05T13:25:51.712Z INFO devtools: COMMAND executeScript("return (() => function () { return console.logs; }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.716Z INFO devtools: RESULT {}
[0-0] 2023-03-05T13:25:51.718Z INFO devtools: COMMAND executeScript("return (() => function () { return console.warns; }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.721Z INFO devtools: RESULT {}
[0-0] 2023-03-05T13:25:51.723Z INFO devtools: COMMAND executeScript("return (() => function () { return console.debugs; }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.727Z INFO devtools: RESULT {}
[0-0] 2023-03-05T13:25:51.729Z INFO devtools: COMMAND executeScript("return (() => function () { return console.errors; }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.732Z INFO devtools: RESULT {}
[0-0] {}
[0-0] {}
[0-0] {}
[0-0] {}
[0-0] 2023-03-05T13:25:56.748Z INFO devtools: COMMAND executeScript("return (() => function () { console.log('clicked !'); return $('div[aria-label="Obsidian_to_Anki - Scan Vault"]').click(); }).apply(null, arguments)", 
<object>)
[0-0] 2023-03-05T13:25:56.752Z INFO devtools: RESULT {}
[0-0] TypeError in "My Login application.should login with valid credentials"
TypeError: browser.getLogs is not a function
    at Context.<anonymous> (D:\Users\Documents\GitHub\Obsidian_to_Anki\tests\specs\example.e2e.ts:69:35)      
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] 2023-03-05T13:25:56.759Z INFO devtools: COMMAND deleteSession()
[0-0] 2023-03-05T13:25:56.848Z INFO devtools: RESULT null
[0-0] FAILED in chrome - file:///D:/Users/Documents/GitHub/Obsidian_to_Anki/tests/specs/example.e2e.ts
```

### What is your expected behavior?

I want to get the browser console logs, esp. errors.

### How to reproduce the bug.

```ts
import type { Options } from '@wdio/types'

// import { join } from 'path';
// import fs from 'fs';
// import { getDirname } from 'cross-dirname';

// const dirname = getDirname();
// const packageJson = JSON.parse(fs.readFileSync('./package.json').toString());
// const {
//   build: { productName },
// } = packageJson;

const path = require('path');

export const config/* : Options.Testrunner */ = {
    //
    // ====================
    // Runner Configuration
    // ====================
    // WebdriverIO supports running e2e tests as well as unit and component tests.
    runner: 'local',
    autoCompileOpts: {
        tsNodeOpts: {
            project: './tests/tsconfig.json'
        }
    },
    
    
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // of the configuration file being run.
    //
    // The specs are defined as an array of spec files (optionally using wildcards
    // that will be expanded). The test for each spec file will be run in a separate
    // worker process. In order to have a group of spec files run in the same worker
    // process simply enclose them in an array within the specs array.
    //
    // If you are calling `wdio` from an NPM script (see https://docs.npmjs.com/cli/run-script),
    // then the current working directory is where your `package.json` resides, so `wdio`
    // will be called from there.
    //
    specs: [
        './tests/specs/**/*.ts'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://saucelabs.com/platform/platform-configurator
    //
    capabilities: [{
    
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        acceptInsecureCerts: true,
        // 'goog:chromeOptions': {
        //     args: [
        //         '--no-sandbox',
        //         '--disable-infobars',
        //         '--headless',
        //         '--disable-gpu',
        //         '--window-size=1440,735'
        //     ],
        // }
        'goog:chromeOptions': {
            // binary: '/squashfs-root/obsidian', // Path to your Electron binary
            args: [
                '--no-sandbox',
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--disable-software-rasterizer',
                '--window-size=1440,735'
            ],
            debuggerAddress: '127.0.0.1:8888'
            // args: [/* cli arguments */] // Optional, perhaps 'app=' + /path/to/your/app/
        }
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'info',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
    //     webdriver: 'info',
    //     '@wdio/appium-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost', //:8080',    
    // path: '/wd/hub', // Required to work with wdio v6
    // port: 9515,
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if browser driver or grid doesn't send response
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    automationProtocol: 'devtools',
    services: [ ['chromedriver', {
        logFileName: 'wdio-chromedriver.log', // default
        outputDir: 'logs', // overwrites the config.outputDir
        args: ['--silent']
    }] /* , 'docker' */ ],

    // dockerLogs: 'logs',
    // dockerOptions: {        
    //     // image: 'sytone/obsidian-remote:latest',
    //     image: 'debian-anki',
    //     healthCheck: 'http://localhost:8080',
    //     options: {
    //         p: ['8080:8080', '8888:8888'],
    //         // shmSize: '2g',
    //         d: true,
    //         // docker run -e LANG=C.UTF-8 -e DISPLAY=$DISPLAY -e LC_ALL=C.UTF-8 -it -v D:\\\\Users\\Documents\\GitHub\\Obsidian_to_Anki\\tests\\test_vault:/vaults -v D:\\\\Users\\Documents\\GitHub\\Obsidian_to_Anki\\tests\\test_config:/config -p 8080:8080 debian-anki
    //         e: ['LANG=C.UTF-8', 'DISPLAY=$DISPLAY', 'LC_ALL=C.UTF-8'], 
    //         v: [
    //             `${ path.join(__dirname, '/tests/test_vault') }:/vaults`,
    //             `${ path.join(__dirname, '/tests/test_config') }:/config`
    //         ]
    //     }        
    // },
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Delay in seconds between the spec file retry attempts
    // specFileRetriesDelay: 0,
    //
    // Whether or not retried specfiles should be retried immediately or deferred to the end of the queue
    // specFileRetriesDeferred: false,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter
    reporters: ['junit'],


    
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 600000
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed before a worker process is spawned and can be used to initialise specific service
     * for that worker as well as modify runtime environments in an async fashion.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {[type]} caps     object containing capabilities for session that will be spawn in the worker
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {[type]} args     object that will be merged with the main configuration once worker is initialized
     * @param  {[type]} execArgv list of string arguments passed to the worker process
     */
    // onWorkerStart: function (cid, caps, specs, args, execArgv) {
    // },
    /**
     * Gets executed just after a worker process has exited.
     * @param  {String} cid      capability id (e.g 0-0)
     * @param  {Number} exitCode 0 - success, 1 - fail
     * @param  {[type]} specs    specs to be run in the worker process
     * @param  {Number} retries  number of retries used
     */
    // onWorkerEnd: function (cid, exitCode, specs, retries) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     * @param {String} cid worker id (e.g. 0-0)
     */
    // beforeSession: function (config, capabilities, specs, cid) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs        List of spec file paths that are to be run
     * @param {Object}         browser      instance of created browser/device session
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) starts.
     */
    // beforeTest: function (test, context) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function (test, context) {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function (test, context, { error, result, duration, passed, retries }) {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine only)
     * @param {Object}  test             test object
     * @param {Object}  context          scope object the test was executed with
     * @param {Error}   result.error     error object in case the test fails, otherwise `undefined`
     * @param {Any}     result.result    return object of test function
     * @param {Number}  result.duration  duration of test
     * @param {Boolean} result.passed    true if test has passed, otherwise false
     * @param {Object}  result.retries   informations to spec related retries, e.g. `{ attempts: 0, limit: 0 }`
     */
    // afterTest: function(test, context, { error, result, duration, passed, retries }) {
    // },


    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    // onReload: function(oldSessionId, newSessionId) {
    // }
}
```

### Relevant log output

```typescript
$ npm run wdio

> obsidian-sample-plugin@0.9.7 wdio
> wdio run ./wdio.conf.ts


Execution of 1 workers started at 2023-03-05T13:25:44.841Z

2023-03-05T13:25:44.903Z INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)
2023-03-05T13:25:44.904Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-03-05T13:25:44.906Z INFO chromedriver: Start Chromedriver (D:\Users\Documents\GitHub\Obsidian_to_Anki\node_modules\chromedriver\lib\chromedriver\chromedriver.exe) with args --silent --port=9515 --url-base=/
2023-03-05T13:25:45.029Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-03-05T13:25:45.031Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.ts
[0-0] 2023-03-05T13:25:46.148Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in chrome - file:///D:/Users/Documents/GitHub/Obsidian_to_Anki/tests/specs/example.e2e.ts
[0-0] 2023-03-05T13:25:46.481Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-0] 2023-03-05T13:25:51.682Z INFO devtools: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-03-05T13:25:51.701Z INFO devtools: COMMAND executeScript("return (() => function () { return [...document.querySelectorAll('button')].find(btn => btn.textContent.includes('Trust')).click(); }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.704Z INFO devtools: RESULT {}
[0-0] 2023-03-05T13:25:51.707Z INFO devtools: COMMAND executeScript("return (() => function () { return dispatchEvent(new KeyboardEvent('keydown', { 'key': 'Escape' })); }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.710Z INFO devtools: RESULT {}
[0-0] 2023-03-05T13:25:51.712Z INFO devtools: COMMAND executeScript("return (() => function () { return console.logs; }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.716Z INFO devtools: RESULT {}
[0-0] 2023-03-05T13:25:51.718Z INFO devtools: COMMAND executeScript("return (() => function () { return console.warns; }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.721Z INFO devtools: RESULT {}
[0-0] 2023-03-05T13:25:51.723Z INFO devtools: COMMAND executeScript("return (() => function () { return console.debugs; }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.727Z INFO devtools: RESULT {}
[0-0] 2023-03-05T13:25:51.729Z INFO devtools: COMMAND executeScript("return (() => function () { return console.errors; }).apply(null, arguments)", <object>)
[0-0] 2023-03-05T13:25:51.732Z INFO devtools: RESULT {}
[0-0] {}
[0-0] {}
[0-0] {}
[0-0] {}
[0-0] 2023-03-05T13:25:56.748Z INFO devtools: COMMAND executeScript("return (() => function () { console.log('clicked !'); return $('div[aria-label="Obsidian_to_Anki - Scan Vault"]').click(); }).apply(null, arguments)", 
<object>)
[0-0] 2023-03-05T13:25:56.752Z INFO devtools: RESULT {}
[0-0] TypeError in "My Login application.should login with valid credentials"
TypeError: browser.getLogs is not a function
    at Context.<anonymous> (D:\Users\Documents\GitHub\Obsidian_to_Anki\tests\specs\example.e2e.ts:69:35)      
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0] 2023-03-05T13:25:56.759Z INFO devtools: COMMAND deleteSession()
[0-0] 2023-03-05T13:25:56.848Z INFO devtools: RESULT null
[0-0] FAILED in chrome - file:///D:/Users/Documents/GitHub/Obsidian_to_Anki/tests/specs/example.e2e.ts
```

```ts
console.log(await browser.getLogs('browser'))
```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by ShootingKing-AM** [comment]
#4275, #4032

**Comment by christian-bromann** [comment]
`getLogs` is only supported for Chrome and in the deprecated JSONWireProtocol. According to your logs you seem to start Chromedriver but still use the Devtools protocol because you have `debuggerAddress` defined. The devtools package also doesn't have `getLogs` implemented. If you are interested in logs, use `getPuppeteer` and use the Puppeteer API to receive them.

**Comment by ShootingKing-AM** [comment]
`debuggerAddress` refers to a Chrome(technically Chromium, technically Electron app) (had to hook it runtime since wdio-Electron service needs some integration and stuff to do in Electron app). 

1. The documentation is confusing it said Chromium protocol has `getLogs()` but does not mention about webdriver protocol having `getLogs()` 
2. has no mention of how to switch to 'Chromium' protocol (https://webdriver.io/docs/api/chromium). 
3. This Chromium protocol has again no mention in Automation Protocol docs - https://webdriver.io/docs/automationProtocols.

Hence I inferred with my *supreme* knowledge that Chromium is referring to Chrome which is referring to devTools Protocol. But now am magically able to `getLogs()` from webdriver (or the default protocol itself[^1]) 

###### or .. am dumb ?

[^1]: https://github.com/ShootingKing-AM/Obsidian_to_Anki/blob/master/wdio.conf.ts

**Comment by christian-bromann** [comment]
> 1. The documentation is confusing it said Chromium protocol has `getLogs()` but does not mention about webdriver protocol having `getLogs()`

If you run tests with Chromedriver you should have the command, however WebdriverIO judges based on the session response whether you are using this driver / browser and adds the command if you do so. Since you say you use Electron , chances are that Electron session responses are not seen as Chromium session and therefore the commands are not applied, mind raising a new issue, saying that Electron sessions are not recognised as Chromium session and provide the log for `browser.capabilities` so we can adjust the logic there?

> 2\. has no mention of how to switch to 'Chromium' protocol (https://webdriver.io/docs/api/chromium).

You can't switch, WebdriverIO decides which protocol commands it adds based on the session response.

> 3\. This Chromium protocol has again no mention in Automation Protocol docs - https://webdriver.io/docs/automationProtocols.

Please make suggestions how we can improve this document.

**Comment by ShootingKing-AM** [comment]
> > 1. The documentation is confusing it said Chromium protocol has `getLogs()` but does not mention about webdriver protocol having `getLogs()`
> 
> If you run tests with Chromedriver you should have the command, however WebdriverIO judges based on the session response whether you are using this driver / browser and adds the command if you do so. Since you say you use Electron , chances are that Electron session responses are not seen as Chromium session and therefore the commands are not applied, mind raising a new issue, saying that Electron sessions are not recognised as Chromium session and provide the log for `browser.capabilities` so we can adjust the logic there?

The logs aforementioned are all the logs I can see, if you can direct me from where can I get the session response from driver, I would be happy to open a new issue.

Just to be clear `automationProtocol: webdriver`-> Has `getLogs()`, If i switch to `automationProtocol: devTools` -> error `getLogs ()` :(

> 
> > 2. has no mention of how to switch to 'Chromium' protocol (https://webdriver.io/docs/api/chromium).
> 
> You can't switch, WebdriverIO decides which protocol commands it adds based on the session response.
> 
Yup, I understood after bruteforcing the api.

**Comment by christian-bromann** [comment]
> Just to be clear `automationProtocol: webdriver`-> Has `getLogs()`

Nope. Only when you use Chrome because Chromedriver has the command implemented

**Comment by ShootingKing-AM** [comment]
Yes I use Chromedriver in BOTH cases

**Comment by christian-bromann** [comment]
As commented above the bug is WebdriverIO doesn't recognise Electron tests as Chromium session. Mind raising another issue with the capabilities?
