### ISSUE TITLE
[🐛 Bug]: Cannot read properties of undefined (reading 'baseUrl') when updating CLI from version 7 to 8

### ISSUE THREAD

**Issue by nizzel55** [webdriverio/webdriverio#9919]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.5.1

### Node.js Version

18.7.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome',
    baseUrl: 'https://ourBaseUrl.com',
}
```

### What happened?

Updating CLI version from 7.27 to 8 + version EG 8.5.7 will result in the following error when trying to run a test:
`Error:  Cannot read properties of undefined (reading 'baseUrl')`

package.json
  {
  "dependencies": {
    "@wdio/allure-reporter": "7.26.0",
    "@wdio/cli": "7.27.0",
    "@wdio/jasmine-framework": "7.26.0",
    "@wdio/local-runner": "7.27.0",
    "@wdio/spec-reporter": "7.26.0",
    "allure-commandline": "^2.21.0",
    "axios": "^1.3.4",
    "eslint": "^8.35.0",
    "eslint-config-google": "^0.14.0",
    "pre-commit": "^1.2.2",
    "typescript": "^4.9.5",
    "wdio-docker-service": "3.2.1",
    "wdio-video-reporter": "^3.5.0",
    "webdriverio": "^8.5.1"
  },
  "devDependencies": {
    "chromedriver": "^110.0.0",
    "wdio-chromedriver-service": "8.1.1"
  },
  "scripts": {
    "test": "npx wdio run ./wdio.conf.js",
  },

We run our tests with:

$ yarn test 
If we would run with a modified url we use:
Locally:
`$ yarn test --baseUrl=custom_base_url`
In Azure:
`$ yarn test-azure --baseUrl=$(target) --suite staging `

We have tried to remove all @wdio dependencies and go through the setup steps. However it ends up with the same problem all the time.

### What is your expected behavior?

Updating from wdio version 7 to 8 should work and baseUrl in the config file should not be considered as undefined.

### How to reproduce the bug.

Upgrade from wdio/cli version 7 to 8 

### Relevant log output

```typescript
$ yarn test --baseUrl=https://ourBaseUrl.com
yarn run v1.22.4
$ npx wdio run ./wdio.conf.js --baseUrl=https://ourBaseUrl.com

Execution of 38 workers started at 2023-03-09T08:12:11.457Z

[0-0] RUNNING in chrome - file:///C:/code/WebdriverIO-e2e/test/specs/ourTest.e2e.js

DevTools listening on ws://127.0.0.1:56118/devtools/browser/6ccf1ac9-acd3-4dd7-83f2-59e7caac8859
[0-0]  Error:  Cannot read properties of undefined (reading 'baseUrl')
[0-0] FAILED in chrome - file:///C:/code/WebdriverIO-e2e/test/specs/ourTest.e2e.js
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide the whole error stack?

**Comment by nizzel55** [comment]
Here is everything from the terminal.
After trying to install the dependencies.

```
nils.johansson@SE-MALMO-NB01 MINGW64 /c/code/WebdriverIO-e2e (main)
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/darwin-arm64@4.1.5: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/darwin-arm64@4.1.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/darwin-arm64@4.1.5: The CPU architecture "x64" is incompatible with this module.
info @ffmpeg-installer/darwin-x64@4.1.0: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/darwin-x64@4.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/linux-arm@4.1.3: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/linux-arm@4.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/linux-arm@4.1.3: The CPU architecture "x64" is incompatible with this module.
info @ffmpeg-installer/linux-arm64@4.1.4: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/linux-arm64@4.1.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/linux-arm64@4.1.4: The CPU architecture "x64" is incompatible with this module.
info @ffmpeg-installer/linux-ia32@4.1.0: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/linux-ia32@4.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/linux-ia32@4.1.0: The CPU architecture "x64" is incompatible with this module.
info @ffmpeg-installer/linux-x64@4.1.0: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/linux-x64@4.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/win32-ia32@4.1.0: The CPU architecture "x64" is incompatible with this module.
info "@ffmpeg-installer/win32-ia32@4.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "wdio-video-reporter > @wdio/allure-reporter@7.16.6" has incorrect peer dependency "@wdio/cli@^7.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 17.70s.

nils.johansson@SE-MALMO-NB01 MINGW64 /c/code/WebdriverIO-e2e (main)
$ yarn test --baseUrl=https://bimobject-staging.ad.bimobject.com/ --suite playground
yarn run v1.22.4
$ npx wdio run ./wdio.conf.js --baseUrl=https://ourBaseUrl/ --suite playground

Execution of 1 workers started at 2023-03-10T07:40:21.552Z

[0-0] RUNNING in chrome - file:///C:/code/WebdriverIO-e2e/test/specs/our_test.e2e.js

DevTools listening on ws://127.0.0.1:56350/devtools/browser/a4e516c0-1768-47bd-8f4e-3476b02f3802
[0-0]  Error:  Cannot read properties of undefined (reading 'baseUrl')
[0-0] FAILED in chrome - file:///C:/code/WebdriverIO-e2e/test/specs/our_test..e2e.js

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:06

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```



Our dependencies before updating.

```
{
  "dependencies": {
    "@wdio/allure-reporter": "7.26.0",
    "@wdio/cli": "7.27.0",
    "@wdio/jasmine-framework": "7.26.0",
    "@wdio/local-runner": "7.27.0",
    "@wdio/spec-reporter": "7.26.0",
    "allure-commandline": "^2.21.0",
    "axios": "^1.3.4",
    "eslint": "^8.35.0",
    "eslint-config-google": "^0.14.0",
    "pre-commit": "^1.2.2",
    "typescript": "^4.9.5",
    "wdio-docker-service": "3.2.1",
    "wdio-video-reporter": "^3.5.0",
    "webdriverio": "^8.5.1"
  },
  "devDependencies": {
    "chromedriver": "^110.0.0",
    "wdio-chromedriver-service": "8.1.1"
  },
```

**Comment by christian-bromann** [comment]
> Here is everything from the terminal.

Can you set `logLevel` to `trace` and check if there is an `outputDir` defined in the config that might cause the runner to push logs into a file? If that is the case please share the wdio logs of these files.

**Comment by nizzel55** [comment]
I have set the logLevel to trace and we have no outputDir or logLevels defined in the config file. 
There is nothing more in the terminal than what I have already written above.

The test fails immediately before the chrome instance starts.

**Comment by christian-bromann** [comment]
@nizzel55 can you provide a minimal reproducible example then?

**Comment by nizzel55** [comment]
Here is our config file. 

```
const path = require('path');

// Helpers
const fileHelper = require('./test/helpers/helper.js'); // eslint-disable-line

// Globals
global.downloadDirectory = path.join(__dirname, 'downloads');
global.dataDirectory = path.join(__dirname, 'data');
global.globalTimeoutTime = 30 * 1000;
global.globalTimeoutTimeExtended = 60 * 1000;

exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    runner: 'local',
    //
    // =====================
    // Server Configurations
    // =====================
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub',
    //
    // ==================
    // Specify Test Files
    // ==================
    specs: [
        './test/specs/**/*.js',
    ],
    suites: {
        production: [
            './test/specs/test.e2e.js',
        ],
        staging: [
            './test/specs/test.e2e.js',
        ],
        playground: [
            './test/specs/test.e2e.js',
        ],
    },
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    maxInstances: 10,
    capabilities: [{
        maxInstances: 1, // eslint-disable-line
        browserName: 'chrome', // eslint-disable-line
        acceptInsecureCerts: true, // eslint-disable-line
        'goog:chromeOptions': {
            'useAutomationExtension': false,
            'excludeSwitches': ['enable-automation'],
            'args': [
                '--incognito',
            ],
            'prefs': {
                'credentials_enable_service': false,
                'download': {
                    'directory_upgrade': true,
                    'prompt_for_download': false,
                    'default_directory': downloadDirectory,
                },
                'profile': {
                    'password_manager_enabled': false,
                },
            },
        },
        'goog:loggingPrefs': {
            browser: 'ALL',
        },
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    logLevel: 'debug',
    bail: 0,
    baseUrl: 'https://ourBaseUrl.com',
    user: '',
    password: '',
    waitforTimeout: 10000,
    connectionRetryTimeout: 120000,
    connectionRetryCount: 3,
    services: ['chromedriver'],
    framework: 'jasmine',
    specFileRetries: 0,
    outputDir: './report/results',
    reporters: [
        'spec',
        ['allure', {
            outputDir: './report/allure-results',
            disableWebdriverStepsReporting: true,
            disableWebdriverScreenshotsReporting: false,
            addConsoleLogs: true,
        }],
    ],

    //
    // Options to be passed to Jasmine.
    jasmineOpts: {
        defaultTimeoutInterval: 180000,
        expectationResultHandler: function(passed, assertion) {
            // do something
        },
        stopOnSpecFailure: true,
    },

    //
    // =====
    // Hooks
    // =====
    onPrepare: async function(config, capabilities) {
        await fileHelper.createDirectory(downloadDirectory);
        // await fileHelper.deleteDirectory(path.join(__dirname, './report/results'));
        await fileHelper.deleteDirectory(path.join(__dirname, './report/allure-results'));
    },
    before: function(capabilities, specs) {
        // Set window size
        const width = 1920;
        const height = 1080;
        return browser.setWindowSize(width, height);
    },
    afterTest: async function(test, context, {error, result, duration, passed, retries}) {
        // if (error) {
        await browser.takeScreenshot();
        // }

        const currentUrl = await browser.getUrl();
        console.log('Current url: \n' + currentUrl);

        const browserLogs = await browser.getLogs('browser');
        const browserLogsText = JSON.stringify(Object.values(browserLogs));
        if (browserLogsText != '[]') {
            console.log('Browser logs: \n' + browserLogsText);
        }

        const cookieSERVERID = await browser.getCookies(['SERVERID']);
        const cookieSERVERIDText = JSON.stringify(Object.values(cookieSERVERID));
        if (cookieSERVERIDText != '[]') {
            console.log('Cookie SERVERID: \n' + cookieSERVERIDText);
        }
    },
    onComplete: async function(exitCode, config, capabilities, results) {
        await fileHelper.deleteDirectory(downloadDirectory);
    },
};

```

**Comment by nizzel55** [comment]
Here is our package.json file

```
{
  "dependencies": {
    "@wdio/allure-reporter": "7.26.0",
    "@wdio/cli": "7.27.0",
    "@wdio/jasmine-framework": "7.26.0",
    "@wdio/local-runner": "7.27.0",
    "@wdio/spec-reporter": "7.26.0",
    "allure-commandline": "^2.21.0",
    "axios": "^1.3.4",
    "eslint": "^8.35.0",
    "eslint-config-google": "^0.14.0",
    "pre-commit": "^1.2.2",
    "typescript": "^4.9.5",
    "wdio-docker-service": "3.2.1",
    "wdio-video-reporter": "^3.5.0",
    "webdriverio": "^8.5.1"
  },
  "devDependencies": {
    "chromedriver": "^110.0.0",
    "wdio-chromedriver-service": "8.1.1"
  },
  "scripts": {
    "test": "npx wdio run ./wdio.conf.js",
    "test-grid": "npx wdio run ./wdio.docker.conf.js",
    "test-grid-local": "npx wdio run ./wdio.docker.local.conf.js",
    "eslint": "./node_modules/.bin/eslint . --ext .js",
    "generate-report": "allure generate ./report/allure-results --clean --report-dir ./report/allure-report"
  },
  "pre-commit": [
    "eslint"
  ],
}

```

**Comment by nizzel55** [comment]
package.json file

```
{
  "dependencies": {
    "@wdio/cli": "8.6.5",
    "@wdio/jasmine-framework": "8.6.3",
    "@wdio/local-runner": "8.6.3",
    "@wdio/spec-reporter": "8.4.0",
    "allure-commandline": "^2.21.0",
    "axios": "^1.3.4",
    "eslint": "^8.35.0",
    "eslint-config-google": "^0.14.0",
    "pre-commit": "^1.2.2",
    "typescript": "^4.9.5",
    "wdio-docker-service": "3.2.1",
    "wdio-video-reporter": "^3.5.0",
    "webdriverio": "^8.6.3"
  },
  "devDependencies": {
    "chromedriver": "^110.0.0",
    "wdio-chromedriver-service": "8.1.1"
  },
  "scripts": {
    "test": "npx wdio run ./wdio.conf.js",
    "test-grid": "npx wdio run ./wdio.docker.conf.js",
    "test-grid-local": "npx wdio run ./wdio.docker.local.conf.js",
    "eslint": "./node_modules/.bin/eslint . --ext .js",
    "generate-report": "allure generate ./report/allure-results --clean --report-dir ./report/allure-report"
  },
  "pre-commit": [
    "eslint"
  ],
  "author": "Nils Johansson",
  "license": "ISC",
  "version": "0.0.0"
}

```


wdio.conf.js file


```
exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    runner: 'local',
    //
    // =====================
    // Server Configurations
    // =====================
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub',
    //
    // ==================
    // Specify Test Files
    // ==================
    specs: [
        './test/specs/**/*.js',
    ],
    suites: {
        test: [
            './test/specs/test.e2e.js', // 2m 38s
        ],
    },
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    maxInstances: 10,
    //
    capabilities: [{
        maxInstances: 1, // eslint-disable-line
        //
        browserName: 'chrome', // eslint-disable-line
        acceptInsecureCerts: true, // eslint-disable-line
        'goog:chromeOptions': {
            'args': [
                '--incognito', // Set chrome incognito mode
            ],
            'prefs': {
            },
        },
        'goog:loggingPrefs': {
            browser: 'ALL',
        },
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    logLevel: 'debug',
    //
    bail: 0,
    //
    baseUrl: 'https://www.saucedemo.com/',
    //
    waitforTimeout: 10000,
    //
    connectionRetryTimeout: 120000,
    //
    // Default request retries count
    connectionRetryCount: 1,
    //
    // Test runner services
    services: ['chromedriver'],
    // Framework you want to run your specs with.
    framework: 'jasmine',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    specFileRetries: 0,
    //
    reporters: [
        'spec',
    ],

    //
    // Options to be passed to Jasmine.
    jasmineOpts: {
        // Jasmine default timeout
        defaultTimeoutInterval: 180000,
        //
        expectationResultHandler: function(passed, assertion) {
            // do something
        },
        stopOnSpecFailure: true, // Stops test suite (describe) execution on first spec (it) failure (other suites continue running)
    },

    //
    // =====
    // Hooks
    // =====
    before: function(capabilities, specs) {
        // Set window size
        const width = 1920;
        const height = 1080;
        return browser.setWindowSize(width, height);
    },
};

```

spec file:
test.e2e.js

const baseUrl = browser.config.baseUrl;

describe('Test baseUrl', function() {
    it('Navigate to saucedemo webpage', async function() {
        await browser.url(baseUrl);
        const elem = await $('#login-button');
        await elem.waitForDisplayed({timeout: 10000});
    });
});

**Comment by nizzel55** [comment]
Logs: 


```
$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/darwin-arm64@4.1.5: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/darwin-arm64@4.1.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/darwin-arm64@4.1.5: The CPU architecture "x64" is incompatible with this module.
info @ffmpeg-installer/darwin-x64@4.1.0: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/darwin-x64@4.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/linux-arm@4.1.3: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/linux-arm@4.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/linux-arm@4.1.3: The CPU architecture "x64" is incompatible with this module.
info @ffmpeg-installer/linux-arm64@4.1.4: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/linux-arm64@4.1.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/linux-arm64@4.1.4: The CPU architecture "x64" is incompatible with this module.
info @ffmpeg-installer/linux-ia32@4.1.0: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/linux-ia32@4.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/linux-ia32@4.1.0: The CPU architecture "x64" is incompatible with this module.
info @ffmpeg-installer/linux-x64@4.1.0: The platform "win32" is incompatible with this module.
info "@ffmpeg-installer/linux-x64@4.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @ffmpeg-installer/win32-ia32@4.1.0: The CPU architecture "x64" is incompatible with this module.
info "@ffmpeg-installer/win32-ia32@4.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "wdio-video-reporter > @wdio/allure-reporter@7.16.6" has incorrect peer dependency "@wdio/cli@^7.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 16.11s.





$ yarn test --suite test
yarn run v1.22.4
$ npx wdio run ./wdio.conf.js --suite test

Execution of 1 workers started at 2023-03-20T14:55:04.356Z

2023-03-20T14:55:04.404Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
2023-03-20T14:55:04.457Z INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)
2023-03-20T14:55:04.458Z INFO @wdio/cli:launcher: Run onPrepare hook
2023-03-20T14:55:04.461Z INFO chromedriver: Start Chromedriver (C:\code\WebdriverIO-e2e\node_modules\chromedriver\lib\chromedriver\chromedriver.exe) with args --port=9515 --url-base=/
2023-03-20T14:55:04.492Z INFO chromedriver: Starting ChromeDriver 110.0.5481.77 (65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}) on port 9515
2023-03-20T14:55:04.492Z INFO chromedriver: Only local connections are allowed.
2023-03-20T14:55:04.493Z INFO chromedriver: Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
2023-03-20T14:55:04.522Z INFO chromedriver: ChromeDriver was started successfully.
2023-03-20T14:55:04.581Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 123ms
2023-03-20T14:55:04.587Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-03-20T14:55:04.588Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2023-03-20T14:55:04.591Z INFO @wdio/local-runner: Start worker 0-0 with arg: run,./wdio.conf.js,--suite,test
2023-03-20T14:55:04.600Z DEBUG @wdio/local-runner: Send command run to worker with cid "0-0"
[0-0] 2023-03-20T14:55:06.159Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2023-03-20T14:55:06.165Z DEBUG @wdio/runner: init remote session
[0-0] 2023-03-20T14:55:06.178Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
[0-0] 2023-03-20T14:55:06.445Z WARN @wdio/jasmine-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-0] Spec file(s): file:///C:/code/WebdriverIO-e2e/test/specs/google.e2e.js
[0-0]  Error:  TypeError: Cannot read properties of undefined (reading 'baseUrl')
[0-0]     at Object.<anonymous> (C:\code\WebdriverIO-e2e\test\specs\google.e2e.js:1:32)
[0-0]     at Module._compile (node:internal/modules/cjs/loader:1120:14)
[0-0]     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
[0-0]     at Module.load (node:internal/modules/cjs/loader:998:32)
[0-0]     at Module._load (node:internal/modules/cjs/loader:839:12)
[0-0]     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
[0-0]     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
[0-0]     at async Promise.all (index 0)
[0-0]     at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
[0-0]     at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
[0-0] RUNNING in chrome - file:///C:/code/WebdriverIO-e2e/test/specs/google.e2e.js
[0-0] 2023-03-20T14:55:06.446Z DEBUG @wdio/runner: init remote session
[0-0] 2023-03-20T14:55:06.447Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-03-20T14:55:06.825Z INFO webdriver: [POST] http://localhost:9515/session
[0-0] 2023-03-20T14:55:06.825Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       'goog:chromeOptions': [Object],
[0-0]       'goog:loggingPrefs': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     acceptInsecureCerts: true,
[0-0]     'goog:chromeOptions': { args: [Array], prefs: {} },
[0-0]     'goog:loggingPrefs': { browser: 'ALL' }
[0-0]   }
[0-0] }

DevTools listening on ws://127.0.0.1:53777/devtools/browser/a8143cc0-aec1-4df4-a4a0-5ccd44ec780a
2023-03-20T14:55:07.429Z WARN chromedriver: [1679324107.430][WARNING]: This version of ChromeDriver has not been tested with Chrome version 111.
2023-03-20T14:55:07.435Z WARN chromedriver: [1679324107.435][WARNING]: virtual void DevToolsClientImpl::AddListener(DevToolsEventListener *) subscribing a listener to the already connected DevToolsClient. Connection notification will not arrive.
[0-0] 2023-03-20T14:55:07.453Z INFO webdriver: COMMAND setWindowRect(null, null, 1920, 1080)
[0-0] 2023-03-20T14:55:07.454Z INFO webdriver: [POST] http://localhost:9515/session/d1ef53d919e4893128988cb954f1d1a5/window/rect
[0-0] 2023-03-20T14:55:07.454Z INFO webdriver: DATA { x: null, y: null, width: 1920, height: 1080 }
[0-0] 2023-03-20T14:55:07.573Z INFO webdriver: RESULT { height: 1080, width: 1920, x: 10, y: 10 }
[0-0] 2023-03-20T14:55:07.573Z DEBUG @wdio/utils:shim: Finished to run "before" hook in 120ms
[0-0] 2023-03-20T14:55:07.575Z ERROR @wdio/runner: TypeError: Cannot read properties of undefined (reading 'baseUrl')
[0-0]     at Object.<anonymous> (C:\code\WebdriverIO-e2e\test\specs\google.e2e.js:1:32)
[0-0]     at Module._compile (node:internal/modules/cjs/loader:1120:14)
[0-0]     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
[0-0]     at Module.load (node:internal/modules/cjs/loader:998:32)
[0-0]     at Module._load (node:internal/modules/cjs/loader:839:12)
[0-0]     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
[0-0]     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
[0-0]     at async Promise.all (index 0)
[0-0]     at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
[0-0]     at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
[0-0]  Error:  Cannot read properties of undefined (reading 'baseUrl')
[0-0] 2023-03-20T14:55:07.576Z INFO webdriver: COMMAND deleteSession()
[0-0] 2023-03-20T14:55:07.576Z INFO webdriver: [DELETE] http://localhost:9515/session/d1ef53d919e4893128988cb954f1d1a5
[0-0] 2023-03-20T14:55:07.601Z INFO webdriver: RESULT null
2023-03-20T14:55:07.743Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///C:/code/WebdriverIO-e2e/test/specs/google.e2e.js
2023-03-20T14:55:07.746Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-03-20T14:55:07.749Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 1ms
2023-03-20T14:55:07.750Z INFO @wdio/cli:launcher: Run onComplete hook
2023-03-20T14:55:07.759Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:03

2023-03-20T14:55:07.777Z INFO @wdio/local-runner: Shutting down spawned worker
2023-03-20T14:55:08.041Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-03-20T14:55:08.041Z INFO @wdio/local-runner: shutting down
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by BorisOsipov** [comment]
@nizzel55 

We removed the `config` property from the browser object. Use `options` instead.

More details here -https://webdriver.io/blog/2022/12/01/webdriverio-v8-released#miscellaneous

**Comment by BorisOsipov** [comment]
@nizzel55 I don't know. Look at https://github.com/webdriverio/webdriverio/issues/9705
