### ISSUE TITLE
[🐛 Bug]: browser.enablePerformanceAudits is not a function node18 wdio 8.5.7

### ISSUE THREAD

**Issue by ghost** [webdriverio/webdriverio#9922]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
        {
            browserName: "chrome",
            maxInstances: 1,
            "goog:chromeOptions": {
                mobileEmulation: {
                    deviceName: "iPhone X",
                },
                args: ["ignore-certificate-errors", "Start-fullscreen"],
            },
        },
    ],
```

### What happened?

Devtools fail when I run the test:

I simply call it in the before => 
```
describe('test perf', async () => {
    before(async function () {
        browser.enablePerformanceAudits()
    })
```

And Here is the Error:

`browser.enablePerformanceAudits is not a function`

### How to reproduce the bug.

Specs file:

```
describe('test perf', async () => {
    before(async function () {
        await browser.enablePerformanceAudits()
    })

    it('should do something', async function () {
        console.log('test devtools')
    })


    after(() => {
        browser.disablePerformanceAudits()
    })
})

```
run:
`npx wdio run ./wdio.conf.ts`

### Relevant log output

```typescript
[0-0] 2023-03-09T18:02:18.202Z ERROR @wdio/utils:shim: TypeError: Failed to fetch browser webSocket URL from http://localhost:62805/json/version: fetch failed
[0-0]     at Object.fetch (node:internal/deps/undici/undici:11413:11)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0]     at async getWSEndpoint (file:///Users/e.frelon/xxxxxxxx/node_modules/puppeteer-core/src/common/BrowserConnector.ts:143:20)
[0-0]     at async _connectToCDPBrowser (file:///Users/e.frelon/xxxxxxxx/node_modules/puppeteer-core/src/common/BrowserConnector.ts:107:27)
[0-0]     at async Browser.getPuppeteer (file:///Users/e.frelon/xxxxxxxx/node_modules/webdriverio/build/commands/browser/getPuppeteer.js:82:26)
[0-0]     at async Browser.wrapCommandFn (file:///Users/e.frelon/xxxxxxxx/node_modules/@wdio/utils/build/shim.js:72:29)
[0-0]     at async DevToolsService._setupHandler (file:///Users/e.frelon/xxxxxxxx/node_modules/@wdio/devtools-service/build/index.js:174:27)
[0-0]     at async Promise.all (index 0)
[0-0]     at async executeHooksWithArgsShim (file:///Users/e.frelon/xxxxxxxx/node_modules/@wdio/utils/build/shim.js:50:20)
[0-0]     at async Runner.run (file:///Users/e.frelon/xxxxxxxx/node_modules/@wdio/runner/build/index.js:88:9)
[0-0] TypeError in "test perf."before all" hook for "should do something""
TypeError: browser.enablePerformanceAudits is not a function
    at Context.<anonymous> (/Users/e.frelon/xxxxx/specs/xxxxxxxx.ts:35:23)
[0-0] FAILED in chrome - file:///specs/xxxxxxxx.ts

 "spec" Reporter:
------------------------------------------------------------------
[chrome 111.0.5563.64 mac os x #0-0] Running: chrome (v111.0.5563.64) on mac os x
[chrome 111.0.5563.64 mac os x #0-0] Session ID: 1a16c931022dab34fe1bc28ced909a7c
[chrome 111.0.5563.64 mac os x #0-0]
[chrome 111.0.5563.64 mac os x #0-0] » /specs/xxxxxxxx.ts
[chrome 111.0.5563.64 mac os x #0-0] test perf
[chrome 111.0.5563.64 mac os x #0-0]    ✖ "before all" hook for test perf
[chrome 111.0.5563.64 mac os x #0-0]
[chrome 111.0.5563.64 mac os x #0-0] 1 failing (65ms)
[chrome 111.0.5563.64 mac os x #0-0]
[chrome 111.0.5563.64 mac os x #0-0] 1) test perf "before all" hook for test perf
[chrome 111.0.5563.64 mac os x #0-0] browser.enablePerformanceAudits is not a function
[chrome 111.0.5563.64 mac os x #0-0] TypeError: browser.enablePerformanceAudits is not a function
[chrome 111.0.5563.64 mac os x #0-0]     at Context.<anonymous> (/Users/e.frelon/xxxxxxx/specs/xxxxxx.ts:35:23)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
> TypeError: Failed to fetch browser webSocket URL from http://localhost:62805/json/version: fetch failed

It seems that WebdriverIO has issues connecting to DevTools which is why the command is not being attached to the browser (there is an issue already to improve the error message). We are not experiencing this issue in CI so not sure how related this is to WebdriverIO or the environment. Any hints or investigations would be appreciated!

**Comment by ichman** [comment]
it works with **node 14** and **node 16**  but then, there is another one -> 

`ERROR @wdio/utils:shim: LHError: TRACING_ALREADY_STARTED`

I don't know if they are related

**Comment by christian-bromann** [comment]
There are reports on Chrome having issues creating devtools connections: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4361

**Comment by erwinheitzman** [comment]
@ichman is this still an issue?

**Comment by LinaRScAl** [comment]
I have a similar issue when trying to run performance tests in Devtools. TypeError: browser.enablePerformanceAudits is not a function

"webdriverio": "^8.12.1"
v16.16.0 - node version. 
services: ['devtools', 'intercept'],

capabilities: [{

        maxInstances: 1,

        browserName: 'chrome',

        'goog:chromeOptions': {
            args: ['--headless', '--incognito', '--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--window-size=1920,1080'],
               prefs: {
                'directory_upgrade': true,
                'prompt_for_download': false,
            }
        },

        acceptInsecureCerts: true
    }],

**Comment by ichman** [comment]
> @ichman is this still an issue?

Hello, It's been a while since I have re-tested it...i'll let you know

**Comment by owens-ben** [comment]
Still seeing this issue on 8.18.0

**Comment by owens-ben** [comment]
Adding more info

```npm list
web-automated-tests@0.1.0 /Users/ben.owens/git/dev-bundle/web/growth/test
├── @babel/core@7.23.9
├── @babel/node@7.23.9
├── @babel/preset-env@7.23.9
├── @lhci/cli@0.12.0
├── @reportportal/agent-js-webdriverio@5.0.3
├── @reportportal/client-javascript@5.0.14
├── @slack/web-api@6.12.0
├── @wdio/appium-service@8.32.2
├── @wdio/cli@8.32.2 overridden
├── @wdio/devtools-service@8.35.1
├── @wdio/junit-reporter@8.32.2
├── @wdio/local-runner@8.32.2
├── @wdio/mocha-framework@8.32.2
├── @wdio/sauce-service@8.0.2
├── @wdio/spec-reporter@8.32.2
├── appium-chromedriver@5.6.32
├── appium@2.5.1
├── chance@1.1.11
├── date-fns@2.30.0
├── dotenv@16.4.4
├── is-number@7.0.0
├── log4js@6.9.1
├── patch-package@8.0.0
├── proper-lockfile@4.1.2
├── rrad@1.1.0
├── selenium-webdriver@4.18.0
├── ts-node@10.9.2
├── wdio-chromedriver-service@8.1.1
├── wdio-cleanuptotal-service@1.0.7
├── wdio-geckodriver-service@5.0.2
├── wdio-safaridriver-service@2.1.1
├── wdio-selenium-standalone-service@0.0.12
├── wdio-video-reporter@4.0.5
├── webdriverio@8.32.2
└── zipcodes@8.0.0```

From wdio.shared.conf.js

```
const config = {
  project: 'xxx',
  launch: 'regression-' + branch,
  mode: 'DEFAULT',
  debug: false,
  description: baseUrl,
  attributes: [
    { key: 'authorEmail', value: authorEmail },
    { key: 'authorName', value: authorName },
    { key: 'baseUrl', value: baseUrl },
    { key: 'branch', value: branch },
    { key: 'isPR', value: isPR },
  ],
  attachPicturesToLogs: true,
  rerun: true,
  rerunOf: launchUUID,
  skippedIssue: false,
  reportSeleniumCommands: false,
  seleniumCommandsLogLevel: 'debug',
  isLaunchMergeRequired: false,
  restClientConfig: { timeout: 90000 },
  services: ['devtools'],
};
```


```

describe('example', () => {
    it('should capture performance metrics', async () => {
        await browser.url('https://www.google.com/');
        await browser.cdp('Performance', 'enable');
    });
});

```

**Comment by christian-bromann** [comment]
> As far as I can tell devTools does not work at all with any recent versions.

Can you please be more specific? We have performance tests running successfully in our CI system. That said, I haven't looked into this section of the code for long time and would appreciate any contributions here.

**Comment by owens-ben** [comment]
@christian-bromann I provided as much info as I could above. All of the functions have the same error

```TypeError: browser.<anyfunction> is not a function```

I'm happy to provide more info if you can direct me where to look.

**Comment by christian-bromann** [comment]
@owens-ben do you have a minimal reproducible example?

**Comment by owens-ben** [comment]
Is there any devtools support in v9+?

**Comment by christian-bromann** [comment]
@owens-ben yes you can use the [Lighthouse Service](https://webdriver.io/docs/lighthouse-service). I also recommend to check out [this talk](https://www.youtube.com/live/KSKWh4gDGy8?si=SZNh3MQGwNeqYIND&t=6309) from one of our recent meetups.

**Comment by AlfredoMoretta** [comment]
hi all , just tried to use lightouse service in wdio 9.12 but i always have error like:
TypeError: browser.getDiagnostic is not a function or TypeError: browser.getMetrics is not a function.
i followed the documentation. There are any news about this bug?

thanks in advice for the answer

**Comment by christian-bromann** [comment]
@AlfredoMoretta do you have a minimal reproducible example?

**Comment by AlfredoMoretta** [comment]
sorry @christian-bromann i cant send you a reproducible example but the strange thing is that i don't have any problem using :
`const result = await browser.checkPWA()` for example :

`async lighthousePerf() {
        await browser.enablePerformanceAudits()
         const result = await browser.checkPWA()
        console.log(result)
        await browser.getMetrics()
       await browser.disablePerformanceAudits()`

for those line of code the output is :

` ✓       Given home page

[0-0] {

[0-0]   passed: false,
[0-0]   details: {
[0-0]     isInstallable: {

[0-0]       score: 0,

[0-0]       warnings: [],
[0-0]       numericValue: 2,
[0-0]       numericUnit: 'element',
[0-0]       displayValue: [Object],
[0-0]       details: [Object]
[0-0]     },
[0-0]     serviceWorker: { score: 0 },
[0-0]     splashScreen: {
[0-0]       score: 0,
[0-0]       explanation: 'Failures: No manifest was fetched.',
[0-0]       details: [Object]
[0-0]     },
[0-0]     themedOmnibox: {
[0-0]       score: 0,
[0-0]       explanation: 'Failures: No manifest was fetched,\n' +
[0-0]         'No `<meta name="theme-color">` tag found.',
[0-0]       details: [Object]
[0-0]     },
[0-0]     contentWith: { score: 1, notApplicable: true },
[0-0]     viewport: { score: 0, explanation: [Object] },
[0-0]     appleTouchIcon: { score: 0, warnings: [] },
[0-0]     maskableIcon: { score: 0, explanation: 'No manifest was fetched' }
[0-0]   }
[0-0] }

[0-0] Error in "36: Then I receive Lighthouse Performance Metrics"
TypeError: browser.getMetrics is not a function`

as you can see i've the result from checkPWA , getMetrics is not recognized . I don't use mocha but cucumber, the versions are the latest :

 @wdio/cli@9.12.4
├── @wdio/cucumber-framework@9.12.3
├── @wdio/dot-reporter@9.12.3
├── @wdio/globals@9.12.4
├── @wdio/junit-reporter@9.12.3
├── @wdio/lighthouse-service@9.12.4
├── @wdio/local-runner@9.12.4
├── @wdio/reporter@9.12.3
├── @wdio/spec-reporter@9.12.3
├── @wdio/types@9.12.3
webdriverio@9.12.4

hope this can help and thank you for yours awesome jobs as usual.

**Comment by christian-bromann** [comment]
I will be honest, I probably won't have time to look into this. I recommend doing some debugging in the service directly, e.g. by adding some `console.log` directly in the `node_modules/@wdio/lighthouse-service` package. Any contributions that may resolve this problem is much appreciated.

**Comment by AlfredoMoretta** [comment]
thank you as usual for your support @christian-bromann . i will try as you suggested and if i will find something i will report here
