### ISSUE TITLE
[🐛 Bug]: Devtools service dropping connection to wdio

### ISSUE THREAD

**Issue by JamesTurnerGit** [webdriverio/webdriverio#9925]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7
8 was also tried to see if it was a problem, But as we've not seen v8 work fully with our codebase, the bug was submitted as v7

### Node.js Version

14.16.1

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
wdioConfig.config.capabilities = [{
    maxInstances: 3,
    browserName: 'chrome',
    'goog:chromeOptions': {
        prefs: {
           'download.default_directory': allurePDFVersionDataDir
        },
        args: [
                '--no-sandbox',
                '--headless',
                '--disable-gpu',
                '--disable-dev-smh-usage',
                '--window-size=1600,900'
        ]
    },
}]
```

### What happened?

While using the Devtools service we consistently get errors at the start of the test session

v7 - `@wdio/utils:shim: undefined`
v8 - `@wdio/utils:shim: socket dropped`

and any commands from devtools, including `browser.cdp` are undefined when used in the test suites

### How to reproduce the bug.

Install chrome 111

in wdio.conf.js add this code

```
before: async function(_, __){
     browser.cdp('Network,'Enable')
}
```

and 'devtools` into your services array in the same file

and try to run any test

### Relevant log output

```typescript
[0-0] 2023-03-10T11:13:15.912Z ERROR @wdio/utils:shim: undefined

[0-0] 2023-03-10T11:13:16.490Z ERROR @wdio/utils:shim: TypeError: browser.cdp is not a function

[0-0]     at Object.before (C:\source\SOH\Automation\/wdio.conf.js:416:21)
[0-0]     at C:\source\SOH\Automation\node_modules\@wdio\utils\build\shim.js:88:27
[0-0]     at new Promise (<anonymous>)
[0-0]     at C:\source\SOH\Automation\node_modules\@wdio\utils\build\shim.js:85:47
[0-0]     at Array.map (<anonymous>)
[0-0]     at executeHooksWithArgsShim (C:\source\SOH\Automation\node_modules\@wdio\utils\build\shim.js:85:33)
[0-0]     at wdioHookBeforeFeature (C:\source\SOH\Automation\node_modules\@wdio\cucumber-framework\build\index.js:246:52)
[0-0]     at Object.run (C:\source\SOH\Automation\node_modules\@wdio\cucumber-framework\node_modules\@cucumber\cucumber\src\user_code_runner.ts:37:21)
[0-0]     at Runtime.runTestRunHooks (C:\source\SOH\Automation\node_modules\@wdio\cucumber-framework\node_modules\@cucumber\cucumber\src\runtime\run_test_run_hooks.ts:21:50)
[0-0]     at Runtime.start (C:\source\SOH\Automation\node_modules\@wdio\cucumber-framework\node_modules\@cucumber\cucumber\src\runtime\index.ts:108:16)

[0-0] 2023-03-10T11:13:16.718Z INFO webdriver: COMMAND deleteSession()
```

### further logs
[wdio-0-0-driver.log](https://github.com/webdriverio/webdriverio/files/10956294/wdio-0-0-driver.log)
[wdio-selenium-standalone.log](https://github.com/webdriverio/webdriverio/files/10956296/wdio-selenium-standalone.log)
[wdio.log](https://github.com/webdriverio/webdriverio/files/10956297/wdio.log)
[wdio-0-0.log](https://github.com/webdriverio/webdriverio/files/10956298/wdio-0-0.log)
[wdio-0-0-browser.log](https://github.com/webdriverio/webdriverio/files/10956300/wdio-0-0-browser.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Can you provide all of your wdio logs?

**Comment by JamesTurnerGit** [comment]
more logs attached

**Comment by JamesTurnerGit** [comment]
we found elsewhere that adding 'remote-allow-origins=*' into the chrome capabilities does work around this issue

**Comment by christian-bromann** [comment]
mhm 🤔 these logs don't really say anything, can you provide a reproducible example?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
