### ISSUE TITLE
Init not finishing

### ISSUE THREAD

**Issue by grofit** [webdriverio/webdriverio#997]
I seem to have having a strange issue where in my cucumber 

```
before(function(scenario, callback){ /* stuff */ });
```
 
step where `init().then(callback);` never invokes callback.

I noticed one person mentioned their init always timed out in their environment but they never responded to the issue so has anyone else had anything like this before?

As I basically need to do the browser setup before the actual cucumber tests are run, but its like the init method never finishes (set timeout to 5 seconds).

I have tried using:
- `init(callback);`
- `init().call(callback);`
- `init().then(callback);`

`callback` is never invoked 

if it helps selenium standalone is running, I am on windows 10, using firefox as desired browser, no other errors.

**Comment by christian-bromann** [comment]
Can you provide some Selenium logs?

**Comment by grofit** [comment]
sure here is what happens before everything bombs.

```
15:47:11.345 INFO - Launching a standalone server
Setting system property webdriver.chrome.driver to C:\Program Files\nodejs\node_modules\selenium-standalone\.selenium\chromedriver\2.14-x64-chromedriver
Setting system property webdriver.ie.driver to C:\Program Files\nodejs\node_modules\selenium-standalone\.selenium\iedriver\2.45.0-x64-IEDriverServer.exe
15:47:11.458 INFO - Java: Oracle Corporation 25.45-b02
15:47:11.458 INFO - OS: Windows 8.1 6.3 x86
15:47:11.465 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
15:47:11.548 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
15:47:11.552 INFO - Version Jetty/5.1.x
15:47:11.553 INFO - Started HttpContext[/selenium-server,/selenium-server]
15:47:11.619 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@1223dd8
15:47:11.621 INFO - Started HttpContext[/wd,/wd]
15:47:11.621 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
15:47:11.623 INFO - Started HttpContext[/,/]
15:47:11.627 INFO - Started SocketListener on 0.0.0.0:4444
15:47:11.627 INFO - Started org.openqa.jetty.jetty.Server@133314b
Selenium started
15:47:15.626 INFO - Executing: [new session: Capabilities [{rotatable=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1162fd2, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]])
15:47:15.644 INFO - Creating a new session for Capabilities [{rotatable=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1162fd2, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]
```

**Comment by grofit** [comment]
If I leave stuff for a while it eventually just all times out and then I get the following stuff:

```
15:47:15.644 INFO - Creating a new session for Capabilities [{rotatable=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@1162fd2, locationContextEnabled=true, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=3.4.0, url=http://webdriver.io}}]
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ing file entry whose name is not a valid add-on ID: C:\Users\Me\AppData\Local\Temp\anonymous7384946297184914362webdriver-profile\extensions\webdriver-staging
1452268038661   addons.xpi      INFO    SystemAddonInstallLocation directory is missing
1452268038662   addons.xpi      INFO    Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}
1452268038662   addons.xpi      DEBUG   Skipping unavailable install location app-system-share
1452268038662   addons.xpi      DEBUG   Skipping unavailable install location app-system-local
1452268038662   addons.xpi      WARN    Ignoring missing add-on in C:\Users\Me\AppData\Roaming\Mozilla\Firefox\Profiles\wxcnsd09.default\extensions\quick_searchff@gmail.com
1452268038663   addons.xpi      DEBUG   checkForChanges
1452268038663   addons.xpi      DEBUG   Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Me\\AppData\\Local\\Temp\\anonymous7384946297184914362webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1452268037141,"mt":1452268036979}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"43.0.4","st":1452155954072,"mt":1452155953888}}}
1452268038664   addons.xpi      DEBUG   Existing add-on fxdriver@googlecode.com in app-profile
1452268038664   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1452268038665   addons.xpi      DEBUG   Existing add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1452268038665   addons.xpi      DEBUG   getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Me\\AppData\\Local\\Temp\\anonymous7384946297184914362webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1452268037141,"mt":1452268036979}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"43.0.4","st":1452155954072,"mt":1452155953888}}}
1452268038666   addons.xpi      DEBUG   No changes found
1452268038671   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1452268038672   addons.manager  DEBUG   Provider finished startup: XPIProvider
1452268038672   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1452268038672   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1452268038672   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1452268038673   addons.manager  DEBUG   Starting provider: GMPProvider
1452268038676   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1452268038676   addons.manager  DEBUG   Provider finished startup: GMPProvider
1452268038676   addons.manager  DEBUG   Starting provider: PluginProvider
1452268038676   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1452268038676   addons.manager  DEBUG   Provider finished startup: PluginProvider
1452268038677   addons.manager  DEBUG   Completed startup sequence
1452268038739   addons.xpi-utils        DEBUG   Starting async load of XPI database C:\Users\Me\AppData\Local\Temp\anonymous7384946297184914362webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1452268038817   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1452268038817   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1452268038817   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1452268038881   addons.xpi-utils        DEBUG   Async JSON file read took 0 MS
1452268038881   addons.xpi-utils        DEBUG   Finished async read of XPI database, parsing...
1452268038882   addons.xpi-utils        DEBUG   Successfully read XPI database
1452268038936   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1452268038936   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1452268038936   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider

        at org.openqa.selenium.firefox.internal.NewProfiMextensionConnection.start(NewProfiMextensionConnection.java:118)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
15:48:03.913 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Embersoft1', ip: '192.168.157.1', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:175)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:111)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:88)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:109)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:110)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:172)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:163)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:129)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
        at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
        at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
        at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
        at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
        at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
        at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
        at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
        at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
        at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
        at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Embersoft1', ip: '192.168.157.1', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_45'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:214)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
        ... 9 more
Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(C:\Program Files (x86)\Mozilla Firefox\firefox.exe) on port 7055; process output follows:
ing file entry whose name is not a valid add-on ID: C:\Users\Me\AppData\Local\Temp\anonymous7384946297184914362webdriver-profile\extensions\webdriver-staging
1452268038661   addons.xpi      INFO    SystemAddonInstallLocation directory is missing
1452268038662   addons.xpi      INFO    Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}
1452268038662   addons.xpi      DEBUG   Skipping unavailable install location app-system-share
1452268038662   addons.xpi      DEBUG   Skipping unavailable install location app-system-local
1452268038662   addons.xpi      WARN    Ignoring missing add-on in C:\Users\Me\AppData\Roaming\Mozilla\Firefox\Profiles\wxcnsd09.default\extensions\quick_searchff@gmail.com
1452268038663   addons.xpi      DEBUG   checkForChanges
1452268038663   addons.xpi      DEBUG   Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Me\\AppData\\Local\\Temp\\anonymous7384946297184914362webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1452268037141,"mt":1452268036979}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"43.0.4","st":1452155954072,"mt":1452155953888}}}
1452268038664   addons.xpi      DEBUG   Existing add-on fxdriver@googlecode.com in app-profile
1452268038664   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1452268038665   addons.xpi      DEBUG   Existing add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1452268038665   addons.xpi      DEBUG   getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Me\\AppData\\Local\\Temp\\anonymous7384946297184914362webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1452268037141,"mt":1452268036979}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"43.0.4","st":1452155954072,"mt":1452155953888}}}
1452268038666   addons.xpi      DEBUG   No changes found
1452268038671   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1452268038672   addons.manager  DEBUG   Provider finished startup: XPIProvider
1452268038672   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1452268038672   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1452268038672   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1452268038673   addons.manager  DEBUG   Starting provider: GMPProvider
1452268038676   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1452268038676   addons.manager  DEBUG   Provider finished startup: GMPProvider
1452268038676   addons.manager  DEBUG   Starting provider: PluginProvider
1452268038676   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1452268038676   addons.manager  DEBUG   Provider finished startup: PluginProvider
1452268038677   addons.manager  DEBUG   Completed startup sequence
1452268038739   addons.xpi-utils        DEBUG   Starting async load of XPI database C:\Users\Me\AppData\Local\Temp\anonymous7384946297184914362webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1452268038817   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1452268038817   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1452268038817   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1452268038881   addons.xpi-utils        DEBUG   Async JSON file read took 0 MS
1452268038881   addons.xpi-utils        DEBUG   Finished async read of XPI database, parsing...
1452268038882   addons.xpi-utils        DEBUG   Successfully read XPI database
1452268038936   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1452268038936   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1452268038936   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider

Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'Embersoft1', ip: '192.168.157.1', os.name: 'Windows 8.1', os.arch: 'x86', os.version: '6.3', java.version: '1.8.0_45'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.internal.NewProfiMextensionConnection.start(NewProfiMextensionConnection.java:130)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:246)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:114)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:193)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:104)
        ... 14 more
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ing file entry whose name is not a valid add-on ID: C:\Users\Me\AppData\Local\Temp\anonymous7384946297184914362webdriver-profile\extensions\webdriver-staging
1452268038661   addons.xpi      INFO    SystemAddonInstallLocation directory is missing
1452268038662   addons.xpi      INFO    Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}
1452268038662   addons.xpi      DEBUG   Skipping unavailable install location app-system-share
1452268038662   addons.xpi      DEBUG   Skipping unavailable install location app-system-local
1452268038662   addons.xpi      WARN    Ignoring missing add-on in C:\Users\Me\AppData\Roaming\Mozilla\Firefox\Profiles\wxcnsd09.default\extensions\quick_searchff@gmail.com
1452268038663   addons.xpi      DEBUG   checkForChanges
1452268038663   addons.xpi      DEBUG   Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Me\\AppData\\Local\\Temp\\anonymous7384946297184914362webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1452268037141,"mt":1452268036979}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"43.0.4","st":1452155954072,"mt":1452155953888}}}
1452268038664   addons.xpi      DEBUG   Existing add-on fxdriver@googlecode.com in app-profile
1452268038664   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1452268038665   addons.xpi      DEBUG   Existing add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1452268038665   addons.xpi      DEBUG   getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Me\\AppData\\Local\\Temp\\anonymous7384946297184914362webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1452268037141,"mt":1452268036979}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"43.0.4","st":1452155954072,"mt":1452155953888}}}
1452268038666   addons.xpi      DEBUG   No changes found
1452268038671   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1452268038672   addons.manager  DEBUG   Provider finished startup: XPIProvider
1452268038672   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1452268038672   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1452268038672   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1452268038673   addons.manager  DEBUG   Starting provider: GMPProvider
1452268038676   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1452268038676   addons.manager  DEBUG   Provider finished startup: GMPProvider
1452268038676   addons.manager  DEBUG   Starting provider: PluginProvider
1452268038676   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1452268038676   addons.manager  DEBUG   Provider finished startup: PluginProvider
1452268038677   addons.manager  DEBUG   Completed startup sequence
1452268038739   addons.xpi-utils        DEBUG   Starting async load of XPI database C:\Users\Me\AppData\Local\Temp\anonymous7384946297184914362webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1452268038817   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1452268038817   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1452268038817   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1452268038881   addons.xpi-utils        DEBUG   Async JSON file read took 0 MS
1452268038881   addons.xpi-utils        DEBUG   Finished async read of XPI database, parsing...
1452268038882   addons.xpi-utils        DEBUG   Successfully read XPI database
1452268038936   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1452268038936   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1452268038936   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider

        at org.openqa.selenium.firefox.internal.NewProfiMextensionConnection.start(NewProfiMextensionConnection.java:118)
        ... 19 more
15:48:04.219 WARN - Exception: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ing file entry whose name is not a valid add-on ID: C:\Users\Me\AppData\Local\Temp\anonymous7384946297184914362webdriver-profile\extensions\webdriver-staging
1452268038661   addons.xpi      INFO    SystemAddonInstallLocation directory is missing
1452268038662   addons.xpi      INFO    Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to C:\Program Files (x86)\Mozilla Firefox\browser\extensions\{972ce4c6-7e08-4474-a285-3208198ce6fd}
1452268038662   addons.xpi      DEBUG   Skipping unavailable install location app-system-share
1452268038662   addons.xpi      DEBUG   Skipping unavailable install location app-system-local
1452268038662   addons.xpi      WARN    Ignoring missing add-on in C:\Users\Me\AppData\Roaming\Mozilla\Firefox\Profiles\wxcnsd09.default\extensions\quick_searchff@gmail.com
1452268038663   addons.xpi      DEBUG   checkForChanges
1452268038663   addons.xpi      DEBUG   Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Me\\AppData\\Local\\Temp\\anonymous7384946297184914362webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1452268037141,"mt":1452268036979}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"43.0.4","st":1452155954072,"mt":1452155953888}}}
1452268038664   addons.xpi      DEBUG   Existing add-on fxdriver@googlecode.com in app-profile
1452268038664   addons.xpi      DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1452268038665   addons.xpi      DEBUG   Existing add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1452268038665   addons.xpi      DEBUG   getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"C:\\Users\\Me\\AppData\\Local\\Temp\\anonymous7384946297184914362webdriver-profile\\extensions\\fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1452268037141,"mt":1452268036979}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"43.0.4","st":1452155954072,"mt":1452155953888}}}
1452268038666   addons.xpi      DEBUG   No changes found
1452268038671   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1452268038672   addons.manager  DEBUG   Provider finished startup: XPIProvider
1452268038672   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1452268038672   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1452268038672   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1452268038673   addons.manager  DEBUG   Starting provider: GMPProvider
1452268038676   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1452268038676   addons.manager  DEBUG   Provider finished startup: GMPProvider
1452268038676   addons.manager  DEBUG   Starting provider: PluginProvider
1452268038676   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1452268038676   addons.manager  DEBUG   Provider finished startup: PluginProvider
1452268038677   addons.manager  DEBUG   Completed startup sequence
1452268038739   addons.xpi-utils        DEBUG   Starting async load of XPI database C:\Users\Me\AppData\Local\Temp\anonymous7384946297184914362webdriver-profile\extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1452268038817   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1452268038817   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1452268038817   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1452268038881   addons.xpi-utils        DEBUG   Async JSON file read took 0 MS
1452268038881   addons.xpi-utils        DEBUG   Finished async read of XPI database, parsing...
1452268038882   addons.xpi-utils        DEBUG   Successfully read XPI database
1452268038936   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1452268038936   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1452268038936   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
```

**Comment by christian-bromann** [comment]
Seems that your firefox isn't launching. The init command therefor can't complete. I guess a Selenium issue.

**Comment by grofit** [comment]
Firefox does launch, it gets to the normal blue page:

![image](https://cloud.githubusercontent.com/assets/927201/12202095/e5bcca62-b61f-11e5-8f21-498dd3c17fe4.png)

Just doesnt seem to do anything...

**Comment by christian-bromann** [comment]
What Selenium standalone and Firefox version are you using?

**Comment by grofit** [comment]
Firefox is latest version (43.0.4), not sure how to find the standalone selenium version, it has not been updated recently so that is a good idea for me to try to update. The log above says `2.45.0` but I don't know if that is the actual version, as it seems to think I am using windows 8.1 whereas I am on 10...

**Comment by grofit** [comment]
Right with the latest selenium standalone it seems to trigger the init, I still seem to get an error afterwards or it bombs at least but I am leaving office now so will try some more things on monday. Thanks for your help so far.

**Comment by grofit** [comment]
Right so this is no longer an issue, once selenium standalone was updated everything fell into place. It is bombing now because the `url("blah").then(callback);` never seems to be calling the callback, but this is a different issue so I am happy to close this one and diagnose this other one (or go on gitter for help if needed).

Thanks for help.
